= MINA - MOLTEN
:toc:

== MINA

* `Luk 19:16` Then the first came, saying, 'Lord, your *_mina_* has gained ten minas.'
* `Luk 19:18` And the second came, saying, 'Lord, your *_mina_* has gained five minas.'
* `Luk 19:20` And another came, saying, 'Lord, behold, here is your *_mina_*, which I have kept laid up in a handkerchief,
* `Luk 19:24` And he said to those who stood by, 'Take from him the *_mina_* and give it to him who has ten minas.'

_4 verses containing MINA_

== MINAS

* `1Ki 10:17` And he made three hundred shields of beaten gold. Three *_minas_* of gold went to one shield. And the king put them in the House of the Forest of Lebanon.
* `Ezr 2:69` They gave according to their ability to the treasury for the work sixty-one thousand drams of gold, five thousand *_minas_* of silver, and one hundred priests' garments.
* `Neh 7:71` And some of the chief of the fathers gave to the treasury for the work twenty thousand drams of gold and two thousand and two hundred *_minas_* of silver.
* `Neh 7:72` And that which the rest of the people gave was twenty thousand drams of gold, two thousand *_minas_* of silver, and sixty-seven priests' garments.
* `Luk 19:13` And he called his ten servants and delivered to them ten *_minas_*, and said to them, 'Occupy until I come.'
* `Luk 19:16` Then the first came, saying, 'Lord, your mina has gained ten *_minas_*.'
* `Luk 19:18` And the second came, saying, 'Lord, your mina has gained five *_minas_*.'
* `Luk 19:24` And he said to those who stood by, 'Take from him the mina and give it to him who has ten *_minas_*.'
* `Luk 19:25` And they said to him, 'Lord, he has ten *_minas_*.'

_9 verses containing MINAS_

== MIND

* `Gen 23:8` And he spoke with them, saying, "If it is your *_mind_* that I should bury my dead out of my sight, hear me, and entreat for me to Ephron the son of Zohar,
* `Gen 26:35` Who were a grief of *_mind_* to Isaac and Rebekah.
* `Lev 24:12` And they put him in custody so that the *_mind_* of the LORD might be shown to them.
* `Num 16:28` And Moses said, "By this you shall know that the LORD has sent me to do all these works, for I have not done them of my own *_mind_*.
* `Num 24:13` 'If Balak would give me his house full of silver and gold, I could not go beyond the commandment of the LORD to do either good or bad of my own *_mind_*, but what the LORD says, that I will speak'?
* `Deu 18:6` "And if a Levite comes from any of your gates out of all Israel where he dwells, and comes with all the desire of his *_mind_* to the place which the LORD chooses,
* `Deu 28:65` And among these nations you shall find no ease, neither shall the sole of your foot have rest, but the LORD shall give you there a trembling heart, failing of eyes, and sorrow of *_mind_*.
* `Deu 30:1` "And it shall come to pass when all these things have come upon you, the blessing and the curse, which I have set before you, and you call them to *_mind_* among all the nations where the LORD your God has driven you
* `1Sa 2:35` And I will raise up for myself a faithful priest who shall do according to that which is in my heart and in my *_mind_*. And I will build him a sure house, and he shall walk before my Anointed forever.
* `1Sa 9:20` And as for your donkeys that were lost three days ago, do not set your *_mind_* on them, for they are found. And on whom is all the desire of Israel? Is it not on you and on all your father's house?"
* `1Ch 22:7` And David said to Solomon, "My son, as for me, it was in my *_mind_* to build a house to the name of the LORD my God.
* `1Ch 28:9` "And you, Solomon my son, know the God of your father and serve him with a perfect heart and with a willing *_mind_*, for the LORD searches all hearts and understands all the imaginations of the thoughts. If you seek him, he will be found by you, but if you forsake him, he will cast you off forever.
* `Neh 4:6` So we built the wall. And all the wall was joined together to the half of it, for the people had a *_mind_* to work.
* `Job 23:13` But he is in one *_mind_*, and who can turn him? And what his soul desires, even that he does.
* `Job 34:33` Should it be according to your *_mind_*? He will recompense it, whether you refuse or whether you choose, and not I. Therefore, speak what you know.
* `Psa 26:2` Examine me, O LORD, and prove me. Try my *_mind_* and my heart.
* `Psa 31:12` I am forgotten like a dead man out of *_mind_*. I am like a broken vessel.
* `Pro 21:27` The sacrifice of the wicked is an abomination. How much more, when he brings it with a wicked *_mind_*?
* `Pro 29:11` A fool utters all his *_mind_*, but a wise man keeps it in until afterward.
* `Isa 26:3` You will keep him in perfect peace, whose *_mind_* is stayed on you, because he trusts in you.
* `Isa 46:8` Remember this, and show yourselves men. Bring it back to *_mind_*, O transgressors.
* `Isa 65:17` For behold, I create new heavens and a new earth. And the former shall not be remembered, nor will they come into *_mind_*.
* `Jer 3:16` And it shall come to pass when you are multiplied and increased in the land in those days," says the LORD, "that they shall no longer say, 'The ark of the covenant of the LORD,' neither shall it come to *_mind_*, neither shall they remember it, neither shall they visit it, neither shall that be done anymore.
* `Jer 11:20` But, O LORD of hosts, who judges righteously, who tries the *_mind_* and the heart, let me see your vengeance on them, for to you I have revealed my cause.
* `Jer 15:1` Then the LORD said to me, "Even if Moses and Samuel stood before me, yet my *_mind_* could not be toward this people. Cast them out of my sight and let them go forth.
* `Jer 17:10` I, the LORD, search the heart. I try the *_mind_*, even to give every man according to his ways and according to the fruit of his doings.
* `Jer 19:5` They have also built the high places of Baal to burn their sons with fire for burnt-offerings to Baal, which I did not command nor speak it, neither did it come into my *_mind_*.
* `Jer 20:12` But, O LORD of hosts, who tries the righteous and sees the *_mind_* and the heart, let me see your vengeance on them, for I have opened my cause to you.
* `Jer 32:35` And they built the high places of Baal which are in the valley of the son of Hinnom to cause their sons and their daughters to pass through the fire to Molech, which I did not command them, neither did it come into my *_mind_*, that they should do this abomination to cause Judah to sin.
* `Jer 44:21` "The incense that you burned in the cities of Judah and in the streets of Jerusalem—you and your fathers, your kings and your princes, and the people of the land—did the LORD not remember them, and did it not come into his *_mind_*?
* `Jer 51:50` You who have escaped the sword, go away, do not stand still. Remember the LORD afar off and let Jerusalem come into your *_mind_*.
* `Lam 3:21` This I recall to my *_mind_*; therefore, I have hope.
* `Ezk 11:5` And the Spirit of the LORD fell upon me, and said to me, "Speak, 'Thus says the LORD: "Thus you have said, O house of Israel, for I know the things that come into your *_mind_*—every one of them.
* `Ezk 20:32` And that which comes into your *_mind_* shall not be at all, when you say, 'We will be as the heathen, as the families of the countries, to serve wood and stone.'
* `Ezk 23:17` And the Babylonians came to her into the bed of love, and they defiled her with their lewdness. And when she was polluted with them, her *_mind_* was alienated from them.
* `Ezk 23:18` Thus she disclosed her lewd deeds and exposed her nakedness. Then my *_mind_* was alienated from her, as my *_mind_* was alienated from her sister.
* `Ezk 23:22` "Therefore, O Aholibah, thus says the Lord GOD: 'Behold, I will raise up your lovers against you, from whom your *_mind_* is alienated, and I will bring them against you on every side:
* `Ezk 23:28` For thus says the Lord GOD: 'Behold, I will deliver you into the hand of those whom you hate, into the hand of those from whom your *_mind_* is alienated.
* `Ezk 38:10` 'Thus says the Lord GOD: "It shall also come to pass, that at the same time things shall come into your *_mind_*, and you shall think an evil thought.
* `Dan 2:29` As for you, O king, your thoughts came into your *_mind_* upon your bed about what should come to pass hereafter, and he who reveals secrets makes known to you what shall come to pass.
* `Dan 5:20` But when his heart was lifted up and his *_mind_* hardened in pride, he was deposed from his kingly throne, and they took his glory from him.
* `Hab 1:11` Then his *_mind_* shall change and he shall pass over and offend, imputing his power to his god."
* `Mth 22:37` Jesus said to him, "'You shall love the Lord your God with all your heart, with all your soul, and with all your *_mind_*.'
* `Mrk 5:15` And they come to Jesus and see him who was possessed with the demon and had the legion sitting there clothed and in his right *_mind_*, and they were afraid.
* `Mrk 12:30` And you shall love the Lord your God with all your heart, with all your soul, with all your *_mind_*, and with all your strength.' This is the first commandment.
* `Mrk 14:72` And the second time the cock crowed. And Peter called to *_mind_* the word that Jesus said to him: "Before the cock crows twice, you will deny me three times." And when he thought thereon, he wept.
* `Luk 8:35` Then they went out to see what was done, and came to Jesus and found the man out of whom the demons had departed, sitting at the feet of Jesus, clothed and in his right *_mind_*, and they were afraid.
* `Luk 10:27` And answering, he said, "'You shall love the Lord your God with all your heart, with all your soul, with all your strength, and with all your *_mind_*,' and 'your neighbor as yourself.'"
* `Luk 12:29` And do not seek what you shall eat or what you shall drink, neither be of doubtful *_mind_*.
* `Act 17:11` These were more noble than those in Thessalonica in that they received the word with all readiness of *_mind_* and searched the Scriptures daily, whether those things were so.
* `Act 20:19` Serving the Lord with all humility of *_mind_* and with many tears and temptations which befell me by the lying in wait of the Jews,
* `Rom 1:28` And even as they did not like to retain God in their knowledge, God gave them over to a reprobate *_mind_* to do those things which are not fitting,
* `Rom 7:23` But I see another law in my members warring against the law of my *_mind_* and bringing me into captivity to the law of sin which is in my members.
* `Rom 7:25` I thank God through Jesus Christ our Lord. So then, with the *_mind_*, I myself serve the law of God, but with the flesh, the law of sin.
* `Rom 8:5` For those who are according to the flesh *_mind_* the things of the flesh, but those who are according to the Spirit, the things of the Spirit.
* `Rom 8:7` Because the carnal *_mind_* is enmity against God, for it is not subject to the law of God, neither indeed can be.
* `Rom 8:27` And he who searches the hearts knows what the *_mind_* of the Spirit is, because he makes intercession for the saints according to the will of God.
* `Rom 11:34` For "who has known the *_mind_* of the Lord? Or who has been his counselor?"
* `Rom 12:2` And do not be conformed to this world, but be transformed by the renewing of your *_mind_* so that you may prove what is that good, acceptable, and perfect will of God.
* `Rom 12:16` Be of the same *_mind_* toward one another. Do not *_mind_* high things, but condescend to men of low estate. Do not be wise in your own conceits.
* `Rom 14:5` One man esteems one day above another, but another esteems every day alike. Let every man be fully persuaded in his own *_mind_*.
* `Rom 15:6` So that you may with one *_mind_* and one mouth glorify God, even the Father of our Lord Jesus Christ.
* `Rom 15:15` Nevertheless, brothers, I have written the more boldly to you in some sort, as putting you in *_mind_*, because of the grace that is given to me from God,
* `1Co 1:10` Now I implore you, brothers, by the name of our Lord Jesus Christ, that you all speak the same thing and that there be no divisions among you, but that you be perfectly joined together in the same *_mind_* and in the same judgment.
* `1Co 2:16` "For who has known the *_mind_* of the Lord so that he may instruct him?" But we have the *_mind_* of Christ.
* `2Co 7:7` And not by his coming only, but by the consolation with which he was comforted in you when he told us your earnest desire, your mourning, and your fervent *_mind_* toward me, so that I rejoiced the more.
* `2Co 8:12` For if there is first a willing *_mind_*, it is accepted according to what a man has and not according to what he does not have.
* `2Co 9:2` For I know the forwardness of your *_mind_*, for which I boast about you to those of Macedonia that Achaia has been ready since last year. And your zeal has incited very many.
* `2Co 13:11` Finally, brothers, farewell. Be perfect, be of good comfort, be of one *_mind_*, live in peace, and the God of love and peace will be with you.
* `Eph 2:3` Among whom also we all had our manner of life in times past in the lusts of our flesh, fulfilling the desires of the flesh and of the *_mind_* and were by nature the children of wrath, even as others.
* `Eph 4:17` This I say therefore, and testify in the Lord, that you from now on do not walk as other Gentiles walk, in the vanity of their *_mind_*,
* `Eph 4:23` And be renewed in the spirit of your *_mind_*,
* `Phl 1:27` Only let your manner of life be worthy of the gospel of Christ, so that whether I come and see you or else am absent, I may hear of your affairs, that you stand firm in one spirit, with one *_mind_* striving together for the faith of the gospel,
* `Phl 2:2` Fulfill my joy, that you be like-minded, having the same love, being of one accord, of one *_mind_*.
* `Phl 2:3` Let nothing be done through strife or vain glory. But in lowliness of *_mind_*, let each esteem the other better than themselves—
* `Phl 2:5` Let this *_mind_* be in you, which was also in Christ Jesus,
* `Phl 3:16` Nevertheless, to what we have already attained, let us walk by the same rule, let us *_mind_* the same thing.
* `Phl 3:19` Whose end is destruction, whose god is their belly, and whose glory is in their shame, who *_mind_* earthly things.)
* `Phl 4:2` I exhort Euodias and exhort Syntyche that they be of the same *_mind_* in the Lord.
* `Col 1:21` And you, who were formerly alienated and enemies in your *_mind_* by wicked works, yet now he has reconciled
* `Col 2:18` Let no man beguile you of your reward in a voluntary humility and worshiping of angels, intruding into those things which he has not seen, vainly puffed up by his fleshly *_mind_*,
* `Col 3:12` Put on therefore, as the elect of God, holy and beloved, hearts of mercies, kindness, humbleness of *_mind_*, meekness, patience,
* `2Th 2:2` That you not be soon shaken in *_mind_*, or be troubled, neither by spirit, by word, nor by letter as from us, saying that the day of Christ is at hand.
* `2Ti 1:7` For God has not given us the spirit of fear, but of power, of love, and of a sound *_mind_*.
* `2Ti 3:8` Now as Jannes and Jambres withstood Moses, so do these also resist the truth—men corrupted in *_mind_*, reprobate concerning the faith.
* `Tit 1:15` To the pure all things are pure, but to those who are defiled and unbelieving nothing is pure, but even their *_mind_* and conscience is defiled.
* `Tit 3:1` Put them in *_mind_* to be subject to principalities and powers, to obey magistrates, to be ready for every good work,
* `Heb 8:10` 'For this is the covenant that I will make with the house of Israel after those days,' says the Lord. 'I will put my laws into their *_mind_* and write them in their hearts. And I will be to them a God, and they shall be to me a people.
* `1Pe 1:13` Therefore, gird up the loins of your *_mind_*, be sober, and hope to the end for the grace that is to be brought to you at the revelation of Jesus Christ,
* `1Pe 3:8` Finally, all of you be of one *_mind_*, compassionate, loving as brothers, tender-hearted, and courteous,
* `1Pe 4:1` Therefore, since Christ has suffered for us in the flesh, arm yourselves likewise with the same *_mind_*. For he who has suffered in the flesh has ceased from sin,
* `1Pe 5:2` Feed the flock of God which is among you, taking the oversight of it—not by constraint, but willingly; not for filthy lucre, but from a ready *_mind_*;
* `Rev 17:9` And here is the *_mind_* which has wisdom. The seven heads are seven mountains on which the woman sits.
* `Rev 17:13` These have one *_mind_* and shall give their power and strength to the beast.
* `Rev 17:17` For God has put in their hearts to fulfill his will and to come to one *_mind_* and give their kingdom to the beast until the words of God are fulfilled.

_95 verses containing MIND_

== MINDED

* `2Ch 24:4` And it came to pass after this, that Joash was *_minded_* to repair the house of the LORD.
* `Rom 8:6` For to be carnally *_minded_* is death, but to be spiritually *_minded_* is life and peace,
* `Rom 11:20` Right. Because of unbelief they were broken off, and you stand by faith. Do not be high-*_minded_*, but fear.
* `Rom 15:5` Now may the God of patience and consolation grant you to be like-*_minded_* toward one another according to Christ Jesus,
* `2Co 1:17` When I therefore was thus *_minded_*, did I use levity? Or the things that I purpose, do I purpose according to the flesh so that with me there should be, "Yes, yes," and, "No, no"?
* `Gal 5:10` I have confidence in you through the Lord that you will not be otherwise *_minded_*. But he who troubles you shall bear his judgment, whoever he may be.
* `Phl 2:2` Fulfill my joy, that you be like-*_minded_*, having the same love, being of one accord, of one mind.
* `Phl 2:20` For I have no man like-*_minded_* who will naturally care for your state.
* `Phl 3:15` Let us therefore, as many as are perfect, be thus *_minded_*. And if in anything you are otherwise *_minded_*, God will reveal even this to you.
* `1Th 5:14` Now we exhort you, brothers, warn those who are disorderly, comfort the feeble-*_minded_*, support the weak, and be patient toward all men.
* `1Ti 6:17` Charge those who are rich in this world, that they not be high-*_minded_*, nor trust in uncertain riches, but in the living God, who gives us richly all things to enjoy.
* `2Ti 3:4` Traitors, headstrong, high-*_minded_*, lovers of pleasures more than lovers of God,
* `Tit 2:6` Likewise, exhort the young men to be sober-*_minded_*.
* `Jms 4:8` Draw near to God and he will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-*_minded_*.

_14 verses containing MINDED_

== MINDFUL

* `1Ch 16:15` Be *_mindful_* always of his covenant, the word which he commanded to a thousand generations,
* `Neh 9:17` And they refused to obey, neither were they *_mindful_* of your wonders that you performed among them, but hardened their necks, and in their rebellion appointed a captain to return to their bondage. But you are a God ready to pardon, gracious and merciful, slow to anger, and of great kindness, and did not forsake them.
* `Psa 8:4` What is man that you are *_mindful_* of him, and the son of man that you visit him?
* `Psa 111:5` He has given food to those who fear him. He will always be *_mindful_* of his covenant.
* `Psa 115:12` The LORD has been *_mindful_* of us. He will bless us. He will bless the house of Israel. He will bless the house of Aaron.
* `Isa 17:10` Because you have forgotten the God of your salvation and have not been *_mindful_* of the rock of your strength, therefore you shall plant pleasant plants and shall set it with foreign cuttings.
* `2Ti 1:4` Greatly desiring to see you, being *_mindful_* of your tears, so that I may be filled with joy,
* `Heb 2:6` But someone in a certain place testified, saying, "What is man that you are *_mindful_* of him, or the son of man that you visit him?
* `Heb 11:15` And truly, if they had been *_mindful_* of that country from where they came, they might have had opportunity to return.
* `2Pe 3:2` So that you may be *_mindful_* of the words which were spoken before by the holy prophets and of the commandment of us the apostles of the Lord and Savior.

_10 verses containing MINDFUL_

== MINDS

* `Jdg 19:30` And it was so, that all who saw it, said, "There has been no such deed done nor seen from the day that the children of Israel came from the land of Egypt to this day. Consider it, take advice, and speak your *_minds_*."
* `2Sa 17:8` Then Hushai said, "You know your father and his men. They are mighty men and they are chafed in their *_minds_* like a bear robbed of her whelps in the field. And your father is a man of war and will not lodge with the people.
* `Psa 7:9` Oh let the wickedness of the wicked come to an end, but establish the just, for the righteous God tries the hearts and *_minds_*.
* `Ezk 24:25` 'Also, son of man, shall it not be in the day when I take from them their strength, the joy of their glory, the desire of their eyes, and that on which they set their *_minds_*, their sons and their daughters,
* `Ezk 36:5` Therefore, thus says the Lord GOD: "Surely in the fire of my jealousy I have spoken against the remnant of the heathen and against all Edom, who have appointed my land into their possession with the joy of all their heart, with despiteful *_minds_*, to cast it out for a prey."'
* `Act 14:2` But the unbelieving Jews stirred up the Gentiles and made their *_minds_* evil-affected against the brothers.
* `Act 28:6` But they expected that he would have swollen or suddenly fallen down dead. But after they had waited a long time and saw nothing amiss happen to him, they changed their *_minds_* and said that he was a god.
* `2Co 3:14` But their *_minds_* were blinded, for until this day, the same veil remains untaken away in the reading of the old testament—which veil is done away in Christ.
* `2Co 4:4` In whom the god of this world has blinded the *_minds_* of those who do not believe, lest the light of the glorious gospel of Christ, who is the image of God, should shine to them.
* `2Co 11:3` But I fear, lest by any means, as the serpent beguiled Eve through his subtlety, so your *_minds_* should be corrupted from the simplicity that is in Christ.
* `Phl 4:7` And the peace of God, which passes all understanding, will keep your hearts and *_minds_* through Christ Jesus.
* `1Ti 6:5` Perverse disputings of men of corrupt *_minds_* and destitute of the truth, supposing gain to be godliness. Withdraw yourself from such.
* `Heb 10:16` "'This is the covenant that I will make with them after those days,' says the Lord, 'I will put my laws into their hearts, and in their *_minds_* I will write them,
* `Heb 12:3` Consider him who endured such contradiction of sinners against himself, lest you be wearied and faint in your *_minds_*.
* `2Pe 3:1` This, beloved, is the second epistle I now write to you, in both of which I stir up your pure *_minds_* by way of remembrance,
* `Rev 2:23` And I will kill her children with death. And all the churches shall know that I am he who searches the *_minds_* and hearts. And I will give to each of you according to your works.

_16 verses containing MINDS_

== MINE

* `Gen 24:8` And if the woman is not willing to follow you, then you shall be clear from this oath of *_mine_*. Only do not bring my son there again."
* `Gen 24:41` Then you shall be clear from this oath of *_mine_* when you come to my kindred. And if they do not give you one, you shall be clear from my oath.'
* `Gen 31:43` And Laban answered and said to Jacob, "These daughters are my daughters, these children are my children, the flocks are my flocks, and all that you see is *_mine_*. But what can I do this day to these daughters of *_mine_*, or to their children which they have borne?
* `Gen 48:5` And now, your two sons, Ephraim and Manasseh, who were born to you in the land of Egypt, before I came to you into Egypt, are *_mine_*. As Reuben and Simeon, they shall be *_mine_*.
* `Exo 10:1` And the LORD said to Moses, "Go to Pharaoh, for I have hardened his heart and the heart of his servants, so that I might show these signs of *_mine_* before him,
* `Exo 13:2` "Sanctify to me all the first-born. Whatever opens the womb among the children of Israel, both of man and of beast, it is *_mine_*."
* `Exo 19:5` Now therefore, if you will obey my voice indeed and keep my covenant, then you shall be a peculiar treasure to me above all people, for all the earth is *_mine_*.
* `Exo 34:19` "Every first-born is *_mine_*, even every first-born among your livestock, whether ox or sheep, that is male.
* `Lev 20:26` And you shall be holy to me, for I, the LORD, am holy and have severed you from other people so that you should be *_mine_*.
* `Lev 25:23` 'The land shall not be sold forever, for the land is *_mine_*, for you are strangers and sojourners with me.
* `Num 3:12` "And I, behold, I have taken the Levites from among the children of Israel instead of every first-born who opens the womb among the children of Israel. Therefore, the Levites shall be *_mine_*,
* `Num 3:13` Because all the first-born are *_mine_*. For on the day that I smote all the first-born in the land of Egypt, I hallowed for myself all the first-born in Israel, both man and beast. They shall be *_mine_*. I am the LORD."
* `Num 3:45` "Take the Levites instead of all the first-born among the children of Israel, and the livestock of the Levites instead of their livestock, and the Levites shall be *_mine_*. I am the LORD.
* `Num 8:14` "Thus you shall separate the Levites from among the children of Israel, and the Levites shall be *_mine_*.
* `Num 8:17` For all the first born of the children of Israel are *_mine_*, both man and beast. On the day that I smote every first-born in the land of Egypt I sanctified them for myself.
* `Deu 11:18` "Therefore, you shall lay up these words of *_mine_* in your heart and in your soul. You shall bind them for a sign upon your hand, and they shall be as frontlets between your eyes.
* `2Sa 14:30` Therefore, he said to his servants, "See, Joab's field is near *_mine_*, and he has barley there. Go and set it on fire." And Absalom's servants set the field on fire.
* `1Ki 2:15` And he said, "You know that the kingdom was *_mine_*, and that all Israel set their faces on me that I should reign. But the kingdom has turned and become my brother's, for it was his from the LORD.
* `1Ki 3:26` Then the woman whose child the living one was spoke to the king, for her heart yearned upon her son, and she said, "O my lord, give her the living child and in no way slay it." But the other said, "Let it be neither *_mine_* nor yours, but divide it."
* `1Ki 8:59` And let these words of *_mine_* with which I have made supplication before the LORD be near to the LORD our God day and night so that he may maintain the cause of his servant and the cause of his people Israel at all times, as the matter shall require,
* `1Ki 20:3` 'Your silver and gold are *_mine_*, and also your wives and your children, even the best, are *_mine_*.'"
* `2Ki 10:6` Then he wrote a letter the second time to them, saying, "If you are *_mine_* and if you will listen to my voice, take the heads of the men your master's sons and come to me to Jezreel by tomorrow this time." Now the king's sons, being seventy persons, were with the great men of the city who brought them up.
* `Job 41:11` Who has first benefited me that I should repay him? Whatever is under the whole heaven is *_mine_*.
* `Psa 50:10` For every beast of the forest is *_mine_*, and the livestock upon a thousand hills.
* `Psa 50:11` I know all the birds of the mountains. And the wild beasts of the field are *_mine_*.
* `Psa 50:12` If I were hungry, I would not tell you, for the world is *_mine_*, and the fullness thereof.
* `Psa 60:7` Gilead is *_mine_*. And Manasseh is *_mine_*. Ephraim also is the strength of my head. Judah is my lawgiver.
* `Psa 108:8` Gilead is *_mine_*. Manasseh is *_mine_*. Ephraim also is the strength of my head. Judah is my lawgiver.
* `Pro 8:14` Counsel and sound wisdom are *_mine_*. I am understanding. I have strength.
* `Pro 23:15` My son, if your heart is wise, my heart shall rejoice, even *_mine_*.
* `Sos 2:16` [Lady:] My beloved is *_mine_* and I am his. He feeds among the lilies.
* `Sos 6:3` I am my beloved's and my beloved is *_mine_*. He feeds among the lilies.
* `Sos 8:12` My vineyard which is *_mine_* is before me. You, O Solomon, must have a thousand, and those who keep its fruit, two hundred.
* `Isa 43:1` But now thus says the LORD who created you, O Jacob, and he who formed you, O Israel: "Do not fear, for I have redeemed you. I have called you by your name. You are *_mine_*.
* `Jer 44:28` Yet a small number who escape the sword shall return from the land of Egypt into the land of Judah, and all the remnant of Judah who have gone into the land of Egypt to sojourn there shall know whose words shall stand—*_mine_*, or theirs.
* `Ezk 16:8` "Now when I passed by you and looked upon you, behold, your time was the time of love. And I spread my skirt over you and covered your nakedness. I even swore to you and entered into a covenant with you," says the Lord GOD, "and you became *_mine_*.
* `Ezk 18:4` Behold, all souls are *_mine_*. As the soul of the father, so also the soul of the son is *_mine_*. The soul who sins, he shall die.
* `Ezk 23:4` And their names were Aholah the elder, and Aholibah her sister. And they were *_mine_*, and they bore sons and daughters. As for their names: Samaria is Aholah, and Jerusalem is Aholibah.
* `Ezk 23:5` "And Aholah played the harlot when she was *_mine_*, and she doted on her lovers, on the Assyrians her neighbors.
* `Ezk 29:9` And the land of Egypt shall be desolate and waste. And they shall know that I am the LORD. Because he has said, 'The river is *_mine_*, and I have made it,'
* `Ezk 35:10` "Because you have said, 'These two nations and these two countries shall be *_mine_*, and we will possess it,' whereas the LORD was there,
* `Hag 2:8` 'The silver is *_mine_* and the gold is *_mine_*,' says the LORD of hosts.
* `Mal 3:17` "And they shall be *_mine_*," says the LORD of hosts, "even my own peculiar treasure, in the day that I prepare. And I will spare them, as a man spares his own son who serves him."
* `Mth 7:24` "Therefore, whoever hears these sayings of *_mine_* and does them, I will compare him to a wise man who built his house upon a rock.
* `Mth 7:26` And everyone who hears these sayings of *_mine_* and does not do them, shall be compared to a foolish man who built his house upon the sand.
* `Mth 20:21` And he said to her, "What do you wish?" She says to him, "Grant that these two sons of *_mine_* may sit, one on your right hand and the other on your left, in your kingdom."
* `Mth 20:23` And he says to them, "You shall drink indeed of my cup and be baptized with the baptism that I am baptized with, but to sit on my right hand and on my left is not *_mine_* to give, but it shall be given to those for whom it is prepared by my Father."
* `Mth 25:40` And the King will answer and say to them, 'Truly I say to you, since you have done it to one of the least of these brothers of *_mine_*, you have done it to me.'
* `Mrk 10:40` But to sit on my right hand and on my left hand is not *_mine_* to give. It shall be given to them for whom it is prepared."
* `Luk 11:6` For a friend of *_mine_* in his journey has come to me and I have nothing to set before him,'
* `Luk 15:24` For this son of *_mine_* was dead, and is alive again. He was lost, and is found.' And they began to be merry.
* `Luk 19:27` But these enemies of *_mine_* who did not wish that I should reign over them, bring them here and slay them before me.'"
* `Jhn 3:29` He who has the bride is the bridegroom, but the friend of the bridegroom, who stands and hears him, rejoices greatly because of the bridegroom's voice. This joy of *_mine_* therefore is fulfilled.
* `Jhn 7:16` Jesus answered them, and said, "My doctrine is not *_mine_*, but his who sent me.
* `Jhn 14:24` He who does not love me does not keep my sayings. And the word which you hear is not *_mine_*, but that of the Father who sent me.
* `Jhn 16:14` He will glorify me, for he will receive from what is *_mine_* and will declare it to you.
* `Jhn 16:15` All things that the Father has are *_mine_*; therefore, I said that he will take what is *_mine_* and declare it to you.
* `Jhn 17:10` And all *_mine_* are yours, and yours are *_mine_*, and I am glorified in them.
* `Rom 12:19` Dearly beloved, do not avenge yourselves, but rather give place to wrath, for it is written, "Vengeance is *_mine_* and I will repay," says the Lord.
* `Rom 16:13` Salute Rufus, chosen in the Lord, and his mother and *_mine_*.
* `Phl 1:4` Always in every prayer of *_mine_* for you all making request with joy,
* `2Pe 1:14` Knowing that shortly I must put off this tabernacle of *_mine_*, even as our Lord Jesus Christ has shown me.

_62 verses containing MINE_

== MINGLE

* `Isa 5:22` Woe to those who are mighty to drink wine and men of strength to *_mingle_* strong drink,
* `Dan 2:43` And whereas you saw iron mixed with miry clay, they shall *_mingle_* themselves with the descendants of men, but they shall not cleave to one another, even as iron is not mixed with clay.

_2 verses containing MINGLE_

== MINGLED

* `Exo 9:24` So there was hail, and fire *_mingled_* with the hail, very grievous, such as there had been none like it in all the land of Egypt since it became a nation.
* `Exo 29:40` And with one lamb [you shall offer] a tenth-portion of flour *_mingled_* with the fourth part of a hin of beaten oil, and the fourth part of a hin of wine for a drink-offering.
* `Lev 2:4` 'And if you bring an oblation of a food-offering baked in the oven, it shall be unleavened cakes of fine flour *_mingled_* with oil or unleavened wafers anointed with oil.
* `Lev 2:5` And if your oblation is a food-offering baked in a pan, it shall be of fine flour unleavened, *_mingled_* with oil.
* `Lev 7:10` And every food-offering *_mingled_* with oil, and dry, all the sons of Aaron shall have, one as much as another.
* `Lev 7:12` If he offers it for a thanksgiving, then he shall offer with the sacrifice of thanksgiving unleavened cakes *_mingled_* with oil, unleavened wafers anointed with oil, and cakes *_mingled_* with oil of fine flour, fried.
* `Lev 9:4` And also a bull and a ram for peace-offerings, to sacrifice before the LORD, and a food-offering *_mingled_* with oil, for today the LORD will appear to you.'"
* `Lev 14:10` "And on the eighth day he shall take two male lambs without blemish, one ewe-lamb of the first year without blemish, three tenth-parts of fine flour for a food-offering *_mingled_* with oil, and one log of oil.
* `Lev 14:21` "And if he is poor and cannot afford these things, then he shall take one lamb for a trespass-offering to be waved to make an atonement for him, one tenth-part of fine flour *_mingled_* with oil for a food-offering, a log of oil,
* `Lev 19:19` 'You shall keep my statutes. You shall not let your livestock engender with a diverse kind. You shall not sow your field with *_mingled_* seed, neither shall a garment *_mingled_* of linen and woolen come upon you.
* `Lev 23:13` And the food-offering thereof shall be two tenth-parts of fine flour *_mingled_* with oil, an offering made by fire to the LORD for a sweet savor. And the drink-offering thereof shall be a fourth part of a hin of wine.
* `Num 6:15` A basket of unleavened bread, cakes of fine flour *_mingled_* with oil, wafers of unleavened bread anointed with oil, and their food-offering and their drink-offerings.
* `Num 7:13` And his offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them were full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:19` He offered for his offering one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:25` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:31` His offering was one silver charger, of the weight of one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:37` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:43` His offering was one silver charger, of the weight of one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:49` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:55` His offering was one silver charger of the weight of one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:61` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:67` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:73` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 7:79` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour *_mingled_* with oil for a food-offering;
* `Num 8:8` Then let them take a young bull with his food-offering, even fine flour *_mingled_* with oil, and another young bull you shall take for a sin-offering.
* `Num 15:4` Then he who offers his offering to the LORD shall bring a food-offering of a tenth part of flour *_mingled_* with the fourth part of a hin of oil.
* `Num 15:6` Or for a ram, you shall prepare for a food-offering two tenth parts of flour *_mingled_* with the third part of a hin of oil.
* `Num 15:9` You shall bring with a bull a food-offering of three tenth parts of flour *_mingled_* with half a hin of oil.
* `Num 28:5` And a tenth part of an ephah of flour for a food-offering, *_mingled_* with a fourth part of a hin of beaten oil—
* `Num 28:9` 'And on the sabbath-day [you shall offer] two lambs of the first year without spot and two tenth-parts of flour for a food-offering *_mingled_* with oil and its drink-offering.
* `Num 28:12` Three tenth-parts of flour for a food-offering, *_mingled_* with oil, for one bull; two tenth-parts of flour for a food-offering, *_mingled_* with oil, for one ram;
* `Num 28:13` And a single tenth-part of flour *_mingled_* with oil for a food-offering for one lamb, for a burnt-offering of a sweet savor, a sacrifice made by fire to the LORD.
* `Num 28:20` And their food-offering shall be of flour *_mingled_* with oil; three tenth-parts you shall offer for a bull and two tenth-parts for a ram;
* `Num 28:28` And their food-offering of flour *_mingled_* with oil—three tenth-parts to one bull, two tenth-parts to one ram,
* `Num 29:3` And their food-offering shall be of flour *_mingled_* with oil—three tenth-parts for a bull, two tenth-parts for a ram,
* `Num 29:9` And their food-offering shall be of flour *_mingled_* with oil—three tenth-parts to a bull, two tenth-parts to one ram,
* `Num 29:14` And their food-offering shall be of flour *_mingled_* with oil—three tenth-parts to every bull of the thirteen bulls, two tenth-parts to each ram of the two rams,
* `Psa 102:9` For I have eaten ashes like bread and *_mingled_* my drink with weeping
* `Psa 106:35` But were *_mingled_* among the heathen and learned their works.
* `Pro 9:2` She has killed her beasts. She has *_mingled_* her wine. She has also furnished her table.
* `Pro 9:5` "Come, eat my bread, and drink the wine which I have *_mingled_*.
* `Isa 19:14` The LORD has *_mingled_* a perverse spirit in the midst of it. And they have caused Egypt to err in every work of it, as a drunken man staggers in his vomit.
* `Jer 25:20` And all the *_mingled_* people; all the kings of the land of Uz, all the kings of the land of the Philistines, Ashkelon, Azzah, Ekron, the remnant of Ashdod;
* `Jer 25:24` All the kings of Arabia, all the kings of the *_mingled_* people who dwell in the desert;
* `Jer 50:37` A sword is upon their horses, upon their chariots, and upon all the *_mingled_* people who are in the midst of her, and they shall become like women. A sword is upon her treasures, and they shall be robbed.
* `Ezk 30:5` Cush, Libya, Lydia, all the *_mingled_* people, Kub, and the men of the land that is in league shall fall with them by the sword."
* `Mth 27:34` They gave him vinegar to drink, *_mingled_* with gall. And when he had tasted it, he would not drink.
* `Mrk 15:23` And they gave him to drink wine *_mingled_* with myrrh, but he did not receive it.
* `Luk 13:1` There were present at that season some who told him of the Galileans, whose blood Pilate had *_mingled_* with their sacrifices.
* `Rev 8:7` The first angel sounded, and there followed hail and fire *_mingled_* with blood, and they were cast upon the earth. And the third part of trees was burnt up, and all green grass was burnt up.
* `Rev 15:2` And I saw something like a sea of glass *_mingled_* with fire. And those who had gained the victory over the beast, over his image, over his mark, and over the number of his name, stand on the sea of glass, having the harps of God.

_51 verses containing MINGLED_

== MINIAMIN

* `2Ch 31:15` And under him were Eden, *_Miniamin_*, Jeshua, Shemaiah, Amariah, and Shecaniah, in the cities of the priests, in their set office, to give to their brothers by courses, to the great as well as to the small,
* `Neh 12:17` Of Abijah, Zichri; of *_Miniamin_*, of Moadiah, Piltai;
* `Neh 12:41` And the priests, Eliakim, Maaseiah, *_Miniamin_*, Michaiah, Elioenai, Zechariah, and Hananiah, with trumpets;

_3 verses containing MINIAMIN_

== MINISTER

* `Exo 24:13` And Moses rose up with his *_minister_* Joshua, and Moses went up upon the mountain of God.
* `Exo 28:1` "And bring to you Aaron your brother and his sons with him from among the children of Israel so that he may *_minister_* to me in the priest's office, even Aaron and Nadab, Abihu, Eleazar, and Ithamar, Aaron's sons.
* `Exo 28:3` And you shall speak to all who are wise in heart, whom I have filled with the spirit of wisdom, so that they may make Aaron's garments to consecrate him so that he may *_minister_* to me in the priest's office.
* `Exo 28:4` And these are the garments which they shall make: a breast-plate, an ephod, a robe, an embroidered coat, a miter, and a girdle. And they shall make holy garments for Aaron your brother and his sons so that he may *_minister_* to me in the priest's office.
* `Exo 28:35` And it shall be upon Aaron to *_minister_*. And his sound shall be heard when he goes into the holy place before the LORD and when he comes out so that he may not die.
* `Exo 28:41` And you shall put them upon Aaron your brother and on his sons with him and shall anoint them, consecrate them, and sanctify them so that they may *_minister_* to me in the priest's office.
* `Exo 28:43` And they shall be upon Aaron and upon his sons when they enter into the Tabernacle of the Congregation or when they come near to the altar to *_minister_* in the holy place so that they do not bear iniquity and die. It shall be a statute forever to him and to his offspring after him."
* `Exo 29:1` "And this is the thing that you shall do to them to hallow them, to *_minister_* to me in the priest's office. Take one young bull and two rams without blemish,
* `Exo 29:30` And that son, who is priest in his stead, shall put them on for seven days when he comes into the Tabernacle of the Congregation to *_minister_* in the holy place.
* `Exo 29:44` And I will sanctify the Tabernacle of the Congregation and the altar. I will also sanctify both Aaron and his sons to *_minister_* to me in the priest's office.
* `Exo 30:20` When they go into the Tabernacle of the Congregation or when they come near to the altar to *_minister_* to burn an offering made by fire to the LORD, they shall wash with water so that they do not die.
* `Exo 30:30` And you shall anoint Aaron and his sons and consecrate them so that they may *_minister_* to me in the priest's office.
* `Exo 31:10` The clothes of service, the holy garments for Aaron the priest and the garments of his sons to *_minister_* in the priest's office,
* `Exo 35:19` The clothes of service to do service in the holy place—the holy garments for Aaron the priest and the garments for his sons to *_minister_* in the priest's office.'"
* `Exo 39:26` A bell and a pomegranate, a bell and a pomegranate, around the hem of the robe to *_minister_* in, as the LORD commanded Moses.
* `Exo 39:41` And the clothes of service to do service in the holy place, both the holy garments for Aaron the priest and the garments for his sons to *_minister_* in the priest's office.
* `Exo 40:13` And you shall put upon Aaron the holy garments, anoint him, and sanctify him so that he may *_minister_* to me in the priest's office.
* `Exo 40:15` And you shall anoint them as you anointed their father so that they may *_minister_* to me in the priest's office, for their anointing shall surely be an everlasting priesthood throughout their generations."
* `Lev 7:35` This is the portion of the anointing of Aaron and of the anointing of his sons out of the offerings of the LORD made by fire, in the day when he presented them to *_minister_* to the LORD in the priest's office,
* `Lev 16:32` And the priest whom he anoints and whom he consecrates to *_minister_* in the priest's office in his father's stead shall make the atonement and put on the linen clothes, even the holy garments.
* `Num 1:50` But you shall appoint the Levites over the tabernacle of testimony, over all its vessels, and over all things that belong to it. They shall bear the tabernacle and all its vessels, and they shall *_minister_* to it and encamp around the tabernacle.
* `Num 3:3` These are the names of the sons of Aaron, the priests who were anointed, whom he consecrated to *_minister_* in the priest's office.
* `Num 3:6` "Bring the tribe of Levi near and present them before Aaron the priest so that they may *_minister_* to him.
* `Num 3:31` And their charge shall be the ark, the table, the candlestick, the altars, the vessels of the sanctuary with which they *_minister_*, the hanging, and all its service.
* `Num 4:9` And they shall take a cloth of blue and cover the candlestick for the light, its lamps, its tongs, its snuff-dishes, and all its oil vessels, with which they *_minister_* to it.
* `Num 4:12` And they shall take all the instruments of ministry, with which they *_minister_* in the sanctuary, and put them in a cloth of blue, cover them with a covering of badgers' skins, and put them on a bar.
* `Num 4:14` And they shall put upon it all its vessels, with which they *_minister_* there, even the censers, the flesh-hooks, the shovels, and the basins, all the vessels of the altar, and they shall spread upon it a covering of badgers' skins and put in its staffs.
* `Num 8:26` But shall *_minister_* with their brothers in the Tabernacle of the Congregation to keep the charge, and shall do no service. Thus you shall do to the Levites concerning their charge."
* `Num 16:9` Is it a small thing to you that the God of Israel has separated you from the congregation of Israel to bring you near to himself to do the service of the tabernacle of the LORD and to stand before the congregation to *_minister_* to them?
* `Num 18:2` And also your brothers of the tribe of Levi, the tribe of your father, bring with you so that they may be joined to you and *_minister_* to you, but you and your sons with you shall *_minister_* before the tabernacle of witness.
* `Deu 10:8` At that time the LORD separated the tribe of Levi to bear the ark of the covenant of the LORD, to stand before the LORD to *_minister_* to him, and to bless in his name, to this day.
* `Deu 17:12` And the man who will do presumptuously and will not listen to the priest who stands to *_minister_* there before the LORD your God, or to the judge, even that man shall die. And you shall remove the evil from Israel.
* `Deu 18:5` For the LORD your God has chosen him out of all your tribes to stand to *_minister_* in the name of the LORD—him and his sons forever.
* `Deu 18:7` Then he shall *_minister_* in the name of the LORD his God, as all his brothers the Levites do who stand there before the LORD.
* `Deu 21:5` And the priests the sons of Levi shall come near (for the LORD your God has chosen them to *_minister_* to him and to bless in the name of the LORD) and by their word every controversy and every stroke shall be tried.
* `Jsh 1:1` Now after the death of Moses the servant of the LORD, it came to pass, that the LORD spoke to Joshua the son of Nun, Moses's *_minister_*, saying,
* `2Sa 20:26` And Ira the Jairite was also a chief *_minister_* to David.
* `1Ki 8:11` So that the priests could not stand to *_minister_* because of the cloud, for the glory of the LORD had filled the house of the LORD.
* `1Ch 15:2` Then David said, "No one ought to carry the ark of God but the Levites, for the LORD has chosen them to carry the ark of God and to *_minister_* to him forever."
* `1Ch 16:4` And he appointed some of the Levites to *_minister_* before the ark of the LORD to record and to thank and praise the LORD God of Israel:
* `1Ch 16:37` So he left there before the ark of the covenant of the LORD Asaph and his brothers to *_minister_* before the ark continually, as every day's work required,
* `1Ch 23:13` The sons of Amram: Aaron and Moses. And Aaron was separated so that he should sanctify the most holy things—he and his sons forever—to burn incense before the LORD, to *_minister_* to him, and to bless in his name forever.
* `1Ch 26:12` Among these were the divisions of the gatekeepers, even among the chief men, having wards against one another, to *_minister_* in the house of the LORD.
* `2Ch 5:14` So that the priests could not stand to *_minister_* by reason of the cloud, for the glory of the LORD had filled the house of God.
* `2Ch 8:14` And he appointed, according to the order of David his father, the courses of the priests to their service, the Levites to their charges to praise and *_minister_* before the priests as the duty of every day required, and the gatekeepers by their courses at every gate, for thus David the man of God had commanded.
* `2Ch 13:10` But as for us, the LORD is our God and we have not forsaken him. And the priests who *_minister_* to the LORD are the sons of Aaron, and the Levites wait upon their business.
* `2Ch 23:6` But let no one come into the house of the LORD, except the priests and those Levites who *_minister_*. They shall go in, for they are holy, but all the people shall keep the watch of the LORD.
* `2Ch 24:14` And when they had finished it, they brought the rest of the money before the king and Jehoiada, of which were made vessels for the house of the LORD, even vessels to *_minister_* and to offer with, and spoons and vessels of gold and silver. And they offered burnt-offerings in the house of the LORD continually all the days of Jehoiada.
* `2Ch 29:11` My sons, do not be negligent now, for the LORD has chosen you to stand before him, to serve him, and that you should *_minister_* to him and burn incense."
* `2Ch 31:2` And Hezekiah appointed the courses of the priests and the Levites after their courses, every man according to his service, the priests and Levites for burnt-offerings and for peace-offerings, to *_minister_*, to give thanks, and to praise in the gates of the tents of the LORD.
* `Neh 10:36` Also the first-born of our sons and of our livestock, as it is written in the law, and the first-born of our herds and of our flocks, to bring to the house of our God to the priests who *_minister_* in the house of our God;
* `Neh 10:39` For the children of Israel and the children of Levi shall bring the offering of the grain, the new wine, and the oil to the chambers where the vessels of the sanctuary are, as well as the priests who *_minister_*, the gatekeepers, and the singers. And we will not forsake the house of our God.
* `Psa 9:8` And he shall judge the world in righteousness. He shall *_minister_* judgment to the people in uprightness.
* `Isa 60:7` All the flocks of Kedar shall be gathered to you. The rams of Nebaioth shall *_minister_* to you. They shall come up with acceptance on my altar, and I will glorify the house of my glory.
* `Isa 60:10` And the sons of strangers shall build up your walls, and their kings shall *_minister_* to you, for in my wrath I smote you, but in my favor I have had mercy on you.
* `Jer 33:22` As the host of heaven cannot be numbered, neither the sand of the sea measured, so I will multiply the offspring of David my servant and the Levites who *_minister_* to me.'"
* `Ezk 40:46` And the chamber whose prospect is toward the north is for the priests, the keepers of the charge of the altar. These are the sons of Zadok among the sons of Levi, who come near to the LORD to *_minister_* to him."
* `Ezk 42:14` When the priests enter therein, they shall not go out of the holy place into the outer court, but there they shall lay their garments in which they *_minister_*, for they are holy, and shall put on other garments, and shall approach to those things which are for the people."
* `Ezk 43:19` And you shall give to the priests the Levites who are of the offspring of Zadok, who approach to me to *_minister_* to me,' says the Lord GOD, 'a young bull for a sin-offering.
* `Ezk 44:11` Yet they shall be ministers in my sanctuary, having charge at the gates of the house and ministering to the house. They shall slay the burnt-offering and the sacrifice for the people, and they shall stand before them to *_minister_* to them.
* `Ezk 44:15` "But the priests, the Levites, the sons of Zadok, who kept the charge of my sanctuary when the children of Israel went astray from me, they shall come near to me to *_minister_* to me, and they shall stand before me to offer to me the fat and the blood," says the Lord GOD.
* `Ezk 44:16` "They shall enter into my sanctuary and they shall come near to my table to *_minister_* to me, and they shall keep my charge.
* `Ezk 44:17` And it shall come to pass when they enter in at the gates of the inner court, that they shall be clothed with linen garments. No wool shall come upon them while they *_minister_* in the gates of the inner court and within.
* `Ezk 44:27` And on the day that he goes into the sanctuary to the inner court to *_minister_* in the sanctuary, he shall offer his sin-offering," says the Lord GOD.
* `Ezk 45:4` The holy portion of the land shall be for the priests the ministers of the sanctuary, who shall come near to *_minister_* to the LORD. And it shall be a place for their houses and a holy place for the sanctuary.
* `Mth 20:26` But it shall not be so among you. But whoever wishes to be great among you, let him be your *_minister_*,
* `Mth 20:28` Even as the Son of man did not come to be ministered to, but to *_minister_* and to give his life a ransom for many."
* `Mth 25:44` Then they will also answer him, saying, 'Lord, when did we see you hungry, thirsty, a stranger, naked, sick, or in prison, and did not *_minister_* to you?'
* `Mrk 10:43` But it shall not be so among you. But whoever wishes to be great among you shall be your *_minister_*,
* `Mrk 10:45` For even the Son of man did not come to be ministered to, but to *_minister_* and to give his life as a ransom for many."
* `Luk 4:20` And he closed the book, gave it back to the *_minister_*, and sat down. And the eyes of all those who were in the synagogue were fastened on him.
* `Act 13:5` And when they were at Salamis, they preached the word of God in the synagogues of the Jews. And they also had John for their *_minister_*.
* `Act 24:23` And he commanded a centurion to keep Paul and to let him have liberty, and that he should forbid none of his acquaintances to *_minister_* or come to him.
* `Act 26:16` But rise and stand upon your feet, for I have appeared to you for this purpose: to make you a *_minister_* and a witness both of the things which you have seen and of the things in which I will appear to you,
* `Rom 13:4` For he is the *_minister_* of God to you for good. But if you do that which is evil, be afraid, for he does not bear the sword in vain, for he is the *_minister_* of God, an avenger to execute wrath upon him who does evil.
* `Rom 15:8` Now I say that Jesus Christ was a *_minister_* of the circumcision for the truth of God to confirm the promises made to the fathers,
* `Rom 15:16` That I should be the *_minister_* of Jesus Christ to the Gentiles, ministering the gospel of God, so that the offering up of the Gentiles might be acceptable, being sanctified by the Holy Spirit.
* `Rom 15:25` But now I go to Jerusalem to *_minister_* to the saints.
* `Rom 15:27` It has pleased them truly, and their debtors they are. For if the Gentiles have been made partakers of their spiritual things, their duty is also to *_minister_* to them in carnal things.
* `1Co 9:13` Do you not know that those who *_minister_* about holy things live from the things of the temple, and those who wait at the altar are partakers with the altar?
* `Gal 2:17` But if, while we seek to be justified by Christ, we ourselves are also found sinners, is therefore Christ the *_minister_* of sin? By no means.
* `Eph 3:7` Of which I was made a *_minister_* according to the gift of the grace of God given to me by the effectual working of his power.
* `Eph 4:29` Let no corrupt communication proceed out of your mouth, but that which is good to the use of edifying so that it may *_minister_* grace to the hearers.
* `Eph 6:21` But so that you also may know my affairs and how I am doing, Tychicus, a beloved brother and faithful *_minister_* in the Lord, will make known to you all things,
* `Col 1:7` As you also learned from Epaphras our dear fellow-servant, who is for you a faithful *_minister_* of Christ,
* `Col 1:23` If you continue in the faith grounded and settled and are not moved away from the hope of the gospel which you have heard and which has been preached to every creature which is under heaven, of which I, Paul, am made a *_minister_*.
* `Col 1:25` Of which I am made a *_minister_* according to the dispensation of God which is given to me for you to fulfill the word of God,
* `Col 4:7` All my state Tychicus shall declare to you, who is a beloved brother and a faithful *_minister_* and fellow-servant in the Lord,
* `1Th 3:2` And sent Timothy, our brother and *_minister_* of God and our fellow-laborer in the gospel of Christ, to establish you and to comfort you concerning your faith,
* `1Ti 1:4` Neither give heed to fables and endless genealogies, which *_minister_* questions rather than godly edifying which is in faith.
* `1Ti 4:6` If you put the brothers in remembrance of these things, you will be a good *_minister_* of Jesus Christ, nourished by the words of faith and of good doctrine, to which you have attained.
* `Heb 1:14` Are they not all ministering spirits, sent forth to *_minister_* for those who shall inherit salvation?
* `Heb 6:10` For God is not unrighteous to forget your work and labor of love, which you have shown toward his name, in that you have ministered to the saints and still *_minister_*.
* `Heb 8:2` A *_minister_* of the sanctuary and of the true tabernacle, which the Lord pitched, and not man.
* `1Pe 4:10` As every man has received the gift, even so *_minister_* the same to one another as good stewards of the manifold grace of God.

_95 verses containing MINISTER_

== MINISTERED

* `Num 3:4` And Nadab and Abihu died before the LORD when they offered strange fire before the LORD in the wilderness of Sinai, and they had no children. And Eleazar and Ithamar *_ministered_* in the priest's office in the sight of Aaron their father.
* `Deu 10:6` "And the children of Israel took their journey from Beeroth of the children of Jakan to Mosira. Aaron died there, and he was buried there. And Eleazar his son *_ministered_* in the priest's office in his stead.
* `1Sa 2:11` And Elkanah went to his house in Ramah. And the child *_ministered_* to the LORD before Eli the priest.
* `1Sa 2:18` But Samuel *_ministered_* before the LORD, being a child, girded with a linen ephod.
* `1Sa 3:1` And the child Samuel *_ministered_* to the LORD before Eli. And the word of the LORD was precious in those days. There was no open vision.
* `2Sa 13:17` Then he called his servant who *_ministered_* to him and said, "Now put this woman out from me and bolt the door after her."
* `1Ki 1:4` And the young woman was very fair, and she cherished the king and *_ministered_* to him, but the king did not know her.
* `1Ki 1:15` And Bath-sheba went to the king into the chamber. And the king was very old, and Abishag the Shunamite *_ministered_* to the king.
* `1Ki 19:21` And he returned from following him, took a yoke of oxen, slew them, boiled their flesh with the instruments of the oxen, and gave to the people, and they ate. Then he arose, went after Elijah, and *_ministered_* to him.
* `2Ki 25:14` And the pots, the shovels, the snuffers, the spoons, and all the vessels of brass with which they *_ministered_*, they took away.
* `1Ch 6:32` And they *_ministered_* before the dwelling-place of the Tabernacle of the Congregation with singing until Solomon had built the house of the LORD in Jerusalem, and then they waited on their office according to their order.
* `1Ch 28:1` And David assembled all the princes of Israel, the princes of the tribes, the captains of the companies that *_ministered_* to the king by course, the captains over the thousands, captains over the hundreds, and the stewards over all the substance and possession of the king and of his sons, with the officers, with the mighty men, and with all the valiant men at Jerusalem.
* `2Ch 22:8` And it came to pass, that when Jehu was executing judgment upon the house of Ahab and found the princes of Judah and the sons of the brothers of Ahaziah, who *_ministered_* to Ahaziah, he slew them.
* `Est 2:2` Then the king's servants who *_ministered_* to him said, "Let there be fair young virgins sought for the king.
* `Est 6:3` And the king said, "What honor and dignity has been done to Mordecai for this?" Then the king's servants who *_ministered_* to him said, "There has nothing been done for him."
* `Jer 52:18` And the cauldrons, the shovels, the snuffers, the bowls, the spoons, and all the vessels of brass with which they *_ministered_*, they took away.
* `Ezk 44:12` Because they *_ministered_* to them before their idols and caused the house of Israel to fall into iniquity, therefore I have lifted up my hand against them," says the Lord GOD, "and they shall bear their iniquity.
* `Ezk 44:19` And when they go forth into the outer court, even into the outer court to the people, they shall take off their garments in which they *_ministered_*, lay them in the holy chambers, and put on other garments so that they do not sanctify the people with their garments.
* `Dan 7:10` A fiery stream issued and came forth from before him. Millions *_ministered_* to him, and ten thousand times ten thousand stood before him. The judgment was set and the books were opened.
* `Mth 4:11` Then the devil leaves him, and behold, angels came and *_ministered_* to him.
* `Mth 8:15` And he touched her hand, and the fever left her. And she arose and *_ministered_* to them.
* `Mth 20:28` Even as the Son of man did not come to be *_ministered_* to, but to minister and to give his life a ransom for many."
* `Mrk 1:13` And he was there in the wilderness forty days tempted by Satan. He was with the wild beasts, and the angels *_ministered_* to him.
* `Mrk 1:31` And he came and took her by the hand and lifted her up. And immediately the fever left her, and she *_ministered_* to them.
* `Mrk 10:45` For even the Son of man did not come to be *_ministered_* to, but to minister and to give his life as a ransom for many."
* `Mrk 15:41` (Who also, when he was in Galilee, followed him and *_ministered_* to him), and many other women who came with him to Jerusalem.
* `Luk 4:39` And he stood over her and rebuked the fever, and it left her. And immediately she arose and *_ministered_* to them.
* `Luk 8:3` Joanna (the wife of Chuza, Herod's steward), Susanna, and many others who *_ministered_* to him from their possessions.
* `Act 13:2` As they *_ministered_* to the Lord and fasted, the Holy Spirit said, "Separate Barnabas and Saul for me for the work to which I have called them."
* `Act 19:22` So he sent into Macedonia two of those who *_ministered_* to him, Timothy and Erastus, but he himself stayed in Asia for a season.
* `Act 20:34` And you yourselves know that these hands have *_ministered_* to my necessities and to those who were with me.
* `2Co 3:3` Because you are manifestly declared to be the epistle of Christ *_ministered_* by us, written not with ink, but with the Spirit of the living God, not on tablets of stone, but on fleshly tablets of the heart.
* `Phl 2:25` Yet I supposed it necessary to send to you Epaphroditus, my brother, companion in labor, and fellow-soldier, but your messenger, and he who *_ministered_* to my needs.
* `2Ti 1:18` May the Lord grant to him that he may find mercy from the Lord in that day. And in all that he *_ministered_* to me at Ephesus, you know very well.
* `Phm 1:13` Whom I wished to have retained with me, so that in your stead he might have *_ministered_* to me in the bonds of the gospel.
* `Heb 6:10` For God is not unrighteous to forget your work and labor of love, which you have shown toward his name, in that you have *_ministered_* to the saints and still minister.
* `1Pe 1:12` To them it was revealed, that not to themselves, but to us they *_ministered_* the things which are now reported to you by those who have preached the gospel to you through the Holy Spirit sent down from heaven—which things the angels desire to look into.
* `2Pe 1:11` For in this way an entrance into the everlasting kingdom of our Lord and Savior Jesus Christ shall be abundantly *_ministered_* to you.

_38 verses containing MINISTERED_

== MINISTERING

* `1Ch 9:28` And some of them had the charge of the *_ministering_* vessels, that they should bring them in and out by number.
* `Ezk 44:11` Yet they shall be ministers in my sanctuary, having charge at the gates of the house and *_ministering_* to the house. They shall slay the burnt-offering and the sacrifice for the people, and they shall stand before them to minister to them.
* `Mth 27:55` And many women were there (beholding at a distance) who followed Jesus from Galilee, *_ministering_* to him,
* `Rom 12:7` Or ministry, let us wait on our *_ministering_*; or he who teaches, on teaching;
* `Rom 15:16` That I should be the minister of Jesus Christ to the Gentiles, *_ministering_* the gospel of God, so that the offering up of the Gentiles might be acceptable, being sanctified by the Holy Spirit.
* `2Co 8:4` Praying us with much entreaty that we would receive the gift and the fellowship of the *_ministering_* to the saints.
* `2Co 9:1` For as concerning the *_ministering_* to the saints, it is superfluous for me to write to you.
* `Heb 1:14` Are they not all *_ministering_* spirits, sent forth to minister for those who shall inherit salvation?
* `Heb 10:11` And every priest stands daily *_ministering_* and often offering the same sacrifices, which can never take away sins.

_9 verses containing MINISTERING_

== MINISTERS

* `2Sa 8:18` Benaiah the son of Jehoiada was over both the Cherethites and the Pelethites, and David's sons were chief *_ministers_*.
* `1Ki 10:5` The provisions of his table, the sitting of his servants, the attendance of his *_ministers_* and their apparel, his cup-bearers, and his ascent by which he went up to the house of the LORD, there was no more spirit in her.
* `2Ch 9:4` The provisions of his table, the sitting of his servants, the attendance of his *_ministers_* and their apparel, his cup-bearers and their apparel, and his ascent by which he went up into the house of the LORD, there was no more spirit in her.
* `Ezr 7:24` Also, we inform you, that concerning any of the priests and Levites, singers, gatekeepers, Nethinims, or *_ministers_* of this house of God, it shall not be lawful to impose toll, tribute, or custom upon them.
* `Ezr 8:17` And I sent them with commandment to Iddo the chief in Casiphia, and I told them what they should say to Iddo and to his brothers the Nethinims in Casiphia, that they should bring to us *_ministers_* for the house of our God.
* `Psa 103:21` Bless the LORD, all you hosts of his, you *_ministers_* of his, who do his pleasure.
* `Psa 104:4` Who makes his angels spirits, his *_ministers_* a flaming fire,
* `Isa 61:6` But you shall be named Priests of the LORD. Men shall call you *_Ministers_* of Our God. You shall eat the riches of the Gentiles, and in their glory you shall boast yourselves.
* `Jer 33:21` Then may my covenant also be broken with David my servant so that he should not have a son to reign upon his throne, and also with the Levites the priests, my *_ministers_*.
* `Ezk 44:11` Yet they shall be *_ministers_* in my sanctuary, having charge at the gates of the house and ministering to the house. They shall slay the burnt-offering and the sacrifice for the people, and they shall stand before them to minister to them.
* `Ezk 45:4` The holy portion of the land shall be for the priests the *_ministers_* of the sanctuary, who shall come near to minister to the LORD. And it shall be a place for their houses and a holy place for the sanctuary.
* `Ezk 45:5` And the twenty-five thousand of length and the ten thousand of breadth shall be for the Levites, the *_ministers_* of the house, as a possession for themselves for twenty chambers.
* `Ezk 46:24` Then he said to me, "These are the places of those who boil, where the *_ministers_* of the house shall boil the sacrifice of the people."
* `Joe 1:9` The food-offering and the drink-offering are cut off from the house of the LORD. The priests, the LORD'S *_ministers_*, mourn.
* `Joe 1:13` Gird yourselves and lament, you priests. Howl, you *_ministers_* of the altar. Come, lie all night in sackcloth, you *_ministers_* of my God, for the food-offering and the drink-offering are withheld from the house of your God.
* `Joe 2:17` Let the priests, the *_ministers_* of the LORD, weep between the porch and the altar, and let them say, "Spare your people, O LORD, and do not give your heritage to reproach so that the heathen should rule over them. Why should they say among the people, 'Where is their God?'"
* `Luk 1:2` Even as they delivered them to us, who, from the beginning, were eye-witnesses and *_ministers_* of the word,
* `Rom 13:6` For because of this you also pay tribute, for they are God's *_ministers_*, attending continually upon this very thing.
* `1Co 3:5` Who then is Paul, and who is Apollos, but *_ministers_* by whom you believed, even as the Lord gave to every man?
* `1Co 4:1` Let a man regard us in this way: as the *_ministers_* of Christ and stewards of the mysteries of God.
* `2Co 3:6` Who also has made us able *_ministers_* of the new testament, not of the letter, but of the Spirit. For the letter kills, but the Spirit gives life.
* `2Co 6:4` But in all things approve ourselves as the *_ministers_* of God, in much patience, in afflictions, in necessities, in distresses,
* `2Co 11:15` Therefore, it is no great thing if his *_ministers_* are also transformed as the *_ministers_* of righteousness, whose end shall be according to their works.
* `2Co 11:23` Are they *_ministers_* of Christ? (I speak as a fool) I am more, with labors more abundant, with stripes above measure, in prisons more frequent, and near death more often.
* `Gal 3:5` He therefore who *_ministers_* to you the Spirit and works miracles among you, does he do this by the works of the law, or by the hearing of faith?
* `Heb 1:7` And of the angels he says, "He makes his angels spirits, and his *_ministers_* a flame of fire."
* `1Pe 4:11` If any man speaks, let him speak as the oracles of God. If any man *_ministers_*, let him do it as of the ability which God gives so that in all things God may be glorified through Jesus Christ, to whom be praise and dominion forever and ever. Amen.

_27 verses containing MINISTERS_

== MINISTRATION

* `Luk 1:23` And it came to pass, that as soon as the days of his *_ministration_* were accomplished, he departed to his own house.
* `Act 6:1` And in those days, when the number of the disciples was multiplied, there arose a murmuring of the Grecians against the Hebrews because their widows were neglected in the daily *_ministration_*.
* `2Co 3:7` But if the *_ministration_* of death written and engraved on stones came with glory so that the children of Israel could not steadfastly behold the face of Moses for the glory of his countenance—which glory was to be done away—
* `2Co 3:8` How shall the *_ministration_* of the Spirit not be even more glorious?
* `2Co 3:9` For if the *_ministration_* of condemnation was glory, much more does the *_ministration_* of righteousness exceed in glory.
* `2Co 9:13` Because of the proof of this *_ministration_*, they glorify God for your professed subjection to the gospel of Christ and for your liberal contribution to them and to all men,

_6 verses containing MINISTRATION_

== MINISTRY

* `Num 4:12` And they shall take all the instruments of *_ministry_*, with which they minister in the sanctuary, and put them in a cloth of blue, cover them with a covering of badgers' skins, and put them on a bar.
* `Num 4:47` From thirty years old and upward even to fifty years old, everyone who came to do the service of the *_ministry_* and the service of the burden in the Tabernacle of the Congregation,
* `2Ch 7:6` And the priests stood, according to their offices, along with the Levites with instruments of music of the LORD, which David the king had made to praise the LORD, saying, "For his mercy endures forever," when David offered praise by their *_ministry_*. And the priests sounded trumpets before them, and all Israel stood.
* `Hos 12:10` I have also spoken by the prophets and I have multiplied visions. I used similitudes by the *_ministry_* of the prophets.
* `Act 1:17` For he was numbered with us and had obtained part of this *_ministry_*."
* `Act 1:25` So that he may take part in this *_ministry_* and apostleship from which Judas by transgression fell in order to go to his own place."
* `Act 6:4` But we will give ourselves continually to prayer and to the *_ministry_* of the word."
* `Act 12:25` And Barnabas and Saul returned from Jerusalem when they had fulfilled their *_ministry_* and took with them John, whose surname was Mark.
* `Act 20:24` But none of these things move me, neither do I count my life dear to myself, so that I may finish my course with joy and the *_ministry_* which I have received from the Lord Jesus to testify the gospel of the grace of God.
* `Act 21:19` And when he had saluted them, he declared particularly what things God had wrought among the Gentiles by his *_ministry_*.
* `Rom 12:7` Or *_ministry_*, let us wait on our ministering; or he who teaches, on teaching;
* `1Co 16:15` I implore you, brothers—you know the house of Stephanas, that it is the first fruits of Achaia and that they have addicted themselves to the *_ministry_* of the saints—
* `2Co 4:1` Therefore, seeing we have this *_ministry_*, as we have received mercy, we do not faint,
* `2Co 5:18` And all things are from God, who has reconciled us to himself by Jesus Christ and has given to us the *_ministry_* of reconciliation,
* `2Co 6:3` We give no offense in anything so that the *_ministry_* is not blamed,
* `Eph 4:12` For the perfecting of the saints, for the work of the *_ministry_*, for the edifying of the body of Christ,
* `Col 4:17` And say to Archippus, "Take heed to the *_ministry_* which you have received in the Lord, that you fulfill it."
* `1Ti 1:12` And I thank Christ Jesus our Lord who has enabled me, because he counted me faithful, putting me into the *_ministry_*.
* `2Ti 4:5` But watch in all things, endure afflictions, do the work of an evangelist, and make full proof of your *_ministry_*.
* `2Ti 4:11` Only Luke is with me. Take Mark and bring him with you, for he is profitable to me for the *_ministry_*.
* `Heb 8:6` But now he has obtained a more excellent *_ministry_*, by as much as he is also the mediator of a better covenant, which was established upon better promises.
* `Heb 9:21` And likewise, he sprinkled both the tabernacle and all the vessels of the *_ministry_* with blood.

_22 verses containing MINISTRY_

== MINNI

* `Jer 51:27` Set up a standard in the land. Blow the trumpet among the nations. Prepare the nations against her. Call together against her the kingdoms of Ararat, *_Minni_*, and Ashchenaz. Appoint a captain against her. Cause the horses to come up as the rough licking-locusts.

_1 verse containing MINNI_

== MINNITH

* `Jdg 11:33` And he smote them from Aroer even as far as *_Minnith_*, even twenty cities, and to the plain of the vineyards, with a very great slaughter. Thus the children of Ammon were subdued before the children of Israel.
* `Ezk 27:17` Judah, and the land of Israel, they were your merchants. They traded in your market in wheat of *_Minnith_*, Pannag, honey, oil, and balm.

_2 verses containing MINNITH_

== MINSTREL

* `2Ki 3:15` But now bring me a *_minstrel_*." And it came to pass, when the *_minstrel_* played, that the hand of the LORD came upon him.

_1 verse containing MINSTREL_

== MINSTRELS

* `Mth 9:23` And when Jesus came into the ruler's house and saw the *_minstrels_* and the people making a noise,

_1 verse containing MINSTRELS_

== MINT

* `Mth 23:23` "Woe to you, scribes and Pharisees! Hypocrites! For you pay tithe of *_mint_*, anise, and cumin, and have omitted the weightier matters of the law: judgment, mercy, and faith. These you ought to have done, and not to leave the others undone.
* `Luk 11:42` "But woe to you, Pharisees! For you tithe *_mint_*, rue, and all manner of herbs, and pass over judgment and the love of God. These you ought to have done, and not to leave the others undone.

_2 verses containing MINT_

== MINUS

* `2Co 11:24` Five times from the Jews I received forty stripes *_minus_* one.

_1 verse containing MINUS_

== MIPHKAD

* `Neh 3:31` After him Malchiah, the goldsmith's son, repaired to the place of the Nethinims and of the merchants, over against the gate *_Miphkad_*, and to the ascent of the corner.

_1 verse containing MIPHKAD_

== MIRA

* `Act 27:5` And when we had sailed over the sea of Cilicia and Pamphylia, we came to *_Mira_*, a city of Lycia.

_1 verse containing MIRA_

== MIRACLE

* `Exo 7:9` "When Pharaoh speaks to you, saying, 'Show a *_miracle_*,' then you shall say to Aaron, 'Take your rod and cast it before Pharaoh,' and it shall become a serpent."
* `Mrk 6:52` For they did not consider the *_miracle_* of the loaves, but their heart was hardened.
* `Mrk 9:39` But Jesus said, "Do not forbid him. For there is no man who does a *_miracle_* in my name who can lightly speak evil of me.
* `Luk 23:8` And when Herod saw Jesus, he was exceedingly glad. For he had been for a long time desirous to see him, because he had heard many things of him and he hoped to see some *_miracle_* done by him.
* `Jhn 4:54` This is again the second *_miracle_* that Jesus performed when he had come from Judea into Galilee.
* `Jhn 6:14` Then those men, when they had seen the *_miracle_* that Jesus performed, said, "This is truly that prophet who should come into the world."
* `Jhn 10:41` And many resorted to him, and said, "John performed no *_miracle_*, but all things that John spoke about this man were true."
* `Jhn 12:18` For this cause the people also met him, for they heard that he had done this *_miracle_*.
* `Act 4:16` Saying, "What shall we do to these men? For that indeed a notable *_miracle_* has been done by them is manifest to all those who dwell in Jerusalem, and we cannot deny it.
* `Act 4:22` For the man was more than forty years old on whom this *_miracle_* of healing was performed.

_10 verses containing MIRACLE_

== MIRACLES

* `Num 14:22` Because all those men who have seen my glory and my *_miracles_* which I did in Egypt and in the wilderness and have tested me now these ten times and have not listened to my voice,
* `Deu 11:3` And his *_miracles_* and his acts, which he did in the midst of Egypt to Pharaoh the king of Egypt and to all his land;
* `Deu 29:3` The great trials which your eyes have seen, the signs, and those great *_miracles_*—
* `Jdg 6:13` And Gideon said to him, "O my Lord, if the LORD is with us, why then has all this befallen us? And where are all his *_miracles_* which our fathers told us about, saying, 'Did the LORD not bring us up from Egypt?' But now the LORD has forsaken us and delivered us into the hands of the Midianites."
* `Jhn 2:11` This beginning of *_miracles_* Jesus performed in Cana of Galilee and manifested his glory, and his disciples believed in him.
* `Jhn 2:23` Now when he was in Jerusalem at the passover, on the feast day, many believed in his name when they saw the *_miracles_* which he performed.
* `Jhn 3:2` The same came to Jesus by night and said to him, "Rabbi, we know that you are a teacher come from God, for no man can do these *_miracles_* that you do unless God is with him."
* `Jhn 6:2` And a great multitude followed him because they saw his *_miracles_* which he performed on those who were diseased.
* `Jhn 6:26` Jesus answered them and said, "Truly, truly, I say to you, you seek me, not because you saw the *_miracles_*, but because you ate the loaves and were satisfied.
* `Jhn 7:31` And many of the people believed in him, and said, "When Christ comes, will he do more *_miracles_* than these which this man has done?"
* `Jhn 9:16` Therefore, some of the Pharisees said, "This man is not from God because he does not keep the sabbath." Others said, "How can a man who is a sinner do such *_miracles_*?" And there was a division among them.
* `Jhn 11:47` Then the chief priests and the Pharisees convened a council, and said, "What do we do? For this man performs many *_miracles_*.
* `Jhn 12:37` But though he had done so many *_miracles_* before them, yet they did not believe in him,
* `Act 2:22` "Men of Israel, hear these words. Jesus of Nazareth, a man approved by God among you by *_miracles_*, wonders, and signs, which God did by him in the midst of you, as you yourselves also know,
* `Act 6:8` And Stephen, full of faith and power, performed great wonders and *_miracles_* among the people.
* `Act 8:6` And the people with one accord gave heed to those things which Philip spoke, hearing and seeing the *_miracles_* which he performed.
* `Act 8:13` Then Simon himself believed also. And when he was baptized, he continued with Philip and wondered, beholding the *_miracles_* and signs which were done.
* `Act 15:12` Then all the multitude kept silence and gave audience to Barnabas and Paul, declaring what *_miracles_* and wonders God had wrought by them among the Gentiles.
* `Act 19:11` And God wrought special *_miracles_* by the hands of Paul,
* `1Co 12:10` To another, the working of *_miracles_*; to another, prophecy; to another, discerning of spirits; to another, diverse kinds of languages; to another, the interpretation of languages.
* `1Co 12:28` And God has set some in the church: first apostles, second prophets, third teachers, next *_miracles_*, then gifts of healings, helps, governments, and diversities of languages.
* `1Co 12:29` Are all apostles? Are all prophets? Are all teachers? Are all workers of *_miracles_*?
* `Gal 3:5` He therefore who ministers to you the Spirit and works *_miracles_* among you, does he do this by the works of the law, or by the hearing of faith?
* `Heb 2:4` God also bearing them testimony, both with signs and wonders, and with diverse *_miracles_* and gifts of the Holy Spirit, according to his own will.
* `Rev 13:14` He deceives those who dwell on the earth by the means of those *_miracles_* which he had power to do in the sight of the beast, saying to those who dwell on the earth that they should make an image to the beast which was wounded by the sword and lived.
* `Rev 16:14` For they are the spirits of demons that work *_miracles_*, which go forth to the kings of the earth and of the whole world to gather them to the battle of that great day of God Almighty.
* `Rev 19:20` And the beast was taken, and with him the false prophet who wrought *_miracles_* before him, with which he deceived those who had received the mark of the beast and those who worshiped his image. These were both cast alive into a lake of fire burning with brimstone.

_27 verses containing MIRACLES_

== MIRE

* `2Sa 22:43` Then I beat them as small as the dust of the earth. I stamped them as the *_mire_* of the street and spread them abroad.
* `Job 8:11` Can the rush grow without *_mire_*? Can the reed grow without water?
* `Job 30:19` He has cast me into the *_mire_*, and I have become like dust and ashes.
* `Job 40:21` He lies under the shady trees, in the covert of the reed and *_mire_*.
* `Job 41:30` Sharp stones are under him. He spreads sharp pointed things upon the *_mire_*.
* `Psa 69:2` I sink in deep *_mire_* where there is no standing. I have come into deep waters where the floods overflow me.
* `Psa 69:14` Deliver me out of the *_mire_* and do not let me sink. Let me be delivered from those who hate me and out of the deep waters.
* `Isa 10:6` I will send him against a hypocritical nation, and against the people of my wrath I will give him a charge, to take the loot, to take the plunder, and to tread them down like the *_mire_* of the streets.
* `Isa 57:20` But the wicked are like the troubled sea when it cannot rest, whose waters cast up *_mire_* and dirt.
* `Jer 38:6` Then they took Jeremiah and cast him into the dungeon of Malchiah the son of Hammelech that was in the court of the prison. And they let Jeremiah down with cords. And in the dungeon there was no water, but *_mire_*. So Jeremiah sunk in the *_mire_*.
* `Jer 38:22` 'And behold, all the women who are left in the king of Judah's house shall be brought forth to the king of Babylon's princes, and those women shall say, "Your friends have enticed you and have prevailed against you. Your feet are sunk in the *_mire_*, and they have turned away from you."
* `Mic 7:10` Then she who is my enemy shall see it, and shame shall cover her who said to me, "Where is the LORD your God?" My eyes shall behold her. Now she shall be trodden down as the *_mire_* of the streets.
* `Zch 9:3` And Tyre built herself a stronghold and amassed silver as the dust and fine gold as the *_mire_* of the streets.
* `Zch 10:5` And they shall be as mighty men who tread down their enemies in the *_mire_* of the streets in the battle. And they shall fight because the LORD is with them. And the riders on horses shall be confounded.
* `2Pe 2:22` But it has happened to them according to the true proverb, "The dog has turned to his own vomit again," and, "The sow that was washed to her wallowing in the *_mire_*."

_15 verses containing MIRE_

== MIRIAM

* `Exo 15:20` And *_Miriam_* the prophetess, the sister of Aaron, took a tambourine in her hand, and all the women went out after her with tambourines and with dances.
* `Exo 15:21` And *_Miriam_* answered them, "Sing to the LORD, for he has triumphed gloriously. The horse and his rider he has thrown into the sea."
* `Num 12:1` And *_Miriam_* and Aaron spoke against Moses because of the Cushite woman whom he had married, for he had married a Cushite woman.
* `Num 12:4` And the LORD spoke suddenly to Moses, to Aaron, and to *_Miriam_*, "Come out, you three, to the Tabernacle of the Congregation." And the three of them came out.
* `Num 12:5` And the LORD came down in the pillar of the cloud and stood in the door of the tabernacle and called Aaron and *_Miriam_*, and they both came forth.
* `Num 12:10` And the cloud departed from off the tabernacle, and behold, *_Miriam_* became leprous, white as snow. And Aaron looked upon *_Miriam_*, and behold, she was leprous.
* `Num 12:15` And *_Miriam_* was shut out from the camp seven days. And the people did not journey until *_Miriam_* was brought in again.
* `Num 20:1` Then the children of Israel came, even the whole congregation, into the desert of Zin in the first month, and the people stayed in Kadesh. And *_Miriam_* died there and was buried there.
* `Num 26:59` And the name of Amram's wife was Jochebed, the daughter of Levi, whom her mother bore to Levi in Egypt. And to Amram she bore Aaron, Moses, and *_Miriam_* their sister.
* `Deu 24:9` Remember what the LORD your God did to *_Miriam_* on the way after you came forth from Egypt.
* `1Ch 4:17` And the sons of Ezra were Jethur, Mered, Epher, and Jalon. Mered took a wife and she bore *_Miriam_*, Shammai, and Ishbah the father of Eshtemoa.
* `1Ch 6:3` And the children of Amram: Aaron, Moses, and *_Miriam_*. The sons also of Aaron: Nadab, Abihu, Eleazar, and Ithamar.
* `Mic 6:4` For I brought you out of the land of Egypt and redeemed you from the house of servants, and I sent before you Moses, Aaron, and *_Miriam_*.

_13 verses containing MIRIAM_

== MIRMA

* `1Ch 8:10` Jeuz, Shachia, and *_Mirma_*. These were his sons, heads of the fathers.

_1 verse containing MIRMA_

== MIRROR

* `Job 37:18` Have you with him spread out the sky, which is as strong as a cast metal *_mirror_*?
* `1Co 13:12` For now we see through a *_mirror_* dimly, but then face to face. Now I know in part, but then I shall know even as I am also known.
* `2Co 3:18` But we all, with open face beholding as in a *_mirror_* the glory of the Lord, are changed into the same image from glory to glory, even as by the Spirit of the Lord.
* `Jms 1:23` For if any is a hearer of the word and not a doer, he is like a man beholding his natural face in a *_mirror_*.

_4 verses containing MIRROR_

== MIRRORS

* `Exo 38:8` And he made the basin of brass and its foot of brass from the *_mirrors_* of the women assembling, who assembled at the door of the Tabernacle of the Congregation.
* `Isa 3:23` The *_mirrors_*, the fine linen, the hoods, and the veils.

_2 verses containing MIRRORS_

== MIRTH

* `Gen 31:27` Why did you flee away secretly and steal away from me and not tell me? I would have sent you away with *_mirth_*, with songs, with tambourine, and with harp.
* `Neh 8:12` And all the people went their way to eat, to drink, to send portions, and to make great *_mirth_*, because they had understood the words that were declared to them.
* `Psa 137:3` For there those who carried us away captive required of us a song, and those who wasted us required of us *_mirth_*, saying, "Sing us one of the songs of Zion."
* `Pro 14:13` Even in laughter the heart is sorrowful, and the end of that *_mirth_* is heaviness.
* `Ecc 2:1` I said in my heart, "Come now, I will prove you with *_mirth_*; therefore, enjoy pleasure," and behold, this also is vanity.
* `Ecc 2:2` I said of laughter, "It is mad," and of *_mirth_*, "What does it do?"
* `Ecc 7:4` The heart of the wise is in the house of mourning, but the heart of fools is in the house of *_mirth_*.
* `Ecc 8:15` Then I commended *_mirth_*, because a man has no better thing under the sun than to eat, to drink, and to be merry, for that shall abide with him in his labor all the days of his life which God gives him under the sun.
* `Isa 24:8` The *_mirth_* of tambourines ceases. The noise of those who rejoice ends. The joy of the harp ceases.
* `Isa 24:11` There is a crying for wine in the streets. All joy is darkened, the *_mirth_* of the land is gone.
* `Jer 7:34` Then I will cause to cease from the cities of Judah and from the streets of Jerusalem the voice of *_mirth_*, the voice of gladness, the voice of the bridegroom, and the voice of the bride, for the land shall be desolate."
* `Jer 16:9` For thus says the LORD of hosts, the God of Israel: "Behold, I will cause to cease out of this place in your eyes and in your days the voice of *_mirth_*, the voice of gladness, the voice of the bridegroom, and the voice of the bride.
* `Jer 25:10` Moreover, I will take from them the voice of *_mirth_*, the voice of gladness, the voice of the bridegroom, the voice of the bride, the sound of the millstones, and the light of the candle.
* `Ezk 21:10` It is sharpened to make a grievous slaughter. It is furbished so that it may glitter.' Should we then make *_mirth_*? The rod of my son despises every tree.
* `Hos 2:11` I will also cause to cease all her *_mirth_*, her feast days, her new moons, her sabbaths, and all her solemn feasts.

_15 verses containing MIRTH_

== MIRY

* `Psa 40:2` He brought me up also out of a horrible pit, out of the *_miry_* clay, and set my feet upon a rock and established my goings.
* `Ezk 47:11` But its *_miry_* places and its marshes shall not be healed. They shall be given to salt.
* `Dan 2:41` And whereas you saw the feet and toes, part of potter's clay and part of iron, the kingdom shall be divided, but there shall be in it some of the strength of the iron, because you saw the iron mixed with the *_miry_* clay.
* `Dan 2:43` And whereas you saw iron mixed with *_miry_* clay, they shall mingle themselves with the descendants of men, but they shall not cleave to one another, even as iron is not mixed with clay.

_4 verses containing MIRY_

== MISCARRIED

* `Gen 31:38` These twenty years I have been with you. Your ewes and your female goats have not *_miscarried_* their young, and the rams of your flock I have not eaten.

_1 verse containing MISCARRIED_

== MISCARRY

* `Exo 23:26` None shall *_miscarry_* their young nor be barren in your land. I will complete the number of your days.
* `Job 21:10` Their bull engenders and does not fail. Their cow brings forth and does not *_miscarry_* her calf.

_2 verses containing MISCARRY_

== MISCARRYING

* `Hos 9:14` Give them, O LORD—what will you give? Give them a *_miscarrying_* womb and dry breasts.

_1 verse containing MISCARRYING_

== MISCHIEF

* `Gen 42:4` But Benjamin, Joseph's brother, Jacob did not send with his brothers, for he said, "Lest perhaps *_mischief_* befalls him."
* `Gen 42:38` And he said, "My son shall not go down with you, for his brother is dead and he is left alone. If *_mischief_* befalls him along the way in which you go, then you will bring down my gray hairs with sorrow to the grave."
* `Gen 44:29` And if you take this one also from me and *_mischief_* befalls him, you will bring down my gray hairs with sorrow to the grave.'
* `Exo 21:22` "If men contend and hurt a woman with child so that her fruit departs from her, and yet no *_mischief_* follows, he shall surely be punished according as the woman's husband will lay upon him. And he shall pay as the judges determine.
* `Exo 21:23` And if any *_mischief_* follows, then you shall give life for life,
* `Exo 32:22` And Aaron said, "Do not let the anger of my lord wax hot. You know the people that they are set on *_mischief_*.
* `1Sa 23:9` And David knew that Saul secretly plotted *_mischief_* against him. And he said to Abiathar the priest, "Bring the ephod here."
* `2Sa 16:8` The LORD has returned upon you all the blood of the house of Saul, in whose stead you have reigned. And the LORD has delivered the kingdom into the hand of Absalom your son. And behold, you are taken in your *_mischief_* because you are a bloody man."
* `1Ki 11:25` And he was an adversary to Israel all the days of Solomon, besides the *_mischief_* that Hadad did. And he abhorred Israel and reigned over Syria.
* `1Ki 20:7` Then the king of Israel called all the elders of the land and said, "Mark, I pray you, and see how this man seeks *_mischief_*, for he sent to me for my wives, for my children, for my silver, and for my gold, and I did not deny him."
* `2Ki 7:9` Then they said to one another, "We do not do right. This day is a day of good tidings, and we hold our peace. If we wait until the morning light, some *_mischief_* will come upon us. Now therefore, come, so that we may go and tell the king's household."
* `Neh 6:2` That Sanballat and Geshem sent to me, saying, "Come, let us meet together in one of the villages in the plain of Ono." But they thought to do me *_mischief_*.
* `Est 8:3` And Esther spoke yet again before the king, fell down at his feet, and implored him with tears to put away the *_mischief_* of Haman the Agagite and his plan that he had devised against the Jews.
* `Job 15:35` They conceive *_mischief_* and bring forth vanity, and their belly prepares deceit."
* `Psa 7:14` Behold, he travails with iniquity, has conceived *_mischief_*, and brought forth falsehood.
* `Psa 7:16` His *_mischief_* shall return upon his own head, and his violent dealing shall come down upon the crown of his own head.
* `Psa 10:7` His mouth is full of cursing and deceit and fraud. Under his tongue is *_mischief_* and vanity.
* `Psa 10:14` You have seen it, for you behold *_mischief_* and spite to requite it with your hand. The poor commits himself to you. You are the helper of the fatherless.
* `Psa 26:10` In whose hands is *_mischief_*, and their right hand is full of bribes.
* `Psa 28:3` Do not draw me away with the wicked and with the workers of iniquity, who speak peace to their neighbors, but *_mischief_* is in their hearts.
* `Psa 36:4` He devises *_mischief_* upon his bed. He sets himself in a way that is not good. He does not abhor evil.
* `Psa 52:1` [To the Chief Musician. Maschil. A Psalm of David: when Doeg the Edomite came and told Saul and said to him, "David has come to the house of Ahimelech."] Why do you boast yourself in *_mischief_*, O mighty man? The goodness of God endures continually.
* `Psa 55:10` Day and night they go around it upon its walls. *_Mischief_* and sorrow are also in the midst of it.
* `Psa 62:3` How long will you devise *_mischief_* against a man? All of you shall be slain. You shall be like a bowing wall and like a tottering fence.
* `Psa 94:20` Shall the throne of iniquity have fellowship with you, which frames *_mischief_* by a law?
* `Psa 119:150` They draw near who follow after *_mischief_*. They are far from your law.
* `Psa 140:9` As for the head of those who encompass me, let the *_mischief_* of their own lips cover them.
* `Pro 4:16` For they do not sleep, unless they have done *_mischief_*, and their sleep is taken away, unless they cause some to fall.
* `Pro 6:14` Perverseness is in his heart. He devises *_mischief_* continually. He sows discord.
* `Pro 6:18` A heart that devises wicked imaginations, feet that are swift in running to *_mischief_*,
* `Pro 10:23` To do *_mischief_* is pleasure to a fool, but a man of understanding has wisdom.
* `Pro 11:27` He who diligently seeks good procures favor, but he who seeks *_mischief_*, it shall come to him.
* `Pro 12:21` No evil shall happen to the just, but the wicked shall be filled with *_mischief_*.
* `Pro 13:17` A wicked messenger falls into *_mischief_*, but a faithful ambassador is health.
* `Pro 17:20` He who has a perverse heart finds no good, and he who has a deceitful tongue falls into *_mischief_*.
* `Pro 24:2` For their heart devises destruction and their lips talk of *_mischief_*.
* `Pro 24:16` For a just man falls seven times and rises again, but the wicked shall fall into *_mischief_*.
* `Pro 28:14` Happy is the man who fears always, but he who hardens his heart shall fall into *_mischief_*.
* `Isa 47:11` Therefore, evil shall come upon you. You shall not know from where it rises. And *_mischief_* shall fall upon you. You shall not be able to put it off. And desolation shall come upon you suddenly, which you shall not know.
* `Isa 59:4` No one calls for justice, nor any pleads for truth. They trust in vanity and speak lies. They conceive *_mischief_* and bring forth iniquity.
* `Ezk 7:26` *_Mischief_* shall come upon *_mischief_* and rumor shall be upon rumor. Then they shall seek a vision of the prophet, but the law shall perish from the priest and counsel from the elders.
* `Ezk 11:2` Then he said to me, "Son of man, these are the men who devise *_mischief_* and give wicked counsel in this city,
* `Dan 11:27` And both these kings' hearts shall be set to do *_mischief_*, and they shall speak lies at one table, but it shall not prosper, for yet the end shall be at the time appointed.
* `Hos 7:15` Though I have bound and strengthened their arms, yet they devise *_mischief_* against me.
* `Act 13:10` And said, "O full of all subtlety and all *_mischief_*, you child of the devil, you enemy of all righteousness, will you not cease to pervert the right ways of the Lord?

_45 verses containing MISCHIEF_

== MISCHIEFS

* `Deu 32:23` 'I will heap *_mischiefs_* upon them. I will spend my arrows upon them.
* `Psa 52:2` Your tongue devises *_mischiefs_*, like a sharp razor, working deceitfully.
* `Psa 140:2` Who devise *_mischiefs_* in their heart. Continually they are assembled for war.

_3 verses containing MISCHIEFS_

== MISCHIEVOUS

* `Psa 21:11` For they intended evil against you. They conceived a *_mischievous_* device which they are not able to perform.
* `Psa 38:12` Those who also seek after my life lay snares for me. And those who seek my hurt speak *_mischievous_* things and plot deceits all the day long.
* `Pro 17:4` A wicked doer gives heed to false lips, and a liar gives ear to a *_mischievous_* tongue.
* `Pro 24:8` He who devises to do evil shall be called a *_mischievous_* person.
* `Ecc 10:13` The beginning of the words of his mouth is foolishness, and the end of his talk is *_mischievous_* madness.

_5 verses containing MISCHIEVOUS_

== MISERABLE

* `Job 16:2` "I have heard many such things. You are all *_miserable_* comforters.
* `1Co 15:19` If in this life only we have hope in Christ, we are of all men most *_miserable_*.
* `Rev 3:17` Because you say, 'I am rich and increased with goods and have need of nothing,' and do not know that you are wretched, *_miserable_*, poor, blind, and naked,

_3 verses containing MISERABLE_

== MISERABLY

* `Mth 21:41` They say to him, "He will *_miserably_* destroy those wicked men and will lease out his vineyard to other farmers, who will render him the fruits in their seasons."

_1 verse containing MISERABLY_

== MISERIES

* `Lam 1:7` [ZAYIN] Jerusalem remembers in the days of her affliction and of her *_miseries_* all her pleasant things that she had in the days of old. When her people fell into the hand of the enemy, no one helped her. The adversaries saw her and mocked at her desolations.
* `Jms 5:1` Come now, you rich men, weep and howl for your *_miseries_* that shall come upon you.

_2 verses containing MISERIES_

== MISERY

* `Jdg 10:16` And they put away the strange gods from among them and served the LORD, and his soul was grieved for the *_misery_* of Israel.
* `Job 3:20` Why is light given to him who is in *_misery_*, and life to the bitter in soul,
* `Job 11:16` For you shall forget your *_misery_*, and remember it as waters that pass away.
* `Pro 31:7` Let him drink and forget his poverty and remember his *_misery_* no more.
* `Ecc 8:6` For to every purpose there is time and judgment; therefore, the *_misery_* of man is great upon him.
* `Lam 3:19` [ZAYIN] Remember my affliction and my *_misery_*, the wormwood and the gall.
* `Rom 3:16` Destruction and *_misery_* are in their ways.

_7 verses containing MISERY_

== MISGAB

* `Jer 48:1` [Against Moab.] Thus says the LORD of hosts, the God of Israel: "Woe to Nebo! For it is laid waste. Kiriathaim is confounded and taken. *_Misgab_* is confounded and dismayed.

_1 verse containing MISGAB_

== MISHAEL

* `Exo 6:22` And the sons of Uzziel: *_Mishael_*, Elzaphan, and Zithri.
* `Lev 10:4` And Moses called *_Mishael_* and Elzaphan, the sons of Uzziel the uncle of Aaron, and said to them, "Come near, carry your brothers from before the sanctuary out of the camp."
* `Neh 8:4` And Ezra the scribe stood upon a pulpit of wood, which they had made for this purpose. And beside him stood Mattithiah, Shema, Anaiah, Urijah, Hilkiah, and Maaseiah on his right hand, and on his left hand, Pedaiah, *_Mishael_*, Malchiah, Hashum, Hashbadana, Zechariah, and Meshullam.
* `Dan 1:6` Now among these were some of the children of Judah: Daniel, Hananiah, *_Mishael_*, and Azariah—
* `Dan 1:7` To whom the prince of the eunuchs gave names. For he gave to Daniel the name of Belteshazzar; and to Hananiah, Shadrach; and to *_Mishael_*, Meshach; and to Azariah, Abed-nego.
* `Dan 1:11` Then Daniel said to Melzar, whom the prince of the eunuchs had set over Daniel, Hananiah, *_Mishael_*, and Azariah,
* `Dan 1:19` And the king spoke with them. And among them all there was found no one like Daniel, Hananiah, *_Mishael_*, and Azariah; therefore, they stood before the king.
* `Dan 2:17` Then Daniel went to his house and made the thing known to Hananiah, *_Mishael_*, and Azariah, his companions,

_8 verses containing MISHAEL_

== MISHAL

* `Jsh 21:30` And out of the tribe of Asher, *_Mishal_* with its suburbs, Abdon with its suburbs,

_1 verse containing MISHAL_

== MISHAM

* `1Ch 8:12` The sons of Elpaal: Eber, *_Misham_*, Shamed (who built Ono and Lod, with its town),

_1 verse containing MISHAM_

== MISHEAL

* `Jsh 19:26` Alammelech, Amad, and *_Misheal_*, and reaches to Carmel westward, and to Shihor-libnath,

_1 verse containing MISHEAL_

== MISHMA

* `Gen 25:14` *_Mishma_*, Dumah, Massa,
* `1Ch 1:30` *_Mishma_*, Dumah, Massa, Hadad, Tema,
* `1Ch 4:25` Shallum his son, Mibsam his son, *_Mishma_* his son.
* `1Ch 4:26` And the sons of *_Mishma_*: Hamuel his son, Zacchur his son, and Shimei his son.

_4 verses containing MISHMA_

== MISHMANNAH

* `1Ch 12:10` *_Mishmannah_* the fourth, Jeremiah the fifth,

_1 verse containing MISHMANNAH_

== MISHRAITES

* `1Ch 2:53` And the families of Kirjath-jearim: the Ithrites, the Puhites, the Shumathites, and the *_Mishraites_*. From them came the Zereathites and the Eshtaulites.

_1 verse containing MISHRAITES_

== MISPERETH

* `Neh 7:7` Who came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, *_Mispereth_*, Bigvai, Nehum, and Baanah. The number of the men of the people of Israel was this:

_1 verse containing MISPERETH_

== MISREPHOTH-MAIM

* `Jsh 11:8` And the LORD delivered them into the hand of Israel, who smote them and chased them to great Zidon, to *_Misrephoth-maim_*, and to the valley of Mizpeh eastward. And they smote them until they left to them no one remaining.
* `Jsh 13:6` And the inhabitants of the hill-country from Lebanon to *_Misrephoth-maim_* and all the Sidonians, I will drive them out from before the children of Israel. Only divide it by lot to the Israelites for an inheritance, as I have commanded you.

_2 verses containing MISREPHOTH-MAIM_

== MISS

* `Jdg 20:16` Among all this people there were seven hundred chosen men who were left-handed. Each could sling stones to a hair-breadth and not *_miss_*.
* `1Sa 25:15` But the men were very good to us, and we were not hurt, neither did we *_miss_* anything as long as we were conversant with them when we were in the fields.
* `Job 5:24` And you shall know that your tabernacle will be in peace, and you shall visit your habitation and *_miss_* nothing.

_3 verses containing MISS_

== MISSED

* `1Sa 20:18` Then Jonathan said to David, "Tomorrow is the new-moon, and you will be *_missed_* because your seat will be empty.
* `1Sa 25:21` (Now David had said, "Surely in vain I have kept all that this man has in the wilderness so that nothing was *_missed_* of all that pertained to him, and he has requited me evil for good.

_2 verses containing MISSED_

== MISSES

* `1Sa 20:6` If your father at all *_misses_* me, then say, 'David earnestly asked leave of me so that he might run to Beth-lehem his city, for there is a yearly sacrifice there for all the family.'

_1 verse containing MISSES_

== MISSING

* `1Sa 25:7` And now I have heard that you have shearers. Now your shepherds who were with us, we did not hurt them, neither was there anything *_missing_* to them all the while they were in Carmel.
* `1Ki 20:39` And as the king passed by, he cried to the king, and said, "Your servant went out into the midst of the battle, and behold, a man turned aside and brought a man to me and said, 'Keep this man. If by any means he is *_missing_*, then your life shall be for his life, or else you shall pay a talent of silver.'

_2 verses containing MISSING_

== MIST

* `Gen 2:6` But there went up a *_mist_* from the earth and watered the whole face of the ground.
* `Act 13:11` And now behold, the hand of the Lord is upon you and you shall be blind, not seeing the sun for a season." And immediately there fell on him a *_mist_* and a darkness and he went around seeking someone to lead him by the hand.
* `2Pe 2:17` These are wells without water, clouds that are carried with a tempest, to whom the *_mist_* of darkness is reserved forever.

_3 verses containing MIST_

== MISTRESS

* `Gen 16:4` And he went in to Hagar, and she conceived. And when she saw that she had conceived, her *_mistress_* was despised in her eyes.
* `Gen 16:8` And he said, "Hagar, Sarai's servant, where did you come from? And where will you go?" And she said, "I flee from the face of my *_mistress_* Sarai."
* `Gen 16:9` And the angel of the LORD said to her, "Return to your *_mistress_* and submit yourself under her hands."
* `1Ki 17:17` And it came to pass after these things that the son of the woman, the *_mistress_* of the house, fell sick. And his sickness was so severe that there was no breath left in him.
* `2Ki 5:3` And she said to her *_mistress_*, "I wish that my lord was with the prophet who is in Samaria! For he would recover him of his leprosy."
* `Psa 123:2` Behold, as the eyes of servants look to the hand of their masters, and as the eyes of a woman-servant to the hand of her *_mistress_*, so our eyes wait upon the LORD our God until he has mercy upon us.
* `Pro 30:23` An odious woman when she is married, and a woman-servant who is heir to her *_mistress_*.
* `Isa 24:2` And it shall be, as with the people, so with the priest; as with the servant, so with his master; as with the woman-servant, so with her *_mistress_*; as with the buyer, so with the seller; as with the lender, so with the borrower; as with the taker of interest, so with the giver of interest to him.
* `Isa 47:5` "Sit silent and go into darkness, O daughter of the Chaldeans, for you shall no longer be called, The *_Mistress_* of Kingdoms.
* `Isa 47:7` And you said, 'I shall be a *_mistress_* forever,' so that you did not lay these things to your heart, neither remembered its latter end.
* `Nah 3:4` All because of the multitude of the lewd deeds of the well-favored harlot, the *_mistress_* of witchcrafts, who sells nations through her lewd deeds and families through her witchcrafts.

_11 verses containing MISTRESS_

== MISUSED

* `2Ch 36:16` But they mocked the messengers of God, despised his words, and *_misused_* his prophets until the wrath of the LORD arose against his people until there was no remedy.

_1 verse containing MISUSED_

== MITE

* `Luk 12:59` I tell you, you shall not depart from there until you have paid the very last *_mite_*."

_1 verse containing MITE_

== MITER

* `Exo 28:4` And these are the garments which they shall make: a breast-plate, an ephod, a robe, an embroidered coat, a *_miter_*, and a girdle. And they shall make holy garments for Aaron your brother and his sons so that he may minister to me in the priest's office.
* `Exo 28:37` And you shall put it on a blue lace so that it may be upon the *_miter_*. Upon the front of the *_miter_* it shall be.
* `Exo 28:39` "And you shall embroider the coat of fine linen, you shall make the *_miter_* of fine linen, and you shall make the girdle of needle-work.
* `Exo 29:6` And you shall put the *_miter_* upon his head and put the holy crown upon the *_miter_*.
* `Exo 39:28` And a *_miter_* of fine linen, fancy caps of fine linen, linen breeches of fine twined linen,
* `Exo 39:31` And they tied to it a lace of blue to fasten it on high upon the *_miter_*, as the LORD commanded Moses.
* `Lev 8:9` And he put the *_miter_* upon his head. Also upon the *_miter_*, even upon his front, he put the golden plate, the holy crown, as the LORD commanded Moses.
* `Lev 16:4` He shall put on the holy linen coat and have the linen breeches upon his body, and he shall be girded with the linen girdle, and with the linen *_miter_* he shall be attired. These are holy garments; therefore, he shall wash his flesh in water and put them on in this manner.
* `Zch 3:5` And I said, "Let them set a fair *_miter_* upon his head." So they set a fair *_miter_* upon his head and clothed him with garments. And the angel of the LORD stood by.

_9 verses containing MITER_

== MITES

* `Mrk 12:42` And there came a certain poor widow, and she threw in two *_mites_*, which make a quadrans.
* `Luk 21:2` And he also saw a certain poor widow casting in there two *_mites_*.

_2 verses containing MITES_

== MITHCAH

* `Num 33:28` And they departed from Tarah and encamped in *_Mithcah_*.
* `Num 33:29` And they went from *_Mithcah_* and encamped in Hashmonah.

_2 verses containing MITHCAH_

== MITHNITE

* `1Ch 11:43` Hanan the son of Maachah, and Joshaphat the *_Mithnite_*,

_1 verse containing MITHNITE_

== MITHREDATH

* `Ezr 1:8` And Cyrus king of Persia brought them forth by the hand of *_Mithredath_* the treasurer, and he numbered them to Sheshbazzar, the prince of Judah.
* `Ezr 4:7` And in the days of Artaxerxes, Bishlam, *_Mithredath_*, Tabeel, and the rest of their companions wrote to Artaxerxes king of Persia, and the writing of the letter was written in the Syrian language and interpreted in the Syrian language.

_2 verses containing MITHREDATH_

== MITYLENE

* `Act 20:14` And when he met with us at Assos, we took him in and came to *_Mitylene_*.

_1 verse containing MITYLENE_

== MIXED

* `Exo 12:38` And a *_mixed_* multitude also went up with them, and also flocks and herds, even a very large number of livestock.
* `Num 11:4` And the *_mixed_* multitude who was among them fell to lusting. And the children of Israel also wept again and said, "Who shall give us flesh to eat?
* `Deu 22:11` "You shall not wear a *_mixed_* garment [woven] of wool and linen together.
* `Ezr 9:2` For they have taken some of their daughters for themselves and for their sons so that the holy nation has *_mixed_* with the people of those lands. Even the hand of the princes and rulers has been chief in this trespass."
* `Neh 13:3` Now it came to pass when they had heard the law, that they separated from Israel all the *_mixed_* multitude.
* `Pro 23:30` Those who stay long at the wine, and those who go to seek *_mixed_* wine.
* `Isa 1:22` Your silver has become dross and your wine *_mixed_* with water.
* `Dan 2:41` And whereas you saw the feet and toes, part of potter's clay and part of iron, the kingdom shall be divided, but there shall be in it some of the strength of the iron, because you saw the iron *_mixed_* with the miry clay.
* `Dan 2:43` And whereas you saw iron *_mixed_* with miry clay, they shall mingle themselves with the descendants of men, but they shall not cleave to one another, even as iron is not *_mixed_* with clay.
* `Hos 7:8` Ephraim, he has *_mixed_* himself among the people. Ephraim is a cake not turned.
* `Heb 4:2` For the gospel was preached to us as well as to them. But the word which they heard did not profit them, not being *_mixed_* with faith in those who heard it.

_11 verses containing MIXED_

== MIXTURE

* `Psa 75:8` For in the hand of the LORD there is a cup, and the wine is red. It is full of *_mixture_*, and he pours out of the same. But all the wicked of the earth shall wring out its dregs and drink them.
* `Jhn 19:39` And Nicodemus (who at the first came to Jesus by night) also came and brought a *_mixture_* of myrrh and aloes, about one hundred pounds in weight.
* `Rev 14:10` The same shall drink of the wine of the wrath of God which is poured out without *_mixture_* into the cup of his indignation, and he shall be tormented with fire and brimstone in the presence of the holy angels and in the presence of the Lamb.

_3 verses containing MIXTURE_

== MIZAR

* `Psa 42:6` O my God, my soul is cast down within me; therefore, I will remember you from the land of the Jordan and of the Hermonites, from the hill *_Mizar_*.

_1 verse containing MIZAR_

== MIZPAH

* `Gen 31:49` And *_Mizpah_*, for he said, "May the LORD watch between you and me when we are absent from one another.
* `1Ki 15:22` Then king Asa made a proclamation throughout all Judah. No one was exempted. And they took away the stones of Ramah and its timber, with which Baasha had built it, and king Asa built with them Geba of Benjamin and *_Mizpah_*.
* `2Ki 25:23` And when all the captains of the armies—they and their men—heard that the king of Babylon had made Gedaliah governor, they came to Gedaliah at *_Mizpah_*, even Ishmael the son of Nethaniah, Johanan the son of Careah, Seraiah the son of Tanhumeth the Netophathite, and Jaazaniah the son of a Maachathite—they and their men.
* `2Ki 25:25` But it came to pass in the seventh month, that Ishmael the son of Nethaniah, the son of Elishama, of the royal family, came, and ten men with him, and smote Gedaliah so that he died, along with the Jews and the Chaldeans who were with him at *_Mizpah_*.
* `2Ch 16:6` Then Asa the king took all Judah, and they carried away the stones of Ramah and its timber with which Baasha was building, and he built with it Geba and *_Mizpah_*.
* `Neh 3:7` And next to them Melatiah the Gibeonite and Jadon the Meronothite, the men of Gibeon and of *_Mizpah_*, repaired to the throne of the governor on this side of the river.
* `Neh 3:15` But the gate of the fountain was repaired by Shallun the son of Col-hozeh, the ruler of part of *_Mizpah_*. He built it, covered it, set up its doors, its locks, and its bars, and the wall of the pool of Siloah by the king's garden, and to the stairs that go down from the city of David.
* `Neh 3:19` And next to him Ezer the son of Jeshua, the ruler of *_Mizpah_*, repaired another piece over against the ascent to the armory, at the turning of the wall.
* `Jer 40:6` Then Jeremiah went to Gedaliah the son of Ahikam at *_Mizpah_* and dwelt with him among the people who were left in the land.
* `Jer 40:8` They came to Gedaliah at *_Mizpah_*, even Ishmael the son of Nethaniah, Johanan and Jonathan the sons of Kareah, Seraiah the son of Tanhumeth, the sons of Ephai the Netophathite, and Jezaniah the son of a Maachathite—they and their men.
* `Jer 40:10` As for me, behold, I will dwell at *_Mizpah_* to serve the Chaldeans who will come to us. But you, gather wine, summer fruits, and oil, and put them in your vessels and dwell in your cities that you have taken."
* `Jer 40:12` Even all the Jews returned out of all places where they were driven and came to the land of Judah, to Gedaliah, to *_Mizpah_*, and gathered wine and summer fruits in abundance.
* `Jer 40:13` Moreover, Johanan the son of Kareah and all the captains of the forces who were in the fields came to Gedaliah at *_Mizpah_*,
* `Jer 40:15` Then Johanan the son of Kareah spoke to Gedaliah in *_Mizpah_* secretly, saying, "Let me go, I pray you, and I will slay Ishmael the son of Nethaniah, and no man shall know it. Why should he slay you so that all the Jews who are gathered to you should be scattered and the remnant of Judah perish?"
* `Jer 41:1` Now it came to pass in the seventh month, that Ishmael the son of Nethaniah, the son of Elishama, of the royal family, and the princes of the king, even ten men with him, came to Gedaliah the son of Ahikam at *_Mizpah_*. And there they ate bread together in *_Mizpah_*.
* `Jer 41:3` Ishmael also slew all the Jews who were with him, even with Gedaliah, at *_Mizpah_*, as well as the Chaldean men of war who were found there.
* `Jer 41:6` And Ishmael the son of Nethaniah went forth from *_Mizpah_* to meet them, weeping all along as he went. And it came to pass, as he met them, he said to them, "Come to Gedaliah the son of Ahikam."
* `Jer 41:10` Then Ishmael carried away captive all the remnant of the people who were in *_Mizpah_*, even the king's daughters and all the people who remained in *_Mizpah_*, whom Nebuzar-adan the captain of the guard had committed to Gedaliah the son of Ahikam. And Ishmael the son of Nethaniah carried them away captive and departed to go over to the Ammonites.
* `Jer 41:14` So all the people who Ishmael had carried away captive from *_Mizpah_* turned around and returned and went to Johanan the son of Kareah.
* `Hos 5:1` "Hear this, O priests, and listen, house of Israel, and give ear, O house of the king, for judgment is toward you because you have been a snare on *_Mizpah_* and a net spread upon Tabor.

_20 verses containing MIZPAH_

== MIZPAR

* `Ezr 2:2` Who came with Zerubbabel: Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, *_Mizpar_*, Bigvai, Rehum, and Baanah. The number of the men of the people of Israel:

_1 verse containing MIZPAR_

== MIZPEH

* `Jsh 11:3` And to the Canaanite on the east and on the west, to the Amorite, the Hittite, the Perizzite, the Jebusite in the mountains, and to the Hivite under Hermon in the land of *_Mizpeh_*.
* `Jsh 11:8` And the LORD delivered them into the hand of Israel, who smote them and chased them to great Zidon, to Misrephoth-maim, and to the valley of *_Mizpeh_* eastward. And they smote them until they left to them no one remaining.
* `Jsh 13:26` And from Heshbon to Ramath-*_mizpeh_*, and Betonim; and from Mahanaim to the border of Debir;
* `Jsh 15:38` Dilean, *_Mizpeh_*, Joktheel,
* `Jsh 18:26` *_Mizpeh_*, Chephirah, Mozah,
* `Jdg 10:17` Then the children of Ammon were assembled and encamped in Gilead. And the children of Israel assembled themselves and encamped in *_Mizpeh_*.
* `Jdg 11:11` Then Jephthah went with the elders of Gilead, and the people made him head and captain over them. And Jephthah uttered all his words before the LORD in *_Mizpeh_*.
* `Jdg 11:29` Then the Spirit of the LORD came upon Jephthah, and he passed over Gilead and Manasseh, and passed over *_Mizpeh_* of Gilead, and from *_Mizpeh_* of Gilead he passed over to the children of Ammon.
* `Jdg 11:34` And Jephthah came to *_Mizpeh_* to his house, and behold, his daughter came out to meet him with tambourines and with dances. And she was his only child. Besides her, he had neither son nor daughter.
* `Jdg 20:1` Then all the children of Israel went out, and the congregation was assembled as one man from Dan even to Beer-sheba, along with the land of Gilead, to the LORD in *_Mizpeh_*.
* `Jdg 20:3` (Now the children of Benjamin heard that the children of Israel had gone up to *_Mizpeh_*.) Then the children of Israel said, "Tell us, how did this wickedness happen?"
* `Jdg 21:1` Now the men of Israel had sworn in *_Mizpeh_*, saying, "Not one of us shall give his daughter to Benjamin for a wife."
* `Jdg 21:5` And the children of Israel said, "Who is there among all the tribes of Israel who did not come up with the congregation to the LORD?" For they had made a great oath concerning him who did not come up to the LORD to *_Mizpeh_*, saying, "He shall surely be put to death."
* `Jdg 21:8` And they said, "Who from among the tribes of Israel did not come up to *_Mizpeh_* to the LORD?" And behold, no one came to the camp from Jabesh-gilead to the assembly.
* `1Sa 7:5` And Samuel said, "Gather all Israel to *_Mizpeh_* and I will pray for you to the LORD."
* `1Sa 7:6` And they assembled at *_Mizpeh_* and drew water, poured it out before the LORD, and fasted on that day, and there said, "We have sinned against the LORD." And Samuel judged the children of Israel in *_Mizpeh_*.
* `1Sa 7:7` And when the Philistines heard that the children of Israel were assembled at *_Mizpeh_*, the lords of the Philistines went up against Israel. And when the children of Israel heard it, they were afraid of the Philistines.
* `1Sa 7:11` And the men of Israel went out of *_Mizpeh_*, pursued the Philistines, and smote them until they came under Beth-car.
* `1Sa 7:12` Then Samuel took a stone, set it between *_Mizpeh_* and Shen, and called its name Eben-ezer, saying, "Until now the LORD has helped us."
* `1Sa 7:16` And he went from year to year in circuit to Beth-el, Gilgal, and *_Mizpeh_*, and judged Israel in all those places.
* `1Sa 10:17` And Samuel called the people together to the LORD at *_Mizpeh_*,
* `1Sa 22:3` And David went from there to *_Mizpeh_* of Moab. And he said to the king of Moab, "Let my father and my mother, I pray you, come forth and be with you until I know what God will do for me."
* `Jer 41:16` Then Johanan the son of Kareah and all the captains of the forces who were with him took all the remnant of the people from *_Mizpeh_* whom he had recovered from Ishmael the son of Nethaniah after he had slain Gedaliah the son of Ahikam, even mighty men of war, and the women, the children, and the eunuchs, whom he had brought back from Gibeon.

_23 verses containing MIZPEH_

== MIZRAIM

* `Gen 10:6` And the sons of Ham: Cush, *_Mizraim_*, Phut, and Canaan.
* `Gen 10:13` And *_Mizraim_* begot Ludim, Anamim, Lehabim, Naphtuhim,
* `Gen 50:11` And when the inhabitants of the land, the Canaanites, saw the mourning in the floor of Atad, they said, "This is a grievous mourning for the Egyptians." Therefore, its name was called Abel-*_mizraim_*, which is beyond the Jordan.
* `1Ch 1:8` The sons of Ham: Cush, *_Mizraim_*, Put, and Canaan.
* `1Ch 1:11` And *_Mizraim_* begot Ludim, Anamim, Lehabim, Naphtuhim,

_5 verses containing MIZRAIM_

== MIZZAH

* `Gen 36:13` And these are the sons of Reuel: Nahath, Zerah, Shammah, and *_Mizzah_*. These are the sons of Bashemath, Esau's wife.
* `Gen 36:17` And these are the sons of Reuel, Esau's son: chief Nahath, chief Zerah, chief Shammah, chief *_Mizzah_*. These are the chiefs, descendants of Reuel, in the land of Edom. These are the sons of Bashemath, Esau's wife.
* `1Ch 1:37` The sons of Reuel: Nahath, Zerah, Shammah, and *_Mizzah_*.

_3 verses containing MIZZAH_

== MNASON

* `Act 21:16` Some of the disciples of Caesarea also went with us and brought with them *_Mnason_* of Cyprus, an old disciple, with whom we should lodge.

_1 verse containing MNASON_

== MOAB

* `Gen 19:37` And the first-born bore a son and called his name *_Moab_*. The same is the father of the Moabites to this day.
* `Gen 36:35` And Husham died, and Hadad the son of Bedad (who smote Midian in the field of *_Moab_*) reigned in his stead, and the name of his city was Avith.
* `Exo 15:15` Then the chiefs of Edom shall be amazed. The mighty men of *_Moab_*, trembling shall take hold upon them. All the inhabitants of Canaan shall melt away.
* `Num 21:11` And they journeyed from Oboth and pitched at Ije-abarim in the wilderness which is before *_Moab_*, toward the sunrise.
* `Num 21:13` From there they departed and pitched on the other side of Arnon, which is in the wilderness that comes out of the border of the Amorites, for Arnon is the border of *_Moab_* between *_Moab_* and the Amorites.
* `Num 21:15` And at the stream of the brooks that goes down to the dwelling of Ar, and lies upon the border of *_Moab_*."
* `Num 21:20` And from Bamoth in the valley, which is in the country of *_Moab_*, to the top of Pisgah, which looks toward Jeshimon.
* `Num 21:26` For Heshbon was the city of Sihon the king of the Amorites, who had fought against the former king of *_Moab_* and taken all his land out of his hand, even to Arnon.
* `Num 21:28` For a fire has gone out of Heshbon, a flame from the city of Sihon. It has consumed Ar of *_Moab_* and the lords of the high places of Arnon.
* `Num 21:29` Woe to you, *_Moab_*! You are undone, O people of Chemosh. He has given his sons as fugitives and his daughters into captivity to Sihon king of the Amorites.
* `Num 22:1` And the children of Israel moved forward and pitched in the plains of *_Moab_* on this side of the Jordan by Jericho.
* `Num 22:3` And *_Moab_* was greatly afraid of the people because they were many. And *_Moab_* was distressed because of the children of Israel.
* `Num 22:4` And *_Moab_* said to the elders of Midian, "Now this company shall lick up all that is around us as the ox licks up the grass of the field." And Balak the son of Zippor was king of the Moabites at that time.
* `Num 22:7` And the elders of *_Moab_* and the elders of Midian departed with the rewards of divination in their hand, and they came to Balaam and spoke to him the words of Balak.
* `Num 22:8` And he said to them, "Lodge here this night, and I will bring you word again as the LORD shall speak to me." And the princes of *_Moab_* stayed with Balaam.
* `Num 22:10` And Balaam said to God, "Balak the son of Zippor, king of *_Moab_*, has sent to me, saying,
* `Num 22:14` And the princes of *_Moab_* rose up and they went to Balak and said, "Balaam refuses to come with us."
* `Num 22:21` And Balaam rose in the morning, saddled his donkey, and went with the princes of *_Moab_*.
* `Num 22:36` And when Balak heard that Balaam had come, he went out to meet him at the city of *_Moab_*, which is in the border of Arnon, which is in the utmost limit.
* `Num 23:6` And he returned to him and behold, he stood by his burnt-sacrifice—he and all the princes of *_Moab_*.
* `Num 23:7` And he took up his parable and said, "Balak the king of *_Moab_* has brought me from Aram, out of the mountains of the east, saying, 'Come, curse Jacob for me, and come, defy Israel.'
* `Num 23:17` And when he came to him, behold, he stood by his burnt-offering, and the princes of *_Moab_* with him. And Balak said to him, "What has the LORD spoken?"
* `Num 24:17` I shall see him, but not now. I shall behold him, but not near. There shall come a Star out of Jacob, and a Scepter shall rise out of Israel and shall smite the corners of *_Moab_* and destroy all the children of Sheth.
* `Num 25:1` And Israel stayed in Shittim, and the people began to commit lewdness with the daughters of *_Moab_*.
* `Num 26:3` And Moses and Eleazar the priest spoke with them in the plains of *_Moab_* by the Jordan near Jericho, saying,
* `Num 26:63` These are those who were numbered by Moses and Eleazar the priest, who numbered the children of Israel in the plains of *_Moab_* by the Jordan near Jericho.
* `Num 31:12` And they brought the captives, the plunder, and the loot to Moses and Eleazar the priest and to the congregation of the children of Israel, to the camp at the plains of *_Moab_*, which are by the Jordan near Jericho.
* `Num 33:44` And they departed from Oboth and encamped in Ije-abarim, in the border of *_Moab_*.
* `Num 33:48` And they departed from the mountains of Abarim and encamped in the plains of *_Moab_* by the Jordan near Jericho.
* `Num 33:49` And they encamped by the Jordan, from Beth-jeshimoth even to Abel-shittim in the plains of *_Moab_*.
* `Num 33:50` And the LORD spoke to Moses in the plains of *_Moab_* by the Jordan near Jericho, saying,
* `Num 35:1` And the LORD spoke to Moses in the plains of *_Moab_* by the Jordan near Jericho, saying,
* `Num 36:13` These are the commandments and the judgments which the LORD commanded by the hand of Moses to the children of Israel in the plains of *_Moab_* by the Jordan near Jericho.
* `Deu 1:5` On the east side of the Jordan, in the land of *_Moab_*, Moses began to declare this law, saying,
* `Deu 2:8` "And when we passed by from our brothers, the children of Esau, who dwelt in Seir, through the way of the plain from Elath and from Ezion-gaber, we turned and passed by the way of the wilderness of *_Moab_*.
* `Deu 2:18` 'Today you are to pass over the border of *_Moab_* at Ar.
* `Deu 29:1` These are the words of the covenant which the LORD commanded Moses to make with the children of Israel in the land of *_Moab_*, besides the covenant which he made with them in Horeb.
* `Deu 32:49` "Ascend this mountain of Abarim, to mount Nebo, which is in the land of *_Moab_*, that is over against Jericho, and behold the land of Canaan which I give to the children of Israel for a possession.
* `Deu 34:1` And Moses went up from the plains of *_Moab_* upon the mountain of Nebo, to the top of Pisgah, which is over against Jericho. And the LORD showed him all the land: from Gilead to Dan,
* `Deu 34:5` So Moses the servant of the LORD died there in the land of *_Moab_*, according to the word of the LORD.
* `Deu 34:6` And he buried him in a valley in the land of *_Moab_*, over against Beth-peor. But no man knows of his sepulcher to this day.
* `Deu 34:8` And the children of Israel wept for Moses in the plains of *_Moab_* for thirty days. So the days of weeping and mourning for Moses were finished.
* `Jsh 13:32` These are the countries which Moses distributed for inheritance in the plains of *_Moab_* on the other side of the Jordan by Jericho eastward.
* `Jsh 24:9` Then Balak the son of Zippor, king of *_Moab_*, arose and warred against Israel, and sent and called Balaam the son of Beor to curse you.
* `Jdg 3:12` And the children of Israel did evil again in the sight of the LORD. And the LORD strengthened Eglon the king of *_Moab_* against Israel, because they had done evil in the sight of the LORD.
* `Jdg 3:14` So the children of Israel served Eglon the king of *_Moab_* for eighteen years.
* `Jdg 3:15` But when the children of Israel cried to the LORD, the LORD raised up for them a deliverer: Ehud the son of Gera, a Benjaminite, a left-handed man. And by him the children of Israel sent a tribute to Eglon king of *_Moab_*.
* `Jdg 3:17` And he brought the tribute to Eglon king of *_Moab_* (Eglon was a very fat man).
* `Jdg 3:28` And he said to them, "Follow me, for the LORD has delivered your enemies the Moabites into your hand." And they went down after him and took the fords of the Jordan toward *_Moab_* and did not allow a man to pass over.
* `Jdg 3:29` And they slew of *_Moab_* at that time about ten thousand men, all lusty and all men of valor, and there did not escape a man.
* `Jdg 3:30` So *_Moab_* was subdued that day under the hand of Israel. And the land had rest for eighty years.
* `Jdg 10:6` And the children of Israel did evil again in the sight of the LORD and served Baalim, Ashtaroth, the gods of Syria, the gods of Zidon, the gods of *_Moab_*, the gods of the children of Ammon, and the gods of the Philistines, and forsook the LORD and did not serve him.
* `Jdg 11:15` And said to him, "Thus says Jephthah: 'Israel did not take away the land of *_Moab_*, nor the land of the children of Ammon,
* `Jdg 11:17` Israel sent messengers to the king of Edom, saying, "Let me, I pray you, pass through your land." But the king of Edom would not listen to it. And in like manner they sent to the king of *_Moab_*, but he would not consent. And Israel stayed in Kadesh.
* `Jdg 11:18` Then they went along through the wilderness and compassed the land of Edom and the land of *_Moab_*, came by the east side of the land of *_Moab_*, and pitched on the other side of Arnon, but did not come within the border of *_Moab_*, for Arnon was the border of *_Moab_*.
* `Jdg 11:25` And now are you anything better than Balak the son of Zippor king of *_Moab_*? Did he ever strive against Israel? Did he ever fight against them?
* `Rth 1:1` Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of Beth-lehem-judah went to dwell in the country of *_Moab_*—he, his wife, and his two sons.
* `Rth 1:2` And the name of the man was Elimelech, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of Beth-lehem-judah. And they came into the country of *_Moab_* and continued there.
* `Rth 1:4` And they took for themselves wives from the women of *_Moab_*: the name of one was Orpah and the name of the other Ruth. And they dwelt there about ten years.
* `Rth 1:6` Then she arose with her daughters-in-law so that she might return from the country of *_Moab_*, for she had heard in the country of *_Moab_* how the LORD had visited his people in giving them bread.
* `Rth 1:22` So Naomi returned, and Ruth the Moabitess her daughter-in-law with her, who returned from the country of *_Moab_*. And they came to Beth-lehem in the beginning of barley-harvest.
* `Rth 2:6` And the servant who was set over the reapers answered and said, "It is the young Moabite woman who came back with Naomi from the country of *_Moab_*.
* `Rth 4:3` And he said to the kinsman, "Naomi, who has come back out of the country of *_Moab_*, sells a parcel of land, which was our brother Elimelech's.
* `1Sa 12:9` And when they forgot the LORD their God, he sold them into the hand of Sisera, who was captain of the host of Hazor, into the hand of the Philistines and into the hand of the king of *_Moab_*, and they fought against them.
* `1Sa 14:47` So Saul took the kingdom over Israel and fought against all his enemies on every side: against *_Moab_*, against the children of Ammon, against Edom, against the kings of Zobah, and against the Philistines. And wherever he turned himself, he harassed them.
* `1Sa 22:3` And David went from there to Mizpeh of *_Moab_*. And he said to the king of *_Moab_*, "Let my father and my mother, I pray you, come forth and be with you until I know what God will do for me."
* `1Sa 22:4` And he brought them before the king of *_Moab_*. And they dwelt with him all the while that David was in the hold.
* `2Sa 8:2` And he smote *_Moab_* and measured them with a line, casting them down to the ground. Even with two lines he measured to put to death, and with one full line to keep alive. And so the Moabites became David's servants and brought gifts.
* `2Sa 8:12` From Syria, from *_Moab_*, from the children of Ammon, from the Philistines, from Amalek, and from the plunder of Hadadezer son of Rehob, king of Zobah.
* `2Sa 23:20` And Benaiah the son of Jehoiada, the son of a valiant man, of Kabzeel, who had done many acts, he slew two lion-like men of *_Moab_*. He went down also and slew a lion in the midst of a pit in time of snow.
* `1Ki 11:7` Then Solomon built a high place for Chemosh, the abomination of *_Moab_*, on the hill that is before Jerusalem, and for Molech, the abomination of the children of Ammon.
* `2Ki 1:1` Then *_Moab_* rebelled against Israel after the death of Ahab.
* `2Ki 3:4` And Mesha king of *_Moab_* was a sheep-master, and he rendered to the king of Israel one hundred thousand lambs and one hundred thousand rams, with the wool.
* `2Ki 3:5` But it came to pass, when Ahab was dead, that the king of *_Moab_* rebelled against the king of Israel.
* `2Ki 3:7` And he went and sent to Jehoshaphat the king of Judah, saying, "The king of *_Moab_* has rebelled against me. Will you go with me against *_Moab_* to battle?" And he said, "I will go. I am as you are, my people as your people, and my horses as your horses."
* `2Ki 3:10` And the king of Israel said, "Alas! For the LORD has called these three kings together to deliver them into the hand of *_Moab_*!"
* `2Ki 3:13` And Elisha said to the king of Israel, "What have I to do with you? Go to the prophets of your father and to the prophets of your mother." And the king of Israel said to him, "No, for the LORD has called these three kings together to deliver them into the hand of *_Moab_*."
* `2Ki 3:23` And they said, "This is blood. The kings are surely slain and they have smitten one another. Now therefore, *_Moab_*, to the plunder."
* `2Ki 3:26` And when the king of *_Moab_* saw that the battle was too severe for him, he took with him seven hundred men who drew swords to break through to the king of Edom, but they could not.
* `1Ch 1:46` And when Husham was dead, Hadad the son of Bedad, who smote Midian in the field of *_Moab_*, reigned in his stead, and the name of his city was Avith.
* `1Ch 4:22` Jokim, the men of Chozeba, Joash, Saraph who had the dominion in *_Moab_*, and Jashubi-lehem. And these records are ancient.
* `1Ch 8:8` And Shaharaim begot children in the country of *_Moab_* after he had sent them away. Hushim and Baara were his wives.
* `1Ch 11:22` Benaiah the son of Jehoiada, the son of a valiant man of Kabzeel, who had done many acts, he slew two lion-like men of *_Moab_*. Also, he went down and slew a lion in a pit on a snowy day.
* `1Ch 18:2` And he smote *_Moab_*, and the Moabites became David's servants and brought gifts.
* `1Ch 18:11` King David also dedicated them to the LORD with the silver and the gold that he brought from all these nations: from Edom, from *_Moab_*, from the children of Ammon, from the Philistines, and from Amalek.
* `2Ch 20:1` It came to pass after this also, that the children of *_Moab_* and the children of Ammon, and with them some of the Ammonites, came against Jehoshaphat to battle.
* `2Ch 20:10` And now, behold, the children of Ammon and *_Moab_* and mount Seir, whom you would not let Israel invade when they came from the land of Egypt, but they turned from them and did not destroy them,
* `2Ch 20:22` And when they began to sing and to praise, the LORD set ambushes against the children of Ammon, *_Moab_*, and mount Seir who had come against Judah, and they were smitten.
* `2Ch 20:23` For the children of Ammon and *_Moab_* stood up against the inhabitants of mount Seir, utterly to slay and destroy them. And when they had made an end of the inhabitants of Seir, everyone helped to destroy another.
* `Ezr 2:6` The children of Pahath-*_moab_*, of the children of Jeshua and Joab, two thousand eight hundred and twelve;
* `Ezr 8:4` Of the sons of Pahath-*_moab_*: Elihoenai the son of Zerahiah, and with him two hundred males.
* `Ezr 10:30` And of the sons of Pahath-*_moab_*: Adna, Chelal, Benaiah, Maaseiah, Mattaniah, Bezaleel, Binnui, and Manasseh.
* `Neh 3:11` Malchijah the son of Harim and Hashub the son of Pahath-*_moab_* repaired the other piece and the tower of the furnaces.
* `Neh 7:11` The children of Pahath-*_moab_*, of the children of Jeshua and Joab, two thousand eight hundred and eighteen;
* `Neh 10:14` The chief of the people: Parosh, Pahath-*_moab_*, Elam, Zatthu, Bani,
* `Neh 13:23` In those days I also saw Jews who had married wives of Ashdod, of Ammon, and of *_Moab_*.
* `Psa 60:8` *_Moab_* is my wash-pot. Over Edom I will cast out my shoe. Over Philistia I shout in triumph."
* `Psa 83:6` The tabernacles of Edom and the Ishmaelites, of *_Moab_* and the Hagarenes,
* `Psa 108:9` *_Moab_* is my wash-pot. Over Edom I will cast out my shoe. Over Philistia I will triumph."
* `Isa 11:14` But they shall fly upon the shoulders of the Philistines toward the west. They shall plunder those of the east together. They shall lay their hand upon Edom and *_Moab_*. And the children of Ammon shall obey them.
* `Isa 15:1` [The burden of *_Moab_*.] For in the night, Ar of *_Moab_* is laid waste and brought to silence. For in the night, Kir of *_Moab_* is laid waste and brought to silence.
* `Isa 15:2` He has gone up to Bajith and to Dibon, the high places, to weep. *_Moab_* shall howl over Nebo and over Medeba. On all their heads there shall be baldness, and every beard shorn.
* `Isa 15:4` And Heshbon shall cry, along with Elealeh. Their voice shall be heard even to Jahaz; therefore, the armed soldiers of *_Moab_* shall cry out. His life shall be grievous to him.
* `Isa 15:5` My heart shall cry out for *_Moab_*. His fugitives shall flee to Zoar, a heifer of three years old. For they shall go up the ascent of Luhith with weeping, for in the way of Horonaim they shall raise a cry of destruction.
* `Isa 15:8` For the cry has gone around the borders of *_Moab_*, her howling to Eglaim and her howling to Beer-elim.
* `Isa 15:9` For the waters of Dimon shall be full of blood, for I will bring more upon Dimon, lions upon him who escapes of *_Moab_* and upon the remnant of the land.
* `Isa 16:2` For it shall be, that as a wandering bird cast out of the nest, so the daughters of *_Moab_* shall be at the fords of Arnon.
* `Isa 16:4` Let my outcasts dwell with you, *_Moab_*. Be a covert to them from the face of the destroyer. For the extortioner is at an end. Devastation ceases. The oppressors are consumed out of the land.
* `Isa 16:6` We have heard of the pride of *_Moab_*, that he is very proud, even of his haughtiness, his pride, and his wrath. But his lies shall not be so.
* `Isa 16:7` Therefore, *_Moab_* shall howl for *_Moab_*, everyone shall howl. For the foundations of Kir-hareseth you shall mourn. Surely they are stricken.
* `Isa 16:11` Therefore, my heart shall sound like a harp for *_Moab_* and my inward parts for Kir-haresh.
* `Isa 16:12` And it shall come to pass when it is seen that *_Moab_* is weary on the high place, that he shall come to his sanctuary to pray, but he shall not prevail.
* `Isa 16:13` This is the word that the LORD has spoken concerning *_Moab_* since that time.
* `Isa 16:14` But now the LORD has spoken, saying, "Within three years, as the years of a hireling, and the glory of *_Moab_* shall be despised with all that great multitude, and the remnant shall be very small and feeble."
* `Isa 25:10` For on this mountain the hand of the LORD shall rest, and *_Moab_* shall be trodden down under him, even as straw is trodden down for the dunghill.
* `Jer 9:26` Egypt, Judah, Edom, the children of Ammon, *_Moab_*, and all who are in the utmost corners who dwell in the wilderness. For all these nations are uncircumcised, and all the house of Israel are uncircumcised in the heart."
* `Jer 25:21` Edom, *_Moab_*, the children of Ammon;
* `Jer 27:3` And send them to the king of Edom, to the king of *_Moab_*, to the king of the Ammonites, to the king of Tyre, and to the king of Zidon by the hand of the messengers who come to Jerusalem to Zedekiah king of Judah.
* `Jer 40:11` Likewise, when all the Jews who were in *_Moab_*, among the Ammonites, in Edom, and who were in all the countries heard that the king of Babylon had left a remnant of Judah and that he had set over them Gedaliah the son of Ahikam the son of Shaphan,
* `Jer 48:1` [Against *_Moab_*.] Thus says the LORD of hosts, the God of Israel: "Woe to Nebo! For it is laid waste. Kiriathaim is confounded and taken. Misgab is confounded and dismayed.
* `Jer 48:2` There shall be no more praise of *_Moab_*. In Heshbon they have devised evil against it. 'Come, and let us cut it off from being a nation.' Also you shall be cut down, O Madmen. The sword shall pursue you.
* `Jer 48:4` *_Moab_* is destroyed. Her little ones have caused a cry to be heard.
* `Jer 48:9` Give wings to *_Moab_* so that it may flee and get away, for its cities shall be desolate without any to dwell in them.
* `Jer 48:11` *_Moab_* has been at ease from his youth, and he has settled on his dregs and has not been emptied from vessel to vessel, neither has he gone into captivity. Therefore, his taste remained in him, and his scent is not changed.
* `Jer 48:13` And *_Moab_* shall be ashamed of Chemosh, as the house of Israel was ashamed of Beth-el their confidence.
* `Jer 48:15` *_Moab_* is laid waste and gone up out of her cities, and his chosen young men have gone down to the slaughter," says the King, whose name is the LORD of hosts.
* `Jer 48:16` "The calamity of *_Moab_* is near to come, and his affliction hastens fast.
* `Jer 48:18` You daughter who inhabits Dibon, come down from your glory and sit in thirst, for the destroyer of *_Moab_* shall come upon you and he shall destroy your strongholds.
* `Jer 48:20` *_Moab_* is confounded, for it is broken down. Howl and cry. Tell it in Arnon that *_Moab_* is laid waste.
* `Jer 48:24` Upon Kerioth, upon Bozrah, and upon all the cities of the land of *_Moab_*, far or near.
* `Jer 48:25` The horn of *_Moab_* is cut off, and his arm is broken," says the LORD.
* `Jer 48:26` "Make him drunken, for he magnified himself against the LORD. *_Moab_* shall also wallow in his vomit and shall also be in derision.
* `Jer 48:28` "O you who dwell in *_Moab_*, leave the cities, dwell in the rock, and be like the dove that makes her nest in the sides of the hole's mouth.
* `Jer 48:29` We have heard the pride of *_Moab_* (he is exceedingly proud), his loftiness, his arrogance, his pride, and the haughtiness of his heart.
* `Jer 48:31` Therefore, I will howl for *_Moab_*, and I will cry out for all *_Moab_*. My heart shall mourn for the men of Kirheres.
* `Jer 48:33` And joy and gladness is taken from the plentiful field and from the land of *_Moab_*, and I have caused wine to fail from the wine-presses. No one shall tread with shouting. Their shouting shall be no shouting.
* `Jer 48:35` Moreover, I will cause to cease in *_Moab_*," says the LORD, "him who offers in the high places and him who burns incense to his gods.
* `Jer 48:36` "Therefore, my heart shall sound for *_Moab_* like pipes, and my heart shall sound like pipes for the men of Kirheres because the riches that he has gotten have perished.
* `Jer 48:38` There shall be lamentation generally upon all the house-tops of *_Moab_* and in its streets, for I have broken *_Moab_* like a vessel in which there is no pleasure," says the LORD.
* `Jer 48:39` "They shall howl, saying, 'How it is broken down! How *_Moab_* has turned the back with shame!' So *_Moab_* shall be a derision and a dismaying to all who are around him."
* `Jer 48:40` For thus says the LORD: "Behold, he shall fly like an eagle and shall spread his wings over *_Moab_*.
* `Jer 48:41` Kerioth is taken and the strongholds are surprised, and the mighty men's hearts in *_Moab_* at that day shall be like the heart of a woman in her pangs.
* `Jer 48:42` And *_Moab_* shall be destroyed from being a people because he has magnified himself against the LORD.
* `Jer 48:43` Fear, the pit, and the snare shall be upon you, O inhabitant of *_Moab_*," says the LORD.
* `Jer 48:44` "He who flees from the fear shall fall into the pit. And he who gets out of the pit shall be taken in the snare. For I will bring upon it, even upon *_Moab_*, the year of their visitation," says the LORD.
* `Jer 48:45` "Those who fled stood under the shadow of Heshbon because of the force. But a fire shall come out of Heshbon, and a flame from the midst of Sihon, and shall devour the corner of *_Moab_* and the crown of the head of the tumultuous ones.
* `Jer 48:46` Woe to you, O *_Moab_*! The people of Chemosh perish, for your sons are taken away captive, and your daughters into captivity.
* `Jer 48:47` Yet I will bring back the captivity of *_Moab_* in the latter days," says the LORD. [Thus far is the judgment of *_Moab_*.]
* `Ezk 25:8` 'Thus says the Lord GOD: "Because *_Moab_* and Seir say, 'Behold, the house of Judah is like all the heathen,'
* `Ezk 25:9` Therefore behold, I will open the side of *_Moab_* from the cities, from his cities which are on his frontiers—Beth-jeshimoth, Baal-meon, and Kiriathaim—the glory of the country.
* `Ezk 25:11` And I will execute judgments upon *_Moab_*. And they shall know that I am the LORD."
* `Dan 11:41` He shall also enter into the glorious land, and many countries shall be overthrown, but these shall escape out of his hand: Edom, *_Moab_*, and the chief of the children of Ammon.
* `Amo 2:1` Thus says the LORD: "For three transgressions of *_Moab_*, and for four, I will not turn away his punishment, because he burned the bones of the king of Edom into lime.
* `Amo 2:2` But I will send a fire upon *_Moab_*, and it shall devour the palaces of Kirioth. And *_Moab_* shall die with tumult, with shouting, and with the sound of the trumpet.
* `Mic 6:5` O my people, remember now what Balak king of *_Moab_* consulted, and what Balaam the son of Beor answered him, [and what I did] from Shittim to Gilgal, so that you may know the righteousness of the LORD."
* `Zph 2:8` "I have heard the reproach of *_Moab_* and the revilings of the children of Ammon by which they have reproached my people and magnified themselves against their border.
* `Zph 2:9` Therefore, as I live," says the LORD of hosts, the God of Israel, "surely *_Moab_* shall be as Sodom and the children of Ammon as Gomorrah, even a place possessed by nettles and salt-pits and a perpetual desolation. The remnant of my people shall lay them waste and the remainder of my people shall possess them."

_157 verses containing MOAB_

== MOABITE

* `Deu 23:3` An Ammonite or *_Moabite_* shall not enter into the congregation of the LORD. Even to their tenth generation they shall not enter into the congregation of the LORD forever,
* `Rth 2:6` And the servant who was set over the reapers answered and said, "It is the young *_Moabite_* woman who came back with Naomi from the country of Moab.
* `1Ch 11:46` Eliel the Mehavite, Jeribai and Joshaviah the sons of Elnaam, Ithmah the *_Moabite_*,
* `Neh 13:1` On that day they read in the book of Moses in the audience of the people. And therein was found written that the Ammonite and the *_Moabite_* should not come into the congregation of God forever,

_4 verses containing MOABITE_

== MOABITES

* `Gen 19:37` And the first-born bore a son and called his name Moab. The same is the father of the *_Moabites_* to this day.
* `Num 22:4` And Moab said to the elders of Midian, "Now this company shall lick up all that is around us as the ox licks up the grass of the field." And Balak the son of Zippor was king of the *_Moabites_* at that time.
* `Deu 2:9` And the LORD said to me, 'Do not distress the *_Moabites_*, neither contend with them in battle, for I will not give you any of their land for a possession, because I have given Ar to the children of Lot for a possession.'
* `Deu 2:11` Who also were accounted Rephaim, as the Anakims, but the *_Moabites_* call them Emims.
* `Deu 2:29` (As the children of Esau who dwell in Seir and the *_Moabites_* who dwell in Ar did to me), until I pass over the Jordan into the land which the LORD our God gives us.'
* `Jdg 3:28` And he said to them, "Follow me, for the LORD has delivered your enemies the *_Moabites_* into your hand." And they went down after him and took the fords of the Jordan toward Moab and did not allow a man to pass over.
* `2Sa 8:2` And he smote Moab and measured them with a line, casting them down to the ground. Even with two lines he measured to put to death, and with one full line to keep alive. And so the *_Moabites_* became David's servants and brought gifts.
* `1Ki 11:1` But king Solomon loved many foreign women, together with the daughter of Pharaoh, women of the *_Moabites_*, Ammonites, Edomites, Zidonians, and Hittites,
* `1Ki 11:33` Because they have forsaken me and have worshiped Ashtoreth the goddess of the Zidonians, Chemosh the god of the *_Moabites_*, and Milcom the god of the children of Ammon, and have not walked in my ways to do that which is right in my eyes and to keep my statutes and my judgments, as David his father did.
* `2Ki 3:18` And this is but a light thing in the sight of the LORD. He will deliver the *_Moabites_* also into your hand.
* `2Ki 3:21` And when all the *_Moabites_* heard that the kings had come up to fight against them, they gathered all who were able to put on armor and older, and stood in the border.
* `2Ki 3:22` And they rose early in the morning, and the sun shone upon the water. And the *_Moabites_* saw the water on the other side as red as blood.
* `2Ki 3:24` And when they came to the camp of Israel, the Israelites rose and smote the *_Moabites_* so that they fled before them. And they went forward smiting the *_Moabites_*, even in their country.
* `2Ki 13:20` And Elisha died, and they buried him. And the bands of the *_Moabites_* invaded the land at the coming in of the year.
* `2Ki 23:13` And the high places that were before Jerusalem, which were on the right hand of the mountain of corruption, which Solomon the king of Israel had built for Ashtoreth the abomination of the Zidonians, for Chemosh the abomination of the *_Moabites_*, and for Milcom the abomination of the children of Ammon, the king defiled.
* `2Ki 24:2` And the LORD sent against him bands of the Chaldeans, bands of the Syrians, bands of the *_Moabites_*, and bands of the children of Ammon, and sent them against Judah to destroy it, according to the word of the LORD which he spoke by his servants the prophets.
* `1Ch 18:2` And he smote Moab, and the *_Moabites_* became David's servants and brought gifts.
* `Ezr 9:1` Now when these things were done, the princes came to me, saying, "The people of Israel, the priests, and the Levites have not separated themselves from the people of the lands, doing according to their abominations, even of the Canaanites, the Hittites, the Perizzites, the Jebusites, the Ammonites, the *_Moabites_*, the Egyptians, and the Amorites.

_18 verses containing MOABITES_

== MOABITESS

* `Rth 1:22` So Naomi returned, and Ruth the *_Moabitess_* her daughter-in-law with her, who returned from the country of Moab. And they came to Beth-lehem in the beginning of barley-harvest.
* `Rth 2:2` And Ruth the *_Moabitess_* said to Naomi, "Let me now go to the field and glean heads of grain after him in whose sight I shall find grace." And she said to her, "Go, my daughter."
* `Rth 2:21` And Ruth the *_Moabitess_* said, "He also said to me, 'You shall keep close by my young men until they have ended all my harvest.'"
* `Rth 4:5` Then Boaz said, "The day you buy the field from the hand of Naomi, you must also accept Ruth the *_Moabitess_*, the wife of the dead, to raise up the name of the dead upon his inheritance."
* `Rth 4:10` Moreover, Ruth the *_Moabitess_*, the wife of Mahlon, I have purchased to be my wife to raise up the name of the dead upon his inheritance, so that the name of the dead is not cut off from among his brothers and from the gate of his place. You are witnesses this day."
* `2Ch 24:26` And these are those who conspired against him: Zabad the son of Shimeath the Ammonitess, and Jehozabad the son of Shimrith the *_Moabitess_*.

_6 verses containing MOABITESS_

== MOADIAH

* `Neh 12:17` Of Abijah, Zichri; of Miniamin, of *_Moadiah_*, Piltai;

_1 verse containing MOADIAH_

== MOAT

* `Dan 9:25` Know therefore, and understand, that from the going forth of the commandment to restore and to build Jerusalem to the Messiah, the Prince, shall be seven weeks and sixty-two weeks. It shall be built again with a plaza and a *_moat_*, even in troubled times.

_1 verse containing MOAT_

== MOCK

* `Gen 39:14` That she called to the men of her house and spoke to them, saying, "See, he has brought in a Hebrew to us to *_mock_* us. He came to me to lie with me, and I cried with a loud voice.
* `Gen 39:17` And she spoke to him according to these words, saying, "The Hebrew servant which you have brought to us came to me to *_mock_* me.
* `Job 11:3` Should your falsehoods make men hold their peace? And when you *_mock_*, shall no man make you ashamed?
* `Job 13:9` Is it good that he should search you out? Or as one man mocks another, do you likewise *_mock_* him?
* `Job 21:3` Allow me that I may speak. And after I have spoken, *_mock_* on.
* `Pro 1:26` I also will laugh at your calamity. I will *_mock_* when your fear comes,
* `Pro 14:9` Fools make a *_mock_* at sin, but among the righteous there is favor.
* `Jer 38:19` And Zedekiah the king said to Jeremiah, "I am afraid of the Jews who have fallen to the Chaldeans, lest they deliver me into their hand and they *_mock_* me."
* `Ezk 22:5` Those who are near and those who are far from you shall *_mock_* you, who are infamous and much troubled.
* `Mth 20:19` And will deliver him to the Gentiles to *_mock_*, scourge, and crucify him. And on the third day he will rise again."
* `Mrk 10:34` And they will *_mock_* him, scourge him, spit upon him, and kill him. But on the third day he will rise again."
* `Luk 14:29` Or else, after he has laid the foundation and is not able to finish it, all who behold it begin to *_mock_* him,

_12 verses containing MOCK_

== MOCKED

* `Gen 19:14` And Lot went out and spoke to his sons-in-law, who married his daughters, and said, "Arise, depart from this place, for the LORD will destroy this city." But he seemed to his sons-in-law as one who *_mocked_*.
* `Num 22:29` And Balaam said to the donkey, "Because you have *_mocked_* me. I wished there were a sword in my hand, for now I would kill you."
* `Jdg 16:10` And Delilah said to Samson, "Behold, you have *_mocked_* me and told me lies. Now tell me, I pray you, with what you may be bound."
* `Jdg 16:13` And Delilah said to Samson, "Until now you have *_mocked_* me and told me lies. Tell me with what you may be bound." And he said to her, "If you weave the seven locks of my head with the web."
* `Jdg 16:15` And she said to him, "How can you say, 'I love you,' when your heart is not with me? You have *_mocked_* me these three times and have not told me in what your great strength lies."
* `1Ki 18:27` And it came to pass at noon, that Elijah *_mocked_* them and said, "Cry aloud, for he is a god! Either he is talking, he is pursuing, he is on a journey, or perhaps he sleeps and must be awakened."
* `2Ki 2:23` And he went up from there to Beth-el. And as he was going up by the way, little children came forth out of the city and *_mocked_* him and said to him, "Go up, you bald-head. Go up, you bald-head."
* `2Ch 30:10` So the posts passed from city to city through the country of Ephraim and Manasseh and even to Zebulun, but they laughed them to scorn and *_mocked_* them.
* `2Ch 36:16` But they *_mocked_* the messengers of God, despised his words, and misused his prophets until the wrath of the LORD arose against his people until there was no remedy.
* `Neh 4:1` But it came to pass, that when Sanballat heard that we were building the wall, he was angry, took great indignation, and *_mocked_* the Jews.
* `Job 12:4` I am like one *_mocked_* by his neighbor, who calls upon God, and he answers him. The just upright man is derided.
* `Lam 1:7` [ZAYIN] Jerusalem remembers in the days of her affliction and of her miseries all her pleasant things that she had in the days of old. When her people fell into the hand of the enemy, no one helped her. The adversaries saw her and *_mocked_* at her desolations.
* `Mth 2:16` Then Herod, when he saw that he was *_mocked_* by the wise men, was exceedingly angry, and sent forth and slew all the children who were in Bethlehem and in all its borders, from two years old and under, according to the time which he had ascertained from the wise men.
* `Mth 27:29` And when they had platted a crown of thorns, they put it upon his head and a reed in his right hand. And they bowed the knee before him and *_mocked_* him, saying, "Hail, King of the Jews!"
* `Mth 27:31` And after they had *_mocked_* him, they took the robe off of him, put his own clothing on him, and led him away to crucify him.
* `Mrk 15:20` And when they had *_mocked_* him, they took the purple from off of him, put his own clothes on him, and led him out to crucify him.
* `Luk 18:32` For he will be delivered to the Gentiles, *_mocked_*, spitefully treated, and spit upon.
* `Luk 22:63` And the men who held Jesus *_mocked_* him and smote him.
* `Luk 23:11` And Herod with his troops set him at nothing, *_mocked_* him, arrayed him in a gorgeous robe, and sent him back to Pilate.
* `Luk 23:36` And the soldiers also *_mocked_* him, coming to him and offering him vinegar,
* `Act 17:32` And when they heard of the resurrection of the dead, some *_mocked_*, but others said, "We will hear you again concerning this matter."
* `Gal 6:7` Do not be deceived. God is not *_mocked_*. For whatever a man sows, that he shall also reap.

_22 verses containing MOCKED_

== MOCKER

* `Pro 20:1` Wine is a *_mocker_*, strong drink is raging, and whoever is deceived by it is not wise.

_1 verse containing MOCKER_

== MOCKERS

* `Job 17:2` Are there not *_mockers_* with me? And does my eye not continue in their provocation?
* `Psa 35:16` With hypocritical *_mockers_* in feasts, they gnashed upon me with their teeth.
* `Isa 28:22` Now therefore, do not be *_mockers_*, lest your bonds be made strong, for I have heard from the Lord GOD of hosts a consumption, even determined upon the whole earth.
* `Jer 15:17` I did not sit in the assembly of the *_mockers_*, nor rejoice. I sat alone because of your hand, for you have filled me with indignation.
* `Jde 1:18` That they told you, "There would be *_mockers_* in the last time who would walk after their own ungodly lusts."

_5 verses containing MOCKERS_

== MOCKING

* `Gen 21:9` And Sarah saw the son of Hagar the Egyptian, which she had borne to Abraham, *_mocking_*.
* `Isa 57:4` Who are you *_mocking_*? Against whom do you make a wide mouth and thrust out the tongue? Are you not children of transgression, offspring of falsehood,
* `Ezk 22:4` You have become guilty in your blood that you have shed, have defiled yourself by your idols which you have made, have caused your days to draw near, and have come even to your years; therefore, I have made you a reproach to the heathen and a *_mocking_* to all countries.
* `Mth 27:41` Likewise, the chief priests also *_mocking_* him, with the scribes and elders, said,
* `Mrk 15:31` Likewise, the chief priests, also *_mocking_*, said among themselves with the scribes, "He saved others, but he cannot save himself.
* `Act 2:13` Others *_mocking_*, said, "These men are full of new wine."

_6 verses containing MOCKING_

== MOCKINGS

* `Heb 11:36` Others had trial of cruel *_mockings_* and scourgings and also of bonds and imprisonment.

_1 verse containing MOCKINGS_

== MOCKS

* `Job 13:9` Is it good that he should search you out? Or as one man *_mocks_* another, do you likewise mock him?
* `Job 39:22` He *_mocks_* at fear and is not terrified, neither does he turn back from the sword.
* `Pro 17:5` He who *_mocks_* the poor reproaches his Maker, and he who is glad at calamities shall not be unpunished.
* `Pro 30:17` The eye that *_mocks_* at its father and despises to obey its mother, the ravens of the valley shall pick it out, and the young eagles shall eat it.
* `Jer 20:7` O LORD, you have deceived me, and I was deceived. You are stronger than I, and have prevailed. I am in derision daily. Everyone *_mocks_* me.

_5 verses containing MOCKS_

== MODERATELY

* `Joe 2:23` Be glad then, children of Zion, and rejoice in the LORD your God, for he has given you the former rain *_moderately_*. He will cause to come down for you the rain, the former rain and the latter rain, in the first month.

_1 verse containing MODERATELY_

== MODESTY

* `1Co 12:23` And those members of the body which we think to be less honorable, upon these we bestow more abundant honor. And our unpresentable parts have more abundant *_modesty_*,
* `1Ti 2:9` In like manner also, [I wish] that women adorn themselves in decent apparel with *_modesty_* and sobriety, not with braided hair, gold, pearls, or costly array,

_2 verses containing MODESTY_

== MOIST

* `Num 6:3` He shall separate himself from wine and strong drink and shall drink no vinegar of wine or vinegar of strong drink, neither shall he drink any liquor of grapes nor eat *_moist_* or dried grapes.
* `Deu 29:19` And it should come to pass when he hears the words of this curse, that he should bless himself in his heart, saying, 'I shall have peace, though I walk in the imagination of my heart,' to sweep away the *_moist_* with the dry.

_2 verses containing MOIST_

== MOISTENED

* `Job 21:24` His pails are full of milk and his bones are *_moistened_* with marrow.

_1 verse containing MOISTENED_

== MOISTURE

* `Job 37:11` Also, with *_moisture_* he lades the thick cloud. He scatters his bright cloud,
* `Psa 32:4` For day and night your hand was heavy upon me. My *_moisture_* is turned into the drought of summer. [Selah.]
* `Luk 8:6` And some fell upon a rock, and as soon as it had sprung up, it withered because it lacked *_moisture_*.

_3 verses containing MOISTURE_

== MOLADAH

* `Jsh 15:26` Aman, Shema, *_Moladah_*,
* `Jsh 19:2` And they had in their inheritance, Beer-sheba (or Sheba), *_Moladah_*,
* `1Ch 4:28` And they dwelt at Beer-sheba, *_Moladah_*, Hazar-shual,
* `Neh 11:26` At Jeshua, at *_Moladah_*, at Beth-phelet,

_4 verses containing MOLADAH_

== MOLDY

* `Jsh 9:5` And also old and patched shoes upon their feet and old garments upon themselves. And all the bread of their provision was dry and *_moldy_*.
* `Jsh 9:12` Our bread we took hot for our provision out of our houses on the day we came forth to go to you, but now, behold, it is dry and *_moldy_*.

_2 verses containing MOLDY_

== MOLE

* `Lev 11:30` The ferret, the chameleon, the lizard, the snail, and the *_mole_*.

_1 verse containing MOLE_

== MOLECH

* `Lev 18:21` And you shall not let any of your children pass through the fire to *_Molech_*, neither shall you profane the name of your God. I am the LORD.
* `Lev 20:2` "Again you shall say to the children of Israel, 'Any man of the children of Israel or of the strangers who sojourn in Israel who gives any of his children to *_Molech_*, he shall surely be put to death. The people of the land shall stone him with stones.
* `Lev 20:3` And I will set my face against that man and will cut him off from among his people because he has given his children to *_Molech_* to defile my sanctuary and to profane my holy name.
* `Lev 20:4` And if the people of the land at all hide their eyes from the man when he gives his children to *_Molech_* and do not kill him,
* `Lev 20:5` Then I will set my face against that man and against his family and will cut off from among their people both him and all who go astray after him to commit lewdness with *_Molech_*.
* `1Ki 11:7` Then Solomon built a high place for Chemosh, the abomination of Moab, on the hill that is before Jerusalem, and for *_Molech_*, the abomination of the children of Ammon.
* `2Ki 23:10` And he defiled Topheth, which is in the valley of the children of Hinnom, so that no man might make his son or his daughter to pass through the fire to *_Molech_*.
* `Jer 32:35` And they built the high places of Baal which are in the valley of the son of Hinnom to cause their sons and their daughters to pass through the fire to *_Molech_*, which I did not command them, neither did it come into my mind, that they should do this abomination to cause Judah to sin.

_8 verses containing MOLECH_

== MOLES

* `Isa 2:20` In that day a man shall cast his idols of silver and his idols of gold, which they made each one for himself to worship, to the *_moles_* and to the bats.

_1 verse containing MOLES_

== MOLID

* `1Ch 2:29` And the name of the wife of Abishur was Abihail, and she bore him Ahban and *_Molid_*.

_1 verse containing MOLID_

== MOLLIFIED

* `Isa 1:6` From the sole of the foot even to the head there is no soundness in it, but wounds, bruises, and putrefying sores. They have not been closed, neither bound up, neither *_mollified_* with ointment.

_1 verse containing MOLLIFIED_

== MOLOCH

* `Act 7:43` You even took up the tabernacle of *_Moloch_* and the star of your god Rephan, figures which you made to worship them. I will carry you away beyond Babylon.'

_1 verse containing MOLOCH_

== MOLTEN

* `Exo 32:4` And he received them at their hand and fashioned it with an engraving tool and made it a *_molten_* calf. And they said, "These are your gods, O Israel, which brought you out of the land of Egypt."
* `Exo 32:8` They have turned aside quickly from the way which I commanded them. They have made themselves a *_molten_* calf, worshiped it, sacrificed to it, and said, 'These are your gods, O Israel, which have brought you out of the land of Egypt.'"
* `Exo 34:17` You shall make yourself no *_molten_* gods.
* `Lev 19:4` Do not turn to idols nor make for yourselves *_molten_* gods. I am the LORD your God.
* `Num 33:52` You shall drive out all the inhabitants of the land from before you, destroy all their pictures, destroy all their *_molten_* images, and quite demolish all their high places.
* `Deu 9:12` And the LORD said to me, 'Arise, go down quickly from here, for your people which you have brought forth out of Egypt have corrupted themselves. They have quickly turned aside from the way which I commanded them. They have made themselves a *_molten_* image.'
* `Deu 9:16` And I looked, and behold, you had sinned against the LORD your God and had made yourselves a *_molten_* calf. You had turned aside quickly from the way which the LORD had commanded you.
* `Deu 27:15` 'Cursed is the man who makes any engraved or *_molten_* image, an abomination to the LORD, the work of the hands of the craftsman, and puts it in a secret place.' And all the people shall answer and say, 'Amen.'
* `Jdg 17:3` And when he had restored the eleven hundred shekels of silver to his mother, his mother said, "I had wholly dedicated the silver to the LORD from my hand for my son to make an engraved image and a *_molten_* image. Now therefore, I will restore it to you."
* `Jdg 17:4` So he restored the money to his mother, and his mother took two hundred shekels of silver and gave them to the founder, who made from it an engraved image and a *_molten_* image. And they were in the house of Micah.
* `Jdg 18:14` Then the five men who went to explore the country of Laish answered and said to their brothers, "Do you know that there is in these houses an ephod, teraphim, an engraved image, and a *_molten_* image? Now therefore, consider what you have to do."
* `Jdg 18:17` And the five men who went to explore the land went up, came in there, and took the engraved image, the ephod, the teraphim, and the *_molten_* image. And the priest stood in the entrance of the gate with the six hundred men who were appointed with weapons of war.
* `Jdg 18:18` And these went into Micah's house and brought the carved image, the ephod, the teraphim, and the *_molten_* image. Then the priest said to them, "What are you doing?"
* `1Ki 7:16` And he made two capitals of *_molten_* brass to set upon the tops of the pillars. The height of one capital was five cubits and the height of the other capital was five cubits.
* `1Ki 7:23` And he made a *_molten_* sea, ten cubits from one brim to the other. It was entirely round and its height was five cubits, and a line of thirty cubits encompassed it.
* `1Ki 7:30` And every base had four brazen wheels and plates of brass, and its four corners had supports. Under the basin were *_molten_* supports, with wreaths at the side of each.
* `1Ki 7:33` And the work of the wheels was like the work of a chariot wheel. Their axletrees, their rims, their hubs, and their spokes were all *_molten_*.
* `1Ki 14:9` But you have done evil above all who were before you, for you have gone and made yourself other gods and *_molten_* images to provoke me to anger, and have cast me behind your back,
* `2Ki 17:16` And they left all the commandments of the LORD their God, made for themselves *_molten_* images, even two calves, and made a grove, worshiped all the host of heaven, and served Baal.
* `2Ch 4:2` He also made a *_molten_* sea of ten cubits from brim to brim, round in compass, and five cubits was its height, and a line of thirty cubits encompassed it.
* `2Ch 28:2` For he walked in the ways of the kings of Israel and also made *_molten_* images for Baalim.
* `2Ch 34:3` For in the eighth year of his reign, while he was still young, he began to seek after the God of David his father. And in the twelfth year he began to purge Judah and Jerusalem of the high places, the groves, the carved images, and the *_molten_* images.
* `2Ch 34:4` And they broke down the altars of Baalim in his presence, and he cut down the images that were on high above them. And the groves, the carved images, and the *_molten_* images he broke in pieces and made dust of them and scattered it upon the graves of those who had sacrificed to them.
* `Neh 9:18` Indeed, when they had made themselves a *_molten_* calf, and said, 'This is your God who brought you out of Egypt,' and had wrought great provocations,
* `Psa 106:19` They made a calf in Horeb and worshiped the *_molten_* image.
* `Isa 30:22` You shall also defile the covering of your engraved images of silver and the ornament of your *_molten_* images of gold. You shall cast them away like a polluted cloth. You shall say to it, "Be gone from me."
* `Isa 41:29` Behold, they are all vanity. Their works are nothing. Their *_molten_* images are wind and confusion."
* `Isa 42:17` They shall be turned back, they shall be greatly ashamed, who trust in engraved images, who say to the *_molten_* images, "You are our gods."
* `Isa 48:5` I have even from the beginning declared it to you. Before it came to pass I showed it to you, lest you should say, 'My idol has done them, and my engraved image and my *_molten_* image has commanded them.'
* `Jer 10:14` Every man is brutish in his knowledge. Every founder is confounded by the engraved image, for his *_molten_* image is falsehood and there is no breath in them.
* `Jer 51:17` Every man is brutish by his knowledge. Every founder is confounded by the engraved image, for his *_molten_* image is falsehood, and there is no breath in them.
* `Hos 13:2` And now they sin more and more, and have made for themselves *_molten_* images of their silver and idols according to their own understanding, all of it the work of craftsmen. They say of them, 'Let the men who sacrifice kiss the calves.'
* `Nah 1:14` And the LORD has given a commandment concerning you, that no more of your name be sown. "Out of the house of your gods I will cut off the engraved image and the *_molten_* image. I will make your grave, for you are vile."
* `Hab 2:18` What profit is the engraved image when its maker has engraved it—the *_molten_* image and a teacher of lies—that the maker trusts in what he has formed, making mute idols?

_34 verses containing MOLTEN_

