= BEND - BETHUL
:toc:

== BEND

* `Psa 11:2` For behold, the wicked *_bend_* their bow. They make ready their arrow upon the string so that they may secretly shoot at the upright in heart.
* `Psa 64:3` Who whet their tongue like a sword and *_bend_* their bows to shoot their arrows, even bitter words,
* `Jer 9:3` "And they *_bend_* their tongues like their bows for lies, but they are not valiant for the truth upon the earth, for they proceed from evil to evil and they do not know me," says the LORD.
* `Jer 46:9` Come up, you horses, and rage, you chariots, and let the mighty men come forth—the Cushites and the Libyans who handle the shield, and the Lydians who handle and *_bend_* the bow.
* `Jer 50:14` Put yourselves in array against Babylon on every side. All you who *_bend_* the bow, shoot at her, spare no arrows, for she has sinned against the LORD.
* `Jer 50:29` "Call together the archers against Babylon. All you who *_bend_* the bow, encamp against it on every side. Let none thereof escape. Recompense her according to her work. According to all that she has done, do to her, for she has been proud against the LORD, against the Holy One of Israel.
* `Jer 51:3` Against him who bends, let the archer *_bend_* his bow, and against him who lifts himself up in his coat of mail. And do not spare her young men. Utterly destroy all her host.

_7 verses containing BEND_

== BENDING

* `Isa 60:14` The sons of those who afflicted you shall also come *_bending_* to you. And all those who despised you shall bow themselves down at the soles of your feet. And they shall call you, The City of the LORD, The Zion of the Holy One of Israel.

_1 verse containing BENDING_

== BENDS

* `Psa 58:7` Let them melt away like waters which run continually. When he *_bends_* his bow to shoot his arrows, let them be as though they were cut off.
* `Jer 51:3` Against him who *_bends_*, let the archer bend his bow, and against him who lifts himself up in his coat of mail. And do not spare her young men. Utterly destroy all her host.

_2 verses containing BENDS_

== BENE-BERAK

* `Jsh 19:45` Jehud, *_Bene-berak_*, Gath-rimmon,

_1 verse containing BENE-BERAK_

== BENE-JAAKAN

* `Num 33:31` And they departed from Moseroth and encamped in *_Bene-jaakan_*.
* `Num 33:32` And they departed from *_Bene-jaakan_* and encamped at Hor-hagidgad.

_2 verses containing BENE-JAAKAN_

== BENEATH

* `Gen 35:8` But Deborah, Rebekah's nurse, died, and she was buried *_beneath_* Beth-el under an oak. And its name was called Allon-bachuth.
* `Gen 49:25` Even by the God of your father who shall help you, and by the Almighty who shall bless you with blessings of heaven above, blessings of the deep that lies *_beneath_*, blessings of the breasts and of the womb.
* `Exo 20:4` "You shall not make for yourself any engraved image or any likeness of anything that is in heaven above, or that is in the earth *_beneath_*, or that is in the water under the earth.
* `Exo 26:24` And they shall be coupled together *_beneath_*, and they shall be coupled together above its head to one ring. Thus it shall be for them both. They shall be for the two corners.
* `Exo 27:5` And you shall put it under the compass of the altar *_beneath_* so that the net may be even to the midst of the altar.
* `Exo 28:33` And *_beneath_*, upon its hem you shall make pomegranates of blue, of purple, and of scarlet around its hem and bells of gold between them around it:
* `Exo 32:19` And it came to pass as soon as he came near the camp, that he saw the calf and the dancing. And Moses's anger waxed hot, and he cast the tablets from his hands and broke them *_beneath_* the mountain.
* `Exo 36:29` And they were coupled *_beneath_* and coupled together at the head thereof to one ring. Thus he did to both of them for both the corners.
* `Exo 38:4` And he made for the altar a brazen grate of net-work under its ledge around it *_beneath_*, up to the middle of it.
* `Deu 4:18` The likeness of anything that creeps on the ground, the likeness of any fish that is in the waters *_beneath_* the earth,
* `Deu 4:39` Know therefore this day, and consider it in your heart, that the LORD, he is God in heaven above and upon the earth *_beneath_*. There is no one else.
* `Deu 5:8` 'You shall not make for yourself any engraved image or any likeness of anything that is in heaven above, that is on the earth *_beneath_*, or that is in the waters *_beneath_* the earth.
* `Deu 28:13` And the LORD shall make you the head and not the tail. And you shall be above only and not *_beneath_* if you listen to the commandments of the LORD your God which I command you this day to observe and to do them.
* `Deu 33:13` And of Joseph he said, "Blessed of the LORD be his land for the precious things of heaven, for the dew, for the deep that couches *_beneath_*,
* `Jsh 2:11` And as soon as we had heard these things, our hearts melted, neither did there remain any more courage in any man, because of you, for the LORD your God, he is God in heaven above and in earth *_beneath_*.
* `Jdg 7:8` So the people took provisions in their hand and their trumpets. And he sent all the rest of Israel each to his tent and retained those three hundred men. And the host of Midian was *_beneath_* him in the valley.
* `1Ki 4:12` Baana the son of Ahilud—to him pertained Taanach, Megiddo, and all Beth-shean, which is by Zartanah *_beneath_* Jezreel, from Beth-shean to Abel-meholah, even to the place that is beyond Jokneam;
* `1Ki 7:29` And on the borders that were between the ledges were lions, oxen, and cherubim. And upon the ledges there was a base above, and *_beneath_* the lions and oxen were wreaths of hanging work.
* `1Ki 8:23` And he said, "LORD God of Israel, there is no God like you in heaven above or on earth *_beneath_*, who keeps covenant and mercy with your servants who walk before you with all their heart,
* `Job 18:16` His roots shall be dried up *_beneath_*, and his branch shall be cut off above.
* `Job 26:5` Those who are dead tremble *_beneath_* the waters and the inhabitants thereof.
* `Pro 15:24` The way of life is above to the wise so that he may depart from hell *_beneath_*.
* `Isa 14:9` Hell from *_beneath_* is moved for you to meet you at your coming. It stirs up the dead for you, even all the chief ones of the earth. It has raised up from their thrones all the kings of the nations.
* `Isa 51:6` Lift up your eyes to the heavens and look upon the earth *_beneath_*, for the heavens shall vanish away like smoke, the earth shall become old like a garment, and its inhabitants shall die in a like manner. But my salvation shall be forever, and my righteousness shall not be abolished.
* `Jer 31:37` Thus says the LORD: "If heaven above can be measured and the foundations of the earth searched out *_beneath_*, I will also cast off all the offspring of Israel for all that they have done," says the LORD.
* `Amo 2:9` Yet I destroyed the Amorite before them, whose height was like the height of the cedars and he was strong as the oaks, yet I destroyed his fruit from above and his roots from *_beneath_*.
* `Jhn 8:23` And he said to them, "You are from *_beneath_*. I am from above. You are of this world. I am not of this world.
* `Act 2:19` And I will show wonders in heaven above and signs on the earth *_beneath_*: blood, fire, and vapor of smoke.

_28 verses containing BENEATH_

== BENEFACTORS

* `Luk 22:25` And he said to them, "The kings of the Gentiles exercise lordship over them, and those who exercise authority upon them are called *_benefactors_*.

_1 verse containing BENEFACTORS_

== BENEFIT

* `2Ch 32:25` But Hezekiah did not recompense according to the *_benefit_* done to him, for his heart was lifted up. Therefore, there was wrath upon him and upon Judah and Jerusalem.
* `Jer 18:10` If it does evil in my sight so that it does not obey my voice, then I will repent of the good with which I said I would *_benefit_* them.
* `2Co 1:15` And in this confidence I purposed to come to you before so that you might have a second *_benefit_*,
* `1Ti 6:2` And those who have believing masters, let them not despise them because they are brothers, but rather do them service because they are faithful and beloved, partakers of the *_benefit_*. Teach and exhort these things.
* `Phm 1:14` But without your consent I would do nothing so that your *_benefit_* would not be according to necessity, but willingly.

_5 verses containing BENEFIT_

== BENEFITED

* `Job 41:11` Who has first *_benefited_* me that I should repay him? Whatever is under the whole heaven is mine.

_1 verse containing BENEFITED_

== BENEFITS

* `Psa 68:19` Blessed be the Lord who daily loads us with *_benefits_*, even the God of our salvation. [Selah.]
* `Psa 103:2` Bless the LORD, O my soul, and do not forget all his *_benefits_*.
* `Psa 116:12` What shall I render to the LORD for all his *_benefits_* toward me?

_3 verses containing BENEFITS_

== BENEVOLENCE

* `1Co 7:3` Let the husband render to the wife due *_benevolence_*, and likewise also the wife to the husband.

_1 verse containing BENEVOLENCE_

== BENINU

* `Neh 10:13` Hodijah, Bani, and *_Beninu_*.

_1 verse containing BENINU_

== BENJAMIN

* `Gen 35:18` And it came to pass as her soul was departing (for she died), that she called his name Ben-oni, but his father called him *_Benjamin_*.
* `Gen 35:24` The sons of Rachel: Joseph and *_Benjamin_*.
* `Gen 42:4` But *_Benjamin_*, Joseph's brother, Jacob did not send with his brothers, for he said, "Lest perhaps mischief befalls him."
* `Gen 42:36` And Jacob their father said to them, "You have bereaved me. Joseph is no more, Simeon is no more, and you will take *_Benjamin_* away. All these things are against me."
* `Gen 43:14` And may God Almighty give you mercy before the man so that he may send away your other brother and *_Benjamin_*. If I am bereaved, I am bereaved."
* `Gen 43:15` And the men took these presents, and they took double money in their hand and *_Benjamin_*, and arose, went down to Egypt, and stood before Joseph.
* `Gen 43:16` And when Joseph saw *_Benjamin_* with them, he said to the ruler of his house, "Bring these men home, and slay and make ready, for these men shall dine with me at noon."
* `Gen 43:29` And he lifted up his eyes and saw his brother *_Benjamin_*, his mother's son, and said, "Is this your younger brother of whom you spoke to me?" And he said, "May God be gracious to you, my son."
* `Gen 43:34` And he took and sent portions to them from before him, but *_Benjamin_*'s portion was five times as much as any of theirs. And they drank and were merry with him.
* `Gen 44:12` And he searched, beginning with the oldest and ending with the youngest. And the cup was found in *_Benjamin_*'s sack.
* `Gen 45:12` And behold, your eyes and the eyes of my brother *_Benjamin_* see that it is my mouth that speaks to you.
* `Gen 45:14` And he fell upon his brother *_Benjamin_*'s neck and wept, and *_Benjamin_* wept upon his neck.
* `Gen 45:22` To all of them he gave each man changes of clothing, but to *_Benjamin_* he gave three hundred pieces of silver and five changes of clothing.
* `Gen 46:19` The sons of Rachel Jacob's wife: Joseph and *_Benjamin_*.
* `Gen 46:21` And the sons of *_Benjamin_*: Belah, Becher, Ashbel, Gera, Naaman, Ehi, Rosh, Muppim, Huppim, and Ard.
* `Gen 49:27` "*_Benjamin_* is a ravenous wolf. In the morning he shall devour the prey, and at night he shall divide the plunder."
* `Exo 1:3` Issachar, Zebulun, *_Benjamin_*,
* `Num 1:11` Of *_Benjamin_*, Abidan the son of Gideoni;
* `Num 1:36` Of the children of *_Benjamin_*—by their generations, after their families, by the house of their fathers, according to the number of the names, from twenty years old and upward, all who were able to go forth to war—
* `Num 1:37` Those who were numbered of them, even of the tribe of *_Benjamin_*, were thirty-five thousand and four hundred.
* `Num 2:22` Then the tribe of *_Benjamin_*, and the captain of the sons of *_Benjamin_* shall be Abidan the son of Gideoni.
* `Num 7:60` On the ninth day Abidan the son of Gideoni, prince of the children of *_Benjamin_*, offered.
* `Num 10:24` And over the host of the tribe of the children of *_Benjamin_* was Abidan the son of Gideoni.
* `Num 13:9` Of the tribe of *_Benjamin_*, Palti the son of Raphu;
* `Num 26:38` The sons of *_Benjamin_* after their families: of Bela, the family of the Belaites; of Ashbel, the family of the Ashbelites; of Ahiram, the family of the Ahiramites;
* `Num 26:41` These are the sons of *_Benjamin_* after their families. And those who were numbered of them were forty-five thousand and six hundred.
* `Num 34:21` Of the tribe of *_Benjamin_*, Elidad the son of Chislon;
* `Deu 27:12` "These shall stand upon mount Gerizim to bless the people when you have come over the Jordan: Simeon, Levi, Judah, Issachar, Joseph, and *_Benjamin_*.
* `Deu 33:12` And of *_Benjamin_* he said, "The beloved of the LORD shall dwell in safety by him, and the LORD shall cover him all day long, and he shall dwell between his shoulders."
* `Jsh 18:11` And the lot of the tribe of the children of *_Benjamin_* came up according to their families. And the border of their lot came forth between the children of Judah and the children of Joseph.
* `Jsh 18:20` And the Jordan was its border on the east side. This was the inheritance of the children of *_Benjamin_*, according to its borders all around, according to their families.
* `Jsh 18:21` Now the cities of the tribe of the children of *_Benjamin_*, according to their families, were Jericho, Beth-hoglah, the valley of Keziz,
* `Jsh 18:28` Zelah, Eleph, Jebusi (which is Jerusalem), Gibeath, and Kirjath; fourteen cities with their villages. This is the inheritance of the children of *_Benjamin_* according to their families.
* `Jsh 21:4` And the lot came out for the families of the Kohathites. And the Levites who were the children of Aaron the priest had by lot out of the tribe of Judah, out of the tribe of Simeon, and out of the tribe of *_Benjamin_*, thirteen cities.
* `Jsh 21:17` And out of the tribe of *_Benjamin_*, Gibeon with its suburbs, Geba with its suburbs,
* `Jdg 1:21` And the children of *_Benjamin_* did not drive out the Jebusites who inhabited Jerusalem, but the Jebusites dwell with the children of *_Benjamin_* in Jerusalem to this day.
* `Jdg 5:14` Out of Ephraim there was a root of them against Amalek. After you was *_Benjamin_* among your people. Out of Machir governors came down, and out of Zebulun those who handle the pen of the writer.
* `Jdg 10:9` Moreover, the children of Ammon passed over the Jordan to fight also against Judah, against *_Benjamin_*, and against the house of Ephraim, so that Israel was greatly distressed.
* `Jdg 19:14` And they passed on and went their way. And the sun went down upon them when they were by Gibeah, which belongs to *_Benjamin_*.
* `Jdg 20:3` (Now the children of *_Benjamin_* heard that the children of Israel had gone up to Mizpeh.) Then the children of Israel said, "Tell us, how did this wickedness happen?"
* `Jdg 20:4` And the Levite, the husband of the woman who was slain, answered and said, "I came into Gibeah that belongs to *_Benjamin_*—my concubine and I—to lodge.
* `Jdg 20:10` And we will take ten men for one hundred throughout all the tribes of Israel, and one hundred for one thousand, and one thousand for ten thousand, to fetch provisions for the people, so that when they come to Gibeah of *_Benjamin_*, they may do according to all the folly that they have wrought in Israel."
* `Jdg 20:12` And the tribes of Israel sent men through all the tribe of *_Benjamin_*, saying, "What wickedness is this that is done among you?
* `Jdg 20:13` Now therefore, deliver us the men, the children of Belial, who are in Gibeah, so that we may put them to death and banish evil from Israel." But the children of *_Benjamin_* would not listen to the voice of their brothers, the children of Israel.
* `Jdg 20:14` But the children of *_Benjamin_* assembled out of the cities at Gibeah to go out to battle against the children of Israel.
* `Jdg 20:15` And the children of *_Benjamin_* were numbered at that time out of the cities twenty-six thousand men who drew the sword, besides the inhabitants of Gibeah, who were numbered seven hundred chosen men.
* `Jdg 20:17` And the men of Israel, besides *_Benjamin_*, were numbered four hundred thousand men who drew the sword. All these were men of war.
* `Jdg 20:18` And the children of Israel arose, went up to the house of God, and asked counsel of God and said, "Which of us shall go up first to the battle against the children of *_Benjamin_*?" And the LORD said, "Judah shall go up first."
* `Jdg 20:20` And the men of Israel went out to battle against *_Benjamin_*, and the men of Israel put themselves in array to fight against them at Gibeah.
* `Jdg 20:21` And the children of *_Benjamin_* came forth from Gibeah and destroyed down to the ground of the Israelites that day twenty-two thousand men.
* `Jdg 20:23` (And the children of Israel went up and wept before the LORD until evening and asked counsel of the LORD, saying, "Shall I go up again to battle against the children of *_Benjamin_* my brother?" And the LORD said, "Go up against him.")
* `Jdg 20:24` And the children of Israel came near against the children of *_Benjamin_* on the second day.
* `Jdg 20:25` And *_Benjamin_* went forth against them out of Gibeah on the second day and again destroyed down to the ground eighteen thousand men of the children of Israel. All these drew the sword.
* `Jdg 20:28` And Phinehas, the son of Eleazar, the son of Aaron, stood before it in those days), saying, "Shall I yet again go out to battle against the children of *_Benjamin_* my brother, or shall I cease?" And the LORD said, "Go up, for tomorrow I will deliver them into your hand."
* `Jdg 20:30` And the children of Israel went up against the children of *_Benjamin_* on the third day and put themselves in array against Gibeah, as at other times.
* `Jdg 20:31` And the children of *_Benjamin_* went out against the people and were drawn away from the city. And they began to smite the people as at other times, killing about thirty men of Israel in the highways, one of which goes up to the house of God and the other to Gibeah in the field.
* `Jdg 20:32` And the children of *_Benjamin_* said, "They are smitten down before us, as at the first." But the children of Israel said, "Let us flee and draw them from the city to the highways."
* `Jdg 20:35` And the LORD smote *_Benjamin_* before Israel. And the children of Israel destroyed twenty-five thousand and one hundred men of the Benjaminites that day. All these drew the sword.
* `Jdg 20:36` So the children of *_Benjamin_* saw that they were smitten, for the men of Israel gave place to the Benjaminites because they trusted in the ambushers which they had set beside Gibeah.
* `Jdg 20:39` And when the men of Israel retired in the battle, *_Benjamin_* began to smite and kill about thirty persons of the men of Israel. For they said, "Surely they are smitten down before us as in the first battle."
* `Jdg 20:41` And when the men of Israel turned back, the men of *_Benjamin_* were amazed, for they saw that evil had come upon them.
* `Jdg 20:44` And eighteen thousand men of *_Benjamin_* fell. All these were men of valor.
* `Jdg 20:46` So all who fell that day of *_Benjamin_* were twenty-five thousand men who drew the sword. All these were men of valor.
* `Jdg 20:48` And the men of Israel turned back upon the children of *_Benjamin_* and smote them with the edge of the sword—the men of every city, as well as the beast, and all that came to hand. They also set all the cities that they came to on fire.
* `Jdg 21:1` Now the men of Israel had sworn in Mizpeh, saying, "Not one of us shall give his daughter to *_Benjamin_* for a wife."
* `Jdg 21:6` And the children of Israel repented for *_Benjamin_* their brother and said, "There is one tribe cut off from Israel this day.
* `Jdg 21:13` And the whole congregation sent some to speak to the children of *_Benjamin_* who were in the rock of Rimmon and to call peaceably to them.
* `Jdg 21:14` And *_Benjamin_* came back at that time. And they gave them the women which they had saved alive from the women of Jabesh-gilead, yet they did not suffice them.
* `Jdg 21:15` And the people repented for *_Benjamin_*, because the LORD had made a breach in the tribes of Israel.
* `Jdg 21:16` Then the elders of the congregation said, "What shall we do for wives for those who remain, seeing the women are destroyed out of *_Benjamin_*?"
* `Jdg 21:17` And they said, "There must be an inheritance for the remnant of *_Benjamin_* so that a tribe is not destroyed out of Israel.
* `Jdg 21:18` However, we may not give them wives from our daughters, for the children of Israel have sworn, saying, 'Cursed is he who gives a wife to *_Benjamin_*.'"
* `Jdg 21:20` Therefore, they commanded the children of *_Benjamin_*, saying, "Go, lie in wait in the vineyards,
* `Jdg 21:21` And when you see the daughters of Shiloh come out to dance in dances, come out of the vineyards and each of you catch his wife from the daughters of Shiloh, and go to the land of *_Benjamin_*.
* `Jdg 21:23` And the children of *_Benjamin_* did so, and took wives, according to their number, from those who danced, whom they caught. And they went and returned to their inheritance and repaired the cities and dwelt in them.
* `1Sa 4:12` And there ran a man of *_Benjamin_* out of the army and came to Shiloh the same day with his clothes rent and with earth upon his head.
* `1Sa 9:1` Now there was a man of *_Benjamin_* whose name was Kish, the son of Abiel, the son of Zeror, the son of Bechorath, the son of Aphiah, a Benjaminite, a mighty man of power.
* `1Sa 9:16` "Tomorrow about this time I will send you a man out of the land of *_Benjamin_*, and you shall anoint him to be captain over my people Israel so that he may save my people from the hand of the Philistines. For I have looked upon my people because their cry has come to me."
* `1Sa 9:21` And Saul answered and said, "Am I not a Benjaminite from the smallest of the tribes of Israel? And is my family not the least of all the families of the tribe of *_Benjamin_*? Why then do you speak to me in this manner?"
* `1Sa 10:2` When you have departed from me today, you shall find two men by Rachel's sepulcher in the border of *_Benjamin_* at Zelzah, and they will say to you, 'The donkeys which you went to seek are found, and behold, your father has ceased caring for the donkeys and sorrows for you, saying, "What shall I do for my son?"'
* `1Sa 10:20` And when Samuel had caused all the tribes of Israel to come near, the tribe of *_Benjamin_* was taken.
* `1Sa 10:21` When he had caused the tribe of *_Benjamin_* to come near by their families, the family of Matri was taken, and Saul the son of Kish was taken. And when they sought him, he could not be found.
* `1Sa 13:2` Saul chose for himself three thousand men of Israel, of which two thousand were with Saul in Michmash and in the mountains of Beth-el, and one thousand were with Jonathan in Gibeah of *_Benjamin_*. And the rest of the people he sent each to his tent.
* `1Sa 13:15` And Samuel arose and went up from Gilgal to Gibeah of *_Benjamin_*. And Saul numbered the people who were present with him, about six hundred men.
* `1Sa 13:16` And Saul, Jonathan his son, and the people who were present with them stayed in Gibeah of *_Benjamin_*, but the Philistines encamped in Michmash.
* `1Sa 14:16` And the watchmen of Saul in Gibeah of *_Benjamin_* looked, and behold, the multitude melted away and they went on beating down one another.
* `2Sa 2:9` And he made him king over Gilead, over the Ashurites, over Jezreel, over Ephraim, over *_Benjamin_*, and over all Israel.
* `2Sa 2:15` Then there arose and went over by number twelve from *_Benjamin_*, who pertained to Ish-bosheth the son of Saul, and twelve from the servants of David.
* `2Sa 2:25` And the children of *_Benjamin_* assembled themselves after Abner, became one troop, and stood on the top of a hill.
* `2Sa 2:31` But the servants of David had smitten three hundred and sixty men of *_Benjamin_* and of Abner's men so that they died.
* `2Sa 3:19` And Abner also spoke in the ears of *_Benjamin_*. And Abner also went to speak in the ears of David in Hebron all that seemed good to Israel and that seemed good to the whole house of *_Benjamin_*.
* `2Sa 4:2` And Saul's son had two men who were captains of bands: the name of one was Baanah and the name of the other Rechab, the sons of Rimmon a Beerothite, of the children of *_Benjamin_* (for Beeroth also was reckoned to *_Benjamin_*,
* `2Sa 19:17` And there were one thousand men from *_Benjamin_* with him, along with Ziba the servant of the house of Saul and his fifteen sons and his twenty servants. And they went over the Jordan before the king.
* `2Sa 21:14` And the bones of Saul and Jonathan his son they buried in the country of *_Benjamin_* in Zelah in the sepulcher of Kish his father. And they performed all that the king commanded. And after that God was entreated for the land.
* `2Sa 23:29` Heleb the son of Baanah (a Netophathite), Ittai the son of Ribai out of Gibeah of the children of *_Benjamin_*,
* `1Ki 4:18` Shimei the son of Elah, in *_Benjamin_*;
* `1Ki 12:21` And when Rehoboam had come to Jerusalem, he assembled all the house of Judah with the tribe of *_Benjamin_*, one hundred and eighty thousand chosen men who were warriors, to fight against the house of Israel to bring the kingdom back to Rehoboam the son of Solomon.
* `1Ki 12:23` "Speak to Rehoboam the son of Solomon king of Judah, to all the house of Judah and *_Benjamin_*, and to the remnant of the people, saying,
* `1Ki 15:22` Then king Asa made a proclamation throughout all Judah. No one was exempted. And they took away the stones of Ramah and its timber, with which Baasha had built it, and king Asa built with them Geba of *_Benjamin_* and Mizpah.
* `1Ch 2:2` Dan, Joseph, *_Benjamin_*, Naphtali, Gad, and Asher.
* `1Ch 6:60` And out of the tribe of *_Benjamin_*: Geba with its suburbs, Alemeth with its suburbs, and Anathoth with its suburbs. All their cities throughout their families were thirteen cities.
* `1Ch 6:65` And they gave by lot out of the tribe of the children of Judah, out of the tribe of the children of Simeon, and out of the tribe of the children of *_Benjamin_*, these cities, which are called by their names.
* `1Ch 7:6` The sons of *_Benjamin_*: Bela, Becher, and Jediael, three.
* `1Ch 7:10` The son of Jediael: Bilhan. And the sons of Bilhan: Jeush, *_Benjamin_*, Ehud, Chenaanah, Zethan, Tarshish, and Ahishahar.
* `1Ch 8:1` Now *_Benjamin_* begot Bela his first-born, Ashbel the second, Aharah the third,
* `1Ch 8:40` And the sons of Ulam were mighty men of valor, archers, and had many sons and sons' sons numbering one hundred and fifty. All these are among the sons of *_Benjamin_*.
* `1Ch 9:3` And in Jerusalem dwelt some of the children of Judah, some of the children of *_Benjamin_*, and some of the children of Ephraim and Manasseh:
* `1Ch 9:7` And of the sons of *_Benjamin_*: Sallu the son of Meshullam, the son of Hodaviah, the son of Hasenuah,
* `1Ch 11:31` Ithai the son of Ribai of Gibeah who pertained to the children of *_Benjamin_*, Benaiah the Pirathonite,
* `1Ch 12:2` They were armed with bows and could use both the right hand and the left in hurling stones and shooting arrows from a bow. They were Saul's kinsmen from *_Benjamin_*.
* `1Ch 12:16` And there came some of the children of *_Benjamin_* and Judah to David at the hold.
* `1Ch 12:29` And of the children of *_Benjamin_*, the kindred of Saul, three thousand, for until now the greatest part of them had kept the ward of the house of Saul.
* `1Ch 21:6` But Levi and *_Benjamin_* he did not count among them, for the king's word was abominable to Joab.
* `1Ch 27:21` Of the half tribe of Manasseh in Gilead, Iddo the son of Zechariah; of *_Benjamin_*, Jaasiel the son of Abner;
* `2Ch 11:1` And when Rehoboam had come to Jerusalem, he gathered from the house of Judah and *_Benjamin_* one hundred and eighty thousand chosen men who were warriors to fight against Israel so that he might bring the kingdom back to Rehoboam.
* `2Ch 11:3` "Speak to Rehoboam the son of Solomon, king of Judah, and to all Israel in Judah and *_Benjamin_*, saying,
* `2Ch 11:10` Zorah, Ajalon, and Hebron, which are in Judah and in *_Benjamin_*, fortified cities.
* `2Ch 11:12` And in every single city he put shields and spears and made them exceedingly strong, having Judah and *_Benjamin_* on his side.
* `2Ch 11:23` And he dealt wisely and dispersed some of his children throughout all the countries of Judah and *_Benjamin_* to every fortified city, and he gave them provisions in abundance. And he desired many wives.
* `2Ch 14:8` And Asa had an army of three hundred thousand men out of Judah who bore bucklers and spears, and two hundred and eighty thousand out of *_Benjamin_* who bore shields and drew bows. All these were mighty men of valor.
* `2Ch 15:2` And he went out to meet Asa and said to him, "Hear me, Asa, and all Judah and *_Benjamin_*. The LORD is with you while you are with him. And if you seek him, he will be found by you, but if you forsake him, he will forsake you.
* `2Ch 15:8` And when Asa heard these words and the prophecy of Oded the prophet, he took courage and put away the abominable idols out of all the land of Judah and *_Benjamin_* and out of the cities which he had taken from mount Ephraim, and renewed the altar of the LORD that was before the porch of the LORD.
* `2Ch 15:9` And he gathered all Judah and *_Benjamin_* and the strangers with them out of Ephraim and Manasseh and out of Simeon, for they resorted to him out of Israel in multitudes when they saw that the LORD his God was with him.
* `2Ch 17:17` And of *_Benjamin_*: Eliada a mighty man of valor, and with him two hundred thousand armed men with bow and shield;
* `2Ch 25:5` Moreover, Amaziah assembled Judah and made them captains over thousands and captains over hundreds, according to the houses of their fathers, throughout all Judah and *_Benjamin_*. And he numbered them from twenty years old and above and found them to be three hundred thousand choice men, able to go forth to war, who could handle spear and shield.
* `2Ch 31:1` Now when all this was finished, all Israel who were present went out to the cities of Judah and broke the images in pieces, cut down the groves, and threw down the high places and the altars out of all Judah, *_Benjamin_*, Ephraim, and Manasseh until they had utterly destroyed them all. Then all the children of Israel each returned to his possession into their own cities.
* `2Ch 34:9` And when they came to Hilkiah the high priest, they delivered the money that was brought into the house of God, which the Levites who kept the doors had collected from the hand of Manasseh and Ephraim, from all the remnant of Israel, from all Judah and *_Benjamin_*, and from the inhabitants of Jerusalem.
* `2Ch 34:32` And he caused all who were present in Jerusalem and *_Benjamin_* to stand to it. And the inhabitants of Jerusalem did according to the covenant of God, the God of their fathers.
* `Ezr 1:5` Then arose the chief of the fathers of Judah and *_Benjamin_*, the priests, and the Levites, with all whose spirit God had raised, to go up to build the house of the LORD which is in Jerusalem.
* `Ezr 4:1` Now when the adversaries of Judah and *_Benjamin_* heard that the children of the captivity were building the temple to the LORD God of Israel,
* `Ezr 10:9` Then all the men of Judah and *_Benjamin_* assembled at Jerusalem within three days. It was the ninth month, and the twentieth day of the month. And all the people sat in the street of the house of God, trembling because of this matter and because of the great rain.
* `Ezr 10:32` *_Benjamin_*, Malluch, and Shemariah.
* `Neh 3:23` After him *_Benjamin_* and Hashub repaired over against their house. After him Azariah the son of Maaseiah, the son of Ananiah, repaired by his house.
* `Neh 11:4` And some of the children of Judah and some of the children of *_Benjamin_* dwelt at Jerusalem. Of the children of Judah: Athaiah the son of Uzziah, the son of Zechariah, the son of Amariah, the son of Shephatiah, the son of Mahalaleel, of the children of Perez;
* `Neh 11:7` And these are the sons of *_Benjamin_*: Sallu the son of Meshullam, the son of Joed, the son of Pedaiah, the son of Kolaiah, the son of Maaseiah, the son of Ithiel, the son of Jesaiah;
* `Neh 11:31` The children of *_Benjamin_* also dwelt from Geba, at Michmash, Aija, and Beth-el, and in their villages,
* `Neh 11:36` And some divisions of the Levites in Judah were joined to *_Benjamin_*.
* `Neh 12:34` Judah, *_Benjamin_*, Shemaiah, Jeremiah,
* `Psa 68:27` There is the youngest, *_Benjamin_*, with their ruler, the princes of Judah and their counsel, the princes of Zebulun, and the princes of Naphtali.
* `Psa 80:2` Before Ephraim and *_Benjamin_* and Manasseh, stir up your strength and come and save us.
* `Jer 1:1` [The words of Jeremiah the son of Hilkiah, of the priests who were in Anathoth in the land of *_Benjamin_*,
* `Jer 6:1` "O children of *_Benjamin_*, gather yourselves to flee out of the midst of Jerusalem, blow the trumpet in Tekoa, and set up a sign of fire in Beth-haccerem, for evil appears out of the north, even great destruction.
* `Jer 17:26` And they shall come from the cities of Judah, from the places around Jerusalem, from the land of *_Benjamin_*, from the plain, from the mountains, and from the south, bringing burnt-offerings, sacrifices, food-offerings, and incense, and bringing sacrifices of praise to the house of the LORD.
* `Jer 20:2` Then Pashur struck Jeremiah the prophet and put him in the stocks that were in the high gate of *_Benjamin_*, which was by the house of the LORD.
* `Jer 32:8` So Hanameel my uncle's son came to me in the court of the prison, according to the word of the LORD, and said to me, 'Buy my field, I pray you, that is in Anathoth, which is in the country of *_Benjamin_*, for the right of inheritance is yours and the redemption is yours. Buy it for yourself.' Then I knew that this was the word of the LORD.
* `Jer 32:44` Men shall buy fields for money, sign evidences and seal them, and take witnesses in the land of *_Benjamin_*, in the places around Jerusalem, in the cities of Judah, in the cities of the mountains, in the cities of the valley, and in the cities of the south, for I will cause their captivity to return,' says the LORD."
* `Jer 33:13` In the cities of the mountains, in the cities of the valley, in the cities of the south, in the land of *_Benjamin_*, in the places around Jerusalem, and in the cities of Judah, the flocks shall pass again under the hands of him who counts them,' says the LORD.
* `Jer 37:12` Jeremiah went out of Jerusalem to go into the land of *_Benjamin_* to separate himself from there in the midst of the people.
* `Jer 37:13` And when he was in the gate of *_Benjamin_*, a captain of the ward was there, whose name was Irijah, the son of Shelemiah, the son of Hananiah, and he took Jeremiah the prophet, saying, "You are falling away to the Chaldeans."
* `Jer 38:7` Now when Ebed-melech the Cushite, one of the eunuchs who was in the king's house, heard that they had put Jeremiah in the dungeon (the king was sitting in the gate of *_Benjamin_*),
* `Ezk 48:22` Moreover, from the possession of the Levites and from the possession of the city, being in the midst of that which is the prince's, between the border of Judah and the border of *_Benjamin_*, shall be for the prince.
* `Ezk 48:23` "As for the rest of the tribes, from the east side to the west side, *_Benjamin_* shall have a portion.
* `Ezk 48:24` And by the border of *_Benjamin_*, from the east side to the west side, Simeon shall have a portion.
* `Ezk 48:32` And on the east side four thousand and five hundred, with three gates: the gate of Joseph, one; the gate of *_Benjamin_*, one; the gate of Dan, one.
* `Hos 5:8` Blow the horn in Gibeah and the trumpet in Ramah. Cry aloud at Beth-aven, 'Behind you, O *_Benjamin_*.'
* `Oba 1:19` And those of the south shall possess the mountain of Esau, and those of the plain, the Philistines. And they shall possess the fields of Ephraim and the fields of Samaria. And *_Benjamin_* shall possess Gilead.
* `Zch 14:10` All the land shall be turned into a plain from Geba to Rimmon, south of Jerusalem. And it shall be lifted up and inhabited in her place, from *_Benjamin_*'s gate to the place of the first gate, to the corner gate, and from the tower of Hananeel to the king's wine-presses.
* `Act 13:21` And afterward, they desired a king, and God gave Saul the son of Kish to them, a man of the tribe of *_Benjamin_*, for forty years.
* `Rom 11:1` I say then, has God cast away his people? By no means. For I also am an Israelite, of the offspring of Abraham, of the tribe of *_Benjamin_*.
* `Phl 3:5` Circumcised the eighth day, of the stock of Israel, of the tribe of *_Benjamin_*, a Hebrew of the Hebrews; with respect to the law, a Pharisee;
* `Rev 7:8` Of the tribe of Zebulun, twelve thousand were sealed. Of the tribe of Joseph, twelve thousand were sealed. Of the tribe of *_Benjamin_*, twelve thousand were sealed.

_161 verses containing BENJAMIN_

== BENJAMINITE

* `Jdg 3:15` But when the children of Israel cried to the LORD, the LORD raised up for them a deliverer: Ehud the son of Gera, a *_Benjaminite_*, a left-handed man. And by him the children of Israel sent a tribute to Eglon king of Moab.
* `1Sa 9:1` Now there was a man of Benjamin whose name was Kish, the son of Abiel, the son of Zeror, the son of Bechorath, the son of Aphiah, a *_Benjaminite_*, a mighty man of power.
* `1Sa 9:21` And Saul answered and said, "Am I not a *_Benjaminite_* from the smallest of the tribes of Israel? And is my family not the least of all the families of the tribe of Benjamin? Why then do you speak to me in this manner?"
* `2Sa 16:11` And David said to Abishai and to all his servants, "Behold, my son who came forth from my body seeks my life. How much more now may this *_Benjaminite_* do it? Leave him alone and let him curse, for the LORD has bidden him.
* `2Sa 19:16` And Shimei the son of Gera, a *_Benjaminite_* who was from Bahurim, hastened and came down with the men of Judah to meet king David.
* `2Sa 20:1` And there happened to be a man of Belial there whose name was Sheba, the son of Bichri, a *_Benjaminite_*. And he blew a trumpet and said, "We have no part in David, neither do we have inheritance in the son of Jesse. Every man to his tents, O Israel."
* `1Ki 2:8` And behold, you have with you Shimei the son of Gera, a *_Benjaminite_* of Bahurim, who cursed me with a grievous curse in the day when I went to Mahanaim. But he came down to meet me at the Jordan, and I swore to him by the LORD, saying, 'I will not put you to death with the sword.'
* `Est 2:5` Now in the palace of Shushan there was a certain Jew, whose name was Mordecai, the son of Jair, the son of Shimei, the son of Kish, a *_Benjaminite_*,
* `Psa 7:1` [Shiggaion of David: which he sang to the LORD concerning the words of Cush the *_Benjaminite_*.] O LORD my God, I put my trust in you. Save me from all those who persecute me, and deliver me,

_9 verses containing BENJAMINITE_

== BENJAMINITES

* `Jdg 19:16` And behold, there came an old man from his work out of the field at evening, who was also of mount Ephraim, and he dwelt in Gibeah. But the men of the place were *_Benjaminites_*.
* `Jdg 20:35` And the LORD smote Benjamin before Israel. And the children of Israel destroyed twenty-five thousand and one hundred men of the *_Benjaminites_* that day. All these drew the sword.
* `Jdg 20:36` So the children of Benjamin saw that they were smitten, for the men of Israel gave place to the *_Benjaminites_* because they trusted in the ambushers which they had set beside Gibeah.
* `Jdg 20:40` But when the flame began to rise from the city with a pillar of smoke, the *_Benjaminites_* looked behind them, and behold, the flame of the city ascended to heaven.
* `Jdg 20:43` So they enclosed the *_Benjaminites_* on all sides and chased them and trod them down with ease over against Gibeah toward the sunrise.
* `1Sa 9:4` And he passed through mount Ephraim and passed through the land of Shalisha, but they did not find them. Then they passed through the land of Shalim, and they were not there. And he passed through the land of the *_Benjaminites_*, but they did not find them.
* `1Sa 22:7` Saul said to his servants who stood around him, "Hear now, you *_Benjaminites_*. Will the son of Jesse give every one of you fields and vineyards and make you all captains of thousands and captains of hundreds?
* `1Ch 27:12` The ninth captain for the ninth month was Abiezer the Anetothite, of the *_Benjaminites_*. And in his course were twenty-four thousand.

_8 verses containing BENJAMINITES_

== BENO

* `1Ch 24:26` The sons of Merari were Mahli and Mushi. The son of Jaaziah: *_Beno_*.
* `1Ch 24:27` The sons of Merari by Jaaziah: *_Beno_*, Shoham, Zaccur, and Ibri.

_2 verses containing BENO_

== BENT

* `Psa 7:12` If he does not turn, he will whet his sword. He has *_bent_* his bow and made it ready.
* `Psa 37:14` The wicked have drawn out the sword and *_bent_* their bow to cast down the poor and needy and to slay those who are of upright deportment.
* `Isa 5:28` Whose arrows are sharp and all their bows *_bent_*, their horses' hooves shall be counted like flint and their wheels like a whirlwind.
* `Isa 21:15` For they fled from the swords, from the drawn sword, from the *_bent_* bow, and from the grievousness of war.
* `Lam 2:4` [DALET] He has *_bent_* his bow like an enemy. He stood with his right hand as an adversary and slew all who were pleasant to the eye in the tabernacle of the daughter of Zion. He poured out his fury like fire.
* `Lam 3:12` He has *_bent_* his bow and set me as a mark for the arrow.
* `Ezk 17:7` "There was also another great eagle with great wings and many feathers, and behold, this vine *_bent_* its roots toward him and shot forth its branches toward him, so that he might water it by the furrows of its plantation.
* `Hos 11:4` I drew them with cords of a man, with ropes of love. And I was to them as those who take off the yoke from their jaws, and I *_bent_* down to them and fed them.
* `Hos 11:7` And my people are *_bent_* to backsliding from me. Though they called to the most High, no one at all would exalt him.
* `Zch 9:13` When I have *_bent_* Judah for me, filled the bow with Ephraim, and raised up your sons, O Zion, against your sons, O Greece, and made you like the sword of a mighty man.

_10 verses containing BENT_

== BENZOHETH

* `1Ch 4:20` And the sons of Shimon were Amnon, Rinnah, Ben-hanan, and Tilon. And the sons of Ishi were Zoheth and *_Benzoheth_*.

_1 verse containing BENZOHETH_

== BEON

* `Num 32:3` "Ataroth, Dibon, Jazer, Nimrah, Heshbon, Elealeh, Shebam, Nebo, and *_Beon_*,

_1 verse containing BEON_

== BEOR

* `Gen 36:32` And Bela the son of *_Beor_* reigned in Edom, and the name of his city was Dinhabah.
* `Num 22:5` He sent messengers therefore to Balaam the son of *_Beor_* at Pethor, which is by the river of the land of the children of his people, to call him, saying, "Behold, a people has come out from Egypt. Behold, they cover the face of the earth and abide over against me.
* `Num 24:3` And he took up his parable and said, "Balaam the son of *_Beor_* has said, and the man whose eyes are open has said,
* `Num 24:15` And he took up his parable and said, "Balaam the son of *_Beor_* has said, and the man whose eyes are open has said,
* `Num 31:8` And they slew the kings of Midian, besides the rest of those who were slain, namely, Evi, Rekem, Zur, Hur, and Reba, five kings of Midian. Balaam the son of *_Beor_* they also slew with the sword.
* `Deu 23:4` Because they did not meet you with bread and with water on the way when you came forth from Egypt, and because they hired against you Balaam the son of *_Beor_* from Pethor of Mesopotamia to curse you.
* `Jsh 13:22` Balaam the son of *_Beor_*, the soothsayer, the children of Israel also slayed with the sword, among those who were slain by them.
* `Jsh 24:9` Then Balak the son of Zippor, king of Moab, arose and warred against Israel, and sent and called Balaam the son of *_Beor_* to curse you.
* `1Ch 1:43` Now these are the kings who reigned in the land of Edom before any king reigned over the children of Israel: Bela the son of *_Beor_*, and the name of his city was Dinhabah.
* `Mic 6:5` O my people, remember now what Balak king of Moab consulted, and what Balaam the son of *_Beor_* answered him, [and what I did] from Shittim to Gilgal, so that you may know the righteousness of the LORD."
* `2Pe 2:15` They have forsaken the right way and gone astray, following the way of Balaam the son of *_Beor_*, who loved the wages of unrighteousness,

_11 verses containing BEOR_

== BERA

* `Gen 14:2` That these made war with *_Bera_* king of Sodom, Birsha king of Gomorrah, Shinab king of Admah, Shemeber king of Zeboiim, and the king of Bela, which is Zoar.

_1 verse containing BERA_

== BERACHAH

* `1Ch 12:3` The chief was Ahiezer, then Joash (the sons of Shemaah the Gibeathite), and Jeziel and Pelet (the sons of Azmaveth), and *_Berachah_* and Jehu the Antothite,
* `2Ch 20:26` And on the fourth day they assembled themselves in the valley of *_Berachah_*, for there they blessed the LORD. Therefore, the name of the same place has been called The Valley of *_Berachah_* to this day.

_2 verses containing BERACHAH_

== BERAIAH

* `1Ch 8:21` Adaiah, *_Beraiah_*, and Shimrath were the sons of Shimhi.

_1 verse containing BERAIAH_

== BEREA

* `Act 17:10` And the brothers immediately sent away Paul and Silas by night to *_Berea_*, who, coming there, went into the synagogue of the Jews.
* `Act 17:13` But when the Jews of Thessalonica had knowledge that the word of God was preached by Paul at *_Berea_*, they came there also and stirred up the people.
* `Act 20:4` And these accompanied him into Asia: Sopater from *_Berea_*, Aristarchus and Secundus from Thessalonica, Gaius from Derbe, Timothy, and Tychicus and Trophimus from Asia.

_3 verses containing BEREA_

== BEREAVE

* `Ecc 4:8` There is one alone, and there is not a second, and he has neither child nor brother. Yet there is no end of all his labor, neither is his eye satisfied with riches, neither does he say, "For whom do I labor and *_bereave_* my soul of good?" This is also vanity. It is even a grievous labor.
* `Jer 15:7` And I will fan them with a fan in the gates of the land. I will *_bereave_* them of children. I will destroy my people, since they do not return from their ways.
* `Ezk 5:17` Thus I will send upon you famine and evil beasts, and they shall *_bereave_* you. Pestilence and blood shall pass through you, and I will bring the sword upon you. I, the LORD, have spoken it.'"
* `Ezk 36:12` I will even cause men to walk upon you, even my people Israel. And they shall possess you, and you shall be their inheritance. And you shall no more from now on *_bereave_* them of men."
* `Ezk 36:14` Therefore you shall no longer devour men, neither *_bereave_* your nations anymore," says the Lord GOD.
* `Hos 9:12` Though they bring up their children, yet I will *_bereave_* them so that there shall not be a man left. Indeed, woe also to them when I depart from them!

_6 verses containing BEREAVE_

== BEREAVED

* `Gen 42:36` And Jacob their father said to them, "You have *_bereaved_* me. Joseph is no more, Simeon is no more, and you will take Benjamin away. All these things are against me."
* `Gen 43:14` And may God Almighty give you mercy before the man so that he may send away your other brother and Benjamin. If I am *_bereaved_*, I am *_bereaved_*."
* `Jer 18:21` Therefore, deliver their children to the famine and pour out their blood by the force of the sword, let their wives be *_bereaved_* of their children and be widows, and let their men be put to death and their young men be slain by the sword in battle.
* `Ezk 36:13` 'Thus says the Lord GOD: "Because they say to you, 'You devour men and have *_bereaved_* your nations,'
* `Hos 13:8` I will meet them like a bear that is *_bereaved_* of her whelps and will rend the enclosure of their heart. And there I will devour them like a lion. The wild beast shall tear them.

_5 verses containing BEREAVED_

== BEREAVES

* `Lam 1:20` [RESH] Behold, O LORD, for I am in distress. My heart is troubled. My heart is turned within me, for I have grievously rebelled. Abroad the sword *_bereaves_*, at home it is as death.

_1 verse containing BEREAVES_

== BEREAVING

* `Psa 35:12` They rewarded me evil for good to the *_bereaving_* of my soul.

_1 verse containing BEREAVING_

== BERECHIAH

* `1Ch 3:20` And Hashubah, Ohel, *_Berechiah_*, Hasadiah, and Jushab-hesed, five.
* `1Ch 6:39` And his brother Asaph who stood on his right hand, even Asaph the son of *_Berechiah_*, the son of Shimea,
* `1Ch 9:16` And Obadiah the son of Shemaiah, the son of Galal, the son of Jeduthun; and *_Berechiah_* the son of Asa, the son of Elkanah, who dwelt in the villages of the Netophathites.
* `1Ch 15:17` So the Levites appointed Heman the son of Joel; and of his brothers, Asaph the son of *_Berechiah_*; and of the sons of Merari their brothers, Ethan the son of Kushaiah;
* `1Ch 15:23` And *_Berechiah_* and Elkanah were door-keepers for the ark.
* `2Ch 28:12` Then some of the heads of the children of Ephraim, Azariah the son of Johanan, *_Berechiah_* the son of Meshillemoth, Jehizkiah the son of Shallum, and Amasa the son of Hadlai, stood up against those who came from the war.
* `Neh 3:4` And next to them Meremoth the son of Urijah, the son of Koz, repaired. And next to them Meshullam the son of *_Berechiah_*, the son of Meshezabeel, repaired. And next to them Zadok the son of Baana repaired.
* `Neh 3:30` After him Hananiah the son of Shelemiah and Hanun the sixth son of Zalaph repaired another piece. After him Meshullam the son of *_Berechiah_* repaired over against his chamber.
* `Neh 6:18` For there were many in Judah bound by oath to him because he was the son-in-law of Shechaniah the son of Arah, and his son Johanan had taken the daughter of Meshullam the son of *_Berechiah_*.

_9 verses containing BERECHIAH_

== BERED

* `Gen 16:14` Therefore, the well was called Beer-la-hai-roi. Behold, it is between Kadesh and *_Bered_*.
* `1Ch 7:20` And the sons of Ephraim: Shuthelah, *_Bered_* his son, Tahath his son, Eladah his son, Tahath his son,

_2 verses containing BERED_

== BERI

* `1Ch 7:36` The sons of Zophah: Suah, Harnepher, Shual, *_Beri_*, Imrah,

_1 verse containing BERI_

== BERIAH

* `Gen 46:17` And the sons of Asher: Jimnah, Ishuah, Isui, and *_Beriah_*. Serah was their sister. And the sons of *_Beriah_*: Heber and Malchiel.
* `Num 26:44` Of the children of Asher after their families: of Jimna, the family of the Jimnites; of Jesui, the family of the Jesuites; of *_Beriah_*, the family of the Beriites.
* `Num 26:45` Of the sons of *_Beriah_*: of Heber, the family of the Heberites; of Malchiel, the family of the Malchielites.
* `1Ch 7:23` And when he went in to his wife, she conceived and bore a son, and he called his name *_Beriah_* because it went evil with his house.
* `1Ch 7:30` The sons of Asher: Imnah, Isuah, Ishua, and *_Beriah_*. Serah was their sister.
* `1Ch 7:31` And the sons of *_Beriah_*: Heber and Malchiel, who is the father of Birzavith.
* `1Ch 8:13` *_Beriah_* and Shema (who were heads of the fathers of the inhabitants of Ajalon, who drove away the inhabitants of Gath),
* `1Ch 8:16` Michael, Ispah, and Joha were the sons of *_Beriah_*.
* `1Ch 23:10` And the sons of Shimei were Jahath, Zina, Jeush and *_Beriah_*. These four were the sons of Shimei.
* `1Ch 23:11` And Jahath was the chief and Zizah the second, but Jeush and *_Beriah_* did not have many sons; therefore, they were in one reckoning according to their father's house.

_10 verses containing BERIAH_

== BERIITES

* `Num 26:44` Of the children of Asher after their families: of Jimna, the family of the Jimnites; of Jesui, the family of the Jesuites; of Beriah, the family of the *_Beriites_*.

_1 verse containing BERIITES_

== BERITES

* `2Sa 20:14` And he went through all the tribes of Israel to Abel of Beth-maachah and all the *_Berites_*. And they were assembled and also went after him.

_1 verse containing BERITES_

== BERITH

* `Jdg 8:33` And it came to pass as soon as Gideon was dead, that the children of Israel turned back and went astray after Baalim and made Baal-*_berith_* their god.
* `Jdg 9:4` And they gave him seventy pieces of silver out of the house of Baal-*_berith_*, with which Abimelech hired vain and light persons who followed him.
* `Jdg 9:46` And when all the men of the tower of Shechem heard that, they entered into a hold of the house of the god *_Berith_*.

_3 verses containing BERITH_

== BERNICE

* `Act 25:13` And after some days, king Agrippa and *_Bernice_* came to Caesarea to salute Festus.
* `Act 25:23` So on the next day, Agrippa and *_Bernice_* had come with great pomp and had entered into the place of hearing with the chief captains and principal men of the city. And at the command of Festus, Paul was brought forth.
* `Act 26:30` And when he had said this, the king rose, along with the governor, *_Bernice_*, and those who sat with them.

_3 verses containing BERNICE_

== BERODACH-BALADAN

* `2Ki 20:12` At that time *_Berodach-baladan_*, the son of Baladan, king of Babylon, sent letters and a present to Hezekiah, for he had heard that Hezekiah had been sick.

_1 verse containing BERODACH-BALADAN_

== BEROTHAH

* `Ezk 47:16` Hamath, *_Berothah_*, Sibraim, which is between the border of Damascus and the border of Hamath; Hazar-hatticon, which is by the border of Hauran.

_1 verse containing BEROTHAH_

== BEROTHAI

* `2Sa 8:8` And from Betah and from *_Berothai_*, cities of Hadadezer, king David took an exceeding amount of brass.

_1 verse containing BEROTHAI_

== BEROTHITE

* `1Ch 11:39` Zelek the Ammonite, Naharai the *_Berothite_*—the armor-bearer of Joab the son of Zeruiah,

_1 verse containing BEROTHITE_

== BERRIES

* `Isa 17:6` Yet gleaning grapes shall be left in it, like the shaking of an olive-tree—two or three *_berries_* in the top of the uppermost bough, four or five in its outermost fruitful branches," says the LORD God of Israel.
* `Jms 3:12` Can the fig-tree, my brothers, bear olive-*_berries_*, or a vine, figs? In the same manner no fountain can yield both salt and fresh water.

_2 verses containing BERRIES_

== BERYL

* `Exo 28:20` And the fourth row a *_beryl_*, an onyx, and a jasper. They shall be set in gold in their enclosings.
* `Exo 39:13` And the fourth row, a *_beryl_*, an onyx, and a jasper. They were enclosed in settings of gold in their enclosings.
* `Sos 5:14` His hands are like gold rings set with the *_beryl_*. His belly is like bright ivory overlaid with sapphires.
* `Ezk 1:16` The appearance of the wheels and their work was like the color of a *_beryl_*. And the four of them had one likeness. And their appearance and their work was like a wheel in the middle of a wheel.
* `Ezk 10:9` And when I looked, behold, the four wheels by the cherubim, one wheel by one cherub and another wheel by another cherub. And the appearance of the wheels was like the color of a *_beryl_* stone.
* `Ezk 28:13` You have been in Eden the garden of God. Every precious stone was your covering: the sardius, topaz, the diamond, the *_beryl_*, the onyx, the jasper, the sapphire, the emerald, the carbuncle, and gold. The workmanship of your tambourines and of your pipes was prepared in you in the day that you were created.
* `Dan 10:6` His body was also like *_beryl_*, his face as the appearance of lightning, his eyes as lamps of fire, his arms and his feet like the appearance of polished brass, and the voice of his words like the voice of a multitude.
* `Rev 21:20` The fifth, sardonyx; the sixth, sardius; the seventh, chrysolite; the eighth, *_beryl_*; the ninth, a topaz; the tenth, a chrysoprase; the eleventh, a jacinth; and the twelfth, an amethyst.

_8 verses containing BERYL_

== BESAI

* `Ezr 2:49` The children of Uzza, the children of Paseah, the children of *_Besai_*,
* `Neh 7:52` The children of *_Besai_*, the children of Meunim, the children of Nephishesim,

_2 verses containing BESAI_

== BESET

* `Jdg 19:22` Now as they were making their hearts merry, behold, the men of the city, some sons of Belial, *_beset_* the house on all sides and beat at the door and spoke to the master of the house, the old man, saying, "Bring forth the man who came into your house so that we may know him."
* `Psa 139:5` You have *_beset_* me behind and before and laid your hand upon me.
* `Hos 7:2` And they do not consider in their hearts that I remember all their wickedness. Now their own doings have *_beset_* them around. They are before my face.

_3 verses containing BESET_

== BESETS

* `Heb 12:1` Therefore, seeing we also are encompassed with so great a cloud of witnesses, let us lay aside every weight and the sin which so easily *_besets_* us, and let us run with patience the race that is set before us,

_1 verse containing BESETS_

== BESIDE

* `Gen 48:7` And as for me, when I came from Padan, Rachel died *_beside_* me in the land of Canaan, on the way when there was only a little distance to come to Ephrath, and I buried her there on the way of Ephrath (the same is Beth-lehem)."
* `Exo 14:9` But the Egyptians pursued them (all the horses and chariots of Pharaoh, his horsemen, and his army) and overtook them encamping by the sea, *_beside_* Pi-hahiroth, before Baal-zephon.
* `Exo 29:12` And you shall take some of the blood of the bull and put it upon the horns of the altar with your finger, and pour all the blood *_beside_* the bottom of the altar.
* `Lev 1:16` And he shall pluck away its crop with its feathers and cast it *_beside_* the altar on the east part by the place of the ashes.
* `Lev 6:10` And the priest shall put on his linen garment and put his linen breeches on his body. And he shall take up the ashes which the fire has consumed with the burnt-offering on the altar and put them *_beside_* the altar.
* `Lev 9:17` And he brought the food-offering, took a handful of it, and burnt it upon the altar *_beside_* the burnt-sacrifice of the morning.
* `Lev 10:12` And Moses spoke to Aaron and to Eleazar and Ithamar, his sons who were left, "Take the food-offering that remains of the offerings of the LORD made by fire and eat it without leaven *_beside_* the altar, for it is most holy.
* `Lev 23:38` *_Beside_* the sabbaths of the LORD, *_beside_* your gifts, *_beside_* all your vows, and *_beside_* all your voluntary-offerings which you give to the LORD.
* `Num 24:6` Like the valleys they are spread forth, like gardens by the river's side, like the trees of lign-aloes which the LORD has planted, and like cedar-trees *_beside_* the waters.
* `Deu 11:30` Are they not on the other side of the Jordan, by the way where the sun goes down in the land of the Canaanites who dwell in the plain over against Gilgal *_beside_* the plains of Moreh?
* `Jsh 3:16` The waters which came down from above stood and rose up in a heap very far from the city of Adam, that is *_beside_* Zaretan, and those which came down toward the sea of the plain, even the Salt Sea, failed, and were cut off. And the people passed through over against Jericho.
* `Jsh 7:2` And Joshua sent men from Jericho to Ai, which is *_beside_* Beth-aven, on the east side of Beth-el, and spoke to them, saying, "Go up and view the country." And the men went up and viewed Ai.
* `Jsh 12:9` The king of Jericho one; the king of Ai, which is *_beside_* Beth-el, one;
* `Jsh 13:4` From the south all the land of the Canaanites, and Mearah that is *_beside_* the Sidonians, to Aphek to the borders of the Amorites;
* `Jdg 6:37` Behold, I will put a fleece of wool on the floor. And if the dew is on the fleece only, and it is dry upon all the earth *_beside_* it, then I shall know that you will save Israel by my hand, as you have said."
* `Jdg 7:1` Then Jerubbaal (who is Gideon) and all the people who were with him rose early and encamped *_beside_* the well of Harod. And the host of the Midianites were on the north side of them in the valley by the hill of Moreh.
* `Jdg 20:36` So the children of Benjamin saw that they were smitten, for the men of Israel gave place to the Benjaminites because they trusted in the ambushers which they had set *_beside_* Gibeah.
* `Rth 2:14` And Boaz said to her, "At meal-time, come here and eat some of the bread and dip your morsel in the vinegar." And she sat *_beside_* the reapers, and he gave her parched grain, and she ate, was satisfied, and had some left over.
* `1Sa 4:1` And the word of Samuel came to all Israel. Now Israel went out against the Philistines to battle and encamped *_beside_* Eben-ezer. And the Philistines encamped in Aphek.
* `1Sa 19:3` And I will go out and stand *_beside_* my father in the field where you are and I will speak with my father about you. And what I see, that I will tell you."
* `2Sa 13:23` And it came to pass after two full years, that Absalom had sheep-shearers in Baal-hazor, which is *_beside_* Ephraim, and Absalom invited all the king's sons.
* `2Sa 15:2` And Absalom rose early and stood *_beside_* the way of the gate. And it was so, that when any man who had a controversy came to the king for judgment, Absalom called to him and said, "Of what city are you?" And he said, "Your servant is one of the tribes of Israel."
* `1Ki 3:20` And she arose at midnight and took my son from *_beside_* me while your servant slept. She laid it in her bosom and laid her dead child in my bosom.
* `1Ki 9:26` And king Solomon made a navy of ships in Ezion-geber, which is *_beside_* Eloth, on the shore of the Red Sea in the land of Edom.
* `1Ki 10:19` The throne had six steps, and the top of the throne was round and behind it. And there were stays on either side on the place of the seat, and two lions stood *_beside_* the stays.
* `1Ki 13:31` And it came to pass after he had buried him, that he spoke to his sons, saying, "When I am dead, bury me in the sepulcher in which the man of God is buried. Lay my bones *_beside_* his bones.
* `2Ki 12:9` But Jehoiada the priest took a chest, bored a hole in its lid, and set it *_beside_* the altar, on the right side as one comes into the house of the LORD. And the priests who kept the door put in it all the money that was brought into the house of the LORD.
* `2Ch 26:19` Then Uzziah was angry and had a censer in his hand to burn incense. And while he was angry with the priests, the leprosy even rose up in his forehead before the priests in the house of the LORD, from *_beside_* the incense altar.
* `Neh 8:4` And Ezra the scribe stood upon a pulpit of wood, which they had made for this purpose. And *_beside_* him stood Mattithiah, Shema, Anaiah, Urijah, Hilkiah, and Maaseiah on his right hand, and on his left hand, Pedaiah, Mishael, Malchiah, Hashum, Hashbadana, Zechariah, and Meshullam.
* `Job 1:14` And a messenger to Job came and said, "The oxen were plowing and the donkeys feeding *_beside_* them,
* `Psa 23:2` He makes me to lie down in green pastures. He leads me *_beside_* the still waters.
* `Sos 1:8` [Gentleman:] If you do not know, O fairest among women, go forth by the footsteps of the flock and feed your kids *_beside_* the shepherds' tents.
* `Isa 26:13` O LORD our God, other lords *_beside_* you have had dominion over us, but by you only we will make mention of your name.
* `Isa 32:20` Blessed are you who sow *_beside_* all waters, who send forth the feet of the ox and the donkey.
* `Jer 36:21` So the king sent Jehudi to bring the scroll, and he took it out of the chamber of Elishama the scribe. And Jehudi read it in the ears of the king and in the ears of all the princes who stood *_beside_* the king.
* `Ezk 1:15` Now as I beheld the living creatures, there appeared one wheel upon the earth *_beside_* the living creatures, for each of the four faces of it.
* `Ezk 9:2` And behold, six men came from the way of the higher gate, which lies toward the north, and each with a slaughter-weapon in his hand. And one man among them was clothed with linen, with a writer's inkhorn by his side. And they went in and stood *_beside_* the brazen altar.
* `Ezk 10:6` And it came to pass when he had commanded the man clothed with linen, saying, "Take fire from between the wheels, from between the cherubim," that he went in and stood *_beside_* the wheels.
* `Ezk 10:16` And when the cherubim went, the wheels went by them. And when the cherubim lifted up their wings to mount up from the earth, the same wheels also did not turn from *_beside_* them.
* `Ezk 10:19` And the cherubim lifted up their wings and mounted up from the earth in my sight. When they went out, the wheels were *_beside_* them. And each stood at the door of the east-gate of the LORD'S house, and the glory of the God of Israel was over them above.
* `Ezk 11:22` Then the cherubim raised their wings with the wheels *_beside_* them, and the glory of the God of Israel was over them above.
* `Ezk 32:13` I will also destroy all its beasts from *_beside_* the great waters, neither shall the foot of man disturb them anymore, nor the hooves of beasts disturb them.
* `Dan 11:4` And when he stands up, his kingdom shall be broken and shall be divided toward the four winds of heaven, and not to his posterity, nor according to his dominion which he ruled, for his kingdom shall be plucked up, even for others *_beside_* those.
* `Mrk 3:21` And when his friends heard of it, they went out to lay hold upon him, for they said, "He is *_beside_* himself."
* `Act 26:24` And as he was thus speaking for himself, Festus said with a loud voice, "Paul, you are *_beside_* yourself. Excessive learning makes you insane."
* `2Co 5:13` For whether we are *_beside_* ourselves, it is to God, or whether we are sober, it is for your cause.

_46 verses containing BESIDE_

== BESIDES

* `Gen 26:1` And there was a famine in the land, *_besides_* the first famine that was in the days of Abraham. And Isaac went to Abimelech king of the Philistines in Gerar.
* `Gen 28:9` Then Esau went to Ishmael and took, *_besides_* the wives which he had, Mahalath the daughter of Ishmael, Abraham's son, the sister of Nebajoth, to be his wife.
* `Gen 31:50` If you afflict my daughters, or if you take other wives *_besides_* my daughters, and no man is with us, behold, God is witness between you and me."
* `Gen 46:26` All the souls who came with Jacob into Egypt, who came out of his loins, *_besides_* Jacob's sons' wives, all the souls were sixty-six.
* `Exo 12:37` And the children of Israel journeyed from Rameses to Succoth, about six hundred thousand on foot who were men, *_besides_* children.
* `Lev 7:13` *_Besides_* the cakes, he shall offer for his offering leavened bread with the sacrifice of thanksgiving of his peace-offerings.
* `Num 5:8` But if the man has no kinsman to recompense the trespass to, let the trespass be recompensed to the LORD, even to the priest, *_besides_* the ram of the atonement, by which an atonement is made for him.
* `Num 5:20` But if you have gone aside to another instead of your husband, and if you are defiled and some man has lain with you *_besides_* your husband"—
* `Num 6:21` "This is the law of the Nazarite who has vowed and of his offering to the LORD for his separation, *_besides_* that which his hand shall get. According to the vow which he vowed, so he must do after the law of his separation."
* `Num 11:6` But now our soul is dried up. There is nothing at all *_besides_* this manna before our eyes."
* `Num 16:49` Now those who died in the plague were fourteen thousand and seven hundred, *_besides_* those who died on account of the matter with Korah.
* `Num 28:10` This is the burnt-offering of every sabbath, *_besides_* the continual burnt-offering and its drink-offering.
* `Num 28:15` And one kid of the goats for a sin-offering to the LORD shall be offered, *_besides_* the continual burnt-offering and its drink-offering.
* `Num 28:23` You shall offer these *_besides_* the burnt-offering in the morning, which is for a continual burnt-offering.
* `Num 28:24` After this manner you shall offer daily, throughout the seven days, the food of the sacrifice made by fire, a sweet savor to the LORD. It shall be offered *_besides_* the continual burnt-offering and its drink-offering.
* `Num 28:31` You shall offer them *_besides_* the continual burnt-offering and its food-offering (they shall be to you without blemish) and their drink-offerings.'"
* `Num 29:6` *_Besides_* the burnt-offering of the month and its food-offering, the daily burnt-offering and its food-offering, and their drink-offerings, according to their manner, for a sweet savor, a sacrifice made by fire to the LORD.
* `Num 29:11` One kid of the goats for a sin-offering, *_besides_* the sin-offering of atonement, the continual burnt-offering and its food-offering, and their drink-offerings.
* `Num 29:16` And one kid of the goats for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:19` And one kid of the goats for a sin-offering *_besides_* the continual burnt-offering, its food-offering, and their drink-offerings.
* `Num 29:22` And one goat for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:25` And one kid of the goats for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:28` And one goat for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:31` And one goat for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:34` And one goat for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:38` And one goat for a sin-offering, *_besides_* the continual burnt-offering, its food-offering, and its drink-offering.
* `Num 29:39` 'These things you shall offer to the LORD in your set feasts, *_besides_* your vows and your voluntary-offerings, for your burnt-offerings, for your food-offerings, for your drink-offerings, and for your peace-offerings.'"
* `Num 31:8` And they slew the kings of Midian, *_besides_* the rest of those who were slain, namely, Evi, Rekem, Zur, Hur, and Reba, five kings of Midian. Balaam the son of Beor they also slew with the sword.
* `Deu 3:5` All these cities were fortified with high walls, gates, and bars, *_besides_* a great number of unwalled towns.
* `Deu 4:35` To you it was shown so that you might know that the LORD is God. There is no one *_besides_* him.
* `Deu 18:8` They shall have like portions to eat, *_besides_* that which comes of the sale of his patrimony.
* `Deu 19:9` If you keep all these commandments to do them, which I command you this day, to love the LORD your God and to always walk in his ways, then you shall add three cities more for yourself, *_besides_* these three,
* `Deu 29:1` These are the words of the covenant which the LORD commanded Moses to make with the children of Israel in the land of Moab, *_besides_* the covenant which he made with them in Horeb.
* `Jsh 17:5` And there fell ten portions to Manasseh, *_besides_* the land of Gilead and Bashan, which were on the other side of the Jordan,
* `Jsh 22:19` However, if the land of your possession is unclean, then pass over to the land of the possession of the LORD, in which the LORD'S tabernacle dwells, and take possession among us. But do not rebel against the LORD nor rebel against us in building yourselves an altar *_besides_* the altar of the LORD our God.
* `Jsh 22:29` Far be it from us that we should rebel against the LORD and turn this day from following the LORD to build an altar for burnt-offerings, for food-offerings, or for sacrifices, *_besides_* the altar of the LORD our God that is before his tabernacle."
* `Jdg 8:26` And the weight of the golden earrings that he requested was one thousand and seven hundred shekels of gold, *_besides_* ornaments, collars, and purple clothing that was on the kings of Midian, and *_besides_* the chains that were around their camels' necks.
* `Jdg 11:34` And Jephthah came to Mizpeh to his house, and behold, his daughter came out to meet him with tambourines and with dances. And she was his only child. *_Besides_* her, he had neither son nor daughter.
* `Jdg 20:15` And the children of Benjamin were numbered at that time out of the cities twenty-six thousand men who drew the sword, *_besides_* the inhabitants of Gibeah, who were numbered seven hundred chosen men.
* `Jdg 20:17` And the men of Israel, *_besides_* Benjamin, were numbered four hundred thousand men who drew the sword. All these were men of war.
* `Rth 4:4` And I thought to advertise it to you, saying, 'Buy it before the inhabitants and before the elders of my people.' If you will redeem it, redeem it. But if you will not redeem it, then tell me so that I may know. For there is no one to redeem it *_besides_* you, and I am after you." And he said, "I will redeem it."
* `1Sa 2:2` "There is no one holy like the LORD, for there is no one *_besides_* you, neither is there any rock like our God.
* `2Sa 7:22` Therefore, you are great, O LORD God. For there is no one like you, neither is there any God *_besides_* you, according to all that we have heard with our ears.
* `1Ki 4:23` Ten fat oxen, twenty oxen out of the pastures, one hundred sheep, *_besides_* deer, gazelles, and fallow-deer, and fattened birds.
* `1Ki 5:16` *_Besides_* Solomon's three thousand and three hundred chief officers who were over the work and ruled over the people who wrought in the work.
* `1Ki 10:13` And king Solomon gave to the queen of Sheba all her desire, whatever she asked, *_besides_* that which Solomon gave her out of his royal bounty. So she turned and went to her own country—she and her servants.
* `1Ki 10:15` *_Besides_* what he had from the merchants, from the traffic of the spice-merchants, from all the kings of Arabia, and from the governors of the country.
* `1Ki 11:25` And he was an adversary to Israel all the days of Solomon, *_besides_* the mischief that Hadad did. And he abhorred Israel and reigned over Syria.
* `2Ki 21:16` Moreover, Manasseh shed very much innocent blood until he had filled Jerusalem from one end to another, *_besides_* his sin with which he made Judah to sin in doing evil in the sight of the LORD.
* `1Ch 3:9` These were all the sons of David, *_besides_* the sons of the concubines and Tamar their sister.
* `1Ch 17:20` O LORD, there is no one like you, neither is there any God *_besides_* you, according to all that we have heard with our ears.
* `2Ch 9:12` And king Solomon gave to the queen of Sheba all her desire, whatever she asked, *_besides_* that which she had brought to the king. So she turned and went away to her own land—she and her servants.
* `2Ch 9:14` *_Besides_* that which traders and merchants brought. And all the kings of Arabia and governors of the country brought gold and silver to Solomon.
* `2Ch 17:19` These waited on the king, *_besides_* those whom the king put in the fortified cities throughout all Judah.
* `2Ch 31:16` *_Besides_* their genealogy of males, from three years old and upward, even to everyone who enters into the house of the LORD, his daily portion for their service in their charges according to their courses.
* `Ezr 1:4` And whoever remains in any place where he sojourns, let the men of his place help him with silver, with gold, with goods, and with beasts, *_besides_* the voluntary-offering for the house of God that is in Jerusalem.'"
* `Ezr 1:6` And all those who were around them strengthened their hands with vessels of silver, with gold, with goods, with beasts, and with precious things, *_besides_* all that was willingly offered.
* `Ezr 2:65` *_Besides_* their men-servants and their women-servants, of whom there were seven thousand three hundred and thirty-seven, and there were among them two hundred singing-men and singing-women.
* `Neh 5:15` But the former governors who had been before me were burdensome to the people and had taken from them bread and wine, *_besides_* forty shekels of silver. And even their servants bore rule over the people. But I did not do so, because of the fear of God.
* `Neh 5:17` Moreover, there were at my table one hundred and fifty of the Jews and rulers, *_besides_* those who came to us from among the heathen who were around us.
* `Neh 7:67` *_Besides_* their men-servants and their women-servants, of whom there were seven thousand three hundred and thirty-seven. And they had two hundred and forty five singing-men and singing-women.
* `Psa 73:25` Whom do I have in heaven but you? And there is no one upon earth that I desire *_besides_* you.
* `Isa 43:11` I, even I, am the LORD, and *_besides_* me there is no savior.
* `Isa 44:6` Thus says the LORD the King of Israel, and his redeemer the LORD of hosts: 'I am the first, and I am the last, and *_besides_* me there is no God.
* `Isa 44:8` Do not fear, neither be afraid. Have I not told you from that time and declared it? You are even my witnesses. Is there a God *_besides_* me? Truly there is no God. I do not know any.'"
* `Isa 45:5` I am the LORD, and there is no one else. There is no God *_besides_* me. I girded you, though you have not known me,
* `Isa 45:6` So that they may know from the rising of the sun and from the west, that there is no one *_besides_* me. I am the LORD, and there is no one else.
* `Isa 45:21` Announce, and bring them near, even let them take counsel together. Who has declared this from ancient time? Who has told it from that time? Have I, the LORD, not? And there is no other God *_besides_* me, a just God and a Savior. There is no one *_besides_* me.
* `Isa 47:8` Now therefore, hear this, you who are given to pleasures, who dwell carelessly, who say in your heart, 'I am, and no one else *_besides_* me. I shall not sit as a widow, neither shall I know the loss of children.'
* `Isa 47:10` For you have trusted in your wickedness. You have said, 'No one sees me.' Your wisdom and your knowledge, it has perverted you. And you have said in your heart, 'I am, and no one else *_besides_* me.'
* `Isa 56:8` The Lord GOD who gathers the outcasts of Israel, says, "Yet I will gather others to him, *_besides_* those who are gathered to him."
* `Isa 64:4` For since the beginning of the world men have not heard, nor perceived by the ear, neither has the eye seen, O God, *_besides_* you, what he has prepared for him who waits for him.
* `Hos 13:4` Yet I am the LORD your God from the land of Egypt, and you shall know no God but me, for there is no savior *_besides_* me.
* `Zph 2:15` This is the rejoicing city that dwelt in security, that said in her heart, "I am, and there is no one *_besides_* me." How she has become a desolation, a place for beasts to lie down in! Everyone who passes by her shall hiss and wag his hand.
* `Mth 14:21` And those who had eaten were about five thousand men, *_besides_* women and children.
* `Mth 15:38` And those who had eaten were four thousand men, *_besides_* women and children.
* `Mth 25:20` And he who had received five talents came and brought another five talents, saying, 'Lord, you delivered to me five talents. Behold, I have gained *_besides_* them five more talents.'
* `Mth 25:22` "He also who had received two talents came, and said, 'Lord, you delivered to me two talents. Behold, I have gained two other talents *_besides_* them.'
* `Luk 16:26` And *_besides_* all this, between us and you there is a great gulf fixed, so that those who would pass from here to you cannot, neither can they pass to us who would come from there.'
* `Luk 24:21` But we trusted that it had been he who would have redeemed Israel. And *_besides_* all this, today is the third day since these things were done.
* `1Co 1:16` And I also baptized the household of Stephanas. *_Besides_* them, I do not know whether I baptized any other.
* `2Co 11:28` *_Besides_* those things that are outside, there is that which comes upon me daily: the care of all the churches.
* `2Pe 1:5` And *_besides_* this, giving all diligence, add to your faith, virtue; to virtue, knowledge;

_83 verses containing BESIDES_

== BESIEGE

* `Deu 20:12` And if it will make no peace with you, but will make war against you, then you shall *_besiege_* it.
* `Deu 20:19` "When you *_besiege_* a city a long time, in making war against it to take it, you shall not destroy its trees by forcing an ax against them. You may eat from them, but you shall not cut them down (for the tree of the field is man's life) to employ them in the siege.
* `Deu 28:52` And he shall *_besiege_* you in all your gates until your high and fortified walls in which you trusted come down throughout all your land. And he shall *_besiege_* you in all your gates throughout all your land which the LORD your God has given you.
* `1Sa 23:8` And Saul called all the people together to war to go down to Keilah and to *_besiege_* David and his men.
* `2Ch 6:28` "If there is famine in the land, if there is pestilence, if there is blight, mildew, swarming-locusts, or ravaging-locusts, if their enemies *_besiege_* them in the cities of their land, whatever calamity or whatever sickness there is,
* `Isa 21:2` A grievous vision is declared to me. The treacherous dealer deals treacherously, and the destroyer destroys. Go up, O Elam. *_Besiege_*, O Media. All her sighing I have made to cease.
* `Jer 21:4` 'Thus says the LORD God of Israel: "Behold, I will turn back the weapons of war that are in your hands, with which you fight against the king of Babylon and against the Chaldeans who *_besiege_* you outside the walls, and I will assemble them into the midst of this city.
* `Jer 21:9` He who abides in this city shall die by the sword, by the famine, and by the pestilence, but he who goes out and falls to the Chaldeans who *_besiege_* you, he shall live, and his life shall be to him for plunder.

_8 verses containing BESIEGE_

== BESIEGED

* `2Sa 20:15` And they came and *_besieged_* him in Abel of Beth-maachah and cast up a siege-mound against the city, and it stood in the trench. And all the people who were with Joab battered the wall to throw it down.
* `1Ki 16:17` And Omri and all Israel with him went up from Gibbethon and *_besieged_* Tirzah.
* `1Ki 20:1` And Ben-hadad the king of Syria collected all his army. And there were thirty-two kings with him and horses and chariots. And he went up and *_besieged_* Samaria and warred against it.
* `2Ki 6:24` And it came to pass after this, that Ben-hadad king of Syria gathered all his army and went up and *_besieged_* Samaria.
* `2Ki 6:25` And there was a great famine in Samaria. And behold, they *_besieged_* it until a donkey's head was sold for eighty pieces of silver and the fourth part of a kab of dove's dung for five pieces of silver.
* `2Ki 16:5` Then Rezin king of Syria and Pekah son of Remaliah king of Israel came up to Jerusalem to war. And they *_besieged_* Ahaz, but could not overcome him.
* `2Ki 17:5` Then the king of Assyria came up throughout all the land, went up to Samaria, and *_besieged_* it for three years.
* `2Ki 18:9` And it came to pass in the fourth year of king Hezekiah, which was the seventh year of Hoshea son of Elah king of Israel, that Shalmaneser king of Assyria came up against Samaria and *_besieged_* it.
* `2Ki 19:24` I have dug and drank strange waters, and with the sole of my feet I have dried up all the rivers of *_besieged_* places."
* `2Ki 24:10` At that time the servants of Nebuchadnezzar king of Babylon came up against Jerusalem, and the city was *_besieged_*.
* `2Ki 24:11` And Nebuchadnezzar king of Babylon came against the city, and his servants *_besieged_* it.
* `2Ki 25:2` And the city was *_besieged_* until the eleventh year of king Zedekiah.
* `1Ch 20:1` And it came to pass, that after the year had expired, at the time that kings go out to battle, Joab led forth the power of the army and wasted the country of the children of Ammon and came and *_besieged_* Rabbah. But David remained in Jerusalem. And Joab smote Rabbah and destroyed it.
* `Ecc 9:14` There was a little city with few men in it, and a great king came against it, *_besieged_* it, and built great bulwarks against it.
* `Isa 1:8` And the daughter of Zion is left like a cottage in a vineyard, like a lodge in a garden of cucumbers, like a *_besieged_* city.
* `Isa 37:25` I have dug and drank water, and with the sole of my feet I have dried up all the rivers of the *_besieged_* places.'
* `Jer 32:2` For then the king of Babylon's army *_besieged_* Jerusalem, and Jeremiah the prophet was confined in the court of the prison, which was in the king of Judah's house,
* `Jer 37:5` Then Pharaoh's army had come from Egypt. And when the Chaldeans who *_besieged_* Jerusalem heard tidings of them, they departed from Jerusalem.
* `Jer 39:1` In the ninth year of Zedekiah king of Judah, in the tenth month, Nebuchadnezzar king of Babylon and all his army came against Jerusalem, and they *_besieged_* it.
* `Jer 52:5` So the city was *_besieged_* until the eleventh year of king Zedekiah.
* `Ezk 4:3` Moreover, take an iron pan and set it for a wall of iron between you and the city. And set your face against it so that it shall be *_besieged_*, and then lay siege against it. This shall be a sign to the house of Israel.
* `Ezk 6:12` He who is far off shall die by the pestilence. And he who is near shall fall by the sword. And he who remains and is *_besieged_* shall die by the famine. Thus I will accomplish my fury upon them.
* `Dan 1:1` In the third year of the reign of Jehoiakim king of Judah, Nebuchadnezzar king of Babylon came to Jerusalem and *_besieged_* it.

_23 verses containing BESIEGED_

== BESIEGES

* `1Ki 8:37` "If there is famine in the land, if there is pestilence, blight, mildew, swarming-locust, or if there is ravaging-locust, if their enemy *_besieges_* them in the land of their cities, whatever plague, whatever sickness there is,

_1 verse containing BESIEGES_

== BESODEIAH

* `Neh 3:6` Moreover, the old gate was repaired by Jehoiada the son of Paseah and Meshullam the son of *_Besodeiah_*. They laid its beams, set up its doors, its locks, and its bars.

_1 verse containing BESODEIAH_

== BESOR

* `1Sa 30:9` So David went—he and the six hundred men who were with him—and came to the brook *_Besor_*, where those who were left behind remained.
* `1Sa 30:10` But David pursued—he and four hundred men—while two hundred stayed behind, who were so faint that they could not go over the brook of *_Besor_*.
* `1Sa 30:21` And David came to the two hundred men who were so faint that they could not follow David, whom they had made also to abide at the brook of *_Besor_*. And they went forth to meet David and to meet the people who were with him. And when David came near to the people, he saluted them.

_3 verses containing BESOR_

== BEST

* `Gen 43:11` And their father Israel said to them, "If it must be so now, do this: take some of the *_best_* fruits in the land in your vessels and carry to the man a present—a little balm, a little honey, spices, myrrh, nuts, and almonds.
* `Gen 47:6` The land of Egypt is before you. In the *_best_* of the land make your father and brothers to dwell. In the land of Goshen let them dwell. And if you know any able men among them, then make them rulers over my livestock."
* `Gen 47:11` And Joseph placed his father and his brothers and gave them a possession in the land of Egypt, in the *_best_* of the land, in the land of Rameses, as Pharaoh had commanded.
* `Exo 22:5` "If a man causes a field or vineyard to be eaten and puts in his beast and feeds in another man's field, from the *_best_* of his own field and from the *_best_* of his own vineyard he shall make restitution.
* `Num 18:12` All the *_best_* of the oil, all the *_best_* of the wine, and of the wheat, the first-fruits of them which they offer to the LORD, I have given them to you.
* `Num 18:29` Out of all your gifts you shall offer every heave-offering of the LORD, from all the *_best_* of it, even the hallowed part of it.'
* `Num 18:30` Therefore, you shall say to them, 'When you have offered its *_best_* from it, it shall be counted to the Levites as the increase of the threshing-floor and as the increase of the wine-press.
* `Num 18:32` And you shall bear no sin by reason of it when you have offered its *_best_* from it, neither shall you pollute the holy things of the children of Israel, lest you die.'"
* `Num 36:6` This is the thing which the LORD commands concerning the daughters of Zelophehad, saying, 'Let them marry to whom they think *_best_*. Only to the family of the tribe of their father they shall marry.'
* `Deu 23:16` He shall dwell with you, even among you in that place which he chooses in one of your gates where it pleases him *_best_*. You shall not oppress him.
* `1Sa 8:14` And he will take your fields, your vineyards, and your olive-groves, even the *_best_* of them, and give them to his servants.
* `1Sa 15:9` But Saul and the people spared Agag and the *_best_* of the sheep, of the oxen, of the fattened calves, the lambs, and all that was good, and would not utterly destroy them. But everything that was vile and worthless, that they utterly destroyed.
* `1Sa 15:15` And Saul said, "They have brought them from the Amalekites, for the people spared the *_best_* of the sheep and of the oxen to sacrifice to the LORD your God, and the rest we have utterly destroyed."
* `2Sa 18:4` And the king said to them, "What seems to you *_best_* I will do." And the king stood by the gate side, and all the people came out by hundreds and by thousands.
* `1Ki 10:18` Moreover, the king made a great throne of ivory and overlaid it with the *_best_* gold.
* `1Ki 20:3` 'Your silver and gold are mine, and also your wives and your children, even the *_best_*, are mine.'"
* `2Ki 10:3` Choose the *_best_* and fittest of your master's sons, set him on his father's throne, and fight for your master's house."
* `Est 2:9` And the young woman pleased him and she obtained kindness from him. And he speedily gave her things for purification, with such things as belonged to her, and seven attendants who were suitable to be given to her out of the king's house. And he moved her and her attendants to the *_best_* place of the house of the women.
* `Psa 39:5` Behold, you have made my days as a hand-breadth and my lifetime as nothing before you. Truly every man at his *_best_* state is altogether vanity." [Selah.]
* `Sos 7:9` And the roof of your mouth shall be like the *_best_* wine— [Lady:] that goes down sweetly for my beloved, causing the lips of those who are asleep to speak.
* `Ezk 31:16` I made the nations to shake at the sound of his fall when I cast him down to the grave with those who descend into the pit. And all the trees of Eden, the choice and *_best_* of Lebanon, all that drink water, shall be comforted in the nether parts of the earth.
* `Mic 7:4` The *_best_* of them is like a brier. The most upright is sharper than a thorn hedge. The day of your watchmen and your visitation comes. Now shall be their perplexity.
* `Luk 15:22` But the father said to his servants, 'Bring forth the *_best_* robe and put it on him. Put a ring on his hand and shoes on his feet.
* `1Co 12:31` But earnestly covet the *_best_* gifts. And yet I show to you a more excellent way.

_24 verses containing BEST_

== BESTOW

* `Exo 32:29` For Moses had said, "Consecrate yourselves today to the LORD, even every man upon his son and upon his brother, so that he may *_bestow_* upon you a blessing this day."
* `Deu 14:26` And you shall *_bestow_* that money for whatever your soul desires, for oxen, for sheep, for wine, for strong drink, or for whatever your soul desires. And you shall eat there before the LORD your God, and you shall rejoice—you and your household.
* `Ezr 7:20` And whatever more is needful for the house of your God, which you have occasion to *_bestow_*, *_bestow_* it out of the king's treasure-house.
* `1Co 12:23` And those members of the body which we think to be less honorable, upon these we *_bestow_* more abundant honor. And our unpresentable parts have more abundant modesty,
* `1Co 13:3` And if I *_bestow_* all my goods to feed the poor and if I give my body to be burned, but do not have charity, it profits me nothing.

_5 verses containing BESTOW_

== BESTOWED

* `1Ki 10:26` And Solomon collected chariots and horsemen. And he had one thousand and four hundred chariots and twelve thousand horsemen, whom he *_bestowed_* in the cities for chariots and with the king at Jerusalem.
* `2Ki 12:15` Moreover, they did not reckon with the men, into whose hand they delivered the money to be *_bestowed_* on workmen, for they dealt faithfully.
* `1Ch 29:25` And the LORD magnified Solomon exceedingly in the sight of all Israel and *_bestowed_* upon him such royal majesty as had not been on any king before him in Israel.
* `2Ch 9:25` And Solomon had four thousand stalls for horses and chariots and twelve thousand horsemen, whom he *_bestowed_* in the chariot cities and with the king at Jerusalem.
* `2Ch 24:7` For the sons of Athaliah, that wicked woman, had broken up the house of God, and also all the dedicated things of the house of the LORD they *_bestowed_* upon Baalim.
* `Isa 63:7` I will mention the loving-kindnesses of the LORD and the praises of the LORD, according to all that the LORD has *_bestowed_* on us and the great goodness toward the house of Israel, which he has *_bestowed_* on them according to his mercies and according to the multitude of his loving-kindnesses.
* `Jhn 4:38` I sent you to reap that on which you *_bestowed_* no labor. Other men labored, and you have entered into their labors."
* `Rom 16:6` Greet Mary, who *_bestowed_* much labor on us.
* `1Co 15:10` But by the grace of God I am what I am, and his grace which was *_bestowed_* upon me was not in vain. But I labored more abundantly than all of them—yet not I, but the grace of God which was with me.
* `2Co 1:11` You also helping together by prayer for us, so that for the gift *_bestowed_* upon us by the means of many persons, thanks may be given by many on our behalf.
* `2Co 8:1` Moreover, brothers, we make known to you the grace of God *_bestowed_* on the churches of Macedonia,
* `Gal 4:11` I am afraid for you, lest I have *_bestowed_* upon you labor in vain.
* `1Jn 3:1` Behold what manner of love the Father has *_bestowed_* upon us, that we should be called the sons of God. Therefore, the world does not know us because it did not know him.

_13 verses containing BESTOWED_

== BET

* `Psa 25:2` [*_BET_*] O my God, I trust in you. Do not let me be ashamed. Do not let my enemies triumph over me.
* `Psa 119:9` [*_BET_*] How shall a young man cleanse his way? By taking heed to it, according to your word.
* `Pro 31:11` [*_BET_*] The heart of her husband safely trusts in her, and he shall have no lack of gain.
* `Lam 1:2` [*_BET_*] She weeps bitterly in the night, and her tears are on her cheeks. Among all her lovers she has no one to comfort her. All her friends have dealt treacherously with her. They have become her enemies.
* `Lam 2:2` [*_BET_*] The Lord has swallowed up all the habitations of Jacob and has not pitied. He has thrown down in his wrath the strongholds of the daughter of Judah. He has brought them down to the ground. He has polluted the kingdom and its princes.
* `Lam 3:4` [*_BET_*] My flesh and my skin he has made old. He has broken my bones.
* `Lam 4:2` [*_BET_*] The precious sons of Zion, comparable to fine gold, how they are esteemed as earthen pitchers, the work of the hands of the potter!

_7 verses containing BET_

== BETAH

* `2Sa 8:8` And from *_Betah_* and from Berothai, cities of Hadadezer, king David took an exceeding amount of brass.

_1 verse containing BETAH_

== BETEN

* `Jsh 19:25` And their border was Helkath, Hali, *_Beten_*, Achshaph,

_1 verse containing BETEN_

== BETH

* `Gen 12:8` And he departed from there to a mountain on the east of *_Beth_*-el and pitched his tent, having *_Beth_*-el on the west and Hai on the east. And there he erected an altar to the LORD and called upon the name of the LORD.
* `Gen 13:3` And he went on his journeys from the south even to *_Beth_*-el to the place where his tent had been at the beginning, between *_Beth_*-el and Hai,
* `Gen 28:19` And he called the name of that place *_Beth_*-el, but the name of that city was called Luz at the first.
* `Gen 31:13` I am the God of *_Beth_*-el, where you anointed the pillar and where you vowed to me a vow. Now arise, depart from this land, and return to the land of your kindred.'"
* `Gen 35:1` And God said to Jacob, "Arise, go up to *_Beth_*-el and dwell there. And make there an altar to God, who appeared to you when you fled from the face of Esau your brother."
* `Gen 35:3` And let us arise and go up to *_Beth_*-el. And I will make there an altar to God, who answered me in the day of my distress and was with me in the way which I went."
* `Gen 35:6` So Jacob came to Luz, which is in the land of Canaan (that is *_Beth_*-el)—he and all the people who were with him.
* `Gen 35:7` And he erected there an altar and called the place El-*_beth_*-el because there God appeared to him when he fled from the face of his brother.
* `Gen 35:8` But Deborah, Rebekah's nurse, died, and she was buried beneath *_Beth_*-el under an oak. And its name was called Allon-bachuth.
* `Gen 35:15` And Jacob called the name of the place where God spoke with him *_Beth_*-el.
* `Gen 35:16` And they journeyed from *_Beth_*-el. And there was only a little distance to come to Ephrath, and Rachel travailed and had hard labor.
* `Gen 35:19` And Rachel died and was buried on the way to Ephrath, which is *_Beth_*-lehem.
* `Gen 48:7` And as for me, when I came from Padan, Rachel died beside me in the land of Canaan, on the way when there was only a little distance to come to Ephrath, and I buried her there on the way of Ephrath (the same is *_Beth_*-lehem)."
* `Num 32:36` *_Beth_*-nimrah, and *_Beth_*-haran—fortified cities—and folds for sheep.
* `Num 33:49` And they encamped by the Jordan, from *_Beth_*-jeshimoth even to Abel-shittim in the plains of Moab.
* `Deu 3:29` So we stayed in the valley over against *_Beth_*-peor."
* `Deu 4:46` On the east side of the Jordan, in the valley over against *_Beth_*-Peor, in the land of Sihon king of the Amorites, who dwelt at Heshbon, whom Moses and the children of Israel smote after they had come forth from Egypt.
* `Deu 34:6` And he buried him in a valley in the land of Moab, over against *_Beth_*-peor. But no man knows of his sepulcher to this day.
* `Jsh 7:2` And Joshua sent men from Jericho to Ai, which is beside *_Beth_*-aven, on the east side of *_Beth_*-el, and spoke to them, saying, "Go up and view the country." And the men went up and viewed Ai.
* `Jsh 8:9` Joshua therefore sent them forth. And they went to lie in ambush and stayed between *_Beth_*-el and Ai on the west side of Ai, but Joshua lodged that night among the people.
* `Jsh 8:12` And he took about five thousand men and set them to lie in ambush between *_Beth_*-el and Ai on the west side of the city.
* `Jsh 8:17` And there was not a man left in Ai or *_Beth_*-el who did not go out after Israel. And they left the city open and pursued Israel.
* `Jsh 10:10` And the LORD completely defeated them before Israel, slew them with a great slaughter at Gibeon, chased them along the way that goes up to *_Beth_*-horon, and smote them to Azekah and to Makkedah.
* `Jsh 10:11` And it came to pass as they fled from before Israel and were in the descent to *_Beth_*-horon, that the LORD cast down great stones from heaven upon them to Azekah, and they died. There were more who died with hailstones than those whom the children of Israel slew with the sword.
* `Jsh 12:3` And from the plain to the sea of Cinneroth on the east and to the sea of the plain, even the Salt Sea on the east, the way to *_Beth_*-jeshimoth; and from the south, under Ashdoth-pisgah;
* `Jsh 12:9` The king of Jericho one; the king of Ai, which is beside *_Beth_*-el, one;
* `Jsh 12:16` The king of Makkedah, one; the king of *_Beth_*-el, one;
* `Jsh 13:17` Heshbon, and all her cities that are in the plain: Dibon, Bamoth-baal, *_Beth_*-baal-meon,
* `Jsh 13:20` *_Beth_*-peor, Ashdoth-pisgah, *_Beth_*-jeshimoth,
* `Jsh 13:27` And in the valley, *_Beth_*-aram, *_Beth_*-nimrah, Succoth, and Zaphon, the rest of the kingdom of Sihon king of Heshbon, the Jordan and its border, even to the edge of the sea of Cinneroth, on the other side of the Jordan eastward.
* `Jsh 15:6` And the border went up to *_Beth_*-hogla, and passed along by the north of *_Beth_*-arabah. And the border went up to the stone of Bohan the son of Reuben.
* `Jsh 15:10` And the border compassed from Baalah westward to mount Seir, passed along to the side of mount Jearim (which is Chesalon) on the north side, went down to *_Beth_*-shemesh, and passed on to Timnah.
* `Jsh 15:27` Hazar-gaddah, Heshmon, *_Beth_*-palet,
* `Jsh 15:41` Gederoth, *_Beth_*-dagon, Naamah, and Makkedah; sixteen cities with their villages.
* `Jsh 15:53` Janum, *_Beth_*-tappuah, Aphekah,
* `Jsh 15:58` Halhul, *_Beth_*-zur, Gedor,
* `Jsh 15:59` Maarath, *_Beth_*-anoth, and Eltekon; six cities with their villages.
* `Jsh 15:61` In the wilderness, *_Beth_*-arabah, Middin, Secacah,
* `Jsh 16:1` And the lot of the children of Joseph fell from the Jordan by Jericho, to the water of Jericho on the east, to the wilderness that goes up from Jericho throughout mount *_Beth_*-el,
* `Jsh 16:2` And goes out from *_Beth_*-el to Luz, and passes along to the borders of Archi to Ataroth,
* `Jsh 16:3` And goes down westward to the border of Japhleti, to the border of *_Beth_*-horon the nether, and to Gezer, and its limits are at the sea.
* `Jsh 16:5` And the border of the children of Ephraim according to their families was this: even the border of their inheritance on the east side was Ataroth-adar, to *_Beth_*-horon the upper,
* `Jsh 17:11` And in Issachar and in Asher, Manasseh had *_Beth_*-shean and its towns, Ibleam and its towns, the inhabitants of Dor and its towns, the inhabitants of En-dor and its towns, the inhabitants of Tanach and its towns, and the inhabitants of Megiddo and its towns, even three countries.
* `Jsh 17:16` And the children of Joseph said, "The hill is not enough for us. And all the Canaanites who dwell in the land of the valley have chariots of iron—both those who are of *_Beth_*-shean and its towns, and those who are of the valley of Jezreel."
* `Jsh 18:12` And their border on the north side was from the Jordan, and the border went up to the side of Jericho on the north side and went up through the mountains westward. And its limits were at the wilderness of *_Beth_*-aven.
* `Jsh 18:13` And the border went over from there toward Luz, to the side of Luz (which is *_Beth_*-el) southward. And the border descended to Ataroth-adar, near the hill that lies on the south side of the nether *_Beth_*-horon.
* `Jsh 18:14` And the border was drawn from there and compassed the corner of the sea southward from the hill that lies before *_Beth_*-horon southward. And its limits were at Kirjath-baal (which is Kirjath-jearim), a city of the children of Judah. This was the west quarter.
* `Jsh 18:19` And the border passed along to the side of *_Beth_*-hoglah northward. And the limits of the border were at the north bay of the Salt Sea at the south end of the Jordan. This was the south border.
* `Jsh 18:21` Now the cities of the tribe of the children of Benjamin, according to their families, were Jericho, *_Beth_*-hoglah, the valley of Keziz,
* `Jsh 18:22` *_Beth_*-arabah, Zemaraim, *_Beth_*-el,
* `Jsh 19:5` Ziklag, *_Beth_*-marcaboth, Hazar-susah,
* `Jsh 19:6` *_Beth_*-lebaoth, and Sheruhen; thirteen cities and their villages;
* `Jsh 19:15` And Kattath, Nahallal, Shimron, Idalah, and *_Beth_*-lehem; twelve cities with their villages.
* `Jsh 19:21` Remeth, En-gannim, En-haddah, and *_Beth_*-pazzez;
* `Jsh 19:22` And the border reaches to Tabor, Shahazimah, and *_Beth_*-shemesh, and the limits of their border were at the Jordan; sixteen cities with their villages.
* `Jsh 19:27` And turns toward the sunrise to *_Beth_*-dagon, and reaches to Zebulun, and to the valley of Jiphthah-el toward the north side of *_Beth_*-emek, and Neiel, and goes out to Cabul on the left hand,
* `Jsh 19:38` Iron, Migdal-el, Horem, *_Beth_*-anath, and *_Beth_*-shemesh; nineteen cities with their villages.
* `Jsh 21:16` Ain with its suburbs, Juttah with its suburbs, and *_Beth_*-shemesh with its suburbs; nine cities out of those two tribes.
* `Jsh 21:22` Kibzaim with its suburbs, and *_Beth_*-horon with its suburbs; four cities.
* `Jdg 1:22` And the house of Joseph, they also went up against *_Beth_*-el, and the LORD was with them.
* `Jdg 1:23` And the house of Joseph sent to explore *_Beth_*-el. Now the name of the city was formerly Luz.
* `Jdg 1:27` Manasseh did not expel the inhabitants of *_Beth_*-shean and its towns, nor Tanach and its towns, nor the inhabitants of Dor and its towns, nor the inhabitants of Ibleam and its towns, nor the inhabitants of Megiddo and its towns, but the Canaanites would dwell in that land.
* `Jdg 1:33` Naphtali did not expel the inhabitants of *_Beth_*-shemesh nor the inhabitants of *_Beth_*-anath, but he dwelt among the Canaanites, the inhabitants of the land. Nevertheless, the inhabitants of *_Beth_*-shemesh and of *_Beth_*-anath became tributaries to them.
* `Jdg 4:5` And she dwelt under the palm-tree of Deborah between Ramah and *_Beth_*-el in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `Jdg 7:22` And the three hundred blew the trumpets, and the LORD set every man's sword against his fellow, even throughout all the host. And the host fled to *_Beth_*-shittah in Zereroth and to the border of Abel-meholah near Tabbath.
* `Jdg 7:24` And Gideon sent messengers throughout all mount Ephraim, saying, "Come down against the Midianites and take the waters before them to *_Beth_*-barah and the Jordan." Then all the men of Ephraim assembled and took the waters to *_Beth_*-barah and the Jordan.
* `Jdg 12:8` And after him Ibzan of *_Beth_*-lehem judged Israel.
* `Jdg 12:10` Then Ibzan died and was buried at *_Beth_*-lehem.
* `Jdg 17:7` And there was a young man out of *_Beth_*-lehem-judah of the family of Judah, who was a Levite, and he sojourned there.
* `Jdg 17:8` And the man departed out of the city from *_Beth_*-lehem-judah to sojourn where he could find a place. And he came to mount Ephraim to the house of Micah as he journeyed.
* `Jdg 17:9` And Micah said to him, "Where do you come from?" And he said to him, "I am a Levite from *_Beth_*-lehem-judah and I go to sojourn where I may find a place."
* `Jdg 18:28` And there was no deliverer because it was far from Zidon and they had no business with any man. And it was in the valley that lies by *_Beth_*-rehob. And they built a city and dwelt in it.
* `Jdg 19:1` And it came to pass in those days when there was no king in Israel, that there was a certain Levite dwelling on the side of mount Ephraim, who took for himself a concubine out of *_Beth_*-lehem-judah.
* `Jdg 19:2` And his concubine played the harlot against him and went away from him to her father's house to *_Beth_*-lehem-judah, and was there for four whole months.
* `Jdg 19:18` And he said to him, "We are passing from *_Beth_*-lehem-Judah toward the side of mount Ephraim. I am from there. And I went to *_Beth_*-lehem-judah, but I am now going to the house of the LORD. And there is no man who receives me into his house.
* `Jdg 21:19` Then they said, "Behold, there is a yearly feast of the LORD in Shiloh in a place which is on the north side of *_Beth_*-el, on the east side of the highway that goes up from *_Beth_*-el to Shechem, and on the south of Lebonah."
* `Rth 1:1` Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of *_Beth_*-lehem-judah went to dwell in the country of Moab—he, his wife, and his two sons.
* `Rth 1:2` And the name of the man was Elimelech, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of *_Beth_*-lehem-judah. And they came into the country of Moab and continued there.
* `Rth 1:19` So the two of them went until they came to *_Beth_*-lehem. And it came to pass, when they had come to *_Beth_*-lehem, that all the city was stirred because of them, and they said, "Is this Naomi?"
* `Rth 1:22` So Naomi returned, and Ruth the Moabitess her daughter-in-law with her, who returned from the country of Moab. And they came to *_Beth_*-lehem in the beginning of barley-harvest.
* `Rth 2:4` And behold, Boaz came from *_Beth_*-lehem and said to the reapers, "May the LORD be with you." And they answered him, "May the LORD bless you."
* `Rth 4:11` And all the people who were in the gate and the elders said, "We are witnesses. May the LORD make the woman who has come into your house like Rachel and like Leah, both of whom built the house of Israel. And may you do worthily in Ephratah and be famous in *_Beth_*-lehem.
* `1Sa 6:9` And behold, if it goes up by the way of his own border to *_Beth_*-shemesh, then he has done us this great evil, but if not, then we shall know that it is not his hand that smote us. It was a chance that happened to us."
* `1Sa 6:12` And the cows took the straight way to the way of *_Beth_*-shemesh and went along the highway, lowing as they went, and did not turn aside to the right hand or to the left. And the lords of the Philistines went after them to the border of *_Beth_*-shemesh.
* `1Sa 6:13` And the people of *_Beth_*-shemesh were reaping their wheat harvest in the valley. And they lifted up their eyes, saw the ark, and rejoiced to see it.
* `1Sa 6:14` And the cart came into the field of Joshua, a *_Beth_*-shemite, and stood there where there was a great stone. And they cleaved the wood of the cart and offered the cows as a burnt-offering to the LORD.
* `1Sa 6:15` And the Levites took down the ark of the LORD and the coffer that was with it, in which were the jewels of gold, and put them on the great stone. And the men of *_Beth_*-shemesh offered burnt-offerings and sacrificed sacrifices the same day to the LORD.
* `1Sa 6:18` And the golden mice, according to the number of all the cities of the Philistines belonging to the five lords, both of fortified cities and of country villages, even to the great stone of Abel on which they set down the ark of the LORD—which stone remains to this day in the field of Joshua the *_Beth_*-shemite.
* `1Sa 6:19` And he smote the men of *_Beth_*-shemesh because they had looked into the ark of the LORD. He even smote among the people seventy men, fifty thousand men. And the people lamented because the LORD had smitten many of the people with a great slaughter.
* `1Sa 6:20` And the men of *_Beth_*-shemesh said, "Who is able to stand before Yahweh, this holy God? And to whom shall he go up from us?"
* `1Sa 7:11` And the men of Israel went out of Mizpeh, pursued the Philistines, and smote them until they came under *_Beth_*-car.
* `1Sa 7:16` And he went from year to year in circuit to *_Beth_*-el, Gilgal, and Mizpeh, and judged Israel in all those places.
* `1Sa 10:3` Then you shall go on forward from there and shall come to the plain of Tabor, and three men going up to God at *_Beth_*-el shall meet you there: one carrying three kids, another carrying three loaves of bread, and another carrying a bottle of wine.
* `1Sa 13:2` Saul chose for himself three thousand men of Israel, of which two thousand were with Saul in Michmash and in the mountains of *_Beth_*-el, and one thousand were with Jonathan in Gibeah of Benjamin. And the rest of the people he sent each to his tent.
* `1Sa 13:5` And the Philistines assembled to fight with Israel: thirty thousand chariots, six thousand horsemen, and people as the sand which is on the sea shore in multitude. And they came up and encamped in Michmash, eastward from *_Beth_*-aven.
* `1Sa 13:18` Another company turned the way to *_Beth_*-horon, and another company turned to the way of the border that looks to the valley of Zeboim toward the wilderness.
* `1Sa 14:23` So the LORD saved Israel that day. And the battle passed over to *_Beth_*-aven.
* `1Sa 16:1` And the LORD said to Samuel, "How long will you mourn for Saul, seeing I have rejected him from reigning over Israel? Fill your horn with oil and go, I will send you to Jesse the *_Beth_*-lehemite, for I have provided myself a king among his sons."
* `1Sa 16:4` And Samuel did that which the LORD spoke and came to *_Beth_*-lehem. And the elders of the town trembled at his coming and said, "Do you come peaceably?"
* `1Sa 16:18` Then one of the servants answered and said, "Behold, I have seen a son of Jesse the *_Beth_*-lehemite who is skillful in playing, a mighty valiant man, a man of war, prudent in matters, and a handsome person, and the LORD is with him."
* `1Sa 17:12` Now David was the son of that Ephrathite of *_Beth_*-lehem-judah, whose name was Jesse, who had eight sons and was an old man in the days of Saul and aged among men.
* `1Sa 17:15` But David went and returned from Saul to feed his father's sheep at *_Beth_*-lehem.
* `1Sa 17:58` And Saul said to him, "Whose son are you, young man?" And David answered, "I am the son of your servant Jesse the *_Beth_*-lehemite."
* `1Sa 20:6` If your father at all misses me, then say, 'David earnestly asked leave of me so that he might run to *_Beth_*-lehem his city, for there is a yearly sacrifice there for all the family.'
* `1Sa 20:28` And Jonathan answered Saul, "David earnestly asked leave of me to go to *_Beth_*-lehem.
* `1Sa 30:27` To those who were in *_Beth_*-el, to those who were in south Ramoth, to those who were in Jattir,
* `1Sa 31:10` And they put his armor in the house of Ashtaroth and fastened his body to the wall of *_Beth_*-shan.
* `1Sa 31:12` All the valiant men arose and went all night, took the body of Saul and the bodies of his sons from the wall of *_Beth_*-shan, and came to Jabesh and burnt them there.
* `2Sa 2:32` And they took up Asahel and buried him in the sepulcher of his father, which was in *_Beth_*-lehem. And Joab and his men went all night and came to Hebron at the break of day.
* `2Sa 10:6` And when the children of Ammon saw that they had made themselves odious before David, the children of Ammon sent and hired the Syrians of *_Beth_*-rehob and the Syrians of Zoba, twenty thousand footmen, and one thousand men from the king of Maacah and twelve thousand men from the men of Tob.
* `2Sa 15:17` And the king went forth, and all the people followed him, and they stayed in *_Beth_*-merhak.
* `2Sa 20:14` And he went through all the tribes of Israel to Abel of *_Beth_*-maachah and all the Berites. And they were assembled and also went after him.
* `2Sa 20:15` And they came and besieged him in Abel of *_Beth_*-maachah and cast up a siege-mound against the city, and it stood in the trench. And all the people who were with Joab battered the wall to throw it down.
* `2Sa 21:12` And David went and took the bones of Saul and the bones of Jonathan his son from the men of Jabesh-gilead who had stolen them from the street of *_Beth_*-shan, where the Philistines had hanged them when the Philistines had slain Saul in Gilboa.
* `2Sa 21:19` And there was again a battle in Gob with the Philistines where Elhanan the son of Jaareoregim, a *_Beth_*-lehemite, slew the brother of Goliath the Gittite, the staff of whose spear was like a weaver's beam.
* `2Sa 23:14` And David was then in a hold, and the garrison of the Philistines was then in *_Beth_*-lehem.
* `2Sa 23:15` And David longed and said, "Oh that someone would give me a drink of the water from the well of *_Beth_*-lehem which is by the gate!"
* `2Sa 23:16` And the three mighty men broke through the host of the Philistines, drew water out of the well of *_Beth_*-lehem that was by the gate, took it, and brought it to David. Nevertheless, he would not drink it, but poured it out to the LORD.
* `2Sa 23:24` Asahel the brother of Joab was one of the thirty, along with Elhanan the son of Dodo of *_Beth_*-lehem,
* `1Ki 4:9` The son of Dekar, in Makaz, in Shaalbim, *_Beth_*-shemesh, and Elon-*_beth_*-hanan;
* `1Ki 4:12` Baana the son of Ahilud—to him pertained Taanach, Megiddo, and all *_Beth_*-shean, which is by Zartanah beneath Jezreel, from *_Beth_*-shean to Abel-meholah, even to the place that is beyond Jokneam;
* `1Ki 9:17` And Solomon built Gezer, *_Beth_*-horon the nether,
* `1Ki 12:29` And he set one in *_Beth_*-el and the other he placed in Dan.
* `1Ki 12:32` And Jeroboam ordained a feast in the eighth month, on the fifteenth day of the month, like the feast that is in Judah, and he offered upon the altar. Thus he did in *_Beth_*-el, sacrificing to the calves that he had made. And he placed in *_Beth_*-el the priests of the high places which he had made.
* `1Ki 12:33` So he offered upon the altar which he had made in *_Beth_*-el on the fifteenth day of the eighth month, even in the month which he had devised in his own heart. And he ordained a feast to the children of Israel and he offered upon the altar and burned incense.
* `1Ki 13:1` And behold, there came a man of God out of Judah by the word of the LORD to *_Beth_*-el. And Jeroboam stood by the altar to burn incense.
* `1Ki 13:4` And it came to pass when king Jeroboam heard the saying of the man of God who had cried against the altar in *_Beth_*-el, that he put forth his hand from the altar, saying, "Lay hold upon him." And his hand, which he put forth against him, dried up so that he could not draw it to him again.
* `1Ki 13:10` So he went another way and did not return by the way that he came to *_Beth_*-el.
* `1Ki 13:11` Now there dwelt an old prophet in *_Beth_*-el. And his sons came and told him all the works that the man of God had done that day in *_Beth_*-el. The words which he had spoken to the king, they also told them to their father.
* `1Ki 13:32` For the saying which he cried by the word of the LORD against the altar in *_Beth_*-el and against all the houses of the high places which are in the cities of Samaria shall surely come to pass."
* `1Ki 15:20` So Ben-hadad listened to king Asa and sent the captains of the armies which he had against the cities of Israel and smote Ijon, Dan, Abel-*_beth_*-maachah, and all Cinneroth, with all the land of Naphtali.
* `1Ki 16:34` In his days, Hiel of *_Beth_*-el built Jericho. He laid its foundation with the loss of Abiram his first-born and set up its gates with the loss of his youngest son Segub, according to the word of the LORD which he spoke by Joshua the son of Nun.
* `2Ki 2:2` And Elijah said to Elisha, "Stay here, I pray you, for the LORD has sent me to *_Beth_*-el." And Elisha said, "As the LORD lives and as your soul lives, I will not leave you." So they went down to *_Beth_*-el.
* `2Ki 2:3` And the sons of the prophets who were at *_Beth_*-el came forth to Elisha and said to him, "Do you know that the LORD will take away your master from your head today?" And he said, "Yes, I know it. Hold your peace."
* `2Ki 2:23` And he went up from there to *_Beth_*-el. And as he was going up by the way, little children came forth out of the city and mocked him and said to him, "Go up, you bald-head. Go up, you bald-head."
* `2Ki 10:29` Yet from the sins of Jeroboam the son of Nebat, who made Israel to sin, Jehu did not depart from after them, namely, the golden calves that were in *_Beth_*-el and that were in Dan.
* `2Ki 14:11` But Amaziah would not listen. Therefore, Jehoash king of Israel went up, and he and Amaziah king of Judah looked one another in the face at *_Beth_*-shemesh, which belongs to Judah.
* `2Ki 14:13` And Jehoash king of Israel took Amaziah king of Judah, the son of Jehoash the son of Ahaziah, at *_Beth_*-shemesh, and came to Jerusalem and broke down the wall of Jerusalem from the gate of Ephraim to the corner gate, four hundred cubits.
* `2Ki 15:29` In the days of Pekah king of Israel, Tiglath-pileser king of Assyria, came and took Ijon, Abel-*_beth_*-maachah, Janoah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naphtali, and carried them captive to Assyria.
* `2Ki 17:28` Then one of the priests whom they had carried away from Samaria came and dwelt in *_Beth_*-el and taught them how they should fear the LORD.
* `2Ki 23:4` And the king commanded Hilkiah the high priest, the priests of the second order, and the keepers of the door to bring forth out of the temple of the LORD all the vessels that were made for Baal, for the grove, and for all the host of heaven. And he burned them outside Jerusalem in the fields of Kidron and carried their ashes to *_Beth_*-el.
* `2Ki 23:15` Moreover, the altar that was at *_Beth_*-el and the high place which Jeroboam the son of Nebat, who made Israel to sin, had made, both that altar and the high place he broke down. Then he burned the high place and ground it to powder and burned the grove.
* `2Ki 23:17` Then he said, "What title is that which I see?" And the men of the city told him, "It is the sepulcher of the man of God who came from Judah and proclaimed these things that you have done against the altar of *_Beth_*-el."
* `2Ki 23:19` And all the houses of the high places that were in the cities of Samaria, which the kings of Israel had made to provoke the LORD to anger, Josiah took away and did to them according to all the acts that he had done in *_Beth_*-el.
* `1Ch 2:45` And the son of Shammai was Maon, and Maon was the father of *_Beth_*-zur.
* `1Ch 2:51` Salma the father of *_Beth_*-lehem, and Hareph the father of *_Beth_*-gader.
* `1Ch 2:54` The sons of Salma: *_Beth_*-lehem and the Netophathites, Ataroth-*_beth_*-joab, half of the Menahethites, and the Zorites.
* `1Ch 4:4` And Penuel the father of Gedor, and Ezer the father of Hushah. These are the sons of Hur, the first-born of Ephratah, the father of *_Beth_*-lehem.
* `1Ch 4:12` And Eshton begot *_Beth_*-rapha, Paseah, and Tehinnah the father of Ir-nahash. These are the men of Rechah.
* `1Ch 4:31` At *_Beth_*-marcaboth, Hazar-susim, at *_Beth_*-birei, and at Shaaraim. These were their cities until the reign of David.
* `1Ch 6:59` Ashan with its suburbs, *_Beth_*-shemesh with its suburbs.
* `1Ch 6:68` Jokmeam with its suburbs, *_Beth_*-horon with its suburbs,
* `1Ch 7:24` (And his daughter was Sherah, who built *_Beth_*-horon the nether and the upper and Uzzen-sherah.)
* `1Ch 7:28` And their possessions and habitations were *_Beth_*-el and its towns, and eastward Naaram, and westward Gezer with its towns, Shechem also and its towns, to Gaza and its towns,
* `1Ch 7:29` And by the borders of the children of Manasseh, *_Beth_*-shean and its towns, Taanach and its towns, Megiddo and its towns, and Dor and its towns. The children of Joseph the son of Israel dwelt in these.
* `1Ch 11:16` And David was then in the hold, and the Philistines' garrison was then at *_Beth_*-lehem.
* `1Ch 11:17` And David longed and said, "Oh that someone would give me drink of the water of the well of *_Beth_*-lehem that is at the gate!"
* `1Ch 11:18` And the three broke through the host of the Philistines and drew water out of the well of *_Beth_*-lehem that was by the gate, took it, and brought it to David. But David would not drink of it, but poured it out to the LORD,
* `1Ch 11:26` Also the valiant men of the armies were Asahel the brother of Joab, Elhanan the son of Dodo of *_Beth_*-lehem,
* `2Ch 8:5` Also he built *_Beth_*-horon the upper and *_Beth_*-horon the nether, fortified cities with walls, gates, and bars,
* `2Ch 11:6` He built even *_Beth_*-lehem, Etam, Tekoa,
* `2Ch 11:7` *_Beth_*-zur, Shocho, Adullam,
* `2Ch 13:19` And Abijah pursued Jeroboam and took cities from him: *_Beth_*-el with its towns, Jeshanah with its towns, and Ephron with its towns.
* `2Ch 25:13` But the soldiers of the army whom Amaziah sent back, so that they should not go with him to battle, fell upon the cities of Judah, from Samaria even to *_Beth_*-horon, and smote three thousand of them and took a large amount of plunder.
* `2Ch 25:21` So Joash the king of Israel went up, and they saw one another in the face, both he and Amaziah king of Judah, at *_Beth_*-shemesh, which belongs to Judah.
* `2Ch 25:23` And Joash the king of Israel took Amaziah king of Judah, the son of Joash, the son of Jehoahaz, at *_Beth_*-shemesh, and brought him to Jerusalem and broke down the wall of Jerusalem from the gate of Ephraim to the corner gate, four hundred cubits.
* `2Ch 28:18` The Philistines also had invaded the cities of the low country, and of the south of Judah, and had taken *_Beth_*-shemesh, Ajalon, Gederoth, Shocho with its villages, Timnah with its villages, and Gimzo with its villages, and they dwelt there.
* `Ezr 2:21` The children of *_Beth_*-lehem, one hundred and twenty-three;
* `Ezr 2:28` The men of *_Beth_*-el and Ai, two hundred and twenty-three;
* `Neh 3:14` But the dung-gate was repaired by Malchiah the son of Rechab, the ruler of part of *_Beth_*-haccerem. He built it, set up its doors, its locks, and its bars.
* `Neh 3:16` After him Nehemiah the son of Azbuk, the ruler of the half part of *_Beth_*-zur, repaired to the place over against the sepulchers of David, and to the pool that was made, and to the house of the mighty.
* `Neh 7:26` The men of *_Beth_*-lehem and Netophah, one hundred and eighty-eight;
* `Neh 7:28` The men of *_Beth_*-azmaveth, forty-two;
* `Neh 7:32` The men of *_Beth_*-el and Ai, one hundred and twenty-three;
* `Neh 11:26` At Jeshua, at Moladah, at *_Beth_*-phelet,
* `Neh 11:31` The children of Benjamin also dwelt from Geba, at Michmash, Aija, and *_Beth_*-el, and in their villages,
* `Jer 6:1` "O children of Benjamin, gather yourselves to flee out of the midst of Jerusalem, blow the trumpet in Tekoa, and set up a sign of fire in *_Beth_*-haccerem, for evil appears out of the north, even great destruction.
* `Jer 41:17` And they departed and dwelt in the habitation of Chimham, which is by *_Beth_*-lehem, to go to enter into Egypt
* `Jer 43:13` He shall also break the images of *_Beth_*-shemesh, which is in the land of Egypt, and the houses of the gods of the Egyptians he shall burn with fire."'"
* `Jer 48:13` And Moab shall be ashamed of Chemosh, as the house of Israel was ashamed of *_Beth_*-el their confidence.
* `Jer 48:22` Upon Dibon, upon Nebo, upon *_Beth_*-diblathaim,
* `Jer 48:23` Upon Kiriathaim, upon *_Beth_*-gamul, upon *_Beth_*-meon,
* `Ezk 25:9` Therefore behold, I will open the side of Moab from the cities, from his cities which are on his frontiers—*_Beth_*-jeshimoth, Baal-meon, and Kiriathaim—the glory of the country.
* `Hos 4:15` Though you, Israel, play the harlot, yet do not let Judah offend, and do not come to Gilgal, neither go up to *_Beth_*-aven, nor swear, 'The LORD lives.'
* `Hos 5:8` Blow the horn in Gibeah and the trumpet in Ramah. Cry aloud at *_Beth_*-aven, 'Behind you, O Benjamin.'
* `Hos 10:5` The inhabitants of Samaria shall fear because of the calves of *_Beth_*-aven. For its people shall mourn over it, and its priests shall tremble for it, for its glory, because it has departed from it.
* `Hos 10:14` Therefore a tumult shall arise among your people, and all your fortresses shall be plundered, as Shalman plundered *_Beth_*-arbel in the day of battle. The mother was dashed in pieces upon her children.
* `Hos 10:15` *_Beth_*-el shall do so to you because of your great wickedness. In a morning the king of Israel shall be utterly cut off."
* `Hos 12:4` He even had power over the angel and prevailed. He wept and made supplication to him. He found [God] in *_Beth_*-el, and there [God] spoke with us,
* `Amo 3:14` "For in the day that I visit the transgressions of Israel upon him, I will also visit the altars of *_Beth_*-el. And the horns of the altar shall be cut off and fall to the ground.
* `Amo 4:4` "Come to *_Beth_*-el and transgress. At Gilgal multiply transgression. Bring your sacrifices every morning and your tithes after three years.
* `Amo 5:5` But do not seek *_Beth_*-el nor enter into Gilgal, and do not pass to Beer-sheba, for Gilgal shall surely go into captivity and *_Beth_*-el shall come to nothing.
* `Amo 5:6` Seek the LORD and you shall live, lest he break out like fire in the house of Joseph and devour it and there be no one to quench it in *_Beth_*-el.
* `Amo 7:10` Then Amaziah the priest of *_Beth_*-el sent to Jeroboam king of Israel, saying, "Amos has conspired against you in the midst of the house of Israel. The land is not able to bear all his words.
* `Amo 7:13` But do not prophesy again anymore at *_Beth_*-el, for it is the king's chapel and it is the king's court."
* `Mic 1:11` Pass on, you inhabitant of Saphir, having your shame exposed. The inhabitant of Zaanan did not come forth in the mourning of *_Beth_*-ezel. He shall receive from you his standing.
* `Mic 5:2` "But you, *_Beth_*-lehem Ephratah, though you are little among the thousands of Judah, yet out of you he shall come forth to me who is to be ruler in Israel, whose goings forth have been from of old, from everlasting."
* `Zch 7:2` When those of *_Beth_*-el had sent Sherezer, Regem-melech, and their men to pray before the LORD

_198 verses containing BETH_

== BETH-ANATH

* `Jsh 19:38` Iron, Migdal-el, Horem, *_Beth-anath_*, and Beth-shemesh; nineteen cities with their villages.
* `Jdg 1:33` Naphtali did not expel the inhabitants of Beth-shemesh nor the inhabitants of *_Beth-anath_*, but he dwelt among the Canaanites, the inhabitants of the land. Nevertheless, the inhabitants of Beth-shemesh and of *_Beth-anath_* became tributaries to them.

_2 verses containing BETH-ANATH_

== BETH-ANOTH

* `Jsh 15:59` Maarath, *_Beth-anoth_*, and Eltekon; six cities with their villages.

_1 verse containing BETH-ANOTH_

== BETH-ARABAH

* `Jsh 15:6` And the border went up to Beth-hogla, and passed along by the north of *_Beth-arabah_*. And the border went up to the stone of Bohan the son of Reuben.
* `Jsh 15:61` In the wilderness, *_Beth-arabah_*, Middin, Secacah,
* `Jsh 18:22` *_Beth-arabah_*, Zemaraim, Beth-el,

_3 verses containing BETH-ARABAH_

== BETH-ARAM

* `Jsh 13:27` And in the valley, *_Beth-aram_*, Beth-nimrah, Succoth, and Zaphon, the rest of the kingdom of Sihon king of Heshbon, the Jordan and its border, even to the edge of the sea of Cinneroth, on the other side of the Jordan eastward.

_1 verse containing BETH-ARAM_

== BETH-ARBEL

* `Hos 10:14` Therefore a tumult shall arise among your people, and all your fortresses shall be plundered, as Shalman plundered *_Beth-arbel_* in the day of battle. The mother was dashed in pieces upon her children.

_1 verse containing BETH-ARBEL_

== BETH-AVEN

* `Jsh 7:2` And Joshua sent men from Jericho to Ai, which is beside *_Beth-aven_*, on the east side of Beth-el, and spoke to them, saying, "Go up and view the country." And the men went up and viewed Ai.
* `Jsh 18:12` And their border on the north side was from the Jordan, and the border went up to the side of Jericho on the north side and went up through the mountains westward. And its limits were at the wilderness of *_Beth-aven_*.
* `1Sa 13:5` And the Philistines assembled to fight with Israel: thirty thousand chariots, six thousand horsemen, and people as the sand which is on the sea shore in multitude. And they came up and encamped in Michmash, eastward from *_Beth-aven_*.
* `1Sa 14:23` So the LORD saved Israel that day. And the battle passed over to *_Beth-aven_*.
* `Hos 4:15` Though you, Israel, play the harlot, yet do not let Judah offend, and do not come to Gilgal, neither go up to *_Beth-aven_*, nor swear, 'The LORD lives.'
* `Hos 5:8` Blow the horn in Gibeah and the trumpet in Ramah. Cry aloud at *_Beth-aven_*, 'Behind you, O Benjamin.'
* `Hos 10:5` The inhabitants of Samaria shall fear because of the calves of *_Beth-aven_*. For its people shall mourn over it, and its priests shall tremble for it, for its glory, because it has departed from it.

_7 verses containing BETH-AVEN_

== BETH-AZMAVETH

* `Neh 7:28` The men of *_Beth-azmaveth_*, forty-two;

_1 verse containing BETH-AZMAVETH_

== BETH-BAAL-MEON

* `Jsh 13:17` Heshbon, and all her cities that are in the plain: Dibon, Bamoth-baal, *_Beth-baal-meon_*,

_1 verse containing BETH-BAAL-MEON_

== BETH-BARAH

* `Jdg 7:24` And Gideon sent messengers throughout all mount Ephraim, saying, "Come down against the Midianites and take the waters before them to *_Beth-barah_* and the Jordan." Then all the men of Ephraim assembled and took the waters to *_Beth-barah_* and the Jordan.

_1 verse containing BETH-BARAH_

== BETH-BIREI

* `1Ch 4:31` At Beth-marcaboth, Hazar-susim, at *_Beth-birei_*, and at Shaaraim. These were their cities until the reign of David.

_1 verse containing BETH-BIREI_

== BETH-CAR

* `1Sa 7:11` And the men of Israel went out of Mizpeh, pursued the Philistines, and smote them until they came under *_Beth-car_*.

_1 verse containing BETH-CAR_

== BETH-DAGON

* `Jsh 15:41` Gederoth, *_Beth-dagon_*, Naamah, and Makkedah; sixteen cities with their villages.
* `Jsh 19:27` And turns toward the sunrise to *_Beth-dagon_*, and reaches to Zebulun, and to the valley of Jiphthah-el toward the north side of Beth-emek, and Neiel, and goes out to Cabul on the left hand,

_2 verses containing BETH-DAGON_

== BETH-DIBLATHAIM

* `Jer 48:22` Upon Dibon, upon Nebo, upon *_Beth-diblathaim_*,

_1 verse containing BETH-DIBLATHAIM_

== BETH-EL

* `Gen 12:8` And he departed from there to a mountain on the east of *_Beth-el_* and pitched his tent, having *_Beth-el_* on the west and Hai on the east. And there he erected an altar to the LORD and called upon the name of the LORD.
* `Gen 13:3` And he went on his journeys from the south even to *_Beth-el_* to the place where his tent had been at the beginning, between *_Beth-el_* and Hai,
* `Gen 28:19` And he called the name of that place *_Beth-el_*, but the name of that city was called Luz at the first.
* `Gen 31:13` I am the God of *_Beth-el_*, where you anointed the pillar and where you vowed to me a vow. Now arise, depart from this land, and return to the land of your kindred.'"
* `Gen 35:1` And God said to Jacob, "Arise, go up to *_Beth-el_* and dwell there. And make there an altar to God, who appeared to you when you fled from the face of Esau your brother."
* `Gen 35:3` And let us arise and go up to *_Beth-el_*. And I will make there an altar to God, who answered me in the day of my distress and was with me in the way which I went."
* `Gen 35:6` So Jacob came to Luz, which is in the land of Canaan (that is *_Beth-el_*)—he and all the people who were with him.
* `Gen 35:7` And he erected there an altar and called the place El-*_beth-el_* because there God appeared to him when he fled from the face of his brother.
* `Gen 35:8` But Deborah, Rebekah's nurse, died, and she was buried beneath *_Beth-el_* under an oak. And its name was called Allon-bachuth.
* `Gen 35:15` And Jacob called the name of the place where God spoke with him *_Beth-el_*.
* `Gen 35:16` And they journeyed from *_Beth-el_*. And there was only a little distance to come to Ephrath, and Rachel travailed and had hard labor.
* `Jsh 7:2` And Joshua sent men from Jericho to Ai, which is beside Beth-aven, on the east side of *_Beth-el_*, and spoke to them, saying, "Go up and view the country." And the men went up and viewed Ai.
* `Jsh 8:9` Joshua therefore sent them forth. And they went to lie in ambush and stayed between *_Beth-el_* and Ai on the west side of Ai, but Joshua lodged that night among the people.
* `Jsh 8:12` And he took about five thousand men and set them to lie in ambush between *_Beth-el_* and Ai on the west side of the city.
* `Jsh 8:17` And there was not a man left in Ai or *_Beth-el_* who did not go out after Israel. And they left the city open and pursued Israel.
* `Jsh 12:9` The king of Jericho one; the king of Ai, which is beside *_Beth-el_*, one;
* `Jsh 12:16` The king of Makkedah, one; the king of *_Beth-el_*, one;
* `Jsh 16:1` And the lot of the children of Joseph fell from the Jordan by Jericho, to the water of Jericho on the east, to the wilderness that goes up from Jericho throughout mount *_Beth-el_*,
* `Jsh 16:2` And goes out from *_Beth-el_* to Luz, and passes along to the borders of Archi to Ataroth,
* `Jsh 18:13` And the border went over from there toward Luz, to the side of Luz (which is *_Beth-el_*) southward. And the border descended to Ataroth-adar, near the hill that lies on the south side of the nether Beth-horon.
* `Jsh 18:22` Beth-arabah, Zemaraim, *_Beth-el_*,
* `Jdg 1:22` And the house of Joseph, they also went up against *_Beth-el_*, and the LORD was with them.
* `Jdg 1:23` And the house of Joseph sent to explore *_Beth-el_*. Now the name of the city was formerly Luz.
* `Jdg 4:5` And she dwelt under the palm-tree of Deborah between Ramah and *_Beth-el_* in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `Jdg 21:19` Then they said, "Behold, there is a yearly feast of the LORD in Shiloh in a place which is on the north side of *_Beth-el_*, on the east side of the highway that goes up from *_Beth-el_* to Shechem, and on the south of Lebonah."
* `1Sa 7:16` And he went from year to year in circuit to *_Beth-el_*, Gilgal, and Mizpeh, and judged Israel in all those places.
* `1Sa 10:3` Then you shall go on forward from there and shall come to the plain of Tabor, and three men going up to God at *_Beth-el_* shall meet you there: one carrying three kids, another carrying three loaves of bread, and another carrying a bottle of wine.
* `1Sa 13:2` Saul chose for himself three thousand men of Israel, of which two thousand were with Saul in Michmash and in the mountains of *_Beth-el_*, and one thousand were with Jonathan in Gibeah of Benjamin. And the rest of the people he sent each to his tent.
* `1Sa 30:27` To those who were in *_Beth-el_*, to those who were in south Ramoth, to those who were in Jattir,
* `1Ki 12:29` And he set one in *_Beth-el_* and the other he placed in Dan.
* `1Ki 12:32` And Jeroboam ordained a feast in the eighth month, on the fifteenth day of the month, like the feast that is in Judah, and he offered upon the altar. Thus he did in *_Beth-el_*, sacrificing to the calves that he had made. And he placed in *_Beth-el_* the priests of the high places which he had made.
* `1Ki 12:33` So he offered upon the altar which he had made in *_Beth-el_* on the fifteenth day of the eighth month, even in the month which he had devised in his own heart. And he ordained a feast to the children of Israel and he offered upon the altar and burned incense.
* `1Ki 13:1` And behold, there came a man of God out of Judah by the word of the LORD to *_Beth-el_*. And Jeroboam stood by the altar to burn incense.
* `1Ki 13:4` And it came to pass when king Jeroboam heard the saying of the man of God who had cried against the altar in *_Beth-el_*, that he put forth his hand from the altar, saying, "Lay hold upon him." And his hand, which he put forth against him, dried up so that he could not draw it to him again.
* `1Ki 13:10` So he went another way and did not return by the way that he came to *_Beth-el_*.
* `1Ki 13:11` Now there dwelt an old prophet in *_Beth-el_*. And his sons came and told him all the works that the man of God had done that day in *_Beth-el_*. The words which he had spoken to the king, they also told them to their father.
* `1Ki 13:32` For the saying which he cried by the word of the LORD against the altar in *_Beth-el_* and against all the houses of the high places which are in the cities of Samaria shall surely come to pass."
* `1Ki 16:34` In his days, Hiel of *_Beth-el_* built Jericho. He laid its foundation with the loss of Abiram his first-born and set up its gates with the loss of his youngest son Segub, according to the word of the LORD which he spoke by Joshua the son of Nun.
* `2Ki 2:2` And Elijah said to Elisha, "Stay here, I pray you, for the LORD has sent me to *_Beth-el_*." And Elisha said, "As the LORD lives and as your soul lives, I will not leave you." So they went down to *_Beth-el_*.
* `2Ki 2:3` And the sons of the prophets who were at *_Beth-el_* came forth to Elisha and said to him, "Do you know that the LORD will take away your master from your head today?" And he said, "Yes, I know it. Hold your peace."
* `2Ki 2:23` And he went up from there to *_Beth-el_*. And as he was going up by the way, little children came forth out of the city and mocked him and said to him, "Go up, you bald-head. Go up, you bald-head."
* `2Ki 10:29` Yet from the sins of Jeroboam the son of Nebat, who made Israel to sin, Jehu did not depart from after them, namely, the golden calves that were in *_Beth-el_* and that were in Dan.
* `2Ki 17:28` Then one of the priests whom they had carried away from Samaria came and dwelt in *_Beth-el_* and taught them how they should fear the LORD.
* `2Ki 23:4` And the king commanded Hilkiah the high priest, the priests of the second order, and the keepers of the door to bring forth out of the temple of the LORD all the vessels that were made for Baal, for the grove, and for all the host of heaven. And he burned them outside Jerusalem in the fields of Kidron and carried their ashes to *_Beth-el_*.
* `2Ki 23:15` Moreover, the altar that was at *_Beth-el_* and the high place which Jeroboam the son of Nebat, who made Israel to sin, had made, both that altar and the high place he broke down. Then he burned the high place and ground it to powder and burned the grove.
* `2Ki 23:17` Then he said, "What title is that which I see?" And the men of the city told him, "It is the sepulcher of the man of God who came from Judah and proclaimed these things that you have done against the altar of *_Beth-el_*."
* `2Ki 23:19` And all the houses of the high places that were in the cities of Samaria, which the kings of Israel had made to provoke the LORD to anger, Josiah took away and did to them according to all the acts that he had done in *_Beth-el_*.
* `1Ch 7:28` And their possessions and habitations were *_Beth-el_* and its towns, and eastward Naaram, and westward Gezer with its towns, Shechem also and its towns, to Gaza and its towns,
* `2Ch 13:19` And Abijah pursued Jeroboam and took cities from him: *_Beth-el_* with its towns, Jeshanah with its towns, and Ephron with its towns.
* `Ezr 2:28` The men of *_Beth-el_* and Ai, two hundred and twenty-three;
* `Neh 7:32` The men of *_Beth-el_* and Ai, one hundred and twenty-three;
* `Neh 11:31` The children of Benjamin also dwelt from Geba, at Michmash, Aija, and *_Beth-el_*, and in their villages,
* `Jer 48:13` And Moab shall be ashamed of Chemosh, as the house of Israel was ashamed of *_Beth-el_* their confidence.
* `Hos 10:15` *_Beth-el_* shall do so to you because of your great wickedness. In a morning the king of Israel shall be utterly cut off."
* `Hos 12:4` He even had power over the angel and prevailed. He wept and made supplication to him. He found [God] in *_Beth-el_*, and there [God] spoke with us,
* `Amo 3:14` "For in the day that I visit the transgressions of Israel upon him, I will also visit the altars of *_Beth-el_*. And the horns of the altar shall be cut off and fall to the ground.
* `Amo 4:4` "Come to *_Beth-el_* and transgress. At Gilgal multiply transgression. Bring your sacrifices every morning and your tithes after three years.
* `Amo 5:5` But do not seek *_Beth-el_* nor enter into Gilgal, and do not pass to Beer-sheba, for Gilgal shall surely go into captivity and *_Beth-el_* shall come to nothing.
* `Amo 5:6` Seek the LORD and you shall live, lest he break out like fire in the house of Joseph and devour it and there be no one to quench it in *_Beth-el_*.
* `Amo 7:10` Then Amaziah the priest of *_Beth-el_* sent to Jeroboam king of Israel, saying, "Amos has conspired against you in the midst of the house of Israel. The land is not able to bear all his words.
* `Amo 7:13` But do not prophesy again anymore at *_Beth-el_*, for it is the king's chapel and it is the king's court."
* `Zch 7:2` When those of *_Beth-el_* had sent Sherezer, Regem-melech, and their men to pray before the LORD

_62 verses containing BETH-EL_

== BETH-EMEK

* `Jsh 19:27` And turns toward the sunrise to Beth-dagon, and reaches to Zebulun, and to the valley of Jiphthah-el toward the north side of *_Beth-emek_*, and Neiel, and goes out to Cabul on the left hand,

_1 verse containing BETH-EMEK_

== BETH-EZEL

* `Mic 1:11` Pass on, you inhabitant of Saphir, having your shame exposed. The inhabitant of Zaanan did not come forth in the mourning of *_Beth-ezel_*. He shall receive from you his standing.

_1 verse containing BETH-EZEL_

== BETH-GADER

* `1Ch 2:51` Salma the father of Beth-lehem, and Hareph the father of *_Beth-gader_*.

_1 verse containing BETH-GADER_

== BETH-GAMUL

* `Jer 48:23` Upon Kiriathaim, upon *_Beth-gamul_*, upon Beth-meon,

_1 verse containing BETH-GAMUL_

== BETH-HACCEREM

* `Neh 3:14` But the dung-gate was repaired by Malchiah the son of Rechab, the ruler of part of *_Beth-haccerem_*. He built it, set up its doors, its locks, and its bars.
* `Jer 6:1` "O children of Benjamin, gather yourselves to flee out of the midst of Jerusalem, blow the trumpet in Tekoa, and set up a sign of fire in *_Beth-haccerem_*, for evil appears out of the north, even great destruction.

_2 verses containing BETH-HACCEREM_

== BETH-HARAN

* `Num 32:36` Beth-nimrah, and *_Beth-haran_*—fortified cities—and folds for sheep.

_1 verse containing BETH-HARAN_

== BETH-HOGLA

* `Jsh 15:6` And the border went up to *_Beth-hogla_*, and passed along by the north of Beth-arabah. And the border went up to the stone of Bohan the son of Reuben.

_1 verse containing BETH-HOGLA_

== BETH-HOGLAH

* `Jsh 18:19` And the border passed along to the side of *_Beth-hoglah_* northward. And the limits of the border were at the north bay of the Salt Sea at the south end of the Jordan. This was the south border.
* `Jsh 18:21` Now the cities of the tribe of the children of Benjamin, according to their families, were Jericho, *_Beth-hoglah_*, the valley of Keziz,

_2 verses containing BETH-HOGLAH_

== BETH-HORON

* `Jsh 10:10` And the LORD completely defeated them before Israel, slew them with a great slaughter at Gibeon, chased them along the way that goes up to *_Beth-horon_*, and smote them to Azekah and to Makkedah.
* `Jsh 10:11` And it came to pass as they fled from before Israel and were in the descent to *_Beth-horon_*, that the LORD cast down great stones from heaven upon them to Azekah, and they died. There were more who died with hailstones than those whom the children of Israel slew with the sword.
* `Jsh 16:3` And goes down westward to the border of Japhleti, to the border of *_Beth-horon_* the nether, and to Gezer, and its limits are at the sea.
* `Jsh 16:5` And the border of the children of Ephraim according to their families was this: even the border of their inheritance on the east side was Ataroth-adar, to *_Beth-horon_* the upper,
* `Jsh 18:13` And the border went over from there toward Luz, to the side of Luz (which is Beth-el) southward. And the border descended to Ataroth-adar, near the hill that lies on the south side of the nether *_Beth-horon_*.
* `Jsh 18:14` And the border was drawn from there and compassed the corner of the sea southward from the hill that lies before *_Beth-horon_* southward. And its limits were at Kirjath-baal (which is Kirjath-jearim), a city of the children of Judah. This was the west quarter.
* `Jsh 21:22` Kibzaim with its suburbs, and *_Beth-horon_* with its suburbs; four cities.
* `1Sa 13:18` Another company turned the way to *_Beth-horon_*, and another company turned to the way of the border that looks to the valley of Zeboim toward the wilderness.
* `1Ki 9:17` And Solomon built Gezer, *_Beth-horon_* the nether,
* `1Ch 6:68` Jokmeam with its suburbs, *_Beth-horon_* with its suburbs,
* `1Ch 7:24` (And his daughter was Sherah, who built *_Beth-horon_* the nether and the upper and Uzzen-sherah.)
* `2Ch 8:5` Also he built *_Beth-horon_* the upper and *_Beth-horon_* the nether, fortified cities with walls, gates, and bars,
* `2Ch 25:13` But the soldiers of the army whom Amaziah sent back, so that they should not go with him to battle, fell upon the cities of Judah, from Samaria even to *_Beth-horon_*, and smote three thousand of them and took a large amount of plunder.

_13 verses containing BETH-HORON_

== BETH-JESHIMOTH

* `Num 33:49` And they encamped by the Jordan, from *_Beth-jeshimoth_* even to Abel-shittim in the plains of Moab.
* `Jsh 12:3` And from the plain to the sea of Cinneroth on the east and to the sea of the plain, even the Salt Sea on the east, the way to *_Beth-jeshimoth_*; and from the south, under Ashdoth-pisgah;
* `Jsh 13:20` Beth-peor, Ashdoth-pisgah, *_Beth-jeshimoth_*,
* `Ezk 25:9` Therefore behold, I will open the side of Moab from the cities, from his cities which are on his frontiers—*_Beth-jeshimoth_*, Baal-meon, and Kiriathaim—the glory of the country.

_4 verses containing BETH-JESHIMOTH_

== BETH-LEBAOTH

* `Jsh 19:6` *_Beth-lebaoth_*, and Sheruhen; thirteen cities and their villages;

_1 verse containing BETH-LEBAOTH_

== BETH-LEHEM

* `Gen 35:19` And Rachel died and was buried on the way to Ephrath, which is *_Beth-lehem_*.
* `Gen 48:7` And as for me, when I came from Padan, Rachel died beside me in the land of Canaan, on the way when there was only a little distance to come to Ephrath, and I buried her there on the way of Ephrath (the same is *_Beth-lehem_*)."
* `Jsh 19:15` And Kattath, Nahallal, Shimron, Idalah, and *_Beth-lehem_*; twelve cities with their villages.
* `Jdg 12:8` And after him Ibzan of *_Beth-lehem_* judged Israel.
* `Jdg 12:10` Then Ibzan died and was buried at *_Beth-lehem_*.
* `Jdg 17:7` And there was a young man out of *_Beth-lehem_*-judah of the family of Judah, who was a Levite, and he sojourned there.
* `Jdg 17:8` And the man departed out of the city from *_Beth-lehem_*-judah to sojourn where he could find a place. And he came to mount Ephraim to the house of Micah as he journeyed.
* `Jdg 17:9` And Micah said to him, "Where do you come from?" And he said to him, "I am a Levite from *_Beth-lehem_*-judah and I go to sojourn where I may find a place."
* `Jdg 19:1` And it came to pass in those days when there was no king in Israel, that there was a certain Levite dwelling on the side of mount Ephraim, who took for himself a concubine out of *_Beth-lehem_*-judah.
* `Jdg 19:2` And his concubine played the harlot against him and went away from him to her father's house to *_Beth-lehem_*-judah, and was there for four whole months.
* `Jdg 19:18` And he said to him, "We are passing from *_Beth-lehem_*-Judah toward the side of mount Ephraim. I am from there. And I went to *_Beth-lehem_*-judah, but I am now going to the house of the LORD. And there is no man who receives me into his house.
* `Rth 1:1` Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of *_Beth-lehem_*-judah went to dwell in the country of Moab—he, his wife, and his two sons.
* `Rth 1:2` And the name of the man was Elimelech, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of *_Beth-lehem_*-judah. And they came into the country of Moab and continued there.
* `Rth 1:19` So the two of them went until they came to *_Beth-lehem_*. And it came to pass, when they had come to *_Beth-lehem_*, that all the city was stirred because of them, and they said, "Is this Naomi?"
* `Rth 1:22` So Naomi returned, and Ruth the Moabitess her daughter-in-law with her, who returned from the country of Moab. And they came to *_Beth-lehem_* in the beginning of barley-harvest.
* `Rth 2:4` And behold, Boaz came from *_Beth-lehem_* and said to the reapers, "May the LORD be with you." And they answered him, "May the LORD bless you."
* `Rth 4:11` And all the people who were in the gate and the elders said, "We are witnesses. May the LORD make the woman who has come into your house like Rachel and like Leah, both of whom built the house of Israel. And may you do worthily in Ephratah and be famous in *_Beth-lehem_*.
* `1Sa 16:4` And Samuel did that which the LORD spoke and came to *_Beth-lehem_*. And the elders of the town trembled at his coming and said, "Do you come peaceably?"
* `1Sa 17:12` Now David was the son of that Ephrathite of *_Beth-lehem_*-judah, whose name was Jesse, who had eight sons and was an old man in the days of Saul and aged among men.
* `1Sa 17:15` But David went and returned from Saul to feed his father's sheep at *_Beth-lehem_*.
* `1Sa 20:6` If your father at all misses me, then say, 'David earnestly asked leave of me so that he might run to *_Beth-lehem_* his city, for there is a yearly sacrifice there for all the family.'
* `1Sa 20:28` And Jonathan answered Saul, "David earnestly asked leave of me to go to *_Beth-lehem_*.
* `2Sa 2:32` And they took up Asahel and buried him in the sepulcher of his father, which was in *_Beth-lehem_*. And Joab and his men went all night and came to Hebron at the break of day.
* `2Sa 23:14` And David was then in a hold, and the garrison of the Philistines was then in *_Beth-lehem_*.
* `2Sa 23:15` And David longed and said, "Oh that someone would give me a drink of the water from the well of *_Beth-lehem_* which is by the gate!"
* `2Sa 23:16` And the three mighty men broke through the host of the Philistines, drew water out of the well of *_Beth-lehem_* that was by the gate, took it, and brought it to David. Nevertheless, he would not drink it, but poured it out to the LORD.
* `2Sa 23:24` Asahel the brother of Joab was one of the thirty, along with Elhanan the son of Dodo of *_Beth-lehem_*,
* `1Ch 2:51` Salma the father of *_Beth-lehem_*, and Hareph the father of Beth-gader.
* `1Ch 2:54` The sons of Salma: *_Beth-lehem_* and the Netophathites, Ataroth-beth-joab, half of the Menahethites, and the Zorites.
* `1Ch 4:4` And Penuel the father of Gedor, and Ezer the father of Hushah. These are the sons of Hur, the first-born of Ephratah, the father of *_Beth-lehem_*.
* `1Ch 11:16` And David was then in the hold, and the Philistines' garrison was then at *_Beth-lehem_*.
* `1Ch 11:17` And David longed and said, "Oh that someone would give me drink of the water of the well of *_Beth-lehem_* that is at the gate!"
* `1Ch 11:18` And the three broke through the host of the Philistines and drew water out of the well of *_Beth-lehem_* that was by the gate, took it, and brought it to David. But David would not drink of it, but poured it out to the LORD,
* `1Ch 11:26` Also the valiant men of the armies were Asahel the brother of Joab, Elhanan the son of Dodo of *_Beth-lehem_*,
* `2Ch 11:6` He built even *_Beth-lehem_*, Etam, Tekoa,
* `Ezr 2:21` The children of *_Beth-lehem_*, one hundred and twenty-three;
* `Neh 7:26` The men of *_Beth-lehem_* and Netophah, one hundred and eighty-eight;
* `Jer 41:17` And they departed and dwelt in the habitation of Chimham, which is by *_Beth-lehem_*, to go to enter into Egypt
* `Mic 5:2` "But you, *_Beth-lehem_* Ephratah, though you are little among the thousands of Judah, yet out of you he shall come forth to me who is to be ruler in Israel, whose goings forth have been from of old, from everlasting."

_39 verses containing BETH-LEHEM_

== BETH-LEHEM-JUDAH

* `Jdg 17:7` And there was a young man out of *_Beth-lehem-judah_* of the family of Judah, who was a Levite, and he sojourned there.
* `Jdg 17:8` And the man departed out of the city from *_Beth-lehem-judah_* to sojourn where he could find a place. And he came to mount Ephraim to the house of Micah as he journeyed.
* `Jdg 17:9` And Micah said to him, "Where do you come from?" And he said to him, "I am a Levite from *_Beth-lehem-judah_* and I go to sojourn where I may find a place."
* `Jdg 19:1` And it came to pass in those days when there was no king in Israel, that there was a certain Levite dwelling on the side of mount Ephraim, who took for himself a concubine out of *_Beth-lehem-judah_*.
* `Jdg 19:2` And his concubine played the harlot against him and went away from him to her father's house to *_Beth-lehem-judah_*, and was there for four whole months.
* `Jdg 19:18` And he said to him, "We are passing from *_Beth-lehem-Judah_* toward the side of mount Ephraim. I am from there. And I went to *_Beth-lehem-judah_*, but I am now going to the house of the LORD. And there is no man who receives me into his house.
* `Rth 1:1` Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of *_Beth-lehem-judah_* went to dwell in the country of Moab—he, his wife, and his two sons.
* `Rth 1:2` And the name of the man was Elimelech, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of *_Beth-lehem-judah_*. And they came into the country of Moab and continued there.
* `1Sa 17:12` Now David was the son of that Ephrathite of *_Beth-lehem-judah_*, whose name was Jesse, who had eight sons and was an old man in the days of Saul and aged among men.

_9 verses containing BETH-LEHEM-JUDAH_

== BETH-LEHEMITE

* `1Sa 16:1` And the LORD said to Samuel, "How long will you mourn for Saul, seeing I have rejected him from reigning over Israel? Fill your horn with oil and go, I will send you to Jesse the *_Beth-lehemite_*, for I have provided myself a king among his sons."
* `1Sa 16:18` Then one of the servants answered and said, "Behold, I have seen a son of Jesse the *_Beth-lehemite_* who is skillful in playing, a mighty valiant man, a man of war, prudent in matters, and a handsome person, and the LORD is with him."
* `1Sa 17:58` And Saul said to him, "Whose son are you, young man?" And David answered, "I am the son of your servant Jesse the *_Beth-lehemite_*."
* `2Sa 21:19` And there was again a battle in Gob with the Philistines where Elhanan the son of Jaareoregim, a *_Beth-lehemite_*, slew the brother of Goliath the Gittite, the staff of whose spear was like a weaver's beam.

_4 verses containing BETH-LEHEMITE_

== BETH-MAACHAH

* `2Sa 20:14` And he went through all the tribes of Israel to Abel of *_Beth-maachah_* and all the Berites. And they were assembled and also went after him.
* `2Sa 20:15` And they came and besieged him in Abel of *_Beth-maachah_* and cast up a siege-mound against the city, and it stood in the trench. And all the people who were with Joab battered the wall to throw it down.
* `1Ki 15:20` So Ben-hadad listened to king Asa and sent the captains of the armies which he had against the cities of Israel and smote Ijon, Dan, Abel-*_beth-maachah_*, and all Cinneroth, with all the land of Naphtali.
* `2Ki 15:29` In the days of Pekah king of Israel, Tiglath-pileser king of Assyria, came and took Ijon, Abel-*_beth-maachah_*, Janoah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naphtali, and carried them captive to Assyria.

_4 verses containing BETH-MAACHAH_

== BETH-MARCABOTH

* `Jsh 19:5` Ziklag, *_Beth-marcaboth_*, Hazar-susah,
* `1Ch 4:31` At *_Beth-marcaboth_*, Hazar-susim, at Beth-birei, and at Shaaraim. These were their cities until the reign of David.

_2 verses containing BETH-MARCABOTH_

== BETH-MEON

* `Jer 48:23` Upon Kiriathaim, upon Beth-gamul, upon *_Beth-meon_*,

_1 verse containing BETH-MEON_

== BETH-MERHAK

* `2Sa 15:17` And the king went forth, and all the people followed him, and they stayed in *_Beth-merhak_*.

_1 verse containing BETH-MERHAK_

== BETH-NIMRAH

* `Num 32:36` *_Beth-nimrah_*, and Beth-haran—fortified cities—and folds for sheep.
* `Jsh 13:27` And in the valley, Beth-aram, *_Beth-nimrah_*, Succoth, and Zaphon, the rest of the kingdom of Sihon king of Heshbon, the Jordan and its border, even to the edge of the sea of Cinneroth, on the other side of the Jordan eastward.

_2 verses containing BETH-NIMRAH_

== BETH-PALET

* `Jsh 15:27` Hazar-gaddah, Heshmon, *_Beth-palet_*,

_1 verse containing BETH-PALET_

== BETH-PAZZEZ

* `Jsh 19:21` Remeth, En-gannim, En-haddah, and *_Beth-pazzez_*;

_1 verse containing BETH-PAZZEZ_

== BETH-PEOR

* `Deu 3:29` So we stayed in the valley over against *_Beth-peor_*."
* `Deu 4:46` On the east side of the Jordan, in the valley over against *_Beth-Peor_*, in the land of Sihon king of the Amorites, who dwelt at Heshbon, whom Moses and the children of Israel smote after they had come forth from Egypt.
* `Deu 34:6` And he buried him in a valley in the land of Moab, over against *_Beth-peor_*. But no man knows of his sepulcher to this day.
* `Jsh 13:20` *_Beth-peor_*, Ashdoth-pisgah, Beth-jeshimoth,

_4 verses containing BETH-PEOR_

== BETH-PHELET

* `Neh 11:26` At Jeshua, at Moladah, at *_Beth-phelet_*,

_1 verse containing BETH-PHELET_

== BETH-RAPHA

* `1Ch 4:12` And Eshton begot *_Beth-rapha_*, Paseah, and Tehinnah the father of Ir-nahash. These are the men of Rechah.

_1 verse containing BETH-RAPHA_

== BETH-REHOB

* `Jdg 18:28` And there was no deliverer because it was far from Zidon and they had no business with any man. And it was in the valley that lies by *_Beth-rehob_*. And they built a city and dwelt in it.
* `2Sa 10:6` And when the children of Ammon saw that they had made themselves odious before David, the children of Ammon sent and hired the Syrians of *_Beth-rehob_* and the Syrians of Zoba, twenty thousand footmen, and one thousand men from the king of Maacah and twelve thousand men from the men of Tob.

_2 verses containing BETH-REHOB_

== BETH-SHAN

* `1Sa 31:10` And they put his armor in the house of Ashtaroth and fastened his body to the wall of *_Beth-shan_*.
* `1Sa 31:12` All the valiant men arose and went all night, took the body of Saul and the bodies of his sons from the wall of *_Beth-shan_*, and came to Jabesh and burnt them there.
* `2Sa 21:12` And David went and took the bones of Saul and the bones of Jonathan his son from the men of Jabesh-gilead who had stolen them from the street of *_Beth-shan_*, where the Philistines had hanged them when the Philistines had slain Saul in Gilboa.

_3 verses containing BETH-SHAN_

== BETH-SHEAN

* `Jsh 17:11` And in Issachar and in Asher, Manasseh had *_Beth-shean_* and its towns, Ibleam and its towns, the inhabitants of Dor and its towns, the inhabitants of En-dor and its towns, the inhabitants of Tanach and its towns, and the inhabitants of Megiddo and its towns, even three countries.
* `Jsh 17:16` And the children of Joseph said, "The hill is not enough for us. And all the Canaanites who dwell in the land of the valley have chariots of iron—both those who are of *_Beth-shean_* and its towns, and those who are of the valley of Jezreel."
* `Jdg 1:27` Manasseh did not expel the inhabitants of *_Beth-shean_* and its towns, nor Tanach and its towns, nor the inhabitants of Dor and its towns, nor the inhabitants of Ibleam and its towns, nor the inhabitants of Megiddo and its towns, but the Canaanites would dwell in that land.
* `1Ki 4:12` Baana the son of Ahilud—to him pertained Taanach, Megiddo, and all *_Beth-shean_*, which is by Zartanah beneath Jezreel, from *_Beth-shean_* to Abel-meholah, even to the place that is beyond Jokneam;
* `1Ch 7:29` And by the borders of the children of Manasseh, *_Beth-shean_* and its towns, Taanach and its towns, Megiddo and its towns, and Dor and its towns. The children of Joseph the son of Israel dwelt in these.

_5 verses containing BETH-SHEAN_

== BETH-SHEMESH

* `Jsh 15:10` And the border compassed from Baalah westward to mount Seir, passed along to the side of mount Jearim (which is Chesalon) on the north side, went down to *_Beth-shemesh_*, and passed on to Timnah.
* `Jsh 19:22` And the border reaches to Tabor, Shahazimah, and *_Beth-shemesh_*, and the limits of their border were at the Jordan; sixteen cities with their villages.
* `Jsh 19:38` Iron, Migdal-el, Horem, Beth-anath, and *_Beth-shemesh_*; nineteen cities with their villages.
* `Jsh 21:16` Ain with its suburbs, Juttah with its suburbs, and *_Beth-shemesh_* with its suburbs; nine cities out of those two tribes.
* `Jdg 1:33` Naphtali did not expel the inhabitants of *_Beth-shemesh_* nor the inhabitants of Beth-anath, but he dwelt among the Canaanites, the inhabitants of the land. Nevertheless, the inhabitants of *_Beth-shemesh_* and of Beth-anath became tributaries to them.
* `1Sa 6:9` And behold, if it goes up by the way of his own border to *_Beth-shemesh_*, then he has done us this great evil, but if not, then we shall know that it is not his hand that smote us. It was a chance that happened to us."
* `1Sa 6:12` And the cows took the straight way to the way of *_Beth-shemesh_* and went along the highway, lowing as they went, and did not turn aside to the right hand or to the left. And the lords of the Philistines went after them to the border of *_Beth-shemesh_*.
* `1Sa 6:13` And the people of *_Beth-shemesh_* were reaping their wheat harvest in the valley. And they lifted up their eyes, saw the ark, and rejoiced to see it.
* `1Sa 6:15` And the Levites took down the ark of the LORD and the coffer that was with it, in which were the jewels of gold, and put them on the great stone. And the men of *_Beth-shemesh_* offered burnt-offerings and sacrificed sacrifices the same day to the LORD.
* `1Sa 6:19` And he smote the men of *_Beth-shemesh_* because they had looked into the ark of the LORD. He even smote among the people seventy men, fifty thousand men. And the people lamented because the LORD had smitten many of the people with a great slaughter.
* `1Sa 6:20` And the men of *_Beth-shemesh_* said, "Who is able to stand before Yahweh, this holy God? And to whom shall he go up from us?"
* `1Ki 4:9` The son of Dekar, in Makaz, in Shaalbim, *_Beth-shemesh_*, and Elon-beth-hanan;
* `2Ki 14:11` But Amaziah would not listen. Therefore, Jehoash king of Israel went up, and he and Amaziah king of Judah looked one another in the face at *_Beth-shemesh_*, which belongs to Judah.
* `2Ki 14:13` And Jehoash king of Israel took Amaziah king of Judah, the son of Jehoash the son of Ahaziah, at *_Beth-shemesh_*, and came to Jerusalem and broke down the wall of Jerusalem from the gate of Ephraim to the corner gate, four hundred cubits.
* `1Ch 6:59` Ashan with its suburbs, *_Beth-shemesh_* with its suburbs.
* `2Ch 25:21` So Joash the king of Israel went up, and they saw one another in the face, both he and Amaziah king of Judah, at *_Beth-shemesh_*, which belongs to Judah.
* `2Ch 25:23` And Joash the king of Israel took Amaziah king of Judah, the son of Joash, the son of Jehoahaz, at *_Beth-shemesh_*, and brought him to Jerusalem and broke down the wall of Jerusalem from the gate of Ephraim to the corner gate, four hundred cubits.
* `2Ch 28:18` The Philistines also had invaded the cities of the low country, and of the south of Judah, and had taken *_Beth-shemesh_*, Ajalon, Gederoth, Shocho with its villages, Timnah with its villages, and Gimzo with its villages, and they dwelt there.
* `Jer 43:13` He shall also break the images of *_Beth-shemesh_*, which is in the land of Egypt, and the houses of the gods of the Egyptians he shall burn with fire."'"

_19 verses containing BETH-SHEMESH_

== BETH-SHEMITE

* `1Sa 6:14` And the cart came into the field of Joshua, a *_Beth-shemite_*, and stood there where there was a great stone. And they cleaved the wood of the cart and offered the cows as a burnt-offering to the LORD.
* `1Sa 6:18` And the golden mice, according to the number of all the cities of the Philistines belonging to the five lords, both of fortified cities and of country villages, even to the great stone of Abel on which they set down the ark of the LORD—which stone remains to this day in the field of Joshua the *_Beth-shemite_*.

_2 verses containing BETH-SHEMITE_

== BETH-SHITTAH

* `Jdg 7:22` And the three hundred blew the trumpets, and the LORD set every man's sword against his fellow, even throughout all the host. And the host fled to *_Beth-shittah_* in Zereroth and to the border of Abel-meholah near Tabbath.

_1 verse containing BETH-SHITTAH_

== BETH-TAPPUAH

* `Jsh 15:53` Janum, *_Beth-tappuah_*, Aphekah,

_1 verse containing BETH-TAPPUAH_

== BETH-ZUR

* `Jsh 15:58` Halhul, *_Beth-zur_*, Gedor,
* `1Ch 2:45` And the son of Shammai was Maon, and Maon was the father of *_Beth-zur_*.
* `2Ch 11:7` *_Beth-zur_*, Shocho, Adullam,
* `Neh 3:16` After him Nehemiah the son of Azbuk, the ruler of the half part of *_Beth-zur_*, repaired to the place over against the sepulchers of David, and to the pool that was made, and to the house of the mighty.

_4 verses containing BETH-ZUR_

== BETHABARA

* `Jhn 1:28` These things were done in *_Bethabara_* beyond the Jordan where John was baptizing.

_1 verse containing BETHABARA_

== BETHANY

* `Mth 21:17` And he left them and went out of the city into *_Bethany_* and lodged there.
* `Mth 26:6` Now when Jesus was in *_Bethany_*, in the house of Simon the leper,
* `Mrk 11:1` And when they came near to Jerusalem, to Bethphage and *_Bethany_*, at the Mount of Olives, he sends forth two of his disciples,
* `Mrk 11:11` And Jesus entered into Jerusalem and into the temple. And when he had looked around at all things, it being now evening, he went out to *_Bethany_* with the twelve.
* `Mrk 11:12` And on the next day, when they had come from *_Bethany_*, he was hungry,
* `Mrk 14:3` And being in *_Bethany_*, in the house of Simon the leper, as he sat at the table, there came a woman having an alabaster vial of ointment of spikenard, very precious, and she broke the vial and poured it on his head.
* `Luk 19:29` And it came to pass, when he had come near to Bethphage and *_Bethany_*, at the mountain called the Mount of Olives, he sent two of his disciples,
* `Luk 24:50` And he led them out as far as to *_Bethany_*, and he lifted up his hands and blessed them.
* `Jhn 11:1` Now a certain man was sick, named Lazarus, from *_Bethany_*, the town of Mary and her sister Martha.
* `Jhn 11:18` (Now *_Bethany_* was near Jerusalem, about fifteen furlongs distant.)
* `Jhn 12:1` Then Jesus, six days before the passover, came to *_Bethany_*, where Lazarus was, who had been dead, whom he raised from the dead.

_11 verses containing BETHANY_

== BETHER

* `Sos 2:17` Until the day breaks and the shadows flee away, turn, my beloved, and be like a gazelle or a young buck upon the mountains of *_Bether_*.

_1 verse containing BETHER_

== BETHESDA

* `Jhn 5:2` Now there is a pool in Jerusalem by the sheep market, which is called in the Hebrew language, *_Bethesda_*, having five porches.

_1 verse containing BETHESDA_

== BETHLEHEM

* `Mth 2:1` Now after Jesus was born in *_Bethlehem_* of Judea in the days of Herod the king, behold, wise men came from the east to Jerusalem,
* `Mth 2:5` And they said to him, "In *_Bethlehem_* of Judea, for thus it is written by the prophet:
* `Mth 2:6` 'And you *_Bethlehem_*, in the land of Judah, are not the least among the princes of Judah, for out of you a Governor shall come, who shall rule my people Israel.'"
* `Mth 2:8` And he sent them to *_Bethlehem_*, and said, "Go, and search diligently for the young child. And when you have found him, report back to me so that I too may come and worship him."
* `Mth 2:16` Then Herod, when he saw that he was mocked by the wise men, was exceedingly angry, and sent forth and slew all the children who were in *_Bethlehem_* and in all its borders, from two years old and under, according to the time which he had ascertained from the wise men.
* `Luk 2:4` And Joseph also went up from Galilee, out of the city of Nazareth, into Judea, to the city of David, which is called *_Bethlehem_* (because he was of the house and lineage of David),
* `Luk 2:15` And it came to pass, when the angels had departed from them into heaven, the shepherds said to one another, "Let us now go even to *_Bethlehem_* and see this thing which has come to pass, which the Lord has made known to us."
* `Jhn 7:42` Has the Scripture not said that Christ comes from the offspring of David and out of the town of *_Bethlehem_* where David was?"

_8 verses containing BETHLEHEM_

== BETHPHAGE

* `Mth 21:1` And when they drew near to Jerusalem and had come to *_Bethphage_*, to the Mount of Olives, Jesus sent two disciples,
* `Mrk 11:1` And when they came near to Jerusalem, to *_Bethphage_* and Bethany, at the Mount of Olives, he sends forth two of his disciples,
* `Luk 19:29` And it came to pass, when he had come near to *_Bethphage_* and Bethany, at the mountain called the Mount of Olives, he sent two of his disciples,

_3 verses containing BETHPHAGE_

== BETHSAIDA

* `Mth 11:21` "Woe to you, Chorazin! Woe to you, *_Bethsaida_*! For if the mighty works which have been done in you had been done in Tyre and Sidon, they would have repented long ago in sackcloth and ashes.
* `Mrk 6:45` And immediately he constrained his disciples to get into the boat and to go to the other side ahead of him to *_Bethsaida_* while he sent the people away.
* `Mrk 8:22` And he comes to *_Bethsaida_*, and they bring a blind man to him and implored him to touch him.
* `Luk 9:10` And the apostles, when they had returned, told him all that they had done. And he took them and went aside privately into a desolate place, belonging to the city called *_Bethsaida_*.
* `Luk 10:13` "Woe to you, Chorazin! Woe to you, *_Bethsaida_*! For if the mighty works had been done in Tyre and Sidon which have been done in you, they would have a great while ago repented, sitting in sackcloth and ashes.
* `Jhn 1:44` Now Philip was from *_Bethsaida_*, the city of Andrew and Peter.
* `Jhn 12:21` The same came therefore to Philip, who was of *_Bethsaida_* of Galilee, and desired him, saying, "Sir, we wish to see Jesus."

_7 verses containing BETHSAIDA_

== BETHUEL

* `Gen 22:22` Chesed, Hazo, Pildash, Jidlaph, and *_Bethuel_*."
* `Gen 22:23` And *_Bethuel_* begot Rebekah. These eight Milcah bore to Nahor Abraham's brother.
* `Gen 24:15` And it came to pass before he had finished speaking, that behold, Rebekah came out, who was born to *_Bethuel_* son of Milcah, the wife of Nahor, Abraham's brother, with her pitcher upon her shoulder.
* `Gen 24:24` And she said to him, "I am the daughter of *_Bethuel_* the son of Milcah, whom she bore to Nahor."
* `Gen 24:47` And I asked her and said, 'Whose daughter are you?' And she said, 'The daughter of *_Bethuel_*, Nahor's son, whom Milcah bore to him.' And I put the earring upon her face and the bracelets upon her hands.
* `Gen 24:50` Then Laban and *_Bethuel_* answered, and said, "The thing proceeds from the LORD. We cannot speak to you bad or good.
* `Gen 25:20` And Isaac was forty years old when he took Rebekah to be his wife, the daughter of *_Bethuel_* the Syrian of Padan-aram, the sister to Laban the Syrian.
* `Gen 28:2` Arise, go to Padan-aram, to the house of *_Bethuel_* your mother's father, and take for yourself from there a wife from the daughters of Laban your mother's brother.
* `Gen 28:5` And Isaac sent away Jacob. And he went to Padan-aram, to Laban, son of *_Bethuel_* the Syrian, the brother of Rebekah, Jacob's and Esau's mother.
* `1Ch 4:30` At *_Bethuel_*, at Hormah, at Ziklag,

_10 verses containing BETHUEL_

== BETHUL

* `Jsh 19:4` Eltolad, *_Bethul_*, Hormah,

_1 verse containing BETHUL_

