= BETONIM - BLAZE
:toc:

== BETONIM

* `Jsh 13:26` And from Heshbon to Ramath-mizpeh, and *_Betonim_*; and from Mahanaim to the border of Debir;

_1 verse containing BETONIM_

== BETRAY

* `1Ch 12:17` And David went out to meet them and answered and said to them, "If you have come peaceably to me to help me, my heart shall be knit to you, but if you have come to *_betray_* me to my enemies, seeing there is no wrong in my hands, may the God of our fathers look on it and rebuke it."
* `Mth 24:10` And then many will be offended, will *_betray_* one another, and will hate one another.
* `Mth 26:16` And from that time he sought opportunity to *_betray_* him.
* `Mth 26:21` And as they were eating, he said, "Truly I say to you, that one of you will *_betray_* me."
* `Mth 26:23` And he answered and said, "He who dips his hand with me in the dish, the same will *_betray_* me.
* `Mrk 13:12` Now the brother will *_betray_* the brother to death, and the father the son. And children will rise up against their parents and will cause them to be put to death.
* `Mrk 14:10` And Judas Iscariot, one of the twelve, went to the chief priests to *_betray_* him to them.
* `Mrk 14:11` And when they heard it, they were glad and promised to give him money. And he sought how he might conveniently *_betray_* him.
* `Mrk 14:18` And as they sat and were eating, Jesus said, "Truly I say to you, one of you who eats with me will *_betray_* me."
* `Luk 22:4` And he went and discussed with the chief priests and captains how he might *_betray_* him to them.
* `Luk 22:6` And he promised and sought opportunity to *_betray_* him to them in the absence of the multitude.
* `Luk 22:48` But Jesus said to him, "Judas, do you *_betray_* the Son of man with a kiss?"
* `Jhn 6:64` But there are some of you who do not believe." For Jesus knew from the beginning who they were who did not believe and who he was who would *_betray_* him.
* `Jhn 6:71` He spoke of Judas Iscariot the son of Simon. For it was he who was to *_betray_* him, being one of the twelve.
* `Jhn 12:4` Then one of his disciples, Judas Iscariot, Simon's son, who was to *_betray_* him, says,
* `Jhn 13:2` And during supper (the devil having now put into the heart of Judas Iscariot, Simon's son, to *_betray_* him),
* `Jhn 13:11` For he knew who would *_betray_* him; therefore, he said, "You are not all clean."
* `Jhn 13:21` When Jesus had said this, he was troubled in spirit and testified, and said, "Truly, truly, I say to you, that one of you will *_betray_* me."

_18 verses containing BETRAY_

== BETRAYED

* `Mth 10:4` Simon the Canaanite, and Judas Iscariot, who also *_betrayed_* him.
* `Mth 17:22` And while they stayed in Galilee, Jesus said to them, "The Son of man will be *_betrayed_* into the hands of men,
* `Mth 20:18` "Behold, we go up to Jerusalem, and the Son of man will be *_betrayed_* to the chief priests and to the scribes, and they will condemn him to death,
* `Mth 26:2` "You know that after two days is the passover and the Son of man is *_betrayed_* to be crucified."
* `Mth 26:24` The Son of man goes, as it is written concerning him. But woe to that man by whom the Son of man is *_betrayed_*! It would have been good for that man if he had not been born."
* `Mth 26:25` Then Judas, who *_betrayed_* him, answered and said, "Master, is it I?" He said to him, "You have said."
* `Mth 26:45` Then he comes to his disciples and says to them, "Sleep on now and take your rest. Behold, the hour is at hand and the Son of man is *_betrayed_* into the hands of sinners.
* `Mth 26:48` Now he who *_betrayed_* him gave them a sign, saying, "Whomever I kiss, he is the one. Seize him."
* `Mth 27:3` Then Judas, who had *_betrayed_* him, when he saw that he was condemned, repented and brought the thirty pieces of silver back to the chief priests and elders,
* `Mth 27:4` Saying, "I have sinned in that I have *_betrayed_* innocent blood." And they said, "What is that to us? See to that yourself."
* `Mrk 3:19` And Judas Iscariot, who also *_betrayed_* him. They went into a house.
* `Mrk 14:21` The Son of man indeed goes, as it is written concerning him. But woe to that man by whom the Son of man is *_betrayed_*! It would have been good for that man if he had never been born."
* `Mrk 14:41` And he comes the third time, and says to them, "Sleep on now and take your rest. It is enough. The hour has come. Behold, the Son of man is *_betrayed_* into the hands of sinners.
* `Mrk 14:44` And he who *_betrayed_* him had given them a sign, saying, "Whomever I kiss, he is the one. Take him and lead him away safely."
* `Luk 21:16` And you will be *_betrayed_* by parents, brothers, kinsmen, and friends, and some of you they will cause to be put to death.
* `Luk 22:22` And truly the Son of man goes as it was determined. But woe to that man by whom he is *_betrayed_*!"
* `Jhn 18:2` And Judas also, who *_betrayed_* him, knew the place, for Jesus often resorted there with his disciples.
* `Jhn 18:5` They answered him, "Jesus of Nazareth." Jesus says to them, "I am he." And Judas also, who *_betrayed_* him, stood with them.
* `1Co 11:23` For I have received from the Lord that which I also delivered to you, that the Lord Jesus, the same night in which he was *_betrayed_*, took bread.

_19 verses containing BETRAYED_

== BETRAYERS

* `Act 7:52` Which of the prophets have your fathers not persecuted? And they have slain those who foretold the coming of the Just One, of whom you have now been the *_betrayers_* and murderers,

_1 verse containing BETRAYERS_

== BETRAYS

* `Mth 26:46` Rise, let us be going. Behold, he is at hand who *_betrays_* me."
* `Mth 26:73` And after a while those who stood by came to him and said to Peter, "Surely you are also one of them, for your speech *_betrays_* you."
* `Mrk 14:42` Rise, let us go. Behold, he who *_betrays_* me is at hand."
* `Luk 22:21` But behold, the hand of him who *_betrays_* me is with me on the table.
* `Jhn 21:20` Then Peter, turning around, sees the disciple whom Jesus loved following (who also leaned on his chest at supper and said, "Lord, who is he who *_betrays_* you?").

_5 verses containing BETRAYS_

== BETROTH

* `Deu 28:30` You shall *_betroth_* a wife and another man shall lie with her. You shall build a house and you shall not dwell in it. You shall plant a vineyard and shall not gather its grapes.
* `Hos 2:19` And I will *_betroth_* you to me forever. I will even *_betroth_* you to me in righteousness, in judgment, in loving-kindness, and in mercies.
* `Hos 2:20` I will even *_betroth_* you to me in faithfulness. And you shall know the LORD.

_3 verses containing BETROTH_

== BETROTHED

* `Exo 21:8` If she shall not please her master who has *_betrothed_* her to himself, then he shall let her be redeemed. He shall have no power to sell her to a strange nation, seeing he has dealt deceitfully with her.
* `Exo 21:9` And if he has *_betrothed_* her to his son, he shall deal with her after the manner of daughters.
* `Exo 22:16` "And if a man entices a virgin who is not *_betrothed_* and lies with her, he shall surely endow her to be his wife.
* `Lev 19:20` 'And whoever lies carnally with a woman who is a servant *_betrothed_* to a husband and not at all redeemed, nor freedom given to her, she shall be scourged. They shall not be put to death because she was not free.
* `Deu 20:7` And what man is there who has *_betrothed_* a wife and has not taken her? Let him go and return to his house, lest he should die in battle and another man should take her.'
* `Deu 22:23` "If a young woman who is a virgin is *_betrothed_* to a husband, and a man finds her in the city and lies with her,
* `Deu 22:25` "But if a man finds a *_betrothed_* young woman in the field, and the man forces her and lies with her, then the man only who lay with her shall die.
* `Deu 22:27` For he found her in the field, and the *_betrothed_* young woman cried, and there was no one to save her.
* `Deu 22:28` "If a man finds a young woman who is a virgin, who is not *_betrothed_*, and lays hold upon her and lies with her, and they are found,

_9 verses containing BETROTHED_

== BETTER

* `Gen 29:19` And Laban said, "It is *_better_* that I give her to you than that I should give her to another man. Abide with me."
* `Exo 14:12` Is this not the word that we told you in Egypt, saying, 'Leave us alone so that we may serve the Egyptians'? For it had been *_better_* for us to serve the Egyptians than that we should die in the wilderness."
* `Num 14:3` Why has the LORD brought us to this land to fall by the sword so that our wives and our children should be plunder? Would it not be *_better_* for us to return into Egypt?"
* `Jdg 8:2` And he said to them, "What have I done now in comparison of you? Is the gleaning of the grapes of Ephraim not *_better_* than the vintage of Abiezer?
* `Jdg 9:2` "Speak, I pray you, in the ears of all the men of Shechem, 'Which is *_better_* for you, either that all the sons of Jerubbaal, which are seventy persons, should reign over you, or that one should reign over you?' Remember also that I am your bone and your flesh."
* `Jdg 11:25` And now are you anything *_better_* than Balak the son of Zippor king of Moab? Did he ever strive against Israel? Did he ever fight against them?
* `Jdg 18:19` And they said to him, "Hold your peace. Lay your hand upon your mouth and go with us, and be to us a father and a priest. Is it *_better_* for you to be a priest for the house of one man or that you should be a priest for a tribe and a family in Israel?"
* `Rth 4:15` And he shall be to you a restorer of your life and a nourisher of your old age, for your daughter-in-law, who loves you, who is *_better_* to you than seven sons, has borne him."
* `1Sa 1:8` Then Elkanah her husband said to her, "Hannah, why do you weep? And why do you not eat? And why is your heart grieved? Am I not *_better_* to you than ten sons?"
* `1Sa 15:22` And Samuel said, "Has the LORD as great delight in burnt-offerings and sacrifices as in obeying the voice of the LORD? Behold, to obey is *_better_* than sacrifice and to listen than the fat of rams.
* `1Sa 15:28` And Samuel said to him, "The LORD has rent the kingdom of Israel from you this day and has given it to a neighbor of yours who is *_better_* than you.
* `1Sa 27:1` And David said in his heart, "I shall now perish one day by the hand of Saul. There is nothing *_better_* for me than that I should speedily escape into the land of the Philistines. And Saul will despair of seeking for me anymore in any border of Israel, and I shall escape from his hand."
* `2Sa 14:32` And Absalom answered Joab, "Behold, I sent to you, saying, 'Come here so that I may send you to the king to say, "Why have I come from Geshur? It would be *_better_* for me to be there still."' Now therefore, let me see the king's face, and if there is any iniquity in me, let him kill me."
* `2Sa 17:14` And Absalom and all the men of Israel said, "The counsel of Hushai the Archite is *_better_* than the counsel of Ahithophel." For the LORD had appointed to defeat the good counsel of Ahithophel, to the intent that the LORD might bring evil upon Absalom.
* `2Sa 18:3` But the people answered, "You shall not go forth. For if we flee away, they will not care for us. Even if half of us die, they will not care for us. But now you are worth ten thousand of us; therefore, it is *_better_* that you give us aid from the city."
* `1Ki 1:47` And moreover, the king's servants came to bless our lord king David, saying, 'May God make the name of Solomon *_better_* than your name and make his throne greater than your throne.' And the king bowed himself upon the bed.
* `1Ki 2:32` And the LORD shall return his blood upon his own head, who fell upon two men more righteous and *_better_* than he is and slew them with the sword, my father David not knowing of it, namely, Abner the son of Ner, captain of the host of Israel, and Amasa the son of Jether, captain of the host of Judah.
* `1Ki 19:4` But he himself went a day's journey into the wilderness and came and sat down under a juniper-tree. And he requested for himself that he might die and said, "It is enough. Now, O LORD, take away my life, for I am not *_better_* than my fathers."
* `1Ki 21:2` And Ahab spoke to Naboth, saying, "Give me your vineyard so that I may have it for a garden of herbs, for it is near to my house. For it, I will give you a *_better_* vineyard in its place, or if it seems good to you, I will give you its worth in money."
* `2Ki 5:12` Are Abana and Pharpar, rivers of Damascus, not *_better_* than all the waters of Israel? May I not wash in them and be clean?" So he turned and went away in a rage.
* `2Ch 21:13` But have walked in the way of the kings of Israel and have made Judah and the inhabitants of Jerusalem to commit idolatry, like the idolatries of the house of Ahab, and also have slain your brothers of your father's house, who were *_better_* than yourself,
* `Est 1:19` If it pleases the king, let a royal commandment go from him, and let it be written among the laws of the Persians and the Medes so that it may not be altered, that Vashti may no longer come before king Ahasuerus. And let the king give her royal estate to another who is *_better_* than she is.
* `Psa 37:16` A little that a righteous man has is *_better_* than the riches of many wicked.
* `Psa 63:3` Because your loving-kindness is *_better_* than life, my lips shall praise you.
* `Psa 69:31` This also shall please the LORD *_better_* than an ox or bull that has horns and hooves.
* `Psa 84:10` For a day in your courts is *_better_* than a thousand [elsewhere]. I would rather be a door-keeper in the house of my God than dwell in the tents of wickedness.
* `Psa 118:8` It is *_better_* to trust in the LORD than to put confidence in man.
* `Psa 118:9` It is *_better_* to trust in the LORD than to put confidence in princes.
* `Psa 119:72` The law of your mouth is *_better_* to me than thousands of gold and silver.
* `Pro 3:14` For its merchandise is *_better_* than the merchandise of silver and its gain than fine gold.
* `Pro 8:11` For wisdom is *_better_* than rubies, and all the things that may be desired are not to be compared to it.
* `Pro 8:19` My fruit is *_better_* than gold, even fine gold, and my revenue than choice silver.
* `Pro 12:9` He who is despised and has a servant is *_better_* than he who honors himself and is destitute of bread.
* `Pro 15:16` *_Better_* is little with the fear of the LORD, than great treasure and trouble with it.
* `Pro 15:17` *_Better_* is a dinner of herbs where love is, than a stalled ox and hatred with it.
* `Pro 16:8` *_Better_* is a little with righteousness, than great revenues without justice.
* `Pro 16:16` How much *_better_* it is to get wisdom than gold! And to get understanding is to be chosen rather than silver.
* `Pro 16:19` It is *_better_* to be of a humble spirit with the lowly, than to divide the plunder with the proud.
* `Pro 16:32` He who is slow to anger is *_better_* than the mighty, and he who rules his spirit, than he who takes a city.
* `Pro 17:1` *_Better_* is a dry morsel and quietness with it, than a house full of sacrifices with strife.
* `Pro 19:1` *_Better_* is the poor who walks in his integrity, than he who is perverse in his lips and is a fool.
* `Pro 19:22` The desire of a man is his kindness. And a poor man is *_better_* than a liar.
* `Pro 21:9` It is *_better_* to dwell in a corner of the house-top, than with a brawling woman in a wide house.
* `Pro 21:19` It is *_better_* to dwell in the wilderness than with a contentious and angry woman.
* `Pro 25:7` For it is *_better_* that it be said to you, "Come up here," than that you should be put lower in the presence of the prince whom your eyes have seen.
* `Pro 25:24` It is *_better_* to dwell in a corner of the house-top than with a brawling woman and in a wide house.
* `Pro 27:5` Open rebuke is *_better_* than secret love.
* `Pro 27:10` Your own friend and your father's friend, do not forsake, neither go into your brother's house in the day of your calamity, for *_better_* is a neighbor who is near than a brother far off.
* `Pro 28:6` *_Better_* is the poor who walks in his uprightness than the rich who is perverse in his ways.
* `Ecc 2:24` There is nothing *_better_* for a man than that he should eat and drink, and that he should make his soul enjoy good in his labor. This also I saw, that it was from the hand of God.
* `Ecc 3:22` Therefore, I perceive that there is nothing *_better_* than that a man should rejoice in his own works, for that is his portion. For who shall bring him to see what shall be after him?
* `Ecc 4:3` Indeed, *_better_* is he than both of them who has not yet been, who has not seen the evil work that is done under the sun.
* `Ecc 4:6` *_Better_* is a handful with quietness, than both the hands full with toil and vexation of spirit.
* `Ecc 4:9` Two are *_better_* than one, because they have a good reward for their labor.
* `Ecc 4:13` *_Better_* is a poor and a wise child, than an old and foolish king who will no more be admonished.
* `Ecc 5:5` It is *_better_* that you should not vow, than that you should vow and not pay.
* `Ecc 6:3` If a man begets a hundred children and lives many years, so that the days of his years are many, but his soul is not filled with good and he also has no burial, I say that the one of an untimely birth is *_better_* than he is.
* `Ecc 6:9` *_Better_* is the sight of the eyes than the wandering of the desire. This is also vanity and vexation of spirit.
* `Ecc 6:11` Seeing there are many things that increase vanity, what is man the *_better_*?
* `Ecc 7:1` A good name is *_better_* than precious ointment, and the day of death than the day of one's birth.
* `Ecc 7:2` It is *_better_* to go to the house of mourning, than to go to the house of feasting, for that is the end of all men, and the living will lay it to his heart.
* `Ecc 7:3` Sorrow is *_better_* than laughter, for by the sadness of the countenance the heart is made *_better_*.
* `Ecc 7:5` It is *_better_* to hear the rebuke of the wise, than for a man to hear the song of fools.
* `Ecc 7:8` *_Better_* is the end of a thing than its beginning. And the patient in spirit is *_better_* than the proud in spirit.
* `Ecc 7:10` Do not say, "Why were the former days *_better_* than these?" For you do not inquire wisely concerning this.
* `Ecc 8:15` Then I commended mirth, because a man has no *_better_* thing under the sun than to eat, to drink, and to be merry, for that shall abide with him in his labor all the days of his life which God gives him under the sun.
* `Ecc 9:4` For to him who is joined to all the living there is hope, for a living dog is *_better_* than a dead lion.
* `Ecc 9:16` Then I said, "Wisdom is *_better_* than strength." Nevertheless, the poor man's wisdom is despised and his words are not heard.
* `Ecc 9:18` Wisdom is *_better_* than weapons of war, but one sinner destroys much good.
* `Ecc 10:11` Surely the serpent will bite without enchantment, and a babbler is no *_better_*.
* `Sos 1:2` [Lady:] Let him kiss me with the kisses of his mouth, for your love is *_better_* than wine.
* `Sos 4:10` How fair your love is, my sister, my spouse! How much *_better_* your love is than wine, and the smell of your ointments than all spices!
* `Isa 56:5` Even to them I will give in my house and within my walls a place and a name *_better_* than that of sons and daughters. I will give them an everlasting name that shall not be cut off.
* `Lam 4:9` [TET] Those who are slain with the sword are *_better_* than those who are slain with hunger, for these pine away, stricken through for lack of the fruits of the field.
* `Ezk 36:11` And I will multiply upon you man and beast, and they shall increase and bring fruit. And I will settle you after your old states and will do *_better_* to you than at your beginnings. And you shall know that I am the LORD.
* `Hos 2:7` And she shall follow after her lovers, but she shall not overtake them, and she shall seek them, but shall not find them. Then she shall say, 'I will go and return to my first husband, for then it was *_better_* with me than now.'
* `Amo 6:2` Pass to Calneh and see, and from there go to Hamath the great. Then go down to Gath of the Philistines. Are they *_better_* than these kingdoms? Or is their border greater than your border?
* `Jna 4:3` Now therefore, O LORD, take, I implore you, my life from me, for it is *_better_* for me to die than to live."
* `Jna 4:8` And it came to pass, when the sun rose, that God prepared a vehement east wind. And the sun beat upon the head of Jonah so that he fainted and wished in himself to die, and said, "It is *_better_* for me to die than to live."
* `Nah 3:8` Are you *_better_* than No-Amon that was situated among the rivers, that had the waters around it, whose rampart was the sea and her wall was from the sea?
* `Mth 6:26` Behold the birds of the air: they do not sow, neither do they reap, nor gather into barns, yet your heavenly Father feeds them. Are you not much *_better_* than they are?
* `Mth 12:12` How much then is a man *_better_* than a sheep? Therefore, it is lawful to do good on the sabbath days."
* `Mth 18:6` But whoever causes one of these little ones who believe in me to sin, it would be *_better_* for him that a millstone were hanged around his neck and that he were drowned in the depth of the sea.
* `Mth 18:8` "Therefore, if your hand or your foot causes you to sin, cut them off and cast them from you. It is *_better_* for you to enter into life lame or maimed than to have two hands or two feet and be cast into everlasting fire.
* `Mth 18:9` And if your eye causes you to sin, pluck it out and cast it from you. It is *_better_* for you to enter into life with one eye than to have two eyes and be cast into hell-fire.
* `Mrk 9:42` "And whoever causes one of these little ones who believe in me to fall into sin, it is *_better_* for him that a millstone were hanged around his neck and he were cast into the sea.
* `Mrk 9:43` And if your hand causes you to fall into sin, cut it off. It is *_better_* for you to enter life maimed than with two hands to go into hell, into the fire that shall never be quenched,
* `Mrk 9:45` And if your foot causes you to fall into sin, cut it off. It is *_better_* for you to enter lame into life than with two feet to be cast into hell, into the fire that never shall be quenched,
* `Mrk 9:47` And if your eye causes you to fall into sin, pluck it out. It is *_better_* for you to enter into the kingdom of God with one eye than with two eyes to be cast into hell-fire,
* `Luk 5:39` No man also having drank old wine immediately desires new, because he says, 'The old is *_better_*.'"
* `Luk 12:24` Consider the ravens: they neither sow nor reap, which neither have store-house, nor barn, and God feeds them. How much more are you *_better_* than the birds?
* `Luk 17:2` It would be *_better_* for him that a millstone were hanged around his neck and he were cast into the sea than that he should cause one of these little ones to fall into sin.
* `Jhn 4:52` Then he asked them the hour when he began to get *_better_*, and they said to him, "Yesterday at the seventh hour the fever left him."
* `Rom 3:9` What then? Are we *_better_* than they are? No, in no way. For we have before proved both Jews and Gentiles, that they are all under sin,
* `1Co 7:9` But if they cannot contain, let them marry, for it is *_better_* to marry than to burn.
* `1Co 7:38` So then he who gives her in marriage does well, but he who does not give her in marriage does *_better_*.
* `1Co 8:8` But food does not commend us to God. For neither are we the *_better_* if we eat, neither are we the worse if we do not eat.
* `1Co 9:15` But I have used none of these things, neither have I written these things, so that it should be thus done to me. For it would be *_better_* for me to die than that any man should make my glorying void.
* `1Co 11:17` Now in this that I declare to you I do not praise you, that you do not come together for the *_better_*, but for the worse.
* `Phl 1:23` For I am hard pressed between the two, having a desire to depart and to be with Christ, which is far *_better_*.
* `Phl 2:3` Let nothing be done through strife or vain glory. But in lowliness of mind, let each esteem the other *_better_* than themselves—
* `Heb 1:4` Being made so much *_better_* than the angels, as he has by inheritance obtained a more excellent name than they have.
* `Heb 6:9` But, beloved, we are persuaded of *_better_* things for you, and things that accompany salvation, though we speak in this manner.
* `Heb 7:7` And without all contradiction the less is blessed by the *_better_*.
* `Heb 7:19` For the law made nothing perfect, but the introduction of a *_better_* hope did, by which we draw near to God.
* `Heb 7:22` By so much Jesus has become surety of a *_better_* testament.
* `Heb 8:6` But now he has obtained a more excellent ministry, by as much as he is also the mediator of a *_better_* covenant, which was established upon *_better_* promises.
* `Heb 9:23` It was therefore necessary that the patterns of things in the heavens should be purified with these, but the heavenly things themselves with *_better_* sacrifices than these.
* `Heb 10:34` For you had compassion on me in my bonds and joyfully took the seizing of your goods, knowing in yourselves that you have in heaven a *_better_* and an enduring substance.
* `Heb 11:16` But now they desire a *_better_* country, that is, a heavenly one. Therefore, God is not ashamed to be called their God, for he has prepared a city for them.
* `Heb 11:35` Women received their dead raised to life again. Others were tortured, not accepting deliverance, so that they might obtain a *_better_* resurrection.
* `Heb 11:40` God having provided something *_better_* for us—so that apart from us they should not be made perfect.
* `Heb 12:24` To Jesus the mediator of the new covenant, and to the blood of sprinkling that speaks *_better_* things than that of Abel.
* `1Pe 3:17` For it is *_better_*, if it is the will of God, that you suffer for well-doing than for evil-doing.
* `2Pe 2:21` For it would have been *_better_* for them not to have known the way of righteousness than after they have known it to turn from the holy commandment delivered to them.

_115 verses containing BETTER_

== BETWEEN

* `Gen 3:15` And I will put enmity *_between_* you and the woman and *_between_* your offspring and her offspring. He shall bruise your head, and you shall bruise his heel."
* `Gen 9:12` And God said, "This is the token of the covenant which I make *_between_* me and you and every living creature that is with you for perpetual generations:
* `Gen 9:13` I have set my bow in the cloud, and it shall be for a token of a covenant *_between_* me and the earth.
* `Gen 9:15` And I will remember my covenant which is *_between_* me and you and every living creature of all flesh, and the waters shall no more become a flood to destroy all flesh.
* `Gen 9:16` And the bow shall be in the cloud, and I will look upon it so that I may remember the everlasting covenant *_between_* God and every living creature of all flesh that is upon the earth."
* `Gen 9:17` And God said to Noah, "This is the token of the covenant which I have established *_between_* me and all flesh that is upon the earth."
* `Gen 10:12` And Resen, *_between_* Nineveh and Calah—the same is a great city.
* `Gen 13:3` And he went on his journeys from the south even to Beth-el to the place where his tent had been at the beginning, *_between_* Beth-el and Hai,
* `Gen 13:7` And there was a strife *_between_* the herdsmen of Abram's livestock and the herdsmen of Lot's livestock. And the Canaanite and the Perizzite dwelt then in the land.
* `Gen 13:8` And Abram said to Lot, "Let there be no strife, I pray you, *_between_* you and me and *_between_* my herdsmen and your herdsmen, for we are brothers.
* `Gen 15:17` And it came to pass, that when the sun had gone down and it was dark, behold, a smoking furnace, and a burning lamp that passed *_between_* those pieces.
* `Gen 16:5` And Sarai said to Abram, "My wrong is upon you. I have given my servant into your bosom, and when she saw that she had conceived, I was despised in her eyes. May the LORD judge *_between_* you and me."
* `Gen 16:14` Therefore, the well was called Beer-la-hai-roi. Behold, it is *_between_* Kadesh and Bered.
* `Gen 17:2` And I will make my covenant *_between_* me and you and will multiply you exceedingly."
* `Gen 17:7` And I will establish my covenant *_between_* me and you and your offspring after you, in their generations, for an everlasting covenant, to be a God to you and to your offspring after you.
* `Gen 17:10` This is my covenant *_between_* me and you and your offspring after you, which you shall keep: every male child among you shall be circumcised.
* `Gen 17:11` And you shall circumcise the flesh of your foreskin, and it shall be a token of the covenant *_between_* me and you.
* `Gen 20:1` And Abraham journeyed from there toward the south country and dwelt *_between_* Kadesh and Shur and sojourned in Gerar.
* `Gen 23:15` "My lord, listen to me. The land is worth four hundred shekels of silver. What is that *_between_* you and me? Therefore, bury your dead."
* `Gen 26:28` And they said, "We saw certainly that the LORD was with you. And we said, 'Let there now be an oath *_between_* us, even *_between_* us and you, and let us make a covenant with you,
* `Gen 30:36` And he set three days' journey *_between_* himself and Jacob. And Jacob fed the rest of Laban's flocks.
* `Gen 31:37` Now that you have searched all my stuff, what have you found of all your household-stuff? Set it here before my brothers and your brothers so that they may judge *_between_* us both.
* `Gen 31:44` Now therefore, come, let us make a covenant—you and I—and let it be for a witness *_between_* you and me."
* `Gen 31:48` And Laban said, "This heap is a witness *_between_* you and me this day." Therefore, the name of it was called Galeed,
* `Gen 31:49` And Mizpah, for he said, "May the LORD watch *_between_* you and me when we are absent from one another.
* `Gen 31:50` If you afflict my daughters, or if you take other wives besides my daughters, and no man is with us, behold, God is witness *_between_* you and me."
* `Gen 31:51` And Laban said to Jacob, "Behold this heap and behold this pillar which I have set *_between_* you and me.
* `Gen 31:53` May the God of Abraham, and the God of Nahor, the God of their father, judge *_between_* us." And Jacob swore by the Fear of his father Isaac.
* `Gen 32:16` And he delivered them into the hand of his servants, every drove by themselves, and said to his servants, "Pass over before me and put a space *_between_* drove and drove."
* `Gen 33:1` And Jacob lifted up his eyes and looked, and behold, Esau came, and with him four hundred men. And he divided the children *_between_* Leah, Rachel, and the two women-servants.
* `Gen 48:12` And Joseph brought them out from *_between_* his knees, and he bowed himself with his face to the earth.
* `Gen 49:10` The scepter shall not depart from Judah, nor a lawgiver from *_between_* his feet, until Shiloh comes. And to him shall be the gathering of the people.
* `Gen 49:14` "Issachar is a strong donkey, couching down *_between_* two burdens.
* `Exo 8:23` And I will put a division *_between_* my people and your people. Tomorrow this sign shall be."'"
* `Exo 9:4` And the LORD shall make a distinction *_between_* the livestock of Israel and the livestock of Egypt, and there shall nothing die of all that belongs to the children of Israel."'"
* `Exo 11:7` But against any of the children of Israel a dog shall not move his tongue, against man or beast, so that you may know how the LORD puts a difference *_between_* the Egyptians and Israel.'
* `Exo 13:9` And it shall be for a sign to you upon your hand and for a memorial *_between_* your eyes so that the LORD'S law may be in your mouth. For with a strong hand the LORD has brought you out of Egypt.
* `Exo 13:16` And it shall be for a token upon your hand and for frontlets *_between_* your eyes. For by strength of hand the LORD brought us forth out of Egypt."
* `Exo 14:2` "Speak to the children of Israel that they turn and encamp before Pi-hahiroth, *_between_* Migdol and the sea, over against Baal-zephon. Before it you shall encamp by the sea.
* `Exo 14:20` And it came *_between_* the camp of the Egyptians and the camp of Israel. It was a cloud and darkness to them, but it gave light by night to these, so that one did not come near the other all the night.
* `Exo 16:1` And they took their journey from Elim, and all the congregation of the children of Israel came to the wilderness of Sin, which is *_between_* Elim and Sinai, on the fifteenth day of the second month after their departure from the land of Egypt.
* `Exo 18:16` When they have a matter, they come to me, and I judge *_between_* one and another and make them know the statutes of God and his laws."
* `Exo 22:11` Then an oath of the LORD shall be *_between_* them both that he has not put his hand to his neighbor's goods. And its owner shall accept it, and he shall not make restitution.
* `Exo 25:22` And there I will meet with you, and I will speak with you from above the mercy-seat, from *_between_* the two cherubim which are upon the ark of the testimony, about all things which I will give you in commandment to the children of Israel.
* `Exo 26:33` And you shall hang the veil under the buttons so that you may bring in there within the veil the ark of the testimony. And the veil shall be for you a separation *_between_* the holy place and the holy of holies.
* `Exo 28:33` And beneath, upon its hem you shall make pomegranates of blue, of purple, and of scarlet around its hem and bells of gold *_between_* them around it:
* `Exo 30:18` "You shall also make a basin of brass, and its foot also of brass, to wash in. And you shall put it *_between_* the Tabernacle of the Congregation and the altar, and you shall put water therein.
* `Exo 31:13` "Speak also to the children of Israel, saying, 'Truly you shall keep my sabbaths, for it is a sign *_between_* me and you throughout your generations so that you may know that I am the LORD who sanctifies you.
* `Exo 31:17` It is a sign *_between_* me and the children of Israel forever, for in six days the LORD made heaven and earth and on the seventh day he rested and was refreshed.'"
* `Exo 39:25` And they made bells of pure gold, and put the bells *_between_* the pomegranates upon the hem of the robe, around *_between_* the pomegranates:
* `Exo 40:7` And you shall set the basin *_between_* the tent of the congregation and the altar and shall put water in it.
* `Exo 40:30` And he set the basin *_between_* the tent of the congregation and the altar, and put water there to wash with.
* `Lev 10:10` So that you may make a difference *_between_* holy and unholy and *_between_* unclean and clean,
* `Lev 11:47` To make a difference *_between_* the unclean and the clean and *_between_* the beast that may be eaten and the beast that may not be eaten.
* `Lev 20:25` You shall therefore distinguish *_between_* clean beasts and unclean and *_between_* unclean birds and clean. And you shall not make your souls abominable by beast or by bird, or by any manner of living animal that creeps on the ground, which I have separated from you as unclean.
* `Lev 26:46` These are the statutes, judgments, and laws which the LORD made *_between_* him and the children of Israel on mount Sinai by the hand of Moses.
* `Num 7:89` And when Moses had entered into the Tabernacle of the Congregation to speak with him, he heard the voice speaking to him from above the mercy-seat that was upon the ark of testimony, from *_between_* the two cherubim. And he spoke to him.
* `Num 11:33` And while the flesh was still *_between_* their teeth, before it was chewed, the wrath of the LORD was kindled against the people, and the LORD smote the people with a very great plague.
* `Num 13:23` And they came to the brook of Eshcol and cut down from there a branch with one cluster of grapes, and they bore it *_between_* two upon a staff, and they brought some of the pomegranates and some of the figs.
* `Num 16:48` And he stood *_between_* the dead and the living, and the plague was stayed.
* `Num 21:13` From there they departed and pitched on the other side of Arnon, which is in the wilderness that comes out of the border of the Amorites, for Arnon is the border of Moab *_between_* Moab and the Amorites.
* `Num 26:56` According to the lot its possession shall be divided *_between_* many and few."
* `Num 30:16` These are the statutes which the LORD commanded Moses, *_between_* a man and his wife, *_between_* the father and his daughter, being still in her youth in her father's house.
* `Num 31:27` And divide the plunder into two parts *_between_* those who took the war upon them, who went out to battle, and *_between_* all the congregation.
* `Num 35:24` Then the congregation shall judge *_between_* the slayer and the avenger of blood according to these judgments.
* `Deu 1:1` These are the words which Moses spoke to all Israel on the east side of the Jordan in the wilderness, in the plain over against Suf, *_between_* Paran, Tophel, Laban, Hazeroth, and Dizahab.
* `Deu 1:16` "And I charged your judges at that time, saying, 'Hear the causes *_between_* your brothers, and judge righteously *_between_* every man and his brother or the stranger who is with him.
* `Deu 1:39` Moreover, your little ones, which you said should be a prey, and your children, which in that day had no knowledge *_between_* good and evil, they shall go in there, and I will give it to them, and they shall possess it.
* `Deu 5:5` (I stood *_between_* the LORD and you at that time to show you the word of the LORD, for you were afraid by reason of the fire and did not go up upon the mountain), saying,
* `Deu 6:8` And you shall bind them for a sign upon your hand, and they shall be as frontlets *_between_* your eyes.
* `Deu 11:18` "Therefore, you shall lay up these words of mine in your heart and in your soul. You shall bind them for a sign upon your hand, and they shall be as frontlets *_between_* your eyes.
* `Deu 14:1` "You are the children of the LORD your God. You shall not cut yourselves nor make any baldness *_between_* your eyes for the dead.
* `Deu 17:8` "If there arises a matter too hard for you in judgment *_between_* blood and blood, *_between_* plea and plea, and *_between_* stroke and stroke, being matters of controversy within your gates, then you shall arise and go up to the place which the LORD your God chooses.
* `Deu 19:17` Then both the men *_between_* whom the controversy is shall stand before the LORD, before the priests and the judges who shall be in those days.
* `Deu 25:1` "If there is a controversy *_between_* men and they come to judgment so that the judges may judge them, then they shall justify the righteous and condemn the wicked.
* `Deu 33:12` And of Benjamin he said, "The beloved of the LORD shall dwell in safety by him, and the LORD shall cover him all day long, and he shall dwell *_between_* his shoulders."
* `Jsh 3:4` Yet there shall be a space *_between_* you and it, about two thousand cubits by measure. Do not come near it so that you may know the way by which you must go, for you have not passed this way before."
* `Jsh 8:9` Joshua therefore sent them forth. And they went to lie in ambush and stayed *_between_* Beth-el and Ai on the west side of Ai, but Joshua lodged that night among the people.
* `Jsh 8:11` And all the people, even the people of war who were with him, went up, drew near, came before the city, and pitched on the north side of Ai. Now there was a valley *_between_* them and Ai.
* `Jsh 8:12` And he took about five thousand men and set them to lie in ambush *_between_* Beth-el and Ai on the west side of the city.
* `Jsh 18:11` And the lot of the tribe of the children of Benjamin came up according to their families. And the border of their lot came forth *_between_* the children of Judah and the children of Joseph.
* `Jsh 22:25` For the LORD has made the Jordan a boundary *_between_* us and you, you children of Reuben and children of Gad. You have no part in the LORD." So your children shall make our children cease from fearing the LORD.'
* `Jsh 22:27` But it shall be a witness *_between_* us and you and our generations after us so that we may do the service of the LORD before him with our burnt-offerings, with our sacrifices, and with our peace-offerings, and that your children may not say to our children in time to come, "You have no part in the LORD."'
* `Jsh 22:28` Therefore, we said that it shall be when they say this to us or to our generations in time to come, that we may say, 'Behold the pattern of the altar of the LORD which our fathers made, not for burnt-offerings nor for sacrifices, but as a witness *_between_* us and you.'
* `Jsh 22:34` And the children of Reuben and the children of Gad called the altar Ed, saying, "For it shall be a witness *_between_* us that the LORD is God."
* `Jsh 24:7` And when they cried to the LORD, he put darkness *_between_* you and the Egyptians and brought the sea upon them and covered them. And your eyes have seen what I have done in Egypt. And you dwelt in the wilderness for a long season.
* `Jdg 4:5` And she dwelt under the palm-tree of Deborah *_between_* Ramah and Beth-el in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `Jdg 4:17` But Sisera fled away on his feet to the tent of Jael the wife of Heber the Kenite, for there was peace *_between_* Jabin the king of Hazor and the house of Heber the Kenite.
* `Jdg 9:23` God sent an evil spirit *_between_* Abimelech and the men of Shechem, and the men of Shechem dealt treacherously with Abimelech,
* `Jdg 11:10` And the elders of Gilead said to Jephthah, "The LORD shall be a witness *_between_* us if we do not do so according to your words."
* `Jdg 11:27` Therefore, I have not sinned against you, but you do me wrong to war against me. May the LORD the Judge be judge this day *_between_* the children of Israel and the children of Ammon.'"
* `Jdg 13:25` And the Spirit of the LORD began to move him at times in the camp of Dan, *_between_* Zorah and Eshtaol.
* `Jdg 15:4` And Samson went and caught three hundred foxes, and took fire-brands, turned tail to tail, and put a fire-brand in the midst *_between_* two tails.
* `Jdg 16:25` And it came to pass when their hearts were merry, that they said, "Call for Samson so that he may entertain us." And they called for Samson out of the prison-house, and he entertained them. And they set him *_between_* the pillars.
* `Jdg 16:31` Then his brothers and all the house of his father came down, took him, brought him up, and buried him *_between_* Zorah and Eshtaol in the burying-place of Manoah his father. And he judged Israel for twenty years.
* `Jdg 20:38` Now there was an appointed sign *_between_* the men of Israel and the ambushers, that they should make a great flame with smoke to rise from the city.
* `1Sa 4:4` So the people sent to Shiloh so that they might bring from there the ark of the covenant of the LORD of hosts, who dwells *_between_* the cherubim. And the two sons of Eli, Hophni and Phinehas, were there with the ark of the covenant of God.
* `1Sa 7:12` Then Samuel took a stone, set it *_between_* Mizpeh and Shen, and called its name Eben-ezer, saying, "Until now the LORD has helped us."
* `1Sa 7:14` And the cities which the Philistines had taken from Israel were restored to Israel, from Ekron even to Gath, and its borders Israel delivered from the hands of the Philistines. And there was peace *_between_* Israel and the Amorites.
* `1Sa 14:4` And *_between_* the passages by which Jonathan sought to go over to the garrison of the Philistines, there was a sharp rock on one side and a sharp rock on the other side. And the name of one was Bozez and the name of the other Seneh.
* `1Sa 14:42` And Saul said, "Cast lots *_between_* me and Jonathan my son." And Jonathan was taken.
* `1Sa 17:1` Now the Philistines collected their armies to battle and were assembled at Shochoh, which belongs to Judah, and encamped *_between_* Shochoh and Azekah in Ephes-dammim.
* `1Sa 17:3` And the Philistines stood on a mountain on one side, and Israel stood on a mountain on the other side, and there was a valley *_between_* them.
* `1Sa 17:6` And he had greaves of brass upon his legs and a javelin of brass *_between_* his shoulders.
* `1Sa 20:3` And David swore moreover and said, "Your father certainly knows that I have found grace in your eyes and he says, 'Do not let Jonathan know this, lest he should be grieved.' But truly as the LORD lives and as your soul lives, there is only a step *_between_* me and death."
* `1Sa 20:23` And as to the matter which you and I have spoken of, behold, the LORD is *_between_* you and me forever."
* `1Sa 20:42` And Jonathan said to David, "Go in peace, for we have sworn both of us in the name of the LORD, saying, 'The LORD is *_between_* you and me, and *_between_* my offspring and your offspring forever.'" And he arose and departed, and Jonathan went into the city.
* `1Sa 24:12` May the LORD judge *_between_* you and me, and may the LORD avenge me of you. But my hand shall not be upon you.
* `1Sa 24:15` May the LORD therefore be judge and judge *_between_* you and me, and see and plead my cause and deliver me out of your hand."
* `1Sa 26:13` Then David went over to the other side and stood on the top of a hill afar off, a great space being *_between_* them.
* `2Sa 3:1` Now there was a long war *_between_* the house of Saul and the house of David, but David grew stronger and stronger, and the house of Saul became weaker and weaker.
* `2Sa 3:6` And it came to pass, while there was war *_between_* the house of Saul and the house of David, that Abner made himself strong for the house of Saul.
* `2Sa 6:2` And David arose and went with all the people who were with him from Baale of Judah to bring up from there the ark of God, whose name is called by the name of the LORD of hosts who dwells *_between_* the cherubim.
* `2Sa 18:9` And Absalom met the servants of David. And Absalom rode upon a mule, and the mule went under the thick boughs of a great oak, and his head caught hold of the oak and he was suspended *_between_* the heaven and the earth, and the mule that was under him went away.
* `2Sa 18:24` And David sat *_between_* the two gates. And the watchman went up to the roof over the gate on the wall and lifted up his eyes and looked, and behold, a man running alone.
* `2Sa 19:35` I am this day eighty years old. And can I discern *_between_* good and evil? Can your servant taste what I eat or what I drink? Can I hear anymore the voice of singing-men and singing-women? Why then should your servant continue to be a burden to my lord the king?
* `2Sa 21:7` But the king spared Mephibosheth, the son of Jonathan, the son of Saul, because of the LORD'S oath that was *_between_* them, *_between_* David and Jonathan the son of Saul.
* `1Ki 3:9` Give therefore to your servant an understanding heart to judge your people so that I may discern *_between_* good and bad. For who is able to judge this great people of yours?"
* `1Ki 5:12` And the LORD gave Solomon wisdom, as he promised him. And there was peace *_between_* Hiram and Solomon, and the two of them made a league together.
* `1Ki 7:28` And the work of the bases was in this manner: They had borders, and the borders were *_between_* the ledges,
* `1Ki 7:29` And on the borders that were *_between_* the ledges were lions, oxen, and cherubim. And upon the ledges there was a base above, and beneath the lions and oxen were wreaths of hanging work.
* `1Ki 7:46` In the plain of the Jordan the king cast them, in the clay ground *_between_* Succoth and Zarthan.
* `1Ki 14:30` And there was war *_between_* Rehoboam and Jeroboam all their days.
* `1Ki 15:6` And there was war *_between_* Rehoboam and Jeroboam all the days of his life.
* `1Ki 15:7` Now the rest of the acts of Abijam and all that he did, are they not written in the book of the chronicles of the kings of Judah? And there was war *_between_* Abijam and Jeroboam.
* `1Ki 15:16` And there was war *_between_* Asa and Baasha king of Israel all their days.
* `1Ki 15:19` "There is a league *_between_* you and me and *_between_* my father and your father. Behold, I have sent to you a present of silver and gold. Come and break your league with Baasha king of Israel so that he may depart from me."
* `1Ki 15:32` And there was war *_between_* Asa and Baasha king of Israel all their days.
* `1Ki 18:6` So they divided the land *_between_* them to pass throughout it. Ahab went one way by himself, and Obadiah went another way by himself.
* `1Ki 18:21` And Elijah came to all the people and said, "How long do you hesitate *_between_* two opinions? If the LORD is God, follow him, but if Baal, then follow him." And the people did not answer him a word.
* `1Ki 18:42` So Ahab went up to eat and to drink. And Elijah went up to the top of Carmel, cast himself down upon the earth, and put his face *_between_* his knees
* `1Ki 22:1` And they continued three years without war *_between_* Syria and Israel.
* `1Ki 22:34` And a certain man drew a bow at random and smote the king of Israel *_between_* the joints of the harness. Therefore, he said to the driver of his chariot, "Turn your hand and carry me out of the host, for I am wounded."
* `2Ki 9:24` And Jehu drew a bow with his full strength and smote Jehoram *_between_* his arms. The arrow went out at his heart, and he sunk down in his chariot.
* `2Ki 11:17` And Jehoiada made a covenant *_between_* the LORD and the king and the people, that they should be the LORD'S people, and also *_between_* the king and the people.
* `2Ki 16:14` And he also brought the brazen altar, which was before the LORD, from the front of the house, from *_between_* the altar and the house of the LORD, and put it on the north side of the altar.
* `2Ki 19:15` And Hezekiah prayed before the LORD and said, "O LORD God of Israel, dwelling *_between_* the cherubim, you are the God, even you alone, of all the kingdoms of the earth. You have made heaven and earth.
* `2Ki 25:4` And the city was broken up, and all the men of war fled by night by the way of the gate *_between_* two walls, which is by the king's garden (now the Chaldeans were against the city on all sides). And the king went the way toward the plain.
* `1Ch 13:6` And David and all Israel went up to Baalah, that is, to Kirjath-jearim, which belonged to Judah, to bring up from there the ark of God the LORD, who dwells *_between_* the cherubim, whose name is called on it.
* `1Ch 21:16` And David lifted up his eyes and saw the angel of the LORD stand *_between_* the earth and the heaven, having a drawn sword in his hand stretched out over Jerusalem. Then David and the elders of Israel, who were clothed in sackcloth, fell upon their faces.
* `2Ch 4:17` In the plain of the Jordan the king cast them, in the clay ground *_between_* Succoth and Zeredathah.
* `2Ch 12:15` Now the acts of Rehoboam, first and last, are they not written in the book of Shemaiah the prophet and of Iddo the seer concerning genealogies? And there were wars *_between_* Rehoboam and Jeroboam continually.
* `2Ch 13:2` He reigned three years in Jerusalem. His mother's name was Michaiah the daughter of Uriel of Gibeah. And there was war *_between_* Abijah and Jeroboam.
* `2Ch 16:3` "There is a league *_between_* you and me, as there was *_between_* my father and your father. Behold, I have sent you silver and gold. Go, break your league with Baasha king of Israel so that he may depart from me."
* `2Ch 18:33` And a certain man drew a bow at random and smote the king of Israel *_between_* the joints of the harness. Therefore, he said to his chariot-man, "Turn your hand so that you may carry me out of the host, for I am wounded."
* `2Ch 19:10` And whatever cause comes to you from your brothers who dwell in their cities, *_between_* blood and blood, *_between_* law and commandment, statutes and judgments, you shall even warn them that they do not trespass against the LORD so that wrath may not come upon you and upon your brothers. Do this and you shall not trespass.
* `2Ch 23:16` And Jehoiada made a covenant *_between_* himself, *_between_* all the people, and *_between_* the king, that they should be the LORD'S people.
* `Neh 3:32` And *_between_* the ascent of the corner to the sheep-gate the goldsmiths and the merchants repaired.
* `Job 9:33` There is no judge *_between_* us who might lay his hand upon us both.
* `Job 41:16` One is so near to another that no air can come *_between_* them.
* `Psa 80:1` [To the Chief Musician upon Shoshannim Eduth. A Psalm of Asaph.] Give ear, O Shepherd of Israel, you who lead Joseph like a flock. You who dwell *_between_* the cherubim, shine forth.
* `Psa 99:1` The LORD reigns. Let the people tremble. He sits *_between_* the cherubim. Let the earth be moved.
* `Pro 18:18` The lot causes contentions to cease and parts *_between_* the mighty.
* `Sos 1:13` A bundle of myrrh is my well beloved to me. He shall lie all night *_between_* my breasts.
* `Isa 5:3` And now, O inhabitants of Jerusalem and men of Judah, judge, I pray you, *_between_* me and my vineyard.
* `Isa 22:11` You also made a ditch *_between_* the two walls for the water of the old pool. But you have not looked to its maker, neither had respect to him who fashioned it long ago.
* `Isa 37:16` "O LORD of hosts, God of Israel, who dwells *_between_* the cherubim, you are the God, even you alone, of all the kingdoms of the earth. You have made heaven and earth.
* `Isa 59:2` But your iniquities have come *_between_* and separated you and your God, and your sins have hid his face from you so that he will not hear.
* `Jer 7:5` For if you thoroughly amend your ways and your doings, if you thoroughly execute judgment *_between_* a man and his neighbor,
* `Jer 34:18` And I will give the men who have transgressed my covenant, who have not performed the words of the covenant which they had made before me when they cut the calf in two and passed *_between_* its parts—
* `Jer 34:19` The princes of Judah, the princes of Jerusalem, the eunuchs, the priests, and all the people of the land, who passed *_between_* the parts of the calf—
* `Jer 39:4` And it came to pass, when Zedekiah the king of Judah and all the men of war saw them, they fled and went out of the city by night, by the way of the king's garden, by the gate *_between_* the two walls, and he went out the way of the plain.
* `Jer 42:5` Then they said to Jeremiah, "May the LORD be a true and faithful witness *_between_* us, if we do not do according to all things for which the LORD your God sends you to us.
* `Jer 52:7` Then the city was broken up, and all the men of war fled and went forth from the city by night by the way of the gate *_between_* the two walls, which was by the king's garden (now the Chaldeans were by the city on all sides), and they went by the way of the plain.
* `Ezk 4:3` Moreover, take an iron pan and set it for a wall of iron *_between_* you and the city. And set your face against it so that it shall be besieged, and then lay siege against it. This shall be a sign to the house of Israel.
* `Ezk 8:3` And he put forth the form of a hand and took me by a lock of my head. And the Spirit lifted me up *_between_* the earth and the heaven and brought me in the visions of God to Jerusalem, to the door of the inner gate that looks toward the north, where the seat of the image of jealousy was, which provokes to jealousy.
* `Ezk 8:16` And he brought me into the inner court of the LORD'S house, and behold, at the door of the temple of the LORD, *_between_* the porch and the altar, were about twenty-five men with their backs toward the temple of the LORD and their faces toward the east, and they worshiped the sun toward the east.
* `Ezk 10:2` And he spoke to the man clothed with linen, and said, "Go in *_between_* the wheels, even under the cherub, and fill your hand with coals of fire from *_between_* the cherubim and scatter them over the city." And he entered in my sight.
* `Ezk 10:6` And it came to pass, that when he had commanded the man clothed with linen, saying, "Take fire from *_between_* the wheels, from *_between_* the cherubim," he went in and stood beside the wheels.
* `Ezk 10:7` And one cherub stretched forth his hand from *_between_* the cherubim to the fire that was *_between_* the cherubim, took some of it, and put it into the hands of him who was clothed with linen, who took it and went out.
* `Ezk 18:8` Has not given forth upon interest, neither has taken any increase, has withdrawn his hand from iniquity, has executed true judgment *_between_* man and man,
* `Ezk 20:12` Moreover, I also gave them my sabbaths to be a sign *_between_* me and them, so that they might know that I am the LORD who sanctifies them.
* `Ezk 20:20` Hallow my sabbaths, and they shall be a sign *_between_* me and you so that you may know that I am the LORD your God.'
* `Ezk 22:26` Her priests have violated my law and have profaned my holy things. They have put no difference *_between_* the holy and profane, neither have they shown difference *_between_* the unclean and the clean. They have hid their eyes from my sabbaths and I am profaned among them.
* `Ezk 34:17` "And as for you, O my flock, thus says the Lord GOD: 'Behold, I judge *_between_* sheep and sheep, *_between_* the rams and the male goats.
* `Ezk 34:20` Therefore, thus says the Lord GOD to them: "Behold, I, even I, will judge *_between_* the fat sheep and *_between_* the lean sheep.
* `Ezk 34:22` Therefore I will save my flock, and they shall no longer be a prey. And I will judge *_between_* sheep and sheep.
* `Ezk 40:7` And every little chamber was one reed long and one reed broad. And *_between_* the little chambers were five cubits. And the threshold of the gate by the porch of the gate within was one reed.
* `Ezk 41:10` And *_between_* the chambers was the width of twenty cubits around the house on every side.
* `Ezk 41:18` And it was made with cherubim and palm-trees, so that a palm-tree was *_between_* a cherub and a cherub. And every cherub had two faces,
* `Ezk 42:20` He measured it by the four sides. It had a wall around, five hundred reeds long and five hundred broad, to make a separation *_between_* the sanctuary and the profane place.
* `Ezk 43:8` In their setting of their threshold by my thresholds, and their post by my posts, and the wall *_between_* me and them, they have even defiled my holy name by their abominations that they have committed; therefore, I have consumed them in my anger.
* `Ezk 44:23` And they shall teach my people the difference *_between_* the holy and profane, and cause them to discern *_between_* the unclean and the clean.
* `Ezk 47:16` Hamath, Berothah, Sibraim, which is *_between_* the border of Damascus and the border of Hamath; Hazar-hatticon, which is by the border of Hauran.
* `Ezk 48:22` Moreover, from the possession of the Levites and from the possession of the city, being in the midst of that which is the prince's, *_between_* the border of Judah and the border of Benjamin, shall be for the prince.
* `Dan 7:5` And behold another beast, a second, like a bear, and it raised itself on one side, and it had three ribs in its mouth *_between_* its teeth, and they said thus to it: 'Arise, devour much flesh.'
* `Dan 8:5` And as I was considering, behold, a male goat came from the west on the face of the whole earth, and did not touch the ground. And the goat had a notable horn *_between_* his eyes.
* `Dan 8:16` And I heard a man's voice *_between_* the banks of the Ulai, which called, and said, "Gabriel, make this man to understand the vision."
* `Dan 8:21` "And the rough goat is the king of Grecia. And the great horn that is *_between_* his eyes is the first king.
* `Dan 11:45` And he shall plant the tabernacles of his palace *_between_* the seas in the glorious holy mountain. Yet he shall come to his end, and no one shall help him."
* `Hos 2:2` Plead with your mother. Plead, for she is not my wife, neither am I her husband. Let her therefore put away her prostitutions out of her sight and her adulteries from *_between_* her breasts,
* `Joe 2:17` Let the priests, the ministers of the LORD, weep *_between_* the porch and the altar, and let them say, "Spare your people, O LORD, and do not give your heritage to reproach so that the heathen should rule over them. Why should they say among the people, 'Where is their God?'"
* `Jna 4:11` And should I not spare Nineveh, that great city, in which are more than one hundred and twenty thousand persons who cannot discern *_between_* their right hand and their left hand—and also a large number of livestock?"
* `Zch 5:9` Then I lifted up my eyes and looked, and behold, there came out two women, and the wind was in their wings, for they had wings like the wings of a stork. And they lifted up the ephah *_between_* the earth and the heaven.
* `Zch 6:1` And I turned, lifted up my eyes, and looked, and behold, four chariots came out from *_between_* two mountains, and the mountains were mountains of brass.
* `Zch 6:13` Even he shall build the temple of the LORD, and he shall bear the glory and shall sit and rule upon his throne. And he shall be a priest upon his throne. And the counsel of peace shall be *_between_* them both.
* `Zch 9:7` And I will take away his blood out of his mouth and his abominations from *_between_* his teeth. But he who remains, even he, shall be for our God, and he shall be as a governor in Judah, and Ekron as a Jebusite.
* `Zch 11:14` Then I cut apart my other staff, even Union, so that I might break the brotherhood *_between_* Judah and Israel.
* `Zch 13:6` And someone shall say to him, 'What are these wounds *_between_* your hands?' Then he shall answer, 'Those with which I was wounded in the house of my friends.'
* `Mal 2:14` Yet you say, "Why?" Because the LORD has been witness *_between_* you and the wife of your youth, against whom you have dealt treacherously. Yet she is your companion and the wife of your covenant.
* `Mal 3:18` Then you shall return and discern *_between_* the righteous and the wicked, *_between_* him who serves God and him who does not serve him.
* `Mth 18:15` "Moreover, if your brother trespasses against you, go and tell him his fault *_between_* you and him alone. If he hears you, you have gained your brother.
* `Mth 23:35` So that upon you may come all the righteous blood shed upon the earth, from the blood of righteous Abel, to the blood of Zechariah son of Barachiah, whom you slew *_between_* the temple and the altar.
* `Luk 11:51` From the blood of Abel to the blood of Zechariah, who perished *_between_* the altar and the temple.' Truly I say to you, it shall be required of this generation.
* `Luk 16:26` And besides all this, *_between_* us and you there is a great gulf fixed, so that those who would pass from here to you cannot, neither can they pass to us who would come from there.'
* `Luk 23:12` And the same day Pilate and Herod were made friends together, for before they were at enmity *_between_* themselves.
* `Jhn 3:25` Then there arose a question *_between_* some of John's disciples and the Jews about purifying.
* `Act 12:6` And when Herod would have brought him forth, the same night Peter was sleeping *_between_* two soldiers, bound with two chains, and the keepers before the door kept the prison.
* `Act 15:9` And put no difference *_between_* us and them, purifying their hearts by faith.
* `Act 15:39` And the contention was so sharp *_between_* them that they departed, separating one from the other. And so Barnabas took Mark and sailed to Cyprus.
* `Act 23:7` And when he had said this, there arose a dissension *_between_* the Pharisees and the Sadducees, and the multitude was divided.
* `Act 26:31` And when they had gone aside, they talked *_between_* themselves, saying, "This man does nothing worthy of death or of bonds."
* `Rom 2:15` In that they show the work of the law written in their hearts, their conscience also bearing testimony and their thoughts *_between_* one another accusing, or else excusing one another—
* `Rom 10:12` For there is no difference *_between_* the Jew and the Greek. For the same Lord over all is rich to all who call upon him,
* `1Co 6:5` I speak to your shame. Is it so, that there is not a wise man among you? Not even one who will be able to judge *_between_* his brothers?
* `1Co 7:34` There is also a difference *_between_* a wife and a virgin. The unmarried woman is anxious for the things of the Lord so that she may be holy, both in body and in spirit. But she who is married is anxious for the things of the world, how she may please her husband.
* `Eph 2:14` For he is our peace, who has made both one and has broken down the middle wall of partition *_between_* us,
* `Phl 1:23` For I am hard pressed *_between_* the two, having a desire to depart and to be with Christ, which is far better.
* `1Ti 2:5` For there is one God, and there is one mediator *_between_* God and men, the man Christ Jesus,

_219 verses containing BETWEEN_

== BEULAH

* `Isa 62:4` You shall no longer be termed Forsaken, neither shall your land be termed Desolate anymore, but you shall be called Hephzi-bah, and your land *_Beulah_*, for the LORD delights in you, and your land shall be married.

_1 verse containing BEULAH_

== BEWAIL

* `Lev 10:6` And Moses said to Aaron and to Eleazar and Ithamar his sons, "Do not uncover your heads, neither rend your clothes, lest you die, and lest wrath come upon all the people. But let your brothers, the whole house of Israel, *_bewail_* the burning which the LORD has kindled.
* `Deu 21:13` And she shall take off from her the clothing of her captivity and shall remain in your house and *_bewail_* her father and her mother for a full month. And after that, you shall go in to her and be her husband, and she shall be your wife.
* `Jdg 11:37` And she said to her father, "Let this thing be done for me: leave me alone for two months so that I may go up and down upon the mountains and *_bewail_* my virginity—my companions and I."
* `2Co 12:21` And lest, when I come again, my God may humble me among you, and I shall *_bewail_* many who have sinned already and have not repented of the uncleanness, lewdness, and lasciviousness which they have committed.
* `Rev 18:9` "And the kings of the earth who have committed lewdness and lived deliciously with her shall *_bewail_* her and lament for her when they see the smoke of her burning,

_5 verses containing BEWAIL_

== BEWAILED

* `Jdg 11:38` And he said, "Go." And he sent her away for two months. And she went with her companions and *_bewailed_* her virginity upon the mountains.
* `Luk 8:52` And all wept and *_bewailed_* her, but he said, "Do not weep. She is not dead, but sleeps."
* `Luk 23:27` And there followed him a great company of people, including women who also *_bewailed_* and lamented him.

_3 verses containing BEWAILED_

== BEWAILS

* `Jer 4:31` For I have heard a voice as of a woman in travail, and the anguish as of her who brings forth her first child, the voice of the daughter of Zion who *_bewails_* herself, who spreads her hands, saying, "Woe is me now! For my soul is wearied because of murderers."

_1 verse containing BEWAILS_

== BEWARE

* `Gen 24:6` And Abraham said to him, "*_Beware_* that you do not bring my son there again.
* `Exo 23:21` *_Beware_* of him and obey his voice. Do not provoke him, for he will not pardon your transgressions, for my name is in him.
* `Deu 6:12` Then *_beware_* lest you should forget the LORD who brought you forth from the land of Egypt, from the house of bondage.
* `Deu 8:11` "*_Beware_* that you do not forget the LORD your God, in not keeping his commandments, his judgments, and his statutes which I command you this day,
* `Deu 15:9` *_Beware_* that there is not a thought in your wicked heart, saying, 'The seventh year, the year of release, is at hand,' and your eye is evil against your poor brother and you give him nothing. He will cry to the LORD against you, and it shall be sin to you.
* `Jdg 13:4` Now therefore, *_beware_*, I pray you, and do not drink wine nor strong drink, and do not eat any unclean thing.
* `Jdg 13:13` And the angel of the LORD said to Manoah, "Of all that I said to the woman, let her *_beware_*.
* `2Sa 18:12` And the man said to Joab, "Though I should receive one thousand shekels of silver in my hand, yet I would not put forth my hand against the king's son. For in our hearing the king charged you, Abishai, and Ittai, saying, '*_Beware_* that no one touch the young man Absalom.'
* `2Ki 6:9` And the man of God sent to the king of Israel, saying, "*_Beware_* that you do not pass such a place, for there the Syrians have come down."
* `Job 36:18` Because there is wrath, *_beware_* lest he take you away with his stroke. Then a great ransom cannot deliver you.
* `Isa 36:18` *_Beware_* lest Hezekiah persuade you, saying, "The LORD will deliver us." Has any of the gods of the nations delivered his land out of the hand of the king of Assyria?
* `Mth 7:15` "*_Beware_* of false prophets who come to you in sheep's clothing, but inwardly they are ravening wolves.
* `Mth 10:17` But *_beware_* of men, for they will deliver you to the councils and they will scourge you in their synagogues.
* `Mth 16:6` Then Jesus said to them, "Take heed and *_beware_* of the leaven of the Pharisees and of the Sadducees."
* `Mth 16:11` How is it that you do not understand that I did not speak to you concerning bread, but that you should *_beware_* of the leaven of the Pharisees and of the Sadducees?"
* `Mrk 8:15` And he charged them saying, "Take heed, *_beware_* of the leaven of the Pharisees and of the leaven of Herod."
* `Mrk 12:38` And he said to them in his doctrine, "*_Beware_* of the scribes who love to go in long clothing, love salutations in the market-places,
* `Luk 12:1` In the mean time, when there was gathered an innumerable multitude of people so that they trod upon one another, he began to say to his disciples first of all, "*_Beware_* of the leaven of the Pharisees, which is hypocrisy.
* `Luk 12:15` And he said to them, "Take heed, and *_beware_* of covetousness, for a man's life does not consist in the abundance of the things which he possesses."
* `Luk 20:46` "*_Beware_* of the scribes who desire to walk in long robes, love greetings in the markets, the highest seats in the synagogues, and the chief rooms at feasts,
* `Act 13:40` *_Beware_* therefore, lest that come upon you which is spoken in the prophets,
* `Phl 3:2` *_Beware_* of dogs. *_Beware_* of evil-workers. *_Beware_* of the mutilation.
* `Col 2:8` *_Beware_* lest any man make a prey of you through philosophy and vain deceit, after the tradition of men, after the rudiments of the world, and not after Christ.
* `2Pe 3:17` You therefore, beloved, seeing you know these things beforehand, *_beware_* lest you also, being led away with the error of the wicked, fall from your own steadfastness.

_24 verses containing BEWARE_

== BEWITCHED

* `Act 8:9` But there was a certain man called Simon, who previously in the same city used sorcery and *_bewitched_* the people of Samaria, saying that he himself was some great one,
* `Act 8:11` And to him they had regard, because for a long time he had *_bewitched_* them with sorceries.
* `Gal 3:1` O foolish Galatians, who has *_bewitched_* you that you should not obey the truth, before whose eyes Jesus Christ was openly set forth among you as crucified?

_3 verses containing BEWITCHED_

== BEYOND

* `Gen 35:21` And Israel journeyed and spread his tent *_beyond_* the tower of Edar.
* `Gen 50:10` And they came to the threshing-floor of Atad, which is *_beyond_* the Jordan, and there they mourned with a great and very sore lamentation. And he made a mourning for his father seven days.
* `Gen 50:11` And when the inhabitants of the land, the Canaanites, saw the mourning in the floor of Atad, they said, "This is a grievous mourning for the Egyptians." Therefore, its name was called Abel-mizraim, which is *_beyond_* the Jordan.
* `Lev 15:25` 'And if a woman has an issue of her blood for many days not in the time of her separation, or if it runs *_beyond_* the time of her separation, all the days of the issue of her uncleanness shall be as the days of her separation. She shall be unclean.
* `Num 22:18` And Balaam answered and said to the servants of Balak, "If Balak would give me his house full of silver and gold, I could not go *_beyond_* the word of the LORD my God, to do less or more.
* `Num 24:13` 'If Balak would give me his house full of silver and gold, I could not go *_beyond_* the commandment of the LORD to do either good or bad of my own mind, but what the LORD says, that I will speak'?
* `Num 32:19` For we will not inherit with them on the other side of the Jordan and *_beyond_*, because our inheritance has fallen to us on this side of the Jordan eastward."
* `Deu 3:20` Until the LORD has given rest to your brothers, as well as to you, and until they also possess the land which the LORD your God has given them *_beyond_* the Jordan. And then you shall each return to his possession which I have given you.'
* `Deu 3:25` I pray you, let me go over and see the good land that is *_beyond_* the Jordan, that good mountain and Lebanon.'
* `Deu 30:13` Neither is it *_beyond_* the sea so that you should say, 'Who shall go over the sea for us and bring it to us so that we may hear it and do it?'
* `Jsh 9:10` And all that he did to the two kings of the Amorites who were *_beyond_* the Jordan, to Sihon king of Heshbon and to Og king of Bashan, who was at Ashtaroth.
* `Jsh 13:8` With him the Reubenites and the Gadites have received their inheritance, which Moses gave them, *_beyond_* the Jordan eastward, even as Moses the servant of the LORD gave them:
* `Jsh 18:7` But the Levites have no part among you, for the priesthood of the LORD is their inheritance. And Gad, Reuben, and the half the tribe of Manasseh have received their inheritance *_beyond_* the Jordan on the east, which Moses the servant of the LORD gave them."
* `Jdg 3:26` And Ehud escaped while they waited and passed *_beyond_* the quarries and escaped to Seirath.
* `Jdg 5:17` Gilead stayed *_beyond_* the Jordan. And why did Dan remain in ships? Asher continued on the sea-shore and stayed in his breaches.
* `1Sa 20:22` But if I say to the young man, 'Behold, the arrows are *_beyond_* you,' go your way, for the LORD has sent you away.
* `1Sa 20:36` And he said to his boy, "Run, find the arrows which I shoot." And as the boy ran, he shot an arrow *_beyond_* him.
* `1Sa 20:37` And when the boy had come to the place of the arrow which Jonathan had shot, Jonathan cried after the boy and said, "Is the arrow not *_beyond_* you?"
* `2Sa 10:16` And Hadarezer sent and brought out the Syrians who were *_beyond_* the river. And they came to Helam, and Shobach the captain of the host of Hadarezer went before them.
* `1Ki 4:12` Baana the son of Ahilud—to him pertained Taanach, Megiddo, and all Beth-shean, which is by Zartanah beneath Jezreel, from Beth-shean to Abel-meholah, even to the place that is *_beyond_* Jokneam;
* `1Ki 14:15` "For the LORD will smite Israel like a reed is shaken in the water, and he will root up Israel out of this good land which he gave to their fathers and scatter them *_beyond_* the river because they have made their groves, provoking the LORD to anger.
* `1Ch 19:16` And when the Syrians saw that they were defeated before Israel, they sent messengers and drew forth the Syrians who were *_beyond_* the river, and Shophach the captain of the host of Hadarezer went before them.
* `1Ch 26:30` And of the Hebronites, Hashabiah and his brothers, men of valor, one thousand and seven hundred, had the oversight of Israel *_beyond_* the Jordan westward in all the business of the LORD and in the service of the king.
* `2Ch 20:2` Then there came some who told Jehoshaphat, saying, "There comes a great multitude against you from *_beyond_* the sea on this side of Syria, and behold, they are in Hazazon-tamar, which is En-gedi."
* `Ezr 4:17` Then the king sent an answer to Rehum the chancellor, to Shimshai the scribe, and to the rest of their companions who dwell in Samaria, and to the rest *_beyond_* the river: "Peace, and at such a time.
* `Ezr 4:20` There have also been mighty kings over Jerusalem, who have ruled over all countries *_beyond_* the river, and toll, tribute, and custom was paid to them.
* `Ezr 6:6` "Now therefore, Tatnai, governor *_beyond_* the river, Shethar-boznai, and your companions the Apharsachites, who are *_beyond_* the river, keep far from there.
* `Ezr 6:8` Moreover, I make a decree as to what you shall do to the elders of these Jews for the building of this house of God: that from the king's goods, even from the tribute *_beyond_* the river, expenses are to be paid to these men immediately so that they are not hindered,
* `Ezr 7:21` "And I, even I, Artaxerxes the king, make a decree to all the treasurers who are *_beyond_* the river, that whatever Ezra the priest, the scribe of the law of the God of heaven, requires of you, it shall be done speedily,
* `Ezr 7:25` "And you, Ezra, according to the wisdom of your God that is in your hand, set magistrates and judges who may judge all the people who are *_beyond_* the river, even all those who know the laws of your God. And you shall teach those who do not know them.
* `Neh 2:7` Moreover, I said to the king, "If it should please the king, let letters be given to me for the governors *_beyond_* the river so that they may convey me over until I come into Judah,
* `Neh 2:9` Then I came to the governors *_beyond_* the river and gave them the king's letters. Now the king had sent captains of the army and horsemen with me.
* `Neh 12:38` And the other company of those who gave thanks went over against them, and I after them, and the half of the people upon the wall, from *_beyond_* the tower of the furnaces even to the broad wall,
* `Isa 7:20` In the same day the Lord will shave with a razor that is hired from *_beyond_* the river (namely, by the king of Assyria) the head and the hair of the feet. And it shall also consume the beard.
* `Isa 9:1` Nevertheless, there shall be no more gloom to her who was in anguish. In the former time, he brought into contempt the land of Zebulun and the land of Naphtali, but in the latter time, he has made glorious the way of the sea, the land *_beyond_* the Jordan, Galilee of the nations.
* `Isa 18:1` Woe to the land shadowing with wings, which is *_beyond_* the rivers of Cush,
* `Jer 22:19` He shall be buried with the burial of a donkey, drawn and cast forth *_beyond_* the gates of Jerusalem.
* `Jer 25:22` All the kings of Tyre, all the kings of Zidon, the kings of the coastlands which are *_beyond_* the sea;
* `Amo 5:27` Therefore, I will cause you to go into captivity *_beyond_* Damascus," says the LORD, whose name is the God of hosts.
* `Zph 3:10` From *_beyond_* the rivers of Cush my suppliants, even the daughter of my dispersed, shall bring my offering.
* `Mth 4:15` "The land of Zebulun and the land of Naphtali, toward the sea, *_beyond_* the Jordan, Galilee of the Gentiles—
* `Mth 4:25` And great multitudes of people followed him from Galilee, from Decapolis, from Jerusalem, from Judea, and from *_beyond_* the Jordan.
* `Mth 19:1` And it came to pass, that when Jesus had finished these sayings, he departed from Galilee and came into the borders of Judea, *_beyond_* the Jordan.
* `Mrk 3:8` From Jerusalem, from Idumea, from *_beyond_* the Jordan, and those around Tyre and Sidon. A great multitude came to him when they had heard what great things he did.
* `Mrk 6:51` Then he went up to them into the boat, and the wind ceased. And they were greatly amazed in themselves *_beyond_* measure and wondered.
* `Mrk 7:37` And were astonished *_beyond_* measure, saying, "He has done all things well. He makes both the deaf to hear and the mute to speak."
* `Mrk 10:1` And he arose from there and comes into the borders of Judea and *_beyond_* the Jordan. And the people resort to him again, and, as he was accustomed, he taught them again.
* `Mrk 10:26` And they were astonished *_beyond_* measure, saying among themselves, "Who then can be saved?"
* `Jhn 1:28` These things were done in Bethabara *_beyond_* the Jordan where John was baptizing.
* `Jhn 3:26` And they came to John and said to him, "Rabbi, he who was with you *_beyond_* the Jordan, to whom you bore testimony, behold, the same baptizes, and all men come to him."
* `Jhn 10:40` And he went again *_beyond_* the Jordan into the place where John at first baptized, and he stayed there.
* `Act 7:43` You even took up the tabernacle of Moloch and the star of your god Rephan, figures which you made to worship them. I will carry you away *_beyond_* Babylon.'
* `2Co 1:8` For we do not wish, brothers, to have you ignorant of our trouble which came to us in Asia, that we were pressed out of measure, *_beyond_* our strength, so that we despaired even of life.
* `2Co 8:3` For I bear testimony that according to their ability and even *_beyond_* their ability, they were willing of themselves,
* `2Co 10:13` But we will not boast of things *_beyond_* our measure, but according to the measure of the rule which God has distributed to us, a measure to reach even to you.
* `2Co 10:14` For we do not stretch ourselves *_beyond_* our measure, as though we did not reach to you. For we have come as far as to you also in preaching the gospel of Christ,
* `2Co 10:15` Not boasting of things *_beyond_* our measure, that is, of other men's labors, but having hope, when your faith is increased, that we shall be enlarged by you, according to our rule abundantly,
* `2Co 10:16` To preach the gospel in the regions *_beyond_* you, and not to boast in another man's line of things already prepared.
* `Gal 1:13` For you have heard of my manner of life in time past in the Jews' religion, that *_beyond_* measure I persecuted the church of God and wasted it,
* `1Th 4:6` And that no man go *_beyond_* and defraud his brother in any matter, because the Lord is the avenger of all such, as we also have forewarned you and testified.

_60 verses containing BEYOND_

== BEZAI

* `Ezr 2:17` The children of *_Bezai_*, three hundred and twenty-three;
* `Neh 7:23` The children of *_Bezai_*, three hundred and twenty-four;
* `Neh 10:18` Hodijah, Hashum, *_Bezai_*,

_3 verses containing BEZAI_

== BEZALEEL

* `Exo 31:2` "Behold, I have called by name *_Bezaleel_* the son of Uri, the son of Hur, of the tribe of Judah,
* `Exo 35:30` And Moses said to the children of Israel, "Behold, the LORD has called by name *_Bezaleel_*, the son of Uri, the son of Hur, of the tribe of Judah.
* `Exo 36:1` "Then *_Bezaleel_*, Aholiab, and every wise-hearted man, in whom the LORD put wisdom and understanding to know how to work all manner of work for the service of the sanctuary, shall do according to all that the LORD has commanded."
* `Exo 36:2` And Moses called *_Bezaleel_*, Aholiab, and every wise-hearted man, in whose heart the LORD had put wisdom, even everyone whose heart excited him to come to the work to do it,
* `Exo 37:1` And *_Bezaleel_* made the ark of shittim wood. Two and a half cubits was its length, a cubit and a half its breadth, and a cubit and a half its height.
* `Exo 38:22` And *_Bezaleel_* the son of Uri, the son of Hur, of the tribe of Judah, made all that the LORD commanded Moses.
* `1Ch 2:20` And Hur begot Uri, and Uri begot *_Bezaleel_*.
* `2Ch 1:5` Moreover, the brazen altar that *_Bezaleel_* the son of Uri, the son of Hur, had made, he put before the tabernacle of the LORD. And Solomon and the congregation sought it out.
* `Ezr 10:30` And of the sons of Pahath-moab: Adna, Chelal, Benaiah, Maaseiah, Mattaniah, *_Bezaleel_*, Binnui, and Manasseh.

_9 verses containing BEZALEEL_

== BEZEK

* `Jdg 1:4` And Judah went up, and the LORD delivered the Canaanites and the Perizzites into their hand. And they slew ten thousand men in *_Bezek_*.
* `Jdg 1:5` And they found Adoni-*_bezek_* in *_Bezek_* and fought against him, and they slew the Canaanites and the Perizzites.
* `Jdg 1:6` But Adoni-*_bezek_* fled, and they pursued him, caught him, and cut off his thumbs and his great toes.
* `Jdg 1:7` And Adoni-*_bezek_* said, "Seventy kings, having their thumbs and their great toes cut off, gathered their food under my table. As I have done, so God has requited me." And they brought him to Jerusalem, and he died there.
* `1Sa 11:8` And when he numbered them in *_Bezek_*, the children of Israel were three hundred thousand, and the men of Judah thirty thousand.

_5 verses containing BEZEK_

== BEZER

* `Deu 4:43` *_Bezer_* in the wilderness in the plain country of the Reubenites, Ramoth in Gilead of the Gadites, and Golan in Bashan of the Manassites.
* `Jsh 20:8` And on the other side of the Jordan by Jericho eastward, they assigned *_Bezer_* in the wilderness upon the plain out of the tribe of Reuben, Ramoth in Gilead out of the tribe of Gad, and Golan in Bashan out of the tribe of Manasseh.
* `Jsh 21:36` And out of the tribe of Reuben, *_Bezer_* with its suburbs, Jahazah with its suburbs,
* `1Ch 6:78` And on the other side of the Jordan by Jericho, on the east side of the Jordan, were given them out of the tribe of Reuben, *_Bezer_* in the wilderness with its suburbs, Jahzah with its suburbs,
* `1Ch 7:37` *_Bezer_*, Hod, Shamma, Shilshah, Ithran, and Beera.

_5 verses containing BEZER_

== BICHRI

* `2Sa 20:1` And there happened to be a man of Belial there whose name was Sheba, the son of *_Bichri_*, a Benjaminite. And he blew a trumpet and said, "We have no part in David, neither do we have inheritance in the son of Jesse. Every man to his tents, O Israel."
* `2Sa 20:2` So every man of Israel, withdrawing from David, followed Sheba the son of *_Bichri_*, but the men of Judah adhered to their king, from the Jordan even to Jerusalem.
* `2Sa 20:6` And David said to Abishai, "Now Sheba the son of *_Bichri_* shall do us more harm than Absalom did. Take your lord's servants and pursue him, lest he get for himself fortified cities and escape us."
* `2Sa 20:7` And there went out after him Joab's men, the Cherethites, the Pelethites, and all the mighty men. And they went out of Jerusalem to pursue after Sheba the son of *_Bichri_*.
* `2Sa 20:10` But Amasa took no heed to the sword that was in Joab's hand. So he smote him in the fifth rib and shed out his bowels to the ground and did not strike him again, and he died. So Joab and Abishai his brother pursued after Sheba the son of *_Bichri_*.
* `2Sa 20:13` When he was removed out of the highway, all the people went on after Joab to pursue after Sheba the son of *_Bichri_*.
* `2Sa 20:21` The matter is not so. But a man of mount Ephraim, Sheba the son of *_Bichri_* by name, has lifted up his hand against the king, even against David. Deliver him only, and I will depart from the city." And the woman said to Joab, "Behold, his head shall be thrown to you over the wall."
* `2Sa 20:22` Then the woman went to all the people in her wisdom. And they cut off the head of Sheba the son of *_Bichri_* and cast it out to Joab. And he blew a trumpet and they retired from the city, every man to his tent. And Joab returned to the king at Jerusalem.

_8 verses containing BICHRI_

== BID

* `Num 15:38` "Speak to the children of Israel and *_bid_* them that they make themselves fringes on the borders of their garments throughout their generations, and that they put a thread of blue upon the fringe of the borders.
* `Jsh 6:10` And Joshua had commanded the people, saying, "You shall not shout nor make any noise with your voice, neither shall any word proceed from your mouth until the day I *_bid_* you to shout. Then you shall shout."
* `1Sa 9:27` And as they were going down to the end of the city, Samuel said to Saul, "*_Bid_* the servant pass on before us"—and he passed on—"but stand still a while so that I may show you the word of God."
* `2Sa 2:26` Then Abner called to Joab and said, "Shall the sword devour forever? Do you not know that it will be bitterness in the latter end? How long shall it be then before you will *_bid_* the people return from following their brothers?"
* `2Ki 4:24` Then she saddled a donkey and said to her servant, "Drive, and go forward. Do not slack your riding for me unless I *_bid_* you."
* `2Ki 5:13` And his servants came near and spoke to him and said, "My father, if the prophet had *_bid_* you to do some great thing, would you not have done it? How much rather then, when he says to you, 'Wash, and be clean'?"
* `2Ki 10:5` And he who was over the house and he who was over the city, the elders also, and those who brought up the children, sent to Jehu, saying, "We are your servants and will do all that you shall *_bid_* us. We will not make any king. Do that which is good in your eyes."
* `Jna 3:2` "Arise, go to Nineveh, that great city, and preach to it the preaching that I *_bid_* you."
* `Mth 14:28` And Peter answered him and said, "Lord, if it is you, *_bid_* me to come to you on the water."
* `Mth 23:3` Therefore, all that they *_bid_* you to observe, observe and do it, but do not do according to their works, for they say and do not do.
* `Luk 9:61` And another also said, "Lord, I will follow you, but first let me go *_bid_* farewell to those who are at my house."
* `Luk 10:40` But Martha was encumbered with much serving and came to him, and said, "Lord, do you not care that my sister has left me to serve alone? *_Bid_* her therefore to help me."
* `Act 18:21` But *_bid_* them farewell, saying, "I must by all means keep this feast that comes in Jerusalem. But I will return to you, if God wills." And he sailed from Ephesus.

_13 verses containing BID_

== BIDDEN

* `2Sa 16:11` And David said to Abishai and to all his servants, "Behold, my son who came forth from my body seeks my life. How much more now may this Benjaminite do it? Leave him alone and let him curse, for the LORD has *_bidden_* him.
* `Mth 1:24` Then Joseph, being raised from sleep, did as the angel of the Lord had *_bidden_* him and took for himself his wife,

_2 verses containing BIDDEN_

== BIDDING

* `1Sa 22:14` Then Ahimelech answered the king and said, "And who is so faithful among all your servants as David, who is the king's son-in-law, and goes at your *_bidding_* and is honorable in your house?

_1 verse containing BIDDING_

== BIDKAR

* `2Ki 9:25` Then Jehu said to *_Bidkar_* his captain, "Take him up and cast him into the portion of the field of Naboth the Jezreelite. For remember how, when you and I rode together after Ahab his father, the LORD laid this burden upon him:

_1 verse containing BIDKAR_

== BIER

* `2Sa 3:31` And David said to Joab and to all the people who were with him, "Rend your clothes, gird yourselves with sackcloth, and mourn before Abner." And king David himself followed the *_bier_*.
* `Luk 7:14` And he came and touched the *_bier_*. And those who bore him stood still. And he said, "Young man, I say to you, arise."

_2 verses containing BIER_

== BIGTHA

* `Est 1:10` On the seventh day, when the heart of the king was merry with wine, he commanded Mehuman, Biztha, Harbona, *_Bigtha_*, Abagtha, Zethar, and Carcas, the seven chamberlains who served in the presence of Ahasuerus the king,

_1 verse containing BIGTHA_

== BIGTHAN

* `Est 2:21` In those days, while Mordecai sat in the king's gate, two of the king's chamberlains, *_Bigthan_* and Teresh, who were keepers of the door, were angry and sought to lay hands on king Ahasuerus.

_1 verse containing BIGTHAN_

== BIGTHANA

* `Est 6:2` And it was found written that Mordecai had reported *_Bigthana_* and Teresh, two of the king's chamberlains and the keepers of the door, who sought to lay hands on king Ahasuerus.

_1 verse containing BIGTHANA_

== BIGVAI

* `Ezr 2:2` Who came with Zerubbabel: Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, Mizpar, *_Bigvai_*, Rehum, and Baanah. The number of the men of the people of Israel:
* `Ezr 2:14` The children of *_Bigvai_*, two thousand and fifty-six;
* `Ezr 8:14` And of the sons of *_Bigvai_*: Uthai, and Zabbud, and with them seventy males.
* `Neh 7:7` Who came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, *_Bigvai_*, Nehum, and Baanah. The number of the men of the people of Israel was this:
* `Neh 7:19` The children of *_Bigvai_*, two thousand and sixty-seven;
* `Neh 10:16` Adonijah, *_Bigvai_*, Adin,

_6 verses containing BIGVAI_

== BILDAD

* `Job 2:11` Now when Job's three friends heard of all this evil that had come upon him, they each came from his own place: Eliphaz the Temanite, *_Bildad_* the Shuhite, and Zophar the Naamathite—for they had made an appointment together to come to mourn with him and to comfort him.
* `Job 8:1` Then *_Bildad_* the Shuhite answered and said,
* `Job 18:1` Then *_Bildad_* the Shuhite answered and said,
* `Job 25:1` Then *_Bildad_* the Shuhite answered and said,
* `Job 42:9` So Eliphaz the Temanite, *_Bildad_* the Shuhite, and Zophar the Naamathite went and did according as the LORD commanded them. The LORD also accepted Job.

_5 verses containing BILDAD_

== BILEAM

* `1Ch 6:70` And out of the half tribe of Manasseh: Aner with its suburbs and *_Bileam_* with its suburbs for the family of the remnant of the sons of Kohath.

_1 verse containing BILEAM_

== BILGAH

* `1Ch 24:14` The fifteenth to *_Bilgah_*, the sixteenth to Immer,
* `Neh 12:5` Miamin, Maadiah, *_Bilgah_*,
* `Neh 12:18` Of *_Bilgah_*, Shammua; of Shemaiah, Jehonathan;

_3 verses containing BILGAH_

== BILGAI

* `Neh 10:8` Maaziah, *_Bilgai_*, and Shemaiah. These were the priests.

_1 verse containing BILGAI_

== BILHAH

* `Gen 29:29` And Laban gave *_Bilhah_* his servant to Rachel his daughter to be her servant.
* `Gen 30:3` And she said, "Behold, my servant *_Bilhah_*, go in to her, and she shall bear upon my knees so that I may also have children by her."
* `Gen 30:4` And she gave him *_Bilhah_* her servant for a wife, and Jacob went in to her.
* `Gen 30:5` And *_Bilhah_* conceived and bore Jacob a son.
* `Gen 30:7` And *_Bilhah_*, Rachel's servant, conceived again and bore Jacob a second son.
* `Gen 35:22` And it came to pass when Israel dwelt in that land, that Reuben went and lay with *_Bilhah_* his father's concubine. And Israel heard it. Now the sons of Jacob were twelve.
* `Gen 35:25` And the sons of *_Bilhah_*, Rachel's servant: Dan and Naphtali.
* `Gen 37:2` These are the generations of Jacob. Joseph being seventeen years old was feeding the flock with his brothers, and the boy was with the sons of *_Bilhah_* and with the sons of Zilpah, his father's wives. And Joseph brought to his father their evil report.
* `Gen 46:25` These are the sons of *_Bilhah_*, whom Laban gave to Rachel his daughter, and she bore these to Jacob. All the souls were seven.
* `1Ch 4:29` At *_Bilhah_*, at Ezem, at Tolad,
* `1Ch 7:13` The sons of Naphtali: Jahziel, Guni, Jezer, and Shallum, the sons of *_Bilhah_*.

_11 verses containing BILHAH_

== BILHAN

* `Gen 36:27` The children of Ezer are these: *_Bilhan_*, Zaavan, and Achan.
* `1Ch 1:42` The sons of Ezer: *_Bilhan_*, Zavan, and Jakan. The sons of Dishan: Uz and Aran.
* `1Ch 7:10` The son of Jediael: *_Bilhan_*. And the sons of *_Bilhan_*: Jeush, Benjamin, Ehud, Chenaanah, Zethan, Tarshish, and Ahishahar.

_3 verses containing BILHAN_

== BILL

* `Deu 24:1` "When a man has taken a wife and married her, and it comes to pass that she finds no favor in his eyes because he has found some uncleanness in her, let him write her a *_bill_* of divorcement, give it in her hand, and send her out of his house.
* `Deu 24:3` And if the latter husband hates her and writes her a *_bill_* of divorcement, gives it in her hand, and sends her out of his house, or if the latter husband dies, who took her to be his wife,
* `Isa 50:1` Thus says the LORD: "Where is the *_bill_* of your mother's divorcement, whom I have put away? Or which of my creditors is it to whom I have sold you? Behold, for your iniquities you have sold yourselves, and for your transgressions your mother is put away.
* `Jer 3:8` And I saw that for all the causes by which backsliding Israel committed adultery, I had put her away and given her a *_bill_* of divorce. Yet her treacherous sister Judah did not fear, but went and played the harlot also.
* `Mrk 10:4` And they said, "Moses 'allowed a man to write a *_bill_* of divorcement and to put her away.'"
* `Luk 16:6` And he said, 'One hundred measures of oil.' And he said to him, 'Take your *_bill_*, sit down quickly, and write fifty.'
* `Luk 16:7` Then he said to another, 'And how much do you owe?' And he said, 'One hundred measures of wheat.' And he said to him, 'Take your *_bill_* and write eighty.'

_7 verses containing BILL_

== BILLOWS

* `Psa 42:7` Deep calls to deep at the noise of your water-spouts. All your waves and your *_billows_* have gone over me.
* `Jna 2:3` For you had cast me into the deep, in the midst of the seas, and the floods encompassed me. All your *_billows_* and your waves passed over me.

_2 verses containing BILLOWS_

== BILSHAN

* `Ezr 2:2` Who came with Zerubbabel: Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, *_Bilshan_*, Mizpar, Bigvai, Rehum, and Baanah. The number of the men of the people of Israel:
* `Neh 7:7` Who came with Zerubbabel, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, *_Bilshan_*, Mispereth, Bigvai, Nehum, and Baanah. The number of the men of the people of Israel was this:

_2 verses containing BILSHAN_

== BIMHAL

* `1Ch 7:33` And the sons of Japhlet: Pasach, *_Bimhal_*, and Ashvath. These are the children of Japhlet.

_1 verse containing BIMHAL_

== BIND

* `Exo 28:28` And they shall *_bind_* the breast-plate by its rings to the rings of the ephod with a lace of blue so that it may be above the skillfully woven girdle of the ephod and that the breast-plate does not come loose from the ephod.
* `Num 30:2` If a man vows a vow to the LORD or swears an oath to *_bind_* his soul with a bond, he shall not break his word. He shall do according to all that proceeds out of his mouth.
* `Deu 6:8` And you shall *_bind_* them for a sign upon your hand, and they shall be as frontlets between your eyes.
* `Deu 11:18` "Therefore, you shall lay up these words of mine in your heart and in your soul. You shall *_bind_* them for a sign upon your hand, and they shall be as frontlets between your eyes.
* `Deu 14:25` Then you shall turn it into money, *_bind_* up the money in your hand, and go to the place which the LORD your God chooses.
* `Jsh 2:18` Behold, when we come into the land, you shall *_bind_* this line of scarlet cord in the window by which you let us down. And you shall bring your father, your mother, your brothers, and all your father's household home to you.
* `Jdg 15:10` And the men of Judah said, "Why have you come up against us?" And they answered, "We have come to *_bind_* Samson, to do to him as he has done to us."
* `Jdg 15:12` And they said to him, "We have come down to *_bind_* you so that we may deliver you into the hand of the Philistines." And Samson said to them, "Swear to me that you will not fall upon me yourselves."
* `Jdg 15:13` And they spoke to him, saying, "No, but we will *_bind_* you firmly and deliver you into their hand. But surely we will not kill you." And they bound him with two new cords and brought him up from the rock.
* `Jdg 16:5` And the lords of the Philistines came to her and said to her, "Entice him, and see in what his great strength lies and by what means we may prevail against him so that we may *_bind_* him to afflict him. And we will each give you eleven hundred pieces of silver."
* `Jdg 16:7` And Samson said to her, "If they *_bind_* me with seven green cords that were never dried, then I shall become weak and be like any other man."
* `Jdg 16:11` And he said to her, "If they *_bind_* me firmly with new ropes that were never used, then I shall become weak and be like any other man."
* `Job 31:36` Surely I would take it upon my shoulder and *_bind_* it on myself like a crown.
* `Job 38:31` Can you *_bind_* the sweet influences of Pleiades, or loosen the cords of Orion?
* `Job 39:10` Can you *_bind_* the wild ox with ropes in the furrow? Or will he harrow the valleys after you?
* `Job 40:13` Hide them in the dust together. *_Bind_* their faces in secret.
* `Job 41:5` Will you play with him as with a bird? Or will you *_bind_* him for your young women?
* `Psa 105:22` To *_bind_* his princes at his pleasure and teach his elders wisdom.
* `Psa 118:27` God is the LORD, who has shown us light. *_Bind_* the sacrifice with cords, even to the horns of the altar.
* `Psa 149:8` To *_bind_* their kings with chains and their nobles with fetters of iron,
* `Pro 3:3` Do not let mercy and truth forsake you. *_Bind_* them around your neck. Write them upon the tablet of your heart.
* `Pro 6:21` *_Bind_* them continually upon your heart and tie them around your neck.
* `Pro 7:3` *_Bind_* them upon your fingers. Write them upon the tablet of your heart.
* `Isa 8:16` *_Bind_* up the testimony. Seal the law among my disciples.
* `Isa 49:18` Lift up your eyes around and behold. All these assemble themselves and come to you. As I live," says the LORD, "you shall surely clothe yourself with them all as with an ornament, and *_bind_* them on yourself as a bride does.
* `Isa 61:1` The Spirit of the Lord GOD is upon me because the LORD has anointed me to publish good tidings to the meek. He has sent me to *_bind_* up the broken-hearted, to proclaim liberty to the captives and the opening of the prison to those who are bound,
* `Jer 51:63` And it shall be when you have made an end of reading this book, that you shall *_bind_* a stone to it and cast it into the midst of the Euphrates,
* `Ezk 3:25` But you, O son of man, behold, they shall put ropes upon you and shall *_bind_* you with them, and you shall not go out among them.
* `Ezk 5:3` You shall also take from them a few in number and *_bind_* them in your skirts.
* `Ezk 24:17` Forbear to cry, make no mourning for the dead, *_bind_* the turban of your head upon you, put your shoes upon your feet, do not cover your lips, and do not eat the bread of men."
* `Ezk 30:21` "Son of man, I have broken the arm of Pharaoh king of Egypt, and behold, it shall not be bound up to be healed nor a bandage put to it to *_bind_* it to make it strong to hold the sword.
* `Ezk 34:16` "I will seek that which was lost and bring back that which was driven away, and I will *_bind_* up that which was broken and strengthen that which was sick. But I will destroy the fat and the strong. I will feed them with judgment.
* `Dan 3:20` And he commanded the most mighty men who were in his army to *_bind_* Shadrach, Meshach, and Abed-nego, and to cast them into the burning fiery furnace.
* `Hos 6:1` "Come, and let us return to the LORD. For he has torn and he will heal us. He has smitten and he will *_bind_* us up.
* `Hos 10:10` It is in my desire that I should chastise them. And the people shall be gathered against them when they *_bind_* themselves in their two furrows.
* `Mic 1:13` O inhabitant of Lachish, *_bind_* the chariot to the swift beast. She is the beginning of the sin to the daughter of Zion, for the transgressions of Israel were found in you.
* `Mth 13:30` Let both grow together until the harvest. And in the time of harvest I will say to the reapers, "Gather first the tares and *_bind_* them in bundles to burn them, but gather the wheat into my barn."'"
* `Mth 16:19` And I will give to you the keys of the kingdom of heaven. And whatever you *_bind_* on earth shall be bound in heaven, and whatever you loose on earth shall be loosed in heaven."
* `Mth 18:18` Truly I say to you, whatever you *_bind_* on earth shall be bound in heaven, and whatever you loose on earth shall be loosed in heaven.
* `Mth 22:13` Then the king said to the servants, '*_Bind_* him hand and foot and take him away and cast him into outer darkness. There shall be weeping and gnashing of teeth.'
* `Mth 23:4` For they *_bind_* heavy burdens that are grievous to be borne and lay them on men's shoulders, but they themselves will not move them with one of their fingers.
* `Mrk 5:3` Who had his dwelling among the tombs. And no man could *_bind_* him, not even with chains,
* `Act 9:14` And here he has authority from the chief priests to *_bind_* all who call on your name."
* `Act 21:11` And when he had come to us, he took Paul's girdle and bound his own hands and feet, and said, "Thus says the Holy Spirit: 'Thus the Jews at Jerusalem will *_bind_* the man who owns this girdle and deliver him into the hands of the Gentiles.'"

_44 verses containing BIND_

== BINDING

* `Gen 37:7` For behold, we were *_binding_* sheaves in the field, and behold, my sheaf arose and also stood upright, and behold, your sheaves stood around and made obeisance to my sheaf."
* `Gen 49:11` *_Binding_* his foal to the vine and his donkey's colt to the choice vine, he washed his garments in wine and his clothes in the blood of grapes.
* `Exo 28:32` And there shall be a hole in its top in the midst of it. It shall have a *_binding_* of woven work around its hole, like the hole of a habergeon, so that it is not rent.
* `Num 30:13` Every vow and every *_binding_* oath to afflict the soul, her husband may establish it or her husband may make it void.
* `Act 22:4` And I persecuted this way even to death, *_binding_* and delivering into prisons both men and women,

_5 verses containing BINDING_

== BINDS

* `Num 30:3` "If a woman also vows a vow to the LORD and *_binds_* herself by a bond, being in her father's house in her youth,
* `Job 5:18` For he makes sore and *_binds_* up. He wounds and his hands make whole.
* `Job 26:8` He *_binds_* up the waters in his thick clouds, and the cloud is not rent under them.
* `Job 28:11` He *_binds_* the floods from overflowing. The thing that is hid he brings forth to light.
* `Job 30:18` By the great force of my disease my garment is changed. It *_binds_* me around like the collar of my coat.
* `Job 36:13` But the hypocrites in heart heap up wrath. They do not cry when he *_binds_* them.
* `Psa 129:7` With which the reaper does not fill his hand, nor he who *_binds_* sheaves, his bosom;
* `Psa 147:3` He heals the broken in heart and *_binds_* up their wounds.
* `Pro 26:8` As he who *_binds_* a stone in a sling, so is he who gives honor to a fool.
* `Isa 30:26` Moreover, the light of the moon shall be like the light of the sun, and the light of the sun shall be seven-fold, like the light of seven days, in the day that the LORD *_binds_* up the breach of his people and heals the stroke of their wound.
* `Mth 12:29` Or else, how can one enter into a strong man's house and seize his goods unless he first *_binds_* the strong man? Then he will plunder his house.
* `Mrk 3:27` No man can enter into a strong man's house and seize his goods unless he first *_binds_* the strong man. And then he will plunder his house.

_12 verses containing BINDS_

== BINEA

* `1Ch 9:43` And Moza begot *_Binea_*, and Rephaiah his son, Eleasah his son, and Azel his son.

_1 verse containing BINEA_

== BINEAH

* `1Ch 8:37` And Moza begot *_Bineah_*. Rapha was his son, Eleasah his son, Azel his son.

_1 verse containing BINEAH_

== BINNUI

* `Ezr 8:33` Now on the fourth day the silver, the gold, and the vessels were weighed in the house of our God by the hand of Meremoth the son of Uriah the priest, and with him was Eleazar the son of Phinehas, and with them were the Levites Jozabad the son of Jeshua and Noadiah the son of *_Binnui_*.
* `Ezr 10:30` And of the sons of Pahath-moab: Adna, Chelal, Benaiah, Maaseiah, Mattaniah, Bezaleel, *_Binnui_*, and Manasseh.
* `Ezr 10:38` Bani, *_Binnui_*, Shimei,
* `Neh 3:24` After him *_Binnui_* the son of Henadad repaired another piece, from the house of Azariah to the turning of the wall, even to the corner.
* `Neh 7:15` The children of *_Binnui_*, six hundred and forty-eight;
* `Neh 10:9` And the Levites: Jeshua the son of Azaniah, *_Binnui_* of the sons of Henadad, and Kadmiel,
* `Neh 12:8` Moreover, the Levites: Jeshua, *_Binnui_*, Kadmiel, Sherebiah, Judah, and Mattaniah who was over the thanksgiving—he and his brothers.

_7 verses containing BINNUI_

== BIRD

* `Gen 1:20` And God said, "Let the waters abundantly bring forth the moving creature that has life and the *_bird_* that may fly above the earth in the open firmament of heaven."
* `Gen 1:21` And God created the great sea-creatures and every living creature that moves, which the waters brought forth abundantly after their kind, and every winged *_bird_* after its kind. And God saw that it was good.
* `Gen 1:28` And God blessed them, and God said to them, "Be fruitful, multiply, replenish the earth, and subdue it. And have dominion over the fish of the sea, over the *_bird_* of the air, and over every living animal that moves upon the earth."
* `Gen 1:30` And to every beast of the earth, to every *_bird_* of the air, and to every animal that creeps upon the earth, in which is life, I have given every green herb for food." And it was so.
* `Gen 2:19` And out of the ground the LORD God formed every beast of the field and every *_bird_* of the air, and brought them to Adam to see what he would call them. And whatever Adam called every living creature, that was its name.
* `Gen 7:14` They, every beast after its kind, all the livestock after their kind, every creeping animal that creeps upon the earth after its kind, and every *_bird_* after its kind, every *_bird_* of every sort.
* `Gen 7:21` And all flesh died that moved upon the earth, of *_bird_*, of livestock, of beast, of every creeping animal that creeps upon the earth, and every man.
* `Gen 7:23` And every living substance was destroyed which was upon the face of the ground—man, livestock, the creeping animals, and the *_bird_* of heaven—and they were destroyed from the earth. And only Noah and those who were with him in the ark remained alive.
* `Gen 8:17` Bring forth with you every living animal that is with you of all flesh, of *_bird_*, of livestock, and of every creeping animal that creeps upon the earth, so that they may breed abundantly on the earth, be fruitful, and multiply upon the earth."
* `Gen 8:19` Every beast, every creeping animal, every *_bird_*, and whatever creeps upon the earth, after their kinds, went out of the ark.
* `Gen 8:20` And Noah built an altar to the LORD, and took some of every clean beast and some of every clean *_bird_*, and offered burnt-offerings on the altar.
* `Gen 9:2` And the fear of you and the dread of you shall be upon every beast of the earth, upon every *_bird_* of the air, upon all that moves on the earth, and upon all the fish of the sea. Into your hand they are delivered.
* `Gen 9:10` And with every living creature that is with you, of the *_bird_*, of the livestock, and of every beast of the earth with you, from all that go out of the ark, to every beast of the earth.
* `Lev 7:26` Moreover, you shall eat no manner of blood, whether of *_bird_* or beast, in any of your dwellings.
* `Lev 11:46` This is the law of the beasts, of the *_bird_*, of every living creature that moves in the waters, and of every creature that creeps upon the earth,
* `Lev 14:6` As for the living *_bird_*, he shall take it, the cedar-wood, the scarlet, and the hyssop and shall dip them and the living *_bird_* in the blood of the *_bird_* that was killed over the running water.
* `Lev 14:7` And he shall sprinkle upon him who is to be cleansed from the leprosy seven times and shall pronounce him clean, and shall release the living *_bird_* into the open field.
* `Lev 14:51` And he shall take the cedar-wood, the hyssop, the scarlet, and the living *_bird_* and dip them in the blood of the slain *_bird_* and in the running water, and sprinkle the house seven times.
* `Lev 14:52` And he shall cleanse the house with the blood of the *_bird_*, with the running water, with the living *_bird_*, with the cedar-wood, with the hyssop, and with the scarlet.
* `Lev 14:53` But he shall let the living *_bird_* go out of the city into the open fields and make an atonement for the house. And it shall be clean."
* `Lev 17:13` And whatever man there may be of the children of Israel or of the strangers who sojourn among you who hunts and catches any beast or *_bird_* that may be eaten, he shall even pour out its blood and cover it with dust.
* `Lev 20:25` You shall therefore distinguish between clean beasts and unclean and between unclean birds and clean. And you shall not make your souls abominable by beast or by *_bird_*, or by any manner of living animal that creeps on the ground, which I have separated from you as unclean.
* `Deu 4:17` The likeness of any beast that is on the earth, the likeness of any winged *_bird_* that flies in the air,
* `Deu 22:6` "If a *_bird_*'s nest happens to be before you in the way on any tree or on the ground, whether with young ones or eggs, and the mother sitting upon the young or upon the eggs, you shall not take the mother with the young.
* `Job 28:7` There is a path which no *_bird_* knows, and which the falcon's eye has not seen.
* `Job 41:5` Will you play with him as with a *_bird_*? Or will you bind him for your young women?
* `Psa 11:1` [To the Chief Musician. A Psalm of David.] I put my trust in the LORD. How can you say to my soul, "Flee like a *_bird_* to your mountain"?
* `Psa 124:7` Our soul has escaped like a *_bird_* out of the snare of the fowlers. The snare is broken, and we have escaped.
* `Pro 1:17` Surely in vain the net is spread in the sight of any *_bird_*.
* `Pro 6:5` Deliver yourself like a gazelle from the hand of the hunter and like a *_bird_* from the hand of the fowler.
* `Pro 7:23` Until a dart strikes through his liver, as a *_bird_* hastens to the snare, and does not know that it is for his life.
* `Pro 26:2` As the *_bird_* by wandering, as the swallow by flying, so the causeless curse shall not come.
* `Pro 27:8` As a *_bird_* that wanders from her nest, so is a man who wanders from his place.
* `Ecc 10:20` Do not curse the king, not even in your thoughts, and do not curse the rich in your bed-chamber, for a *_bird_* of the air will carry the voice, and that which has wings will tell the matter.
* `Ecc 12:4` And the doors are shut in the streets; when the sound of the grinding is low, and he shall rise up at the voice of the *_bird_*, and all the daughters of music shall be brought low;
* `Isa 16:2` For it shall be, that as a wandering *_bird_* cast out of the nest, so the daughters of Moab shall be at the fords of Arnon.
* `Isa 46:11` Calling a ravenous *_bird_* from the east, the man who executes my counsel from a far country. I have spoken it and I will also bring it to pass. I have purposed it and I will also perform it.
* `Jer 9:10` For the mountains I will take up a weeping and wailing, and for the habitations of the wilderness a lamentation, because they are burned up so that no one can pass through them, neither can men hear the voice of the livestock. Both the *_bird_* of the heavens and the beast have fled. They are gone.
* `Jer 12:9` My heritage is to me like a speckled *_bird_*. The birds around are against her. Come, assemble all the beasts of the field, come to devour.
* `Lam 3:52` [TSADI] My enemies chased me fiercely, like a *_bird_* without cause.
* `Ezk 39:17` "And, son of man, thus says the Lord GOD: 'Say to every feathered *_bird_* and to every beast of the field, "Assemble yourselves, and come. Gather yourselves on every side to my sacrifice that I sacrifice for you, even a great sacrifice upon the mountains of Israel, so that you may eat flesh and drink blood.
* `Ezk 44:31` The priests shall not eat anything that is dead of itself or torn, whether *_bird_* or beast."'"
* `Dan 7:6` After this I beheld, and behold another, like a leopard, which had upon its back four wings of a *_bird_*. The beast also had four heads, and dominion was given to it.
* `Hos 9:11` As for Ephraim, their glory shall fly away like a *_bird_* from the birth, from the womb, and from the conception.
* `Hos 11:11` They shall tremble as a *_bird_* out of Egypt and as a dove out of the land of Assyria. And I will place them in their houses," says the LORD.
* `Amo 3:5` Can a *_bird_* fall in a trap upon the earth where no snare is for him? Shall one take up a trap from the earth and have taken nothing at all?
* `Rev 18:2` And he cried mightily with a strong voice, saying, "'Fallen, fallen is Babylon' the great, and she has become the habitation of demons, the hold of every foul spirit, and a cage for every unclean and hateful *_bird_*.

_47 verses containing BIRD_

== BIRDS

* `Gen 1:22` And God blessed them, saying, "Be fruitful, multiply, fill the waters in the seas, and let *_birds_* multiply on the earth."
* `Gen 1:26` And God said, "Let us make man in our image, after our likeness, and let them have dominion over the fish of the sea, over the *_birds_* of the air, over the livestock, over all the earth, and over every creeping animal that creeps upon the earth."
* `Gen 2:20` And Adam gave names to all livestock, to the *_birds_* of the air, and to every beast of the field, but for Adam, a helper suitable for him was not found.
* `Gen 6:7` And the LORD said, "I will destroy man whom I have created from the face of the earth—man, beast, the creeping animal, and the *_birds_* of the air. For I repent that I have made them."
* `Gen 6:20` Of *_birds_* after their kind, of livestock after their kind, and of every creeping animal of the earth after its kind, two of every sort shall come to you to keep them alive.
* `Gen 7:3` Of *_birds_* of the air also by sevens, the male and the female, to keep their offspring alive on the face of all the earth.
* `Gen 7:8` Of clean beasts, of beasts that are not clean, of *_birds_*, and of every animal that creeps upon the earth,
* `Gen 15:10` And he brought all these to him, divided them in the midst, and laid each piece one against another, but the *_birds_* he did not divide.
* `Gen 15:11` And when the *_birds_* came down upon the carcasses, Abram drove them away.
* `Gen 40:17` And in the uppermost basket there was all manner of baked food for Pharaoh, but the *_birds_* ate them out of the basket upon my head."
* `Gen 40:19` Within three days Pharaoh shall lift up your head from off you and hang you on a tree. And the *_birds_* shall eat your flesh from off you."
* `Lev 1:14` 'And if the burnt sacrifice for his offering to the LORD is of *_birds_*, then he shall bring his offering of turtle-doves or of young pigeons.
* `Lev 11:13` 'And these you shall consider as an abomination among the *_birds_*, and they shall not be eaten, for they are an abomination: the eagle, the vulture, the osprey,
* `Lev 14:4` Then the priest shall command to take for him who is to be cleansed two *_birds_* alive and clean, cedar-wood, scarlet, and hyssop.
* `Lev 14:5` And the priest shall command that one of the *_birds_* be killed in an earthen vessel over running water.
* `Lev 14:49` And he shall take to cleanse the house two *_birds_*, cedar-wood, scarlet, and hyssop.
* `Lev 14:50` And he shall kill one of the *_birds_* in an earthen vessel over running water,
* `Lev 20:25` You shall therefore distinguish between clean beasts and unclean and between unclean *_birds_* and clean. And you shall not make your souls abominable by beast or by bird, or by any manner of living animal that creeps on the ground, which I have separated from you as unclean.
* `Deu 14:11` "All clean *_birds_* you may eat.
* `Deu 14:20` But all clean *_birds_* you may eat.
* `Deu 28:26` And your carcass shall be food for all *_birds_* of the air and for the beasts of the earth, and no man shall drive them away.
* `1Sa 17:44` And the Philistine said to David, "Come to me, and I will give your flesh to the *_birds_* of the air and to the beasts of the field."
* `1Sa 17:46` This day the LORD will deliver you into my hand. And I will smite you and take your head from you. And I will give the carcasses of the host of the Philistines this day to the *_birds_* of the air and to the wild beasts of the earth so that all the earth may know that there is a God in Israel.
* `2Sa 21:10` And Rizpah the daughter of Aiah took sackcloth and spread it for herself upon the rock, from the beginning of harvest until water dropped upon them out of heaven, and allowed neither the *_birds_* of the air to rest on them by day nor the beasts of the field by night.
* `1Ki 4:23` Ten fat oxen, twenty oxen out of the pastures, one hundred sheep, besides deer, gazelles, and fallow-deer, and fattened *_birds_*.
* `1Ki 4:33` And he spoke of trees, from the cedar tree that is in Lebanon even to the hyssop that springs out of the wall. He also spoke of beasts, of *_birds_*, of creeping animals, and of fish.
* `1Ki 14:11` He who dies belonging to Jeroboam in the city the dogs shall eat, and he who dies in the field the *_birds_* of the air shall eat, for the LORD has spoken it."'
* `1Ki 16:4` Anyone belonging to Baasha who dies in the city the dogs shall eat, and anyone belonging to him who dies in the fields the *_birds_* of the air shall eat."
* `1Ki 21:24` He who dies belonging to Ahab in the city the dogs shall eat, and he who dies in the field the *_birds_* of the air shall eat."
* `Neh 5:18` Now that which was prepared for me daily was one ox and six choice sheep, *_birds_* were also prepared for me, and once in ten days an abundance of all sorts of wine. Yet for all this I did not require the bread of the governor, because the bondage was heavy upon this people.
* `Job 12:7` But now ask the beasts, and they shall teach you, and the *_birds_* of the air, and they shall tell you;
* `Job 28:21` It is hid from the eyes of all living and kept close from the *_birds_* of the air.
* `Job 35:11` Who teaches us more than the beasts of the earth and makes us wiser than the *_birds_* of heaven?'
* `Psa 8:8` The *_birds_* of the air, the fish of the sea, and whatever passes through the paths of the seas.
* `Psa 50:11` I know all the *_birds_* of the mountains. And the wild beasts of the field are mine.
* `Psa 78:27` He also rained flesh upon them like dust, and feathered *_birds_* like the sand of the sea.
* `Psa 79:2` They have given the dead bodies of your servants to be food for the *_birds_* of the heaven, the flesh of your saints to the beasts of the earth.
* `Psa 104:12` By them the *_birds_* of the heaven shall have their habitation, which sing among the branches.
* `Psa 104:17` There the *_birds_* make their nests. As for the stork, the fir-trees are her house.
* `Psa 148:10` Beasts and all livestock, creeping animals and flying *_birds_*,
* `Ecc 9:12` For man also does not know his time. As the fish that are taken in an evil net, and as the *_birds_* that are caught in the snare, so are the sons of men snared in an evil time when it falls suddenly upon them.
* `Sos 2:12` The flowers appear on the earth. The time of the singing of *_birds_* has come, and the voice of the turtle-dove is heard in our land.
* `Isa 18:6` They shall be left together to the *_birds_* of the mountains and to the beasts of the earth. And the *_birds_* shall summer upon them, and all the beasts of the earth shall winter upon them.
* `Isa 31:5` As *_birds_* flying, so the LORD of hosts will defend Jerusalem. Defending, he will also deliver it. And passing over, he will preserve it."
* `Jer 4:25` I beheld, and behold, there was no man, and all the *_birds_* of the heavens had fled.
* `Jer 5:27` As a cage is full of *_birds_*, so are their houses full of deceit. Therefore, they have become great and have grown rich.
* `Jer 7:33` And the carcasses of this people shall be food for the *_birds_* of heaven and for the beasts of the earth, and no one shall frighten them away.
* `Jer 12:4` How long shall the land mourn and the herbs of every field wither for the wickedness of those who dwell therein? The beasts are consumed, and also the *_birds_*, because they said, "He will not see our last end."
* `Jer 12:9` My heritage is to me like a speckled bird. The *_birds_* around are against her. Come, assemble all the beasts of the field, come to devour.
* `Jer 15:3` "And I will appoint over them four kinds," says the LORD. "The sword to slay, the dogs to tear, the *_birds_* of the heaven and the beasts of the earth to devour and destroy.
* `Jer 16:4` "They shall die by grievous deaths. They shall not be lamented, neither shall they be buried, but they shall be as dung upon the face of the earth. And they shall be consumed by the sword and by famine, and their carcasses shall be food for the *_birds_* of heaven and for the beasts of the earth."
* `Jer 19:7` And I will make the counsel of Judah and Jerusalem void in this place. And I will cause them to fall by the sword before their enemies and by the hands of those who seek their lives. And their carcasses I will give to be food for the *_birds_* of the heaven and for the beasts of the earth.
* `Jer 34:20` I will even give them into the hand of their enemies and into the hand of those who seek their life. And their dead bodies shall be food for the *_birds_* of the heaven and for the beasts of the earth.
* `Ezk 17:23` On the mountain of the height of Israel I will plant it. And it shall bring forth boughs, bear fruit, and be a majestic cedar. And under it all *_birds_* of every wing shall dwell. In the shade of its branches they shall dwell.
* `Ezk 29:5` And I will leave you thrown into the wilderness—you and all the fish of your rivers. You shall fall upon the open fields. You shall not be brought together, nor gathered. I have given you as food to the beasts of the field and to the *_birds_* of heaven.
* `Ezk 31:6` All the *_birds_* of heaven made their nests in his boughs, and under his branches all the beasts of the field brought forth their young, and under his shade all great nations dwelt.
* `Ezk 31:13` Upon his ruin all the *_birds_* of the heaven shall remain, and all the beasts of the field shall be upon his branches,
* `Ezk 32:4` Then I will leave you upon the land and will cast you forth upon the open field. And I will cause all the *_birds_* of the heaven to remain upon you and will fill the beasts of the whole earth with you.
* `Ezk 38:20` So that the fish of the sea, the *_birds_* of the heaven, the beasts of the field, all creeping animals that creep upon the earth, and all the men who are upon the face of the earth shall shake at my presence, and the mountains shall be overturned, the steep places shall fall, and every wall shall fall to the ground.
* `Ezk 39:4` You shall fall upon the mountains of Israel—you and all your bands, and the people who are with you. I will give you to the ravenous *_birds_* of every sort and to the beasts of the field to be devoured.
* `Dan 2:38` And wherever the children of men dwell, or the beasts of the field, or the *_birds_* of the heaven, he has given into your hand and has made you ruler over them all. You are this head of gold.
* `Dan 4:12` Its leaves were fair and its fruit abundant, and in it was food for all. The beasts of the field had shade under it, the *_birds_* of heaven dwelt among its boughs, and all flesh was fed from it.
* `Dan 4:14` He cried aloud, and said thus: "Hew down the tree and cut off its branches, shake off its leaves and scatter its fruit. Let the beasts escape from under it and the *_birds_* from its branches.
* `Dan 4:21` Whose leaves were fair, its fruit abundant, and in it was food for all, under which the beasts of the field dwelt, and upon whose branches the *_birds_* of heaven had their habitation—
* `Dan 4:33` The same hour, the thing was fulfilled upon Nebuchadnezzar. He was driven from men and ate grass as oxen, and his body was wet with the dew of heaven, until his hairs were grown like eagles' feathers and his nails like *_birds_*' claws.
* `Hos 2:18` And in that day I will make a covenant for them with the beasts of the field, with the *_birds_* of heaven, and with the creeping animals of the ground. And I will break the bow, the sword, and the battle out of the earth, and will make them to lie down in safety.
* `Hos 4:3` Therefore, the land shall mourn, and everyone who dwells in it shall languish, with the beasts of the field and with the *_birds_* of heaven. Even the fish of the sea shall also be taken away.
* `Hos 7:12` When they go, I will spread my net upon them. I will bring them down as the *_birds_* of the heaven. I will chastise them, as their congregation has heard.
* `Zph 1:3` "I will consume man and beast. I will consume the *_birds_* of the heaven, the fish of the sea, and the stumbling-blocks with the wicked. And I will cut off man from off the land," says the LORD.
* `Mth 6:26` Behold the *_birds_* of the air: they do not sow, neither do they reap, nor gather into barns, yet your heavenly Father feeds them. Are you not much better than they are?
* `Mth 8:20` And Jesus says to him, "The foxes have holes and the *_birds_* of the air have nests, but the Son of man has nowhere to lay his head."
* `Mth 13:4` And when he sowed, some seeds fell by the wayside, and the *_birds_* came and devoured them.
* `Mth 13:32` Which indeed is the least of all seeds, but when it is grown, it is the greatest among herbs and becomes a tree so that the '*_birds_* of the air come and lodge on its branches.'"
* `Mrk 4:4` And it came to pass as he sowed, some fell by the wayside and the *_birds_* of the air came and devoured it.
* `Mrk 4:32` But when it is sown, it grows up, becomes greater than all herbs, and shoots out great branches so that the '*_birds_* of the air may lodge under its shade.'"
* `Luk 8:5` "A sower went out to sow his seed, and as he sowed, some fell by the wayside, and it was trodden down and the *_birds_* of the air devoured it.
* `Luk 9:58` And Jesus said to him, "Foxes have holes and *_birds_* of the air have nests, but the Son of man has nowhere to lay his head."
* `Luk 12:24` Consider the ravens: they neither sow nor reap, which neither have store-house, nor barn, and God feeds them. How much more are you better than the *_birds_*?
* `Luk 13:19` It is like a grain of mustard-seed, which a man took and cast into his garden, and it grew and became a great tree and the '*_birds_* of the air lodged in its branches.'"
* `Act 10:12` In which were all manner of four-footed beasts of the earth, wild beasts, creeping animals, and *_birds_* of the air.
* `Act 11:6` Upon which when I had fastened my eyes, I considered, and saw four-footed beasts of the earth, wild beasts, creeping animals, and *_birds_* of the air.
* `Rom 1:23` And changed the glory of the incorruptible God into an image made like corruptible man, *_birds_*, four-footed beasts, and creeping animals.
* `1Co 15:39` All flesh is not the same flesh, but there is one kind of flesh of men, another flesh of beasts, another of fish, and another of *_birds_*.
* `Jms 3:7` For every kind, both of beasts and of *_birds_*, both of creeping things and of animals in the sea, is tamed and has been tamed by mankind.
* `Rev 19:17` And I saw an angel standing in the sun, and he cried with a loud voice, saying to all the *_birds_* that fly in the midst of heaven, "Come, and assemble yourselves to the supper of the great God
* `Rev 19:21` And the remnant were slain with the sword of him who sat upon the horse, which sword proceeds out of his mouth. And all the *_birds_* were filled with their flesh.

_86 verses containing BIRDS_

== BIRSHA

* `Gen 14:2` That these made war with Bera king of Sodom, *_Birsha_* king of Gomorrah, Shinab king of Admah, Shemeber king of Zeboiim, and the king of Bela, which is Zoar.

_1 verse containing BIRSHA_

== BIRTH

* `Gen 25:31` And Jacob said, "Sell to me this day your *_birth_*-right."
* `Gen 25:32` And Esau said, "Behold, I am at the point to die, and what profit shall this *_birth_*-right bring to me?"
* `Gen 25:33` And Jacob said, "Swear to me this day." And he swore to him and sold his *_birth_*-right to Jacob.
* `Gen 25:34` Then Jacob gave Esau bread and pottage of lentils, and he ate and drank and rose and went his way. Thus Esau despised his *_birth_*-right.
* `Gen 27:36` And he said, "Is he not rightly named Jacob? For he has supplanted me twice: he took away my *_birth_*-right, and behold, now he has taken away my blessing." And he said, "Have you not reserved a blessing for me?"
* `Gen 43:33` And they sat before him, the first-born according to his *_birth_*-right and the youngest according to his youth. And the men wondered at one another.
* `Exo 28:10` Six of their names on one stone and the six names of the rest on the other stone according to their *_birth_*.
* `Lev 12:2` "Speak to the children of Israel, saying, 'If a woman conceives and gives *_birth_* to a male child, then she shall be unclean for seven days. According to the days of the separation for her infirmity she shall be unclean.
* `Num 12:12` Do not let her be as one dead, of whom the flesh is half consumed at the time of his *_birth_*."
* `Jdg 13:5` For behold, you shall conceive and bear a son. And no razor shall come on his head, for the child shall be a Nazarite to God from his *_birth_*. And he shall begin to deliver Israel from the hand of the Philistines."
* `Jdg 13:7` But he said to me, 'Behold, you shall conceive and bear a son. And now drink no wine or strong drink, neither eat any unclean thing, for the child shall be a Nazarite to God from his *_birth_* until the day of his death.'"
* `Jdg 16:17` That he told her all his heart and said to her, "No razor has ever come upon my head, for I have been a Nazarite to God from my *_birth_*. If I am shaved, then my strength will go from me, and I shall become weak and be like any other man."
* `2Ki 19:3` And they said to him, "Thus says Hezekiah: 'This day is a day of trouble, of rebuke, and blasphemy, for the children have come to the *_birth_*, and there is not strength to bring forth.
* `1Ch 5:1` Now the sons of Reuben the first-born of Israel (for he was the first-born, but because he defiled his father's bed, his *_birth_*-right was given to the sons of Joseph the son of Israel and the genealogy is not to be reckoned after the *_birth_*-right;
* `1Ch 5:2` For Judah prevailed above his brothers, and from him came the chief ruler, but the *_birth_*-right was Joseph's),
* `Job 3:10` Because it did not prevent my *_birth_* nor hide sorrow from my eyes.
* `Job 3:11` Why did I not die from the womb? Why did I not expire at the time of my *_birth_*?
* `Job 3:16` Or why was I not like a hidden untimely *_birth_*, like infants which never saw light?
* `Psa 22:10` I was cast upon you from my *_birth_*. You are my God from the time I was born.
* `Psa 58:3` The wicked are estranged from their *_birth_*. They go astray as soon as they are born, speaking lies.
* `Psa 58:8` As a snail which melts, let every one of them pass away like the untimely *_birth_* of a woman so that they may not see the sun.
* `Psa 71:6` I have been sustained by you from my *_birth_*. You are he who brought me into life. My praise shall be continually of you.
* `Ecc 6:3` If a man begets a hundred children and lives many years, so that the days of his years are many, but his soul is not filled with good and he also has no burial, I say that the one of an untimely *_birth_* is better than he is.
* `Ecc 7:1` A good name is better than precious ointment, and the day of death than the day of one's *_birth_*.
* `Isa 37:3` And they said to him, "Thus says Hezekiah: 'This day is a day of trouble, of rebuke, and of blasphemy, for the children have come to the *_birth_*, and there is not strength to bring forth.
* `Isa 46:3` "Listen to me, O house of Jacob, and all the remnant of the house of Israel, which are borne by me from the *_birth_*, which are carried from the womb.
* `Isa 66:9` Shall I bring to the *_birth_* and not cause to bring forth?" says the LORD. "Shall I cause to bring forth and shut the womb?" says your God.
* `Jer 20:17` Because he did not slay me at my *_birth_* so that my mother might have been my grave and she always be great with child.
* `Ezk 16:3` And say, 'Thus says the Lord GOD to Jerusalem: "Your *_birth_* and your nativity is of the land of Canaan. Your father was an Amorite and your mother a Hittite.
* `Hos 9:11` As for Ephraim, their glory shall fly away like a bird from the *_birth_*, from the womb, and from the conception.
* `Mth 1:18` Now the *_birth_* of Jesus Christ was in this manner: When his mother, Mary, was espoused to Joseph, before they came together, she was found with child by the Holy Spirit.
* `Luk 1:14` And you shall have joy and gladness, and many shall rejoice at his *_birth_*,
* `Jhn 9:1` And as Jesus passed by, he saw a man who was blind from his *_birth_*.
* `Gal 4:19` My little children, of whom I travail in *_birth_* again until Christ is formed in you,
* `Heb 12:16` Lest there be any fornicator or profane person like Esau, who sold his *_birth_*-right for one morsel of food.
* `Rev 12:2` And she was with child and she cried out, travailing in *_birth_* and in pain to deliver.

_36 verses containing BIRTH_

== BIRTH-RIGHT

* `Gen 25:31` And Jacob said, "Sell to me this day your *_birth-right_*."
* `Gen 25:32` And Esau said, "Behold, I am at the point to die, and what profit shall this *_birth-right_* bring to me?"
* `Gen 25:33` And Jacob said, "Swear to me this day." And he swore to him and sold his *_birth-right_* to Jacob.
* `Gen 25:34` Then Jacob gave Esau bread and pottage of lentils, and he ate and drank and rose and went his way. Thus Esau despised his *_birth-right_*.
* `Gen 27:36` And he said, "Is he not rightly named Jacob? For he has supplanted me twice: he took away my *_birth-right_*, and behold, now he has taken away my blessing." And he said, "Have you not reserved a blessing for me?"
* `Gen 43:33` And they sat before him, the first-born according to his *_birth-right_* and the youngest according to his youth. And the men wondered at one another.
* `1Ch 5:1` Now the sons of Reuben the first-born of Israel (for he was the first-born, but because he defiled his father's bed, his *_birth-right_* was given to the sons of Joseph the son of Israel and the genealogy is not to be reckoned after the *_birth-right_*;
* `1Ch 5:2` For Judah prevailed above his brothers, and from him came the chief ruler, but the *_birth-right_* was Joseph's),
* `Heb 12:16` Lest there be any fornicator or profane person like Esau, who sold his *_birth-right_* for one morsel of food.

_9 verses containing BIRTH-RIGHT_

== BIRTHDAY

* `Gen 40:20` And it came to pass on the third day, which was Pharaoh's *_birthday_*, that he made a feast for all his servants, and he lifted up the head of the chief butler and of the chief baker among his servants.
* `Mth 14:6` But when Herod's *_birthday_* came, the daughter of Herodias danced before them and pleased Herod,
* `Mrk 6:21` And when a convenient day had come, Herod, on his *_birthday_*, made a supper for his lords, high captains, and chief men of Galilee.

_3 verses containing BIRTHDAY_

== BIRZAVITH

* `1Ch 7:31` And the sons of Beriah: Heber and Malchiel, who is the father of *_Birzavith_*.

_1 verse containing BIRZAVITH_

== BISHLAM

* `Ezr 4:7` And in the days of Artaxerxes, *_Bishlam_*, Mithredath, Tabeel, and the rest of their companions wrote to Artaxerxes king of Persia, and the writing of the letter was written in the Syrian language and interpreted in the Syrian language.

_1 verse containing BISHLAM_

== BIT

* `Num 21:6` And the LORD sent fiery serpents among the people, and they *_bit_* the people, and many people of Israel died.
* `Psa 32:9` Do not be like the horse or like the mule, which have no understanding, whose mouth must be held in with *_bit_* and bridle, lest they come near to you.
* `Amo 5:19` As if a man fled from a lion and a bear met him, or went into the house and leaned his hand on the wall and a serpent *_bit_* him.

_3 verses containing BIT_

== BITE

* `Ecc 10:8` He who digs a pit shall fall into it, and whoever breaks a hedge, a serpent shall *_bite_* him.
* `Ecc 10:11` Surely the serpent will *_bite_* without enchantment, and a babbler is no better.
* `Jer 8:17` "For behold, I will send serpents among you, adders which will not be charmed, and they shall *_bite_* you," says the LORD.
* `Amo 9:3` Though they hide themselves on the top of Carmel, I will search and take them out from there. Though they are hid from my sight in the bottom of the sea, from there I will command the serpent, and he shall *_bite_* them.
* `Mic 3:5` Thus says the LORD concerning the prophets who deceive my people, who *_bite_* with their teeth, and cry, "Peace," and he who puts nothing into their mouths, they even prepare war against him:
* `Hab 2:7` Shall they not rise suddenly who *_bite_* you, and awake who disturb you, and you shall be plunder for them?
* `Gal 5:15` But if you *_bite_* and devour one another, take heed that you are not consumed by one another.

_7 verses containing BITE_

== BITES

* `Gen 49:17` Dan shall be a serpent by the way, an adder in the path that *_bites_* the horse-heels so that his rider shall fall backward.
* `Pro 23:32` At the last it *_bites_* like a serpent and stings like an adder.

_2 verses containing BITES_

== BITHIAH

* `1Ch 4:18` And his wife Jehudijah bore Jered the father of Gedor, Heber the father of Socho, and Jekuthiel the father of Zanoah. And these are the sons of *_Bithiah_* the daughter of Pharaoh whom Mered took.

_1 verse containing BITHIAH_

== BITHRON

* `2Sa 2:29` And Abner and his men walked all that night through the plain. And they passed over the Jordan, went through all *_Bithron_*, and came to Mahanaim.

_1 verse containing BITHRON_

== BITHYNIA

* `Act 16:7` After they had come to Mysia, they essayed to go into *_Bithynia_*, but the Spirit did not allow them.
* `1Pe 1:1` Peter, an apostle of Jesus Christ, to the strangers scattered throughout Pontus, Galatia, Cappadocia, Asia, and *_Bithynia_*,

_2 verses containing BITHYNIA_

== BITS

* `Jms 3:3` Behold, we put *_bits_* in the mouths of horses so that they may obey us, and we direct their whole body.

_1 verse containing BITS_

== BITTEN

* `Num 21:8` And the LORD said to Moses, "Make for yourself a fiery serpent and set it upon a pole. And it shall come to pass, that everyone who is *_bitten_*, when he looks upon it, shall live."
* `Num 21:9` And Moses made a serpent of brass and put it upon a pole. And it came to pass, that if a serpent had *_bitten_* any man, when he beheld the serpent of brass, he lived.
* `Job 18:12` His strength shall be hunger-*_bitten_*, and destruction shall be ready at his side.

_3 verses containing BITTEN_

== BITTER

* `Gen 27:34` And when Esau heard the words of his father, he cried with a great and exceedingly *_bitter_* cry and said to his father, "Bless me, even me also, O my father."
* `Exo 1:14` And they made their lives *_bitter_* with hard bondage in mortar, in brick, and in all manner of service in the field. All their service in which they made them serve was with rigor.
* `Exo 12:8` And they shall eat the flesh in that night, roasted with fire. With unleavened bread and *_bitter_* herbs they shall eat it.
* `Exo 15:23` And when they came to Marah, they could not drink the waters of Marah because they were *_bitter_*. Therefore, its name was called Marah.
* `Num 5:18` And the priest shall set the woman before the LORD, uncover the woman's head, and put the offering of memorial in her hands, which is the jealousy-offering. And the priest shall have in his hand the *_bitter_* water that causes the curse.
* `Num 5:19` And the priest shall charge her by an oath and say to the woman, "If no man has lain with you and if you have not gone aside to uncleanness with another instead of your husband, be free from this *_bitter_* water that causes the curse.
* `Num 5:23` 'And the priest shall write these curses in a book and he shall blot them out with the *_bitter_* water.
* `Num 5:24` And he shall cause the woman to drink the *_bitter_* water that causes the curse. And the water that causes the curse shall enter into her and become *_bitter_*.
* `Num 5:27` And when he has made her to drink the water, it shall come to pass, that if she is defiled and has done trespass against her husband, that the water that causes the curse shall enter into her and become *_bitter_*, and her belly shall swell and her thigh shall perish, and the woman shall be a curse among her people.
* `Num 9:11` On the fourteenth day of the second month, at evening, they shall keep it and eat it with unleavened bread and *_bitter_* herbs.
* `Deu 32:24` They shall be burnt with hunger and devoured with burning heat and with *_bitter_* destruction. I will also send the teeth of beasts upon them, with the poison of serpents of the dust.
* `Deu 32:32` For their vine is of the vine of Sodom and of the fields of Gomorrah. Their grapes are grapes of gall, their clusters are *_bitter_*.
* `2Ki 14:26` For the LORD saw the affliction of Israel, that it was very *_bitter_*, for there was no one shut up nor left at large, nor any helper for Israel.
* `Est 4:1` When Mordecai perceived all that was done, Mordecai rent his clothes and put on sackcloth with ashes, went out into the midst of the city, and cried with a loud and *_bitter_* cry.
* `Job 3:20` Why is light given to him who is in misery, and life to the *_bitter_* in soul,
* `Job 13:26` For you write *_bitter_* things against me and make me to possess the iniquities of my youth.
* `Job 23:2` "Even today my complaint is *_bitter_*. My stroke is heavier than my groaning.
* `Psa 64:3` Who whet their tongue like a sword and bend their bows to shoot their arrows, even *_bitter_* words,
* `Pro 5:4` But her end is *_bitter_* as wormwood, sharp as a two-edged sword.
* `Pro 27:7` The full soul loathes a honey-comb, but to the hungry soul every *_bitter_* thing is sweet.
* `Ecc 7:26` And I find more *_bitter_* than death the woman whose heart is snares and nets, and her hands as bonds. Whoever pleases God shall escape from her, but the sinner shall be taken by her.
* `Isa 5:20` Woe to those who call evil good and good evil, who put darkness for light and light for darkness, who put *_bitter_* for sweet and sweet for *_bitter_*!
* `Isa 24:9` They shall not drink wine with a song. Strong drink shall be *_bitter_* to those who drink it.
* `Jer 2:19` Your own wickedness shall correct you, and your backslidings shall reprove you. Know therefore, and see that it is an evil and *_bitter_* thing that you have forsaken the LORD your God and that my fear is not in you," says the Lord GOD of hosts.
* `Jer 4:18` Your way and your doings have procured these things to you. This is your wickedness because it is *_bitter_*, because it reaches to your heart."
* `Jer 6:26` O daughter of my people, gird yourself with sackcloth and wallow yourself in ashes. Make for yourself a mourning, as for an only son, a most *_bitter_* lamentation, for the destroyer shall suddenly come upon us.
* `Jer 31:15` Thus says the LORD: "A voice was heard in Ramah, lamentation and *_bitter_* weeping. Rachel weeping for her children refused to be comforted for her children, because they were no more."
* `Ezk 27:31` And they shall make themselves utterly bald for you and gird themselves with sackcloth. They shall weep for you with bitterness of heart and *_bitter_* wailing.
* `Amo 8:10` I will turn your feasts into mourning and all your songs into lamentation, I will bring up sackcloth upon all loins and baldness upon every head, and I will make it as the mourning of an only son and its end as a *_bitter_* day.
* `Hab 1:6` For behold, I raise up the Chaldeans, that *_bitter_* and hasty nation, which shall march through the breadth of the land to possess the dwelling-places that are not theirs.
* `Col 3:19` Husbands, love your wives and do not be *_bitter_* against them.
* `Jms 3:11` Does a fountain send forth at the same place sweet and *_bitter_* water?
* `Jms 3:14` But if you have *_bitter_* envying and strife in your hearts, do not glory and do not lie against the truth.
* `Rev 8:11` And the name of the star is called Wormwood. And the third part of the waters became wormwood, and many men died by the waters because they were made *_bitter_*.
* `Rev 10:9` And I went to the angel and said to him, "Give me the little book." And he said to me, "Take it and eat it. It shall make your belly *_bitter_*, but it shall be in your mouth sweet as honey."
* `Rev 10:10` And I took the little book out of the angel's hand and ate it. And it was in my mouth sweet as honey, but as soon as I had eaten it, my belly was *_bitter_*.

_36 verses containing BITTER_

== BITTERLY

* `Jdg 5:23` "'Curse Meroz,' said the angel of the LORD, '*_bitterly_* curse its inhabitants, because they did not come to the help of the LORD, to the help of the LORD against the mighty.'
* `Jdg 21:2` And the people came to the house of God and stayed there until evening before God, and they lifted up their voices and wept *_bitterly_*
* `Rth 1:20` And she said to them, "Do not call me Naomi. Call me Mara, for the Almighty has dealt very *_bitterly_* with me.
* `1Sa 1:10` And she was in bitterness of soul and prayed to the LORD and wept *_bitterly_*.
* `Ezr 10:1` Now when Ezra had prayed and when he had confessed, weeping and casting himself down before the house of God, there assembled to him out of Israel a very great congregation of men and women and children, for the people wept very *_bitterly_*.
* `Isa 22:4` Therefore, I said, "Look away from me. I will weep *_bitterly_*. Do not labor to comfort me because of the devastation of the daughter of my people."
* `Isa 33:7` Behold, their valiant ones shall cry outside. The ambassadors of peace shall weep *_bitterly_*.
* `Isa 38:3` And said, "Remember now, O LORD, I implore you, how I have walked before you in truth and with a perfect heart and have done that which is good in your sight." And Hezekiah wept *_bitterly_*.
* `Isa 59:11` We all roar like bears and mourn *_bitterly_* like doves. We look for judgment, but there is none, for salvation, but it is far from us.
* `Jer 13:17` But if you will not hear it, my soul shall weep in secret places for your pride, and my eye shall weep *_bitterly_* and run down with tears, because the LORD'S flock is carried away captive.
* `Jer 22:10` Do not weep for the dead, neither bemoan him, but weep *_bitterly_* for him who goes away, for he shall no longer return nor see his native country.
* `Lam 1:2` [BET] She weeps *_bitterly_* in the night, and her tears are on her cheeks. Among all her lovers she has no one to comfort her. All her friends have dealt treacherously with her. They have become her enemies.
* `Ezk 27:30` They shall cause their voice to be heard against you and shall cry *_bitterly_*. They shall cast up dust upon their heads. They shall wallow themselves in the ashes.
* `Hos 12:14` Ephraim provoked him to anger most *_bitterly_*; therefore, he will leave his blood upon him, and his Lord will return his reproach to him."
* `Zph 1:14` The great day of the LORD is near, it is near and hastens greatly, even the voice of the day of the LORD. The mighty man shall cry there *_bitterly_*.
* `Mth 26:75` And Peter remembered the word of Jesus, who said to him, "Before the cock crows, you will deny me three times." And he went out and wept *_bitterly_*.
* `Luk 22:62` And Peter went out and wept *_bitterly_*.
* `Act 20:37` And they all wept *_bitterly_*, fell on Paul's neck, and kissed him,

_18 verses containing BITTERLY_

== BITTERN

* `Isa 14:23` "I will also make it a possession for the *_bittern_* and pools of water. And I will sweep it with the broom of destruction," says the LORD of hosts.
* `Isa 34:11` But the cormorant and the *_bittern_* shall possess it. The owl and the raven shall dwell in it. And he shall stretch out upon it the line of confusion and the stones of emptiness.
* `Zph 2:14` And flocks shall lie down in the midst of her, all the beasts of the nations. Both the cormorant and the *_bittern_* shall lodge in its upper lintels. Their voice shall sing in the windows. Desolation shall be in the thresholds, for he shall uncover the cedar work.

_3 verses containing BITTERN_

== BITTERNESS

* `1Sa 1:10` And she was in *_bitterness_* of soul and prayed to the LORD and wept bitterly.
* `1Sa 15:32` Then Samuel said, "Bring Agag the king of the Amalekites here to me." And Agag came to him delicately. And Agag said, "Surely the *_bitterness_* of death is past."
* `2Sa 2:26` Then Abner called to Joab and said, "Shall the sword devour forever? Do you not know that it will be *_bitterness_* in the latter end? How long shall it be then before you will bid the people return from following their brothers?"
* `Job 7:11` Therefore, I will not restrain my mouth. I will speak in the anguish of my spirit. I will complain in the *_bitterness_* of my soul.
* `Job 9:18` He will not allow me to take my breath, but fills me with *_bitterness_*.
* `Job 10:1` "My soul is weary of my life. I will leave my complaint upon myself. I will speak in the *_bitterness_* of my soul.
* `Job 21:25` And another dies in the *_bitterness_* of his soul and never eats with pleasure.
* `Pro 14:10` The heart knows its own *_bitterness_*, and a stranger does not intermeddle with its joy.
* `Pro 17:25` A foolish son is a grief to his father, and *_bitterness_* to her who bore him.
* `Isa 38:15` What shall I say? He has both spoken to me, and he himself has done it. I shall go softly all my years in the *_bitterness_* of my soul.
* `Isa 38:17` Behold, for peace I had great *_bitterness_*. But you have in love to my soul delivered it from the pit of corruption, for you have cast all my sins behind your back.
* `Lam 1:4` [DALET] The ways of Zion mourn, because no one comes to the solemn feasts. All her gates are desolate. Her priests sigh. Her virgins are afflicted. She is in *_bitterness_*.
* `Lam 3:15` He has filled me with *_bitterness_*. He has made me drunken with wormwood.
* `Ezk 3:14` So the Spirit lifted me up and took me away, and I went in *_bitterness_*, in the heat of my spirit, but the hand of the LORD was strong upon me.
* `Ezk 21:6` Sigh therefore, son of man, with the breaking of your loins. And with *_bitterness_* sigh before their eyes.
* `Ezk 27:31` And they shall make themselves utterly bald for you and gird themselves with sackcloth. They shall weep for you with *_bitterness_* of heart and bitter wailing.
* `Zch 12:10` "And I will pour upon the house of David and upon the inhabitants of Jerusalem the Spirit of grace and of supplications. And they shall look upon me whom they have pierced, and they shall mourn for him as one mourns for his only son, and shall be in *_bitterness_* for him as one who is in *_bitterness_* for his first-born.
* `Act 8:23` For I perceive that you are in the gall of *_bitterness_* and in the bond of iniquity."
* `Rom 3:14` "Whose mouth is full of cursing and *_bitterness_*."
* `Eph 4:31` Let all *_bitterness_*, wrath, anger, clamor, and evil-speaking be put away from you, along with all malice.
* `Heb 12:15` Look diligently, lest any man fall short of the grace of God; lest any root of *_bitterness_* springing up, trouble you, and by it many be defiled;

_21 verses containing BITTERNESS_

== BIZJOTHJAH

* `Jsh 15:28` Hazar-shual, Beer-sheba, *_Bizjothjah_*,

_1 verse containing BIZJOTHJAH_

== BIZTHA

* `Est 1:10` On the seventh day, when the heart of the king was merry with wine, he commanded Mehuman, *_Biztha_*, Harbona, Bigtha, Abagtha, Zethar, and Carcas, the seven chamberlains who served in the presence of Ahasuerus the king,

_1 verse containing BIZTHA_

== BLACK

* `Lev 13:31` And if the priest looks at the plague of the itching, and behold, it does not appear deeper than the skin and no *_black_* hair in it, then the priest shall shut him up who has the plague of the itching for seven days.
* `Lev 13:37` But if the itch appears to be at a stay and there is *_black_* hair grown in it, the itch is healed and he is clean. And the priest shall pronounce him clean.
* `1Ki 18:45` And it came to pass in a little while, that the heaven was *_black_* with clouds and wind, and there was a great rain. And Ahab rode and went to Jezreel.
* `Est 1:6` Where white, green, and blue hangings were fastened with cords of fine linen and purple to silver rings and pillars of marble. The couches were of gold and silver upon a pavement of red, blue, white, and *_black_* marble.
* `Job 30:30` My skin is *_black_* upon me, and my bones are burned with heat.
* `Pro 7:9` In the twilight, in the evening, in the *_black_* and dark night.
* `Sos 1:5` [Lady:] I am *_black_*, but beautiful, O daughters of Jerusalem, as the tents of Kedar, as the curtains of Solomon.
* `Sos 1:6` Do not look upon me because I am *_black_*, because the sun has looked upon me. My mother's children were angry with me. They made me the keeper of the vineyards, but I have not kept my own vineyard.
* `Sos 5:11` His head is as the most fine gold. His locks are bushy and *_black_* as a raven.
* `Jer 4:28` For this the earth shall mourn and the heavens above shall be *_black_*. For I have spoken it and I have purposed it. I will not repent, neither will I turn back from it."
* `Jer 8:21` For the hurt of the daughter of my people am I hurt. I am *_black_*. Astonishment has taken hold upon me.
* `Jer 14:2` "Judah mourns, and her gates languish. They are *_black_* to the ground. And the cry of Jerusalem has gone up.
* `Lam 5:10` Our skin was *_black_* like an oven because of the terrible famine.
* `Zch 6:2` In the first chariot there were red horses, in the second chariot *_black_* horses,
* `Zch 6:6` The *_black_* horses which are therein go forth into the north country, the white go forth after them, the grizzled go forth toward the south country."
* `Mth 5:36` Neither shall you swear by your head, because you cannot make one hair white or *_black_*.
* `Rev 6:5` And when he had opened the third seal, I heard the third living being say, "Come and see." And I beheld, and behold, a *_black_* horse. And he who sat on him had a pair of balances in his hand.
* `Rev 6:12` And I beheld when he had opened the sixth seal, and behold, there was a great earthquake, and the sun became *_black_* as sackcloth of hair, and the moon became as blood.

_18 verses containing BLACK_

== BLACKER

* `Lam 4:8` [HET] Their visage is *_blacker_* than a coal. They are not known in the streets. Their skin cleaves to their bones. It is withered. It has become like a stick.

_1 verse containing BLACKER_

== BLACKISH

* `Job 6:16` Which are *_blackish_* by reason of the ice, and in which the snow is hid.

_1 verse containing BLACKISH_

== BLACKNESS

* `Job 3:5` Let darkness and the shadow of death stain it. Let a cloud dwell upon it. Let the *_blackness_* of the day terrify it.
* `Isa 50:3` I clothe the heavens with *_blackness_* and I make sackcloth their covering."
* `Joe 2:6` Before their face the people shall be much pained. All faces shall gather *_blackness_*.
* `Nah 2:10` She is empty, void, and waste. And the heart melts, the knees smite together, much pain is in all loins, and all of their faces gather *_blackness_*.
* `Heb 12:18` For you have not come to the mountain that might be touched and that burned with fire, nor to *_blackness_*, to darkness, to tempest,
* `Jde 1:13` They are raging waves of the sea foaming out their own shame. They are wandering stars to whom the *_blackness_* of darkness is reserved forever.

_6 verses containing BLACKNESS_

== BLADE

* `Jdg 3:22` And the hilt also entered after the *_blade_*, and the fat closed upon the *_blade_* so that he could not draw the dagger out of his belly. And the dirt came out.
* `Job 31:22` Then let my arm fall from my shoulder-*_blade_*, and my arm be broken from the bone.
* `Mth 13:26` But when the *_blade_* had sprung up and brought forth fruit, the tares also appeared.
* `Mrk 4:28` For the earth brings forth fruit by itself: first the *_blade_*, then the head, after that the full grain in the head.

_4 verses containing BLADE_

== BLAME

* `Gen 43:9` I will be surety for him. From my hand you shall require him. If I do not bring him to you and set him before you, then let me bear the *_blame_* forever.
* `Gen 44:32` For your servant became surety for the boy to my father, saying, 'If I do not bring him to you, then I will bear the *_blame_* before my father forever.'
* `2Co 8:20` We are avoiding this: that no man should *_blame_* us in this abundance which is administered by us.
* `Eph 1:4` According as he has chosen us in him before the foundation of the world, that we should be holy and without *_blame_* before him in love,

_4 verses containing BLAME_

== BLAMED

* `2Co 6:3` We give no offense in anything so that the ministry is not *_blamed_*,
* `Gal 2:11` But when Peter had come to Antioch, I withstood him to the face because he was to be *_blamed_*.

_2 verses containing BLAMED_

== BLAMELESS

* `Gen 44:10` And he said, "Now also let it be according to your words: he with whom it shall be found shall be my servant, and you shall be *_blameless_*."
* `Jsh 2:17` And the men said to her, "We will be *_blameless_* of this oath of yours which you have made us swear.
* `Jdg 15:3` And Samson said concerning them, "Now I shall be more *_blameless_* than the Philistines, though I do them a displeasure."
* `Mth 12:5` Or have you not read in the law, that on the sabbath the priests in the temple profane the sabbath and are *_blameless_*?
* `1Co 1:8` Who will also confirm you to the end so that you may be *_blameless_* in the day of our Lord Jesus Christ.
* `Phl 2:15` So that you may be *_blameless_* and innocent, the sons of God without rebuke, in the midst of a crooked and perverse nation, among whom you shine as lights in the world,
* `Phl 3:6` Concerning zeal, persecuting the church; with respect to the righteousness which is by the law, found *_blameless_*.
* `Col 1:22` In the body of his flesh through death to present you holy, *_blameless_*, and unreprovable in his sight,
* `1Th 3:13` To the end he may establish your hearts *_blameless_* in holiness before God, even our Father, at the coming of our Lord Jesus Christ with all his saints.
* `1Th 5:23` And may the very God of peace sanctify you wholly. And may your whole spirit, soul, and body be preserved *_blameless_* to the coming of our Lord Jesus Christ.
* `1Ti 3:2` An overseer then must be *_blameless_*, the husband of one wife, vigilant, sober, of good behavior, given to hospitality, apt to teach,
* `1Ti 3:10` And let these also first be proved. Then let them use the office of a deacon, being found *_blameless_*.
* `1Ti 5:7` And these things give in charge, so that they may be *_blameless_*.
* `Tit 1:6` If anyone is *_blameless_*, the husband of one wife, having faithful children, not accused of riot, or disorderly.
* `Tit 1:7` For an overseer must be *_blameless_* as the steward of God, not self-willed, not soon angry, not given to wine, not quarrelsome, not given to filthy lucre,
* `2Pe 3:14` Therefore, beloved, seeing that you look for such things, be diligent that you may be found by him in peace, without spot, and *_blameless_*.

_16 verses containing BLAMELESS_

== BLAMELESSLY

* `Luk 1:6` And they were both righteous before God, walking *_blamelessly_* in all the commandments and ordinances of the Lord.
* `1Th 2:10` You are witnesses, and God also, how holy, justly, and *_blamelessly_* we behaved ourselves among you who believe,

_2 verses containing BLAMELESSLY_

== BLASPHEME

* `2Sa 12:14` But because by this deed you have given great occasion to the enemies of the LORD to *_blaspheme_*, the child also who is born to you shall surely die."
* `Psa 74:10` O God, how long shall the adversary reproach? Shall the enemy *_blaspheme_* your name forever?
* `Mrk 3:28` "Truly I say to you, the sons of men shall be forgiven of all sins and any blasphemies with which they shall *_blaspheme_*.
* `Jhn 10:36` Do you say of him whom the Father has sanctified and sent into the world, 'You *_blaspheme_*,' because I said, 'I am the Son of God'?
* `Act 26:11` And I punished them often in every synagogue and compelled them to *_blaspheme_*, and being exceedingly enraged against them, I persecuted them even to foreign cities.
* `1Ti 1:20` Of whom are Hymeneus and Alexander, whom I have delivered to Satan so that they may learn not to *_blaspheme_*.
* `Jms 2:7` Do they not *_blaspheme_* that worthy name by which you are called?
* `Rev 13:6` And he opened his mouth in blasphemy against God to *_blaspheme_* his name, his tabernacle, and those who dwell in heaven.

_8 verses containing BLASPHEME_

== BLASPHEMED

* `Lev 24:11` And the Israelite woman's son *_blasphemed_* the name of the LORD and cursed. And they brought him to Moses (and his mother's name was Shelomith, the daughter of Dibri, of the tribe of Dan),
* `1Ki 21:10` And set two men before him, sons of Belial, to bear witness against him, saying, 'You *_blasphemed_* God and the king.' And then carry him out and stone him so that he may die."
* `1Ki 21:13` And two men came in, children of Belial, and sat before him. And the men of Belial witnessed against him, even against Naboth, in the presence of the people, saying, "Naboth *_blasphemed_* God and the king." Then they carried him forth out of the city and stoned him with stones so that he died.
* `2Ki 19:6` And Isaiah said to them, "Thus you shall say to your master: 'Thus says the LORD: "Do not be afraid of the words which you have heard, with which the servants of the king of Assyria have *_blasphemed_* me.
* `2Ki 19:22` 'Whom have you reproached and *_blasphemed_*? And against whom have you exalted your voice and lifted up your eyes on high? Even against the Holy One of Israel.
* `Psa 74:18` Remember this: the enemy has reproached, O LORD, and the foolish people have *_blasphemed_* your name.
* `Isa 37:6` And Isaiah said to them, "Thus you shall say to your master: 'Thus says the LORD: "Do not be afraid of the words that you have heard, with which the servants of the king of Assyria have *_blasphemed_* me.
* `Isa 37:23` Whom have you reproached and *_blasphemed_*? And against whom have you exalted your voice and lifted your eyes on high? Even against the Holy One of Israel.
* `Isa 52:5` Now therefore, what do I have here," says the LORD, "that my people are taken away for nothing? Those who rule over them make them to howl," says the LORD, "and my name continually every day is *_blasphemed_*.
* `Isa 65:7` Your iniquities and the iniquities of your fathers together," says the LORD, "who have burned incense upon the mountains and *_blasphemed_* me upon the hills. Therefore, I will measure their former work into their bosom."
* `Ezk 20:27` "Therefore, son of man, speak to the house of Israel, and say to them, 'Thus says the Lord GOD: "Yet in this your fathers have *_blasphemed_* me, in that they have committed a trespass against me.
* `Act 18:6` And when they opposed themselves and *_blasphemed_*, he shook his clothing and said to them, "May your blood be upon your own heads. I am clean. From now on I will go to the Gentiles."
* `Rom 2:24` For "the name of God is *_blasphemed_* among the Gentiles because of you," as it is written.
* `1Ti 6:1` Let as many servants as are under the yoke count their own masters worthy of all honor so that the name of God and his doctrine may not be *_blasphemed_*.
* `Tit 2:5` To be discreet, chaste, keepers of the home, good, obedient to their own husbands, so that the word of God may not be *_blasphemed_*.
* `2Pe 2:2` And many will follow their pernicious ways, by reason of whom the way of truth will be *_blasphemed_*.
* `Rev 16:9` And men were scorched with great heat and they *_blasphemed_* the name of God, who has power over these plagues. And they did not repent to give him glory.
* `Rev 16:11` And *_blasphemed_* the God of heaven because of their pains and their sores. And they did not repent of their deeds.
* `Rev 16:21` And there fell upon men a great hail out of heaven, every stone about the weight of a talent. And men *_blasphemed_* God because of the plague of the hail, because its plague was exceedingly great.

_19 verses containing BLASPHEMED_

== BLASPHEMER

* `1Ti 1:13` I was before a *_blasphemer_*, a persecutor, and injurious, but I obtained mercy because I did it ignorantly in unbelief.

_1 verse containing BLASPHEMER_

== BLASPHEMERS

* `Act 19:37` For you have brought these men here who are neither robbers of temples, nor yet *_blasphemers_* of your goddess.
* `2Ti 3:2` For men will be lovers of their own selves, covetous, boasters, proud, *_blasphemers_*, disobedient to parents, unthankful, unholy,

_2 verses containing BLASPHEMERS_

== BLASPHEMES

* `Lev 24:16` And he who *_blasphemes_* the name of the LORD, he shall surely be put to death, and all the congregation shall certainly stone him. The stranger, as well as he who is born in the land, when he *_blasphemes_* the name of the LORD, shall be put to death.
* `Psa 44:16` Because of the voice of him who reproaches and *_blasphemes_*, because of the enemy and avenger.
* `Mth 9:3` And behold, some of the scribes said within themselves, "This man *_blasphemes_*."
* `Mrk 3:29` But he who *_blasphemes_* against the Holy Spirit never has forgiveness, but is in danger of eternal condemnation"—
* `Luk 12:10` And whoever speaks a word against the Son of man, he shall be forgiven, but to him who *_blasphemes_* against the Holy Spirit, he shall not be forgiven.

_5 verses containing BLASPHEMES_

== BLASPHEMIES

* `Ezk 35:12` And you shall know that I am the LORD and that I have heard all your *_blasphemies_* which you have spoken against the mountains of Israel, saying, 'They are laid desolate. They are given to us to consume.'
* `Mth 15:19` For out of the heart evil thoughts proceed: murders, adulteries, fornications, thefts, false witness, and *_blasphemies_*.
* `Mrk 2:7` "Why does this man thus speak *_blasphemies_*? Who can forgive sins but God only?"
* `Mrk 3:28` "Truly I say to you, the sons of men shall be forgiven of all sins and any *_blasphemies_* with which they shall blaspheme.
* `Luk 5:21` And the scribes and the Pharisees began to reason, saying, "Who is this who speaks *_blasphemies_*? Who can forgive sins but God alone?"
* `Rev 13:5` And there was given to him a mouth speaking great things and *_blasphemies_*, and power was given to him to continue forty-two months.

_6 verses containing BLASPHEMIES_

== BLASPHEMING

* `Act 13:45` But when the Jews saw the multitudes, they were filled with envy and spoke against those things which were uttered by Paul, contradicting and *_blaspheming_*.

_1 verse containing BLASPHEMING_

== BLASPHEMOUS

* `Act 6:11` Then they suborned men, who said, "We have heard him speak *_blasphemous_* words against Moses and against God."
* `Act 6:13` And set up false witnesses, who said, "This man does not cease to speak *_blasphemous_* words against this holy place and the law.

_2 verses containing BLASPHEMOUS_

== BLASPHEMOUSLY

* `Luk 22:65` And many other things they *_blasphemously_* spoke against him.

_1 verse containing BLASPHEMOUSLY_

== BLASPHEMY

* `2Ki 19:3` And they said to him, "Thus says Hezekiah: 'This day is a day of trouble, of rebuke, and *_blasphemy_*, for the children have come to the birth, and there is not strength to bring forth.
* `Isa 37:3` And they said to him, "Thus says Hezekiah: 'This day is a day of trouble, of rebuke, and of *_blasphemy_*, for the children have come to the birth, and there is not strength to bring forth.
* `Mth 12:31` "Therefore, I say to you, for all manner of sin and *_blasphemy_* men shall be forgiven, but for the *_blasphemy_* against the Holy Spirit men shall not be forgiven.
* `Mth 26:65` Then the high priest rent his clothes, saying, "He has spoken *_blasphemy_*. What further need do we have of witnesses? Behold, now you have heard his *_blasphemy_*.
* `Mrk 7:22` Thefts, covetousness, wickedness, deceit, lasciviousness, an evil eye, *_blasphemy_*, pride, foolishness.
* `Mrk 14:64` You have heard the *_blasphemy_*. What do you think?" And they all condemned him to be guilty of death.
* `Jhn 10:33` The Jews answered him, saying, "For a good work we do not stone you, but for *_blasphemy_*, because you, being a man, make yourself God."
* `Col 3:8` But now you also put off all these: anger, wrath, malice, *_blasphemy_*, and filthy communication out of your mouth.
* `Rev 2:9` "'"I know your works, tribulation, and poverty (but you are rich), and I know the *_blasphemy_* of those who say they are Jews and are not, but are the synagogue of Satan.
* `Rev 13:1` And I stood upon the sand of the sea and saw a beast rise up out of the sea having seven heads and ten horns, and upon his horns ten crowns and upon his heads the name of *_blasphemy_*.
* `Rev 13:6` And he opened his mouth in *_blasphemy_* against God to blaspheme his name, his tabernacle, and those who dwell in heaven.
* `Rev 17:3` So he carried me away in the Spirit into the wilderness. And I saw a woman sit upon a scarlet-colored beast that was full of names of *_blasphemy_* and had seven heads and ten horns.

_12 verses containing BLASPHEMY_

== BLAST

* `Exo 15:8` And with the *_blast_* of your nostrils the waters were collected, the floods stood upright like a heap, and the depths were congealed in the heart of the sea.
* `Jsh 6:5` And it shall come to pass, that when they make a long *_blast_* with the ram's horn, and when you hear the sound of the trumpet, all the people shall shout with a great shout. And the wall of the city shall fall down flat, and the people shall each ascend straight before him."
* `2Sa 22:16` And the channels of the sea appeared, the foundations of the world were laid open at the rebuking of the LORD, at the *_blast_* of the breath of his nostrils.
* `Job 4:9` By the *_blast_* of God they perish, and by the breath of his nostrils they are consumed.
* `Psa 18:15` Then the channels of waters were seen and the foundations of the world were uncovered at your rebuke, O LORD, at the *_blast_* of the breath of your nostrils.
* `Isa 25:4` For you have been a defense to the poor, a defense to the needy in his distress, a refuge from the storm, a shade from the heat, when the *_blast_* of the terrible ones is like a storm against the wall.

_6 verses containing BLAST_

== BLASTED

* `Gen 41:6` And behold, seven heads, thin and *_blasted_* with the east wind, sprung up after them.
* `Gen 41:23` And behold, seven heads, withered, thin, and *_blasted_* with the east wind, sprung up after them.
* `Gen 41:27` And the seven thin and ill-favored cows that came up after them are seven years, and the seven empty heads *_blasted_* with the east wind will be seven years of famine.
* `2Ki 19:26` Therefore, their inhabitants were of small power, they were dismayed and confounded, they were as the grass of the field, as the green herb, as the grass on the house-tops, and as grain *_blasted_* before it is grown up.
* `Isa 37:27` Therefore, their inhabitants were of small power. They were dismayed and confounded. They were like the grass of the field, like the green herb, like the grass on the house-tops, and like grain *_blasted_* before it is grown up.

_5 verses containing BLASTED_

== BLASTUS

* `Act 12:20` And Herod was highly displeased with those of Tyre and Sidon. But they came with one accord to him, and having made *_Blastus_* the king's chamberlain their friend, desired peace, because their country was nourished by the king's country.

_1 verse containing BLASTUS_

== BLAZE

* `Mrk 1:45` But he went out and began to publish it much and to *_blaze_* abroad the matter; therefore, Jesus could no longer openly enter into the city, but was outside in desolate places. And they came to him from every quarter.

_1 verse containing BLAZE_

