= IBEX - INCURABLE
:toc:

== IBEX

* `Deu 14:5` The deer, the gazelle, the fallow-deer, the wild-goat, the *_ibex_*, the wild ox, and the chamois.

_1 verse containing IBEX_

== IBHAR

* `2Sa 5:15` *_Ibhar_*, Elishua, Nepheg, Japhia,
* `1Ch 3:6` And also *_Ibhar_*, Elishama, Eliphelet,
* `1Ch 14:5` *_Ibhar_*, Elishua, Elpalet,

_3 verses containing IBHAR_

== IBLEAM

* `Jsh 17:11` And in Issachar and in Asher, Manasseh had Beth-shean and its towns, *_Ibleam_* and its towns, the inhabitants of Dor and its towns, the inhabitants of En-dor and its towns, the inhabitants of Tanach and its towns, and the inhabitants of Megiddo and its towns, even three countries.
* `Jdg 1:27` Manasseh did not expel the inhabitants of Beth-shean and its towns, nor Tanach and its towns, nor the inhabitants of Dor and its towns, nor the inhabitants of *_Ibleam_* and its towns, nor the inhabitants of Megiddo and its towns, but the Canaanites would dwell in that land.
* `2Ki 9:27` But when Ahaziah the king of Judah saw this, he fled by the way of the garden house. And Jehu followed him and said, "Smite him also in the chariot." And they did so at the going up to Gur, which is by *_Ibleam_*. And he fled to Megiddo and died there.

_3 verses containing IBLEAM_

== IBNEIAH

* `1Ch 9:8` And *_Ibneiah_* the son of Jeroham, and Elah the son of Uzzi, the son of Michri, and Meshullam the son of Shephatiah, the son of Reuel, the son of Ibnijah,

_1 verse containing IBNEIAH_

== IBNIJAH

* `1Ch 9:8` And Ibneiah the son of Jeroham, and Elah the son of Uzzi, the son of Michri, and Meshullam the son of Shephatiah, the son of Reuel, the son of *_Ibnijah_*,

_1 verse containing IBNIJAH_

== IBRI

* `1Ch 24:27` The sons of Merari by Jaaziah: Beno, Shoham, Zaccur, and *_Ibri_*.

_1 verse containing IBRI_

== IBZAN

* `Jdg 12:8` And after him *_Ibzan_* of Beth-lehem judged Israel.
* `Jdg 12:10` Then *_Ibzan_* died and was buried at Beth-lehem.

_2 verses containing IBZAN_

== ICE

* `Job 6:16` Which are blackish by reason of the *_ice_*, and in which the snow is hid.
* `Job 38:29` Out of whose womb did the *_ice_* come? And the hoary frost of heaven, who has engendered it?
* `Psa 147:17` He casts forth his *_ice_* like morsels. Who can stand before his cold?

_3 verses containing ICE_

== ICHABOD

* `1Sa 4:21` And she named the child *_Ichabod_*, saying, "The glory has departed from Israel"—because the ark of God was taken and because of her father-in-law and her husband.
* `1Sa 14:3` Along with Ahiah, the son of Ahitub, *_Ichabod_*'s brother, the son of Phinehas, the son of Eli, the LORD'S priest in Shiloh, wearing an ephod. And the people did not know that Jonathan was gone.

_2 verses containing ICHABOD_

== ICONIUM

* `Act 13:51` But they shook off the dust of their feet against them and came to *_Iconium_*.
* `Act 14:1` And it came to pass in *_Iconium_*, that they went both together into the synagogue of the Jews and spoke in such a way that a great multitude both of the Jews and also of the Greeks believed.
* `Act 14:19` And some Jews from Antioch and *_Iconium_* came there, who persuaded the people. And having stoned Paul, they drew him out of the city supposing him to be dead.
* `Act 14:21` And when they had preached the gospel to that city and had taught many, they returned again to Lystra, to *_Iconium_*, and to Antioch,
* `Act 16:2` He was well reported of by the brothers who were at Lystra and *_Iconium_*.
* `2Ti 3:11` Persecutions, and afflictions which came to me at Antioch, at *_Iconium_*, and at Lystra. I endured such persecutions, and out of them all the Lord delivered me.

_6 verses containing ICONIUM_

== IDALAH

* `Jsh 19:15` And Kattath, Nahallal, Shimron, *_Idalah_*, and Beth-lehem; twelve cities with their villages.

_1 verse containing IDALAH_

== IDBASH

* `1Ch 4:3` And these were the sons of the father of Etam: Jezreel, Ishma, and *_Idbash_*, and the name of their sister was Hazelelponi,

_1 verse containing IDBASH_

== IDDO

* `1Ki 4:14` Ahinadab the son of *_Iddo_* had Mahanaim;
* `1Ch 6:21` Joah his son, *_Iddo_* his son, Zerah his son, and Jeaterai his son.
* `1Ch 27:21` Of the half tribe of Manasseh in Gilead, *_Iddo_* the son of Zechariah; of Benjamin, Jaasiel the son of Abner;
* `2Ch 9:29` Now the rest of the acts of Solomon, first and last, are they not written in the book of Nathan the prophet, in the prophecy of Ahijah the Shilonite, and in the visions of *_Iddo_* the seer against Jeroboam the son of Nebat?
* `2Ch 12:15` Now the acts of Rehoboam, first and last, are they not written in the book of Shemaiah the prophet and of *_Iddo_* the seer concerning genealogies? And there were wars between Rehoboam and Jeroboam continually.
* `2Ch 13:22` And the rest of the acts of Abijah, along with his ways and his sayings, are written in the story of the prophet *_Iddo_*.
* `Ezr 5:1` Then the prophets, Haggai the prophet and Zechariah the son of *_Iddo_*, prophesied to the Jews who were in Judah and Jerusalem in the name of the God of Israel, even to them.
* `Ezr 6:14` And the elders of the Jews built, and they prospered through the prophesying of Haggai the prophet and Zechariah the son of *_Iddo_*. And they built and finished it according to the commandment of the God of Israel and according to the commandment of Cyrus, Darius, and Artaxerxes king of Persia.
* `Ezr 8:17` And I sent them with commandment to *_Iddo_* the chief in Casiphia, and I told them what they should say to *_Iddo_* and to his brothers the Nethinims in Casiphia, that they should bring to us ministers for the house of our God.
* `Neh 12:4` *_Iddo_*, Ginnetho, Abijah,
* `Neh 12:16` Of *_Iddo_*, Zechariah; of Ginnethon, Meshullam;
* `Zch 1:1` In the eighth month, in the second year of Darius, the word of the LORD came to the prophet Zechariah, the son of Barachiah, the son of *_Iddo_*, saying,
* `Zch 1:7` On the twenty-fourth day of the eleventh month, which is the month Sebat, in the second year of Darius, the word of the LORD came to the prophet Zechariah, the son of Barachiah, the son of *_Iddo_*, saying,

_13 verses containing IDDO_

== IDLE

* `Exo 5:8` And the number of the bricks which they made before, you shall lay upon them. You shall not diminish anything thereof. Because they are *_idle_*, therefore they cry, saying, 'Let us go and sacrifice to our God.'
* `Exo 5:17` But he said, "You are *_idle_*. You are *_idle_*. Therefore, you say, 'Let us go and do sacrifice to the LORD.'
* `Pro 19:15` Slothfulness casts into a deep sleep, and an *_idle_* soul shall suffer hunger.
* `Zch 11:17` "Woe to the *_idle_* shepherd who leaves the flock! The sword shall be upon his arm and upon his right eye. His arm shall be wholly dried up and his right eye shall be utterly darkened."
* `Mth 12:36` But I say to you, that for every *_idle_* word that men speak, they shall give account on the day of judgment.
* `Mth 20:3` And he went out about the third hour and saw others standing *_idle_* in the market-place,
* `Mth 20:6` And about the eleventh hour he went out and found others standing *_idle_*, and says to them, 'Why do you stand here all day *_idle_*?'
* `Luk 24:11` Their words seemed to them as *_idle_* tales, and they did not believe them.
* `1Ti 5:13` And at the same time, they learn to be *_idle_*, wandering around from house to house, and not only *_idle_*, but tattlers also, and busy-bodies, speaking things which they ought not.
* `Tit 1:12` One of their own, even a prophet of their own, said, "The Cretians are always liars, evil beasts, *_idle_* gluttons."

_10 verses containing IDLE_

== IDLENESS

* `Pro 31:27` [TSADI] She looks well to the ways of her household and does not eat the bread of *_idleness_*.
* `Ecc 10:18` By much slothfulness the building decays, and through *_idleness_* of the hands the house drops through.
* `Ezk 16:49` Behold, this was the iniquity of your sister Sodom: pride, fullness of bread, and abundance of *_idleness_* was in her and in her daughters, neither did she strengthen the hand of the poor and needy.

_3 verses containing IDLENESS_

== IDOL

* `1Ki 15:13` And also Maachah his mother, he even removed her from being queen because she had made an *_idol_* in a grove. And Asa destroyed her *_idol_* and burnt it by the brook Kidron.
* `2Ch 15:16` And also concerning Maachah the mother of Asa the king, he removed her from being queen because she had made an *_idol_* in a grove. And Asa cut down her *_idol_*, stamped it, and burnt it at the brook Kidron.
* `2Ch 33:7` And he set a carved image, the *_idol_* which he had made, in the house of God, of which God had said to David and to Solomon his son, "In this house and in Jerusalem, which I have chosen before all the tribes of Israel, I will put my name forever.
* `2Ch 33:15` And he took away the strange gods, the *_idol_* out of the house of the LORD, and all the altars that he had built on the mountain of the house of the LORD and in Jerusalem, and cast them out of the city.
* `Isa 48:5` I have even from the beginning declared it to you. Before it came to pass I showed it to you, lest you should say, 'My *_idol_* has done them, and my engraved image and my molten image has commanded them.'
* `Isa 66:3` He who kills an ox is as if he slew a man. He who sacrifices a lamb is as if he cut off a dog's neck. He who offers an oblation is as if he offered swine's blood. He who burns incense is as if he blessed an *_idol_*. Indeed, they have chosen their own ways, and their soul delights in their abominations.
* `Jer 22:28` "Is this man Coniah a despised broken *_idol_*? Is he a vessel in which there is no pleasure? Why are they cast out—he and his offspring—and are cast into a land which they do not know?
* `Act 7:41` And they made a calf in those days, offered sacrifice to the *_idol_*, and rejoiced in the works of their own hands.
* `1Co 8:4` Therefore, as concerning the eating of those things that are offered in sacrifice to idols, we know that an *_idol_* is nothing in the world and that there is no other God but one.
* `1Co 8:7` But that knowledge is not in every man. For some, with consciousness of the *_idol_* to this hour, eat it as a thing offered to an *_idol_*, and their conscience, being weak, is defiled.
* `1Co 8:10` For if any man sees you, who have knowledge, eating in the *_idol_*'s temple, will the conscience of him who is weak not be emboldened to eat those things which are offered to idols?
* `1Co 10:19` What then do I say? That the *_idol_* is anything, or that which is offered in sacrifice to idols is anything?

_12 verses containing IDOL_

== IDOLATER

* `1Co 5:11` But now I have written to you not to keep company with any man who is called a brother if he is a lewd person, covetous, an *_idolater_*, a railer, a drunkard, or an extortioner. Do not even eat with such a person.
* `Eph 5:5` For this you know, that no lewd person, unclean person, or covetous man, who is an *_idolater_*, has any inheritance in the kingdom of Christ and of God.

_2 verses containing IDOLATER_

== IDOLATERS

* `1Co 5:10` Yet not altogether with lewd persons of this world, or with the covetous, extortioners, or with *_idolaters_*, for then you would have to go out of the world.
* `1Co 6:9` Do you not know that the unrighteous shall not inherit the kingdom of God? Do not be deceived. Neither fornicators, *_idolaters_*, adulterers, effeminate, abusers of themselves with mankind,
* `1Co 10:7` Neither be *_idolaters_* as some of them were, as it is written, "The people sat down to eat and drink and rose up to play."
* `Rev 21:8` But the fearful, unbelieving, the abominable, murderers, lewd men, sorcerers, *_idolaters_*, and all liars shall have their part in the lake which burns with fire and brimstone. This is the second death."
* `Rev 22:15` For outside are dogs, sorcerers, lewd men, murderers, *_idolaters_*, and whoever loves and makes a lie.

_5 verses containing IDOLATERS_

== IDOLATRIES

* `2Ch 21:13` But have walked in the way of the kings of Israel and have made Judah and the inhabitants of Jerusalem to commit idolatry, like the *_idolatries_* of the house of Ahab, and also have slain your brothers of your father's house, who were better than yourself,
* `1Pe 4:3` For the past time is sufficient to have wrought the desire of the Gentiles, having walked in lasciviousness, lusts, excess of wine, revelings, banquetings, and abominable *_idolatries_*,

_2 verses containing IDOLATRIES_

== IDOLATROUS

* `2Ki 23:5` And he put down the *_idolatrous_* priests whom the kings of Judah had ordained to burn incense in the high places in the cities of Judah and in the places around Jerusalem, those who burned incense to Baal, to the sun, to the moon, to the planets, and to all the host of heaven.

_1 verse containing IDOLATROUS_

== IDOLATRY

* `Lev 17:7` And they shall no longer offer their sacrifices to idols, with which they have committed *_idolatry_*. This shall be a statute forever to them throughout their generations."'
* `Deu 31:16` And the LORD said to Moses, "Behold, you shall sleep with your fathers, and this people will rise up and commit *_idolatry_* with the gods of the strangers of the land where they go to be among them, and will forsake me and break my covenant which I have made with them.
* `1Sa 15:23` For rebellion is as the sin of witchcraft and stubbornness is as iniquity and *_idolatry_*. Because you have rejected the word of the LORD, he has also rejected you from being king."
* `2Ch 21:13` But have walked in the way of the kings of Israel and have made Judah and the inhabitants of Jerusalem to commit *_idolatry_*, like the idolatries of the house of Ahab, and also have slain your brothers of your father's house, who were better than yourself,
* `Act 17:16` Now, while Paul waited for them at Athens, his spirit was stirred in him when he saw the city wholly given to *_idolatry_*.
* `1Co 10:14` Therefore, my dearly beloved, flee from *_idolatry_*.
* `Gal 5:20` *_Idolatry_*, witchcraft, hatred, variance, jealousy, wrath, strife, dissensions, heresies,
* `Col 3:5` Mortify therefore your members which are upon the earth: lewdness, uncleanness, inordinate affection, evil concupiscence, and covetousness, which is *_idolatry_*.

_8 verses containing IDOLATRY_

== IDOLS

* `Lev 17:7` And they shall no longer offer their sacrifices to *_idols_*, with which they have committed idolatry. This shall be a statute forever to them throughout their generations."'
* `Lev 19:4` Do not turn to *_idols_*, nor make for yourselves molten gods. I am the LORD your God.
* `Lev 26:1` "'You shall make for yourselves no *_idols_* nor engraved image, neither rear up for yourselves a standing image, neither shall you set up any image of stone in your land to bow down to it. For I am the LORD your God.
* `Lev 26:30` And I will destroy your high places, cut down your images, and cast your carcasses upon the carcasses of your *_idols_*, and my soul shall abhor you.
* `Deu 29:17` And you have seen their abominations and their *_idols_*, wood and stone, silver and gold, which were among them),
* `1Sa 31:9` And they cut off his head, stripped off his armor, and sent into the land of the Philistines all around to publish it in the house of their *_idols_* and among the people.
* `1Ki 15:12` And he banished the temple prostitutes from the land and removed all the *_idols_* that his fathers had made.
* `1Ki 21:26` And he did very abominably in following *_idols_*, according to all things that the Amorites did, whom the LORD cast out before the children of Israel.
* `2Ki 17:12` For they served *_idols_*, of which the LORD had said to them, "You shall not do this thing."
* `2Ki 21:11` "Because Manasseh king of Judah has done these abominations and has done wickedly above all that the Amorites did, who were before him, and has made Judah also to sin with his *_idols_*,
* `2Ki 21:21` And he walked in all the way that his father walked in and served the *_idols_* that his father served and worshiped them.
* `2Ki 23:24` Moreover, the workers with familiar spirits, the wizards, the images, the *_idols_*, and all the abominations that were seen in the land of Judah and in Jerusalem, Josiah put away so that he might perform the words of the law which were written in the book that Hilkiah the priest found in the house of the LORD.
* `1Ch 10:9` And when they had stripped him, they took his head and his armor and sent into the land of the Philistines around to carry tidings to their *_idols_* and to the people.
* `1Ch 16:26` For all the gods of the people are *_idols_*, but the LORD made the heavens.
* `2Ch 15:8` And when Asa heard these words and the prophecy of Oded the prophet, he took courage and put away the abominable *_idols_* out of all the land of Judah and Benjamin and out of the cities which he had taken from mount Ephraim, and renewed the altar of the LORD that was before the porch of the LORD.
* `2Ch 24:18` And they left the house of the LORD God of their fathers and served groves and *_idols_*. And wrath came upon Judah and Jerusalem for their trespass.
* `2Ch 34:7` And when he had broken down the altars and the groves, beaten the engraved images into powder, and cut down all the *_idols_* throughout all the land of Israel, he returned to Jerusalem.
* `Psa 96:5` For all the gods of the nations are *_idols_*, but the LORD made the heavens.
* `Psa 97:7` Confounded are all those who serve engraved images, who boast themselves of *_idols_*. Worship him, all you gods.
* `Psa 106:36` And they served their *_idols_*, which were a snare to them.
* `Psa 106:38` And shed innocent blood, even the blood of their sons and of their daughters, whom they sacrificed to the *_idols_* of Canaan. And the land was polluted with blood.
* `Psa 115:4` Their *_idols_* are silver and gold, the work of men's hands.
* `Psa 135:15` The *_idols_* of the heathen are silver and gold, the work of men's hands.
* `Isa 2:8` Their land is also full of *_idols_*. They worship the work of their own hands, that which their own fingers have made.
* `Isa 2:18` And he will utterly abolish the *_idols_*.
* `Isa 2:20` In that day a man shall cast his *_idols_* of silver and his *_idols_* of gold, which they made each one for himself to worship, to the moles and to the bats.
* `Isa 10:10` As my hand has found the kingdoms of the *_idols_*, and whose engraved images excelled those of Jerusalem and of Samaria,
* `Isa 10:11` Shall I not, as I have done to Samaria and her *_idols_*, do so to Jerusalem and her *_idols_*?"
* `Isa 19:1` [The burden of Egypt.] "Behold, the LORD rides upon a swift cloud and will come into Egypt. And the *_idols_* of Egypt shall be moved at his presence, and the heart of Egypt shall melt in the midst of it.
* `Isa 19:3` And the spirit of Egypt shall fail in the midst of her, and I will destroy her counsel. And they shall seek the *_idols_*, the charmers, those who have familiar spirits, and the wizards.
* `Isa 31:7` For in that day every man shall cast away his *_idols_* of silver and his *_idols_* of gold, which your own hands have made for you for a sin.
* `Isa 45:16` They shall be ashamed and also confounded, all of them. They shall go in disgrace together who are makers of *_idols_*.
* `Isa 46:1` Bel bows down and Nebo stoops. Their *_idols_* were upon the beasts and upon the livestock. Your loads were heavy. They were a burden to the weary beast.
* `Isa 57:5` Inflaming yourselves with *_idols_* under every green tree, slaying the children in the valleys under the cliffs of the rocks?
* `Jer 50:2` "Declare among the nations and publish, and set up a standard. Publish, and do not conceal. Say, 'Babylon is taken. Bel is confounded. Merodach is broken in pieces. Her *_idols_* are confounded. Her images are broken in pieces.'
* `Jer 50:38` A drought is upon her waters, and they shall be dried up. For it is the land of engraved images, and they are mad upon their *_idols_*.
* `Ezk 6:4` And your altars shall be desolate, and your images shall be broken. And I will cast down your slain men before your *_idols_*.
* `Ezk 6:5` And I will lay the dead carcasses of the children of Israel before their *_idols_*. And I will scatter your bones around your altars.
* `Ezk 6:6` In all your dwelling-places the cities shall be laid waste and the high places shall be desolate, so that your altars may be laid waste and made desolate, your *_idols_* may be broken and cease, your images may be cut down, and your works may be abolished.
* `Ezk 6:9` And those of you who escape shall remember me among the nations where they shall be carried captives, because I am broken with their apostate heart, which has departed from me, and with their eyes which go astray after their *_idols_*. And they shall loathe themselves for the evils which they have committed in all their abominations.
* `Ezk 6:13` Then you shall know that I am the LORD, when their slain men are among their *_idols_* all around their altars, upon every high hill, on all the tops of the mountains, under every green tree, and under every thick oak, the place where they offered sweet savor to all their *_idols_*.
* `Ezk 8:10` So I went in and saw, and behold, every form of creeping animals and abominable beasts and all the *_idols_* of the house of Israel were portrayed around upon the wall.
* `Ezk 14:3` "Son of man, these men have set up their *_idols_* in their heart and put the stumbling-block of their iniquity before their face. Should I be inquired of at all by them?
* `Ezk 14:4` Therefore, speak to them, and say to them, 'Thus says the Lord GOD: "Every man of the house of Israel who sets up his *_idols_* in his heart and puts the stumbling-block of his iniquity before his face and comes to the prophet, I, the LORD, will answer him who comes according to the multitude of his *_idols_*,
* `Ezk 14:5` So that I may take the house of Israel in their own heart, because they are all estranged from me through their *_idols_*."'
* `Ezk 14:6` "Therefore, say to the house of Israel, 'Thus says the Lord GOD: "Repent, turn yourselves from your *_idols_*, and turn away your faces from all your abominations.
* `Ezk 14:7` For when anyone from the house of Israel or from the strangers who sojourn in Israel who separates himself from me, sets up his *_idols_* in his heart, puts the stumbling-block of his iniquity before his face, and comes to a prophet to inquire of him concerning me, I, the LORD, will answer him by myself.
* `Ezk 16:36` Thus says the Lord GOD: "Because your filthiness was poured out and your nakedness exposed through your carnal connection with your lovers, with all the *_idols_* of your abominations, and by the blood of your children, which you gave to them,
* `Ezk 18:6` Has not eaten upon the mountains, neither has lifted up his eyes to the *_idols_* of the house of Israel, neither has defiled his neighbor's wife, neither has come near to a polluted woman,
* `Ezk 18:12` Has oppressed the poor and needy, has stripped by violence, has not restored the pledge, has lifted up his eyes to the *_idols_*, has committed abomination,
* `Ezk 18:15` Who has not eaten upon the mountains, neither has lifted up his eyes to the *_idols_* of the house of Israel, has not defiled his neighbor's wife,
* `Ezk 20:7` I said to them, 'Every one of you cast away the abominations of his eyes, and do not defile yourselves with the *_idols_* of Egypt. I am the LORD your God.'
* `Ezk 20:8` But they rebelled against me and would not listen to me. They did not each cast away the abominations of their eyes, neither did they forsake the *_idols_* of Egypt. Then I said I would pour out my fury upon them to accomplish my anger against them in the midst of the land of Egypt.
* `Ezk 20:16` Because they despised my judgments and did not walk in my statutes, but profaned my sabbaths, for their heart went after their *_idols_*.
* `Ezk 20:18` "But I said to their children in the wilderness, 'Do not walk in the statutes of your fathers, neither observe their judgments, nor defile yourselves with their *_idols_*.
* `Ezk 20:24` For they had not executed my judgments, but had despised my statutes and had profaned my sabbaths, and their eyes were after their fathers' *_idols_*.
* `Ezk 20:31` For when you offer your gifts, when you make your sons to pass through the fire, you pollute yourselves with all your *_idols_*, even to this day. And shall I be inquired of by you, O house of Israel? As I live," says the Lord GOD, "I will not be inquired of by you.
* `Ezk 20:39` "As for you, O house of Israel," thus says the Lord GOD: "Go, each of you serve his *_idols_*, and hereafter also, if you will not listen to me. But profane my holy name no longer with your gifts and with your *_idols_*.
* `Ezk 22:3` Then say, 'Thus says the Lord GOD: "The city sheds blood in the midst of it so that her time may come, and makes *_idols_* against herself to defile herself.
* `Ezk 22:4` You have become guilty in your blood that you have shed, have defiled yourself by your *_idols_* which you have made, have caused your days to draw near, and have come even to your years; therefore, I have made you a reproach to the heathen and a mocking to all countries.
* `Ezk 23:7` Thus she committed her lewd deeds with them, with all those who were the chosen men of Assyria, and with all on whom she doted. With all their *_idols_* she defiled herself.
* `Ezk 23:30` I will do these things to you because you have gone astray after the heathen and because you are polluted with their *_idols_*.
* `Ezk 23:37` For they have committed adultery, and blood is on their hands. They have committed adultery with their *_idols_*. They have also caused their sons, whom they bore to me, to pass through the fire to them to be devoured.
* `Ezk 23:39` For when they had slain their children to their *_idols_*, then they came the same day into my sanctuary to profane it. Behold, thus they have done in the midst of my house.
* `Ezk 23:49` And they shall recompense your lewdness upon you, and you shall bear the sins of your *_idols_*. And you shall know that I am the Lord GOD.'"
* `Ezk 30:13` Thus says the Lord GOD: "I will also destroy the *_idols_*, and I will cause their images to cease out of Noph. And there shall no longer be a prince of the land of Egypt. And I will put a fear in the land of Egypt.
* `Ezk 33:25` Therefore, say to them, 'Thus says the Lord GOD: "You eat with the blood, lift up your eyes toward your *_idols_*, and shed blood. And shall you possess the land?
* `Ezk 36:18` Therefore, I poured my fury upon them for the blood that they had shed upon the land and for their *_idols_* with which they had polluted it.
* `Ezk 36:25` Then I will sprinkle clean water upon you, and you shall be clean. From all your filthiness and from all your *_idols_*, I will cleanse you.
* `Ezk 37:23` Neither shall they defile themselves anymore with their *_idols_*, nor with their detestable things, nor with any of their transgressions. But I will save them out of all their dwelling-places in which they have sinned and cleanse them. So they shall be my people, and I will be their God.
* `Ezk 44:10` And the Levites who have gone away far from me when Israel went astray, and who went astray from me after their *_idols_*, they shall even bear their iniquity.
* `Ezk 44:12` Because they ministered to them before their *_idols_* and caused the house of Israel to fall into iniquity, therefore I have lifted up my hand against them," says the Lord GOD, "and they shall bear their iniquity.
* `Hos 4:17` Ephraim is joined to *_idols_*. Leave him alone.
* `Hos 8:4` They have set up kings, but not by me. They have made princes, and I did not know it. Of their silver and their gold they have made for themselves *_idols_*, so that they may be cut off.
* `Hos 13:2` And now they sin more and more, and have made for themselves molten images of their silver and *_idols_* according to their own understanding, all of it the work of craftsmen. They say of them, 'Let the men who sacrifice kiss the calves.'
* `Hos 14:8` Ephraim shall say, 'What have I to do anymore with *_idols_*?' I have heard him and observed him. I am like a green fir-tree. Your fruit is found from me."
* `Mic 1:7` And all her engraved images shall be beaten to pieces, all her wages shall be burned with the fire, and all her *_idols_* I will lay desolate, for she gathered it from the payment of a harlot, and they shall return to the payment of a harlot."
* `Hab 2:18` What profit is the engraved image when its maker has engraved it—the molten image and a teacher of lies—that the maker trusts in what he has formed, making mute *_idols_*?
* `Zch 10:2` For the *_idols_* have spoken vanity, and the diviners have seen a lie. They have told false dreams. They comfort in vain. Therefore, they went their way as a flock. They were troubled because there was no shepherd.
* `Zch 13:2` "And it shall come to pass in that day," says the LORD of hosts, "that I will cut off the names of the *_idols_* out of the land and they shall no longer be remembered. And I will also remove the prophets and the unclean spirit from the land.
* `Act 15:20` But that we write to them that they abstain from pollutions of *_idols_*, from lewdness, from things strangled, and from blood.
* `Act 15:29` That you abstain from things offered to *_idols_*, from blood, from things strangled, and from lewdness—which if you keep yourselves from you will do well. Farewell."
* `Act 21:25` As concerning the Gentiles who believe, we have written and concluded that they observe no such thing, except only that they keep themselves from things offered to *_idols_*, from blood, from things strangled, and from lewdness."
* `Rom 2:22` You who say a man should not commit adultery, do you commit adultery? You who abhor *_idols_*, do you commit sacrilege?
* `1Co 8:1` Now as concerning things offered to *_idols_*, we know that we all have knowledge. Knowledge puffs up, but charity edifies.
* `1Co 8:4` Therefore, as concerning the eating of those things that are offered in sacrifice to *_idols_*, we know that an idol is nothing in the world and that there is no other God but one.
* `1Co 8:10` For if any man sees you, who have knowledge, eating in the idol's temple, will the conscience of him who is weak not be emboldened to eat those things which are offered to *_idols_*?
* `1Co 10:19` What then do I say? That the idol is anything, or that which is offered in sacrifice to *_idols_* is anything?
* `1Co 10:28` But if any man says to you, "This is offered in sacrifice to *_idols_*," do not eat for his sake who showed it and for the sake of conscience. For "the earth is the Lord's, and its fullness."
* `1Co 12:2` You know that you were Gentiles, carried away to these mute *_idols_*, even as you were led.
* `2Co 6:16` And what agreement has the temple of God with *_idols_*? For you are the temple of the living God, as God has said, "'I will dwell in them' and walk in them. 'And I will be their God, and they shall be my people.'"
* `1Th 1:9` For they themselves report concerning us what manner of entering in we had to you and how you turned to God from *_idols_* to serve the living and true God,
* `1Jn 5:21` Little children, keep yourselves from *_idols_*. Amen.
* `Rev 2:14` But I have a few things against you, because you have there those who hold the doctrine of Balaam, who taught Balak to cast a stumbling-block before the children of Israel, to eat things sacrificed to *_idols_*, and to commit lewdness.
* `Rev 2:20` But, I have a few things against you, because you tolerate that woman Jezebel, who calls herself a prophetess. She teaches and seduces my servants to commit lewdness and to eat things sacrificed to *_idols_*.
* `Rev 9:20` And the rest of the men who were not killed by these plagues still did not repent of the works of their hands, that they should not worship demons and *_idols_* of gold, silver, brass, stone, and of wood, which neither can see, hear, nor walk.

_96 verses containing IDOLS_

== IDUMEA

* `Mrk 3:8` From Jerusalem, from *_Idumea_*, from beyond the Jordan, and those around Tyre and Sidon. A great multitude came to him when they had heard what great things he did.

_1 verse containing IDUMEA_

== IGAL

* `Num 13:7` Of the tribe of Issachar, *_Igal_* the son of Joseph;
* `2Sa 23:36` *_Igal_* the son of Nathan of Zobah, Bani the Gadite,

_2 verses containing IGAL_

== IGDALIAH

* `Jer 35:4` And I brought them into the house of the LORD, into the chamber of the sons of Hanan, the son of *_Igdaliah_*, a man of God, who was by the chamber of the princes, which was above the chamber of Maaseiah the son of Shallum, the keeper of the door.

_1 verse containing IGDALIAH_

== IGEAL

* `1Ch 3:22` And the son of Shechaniah: Shemaiah. And the sons of Shemaiah: Hattush, *_Igeal_*, Bariah, Neariah, and Shaphat, six.

_1 verse containing IGEAL_

== IGNOMINY

* `Pro 18:3` When the wicked comes, then contempt also comes, and with *_ignominy_* comes reproach.

_1 verse containing IGNOMINY_

== IGNORANCE

* `Lev 4:2` "Speak to the children of Israel, saying, 'If a soul sins through *_ignorance_* against any of the commandments of the LORD concerning things which ought not to be done and violates any of them,
* `Lev 4:13` 'And if the whole congregation of Israel sins through *_ignorance_*, and the thing is hid from the eyes of the assembly, and they have done something against any of the commandments of the LORD concerning things which should not be done, and are guilty,
* `Lev 4:22` 'When a ruler has sinned and done something through *_ignorance_* against any of the commandments of the LORD his God concerning things which should not be done, and is guilty,
* `Lev 4:27` 'And if anyone of the common people sins through *_ignorance_*, while he does something against any of the commandments of the LORD concerning things which ought not to be done, and is guilty,
* `Lev 5:15` "If a soul commits a trespass and sins through *_ignorance_* in the holy things of the LORD, then he shall bring for his trespass to the LORD a ram without blemish out of the flocks, with your estimation by shekels of silver after the shekel of the sanctuary, for a trespass-offering.
* `Lev 5:18` And he shall bring a ram without blemish out of the flock, with your estimation, for a trespass-offering to the priest. And the priest shall make an atonement for him concerning his *_ignorance_* wherein he erred and did not know it, and he shall be forgiven.
* `Num 15:24` Then it shall be, if anything is committed by *_ignorance_* without the knowledge of the congregation, that all the congregation shall offer one young bull for a burnt-offering for a sweet savor to the LORD, with his food-offering and his drink-offering, according to the manner, and one kid of the goats for a sin-offering.
* `Num 15:25` And the priest shall make an atonement for all the congregation of the children of Israel, and they shall be forgiven, for it is *_ignorance_*. And they shall bring their offering, a sacrifice made by fire to the LORD, and their sin-offering before the LORD for their *_ignorance_*.
* `Num 15:26` And all the congregation of the children of Israel shall be forgiven, and also the stranger who sojourns among them, seeing all the people were in *_ignorance_*.
* `Num 15:27` 'And if any soul sins through *_ignorance_*, then he shall bring a female goat of the first year for a sin-offering.
* `Num 15:28` And the priest shall make an atonement for the soul who sins ignorantly when he sins by *_ignorance_* before the LORD, to make an atonement for him. And he shall be forgiven.
* `Num 15:29` You shall have one law for him who sins through *_ignorance_*, both for him who is born among the children of Israel and for the stranger who sojourns among them.
* `Act 3:17` "And now, brothers, I know that through *_ignorance_* you did it, as your rulers also did.
* `Act 17:30` And the times of this *_ignorance_* God winked at, but now commands all men everywhere to repent,
* `Eph 4:18` Having their understanding darkened, being alienated from the life of God through the *_ignorance_* that is in them because of the blindness of their heart,
* `1Pe 1:14` As obedient children, not fashioning yourselves according to the former lusts in your *_ignorance_*.
* `1Pe 2:15` For this is the will of God: that with well-doing you may put to silence the *_ignorance_* of foolish men,

_17 verses containing IGNORANCE_

== IGNORANT

* `Psa 73:22` So foolish was I, and *_ignorant_*. I was like a beast before you.
* `Isa 56:10` His watchmen are blind. They are all *_ignorant_*. They are all mute dogs that cannot bark. They are sleeping, lying down, loving to slumber.
* `Isa 63:16` Doubtless you are our Father, though Abraham is *_ignorant_* of us, and Israel does not acknowledge us. You, O LORD, are our Father, our Redeemer. Your name is from everlasting.
* `Act 4:13` Now when they saw the boldness of Peter and John and perceived that they were unlearned and *_ignorant_* men, they marveled and they took knowledge of them, that they had been with Jesus.
* `Rom 1:13` Now I would not have you *_ignorant_*, brothers, that I have often purposed to come to you (but have been until now hindered) so that I might have some fruit among you also, even as among other Gentiles.
* `Rom 10:3` For they, being *_ignorant_* of God's righteousness and seeking to establish their own righteousness, have not submitted themselves to the righteousness of God.
* `Rom 11:25` For I do not wish, brothers, that you should be *_ignorant_* of this mystery (lest you should be wise in your own conceits), that blindness in part has happened to Israel until the fullness of the Gentiles has come in.
* `1Co 10:1` Moreover, brothers, I do not wish that you should be *_ignorant_*, that all our fathers were under the cloud, and all passed through the sea,
* `1Co 12:1` Now concerning spiritual gifts, brothers, I wish to not have you *_ignorant_*.
* `1Co 14:38` But if any man is *_ignorant_*, let him be *_ignorant_*.
* `2Co 1:8` For we do not wish, brothers, to have you *_ignorant_* of our trouble which came to us in Asia, that we were pressed out of measure, beyond our strength, so that we despaired even of life.
* `2Co 2:11` Lest Satan should get an advantage of us, for we are not *_ignorant_* of his devices.
* `1Th 4:13` But I do not wish to have you to be *_ignorant_*, brothers, concerning those who are asleep, so that you do not sorrow, even as others who have no hope.
* `Heb 5:2` He can have compassion on the *_ignorant_* and on those who are out of the way, for he himself also is compassed with infirmity.
* `2Pe 3:5` For this they willingly are *_ignorant_* of: that by the word of God the heavens were of old and the earth formed out of the water and through the water,
* `2Pe 3:8` But, beloved, do not be *_ignorant_* of this one thing: one day with the Lord is as a thousand years, and a thousand years as one day.

_16 verses containing IGNORANT_

== IGNORANTLY

* `Num 15:28` And the priest shall make an atonement for the soul who sins *_ignorantly_* when he sins by ignorance before the LORD, to make an atonement for him. And he shall be forgiven.
* `Deu 19:4` "And this is the case of the slayer who flees there so that he may live. Whoever kills his neighbor *_ignorantly_*, whom he did not hate in time past,
* `Jsh 20:3` So that the slayer who kills any person unintentionally and *_ignorantly_* may flee there. And they shall be your refuge from the avenger of blood.
* `Jsh 20:5` And if the avenger of blood pursues him, then they shall not deliver the slayer into his hand because he smote his neighbor *_ignorantly_* and had not hated him before.
* `Act 17:23` For as I passed by and beheld your devotions, I found an altar with this inscription: 'TO THE UNKNOWN GOD.' Therefore, whom you *_ignorantly_* worship, I declare him to you.
* `1Ti 1:13` I was before a blasphemer, a persecutor, and injurious, but I obtained mercy because I did it *_ignorantly_* in unbelief.

_6 verses containing IGNORANTLY_

== IIM

* `Num 33:45` And they departed from *_Iim_* and encamped in Dibon-gad.
* `Jsh 15:29` Baalah, *_Iim_*, Azem,

_2 verses containing IIM_

== IJE-ABARIM

* `Num 21:11` And they journeyed from Oboth and pitched at *_Ije-abarim_* in the wilderness which is before Moab, toward the sunrise.
* `Num 33:44` And they departed from Oboth and encamped in *_Ije-abarim_*, in the border of Moab.

_2 verses containing IJE-ABARIM_

== IJON

* `1Ki 15:20` So Ben-hadad listened to king Asa and sent the captains of the armies which he had against the cities of Israel and smote *_Ijon_*, Dan, Abel-beth-maachah, and all Cinneroth, with all the land of Naphtali.
* `2Ki 15:29` In the days of Pekah king of Israel, Tiglath-pileser king of Assyria, came and took *_Ijon_*, Abel-beth-maachah, Janoah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naphtali, and carried them captive to Assyria.
* `2Ch 16:4` And Ben-hadad listened to king Asa and sent the captains of his armies against the cities of Israel. And they smote *_Ijon_*, Dan, Abelmaim, and all the store cities of Naphtali.

_3 verses containing IJON_

== IKKESH

* `2Sa 23:26` Helez the Paltite, Ira the son of *_Ikkesh_* the Tekoite,
* `1Ch 11:28` Ira the son of *_Ikkesh_* the Tekoite, Abiezer the Antothite,
* `1Ch 27:9` The sixth captain for the sixth month was Ira the son of *_Ikkesh_* the Tekoite. And in his course were twenty-four thousand.

_3 verses containing IKKESH_

== ILAI

* `1Ch 11:29` Sibbecai the Hushathite, *_Ilai_* the Ahohite,

_1 verse containing ILAI_

== ILL

* `Gen 41:3` And behold, seven other cows came up after them out of the river, *_ill_*-favored and lean-fleshed, and stood by the other cows upon the bank of the river.
* `Gen 41:4` And the *_ill_*-favored and lean-fleshed cows ate up the seven well-favored and fat cows. So Pharaoh awoke.
* `Gen 41:19` And behold, seven other cows came out after them, poor, very *_ill_*-favored, and lean-fleshed, such that I never saw worse in all the land of Egypt.
* `Gen 41:20` And the lean and the *_ill_*-favored cows ate up the first seven fat cows.
* `Gen 41:21` And when they had eaten them up, it could not be known that they had eaten them, but they were still *_ill_*-favored, as at the beginning. So I awoke.
* `Gen 41:27` And the seven thin and *_ill_*-favored cows that came up after them are seven years, and the seven empty heads blasted with the east wind will be seven years of famine.
* `Gen 43:6` And Israel said, "Why did you deal so *_ill_* with me, as to tell the man whether you had another brother?"
* `Exo 5:22` And Moses returned to the LORD and said, "Lord, why have you so *_ill_* treated this people? Why is it that you have sent me?
* `Deu 15:21` And if there is any blemish in it, as if it is lame, blind, or has any *_ill_* blemish, you shall not sacrifice it to the LORD your God.
* `Deu 26:6` And the Egyptians *_ill_*-treated us and afflicted us and laid upon us hard bondage.
* `Job 20:26` All darkness shall be hid in his secret places. A fire not blown shall consume him. It shall go *_ill_* with him who is left in his tabernacle.
* `Psa 106:32` They also angered him at the waters of strife so that it went *_ill_* with Moses for their sakes,
* `Isa 3:11` Woe to the wicked! It shall be *_ill_* with him, for the reward of his hands shall be given to him.
* `Isa 34:3` Their slain shall also be cast out, and their *_ill_* smell shall come up from their carcasses. The mountains shall be melted with their blood.
* `Jer 40:4` And now, behold, I release you this day from the chains which were upon your hand. If it seems good to you to come with me into Babylon, come, and I will look well to you. But if it seems *_ill_* to you to come with me into Babylon, forbear. Behold, all the land is before you. Where it seems good and right for you to go, go there."
* `Joe 2:20` But I will remove far from you the northern army and drive him into a land barren and desolate with his face toward the east sea and his back parts toward the utmost sea, and his odious scent shall come up and his *_ill_* savor shall come up, because he has worked proudly."
* `Amo 4:10` "I have sent among you the pestilence after the manner of Egypt. I have slain your young men with the sword and have taken away your horses. I have made the *_ill_* savor of your camps to come up to your nostrils. Yet you have not returned to me," says the LORD.
* `Mic 3:4` Then you shall cry to the LORD, but he will not hear you. He will even hide his face from you at that time, as you have been *_ill_* behaved in your doings."
* `Act 7:6` And God spoke in this way, that 'his offspring should sojourn in a foreign land, and that they should bring them into bondage and treat them *_ill_* four hundred years.'
* `Act 7:19` The same dealt subtly with our kindred and *_ill_*-treated our fathers, making them cast out their young children so that they would not live.
* `Rom 13:10` Love works no *_ill_* to one's neighbor; therefore, love is the fulfilling of the law.

_21 verses containing ILL_

== ILL-FAVORED

* `Gen 41:3` And behold, seven other cows came up after them out of the river, *_ill-favored_* and lean-fleshed, and stood by the other cows upon the bank of the river.
* `Gen 41:4` And the *_ill-favored_* and lean-fleshed cows ate up the seven well-favored and fat cows. So Pharaoh awoke.
* `Gen 41:19` And behold, seven other cows came out after them, poor, very *_ill-favored_*, and lean-fleshed, such that I never saw worse in all the land of Egypt.
* `Gen 41:20` And the lean and the *_ill-favored_* cows ate up the first seven fat cows.
* `Gen 41:21` And when they had eaten them up, it could not be known that they had eaten them, but they were still *_ill-favored_*, as at the beginning. So I awoke.
* `Gen 41:27` And the seven thin and *_ill-favored_* cows that came up after them are seven years, and the seven empty heads blasted with the east wind will be seven years of famine.

_6 verses containing ILL-FAVORED_

== ILL-TREATED

* `Deu 26:6` And the Egyptians *_ill-treated_* us and afflicted us and laid upon us hard bondage.
* `Act 7:19` The same dealt subtly with our kindred and *_ill-treated_* our fathers, making them cast out their young children so that they would not live.

_2 verses containing ILL-TREATED_

== ILLEGITIMATE

* `Deu 23:2` An *_illegitimate_* son shall not enter into the congregation of the LORD. Even to his tenth generation he shall not enter into the congregation of the LORD.
* `Heb 12:8` But if you are without chastisement, of which all are partakers, then you are *_illegitimate_* sons and not sons.

_2 verses containing ILLEGITIMATE_

== ILLUMINATED

* `Heb 10:32` But call to remembrance the former days, in which, after you were *_illuminated_*, you endured a great fight of afflictions,

_1 verse containing ILLUMINATED_

== ILLYRICUM

* `Rom 15:19` Through mighty signs and wonders, by the power of the Spirit of God, so that from Jerusalem and around to *_Illyricum_* I have fully preached the gospel of Christ.

_1 verse containing ILLYRICUM_

== IMAGE

* `Gen 1:26` And God said, "Let us make man in our *_image_*, after our likeness, and let them have dominion over the fish of the sea, over the birds of the air, over the livestock, over all the earth, and over every creeping animal that creeps upon the earth."
* `Gen 1:27` So God created man in his own *_image_*. In the *_image_* of God he created him. Male and female he created them.
* `Gen 5:3` And Adam lived one hundred and thirty years and begot a son in his own likeness, after his *_image_*, and called his name Seth.
* `Gen 9:6` "Whoever sheds man's blood, by man his blood shall be shed, for in the *_image_* of God he made man.
* `Exo 20:4` "You shall not make for yourself any engraved *_image_* or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth.
* `Lev 26:1` "'You shall make for yourselves no idols nor engraved *_image_*, neither rear up for yourselves a standing *_image_*, neither shall you set up any *_image_* of stone in your land to bow down to it. For I am the LORD your God.
* `Deu 4:16` Lest you corrupt yourselves and make for yourselves an engraved *_image_*, the similitude of any figure, the likeness of male or female,
* `Deu 4:23` Take heed to yourselves, lest you forget the covenant of the LORD your God, which he made with you, and make yourselves an engraved *_image_* or the likeness of anything which the LORD your God has forbidden you.
* `Deu 4:25` "When you beget children and children's children, and you have remained long in the land, and corrupt yourselves and make an engraved *_image_* or the likeness of anything, and shall do evil in the sight of the LORD your God to provoke him to anger,
* `Deu 5:8` 'You shall not make for yourself any engraved *_image_* or any likeness of anything that is in heaven above, that is on the earth beneath, or that is in the waters beneath the earth.
* `Deu 9:12` And the LORD said to me, 'Arise, go down quickly from here, for your people which you have brought forth out of Egypt have corrupted themselves. They have quickly turned aside from the way which I commanded them. They have made themselves a molten *_image_*.'
* `Deu 16:22` Neither shall you set yourself up any *_image_*, which the LORD your God hates."
* `Deu 27:15` 'Cursed is the man who makes any engraved or molten *_image_*, an abomination to the LORD, the work of the hands of the craftsman, and puts it in a secret place.' And all the people shall answer and say, 'Amen.'
* `Jdg 17:3` And when he had restored the eleven hundred shekels of silver to his mother, his mother said, "I had wholly dedicated the silver to the LORD from my hand for my son to make an engraved *_image_* and a molten *_image_*. Now therefore, I will restore it to you."
* `Jdg 17:4` So he restored the money to his mother, and his mother took two hundred shekels of silver and gave them to the founder, who made from it an engraved *_image_* and a molten *_image_*. And they were in the house of Micah.
* `Jdg 18:14` Then the five men who went to explore the country of Laish answered and said to their brothers, "Do you know that there is in these houses an ephod, teraphim, an engraved *_image_*, and a molten *_image_*? Now therefore, consider what you have to do."
* `Jdg 18:17` And the five men who went to explore the land went up, came in there, and took the engraved *_image_*, the ephod, the teraphim, and the molten *_image_*. And the priest stood in the entrance of the gate with the six hundred men who were appointed with weapons of war.
* `Jdg 18:18` And these went into Micah's house and brought the carved *_image_*, the ephod, the teraphim, and the molten *_image_*. Then the priest said to them, "What are you doing?"
* `Jdg 18:20` And the priest's heart was glad and he took the ephod, the teraphim, and the engraved *_image_* and went in the midst of the people.
* `Jdg 18:30` And the children of Dan set up the engraved *_image_*. And Jonathan, the son of Gershom, the son of Moses, he and his sons were priests for the tribe of Dan until the day of the captivity of the land.
* `Jdg 18:31` And they set up for themselves Micah's engraved *_image_* which he made the whole time that the house of God was in Shiloh.
* `1Sa 19:13` And Michal took an *_image_*, laid it in the bed, put a pillow of goat's hair for his bolster, and covered it with a cloth.
* `1Sa 19:16` And when the messengers had come in, behold, there was an *_image_* in the bed with a pillow of goat's hair for his bolster.
* `2Ki 3:2` And he wrought evil in the sight of the LORD, but not like his father and his mother, for he put away the *_image_* of Baal that his father had made.
* `2Ki 10:27` And they broke down the *_image_* of Baal. Then they broke down the house of Baal and made it a latrine-house to this day.
* `2Ki 21:7` And he set an engraved *_image_* of the grove that he had made in the house, of which the LORD said to David and to Solomon his son, "In this house and in Jerusalem, which I have chosen out of all tribes of Israel, I will put my name forever.
* `2Ch 3:10` And in the most holy house he made two cherubim of *_image_* work and overlaid them with gold.
* `2Ch 33:7` And he set a carved *_image_*, the idol which he had made, in the house of God, of which God had said to David and to Solomon his son, "In this house and in Jerusalem, which I have chosen before all the tribes of Israel, I will put my name forever.
* `Job 4:16` It stood still, but I could not discern its form. An *_image_* was before my eyes. There was silence, and I heard a voice, saying,
* `Psa 73:20` As a dream when one awakes, so, O Lord, when you awake, you will despise their *_image_*.
* `Psa 106:19` They made a calf in Horeb and worshiped the molten *_image_*.
* `Isa 40:19` The workman melts an engraved *_image_*, and the goldsmith spreads it over with gold and casts silver chains.
* `Isa 40:20` He who is so impoverished that he has no oblation chooses a tree that will not rot. He seeks for himself a skillful workman to prepare an engraved *_image_* that shall not be moved.
* `Isa 44:9` Those who make an engraved *_image_* are all of them vanity, and their delectable things shall not profit, and they are their own witnesses. They neither see nor know so that they may be ashamed.
* `Isa 44:10` Who has formed a god, or cast an engraved *_image_* that is profitable for nothing?
* `Isa 44:15` Then it shall be for a man to burn, for he will take some of it and warm himself. Indeed he kindles it and bakes bread. He even makes a god and worships it. He makes it an engraved *_image_* and falls down to it.
* `Isa 44:17` And from the rest of it he makes a god, even his engraved *_image_*. He falls down to it, worships it, and prays to it, and says, "Deliver me, for you are my god."
* `Isa 45:20` Assemble yourselves and come. Draw near together, you who have escaped of the nations. They have no knowledge who set up the wood of their engraved *_image_* and pray to a god that cannot save.
* `Isa 48:5` I have even from the beginning declared it to you. Before it came to pass I showed it to you, lest you should say, 'My idol has done them, and my engraved *_image_* and my molten *_image_* has commanded them.'
* `Jer 10:14` Every man is brutish in his knowledge. Every founder is confounded by the engraved *_image_*, for his molten *_image_* is falsehood and there is no breath in them.
* `Jer 51:17` Every man is brutish by his knowledge. Every founder is confounded by the engraved *_image_*, for his molten *_image_* is falsehood, and there is no breath in them.
* `Ezk 8:3` And he put forth the form of a hand and took me by a lock of my head. And the Spirit lifted me up between the earth and the heaven and brought me in the visions of God to Jerusalem, to the door of the inner gate that looks toward the north, where the seat of the *_image_* of jealousy was, which provokes to jealousy.
* `Ezk 8:5` Then he said to me, "Son of man, lift up your eyes now toward the north." So I lifted up my eyes toward the north, and behold, northward at the gate of the altar, in the entry, was this *_image_* of jealousy.
* `Dan 2:31` "You, O king, saw, and behold a great *_image_*. This great *_image_*, whose brightness was excellent, stood before you, and its form was awesome.
* `Dan 2:32` The head of this *_image_* was of fine gold, his chest and his arms of silver, his belly and his thighs of brass,
* `Dan 2:34` You were looking until a stone was cut out without hands, which smote the *_image_* upon his feet that were of iron and clay and broke them to pieces.
* `Dan 2:35` Then the iron, the clay, the brass, the silver, and the gold were broken to pieces together and became like the chaff of the summer threshing-floors, and the wind carried them away so that no place was found for them. And the stone that smote the *_image_* became a great mountain and filled the whole earth.
* `Dan 3:1` Nebuchadnezzar the king made an *_image_* of gold whose height was sixty cubits and its breadth six cubits. He set it up in the plain of Dura, in the province of Babylon.
* `Dan 3:2` Then Nebuchadnezzar the king sent to convene the princes, the governors, the captains, the judges, the treasurers, the counselors, the sheriffs, and all the rulers of the provinces to come to the dedication of the *_image_* which Nebuchadnezzar the king had set up.
* `Dan 3:3` Then the princes, the governors, the captains, the judges, the treasurers, the counselors, the sheriffs, and all the rulers of the provinces were assembled to the dedication of the *_image_* that Nebuchadnezzar the king had set up, and they stood before the *_image_* that Nebuchadnezzar had set up.
* `Dan 3:5` That at the time you hear the sound of the horn, flute, harp, sackbut, psaltery, bagpipe, and all kinds of music, you shall fall down and worship the golden *_image_* that Nebuchadnezzar the king has set up.
* `Dan 3:7` Therefore, at that time, when all the people heard the sound of the horn, flute, harp, sackbut, psaltery, and all kinds of music, all the people, the nations, and the languages fell down and worshiped the golden *_image_* that Nebuchadnezzar the king had set up.
* `Dan 3:10` You, O king, have made a decree, that every man who hears the sound of the horn, flute, harp, sackbut, psaltery, bagpipe, and all kinds of music, shall fall down and worship the golden *_image_*.
* `Dan 3:12` There are some Jews whom you have set over the affairs of the province of Babylon: Shadrach, Meshach, and Abed-nego. These men, O king, have not regarded you. They do not serve your gods, nor worship the golden *_image_* which you have set up."
* `Dan 3:14` Nebuchadnezzar spoke and said to them, "Is it true, O Shadrach, Meshach, and Abed-nego, do you not serve my gods, nor worship the golden *_image_* which I have set up?
* `Dan 3:15` Now if you are ready at the time you hear the sound of the horn, flute, harp, sackbut, psaltery, bagpipe, and all kinds of music, to fall down and worship the *_image_* which I have made, very well. But if you do not worship, you shall be cast the same hour into the midst of a burning fiery furnace. And who is that God who shall deliver you out of my hands?"
* `Dan 3:18` But if not, may it be known to you, O king, that we will not serve your gods, nor worship the golden *_image_* which you have set up."
* `Hos 3:4` For the children of Israel shall abide many days without a king, without a prince, without a sacrifice, without an *_image_*, without an ephod, and without teraphim.
* `Nah 1:14` And the LORD has given a commandment concerning you, that no more of your name be sown. "Out of the house of your gods I will cut off the engraved *_image_* and the molten *_image_*. I will make your grave, for you are vile."
* `Hab 2:18` What profit is the engraved *_image_* when its maker has engraved it—the molten *_image_* and a teacher of lies—that the maker trusts in what he has formed, making mute idols?
* `Mth 22:20` And he says to them, "Whose *_image_* and superscription is this?"
* `Mrk 12:16` And they brought it, and he says to them, "Whose *_image_* and superscription is this?" And they said to him, "Caesar's."
* `Luk 20:24` Show me a denarius. Whose *_image_* and superscription does it have?" They answered and said, "Caesar's."
* `Act 19:35` And when the town-clerk had appeased the people, he said, "Men of Ephesus, what man is there who does not know that the city of the Ephesians is a worshiper of the great goddess Diana and of the *_image_* which fell down from the sky?
* `Rom 1:23` And changed the glory of the incorruptible God into an *_image_* made like corruptible man, birds, four-footed beasts, and creeping animals.
* `Rom 8:29` For whom he foreknew, he also predestined to be conformed to the *_image_* of his Son so that he might be the first-born among many brothers.
* `1Co 11:7` For a man indeed ought not to cover his head because he is the *_image_* and glory of God, but the woman is the glory of the man.
* `1Co 15:49` And as we have borne the *_image_* of the earthy, we shall also bear the *_image_* of the heavenly.
* `2Co 3:18` But we all, with open face beholding as in a mirror the glory of the Lord, are changed into the same *_image_* from glory to glory, even as by the Spirit of the Lord.
* `2Co 4:4` In whom the god of this world has blinded the minds of those who do not believe, lest the light of the glorious gospel of Christ, who is the *_image_* of God, should shine to them.
* `Col 1:15` He is the *_image_* of the invisible God, the first-born of every creature.
* `Col 3:10` And have put on the new man, which is renewed in knowledge after the *_image_* of him who created him,
* `Heb 1:3` He is the brightness of his glory and the express *_image_* of his person, and upholding all things by the word of his power, when he had by himself made purification of our sins, sat down on the right hand of the Majesty on high,
* `Heb 10:1` For the law, having a shadow of good things to come, and not the very *_image_* of the things, can never with those sacrifices, which they offered year by year continually, make perfect those who draw near.
* `Rev 13:14` He deceives those who dwell on the earth by the means of those miracles which he had power to do in the sight of the beast, saying to those who dwell on the earth that they should make an *_image_* to the beast which was wounded by the sword and lived.
* `Rev 13:15` And he had power to give life to the *_image_* of the beast so that the *_image_* of the beast should both speak and cause as many as would not worship the *_image_* of the beast to be killed.
* `Rev 14:9` And the third angel followed them, saying with a loud voice, "If any man worships the beast and his *_image_* and receives his mark on his forehead or on his hand,
* `Rev 14:11` And the smoke of their torment ascends up forever and ever. And they have no rest day or night who worship the beast and his *_image_* and whoever receives the mark of his name.
* `Rev 15:2` And I saw something like a sea of glass mingled with fire. And those who had gained the victory over the beast, over his *_image_*, over his mark, and over the number of his name, stand on the sea of glass, having the harps of God.
* `Rev 16:2` And the first went and poured out his vial upon the earth. And there fell a noisome and grievous sore upon the men who had the mark of the beast and upon those who worshiped his *_image_*.
* `Rev 19:20` And the beast was taken, and with him the false prophet who wrought miracles before him, with which he deceived those who had received the mark of the beast and those who worshiped his *_image_*. These were both cast alive into a lake of fire burning with brimstone.
* `Rev 20:4` And I saw thrones, and they sat upon them, and judgment was given to them. And I saw the souls of those who were beheaded for the testimony of Jesus and for the word of God, and who had not worshiped the beast nor his *_image_*, neither had received his mark upon their foreheads or on their hands. And they lived and reigned with Christ a thousand years.

_82 verses containing IMAGE_

== IMAGERY

* `Ezk 8:12` Then he said to me, "Son of man, have you seen what the elders of the house of Israel do in the dark, each in the chambers of his *_imagery_*? For they say, 'The LORD does not see us. The LORD has forsaken the earth.'"

_1 verse containing IMAGERY_

== IMAGES

* `Gen 31:19` And Laban went to shear his sheep, and Rachel had stolen the *_images_* that were her father's.
* `Gen 31:34` Now Rachel had taken the *_images_* and put them in the camel's saddle and sat upon them. And Laban searched all the tent, but did not find them.
* `Gen 31:35` And she said to her father, "Do not let it displease my lord that I cannot rise up before you, for the custom of women is upon me." And he searched, but did not find the *_images_*.
* `Exo 23:24` You shall not bow down to their gods, nor serve them, nor do after their works, but you shall utterly overthrow them and quite break down their *_images_*.
* `Exo 34:13` But you shall destroy their altars, break their *_images_*, and cut down their groves.
* `Lev 26:30` And I will destroy your high places, cut down your *_images_*, and cast your carcasses upon the carcasses of your idols, and my soul shall abhor you.
* `Num 33:52` You shall drive out all the inhabitants of the land from before you, destroy all their pictures, destroy all their molten *_images_*, and quite demolish all their high places.
* `Deu 7:5` But this is how you shall deal with them: you shall destroy their altars, break down their *_images_*, cut down their groves, and burn their engraved *_images_* with fire.
* `Deu 7:25` The engraved *_images_* of their gods you shall burn with fire. You shall not desire the silver or gold that is on them, nor take it for yourselves, lest you should be snared in it, for it is an abomination to the LORD your God.
* `Deu 12:3` And you shall overthrow their altars, break their pillars, and burn their groves with fire. And you shall hew down the engraved *_images_* of their gods and destroy their names out of that place.
* `1Sa 6:5` Therefore, you shall make *_images_* of your emerods and *_images_* of your mice that mar the land, and you shall give glory to the God of Israel. It may be that he will lighten his hand from off you, from off your gods, and from off your land.
* `1Sa 6:11` And they laid the ark of the LORD upon the cart and the coffer with the mice of gold and the *_images_* of their emerods.
* `2Sa 5:21` And there they left their *_images_*, and David and his men burned them.
* `1Ki 14:9` But you have done evil above all who were before you, for you have gone and made yourself other gods and molten *_images_* to provoke me to anger, and have cast me behind your back,
* `1Ki 14:23` For they also built for themselves high places and *_images_* and groves on every high hill and under every green tree.
* `2Ki 10:26` And they brought forth the *_images_* out of the house of Baal and burned them.
* `2Ki 11:18` And all the people of the land went into the house of Baal and broke it down. His altars and his *_images_* they broke wholly in pieces and slew Mattan the priest of Baal before the altars. And the priest appointed officers over the house of the LORD.
* `2Ki 17:10` And they set up for themselves *_images_* and groves on every high hill and under every green tree.
* `2Ki 17:16` And they left all the commandments of the LORD their God, made for themselves molten *_images_*, even two calves, and made a grove, worshiped all the host of heaven, and served Baal.
* `2Ki 17:41` So these nations feared the LORD, but also served their engraved *_images_*, both their children and their children's children. As their fathers did, so they do to this day.
* `2Ki 18:4` He removed the high places, broke the *_images_*, cut down the groves, and broke in pieces the brazen serpent that Moses had made, for until those days the children of Israel burnt incense to it. And he called it Nehushtan.
* `2Ki 23:14` And he broke the *_images_* in pieces, cut down the groves, and filled their places with the bones of men.
* `2Ki 23:24` Moreover, the workers with familiar spirits, the wizards, the *_images_*, the idols, and all the abominations that were seen in the land of Judah and in Jerusalem, Josiah put away so that he might perform the words of the law which were written in the book that Hilkiah the priest found in the house of the LORD.
* `2Ch 14:3` For he took away the altars of the strange gods and the high places, broke down the *_images_*, cut down the groves,
* `2Ch 14:5` He also took away out of all the cities of Judah the high places and the *_images_*. And the kingdom was quiet before him.
* `2Ch 23:17` Then all the people went to the house of Baal, broke it down, broke his altars and his *_images_* in pieces, and slew Mattan the priest of Baal before the altars.
* `2Ch 28:2` For he walked in the ways of the kings of Israel and also made molten *_images_* for Baalim.
* `2Ch 31:1` Now when all this was finished, all Israel who were present went out to the cities of Judah and broke the *_images_* in pieces, cut down the groves, and threw down the high places and the altars out of all Judah, Benjamin, Ephraim, and Manasseh until they had utterly destroyed them all. Then all the children of Israel each returned to his possession into their own cities.
* `2Ch 33:19` His prayer also, and how God was entreated by him, and all his sin, his trespass, and the places in which he built high places, and set up groves and engraved *_images_*, before he was humbled, behold, they are written among the sayings of the seers.
* `2Ch 33:22` But he did that which was evil in the sight of the LORD, as Manasseh his father did, for Amon sacrificed to all the carved *_images_* which Manasseh his father had made and served them,
* `2Ch 34:3` For in the eighth year of his reign, while he was still young, he began to seek after the God of David his father. And in the twelfth year he began to purge Judah and Jerusalem of the high places, the groves, the carved *_images_*, and the molten *_images_*.
* `2Ch 34:4` And they broke down the altars of Baalim in his presence, and he cut down the *_images_* that were on high above them. And the groves, the carved *_images_*, and the molten *_images_* he broke in pieces and made dust of them and scattered it upon the graves of those who had sacrificed to them.
* `2Ch 34:7` And when he had broken down the altars and the groves, beaten the engraved *_images_* into powder, and cut down all the idols throughout all the land of Israel, he returned to Jerusalem.
* `Psa 78:58` For they provoked him to anger with their high places and moved him to jealousy with their engraved *_images_*.
* `Psa 97:7` Confounded are all those who serve engraved *_images_*, who boast themselves of idols. Worship him, all you gods.
* `Isa 10:10` As my hand has found the kingdoms of the idols, and whose engraved *_images_* excelled those of Jerusalem and of Samaria,
* `Isa 17:8` And he shall not look to the altars, the work of his hands, neither shall he respect that which his fingers have made, either the groves or the *_images_*.
* `Isa 21:9` And behold, here comes a chariot of men with a couple of horsemen." And he answered and said, "Babylon has fallen, has fallen, and all the engraved *_images_* of her gods he has broken to the ground."
* `Isa 27:9` By this therefore, the iniquity of Jacob shall be purged, and this is all the fruit to take away his sin: when he makes all the stones of the altar like chalk-stones that are beaten apart, the groves and *_images_* shall not stand up.
* `Isa 30:22` You shall also defile the covering of your engraved *_images_* of silver and the ornament of your molten *_images_* of gold. You shall cast them away like a polluted cloth. You shall say to it, "Be gone from me."
* `Isa 41:29` Behold, they are all vanity. Their works are nothing. Their molten *_images_* are wind and confusion."
* `Isa 42:8` I am the LORD. That is my name. And I will not give my glory to another, neither my praise to engraved *_images_*.
* `Isa 42:17` They shall be turned back, they shall be greatly ashamed, who trust in engraved *_images_*, who say to the molten *_images_*, "You are our gods."
* `Jer 8:19` Behold the voice of the cry of the daughter of my people because of those who dwell in a distant country: "Is the LORD not in Zion? Is her king not in her?" "Why have they provoked me to anger with their engraved *_images_* and with strange vanities?"
* `Jer 43:13` He shall also break the *_images_* of Beth-shemesh, which is in the land of Egypt, and the houses of the gods of the Egyptians he shall burn with fire."'"
* `Jer 50:2` "Declare among the nations and publish, and set up a standard. Publish, and do not conceal. Say, 'Babylon is taken. Bel is confounded. Merodach is broken in pieces. Her idols are confounded. Her *_images_* are broken in pieces.'
* `Jer 50:38` A drought is upon her waters, and they shall be dried up. For it is the land of engraved *_images_*, and they are mad upon their idols.
* `Jer 51:47` Therefore, behold, the days come that I will do judgment upon the engraved *_images_* of Babylon. And her whole land shall be confounded, and all her slain shall fall in the midst of her.
* `Jer 51:52` "Therefore, behold, the days come," says the LORD, "that I will do judgment upon her engraved *_images_*. And through all her land the wounded shall groan.
* `Ezk 6:4` And your altars shall be desolate, and your *_images_* shall be broken. And I will cast down your slain men before your idols.
* `Ezk 6:6` In all your dwelling-places the cities shall be laid waste and the high places shall be desolate, so that your altars may be laid waste and made desolate, your idols may be broken and cease, your *_images_* may be cut down, and your works may be abolished.
* `Ezk 7:20` 'As for the beauty of his ornament, he set it in majesty, but they made the *_images_* of their abominations and of their detestable things therein; therefore, I have set it far from them.
* `Ezk 16:17` You have also taken your fair jewels of my gold and of my silver, which I had given you, and have made for yourself *_images_* of men and committed lewdness with them.
* `Ezk 21:21` For the king of Babylon stood at the parting of the way, at the head of the two ways, to use divination. He made his arrows bright, he consulted with *_images_*, he looked in the liver.
* `Ezk 23:14` So she increased her prostitutions, for when she saw men portrayed upon the wall, the *_images_* of the Chaldeans portrayed with vermilion,
* `Ezk 30:13` Thus says the Lord GOD: "I will also destroy the idols, and I will cause their *_images_* to cease out of Noph. And there shall no longer be a prince of the land of Egypt. And I will put a fear in the land of Egypt.
* `Hos 10:1` Israel is an empty vine that brings forth fruit to himself. According to the multitude of his fruit he has multiplied the altars. According to the goodness of his land they have made ornate *_images_*.
* `Hos 10:2` Their heart is divided. Now they shall be found faulty. He shall break down their altars. He shall destroy their *_images_*.
* `Hos 11:2` As they called them, so they went from them. They sacrificed to Baalim and burned incense to engraved *_images_*.
* `Hos 13:2` And now they sin more and more, and have made for themselves molten *_images_* of their silver and idols according to their own understanding, all of it the work of craftsmen. They say of them, 'Let the men who sacrifice kiss the calves.'
* `Amo 5:26` But you have borne Sikkuth your king and Chiun, your *_images_*, the star of your god, which you made for yourselves.
* `Mic 1:7` And all her engraved *_images_* shall be beaten to pieces, all her wages shall be burned with the fire, and all her idols I will lay desolate, for she gathered it from the payment of a harlot, and they shall return to the payment of a harlot."
* `Mic 5:13` Your engraved *_images_* I will also cut off, and your standing *_images_* out of the midst of you, and you shall no longer worship the work of your hands.

_63 verses containing IMAGES_

== IMAGINATION

* `Gen 6:5` And GOD saw that the wickedness of man was great in the earth, and that every *_imagination_* of the thoughts of his heart was only evil continually.
* `Gen 8:21` And the LORD smelled a sweet savor, and the LORD said in his heart, "I will not again curse the ground anymore for man's sake, for the *_imagination_* of man's heart is evil from his youth, neither will I ever again smite every living animal as I have done.
* `Deu 29:19` And it should come to pass, when he hears the words of this curse, that he should bless himself in his heart, saying, 'I shall have peace, though I walk in the *_imagination_* of my heart,' to sweep away the moist with the dry.
* `Deu 31:21` And it shall come to pass, when many evils and troubles have befallen them, that this song shall testify against them as a witness, for it shall not be forgotten out of the mouths of their offspring. For I know their *_imagination_* which they form, even now, before I have brought them into the land which I swore."
* `1Ch 29:18` O LORD God of Abraham, Isaac, and of Israel our fathers, keep this forever in the *_imagination_* of the thoughts of the heart of your people, and prepare their heart for you.
* `Jer 3:17` At that time they shall call Jerusalem, The Throne of the LORD, and all the nations shall be gathered to it, to the name of the LORD, to Jerusalem. They shall not walk anymore after the *_imagination_* of their evil heart.
* `Jer 7:24` But they did not listen, nor incline their ear, but walked in the counsels and in the *_imagination_* of their evil heart, and went backward and not forward.
* `Jer 9:14` But have walked after the *_imagination_* of their own heart and after Baalim, which their fathers taught them,"
* `Jer 11:8` Yet they did not obey nor incline their ear, but each walked in the *_imagination_* of his evil heart. Therefore, I will bring upon them all the words of this covenant which I commanded them to do, but they did not do them.'"
* `Jer 13:10` This evil people who refuse to hear my words, who walk in the *_imagination_* of their heart and walk after other gods to serve them and to worship them, shall even be as this girdle, which is good for nothing.
* `Jer 16:12` And you have done worse than your fathers, for, behold, you all walk after the *_imagination_* of your evil heart so that you do not listen to me.
* `Jer 18:12` And they said, 'There is no hope, but we will walk after our own devices and will each do the *_imagination_* of his evil heart.'
* `Jer 23:17` They still say to those who despise me, 'The LORD has said, "You shall have peace."' And they say to everyone who walks after the *_imagination_* of his own heart, 'No evil shall come upon you.'
* `Luk 1:51` He has shown strength with his arm. He has scattered the proud in the *_imagination_* of their hearts.

_14 verses containing IMAGINATION_

== IMAGINATIONS

* `1Ch 28:9` "And you, Solomon my son, know the God of your father and serve him with a perfect heart and with a willing mind, for the LORD searches all hearts and understands all the *_imaginations_* of the thoughts. If you seek him, he will be found by you, but if you forsake him, he will cast you off forever.
* `Psa 73:7` Their eyes stand out with fatness. The *_imaginations_* of their heart transgressed.
* `Pro 6:18` A heart that devises wicked *_imaginations_*, feet that are swift in running to mischief,
* `Lam 3:60` You have seen all their vengeance and all their *_imaginations_* against me.
* `Lam 3:61` [SHIN] You have heard their reproach, O LORD, and all their *_imaginations_* against me,
* `Rom 1:21` For when they knew God, they did not glorify him as God, neither were thankful, but they became vain in their *_imaginations_* and their foolish hearts were darkened.
* `2Co 10:5` Casting down *_imaginations_* and every high thing that exalts itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ.

_7 verses containing IMAGINATIONS_

== IMLA

* `2Ch 18:7` And the king of Israel said to Jehoshaphat, "There is still one man by whom we may inquire of the LORD, but I hate him, for he never prophesies good to me, but always evil. The same is Micaiah the son of *_Imla_*." And Jehoshaphat said, "Do not let the king say so."
* `2Ch 18:8` And the king of Israel called for one of his officers and said, "Quickly bring Micaiah the son of *_Imla_*."

_2 verses containing IMLA_

== IMLAH

* `1Ki 22:8` And the king of Israel said to Jehoshaphat, "There is still one man, Micaiah the son of *_Imlah_*, by whom we may inquire of the LORD, but I hate him, for he does not prophesy good concerning me, but evil." And Jehoshaphat said, "Do not let the king say so."
* `1Ki 22:9` Then the king of Israel called an officer and said, "Hasten here Micaiah the son of *_Imlah_*."

_2 verses containing IMLAH_

== IMMANUEL

* `Isa 7:14` Therefore, the Lord himself will give you a sign: behold, a virgin shall conceive and bear a son, and shall call his name *_Immanuel_*.
* `Isa 8:8` And he shall pass through Judah. He shall overflow and go over. He shall reach even to the neck. And the extension of his wings shall fill the breadth of your land, O *_Immanuel_*.
* `Mth 1:23` "Behold, the virgin shall be with child and shall bring forth a son, and they shall call his name *_Immanuel_*," which being interpreted is, "God with us."

_3 verses containing IMMANUEL_

== IMMEDIATELY

* `1Sa 9:13` As soon as you enter the city, you will *_immediately_* find him before he goes up to the high place to eat. For the people will not eat until he comes because he blesses the sacrifice. And afterward, those who are invited will eat. Now therefore, go up, for about this time you will find him."
* `1Sa 28:20` Then Saul *_immediately_* fell his full length on the earth and was exceedingly afraid because of the words of Samuel. And there was no strength in him, for he had eaten no bread all day, nor all night.
* `Ezr 6:8` Moreover, I make a decree as to what you shall do to the elders of these Jews for the building of this house of God: that from the king's goods, even from the tribute beyond the river, expenses are to be paid to these men *_immediately_* so that they are not hindered,
* `Dan 10:17` For how can this servant of my lord talk with my lord? For as for me, *_immediately_* there remained no strength in me, neither is there breath left in me."
* `Mth 3:16` And Jesus, when he was baptized, went up *_immediately_* out of the water, and behold, the heavens were opened to him, and he saw the Spirit of God descending like a dove and coming upon him.
* `Mth 4:20` And they *_immediately_* left their nets and followed him.
* `Mth 4:22` And they *_immediately_* left the boat and their father and followed him.
* `Mth 8:3` And Jesus put forth his hand and touched him, saying, "I am willing. Be clean." And *_immediately_* his leprosy was cleansed.
* `Mth 13:5` Some fell upon stony places where they did not have much earth. And *_immediately_* they sprung up because they had no deepness of earth.
* `Mth 13:20` But he who received the seed upon stony places, the same is he who hears the word and *_immediately_* with joy receives it,
* `Mth 13:21` Yet he does not have root in himself, but endures for a while. For when tribulation or persecution arises because of the word, *_immediately_* he is offended.
* `Mth 14:22` And *_immediately_* Jesus constrained his disciples to get into a boat and to go before him to the other side while he sent the multitudes away.
* `Mth 14:27` But *_immediately_* Jesus spoke to them, saying, "Be of good cheer. It is I. Do not be afraid."
* `Mth 14:31` And *_immediately_* Jesus stretched forth his hand and caught him, and said to him, "O you of little faith, why did you doubt?"
* `Mth 20:34` So Jesus had compassion on them and touched their eyes. And *_immediately_* their eyes received sight and they followed him.
* `Mth 21:2` Saying to them, "Go into the village over against you, and *_immediately_* you shall find a donkey tied and a colt with her. Untie them and bring them to me.
* `Mth 21:3` And if any man says anything to you, you shall say, 'The Lord has need of them,' and *_immediately_* he will send them."
* `Mth 21:19` And when he saw a fig-tree in the way, he came to it and found nothing on it, but leaves only, and said to it, "Let no fruit grow on you from now on forever." And *_immediately_* the fig-tree withered.
* `Mth 24:29` "*_Immediately_* after the tribulation of those days 'the sun shall be darkened and the moon shall not give her light, the stars shall fall' from heaven and the powers of the heavens shall be shaken.
* `Mth 25:15` And to one he gave five talents, to another two, and to another one, to each according to his own ability. Then he *_immediately_* took his journey.
* `Mth 26:49` And *_immediately_* he came to Jesus, and said, "Hail Master," and kissed him.
* `Mth 26:74` Then he began to curse and to swear, saying, "I do not know the man." And *_immediately_* the cock crowed.
* `Mth 27:48` And *_immediately_* one of them ran and took a sponge, filled it with vinegar, put it on a reed, and gave it to him to drink.
* `Mrk 1:10` And *_immediately_* coming up out of the water, he saw the heavens opened and the Spirit like a dove descending upon him.
* `Mrk 1:12` And *_immediately_* the Spirit drives him into the wilderness.
* `Mrk 1:18` And *_immediately_* they forsook their nets and followed him.
* `Mrk 1:20` And *_immediately_* he called them, and they left their father Zebedee in the boat with the hired servants and went after him.
* `Mrk 1:21` And they went into Capernaum, and *_immediately_* on the sabbath he entered into the synagogue and taught.
* `Mrk 1:28` And *_immediately_* his fame spread abroad throughout all the region around Galilee.
* `Mrk 1:29` And *_immediately_*, when they had come out of the synagogue, they entered into the house of Simon and Andrew, with James and John.
* `Mrk 1:30` But the mother of Simon's wife lay sick with a fever, and *_immediately_* they tell him about her.
* `Mrk 1:31` And he came and took her by the hand and lifted her up. And *_immediately_* the fever left her, and she ministered to them.
* `Mrk 1:42` And as soon as he had spoken, *_immediately_* the leprosy departed from him and he was cleansed.
* `Mrk 1:43` And he strictly charged him and *_immediately_* sent him away,
* `Mrk 2:2` And *_immediately_* many were assembled so that there was no room to receive them, not even at the door. And he preached the word to them.
* `Mrk 2:8` And *_immediately_*, when Jesus perceived in his spirit that they thus reasoned within themselves, he said to them, "Why do you reason these things in your hearts?
* `Mrk 2:12` And *_immediately_* he arose, took up the bed, and went forth before them all. Therefore, they were all amazed and glorified God, saying, "We never saw it in this fashion."
* `Mrk 3:6` And the Pharisees went forth and *_immediately_* took counsel with the Herodians against him, how they might destroy him.
* `Mrk 4:5` And some fell on stony ground where it did not have much earth. And *_immediately_* it sprang up because it had no depth of earth.
* `Mrk 4:15` And these are those by the wayside where the word is sown, but when they have heard, Satan comes *_immediately_* and takes away the word that was sown in their hearts.
* `Mrk 4:16` And likewise, these are those who are sown on stony ground, who, when they have heard the word, *_immediately_* receive it with gladness,
* `Mrk 4:17` And have no root in themselves, and so endure only for a time. Afterward, when affliction or persecution arises for the word's sake, *_immediately_* they relapse.
* `Mrk 4:29` But when the fruit is brought forth, *_immediately_* he puts in the sickle because the harvest has come."
* `Mrk 5:2` And when he had come out of the boat, *_immediately_* out of the tombs a man with an unclean spirit met him there,
* `Mrk 5:13` And *_immediately_* Jesus gave them leave. And the unclean spirits went out and entered into the swine, and the herd ran violently down a steep place into the sea (they were about two thousand) and were choked in the sea.
* `Mrk 5:29` And *_immediately_* the fountain of her blood was dried up and she felt in her body that she was healed of that infirmity.
* `Mrk 5:30` And Jesus, *_immediately_* knowing in himself that power had gone out of him, turned himself around in the throng, and said, "Who touched my clothes?"
* `Mrk 5:42` And *_immediately_* the girl arose and walked. She was of the age of twelve years. And they were astonished with a great astonishment.
* `Mrk 6:25` And she came in *_immediately_* with haste to the king, and asked, saying, "I wish that you would give me at once the head of John the Baptist in a dish."
* `Mrk 6:27` And *_immediately_* the king sent an executioner and commanded his head to be brought. And he went and beheaded him in the prison,
* `Mrk 6:45` And *_immediately_* he constrained his disciples to get into the boat and to go to the other side ahead of him to Bethsaida while he sent the people away.
* `Mrk 6:50` (For they all saw him and were troubled.) And *_immediately_* he talked with them, and says to them, "Be of good cheer. It is I. Do not be afraid."
* `Mrk 6:54` And when they had come out of the boat, *_immediately_* they knew him,
* `Mrk 7:35` And *_immediately_* his ears were opened, the string of his tongue was loosened, and he spoke plainly.
* `Mrk 8:10` And *_immediately_* he entered into a boat with his disciples and came into the parts of Dalmanutha.
* `Mrk 9:15` And *_immediately_*, when they beheld him, all the people were greatly amazed and ran to him and saluted him.
* `Mrk 9:20` And they brought him to him. And when he saw him, *_immediately_* the spirit convulsed him, and he fell on the ground and wallowed, foaming.
* `Mrk 9:24` And *_immediately_* the father of the child cried out and said with tears, "Lord, I believe. Help my unbelief."
* `Mrk 10:52` And Jesus said to him, "Go, your faith has made you whole." And *_immediately_* he received his sight and followed Jesus on the way.
* `Mrk 11:3` And if any man says to you, 'Why do you do this?' say that the Lord has need of him, and *_immediately_* he will send him here."
* `Mrk 14:43` And *_immediately_* while he was yet speaking, Judas comes, one of the twelve, and with him a great multitude with swords and staffs from the chief priests, the scribes, and the elders.
* `Mrk 14:45` And as soon as he had come, he goes *_immediately_* to him, and says, "Master, master," and kissed him.
* `Mrk 15:1` And *_immediately_* in the morning the chief priests held a consultation with the elders, scribes, and the whole council, and bound Jesus, carried him away, and delivered him to Pilate.
* `Luk 1:64` And his mouth was opened *_immediately_* and his tongue loosened, and he spoke and praised God.
* `Luk 4:39` And he stood over her and rebuked the fever, and it left her. And *_immediately_* she arose and ministered to them.
* `Luk 5:13` And he put forth his hand and touched him, saying, "I am willing. Be clean." And *_immediately_* the leprosy departed from him.
* `Luk 5:25` And *_immediately_* he arose before them, took up that on which he lay, and departed to his own house glorifying God.
* `Luk 5:39` No man also having drank old wine *_immediately_* desires new, because he says, 'The old is better.'"
* `Luk 6:49` But he who hears and does not do, is like a man who built a house on the earth without a foundation, against which the stream beat vehemently and *_immediately_* it fell, and the ruin of that house was great."
* `Luk 8:44` Came behind him and touched the border of his garment, and *_immediately_* her issue of blood stanched.
* `Luk 8:47` And when the woman saw that she was not hid, she came trembling, and falling down before him, she declared to him before all the people for what cause she had touched him and how she was healed *_immediately_*.
* `Luk 8:55` And her spirit came back, and she arose *_immediately_*. Then he commanded them to give her food.
* `Luk 12:36` And you yourselves be like men who wait for their lord when he returns from the wedding, so that when he comes and knocks, they may open to him *_immediately_*.
* `Luk 12:54` And he said also to the people, "When you see a cloud rising in the west, *_immediately_* you say, 'There comes a shower,' and it is so.
* `Luk 13:13` And he laid his hands on her, and *_immediately_* she was made straight and glorified God.
* `Luk 14:5` And answered them, saying, "Which of you having a donkey or an ox fall into a pit would not *_immediately_* pull him out on the sabbath?"
* `Luk 17:7` "But which of you, having a servant plowing or feeding sheep, will say to him *_immediately_* when he has come from the field, 'Go and sit down to eat'?
* `Luk 18:43` And *_immediately_* he received his sight and followed him, glorifying God. And when they saw it, all the people gave praise to God.
* `Luk 19:11` And as they heard these things, he added and spoke a parable, because he was near to Jerusalem and because they thought that the kingdom of God would *_immediately_* appear.
* `Luk 19:40` And he answered and said to them, "I tell you, that if these should hold their peace, the stones would *_immediately_* cry out."
* `Luk 21:9` But when you hear of wars and commotions, do not be terrified. For these things must first come to pass, but the end will not come *_immediately_*."
* `Luk 22:60` And Peter said, "Man, I do not know what you say." And *_immediately_*, while he was still speaking, the cock crowed.
* `Jhn 5:9` And *_immediately_* the man was healed and he took up his bed and walked. Now on the same day was the sabbath.
* `Jhn 6:21` Then they willingly received him into the boat, and *_immediately_* the boat was at the land where they were going.
* `Jhn 13:30` Then having received the piece of bread, he went out *_immediately_*. And it was night.
* `Jhn 13:32` If God is glorified in him, God will also glorify him in himself, and will glorify him *_immediately_*.
* `Jhn 18:27` Peter then denied again, and *_immediately_* the cock crowed.
* `Jhn 19:34` But one of the soldiers pierced his side with a spear, and *_immediately_* blood and water came out.
* `Jhn 21:3` Simon Peter says to them, "I am going fishing." They say to him, "We also will go with you." They went forth and entered into a boat *_immediately_*. And that night they caught nothing.
* `Act 3:7` And he took him by the right hand and lifted him up. And *_immediately_* his feet and ankle bones received strength.
* `Act 5:10` Then she fell down *_immediately_* at his feet and expired. And the young men came in and found her dead, and carrying her forth, buried her by her husband.
* `Act 9:18` And *_immediately_* there fell from his eyes something like scales, and he received sight *_immediately_*. Then he arose and was baptized.
* `Act 9:20` And *_immediately_* he preached Christ in the synagogues, that he is the Son of God.
* `Act 9:34` And Peter said to him, "Eneas, Jesus Christ heals you. Arise, and make your bed." And he arose *_immediately_*.
* `Act 10:33` *_Immediately_* therefore I sent for you, and you have done well that you have come. Now therefore, we are all here present before God to hear all things that are commanded you by God."
* `Act 11:11` And behold, *_immediately_* there were three men already standing at the house where I was, sent to me from Caesarea.
* `Act 12:10` When they were past the first and the second ward, they came to the iron gate that leads to the city, which opened to them of its own accord. And they went out and passed on through one street, and *_immediately_* the angel departed from him.
* `Act 12:23` And *_immediately_* the angel of the Lord smote him because he did not give God the glory, and he was eaten by worms and died.
* `Act 13:11` And now behold, the hand of the Lord is upon you and you shall be blind, not seeing the sun for a season." And *_immediately_* there fell on him a mist and a darkness and he went around seeking someone to lead him by the hand.
* `Act 16:10` And after he had seen the vision, *_immediately_* we endeavored to go into Macedonia, concluding that the Lord had called us to preach the gospel to them.
* `Act 16:26` And suddenly there was a great earthquake so that the foundations of the prison were shaken, and *_immediately_* all the doors were opened and everyone's bonds were loosened.
* `Act 17:10` And the brothers *_immediately_* sent away Paul and Silas by night to Berea, who, coming there, went into the synagogue of the Jews.
* `Act 17:14` And then *_immediately_* the brothers sent Paul away to go as far as to the sea, but Silas and Timothy stayed there still.
* `Act 21:30` And all the city was moved and the people ran together. And they took Paul and drew him out of the temple. And *_immediately_* the doors were shut.
* `Act 21:32` Who *_immediately_* took soldiers and centurions and ran down to them. And when they saw the chief captain and the soldiers, they stopped beating Paul.
* `Act 22:29` Then *_immediately_* those who were about to examine him departed from him. And the chief captain also was afraid after he knew that he was a Roman and because he had bound him.
* `Act 23:30` And when it was told to me that the Jews laid wait for the man, I sent *_immediately_* to you and gave commandment to his accusers also to say before you what they had against him. Farewell."
* `Gal 1:16` To reveal his Son in me, so that I might preach him among the heathen, *_immediately_* I did not confer with flesh and blood,
* `Jms 1:24` For he beholds himself, goes away, and *_immediately_* forgets what manner of man he was.
* `Rev 4:2` And *_immediately_* I was in the Spirit. And behold, a throne was set in heaven, and someone sat on the throne.

_110 verses containing IMMEDIATELY_

== IMMER

* `1Ch 9:12` And Adaiah the son of Jeroham, the son of Pashur, the son of Malchijah; and Maasiai the son of Adiel, the son of Jahzerah, the son of Meshullam, the son of Meshillemith, the son of *_Immer_*;
* `1Ch 24:14` The fifteenth to Bilgah, the sixteenth to *_Immer_*,
* `Ezr 2:37` The children of *_Immer_*, one thousand and fifty-two;
* `Ezr 2:59` And these were those who went up from Tel-melah, Tel-harsa, Cherub, Addan, and *_Immer_*, but they could not prove their fathers' houses or their genealogy, whether they were of Israel:
* `Ezr 10:20` And of the sons of *_Immer_*: Hanani and Zebadiah.
* `Neh 3:29` After them Zadok the son of *_Immer_* repaired over against his house. After him Shemaiah the son of Shechaniah, the keeper of the east gate, repaired.
* `Neh 7:40` The children of *_Immer_*, one thousand and fifty-two;
* `Neh 7:61` And these were those who went up also from Tel-mela, Tel-haresha, Cherub, Addon, and *_Immer_*, but they could not show their fathers' house, nor their genealogy, whether they were of Israel.
* `Neh 11:13` And his brothers, chief of the fathers, two hundred and forty-two; and Amashai the son of Azareel, the son of Ahasai, the son of Meshillemoth, the son of *_Immer_*,
* `Jer 20:1` Now Pashur the son of *_Immer_* the priest, who was also chief governor in the house of the LORD, heard that Jeremiah prophesied these things.

_10 verses containing IMMER_

== IMMORTAL

* `1Ti 1:17` Now to the King eternal, *_immortal_*, invisible, God the only wise, be honor and glory forever and ever. Amen.

_1 verse containing IMMORTAL_

== IMMORTALITY

* `Rom 2:7` To those who, by patient continuance in well-doing, seek for glory, honor, and *_immortality_*, he will give eternal life,
* `1Co 15:53` For this corruptible must put on incorruption and this mortal must put on *_immortality_*.
* `1Co 15:54` So when this corruptible has put on incorruption and this mortal has put on *_immortality_*, the saying that is written shall be brought to pass: "Death is swallowed up in victory."
* `1Ti 6:16` Who only has *_immortality_*, dwelling in the light which no man can approach, whom no man has seen, nor can see, to whom be honor and everlasting power. Amen.
* `2Ti 1:10` But is now made manifest by the appearing of our Savior Jesus Christ, who has abolished death and has brought life and *_immortality_* to light through the gospel.

_5 verses containing IMMORTALITY_

== IMMOVABLE

* `Act 27:41` And falling into a place where two seas met, they ran the ship aground. And the forepart stuck firmly and remained *_immovable_*, but the back part was broken with the violence of the waves.
* `1Co 15:58` Therefore, my beloved brothers, be steadfast, *_immovable_*, always abounding in the work of the Lord, because you know that your labor is not in vain in the Lord.

_2 verses containing IMMOVABLE_

== IMMUTABILITY

* `Heb 6:17` In this, God, more abundantly willing to show to the heirs of promise the *_immutability_* of his counsel, confirmed it by an oath,

_1 verse containing IMMUTABILITY_

== IMMUTABLE

* `Heb 6:18` So that by two *_immutable_* things, in which it was impossible for God to lie, we might have a strong consolation, who have fled for refuge to lay hold upon the hope set before us.

_1 verse containing IMMUTABLE_

== IMNA

* `1Ch 7:35` And the sons of his brother Helem: Zophah, *_Imna_*, Shelesh, and Amal.

_1 verse containing IMNA_

== IMNAH

* `1Ch 7:30` The sons of Asher: *_Imnah_*, Isuah, Ishua, and Beriah. Serah was their sister.
* `2Ch 31:14` And Kore the son of *_Imnah_* the Levite, the gatekeeper toward the east, was over the voluntary-offerings of God to distribute the oblations of the LORD and the most holy things.

_2 verses containing IMNAH_

== IMPART

* `Luk 3:11` He answers and says to them, "He who has two coats, let him *_impart_* to him who has none, and he who has provisions, let him do likewise."
* `Rom 1:11` For I long to see you so that I may *_impart_* to you some spiritual gift, to the end you may be established,

_2 verses containing IMPART_

== IMPARTED

* `Job 39:17` Because God has withheld wisdom from her, neither has he *_imparted_* to her understanding.
* `1Th 2:8` So being affectionately desirous of you, we were willing to have *_imparted_* to you, not the gospel of God only, but also our own souls, because you were dear to us.

_2 verses containing IMPARTED_

== IMPATIENT

* `Zch 11:8` I also cut off three shepherds in one month. My soul was *_impatient_* with them, and their soul also abhorred me.

_1 verse containing IMPATIENT_

== IMPEDIMENT

* `Mrk 7:32` And they bring to him someone who was deaf and had an *_impediment_* in his speech, and they implore him to put his hand upon him.

_1 verse containing IMPEDIMENT_

== IMPELLED

* `Pro 7:21` With her much fair speech she caused him to yield. With the flattering of her lips she *_impelled_* him.

_1 verse containing IMPELLED_

== IMPENITENT

* `Rom 2:5` But because of your hardness and *_impenitent_* heart, you treasure up for yourself wrath against the day of wrath and revelation of the righteous judgment of God,

_1 verse containing IMPENITENT_

== IMPERFECT


_0 verses containing IMPERFECT_

== IMPERIOUS

* `Ezk 16:30` "How weak is your heart," says the Lord GOD, "seeing you do all these things, the work of an *_imperious_* lewd woman,

_1 verse containing IMPERIOUS_

== IMPIOUSLY

* `Jde 1:15` To execute judgment upon all and to convict all who are ungodly among them of all their ungodly deeds which they have *_impiously_* committed and of all their hard speeches which ungodly sinners have spoken against him."

_1 verse containing IMPIOUSLY_

== IMPLACABLE

* `Rom 1:31` Without understanding, covenant-breakers, without natural affection, *_implacable_*, unmerciful;

_1 verse containing IMPLACABLE_

== IMPLANTED

* `Rom 11:17` And if some of the branches are broken off, and you, being a wild olive-tree, are *_implanted_* among them, and with them partake of the root and fatness of the olive-tree,
* `Jms 1:21` Therefore, lay apart all filthiness and overflow of wickedness and receive with meekness the *_implanted_* word, which is able to save your souls.

_2 verses containing IMPLANTED_

== IMPLORE

* `Exo 3:18` And they shall listen to your voice, and you shall come—you and the elders of Israel—to the king of Egypt, and you shall say to him, 'The LORD God of the Hebrews has met with us. And now let us go (we *_implore_* you) three days journey into the wilderness so that we may sacrifice to the LORD our God.'
* `Exo 33:18` And [Moses] said, "I *_implore_* you, show me your glory."
* `Num 12:11` And Aaron said to Moses, "Alas, my lord, I *_implore_* you, do not lay the sin upon us in which we have done foolishly and in which we have sinned.
* `Num 12:13` And Moses cried to the LORD, saying, "Heal her now, O God, I *_implore_* you."
* `Num 14:17` And now, I *_implore_* you, let the power of my Lord be great, according as you have spoken, saying,
* `Num 14:19` Pardon, I *_implore_* you, the iniquity of this people according to the greatness of your mercy, as you have forgiven this people from Egypt even until now."
* `1Sa 23:11` Will the men of Keilah deliver me up into his hand? Will Saul come down as your servant has heard? O LORD God of Israel, I *_implore_* you, tell your servant." And the LORD said, "He will come down."
* `2Sa 13:24` And Absalom came to the king and said, "Behold now, your servant has sheep-shearers. Let the king, I *_implore_* you, and his servants go with your servant."
* `2Sa 16:4` Then the king said to Ziba, "Behold, all that pertained to Mephibosheth is yours." And Ziba said, "I humbly *_implore_* you that I may find grace in your sight, my lord, O king."
* `2Sa 24:10` And David's heart smote him after he had numbered the people. And David said to the LORD, "I have sinned greatly in what I have done. And now, I *_implore_* you, O LORD, take away the iniquity of your servant, for I have done very foolishly."
* `2Ki 19:19` Now therefore, O LORD our God, I *_implore_* you, save us from his hand so that all the kingdoms of the earth may know that you are the LORD God, even you only."
* `2Ki 20:3` "I *_implore_* you, O LORD, remember now how I have walked before you in truth and with a perfect heart and have done that which is good in your sight." And Hezekiah wept grievously.
* `1Ch 21:8` And David said to God, "I have sinned greatly because I have done this thing. But now, I *_implore_* you, put away the iniquity of your servant, for I have done very foolishly."
* `2Ch 6:40` "Now, my God, I *_implore_* you, let your eyes be open and let your ears be attentive to the prayer that is made in this place.
* `Neh 1:5` And said, "I *_implore_* you, O LORD God of heaven, the great and awesome God, who keeps covenant and mercy for those who love him and observe his commandments,
* `Neh 1:8` Remember, I *_implore_* you, the word that you commanded your servant Moses, saying, 'If you transgress, I will scatter you abroad among the nations,
* `Neh 1:11` O Lord, I *_implore_* you, now let your ear be attentive to the prayer of your servant and to the prayer of your servants who desire to fear your name. And prosper, I pray you, your servant this day, and grant him mercy in the sight of this man." (I was the king's cup-bearer.)
* `Job 10:9` Remember, I *_implore_* you, that you have made me like the clay. And will you bring me into dust again?
* `Job 42:4` Hear, I *_implore_* you, and I will speak. I will ask of you, and you declare to me.
* `Psa 80:14` Return, we *_implore_* you, O God of hosts. Look down from heaven and behold. Visit this vine,
* `Psa 116:4` Then I called upon the name of the LORD: "O LORD, I *_implore_* you, deliver my soul."
* `Psa 118:25` Save now, I *_implore_* you, O LORD. O LORD, I *_implore_* you, send prosperity now.
* `Psa 119:108` Accept, I *_implore_* you, the voluntary-offerings of my mouth, O LORD, and teach me your judgments.
* `Isa 38:3` And said, "Remember now, O LORD, I *_implore_* you, how I have walked before you in truth and with a perfect heart and have done that which is good in your sight." And Hezekiah wept bitterly.
* `Isa 64:9` Do not be very angry, O LORD, neither remember iniquity forever. Behold, see, we *_implore_* you, we are all your people.
* `Jer 26:19` "Did Hezekiah king of Judah and all Judah put him to death? Did he not fear the LORD and *_implore_* the LORD, and the LORD repented of the evil which he had pronounced against them? Thus we might procure great evil against our souls."
* `Jer 38:4` Therefore, the princes said to the king, "We *_implore_* you, let this man be put to death, for thus he weakens the hands of the men of war who remain in this city and the hands of all the people in speaking such words to them. For this man does not seek the welfare of this people, but the hurt."
* `Jer 38:20` But Jeremiah said, "They shall not deliver you. Obey, I *_implore_* you, the voice of the LORD, which I speak to you, so that it may be well with you, and that your soul may live.
* `Jer 42:2` And said to Jeremiah the prophet, "We *_implore_* you, let our supplication be accepted before you, and pray for us to the LORD your God, even for all this remnant (for we are left but a few of many, as your eyes behold us),
* `Dan 1:12` "Prove your servants, I *_implore_* you, ten days. And let them give us pulse to eat and water to drink.
* `Dan 9:16` O Lord, according to all your righteousness, I *_implore_* you, let your anger and your fury be turned away from your city Jerusalem, your holy mountain. Because for our sins and for the iniquities of our fathers, Jerusalem and your people have become a reproach to all who are around us.
* `Amo 7:2` And it came to pass, that when they had made an end of eating the grass of the land, then I said, "O Lord GOD, forgive, I *_implore_* you. By whom shall Jacob arise? For he is small."
* `Amo 7:5` Then I said, "O Lord GOD, cease, I *_implore_* you. By whom shall Jacob arise? For he is small."
* `Jna 1:14` Therefore, they cried to the LORD, and said, "We *_implore_* you, O LORD, we *_implore_* you, do not let us perish for this man's life and do not lay upon us innocent blood. For you, O LORD, have done as it pleased you."
* `Jna 4:3` Now therefore, O LORD, take, I *_implore_* you, my life from me, for it is better for me to die than to live."
* `Mal 1:9` "And now, I pray you, *_implore_* God that he will be gracious to us. This has been by your means. Will he regard your person?" says the LORD of hosts.
* `Mrk 7:32` And they bring to him someone who was deaf and had an impediment in his speech, and they *_implore_* him to put his hand upon him.
* `Luk 8:28` When he saw Jesus, he cried out and fell down before him, and with a loud voice said, "What have I to do with you, Jesus, Son of God most high? I *_implore_* you to not torment me."
* `Luk 9:38` And behold, a man of the company cried out, saying, "Master, I *_implore_* you to look upon my son, for he is my only child.
* `Act 21:39` But Paul said, "I am a Jew of Tarsus, a city of Cilicia, a citizen of no mean city, and I *_implore_* you to allow me to speak to the people."
* `Act 26:3` Especially because I know you to be expert in all customs and questions which are among the Jews. Therefore, I *_implore_* you to hear me patiently.
* `Rom 12:1` I *_implore_* you therefore, brothers, by the mercies of God, that you present your bodies as a living sacrifice, holy, acceptable to God, which is your reasonable service.
* `Rom 15:30` Now I *_implore_* you, brothers, for the Lord Jesus Christ's sake and for the love of the Spirit, that you strive together with me in your prayers to God for me,
* `Rom 16:17` Now I *_implore_* you, brothers, mark those who cause divisions and offenses contrary to the doctrine which you have learned, and avoid them.
* `1Co 1:10` Now I *_implore_* you, brothers, by the name of our Lord Jesus Christ, that you all speak the same thing and that there be no divisions among you, but that you be perfectly joined together in the same mind and in the same judgment.
* `1Co 4:16` Therefore, I *_implore_* you, be followers of me.
* `1Co 16:15` I *_implore_* you, brothers—you know the house of Stephanas, that it is the first fruits of Achaia and that they have addicted themselves to the ministry of the saints—
* `2Co 2:8` Therefore, I *_implore_* you that you would confirm your love toward him.
* `2Co 10:1` Now I, Paul, myself *_implore_* you by the meekness and gentleness of Christ—I who in presence am base among you, but being absent am bold toward you.
* `2Co 10:2` But I *_implore_* you that when I am present I may not be bold with the confidence with which I intend to be bold against some, who think of us as if we walked according to the flesh.
* `Gal 4:12` Brothers, I *_implore_* you, be as I am, for I am as you are. You have not injured me at all.
* `Eph 4:1` I therefore, the prisoner of the Lord, *_implore_* you that you walk worthy of the vocation by which you are called,
* `1Th 4:1` Furthermore then, we *_implore_* you, brothers, and exhort you by the Lord Jesus, that as you have received from us how you ought to walk and to please God, so you would abound more and more.
* `1Th 4:10` And indeed you do it toward all the brothers who are in all Macedonia. But we *_implore_* you, brothers, that you increase more and more,
* `1Th 5:12` And we *_implore_* you, brothers, to regard those who labor among you and are over you in the Lord and admonish you,
* `2Th 2:1` Now we *_implore_* you, brothers, by the coming of our Lord Jesus Christ and by our gathering to him,
* `Phm 1:9` Yet for love's sake I rather *_implore_* you, being such a one as Paul the aged and now also a prisoner of Jesus Christ.
* `Phm 1:10` I *_implore_* you for my son Onesimus whom I have begotten in my bonds,
* `Heb 13:19` But I *_implore_* you the rather to do this so that I may be restored to you more quickly.
* `Heb 13:22` And I *_implore_* you, brothers, bear with the word of exhortation, for I have written a letter to you in few words.
* `1Pe 2:11` Dearly beloved, I *_implore_* you as strangers and pilgrims, abstain from fleshly lusts which war against the soul,
* `2Jn 1:5` And now I *_implore_* you, lady, not as though I wrote a new commandment to you, but that which we had from the beginning, that we love one another.

_62 verses containing IMPLORE_

== IMPLORED

* `Gen 42:21` And they said to one another, "We are truly guilty concerning our brother in that we saw the anguish of his soul when he *_implored_* us, and we would not hear; therefore, this distress has come upon us."
* `Exo 32:11` And Moses *_implored_* the LORD his God and said, "LORD, why does your wrath wax hot against your people which you have brought forth from the land of Egypt with great power and with a mighty hand?
* `Deu 3:23` "And I *_implored_* the LORD at that time, saying,
* `2Sa 12:16` David therefore *_implored_* God for the child. And David fasted, went in, and lay all night upon the earth.
* `1Ki 13:6` And the king answered and said to the man of God, "Entreat now the face of the LORD your God and pray for me so that my hand may be restored to me again." And the man of God *_implored_* the LORD, and the king's hand was restored to him again and became as it was before.
* `2Ki 1:13` And again he sent a third captain of fifty with his fifty. And the third captain of fifty went up, came and fell on his knees before Elijah, and *_implored_* him and said to him, "O man of God, I pray you, let my life and the life of these fifty your servants be precious in your sight.
* `2Ki 13:4` And Jehoahaz *_implored_* the LORD, and the LORD listened to him, for he saw the oppression of Israel because the king of Syria oppressed them.
* `2Ch 33:12` And when he was in affliction, he *_implored_* the LORD his God and humbled himself greatly before the God of his fathers.
* `Ezr 8:23` So we fasted and *_implored_* our God for this. And he was entreated by us.
* `Est 8:3` And Esther spoke yet again before the king, fell down at his feet, and *_implored_* him with tears to put away the mischief of Haman the Agagite and his plan that he had devised against the Jews.
* `Mth 8:31` So the demons *_implored_* him, saying, "If you expel us, allow us to go away into the herd of swine."
* `Mth 8:34` And behold, the whole city came out to meet Jesus. And when they saw him, they *_implored_* him that he would depart out of their borders.
* `Mth 14:36` And *_implored_* him that they might only touch the hem of his garment. And as many as touched it were restored to health.
* `Mth 15:23` But he did not answer her a word. And his disciples came and *_implored_* him, saying, "Send her away, for she cries after us."
* `Mth 18:29` And his fellow-servant fell down at his feet and *_implored_* him, saying, 'Have patience with me and I will pay you everything.'
* `Mrk 5:10` And he *_implored_* him much that he would not send them away out of the country.
* `Mrk 5:12` And all the demons *_implored_* him, saying, "Send us into the swine so that we may enter into them."
* `Mrk 5:23` And *_implored_* him greatly, saying, "My little daughter lies at the point of death. I pray you, come and lay your hands on her so that she may be healed, and she will live."
* `Mrk 6:56` And wherever he entered, into villages, cities, or country, they laid the sick in the streets and *_implored_* him that they might touch at least the fringe of his garment. And as many as touched him were healed.
* `Mrk 7:26` (The woman was a Greek, a Syrophenician by nation), and she *_implored_* him that he would cast forth the demon out of her daughter.
* `Mrk 8:22` And he comes to Bethsaida, and they bring a blind man to him and *_implored_* him to touch him.
* `Luk 4:38` And he arose out of the synagogue and entered into Simon's house. And the mother of Simon's wife was taken with a violent fever, and they *_implored_* him for her.
* `Luk 5:12` And it came to pass, when he was in a certain city, behold, a man full of leprosy, who, seeing Jesus, fell on his face and *_implored_* him, saying, "Lord, if you are willing, you can make me clean."
* `Luk 7:4` And when they came to Jesus, they *_implored_* him earnestly, saying, "He is worthy for you to do this,
* `Luk 8:31` And they *_implored_* him that he would not command them to go out into the deep.
* `Luk 8:32` Now there was a herd of many swine feeding on the mountain. And they *_implored_* him that he would allow them to enter into them. And he allowed them.
* `Luk 8:37` Then the whole multitude of the surrounding country of the Gadarenes *_implored_* him to depart from them, for they were taken with great fear. And he went into the boat and returned.
* `Luk 8:38` Now the man out of whom the demons had departed *_implored_* him that he might be with him. But Jesus sent him away, saying,
* `Luk 8:41` And behold, there came a man named Jairus, and he was a ruler of the synagogue. He fell down at the feet of Jesus and *_implored_* him that he would come into his house.
* `Luk 9:40` And I *_implored_* your disciples to cast him out, but they could not."
* `Luk 11:37` And as he was speaking, a certain Pharisee *_implored_* him to dine with him. And he went in and sat down to eat.
* `Jhn 4:40` So when the Samaritans had come to him, they *_implored_* him that he would stay with them. And he stayed there two days.
* `Jhn 4:47` When he heard that Jesus had come from Judea into Galilee, he went to him and *_implored_* him that he would come down and heal his son, for he was at the point of death.
* `Jhn 19:31` The Jews therefore, because it was the preparation, so that the bodies should not remain upon the cross on the sabbath (for that sabbath was a high day), *_implored_* Pilate that their legs might be broken and that they might be taken away.
* `Act 13:42` And when the Jews had gone out of the synagogue, the Gentiles *_implored_* that these words might be preached to them the next sabbath.
* `Act 16:9` And a vision appeared to Paul in the night: a man of Macedonia stood there and *_implored_* him, saying, "Come over into Macedonia and help us."
* `Act 16:15` And when she was baptized, along with her household, she *_implored_* us, saying, "If you have judged me to be faithful to the Lord, come into my house and stay there." And she constrained us.
* `Act 16:39` So they came and *_implored_* them. And having brought them out, they asked them to depart out of the city.
* `Act 21:12` And when we heard these things, both we and those of that place *_implored_* him not to go up to Jerusalem.
* `Act 25:2` Then the high priest and the chief of the Jews brought charges to him against Paul. And they *_implored_* him
* `Act 27:33` And as the day was about to come, Paul *_implored_* them all to take food, saying, "This day is the fourteenth day that you have waited and continued fasting, having taken nothing.
* `2Co 5:20` Now then we are ambassadors for Christ, as though God *_implored_* you by us. We pray you on behalf of Christ: be reconciled to God.
* `2Co 12:8` For this thing I *_implored_* the Lord three times that it might depart from me.
* `1Ti 1:3` As I *_implored_* you when I went into Macedonia, remain at Ephesus so that you might charge some that they teach no other doctrine,

_44 verses containing IMPLORED_

== IMPLORING

* `Mth 8:5` And when Jesus had entered into Capernaum, a centurion came to him, *_imploring_* him,
* `Mrk 1:40` And there came a leper to him, *_imploring_* him, and kneeling down to him and saying to him, "If you are willing, you can make me clean."
* `Luk 7:3` And when he heard of Jesus, he sent the elders of the Jews to him *_imploring_* him that he would come and heal his servant.

_3 verses containing IMPLORING_

== IMPORTED

* `1Ki 9:28` And they came to Ophir and *_imported_* four hundred and twenty talents of gold from there and brought it to king Solomon.

_1 verse containing IMPORTED_

== IMPORTUNITY

* `Luk 11:8` I say to you, even though he will not rise and give to him because he is his friend, yet because of his *_importunity_* he will rise and give to him as many as he needs.

_1 verse containing IMPORTUNITY_

== IMPOSE

* `Ezr 7:24` Also, we inform you, that concerning any of the priests and Levites, singers, gatekeepers, Nethinims, or ministers of this house of God, it shall not be lawful to *_impose_* toll, tribute, or custom upon them.

_1 verse containing IMPOSE_

== IMPOSED

* `2Ch 36:3` And the king of Egypt deposed him at Jerusalem and *_imposed_* upon the land a fine of one hundred talents of silver and a talent of gold.
* `Heb 9:10` Which stood only in foods and drinks, diverse washings, and carnal ordinances *_imposed_* on them until the time of reformation.

_2 verses containing IMPOSED_

== IMPOSITION

* `2Ti 1:6` For this cause I put you in remembrance that you stir up the gift of God which is in you by the *_imposition_* of my hands.

_1 verse containing IMPOSITION_

== IMPOSSIBLE

* `Mth 17:20` And Jesus said to them, "Because of your unbelief. For truly I say to you, if you have faith as a grain of mustard-seed, you shall say to this mountain, 'Move from here to yonder place,' and it shall move. And nothing shall be *_impossible_* to you.
* `Mth 19:26` But Jesus beheld them, and said to them, "With men this is *_impossible_*, but with God all things are possible."
* `Mrk 10:27` And Jesus looking upon them, says, "With men it is *_impossible_*, but not with God. For with God all things are possible."
* `Luk 1:37` For with God nothing will be *_impossible_*."
* `Luk 17:1` Then he said to the disciples, "It is *_impossible_* for the causes of sin to not come. But woe to him by whom they come!
* `Luk 18:27` Then he said, "The things which are *_impossible_* with men are possible with God."
* `Heb 6:4` For it is *_impossible_* for those who have been once enlightened, have tasted the heavenly gift, have been made partakers of the Holy Spirit,
* `Heb 6:18` So that by two immutable things, in which it was *_impossible_* for God to lie, we might have a strong consolation, who have fled for refuge to lay hold upon the hope set before us.
* `Heb 11:6` But without faith it is *_impossible_* to please him. For he who comes to God must believe that he exists and that he is a rewarder of those who diligently seek him.

_9 verses containing IMPOSSIBLE_

== IMPOVERISH

* `Jer 5:17` And they shall eat up your harvest and your bread, which your sons and your daughters should eat. They shall eat up your flocks and your herds. They shall eat up your vines and your fig-trees. They shall *_impoverish_* with the sword your fortified cities, in which you have trusted.

_1 verse containing IMPOVERISH_

== IMPOVERISHED

* `Jdg 6:6` And Israel was greatly *_impoverished_* because of the Midianites. And the children of Israel cried to the LORD.
* `Isa 40:20` He who is so *_impoverished_* that he has no oblation chooses a tree that will not rot. He seeks for himself a skillful workman to prepare an engraved image that shall not be moved.
* `Mal 1:4` Whereas Edom says, "We are *_impoverished_*, but we will return and build the desolate places," thus says the LORD of hosts: "They shall build, but I will throw down, and they shall call them, 'The Border of Wickedness,' and, 'The People Against Whom the LORD Has Indignation Forever.'"

_3 verses containing IMPOVERISHED_

== IMPRISONED

* `Act 22:19` And I said, 'Lord, they know that I *_imprisoned_* and beat in every synagogue those who believed in you.

_1 verse containing IMPRISONED_

== IMPRISONMENT

* `Ezr 7:26` And whoever will not do the law of your God and the law of the king, let judgment be executed speedily upon him, whether it be to death, to banishment, to confiscation of goods, or to *_imprisonment_*."
* `Heb 11:36` Others had trial of cruel mockings and scourgings and also of bonds and *_imprisonment_*.

_2 verses containing IMPRISONMENT_

== IMPRISONMENTS

* `2Co 6:5` In stripes, in *_imprisonments_*, in tumults, in labors, in watchings, in fastings;

_1 verse containing IMPRISONMENTS_

== IMPRISONS

* `Job 11:10` If he passes by, *_imprisons_*, or calls to judgment, then who can hinder him?

_1 verse containing IMPRISONS_

== IMPROPERLY

* `1Co 7:36` But if any man thinks that he behaves himself *_improperly_* toward his virgin, if she has passed the flower of her age, and need so requires, let him do what he wishes. He does not sin. Let them marry.

_1 verse containing IMPROPERLY_

== IMPUDENT

* `Pro 7:13` So she caught him, kissed him, and with an *_impudent_* face said to him,
* `Ezk 2:4` For they are *_impudent_* children and obstinate in heart. I send you to them, and you shall say to them, 'Thus says the Lord GOD.'
* `Ezk 3:7` But the house of Israel will not listen to you because they will not listen to me, for all the house of Israel are *_impudent_* and hard-hearted.

_3 verses containing IMPUDENT_

== IMPURITIES

* `Ezk 23:8` She did not leave her lewd deeds brought from Egypt. For in her youth they lay with her, and they first corrupted her and poured their *_impurities_* upon her.

_1 verse containing IMPURITIES_

== IMPURITY

* `Ezk 36:17` "Son of man, when the house of Israel dwelt in their own land, they defiled it by their own way and by their doings. Their way was before me as the uncleanness of a woman in her *_impurity_*.
* `1Th 2:3` For our exhortation was not from deceit, nor from *_impurity_*, nor in guile,
* `Jde 1:7` Even as Sodom and Gomorrah, and the cities around them in like manner, giving themselves over to *_impurity_* and going after strange flesh, are set forth for an example, suffering the vengeance of eternal fire.

_3 verses containing IMPURITY_

== IMPUTE

* `1Sa 22:15` Did I then begin to inquire of God for him? Be it far from me. Do not let the king *_impute_* anything to his servant, nor to all the house of my father, for your servant knew nothing of the least of all of this."
* `2Sa 19:19` And said to the king, "Do not let my lord *_impute_* iniquity to me, neither remember that which your servant did perversely the day that my lord the king went out of Jerusalem, that the king should take it to his heart.
* `Psa 32:2` Blessed is the man to whom the LORD does not *_impute_* iniquity and in whose spirit there is no guile.
* `Rom 4:8` Blessed is the man to whom the Lord will not *_impute_* sin."

_4 verses containing IMPUTE_

== IMPUTED

* `Lev 7:18` And if any of the flesh of the sacrifice of his peace-offerings is eaten at all on the third day, it shall not be accepted, neither shall it be *_imputed_* to him who offers it. It shall be an abomination. And the soul who eats of it shall bear his iniquity.
* `Lev 17:4` And does not bring it to the door of the Tabernacle of the Congregation to offer an offering to the LORD before the tabernacle of the LORD, blood shall be *_imputed_* to that man. He has shed blood, and that man shall be cut off from among his people.
* `Rom 4:11` And he received the sign of circumcision, a seal of the righteousness of the faith, which he had while still uncircumcised, so that he might be the father of all those who believe, though they are not circumcised, so that righteousness might be *_imputed_* to them also;
* `Rom 4:22` And therefore, it was "*_imputed_* to him for righteousness."
* `Rom 4:23` Now it was not written for his sake alone that it was *_imputed_* to him,
* `Rom 4:24` But for us also, to whom it will be *_imputed_*, if we believe in him who raised Jesus our Lord from the dead,
* `Rom 5:13` For until the law, sin was in the world. But sin is not *_imputed_* when there is no law.
* `Jms 2:23` And the Scripture was fulfilled, which says, "Abraham believed God, and it was *_imputed_* to him for righteousness," and he was called the Friend of God.

_8 verses containing IMPUTED_

== IMPUTES

* `Rom 4:6` Even as David also describes the blessedness of the man to whom God *_imputes_* righteousness without works,

_1 verse containing IMPUTES_

== IMPUTING

* `Hab 1:11` Then his mind shall change and he shall pass over and offend, *_imputing_* his power to his god."
* `2Co 5:19` Namely, that God was in Christ reconciling the world to himself, not *_imputing_* their trespasses to them, and has committed to us the word of reconciliation.

_2 verses containing IMPUTING_

== IMRAH

* `1Ch 7:36` The sons of Zophah: Suah, Harnepher, Shual, Beri, *_Imrah_*,

_1 verse containing IMRAH_

== IMRI

* `1Ch 9:4` Uthai the son of Ammihud, the son of Omri, the son of *_Imri_*, the son of Bani, of the children of Pharez the son of Judah.
* `Neh 3:2` And next to him the men of Jericho built. And next to them Zaccur the son of *_Imri_* built.

_2 verses containing IMRI_

== IN-GATHERING

* `Exo 23:16` And the feast of harvest, the first-fruits of your labors, which you have sown in the field; and the feast of *_in-gathering_*, which is at the end of the year, when you have gathered in your labors out of the field.
* `Exo 34:22` And you shall observe the feast of weeks with the first-fruits of wheat-harvest, and the feast of *_in-gathering_* at the year's end.

_2 verses containing IN-GATHERING_

== INCENSE

* `Exo 25:6` Oil for the light, spices for anointing oil and for sweet *_incense_*,
* `Exo 30:1` "And you shall make an altar to burn *_incense_* upon. Of shittim wood you shall make it.
* `Exo 30:7` And Aaron shall burn upon it sweet *_incense_* every morning. When he dresses the lamps, he shall burn *_incense_* upon it.
* `Exo 30:8` And when Aaron lights the lamps at evening, he shall burn *_incense_* upon it, a perpetual *_incense_* before the LORD throughout your generations.
* `Exo 30:9` You shall offer no strange *_incense_* upon it, nor burnt-sacrifice, nor food-offering, neither shall you pour drink-offering upon it.
* `Exo 30:27` The table and all its vessels, the candlestick and its vessels, the altar of *_incense_*,
* `Exo 31:8` The table and its vessels, the pure candlestick with all its vessels, the altar of *_incense_*,
* `Exo 31:11` And the anointing oil and sweet *_incense_* for the holy place. According to all that I have commanded you, they shall do."
* `Exo 35:8` Oil for the light, spices for anointing oil and for the sweet *_incense_*,
* `Exo 35:15` The *_incense_*-altar and its staffs; the anointing oil and the sweet *_incense_*; the hanging for the door at the entrance of the tabernacle;
* `Exo 35:28` And spice and oil for the light, for the anointing oil, and for the sweet *_incense_*.
* `Exo 37:25` And he made the *_incense_*-altar of shittim wood. Its length was a cubit and its breadth a cubit. It was square and two cubits was its height. Its horns were of the same.
* `Exo 37:29` And he made the holy anointing oil and the pure *_incense_* of sweet spices according to the work of the perfumer.
* `Exo 39:38` The golden altar, the anointing oil, and the sweet *_incense_*; the hanging for the tabernacle door;
* `Exo 40:5` And you shall set the altar of gold for the *_incense_* before the ark of the testimony and set up the hanging for the door of the tabernacle.
* `Exo 40:27` And he burnt sweet *_incense_* on it, as the LORD commanded Moses.
* `Lev 4:7` And the priest shall put some of the blood upon the horns of the altar of sweet *_incense_* before the LORD, which is in the Tabernacle of the Congregation, and shall pour all the blood of the bull at the bottom of the altar of the burnt-offering, which is at the door of the Tabernacle of the Congregation.
* `Lev 10:1` And Nadab and Abihu, the sons of Aaron, each took his censer, put fire in it, put *_incense_* on it, and offered strange fire before the LORD, which he did not command them.
* `Lev 16:12` And he shall take a censer full of burning coals of fire from off the altar before the LORD, and his hands full of sweet *_incense_* beaten small, and bring it within the veil.
* `Lev 16:13` And he shall put the *_incense_* upon the fire before the LORD, and the cloud of the *_incense_* shall cover the mercy-seat that is upon the testimony so that he will not die.
* `Num 4:16` "And to the office of Eleazar the son of Aaron the priest pertain the oil for the light, the sweet *_incense_*, the daily food-offering, the anointing oil, the oversight of all the tabernacle, and of all that is in it, in the sanctuary, and in its vessels."
* `Num 7:14` One spoon of ten shekels of gold, full of *_incense_*;
* `Num 7:20` One spoon of gold of ten shekels, full of *_incense_*;
* `Num 7:26` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:32` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:38` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:44` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:50` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:56` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:62` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:68` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:74` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:80` One golden spoon of ten shekels, full of *_incense_*;
* `Num 7:86` Twelve golden spoons full of *_incense_* weighing ten shekels apiece, after the shekel of the sanctuary; all the gold of the spoons was one hundred and twenty shekels;
* `Num 16:7` And put fire in them and put *_incense_* in them before the LORD tomorrow. And it shall be that the man whom the LORD chooses, he shall be holy. You take too much upon yourselves, you sons of Levi."
* `Num 16:17` And each take his censer and put *_incense_* in them, and each bring before the LORD his censer, two hundred and fifty censers—you and also Aaron, each his censer."
* `Num 16:18` And they each took his censer, put fire in them, laid *_incense_* on them, and stood in the door of the Tabernacle of the Congregation with Moses and Aaron.
* `Num 16:35` And a fire came out from the LORD and consumed the two hundred and fifty men who offered *_incense_*.
* `Num 16:40` To be a memorial to the children of Israel, so that no stranger who is not of the offspring of Aaron should come near to offer *_incense_* before the LORD and become like Korah and his company, as the LORD said to him by the hand of Moses.
* `Num 16:46` And Moses said to Aaron, "Take a censer and put fire in it from off the altar and put *_incense_* on it, and go quickly to the congregation and make an atonement for them, for wrath has gone out from the LORD. The plague has begun."
* `Num 16:47` And Aaron took as Moses commanded and ran into the midst of the congregation, and behold, the plague had begun among the people. And he put *_incense_* on it and made an atonement for the people.
* `Deu 33:10` They shall teach Jacob your judgments and Israel your law. They shall put *_incense_* before you and whole burnt sacrifice upon your altar.
* `1Sa 2:28` And did I choose him out of all the tribes of Israel to be my priest, to offer upon my altar, to burn *_incense_*, to wear an ephod before me? And did I give to the house of your father all the offerings made by fire of the children of Israel?
* `1Ki 3:3` And Solomon loved the LORD, walking in the statutes of David his father. Only he sacrificed and burnt *_incense_* in high places.
* `1Ki 9:25` And three times in a year Solomon offered burnt-offerings and peace-offerings upon the altar which he built to the LORD, and he burnt *_incense_* upon the altar that was before the LORD. So he finished the house.
* `1Ki 11:8` And he did likewise for all his foreign wives who burnt *_incense_* and sacrificed to their gods.
* `1Ki 12:33` So he offered upon the altar which he had made in Beth-el on the fifteenth day of the eighth month, even in the month which he had devised in his own heart. And he ordained a feast to the children of Israel and he offered upon the altar and burned *_incense_*.
* `1Ki 13:1` And behold, there came a man of God out of Judah by the word of the LORD to Beth-el. And Jeroboam stood by the altar to burn *_incense_*.
* `1Ki 13:2` And he cried against the altar in the word of the LORD and said, "O altar, altar, thus says the LORD: 'Behold, a child shall be born to the house of David, Josiah by name, and upon you he shall offer the priests of the high places who burn *_incense_* upon you, and men's bones shall be burnt upon you.'"
* `1Ki 22:43` And he walked in all the way of Asa his father. He did not turn aside from it, doing that which was right in the eyes of the LORD. Nevertheless, the high places were not taken away, and the people still offered and burnt *_incense_* in the high places.
* `2Ki 12:3` But the high places were not taken away. The people still sacrificed and burnt *_incense_* in the high places.
* `2Ki 14:4` But the high places were not taken away. The people still sacrificed and burnt *_incense_* on the high places.
* `2Ki 15:4` Except that the high places were not removed. The people still sacrificed and burnt *_incense_* on the high places.
* `2Ki 15:35` Yet the high places were not removed. The people still sacrificed and burned *_incense_* in the high places. He built the higher gate of the house of the LORD.
* `2Ki 16:4` And he sacrificed and burnt *_incense_* in the high places, on the hills, and under every green tree.
* `2Ki 17:11` And there they burnt *_incense_* on all the high places, as did the heathen whom the LORD carried away before them, and wrought wicked things to provoke the LORD to anger.
* `2Ki 18:4` He removed the high places, broke the images, cut down the groves, and broke in pieces the brazen serpent that Moses had made, for until those days the children of Israel burnt *_incense_* to it. And he called it Nehushtan.
* `2Ki 22:17` Because they have forsaken me and have burned *_incense_* to other gods that they might provoke me to anger with all the works of their hands, therefore my wrath shall be kindled against this place and shall not be quenched.'"
* `2Ki 23:5` And he put down the idolatrous priests whom the kings of Judah had ordained to burn *_incense_* in the high places in the cities of Judah and in the places around Jerusalem, those who burned *_incense_* to Baal, to the sun, to the moon, to the planets, and to all the host of heaven.
* `2Ki 23:8` And he brought all the priests out of the cities of Judah and defiled the high places where the priests had burned *_incense_*, from Geba to Beer-sheba, and broke down the high places of the gates that were in the entrance of the gate of Joshua the governor of the city, which were on a man's left hand at the gate of the city.
* `1Ch 6:49` But Aaron and his sons offered upon the altar of the burnt-offering and on the altar of *_incense_*, and were appointed for all the work of the holy of holies and to make an atonement for Israel, according to all that Moses the servant of God had commanded.
* `1Ch 23:13` The sons of Amram: Aaron and Moses. And Aaron was separated so that he should sanctify the most holy things—he and his sons forever—to burn *_incense_* before the LORD, to minister to him, and to bless in his name forever.
* `1Ch 28:18` And for the altar of *_incense_* he gave refined gold by weight. And he gave gold for the pattern of the chariot of the cherubim that spread out their wings and covered the ark of the covenant of the LORD.
* `2Ch 2:4` Behold, I build a house to the name of the LORD my God to dedicate it to him, to burn before him sweet *_incense_*, for the continual show-bread and for the burnt-offerings morning and evening, on the sabbaths, on the new moons, and on the solemn feasts of the LORD our God. This is an ordinance forever to Israel.
* `2Ch 13:11` And they burn to the LORD every morning and every evening burnt-sacrifices and sweet *_incense_*. They also set the show-bread in order upon the pure table and the candlestick of gold with its lamps to burn every evening. For we keep the charge of the LORD our God, but you have forsaken him.
* `2Ch 25:14` Now it came to pass, after Amaziah had come from the slaughter of the Edomites, that he brought the gods of the children of Seir, set them up to be his gods, bowed himself before them, and burned *_incense_* to them.
* `2Ch 26:16` But when he was strong, his heart was lifted up to his destruction, for he transgressed against the LORD his God and went into the temple of the LORD to burn *_incense_* upon the altar of *_incense_*.
* `2Ch 26:18` And they withstood Uzziah the king and said to him, "It does not belong to you, Uzziah, to burn *_incense_* to the LORD, but to the priests the sons of Aaron who are consecrated to burn *_incense_*. Go out of the sanctuary, for you have trespassed. It will not be for your honor from the LORD God."
* `2Ch 26:19` Then Uzziah was angry and had a censer in his hand to burn *_incense_*. And while he was angry with the priests, the leprosy even rose up in his forehead before the priests in the house of the LORD, from beside the *_incense_* altar.
* `2Ch 28:3` Moreover, he burnt *_incense_* in the valley of the son of Hinnom and burnt his children in the fire, after the abominations of the heathen whom the LORD had cast out before the children of Israel.
* `2Ch 28:4` He also sacrificed and burnt *_incense_* in the high places, on the hills, and under every green tree.
* `2Ch 28:25` And in every single city of Judah he made high places to burn *_incense_* to other gods and provoked to anger the LORD God of his fathers.
* `2Ch 29:7` Also, they have shut up the doors of the porch, put out the lamps, and have not burned *_incense_* nor offered burnt-offerings in the holy place to the God of Israel.
* `2Ch 29:11` My sons, do not be negligent now, for the LORD has chosen you to stand before him, to serve him, and that you should minister to him and burn *_incense_*."
* `2Ch 30:14` And they arose and took away the altars that were in Jerusalem, and all the altars for *_incense_* they took away and cast them into the brook Kidron.
* `2Ch 32:12` Has the same Hezekiah not taken away his high places and his altars and commanded Judah and Jerusalem, saying, "You shall worship before one altar and burn *_incense_* upon it"?
* `2Ch 34:25` Because they have forsaken me and have burned *_incense_* to other gods in order to provoke me to anger with all the works of their hands, therefore my wrath shall be poured out upon this place and shall not be quenched.'"'
* `Psa 66:15` I will offer to you burnt-sacrifices of fattened calves with the *_incense_* of rams. I will offer bulls with goats. [Selah.]
* `Psa 141:2` Let my prayer be set forth before you as *_incense_*, and the lifting up of my hands as the evening sacrifice.
* `Isa 1:13` Bring no more vain oblations. *_Incense_* is an abomination to me. The new moons and sabbaths, the calling of assemblies, I cannot endure. It is iniquity, even the solemn meeting.
* `Isa 43:23` You have not brought me the sheep of your burnt-offerings, neither have you honored me with your sacrifices. I have not caused you to serve with an offering, nor wearied you with *_incense_*.
* `Isa 60:6` The multitude of camels shall cover you, dromedaries of Midian and Ephah. All those from Sheba shall come. They shall bring gold and *_incense_* and show forth the praises of the LORD.
* `Isa 65:3` A people who provokes me to anger continually to my face, who sacrifices in gardens and burns *_incense_* upon altars of brick,
* `Isa 65:7` Your iniquities and the iniquities of your fathers together," says the LORD, "who have burned *_incense_* upon the mountains and blasphemed me upon the hills. Therefore, I will measure their former work into their bosom."
* `Isa 66:3` He who kills an ox is as if he slew a man. He who sacrifices a lamb is as if he cut off a dog's neck. He who offers an oblation is as if he offered swine's blood. He who burns *_incense_* is as if he blessed an idol. Indeed, they have chosen their own ways, and their soul delights in their abominations.
* `Jer 1:16` And I will utter my judgments against them touching all their wickedness, who have forsaken me, burned *_incense_* to other gods, and worshiped the works of their own hands.
* `Jer 6:20` For what purpose does *_incense_* come to me from Sheba and the sweet cane from a distant country? Your burnt-offerings are not acceptable, nor are your sacrifices sweet to me."
* `Jer 7:9` Will you steal, murder, commit adultery, swear falsely, burn *_incense_* to Baal, and walk after other gods whom you do not know,
* `Jer 11:12` Then the cities of Judah and inhabitants of Jerusalem shall go and cry to the gods to which they offer *_incense_*, but they shall not save them at all in the time of their trouble.
* `Jer 11:13` For according to the number of your cities were your gods, O Judah, and according to the number of the streets of Jerusalem you have set up altars to that shameful thing, even altars to burn *_incense_* to Baal.
* `Jer 11:17` For the LORD of hosts, who planted you, has pronounced evil against you for the evil of the house of Israel and of the house of Judah, which they have done against themselves to provoke me to anger in offering *_incense_* to Baal.
* `Jer 17:26` And they shall come from the cities of Judah, from the places around Jerusalem, from the land of Benjamin, from the plain, from the mountains, and from the south, bringing burnt-offerings, sacrifices, food-offerings, and *_incense_*, and bringing sacrifices of praise to the house of the LORD.
* `Jer 18:15` For my people have forgotten me and they have burned *_incense_* to vanity. And they have been made to stumble in their ways in the ancient paths, to walk in tracks, in a way not cast up,
* `Jer 19:4` Because they have forsaken me and have estranged this place and have burned *_incense_* in it to other gods, whom neither they nor their fathers have known, nor the kings of Judah, and have filled this place with the blood of innocents.
* `Jer 19:13` And the houses of Jerusalem and the houses of the kings of Judah shall be defiled like the place of Tophet, because of all the houses upon whose roofs they have burned *_incense_* to all the host of heaven and have poured out drink-offerings to other gods."'"
* `Jer 32:29` And the Chaldeans, who fight against this city, shall come and set this city on fire and burn it with the houses upon whose roofs they have offered *_incense_* to Baal and poured out drink-offerings to other gods to provoke me to anger.
* `Jer 41:5` That there came men from Shechem, from Shiloh, and from Samaria, even eighty men, having their beards shaved and their clothes rent and having cut themselves, with offerings and *_incense_* in their hand, to bring them to the house of the LORD.
* `Jer 44:3` Because of their wickedness which they have committed to provoke me to anger in that they went to burn *_incense_* and to serve other gods, whom they did not know—neither they, you, nor your fathers.
* `Jer 44:5` But they did not listen or incline their ear to turn from their wickedness and to burn no *_incense_* to other gods.
* `Jer 44:8` In that you provoke me to wrath with the works of your hands, burning *_incense_* to other gods in the land of Egypt where you have gone to dwell, so that you may cut yourselves off and that you may be a curse and a reproach among all the nations of the earth?
* `Jer 44:15` Then all the men who knew that their wives had burned *_incense_* to other gods and all the women who stood by, a great multitude, even all the people who dwelt in the land of Egypt, in Pathros, answered Jeremiah, saying,
* `Jer 44:17` But we will certainly do whatever thing proceeds from our own mouth, to burn *_incense_* to the queen of heaven and to pour out drink-offerings to her, as we have done—we, our fathers, our kings, and our princes—in the cities of Judah and in the streets of Jerusalem. For then we had plenty of provisions and were well and saw no evil.
* `Jer 44:18` But since we ceased to burn *_incense_* to the queen of heaven and to pour out drink-offerings to her, we have lacked all things and have been consumed by the sword and by the famine.
* `Jer 44:19` And when we burned *_incense_* to the queen of heaven and poured out drink-offerings to her, did we make for her cakes to worship her and pour out drink-offerings to her without our men?"
* `Jer 44:21` "The *_incense_* that you burned in the cities of Judah and in the streets of Jerusalem—you and your fathers, your kings and your princes, and the people of the land—did the LORD not remember them, and did it not come into his mind?
* `Jer 44:23` Because you have burned *_incense_* and because you have sinned against the LORD and have not obeyed the voice of the LORD, nor walked in his law, nor in his statutes, nor in his testimonies, therefore this evil has happened to you, as at this day."
* `Jer 44:25` Thus says the LORD of hosts, the God of Israel, saying, 'You and your wives have both spoken with your mouths and fulfilled with your hand, saying, "We will surely perform our vows that we have vowed, to burn *_incense_* to the queen of heaven and to pour out drink-offerings to her." You will surely accomplish your vows and surely perform your vows.'
* `Jer 48:35` Moreover, I will cause to cease in Moab," says the LORD, "him who offers in the high places and him who burns *_incense_* to his gods.
* `Ezk 8:11` And there stood before them seventy men of the elders of the house of Israel, and in the midst of them stood Jaazaniah the son of Shaphan, each with his censer in his hand, and a thick cloud of *_incense_* went up.
* `Ezk 16:18` And you have taken your embroidered garments and covered them, and you have set my oil and my *_incense_* before them.
* `Ezk 23:41` And sat upon a stately bed and a table prepared before it, upon which you have set my *_incense_* and my oil.
* `Hos 2:13` And I will visit upon her the days of Baalim, in which she burned *_incense_* to them and decked herself with her earrings and her jewels, and she went after her lovers and forgot me," says the LORD.
* `Hos 4:13` They sacrifice upon the tops of the mountains and burn *_incense_* upon the hills, under oaks, poplars, and elms, because their shade is agreeable. Therefore, your daughters shall be guilty of lewdness and your spouses shall commit adultery.
* `Hos 11:2` As they called them, so they went from them. They sacrificed to Baalim and burned *_incense_* to engraved images.
* `Hab 1:16` Therefore, they sacrifice to their net and burn *_incense_* to their dragnet, because by them their portion is fat and their food plenteous.
* `Mal 1:11` For from the rising of the sun even to the setting of the same, my name shall be great among the Gentiles, and in every place *_incense_* shall be offered to my name, even a pure offering, for my name shall be great among the heathen," says the LORD of hosts.
* `Luk 1:9` According to the custom of the priest's office, his lot was to burn *_incense_* when he went into the temple of the Lord.
* `Luk 1:10` And the whole multitude of the people were praying outside at the time of *_incense_*.
* `Luk 1:11` And there appeared to him an angel of the Lord standing on the right side of the altar of *_incense_*.
* `Rev 8:3` And another angel having a golden censer came and stood at the altar. And much *_incense_* was given to him so that he should offer it with the prayers of all saints upon the golden altar which was before the throne.
* `Rev 8:4` And the smoke of the *_incense_*, which came with the prayers of the saints, ascended before God out of the angel's hand.

_121 verses containing INCENSE_

== INCENSE-ALTAR

* `Exo 35:15` The *_incense-altar_* and its staffs; the anointing oil and the sweet incense; the hanging for the door at the entrance of the tabernacle;
* `Exo 37:25` And he made the *_incense-altar_* of shittim wood. Its length was a cubit and its breadth a cubit. It was square and two cubits was its height. Its horns were of the same.

_2 verses containing INCENSE-ALTAR_

== INCENSED

* `Isa 41:11` Behold, all those who were *_incensed_* against you shall be ashamed and confounded. They shall be as nothing. And those who contend with you shall perish.
* `Isa 45:24` Surely, one shall say, 'In the LORD I have righteousness and strength.' Even to him men shall come. And all who are *_incensed_* against him shall be ashamed.

_2 verses containing INCENSED_

== INCITE


_0 verses containing INCITE_

== INCITED

* `1Ch 21:1` And Satan stood up against Israel and *_incited_* David to number Israel.
* `2Co 9:2` For I know the forwardness of your mind, for which I boast about you to those of Macedonia that Achaia has been ready since last year. And your zeal has *_incited_* very many.

_2 verses containing INCITED_

== INCLINE

* `Jsh 24:23` "Now therefore," he said, "put away the strange gods which are among you and *_incline_* your heart to the LORD God of Israel."
* `1Ki 8:58` So that he may *_incline_* our hearts to him to walk in all his ways and to keep his commandments, his statutes, and his judgments which he commanded our fathers.
* `Psa 17:6` I have called upon you, for you will hear me, O God. *_Incline_* your ear to me and hear my speech.
* `Psa 45:10` Listen, O daughter. Consider, and *_incline_* your ear. Forget your own people and your father's house,
* `Psa 49:4` I will *_incline_* my ear to a parable. I will open my dark saying upon the harp.
* `Psa 71:2` Deliver me in your righteousness and cause me to escape. *_Incline_* your ear to me and save me.
* `Psa 78:1` [Maschil of Asaph.] Give ear, O my people, to my law. *_Incline_* your ear to the words of my mouth.
* `Psa 88:2` Let my prayer come before you. *_Incline_* your ear to my cry,
* `Psa 102:2` Do not hide your face from me in the day when I am in trouble. *_Incline_* your ear to me. In the day when I call, answer me speedily.
* `Psa 119:36` *_Incline_* my heart to your testimonies and not to covetousness.
* `Psa 141:4` Do not *_incline_* my heart to any evil thing or to practice wicked works with men who work iniquity. And do not let me eat their dainties.
* `Pro 2:2` So that you *_incline_* your ear to wisdom and apply your heart to understanding,
* `Pro 4:20` My son, attend to my words. *_Incline_* your ear to my sayings.
* `Isa 37:17` *_Incline_* your ear, O LORD, and hear. Open your eyes, O LORD, and see. And hear all the words of Sennacherib, who has sent to reproach the living God.
* `Isa 55:3` *_Incline_* your ear and come to me. Hear, and your soul shall live. And I will make an everlasting covenant with you, even the sure mercies of David.
* `Jer 7:24` But they did not listen, nor *_incline_* their ear, but walked in the counsels and in the imagination of their evil heart, and went backward and not forward.
* `Jer 7:26` Yet they did not listen to me nor *_incline_* their ear, but hardened their neck. They did worse than their fathers.
* `Jer 11:8` Yet they did not obey nor *_incline_* their ear, but each walked in the imagination of his evil heart. Therefore, I will bring upon them all the words of this covenant which I commanded them to do, but they did not do them.'"
* `Jer 17:23` But they did not obey nor *_incline_* their ear, but made their neck stiff so that they might not hear nor receive instruction.
* `Jer 34:14` "At the end of seven years each of you shall dismiss his brother, a Hebrew, who has been sold to you. And when he has served you six years, you shall let him go free from you." But your fathers did not listen to me or *_incline_* their ear.
* `Jer 44:5` But they did not listen or *_incline_* their ear to turn from their wickedness and to burn no incense to other gods.
* `Dan 9:18` O my God, *_incline_* your ear and hear. Open your eyes and behold our desolations and the city which is called by your name. For we do not present our supplications before you for our righteousnesses, but for your great mercies.

_22 verses containing INCLINE_

== INCLINED

* `Jdg 9:3` And his mother's brothers spoke all these words about him in the ears of all the men of Shechem. And their hearts *_inclined_* to follow Abimelech, for they said, "He is our brother."
* `1Sa 2:25` If one man sins against another, the judge shall judge him, but if a man sins against the LORD, who shall entreat for him?" Nevertheless, they did not listen to the voice of their father because the LORD was *_inclined_* to slay them.
* `Psa 40:1` [To the Chief Musician. A Psalm of David.] I waited patiently for the LORD, and he *_inclined_* to me and heard my cry.
* `Psa 116:2` Because he has *_inclined_* his ear to me, therefore I will call upon him as long as I live.
* `Psa 119:112` I have *_inclined_* my heart to perform your statutes always, even to the end.
* `Pro 5:13` And have not obeyed the voice of my teachers, nor *_inclined_* my ear to those who instructed me!
* `Jer 25:4` And the LORD has sent to you all his servants the prophets, rising early and sending them, but you have not listened nor *_inclined_* your ear to hear.
* `Jer 35:15` I have also sent to you all my servants the prophets, rising early and sending them, saying, 'Return each of you now from his evil way, amend your doings, and do not go after other gods to serve them, and you shall dwell in the land which I have given to you and to your fathers. But you have not *_inclined_* your ear nor listened to me.

_8 verses containing INCLINED_

== INCLINES

* `Pro 2:18` For her house *_inclines_* to death and her paths to the dead.

_1 verse containing INCLINES_

== INCLUDING

* `Mth 8:33` And those who kept them fled, went into the city, and told everything, *_including_* what had befallen to the men possessed with demons.
* `Luk 23:27` And there followed him a great company of people, *_including_* women who also bewailed and lamented him.

_2 verses containing INCLUDING_

== INCONTINENCE

* `1Co 7:5` Do not deprive one another, except with consent for a time, so that you may give yourselves to fasting and prayer. And come together again so that Satan may not tempt you for your *_incontinence_*.

_1 verse containing INCONTINENCE_

== INCORRUPTIBLE

* `Rom 1:23` And changed the glory of the *_incorruptible_* God into an image made like corruptible man, birds, four-footed beasts, and creeping animals.
* `1Co 9:25` And every man who strives for the mastery is temperate in all things. Now they do it to obtain a corruptible crown, but we an *_incorruptible_*.
* `1Co 15:52` In a moment, in the twinkling of an eye, at the last trumpet. For the trumpet shall sound, the dead shall be raised *_incorruptible_*, and we shall be changed.
* `1Pe 1:4` To an inheritance *_incorruptible_*, undefiled, and that does not fade away, reserved in heaven for you,
* `1Pe 1:23` Being born again, not of corruptible seed, but of *_incorruptible_*, by the word of God which lives and abides forever.

_5 verses containing INCORRUPTIBLE_

== INCORRUPTION

* `1Co 15:42` Thus also is the resurrection of the dead. It is sown in corruption, it is raised in *_incorruption_*.
* `1Co 15:50` Now this I say, brothers, that flesh and blood cannot inherit the kingdom of God, neither does corruption inherit *_incorruption_*.
* `1Co 15:53` For this corruptible must put on *_incorruption_* and this mortal must put on immortality.
* `1Co 15:54` So when this corruptible has put on *_incorruption_* and this mortal has put on immortality, the saying that is written shall be brought to pass: "Death is swallowed up in victory."

_4 verses containing INCORRUPTION_

== INCREASE

* `Gen 47:24` And it shall come to pass in the *_increase_*, that you shall give the fifth part to Pharaoh, and four parts shall be your own, for seed of the field, for your food, for those of your households, and for food for your little ones."
* `Lev 19:25` And in the fifth year you shall eat its fruit so that it may yield its *_increase_* to you. I am the LORD your God.
* `Lev 25:7` For your livestock, and for the beasts that are in your land. All of its *_increase_* shall be food.
* `Lev 25:12` For it is the jubilee. It shall be holy to you. You shall eat its *_increase_* out of the field.
* `Lev 25:16` According to the multitude of years you shall *_increase_* its price and according to the fewness of years you shall diminish its price, for according to the number of the years of the fruits he sells to you.
* `Lev 25:20` And if you say, "What shall we eat the seventh year? Behold, we shall not sow nor gather in our *_increase_*,"
* `Lev 25:36` Take no interest from him or *_increase_*, but fear your God so that your brother may live with you.
* `Lev 25:37` You shall not give him your money upon interest, nor lend him your food for *_increase_*.
* `Lev 26:4` Then I will give you rain in due season, and the land shall yield her *_increase_* and the trees of the field shall yield their fruit,
* `Lev 26:20` And your strength shall be spent in vain, for your land shall not yield her *_increase_*, neither shall the trees of the land yield their fruits.
* `Num 18:30` Therefore, you shall say to them, 'When you have offered its best from it, it shall be counted to the Levites as the *_increase_* of the threshing-floor and as the *_increase_* of the wine-press.
* `Num 32:14` And behold, you have risen up in your fathers' stead, an *_increase_* of sinful men, to further augment the fierce anger of the LORD toward Israel.
* `Deu 6:3` Hear therefore, O Israel, and observe to do it so that it may be well with you and that you may *_increase_* mightily, as the LORD God of your fathers has promised you, in the land that flows with milk and honey.
* `Deu 7:13` And he will love you, bless you, and multiply you. He will also bless your children, and the fruit of your land, your grain, your wine, and your oil, the *_increase_* of your cows, and the flocks of your sheep, in the land which he swore to your fathers to give you.
* `Deu 7:22` And the LORD your God will drive out those nations before you little by little. You may not consume them at once, lest the beasts of the field *_increase_* upon you.
* `Deu 14:22` "You shall truly tithe all the *_increase_* of your seed that the field brings forth year by year.
* `Deu 14:28` "At the end of three years you shall bring forth all the tithe of your *_increase_* the same year and shall lay it up within your gates.
* `Deu 16:15` Seven days you shall keep a solemn feast to the LORD your God in the place which the LORD chooses, because the LORD your God shall bless you in all your *_increase_* and in all the works of your hands; therefore, you shall surely rejoice.
* `Deu 26:12` "When you have made an end of tithing all the tithes of your *_increase_* the third year, which is the year of tithing, and have given it to the Levite, the stranger, the fatherless, and the widow, so that they may eat within your gates and be filled,
* `Deu 28:4` "Blessed shall be the fruit of your body, the fruit of your ground, the fruit of your livestock, the *_increase_* of your livestock, and the flocks of your sheep.
* `Deu 28:18` "Cursed shall be the fruit of your body, the fruit of your land, the *_increase_* of your cows, and the flocks of your sheep.
* `Deu 28:51` And he shall eat the fruit of your livestock and the fruit of your land until you are destroyed. He also shall not leave you either grain, wine, oil, the *_increase_* of your livestock, or flocks of your sheep until he has destroyed you.
* `Deu 32:13` He made him ride on the high places of the earth. He ate the *_increase_* of the fields. He nourished him with honey out of the rock, and oil out of the flinty rock,
* `Deu 32:22` For a fire is kindled in my anger, and shall burn to the lowest hell, consume the earth with her *_increase_*, and set on fire the foundations of the mountains.
* `Jdg 6:4` And they encamped against them and destroyed the *_increase_* of the earth as far as Gaza, and they left no sustenance for Israel, neither sheep, ox, or donkey.
* `Jdg 9:29` Oh that this people were under my hand! Then I would remove Abimelech." And he said to Abimelech, "*_Increase_* your army and come out."
* `1Sa 2:33` And the man of yours, whom I shall not cut off from my altar, is to consume your eyes and to grieve your heart. And all the *_increase_* of your house shall die in the flower of their age.
* `1Ch 27:23` But David did not take the number of them from twenty years old and under because the LORD had said he would *_increase_* Israel like the stars of the heavens.
* `1Ch 27:27` And over the vineyards was Shimei the Ramathite; and over the *_increase_* of the vineyards for the wine cellars was Zabdi the Shiphmite;
* `2Ch 31:5` And as soon as the commandment came abroad, the children of Israel brought in abundance the first-fruits of grain, wine, oil, honey, and of all the *_increase_* of the field. And the tithe of all things they brought in abundantly.
* `2Ch 32:28` And also store-houses for the *_increase_* of grain, wine, and oil, and stalls for all manner of beasts, and folds for flocks.
* `Ezr 10:10` And Ezra the priest stood up, and said to them, "You have transgressed and have taken foreign wives to *_increase_* the trespass of Israel.
* `Neh 9:37` And it yields much *_increase_* to the kings whom you have set over us because of our sins. They also have dominion over our bodies and over our livestock at their pleasure, and we are in great distress.
* `Job 8:7` Though your beginning was small, yet your latter end would greatly *_increase_*.
* `Job 10:17` You renew your witnesses against me and *_increase_* your indignation upon me. Changes and war are against me.
* `Job 20:28` The *_increase_* of his house shall depart, and his goods shall flow away in the day of his wrath.
* `Job 31:12` For it is a fire that consumes to destruction and would root out all my *_increase_*.
* `Psa 62:10` Do not trust in oppression, and do not become vain in robbery. If riches *_increase_*, do not set your heart upon them.
* `Psa 67:6` Then the earth shall yield her *_increase_*, and God, even our own God, will bless us.
* `Psa 71:21` You will *_increase_* my greatness and comfort me on every side.
* `Psa 73:12` Behold, these are the ungodly who prosper in the world. They *_increase_* in riches.
* `Psa 78:46` He also gave their *_increase_* to the ravaging-locust and their labor to the swarming-locust.
* `Psa 85:12` Indeed, the LORD will give that which is good, and our land shall yield her *_increase_*.
* `Psa 107:37` They sow the fields and plant vineyards, which yield fruits of *_increase_*.
* `Psa 115:14` The LORD will *_increase_* you more and more—you and your children.
* `Pro 1:5` A wise man will hear and will *_increase_* learning, and a man of understanding shall attain to wise counsels,
* `Pro 3:9` Honor the LORD with your substance and with the first-fruits of all your *_increase_*,
* `Pro 9:9` Give instruction to a wise man, and he will be wiser still. Teach a just man, and he will *_increase_* in learning.
* `Pro 13:11` Wealth gotten by vanity shall be diminished, but he who gathers by labor shall *_increase_*.
* `Pro 14:4` Where no oxen are, the manger is clean, but much *_increase_* is by the strength of the ox.
* `Pro 18:20` A man's belly shall be satisfied with the fruit of his mouth. And with the *_increase_* of his lips he shall be filled.
* `Pro 22:16` He who oppresses the poor to *_increase_* his riches, and he who gives to the rich, shall surely come to poverty.
* `Pro 28:28` When the wicked rise, men hide themselves, but when they perish, the righteous *_increase_*.
* `Ecc 5:10` He who loves silver shall not be satisfied with silver, nor he who loves abundance with *_increase_*. This is also vanity.
* `Ecc 5:11` When goods *_increase_*, they are increased who eat them. And what good is there to their owners, except the beholding of them with their eyes?
* `Ecc 6:11` Seeing there are many things that *_increase_* vanity, what is man the better?
* `Isa 9:7` Of the *_increase_* of his government and peace there shall be no end, upon the throne of David and upon his kingdom, to order it and to establish it with judgment and with justice from now on even forever. The zeal of the LORD of hosts will perform this.
* `Isa 29:19` The meek shall also *_increase_* their joy in the LORD, and the poor among men shall rejoice in the Holy One of Israel.
* `Isa 30:23` Then he shall give the rain of your seed, with which you shall sow the ground, and bread of the *_increase_* of the earth, and it shall be fat and plenteous. In that day your livestock shall feed in large pastures.
* `Jer 2:3` Israel was holiness to the LORD and the first-fruits of his *_increase_*. All who devour him shall offend. Evil shall come upon them," says the LORD.'"
* `Jer 23:3` "And I will gather the remnant of my flock from all countries where I have driven them and bring them back to their folds, and they shall be fruitful and *_increase_*.
* `Ezk 5:16` When I send upon them the evil arrows of famine, which shall be for their destruction and which I will send to destroy you, I will *_increase_* the famine upon you and will break your staff of bread.
* `Ezk 18:8` Has not given forth upon interest, neither has taken any *_increase_*, has withdrawn his hand from iniquity, has executed true judgment between man and man,
* `Ezk 18:13` Has given forth upon interest, and has taken *_increase_*, shall he then live? He shall not live. He has done all these abominations. He shall surely die. His blood shall be upon him.
* `Ezk 18:17` Who has taken off his hand from the poor, who has not received interest nor *_increase_*, has executed my judgments, and has walked in my statutes, he shall not die for the iniquity of his father. He shall surely live.
* `Ezk 22:12` In you they have taken gifts to shed blood. You have taken interest and *_increase_* and you have greedily gained from your neighbors by extortion, and have forgotten me," says the Lord GOD.
* `Ezk 34:27` And the tree of the field shall yield her fruit, and the earth shall yield her *_increase_*, and they shall be safe in their land. And they shall know that I am the LORD when I have broken the bars of their yoke and delivered them out of the hand of those who subjected them to service.
* `Ezk 36:11` And I will multiply upon you man and beast, and they shall *_increase_* and bring fruit. And I will settle you after your old states and will do better to you than at your beginnings. And you shall know that I am the LORD.
* `Ezk 36:29` I will also save you from all your uncleannesses. And I will call for the grain and *_increase_* it, and lay no famine upon you.
* `Ezk 36:30` And I will multiply the fruit of the tree and the *_increase_* of the field, so that you shall no longer receive reproach of famine among the heathen.
* `Ezk 36:37` 'Thus says the Lord GOD: "I will once again be inquired of by the house of Israel and do this for them: I will *_increase_* them with men like a flock.
* `Ezk 48:18` And the remainder in length over against the oblation of the holy portion shall be ten thousand eastward and ten thousand westward. And it shall be over against the oblation of the holy portion, and its *_increase_* shall be for food to those who serve the city.
* `Dan 11:39` He shall do so in the strongest fortresses with a strange god, whom he shall acknowledge and *_increase_* with glory. And he shall cause them to rule over many, and shall divide the land for gain.
* `Hos 4:10` For they shall eat and not have enough. They shall be guilty of lewdness and shall not *_increase_*, because they have ceased to take heed to the LORD.
* `Zch 8:12` 'For the seed shall be prosperous, the vine shall give her fruit, the ground shall give her *_increase_*, and the heavens shall give their dew, and I will cause the remnant of this people to possess all these things.
* `Zch 10:8` I will hiss for them and gather them, for I have redeemed them. And they shall *_increase_* as they have increased.
* `Luk 17:5` And the apostles said to the Lord, "*_Increase_* our faith."
* `Jhn 3:30` He must *_increase_*, but I must decrease.
* `1Co 3:6` I have planted, Apollos watered, but God has given the *_increase_*.
* `1Co 3:7` So then, neither he who plants nor he who waters is anything, but God who gives the *_increase_*.
* `2Co 9:10` Now may he who supplies "seed to the sower and bread for food," supply and multiply your seed for sowing and *_increase_* "the fruits of your righteousness,"
* `Eph 4:16` From whom the whole body properly joined together and united by that which every joint supplies, according to the effectual working in the measure of every part, makes *_increase_* of the body to the edifying of itself in love.
* `Col 2:19` And not holding the head, from which all the body, being supplied and knit together by joints and ligaments, increases with the *_increase_* of God.
* `1Th 3:12` And may the Lord make you to *_increase_* and abound in love toward one another and toward all men, even as we do toward you,
* `1Th 4:10` And indeed you do it toward all the brothers who are in all Macedonia. But we implore you, brothers, that you *_increase_* more and more,
* `2Ti 2:16` But shun profane and vain babblings, for they will *_increase_* to more ungodliness.

_86 verses containing INCREASE_

== INCREASED

* `Gen 7:17` And the flood was forty days upon the earth. And the waters *_increased_* and bore up the ark, and it was lifted above the earth.
* `Gen 7:18` And the waters prevailed and were *_increased_* greatly upon the earth, and the ark moved upon the face of the waters.
* `Gen 30:30` For it was little which you had before I came, and it is now *_increased_* to a multitude, and the LORD has blessed you since my coming. And now when shall I provide for my own house also?"
* `Gen 30:43` And the man *_increased_* exceedingly and had many flocks, women-servants, men-servants, camels, and donkeys.
* `Exo 1:7` And the children of Israel were fruitful, *_increased_* abundantly, multiplied, and became exceedingly mighty, and the land was filled with them.
* `Exo 23:30` Little by little I will drive them out from before you until you have *_increased_* and inherit the land.
* `Deu 8:13` And when your herds and your flocks multiply and your silver and your gold are *_increased_* and all that you have is *_increased_*,
* `1Sa 14:19` And it came to pass while Saul talked to the priest, that the noise that was in the host of the Philistines went on and *_increased_*. And Saul said to the priest, "Withdraw your hand."
* `2Sa 15:12` And Absalom sent for Ahithophel the Gilonite, David's counselor, from his city, even from Giloh, while he offered sacrifices. And the conspiracy was strong, for the people *_increased_* continually with Absalom.
* `1Ki 22:35` And the battle *_increased_* that day. And the king was stayed up in his chariot against the Syrians and died at evening. And the blood ran out of the wound into the midst of the chariot.
* `1Ch 4:38` These mentioned by their names were princes in their families, and the house of their fathers *_increased_* greatly.
* `1Ch 5:23` And the children of the half tribe of Manasseh dwelt in the land. They *_increased_* from Bashan to Baal-hermon and Senir and to mount Hermon.
* `2Ch 18:34` And the battle *_increased_* that day. Nevertheless, the king of Israel supported himself in his chariot against the Syrians until the evening. And about the time of the sunset he died.
* `Ezr 9:6` And said, "O my God, I am ashamed and blush to lift up my face to you, my God. For our iniquities have *_increased_* over our head, and our trespass has grown up to the heavens.
* `Job 1:10` Have you not made a hedge around him, around his house, and around all that he has on every side? You have blessed the work of his hands, and his substance has *_increased_* in the land.
* `Psa 4:7` You have put gladness in my heart, more than in the time when their grain and their wine *_increased_*.
* `Psa 44:12` You sell your people for nothing and have not *_increased_* your wealth by their price.
* `Psa 49:16` Do not be afraid when one is made rich, when the glory of his house is *_increased_*,
* `Psa 105:24` And he *_increased_* his people greatly and made them stronger than their enemies.
* `Pro 9:11` For by me your days shall be multiplied, and the years of your life shall be *_increased_*.
* `Ecc 2:9` Thus I was great and *_increased_* more than all who were before me in Jerusalem, and also my wisdom remained with me.
* `Ecc 5:11` When goods increase, they are *_increased_* who eat them. And what good is there to their owners, except the beholding of them with their eyes?
* `Isa 9:3` You have multiplied the nation. You have *_increased_* its joy. They joy before you according to the joy in harvest, and as men rejoice when they divide the plunder.
* `Isa 26:15` You have *_increased_* the nation, O LORD, you have *_increased_* the nation. You are glorified. You have enlarged all the borders of the land.
* `Isa 51:2` Look to Abraham your father and to Sarah who bore you, for I called him alone, blessed him, and *_increased_* him.
* `Isa 57:9` And you went to the king with ointment and *_increased_* your perfumes. You sent your messengers far off, and debased yourself even to hell.
* `Jer 3:16` And it shall come to pass when you are multiplied and *_increased_* in the land in those days," says the LORD, "that they shall no longer say, 'The ark of the covenant of the LORD,' neither shall it come to mind, neither shall they remember it, neither shall they visit it, neither shall that be done anymore.
* `Jer 5:6` Therefore, a lion from the forest shall slay them, a wolf of the evenings shall destroy them, a leopard shall watch over their cities. Everyone who goes out from there shall be torn in pieces because their transgressions are many and their backslidings have *_increased_*.
* `Jer 30:14` All your lovers have forgotten you. They do not seek you, for I have wounded you with the wound of an enemy, with the chastisements of a cruel one, for the multitude of your iniquity because your sins were *_increased_*.
* `Jer 30:15` Why do you cry for your affliction? Your sorrow is incurable for the multitude of your iniquity. Because your sins were *_increased_*, I have done these things to you.
* `Lam 2:5` [HE] The Lord was like an enemy. He has swallowed up Israel. He has swallowed up all her palaces. He has destroyed his strongholds and has *_increased_* in the daughter of Judah mourning and lamentation.
* `Ezk 16:7` I have caused you to multiply as the bud of the field, and you have *_increased_* and become great and have come to excellent ornaments. Your breasts are fashioned and your hair is grown, whereas you were naked and bare.
* `Ezk 23:14` So she *_increased_* her prostitutions, for when she saw men portrayed upon the wall, the images of the Chaldeans portrayed with vermilion,
* `Ezk 28:5` By your great wisdom and by your traffic you have *_increased_* your riches, and your heart is lifted up because of your riches."
* `Dan 12:4` But you, O Daniel, shut up the words and seal the book, even to the time of the end. Many shall run to and fro, and knowledge shall be *_increased_*."
* `Hos 4:7` As they were *_increased_*, so they sinned against me; therefore, I will change their glory into shame.
* `Amo 4:9` "I have smitten you with blight and mildew. When your gardens, your vineyards, your fig-trees, and your olive-trees *_increased_*, the cutting-locust devoured them. Yet you have not returned to me," says the LORD.
* `Zch 10:8` I will hiss for them and gather them, for I have redeemed them. And they shall increase as they have *_increased_*.
* `Mrk 4:8` And others fell on good ground and yielded fruit that sprang up, *_increased_*, and brought forth, some thirty-, some sixty-, and some one hundred-fold."
* `Luk 2:52` And Jesus *_increased_* in wisdom and stature and in favor with God and man.
* `Act 6:7` And the word of God *_increased_*, and the number of the disciples multiplied in Jerusalem greatly, and a great company of the priests were obedient to the faith.
* `Act 9:22` But Saul *_increased_* the more in strength and confounded the Jews who dwelt at Damascus, proving that this is the Christ.
* `Act 16:5` And so the churches were established in the faith and *_increased_* in number daily.
* `2Co 10:15` Not boasting of things beyond our measure, that is, of other men's labors, but having hope, when your faith is *_increased_*, that we shall be enlarged by you, according to our rule abundantly,
* `Rev 3:17` Because you say, 'I am rich and *_increased_* with goods and have need of nothing,' and do not know that you are wretched, miserable, poor, blind, and naked,

_45 verses containing INCREASED_

== INCREASES

* `Job 12:23` He *_increases_* nations and destroys them. He enlarges nations and diminishes them.
* `Psa 74:23` Do not forget the voice of your enemies. The tumult of those who rise against you *_increases_* continually.
* `Psa 107:41` Yet he sets the poor on high from affliction and *_increases_* their families like a flock.
* `Pro 11:24` There is one who scatters, and yet *_increases_*, and there is one who withholds more than is proper, but it tends to poverty.
* `Pro 16:21` The wise in heart shall be called prudent. And the sweetness of the lips *_increases_* learning.
* `Pro 23:28` She also lies in wait as for prey and *_increases_* the transgressors among men.
* `Pro 24:5` A wise man is strong, and a man of knowledge *_increases_* strength.
* `Pro 28:8` He who by usury and unjust gain *_increases_* his substance, he shall gather it for him who will pity the poor.
* `Pro 29:16` When the wicked are multiplied, transgression *_increases_*, but the righteous shall see their fall.
* `Ecc 1:18` For in much wisdom is much grief. And he who *_increases_* knowledge *_increases_* sorrow.
* `Isa 40:29` He gives power to the faint, and to those who have no might he *_increases_* strength.
* `Hab 2:6` Shall all these not take up a parable against him and a taunting proverb against him, and say, 'Woe to him who *_increases_* that which is not his and to him who lades himself with thick clay! How long?'
* `Col 2:19` And not holding the head, from which all the body, being supplied and knit together by joints and ligaments, *_increases_* with the increase of God.

_13 verses containing INCREASES_

== INCREASING

* `Col 1:10` So that you may walk worthy of the Lord, pleasing him in every way, being fruitful in every good work, and *_increasing_* in the knowledge of God,

_1 verse containing INCREASING_

== INCREDIBLE

* `Act 26:8` Why is it judged *_incredible_* with you if God raises the dead?

_1 verse containing INCREDIBLE_

== INCURABLE

* `2Ch 21:18` And after all this the LORD smote him in his bowels with an *_incurable_* disease.
* `Job 34:6` Should I lie against my right? My wound is *_incurable_* without transgression.'
* `Jer 15:18` Why is my pain perpetual and my wound *_incurable_*, which refuses to be healed? Will you be altogether to me as a liar and as waters that fail?
* `Jer 30:12` For thus says the LORD: 'Your bruise is *_incurable_* and your wound is grievous.
* `Jer 30:15` Why do you cry for your affliction? Your sorrow is *_incurable_* for the multitude of your iniquity. Because your sins were increased, I have done these things to you.
* `Mic 1:9` For her wound is *_incurable_*, and it has come to Judah. He has come to the gate of my people, even to Jerusalem.

_6 verses containing INCURABLE_

