= PAARAI - PARVAIM
:toc:

== PAARAI

* `2Sa 23:35` Hezrai the Carmelite, *_Paarai_* the Arbite,

_1 verse containing PAARAI_

== PACES

* `2Sa 6:13` And it was so, that when those who bore the ark of the LORD had gone six *_paces_*, he sacrificed oxen and fattened calves.

_1 verse containing PACES_

== PACIFIED

* `Est 7:10` So they hanged Haman on the gallows that he had prepared for Mordecai. Then the king's wrath was *_pacified_*.
* `Ezk 16:63` So that you may remember and be confounded and never open your mouth anymore because of your shame, when I am *_pacified_* toward you for all that you have done," says the Lord GOD.

_2 verses containing PACIFIED_

== PACIFIES

* `Pro 21:14` A gift in secret *_pacifies_* anger, and a reward in the bosom, strong wrath.
* `Ecc 10:4` If the spirit of the ruler rises against you, do not leave your place, for yielding *_pacifies_* great offenses.

_2 verses containing PACIFIES_

== PACIFY

* `Pro 16:14` The wrath of a king is as messengers of death, but a wise man will *_pacify_* it.

_1 verse containing PACIFY_

== PADAN

* `Gen 25:20` And Isaac was forty years old when he took Rebekah to be his wife, the daughter of Bethuel the Syrian of *_Padan_*-aram, the sister to Laban the Syrian.
* `Gen 28:2` Arise, go to *_Padan_*-aram, to the house of Bethuel your mother's father, and take for yourself from there a wife from the daughters of Laban your mother's brother.
* `Gen 28:5` And Isaac sent away Jacob. And he went to *_Padan_*-aram, to Laban, son of Bethuel the Syrian, the brother of Rebekah, Jacob's and Esau's mother.
* `Gen 28:6` When Esau saw that Isaac had blessed Jacob and sent him away to *_Padan_*-aram to take for himself a wife from there, and that as he blessed him, he gave him a charge, saying, "You shall not take a wife from the daughters of Canaan,"
* `Gen 28:7` And that Jacob obeyed his father and his mother and had gone to *_Padan_*-aram,
* `Gen 31:18` And he carried away all his livestock and all his goods which he had gained, his own livestock which he had gained in *_Padan_*-aram, to go to Isaac his father in the land of Canaan.
* `Gen 33:18` And Jacob came to Shalem, a city of Shechem, which is in the land of Canaan, when he came from *_Padan_*-aram, and pitched his tent before the city.
* `Gen 35:9` And God appeared to Jacob again when he came out of *_Padan_*-aram, and he blessed him.
* `Gen 35:26` And the sons of Zilpah, Leah's servant: Gad and Asher. These are the sons of Jacob who were born to him in *_Padan_*-aram.
* `Gen 46:15` These are the sons of Leah, which she bore to Jacob in *_Padan_*-aram, with his daughter Dinah. All the souls of his sons and his daughters were thirty-three.
* `Gen 48:7` And as for me, when I came from *_Padan_*, Rachel died beside me in the land of Canaan, on the way when there was only a little distance to come to Ephrath, and I buried her there on the way of Ephrath (the same is Beth-lehem)."

_11 verses containing PADAN_

== PADAN-ARAM

* `Gen 25:20` And Isaac was forty years old when he took Rebekah to be his wife, the daughter of Bethuel the Syrian of *_Padan-aram_*, the sister to Laban the Syrian.
* `Gen 28:2` Arise, go to *_Padan-aram_*, to the house of Bethuel your mother's father, and take for yourself from there a wife from the daughters of Laban your mother's brother.
* `Gen 28:5` And Isaac sent away Jacob. And he went to *_Padan-aram_*, to Laban, son of Bethuel the Syrian, the brother of Rebekah, Jacob's and Esau's mother.
* `Gen 28:6` When Esau saw that Isaac had blessed Jacob and sent him away to *_Padan-aram_* to take for himself a wife from there, and that as he blessed him, he gave him a charge, saying, "You shall not take a wife from the daughters of Canaan,"
* `Gen 28:7` And that Jacob obeyed his father and his mother and had gone to *_Padan-aram_*,
* `Gen 31:18` And he carried away all his livestock and all his goods which he had gained, his own livestock which he had gained in *_Padan-aram_*, to go to Isaac his father in the land of Canaan.
* `Gen 33:18` And Jacob came to Shalem, a city of Shechem, which is in the land of Canaan, when he came from *_Padan-aram_*, and pitched his tent before the city.
* `Gen 35:9` And God appeared to Jacob again when he came out of *_Padan-aram_*, and he blessed him.
* `Gen 35:26` And the sons of Zilpah, Leah's servant: Gad and Asher. These are the sons of Jacob who were born to him in *_Padan-aram_*.
* `Gen 46:15` These are the sons of Leah, which she bore to Jacob in *_Padan-aram_*, with his daughter Dinah. All the souls of his sons and his daughters were thirty-three.

_10 verses containing PADAN-ARAM_

== PADDLE

* `Deu 23:13` And you shall have a *_paddle_* upon your weapon, and it shall be when you relieve yourself abroad, that you shall dig with it and turn back and cover that which comes from you.

_1 verse containing PADDLE_

== PADON

* `Ezr 2:44` The children of Keros, the children of Siaha, the children of *_Padon_*,
* `Neh 7:47` The children of Keros, the children of Sia, the children of *_Padon_*,

_2 verses containing PADON_

== PAGIEL

* `Num 1:13` Of Asher, *_Pagiel_* the son of Ocran;
* `Num 2:27` And those who encamp by him shall be the tribe of Asher, and the captain of the children of Asher shall be *_Pagiel_* the son of Ocran.
* `Num 7:72` On the eleventh day *_Pagiel_* the son of Ocran, prince of the children of Asher, offered.
* `Num 7:77` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of *_Pagiel_* the son of Ocran.
* `Num 10:26` And over the host of the tribe of the children of Asher was *_Pagiel_* the son of Ocran.

_5 verses containing PAGIEL_

== PAHATH-MOAB

* `Ezr 2:6` The children of *_Pahath-moab_*, of the children of Jeshua and Joab, two thousand eight hundred and twelve;
* `Ezr 8:4` Of the sons of *_Pahath-moab_*: Elihoenai the son of Zerahiah, and with him two hundred males.
* `Ezr 10:30` And of the sons of *_Pahath-moab_*: Adna, Chelal, Benaiah, Maaseiah, Mattaniah, Bezaleel, Binnui, and Manasseh.
* `Neh 3:11` Malchijah the son of Harim and Hashub the son of *_Pahath-moab_* repaired the other piece and the tower of the furnaces.
* `Neh 7:11` The children of *_Pahath-moab_*, of the children of Jeshua and Joab, two thousand eight hundred and eighteen;
* `Neh 10:14` The chief of the people: Parosh, *_Pahath-moab_*, Elam, Zatthu, Bani,

_6 verses containing PAHATH-MOAB_

== PAI

* `1Ch 1:50` And when Baal-hanan was dead, Hadad reigned in his stead, and the name of his city was *_Pai_*. And his wife's name was Mehetabel, the daughter of Matred, the daughter of Mezahab.

_1 verse containing PAI_

== PAID

* `Ezr 4:20` There have also been mighty kings over Jerusalem, who have ruled over all countries beyond the river, and toll, tribute, and custom was *_paid_* to them.
* `Ezr 6:8` Moreover, I make a decree as to what you shall do to the elders of these Jews for the building of this house of God: that from the king's goods, even from the tribute beyond the river, expenses are to be *_paid_* to these men immediately so that they are not hindered,
* `Pro 7:14` "I have peace-offerings with me. This day I have *_paid_* my vows.
* `Jna 1:3` But Jonah arose to flee to Tarshish from the presence of the LORD and went down to Joppa, and he found a ship going to Tarshish. So he *_paid_* its fare and went down into it to go with them to Tarshish from the presence of the LORD.
* `Mth 5:26` Truly, I say to you, you shall by no means come out from there until you have *_paid_* the uttermost quadrans.
* `Luk 12:59` I tell you, you shall not depart from there until you have *_paid_* the very last mite."

_6 verses containing PAID_

== PAILS

* `Job 21:24` His *_pails_* are full of milk and his bones are moistened with marrow.

_1 verse containing PAILS_

== PAIN

* `Job 14:22` But his flesh upon him shall have *_pain_*, and his soul within him shall mourn."
* `Job 15:20` The wicked man travails with *_pain_* all his days, and the number of years is hidden to the oppressor.
* `Job 33:19` He is chastened also with *_pain_* upon his bed, and the multitude of his bones with strong *_pain_*,
* `Psa 25:18` [TSADI] Look upon my affliction and my *_pain_*, and forgive all my sins.
* `Psa 48:6` Fear took hold upon them there, and *_pain_*, as of a woman in travail.
* `Isa 13:8` And they shall be afraid. Pangs and sorrows shall take hold of them. They shall be in *_pain_* like a woman who travails. They shall be amazed at one another. Their faces shall be as flames.
* `Isa 21:3` Therefore, my loins are filled with *_pain_*. Pangs have taken hold upon me like the pangs of a woman who travails. I was bowed down when I heard it. I was dismayed when I saw it.
* `Isa 26:17` As a woman with child, who draws near the time of her delivery, is in *_pain_* and cries out in her pangs, so we have been in your sight, O LORD.
* `Isa 26:18` We have been with child. We have been in *_pain_*. We have, it seems, brought forth wind. We have not wrought any deliverance on the earth, neither have the inhabitants of the world fallen.
* `Isa 66:7` Before she travailed, she brought forth. Before her *_pain_* came, she had delivered a male child.
* `Jer 6:24` We have heard its fame. Our hands become feeble. Anguish has taken hold of us, and *_pain_*, as of a woman in travail.
* `Jer 12:13` They have sown wheat, but shall reap thorns. They have put themselves to *_pain_*, but shall not profit. And they shall be ashamed of your revenues because of the fierce anger of the LORD."
* `Jer 15:18` Why is my *_pain_* perpetual and my wound incurable, which refuses to be healed? Will you be altogether to me as a liar and as waters that fail?
* `Jer 22:23` O inhabitant of Lebanon, who makes your nest in the cedars, how gracious you shall be when pangs come upon you, the *_pain_* as of a woman in travail!
* `Jer 30:23` Behold, the whirlwind of the LORD goes forth with fury, a continuing whirlwind. It shall fall with *_pain_* upon the head of the wicked.
* `Jer 51:8` Babylon is suddenly fallen and destroyed. Howl for her. Take balm for her *_pain_*. It may be that she may be healed.
* `Ezk 30:4` And the sword shall come upon Egypt and great *_pain_* shall be in Cush when the slain fall in Egypt and they take away her multitude and her foundations are broken down.
* `Ezk 30:9` In that day messengers shall go forth from me in ships to make the careless Cushites afraid, and great *_pain_* shall come upon them, as in the day of Egypt, for behold, it comes."
* `Ezk 30:16` And I will set fire in Egypt. Sin shall have great *_pain_*, No shall be rent apart, and Noph shall have distresses daily.
* `Mic 4:10` Be in *_pain_* and labor to bring forth, O daughter of Zion, like a woman in travail. For now you shall go forth from the city and you shall dwell in the field, and you shall go even to Babylon. There you shall be delivered. There the LORD shall redeem you from the hand of your enemies.
* `Nah 2:10` She is empty, void, and waste. And the heart melts, the knees smite together, much *_pain_* is in all loins, and all of their faces gather blackness.
* `Rom 8:22` For we know that the whole creation groans and travails in *_pain_* together until now.
* `Rev 12:2` And she was with child and she cried out, travailing in birth and in *_pain_* to deliver.
* `Rev 16:10` And the fifth angel poured out his vial upon the seat of the beast, and his kingdom was full of darkness. And they gnawed their tongues because of the *_pain_*
* `Rev 21:4` And God will wipe away all tears from their eyes, and there shall be no more death, neither sorrow, nor crying, neither shall there be any more *_pain_*, because the former things have passed away."

_25 verses containing PAIN_

== PAINED

* `Psa 55:4` My heart is severely *_pained_* within me, and the terrors of death have fallen upon me.
* `Isa 23:5` As at the report concerning Egypt, so they shall be sorely *_pained_* at the report of Tyre.
* `Jer 4:19` My anguish, my anguish! I am *_pained_* at my very heart. My heart makes a noise in me. I cannot hold my peace because you have heard, O my soul, the sound of the trumpet, the alarm of war.
* `Joe 2:6` Before their face the people shall be much *_pained_*. All faces shall gather blackness.

_4 verses containing PAINED_

== PAINFUL

* `Psa 73:16` When I thought to know this, it was too *_painful_* for me,

_1 verse containing PAINFUL_

== PAINFULNESS

* `2Co 11:27` In weariness and *_painfulness_*, in watchings often, in hunger and thirst, in fastings often, in cold and nakedness.

_1 verse containing PAINFULNESS_

== PAINS

* `1Sa 4:19` And his daughter-in-law, the wife of Phinehas, was with child and about to deliver. And when she heard the tidings that the ark of God was taken and that her father-in-law and her husband were dead, she bowed herself and travailed, for her *_pains_* came upon her.
* `Psa 116:3` The sorrows of death encompassed me, and the *_pains_* of hell came upon me. I found trouble and sorrow.
* `Act 2:24` Whom God has raised up, having released him from the *_pains_* of death, because it was not possible that he should be held by it.
* `Rev 16:11` And blasphemed the God of heaven because of their *_pains_* and their sores. And they did not repent of their deeds.

_4 verses containing PAINS_

== PAINTED

* `2Ki 9:30` And when Jehu had come to Jezreel, Jezebel heard of it. And she *_painted_* her face, adorned her head, and looked out a window.
* `Jer 22:14` Who says, 'I will build myself a wide house and large chambers,' and cuts out windows for himself, and it is ceiled with cedar and *_painted_* with vermilion.
* `Ezk 23:40` "And furthermore, you have even sent for men to come from far, to whom a messenger was sent, and behold, they came. For them you washed yourself, *_painted_* your eyes, decked yourself with ornaments,

_3 verses containing PAINTED_

== PAINTING

* `Jer 4:30` And when you are laid waste, what will you do? Though you clothe yourself with crimson, though you deck yourself with ornaments of gold, though you rend your face with *_painting_*, in vain you shall make yourself fair. Your lovers will despise you. They will seek your life.

_1 verse containing PAINTING_

== PAIR

* `Amo 2:6` Thus says the LORD: "For three transgressions of Israel, and for four, I will not turn away their punishment, because they sold the righteous for silver and the poor for a *_pair_* of shoes.
* `Amo 8:6` So that we may buy the poor for silver and the needy for a *_pair_* of shoes, and even sell the refuse of the wheat?'"
* `Luk 2:24` And to offer a sacrifice according to that which is said in the law of the Lord: "A *_pair_* of turtle-doves, or two young pigeons."
* `Rev 6:5` And when he had opened the third seal, I heard the third living being say, "Come and see." And I beheld, and behold, a black horse. And he who sat on him had a *_pair_* of balances in his hand.

_4 verses containing PAIR_

== PALACE

* `1Ki 16:18` And it came to pass, when Zimri saw that the city was taken, that he went into the *_palace_* of the king's house and burnt the king's house over him with fire and died,
* `1Ki 21:1` And it came to pass after these things, that Naboth the Jezreelite had a vineyard which was in Jezreel, next to the *_palace_* of Ahab king of Samaria.
* `2Ki 15:25` But Pekah the son of Remaliah, a captain of his, conspired against him and smote him in Samaria at the *_palace_* of the king's house, with Argob and Arieh. Fifty men of the Gileadites were with him. And he killed him and reigned in his stead.
* `2Ki 20:18` 'And of your sons who shall issue from you, which you shall beget, they shall take away, and they shall be eunuchs in the *_palace_* of the king of Babylon.'"
* `1Ch 29:1` Furthermore, David the king said to all the congregation, "Solomon my son, whom alone God has chosen, is yet young and tender, and the work is great, for the *_palace_* is not for man, but for the LORD God.
* `1Ch 29:19` And give to Solomon my son a perfect heart to keep your commandments, your testimonies, and your statutes, and to do all these things and to build the *_palace_* for which I have made provision."
* `2Ch 9:11` And the king made terraces from the algum trees for the house of the LORD and for the king's *_palace_*, and harps and psalteries for singers. And there were none such seen before in the land of Judah.
* `Ezr 4:14` Now because we eat the salt of the *_palace_*, and it was not proper for us to see the king's dishonor, therefore we have sent and informed the king,
* `Ezr 6:2` And a scroll was found at Achmetha in the *_palace_* that is in the province of the Medes, and in it was a record thus written:
* `Neh 1:1` [The words of Nehemiah the son of Hachaliah.] And it came to pass in the month Chisleu, in the twentieth year, as I was in the *_palace_* of Shushan,
* `Neh 2:8` And a letter to Asaph the keeper of the king's forest so that he may give me timber to make beams for the gates of the *_palace_* which belonged to the house, for the wall of the city, and for the house that I shall enter." And the king granted me, according to the good hand of my God upon me.
* `Neh 7:2` That I gave my brother Hanani and Hananiah the ruler of the *_palace_* charge over Jerusalem, for he was a faithful man and feared God above many.
* `Est 1:2` That in those days, when king Ahasuerus sat on the throne of his kingdom, which was in the *_palace_* of Shushan,
* `Est 1:5` And when these days had expired, the king held a feast for seven days for all the people who were present in the *_palace_* of Shushan, both for great and small, in the court of the garden of the king's *_palace_*
* `Est 2:3` And let the king appoint officers in all the provinces of his kingdom so that they may collect all the fair young virgins to the *_palace_* of Shushan to the house of the women, into the custody of Hege the king's chamberlain, keeper of the women. And let their things for purification be given to them.
* `Est 2:5` Now in the *_palace_* of Shushan there was a certain Jew, whose name was Mordecai, the son of Jair, the son of Shimei, the son of Kish, a Benjaminite,
* `Est 2:8` So it came to pass when the king's commandment and his decree were heard and when many young women were assembled at the *_palace_* of Shushan to the custody of Hegai, that Esther was brought also to the king's house to the custody of Hegai, keeper of the women.
* `Est 3:15` The posts departed, being hastened by the king's commandment, and the decree was given in the *_palace_* of Shushan. And the king and Haman sat down to drink, but the city of Shushan was perplexed.
* `Est 7:7` And the king arose from the banquet of wine in his wrath and went into the *_palace_*-garden. And Haman stood up to make request for his life to Esther the queen, for he saw that there was evil determined against him by the king.
* `Est 7:8` Then the king returned out of the *_palace_*-garden into the place of the banquet of wine, and Haman had fallen upon the couch on which Esther was. Then the king said, "Will he force the queen also before me in the house?" As the word went out of the king's mouth, they covered Haman's face.
* `Est 8:14` So the posts who rode upon royal horses went out, being hastened and pressed on by the king's commandment. And the decree was given at the *_palace_* of Shushan.
* `Est 9:6` And in the *_palace_* of Shushan the Jews slew and destroyed five hundred men.
* `Est 9:11` On that day the number of those who were slain in the *_palace_* of Shushan was brought before the king.
* `Est 9:12` And the king said to Esther the queen, "The Jews have slain and destroyed five hundred men in the *_palace_* of Shushan and the ten sons of Haman. What have they done in the rest of the king's provinces? Now what is your petition? It shall be granted to you. Or what is your request further? It shall be done."
* `Psa 45:15` With gladness and rejoicing they shall be brought. They shall enter into the king's *_palace_*.
* `Psa 144:12` So that our sons may be like plants grown up in their youth; so that our daughters may be like corner stones, polished after the similitude of a *_palace_*;
* `Sos 8:9` If she is a wall, we will build upon her a *_palace_* of silver. And if she is a door, we will enclose her with boards of cedar.
* `Isa 25:2` For you have made a city into a heap, a fortified city into a ruin, a *_palace_* of strangers to be no city. It shall never be built.
* `Isa 39:7` 'And of your sons who shall issue from you, which you shall beget, they shall take away and they shall be eunuchs in the *_palace_* of the king of Babylon.'"
* `Jer 30:18` Thus says the LORD: 'Behold, I will bring back the captivity of Jacob's tents and have mercy on his dwelling places, and the city shall be built upon her own heap, and the *_palace_* shall remain after its manner.
* `Dan 1:4` Children in whom there was no blemish, but of good appearance, skillful in all wisdom, intelligent in knowledge, understanding science, and those who had ability in them to stand in the king's *_palace_*, and whom they might teach the writing and the language of the Chaldeans.
* `Dan 4:4` "I, Nebuchadnezzar, was at rest in my house and flourishing in my *_palace_*.
* `Dan 4:29` At the end of twelve months he walked in the *_palace_* of the kingdom of Babylon.
* `Dan 5:5` In the same hour fingers of a man's hand came forth and wrote over against the candlestick upon the plaster of the wall of the king's *_palace_*. And the king saw the part of the hand that wrote.
* `Dan 6:18` Then the king went to his *_palace_* and passed the night fasting, neither were instruments of music brought before him. And his sleep went from him.
* `Dan 8:2` And I saw in a vision, and it came to pass when I saw, that I was at Shushan in the *_palace_*, which is in the province of Elam. And I saw in a vision that I was by the Ulai River.
* `Dan 11:45` And he shall plant the tabernacles of his *_palace_* between the seas in the glorious holy mountain. Yet he shall come to his end, and no one shall help him."
* `Amo 4:3` And you shall go out at the breaches, every cow at that which is before her, and you shall cast them into the *_palace_*," says the LORD.
* `Nah 2:6` The gates of the rivers shall be opened, and the *_palace_* shall be dissolved.
* `Mth 26:3` Then the chief priests, the scribes, and the elders of the people assembled in the *_palace_* of the high priest, who was called Caiaphas,
* `Mth 26:58` But Peter followed him at a distance to the high priest's *_palace_*, went in, and sat with the servants to see the end.
* `Mth 26:69` Now Peter sat outside in the *_palace_*. And a woman-servant came to him, saying, "You were also with Jesus of Galilee."
* `Mrk 14:54` And Peter followed him at a distance, even into the *_palace_* of the high priest, and he sat with the servants and warmed himself at the fire.
* `Mrk 14:66` And as Peter was below in the *_palace_*, there comes one of the women-servants of the high priest.
* `Luk 11:21` When a strong armed man keeps his *_palace_*, his goods are in peace.
* `Jhn 18:15` And Simon Peter followed Jesus, and so did another disciple. Since that disciple was known to the high priest, he entered with Jesus into the *_palace_* of the high priest.

_46 verses containing PALACE_

== PALACE-GARDEN

* `Est 7:7` And the king arose from the banquet of wine in his wrath and went into the *_palace-garden_*. And Haman stood up to make request for his life to Esther the queen, for he saw that there was evil determined against him by the king.
* `Est 7:8` Then the king returned out of the *_palace-garden_* into the place of the banquet of wine, and Haman had fallen upon the couch on which Esther was. Then the king said, "Will he force the queen also before me in the house?" As the word went out of the king's mouth, they covered Haman's face.

_2 verses containing PALACE-GARDEN_

== PALACES

* `2Ch 36:19` And they burnt the house of God, broke down the wall of Jerusalem, burnt all its *_palaces_* with fire, and destroyed all its precious vessels.
* `Psa 45:8` All your garments smell of myrrh, aloes, and cassia. Out of the ivory *_palaces_* stringed instruments have made you glad.
* `Psa 48:3` God is known in her *_palaces_* as a refuge.
* `Psa 48:13` Mark well her bulwarks, and consider her *_palaces_* so that you may tell it to the generation following.
* `Psa 78:69` And he built his sanctuary like high *_palaces_*, like the earth which he has established forever.
* `Psa 122:7` May peace be within your walls and prosperity within your *_palaces_*.
* `Pro 30:28` The spider takes hold with her hands and is in kings' *_palaces_*.
* `Isa 13:22` And the wolves shall cry in their desolate houses, and jackals in their pleasant *_palaces_*. And her time is near to come, and her days shall not be prolonged.
* `Isa 23:13` Behold the land of the Chaldeans. This people was not, until the Assyrian founded it for those who dwell in the wilderness. They set up its towers, they raised up its *_palaces_*, and they brought it to ruin.
* `Isa 32:14` For the *_palaces_* shall be forsaken, the multitude of the city shall be left, the forts and towers shall be for dens forever, a joy of wild donkeys, a pasture of flocks,
* `Isa 34:13` And thorns shall come up in her *_palaces_*, nettles and brambles in her fortresses, and it shall be a habitation of jackals and a court for owls.
* `Jer 6:5` Arise, and let us go by night and destroy her *_palaces_*."
* `Jer 9:21` For death has come up into our windows and has entered into our *_palaces_* to cut off the children from outside and the young men from the streets.
* `Jer 17:27` But if you will not listen to me to hallow the sabbath day and to bear no burdens while entering at the gates of Jerusalem on the sabbath day, then I will kindle a fire in its gates, and it shall devour the *_palaces_* of Jerusalem and shall not be quenched."'"
* `Jer 49:27` "And I will kindle a fire in the wall of Damascus, and it shall consume the *_palaces_* of Ben-hadad."
* `Lam 2:5` [HE] The Lord was like an enemy. He has swallowed up Israel. He has swallowed up all her *_palaces_*. He has destroyed his strongholds and has increased in the daughter of Judah mourning and lamentation.
* `Lam 2:7` [ZAYIN] The Lord has cast off his altar. He has abhorred his sanctuary. He has given up into the hand of the enemy the walls of her *_palaces_*. They have made a noise in the house of the LORD as in the day of a solemn feast.
* `Ezk 19:7` And he knew their desolate *_palaces_*, and he laid waste their cities. And the land and its fullness was desolate by the noise of his roaring.
* `Ezk 25:4` Therefore behold, I will deliver you to the men of the east for a possession, and they shall set their *_palaces_* in you and make their dwellings in you. They shall eat your fruit and they shall drink your milk.
* `Hos 8:14` For Israel has forgotten his Maker and builds temples, and Judah has multiplied fortified cities. But I will send a fire upon his cities, and it shall devour the *_palaces_* thereof."
* `Amo 1:4` But I will send a fire into the house of Hazael which shall devour the *_palaces_* of Ben-hadad.
* `Amo 1:7` But I will send a fire on the wall of Gaza which shall devour its *_palaces_*.
* `Amo 1:10` But I will send a fire on the wall of Tyre which shall devour its *_palaces_*."
* `Amo 1:12` But I will send a fire upon Teman which shall devour the *_palaces_* of Bozrah."
* `Amo 1:14` But I will kindle a fire in the wall of Rabbah, and it shall devour its *_palaces_*, with shouting in the day of battle, with a tempest in the day of the whirlwind.
* `Amo 2:2` But I will send a fire upon Moab, and it shall devour the *_palaces_* of Kirioth. And Moab shall die with tumult, with shouting, and with the sound of the trumpet.
* `Amo 2:5` But I will send a fire upon Judah, and it shall devour the *_palaces_* of Jerusalem."
* `Amo 3:9` Publish in the *_palaces_* at Ashdod and in the *_palaces_* in the land of Egypt, and say, "Assemble yourselves upon the mountains of Samaria, and behold the great tumults in the midst of it and the oppressed in the midst of it."
* `Amo 3:10` "For they do not know to do right," says the LORD, "who store up violence and robbery in their *_palaces_*."
* `Amo 3:11` Therefore, thus says the Lord GOD: "There shall even be an adversary around the land, and he shall bring down your strength from you, and your *_palaces_* shall be plundered."
* `Amo 6:8` "The Lord GOD has sworn by himself," says the LORD the God of hosts, "I abhor the excellence of Jacob and hate his *_palaces_*; therefore, I will deliver up the city with all its abundance.
* `Mic 5:5` And this one will be peace. When the Assyrian comes into our land and treads in our *_palaces_*, we shall raise against him seven shepherds and eight principal men.

_32 verses containing PALACES_

== PALAL

* `Neh 3:25` *_Palal_* the son of Uzai repaired over against the turning of the wall and the tower projecting from the king's high house that was by the court of the prison, and after him Pedaiah the son of Parosh;

_1 verse containing PALAL_

== PALE

* `Isa 29:22` Therefore, thus says the LORD, who redeemed Abraham, concerning the house of Jacob: "Jacob shall not now be ashamed, neither shall his face now become *_pale_*.
* `Rev 6:8` And I looked, and behold, a *_pale_* horse. And his name who sat on him was Death, and hell followed with him. And power was given to them over the fourth part of the earth to kill with sword, with hunger, with death, and with the beasts of the earth.

_2 verses containing PALE_

== PALENESS

* `Jer 30:6` Ask now, and see whether a man travails with child. Why do I see every man with his hands on his loins as a woman in travail, and all faces are turned into *_paleness_*?

_1 verse containing PALENESS_

== PALESTINA

* `Exo 15:14` The people shall hear and be afraid. Sorrow shall take hold upon the inhabitants of *_Palestina_*.
* `Isa 14:29` Do not rejoice, all *_Palestina_*, because the rod of him who smote you is broken. For out of the serpent's root shall come forth an adder, and his fruit shall be a fiery flying serpent.
* `Isa 14:31` Howl, O gate. Cry, O city. You, all *_Palestina_*, are dissolved. For there shall come from the north a smoke, and no one shall be alone in his appointed times.

_3 verses containing PALESTINA_

== PALESTINE

* `Joe 3:4` "And what do you even have to do with me, O Tyre, Zidon, and all the regions of *_Palestine_*? Will you render me a recompense? And if you recompense me, swiftly and speedily I will return your recompense upon your own head,

_1 verse containing PALESTINE_

== PALLU

* `Exo 6:14` These are the heads of their father's houses. The sons of Reuben (the first-born of Israel): Hanoch, *_Pallu_*, Hezron, and Carmi. These are the families of Reuben.
* `1Ch 5:3` The sons of Reuben the first-born of Israel were Hanoch, *_Pallu_*, Hezron, and Carmi.

_2 verses containing PALLU_

== PALM

* `Exo 15:27` And they came to Elim, where there were twelve wells of water and seventy *_palm_*-trees. And they encamped there by the waters.
* `Lev 14:15` And the priest shall take some of the log of oil and pour it into the *_palm_* of his own left hand.
* `Lev 14:26` And the priest shall pour some of the oil into the *_palm_* of his own left hand.
* `Lev 23:40` And you shall take for yourselves on the first day the boughs of beautiful trees—branches of *_palm_*-trees, the boughs of thick trees, and willows of the brook—and you shall rejoice before the LORD your God seven days.
* `Num 33:9` And they departed from Marah and came to Elim. And in Elim there were twelve fountains of water and seventy *_palm_*-trees, and they encamped there.
* `Deu 34:3` The south, and the plain of the valley of Jericho, the city of *_palm_*-trees, to Zoar.
* `Jdg 1:16` And the children of the Kenite, Moses's father-in-law, went up out of the city of *_palm_*-trees with the children of Judah into the wilderness of Judah, which lies in the south of Arad, and they went and dwelt among the people.
* `Jdg 3:13` And he gathered to himself the children of Ammon and Amalek, and went and smote Israel, and possessed the city of *_palm_*-trees.
* `Jdg 4:5` And she dwelt under the *_palm_*-tree of Deborah between Ramah and Beth-el in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `1Ki 6:29` And he carved all the walls of the house around with carved figures of cherubim, *_palm_* trees, and open flowers, inside and outside.
* `1Ki 6:32` The two doors were also of olive tree, and he carved upon them carvings of cherubim, *_palm_* trees, and open flowers, and overlaid them with gold. And he spread gold upon the cherubim and upon the *_palm_* trees.
* `1Ki 6:35` And he carved thereon cherubim, *_palm_* trees, and open flowers, and covered them with gold, fitted upon the carved work.
* `1Ki 7:36` For on the plates of its ledges and on its borders he engraved cherubim, lions, and *_palm_* trees, according to the proportion of each, with wreaths around.
* `1Ki 18:44` And it came to pass at the seventh time, that he said, "Behold, there arises a little cloud out of the sea about the size of a man's *_palm_*." And he said, "Go up, say to Ahab, 'Prepare your chariot and go down so that the rain may not hinder you.'"
* `2Ch 3:5` And the greater house he ceiled with fir tree, which he overlaid with fine gold and set on it *_palm_* trees and chains.
* `2Ch 28:15` And the men who were expressed by name arose, took the captives, and with the plunder clothed all who were naked among them and arrayed them, shod them, gave them something to eat and to drink, anointed them, carried all the feeble among them upon donkeys, and brought them to their brothers at Jericho, the city of *_palm_* trees. Then they returned to Samaria.
* `Neh 8:15` And that they should publish and proclaim in all their cities and in Jerusalem, saying, "Go forth to the mountain and fetch olive branches, pine branches, myrtle branches, *_palm_* branches, and branches of thick trees to make booths, as it is written."
* `Psa 92:12` The righteous shall flourish like the *_palm_*-tree. He shall grow like a cedar in Lebanon.
* `Sos 7:7` Your stature is like a *_palm_* tree, and your breasts like clusters of grapes.
* `Sos 7:8` I said, "I will go up to the *_palm_* tree. I will take hold of its boughs." Now also your breasts shall be as clusters of the vine, and the smell of your nose like apples.
* `Jer 10:5` They are upright as the *_palm_* tree, but do not speak. They must be carried because they cannot walk. Do not be afraid of them, for they cannot do evil, neither is it also in them to do good."
* `Ezk 40:16` And there were narrow windows to the little chambers and to their posts within the gate around, and likewise to the arches. And windows were around inward. And upon each post were *_palm_*-trees.
* `Ezk 40:22` And their windows, their arches, and their *_palm_*-trees were after the measure of the gate that looks toward the east. And they went up to it by seven steps, and its arches were before them.
* `Ezk 40:26` And there were seven steps to go up to it, and its arches were before them. And it had *_palm_*-trees, one on this side and another on that side, upon its posts.
* `Ezk 40:31` And its arches were toward the outer court. And *_palm_*-trees were upon its posts. And the ascent to it had eight steps.
* `Ezk 40:34` And its arches were toward the outward court. And *_palm_*-trees were upon its posts on this side and on that side. And the ascent to it had eight steps.
* `Ezk 40:37` And its posts were toward the outer court. And *_palm_*-trees were upon its posts on this side and on that side. And the ascent to it had eight steps.
* `Ezk 41:18` And it was made with cherubim and *_palm_*-trees, so that a *_palm_*-tree was between a cherub and a cherub. And every cherub had two faces,
* `Ezk 41:19` So that the face of a man was toward the *_palm_*-tree on one side and the face of a young lion toward the *_palm_*-tree on the other side. It was made through all the house around.
* `Ezk 41:20` From the ground to above the door, cherubim and *_palm_*-trees were made, as well as on the wall of the temple.
* `Ezk 41:25` And there were made on them, on the doors of the temple, cherubim and *_palm_*-trees, as were made upon the walls. And there were thick planks upon the face of the porch outside.
* `Ezk 41:26` And there were narrow windows and *_palm_*-trees on one side and on the other side, on the sides of the porch, the side-chambers of the house, and the thick planks.
* `Joe 1:12` The vine is dried up and the fig-tree languishes. The pomegranate-tree, the *_palm_*-tree, and the apple-tree, even all the trees of the field are withered, because joy has withered away from the sons of men.
* `Jhn 12:13` Took branches of *_palm_*-trees and went forth to meet him, and cried, "'Hosanna! Blessed is he who comes in the name of the Lord,' even the King of Israel."
* `Jhn 18:22` And when he had said this, one of the officers who stood by struck Jesus with the *_palm_* of his hand, saying, "Do you answer the high priest like that?"
* `Rev 7:9` After this, I beheld, and behold, a great multitude, which no man could number of all nations, kindreds, people, and languages, stood before the throne and before the Lamb, clothed in white robes and with *_palm_* branches in their hands.

_36 verses containing PALM_

== PALM-TREE

* `Jdg 4:5` And she dwelt under the *_palm-tree_* of Deborah between Ramah and Beth-el in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `Psa 92:12` The righteous shall flourish like the *_palm-tree_*. He shall grow like a cedar in Lebanon.
* `Ezk 41:18` And it was made with cherubim and palm-trees, so that a *_palm-tree_* was between a cherub and a cherub. And every cherub had two faces,
* `Ezk 41:19` So that the face of a man was toward the *_palm-tree_* on one side and the face of a young lion toward the *_palm-tree_* on the other side. It was made through all the house around.
* `Joe 1:12` The vine is dried up and the fig-tree languishes. The pomegranate-tree, the *_palm-tree_*, and the apple-tree, even all the trees of the field are withered, because joy has withered away from the sons of men.

_5 verses containing PALM-TREE_

== PALM-TREES

* `Exo 15:27` And they came to Elim, where there were twelve wells of water and seventy *_palm-trees_*. And they encamped there by the waters.
* `Lev 23:40` And you shall take for yourselves on the first day the boughs of beautiful trees—branches of *_palm-trees_*, the boughs of thick trees, and willows of the brook—and you shall rejoice before the LORD your God seven days.
* `Num 33:9` And they departed from Marah and came to Elim. And in Elim there were twelve fountains of water and seventy *_palm-trees_*, and they encamped there.
* `Deu 34:3` The south, and the plain of the valley of Jericho, the city of *_palm-trees_*, to Zoar.
* `Jdg 1:16` And the children of the Kenite, Moses's father-in-law, went up out of the city of *_palm-trees_* with the children of Judah into the wilderness of Judah, which lies in the south of Arad, and they went and dwelt among the people.
* `Jdg 3:13` And he gathered to himself the children of Ammon and Amalek, and went and smote Israel, and possessed the city of *_palm-trees_*.
* `Ezk 40:16` And there were narrow windows to the little chambers and to their posts within the gate around, and likewise to the arches. And windows were around inward. And upon each post were *_palm-trees_*.
* `Ezk 40:22` And their windows, their arches, and their *_palm-trees_* were after the measure of the gate that looks toward the east. And they went up to it by seven steps, and its arches were before them.
* `Ezk 40:26` And there were seven steps to go up to it, and its arches were before them. And it had *_palm-trees_*, one on this side and another on that side, upon its posts.
* `Ezk 40:31` And its arches were toward the outer court. And *_palm-trees_* were upon its posts. And the ascent to it had eight steps.
* `Ezk 40:34` And its arches were toward the outward court. And *_palm-trees_* were upon its posts on this side and on that side. And the ascent to it had eight steps.
* `Ezk 40:37` And its posts were toward the outer court. And *_palm-trees_* were upon its posts on this side and on that side. And the ascent to it had eight steps.
* `Ezk 41:18` And it was made with cherubim and *_palm-trees_*, so that a palm-tree was between a cherub and a cherub. And every cherub had two faces,
* `Ezk 41:20` From the ground to above the door, cherubim and *_palm-trees_* were made, as well as on the wall of the temple.
* `Ezk 41:25` And there were made on them, on the doors of the temple, cherubim and *_palm-trees_*, as were made upon the walls. And there were thick planks upon the face of the porch outside.
* `Ezk 41:26` And there were narrow windows and *_palm-trees_* on one side and on the other side, on the sides of the porch, the side-chambers of the house, and the thick planks.
* `Jhn 12:13` Took branches of *_palm-trees_* and went forth to meet him, and cried, "'Hosanna! Blessed is he who comes in the name of the Lord,' even the King of Israel."

_17 verses containing PALM-TREES_

== PALMS

* `1Sa 5:4` And when they arose early on the next morning, behold, Dagon had fallen upon his face to the ground before the ark of the LORD. And the head of Dagon and both the *_palms_* of his hands were cut off upon the threshold. Only the stump of Dagon was left to him.
* `2Ki 9:35` And they went to bury her, but they found no more of her than the skull, the feet, and the *_palms_* of her hands.
* `Isa 49:16` Behold, I have engraved you upon the *_palms_* of my hands. Your walls are continually before me.
* `Dan 10:10` And behold, a hand touched me, which set me upon my knees and upon the *_palms_* of my hands.
* `Mth 26:67` Then they spit in his face and buffeted him. And others smote him with the *_palms_* of their hands,
* `Mrk 14:65` And some began to spit on him, to cover his face, to buffet him, and to say to him, "Prophesy." And the servants struck him with the *_palms_* of their hands.

_6 verses containing PALMS_

== PALTI

* `Num 13:9` Of the tribe of Benjamin, *_Palti_* the son of Raphu;

_1 verse containing PALTI_

== PALTIEL

* `Num 34:26` The prince of the tribe of the children of Issachar, *_Paltiel_* the son of Azzan;

_1 verse containing PALTIEL_

== PALTITE

* `2Sa 23:26` Helez the *_Paltite_*, Ira the son of Ikkesh the Tekoite,

_1 verse containing PALTITE_

== PAMPHYLIA

* `Act 2:10` Phrygia, *_Pamphylia_*, in Egypt, in the parts of Libya around Cyrene, strangers of Rome, both Jews and Proselytes,
* `Act 13:13` Now when Paul and his company set sail from from Paphos, they came to Perga in *_Pamphylia_*. And John, departing from them, returned to Jerusalem.
* `Act 14:24` And after they had passed throughout Pisidia, they came to *_Pamphylia_*.
* `Act 15:38` But Paul did not think it good to take with them him who departed from them in *_Pamphylia_* and did not go with them to the work.
* `Act 27:5` And when we had sailed over the sea of Cilicia and *_Pamphylia_*, we came to Mira, a city of Lycia.

_5 verses containing PAMPHYLIA_

== PAN

* `Lev 2:5` And if your oblation is a food-offering baked in a *_pan_*, it shall be of fine flour unleavened, mingled with oil.
* `Lev 2:7` And if your oblation is a food-offering baked in the frying-*_pan_*, it shall be made of fine flour with oil.
* `Lev 6:21` In a *_pan_* it shall be made with oil. And when it is baked, you shall bring it in, and the baked pieces of the food-offering you shall offer for a sweet savor to the LORD.
* `Lev 7:9` And all the food-offering that is baked in the oven and all that is dressed in the frying-*_pan_* and on the griddle shall be the priest's who offers it.
* `1Sa 2:14` And he struck it into the *_pan_*, kettle, cauldron, or pot, and all that the flesh-hook brought up the priest took for himself. They did so in Shiloh to all the Israelites who came there.
* `2Sa 13:9` And she took a *_pan_* and poured them out before him, but he refused to eat. And Amnon said, "Have all men go out from me." And every man went out from him.
* `1Ch 23:29` For the show-bread, for the fine flour for food-offering, for the unleavened cakes, for that which is baked in the *_pan_*, for that which is fried, and for all manner of measure and size;
* `Ezk 4:3` Moreover, take an iron *_pan_* and set it for a wall of iron between you and the city. And set your face against it so that it shall be besieged, and then lay siege against it. This shall be a sign to the house of Israel.

_8 verses containing PAN_

== PANGS

* `Psa 73:4` For there are no *_pangs_* in their death, but their strength is firm.
* `Isa 13:8` And they shall be afraid. *_Pangs_* and sorrows shall take hold of them. They shall be in pain like a woman who travails. They shall be amazed at one another. Their faces shall be as flames.
* `Isa 21:3` Therefore, my loins are filled with pain. *_Pangs_* have taken hold upon me like the *_pangs_* of a woman who travails. I was bowed down when I heard it. I was dismayed when I saw it.
* `Isa 26:17` As a woman with child, who draws near the time of her delivery, is in pain and cries out in her *_pangs_*, so we have been in your sight, O LORD.
* `Jer 22:23` O inhabitant of Lebanon, who makes your nest in the cedars, how gracious you shall be when *_pangs_* come upon you, the pain as of a woman in travail!
* `Jer 48:41` Kerioth is taken and the strongholds are surprised, and the mighty men's hearts in Moab at that day shall be like the heart of a woman in her *_pangs_*.
* `Jer 49:22` Behold, he shall come up and fly like the eagle and spread his wings over Bozrah. And at that day the heart of the mighty men of Edom shall be like the heart of a woman in her *_pangs_*.
* `Jer 50:43` The king of Babylon has heard their report and his hands became feeble. Anguish took hold of him, and *_pangs_* as of a woman in travail.
* `Mic 4:9` Now why do you cry aloud? Is there no king in you? Has your counselor perished? For *_pangs_* have taken you as a woman in travail.

_9 verses containing PANGS_

== PANNAG

* `Ezk 27:17` Judah, and the land of Israel, they were your merchants. They traded in your market in wheat of Minnith, *_Pannag_*, honey, oil, and balm.

_1 verse containing PANNAG_

== PANS

* `Exo 27:3` And you shall make its *_pans_* to receive its ashes, its shovels, its basins, its flesh-hooks, and its fire-*_pans_*. All its vessels you shall make of brass.
* `Exo 38:3` And he made all the vessels of the altar: the pots, the shovels, the basins, the flesh-hooks, and the fire-*_pans_*. All its vessels he made of brass.
* `Num 11:8` And the people went around and gathered it, ground it in mills or beat it in a mortar, and baked it in *_pans_* and made cakes with it. And its taste was like the taste of fresh oil.
* `2Ki 25:15` And the fire-*_pans_*, the bowls, and such things as were of gold, in gold, and of silver, in silver, the captain of the guard took away.
* `1Ch 9:31` And Mattithiah, one of the Levites, who was the first-born of Shallum the Korahite, had the set office over the things that were made in the *_pans_*.
* `2Ch 35:13` And they roasted the passover with fire according to the ordinance, but the other holy offerings they boiled in pots, in cauldrons, and in *_pans_*, and divided them speedily among all the people.
* `Jer 52:19` And the basins, the fire-*_pans_*, the bowls, the cauldrons, the candlesticks, the spoons, and the cups—the gold from that which was made of gold, and the silver from that which was made of silver—the captain of the guard took away.

_7 verses containing PANS_

== PANT

* `Amo 2:7` They *_pant_* after the dust of the earth on the head of the poor and turn aside the way of the meek. And a man and his father will go in to the same woman to profane my holy name.

_1 verse containing PANT_

== PANTED

* `Psa 119:131` I opened my mouth and *_panted_*, for I longed for your commandments.
* `Isa 21:4` My heart *_panted_*, fearfulness terrified me. The night of my pleasure he has turned into fear for me.

_2 verses containing PANTED_

== PANTS

* `Psa 38:10` My heart *_pants_*. My strength fails me. As for the light of my eyes, that also is gone from me.
* `Psa 42:1` [To the Chief Musician. Maschil for the Sons of Korah.] As the deer *_pants_* after the water brooks, so my soul *_pants_* after you, O God.
* `Dan 3:21` Then these men were bound in their coats, their *_pants_*, their hats, and their other garments, and were cast into the midst of the burning fiery furnace.

_3 verses containing PANTS_

== PAPER

* `Isa 19:7` The *_paper_*-reeds by the brooks, by the mouth of the brooks, and everything sown by the brooks shall wither, be driven away, and be no more.
* `2Jn 1:12` Having many things to write to you, I do not wish to write with *_paper_* and ink. But I trust to come to you and speak face to face so that our joy may be full.

_2 verses containing PAPER_

== PAPER-REEDS

* `Isa 19:7` The *_paper-reeds_* by the brooks, by the mouth of the brooks, and everything sown by the brooks shall wither, be driven away, and be no more.

_1 verse containing PAPER-REEDS_

== PAPHOS

* `Act 13:6` And when they had gone through the island to *_Paphos_*, they found a certain sorcerer, a false prophet, a Jew whose name was Barjesus,
* `Act 13:13` Now when Paul and his company set sail from from *_Paphos_*, they came to Perga in Pamphylia. And John, departing from them, returned to Jerusalem.

_2 verses containing PAPHOS_

== PARABLE

* `Num 23:7` And he took up his *_parable_* and said, "Balak the king of Moab has brought me from Aram, out of the mountains of the east, saying, 'Come, curse Jacob for me, and come, defy Israel.'
* `Num 23:18` And he took up his *_parable_* and said, "Rise, Balak, and hear. Listen to me, son of Zippor.
* `Num 24:3` And he took up his *_parable_* and said, "Balaam the son of Beor has said, and the man whose eyes are open has said,
* `Num 24:15` And he took up his *_parable_* and said, "Balaam the son of Beor has said, and the man whose eyes are open has said,
* `Num 24:20` And when he looked at Amalek, he took up his *_parable_* and said, "Amalek was the first of the nations, but his latter end shall be that he shall perish forever."
* `Num 24:21` And he looked at the Kenites and took up his *_parable_* and said, "Your dwelling-place is strong and you put your nest in a rock.
* `Num 24:23` And he took up his *_parable_* and said, "Alas! Who shall live when God does this?
* `Job 27:1` Moreover, Job continued his *_parable_* and said,
* `Job 29:1` Moreover, Job continued his *_parable_* and said,
* `Psa 49:4` I will incline my ear to a *_parable_*. I will open my dark saying upon the harp.
* `Psa 78:2` I will open my mouth in a *_parable_*. I will utter dark sayings of old,
* `Pro 26:7` The legs of the lame are not equal, and so is a *_parable_* in the mouth of fools.
* `Pro 26:9` As a thorn goes up into the hand of a drunkard, so is a *_parable_* in the mouth of fools.
* `Ezk 17:2` "Son of man, put forth a riddle and speak a *_parable_* to the house of Israel,
* `Ezk 24:3` And utter a *_parable_* to the rebellious house, and say to them, 'Thus says the Lord GOD: "Set on a pot, set it on, and also pour water into it.
* `Mic 2:4` In that day one shall take up a *_parable_* against you and lament with a grievous lamentation, and say, 'We are utterly wasted. He has changed the portion of my people. How he has removed it from me! To the rebellious he has divided our fields.'
* `Hab 2:6` Shall all these not take up a *_parable_* against him and a taunting proverb against him, and say, 'Woe to him who increases that which is not his and to him who lades himself with thick clay! How long?'
* `Mth 13:18` "Hear, therefore, the *_parable_* of the sower.
* `Mth 13:24` Another *_parable_* he proposed to them, saying, "The kingdom of heaven is compared to a man who sowed good seed in his field,
* `Mth 13:31` Another *_parable_* he proposed to them, saying, "The kingdom of heaven is like a grain of mustard-seed, which a man took and sowed in his field,
* `Mth 13:33` He spoke another *_parable_* to them: "The kingdom of heaven is like leaven, which a woman took and hid in three measures of meal until the whole was leavened."
* `Mth 13:34` All these things Jesus spoke to the multitude in parables, and without a *_parable_* he did not speak to them,
* `Mth 13:36` Then Jesus sent the multitude away and went into the house. And his disciples came to him, saying, "Declare to us the *_parable_* of the tares of the field."
* `Mth 15:15` Then Peter answered and said to him, "Declare to us this *_parable_*."
* `Mth 21:33` "Hear another *_parable_*. There was a certain householder who planted a vineyard, hedged it around, dug a wine-press in it, built a tower, and lent it out to farmers and went into a remote country.
* `Mth 24:32` "Now learn a *_parable_* of the fig-tree. When its branch is yet tender and puts forth leaves, you know that summer is near.
* `Mrk 4:10` And when he was alone, those who were around him, with the twelve, asked him about the *_parable_*.
* `Mrk 4:13` And he said to them, "Do you not know this *_parable_*? And how then will you know all parables?
* `Mrk 4:34` But without a *_parable_* he did not speak to them. And when they were alone, he expounded all things to his disciples.
* `Mrk 7:17` And when he had entered into the house from the people, his disciples asked him concerning the *_parable_*.
* `Mrk 12:12` And they sought to lay hold upon him, but feared the people, for they knew that he had spoken the *_parable_* against them. And they left him and departed.
* `Mrk 13:28` "Now learn a *_parable_* of the fig-tree: when its branch is yet tender and puts forth leaves, you know that summer is near.
* `Luk 5:36` And he also spoke a *_parable_* to them: "No man puts a patch of a new garment upon an old, or else the new makes a rent and the piece that was taken out of the new does not agree with the old.
* `Luk 6:39` And he spoke a *_parable_* to them: "Can the blind lead the blind? Will they not both fall into the ditch?
* `Luk 8:4` And when many people were collected and had come to him out of every city, he spoke by a *_parable_*:
* `Luk 8:9` And his disciples asked him, saying, "What does this *_parable_* mean?"
* `Luk 8:11` "Now the *_parable_* is this: The seed is the word of God.
* `Luk 12:16` And he spoke a *_parable_* to them, saying, "The ground of a certain rich man brought forth plentifully.
* `Luk 12:41` Then Peter said to him, "Lord, do you speak this *_parable_* to us, or even to all?"
* `Luk 13:6` He also spoke this *_parable_*: "A certain man had a fig-tree planted in his vineyard, and he came and sought fruit on it, and found none.
* `Luk 14:7` And he put forth a *_parable_* to those who were invited, when he marked how they chose out the chief places, saying to them,
* `Luk 15:3` And he spoke this *_parable_* to them, saying,
* `Luk 18:1` And he spoke a *_parable_* to them to this end, that men ought always to pray and not to faint,
* `Luk 18:9` And he spoke this *_parable_* to some who trusted in themselves that they were righteous, and despised others:
* `Luk 19:11` And as they heard these things, he added and spoke a *_parable_*, because he was near to Jerusalem and because they thought that the kingdom of God would immediately appear.
* `Luk 20:9` Then he began to speak to the people this *_parable_*: "A certain man planted a vineyard, leased it to farmers, and went into a far country for a long time.
* `Luk 20:19` And the chief priests and the scribes the same hour sought to lay hands on him, and they feared the people, for they perceived that he had spoken this *_parable_* against them.
* `Luk 21:29` And he spoke to them a *_parable_*: "Behold the fig-tree and all the trees.
* `Jhn 10:6` Jesus spoke this *_parable_* to them, but they did not understand what things those were which he spoke to them.

_49 verses containing PARABLE_

== PARABLES

* `Ezk 20:49` Then I said, "Ah, Lord GOD! They say of me, 'Does he not speak *_parables_*?'"
* `Mth 13:3` And he spoke many things to them in *_parables_*, saying, "Behold, a sower went forth to sow.
* `Mth 13:10` And the disciples came, and said to him, "Why do you speak to them in *_parables_*?"
* `Mth 13:13` Therefore, I speak to them in *_parables_*, because seeing they do not see, and hearing they do not hear, neither do they understand.
* `Mth 13:34` All these things Jesus spoke to the multitude in *_parables_*, and without a parable he did not speak to them,
* `Mth 13:35` So that it might be fulfilled which was spoken by the prophet, saying, "I will open my mouth in *_parables_*. I will utter things which have been kept secret from the foundation of the world."
* `Mth 13:53` And it came to pass, that when Jesus had finished these *_parables_*, he departed from there.
* `Mth 21:45` And when the chief priests and Pharisees had heard his *_parables_*, they perceived that he spoke of them.
* `Mth 22:1` And Jesus answered and spoke to them again by *_parables_*, and said,
* `Mrk 3:23` And he called them to him and said to them in *_parables_*, "How can Satan cast out Satan?
* `Mrk 4:2` And he taught them many things by *_parables_* and said to them in his doctrine,
* `Mrk 4:11` And he said to them, "To you it is given to know the mystery of the kingdom of God, but to those who are outside, all these things are done in *_parables_*,
* `Mrk 4:13` And he said to them, "Do you not know this parable? And how then will you know all *_parables_*?
* `Mrk 4:33` And with many such *_parables_* he spoke the word to them, as they were able to hear it.
* `Mrk 12:1` And he began to speak to them in *_parables_*. "A certain man planted a vineyard, set a hedge around it, dug a place for the wine-vat, built a tower, lent it out to farmers, and went into a far country.
* `Luk 8:10` And he said, "To you it is given to know the mysteries of the kingdom of God, but to others in *_parables_* so that 'seeing they may not see, and hearing they may not understand.'

_16 verses containing PARABLES_

== PARADISE

* `Luk 23:43` And Jesus said to him, "Truly I say to you, this day you shall be with me in *_paradise_*."
* `2Co 12:4` That he was caught up into *_paradise_* and heard unspeakable words, which it is not lawful for a man to utter.
* `Rev 2:7` He who has an ear, let him hear what the Spirit says to the churches. To him who overcomes, I will give to eat from the tree of life, which is in the midst of the *_paradise_* of God."'

_3 verses containing PARADISE_

== PARAH

* `Jsh 18:23` Avim, *_Parah_*, Ophrah,

_1 verse containing PARAH_

== PARALYTIC

* `Mth 9:2` And behold, they brought to him a paralyzed man lying on a bed. And Jesus, seeing their faith, said to the *_paralytic_*, "Son, be of good cheer. Your sins are forgiven."
* `Mth 9:6` But so that you may know that the Son of man has power on earth to forgive sins"—then he says to the *_paralytic_*—"Arise, take up your bed, and go to your house."
* `Mrk 2:4` And when they could not come near to him by reason of the crowd, they uncovered the roof where he was. And when they had broken it up, they let down the bed on which the *_paralytic_* lay.
* `Mrk 2:5` When Jesus saw their faith, he said to the *_paralytic_*, "Son, your sins are forgiven."
* `Mrk 2:9` Which is easier, to say to the *_paralytic_*, 'Your sins are forgiven,' or to say, 'Arise, take up your bed, and walk'?
* `Mrk 2:10` But so that you may know that the Son of man has power on earth to forgive sins"—he says to the *_paralytic_*—
* `Luk 5:24` But so that you may know that the Son of man has power upon earth to forgive sins"—he said to the *_paralytic_*—"I say to you, arise, take up your bed, and go into your house."

_7 verses containing PARALYTIC_

== PARALYZED

* `Mth 4:24` And his fame spread throughout all Syria. And they brought to him all sick people who were taken with various diseases and torments, those who were possessed with demons, those who were lunatic, and those who were *_paralyzed_*, and he healed them.
* `Mth 8:6` And saying, "Lord, my servant lies at home *_paralyzed_*, grievously tormented."
* `Mth 9:2` And behold, they brought to him a *_paralyzed_* man lying on a bed. And Jesus, seeing their faith, said to the paralytic, "Son, be of good cheer. Your sins are forgiven."
* `Mrk 2:3` And they come to him, bringing someone *_paralyzed_* who was carried by four men.
* `Luk 5:18` And behold, men brought on a bed a man who was *_paralyzed_*. And they sought means to bring him in and to lay him before him.
* `Act 8:7` For unclean spirits, crying with loud voice, came out of many who were possessed, and many who were *_paralyzed_* and who were lame were healed.
* `Act 9:33` And there he found a certain man named Eneas who had been bedridden for eight years and was *_paralyzed_*.

_7 verses containing PARALYZED_

== PARAMOURS

* `Ezk 23:20` For she doted upon their *_paramours_*, whose flesh is as the flesh of donkeys and whose issue is like the issue of horses.

_1 verse containing PARAMOURS_

== PARAN

* `Gen 14:6` And the Horites in the mountains of Seir, to El-*_paran_*, which is by the wilderness.
* `Gen 21:21` And he dwelt in the wilderness of *_Paran_*. And his mother took for him a wife out of the land of Egypt.
* `Num 10:12` And the children of Israel took their journeys from the wilderness of Sinai. And the cloud rested in the wilderness of *_Paran_*.
* `Num 12:16` And afterward, the people departed from Hazeroth and encamped in the wilderness of *_Paran_*.
* `Num 13:3` And Moses, by the commandment of the LORD, sent them from the wilderness of *_Paran_*. All those men were heads of the children of Israel.
* `Num 13:26` And they went and came to Moses, to Aaron, and to all the congregation of the children of Israel in the wilderness of *_Paran_* at Kadesh. And they brought back word to them and to all the congregation and showed them the fruit of the land.
* `Deu 1:1` These are the words which Moses spoke to all Israel on the east side of the Jordan in the wilderness, in the plain over against Suf, between *_Paran_*, Tophel, Laban, Hazeroth, and Dizahab.
* `Deu 33:2` And he said, "The LORD came from Sinai, and rose up from Seir to them. He shined forth from mount *_Paran_*, and he came with tens of thousands of saints. From his right hand went a fiery law for them.
* `1Sa 25:1` And Samuel died. And all the Israelites assembled, lamented him, and buried him in his house at Ramah. And David arose and went down to the wilderness of *_Paran_*.
* `1Ki 11:18` And they arose out of Midian and came to *_Paran_*. And they took men with them from *_Paran_* and they came to Egypt, to Pharaoh king of Egypt, who gave him a house, appointed him food, and gave him land.
* `Hab 3:3` God came from Teman, and the Holy One from mount *_Paran_*. [Selah.] His glory covered the heavens, and the earth was full of his praise.

_11 verses containing PARAN_

== PARAPET

* `Deu 22:8` "When you build a new house, you shall make a *_parapet_* for your roof so that you may not bring blood upon your house if any man falls from there.

_1 verse containing PARAPET_

== PARBAR

* `1Ch 26:18` At *_Parbar_* westward, there were four at the highway and two at *_Parbar_*.

_1 verse containing PARBAR_

== PARCEL

* `Jsh 24:32` And the bones of Joseph which the children of Israel brought out of Egypt, they buried in Shechem in a *_parcel_* of ground which Jacob bought of the sons of Hamor the father of Shechem for one hundred pieces of silver. And it became the inheritance of the children of Joseph.
* `Rth 4:3` And he said to the kinsman, "Naomi, who has come back out of the country of Moab, sells a *_parcel_* of land, which was our brother Elimelech's.
* `1Ch 11:13` He was with David at Pas-dammim, and there the Philistines were gathered to battle, where a *_parcel_* of ground full of barley was, and the people fled from before the Philistines.
* `1Ch 11:14` And they set themselves in the midst of that *_parcel_*, delivered it, and slew the Philistines, and the LORD saved them by a great deliverance.
* `Jhn 4:5` Then he comes to a city of Samaria, which is called Sychar, near the *_parcel_* of ground that Jacob gave to his son Joseph.

_5 verses containing PARCEL_

== PARCHED

* `Lev 23:14` And you shall eat neither bread, *_parched_* grain, nor new grain until the same day that you have brought an offering to your God. It shall be a statute forever throughout your generations in all your dwellings.
* `Jsh 5:11` And they ate unleavened cakes and *_parched_* grain from the produce of the land on the next day after the passover—on that very day.
* `Rth 2:14` And Boaz said to her, "At meal-time, come here and eat some of the bread and dip your morsel in the vinegar." And she sat beside the reapers, and he gave her *_parched_* grain, and she ate, was satisfied, and had some left over.
* `1Sa 17:17` And Jesse said to David his son, "Now take for your brothers an ephah of this *_parched_* grain and these ten loaves, and run to the camp to your brothers.
* `1Sa 25:18` Then Abigail made haste and took two hundred loaves, two bottles of wine, five sheep ready and dressed, five measures of *_parched_* grain, one hundred clusters of raisins, and two hundred cakes of figs, and laid them on donkeys.
* `2Sa 17:28` Brought beds, basins, earthen vessels, wheat, barley, flour, *_parched_* grain, beans, lentils, *_parched_* pulse,
* `Isa 35:7` And the *_parched_* ground shall become a pool, and the thirsty land springs of water. In the habitation of jackals, where each lay, there shall be grass with reeds and rushes.
* `Jer 17:6` For he shall be like the heath in the desert. It shall not see when good comes, but shall inhabit the *_parched_* places in the wilderness, in a salt land and not inhabited.

_8 verses containing PARCHED_

== PARCHMENTS

* `2Ti 4:13` The cloak that I left at Troas with Carpus, when you come, bring it with you, and also the books, but especially the *_parchments_*.

_1 verse containing PARCHMENTS_

== PARDON

* `Exo 23:21` Beware of him and obey his voice. Do not provoke him, for he will not *_pardon_* your transgressions, for my name is in him.
* `Exo 34:9` And he said, "If now I have found grace in your sight, O Lord, let my Lord, I pray you, go among us (for it is a stiff-necked people) and *_pardon_* our iniquity and our sin and take us for your inheritance."
* `Num 14:19` *_Pardon_*, I implore you, the iniquity of this people according to the greatness of your mercy, as you have forgiven this people from Egypt even until now."
* `1Sa 15:25` Now therefore, I pray you, *_pardon_* my sin and turn back with me so that I may worship the LORD."
* `2Ki 5:18` In this thing may the LORD *_pardon_* your servant: when my master goes into the house of Rimmon to worship there and he leans on my hand, and I bow myself in the house of Rimmon, when I bow down myself in the house of Rimmon, may the LORD *_pardon_* your servant in this thing."
* `2Ki 24:4` And also for the innocent blood that he shed, for he filled Jerusalem with innocent blood which the LORD would not *_pardon_*.
* `2Ch 30:18` For a multitude of the people, even many of Ephraim, Manasseh, Issachar, and Zebulun, had not cleansed themselves, yet they ate the passover in a way other than it was written. But Hezekiah prayed for them, saying, "May the good LORD *_pardon_* everyone
* `Neh 9:17` And they refused to obey, neither were they mindful of your wonders that you performed among them, but hardened their necks, and in their rebellion appointed a captain to return to their bondage. But you are a God ready to *_pardon_*, gracious and merciful, slow to anger, and of great kindness, and did not forsake them.
* `Job 7:21` And why do you not *_pardon_* my transgression and take away my iniquity? For now I shall sleep in the dust. And you shall seek me in the morning, but I shall be no more."
* `Psa 25:11` [KAF] For your name's sake, O LORD, *_pardon_* my iniquity, for it is great.
* `Isa 55:7` Let the wicked forsake his way and the unrighteous man his thoughts. And let him return to the LORD, and he will have mercy upon him, and to our God, for he will abundantly *_pardon_*.
* `Jer 5:1` "Run to and fro through the streets of Jerusalem. And now look, and know, and seek in its broad places. If you can find a man, if there is anyone who executes judgment, who seeks the truth, then I will *_pardon_* it.
* `Jer 5:7` "How shall I *_pardon_* you for this? Your children have forsaken me and sworn by those who are not gods. When I had fed them to the full, they committed adultery and assembled themselves by troops in the harlots' houses.
* `Jer 33:8` And I will cleanse them from all their iniquity, by which they have sinned against me, and I will *_pardon_* all their iniquities, by which they have sinned and by which they have transgressed against me.
* `Jer 50:20` In those days and in that time,' says the LORD, 'the iniquity of Israel shall be sought for, and there shall be none, and the sins of Judah, and they shall not be found, for I will *_pardon_* those whom I reserve.'

_15 verses containing PARDON_

== PARDONED

* `Num 14:20` And the LORD said, "I have *_pardoned_* according to your word.
* `Isa 40:2` "Speak comfortably to Jerusalem, and cry to her, that her warfare is accomplished, that her iniquity is *_pardoned_*, for she has received from the LORD'S hand double for all her sins."
* `Lam 3:42` We have transgressed and have rebelled. You have not *_pardoned_*.

_3 verses containing PARDONED_

== PARDONS

* `Mic 7:18` Who is a God like you, who *_pardons_* iniquity and passes by the transgression of the remnant of his heritage? He does not retain his anger forever because he delights in mercy.

_1 verse containing PARDONS_

== PARE

* `Deu 21:12` Then you shall bring her home to your house, and she shall shave her head and *_pare_* her nails.

_1 verse containing PARE_

== PARENTS

* `Mth 10:21` "And the brother will deliver up the brother to death, and the father the child. And the children will rise up against their *_parents_* and cause them to be put to death.
* `Mrk 13:12` Now the brother will betray the brother to death, and the father the son. And children will rise up against their *_parents_* and will cause them to be put to death.
* `Luk 2:27` And he came by the Spirit into the temple. And when the *_parents_* brought in the child Jesus, to do for him after the custom of the law,
* `Luk 2:41` Now his *_parents_* went to Jerusalem every year at the feast of the passover.
* `Luk 8:56` And her *_parents_* were astonished, but he charged them that they should tell no man what was done.
* `Luk 18:29` And he said to them, "Truly I say to you, there is no man who has left house, *_parents_*, brothers, wife, or children for the sake of the kingdom of God
* `Luk 21:16` And you will be betrayed by *_parents_*, brothers, kinsmen, and friends, and some of you they will cause to be put to death.
* `Jhn 9:2` And his disciples asked him, saying, "Master, who sinned, this man or his *_parents_*, so that he was born blind?"
* `Jhn 9:3` Jesus answered, "Neither has this man sinned, nor his *_parents_*, but this is so that the works of God should be made manifest in him.
* `Jhn 9:18` But the Jews did not believe concerning him, that he had been blind and received his sight, until they called the *_parents_* of him who had received his sight.
* `Jhn 9:20` His *_parents_* answered them and said, "We know that this is our son and that he was born blind.
* `Jhn 9:22` His *_parents_* spoke these words because they feared the Jews. For the Jews had already agreed that if any man confessed that he was Christ, he should be put out of the synagogue.
* `Jhn 9:23` Therefore, his *_parents_* said, "He is of age. Ask him."
* `Rom 1:30` Backbiters, haters of God, despiteful, proud, boasters, inventors of evil things, disobedient to *_parents_*,
* `2Co 12:14` Behold, the third time I am ready to come to you and I will not be burdensome to you, for I do not seek what is yours, but you. For the children ought not to lay up for the *_parents_*, but the *_parents_* for the children.
* `Eph 6:1` Children, obey your *_parents_* in the Lord, for this is right.
* `Col 3:20` Children, obey your *_parents_* in all things, for this is well-pleasing to the Lord.
* `1Ti 5:4` But if any widow has children or grandchildren, let them first learn to show piety at home and to requite their *_parents_*, for that is good and acceptable before God.
* `2Ti 3:2` For men will be lovers of their own selves, covetous, boasters, proud, blasphemers, disobedient to *_parents_*, unthankful, unholy,
* `Heb 11:23` By faith Moses, when he was born, was hid three months by his *_parents_* because they saw he was an exceedingly fair child, and they were not afraid of the king's commandment.

_20 verses containing PARENTS_

== PARLOR

* `Jdg 3:20` And Ehud came to him. And he was sitting in a summer-*_parlor_* which he had for himself alone. And Ehud said, "I have a message from God to you." And he arose from his seat.
* `Jdg 3:23` Then Ehud went forth through the porch and shut the doors of the *_parlor_* upon him and locked them.
* `Jdg 3:24` When he had gone out, his servants came. And when they saw that, behold, the doors of the *_parlor_* were locked, they said, "Surely he covers his feet in his summer-chamber."
* `Jdg 3:25` And they waited until they were ashamed. And behold, he did not open the doors of the *_parlor_*; therefore, they took a key and opened them, and behold, their lord lay dead on the earth.

_4 verses containing PARLOR_

== PARMASHTA

* `Est 9:9` *_Parmashta_*, Arisai, Aridai, and Vajezatha,

_1 verse containing PARMASHTA_

== PARMENAS

* `Act 6:5` And the saying pleased the whole multitude and they chose Stephen, a man full of faith and of the Holy Spirit, and also Philip, Prochorus, Nicanor, Timon, *_Parmenas_*, and Nicolas a proselyte of Antioch.

_1 verse containing PARMENAS_

== PARNACH

* `Num 34:25` The prince of the tribe of the children of Zebulun, Elizaphan the son of *_Parnach_*;

_1 verse containing PARNACH_

== PAROSH

* `Ezr 2:3` The children of *_Parosh_*, two thousand one hundred and seventy-two;
* `Ezr 10:25` Moreover, of Israel: of the sons of *_Parosh_*: Ramiah, Jeziah, Malchiah, Miamin, Eleazar, Malchijah, and Benaiah.
* `Neh 3:25` Palal the son of Uzai repaired over against the turning of the wall and the tower projecting from the king's high house that was by the court of the prison, and after him Pedaiah the son of *_Parosh_*;
* `Neh 7:8` The children of *_Parosh_*, two thousand one hundred and seventy-two;
* `Neh 10:14` The chief of the people: *_Parosh_*, Pahath-moab, Elam, Zatthu, Bani,

_5 verses containing PAROSH_

== PARSHANDATHA

* `Est 9:7` And they slew *_Parshandatha_*, Dalphon, Aspatha,

_1 verse containing PARSHANDATHA_

== PART

* `Gen 27:16` And she put the skins of the kids of the goats on his hands and on the smooth *_part_* of his neck.
* `Gen 33:19` And he bought a *_part_* of a field where he had spread his tent at the hand of the children of Hamor, Shechem's father, for one hundred pieces of money.
* `Gen 41:34` Let Pharaoh do this: let him appoint officers over the land to take up the fifth *_part_* of the land of Egypt in the seven plenteous years.
* `Gen 47:24` And it shall come to pass in the increase, that you shall give the fifth *_part_* to Pharaoh, and four parts shall be your own, for seed of the field, for your food, for those of your households, and for food for your little ones."
* `Gen 47:26` And Joseph made it a law over the land of Egypt to this day, that Pharaoh should have the fifth *_part_*, except the land of the priests only, which did not become Pharaoh's.
* `Exo 16:36` (Now an omer is the tenth *_part_* of an ephah.)
* `Exo 19:17` And Moses brought forth the people out of the camp to meet with God, and they stood at the nether *_part_* of the mountain.
* `Exo 29:26` "And you shall take the breast of the ram of Aaron's consecration and wave it for a wave-offering before the LORD, and it shall be your *_part_*.
* `Exo 29:40` And with one lamb [you shall offer] a tenth-portion of flour mingled with the fourth *_part_* of a hin of beaten oil, and the fourth *_part_* of a hin of wine for a drink-offering.
* `Lev 1:16` And he shall pluck away its crop with its feathers and cast it beside the altar on the east *_part_* by the place of the ashes.
* `Lev 2:6` You shall *_part_* it in pieces and pour oil upon it. It is a food-offering.
* `Lev 2:16` And the priest shall burn its memorial, *_part_* of its beaten grain and *_part_* of its oil, with all its frankincense. It is an offering made by fire to the LORD.'"
* `Lev 5:11` 'But if he is not able to bring two turtle-doves or two young pigeons, then he who sinned shall bring for his offering the tenth *_part_* of an ephah of fine flour for a sin-offering. He shall put no oil upon it, neither shall he put any frankincense upon it, for it is a sin-offering.
* `Lev 5:16` And he shall make amends for the harm that he has done in the holy thing, and shall add to it the fifth *_part_* and give it to the priest. And the priest shall make an atonement for him with the ram of the trespass-offering, and he shall be forgiven.
* `Lev 6:5` Or all that about which he has sworn falsely. He shall even restore it in the principal and shall add to it the fifth *_part_* more and give it to him to whom it belongs in the day of his trespass-offering.
* `Lev 6:20` "This is the offering of Aaron and of his sons, which they shall offer to the LORD in the day when he is anointed: the tenth *_part_* of an ephah of fine flour for a perpetual food-offering, half of it in the morning and half of it at night.
* `Lev 7:33` He among the sons of Aaron who offers the blood of the peace-offerings and the fat shall have the right shoulder for his *_part_*.
* `Lev 8:11` And he sprinkled *_part_* of it upon the altar seven times and anointed the altar and all its vessels, both the basin and its foot, to sanctify them.
* `Lev 8:29` And Moses took the breast and waved it for a wave-offering before the LORD. It was Moses's *_part_* of the ram of consecration, as the LORD commanded Moses.
* `Lev 11:35` And everything on which any *_part_* of their carcass falls shall be unclean. Whether an oven or ranges for pots, they shall be broken down, for they are unclean and shall be unclean to you.
* `Lev 11:37` And if any *_part_* of their carcass shall fall upon any sowing-seed which is to be sown, it shall be clean.
* `Lev 11:38` But if any water is put upon the seed, and any *_part_* of their carcass falls on it, it shall be unclean to you.
* `Lev 13:41` And he who has his hair fallen off from the *_part_* of his head toward his face, he is forehead-bald. He is clean.
* `Lev 14:21` "And if he is poor and cannot afford these things, then he shall take one lamb for a trespass-offering to be waved to make an atonement for him, one tenth-*_part_* of fine flour mingled with oil for a food-offering, a log of oil,
* `Lev 22:14` And if a man eats the holy thing unknowingly, then he shall add to it a fifth *_part_* and shall give it to the priest with the holy thing.
* `Lev 23:13` And the food-offering thereof shall be two tenth-parts of fine flour mingled with oil, an offering made by fire to the LORD for a sweet savor. And the drink-offering thereof shall be a fourth *_part_* of a hin of wine.
* `Lev 27:13` But if he will at all redeem it, then he shall add a fifth *_part_* of it to your estimation.
* `Lev 27:15` And if he who sanctified it will redeem his house, then he shall add the fifth *_part_* of the money of your estimation to it and it shall be his.
* `Lev 27:16` 'And if a man sanctifies to the LORD some *_part_* of a field of his possession, then your estimation shall be according to its seed. A homer of barley seed shall be valued at fifty shekels of silver.
* `Lev 27:19` And if he who sanctified the field will in any way redeem it, then he shall add the fifth *_part_* of the money of your estimation to it and it shall be assured to him.
* `Lev 27:22` And if a man sanctifies to the LORD a field which he has bought, which is not *_part_* of the fields of his possession,
* `Lev 27:27` And if it is an unclean beast, then he shall redeem it, according to your estimation, and shall add to it a fifth *_part_* of it. Or if it is not redeemed, then it shall be sold according to your estimation.
* `Lev 27:31` And if a man will at all redeem anything of his tithes, he shall add to it its fifth *_part_*.
* `Num 5:7` They shall confess their sin which they have done. And he shall recompense his trespass with its principal and add to it its fifth *_part_* and give it to him against whom he has trespassed.
* `Num 5:15` Then the man shall bring his wife to the priest and bring her offering for her, the tenth *_part_* of an ephah of barley-meal. He shall pour no oil upon it nor put frankincense upon it, for it is an offering of jealousy, an offering of memorial, bringing iniquity to remembrance.
* `Num 15:4` Then he who offers his offering to the LORD shall bring a food-offering of a tenth *_part_* of flour mingled with the fourth *_part_* of a hin of oil.
* `Num 15:5` And the fourth *_part_* of a hin of wine for a drink-offering you shall prepare with the burnt-offering or sacrifice for one lamb.
* `Num 15:6` Or for a ram, you shall prepare for a food-offering two tenth parts of flour mingled with the third *_part_* of a hin of oil.
* `Num 15:7` And for a drink-offering you shall offer the third *_part_* of a hin of wine for a sweet savor to the LORD.
* `Num 18:20` And the LORD spoke to Aaron, "You shall have no inheritance in their land, neither shall you have any *_part_* among them. I am your *_part_* and your inheritance among the children of Israel.
* `Num 18:26` "You shall also speak to the Levites and say to them, 'When you take from the children of Israel the tithes which I have given you from them for your inheritance, you shall offer up a heave-offering of it for the LORD, even a tenth *_part_* of the tithe.
* `Num 18:29` Out of all your gifts you shall offer every heave-offering of the LORD, from all the best of it, even the hallowed *_part_* of it.'
* `Num 22:41` And it came to pass on the next day, that Balak took Balaam and conducted him to the high places of Baal so that from there he might see the utmost *_part_* of the people.
* `Num 23:10` Who can count the dust of Jacob and the number of the fourth *_part_* of Israel? Let me die the death of the righteous, and let my last end be like his!"
* `Num 23:13` And Balak said to him, "Come, I pray you, with me to another place, from where you may see them. You shall see only the utmost *_part_* of them, but not all of them. And from there curse them for me."
* `Num 28:5` And a tenth *_part_* of an ephah of flour for a food-offering, mingled with a fourth *_part_* of a hin of beaten oil—
* `Num 28:7` And its drink-offering shall be the fourth *_part_* of a hin for one lamb—in the holy place you shall cause the strong wine to be poured to the LORD for a drink-offering;
* `Num 28:13` And a single tenth-*_part_* of flour mingled with oil for a food-offering for one lamb, for a burnt-offering of a sweet savor, a sacrifice made by fire to the LORD.
* `Num 28:14` And their drink-offering shall be half a hin of wine to a bull, the third *_part_* of a hin to a ram, and a fourth *_part_* of a hin to a lamb. This is the burnt-offering of every month throughout the months of the year.
* `Num 28:21` A single tenth-*_part_* you shall offer for every lamb, throughout the seven lambs;
* `Num 28:29` And a single tenth *_part_* to one lamb, throughout the seven lambs;
* `Num 29:4` And one tenth-*_part_* for one lamb, throughout the seven lambs;
* `Num 29:10` And a single tenth-*_part_* for one lamb, throughout the seven lambs;
* `Num 29:15` And a single tenth-*_part_* to each lamb of the fourteen lambs;
* `Deu 10:9` Therefore, Levi has no *_part_* nor inheritance with his brothers. The LORD is his inheritance, according as the LORD your God promised him.
* `Deu 12:12` And you shall rejoice before the LORD your God—you, your sons, your daughters, your men-servants, your women-servants, and the Levite who is within your gates, because he has no *_part_* nor inheritance with you.
* `Deu 14:27` And the Levite who is within your gates, you shall not forsake him, for he has no *_part_* nor inheritance with you.
* `Deu 14:29` Then the Levite (because he has no *_part_* nor inheritance with you), the stranger, the fatherless, and the widow who are within your gates shall come and shall eat and be satisfied so that the LORD your God may bless you in all the work of your hand which you do."
* `Deu 18:1` "The priests the Levites, even all the tribe of Levi, shall have no *_part_* nor inheritance with Israel. They shall eat the offerings of the LORD made by fire and his inheritance.
* `Deu 33:21` And he provided the first *_part_* for himself, because there, in a portion of the lawgiver, he was seated. And he came with the heads of the people. He executed the justice of the LORD and his judgments with Israel."
* `Jsh 14:4` For the children of Joseph were two tribes, Manasseh and Ephraim; therefore, they gave no *_part_* to the Levites in the land, except cities to dwell in with their suburbs for their livestock and for their substance.
* `Jsh 15:1` And the lot for the tribe of the children of Judah according to their families was to the border of Edom, even to the wilderness of Zin southward, at the uttermost *_part_* of the south border.
* `Jsh 15:5` And the east border was the Salt Sea, even to the end of the Jordan. And their border in the north quarter was from the bay of the sea, at the uttermost *_part_* of the Jordan.
* `Jsh 15:13` And to Caleb the son of Jephunneh he gave a *_part_* among the children of Judah, according to the commandment of the LORD to Joshua, even the city of Arba the father of Anak (which city is Hebron).
* `Jsh 18:7` But the Levites have no *_part_* among you, for the priesthood of the LORD is their inheritance. And Gad, Reuben, and half the tribe of Manasseh have received their inheritance beyond the Jordan on the east, which Moses the servant of the LORD gave them."
* `Jsh 19:9` Out of the portion of the children of Judah was the inheritance of the children of Simeon, for the *_part_* of the children of Judah was too much for them; therefore, the children of Simeon had their inheritance within their inheritance.
* `Jsh 22:25` For the LORD has made the Jordan a boundary between us and you, you children of Reuben and children of Gad. You have no *_part_* in the LORD." So your children shall make our children cease from fearing the LORD.'
* `Jsh 22:27` But it shall be a witness between us and you and our generations after us so that we may do the service of the LORD before him with our burnt-offerings, with our sacrifices, and with our peace-offerings, and that your children may not say to our children in time to come, "You have no *_part_* in the LORD."'
* `Rth 1:17` Where you die, I will die, and there I will be buried. May the LORD do so to me, and more also, if anything but death shall *_part_* you and me."
* `Rth 2:3` And she went, and came and gleaned in the field after the reapers. And she happened to come to a *_part_* of the field belonging to Boaz, who was of the kindred of Elimelech.
* `Rth 3:13` Stay this night, and it shall be in the morning, that if he will perform to you the *_part_* of a kinsman, good. Let him do the kinsman's *_part_*. But if he will not do the *_part_* of a kinsman to you, then I will do the *_part_* of a kinsman to you, as the LORD lives. Lie down until the morning."
* `1Sa 9:8` And the servant answered Saul again and said, "Behold, I have here at hand the fourth *_part_* of a shekel of silver. I will give that to the man of God to tell us our way."
* `1Sa 14:2` And Saul stayed in the uttermost *_part_* of Gibeah under a pomegranate tree which is in Migron. And the people who were with him were about six hundred men,
* `1Sa 23:20` Now therefore, O king, come down according to all the desire of your soul to come down, and our *_part_* shall be to deliver him into the king's hand."
* `1Sa 30:24` For who will listen to you in this matter? But as his *_part_* is who goes down to the battle, so shall his *_part_* be who remains by the goods. They shall share alike."
* `2Sa 14:6` And your servant had two sons, and the two of them strove together in the field, and there was no one to *_part_* them, but one smote the other and slew him.
* `2Sa 18:2` And David sent forth a third *_part_* of the people under the hand of Joab, a third *_part_* under the hand of Abishai the son of Zeruiah (Joab's brother), and a third *_part_* under the hand of Ittai the Gittite. And the king said to the people, "I myself will surely go forth with you also."
* `2Sa 20:1` And there happened to be a man of Belial there whose name was Sheba, the son of Bichri, a Benjaminite. And he blew a trumpet and said, "We have no *_part_* in David, neither do we have inheritance in the son of Jesse. Every man to his tents, O Israel."
* `1Ki 6:24` And five cubits was one wing of the cherub and five cubits the other wing of the cherub. From the uttermost *_part_* of one wing to the uttermost *_part_* of the other were ten cubits.
* `1Ki 6:31` And for the entrance of the oracle he made doors of olive tree. The lintel and side-posts were a fifth *_part_* of the wall.
* `1Ki 6:33` In the same manner he also made for the door of the temple posts of olive tree out of a fourth *_part_* of the wall.
* `2Ki 6:25` And there was a great famine in Samaria. And behold, they besieged it until a donkey's head was sold for eighty pieces of silver and the fourth *_part_* of a kab of dove's dung for five pieces of silver.
* `2Ki 7:5` And they rose in the twilight to go to the camp of the Syrians. And when they had come to the uttermost *_part_* of the camp of Syria, behold, there was no man there.
* `2Ki 7:8` And when these lepers came to the uttermost *_part_* of the camp, they went into one tent, ate and drank, and carried from there silver, gold, and clothing, and went and hid it. And they came back, entered into another tent, and carried from there also, and went and hid it.
* `2Ki 11:5` And he commanded them, saying, "This is the thing that you shall do: a third *_part_* of you who enter in on the sabbath shall even be keepers of the watch of the king's house,
* `2Ki 11:6` And a third *_part_* shall be at the gate of Sur, and a third *_part_* at the gate behind the guard. Thus you shall keep the watch of the house so that it is not broken down.
* `2Ki 18:23` Now therefore, I pray you, give pledges to my lord the king of Assyria, and I will deliver you two thousand horses, if you are able on your *_part_* to set riders upon them.
* `1Ch 12:29` And of the children of Benjamin, the kindred of Saul, three thousand, for until now the greatest *_part_* of them had kept the ward of the house of Saul.
* `2Ch 23:4` This is the thing that you shall do: a third *_part_* of you entering on the sabbath, of the priests and of the Levites, shall be gatekeepers of the doors,
* `2Ch 23:5` A third *_part_* shall be at the king's house, and a third *_part_* at the gate of the foundation. And all the people shall be in the courts of the house of the LORD.
* `2Ch 29:16` And the priests went into the inner *_part_* of the house of the LORD to cleanse it, and brought out all the uncleanness that they found in the temple of the LORD into the court of the house of the LORD. And the Levites took it and carried it out abroad into the brook Kidron.
* `Neh 1:9` But if you turn to me and keep my commandments and do them, though there were some of you driven to the uttermost *_part_* of the heaven, yet I will gather them from there and will bring them to the place where I have chosen to set my name.'
* `Neh 3:9` And next to them Rephaiah the son of Hur, the ruler of the half *_part_* of Jerusalem, repaired.
* `Neh 3:12` And next to him Shallum the son of Halohesh, the ruler of the half *_part_* of Jerusalem, repaired—he and his daughters.
* `Neh 3:14` But the dung-gate was repaired by Malchiah the son of Rechab, the ruler of *_part_* of Beth-haccerem. He built it, set up its doors, its locks, and its bars.
* `Neh 3:15` But the gate of the fountain was repaired by Shallun the son of Col-hozeh, the ruler of *_part_* of Mizpah. He built it, covered it, set up its doors, its locks, and its bars, and the wall of the pool of Siloah by the king's garden, and to the stairs that go down from the city of David.
* `Neh 3:16` After him Nehemiah the son of Azbuk, the ruler of the half *_part_* of Beth-zur, repaired to the place over against the sepulchers of David, and to the pool that was made, and to the house of the mighty.
* `Neh 3:17` After him the Levites repaired: Rehum the son of Bani. Next to him Hashabiah, the ruler of the half *_part_* of Keilah, repaired in his *_part_*.
* `Neh 3:18` After him their brothers, Bavai the son of Henadad, the ruler of the half *_part_* of Keilah, repaired.
* `Neh 5:11` I pray you, restore to them even this day their lands, their vineyards, their olive-groves, and their houses, also the hundredth *_part_* of the money, and of the grain, the wine, and the oil that you exact from them."
* `Neh 9:3` And they stood up in their place and read in the book of the law of the LORD their God for one fourth *_part_* of the day, and for another fourth *_part_* they confessed and worshiped the LORD their God.
* `Neh 10:32` We also made ordinances for ourselves to charge ourselves yearly with the third *_part_* of a shekel for the service of the house of our God:
* `Job 32:17` I will also answer my *_part_* and will also show my opinion.
* `Job 41:6` Shall the traders make a banquet of him? Shall they *_part_* him among the merchants?
* `Psa 5:9` For there is no faithfulness in their mouth. Their inward *_part_* is wickedness. Their throat is an open sepulcher. They flatter with their tongue.
* `Psa 22:18` They *_part_* my garments among them and cast lots upon my vesture.
* `Psa 51:6` Behold, you desire truth in the inward parts. And in the hidden *_part_* you shall make me to know wisdom.
* `Psa 118:7` The LORD takes my *_part_* with those who help me; therefore, I shall see my desire upon those who hate me.
* `Pro 8:26` While he had not yet made the earth, the fields, nor the highest *_part_* of the dust of the world.
* `Pro 8:31` Rejoicing in the habitable *_part_* of his earth. And my delights were with the sons of men.
* `Pro 17:2` A wise servant shall have rule over a son who causes shame, and shall have *_part_* of the inheritance among the brothers.
* `Isa 7:18` And it shall come to pass in that day, that the LORD will hiss for the fly that is in the uttermost *_part_* of the rivers of Egypt and for the bee that is in the land of Assyria.
* `Isa 24:16` From the uttermost *_part_* of the earth we have heard songs, even glory to the righteous. But I said, "My leanness, my leanness, woe to me! The treacherous dealers have dealt treacherously. Indeed, the treacherous dealers have dealt very treacherously."
* `Isa 36:8` Now therefore, give pledges, I pray you, to my master the king of Assyria, and I will give you two thousand horses, if you can on your *_part_* set riders upon them.
* `Isa 44:16` He burns *_part_* of it in the fire. With *_part_* of it he eats flesh. He roasts meat and is satisfied. Indeed, he warms himself and says, "Aha, I am warm. I have seen the fire."
* `Isa 44:19` And no one considers in his heart, neither is there knowledge nor understanding to say, "I have burned *_part_* of it in the fire. I have also baked bread upon its coals. I have roasted flesh and eaten it. And shall I make the rest of it an abomination? Shall I fall down to the stock of a tree?"
* `Ezk 4:11` You shall also drink water by measure, the sixth *_part_* of a hin. From time to time you shall drink.
* `Ezk 5:2` You shall burn with fire a third *_part_* in the midst of the city when the days of the siege are fulfilled. And you shall take a third *_part_* and smite around it with a knife. And a third *_part_* you shall scatter in the wind, and I will draw out a sword after them.
* `Ezk 5:12` A third *_part_* of you shall die with the pestilence, and with famine they shall be consumed in the midst of you. And a third *_part_* shall fall by the sword around you. And I will scatter a third *_part_* into all the winds and draw out a sword after them.
* `Ezk 45:11` The ephah and the bath shall be of one measure, so that the bath may contain the tenth *_part_* of a homer and the ephah the tenth *_part_* of a homer. Its measure shall be after the homer.
* `Ezk 45:13` "This is the oblation that you shall offer: the sixth *_part_* of an ephah of a homer of wheat, and you shall give the sixth *_part_* of an ephah of a homer of barley;
* `Ezk 45:14` Concerning the ordinance of oil, the bath of oil, you shall offer the tenth *_part_* of a bath out of the cor, which is a homer of ten baths (for ten baths are a homer);
* `Ezk 45:17` And it shall be the prince's *_part_* to give burnt-offerings, food-offerings, and drink-offerings in the feasts, in the new moons, and in the sabbaths, in all solemnities of the house of Israel. He shall prepare the sin-offering, the food-offering, the burnt-offering, and the peace-offerings to make reconciliation for the house of Israel."
* `Ezk 46:14` And you shall prepare a food-offering for it every morning, the sixth *_part_* of an ephah and the third *_part_* of a hin of oil to temper with the fine flour, a food-offering continually by a perpetual ordinance to the LORD.
* `Dan 1:2` And the Lord gave Jehoiakim king of Judah into his hand, with *_part_* of the vessels of the house of God, which he carried into the land of Shinar to the house of his god. And he brought the vessels into the treasure-house of his god.
* `Dan 2:33` His legs of iron, his feet *_part_* of iron and *_part_* of clay.
* `Dan 2:41` And whereas you saw the feet and toes, *_part_* of potter's clay and *_part_* of iron, the kingdom shall be divided, but there shall be in it some of the strength of the iron, because you saw the iron mixed with the miry clay.
* `Dan 2:42` And as the toes of the feet were *_part_* of iron and *_part_* of clay, so the kingdom shall be partly strong and partly broken.
* `Dan 5:5` In the same hour fingers of a man's hand came forth and wrote over against the candlestick upon the plaster of the wall of the king's palace. And the king saw the *_part_* of the hand that wrote.
* `Dan 5:24` Then the *_part_* of the hand was sent from him and this writing was written.
* `Dan 11:31` And forces shall stand on his *_part_*, and they shall pollute the sanctuary of strength and shall take away the daily sacrifice, and they shall place the abomination that makes desolate.
* `Amo 7:4` Thus the Lord GOD has shown to me, and behold, the Lord GOD called to contend by fire, and it devoured the great deep and ate up a *_part_*.
* `Zch 13:9` And I will bring the third *_part_* through the fire, and I will refine them as silver is refined and try them as gold is tried. They shall call on my name, and I will hear them. I will say, 'They are my people,' and they shall say, 'The LORD is our God.'"
* `Mrk 4:38` And he was in the back *_part_* of the boat asleep on a pillow. And they wake him, and say to him, "Master, do you not care that we perish?"
* `Mrk 9:40` For he who is not against us is on our *_part_*.
* `Mrk 13:27` And then he will send his angels and will assemble his elect from the four winds, 'from the uttermost *_part_* of the earth to the uttermost *_part_* of heaven.'
* `Luk 10:42` But one thing is needful, and Mary has chosen that good *_part_* which shall not be taken away from her."
* `Luk 11:36` If your whole body therefore is full of light, having no dark *_part_*, the whole shall be full of light, as when the bright shining of a candle gives you light."
* `Luk 11:39` And the Lord said to him, "Now you Pharisees make the outside of the cup and the platter clean, but your inward *_part_* is full of ravening and wickedness.
* `Luk 17:24` For as the lightning that lightens from one *_part_* under heaven shines to the other *_part_* under heaven, so the Son of man shall also be in his day.
* `Jhn 13:8` Peter says to him, "You shall never wash my feet." Jesus answered him, "If I do not wash you, you have no *_part_* with me."
* `Jhn 19:23` Then the soldiers, when they had crucified Jesus, took his garments and made four parts, to every soldier a *_part_*, and also his coat. Now the coat was without seam, woven from the top throughout.
* `Act 1:8` But you shall receive power after the Holy Spirit has come upon you. And you shall be witnesses to me in Jerusalem, in all Judea, in Samaria, and to the uttermost *_part_* of the earth."
* `Act 1:17` For he was numbered with us and had obtained *_part_* of this ministry."
* `Act 1:25` So that he may take *_part_* in this ministry and apostleship from which Judas by transgression fell in order to go to his own place."
* `Act 5:2` Kept back *_part_* of the price (his wife also being aware of it), and brought a certain *_part_* and laid it at the apostles' feet.
* `Act 5:3` But Peter said, "Ananias, why has Satan filled your heart to lie to the Holy Spirit and to keep back *_part_* of the value of the land?
* `Act 8:21` You have neither *_part_* nor lot in this matter, for your heart is not right in the sight of God.
* `Act 14:4` But the multitude of the city was divided. And *_part_* held with the Jews and *_part_* with the apostles.
* `Act 16:12` And from there to Philippi, which is the chief city of that *_part_* of Macedonia and a colony. And we were in that city staying some days.
* `Act 19:32` Some therefore cried one thing and some another, for the assembly was confused, and the greater *_part_* did not know why they had come together.
* `Act 23:6` But when Paul perceived that one *_part_* were Sadducees and the other Pharisees, he cried out in the council, "Men, brothers, I am a Pharisee, the son of a Pharisee. Concerning the hope and resurrection of the dead I am called in question."
* `Act 23:9` And there arose a great cry. And the scribes who were from the Pharisees' *_part_* arose and contended, saying, "We find no evil in this man. But if a spirit or an angel has spoken to him, let us not fight against God."
* `Act 27:12` And because the haven was not suitable to winter in, the greater *_part_* advised to depart from there also, if by any means they might attain to Phenice and winter there, which is a haven of Crete looking toward the southwest and northwest.
* `Act 27:41` And falling into a place where two seas met, they ran the ship aground. And the forepart stuck firmly and remained immovable, but the back *_part_* was broken with the violence of the waves.
* `Rom 11:25` For I do not wish, brothers, that you should be ignorant of this mystery (lest you should be wise in your own conceits), that blindness in *_part_* has happened to Israel until the fullness of the Gentiles has come in.
* `1Co 12:24` But our presentable parts have no need. But God has tempered the body together, having given more abundant honor to that *_part_* which lacked,
* `1Co 13:9` For we know in *_part_* and we prophesy in *_part_*.
* `1Co 13:10` But when that which is perfect has come, then that which is in *_part_* shall be done away.
* `1Co 13:12` For now we see through a mirror dimly, but then face to face. Now I know in *_part_*, but then I shall know even as I am also known.
* `1Co 15:6` After that, he was seen by more than five hundred brothers at once, of whom the greater *_part_* remain to this present, but some have fallen asleep.
* `1Co 16:17` I am glad of the coming of Stephanas, Fortunatus, and Achaicus, for that which was lacking on your *_part_*, they have supplied,
* `2Co 1:14` As also you have acknowledged us in *_part_*, that we are your rejoicing, even as you also are ours in the day of the Lord Jesus.
* `2Co 2:5` But if any has caused grief, he has not grieved me, but in *_part_*, so that I may not overcharge you all.
* `2Co 6:15` And what concord has Christ with Belial? Or what *_part_* has he who believes with an infidel?
* `Eph 4:16` From whom the whole body properly joined together and united by that which every joint supplies, according to the effectual working in the measure of every *_part_*, makes increase of the body to the edifying of itself in love.
* `Tit 2:8` Sound speech that cannot be condemned, so that he who is of the contrary *_part_* may be ashamed, having no evil thing to say concerning you.
* `Heb 2:14` Since then the children are partakers of flesh and blood, he also himself likewise took *_part_* of the same so that through death he might destroy him who had the power of death, that is, the devil,
* `Heb 7:2` To whom also Abraham gave a tenth *_part_* of all, first being by interpretation King of righteousness, and after that also King of Salem, which is, King of peace,
* `Heb 9:2` For there was a tabernacle made. In the first *_part_* was the candlestick, the table, and the show-bread, which is called the holy place.
* `1Pe 4:14` If you are reproached for the name of Christ, happy are you, for the Spirit of glory and of God rests upon you. On their *_part_* he is evil spoken of, but on your *_part_* he is glorified.
* `Rev 6:8` And I looked, and behold, a pale horse. And his name who sat on him was Death, and hell followed with him. And power was given to them over the fourth *_part_* of the earth to kill with sword, with hunger, with death, and with the beasts of the earth.
* `Rev 8:7` The first angel sounded, and there followed hail and fire mingled with blood, and they were cast upon the earth. And the third *_part_* of trees was burnt up, and all green grass was burnt up.
* `Rev 8:8` And the second angel sounded, and something like a great mountain burning with fire was cast into the sea. And the third *_part_* of the sea became blood.
* `Rev 8:9` And the third *_part_* of the creatures having life which were in the sea died. And the third *_part_* of the ships were destroyed.
* `Rev 8:10` And the third angel sounded, and there fell a great star from heaven, burning like a lamp, and it fell upon the third *_part_* of the rivers and upon the fountains of waters.
* `Rev 8:11` And the name of the star is called Wormwood. And the third *_part_* of the waters became wormwood, and many men died by the waters because they were made bitter.
* `Rev 8:12` And the fourth angel sounded, and the third *_part_* of the sun was smitten, along with the third *_part_* of the moon and the third *_part_* of the stars, so that the third *_part_* of them was darkened. And the day did not shine for a third *_part_* of it, and the night likewise.
* `Rev 9:15` And the four angels were released who were prepared for that hour, day, month, and year to slay the third *_part_* of men.
* `Rev 9:18` By these three the third *_part_* of men was killed: by the fire, by the smoke, and by the brimstone which issued out of their mouths.
* `Rev 11:13` And the same hour there was a great earthquake, and the tenth *_part_* of the city fell. And seven thousand men were killed in the earthquake. And the remnant were terrified and gave glory to the God of heaven.
* `Rev 12:4` And his tail drew the third *_part_* of the stars of heaven and cast them to the earth. And the dragon stood before the woman who was ready to deliver to devour her child as soon as it was born.
* `Rev 20:6` Blessed and holy is he who has *_part_* in the first resurrection. On such the second death has no power, but they shall be priests of God and of Christ and shall reign with him a thousand years.
* `Rev 21:8` But the fearful, unbelieving, the abominable, murderers, lewd men, sorcerers, idolaters, and all liars shall have their *_part_* in the lake which burns with fire and brimstone. This is the second death."
* `Rev 22:19` And if any man takes away from the words of the book of this prophecy, God will take away his *_part_* out of the tree of life, out of the holy city, and from the things which are written in this book.

_185 verses containing PART_

== PARTAKE

* `Rom 11:17` And if some of the branches are broken off, and you, being a wild olive-tree, are implanted among them, and with them *_partake_* of the root and fatness of the olive-tree,

_1 verse containing PARTAKE_

== PARTAKER

* `Psa 50:18` When you saw a thief, you consented with him. You have been *_partaker_* with adulterers.
* `1Co 9:10` Or does he say this altogether for our sakes? For our sakes no doubt this is written, so that he who plows should plow in hope, and that he who threshes in hope should be *_partaker_* of his hope.
* `1Co 9:23` And this I do for the gospel's sake so that I may be *_partaker_* of it with you.
* `1Co 10:30` For if I by grace am a *_partaker_*, why am I evil spoken of for that for which I give thanks?
* `1Ti 5:22` Do not hastily lay hands on any man, neither be *_partaker_* of other men's sins. Keep yourself pure.
* `2Ti 1:8` Do not be therefore ashamed of the testimony of our Lord, nor of me his prisoner, but be *_partaker_* of the afflictions of the gospel according to the power of God.
* `2Ti 2:6` The farmer who labors must be first *_partaker_* of the fruits.
* `1Pe 5:1` I exhort the elders who are among you as a fellow elder and a witness of the sufferings of Christ and also a *_partaker_* of the glory that shall be revealed:
* `2Jn 1:11` For he who wishes him happiness is *_partaker_* of his evil deeds.

_9 verses containing PARTAKER_

== PARTAKERS

* `Mth 23:30` And say, 'If we had been in the days of our fathers, we would not have been *_partakers_* with them in the blood of the prophets.'
* `Rom 15:27` It has pleased them truly, and their debtors they are. For if the Gentiles have been made *_partakers_* of their spiritual things, their duty is also to minister to them in carnal things.
* `1Co 9:12` If others are *_partakers_* of this power over you, are we not rather? Nevertheless, we have not used this power, but bear all things, lest we should hinder the gospel of Christ.
* `1Co 9:13` Do you not know that those who minister about holy things live from the things of the temple, and those who wait at the altar are *_partakers_* with the altar?
* `1Co 10:17` For we, being many, are one bread and one body, for we are all *_partakers_* of that one bread.
* `1Co 10:18` Behold Israel after the flesh: are those who eat the sacrifices not *_partakers_* of the altar?
* `1Co 10:21` You cannot drink the cup of the Lord and the cup of demons. You cannot be *_partakers_* of the Lord's table and of the table of demons.
* `2Co 1:7` And our hope for you is steadfast, knowing, that as you are *_partakers_* of the sufferings, so you shall also be of the consolation.
* `Eph 3:6` That the Gentiles should be fellow-heirs, fellow-members of the body, and fellow-*_partakers_* of his promise in Christ by the Gospel,
* `Eph 5:7` Therefore, do not be *_partakers_* with them.
* `Phl 1:7` Even as it is proper for me to think this of you all because I have you in my heart, for both in my bonds and in the defense and confirmation of the gospel, you all are *_partakers_* of my grace.
* `Col 1:12` Giving thanks to the Father, who has made us fit to be *_partakers_* of the inheritance of the saints in light.
* `1Ti 6:2` And those who have believing masters, let them not despise them because they are brothers, but rather do them service because they are faithful and beloved, *_partakers_* of the benefit. Teach and exhort these things.
* `Heb 2:14` Since then the children are *_partakers_* of flesh and blood, he also himself likewise took part of the same so that through death he might destroy him who had the power of death, that is, the devil,
* `Heb 3:1` Therefore, holy brothers, *_partakers_* of the heavenly calling, consider the Apostle and High Priest of our profession, Christ Jesus,
* `Heb 3:14` For we are made *_partakers_* of Christ if we hold the beginning of our confidence steadfast to the end,
* `Heb 6:4` For it is impossible for those who have been once enlightened, have tasted the heavenly gift, have been made *_partakers_* of the Holy Spirit,
* `Heb 12:8` But if you are without chastisement, of which all are *_partakers_*, then you are illegitimate sons and not sons.
* `Heb 12:10` For they truly for a few days chastened us after their own pleasure, but he for our profit, so that we might be *_partakers_* of his holiness.
* `1Pe 4:13` But rejoice, seeing you are *_partakers_* of Christ's sufferings, so that when his glory is revealed you may also be glad with exceeding joy.
* `2Pe 1:4` Through which exceedingly great and precious promises are given to us, so that by these you might be *_partakers_* of the divine nature, having escaped the corruption that is in the world through lust.
* `Rev 18:4` And I heard another voice from heaven, saying, "Come out of her, my people, so that you are not *_partakers_* of her sins and that you do not receive any of her plagues.

_22 verses containing PARTAKERS_

== PARTAKES

* `Heb 5:13` For everyone who *_partakes_* of milk is unskillful in the word of righteousness, for he is a baby.

_1 verse containing PARTAKES_

== PARTED

* `Gen 2:10` And a river went out of Eden to water the garden. And from there it was *_parted_* and became into four heads.
* `2Ki 2:11` And it came to pass, as they still went on and talked, that behold, there appeared a chariot of fire and horses of fire and *_parted_* them both apart. And Elijah went up by a whirlwind into heaven.
* `2Ki 2:14` And he took the mantle of Elijah that fell from him and smote the waters and said, "Where is the LORD God of Elijah?" And when he also had smitten the waters, they *_parted_* here and there, and Elisha went over.
* `Job 38:24` By what way is the light *_parted_*, which scatters the east wind upon the earth?
* `Mth 27:35` And when they had crucified him, they divided his garments by casting lots so that it might be fulfilled which was spoken by the prophet, "They *_parted_* my garments among them, and upon my vesture they cast lots."
* `Mrk 15:24` And when they had crucified him, they *_parted_* his garments, casting lots upon them, what every man should take.
* `Luk 23:34` Then Jesus said, "Father, forgive them, for they do not know what they do." And they *_parted_* his clothing and cast lots.
* `Luk 24:51` And it came to pass, while he was blessing them, he *_parted_* from them and was carried up into heaven.
* `Jhn 19:24` Therefore, they said among themselves, "Let us not rend it, but cast lots for it to decide whose it shall be," so that the Scripture might be fulfilled, which says, "They *_parted_* my clothing among them, and for my vesture they cast lots." Therefore the soldiers did these things.
* `Act 2:45` And sold their possessions and goods and *_parted_* them to all men, as every man had need.
* `Phm 1:15` For perhaps he was therefore *_parted_* from you for a season so that you should receive him forever,

_11 verses containing PARTED_

== PARTHIANS

* `Act 2:9` *_Parthians_*, Medes, Elamites, the dwellers in Mesopotamia, in Judea, Cappadocia, in Pontus, Asia,

_1 verse containing PARTHIANS_

== PARTIAL

* `Mal 2:9` "Therefore, I have also made you contemptible and base before all the people, according as you have not kept my ways, but have been *_partial_* in the law."
* `Jms 2:4` Are you not then *_partial_* in yourselves and have become judges with evil thoughts?

_2 verses containing PARTIAL_

== PARTIALITY

* `1Ti 5:21` I charge you before God and the Lord Jesus Christ and the elect angels, that you observe these things without preferring one before another, doing nothing by *_partiality_*.
* `Jms 3:17` But the wisdom that is from above is first pure, then peaceable, gentle, easy to be entreated, full of mercy and good fruits, without *_partiality_*, and without hypocrisy.

_2 verses containing PARTIALITY_

== PARTICULAR

* `1Co 12:27` Now you are the body of Christ and members in *_particular_*.
* `Eph 5:33` Nevertheless, let each of you in *_particular_* thus love his wife even as himself, and the wife see that she reverences her husband.

_2 verses containing PARTICULAR_

== PARTICULARLY

* `Act 21:19` And when he had saluted them, he declared *_particularly_* what things God had wrought among the Gentiles by his ministry.
* `Heb 9:5` And over it the cherubim of glory shadowing the mercy-seat, of which we cannot now speak *_particularly_*.

_2 verses containing PARTICULARLY_

== PARTIES

* `Exo 22:9` For all manner of trespass, whether it is for ox, for donkey, for sheep, for clothing, or for any manner of lost thing which another challenges to be his, the cause of both *_parties_* shall come before the judges. And he whom the judges condemn shall pay double to his neighbor.

_1 verse containing PARTIES_

== PARTING

* `Ezk 21:21` For the king of Babylon stood at the *_parting_* of the way, at the head of the two ways, to use divination: he shook the arrows, he consulted with images, and he examined the liver.

_1 verse containing PARTING_

== PARTITION

* `1Ki 6:21` So Solomon overlaid the house inside with pure gold. And he made a *_partition_* by the chains of gold before the oracle and he overlaid it with gold.
* `Eph 2:14` For he is our peace, who has made both one and has broken down the middle wall of *_partition_* between us,

_2 verses containing PARTITION_

== PARTLY

* `Dan 2:42` And as the toes of the feet were part of iron and part of clay, so the kingdom shall be *_partly_* strong and *_partly_* broken.
* `1Co 11:18` For first of all, when you come together in the church, I hear that there are divisions among you, and I *_partly_* believe it.
* `Heb 10:33` *_Partly_* while you were made a spectacle both by reproaches and afflictions, and *_partly_* while you became companions of those who were thus used.

_3 verses containing PARTLY_

== PARTNER

* `Pro 29:24` Whoever is *_partner_* with a thief hates his own soul. He hears cursing and does not disclose it.
* `2Co 8:23` If any ask about Titus, he is my *_partner_* and fellow-worker concerning you, or about our brothers, they are the messengers of the churches and the glory of Christ.
* `Phm 1:17` If you account me therefore a *_partner_*, receive him as you would me.

_3 verses containing PARTNER_

== PARTNERS

* `Luk 5:7` And they beckoned to their *_partners_* who were in the other boat that they should come and help them. And they came and filled both boats so that they began to sink.
* `Luk 5:10` And so were James and John the sons of Zebedee, who were *_partners_* with Simon. And Jesus said to Simon, "Do not fear. From now on you shall catch men."

_2 verses containing PARTNERS_

== PARTRIDGE

* `1Sa 26:20` Now therefore, do not let my blood fall to the earth before the face of the LORD, for the king of Israel has come out to seek a flea, as when one hunts a *_partridge_* in the mountains."
* `Jer 17:11` As the *_partridge_* sits on eggs and does not hatch them, so he who gets riches, and not by right, shall leave them in the midst of his days, and at his end shall be a fool."

_2 verses containing PARTRIDGE_

== PARTS

* `Gen 47:24` And it shall come to pass in the increase, that you shall give the fifth part to Pharaoh, and four *_parts_* shall be your own, for seed of the field, for your food, for those of your households, and for food for your little ones."
* `Lev 1:8` And the priests, Aaron's sons, shall lay the *_parts_*, the head, and the fat in order upon the wood that is on the fire which is upon the altar.
* `Lev 11:3` Whatever *_parts_* the hoof, is cloven-footed, and chews the cud among the beasts, that you shall eat.
* `Lev 14:10` "And on the eighth day he shall take two male lambs without blemish, one ewe-lamb of the first year without blemish, three tenth-*_parts_* of fine flour for a food-offering mingled with oil, and one log of oil.
* `Lev 22:23` Either a bull or a lamb that has anything superfluous or lacking in his *_parts_*, that you may offer for a voluntary-offering, but for a vow it shall not be accepted.
* `Lev 23:13` And the food-offering thereof shall be two tenth-*_parts_* of fine flour mingled with oil, an offering made by fire to the LORD for a sweet savor. And the drink-offering thereof shall be a fourth part of a hin of wine.
* `Lev 23:17` You shall bring out of your habitations two wave-loaves. They shall be made of two tenth-*_parts_* of fine flour and they shall be baked with leaven. They are the first-fruits to the LORD.
* `Lev 24:5` "And you shall take fine flour and bake twelve cakes with it. Two tenth-*_parts_* shall be in one cake.
* `Num 10:5` When you blow an alarm, the camps that lie on the east *_parts_* shall go forward.
* `Num 11:1` And when the people complained, it displeased the LORD. And the LORD heard it and his anger was kindled, and the fire of the LORD burnt among them and consumed those who were in the uttermost *_parts_* of the camp.
* `Num 15:6` Or for a ram, you shall prepare for a food-offering two tenth *_parts_* of flour mingled with the third part of a hin of oil.
* `Num 15:9` You shall bring with a bull a food-offering of three tenth *_parts_* of flour mingled with half a hin of oil.
* `Num 28:9` 'And on the sabbath-day [you shall offer] two lambs of the first year without spot and two tenth-*_parts_* of flour for a food-offering mingled with oil and its drink-offering.
* `Num 28:12` Three tenth-*_parts_* of flour for a food-offering, mingled with oil, for one bull; two tenth-*_parts_* of flour for a food-offering, mingled with oil, for one ram;
* `Num 28:20` And their food-offering shall be of flour mingled with oil; three tenth-*_parts_* you shall offer for a bull and two tenth-*_parts_* for a ram;
* `Num 28:28` And their food-offering of flour mingled with oil—three tenth-*_parts_* to one bull, two tenth-*_parts_* to one ram,
* `Num 29:3` And their food-offering shall be of flour mingled with oil—three tenth-*_parts_* for a bull, two tenth-*_parts_* for a ram,
* `Num 29:9` And their food-offering shall be of flour mingled with oil—three tenth-*_parts_* to a bull, two tenth-*_parts_* to one ram,
* `Num 29:14` And their food-offering shall be of flour mingled with oil—three tenth-*_parts_* to every bull of the thirteen bulls, two tenth-*_parts_* to each ram of the two rams,
* `Num 31:27` And divide the plunder into two *_parts_* between those who took the war upon them, who went out to battle, and between all the congregation.
* `Deu 14:6` And every beast that *_parts_* the hoof and has the hoof split in two and chews the cud among the beasts, that you shall eat.
* `Deu 19:3` You shall prepare yourself a way and divide into three *_parts_* the limits of your land which the LORD your God gives you to inherit so that every slayer may flee there.
* `Deu 30:4` If any of your outcasts are driven out to the uttermost *_parts_* of the heavens, from there the LORD your God will gather you, and from there he will bring you.
* `Jsh 18:5` And they shall divide it into seven *_parts_*. Judah shall abide in their border on the south, and the house of Joseph shall abide in their borders on the north.
* `Jsh 18:6` You shall therefore describe the land in seven *_parts_* and bring the description here to me so that I may cast lots for you here before the LORD our God.
* `Jsh 18:9` And the men went and passed through the land, described it by cities in seven *_parts_* in a book, and came back to Joshua to the host at Shiloh.
* `1Sa 5:9` And it was so, that after they had carried it there, the hand of the LORD was against the city with a very great destruction, and he smote the men of the city both small and great, and they had emerods in their secret *_parts_*.
* `1Sa 24:3` And he came to the sheep-folds by the way, where there was a cave, and Saul went in to cover his feet. And David and his men remained in the innermost *_parts_* of the cave.
* `2Sa 19:43` And the men of Israel answered the men of Judah and said, "We have ten *_parts_* in the king, and we have also more right in David than you. Why then did you despise us so that our advice should not be first had in bringing back our king?" And the words of the men of Judah were fiercer than the words of the men of Israel.
* `1Ki 6:38` And in the eleventh year, in the month of Bul (which is the eighth month), the house was finished throughout all its *_parts_* and according to all its fashion. So he was seven years in building it.
* `1Ki 16:21` Then the people of Israel were divided into two *_parts_*: half of the people followed Tibni the son of Ginath to make him king, and half followed Omri.
* `2Ki 11:7` And two *_parts_* of all you who go forth on the sabbath, even they shall keep the watch of the house of the LORD around the king.
* `Neh 11:1` And the rulers of the people dwelt at Jerusalem. The rest of the people also cast lots to bring one of ten to dwell in Jerusalem the holy city, and nine *_parts_* to dwell in other cities.
* `Job 10:8` Your hands have made me and fashioned me in all my *_parts_*, yet you destroy me.
* `Job 26:14` Behold, these are *_parts_* of his ways, and how little a portion is heard of him! But the thunder of his power, who can understand?"
* `Job 38:36` Who has put wisdom in the inward *_parts_*? Or who has given understanding to the heart?
* `Job 41:12` I will not conceal his *_parts_*, nor his power, nor his orderly proportion.
* `Job 41:23` The hanging *_parts_* of his flesh are joined together. They are firm in themselves. They cannot be moved.
* `Psa 2:8` Ask of me, and I will give you the heathen for your inheritance and the uttermost *_parts_* of the earth for your possession.
* `Psa 51:6` Behold, you desire truth in the inward *_parts_*. And in the hidden part you shall make me to know wisdom.
* `Psa 63:9` But those who seek my soul to destroy it shall go into the lower *_parts_* of the earth.
* `Psa 65:8` Also those who dwell in the uttermost *_parts_* are in awe of your signs. You make the outgoings of the morning and evening to rejoice.
* `Psa 136:13` To him who divided the Red Sea into *_parts_*—for his mercy endures forever—
* `Psa 139:9` If I take the wings of the morning and dwell in the uttermost *_parts_* of the sea,
* `Psa 139:15` My substance was not hid from you when I was made in secret and skillfully formed in the lowest *_parts_* of the earth.
* `Pro 18:8` The words of a gossiper are like dainty morsels, and they go down into the innermost *_parts_* of the belly.
* `Pro 18:18` The lot causes contentions to cease and *_parts_* between the mighty.
* `Pro 20:27` The spirit of man is the candle of the LORD, searching all the inward *_parts_* of the belly.
* `Pro 20:30` The blueness of a wound cleanses away evil, and so do stripes to the inward *_parts_* of the belly.
* `Pro 26:22` The words of a gossiper are like dainty morsels, and they go down into the innermost *_parts_* of the belly.
* `Isa 3:17` Therefore the Lord will smite with a scab the crown of the head of the daughters of Zion, and the LORD will uncover their secret *_parts_*."
* `Isa 14:13` For you have said in your heart, 'I will ascend into heaven. I will exalt my throne above the stars of God. I will also sit upon the mountain of the congregation in the uttermost *_parts_* of the north.
* `Isa 16:11` Therefore, my heart shall sound like a harp for Moab and my inward *_parts_* for Kir-haresh.
* `Isa 44:23` Sing, O heavens, for the LORD has done it. Shout, you lower *_parts_* of the earth. Break forth into singing, you mountains, O forest, and every tree therein, for the LORD has redeemed Jacob and glorified himself in Israel.
* `Jer 31:33` "But this shall be the covenant that I will make with the house of Israel after those days," says the LORD, "I will put my law in their inward *_parts_* and write it in their hearts. And I will be their God, and they shall be my people.
* `Jer 34:18` And I will give the men who have transgressed my covenant, who have not performed the words of the covenant which they had made before me when they cut the calf in two and passed between its *_parts_*—
* `Jer 34:19` The princes of Judah, the princes of Jerusalem, the eunuchs, the priests, and all the people of the land, who passed between the *_parts_* of the calf—
* `Ezk 26:20` Then I will bring you down with those who descend into the pit, with the people of old time. I will set you in the low *_parts_* of the earth, in places desolate of old, with those who go down to the pit, so that you are not inhabited, but I shall set glory in the land of the living.
* `Ezk 31:14` To the end that none of all the trees by the waters shall exalt themselves for their height, nor shoot up their top among the thick boughs, nor their trees stand up in their height, even all that drink water. For they are all delivered to death, to the nether *_parts_* of the earth, in the midst of the children of men, with those who go down to the pit."
* `Ezk 31:16` I made the nations to shake at the sound of his fall when I cast him down to the grave with those who descend into the pit. And all the trees of Eden, the choice and best of Lebanon, all that drink water, shall be comforted in the nether *_parts_* of the earth.
* `Ezk 31:18` "To whom are you thus like in glory and in greatness among the trees of Eden? Yet you shall be brought down with the trees of Eden to the nether *_parts_* of the earth. You shall lie in the midst of the uncircumcised, with those who are slain by the sword. This is Pharaoh and all his multitude,"' says the Lord GOD."
* `Ezk 32:18` "Son of man, wail for the multitude of Egypt and cast them down, even her and the daughters of the famous nations, to the nether *_parts_* of the earth with those who go down into the pit.
* `Ezk 32:24` "There is Elam and all her multitude around her grave. All of them are slain, fallen by the sword, who have gone down uncircumcised into the nether *_parts_* of the earth, who caused their terror in the land of the living. Yet they have borne their shame with those who go down to the pit.
* `Ezk 38:15` And you shall come from your place out of the north *_parts_*—you and many people with you, all of them riding upon horses, a great company and a mighty army.
* `Ezk 39:2` And I will turn you back, lead you on, and cause you to come from the north *_parts_*, and I will bring you upon the mountains of Israel.
* `Ezk 48:8` "And by the border of Judah, from the east side to the west side, shall be the offering which you shall offer of twenty-five thousand reeds in breadth and in length as one of the other *_parts_*, from the east side to the west side. And the sanctuary shall be in the midst of it.
* `Joe 2:20` But I will remove far from you the northern army and drive him into a land barren and desolate with his face toward the east sea and his back *_parts_* toward the utmost sea, and his odious scent shall come up and his ill savor shall come up, because he has worked proudly."
* `Zch 13:8` And it shall come to pass, that in all the land," says the LORD, "two *_parts_* therein shall be cut off and die, but the third shall be left therein.
* `Mth 2:22` But when he heard that Archelaus reigned in Judea in place of his father Herod, he was afraid to go there. And being warned by God in a dream, he turned aside into the *_parts_* of Galilee.
* `Mth 12:42` The queen of the south shall rise up in the judgment with this generation and condemn it because she came from the uttermost *_parts_* of the earth to hear the wisdom of Solomon, and behold, one greater than Solomon is here.
* `Mrk 8:10` And immediately he entered into a boat with his disciples and came into the *_parts_* of Dalmanutha.
* `Luk 11:31` The queen of the south shall rise up in the judgment with the men of this generation and condemn them. For she came from the utmost *_parts_* of the earth to hear the wisdom of Solomon, and behold, someone greater than Solomon is here.
* `Jhn 19:23` Then the soldiers, when they had crucified Jesus, took his garments and made four *_parts_*, to every soldier a part, and also his coat. Now the coat was without seam, woven from the top throughout.
* `Act 2:10` Phrygia, Pamphylia, in Egypt, in the *_parts_* of Libya around Cyrene, strangers of Rome, both Jews and Proselytes,
* `Act 20:2` And when he had gone over those *_parts_* and had given them much exhortation, he came into Greece,
* `Rom 15:23` But now having no more place in these *_parts_* and having a great desire these many years to come to you,
* `1Co 12:23` And those members of the body which we think to be less honorable, upon these we bestow more abundant honor. And our unpresentable *_parts_* have more abundant modesty,
* `1Co 12:24` But our presentable *_parts_* have no need. But God has tempered the body together, having given more abundant honor to that part which lacked,
* `Eph 4:9` Now that "he ascended," what is it but that he also descended first into the lower *_parts_* of the earth?
* `Rev 16:19` And the great city was divided into three *_parts_*, and the cities of the nations fell. And great Babylon came in remembrance before God, to give to her the cup of the wine of the fierceness of his wrath.

_80 verses containing PARTS_

== PARUAH

* `1Ki 4:17` Jehoshaphat the son of *_Paruah_*, in Issachar;

_1 verse containing PARUAH_

== PARVAIM

* `2Ch 3:6` And he garnished the house with precious stones for beauty. And the gold was gold of *_Parvaim_*.

_1 verse containing PARVAIM_

