= PERAZIM - PESTLE
:toc:

== PERAZIM

* `2Sa 5:20` And David came to Baal-*_perazim_*, and David smote them there and said, "The LORD has broken forth upon my enemies before me like a breach of waters." Therefore, he called the name of that place Baal-*_perazim_*.
* `1Ch 14:11` So they came up to Baal-*_perazim_*. And David smote them there. Then David said, "God has broken in upon my enemies by my hand like the breaking forth of waters." Therefore, they called the name of that place Baal-*_perazim_*.
* `Isa 28:21` For the LORD will rise as on mount *_Perazim_*, he will be angry as in the valley of Gibeon, so that he may do his work, his strange work, and bring to pass his act, his strange act.

_3 verses containing PERAZIM_

== PERCEIVE

* `Gen 19:33` And they made their father drink wine that night. And the first-born went in and lay with her father, and he did not *_perceive_* when she lay down, nor when she arose.
* `Gen 19:35` And they made their father drink wine that night also. And the younger arose and lay with him, and he did not *_perceive_* when she lay down, nor when she arose.
* `Deu 29:4` Yet the LORD has not given you a heart to *_perceive_*, eyes to see, and ears to hear to this day.
* `Jsh 22:31` And Phinehas the son of Eleazar the priest said to the children of Reuben, to the children of Gad, and to the children of Manasseh, "This day we *_perceive_* that the LORD is among us because you have not committed this trespass against the LORD. Now you have delivered the children of Israel out of the hand of the LORD."
* `1Sa 12:17` Is it not wheat-harvest today? I will call to the LORD, and he will send thunder and rain so that you may *_perceive_* and see that your wickedness is great which you have done in the sight of the LORD in asking for yourselves a king."
* `2Sa 19:6` In that you love your enemies and hate your friends. For you have declared this day that you regard neither princes nor servants. For this day I *_perceive_* that if Absalom had lived and all of us had died this day then it would have pleased you.
* `2Ki 4:9` And she said to her husband, "Behold now, I *_perceive_* that this is a holy man of God who passes by us continually.
* `Job 9:11` Behold, he goes by me, and I do not see him. He passes on also, but I do not *_perceive_* him.
* `Job 14:21` His sons come to honor, and he does not know it. And they are brought low, but he does not *_perceive_* it of them.
* `Job 23:8` Behold, I go forward, but he is not there. I go backward, but I cannot *_perceive_* him.
* `Job 33:14` For God speaks once, even twice, yet man does not *_perceive_* it.
* `Pro 1:2` To know wisdom and instruction, to *_perceive_* the words of understanding,
* `Pro 14:7` Go from the presence of a foolish man, when you do not *_perceive_* in him the lips of knowledge.
* `Ecc 3:22` Therefore, I *_perceive_* that there is nothing better than that a man should rejoice in his own works, for that is his portion. For who shall bring him to see what shall be after him?
* `Isa 6:9` And he said, "Go, and tell this people, 'In hearing you hear, but do not understand. In seeing you see, but do not *_perceive_*.'
* `Isa 33:19` You shall not see a fierce people, a people of deeper speech than you can *_perceive_*, of a stammering tongue that you cannot understand.
* `Mth 13:14` And in them the prophecy of Isaiah is fulfilled, which says, 'By hearing you shall hear and shall not understand, and seeing you shall see and shall not *_perceive_*.
* `Mrk 4:12` So that 'seeing they may see and not *_perceive_*, and hearing they may hear and not understand, lest at any time they should be converted and their sins should be forgiven.'"
* `Mrk 7:18` And he says to them, "Are you so void of understanding also? Do you not *_perceive_*, that whatever thing from outside enters into the man, it cannot defile him,
* `Mrk 8:17` And when Jesus knew it, he says to them, "Why do you discuss that you have no bread? Do you still not *_perceive_* or understand? Is your heart still hardened?
* `Luk 6:41` And why do you behold the mote that is in your brother's eye, but not *_perceive_* the beam that is in your own eye?
* `Luk 8:46` And Jesus said, "Somebody has touched me, for I *_perceive_* that power has gone out of me."
* `Luk 9:45` But they did not understand this saying, and it was hid from them so that they did not *_perceive_* it. And they feared to ask him concerning that saying.
* `Luk 12:55` And when you *_perceive_* the south wind blowing, you say, 'There will be heat,' and it comes to pass.
* `Jhn 4:19` The woman says to him, "Sir, I *_perceive_* that you are a prophet.
* `Jhn 12:19` The Pharisees therefore said among themselves, "Do you *_perceive_* how you prevail nothing? Behold, the world has gone after him."
* `Act 8:23` For I *_perceive_* that you are in the gall of bitterness and in the bond of iniquity."
* `Act 10:34` Then Peter opened his mouth, and said, "In truth I *_perceive_* that God is no respecter of persons.
* `Act 17:22` Then Paul stood in the midst of Mars-hill, and said, "Men of Athens, I *_perceive_* that in all things you are too superstitious.
* `Act 27:10` And said to them, "Sirs, I *_perceive_* that this voyage will be with hurt and much damage, not only of the cargo and the ship, but also of our lives."
* `Act 28:26` Saying, 'Go to this people, and say, "Hearing you shall hear and shall not understand, and seeing you shall see and not *_perceive_*.
* `2Co 7:8` For though I made you sorry with a letter, I do not repent, though I did repent. For I *_perceive_* that the same epistle has made you sorry, though it was only for a season.

_32 verses containing PERCEIVE_

== PERCEIVED

* `Jdg 6:22` And when Gideon *_perceived_* that he was an angel of the LORD, Gideon said, "Alas, O Lord GOD! For because I have seen an angel of the LORD face to face."
* `1Sa 3:8` And the LORD called Samuel again the third time. And he arose and went to Eli and said, "Here I am. You called me." And Eli *_perceived_* that the LORD had called the child.
* `1Sa 28:14` And he said to her, "What is his form?" And she said, "An old man comes up, and he is covered with a mantle." And Saul *_perceived_* that it was Samuel, and he stooped with his face to the ground and bowed himself.
* `2Sa 5:12` And David *_perceived_* that the LORD had established him king over Israel and that he had exalted his kingdom for his people Israel's sake.
* `2Sa 12:19` But when David saw that his servants whispered, David *_perceived_* that the child was dead. Therefore, David said to his servants, "Is the child dead?" And they said, "He is dead."
* `2Sa 14:1` Now Joab the son of Zeruiah *_perceived_* that the king's heart was toward Absalom.
* `1Ki 22:33` And it came to pass when the captains of the chariots *_perceived_* that it was not the king of Israel, that they turned back from pursuing him.
* `1Ch 14:2` And David *_perceived_* that the LORD had confirmed him king over Israel, for his kingdom was exalted on high because of his people Israel.
* `2Ch 18:32` For it came to pass, that when the captains of the chariots *_perceived_* that it was not the king of Israel, they turned back again from pursuing him.
* `Neh 6:12` And behold, I *_perceived_* that God had not sent him, but that he pronounced this prophecy against me, for Tobiah and Sanballat had hired him.
* `Neh 6:16` And it came to pass when all our enemies heard of it and all the heathen who were around us saw these things, that they were much cast down in their own eyes, for they *_perceived_* that this work was wrought by our God.
* `Neh 13:10` And I *_perceived_* that the portions of the Levites had not been given to them, for the Levites and the singers who did the work had each fled to his field.
* `Est 4:1` When Mordecai *_perceived_* all that was done, Mordecai rent his clothes and put on sackcloth with ashes, went out into the midst of the city, and cried with a loud and bitter cry.
* `Job 38:18` Have you *_perceived_* the breadth of the earth? Declare if you know it all.
* `Ecc 1:17` And I gave my heart to know wisdom and to know madness and folly. I *_perceived_* that this also is vexation of spirit.
* `Ecc 2:14` The wise man's eyes are in his head, but the fool walks in darkness. And I myself *_perceived_* also that one event happens to them all.
* `Isa 64:4` For since the beginning of the world men have not heard, nor *_perceived_* by the ear, neither has the eye seen, O God, besides you, what he has prepared for him who waits for him.
* `Jer 23:18` For who has stood in the counsel of the LORD and has *_perceived_* and heard his word? Who has marked his word and heard it?
* `Jer 38:27` Then all the princes came to Jeremiah and asked him, and he told them according to all these words that the king had commanded. So they left off speaking with him, for the matter was not *_perceived_*.
* `Mth 16:8` When Jesus *_perceived_* this, he said to them, "O you of little faith, why do you discuss among yourselves that you have brought no bread?
* `Mth 21:45` And when the chief priests and Pharisees had heard his parables, they *_perceived_* that he spoke of them.
* `Mth 22:18` But Jesus *_perceived_* their wickedness, and said, "Why do you test me, you hypocrites?
* `Mrk 2:8` And immediately, when Jesus *_perceived_* in his spirit that they thus reasoned within themselves, he said to them, "Why do you reason these things in your hearts?
* `Luk 1:22` And when he came out, he could not speak to them. And they *_perceived_* that he had seen a vision in the temple, for he beckoned to them and remained speechless.
* `Luk 5:22` But when Jesus *_perceived_* their thoughts, he, answering, said to them, "What do you reason in your hearts?
* `Luk 20:19` And the chief priests and the scribes the same hour sought to lay hands on him, and they feared the people, for they *_perceived_* that he had spoken this parable against them.
* `Luk 20:23` But he *_perceived_* their craftiness and said to them, "Why do you test me?
* `Jhn 6:15` When Jesus therefore *_perceived_* that they would come and take him by force to make him a king, he departed again to a mountain by himself alone.
* `Act 4:13` Now when they saw the boldness of Peter and John and *_perceived_* that they were unlearned and ignorant men, they marveled and they took knowledge of them, that they had been with Jesus.
* `Act 23:6` But when Paul *_perceived_* that one part were Sadducees and the other Pharisees, he cried out in the council, "Men, brothers, I am a Pharisee, the son of a Pharisee. Concerning the hope and resurrection of the dead I am called in question."
* `Act 23:29` Whom I *_perceived_* to be accused of questions of their law, but to have nothing laid to his charge worthy of death, or of bonds.
* `Gal 2:9` And when James, Cephas, and John, who seemed to be pillars, *_perceived_* the grace that was given to me, they gave to Barnabas and me the right hands of fellowship so that we should go to the heathen and they to the circumcision.

_32 verses containing PERCEIVED_

== PERCEIVES

* `Pro 31:18` [TET] She *_perceives_* that her merchandise is good. Her candle does not go out by night.

_1 verse containing PERCEIVES_

== PERCEIVING

* `Mrk 12:28` And one of the scribes came, and having heard them reasoning together and *_perceiving_* that he had answered them well, asked him, "Which is the first commandment of all?"
* `Luk 9:47` And Jesus *_perceiving_* the thought of their heart, took a child and set him by him,
* `Act 14:9` The same heard Paul speak, who, steadfastly beholding him and *_perceiving_* that he had faith to be healed,

_3 verses containing PERCEIVING_

== PERDITION

* `Jhn 17:12` While I was with them in the world, I kept them in your name. Those whom you gave to me I have kept, and not one of them is lost but the son of *_perdition_*, so that the Scripture might be fulfilled.
* `Phl 1:28` And in nothing terrified by your adversaries—which is to them an evident token of *_perdition_*, but to you of salvation, and that from God.
* `2Th 2:3` Let no man deceive you by any means. For that day shall not come unless the falling away comes first and that man of sin is revealed, the son of *_perdition_*,
* `1Ti 6:9` But those who wish to be rich fall into temptation, a snare, and into many foolish and hurtful lusts which drown men in destruction and *_perdition_*.
* `Heb 10:39` But we are not of those who draw back to *_perdition_*, but of those who believe to the saving of the soul.
* `2Pe 3:7` But the present heavens and the earth are kept in store by the same word, reserved to fire against the day of judgment and *_perdition_* of ungodly men.
* `Rev 17:8` The beast that you saw, it was and is no more. And it shall ascend out of the bottomless pit and go into *_perdition_*. And those who dwell on the earth shall wonder, whose names were not written in the book of life from the foundation of the world, when they behold the beast that was, is no more, and yet is.
* `Rev 17:11` And the beast that was and is no more, he is also an eighth, and belongs to the seven and goes into *_perdition_*.

_8 verses containing PERDITION_

== PERES

* `Dan 5:28` '*_PERES_*': your kingdom is divided, and given to the Medes and Persians."

_1 verse containing PERES_

== PERESH

* `1Ch 7:16` And Maachah the wife of Machir bore a son and she called his name *_Peresh_*. And the name of his brother was Sheresh, and his sons were Ulam and Rakem.

_1 verse containing PERESH_

== PEREZ

* `2Sa 6:8` And David was displeased because the LORD had made a breach upon Uzzah. And he called the name of the place *_Perez_*-uzzah to this day.
* `1Ch 13:11` And David was displeased because the LORD had made a breach upon Uzza. Therefore, that place is called *_Perez_*-uzza to this day.
* `1Ch 27:3` Of the children of *_Perez_* was the chief of all the captains of the host for the first month.
* `Neh 11:4` And some of the children of Judah and some of the children of Benjamin dwelt at Jerusalem. Of the children of Judah: Athaiah the son of Uzziah, the son of Zechariah, the son of Amariah, the son of Shephatiah, the son of Mahalaleel, of the children of *_Perez_*;
* `Neh 11:6` All the sons of *_Perez_* who dwelt at Jerusalem were four hundred and sixty-eight valiant men.

_5 verses containing PEREZ_

== PEREZ-UZZA

* `1Ch 13:11` And David was displeased because the LORD had made a breach upon Uzza. Therefore, that place is called *_Perez-uzza_* to this day.

_1 verse containing PEREZ-UZZA_

== PEREZ-UZZAH

* `2Sa 6:8` And David was displeased because the LORD had made a breach upon Uzzah. And he called the name of the place *_Perez-uzzah_* to this day.

_1 verse containing PEREZ-UZZAH_

== PERFECT

* `Gen 6:9` These are the generations of Noah. Noah was a just man and *_perfect_* in his generations, and Noah walked with God.
* `Gen 17:1` And when Abram was ninety-nine years old, the LORD appeared to Abram and said to him, "I am the Almighty God. Walk before me and be *_perfect_*.
* `Lev 22:21` And whoever offers a sacrifice of peace-offerings to the LORD to accomplish his vow or a voluntary-offering in bulls or sheep, it shall be *_perfect_* to be accepted. There shall be no blemish in it.
* `Deu 18:13` You shall be *_perfect_* with the LORD your God.
* `Deu 25:15` But you shall have a *_perfect_* and just weight, and you shall have a *_perfect_* and just measure, so that your days may be lengthened in the land which the LORD your God gives you.
* `Deu 32:4` "The Rock—his work is *_perfect_*. For all his ways are judgment. A God of truth and without iniquity. He is just and right.
* `1Sa 14:41` Therefore, Saul said to the LORD God of Israel, "Give a *_perfect_* lot." And Saul and Jonathan were taken, but the people escaped.
* `2Sa 22:31` As for God, his way is *_perfect_*. The word of the LORD is tried. He is a buckler to all those who trust in him.
* `2Sa 22:33` God is my strength and power, and he makes my way *_perfect_*.
* `1Ki 8:61` Let your heart therefore be *_perfect_* with the LORD our God to walk in his statutes and to keep his commandments, as at this day."
* `1Ki 11:4` For it came to pass when Solomon was old, that his wives turned away his heart after other gods, and his heart was not *_perfect_* with the LORD his God, as the heart of David his father was.
* `1Ki 15:3` And he walked in all the sins of his father, which he had done before him. And his heart was not *_perfect_* with the LORD his God, as the heart of David his father.
* `1Ki 15:14` But the high places were not removed. Nevertheless, Asa's heart was *_perfect_* with the LORD all his days.
* `2Ki 20:3` "I implore you, O LORD, remember now how I have walked before you in truth and with a *_perfect_* heart and have done that which is good in your sight." And Hezekiah wept grievously.
* `1Ch 12:38` All these men of war, who could keep rank, came with a *_perfect_* heart to Hebron to make David king over all Israel. And all the rest also of Israel were of one heart to make David king.
* `1Ch 28:9` "And you, Solomon my son, know the God of your father and serve him with a *_perfect_* heart and with a willing mind, for the LORD searches all hearts and understands all the imaginations of the thoughts. If you seek him, he will be found by you, but if you forsake him, he will cast you off forever.
* `1Ch 29:9` Then the people rejoiced, for they offered willingly, because with *_perfect_* heart they offered willingly to the LORD. And David the king also rejoiced with great joy.
* `1Ch 29:19` And give to Solomon my son a *_perfect_* heart to keep your commandments, your testimonies, and your statutes, and to do all these things and to build the palace for which I have made provision."
* `2Ch 4:21` And the flowers, the lamps, and the tongs, he made of gold (and that of *_perfect_* gold);
* `2Ch 15:17` But the high places were not taken away out of Israel. Nevertheless, the heart of Asa was *_perfect_* all his days.
* `2Ch 16:9` For the eyes of the LORD run to and fro throughout the whole earth to show himself strong on behalf of those whose heart is *_perfect_* toward him. In this you have done foolishly. Therefore, from now on you shall have wars."
* `2Ch 19:9` And he charged them, saying, "Thus you shall do in the fear of the LORD, faithfully and with a *_perfect_* heart.
* `2Ch 25:2` And he did that which was right in the sight of the LORD, but not with a *_perfect_* heart.
* `Ezr 7:12` "Artaxerxes, king of kings, to Ezra the priest, a scribe of the law of the God of heaven: *_Perfect_* peace, and at such a time.
* `Job 8:20` Behold, God will not cast away a *_perfect_* man, neither will he help the evildoers,
* `Job 9:20` If I justify myself, my own mouth will condemn me. If I say, 'I am *_perfect_*,' that also will prove me perverse.
* `Job 9:21` Though I were *_perfect_*, yet I would not know my soul. I would despise my life.
* `Job 9:22` This is one thing; therefore, I said, 'He destroys the *_perfect_* and the wicked.'
* `Job 22:3` Is it any pleasure to the Almighty that you are righteous? Or is it gain to him that you make your ways *_perfect_*?
* `Job 36:4` For truly my words shall not be false. He who is *_perfect_* in knowledge is with you.
* `Job 37:16` Do you know the balancings of the clouds, the wondrous works of him who is *_perfect_* in knowledge,
* `Psa 18:30` As for God, his way is *_perfect_*. The word of the LORD is tried. He is a buckler to all those who trust in him.
* `Psa 18:32` It is God who girds me with strength and makes my way *_perfect_*.
* `Psa 19:7` The law of the LORD is *_perfect_*, converting the soul. The testimony of the LORD is sure, making the simple wise.
* `Psa 37:37` Mark the *_perfect_* man and behold the upright, for the end of that man is peace.
* `Psa 64:4` So that they may shoot in secret at the *_perfect_*. Suddenly they shoot at him and do not fear.
* `Psa 101:2` I will behave myself wisely in a *_perfect_* way. O when will you come to me? I will walk within my house with a *_perfect_* heart.
* `Psa 101:6` My eyes shall be upon the faithful of the land so that they may dwell with me. He who walks in a *_perfect_* way, he shall serve me.
* `Psa 138:8` The LORD will *_perfect_* that which concerns me. Your mercy, O LORD, endures forever. Do not forsake the works of your own hands.
* `Psa 139:22` I hate them with *_perfect_* hatred. I count them my enemies.
* `Pro 2:21` For the upright shall dwell in the land, and the *_perfect_* shall remain in it.
* `Pro 4:18` But the path of the just is like the shining light that shines more and more to the *_perfect_* day.
* `Pro 11:5` The righteousness of the *_perfect_* shall direct his way, but the wicked shall fall by his own wickedness.
* `Isa 18:5` For before the harvest when the bud is *_perfect_* and the sour grape is ripening in the flower, he shall both cut off the sprigs with pruning-hooks and take away and cut down the branches.
* `Isa 26:3` You will keep him in *_perfect_* peace, whose mind is stayed on you, because he trusts in you.
* `Isa 38:3` And said, "Remember now, O LORD, I implore you, how I have walked before you in truth and with a *_perfect_* heart and have done that which is good in your sight." And Hezekiah wept bitterly.
* `Isa 42:19` Who is blind, but my servant, or deaf, as my messenger whom I sent? Who is blind as he who is *_perfect_*, and blind as the LORD'S servant?
* `Ezk 16:14` And your renown went forth among the heathen for your beauty, for it was *_perfect_* through my splendor which I had put upon you," says the Lord GOD.
* `Ezk 27:3` And say to Tyre, who is situated at the entry of the sea, who is a merchant of the people for many coastlands, 'Thus says the Lord GOD: "O Tyre, you have said, 'I am of *_perfect_* beauty.'
* `Ezk 27:11` The men of Arvad with your army were upon your walls on all sides, and the Gammadims were in your towers. They hung their shields upon your walls on every side. They have made your beauty *_perfect_*.
* `Ezk 28:12` "Son of man, take up a lamentation upon the king of Tyre, and say to him, 'Thus says the Lord GOD: "You seal up the sum, full of wisdom and *_perfect_* in beauty.
* `Ezk 28:15` You were *_perfect_* in your ways from the day that you were created, until iniquity was found in you.
* `Mth 5:48` Therefore, be *_perfect_*, even as your Father who is in heaven is *_perfect_*."
* `Mth 19:21` Jesus said to him, "If you wish to be *_perfect_*, go and sell what you have, give to the poor, and you shall have treasure in heaven. Then come and follow me."
* `Luk 1:3` It seemed good to me also, having had *_perfect_* understanding of all things from the very first, to write to you in order, most excellent Theophilus,
* `Luk 6:40` The disciple is not above his master, but everyone who is *_perfect_* shall be as his master.
* `Jhn 17:23` I am in them and you are in me so that they may be made *_perfect_* in one, and that the world may know that you have sent me and have loved them as you have loved me.
* `Act 3:16` And through faith in his name, his name has made this man strong, whom you see and know. Indeed, the faith which is by him has given him this *_perfect_* soundness in the presence of you all.
* `Act 22:3` "I am truly a Jew, born in Tarsus, a city in Cilicia, yet brought up in this city at the feet of Gamaliel and taught according to the *_perfect_* manner of the law of the fathers, being zealous toward God as you all are this day.
* `Act 24:22` And when Felix heard these things, having more *_perfect_* knowledge of that way, he deferred them, and said, "When Lysias the chief captain comes down, I will know the uttermost of your matter."
* `Rom 12:2` And do not be conformed to this world, but be transformed by the renewing of your mind so that you may prove what is that good, acceptable, and *_perfect_* will of God.
* `1Co 13:10` But when that which is *_perfect_* has come, then that which is in part shall be done away.
* `2Co 12:9` And he said to me, "My grace is sufficient for you, for my strength is made *_perfect_* in weakness." Therefore, most gladly I will so much the more glory in my infirmities so that the power of Christ may rest upon me.
* `2Co 13:11` Finally, brothers, farewell. Be *_perfect_*, be of good comfort, be of one mind, live in peace, and the God of love and peace will be with you.
* `Gal 3:3` Are you so foolish? Having begun in the Spirit, are you now made *_perfect_* by the flesh?
* `Phl 3:12` It is not as though I had already attained, or were already *_perfect_*, but I pursue, if that I may obtain that for which Christ Jesus also obtained me.
* `Phl 3:15` Let us therefore, as many as are *_perfect_*, be thus minded. And if in anything you are otherwise minded, God will reveal even this to you.
* `Col 1:28` We preach Him, warning every man and teaching every man in all wisdom, so that we may present every man *_perfect_* in Christ Jesus.
* `Col 4:12` Epaphras, who is one of you, a servant of Christ, salutes you, always laboring fervently for you in prayers, that you may stand *_perfect_* and complete in all the will of God.
* `1Th 3:10` Night and day praying exceedingly that we may see your face and may *_perfect_* that which is lacking in your faith?
* `Heb 2:10` For it was fitting for him, for whom are all things and by whom are all things, in bringing many sons to glory, to make the Captain of their salvation *_perfect_* through sufferings.
* `Heb 5:9` And being made *_perfect_*, he became the author of eternal salvation to all those who obey him,
* `Heb 7:19` For the law made nothing *_perfect_*, but the introduction of a better hope did, by which we draw near to God.
* `Heb 9:9` This was a figure for the time then present, in which were offered both gifts and sacrifices that could not make him who did the service *_perfect_*, as pertaining to the conscience,
* `Heb 9:11` But Christ, having come as a high priest of good things to come, by a greater and more *_perfect_* tabernacle, not made with hands, that is to say, not of this building,
* `Heb 10:1` For the law, having a shadow of good things to come, and not the very image of the things, can never with those sacrifices, which they offered year by year continually, make *_perfect_* those who draw near.
* `Heb 11:40` God having provided something better for us—so that apart from us they should not be made *_perfect_*.
* `Heb 12:23` To the general assembly and church of the first-born who are written in heaven, to God the Judge of all, to the spirits of just men made *_perfect_*,
* `Heb 13:21` Make you *_perfect_* in every good work to do his will, working in you that which is well-pleasing in his sight through Jesus Christ, to whom be glory forever and ever. Amen.
* `Jms 1:4` But let patience have her *_perfect_* work so that you may be *_perfect_* and entire, lacking nothing.
* `Jms 1:17` Every good gift and every *_perfect_* gift is from above and comes down from the Father of lights, with whom there is no variableness, neither shadow of turning.
* `Jms 1:25` But he who looks into the *_perfect_* law of liberty and continues in it, not being a forgetful hearer, but a doer of the work, this man shall be blessed in his deed.
* `Jms 2:22` Do you see how faith wrought with his works, and faith was made *_perfect_* by works?
* `Jms 3:2` For in many things we all offend. If any man does not offend in word, the same is a *_perfect_* man, able also to bridle the whole body.
* `1Pe 5:10` But the God of all grace who has called us to his eternal glory by Christ Jesus, after you have suffered a while, shall himself *_perfect_*, establish, strengthen, and settle you.
* `1Jn 4:17` In this our love is made *_perfect_* so that we may have boldness in the day of judgment, because as he is, so are we in this world.
* `1Jn 4:18` There is no fear in love. But *_perfect_* love casts out fear, because fear has torment. He who fears is not made *_perfect_* in love.

_87 verses containing PERFECT_

== PERFECTED

* `2Ch 8:16` Now all the work of Solomon was prepared from the day of the foundation of the house of the LORD until it was finished. Thus the house of the LORD was *_perfected_*.
* `2Ch 24:13` Thus the workmen wrought and the work was *_perfected_* by them, and they set the house of God in its state and strengthened it.
* `Ezk 27:4` Your borders are in the midst of the seas. Your builders have *_perfected_* your beauty.
* `Mth 21:16` And said to him, "Do you hear what these say?" And Jesus says to them, "Yes. Have you never read, 'Out of the mouth of babies and infants you have *_perfected_* praise'?"
* `Luk 13:32` And he said to them, "Go and tell that fox, 'Behold, I cast out demons and I do cures today and tomorrow, and on the third day I shall be *_perfected_*.
* `Heb 7:28` For the law appoints men as high priests who have infirmity, but the word of the oath which was after the law appoints the Son who has been *_perfected_* forevermore.
* `Heb 10:14` For by one offering he has *_perfected_* forever those who are sanctified.
* `1Jn 2:5` But whoever keeps his word, the love of God is truly *_perfected_* in him. By this we know that we are in him.
* `1Jn 4:12` No man has seen God at any time. If we love one another, God dwells in us and his love is *_perfected_* in us.

_9 verses containing PERFECTED_

== PERFECTING

* `2Co 7:1` Having therefore these promises, dearly beloved, let us cleanse ourselves from all filthiness of the flesh and spirit, *_perfecting_* holiness in the fear of God.
* `Eph 4:12` For the *_perfecting_* of the saints, for the work of the ministry, for the edifying of the body of Christ,

_2 verses containing PERFECTING_

== PERFECTION

* `Job 11:7` Can you by searching find out God? Can you find out the Almighty to *_perfection_*?
* `Job 15:29` He shall not be rich, neither shall his substance continue, neither shall he prolong its *_perfection_* upon the earth.
* `Job 28:3` He sets an end to darkness, and to all *_perfection_* he searches out the stones of darkness and the shadow of death.
* `Psa 50:2` Out of Zion, the *_perfection_* of beauty, God has shined.
* `Psa 119:96` I have seen an end of all *_perfection_*, but your commandment is exceedingly broad.
* `Isa 47:9` But these two things shall come to you in a moment in one day: the loss of children and widowhood. They shall come upon you in their *_perfection_* in spite of the multitude of your sorceries and in spite of the great abundance of your enchantments.
* `Lam 2:15` [SAMEKH] All who pass by clap their hands at you. They hiss and wag their head at the daughter of Jerusalem, saying, "Is this the city that men call The *_Perfection_* of Beauty, The Joy of the Whole Earth?"
* `Luk 8:14` And that which fell among thorns are those who, when they have heard, go forth and are choked with cares and riches and pleasures of this life and bring no fruit to *_perfection_*.
* `2Co 13:9` For we are glad when we are weak and you are strong. And this also we wish: even your *_perfection_*.
* `Heb 6:1` Therefore, leaving the first principles of the doctrine of Christ, let us go on to *_perfection_*, not laying again the foundation of repentance from dead works and of faith toward God,
* `Heb 7:11` If therefore *_perfection_* were by the Levitical priesthood (for under it the people received the law), what further need was there that another priest should rise after the order of Melchizedek and not be called after the order of Aaron?

_11 verses containing PERFECTION_

== PERFECTLY

* `Jer 23:20` The anger of the LORD shall not return until he has executed and until he has performed the thoughts of his heart. In the latter days you shall consider it *_perfectly_*.
* `Act 18:26` And he began to speak boldly in the synagogue, but when Aquila and Priscilla had heard, they took him aside and expounded to him the way of God more *_perfectly_*.
* `Act 23:15` Now therefore, you and the council signify to the chief captain that he bring him down to you tomorrow as though you would inquire something more *_perfectly_* concerning him. And we, before he comes near, are ready to kill him."
* `Act 23:20` And he said, "The Jews have agreed to desire of you that you would bring Paul down tomorrow into the council as though they would inquire somewhat more *_perfectly_* concerning him.
* `1Co 1:10` Now I implore you, brothers, by the name of our Lord Jesus Christ, that you all speak the same thing and that there be no divisions among you, but that you be *_perfectly_* joined together in the same mind and in the same judgment.
* `1Th 5:2` For you yourselves know *_perfectly_* that the day of the Lord comes even as a thief in the night.

_6 verses containing PERFECTLY_

== PERFECTNESS

* `Col 3:14` And above all these things, put on charity, which is the bond of *_perfectness_*.

_1 verse containing PERFECTNESS_

== PERFORM

* `Gen 26:3` Sojourn in this land, and I will be with you and will bless you. For to you and to your offspring I will give all these countries, and I will *_perform_* the oath which I swore to Abraham your father.
* `Exo 4:17` And you shall take this rod in your hand, with which you shall *_perform_* signs."
* `Exo 4:21` And the LORD said to Moses, "When you go to return into Egypt, see that you *_perform_* all those wonders before Pharaoh which I have put in your hand. But I will harden his heart so that he shall not let the people go.
* `Exo 18:18` You will surely wear away, both you and this people who is with you, for this thing is too heavy for you. You are not able to *_perform_* it yourself alone.
* `Exo 21:11` And if he does not *_perform_* these three to her, then she shall depart free without money.
* `Exo 24:3` And Moses came and told the people all the words of the LORD and all the judgments. And all the people answered with one voice and said, "All the words which the LORD has said we will *_perform_*."
* `Lev 18:4` You shall *_perform_* my judgments and keep my ordinances to walk in them. I am the LORD your God.
* `Num 4:23` From thirty years old and upward until fifty years old you shall number them—all who enter in to *_perform_* the service to do the work in the Tabernacle of the Congregation.
* `Num 7:5` "Take it from them so that they may be used to *_perform_* the service of the Tabernacle of the Congregation, and you shall give them to the Levites, to each according to his service."
* `Num 8:15` And after that, the Levites shall go in to *_perform_* the service of the Tabernacle of the Congregation. And you shall cleanse them and offer them for an offering,
* `Num 8:22` And after that, the Levites went in to *_perform_* their service in the Tabernacle of the Congregation before Aaron and before his sons. As the LORD had commanded Moses concerning the Levites, so they did to them.
* `Num 22:20` And God came to Balaam at night and said to him, "If the men come to call you, rise and go with them, but only the word which I shall say to you, you shall *_perform_*."
* `Deu 4:13` And he declared to you his covenant, which he commanded you to *_perform_*, even the Ten Commandments, and he wrote them upon two tablets of stone.
* `Deu 9:5` Not for your righteousness or for the uprightness of your heart do you go to possess their land, but for the wickedness of these nations the LORD your God drives them out from before you so that he may *_perform_* the word which the LORD swore to your fathers, Abraham, Isaac, and Jacob.
* `Deu 23:23` That which is uttered by your lips you shall keep and *_perform_*, even a voluntary-offering, according as you have vowed to the LORD your God, which you have promised with your mouth.
* `Deu 25:5` "If brothers dwell together, and one of them dies and has no child, the wife of the dead shall not marry outside to a stranger. Her husband's brother shall go in to her and take her for himself for a wife and *_perform_* the duty of a husband's brother to her.
* `Deu 25:7` And if the man does not want to take his brother's wife, then let his brother's wife go up to the gate to the elders and say, 'My husband's brother refuses to raise up for his brother a name in Israel. He will not *_perform_* the duty of my husband's brother.'
* `Deu 26:16` "This day the LORD your God has commanded you to *_perform_* these statutes and judgments. You shall therefore keep and do them with all your heart and with all your soul.
* `Deu 28:20` "The LORD shall send upon you cursing, vexation, and rebuke in all that you undertake to *_perform_* until you are destroyed and until you perish quickly, because of the wickedness of your doings by which you have forsaken me.
* `Jsh 22:5` But take diligent heed to *_perform_* the commandment and the law which Moses the servant of the LORD charged you, to love the LORD your God, to walk in all his ways, to keep his commandments, to cleave to him, and to serve him with all your heart and with all your soul."
* `Rth 3:13` Stay this night, and it shall be in the morning, that if he will *_perform_* to you the part of a kinsman, good. Let him do the kinsman's part. But if he will not do the part of a kinsman to you, then I will do the part of a kinsman to you, as the LORD lives. Lie down until the morning."
* `1Sa 3:12` In that day, I will *_perform_* against Eli all things which I have spoken concerning his house. When I begin, I will also make an end.
* `2Sa 14:15` Now therefore, seeing that I have come to speak of this thing to my lord the king, it is because the people have made me afraid. And your servant said, 'I will now speak to the king. It may be that the king will *_perform_* the request of his servant.
* `1Ki 5:8` And Hiram sent to Solomon, saying, "I have considered the things which you sent to me for, and I will *_perform_* all your desire concerning timber of cedar and concerning timber of fir.
* `1Ki 6:12` "Concerning this house which you are in building, if you will walk in my statutes, execute my judgments, and keep all my commandments to walk in them, then I will *_perform_* my word with you which I spoke to David your father.
* `1Ki 9:1` And it came to pass, when Solomon had finished the building of the house of the LORD, the king's house, and all Solomon's desire which he was pleased to *_perform_*,
* `1Ki 12:15` Therefore, the king did not listen to the people, for the cause was from the LORD that he might *_perform_* his saying which the LORD spoke by Ahijah the Shilonite to Jeroboam the son of Nebat.
* `1Ki 12:27` If this people goes up to *_perform_* sacrifice in the house of the LORD at Jerusalem, then the heart of this people shall turn back to their lord, even to Rehoboam king of Judah, and they shall kill me and return to Rehoboam king of Judah."
* `2Ki 23:3` And the king stood by a pillar and made a covenant before the LORD to walk after the LORD, to keep his commandments, his testimonies, and his statutes, with all their heart and all their soul, to *_perform_* the words of this covenant that were written in this book. And all the people stood to the covenant.
* `2Ki 23:24` Moreover, the workers with familiar spirits, the wizards, the images, the idols, and all the abominations that were seen in the land of Judah and in Jerusalem, Josiah put away so that he might *_perform_* the words of the law which were written in the book that Hilkiah the priest found in the house of the LORD.
* `2Ch 10:15` So the king did not listen to the people, for the cause was from God so that the LORD might *_perform_* his word which he spoke by the hand of Ahijah the Shilonite to Jeroboam the son of Nebat.
* `2Ch 34:16` And Shaphan carried the book to the king and brought the king word back again, saying, "All that was committed to your servants, they *_perform_*.
* `2Ch 34:31` And the king stood in his place and made a covenant before the LORD, to walk after the LORD and to keep his commandments, his testimonies, and his statutes with all his heart and with all his soul, to *_perform_* the words of the covenant which are written in this book.
* `Neh 5:13` Also I shook my lap, and said, "In this manner may God shake out every man from his house and from his labor who does not *_perform_* this promise. Even in this manner may he be shaken out and emptied." And all the congregation said, "Amen," and praised the LORD. And the people did according to this promise.
* `Est 5:8` If I have found favor in the sight of the king, and if it pleases the king to grant my petition and to *_perform_* my request, let the king and Haman come to the banquet that I shall prepare for them, and I will do tomorrow as the king has said."
* `Job 5:12` He disappoints the devices of the crafty so that their hands cannot *_perform_* their enterprise.
* `Psa 21:11` For they intended evil against you. They conceived a mischievous device which they are not able to *_perform_*.
* `Psa 61:8` So I will sing praise to your name forever when I daily *_perform_* my vows.
* `Psa 119:106` I have sworn, and I will *_perform_* it, that I will keep your righteous judgments.
* `Psa 119:112` I have inclined my heart to *_perform_* your statutes always, even to the end.
* `Isa 9:7` Of the increase of his government and peace there shall be no end, upon the throne of David and upon his kingdom, to order it and to establish it with judgment and with justice from now on even forever. The zeal of the LORD of hosts will *_perform_* this.
* `Isa 19:15` There shall not be any work for Egypt which the head or tail, branch or rush, may *_perform_*.
* `Isa 19:21` And the LORD shall be known to Egypt, and the Egyptians shall know the LORD in that day and shall do sacrifice and oblation. They shall even vow a vow to the LORD and *_perform_* it.
* `Isa 44:28` Who says of Cyrus, 'He is my shepherd, and he shall *_perform_* all my pleasure,' even saying to Jerusalem, 'You shall be built,' and to the temple, 'Your foundation shall be laid.'"
* `Isa 46:11` Calling a ravenous bird from the east, the man who executes my counsel from a far country. I have spoken it and I will also bring it to pass. I have purposed it and I will also *_perform_* it.
* `Jer 1:12` Then the LORD said to me, "You have seen well. For I will hasten my word to *_perform_* it."
* `Jer 11:5` So that I may *_perform_* the oath which I have sworn to your fathers, to give them a land flowing with milk and honey, as it is this day."'" Then I answered and said, "So be it, O LORD."
* `Jer 28:6` Even the prophet Jeremiah said, "Amen. May the LORD do so. May the LORD *_perform_* your words which you have prophesied, to bring back the vessels of the LORD'S house and all that is carried away captive from Babylon into this place.
* `Jer 29:10` "For thus says the LORD: 'After seventy years is accomplished at Babylon I will visit you and *_perform_* my good word toward you, in causing you to return to this place.
* `Jer 33:14` 'Behold, the days come,' says the LORD, 'that I will *_perform_* that good thing which I have promised to the house of Israel and to the house of Judah.
* `Jer 44:25` Thus says the LORD of hosts, the God of Israel, saying, 'You and your wives have both spoken with your mouths and fulfilled with your hand, saying, "We will surely *_perform_* our vows that we have vowed, to burn incense to the queen of heaven and to pour out drink-offerings to her." You will surely accomplish your vows and surely *_perform_* your vows.'
* `Ezk 12:25` For I am the LORD. I will speak, and the word that I shall speak shall come to pass. It shall no longer be prolonged, for in your days, O rebellious house, I will say the word and *_perform_* it," says the Lord GOD.'"
* `Ezk 33:32` And behold, you are to them like a very lovely song by one who has a pleasant voice and can play well on an instrument, for they hear your words, but they do not *_perform_* them.
* `Nah 1:15` Behold upon the mountains the feet of him who brings good tidings, who publishes peace! O Judah, keep your solemn feasts and *_perform_* your vows, for the wicked shall no longer pass through you. He is utterly cut off.
* `Mth 5:33` "Again, you have heard that it has been said to them of old time, 'You shall not swear falsely, but shall *_perform_* to the Lord your oaths.'
* `Luk 1:72` To *_perform_* the mercy promised to our fathers, and to remember his holy covenant,
* `Rom 4:21` And being fully persuaded that what he had promised he was also able to *_perform_*.
* `Rom 7:18` For I know that in me (that is, in my flesh) no good thing dwells. For desire is present with me, but how to *_perform_* that which is good, I do not find.
* `Phl 1:6` Being confident of this very thing, that he who has begun a good work in you will *_perform_* it until the day of Jesus Christ,

_59 verses containing PERFORM_

== PERFORMANCE

* `Luk 1:45` And blessed is she who believed that there will be a *_performance_* of those things which were told to her from the Lord."
* `2Co 8:11` Now therefore, finish the doing also, so that as there was a readiness to will, so may there be a *_performance_* also out of that which you have.

_2 verses containing PERFORMANCE_

== PERFORMED

* `Exo 4:30` And Aaron spoke all the words which the LORD had spoken to Moses and *_performed_* the signs in the sight of the people.
* `1Sa 15:11` "I repent that I have set up Saul to be king, for he has turned back from following me and has not *_performed_* my commandments." And it grieved Samuel and he cried to the LORD all night.
* `1Sa 15:13` And Samuel came to Saul. And Saul said to him, "Blessed are you of the LORD. I have *_performed_* the commandment of the LORD."
* `2Sa 21:14` And the bones of Saul and Jonathan his son they buried in the country of Benjamin in Zelah in the sepulcher of Kish his father. And they *_performed_* all that the king commanded. And after that God was entreated for the land.
* `1Ki 8:20` And the LORD has *_performed_* his word that he spoke, and I have risen in place of David my father and sit on the throne of Israel, as the LORD promised, and have built a house for the name of the LORD God of Israel.
* `2Ch 6:10` The LORD therefore has *_performed_* his word that he has spoken, for I am raised up in place of David my father and am set on the throne of Israel, as the LORD promised, and have built the house for the name of the LORD God of Israel.
* `2Ch 31:20` And Hezekiah did this throughout all Judah. And he *_performed_* that which was good and right and faithful before the LORD his God.
* `Neh 9:8` And found his heart faithful before you and made a covenant with him, to give the land of the Canaanites, the Hittites, the Amorites, the Perizzites, the Jebusites, and the Girgashites, to give it to his offspring, and have *_performed_* your words, for you are righteous.
* `Neh 9:17` And they refused to obey, neither were they mindful of your wonders that you *_performed_* among them, but hardened their necks, and in their rebellion appointed a captain to return to their bondage. But you are a God ready to pardon, gracious and merciful, slow to anger, and of great kindness, and did not forsake them.
* `Neh 11:12` And their brothers who *_performed_* the work of the house numbered eight hundred and twenty-two; and Adaiah the son of Jeroham, the son of Pelaliah, the son of Amzi, the son of Zechariah, the son of Pashur, the son of Malchiah,
* `Est 1:15` "What shall we do to the queen Vashti according to law because she has not *_performed_* the commandment of king Ahasuerus by the chamberlains?"
* `Est 2:20` Esther had not yet revealed her kindred nor her people, as Mordecai had charged her, for Esther *_performed_* the commandment of Mordecai, as when she was brought up with him.
* `Est 5:6` And the king said to Esther at the banquet of wine, "What is your petition? It shall be granted you. And what is your request? Even to the half of the kingdom it shall be *_performed_*."
* `Est 7:2` And the king said again to Esther on the second day at the banquet of wine, "What is your petition, queen Esther? It shall be granted to you. And what is your request? It shall be *_performed_*, even to the half of the kingdom."
* `Psa 65:1` [To the Chief Musician. A Psalm and Song of David.] Praise waits for you, O God, in Zion. And to you the vow shall be *_performed_*.
* `Psa 119:166` LORD, I have hoped for your salvation and *_performed_* your commandments.
* `Isa 10:12` Therefore, it shall come to pass when the Lord has *_performed_* his whole work upon mount Zion and on Jerusalem, that I will punish the fruit of the stout heart of the king of Assyria and the glory of his high looks.
* `Jer 23:20` The anger of the LORD shall not return until he has executed and until he has *_performed_* the thoughts of his heart. In the latter days you shall consider it perfectly.
* `Jer 30:24` The fierce anger of the LORD shall not return until he has done it and until he has *_performed_* the intents of his heart. In the latter days you shall consider it.
* `Jer 34:18` And I will give the men who have transgressed my covenant, who have not *_performed_* the words of the covenant which they had made before me when they cut the calf in two and passed between its parts—
* `Jer 35:14` "The words of Jonadab the son of Rechab that he commanded his sons not to drink wine are *_performed_*. For to this day they drink none, but obey their father's commandment. But I have spoken to you, rising early and speaking, and you did not listen to me.
* `Jer 35:16` Because the sons of Jonadab the son of Rechab have *_performed_* the commandment of their father which he commanded them, but this people has not listened to me,'"'
* `Jer 51:29` And the land shall tremble and sorrow, for every purpose of the LORD shall be *_performed_* against Babylon to make the land of Babylon a desolation without an inhabitant.
* `Ezk 37:14` And I will put my Spirit in you, and you shall live, and I will place you in your own land. Then you shall know that I, the LORD, have spoken it and *_performed_* it," says the LORD.'"
* `Zph 2:3` Seek the LORD, all you meek of the earth, who have *_performed_* his judgment. Seek righteousness. Seek meekness. It may be that you will be hid in the day of the LORD'S anger.
* `Hag 1:14` And the LORD stirred up the spirit of Zerubbabel the son of Shealtiel, governor of Judah, and the spirit of Joshua the son of Josedech, the high priest, and the spirit of all the remnant of the people, and they came and *_performed_* work in the house of the LORD of hosts, their God,
* `Luk 1:20` And behold, you shall be mute and not able to speak until the day that these things are *_performed_* because you do not believe my words which shall be fulfilled in their season."
* `Luk 2:39` And when they had *_performed_* all things according to the law of the Lord, they returned into Galilee to their own city of Nazareth.
* `Jhn 2:11` This beginning of miracles Jesus *_performed_* in Cana of Galilee and manifested his glory, and his disciples believed in him.
* `Jhn 2:23` Now when he was in Jerusalem at the passover, on the feast day, many believed in his name when they saw the miracles which he *_performed_*.
* `Jhn 4:54` This is again the second miracle that Jesus *_performed_* when he had come from Judea into Galilee.
* `Jhn 6:2` And a great multitude followed him because they saw his miracles which he *_performed_* on those who were diseased.
* `Jhn 6:14` Then those men, when they had seen the miracle that Jesus *_performed_*, said, "This is truly that prophet who should come into the world."
* `Jhn 10:41` And many resorted to him, and said, "John *_performed_* no miracle, but all things that John spoke about this man were true."
* `Act 4:22` For the man was more than forty years old on whom this miracle of healing was *_performed_*.
* `Act 6:8` And Stephen, full of faith and power, *_performed_* great wonders and miracles among the people.
* `Act 8:6` And the people with one accord gave heed to those things which Philip spoke, hearing and seeing the miracles which he *_performed_*.
* `Rom 15:28` When therefore I have *_performed_* this and have sealed to them this fruit, I will go by you into Spain.

_38 verses containing PERFORMED_

== PERFORMING

* `Num 15:3` And you make an offering by fire to the LORD from the herd or from the flock—a burnt-offering or a sacrifice, in *_performing_* a vow, or in a voluntary-offering, or in your solemn feasts—to make a sweet savor to the LORD,
* `Num 15:8` And when you prepare a bull for a burnt-offering, or for a sacrifice in *_performing_* a vow, or for peace-offerings to the LORD,

_2 verses containing PERFORMING_

== PERFORMS

* `Job 23:14` For he *_performs_* the thing that is appointed for me. And many such things are with him.
* `Psa 57:2` I will cry to God most high, to God who *_performs_* all things for me.
* `Isa 44:26` Who confirms the word of his servant and *_performs_* the counsel of his messengers, who says to Jerusalem, 'You shall be inhabited,' and to the cities of Judah, 'You shall be built, and I will raise up her decayed places,'
* `Jhn 11:47` Then the chief priests and the Pharisees convened a council, and said, "What do we do? For this man *_performs_* many miracles.

_4 verses containing PERFORMS_

== PERFUME

* `Exo 30:35` And you shall make it a *_perfume_*, a confection after the art of the perfumer, tempered together, pure and holy.
* `Exo 30:37` And as for the *_perfume_* which you shall make, you shall not make for yourselves according to its composition. It shall be to you holy for the LORD.
* `Pro 27:9` Ointment and *_perfume_* rejoice the heart, and so does the sweetness of a man's friend by hearty counsel.
* `Isa 3:20` The caps, the ornaments of the legs, the head-bands, the *_perfume_* boxes, the amulets,

_4 verses containing PERFUME_

== PERFUMED

* `Pro 7:17` I have *_perfumed_* my bed with myrrh, aloes, and cinnamon.
* `Sos 3:6` Who is this who comes out of the wilderness like pillars of smoke, *_perfumed_* with myrrh and frankincense, with all powders of the merchant?

_2 verses containing PERFUMED_

== PERFUMER

* `Exo 30:25` And you shall make it an oil of holy ointment, an ointment compound after the art of the *_perfumer_*. It shall be a holy anointing oil.
* `Exo 30:35` And you shall make it a perfume, a confection after the art of the *_perfumer_*, tempered together, pure and holy.
* `Exo 37:29` And he made the holy anointing oil and the pure incense of sweet spices according to the work of the *_perfumer_*.
* `Ecc 10:1` Dead flies cause the ointment of the *_perfumer_* to send forth an offensive odor, and so does a little folly to him who is in reputation for wisdom and honor.

_4 verses containing PERFUMER_

== PERFUMERS

* `2Ch 16:14` And they buried him in his own sepulchers which he had made for himself in the city of David, and laid him in the bed which was filled with sweet odors and diverse kinds of spices prepared by the *_perfumers_*' art. And they made a very great burning for him.
* `Neh 3:8` Next to him Uzziel the son of Harhaiah, of the goldsmiths, repaired. Next to him Hananiah the son of one of the *_perfumers_* repaired, and they fortified Jerusalem to the broad wall.

_2 verses containing PERFUMERS_

== PERFUMES

* `Isa 57:9` And you went to the king with ointment and increased your *_perfumes_*. You sent your messengers far off, and debased yourself even to hell.

_1 verse containing PERFUMES_

== PERGA

* `Act 13:13` Now when Paul and his company set sail from from Paphos, they came to *_Perga_* in Pamphylia. And John, departing from them, returned to Jerusalem.
* `Act 13:14` But when they departed from *_Perga_*, they came to Antioch in Pisidia and went into the synagogue on the sabbath and sat down.
* `Act 14:25` And when they had preached the word in *_Perga_*, they went down into Attalia.

_3 verses containing PERGA_

== PERGAMOS

* `Rev 1:11` Saying, "I am Alpha and Omega, the first and the last," and, "What you see, write in a book and send it to the seven churches which are in Asia: to Ephesus, to Smyrna, to *_Pergamos_*, to Thyatira, to Sardis, to Philadelphia, and to Laodicea."
* `Rev 2:12` "And to the angel of the church in *_Pergamos_*, write: 'He who has the sharp sword with two edges says these things:

_2 verses containing PERGAMOS_

== PERHAPS

* `Gen 18:24` *_Perhaps_* there are fifty righteous within the city. Will you also destroy and not spare the place for the fifty righteous who are in it?
* `Gen 18:28` *_Perhaps_* there will lack five of the fifty righteous. Will you destroy all the city for lack of five?" And he said, "If I find there forty-five, I will not destroy it."
* `Gen 18:29` And he spoke to him yet again, and said, "*_Perhaps_* there will be forty found there." And he said, "I will not do it for the forty's sake."
* `Gen 18:30` And he said, "Oh do not let the Lord be angry, and I will speak. *_Perhaps_* there will be thirty found there." And he said, "I will not do it if I find thirty there."
* `Gen 18:31` And he said, "Behold now, I have taken upon myself to speak to the Lord. *_Perhaps_* there will be twenty found there." And he said, "I will not destroy it for the twenty's sake."
* `Gen 18:32` And he said, "Oh do not let the Lord be angry, and I will speak just once more. *_Perhaps_* ten will be found there." And he said, "I will not destroy it for ten's sake."
* `Gen 27:12` My father *_perhaps_* will feel me, and I shall seem to him as a deceiver, and I shall bring a curse upon me and not a blessing."
* `Gen 32:20` And say moreover, 'Behold, your servant Jacob is behind us.'" For he said, "I will appease him with the present that goes before me, and afterward, I will see his face. *_Perhaps_* he will accept me."
* `Gen 38:11` Then Judah said to Tamar his daughter-in-law, "Remain a widow at your father's house until Shelah my son is grown," for he said, "Lest *_perhaps_* he die also as his brothers did." And Tamar went and dwelt in her father's house.
* `Gen 42:4` But Benjamin, Joseph's brother, Jacob did not send with his brothers, for he said, "Lest *_perhaps_* mischief befalls him."
* `Gen 44:34` For how shall I return to my father if the boy is not with me?—Lest *_perhaps_* I see the evil that shall come on my father."
* `Gen 50:15` And when Joseph's brothers saw that their father was dead, they said, "Joseph will *_perhaps_* hate us and will certainly requite us all the evil which we did to him."
* `Exo 13:17` And it came to pass when Pharaoh had let the people go, that God did not lead them through the way of the land of the Philistines, although that was near, for God said, "Lest *_perhaps_* the people repent when they see war and they return to Egypt."
* `Num 23:27` And Balak said to Balaam, "Come, I pray you, I will bring you to another place. *_Perhaps_* it will please God that you may from there curse them for me."
* `1Sa 14:30` How much more, if *_perhaps_* the people had eaten freely today of the plunder of their enemies which they found? Would not the slaughter among the Philistines have been much greater?"
* `1Ki 18:27` And it came to pass at noon, that Elijah mocked them and said, "Cry aloud, for he is a god! Either he is talking, he is pursuing, he is on a journey, or *_perhaps_* he sleeps and must be awakened."
* `2Ki 2:16` And they said to him, "Behold now, there are with your servants fifty strong men. Let them go, we pray you, and seek your master, lest *_perhaps_* the Spirit of the LORD has taken him up and cast him upon some mountain or into some valley." And he said, "You shall not send."
* `Isa 47:12` Stand now with your enchantments and with the multitude of your sorceries in which you have labored from your youth. It may be you are able to profit. *_Perhaps_* you may prevail.
* `Jer 20:10` For I heard the defaming of many, "Fear is on every side. Report," they say, "and we will report it." All my familiar friends watched for my fall, saying, "*_Perhaps_* he will be enticed, and we shall prevail against him and take our revenge on him."
* `Mth 13:15` For this people's heart has become callous, their ears are dull of hearing, and their eyes they have closed, or else *_perhaps_* they should see with their eyes, hear with their ears, and should understand with their heart and should be converted, and I should heal them.'
* `Mrk 11:13` And seeing a fig-tree afar off having leaves, he came, if *_perhaps_* he might find anything on it. And when he came to it, he found nothing but leaves, for the time of figs had not yet come.
* `Act 5:39` But if it is from God, you cannot overthrow it, lest *_perhaps_* you be found even to fight against God."
* `Act 8:22` Repent therefore of this wickedness of yours and pray to God, if *_perhaps_* the thought of your heart may be forgiven.
* `Act 17:27` That they should seek the Lord, if *_perhaps_* they might feel after him and find him, though he is not far from each one of us.
* `Rom 5:7` For one will scarcely die for a righteous man, though *_perhaps_* for a good man some would even dare to die.
* `2Co 2:7` So that on the other hand you ought rather to forgive him and comfort him, lest *_perhaps_* such a one should be swallowed up with excessive sorrow.
* `2Co 9:4` Lest *_perhaps_* if those of Macedonia come with me and find you unprepared, we (to not speak of you) should be ashamed in this same confident boasting.
* `2Ti 2:25` In meekness instructing those who oppose themselves, if God *_perhaps_* will give them repentance to the acknowledging of the truth,
* `Phm 1:15` For *_perhaps_* he was therefore parted from you for a season so that you should receive him forever,

_29 verses containing PERHAPS_

== PERIDA

* `Neh 7:57` The children of Solomon's servants: the children of Sotai, the children of Sophereth, the children of *_Perida_*,

_1 verse containing PERIDA_

== PERIL

* `Lam 5:9` We procured our bread with the *_peril_* of our lives, because of the sword of the wilderness.
* `Rom 8:35` Who shall separate us from the love of Christ? Shall tribulation, distress, persecution, famine, nakedness, *_peril_*, or sword?

_2 verses containing PERIL_

== PERILOUS

* `2Ti 3:1` Know this also, that in the last days *_perilous_* times will come.

_1 verse containing PERILOUS_

== PERILS

* `2Co 11:26` In journeyings often, in *_perils_* of waters, in *_perils_* of robbers, in *_perils_* by my own countrymen, in *_perils_* by the heathen, in *_perils_* in the city, in *_perils_* in the wilderness, in *_perils_* in the sea, in *_perils_* among false brothers;

_1 verse containing PERILS_

== PERISH

* `Gen 41:36` And that food shall be a store for the land against the seven years of famine, which shall be in the land of Egypt, so that the land may not *_perish_* through the famine."
* `Exo 19:21` And the LORD said to Moses, "Go down, charge the people, lest they break through to the LORD to gaze and many of them *_perish_*.
* `Lev 26:38` And you shall *_perish_* among the heathen, and the land of your enemies shall eat you up.
* `Num 5:21` Then the priest shall charge the woman with an oath of cursing and the priest shall say to the woman—"May the LORD make you a curse and an oath among your people when the LORD causes your thigh to *_perish_* and your belly to swell.
* `Num 5:22` And this water that causes the curse shall go into your bowels to cause your belly to swell and your thigh to *_perish_*." And the woman shall say, "Amen, amen."
* `Num 5:27` And when he has made her to drink the water, it shall come to pass, that if she is defiled and has done trespass against her husband, that the water that causes the curse shall enter into her and become bitter, and her belly shall swell and her thigh shall *_perish_*, and the woman shall be a curse among her people.
* `Num 17:12` And the children of Israel spoke to Moses, saying, "Behold, we die. We *_perish_*. We all *_perish_*.
* `Num 24:20` And when he looked at Amalek, he took up his parable and said, "Amalek was the first of the nations, but his latter end shall be that he shall *_perish_* forever."
* `Num 24:24` And ships shall come from the coast of Chittim and shall afflict Ashur and shall afflict Eber, and he also shall *_perish_* forever."
* `Deu 4:26` I call heaven and earth to witness against you this day, that you shall soon utterly *_perish_* from the land to which you go over the Jordan to possess it. You shall not prolong your days upon it, but shall be utterly destroyed.
* `Deu 8:19` And it shall be, if you at all forget the LORD your God and walk after other gods and serve and worship them, I testify against you this day that you shall surely *_perish_*.
* `Deu 8:20` As the nations which the LORD destroys before your face, so you shall *_perish_*, because you would not be obedient to the voice of the LORD your God."
* `Deu 11:17` And the LORD'S wrath be kindled against you, and he restrain the heavens so that there shall be no rain, and the land shall not yield her fruit; and lest you *_perish_* quickly from off the good land which the LORD gives you.
* `Deu 26:5` And you shall speak and say before the LORD your God, 'My father was a Syrian ready to *_perish_*, and he went down to Egypt and sojourned there with a few and became a great, mighty, and populous nation there.
* `Deu 28:20` "The LORD shall send upon you cursing, vexation, and rebuke in all that you undertake to perform until you are destroyed and until you *_perish_* quickly, because of the wickedness of your doings by which you have forsaken me.
* `Deu 28:22` The LORD shall smite you with a consumption, with a fever, with an inflammation, with an extreme burning, with the sword, with blight, and with mildew. And they shall pursue you until you *_perish_*.
* `Deu 30:18` I denounce to you this day, that you shall surely *_perish_*, and that you shall not prolong your days upon the land where you pass over the Jordan to go to possess it.
* `Jsh 22:20` Did Achan the son of Zerah not commit a trespass in the accursed thing and wrath fall on all the congregation of Israel? And that man did not *_perish_* alone in his iniquity.'"
* `Jsh 23:13` Know for a certainty that the LORD your God will no longer drive out any of these nations from before you, but they shall be snares and traps to you, scourges in your sides, and thorns in your eyes until you *_perish_* from off this good land which the LORD your God has given you.
* `Jsh 23:16` If you transgress the covenant of the LORD your God, which he commanded you, and have gone and served other gods and bowed yourselves to them, then the anger of the LORD shall be kindled against you, and you shall *_perish_* quickly from off the good land which he has given to you."
* `Jdg 5:31` "So let all your enemies *_perish_*, O LORD. But let those who love him be like the sun when he goes forth in his might." And the land had rest for forty years.
* `1Sa 26:10` David said furthermore, "As the LORD lives, the LORD will smite him, or his day will come to die, or he will descend into battle and *_perish_*.
* `1Sa 27:1` And David said in his heart, "I shall now *_perish_* one day by the hand of Saul. There is nothing better for me than that I should speedily escape into the land of the Philistines. And Saul will despair of seeking for me anymore in any border of Israel, and I shall escape from his hand."
* `2Ki 9:8` For the whole house of Ahab shall *_perish_*. And I will cut off from Ahab the males and him who is shut up and him who is left at large in Israel.
* `Est 3:13` And the letters were sent by posts into all the king's provinces to destroy, to kill, and to cause to *_perish_* all Jews, both young and old, little children and women, in one day, even upon the thirteenth day of the twelfth month (that is, the month Adar), and to plunder their goods.
* `Est 4:16` "Go, assemble all the Jews who are present in Shushan and fast for me, and neither eat nor drink three days, night or day. I also and my attendants will fast likewise. And so I will go before the king, which is not according to the law, and if I *_perish_*, I *_perish_*."
* `Est 7:4` For we are sold—I and my people—to be destroyed, to be slain, and to *_perish_*. But if we had been sold for men-servants and women-servants, I would have held my tongue, although the enemy could not have compensated for the damage to the king."
* `Est 8:11` In them the king granted the Jews who were in every city to assemble and to stand for their life, to destroy, to slay, and to cause to *_perish_* all the power of the people and province that would assault them, both little ones and women, and to plunder their goods,
* `Est 9:28` And that these days should be remembered and kept throughout every generation, every family, every province, and every city, and that these days of Purim should not fail from among the Jews, nor their memorial *_perish_* from their descendants.
* `Job 3:3` "Let the day *_perish_* in which I was born, and the night in which it was said, 'There is a male child conceived.'
* `Job 4:9` By the blast of God they *_perish_*, and by the breath of his nostrils they are consumed.
* `Job 4:20` They are destroyed from morning to evening. They *_perish_* forever without any regarding it.
* `Job 6:18` The paths of their way are turned aside. They go to nothing and *_perish_*.
* `Job 8:13` Thus are the paths of all who forget God. And the hypocrite's hope shall *_perish_*,
* `Job 18:17` His remembrance shall *_perish_* from the earth, and he shall have no name in the street.
* `Job 20:7` Yet he shall *_perish_* forever like his own dung. Those who have seen him shall say, 'Where is he?'
* `Job 29:13` The blessing of him who was ready to *_perish_* came upon me, and I caused the widow's heart to sing for joy.
* `Job 31:19` If I have seen any *_perish_* for lack of clothing, or any poor without covering,
* `Job 34:15` All flesh would *_perish_* together and man would return to dust.
* `Job 36:12` But if they do not obey, they shall *_perish_* by the sword and die without knowledge.
* `Psa 1:6` For the LORD knows the way of the righteous. But the way of the ungodly shall *_perish_*.
* `Psa 2:12` Kiss the Son, lest he be angry, and you *_perish_* from the way, for his wrath may soon be kindled. Blessed are all those who put their trust in him.
* `Psa 9:3` When my enemies are turned back, they shall fall and *_perish_* at your presence.
* `Psa 9:18` For the needy shall not always be forgotten. The expectation of the poor shall not *_perish_* forever.
* `Psa 37:20` But the wicked shall *_perish_*, and the enemies of the LORD shall be like the fat of lambs. They shall consume. Into smoke they shall consume away.
* `Psa 41:5` My enemies speak evil of me, "When shall he die and his name *_perish_*?"
* `Psa 49:10` For he sees that wise men die; likewise the fool and the brutish person *_perish_* and leave their wealth to others.
* `Psa 49:12` Nevertheless, man being in honor does not abide. He is like the beasts that *_perish_*.
* `Psa 49:20` A man who is in honor and does not understand is like the beasts that *_perish_*.
* `Psa 68:2` As smoke is driven away, so drive them away. As wax melts before the fire, so let the wicked *_perish_* at the presence of God.
* `Psa 73:27` For behold, those who are far from you shall *_perish_*. You have destroyed all those who go astray from you.
* `Psa 80:16` It is burnt with fire. It is cut down. They *_perish_* at the rebuke of your countenance.
* `Psa 83:17` Let them be confounded and troubled forever. Let them even be put to shame and *_perish_*,
* `Psa 92:9` For behold, your enemies, O LORD, for behold, your enemies shall *_perish_*. All the workers of iniquity shall be scattered.
* `Psa 102:26` They shall *_perish_*, but you will endure. Indeed, all of them shall grow old like a garment. Like a vesture you will change them, and they shall be changed.
* `Psa 112:10` The wicked shall see it and be grieved. He shall gnash with his teeth and melt away. The desire of the wicked shall *_perish_*.
* `Psa 146:4` His breath goes forth and he returns to the earth. In that very day his thoughts *_perish_*.
* `Pro 10:7` The memory of the just is blessed, but the name of the wicked shall *_perish_*.
* `Pro 10:28` The hope of the righteous shall be gladness, but the expectation of the wicked shall *_perish_*.
* `Pro 11:7` When a wicked man dies, his expectation shall *_perish_*, and the hope of unjust men perishes.
* `Pro 11:10` When the righteous prosper, the city rejoices, and when the wicked *_perish_*, there is shouting.
* `Pro 19:9` A false witness shall not be unpunished, and he who speaks lies shall *_perish_*.
* `Pro 21:28` A false witness shall *_perish_*, but the man who listens shall speak forever.
* `Pro 28:28` When the wicked rise, men hide themselves, but when they *_perish_*, the righteous increase.
* `Pro 29:18` Where there is no vision, the people *_perish_*, but he who keeps the law is happy.
* `Pro 31:6` Give strong drink to him who is ready to *_perish_*, and wine to those who are of heavy hearts.
* `Ecc 5:14` But those riches *_perish_* by evil labor, and if he begets a son, there is nothing in his hand.
* `Isa 26:14` They are dead, they shall not live. They are deceased, they shall not rise. Therefore, you have visited and destroyed them and made all their memory to *_perish_*.
* `Isa 27:13` And it shall come to pass in that day, that the great trumpet shall be blown, and they shall come who were ready to *_perish_* in the land of Assyria, with the outcasts in the land of Egypt, and shall worship the LORD on the holy mountain at Jerusalem.
* `Isa 29:14` Therefore behold, I will proceed to do a marvelous work among this people, even an astonishing work and a wonder. For the wisdom of their wise men shall *_perish_* and the understanding of their prudent men shall be hid."
* `Isa 41:11` Behold, all those who were incensed against you shall be ashamed and confounded. They shall be as nothing. And those who contend with you shall *_perish_*.
* `Isa 57:1` The righteous *_perish_*, and no man lays it to heart. And merciful men are taken away, no one considering that the righteous is taken away from the evil to come.
* `Isa 60:12` For the nation and kingdom that will not serve you shall *_perish_*. Indeed, those nations shall be utterly wasted.
* `Jer 4:9` "And it shall come to pass at that day," says the LORD, "that the heart of the king and the heart of the princes shall *_perish_*, the priests shall be astonished, and the prophets shall wonder."
* `Jer 6:21` Therefore, thus says the LORD: "Behold, I will lay stumbling-blocks before this people, and the fathers and the sons together shall fall upon them. The neighbor and his friend shall *_perish_*."
* `Jer 10:11` Thus you shall say to them: "The gods that have not made the heavens and the earth, even they shall *_perish_* from the earth and from under these heavens."
* `Jer 10:15` They are vanity and the work of errors. In the time of their visitation they shall *_perish_*.
* `Jer 18:18` Then they said, "Come, and let us devise devices against Jeremiah, for the law shall not *_perish_* from the priest, nor counsel from the wise, nor the word from the prophet. Come, and let us smite him with the tongue and not give heed to any of his words."
* `Jer 27:10` For they prophesy a lie to you to remove you far from your land, and that I should drive you out, and you should *_perish_*.
* `Jer 27:15` For I have not sent them," says the LORD, "yet they prophesy a lie in my name so that I might drive you out and that you might *_perish_*—you and the prophets who prophesy to you."
* `Jer 40:15` Then Johanan the son of Kareah spoke to Gedaliah in Mizpah secretly, saying, "Let me go, I pray you, and I will slay Ishmael the son of Nethaniah, and no man shall know it. Why should he slay you so that all the Jews who are gathered to you should be scattered and the remnant of Judah *_perish_*?"
* `Jer 48:8` And the destroyer shall come upon every city, and no city shall escape. The valley shall also *_perish_*, and the plain shall be destroyed, as the LORD has spoken.
* `Jer 48:46` Woe to you, O Moab! The people of Chemosh *_perish_*, for your sons are taken away captive, and your daughters into captivity.
* `Jer 51:18` They are vanity, the work of errors. In the time of their visitation they shall *_perish_*.
* `Ezk 7:26` Mischief shall come upon mischief and rumor shall be upon rumor. Then they shall seek a vision of the prophet, but the law shall *_perish_* from the priest and counsel from the elders.
* `Ezk 25:7` Therefore behold, I will stretch out my hand upon you and will deliver you as plunder to the heathen. I will cut you off from the people and will cause you to *_perish_* out of the countries. I will destroy you. And you shall know that I am the LORD."
* `Dan 2:18` That they would desire mercies of the God of heaven concerning this secret, so that Daniel and his companions should not *_perish_* with the rest of the wise men of Babylon.
* `Amo 1:8` And I will cut off the inhabitant from Ashdod and him who holds the scepter from Ashkelon, and I will turn my hand against Ekron. And the remnant of the Philistines shall *_perish_*," says the Lord GOD.
* `Amo 2:14` Therefore, the flight shall *_perish_* from the swift and the strong shall not strengthen his force, neither shall the mighty deliver himself;
* `Amo 3:15` And I will smite the winter-house together with the summer-house, the houses of ivory shall *_perish_*, and the great houses shall have an end," says the LORD.
* `Jna 1:6` So the ship-master came to him and said to him, "What do you mean, O sleeper? Arise, call upon your God. It may be that God will think upon us so that we do not *_perish_*."
* `Jna 1:14` Therefore, they cried to the LORD, and said, "We implore you, O LORD, we implore you, do not let us *_perish_* for this man's life and do not lay upon us innocent blood. For you, O LORD, have done as it pleased you."
* `Jna 3:9` Who can tell if God will turn and repent and turn away from his fierce anger so that we do not *_perish_*?"
* `Zch 9:5` Ashkelon shall see it and fear. Gaza shall also see it and be very sorrowful, as will Ekron, for her expectation shall be ashamed. And the king shall *_perish_* from Gaza, and Ashkelon shall not be inhabited.
* `Mth 5:29` And if your right eye causes you to sin, pluck it out and cast it from you. For it is profitable for you that one of your members should *_perish_* than for your whole body to be cast into hell.
* `Mth 5:30` And if your right hand causes you to sin, cut it off and cast it from you. For it is profitable for you that one of your members should *_perish_* than for your whole body to be cast into hell.
* `Mth 8:25` And his disciples came to him and awoke him, saying, "Lord, save us. We *_perish_*."
* `Mth 9:17` Men do not put new wine into old bottles, or else the bottles break, the wine runs out, and the bottles *_perish_*. But they put new wine into new bottles and both are preserved."
* `Mth 18:14` Likewise, it is not the will of your Father who is in heaven that one of these little ones should *_perish_*.
* `Mth 26:52` Then Jesus said to him, "Put your sword back into its place. For all those who take the sword shall *_perish_* by the sword.
* `Mrk 4:38` And he was in the back part of the boat asleep on a pillow. And they wake him, and say to him, "Master, do you not care that we *_perish_*?"
* `Luk 5:37` And no man puts new wine into old bottles, or else the new wine will burst the bottles and be spilled and the bottles will *_perish_*.
* `Luk 8:24` And they came to him and awoke him, saying, "Master, master, we *_perish_*." Then he arose and rebuked the wind and the raging of the water. Then they ceased, and there was a calm.
* `Luk 13:3` I tell you, no, but unless you repent, you shall all likewise *_perish_*.
* `Luk 13:5` I tell you, no, but unless you repent, you shall all likewise *_perish_*."
* `Luk 13:33` Nevertheless, I must walk today and tomorrow and the day following, for it cannot be that a prophet should *_perish_* outside of Jerusalem.'
* `Luk 21:18` But there shall not a hair of your head *_perish_*.
* `Jhn 3:15` So that whoever believes in him should not *_perish_*, but have eternal life.
* `Jhn 3:16` "For this is how God loved the world: he gave his only-begotten Son, so that whoever believes in him should not *_perish_* but have eternal life.
* `Jhn 10:28` And I give eternal life to them. They shall never *_perish_*, and no one shall pluck them out of my hand.
* `Jhn 11:50` Nor consider that it is expedient for us that one man should die for the people, and that the whole nation not *_perish_*."
* `Act 8:20` But Peter said to him, "May your money *_perish_* with you because you have thought that the gift of God may be purchased with money.
* `Act 13:41` '"Behold, you despisers, wonder and *_perish_*, for I work a work in your days," a work "which you will in no way believe, though a man declares it to you."'"
* `Rom 2:12` For as many as have sinned without law shall also *_perish_* without law, and as many as have sinned in the law shall be judged by the law—
* `1Co 1:18` For the preaching of the cross is foolishness to those who *_perish_*. But to us who are saved, it is the power of God.
* `1Co 8:11` And through your knowledge, shall the weak brother *_perish_*, for whom Christ died?
* `2Co 2:15` For we are to God a sweet savor of Christ among those who are saved and among those who *_perish_*.
* `Col 2:22` Which are all to *_perish_* with use), according to the commandments and doctrines of men?
* `2Th 2:10` And with all deceitfulness of unrighteousness in those who *_perish_* because they did not receive the love of the truth so that they might be saved.
* `Heb 1:11` They shall *_perish_*, but you remain. And they all shall become old as a garment does.
* `Heb 11:31` By faith the harlot Rahab did not *_perish_* with those who did not believe, as she had received the spies with peace.
* `2Pe 2:12` But these, as natural brute beasts made to be taken and destroyed, speak evil of the things that they do not understand. They shall utterly *_perish_* in their own corruption,
* `2Pe 3:9` The Lord is not slack concerning his promise, as some men count slackness, but is patient toward us, not willing that any should *_perish_*, but that all should come to repentance.

_123 verses containing PERISH_

== PERISHED

* `Num 16:33` They and all that belonged to them went down alive into the pit, and the earth closed upon them, and they *_perished_* from among the congregation.
* `Num 21:30` We have shot at them. Heshbon has *_perished_* even to Dibon, and we have laid them waste even to Nophah, which reaches to Medeba."
* `2Sa 1:27` "How the mighty have fallen and the weapons of war *_perished_*!"
* `Job 4:7` Remember, I pray you: who has *_perished_*, being innocent? Or where were the righteous cut off?
* `Job 30:2` Indeed, to what might the strength of their hands profit me, in whom old age had *_perished_*?
* `Psa 9:6` O enemy, destructions have come to a perpetual end, and you have destroyed cities. Their memorial has *_perished_* with them.
* `Psa 10:16` The LORD is King forever and ever. The heathen have *_perished_* out of his land.
* `Psa 83:10` Who *_perished_* at En-dor. They became like dung for the earth.
* `Psa 119:92` Unless your law had been my delight, I would have *_perished_* in my affliction.
* `Ecc 9:6` Also their love, their hatred, and their envy has now *_perished_*, neither do they have anymore a portion forever in anything that is done under the sun.
* `Jer 7:28` But you shall say to them, 'This is a nation that does not obey the voice of the LORD their God, nor receives correction. Truth has *_perished_* and is cut off from their mouth.
* `Jer 9:12` Who is the wise man who may understand this? And who is he to whom the mouth of the LORD has spoken so that he may declare it? For why has the land *_perished_* and burned up like a wilderness so that no one passes through?
* `Jer 48:36` "Therefore, my heart shall sound for Moab like pipes, and my heart shall sound like pipes for the men of Kirheres because the riches that he has gotten have *_perished_*.
* `Jer 49:7` [Concerning Edom.] Thus says the LORD of hosts: "Is wisdom no longer in Teman? Has counsel *_perished_* from the prudent? Has their wisdom vanished?
* `Lam 3:18` And I said, "My strength and my hope has *_perished_* from the LORD."
* `Joe 1:11` Be ashamed, O farmers. Howl, O vine-dressers, for the wheat and for the barley, because the harvest of the field has *_perished_*.
* `Joe 1:17` The seed has *_perished_* under their clods, the granaries are laid desolate, and the barns are broken down, for the grain has withered.
* `Jna 4:10` Then the LORD said, "You have had pity on the gourd, for which you have not labored, neither made it grow, which came up in a night and *_perished_* in a night.
* `Mic 4:9` Now why do you cry aloud? Is there no king in you? Has your counselor *_perished_*? For pangs have taken you as a woman in travail.
* `Mic 7:2` The godly man has *_perished_* from the earth and there is no one upright among men. They all lie in wait for blood. They each hunt his brother with a net.
* `Mth 8:32` And he said to them, "Go." And when they had come out, they went into the herd of swine. And behold, the whole herd of swine ran violently down a steep place into the sea and *_perished_* in the waters.
* `Luk 11:51` From the blood of Abel to the blood of Zechariah, who *_perished_* between the altar and the temple.' Truly I say to you, it shall be required of this generation.
* `Act 5:37` After this man, Judas of Galilee rose in the days of the taxing and drew away many people after him. He also *_perished_*, and even as many as obeyed him were all dispersed.
* `1Co 15:18` Then those also who have fallen asleep in Christ have *_perished_*.
* `Jms 1:11` For the sun arose with its burning heat and withered the grass. Its flower fell and the grace of its fashion *_perished_*. Likewise also, the rich man shall fade away in his ways.
* `2Pe 3:6` By which the world that then was, being overflowed with water, *_perished_*.
* `Jde 1:11` Woe to them! For they have gone in the way of Cain, have run greedily after the error of Balaam for reward, and have *_perished_* in the gainsaying of Korah.

_27 verses containing PERISHED_

== PERISHES

* `Exo 21:26` "And if a man smites the eye of his man-servant or the eye of his woman-servant so that it *_perishes_*, he shall let him go free for his eye's sake.
* `Job 4:11` The old lion *_perishes_* for lack of prey, and the stout lion's whelps are scattered abroad.
* `Pro 11:7` When a wicked man dies, his expectation shall perish, and the hope of unjust men *_perishes_*.
* `Ecc 7:15` I have seen all things in the days of my vanity. There is a just man who *_perishes_* in his righteousness, and there is a wicked man who prolongs his life in his wickedness.
* `Jhn 6:27` Do not labor for the food which *_perishes_*, but for that food which endures to everlasting life, which the Son of man will give to you, for God the Father has sealed him."
* `2Co 4:16` For which cause we do not faint, but though our outward man *_perishes_*, yet the inward man is renewed day by day.
* `1Pe 1:7` So that the trial of your faith, being much more precious than of gold that *_perishes_*, though tried with fire, might result in praise, honor, and glory at the appearing of Jesus Christ.

_7 verses containing PERISHES_

== PERISHING

* `Job 33:18` He keeps back his soul from the pit and his life from *_perishing_* by the sword.
* `Luk 15:17` And when he came to himself, he said, 'How many hired servants of my father have bread enough to spare, and I am *_perishing_* with hunger!

_2 verses containing PERISHING_

== PERIZZITE

* `Gen 13:7` And there was a strife between the herdsmen of Abram's livestock and the herdsmen of Lot's livestock. And the Canaanite and the *_Perizzite_* dwelt then in the land.
* `Exo 33:2` And I will send an angel before you and will drive out the Canaanite, the Amorite, the Hittite, the *_Perizzite_*, the Hivite, and the Jebusite.
* `Exo 34:11` "Observe that which I command you this day. Behold, I drive out before you the Amorite, the Canaanite, the Hittite, the *_Perizzite_*, the Hivite, and the Jebusite.
* `Jsh 9:1` And it came to pass when all the kings who were on this side of the Jordan heard these things—those in the hills, in the valleys, and in all the coasts of the Great Sea over against Lebanon, the Hittite, the Amorite, the Canaanite, the *_Perizzite_*, the Hivite, and the Jebusite—
* `Jsh 11:3` And to the Canaanite on the east and on the west, to the Amorite, the Hittite, the *_Perizzite_*, the Jebusite in the mountains, and to the Hivite under Hermon in the land of Mizpeh.

_5 verses containing PERIZZITE_

== PERIZZITES

* `Gen 15:20` The Hittites, the *_Perizzites_*, the Rephaims,
* `Gen 34:30` And Jacob said to Simeon and Levi, "You have troubled me to make me odious among the inhabitants of the land, among the Canaanites and the *_Perizzites_*. And I being few in number, they will assemble themselves against me and slay me, and I shall be destroyed—I and my house."
* `Exo 3:8` And I have come down to deliver them from the hand of the Egyptians, and to bring them out of that land to a good and large land, to a land flowing with milk and honey, to the place of the Canaanites, the Hittites, the Amorites, the *_Perizzites_*, the Hivites, and the Jebusites.
* `Exo 3:17` And I have said I will bring you out of the affliction of Egypt to the land of the Canaanites, the Hittites, the Amorites, the *_Perizzites_*, the Hivites, and the Jebusites, to a land flowing with milk and honey."'
* `Exo 23:23` For my Angel shall go before you and bring you to the Amorites, the Hittites, the *_Perizzites_*, the Canaanites, the Hivites, and the Jebusites, and I will cut them off.
* `Deu 20:17` But you shall utterly destroy them, namely, the Hittites, the Amorites, Canaanites, the *_Perizzites_*, Hivites, and the Jebusites, as the LORD your God has commanded you,
* `Jsh 3:10` And Joshua said, "By this you shall know that the living God is among you and that he will without fail drive out from before you the Canaanites, the Hittites, the Hivites, the *_Perizzites_*, the Girgashites, the Amorites, and the Jebusites.
* `Jsh 12:8` In the mountains, in the valleys, in the plains, in the springs, in the wilderness, and in the south country—[the land of] the Hittites, the Amorites, the Canaanites, the *_Perizzites_*, the Hivites, and the Jebusites:
* `Jsh 17:15` And Joshua answered them, "If you are a great people, then go up to the forest and cut down for yourself there in the land of the *_Perizzites_* and of the Rephaim, since mount Ephraim is too narrow for you."
* `Jsh 24:11` And you went over the Jordan and came to Jericho, and the men of Jericho fought against you—the Amorites, the *_Perizzites_*, the Canaanites, the Hittites, the Girgashites, the Hivites, and the Jebusites—and I delivered them into your hand.
* `Jdg 1:4` And Judah went up, and the LORD delivered the Canaanites and the *_Perizzites_* into their hand. And they slew ten thousand men in Bezek.
* `Jdg 1:5` And they found Adoni-bezek in Bezek and fought against him, and they slew the Canaanites and the *_Perizzites_*.
* `Jdg 3:5` And the children of Israel dwelt among the Canaanites, Hittites, Amorites, *_Perizzites_*, Hivites, and Jebusites.
* `1Ki 9:20` And all the people who were left of the Amorites, Hittites, *_Perizzites_*, Hivites, and Jebusites, who were not of the children of Israel,
* `2Ch 8:7` As for all the people who were left of the Hittites, the Amorites, the *_Perizzites_*, the Hivites, and the Jebusites, who were not of Israel—
* `Ezr 9:1` Now when these things were done, the princes came to me, saying, "The people of Israel, the priests, and the Levites have not separated themselves from the people of the lands, doing according to their abominations, even of the Canaanites, the Hittites, the *_Perizzites_*, the Jebusites, the Ammonites, the Moabites, the Egyptians, and the Amorites.
* `Neh 9:8` And found his heart faithful before you and made a covenant with him, to give the land of the Canaanites, the Hittites, the Amorites, the *_Perizzites_*, the Jebusites, and the Girgashites, to give it to his offspring, and have performed your words, for you are righteous.

_17 verses containing PERIZZITES_

== PERJURED

* `1Ti 1:10` For lewd persons, for those who defile themselves with mankind, for kidnappers, for liars, for *_perjured_* persons, and if there is any other thing that is contrary to sound doctrine,

_1 verse containing PERJURED_

== PERMISSION

* `1Co 7:6` But I speak this by *_permission_* and not as a commandment.

_1 verse containing PERMISSION_

== PERMITS

* `1Co 16:7` For I do not wish to see you merely in passing, but I trust to remain a while with you, if the Lord *_permits_*.
* `Heb 6:3` And this we will do, if God *_permits_*.

_2 verses containing PERMITS_

== PERMITTED

* `Act 26:1` Then Agrippa said to Paul, "You are *_permitted_* to speak for yourself." Then Paul stretched forth the hand and answered for himself.
* `1Co 14:34` Let your women be silent in the churches. For it is not *_permitted_* for them to speak, but they are commanded to be under obedience, as also says the law.

_2 verses containing PERMITTED_

== PERNICIOUS

* `2Pe 2:2` And many will follow their *_pernicious_* ways, by reason of whom the way of truth will be blasphemed.

_1 verse containing PERNICIOUS_

== PERPETUAL

* `Gen 9:12` And God said, "This is the token of the covenant which I make between me and you and every living creature that is with you for *_perpetual_* generations:
* `Exo 29:9` And you shall gird them with girdles (Aaron and his sons) and put the caps on them. And the priest's office shall be theirs for a *_perpetual_* statute. And you shall consecrate Aaron and his sons.
* `Exo 30:8` And when Aaron lights the lamps at evening, he shall burn incense upon it, a *_perpetual_* incense before the LORD throughout your generations.
* `Exo 31:16` Therefore, the children of Israel shall keep the sabbath to observe the sabbath throughout their generations for a *_perpetual_* covenant.
* `Lev 3:17` It shall be a *_perpetual_* statute for your generations throughout all your dwellings that you eat neither fat nor blood.'"
* `Lev 6:20` "This is the offering of Aaron and of his sons, which they shall offer to the LORD in the day when he is anointed: the tenth part of an ephah of fine flour for a *_perpetual_* food-offering, half of it in the morning and half of it at night.
* `Lev 24:9` And it shall be Aaron's and his sons', and they shall eat it in the holy place, for it is most holy to him from the offerings of the LORD made by fire by a *_perpetual_* statute."
* `Lev 25:34` But the field of the suburbs of their cities may not be sold, for it is their *_perpetual_* possession.
* `Num 19:21` And it shall be a *_perpetual_* statute to them, that he who sprinkles the water of separation shall wash his clothes, and he who touches the water of separation shall be unclean until the evening.
* `Psa 9:6` O enemy, destructions have come to a *_perpetual_* end, and you have destroyed cities. Their memorial has perished with them.
* `Psa 74:3` Lift up your feet to the *_perpetual_* desolations, even all that the enemy has done wickedly in the sanctuary.
* `Psa 78:66` And he smote his enemies backward. He put them to a *_perpetual_* reproach.
* `Jer 5:22` Do you not fear me?' says the LORD. 'Will you not tremble at my presence, who have placed the sand for the bound of the sea by a *_perpetual_* decree so that it cannot pass it? And though its waves toss themselves, yet they cannot prevail. Even though they roar, yet they cannot pass over it.
* `Jer 8:5` Why then has this people of Jerusalem slid back by a *_perpetual_* backsliding? They hold fast deceit. They refuse to return.
* `Jer 15:18` Why is my pain *_perpetual_* and my wound incurable, which refuses to be healed? Will you be altogether to me like a liar and like waters that fail?
* `Jer 18:16` To make their land desolate and a *_perpetual_* hissing. Everyone who passes by it shall be astonished and wag his head.
* `Jer 23:40` And I will bring upon you an everlasting reproach and a *_perpetual_* shame which shall not be forgotten."
* `Jer 25:9` Behold, I will send and take all the families of the north,' says the LORD, 'and Nebuchadnezzar the king of Babylon, my servant, and will bring them against this land, against its inhabitants, and against all these nations around, and will utterly destroy them and make them an astonishment, a hissing, and *_perpetual_* desolations.
* `Jer 25:12` 'And it shall come to pass when seventy years are accomplished, that I will punish the king of Babylon and that nation,' says the LORD, 'for their iniquity, the land of the Chaldeans, and will make it *_perpetual_* desolations.
* `Jer 49:13` For I have sworn by myself," says the LORD, "that Bozrah shall become a desolation, a reproach, a waste, and a curse, and all her cities shall be *_perpetual_* wastes."
* `Jer 50:5` They shall ask the way to Zion with their faces toward it, saying, 'Come, and let us join ourselves to the LORD in a *_perpetual_* covenant that shall not be forgotten.'
* `Jer 51:39` In their heat I will make their feasts, and I will make them drunken so that they may rejoice and sleep a *_perpetual_* sleep and not wake," says the LORD.
* `Jer 51:57` "And I will make drunk her princes, her wise men, her captains, her rulers, and her mighty men. And they shall sleep a *_perpetual_* sleep and not wake," says the King, whose name is the LORD of hosts.
* `Ezk 35:5` "Because you have had a *_perpetual_* hatred and have shed the blood of the children of Israel by the force of the sword in the time of their calamity, in the time that their iniquity had an end,
* `Ezk 35:9` I will make you *_perpetual_* desolations, and your cities shall not return. And you shall know that I am the LORD.
* `Ezk 46:14` And you shall prepare a food-offering for it every morning, the sixth part of an ephah and the third part of a hin of oil to temper with the fine flour, a food-offering continually by a *_perpetual_* ordinance to the LORD.
* `Hab 3:6` He stood and measured the earth. He beheld and drove apart the nations. The everlasting mountains were scattered and the *_perpetual_* hills bowed. His ways are everlasting.
* `Zph 2:9` Therefore, as I live," says the LORD of hosts, the God of Israel, "surely Moab shall be as Sodom and the children of Ammon as Gomorrah, even a place possessed by nettles and salt-pits and a *_perpetual_* desolation. The remnant of my people shall lay them waste and the remainder of my people shall possess them."

_28 verses containing PERPETUAL_

== PERPETUALLY

* `1Ki 9:3` And the LORD said to him, "I have heard your prayer and your supplication that you have made before me. I have hallowed this house which you have built to put my name there forever. And my eyes and my heart shall be there *_perpetually_*.
* `2Ch 7:16` For now I have chosen and sanctified this house so that my name may be there forever. And my eyes and my heart shall be there *_perpetually_*.
* `Amo 1:11` Thus says the LORD: "For three transgressions of Edom, and for four, I will not turn away its punishment, because he pursued his brother with the sword and cast off all pity, and his anger tore *_perpetually_* and he kept his wrath forever.

_3 verses containing PERPETUALLY_

== PERPLEXED

* `Est 3:15` The posts departed, being hastened by the king's commandment, and the decree was given in the palace of Shushan. And the king and Haman sat down to drink, but the city of Shushan was *_perplexed_*.
* `Joe 1:18` How the beasts groan! The herds of livestock are *_perplexed_* because they have no pasture. Even the flocks of sheep are made desolate.
* `Mrk 6:20` For Herod feared John and kept him safe, knowing that he was a just and holy man. And when he heard him, he was very *_perplexed_*, yet he heard him gladly.
* `Luk 9:7` Now Herod the tetrarch heard of all that was done by him. And he was *_perplexed_*, because it was said by some that John had risen from the dead,
* `Luk 24:4` And it came to pass, as they were much *_perplexed_* at this, behold, two men stood by them in shining garments.
* `2Co 4:8` We are troubled on every side, yet not distressed; we are *_perplexed_*, but not in despair;

_6 verses containing PERPLEXED_

== PERPLEXITY

* `Isa 22:5` For the Lord GOD of hosts has set a day of trouble, treading down, and *_perplexity_* in the valley of vision, of breaking down the walls and crying to the mountains.
* `Mic 7:4` The best of them is as a brier. The most upright is sharper than a thorn hedge. The day of your watchmen and your visitation comes. Now shall be their *_perplexity_*.
* `Luk 21:25` "And there shall be signs in the sun, in the moon, and in the stars, and upon the earth distress of nations in *_perplexity_* because of the roaring of the sea and the waves.

_3 verses containing PERPLEXITY_

== PERRIZITES

* `Deu 7:1` "When the LORD your God brings you into the land where you go to possess it and has cast out many nations before you—the Hittites, the Girgashites, the Amorites, the Canaanites, the *_Perrizites_*, the Hivites, and the Jebusites, seven nations greater and mightier than you—

_1 verse containing PERRIZITES_

== PERSECUTE

* `Job 19:22` Why do you *_persecute_* me as God does, and are not satisfied with my flesh?
* `Job 19:28` Therefore, you should say, 'Why do we *_persecute_* him, seeing the root of the matter is found in him?'
* `Psa 7:1` [Shiggaion of David: which he sang to the LORD concerning the words of Cush the Benjaminite.] O LORD my God, I put my trust in you. Save me from all those who *_persecute_* me, and deliver me,
* `Psa 7:5` Let the enemy *_persecute_* my soul and take it. Let him even tread down my life upon the earth and lay my honor in the dust. [Selah.]
* `Psa 31:15` My times are in your hand. Deliver me from the hand of my enemies and from those who *_persecute_* me.
* `Psa 35:3` Draw out the spear also and stop the way against those who *_persecute_* me. Say to my soul, "I am your salvation."
* `Psa 35:6` Let their way be dark and slippery, and let the angel of the LORD *_persecute_* them.
* `Psa 69:26` For they *_persecute_* him whom you have smitten and talk to the grief of those whom you have wounded.
* `Psa 71:11` Saying, "God has forsaken him. *_Persecute_* and take him, for there is no one to deliver him."
* `Psa 83:15` So *_persecute_* them with your tempest and make them afraid with your storm.
* `Psa 119:84` How many are the days of your servant? When will you execute judgment on those who *_persecute_* me?
* `Psa 119:86` All your commandments are faithful. They *_persecute_* me wrongfully. Help me.
* `Jer 17:18` Let them be confounded who *_persecute_* me, but do not let me be confounded. Let them be dismayed, but do not let me be dismayed. Bring upon them the day of evil and destroy them with double destruction.
* `Jer 29:18` And I will *_persecute_* them with the sword, with the famine, and with the pestilence, and will make them a horror to all the kingdoms of the earth to be a curse, an astonishment, a hissing, and a reproach among all the nations where I have driven them,
* `Lam 3:66` *_Persecute_* and destroy them in anger from under the heavens of the LORD.
* `Mth 5:11` "Blessed are you when men revile you, *_persecute_* you, and say all manner of evil against you falsely for my sake.
* `Mth 5:44` But I say to you, love your enemies, bless those who curse you, do good to those who hate you, and pray for those who despitefully use you and *_persecute_* you,
* `Mth 10:23` "But when they *_persecute_* you in this city, flee into another. For truly I say to you, you shall not have gone over the cities of Israel until the Son of man has come.
* `Mth 23:34` "Therefore, behold, I send to you prophets, wise men, and scribes. Some of them you will kill and crucify, and some of them you will scourge in your synagogues and *_persecute_* them from city to city,
* `Luk 11:49` Therefore, the wisdom of God also said, 'I will send them prophets and apostles, and some of them they will slay and *_persecute_*,
* `Luk 21:12` "But before all these, they will lay their hands on you and *_persecute_* you, delivering you up to the synagogues and into prisons, being brought before kings and rulers for my name's sake.
* `Jhn 15:20` Remember the word that I said to you: 'The servant is not greater than his lord.' If they have persecuted me, they will also *_persecute_* you. If they have kept my saying, they will keep yours also.
* `Act 9:4` And he fell to the earth and heard a voice saying to him, "Saul, Saul, why do you *_persecute_* me?"
* `Act 9:5` And he said, "Who are you, Lord?" And the Lord said, "I am Jesus whom you *_persecute_*. It is hard for you to kick against the goads."
* `Act 22:7` And I fell to the ground and heard a voice saying to me, 'Saul, Saul, why do you *_persecute_* me?'
* `Act 22:8` And I answered, 'Who are you, Lord?' And he said to me, 'I am Jesus of Nazareth, whom you *_persecute_*.'
* `Act 26:14` And when we had all fallen to the earth, I heard a voice speaking to me and saying in the Hebrew language, 'Saul, Saul, why do you *_persecute_* me? It is hard for you to kick against the goads.'
* `Act 26:15` And I said, 'Who are you, Lord?' And he said, 'I am Jesus whom you *_persecute_*.
* `Rom 12:14` Bless those who *_persecute_* you. Bless, and do not curse.

_29 verses containing PERSECUTE_

== PERSECUTED

* `Deu 30:7` And the LORD your God will put all these curses upon your enemies and upon those who hate you who have *_persecuted_* you.
* `Psa 109:16` For he did not remember to show mercy, but *_persecuted_* the poor and needy man so that he might even slay the broken in heart.
* `Psa 119:161` [SHIN] Princes have *_persecuted_* me without a cause, but my heart stands in awe of your word.
* `Psa 143:3` For the enemy has *_persecuted_* my soul. He has smitten my life down to the ground. He has made me to dwell in darkness like those who have been long dead.
* `Isa 14:6` He who smote the people in wrath with a continual stroke, he who ruled the nations in anger is *_persecuted_*, and no one hinders.
* `Lam 3:43` [SAMEKH] You have covered with anger and *_persecuted_* us. You have slain. You have not pitied.
* `Mth 5:10` Blessed are those who are *_persecuted_* for righteousness' sake, for theirs is the kingdom of heaven.
* `Mth 5:12` Rejoice, and be exceedingly glad, for your reward in heaven is great. For thus they *_persecuted_* the prophets who were before you.
* `Jhn 5:16` And therefore, the Jews *_persecuted_* Jesus and sought to slay him because he had done these things on the sabbath.
* `Jhn 15:20` Remember the word that I said to you: 'The servant is not greater than his lord.' If they have *_persecuted_* me, they will also persecute you. If they have kept my saying, they will keep yours also.
* `Act 7:52` Which of the prophets have your fathers not *_persecuted_*? And they have slain those who foretold the coming of the Just One, of whom you have now been the betrayers and murderers,
* `Act 22:4` And I *_persecuted_* this way even to death, binding and delivering into prisons both men and women,
* `Act 26:11` And I punished them often in every synagogue and compelled them to blaspheme, and being exceedingly enraged against them, I *_persecuted_* them even to foreign cities.
* `1Co 4:12` And we labor, working with our own hands. Being reviled, we bless. Being *_persecuted_*, we suffer it.
* `1Co 15:9` For I am the least of the apostles, who am not worthy to be called an apostle because I *_persecuted_* the church of God.
* `2Co 4:9` *_Persecuted_*, but not forsaken; cast down, but not destroyed;
* `Gal 1:13` For you have heard of my manner of life in time past in the Jews' religion, that beyond measure I *_persecuted_* the church of God and wasted it,
* `Gal 1:23` But they had only heard: "He who *_persecuted_* us in times past now preaches the faith which he once destroyed."
* `Gal 4:29` But as then he who was born according to the flesh *_persecuted_* him who was born according to the Spirit, even so it is now.
* `1Th 2:15` Who killed both the Lord Jesus and their own prophets and have *_persecuted_* us. And they do not please God and are contrary to all men,
* `Rev 12:13` And when the dragon saw that he was cast to the earth, he *_persecuted_* the woman who brought forth the male child.

_21 verses containing PERSECUTED_

== PERSECUTES

* `Psa 10:2` The wicked in his pride *_persecutes_* the poor. Let them be taken in the devices that they have conceived.

_1 verse containing PERSECUTES_

== PERSECUTING

* `Phl 3:6` Concerning zeal, *_persecuting_* the church; with respect to the righteousness which is by the law, found blameless.

_1 verse containing PERSECUTING_

== PERSECUTION

* `Lam 5:5` Our necks are under *_persecution_*. We labor and have no rest.
* `Mth 13:21` Yet he does not have root in himself, but endures for a while. For when tribulation or *_persecution_* arises because of the word, immediately he is offended.
* `Mrk 4:17` And have no root in themselves, and so endure only for a time. Afterward, when affliction or *_persecution_* arises for the word's sake, immediately they relapse.
* `Act 8:1` And Saul was consenting to his death. And at that time there was a great *_persecution_* against the church which was at Jerusalem, and they were all dispersed throughout the regions of Judea and Samaria, except the apostles.
* `Act 11:19` Now those who were dispersed upon the *_persecution_* that arose about Stephen traveled as far as Phenice, Cyprus, and Antioch, preaching the word to no one but to the Jews only.
* `Act 13:50` But the Jews stirred up the devout and honorable women and the chief men of the city, raised *_persecution_* against Paul and Barnabas, and expelled them from their borders.
* `Rom 8:35` Who shall separate us from the love of Christ? Shall tribulation, distress, *_persecution_*, famine, nakedness, peril, or sword?
* `Gal 5:11` And I, brothers, if I still preach circumcision, why do I still suffer *_persecution_*? Then the offense of the cross has ceased.
* `Gal 6:12` As many as desire to make a fair show in the flesh, they constrain you to be circumcised—only lest they should suffer *_persecution_* for the cross of Christ.
* `2Ti 3:12` And indeed all who desire to live godly in Christ Jesus will suffer *_persecution_*.

_10 verses containing PERSECUTION_

== PERSECUTIONS

* `Mrk 10:30` Who shall not receive one hundred-fold now in this time—houses, brothers, sisters, mothers, children, and lands, along with *_persecutions_*—and in the age to come, eternal life.
* `2Co 12:10` Therefore, I take pleasure in infirmities, in reproaches, in hardships, in *_persecutions_*, in distresses for Christ's sake. For when I am weak, then I am strong.
* `2Th 1:4` So that we ourselves glory in you in the churches of God for your patience and faith in all your *_persecutions_* and tribulations that you endure.
* `2Ti 3:11` *_Persecutions_*, and afflictions which came to me at Antioch, at Iconium, and at Lystra. I endured such *_persecutions_*, and out of them all the Lord delivered me.

_4 verses containing PERSECUTIONS_

== PERSECUTOR

* `1Ti 1:13` I was before a blasphemer, a *_persecutor_*, and injurious, but I obtained mercy because I did it ignorantly in unbelief.

_1 verse containing PERSECUTOR_

== PERSECUTORS

* `Neh 9:11` And you divided the sea before them so that they went through the midst of the sea on the dry land. And you threw their *_persecutors_* into the depths, as a stone into the mighty waters.
* `Psa 7:13` He has also prepared for him the instruments of death. He ordains his arrows against the *_persecutors_*.
* `Psa 119:157` Many are my *_persecutors_* and my enemies, yet I do not decline from your testimonies.
* `Psa 142:6` Attend to my cry, for I am brought very low. Deliver me from my *_persecutors_*, for they are stronger than I am.
* `Jer 15:15` O LORD, you know. Remember me, visit me, and avenge me of my *_persecutors_*. Do not take me away in your patience. Know that for your sake I have suffered rebuke.
* `Jer 20:11` But the LORD is with me like an awesome mighty one; therefore, my *_persecutors_* shall stumble and shall not prevail. They shall be greatly ashamed, for they shall not prosper. Their everlasting disgrace shall never be forgotten.
* `Lam 1:3` [GIMEL] Judah has gone into captivity because of affliction and because of great servitude. She dwells among the heathen. She finds no rest. All her *_persecutors_* overtook her in the midst of distress.
* `Lam 4:19` [QOF] Our *_persecutors_* are swifter than the eagles of heaven. They pursued us upon the mountains. They laid wait for us in the wilderness.

_8 verses containing PERSECUTORS_

== PERSEVERANCE

* `Eph 6:18` Praying always with all prayer and supplication in the Spirit and watching for this purpose with all *_perseverance_* and supplication for all saints.

_1 verse containing PERSEVERANCE_

== PERSIA

* `2Ch 36:20` And those who had escaped from the sword he carried away to Babylon, where they were servants to him and his sons until the reign of the kingdom of *_Persia_*,
* `2Ch 36:22` Now in the first year of Cyrus king of *_Persia_*, so that the word of the LORD spoken by the mouth of Jeremiah might be accomplished, the LORD stirred up the spirit of Cyrus king of *_Persia_* so that he made a proclamation throughout all his kingdom, and put it also in writing, saying,
* `2Ch 36:23` "Thus says Cyrus king of *_Persia_*: 'All the kingdoms of the earth the LORD God of heaven has given me. And he has charged me to build him a house in Jerusalem, which is in Judah. Who is there among you of all his people? May the LORD his God be with him and let him go up.'"
* `Ezr 1:1` Now in the first year of Cyrus king of *_Persia_*, so that the word of the LORD by the mouth of Jeremiah might be fulfilled, the LORD stirred up the spirit of Cyrus king of *_Persia_*, so that he made a proclamation throughout all his kingdom and put it also in writing, saying,
* `Ezr 1:2` "Thus says Cyrus king of *_Persia_*: 'The LORD God of heaven has given me all the kingdoms of the earth, and he has charged me to build him a house at Jerusalem, which is in Judah.
* `Ezr 1:8` And Cyrus king of *_Persia_* brought them forth by the hand of Mithredath the treasurer, and he numbered them to Sheshbazzar, the prince of Judah.
* `Ezr 3:7` They gave money also to the masons and to the carpenters, and provisions, drink, and oil to those of Zidon and to those of Tyre, to bring cedar trees from Lebanon to the sea of Joppa, according to the grant that they had from Cyrus king of *_Persia_*.
* `Ezr 4:3` But Zerubbabel, Jeshua, and the rest of the chief of the fathers of Israel, said to them, "You have nothing to do with us to build a house to our God. But we ourselves together will build to the LORD God of Israel, as king Cyrus the king of *_Persia_* has commanded us."
* `Ezr 4:5` And they hired counselors against them to frustrate their purpose all the days of Cyrus king of *_Persia_*, even until the reign of Darius king of *_Persia_*.
* `Ezr 4:7` And in the days of Artaxerxes, Bishlam, Mithredath, Tabeel, and the rest of their companions wrote to Artaxerxes king of *_Persia_*, and the writing of the letter was written in the Syrian language and interpreted in the Syrian language.
* `Ezr 4:24` Then the work of the house of God which is at Jerusalem ceased. Thus it ceased until the second year of the reign of Darius king of *_Persia_*.
* `Ezr 6:14` And the elders of the Jews built, and they prospered through the prophesying of Haggai the prophet and Zechariah the son of Iddo. And they built and finished it according to the commandment of the God of Israel and according to the commandment of Cyrus, Darius, and Artaxerxes king of *_Persia_*.
* `Ezr 7:1` Now after these things, in the reign of Artaxerxes king of *_Persia_*, Ezra the son of Seraiah, the son of Azariah, the son of Hilkiah,
* `Ezr 9:9` For we were slaves, yet our God has not forsaken us in our bondage, but has extended mercy to us in the sight of the kings of *_Persia_*, to give us a reviving, to set up the house of our God, to repair its desolations, and to give us a wall in Judah and in Jerusalem.
* `Est 1:3` In the third year of his reign, he made a feast to all his princes and his servants. The power of *_Persia_* and Media, the nobles and princes of the provinces, were before him
* `Est 1:14` And were close to him: Carshena, Shethar, Admatha, Tarshish, Meres, Marsena, and Memucan, the seven princes of *_Persia_* and Media, who saw the king's face and who sat the first in the kingdom),
* `Est 1:18` This day, the ladies of *_Persia_* and Media who have heard of the deed of the queen will say the same thing to all the king's princes. Thus there will arise too much contempt and wrath.
* `Est 10:2` And all the acts of his power and of his might, and the declaration of the greatness of Mordecai, to which the king advanced him, are they not written in the book of the chronicles of the kings of Media and *_Persia_*?
* `Ezk 27:10` "They of *_Persia_*, of Lud, and of Phut were in your army, your military men. They hung the shield and helmet in you. They set forth your splendor.
* `Ezk 38:5` *_Persia_*, Cush, and Phut with them, all of them with shield and helmet;
* `Dan 8:20` "The ram which you saw having two horns, these are the kings of Media and *_Persia_*.
* `Dan 10:1` In the third year of Cyrus king of *_Persia_*, a thing was revealed to Daniel, whose name was called Belteshazzar, and the thing was true, but the appointed time was long. And he understood the thing, and had understanding of the vision.
* `Dan 10:13` But the prince of the kingdom of *_Persia_* withstood me twenty-one days. But behold, Michael, one of the chief princes, came to help me, and I remained there with the kings of *_Persia_*.
* `Dan 10:20` Then he said, "Do you know for what cause I come to you? And now I will return to fight with the prince of *_Persia_*. And when I have gone forth, behold, the prince of Grecia shall come.
* `Dan 11:2` And now I will show you the truth. Behold, there shall stand up yet three kings in *_Persia_*. And a fourth shall be far richer than all of them, and by his strength through his riches he shall stir up all against the realm of Grecia.

_25 verses containing PERSIA_

== PERSIAN

* `Neh 12:22` As for the Levites, in the days of Eliashib, Joiada, Johanan, and Jaddua, the chiefs of the fathers were recorded, and also the priests in the reign of Darius the *_Persian_*.
* `Dan 6:28` So this Daniel prospered in the reign of Darius and in the reign of Cyrus the *_Persian_*.

_2 verses containing PERSIAN_

== PERSIANS

* `Est 1:19` If it pleases the king, let a royal commandment go from him, and let it be written among the laws of the *_Persians_* and the Medes so that it may not be altered, that Vashti may no longer come before king Ahasuerus. And let the king give her royal estate to another who is better than she is.
* `Dan 5:28` 'PERES': your kingdom is divided, and given to the Medes and *_Persians_*."
* `Dan 6:8` Now, O king, establish the decree and sign the writing so that it may not be changed, according to the law of the Medes and *_Persians_*, which does not alter."
* `Dan 6:12` Then they came near and spoke before the king concerning the king's decree, "Have you not signed a decree, that every man who asks a petition of any god or man within thirty days, except of you, O king, shall be cast into the den of lions?" The king answered and said, "The thing is true, according to the law of the Medes and *_Persians_*, which does not alter."
* `Dan 6:15` Then these men went together to the king, and said to the king, "Know, O king, that the law of the Medes and *_Persians_* is that no decree nor statute which the king establishes may be changed."

_5 verses containing PERSIANS_

== PERSIS

* `Rom 16:12` Salute Tryphena and Tryphosa, who labor in the Lord. Salute the beloved *_Persis_*, who labored much in the Lord.

_1 verse containing PERSIS_

== PERSON

* `Gen 39:6` And he left all that he had in Joseph's hand, and he did not know anything that he had, except the bread which he ate. And Joseph was a handsome *_person_* and well favored.
* `Exo 12:48` And when a stranger sojourns with you and wishes to keep the passover to the LORD, let all his males be circumcised and then let him come near and keep it, and he shall be as one who is born in the land. For no uncircumcised *_person_* shall eat it.
* `Lev 19:15` 'You shall do no unrighteousness in judgment. You shall not respect the *_person_* of the poor nor honor the *_person_* of the mighty, but in righteousness you shall judge your neighbor.
* `Num 5:6` "Speak to the children of Israel, 'When a man or woman commits any sin that men commit to do a trespass against the LORD, and that *_person_* is guilty,
* `Num 19:17` And for an unclean *_person_* they shall take some of the ashes of the burnt heifer of purification for sin, and running water shall be put to it in a vessel.
* `Num 19:18` And a clean *_person_* shall take hyssop, dip it in the water, and sprinkle it upon the tent, upon all the vessels, upon the persons who were there, and upon him who touched a bone, someone slain, someone dead, or a grave.
* `Num 19:19` And the clean *_person_* shall sprinkle upon the unclean on the third day and on the seventh day. And on the seventh day he shall purify himself, wash his clothes, bathe himself in water, and shall be clean at evening.
* `Num 19:22` And whatever the unclean *_person_* touches shall be unclean, and the soul who touches it shall be unclean until the evening.'"
* `Num 31:19` And you, abide outside the camp seven days. Whoever has killed any *_person_* and whoever has touched any slain, purify both yourselves and your captives on the third day and on the seventh day.
* `Num 35:11` You shall appoint for yourselves cities to be cities of refuge for you so that the slayer may flee there who kills any *_person_* unintentionally.
* `Num 35:15` These six cities shall be a refuge for the children of Israel, for the stranger, and for the sojourner among them so that everyone who kills any *_person_* unintentionally may flee there.
* `Num 35:30` 'Whoever kills any *_person_*, the murderer shall be put to death by the mouth of witnesses. But one witness shall not testify against any *_person_* to cause him to die.
* `Deu 15:22` You shall eat it within your gates. The unclean and the clean *_person_* shall eat it alike, as they would the gazelle or the deer.
* `Deu 27:25` 'Cursed is he who takes reward to slay an innocent *_person_*.' And all the people shall say, 'Amen.'
* `Deu 28:50` A nation of fierce countenance which shall not regard the *_person_* of the old nor show favor to the young.
* `Jsh 20:3` So that the slayer who kills any *_person_* unintentionally and ignorantly may flee there. And they shall be your refuge from the avenger of blood.
* `Jsh 20:9` These were the cities appointed for all the children of Israel and for the stranger sojourning among them, so that whoever kills any *_person_* unintentionally might flee there and not die by the hand of the avenger of blood until he stood before the congregation.
* `1Sa 9:2` And he had a son whose name was Saul, a choice and handsome young man. And there was not among the children of Israel a more handsome *_person_* than he was. From his shoulders and upward he was higher than any of the people.
* `1Sa 16:18` Then one of the servants answered and said, "Behold, I have seen a son of Jesse the Beth-lehemite who is skillful in playing, a mighty valiant man, a man of war, prudent in matters, and a handsome *_person_*, and the LORD is with him."
* `1Sa 25:22` May God do so and more also to the enemies of David if I leave of all that pertain to him by the morning light any male *_person_*.")
* `1Sa 25:34` For indeed, as the LORD God of Israel lives, who has kept me back from hurting you, unless you had hastened and come to meet me, surely there had not been left to Nabal by the morning light any male *_person_*."
* `1Sa 25:35` So David received from her hand that which she had brought him and said to her, "Return in peace to your house. Behold, I have listened to your voice and have accepted your *_person_*."
* `2Sa 4:11` How much more, when wicked men have slain a righteous *_person_* in his own house upon his bed, should I not now require his blood at your hand and take you away from the earth?"
* `2Sa 14:14` For we must die and are like water spilled on the ground which cannot be gathered up again. God does not respect any *_person_*, yet he devises means so that his banished is not expelled from him.
* `2Sa 17:11` Therefore, I counsel that all Israel should be generally gathered to you, from Dan even to Beer-sheba, as the sand that is by the sea for multitude, and that you should go to battle in your own *_person_*.
* `Job 13:8` Will you accept his *_person_*? Will you contend for God?
* `Job 22:29` When men are cast down, you shall say, 'There is exaltation,' and he shall save the humble *_person_*.
* `Job 32:21` Do not let me, I pray you, accept any man's *_person_*, neither let me give flattering titles to man.
* `Psa 15:4` In whose eyes a vile *_person_* is despised, but he honors those who fear the LORD; he who swears to his own hurt and does not change;
* `Psa 49:10` For he sees that wise men die; likewise the fool and the brutish *_person_* perish and leave their wealth to others.
* `Psa 101:4` A perverse heart shall depart from me. I will not know a wicked *_person_*.
* `Psa 105:37` He also brought them forth with silver and gold. And there was not one feeble *_person_* among their tribes.
* `Pro 6:12` A worthless *_person_*, a wicked man, walks with a crooked mouth.
* `Pro 18:5` It is not good to accept the *_person_* of the wicked or to overthrow the righteous in judgment.
* `Pro 24:8` He who devises to do evil shall be called a mischievous *_person_*.
* `Pro 28:17` A man who does violence to the blood of any *_person_* shall flee to the pit. Let no man stay him.
* `Isa 32:5` The vile *_person_* shall no longer be called liberal, nor the churl said to be bountiful.
* `Isa 32:6` For the vile *_person_* will speak villainy, and his heart will work iniquity, to practice hypocrisy and to utter error against the LORD, to make the soul of the hungry empty, and to cause the drink of the thirsty to fail.
* `Jer 43:6` Even men, women, children, the king's daughters, and every *_person_* that Nebuzar-adan the captain of the guard had left with Gedaliah the son of Ahikam, the son of Shaphan, and Jeremiah the prophet, and Baruch the son of Neriah.
* `Jer 52:25` He also took a eunuch out of the city who had the charge of the men of war, seven men of those who were near the king's *_person_* who were found in the city, the principal scribe of the host who mustered the people of the land, and sixty men of the people of the land who were found in the midst of the city.
* `Ezk 33:6` But if the watchman sees the sword come and does not blow the trumpet, and the people are not warned, if the sword comes and takes any *_person_* from among them, he is taken away in his iniquity, but his blood I will require at the watchman's hand.'
* `Ezk 44:25` And they shall not come near to a dead *_person_* to defile themselves. But for father, for mother, for son, for daughter, for brother, or for sister who has had no husband, they may defile themselves.
* `Dan 11:21` And in his estate a vile *_person_* shall stand up, to whom they shall not give the honor of the kingdom, but he shall come in peaceably and obtain the kingdom by flatteries.
* `Mal 1:8` "And if you offer the blind for sacrifice, 'It is not evil!' And if you offer the lame and sick, 'It is not evil!' Offer it now to your governor. Will he be pleased with you, or accept your *_person_*?" says the LORD of hosts.
* `Mal 1:9` "And now, I pray you, implore God that he will be gracious to us. This has been by your means. Will he regard your *_person_*?" says the LORD of hosts.
* `Mth 22:16` And they sent their disciples out to him along with the Herodians, saying, "Master, we know that you are true and teach the way of God in truth, neither do you care for any man, for you do not regard the *_person_* of men.
* `Mth 27:24` When Pilate saw that he could not prevail at all, but that rather a tumult was made, he took water and washed his hands before the multitude, saying, "I am innocent of the blood of this just *_person_*. See to it yourselves."
* `Mrk 12:14` And when they had come, they say to him, "Master, we know that you are true and care for no man, for you do not regard the *_person_* of men, but teach the way of God in truth. Is it lawful to give tribute to Caesar, or not?
* `Luk 20:21` And they asked him, saying, "Master, we know that you say and teach rightly, neither do you accept the *_person_* of any, but teach the way of God truly.
* `1Co 5:11` But now I have written to you not to keep company with any man who is called a brother if he is a lewd *_person_*, covetous, an idolater, a railer, a drunkard, or an extortioner. Do not even eat with such a *_person_*.
* `1Co 5:13` But those who are outside God judges. "Therefore, put away from among yourselves that wicked *_person_*."
* `Gal 2:6` But of these, who seemed to be something (whatever they were, it makes no matter to me—God accepts no man's *_person_*), for those who seemed to be something, in conference added nothing to me.
* `Eph 5:5` For this you know, that no lewd *_person_*, unclean *_person_*, or covetous man, who is an idolater, has any inheritance in the kingdom of Christ and of God.
* `Heb 1:3` He is the brightness of his glory and the express image of his *_person_*, and upholding all things by the word of his power, when he had by himself made purification of our sins, sat down on the right hand of the Majesty on high,
* `Heb 12:16` Lest there be any fornicator or profane *_person_* like Esau, who sold his birth-right for one morsel of food.
* `1Pe 3:4` But let it be the hidden *_person_* of the heart, in that which is not corruptible, even the ornament of a meek and quiet spirit, which is in the sight of God of great price.
* `2Pe 2:5` And did not spare the old world, but saved Noah the eighth *_person_*, a preacher of righteousness, bringing the flood upon the world of the ungodly,

_57 verses containing PERSON_

== PERSONS

* `Gen 14:21` And the king of Sodom said to Abram, "Give me the *_persons_* and take the goods for yourself."
* `Gen 36:6` And Esau took his wives, his sons, his daughters, all the *_persons_* of his house, his livestock, all his beasts, and all his substance which he had acquired in the land of Canaan, and went into the country from the face of his brother Jacob.
* `Exo 16:16` This is the thing which the LORD has commanded: 'Every man is to gather from it according to his eating. You shall take an omer for every man according to the number of your *_persons_*, each for those who are in his tent.'"
* `Lev 27:2` "Speak to the children of Israel and say to them, 'When a man makes a singular vow, the *_persons_* shall be for the LORD by your estimation.
* `Num 19:18` And a clean person shall take hyssop, dip it in the water, and sprinkle it upon the tent, upon all the vessels, upon the *_persons_* who were there, and upon him who touched a bone, someone slain, someone dead, or a grave.
* `Num 31:28` And levy a tribute to the LORD of the men of war who went out to battle, one soul of five hundred, both of the *_persons_*, of the bulls, of the donkeys, and of the sheep.
* `Num 31:30` And of the children of Israel's half, you shall take one portion of fifty of the *_persons_*, of the bulls, of the donkeys, and of the flocks, of all manner of beasts, and give them to the Levites who keep the charge of the tabernacle of the LORD."
* `Num 31:35` And thirty-two thousand *_persons_* in all, of women who had not known man by lying with him.
* `Num 31:40` And the *_persons_* were sixteen thousand, of which the LORD'S tribute was thirty-two *_persons_*.
* `Num 31:46` And sixteen thousand *_persons_*),
* `Deu 1:17` You shall not respect *_persons_* in judgment, but you shall hear the small as well as the great. You shall not be afraid of the face of man, for the judgment is God's. And the cause that is too hard for you, bring to me, and I will hear it.'
* `Deu 10:17` For the LORD your God is God of gods and Lord of lords, a great, a mighty, and an awesome God, who does not regard *_persons_* nor take reward.
* `Deu 10:22` Your fathers went down into Egypt with seventy *_persons_*, and now the LORD your God has made you as the stars of heaven for multitude."
* `Deu 16:19` You shall not wrest judgment. You shall not respect *_persons_*, neither take a gift, for a gift blinds the eyes of the wise and perverts the words of the righteous.
* `Jdg 9:2` "Speak, I pray you, in the ears of all the men of Shechem, 'Which is better for you, either that all the sons of Jerubbaal, which are seventy *_persons_*, should reign over you, or that one should reign over you?' Remember also that I am your bone and your flesh."
* `Jdg 9:4` And they gave him seventy pieces of silver out of the house of Baal-berith, with which Abimelech hired vain and light *_persons_* who followed him.
* `Jdg 9:5` And he went to his father's house at Ophrah and slew his brothers the sons of Jerubbaal, being seventy *_persons_*, upon one stone. But Jotham the youngest son of Jerubbaal was left, for he hid himself.
* `Jdg 9:18` And you have risen up against my father's house this day and have slain his sons, seventy *_persons_*, upon one stone, and have made Abimelech, the son of his woman-servant, king over the men of Shechem, because he is your brother),
* `Jdg 20:39` And when the men of Israel retired in the battle, Benjamin began to smite and kill about thirty *_persons_* of the men of Israel. For they said, "Surely they are smitten down before us as in the first battle."
* `1Sa 9:22` And Samuel took Saul and his servant, brought them into the chamber, and made them sit in the chief place among those who were invited, who were about thirty *_persons_*.
* `1Sa 22:18` And the king said to Doeg, "Turn, and fall upon the priests." And Doeg the Edomite turned and he fell upon the priests and slew on that day eighty-five *_persons_* who wore a linen ephod.
* `1Sa 22:22` And David said to Abiathar, "I knew that day, when Doeg the Edomite was there, that he would surely tell Saul. I have occasioned the death of all the *_persons_* of your father's house.
* `2Ki 10:6` Then he wrote a letter the second time to them, saying, "If you are mine and if you will listen to my voice, take the heads of the men, your master's sons, and come to me to Jezreel by tomorrow this time." Now the king's sons, being seventy *_persons_*, were with the great men of the city who brought them up.
* `2Ki 10:7` And it came to pass when the letter came to them, that they took the king's sons and slew them, seventy *_persons_*, and put their heads in baskets and sent them to him at Jezreel.
* `2Ch 19:7` Now therefore, let the fear of the LORD be upon you. Take heed and do it, for there is no iniquity with the LORD our God, nor respect of *_persons_*, nor taking of gifts."
* `Job 13:10` He will surely reprove you, if you secretly accept *_persons_*.
* `Job 34:19` How much less to him who does not accept the *_persons_* of princes, nor regards the rich more than the poor? For they all are the work of his hands.
* `Psa 26:4` I have not sat with vain *_persons_*, neither will I go in with dissemblers.
* `Psa 82:2` "How long will you judge unjustly and accept the *_persons_* of the wicked?" [Selah.]
* `Pro 12:11` He who tills his land shall be satisfied with bread, but he who follows vain *_persons_* is void of understanding.
* `Pro 24:23` These things also belong to the wise. It is not good to have respect of *_persons_* in judgment.
* `Pro 28:19` He who tills his land shall have plenty of bread, but he who follows after vain *_persons_* shall be filled with poverty.
* `Pro 28:21` To have respect of *_persons_* is not good, because for a piece of bread a man will transgress.
* `Jer 52:29` In the eighteenth year of Nebuchadnezzar, he carried away captive from Jerusalem eight hundred and thirty-two *_persons_*;
* `Jer 52:30` In the twenty-third year of Nebuchadnezzar, Nebuzar-adan the captain of the guard carried away captive of the Jews seven hundred and forty-five *_persons_*. All the *_persons_* were four thousand and six hundred.
* `Lam 4:16` [AYIN] The anger of the LORD has divided them. He will no longer regard them. They did not respect the *_persons_* of the priests. They did not favor the elders.
* `Ezk 27:13` Javan, Tubal, and Meshech, they were your merchants. They traded in the *_persons_* of men and vessels of brass in your market.
* `Jna 4:11` And should I not spare Nineveh, that great city, in which are more than one hundred and twenty thousand *_persons_* who cannot discern between their right hand and their left hand—and also a large number of livestock?"
* `Zph 3:4` Her prophets are unstable and treacherous *_persons_*. Her priests have polluted what is holy. They have done violence to the law.
* `Mrk 6:5` And he could do no mighty work there, except that he laid his hands upon a few sick *_persons_* and healed them.
* `Luk 15:7` I say to you, that likewise, joy shall be in heaven over one sinner who repents, more than over ninety-nine just *_persons_* who need no repentance.
* `Act 5:16` There also came a multitude out of the cities around to Jerusalem bringing sick *_persons_* and those who were afflicted with unclean spirits, and they were all healed.
* `Act 10:34` Then Peter opened his mouth, and said, "In truth I perceive that God is no respecter of *_persons_*.
* `Act 17:17` Therefore, he disputed in the synagogue with the Jews and with the devout *_persons_*, and in the market daily with those who met with him.
* `Rom 2:11` For there is no respect of *_persons_* with God.
* `1Co 5:9` I have written to you in this epistle not to associate with *_persons_* guilty of lewdness—
* `1Co 5:10` Yet not altogether with lewd *_persons_* of this world, or with the covetous, extortioners, or with idolaters, for then you would have to go out of the world.
* `2Co 1:11` You also helping together by prayer for us, so that for the gift bestowed upon us by the means of many *_persons_*, thanks may be given by many on our behalf.
* `Eph 6:9` And masters, do the same things to them, forbearing threatening, knowing that your Master also is in heaven, neither is there respect of *_persons_* with him.
* `Col 3:25` But he who does wrong will receive for the wrong which he has done. And there is no respect of *_persons_*.
* `1Ti 1:10` For lewd *_persons_*, for those who defile themselves with mankind, for kidnappers, for liars, for perjured *_persons_*, and if there is any other thing that is contrary to sound doctrine,
* `Heb 13:4` Let marriage be held in honor among all, and let the bed be undefiled, but God will judge lewd *_persons_* and adulterers.
* `Jms 2:1` My brothers, do not have the faith of our Lord Jesus Christ, the Lord of glory, with respect of *_persons_*.
* `Jms 2:9` But if you have respect to *_persons_*, you commit sin and are convicted by the law as transgressors.
* `1Pe 1:17` And if you call on the Father, who, without respect of *_persons_*, judges according to every man's work, pass the time of your sojourning here in fear,
* `2Pe 3:11` Seeing then that all these things will be dissolved, what manner of *_persons_* ought you to be in all holy deportment and godliness,
* `Jde 1:16` These are murmurers and complainers, walking after their own lusts, and their mouth speaks great swelling words, having men's *_persons_* in admiration for the sake of profit.

_57 verses containing PERSONS_

== PERSUADE

* `1Ki 22:20` And the LORD said, 'Who shall *_persuade_* Ahab that he may go up and fall at Ramoth-gilead?' And one said in this manner and another said in that manner.
* `1Ki 22:21` And there came forth a spirit and stood before the LORD and said, 'I will *_persuade_* him.'
* `1Ki 22:22` And the LORD said to him, 'With what?' And he said, 'I will go forth and be a lying spirit in the mouth of all his prophets.' And he said, 'You shall *_persuade_* him and prevail also. Go forth and do so.'
* `2Ch 32:11` Does Hezekiah not *_persuade_* you to give over yourselves to die by famine and by thirst, saying, "The LORD our God will deliver us out of the hand of the king of Assyria"?
* `2Ch 32:15` Now therefore, do not let Hezekiah deceive you, nor *_persuade_* you in this manner, neither yet believe him. For no god of any nation or kingdom has been able to deliver his people out of my hand and out of the hand of my fathers. How much less shall your God deliver you out of my hand?'"
* `Isa 36:18` Beware lest Hezekiah *_persuade_* you, saying, "The LORD will deliver us." Has any of the gods of the nations delivered his land out of the hand of the king of Assyria?
* `Mth 28:14` And if this comes to the governor's ears, we will *_persuade_* him and secure you."
* `Act 26:28` Then Agrippa said to Paul, "You almost *_persuade_* me to be a Christian."
* `2Co 5:11` Knowing therefore the terror of the Lord, we *_persuade_* men, but we are made manifest to God, and I trust also are made manifest in your consciences.
* `Gal 1:10` For do I now *_persuade_* men, or God? Or do I seek to please men? For if I still pleased men, I would not be the servant of Christ.

_10 verses containing PERSUADE_

== PERSUADED

* `2Ch 18:2` And after some years he went down to Ahab in Samaria. And Ahab killed sheep and oxen in abundance for him and for the people who were with him, and *_persuaded_* him to go up with him to Ramoth-gilead.
* `Pro 25:15` By long forbearing a prince is *_persuaded_*, and a soft tongue breaks the bone.
* `Mth 27:20` But the chief priests and elders *_persuaded_* the multitude that they should ask for Barabbas and destroy Jesus.
* `Luk 16:31` And he said to him, 'If they do not hear Moses and the prophets, neither will they be *_persuaded_* if one rises from the dead.'"
* `Luk 20:6` But if we say, 'From men,' all the people will stone us, for they are *_persuaded_* that John was a prophet."
* `Act 13:43` Now when the congregation was broken up, many of the Jews and religious proselytes followed Paul and Barnabas, who, speaking to them, *_persuaded_* them to continue in the grace of God.
* `Act 14:19` And some Jews from Antioch and Iconium came there, who *_persuaded_* the people. And having stoned Paul, they drew him out of the city supposing him to be dead.
* `Act 18:4` And he reasoned in the synagogue every sabbath and *_persuaded_* the Jews and the Greeks.
* `Act 19:26` Moreover, you see and hear, that not at Ephesus alone, but almost throughout all Asia, this Paul has *_persuaded_* and turned away many people, saying that they are no gods which are made with hands.
* `Act 21:14` And when he would not be *_persuaded_*, we ceased, saying, "May the will of the Lord be done."
* `Act 26:26` For the king knows of these things, before whom also I speak freely. For I am *_persuaded_* that none of these things are hidden from him, for this thing was not done in a corner.
* `Rom 4:21` And being fully *_persuaded_* that what he had promised he was also able to perform.
* `Rom 8:38` For I am *_persuaded_* that neither death, life, angels, principalities, powers, things present, things to come,
* `Rom 14:5` One man esteems one day above another, but another esteems every day alike. Let every man be fully *_persuaded_* in his own mind.
* `Rom 14:14` I know and am *_persuaded_* by the Lord Jesus that there is nothing unclean by itself. But to him who esteems anything to be unclean, to him it is unclean.
* `Rom 15:14` And I myself also am *_persuaded_* concerning you, my brothers, that you also are full of goodness, filled with all knowledge, able also to admonish one another.
* `2Ti 1:5` When I call to remembrance the unfeigned faith that is in you, which dwelt first in your grandmother Lois and your mother Eunice, and I am *_persuaded_* that is in you also.
* `2Ti 1:12` For this cause, I also suffer these things. Nevertheless, I am not ashamed, for I know whom I have believed and am *_persuaded_* that he is able to keep that which I have committed to him for that day.
* `Heb 6:9` But, beloved, we are *_persuaded_* of better things for you, and things that accompany salvation, though we speak in this manner.

_19 verses containing PERSUADED_

== PERSUADES

* `2Ki 18:32` Until I come and take you away to a land like your own land, a land of grain and wine, a land of bread and vineyards, a land of olive-oil and of honey, so that you may live and not die." And do not listen to Hezekiah when he *_persuades_* you, saying, "The LORD will deliver us."
* `Act 18:13` Saying, "This man *_persuades_* men to worship God contrary to the law."

_2 verses containing PERSUADES_

== PERSUADING

* `Act 19:8` And he went into the synagogue and spoke boldly for three months, disputing and *_persuading_* the things concerning the kingdom of God.
* `Act 28:23` And when they had appointed him a day, many came to him into his lodging. He expounded to them from morning until evening, testifying about the kingdom of God and *_persuading_* them concerning Jesus, both out of the law of Moses and out of the prophets.

_2 verses containing PERSUADING_

== PERSUASION

* `Gal 5:8` This *_persuasion_* does not come from him who calls you.

_1 verse containing PERSUASION_

== PERTAIN

* `Lev 7:20` But the soul who eats the flesh of the sacrifice of peace-offerings that *_pertain_* to the LORD, having his uncleanness upon him, even that soul shall be cut off from his people.
* `Lev 7:21` Moreover, the soul who touches any unclean thing, whether the uncleanness of man, any unclean beast, or any abominable unclean thing, and eats the flesh of the sacrifice of peace-offerings which *_pertain_* to the LORD, even that soul shall be cut off from his people.'"
* `Num 4:16` "And to the office of Eleazar the son of Aaron the priest *_pertain_* the oil for the light, the sweet incense, the daily food-offering, the anointing oil, the oversight of all the tabernacle, and of all that is in it, in the sanctuary, and in its vessels."
* `1Sa 25:22` May God do so and more also to the enemies of David if I leave of all that *_pertain_* to him by the morning light any male person.")
* `Rom 9:4` Who are Israelites, to whom *_pertain_* the adoption, the glory, the covenants, the giving of the law, the service of God, and the promises,
* `Rom 15:17` Therefore, I have cause for glorying through Jesus Christ in those things which *_pertain_* to God.
* `1Co 6:3` Do you not know that we shall judge angels? How much more things that *_pertain_* to this life?
* `2Pe 1:3` According as his divine power has given to us all things that *_pertain_* to life and godliness through the knowledge of him who has called us to glory and virtue,

_8 verses containing PERTAIN_

== PERTAINED

* `Num 31:43` (Now the half that *_pertained_* to the congregation was three hundred and thirty-seven thousand and five hundred sheep,
* `Jsh 24:33` And Eleazar the son of Aaron died, and they buried him on a hill that *_pertained_* to Phinehas his son, which was given to him on mount Ephraim.
* `Jdg 6:11` And an angel of the LORD came and sat under an oak which was in Ophrah that *_pertained_* to Joash the Abi-ezrite. And his son Gideon threshed wheat by the wine-press to hide it from the Midianites.
* `1Sa 25:21` (Now David had said, "Surely in vain I have kept all that this man has in the wilderness so that nothing was missed of all that *_pertained_* to him, and he has requited me evil for good.
* `2Sa 2:15` Then there arose and went over by number twelve from Benjamin, who *_pertained_* to Ish-bosheth the son of Saul, and twelve from the servants of David.
* `2Sa 9:9` Then the king called to Ziba, Saul's servant, and said to him, "I have given to your master's son all that *_pertained_* to Saul and to all his house.
* `2Sa 16:4` Then the king said to Ziba, "Behold, all that *_pertained_* to Mephibosheth is yours." And Ziba said, "I humbly implore you that I may find grace in your sight, my lord, O king."
* `1Ki 4:10` The son of Hesed, in Aruboth—to him *_pertained_* Sochoh and all the land of Hepher;
* `1Ki 4:12` Baana the son of Ahilud—to him *_pertained_* Taanach, Megiddo, and all Beth-shean, which is by Zartanah beneath Jezreel, from Beth-shean to Abel-meholah, even to the place that is beyond Jokneam;
* `1Ki 4:13` The son of Geber, in Ramoth-gilead—to him *_pertained_* the towns of Jair the son of Manasseh, which are in Gilead, and also to him *_pertained_* the region of Argob, which is in Bashan, sixty great cities with walls and brazen bars;
* `1Ki 7:48` And Solomon made all the vessels that *_pertained_* to the house of the LORD: the altar of gold; the table of gold, upon which was the show-bread;
* `2Ki 24:7` And the king of Egypt did not come out of his land again, for the king of Babylon had taken all that *_pertained_* to the king of Egypt from the river of Egypt to the Euphrates River.
* `1Ch 9:27` And they lodged around the house of God because the charge was upon them and its opening every morning *_pertained_* to them.
* `1Ch 11:31` Ithai the son of Ribai of Gibeah who *_pertained_* to the children of Benjamin, Benaiah the Pirathonite,
* `2Ch 12:4` And he took the fortified cities which *_pertained_* to Judah and came to Jerusalem.
* `2Ch 34:33` And Josiah took away all the abominations out of all the countries that *_pertained_* to the children of Israel and made all who were present in Israel to serve, even to serve the LORD their God. And all his days they did not depart from following the LORD, the God of their fathers.

_16 verses containing PERTAINED_

== PERTAINING

* `Jsh 13:31` And half of Gilead, Ashtaroth, and Edrei, cities of the kingdom of Og in Bashan, were *_pertaining_* to the children of Machir the son of Manasseh, even to the one half of the children of Machir by their families.
* `1Ch 26:32` And his brothers, men of valor, were two thousand and seven hundred chief fathers, whom king David made rulers over the Reubenites, the Gadites, and the half-tribe of Manasseh, for every matter *_pertaining_* to God and affairs of the king.
* `Act 1:3` To whom also he showed himself alive after his passion by many infallible proofs, being seen by them forty days and speaking about the things *_pertaining_* to the kingdom of God,
* `Rom 4:1` What shall we then say that Abraham our father, as *_pertaining_* to the flesh, has found?
* `1Co 6:4` If then you have judgments of things *_pertaining_* to this life, set them to judge who are least esteemed in the church.
* `Heb 2:17` Therefore, in all things it behooved him to be made like his brothers so that he might be a merciful and faithful High Priest in things *_pertaining_* to God to make reconciliation for the sins of the people.
* `Heb 5:1` For every high priest taken from among men is ordained for men in things *_pertaining_* to God so that he may offer both gifts and sacrifices for sins.
* `Heb 9:9` This was a figure for the time then present, in which were offered both gifts and sacrifices that could not make him who did the service perfect, as *_pertaining_* to the conscience,

_8 verses containing PERTAINING_

== PERTAINS

* `Lev 14:32` This is the law of him in whom is the plague of leprosy, whose hand is not able to afford that which *_pertains_* to his cleansing."
* `Num 8:24` "This is that which *_pertains_* to the Levites: from twenty-five years old and upward they shall go in to wait upon the service of the Tabernacle of the Congregation,
* `Deu 22:5` "A woman shall not wear that which *_pertains_* to a man, neither shall a man put on a woman's garment, for all who do so are an abomination to the LORD your God.
* `1Sa 27:6` Then Achish gave him Ziklag that day. Therefore, Ziklag *_pertains_* to the kings of Judah to this day.
* `2Sa 6:12` And it was told to king David, saying, "The LORD has blessed the house of Obed-edom and all that *_pertains_* to him because of the ark of God." So David went and brought up the ark of God from the house of Obed-edom into the city of David with gladness.
* `Dan 10:14` Now I have come to make you understand what shall befall your people in the latter days, for the vision *_pertains_* to those days."
* `Heb 7:13` For he of whom these things are spoken *_pertains_* to another tribe, of which no man gave attendance at the altar.

_7 verses containing PERTAINS_

== PERUDA

* `Ezr 2:55` The children of Solomon's servants: the children of Sotai, the children of Sophereth, the children of *_Peruda_*,

_1 verse containing PERUDA_

== PERVERSE

* `Num 22:32` And the angel of the LORD said to him, "Why have you smitten your donkey these three times? Behold, I went out to withstand you because your way is *_perverse_* before me.
* `Deu 32:5` They have corrupted themselves. Their spot is not the spot of his children. They are a *_perverse_* and crooked generation.
* `Deu 32:20` And he said, 'I will hide my face from them. I will see what their end will be, for they are a very *_perverse_* generation, children in whom there is no faith.
* `1Sa 20:30` Then Saul's anger was kindled against Jonathan and he said to him, "You son of the *_perverse_* rebellious woman, do I not know that you have chosen the son of Jesse to your own shame and to the shame of your mother's nakedness?
* `2Sa 22:27` With the pure you will show yourself pure, and with the *_perverse_* you will contend.
* `Job 6:30` Is there iniquity in my tongue? Can my taste not discern *_perverse_* things?"
* `Job 9:20` If I justify myself, my own mouth will condemn me. If I say, 'I am perfect,' that also will prove me *_perverse_*.
* `Psa 18:26` With the pure you will show yourself pure. With the *_perverse_* you will contend.
* `Psa 101:4` A *_perverse_* heart shall depart from me. I will not know a wicked person.
* `Pro 2:12` To deliver you from the way of the evil men, from the men who speak *_perverse_* things,
* `Pro 2:15` Whose ways are crooked, and who are *_perverse_* in their paths;
* `Pro 3:32` For the *_perverse_* is an abomination to the LORD, but his secret is with the righteous.
* `Pro 4:24` Put away from you a crooked mouth, and *_perverse_* lips put far from you.
* `Pro 8:8` All the words of my mouth are in righteousness. There is nothing crooked or *_perverse_* in them.
* `Pro 8:13` The fear of the LORD is to hate evil. Pride, arrogance, the evil way, and the *_perverse_* mouth, I hate.
* `Pro 10:31` The mouth of the just brings forth wisdom, but the *_perverse_* tongue shall be cut out.
* `Pro 11:20` Those who are of a *_perverse_* heart are abominations to the LORD, but those who are upright in their way are his delight.
* `Pro 12:8` A man shall be commended according to his wisdom, but he who is of a *_perverse_* heart shall be despised.
* `Pro 14:2` He who walks in his uprightness fears the LORD, but he who is *_perverse_* in his ways despises him.
* `Pro 16:28` A *_perverse_* man sows strife, and a whisperer separates chief friends.
* `Pro 16:30` He shuts his eyes to devise *_perverse_* things. Moving his lips he brings evil to pass.
* `Pro 17:20` He who has a *_perverse_* heart finds no good, and he who has a deceitful tongue falls into mischief.
* `Pro 19:1` Better is the poor who walks in his integrity, than he who is *_perverse_* in his lips and is a fool.
* `Pro 22:5` Thorns and snares are in the way of the *_perverse_*. He who keeps his soul shall be far from them.
* `Pro 23:33` Your eyes shall behold strange women, and your heart shall utter *_perverse_* things.
* `Pro 28:6` Better is the poor who walks in his uprightness than the rich who is *_perverse_* in his ways.
* `Pro 28:18` He who walks uprightly shall be saved, but he who is *_perverse_* in his ways shall fall at once.
* `Isa 19:14` The LORD has mingled a *_perverse_* spirit in the midst of it. And they have caused Egypt to err in every work of it, as a drunken man staggers in his vomit.
* `Mth 17:17` Then Jesus answered and said, "O faithless and *_perverse_* generation, how long shall I be with you? How long shall I bear with you? Bring him here to me."
* `Luk 9:41` And Jesus, answering, said, "O faithless and *_perverse_* generation, how long shall I be with you and bear with you? Bring your son here."
* `Act 2:40` And with many other words he testified and exhorted, saying, "Save yourselves from this *_perverse_* generation."
* `Act 20:30` Also from your own selves men will arise, speaking *_perverse_* things to draw away disciples after them.
* `Phl 2:15` So that you may be blameless and innocent, the sons of God without rebuke, in the midst of a crooked and *_perverse_* nation, among whom you shine as lights in the world,
* `1Ti 6:5` *_Perverse_* disputings of men of corrupt minds and destitute of the truth, supposing gain to be godliness. Withdraw yourself from such.

_34 verses containing PERVERSE_

== PERVERSELY

* `2Sa 19:19` And said to the king, "Do not let my lord impute iniquity to me, neither remember that which your servant did *_perversely_* the day that my lord the king went out of Jerusalem, that the king should take it to his heart.
* `1Ki 8:47` Yet if they repent themselves in the land where they were carried captives and repent and make supplication to you in the land of those who carried them captives, saying, 'We have sinned and have done *_perversely_*, we have committed wickedness,'
* `Psa 119:78` Let the proud be ashamed, for they dealt *_perversely_* with me without a cause. But I will meditate in your precepts.

_3 verses containing PERVERSELY_

== PERVERSENESS

* `Num 23:21` He has not beheld iniquity in Jacob, neither has he seen *_perverseness_* in Israel. The LORD his God is with him, and the shout of a king is among them.
* `Pro 2:14` Who rejoice to do evil and delight in the *_perverseness_* of the wicked,
* `Pro 6:14` *_Perverseness_* is in his heart. He devises mischief continually. He sows discord.
* `Pro 10:32` The lips of the righteous know what is acceptable, but the mouth of the wicked speaks *_perverseness_*.
* `Pro 11:3` The integrity of the upright shall guide them, but the *_perverseness_* of transgressors shall destroy them.
* `Pro 15:4` A wholesome tongue is a tree of life, but *_perverseness_* in it is a breach in the spirit.
* `Isa 30:12` Therefore, thus says the Holy One of Israel: "Because you despise this word and trust in oppression and *_perverseness_* and lean upon it,
* `Isa 59:3` For your hands are defiled with blood and your fingers with iniquity. Your lips have spoken lies, your tongue has uttered *_perverseness_*.
* `Ezk 9:9` Then he said to me, "The iniquity of the house of Israel and Judah is exceedingly great. The land is full of blood and the city is full of *_perverseness_*. For they say, 'The LORD has forsaken the earth, and the LORD does not see.'

_9 verses containing PERVERSENESS_

== PERVERSION

* `Lev 18:23` You shall not lie with any beast to defile yourself therewith, neither shall any woman stand before a beast to lie down thereto. It is a *_perversion_*.
* `Lev 20:12` And if a man lies with his daughter-in-law, both of them shall surely be put to death. They have committed a *_perversion_*. Their blood shall be upon them.
* `Ecc 5:8` If you see the oppression of the poor and violent *_perversion_* of judgment and justice in a province, do not wonder at the matter. For he who is higher than the highest regards, and there are higher than those.

_3 verses containing PERVERSION_

== PERVERT

* `Deu 24:17` "You shall not *_pervert_* the judgment of the stranger nor of the fatherless, nor take a widow's clothing for a pledge.
* `Job 8:3` Does God *_pervert_* judgment? Or does the Almighty *_pervert_* justice?
* `Job 34:12` Surely God will not do wickedly, neither will the Almighty *_pervert_* judgment.
* `Pro 17:23` A wicked man takes a gift out of the bosom to *_pervert_* the ways of judgment.
* `Pro 31:5` Lest they drink, forget the law, and *_pervert_* the judgment of any of the afflicted.
* `Mic 3:9` Hear this, I pray you, you heads of the house of Jacob and princes of the house of Israel, who abhor judgment and *_pervert_* all equity.
* `Act 13:10` And said, "O full of all subtlety and all mischief, you child of the devil, you enemy of all righteousness, will you not cease to *_pervert_* the right ways of the Lord?
* `Gal 1:7` Which is not another. But there are some who trouble you and would *_pervert_* the gospel of Christ.

_8 verses containing PERVERT_

== PERVERTED

* `1Sa 8:3` And his sons did not walk in his ways, but turned aside after lucre, took bribes, and *_perverted_* judgment.
* `Job 33:27` He looks upon [his fellow] man and says, 'I have sinned and *_perverted_* that which was right, and it did not profit me.
* `Isa 47:10` For you have trusted in your wickedness. You have said, 'No one sees me.' Your wisdom and your knowledge, it has *_perverted_* you. And you have said in your heart, 'I am, and no one else besides me.'
* `Jer 3:21` A voice was heard upon the high places, weeping and supplications of the children of Israel, for they have *_perverted_* their way and have forgotten the LORD their God.
* `Jer 23:36` And you shall no longer mention the burden of the LORD. For every man's word shall be his burden, for you have *_perverted_* the words of the living God, the LORD of hosts, our God.
* `Hab 1:4` Therefore, the law is slackened, and judgment never goes forth. For the wicked encompasses the righteous; therefore, *_perverted_* justice proceeds.
* `Tit 3:11` Knowing that he who is such is *_perverted_* and sins, being self-condemned.

_7 verses containing PERVERTED_

== PERVERTING

* `Luk 23:2` And they began to accuse him, saying, "We found this man *_perverting_* the nation and forbidding to give tribute to Caesar, saying, that he himself is Christ a king."

_1 verse containing PERVERTING_

== PERVERTS

* `Exo 23:8` "And you shall take no gift, for the gift blinds the wise and *_perverts_* the words of the righteous.
* `Deu 16:19` You shall not wrest judgment. You shall not respect persons, neither take a gift, for a gift blinds the eyes of the wise and *_perverts_* the words of the righteous.
* `Deu 27:19` 'Cursed is he who *_perverts_* the judgment of the stranger, fatherless, and widow.' And all the people shall say, 'Amen.'
* `Pro 10:9` He who walks uprightly walks surely, but he who *_perverts_* his ways shall be known.
* `Pro 19:3` The foolishness of man *_perverts_* his way, and his heart frets against the LORD.
* `Luk 23:14` Said to them, "You have brought this man to me as one who *_perverts_* the people, and behold, having examined him before you, I have found no fault in this man, touching those things of which you accuse him,

_6 verses containing PERVERTS_

== PESTILENCE

* `Exo 5:3` And they said, "The God of the Hebrews has met with us. Let us go, we pray you, three days' journey into the desert and sacrifice to the LORD our God, lest he fall upon us with *_pestilence_* or with the sword."
* `Exo 9:3` Behold, the hand of the LORD is upon your livestock which are in the field, and also upon the horses, upon the donkeys, upon the camels, upon the oxen, and upon the sheep, and there shall be a very grievous *_pestilence_*.
* `Exo 9:15` For now I will stretch out my hand so that I may smite you and your people with *_pestilence_*, and you shall be cut off from the earth.
* `Lev 26:25` And I will bring a sword upon you that shall avenge the quarrel of my covenant. And when you are gathered within your cities, I will send the *_pestilence_* among you, and you shall be delivered into the hand of the enemy.
* `Num 14:12` I will smite them with the *_pestilence_* and disinherit them, and I will make of you a greater and mightier nation than they are."
* `Deu 28:21` The LORD shall make the *_pestilence_* cleave to you until he has consumed you from off the land where you go to possess it.
* `2Sa 24:13` So Gad came to David and told him. And he said to him, "Shall seven years of famine come upon you in your land? Or will you flee three months before your enemies while they pursue you? Or shall there be three days' *_pestilence_* in your land? Now consider, and see what answer I shall return to him who sent me."
* `2Sa 24:15` So the LORD sent a *_pestilence_* upon Israel from the morning even to the time appointed, and seventy thousand men of the people from Dan even to Beer-sheba died.
* `1Ki 8:37` "If there is famine in the land, if there is *_pestilence_*, blight, mildew, swarming-locust, or if there is ravaging-locust, if their enemy besieges them in the land of their cities, whatever plague, whatever sickness there is,
* `1Ch 21:12` Either three years of famine, or three months to be destroyed before your foes while the sword of your enemies overtakes you, or else three days of the sword of the LORD, even the *_pestilence_* in the land and the angel of the LORD destroying throughout all the borders of Israel.' Now therefore, advise yourself what word I shall bring back to him who sent me."
* `1Ch 21:14` So the LORD sent *_pestilence_* upon Israel, and there fell of Israel seventy thousand men.
* `2Ch 6:28` "If there is famine in the land, if there is *_pestilence_*, if there is blight, mildew, swarming-locusts, or ravaging-locusts, if their enemies besiege them in the cities of their land, whatever calamity or whatever sickness there is,
* `2Ch 7:13` If I shut up heaven so that there is no rain, if I command the locusts to devour the land, or if I send *_pestilence_* among my people,
* `2Ch 20:9` 'If, when evil comes upon us, as the sword, judgment, *_pestilence_*, or famine, we stand before this house and in your presence (for your name is in this house) and cry to you in our affliction, then you will hear and help.'
* `Psa 78:50` He made a way to his anger. He did not spare their soul from death, but gave their life over to the *_pestilence_*,
* `Psa 91:3` Surely he shall deliver you from the snare of the fowler and from the noisome *_pestilence_*.
* `Psa 91:6` Nor of the *_pestilence_* that walks in darkness, nor of the destruction that wastes at noon-day.
* `Jer 14:12` When they fast, I will not hear their cry. And when they offer a burnt-offering and an oblation, I will not accept them. But I will consume them by the sword, by the famine, and by the *_pestilence_*."
* `Jer 21:6` And I will smite the inhabitants of this city, both man and beast. They shall die by a great *_pestilence_*.
* `Jer 21:7` And afterward," says the LORD, "I will deliver Zedekiah king of Judah, his servants, and the people who are left in this city from the *_pestilence_*, from the sword, and from the famine, into the hand of Nebuchadnezzar king of Babylon, and into the hand of their enemies and into the hand of those who seek their life. And he shall smite them with the edge of the sword. He shall not spare them, neither have pity, nor have mercy."'
* `Jer 21:9` He who abides in this city shall die by the sword, by the famine, and by the *_pestilence_*, but he who goes out and falls to the Chaldeans who besiege you, he shall live, and his life shall be to him for plunder.
* `Jer 24:10` And I will send the sword, the famine, and the *_pestilence_* among them until they are consumed from off the land that I gave to them and to their fathers.'"
* `Jer 27:8` 'And it shall come to pass, that the nation and kingdom which will not serve the same Nebuchadnezzar king of Babylon, and which will not put their neck under the yoke of the king of Babylon, that nation I will punish,' says the LORD, 'with the sword, with the famine, and with the *_pestilence_* until I have consumed them by his hand.
* `Jer 27:13` Why will you die—you and your people—by the sword, by the famine, and by the *_pestilence_*, as the LORD has spoken against the nation that will not serve the king of Babylon?
* `Jer 28:8` The prophets who have been before me and before you of old prophesied both against many countries and against great kingdoms concerning war, evil, and *_pestilence_*.
* `Jer 29:17` Thus says the LORD of hosts: 'Behold, I will send upon them the sword, the famine, and the *_pestilence_* and will make them like vile figs that cannot be eaten they are so bad.
* `Jer 29:18` And I will persecute them with the sword, with the famine, and with the *_pestilence_*, and will make them a horror to all the kingdoms of the earth to be a curse, an astonishment, a hissing, and a reproach among all the nations where I have driven them,
* `Jer 32:24` Behold the siege-mounds, they have come to the city to take it, and the city is given into the hand of the Chaldeans who fight against it, because of the sword, the famine, and the *_pestilence_*. And what you have spoken has come to pass, and behold, you see it.
* `Jer 32:36` "And now therefore, thus says the LORD, the God of Israel, concerning this city, of which you say, 'It shall be delivered into the hand of the king of Babylon by the sword, by the famine, and by the *_pestilence_*':
* `Jer 34:17` "Therefore, thus says the LORD: 'You have not listened to me in proclaiming liberty, each to his brother and each to his neighbor. Behold, I proclaim a liberty for you,' says the LORD, 'to the sword, to the *_pestilence_*, and to the famine, and I will make you a horror to all the kingdoms of the earth.
* `Jer 38:2` "Thus says the LORD: 'He who remains in this city shall die by the sword, by the famine, and by the *_pestilence_*, but he who goes forth to the Chaldeans shall live, for he shall have his life for plunder and shall live.'
* `Jer 42:17` Thus it shall be with all the men who set their faces to go into Egypt to sojourn there. They shall die by the sword, by the famine, and by the *_pestilence_*. And none of them shall remain or escape from the evil that I will bring upon them."'
* `Jer 42:22` Now therefore, know certainly that you shall die by the sword, by the famine, and by the *_pestilence_* in the place where you desire to go and to sojourn."
* `Jer 44:13` For I will punish those who dwell in the land of Egypt, as I have punished Jerusalem, by the sword, by the famine, and by the *_pestilence_*,
* `Ezk 5:12` A third part of you shall die with the *_pestilence_*, and with famine they shall be consumed in the midst of you. And a third part shall fall by the sword around you. And I will scatter a third part into all the winds and draw out a sword after them.
* `Ezk 5:17` Thus I will send upon you famine and evil beasts, and they shall bereave you. *_Pestilence_* and blood shall pass through you, and I will bring the sword upon you. I, the LORD, have spoken it.'"
* `Ezk 6:11` "Thus says the Lord GOD: 'Smite with your hand, stamp with your foot, and say, "Alas," because of all the evil abominations of the house of Israel. For they shall fall by the sword, by the famine, and by the *_pestilence_*.
* `Ezk 6:12` He who is far off shall die by the *_pestilence_*. And he who is near shall fall by the sword. And he who remains and is besieged shall die by the famine. Thus I will accomplish my fury upon them.
* `Ezk 7:15` The sword is outside, and the *_pestilence_* and the famine inside. He who is in the field shall die with the sword, and he who is in the city, famine and *_pestilence_* shall devour him.
* `Ezk 12:16` But I will leave a few men of them from the sword, from the famine, and from the *_pestilence_* so that they may declare all their abominations among the heathen where they come. And they shall know that I am the LORD."
* `Ezk 14:19` Or if I send a *_pestilence_* into that land and pour out my fury upon it in blood to cut off man and beast from it,
* `Ezk 14:21` For thus says the Lord GOD: "How much more when I send my four severe judgments upon Jerusalem, the sword, the famine, the noisome beast, and the *_pestilence_*, to cut off man and beast from it!
* `Ezk 28:23` For I will send into her *_pestilence_*, and blood into her streets, and the wounded shall be judged in the midst of her by the sword upon her on every side. And they shall know that I am the LORD.
* `Ezk 33:27` Say thus to them: 'Thus says the Lord GOD: "As I live, surely those who are in the wastes shall fall by the sword, and him who is in the open field I will give to the beasts to be devoured, and those who are in the forts and in the caves shall die by the *_pestilence_*.
* `Ezk 38:22` And I will plead against him with *_pestilence_* and with blood, and I will rain upon him, upon his bands, and upon the many people who are with him, an overflowing rain, with great hailstones, fire, and brimstone.
* `Amo 4:10` "I have sent among you the *_pestilence_* after the manner of Egypt. I have slain your young men with the sword and have taken away your horses. I have made the ill savor of your camps to come up to your nostrils. Yet you have not returned to me," says the LORD.
* `Hab 3:5` Before him went the *_pestilence_*, and burning coals went forth at his feet.

_47 verses containing PESTILENCE_

== PESTILENCES

* `Mth 24:7` For nation will rise against nation and kingdom against kingdom. And there will be famines, *_pestilences_*, and earthquakes in diverse places.
* `Luk 21:11` Great earthquakes, famines, and *_pestilences_* will be in various places. And there will be fearful sights and great signs from heaven.

_2 verses containing PESTILENCES_

== PESTILENT

* `Act 24:5` For we have found this a *_pestilent_* man, and a mover of sedition among all the Jews throughout the world, and a ring-leader of the sect of the Nazarenes,

_1 verse containing PESTILENT_

== PESTLE

* `Pro 27:22` Though you should bray a fool in a mortar among wheat with a *_pestle_*, yet his foolishness will not depart from him.

_1 verse containing PESTLE_

