= QUADRANS - QUIVERED
:toc:

== QOF

* `Psa 25:19` [*_QOF_*] Consider my enemies, for they are many, and they hate me with cruel hatred.
* `Psa 119:145` [*_QOF_*] I cried with my whole heart. Hear me, O LORD. I will keep your statutes.
* `Pro 31:28` [*_QOF_*] Her children rise up and call her blessed, her husband also, and he praises her:
* `Lam 1:19` [*_QOF_*] I called for my lovers, but they deceived me. My priests and my elders resigned their breath in the city while they sought their food to relieve their souls.
* `Lam 2:19` [*_QOF_*] Arise, cry out in the night. In the beginning of the watches pour out your heart like water before the face of the Lord. Lift up your hands toward him for the life of your young children, who faint for hunger at the head of every street."
* `Lam 3:55` [*_QOF_*] I called upon your name, O LORD, out of the low dungeon.
* `Lam 4:19` [*_QOF_*] Our persecutors are swifter than the eagles of heaven. They pursued us upon the mountains. They laid wait for us in the wilderness.

_7 verses containing QOF_

== QUADRANS

* `Mth 5:26` Truly, I say to you, you shall by no means come out from there until you have paid the uttermost *_quadrans_*.
* `Mrk 12:42` And there came a certain poor widow, and she threw in two mites, which make a *_quadrans_*.

_2 verses containing QUADRANS_

== QUAILS

* `Exo 16:13` And it came to pass, that at evening the *_quails_* came up and covered the camp, and in the morning the dew lay around the host.
* `Num 11:31` And a wind went forth from the LORD, brought *_quails_* from the sea, and let them fall by the camp, about a day's journey on this side and about a day's journey on the other side around the camp, and about two cubits high upon the face of the earth.
* `Num 11:32` And the people stood up all that day, all that night, and all the next day, and they gathered the *_quails_*. He who gathered least gathered ten homers. And they spread them all abroad for themselves around the camp.
* `Psa 105:40` The people asked, and he brought *_quails_* and satisfied them with the bread of heaven.

_4 verses containing QUAILS_

== QUAKE

* `Joe 2:10` The earth shall *_quake_* before them. The heavens shall tremble. The sun and the moon shall be dark, and the stars shall withdraw their shining.
* `Nah 1:5` The mountains *_quake_* at him and the hills melt. The earth is upheaved at his presence, even the world and all who dwell therein.

_2 verses containing QUAKE_

== QUAKED

* `1Sa 14:15` And there was a trembling in the host, in the field, and among all the people. The garrison and the raiders also trembled, and the earth *_quaked_*, and it was a very great trembling.

_1 verse containing QUAKED_

== QUAKING

* `Ezk 12:18` "Son of man, eat your bread with *_quaking_* and drink your water with trembling and with solicitude.
* `Dan 10:7` And I, Daniel, alone saw the vision. The men who were with me did not see the vision, but a great *_quaking_* fell upon them, so that they fled to hide themselves.

_2 verses containing QUAKING_

== QUANTITY

* `Lev 19:35` 'You shall do no unrighteousness in judgment, in measures of length, of weight, or of *_quantity_*.
* `1Ki 10:10` And she gave the king one hundred and twenty talents of gold, a very great *_quantity_* of spices, and precious stones. Never again did there come such abundance of spices as these which the queen of Sheba gave to king Solomon.
* `1Ki 10:11` And also the navy of Hiram, which brought gold from Ophir, brought in from Ophir a large *_quantity_* of almug trees and precious stones.
* `1Ch 20:2` And David took the crown of their king from his head and found it to weigh a talent of gold, and there were precious stones in it. And it was set upon David's head. And he also brought a great *_quantity_* of plunder out of the city.
* `Isa 22:24` And they shall hang upon him all the glory of his father's house: the offspring and the descendants, all vessels of small *_quantity_*, from the vessels of cups, even to all the vessels of flagons.

_5 verses containing QUANTITY_

== QUARREL

* `Lev 26:25` And I will bring a sword upon you that shall avenge the *_quarrel_* of my covenant. And when you are gathered within your cities, I will send the pestilence among you, and you shall be delivered into the hand of the enemy.
* `2Ki 5:7` And it came to pass when the king of Israel had read the letter, that he rent his clothes and said, "Am I God, to kill and to make alive, that this man sends to me to recover a man of his leprosy? Therefore, consider, I pray you, and see how he seeks a *_quarrel_* against me."
* `Mrk 6:19` Therefore, Herodias had a *_quarrel_* against him and would have killed him, but she could not,
* `Col 3:13` Forbearing one another, and forgiving one another, if any man has a *_quarrel_* against any. Just as Christ forgave you, so also should you.

_4 verses containing QUARREL_

== QUARRELSOME

* `1Ti 3:3` Not given to wine, not *_quarrelsome_*, not greedy of filthy lucre, but patient, not a brawler, not covetous,
* `Tit 1:7` For an overseer must be blameless as the steward of God, not self-willed, not soon angry, not given to wine, not *_quarrelsome_*, not given to filthy lucre,

_2 verses containing QUARRELSOME_

== QUARRIES

* `Jdg 3:19` But he himself turned back from the *_quarries_* that were by Gilgal and said, "I have a secret errand for you, O king." He said, "Keep silence." And all who stood by him went out from him.
* `Jdg 3:26` And Ehud escaped while they waited and passed beyond the *_quarries_* and escaped to Seirath.

_2 verses containing QUARRIES_

== QUARTER

* `Gen 19:4` But before they lay down, the men of the city, even the men of Sodom, surrounded the house, both old and young, all the people from every *_quarter_*.
* `Num 34:3` Your south *_quarter_* shall be from the wilderness of Zin along by the border of Edom, and your south border shall be from the end of the Salt Sea eastward.
* `Jsh 15:5` And the east border was the Salt Sea, even to the end of the Jordan. And their border in the north *_quarter_* was from the bay of the sea, at the uttermost part of the Jordan.
* `Jsh 18:14` And the border was drawn from there and compassed the corner of the sea southward from the hill that lies before Beth-horon southward. And its limits were at Kirjath-baal (which is Kirjath-jearim), a city of the children of Judah. This was the west *_quarter_*.
* `Jsh 18:15` And the south *_quarter_* was from the end of Kirjath-jearim, and the border went out on the west, and went out to the well of waters of Nephtoah.
* `2Ki 22:14` So Hilkiah the priest, Ahikam, Achbor, Shaphan, and Asahiah went to Huldah the prophetess, the wife of Shallum, the son of Tikvah, the son of Harhas, keeper of the wardrobe (now she dwelt in Jerusalem in the second *_quarter_*), and they spoke with her.
* `2Ch 34:22` And Hilkiah and those whom the king had appointed went to Huldah the prophetess, the wife of Shallum the son of Tikvath, the son of Hasrah, keeper of the wardrobe (now she dwelt in Jerusalem in the second *_quarter_*), and they spoke to her to that effect.
* `Isa 47:15` Thus they shall be to you with whom you have labored, even your merchants, from your youth. They shall each wander to his *_quarter_*. No one shall save you."
* `Isa 56:11` Indeed, they are greedy dogs which can never have enough, and they are shepherds who cannot understand. They all look to their own way, each for his gain, from his *_quarter_*.
* `Zph 1:10` And it shall come to pass in that day," says the LORD, "that there shall be the noise of a cry from the fish-gate, a howling from the second *_quarter_*, and a great crashing from the hills.
* `Mrk 1:45` But he went out and began to publish it much and to blaze abroad the matter; therefore, Jesus could no longer openly enter into the city, but was outside in desolate places. And they came to him from every *_quarter_*.

_11 verses containing QUARTER_

== QUARTERS

* `Exo 13:7` Unleavened bread shall be eaten seven days. And there shall no leavened bread be seen with you, neither shall there be leaven seen with you in all your *_quarters_*.
* `Deu 22:12` "You shall make yourself fringes upon the four *_quarters_* of your vesture with which you cover yourself.
* `1Ch 9:24` In four *_quarters_* were the gatekeepers, toward the east, west, north, and south.
* `Jer 49:36` And upon Elam I will bring the four winds from the four *_quarters_* of heaven and will scatter them toward all those winds. And there shall be no nation where the outcasts of Elam shall not come.
* `Ezk 38:6` Gomer and all his bands, the house of Togarmah of the north *_quarters_* and all his bands, and many people with you.
* `Act 9:32` And it came to pass, as Peter passed throughout all *_quarters_*, he also came down to the saints who dwelt at Lydda.
* `Act 16:3` Paul wished to have him go forth with him and took and circumcised him because of the Jews who were in those *_quarters_*, for they all knew that his father was a Greek.
* `Rev 20:8` And shall go out to deceive the nations which are in the four *_quarters_* of the earth, Gog and Magog, to gather them to battle—the number of whom is as the sand of the sea.

_8 verses containing QUARTERS_

== QUARTUS

* `Rom 16:23` Gaius, my host and also of the whole church, salutes you. Erastus the chamberlain of the city salutes you, and also *_Quartus_*, a brother.

_1 verse containing QUARTUS_

== QUATERNIONS

* `Act 12:4` And when he had apprehended him, he put him in prison and delivered him to four *_quaternions_* of soldiers to keep him, intending after the passover to bring him forth to the people.

_1 verse containing QUATERNIONS_

== QUEEN

* `1Ki 10:1` And when the *_queen_* of Sheba heard of the fame of Solomon concerning the name of the LORD, she came to prove him with hard questions.
* `1Ki 10:4` And when the *_queen_* of Sheba had seen all Solomon's wisdom, the house that he had built,
* `1Ki 10:10` And she gave the king one hundred and twenty talents of gold, a very great quantity of spices, and precious stones. Never again did there come such abundance of spices as these which the *_queen_* of Sheba gave to king Solomon.
* `1Ki 10:13` And king Solomon gave to the *_queen_* of Sheba all her desire, whatever she asked, besides that which Solomon gave her out of his royal bounty. So she turned and went to her own country—she and her servants.
* `1Ki 11:19` And Hadad found great favor in the sight of Pharaoh so that he gave him for a wife the sister of his own wife, the sister of Tahpenes the *_queen_*.
* `1Ki 15:13` And also Maachah his mother, he even removed her from being *_queen_* because she had made an idol in a grove. And Asa destroyed her idol and burnt it by the brook Kidron.
* `2Ki 10:13` Jehu met with the brothers of Ahaziah king of Judah and said, "Who are you?" And they answered, "We are the brothers of Ahaziah, and we go down to salute the children of the king and the children of the *_queen_*."
* `2Ch 9:1` And when the *_queen_* of Sheba heard of the fame of Solomon, she came to prove Solomon with hard questions at Jerusalem, with a very great company and camels that bore spices, gold in abundance, and precious stones. And when she had come to Solomon, she spoke with him about all that was in her heart.
* `2Ch 9:3` And when the *_queen_* of Sheba had seen the wisdom of Solomon, the house that he had built,
* `2Ch 9:9` And she gave the king one hundred and twenty talents of gold, spices of great abundance, and precious stones. Never was there any such spice as the *_queen_* of Sheba gave to king Solomon.
* `2Ch 9:12` And king Solomon gave to the *_queen_* of Sheba all her desire, whatever she asked, besides that which she had brought to the king. So she turned and went away to her own land—she and her servants.
* `2Ch 15:16` And also concerning Maachah the mother of Asa the king, he removed her from being *_queen_* because she had made an idol in a grove. And Asa cut down her idol, stamped it, and burnt it at the brook Kidron.
* `Neh 2:6` And the king said to me (the *_queen_* also sitting by him), "For how long shall your journey be? And when will you return?" So it pleased the king to send me, and I set him a time.
* `Est 1:9` Also, Vashti the *_queen_* made a feast for the women in the royal house which belonged to king Ahasuerus.
* `Est 1:11` To bring Vashti the *_queen_* before the king with the royal crown to show the people and the princes her beauty, for she was fair to look upon.
* `Est 1:12` But the *_queen_* Vashti refused to come at the king's commandment by his chamberlains. Therefore, the king was very angry and his anger burned in him.
* `Est 1:15` "What shall we do to the *_queen_* Vashti according to law because she has not performed the commandment of king Ahasuerus by the chamberlains?"
* `Est 1:16` And Memucan answered before the king and the princes, "Vashti the *_queen_* has not done wrong to the king only, but also to all the princes and to all the people who are in all the provinces of king Ahasuerus.
* `Est 1:17` For this deed of the *_queen_* will come abroad to all women to make their husbands contemptible in their eyes when they say, 'King Ahasuerus commanded Vashti the *_queen_* to be brought in before him, but she did not come.'
* `Est 1:18` This day, the ladies of Persia and Media who have heard of the deed of the *_queen_* will say the same thing to all the king's princes. Thus there will arise too much contempt and wrath.
* `Est 2:4` And let the young woman who pleases the king be *_queen_* instead of Vashti." And the thing pleased the king, and he did so.
* `Est 2:17` And the king loved Esther above all the women, and she obtained grace and favor in his sight more than all the virgins. So he set the royal crown upon her head and made her *_queen_* instead of Vashti.
* `Est 2:22` And the thing was known to Mordecai, who told it to Esther the *_queen_*. And Esther told the king about it in Mordecai's name.
* `Est 4:4` So Esther's attendants and her chamberlains came and told it to her. Then the *_queen_* was exceedingly grieved, and she sent clothing to clothe Mordecai and to take away his sackcloth from him, but he did not receive it.
* `Est 5:2` And it was so, when the king saw Esther the *_queen_* standing in the court, that she obtained favor in his sight, and the king held out to Esther the golden scepter that was in his hand. So Esther drew near and touched the top of the scepter.
* `Est 5:3` Then the king said to her, "What do you wish, *_queen_* Esther? And what is your request? It shall be given to you even to the half of the kingdom."
* `Est 5:12` Haman said moreover, "Even Esther the *_queen_* let no man come in with the king to the banquet that she had prepared but myself. And tomorrow I am invited by her together with the king.
* `Est 7:1` So the king and Haman came to banquet with Esther the *_queen_*.
* `Est 7:2` And the king said again to Esther on the second day at the banquet of wine, "What is your petition, *_queen_* Esther? It shall be granted to you. And what is your request? It shall be performed, even to the half of the kingdom."
* `Est 7:3` Then Esther the *_queen_* answered and said, "If I have found favor in your sight, O king, and if it pleases the king, let my life be given to me at my petition and my people at my request,
* `Est 7:5` Then king Ahasuerus answered and said to Esther the *_queen_*, "Who is he and where is he who dares presume in his heart to do so?"
* `Est 7:6` And Esther said, "The adversary and enemy is this wicked Haman." Then Haman was afraid before the king and the *_queen_*.
* `Est 7:7` And the king arose from the banquet of wine in his wrath and went into the palace-garden. And Haman stood up to make request for his life to Esther the *_queen_*, for he saw that there was evil determined against him by the king.
* `Est 7:8` Then the king returned out of the palace-garden into the place of the banquet of wine, and Haman had fallen upon the couch on which Esther was. Then the king said, "Will he force the *_queen_* also before me in the house?" As the word went out of the king's mouth, they covered Haman's face.
* `Est 8:1` On that day king Ahasuerus gave the house of Haman, the Jews' enemy, to Esther the *_queen_*. And Mordecai came before the king, for Esther had told what he was to her.
* `Est 8:7` Then king Ahasuerus said to Esther the *_queen_* and to Mordecai the Jew, "Behold, I have given Esther the house of Haman, and they have hanged him upon the gallows because he laid his hand upon the Jews.
* `Est 9:12` And the king said to Esther the *_queen_*, "The Jews have slain and destroyed five hundred men in the palace of Shushan and the ten sons of Haman. What have they done in the rest of the king's provinces? Now what is your petition? It shall be granted to you. Or what is your request further? It shall be done."
* `Est 9:29` Then Esther the *_queen_*, the daughter of Abihail, and Mordecai the Jew, wrote with all authority to confirm this second letter of Purim.
* `Est 9:31` To confirm these days of Purim in their times appointed, according as Mordecai the Jew and Esther the *_queen_* had enjoined them, and as they had decreed for themselves and for their descendants the matters of the fastings and their cry.
* `Psa 45:9` Kings' daughters were among your honorable women. Upon your right hand stood the *_queen_* in gold of Ophir.
* `Jer 7:18` The children gather wood, the fathers kindle the fire, and the women knead dough to make cakes for the *_queen_* of heaven. And they pour out drink-offerings to other gods to provoke me to anger.
* `Jer 13:18` Say to the king and to the *_queen_*, "Humble yourselves, sit down, for your principalities shall come down, even the crown of your glory."
* `Jer 29:2` (After Jeconiah the king, the *_queen_*, the eunuchs, the princes of Judah and Jerusalem, the carpenters, and the smiths had departed from Jerusalem)
* `Jer 44:17` But we will certainly do whatever thing proceeds from our own mouth, to burn incense to the *_queen_* of heaven and to pour out drink-offerings to her, as we have done—we, our fathers, our kings, and our princes—in the cities of Judah and in the streets of Jerusalem. For then we had plenty of provisions and were well and saw no evil.
* `Jer 44:18` But since we ceased to burn incense to the *_queen_* of heaven and to pour out drink-offerings to her, we have lacked all things and have been consumed by the sword and by the famine.
* `Jer 44:19` And when we burned incense to the *_queen_* of heaven and poured out drink-offerings to her, did we make for her cakes to worship her and pour out drink-offerings to her without our men?"
* `Jer 44:25` Thus says the LORD of hosts, the God of Israel, saying, 'You and your wives have both spoken with your mouths and fulfilled with your hand, saying, "We will surely perform our vows that we have vowed, to burn incense to the *_queen_* of heaven and to pour out drink-offerings to her." You will surely accomplish your vows and surely perform your vows.'
* `Dan 5:10` Now the *_queen_*, by reason of the words of the king and his lords, came into the banquet house. And the *_queen_* spoke, and said, "O king, live forever. Do not let your thoughts trouble you, nor let your countenance be changed.
* `Mth 12:42` The *_queen_* of the south shall rise up in the judgment with this generation and condemn it because she came from the uttermost parts of the earth to hear the wisdom of Solomon, and behold, one greater than Solomon is here.
* `Luk 11:31` The *_queen_* of the south shall rise up in the judgment with the men of this generation and condemn them. For she came from the utmost parts of the earth to hear the wisdom of Solomon, and behold, someone greater than Solomon is here.
* `Act 8:27` And he arose and went, and behold, there was a man of Ethiopia, a eunuch of great authority under Candace *_queen_* of the Ethiopians who had the charge of all her treasure. He had come to Jerusalem to worship
* `Rev 18:7` However much she has glorified herself and lived deliciously, in such amount give her torment and sorrow, for she says in her heart, '"I sit as a *_queen_*," "I am not a widow, and never shall I see sorrow."'

_52 verses containing QUEEN_

== QUEENS

* `Sos 6:8` There are sixty *_queens_*, eighty concubines, and virgins without number.
* `Sos 6:9` My dove, my undefiled is but one. She is the only one of her mother. She is the choice one of her who bore her. The daughters saw her and blessed her, even the *_queens_* and the concubines, and they praised her.
* `Isa 49:23` And kings shall be your nursing fathers, and their *_queens_* your nursing mothers. They shall bow to you with their face toward the earth and lick up the dust of your feet. And you shall know that I am the LORD, for they shall not be ashamed who wait for me.

_3 verses containing QUEENS_

== QUENCH

* `2Sa 14:7` And behold, the whole family has risen against your servant and they said, 'Deliver him who smote his brother so that we may kill him for the life of his brother whom he slew. And we will destroy the heir also.' And so they will *_quench_* my coal which is left and will not leave to my husband neither name nor remainder upon the earth."
* `Psa 104:11` They give drink to every beast of the field. The wild donkeys *_quench_* their thirst.
* `Sos 8:7` Many waters cannot *_quench_* love, neither can the floods drown it. If a man would give all the substance of his house for love, it would utterly be despised.
* `Isa 1:31` And the strong shall be like tow and its maker like a spark, and they shall both burn together, and no one shall *_quench_* them.
* `Isa 42:3` A bruised reed he shall not break, and the smoking flax he shall not *_quench_*. He shall bring forth judgment to truth.
* `Jer 4:4` Circumcise yourselves to the LORD and take away the foreskins of your heart, men of Judah and inhabitants of Jerusalem, lest my fury come forth like fire and burn so that none can *_quench_* it because of the evil of your doings."
* `Jer 21:12` O house of David. Thus says the LORD: "Execute judgment in the morning and deliver him who is made desolate out of the hand of the oppressor, lest my fury go out like fire and burn so that no one can *_quench_* it because of the evil of your doings.
* `Amo 5:6` Seek the LORD and you shall live, lest he break out like fire in the house of Joseph and devour it and there be no one to *_quench_* it in Beth-el.
* `Mth 12:20` A bruised reed he shall not break and smoking flax he shall not *_quench_* until he sends forth judgment to victory.
* `1Th 5:19` Do not *_quench_* the Spirit.

_10 verses containing QUENCH_

== QUENCHED

* `Num 11:2` And the people cried to Moses. And when Moses prayed to the LORD, the fire was *_quenched_*.
* `2Ki 22:17` Because they have forsaken me and have burned incense to other gods that they might provoke me to anger with all the works of their hands, therefore my wrath shall be kindled against this place and shall not be *_quenched_*.'"
* `2Ch 34:25` Because they have forsaken me and have burned incense to other gods in order to provoke me to anger with all the works of their hands, therefore my wrath shall be poured out upon this place and shall not be *_quenched_*.'"'
* `Psa 118:12` They encompassed me like bees. They are *_quenched_* like the fire of thorns, for in the name of the LORD I will destroy them.
* `Isa 34:10` It shall not be *_quenched_* night or day. Its smoke shall ascend forever. From generation to generation it shall lie waste. None shall pass through it forever and ever.
* `Isa 43:17` Who brings forth the chariot and horse, the army and the power (they shall lie down together, they shall not rise, they are extinct, they are *_quenched_* like tow):
* `Isa 66:24` "And they shall go forth and look upon the carcasses of the men who have transgressed against me. For their worm shall not die, neither shall their fire be *_quenched_*, and they shall be an abhorrence to all flesh."
* `Jer 7:20` Therefore, thus says the Lord GOD: "Behold, my anger and my fury shall be poured out upon this place, upon man and upon beast, and upon the trees of the field and upon the fruit of the ground, and it shall burn and shall not be *_quenched_*."
* `Jer 17:27` But if you will not listen to me to hallow the sabbath day and to bear no burdens while entering at the gates of Jerusalem on the sabbath day, then I will kindle a fire in its gates, and it shall devour the palaces of Jerusalem and shall not be *_quenched_*."'"
* `Ezk 20:47` And say to the forest of the south, 'Hear the word of the LORD. Thus says the Lord GOD: "Behold, I will kindle a fire in you, and it shall devour every green tree and every dry tree in you. The flaming flame shall not be *_quenched_*, and all faces from the south to the north shall be burned therein.
* `Ezk 20:48` And all flesh shall see that I, the LORD, have kindled it. It shall not be *_quenched_*."'"
* `Mrk 9:43` And if your hand causes you to fall into sin, cut it off. It is better for you to enter life maimed than with two hands to go into hell, into the fire that shall never be *_quenched_*,
* `Mrk 9:44` 'Where their worm does not die and the fire is not *_quenched_*.'
* `Mrk 9:45` And if your foot causes you to fall into sin, cut it off. It is better for you to enter lame into life than with two feet to be cast into hell, into the fire that never shall be *_quenched_*,
* `Mrk 9:46` 'Where their worm does not die and the fire is not *_quenched_*.'
* `Mrk 9:48` 'Where their worm does not die and the fire is not *_quenched_*.'
* `Heb 11:34` *_Quenched_* the violence of fire, escaped the edge of the sword, out of weakness were made strong, became valiant in fight, and turned to flight the armies of the foreigners.

_17 verses containing QUENCHED_

== QUESTION

* `Mth 22:35` Then one of them who was a lawyer, asked him a *_question_*, tempting him, and saying,
* `Mrk 8:11` And the Pharisees came forth and began to *_question_* with him, seeking from him a sign from heaven, testing him.
* `Mrk 11:29` And Jesus answered and said to them, "I will also ask of you one *_question_*. Answer me, and I will tell you by what authority I do these things.
* `Mrk 12:34` And when Jesus saw that he answered discreetly, he said to him, "You are not far from the kingdom of God." And no man after that dared to *_question_* him.
* `Luk 20:40` And after that, they dared not ask him any *_question_* at all.
* `Jhn 3:25` Then there arose a *_question_* between some of John's disciples and the Jews about purifying.
* `Act 15:2` Therefore, when Paul and Barnabas had no small dissension and disputation with them, they determined that Paul, Barnabas, and some others of them should go to Jerusalem to the apostles and elders about this *_question_*.
* `Act 18:15` But if it is a *_question_* of words and names and of your law, you look to it, for I will be no judge of such matters."
* `Act 19:40` For we are in danger of being called in *_question_* for this day's uproar, since there is no cause by which we may give an account of this commotion."
* `Act 23:6` But when Paul perceived that one part were Sadducees and the other Pharisees, he cried out in the council, "Men, brothers, I am a Pharisee, the son of a Pharisee. Concerning the hope and resurrection of the dead I am called in *_question_*."
* `Act 24:21` Unless it is for this one voice that I cried standing among them: 'Concerning the resurrection of the dead I am called in *_question_* by you this day.'"
* `1Co 10:25` Whatever is sold in the provision market, eat, asking no *_question_* for conscience' sake.
* `1Co 10:27` If any of those who do not believe invites you to a feast and you are disposed to go, whatever is set before you, eat, asking no *_question_* on account of conscience.

_13 verses containing QUESTION_

== QUESTIONED

* `Jdg 8:14` And caught a young man of the men of Succoth and *_questioned_* him. And he described to him the princes of Succoth and its elders, even seventy-seven men.
* `2Ch 31:9` Then Hezekiah *_questioned_* with the priests and the Levites concerning the heaps.
* `Dan 1:20` And in all matters of wisdom and understanding wherein the king *_questioned_* them, he found them ten times superior to all the magicians and astrologers who were in all his realm.
* `Mrk 1:27` And they were all amazed; therefore, they *_questioned_* among themselves, saying, "What thing is this? What new doctrine is this? For with authority he commands even the unclean spirits, and they obey him."
* `Luk 23:9` Then he *_questioned_* with him in many words, but he answered him nothing.

_5 verses containing QUESTIONED_

== QUESTIONING

* `Mrk 9:10` And they kept that saying with themselves, *_questioning_* with one another what the rising from the dead should mean.
* `Mrk 9:14` And when he came to his disciples, he saw a great multitude around them and the scribes *_questioning_* with them.
* `Mrk 9:16` And he asked the scribes, "What are you *_questioning_* with them?"

_3 verses containing QUESTIONING_

== QUESTIONS

* `1Ki 10:1` And when the queen of Sheba heard of the fame of Solomon concerning the name of the LORD, she came to prove him with hard *_questions_*.
* `1Ki 10:3` And Solomon answered all her *_questions_*. There was not anything hid from the king which he did not tell her.
* `2Ch 9:1` And when the queen of Sheba heard of the fame of Solomon, she came to prove Solomon with hard *_questions_* at Jerusalem, with a very great company and camels that bore spices, gold in abundance, and precious stones. And when she had come to Solomon, she spoke with him about all that was in her heart.
* `2Ch 9:2` And Solomon answered all her *_questions_*, and there was nothing hid from Solomon which he did not tell her.
* `Mth 22:46` And no man was able to answer him a word, neither did any man dare from that day forth to ask him any more *_questions_*.
* `Luk 2:46` And it came to pass, that after three days they found him in the temple sitting in the midst of the teachers, both hearing them and asking them *_questions_*.
* `Act 23:29` Whom I perceived to be accused of *_questions_* of their law, but to have nothing laid to his charge worthy of death, or of bonds.
* `Act 25:19` But had some *_questions_* against him of their own superstition and of one, Jesus, who was dead, whom Paul affirmed to be alive.
* `Act 25:20` And because I doubted of such manner of *_questions_*, I asked him whether he would go to Jerusalem and there be judged concerning these matters.
* `Act 26:3` Especially because I know you to be expert in all customs and *_questions_* which are among the Jews. Therefore, I implore you to hear me patiently.
* `1Ti 1:4` Neither give heed to fables and endless genealogies, which minister *_questions_* rather than godly edifying which is in faith.
* `1Ti 6:4` He is proud, knowing nothing, but doting about *_questions_* and strifes of words, from which comes envy, strife, railings, evil surmisings,
* `2Ti 2:23` But avoid foolish and unlearned *_questions_*, knowing that they engender contentions.
* `Tit 3:9` But avoid foolish *_questions_*, genealogies, contentions, and strivings about the law, for they are unprofitable and vain.

_14 verses containing QUESTIONS_

== QUICK

* `Pro 14:17` He who is *_quick_* to anger deals foolishly, and a man of wicked devices is hated.

_1 verse containing QUICK_

== QUICKLY

* `Gen 18:6` And Abraham hastened into the tent to Sarah and said, "*_Quickly_* make ready three measures of fine meal, knead it, and make cakes upon the hearth."
* `Gen 27:20` And Isaac said to his son, "How is it that you have found it so *_quickly_*, my son?" And he said, "Because the LORD your God brought it to me."
* `Exo 32:8` They have turned aside *_quickly_* from the way which I commanded them. They have made themselves a molten calf, worshiped it, sacrificed to it, and said, 'These are your gods, O Israel, which have brought you out of the land of Egypt.'"
* `Num 16:46` And Moses said to Aaron, "Take a censer and put fire in it from off the altar and put incense on it, and go *_quickly_* to the congregation and make an atonement for them, for wrath has gone out from the LORD. The plague has begun."
* `Deu 9:3` Understand therefore this day, that the LORD your God is he who goes over before you as a consuming fire. He shall destroy them and he shall bring them down before your face. So you shall drive them out and destroy them *_quickly_*, as the LORD has said to you.
* `Deu 9:12` And the LORD said to me, 'Arise, go down *_quickly_* from here, for your people which you have brought forth out of Egypt have corrupted themselves. They have *_quickly_* turned aside from the way which I commanded them. They have made themselves a molten image.'
* `Deu 9:16` And I looked, and behold, you had sinned against the LORD your God and had made yourselves a molten calf. You had turned aside *_quickly_* from the way which the LORD had commanded you.
* `Deu 11:17` And the LORD'S wrath be kindled against you, and he restrain the heavens so that there shall be no rain, and the land shall not yield her fruit; and lest you perish *_quickly_* from off the good land which the LORD gives you.
* `Deu 28:20` "The LORD shall send upon you cursing, vexation, and rebuke in all that you undertake to perform until you are destroyed and until you perish *_quickly_*, because of the wickedness of your doings by which you have forsaken me.
* `Jsh 2:5` And it came to pass about the time of shutting the gate, when it was dark, that the men went out. Where the men went, I do not know. Pursue after them *_quickly_*, for you will overtake them."
* `Jsh 8:19` And the ambush arose *_quickly_* out of their place, and they ran as soon as he had stretched out his hand. And they entered into the city, took it, and hastened to set the city on fire.
* `Jsh 10:6` And the men of Gibeon sent to Joshua in the camp at Gilgal, saying, "Do not slack your hand from your servants. Come up to us *_quickly_* and save us, and help us, for all the kings of the Amorites who dwell in the mountains are assembled against us."
* `Jsh 23:16` If you transgress the covenant of the LORD your God, which he commanded you, and have gone and served other gods and bowed yourselves to them, then the anger of the LORD shall be kindled against you, and you shall perish *_quickly_* from off the good land which he has given to you."
* `Jdg 2:17` And still they would not listen to their judges, but they went astray after other gods and bowed themselves to them. They turned *_quickly_* out of the way which their fathers walked in, who obeyed the commandments of the LORD—but they did not do so.
* `1Sa 20:19` And when you have stayed three days, you shall go down *_quickly_* and come to the place where you hid yourself on the day of the business, and you shall remain by the stone of Ezel.
* `2Sa 5:24` And it shall come to pass when you hear the sound of a going in the tops of the mulberry-trees, that you shall move *_quickly_*, for then the LORD shall go out before you to smite the host of the Philistines."
* `2Sa 17:16` Now therefore, send *_quickly_* and tell David, saying, 'Do not lodge this night in the plains of the wilderness, but speedily pass over, lest the king be swallowed up, along with all the people who are with him.'"
* `2Sa 17:18` Nevertheless, a boy saw them and told Absalom. But the both of them went away *_quickly_* and came to the house of a man in Bahurim, who had a well in his court, into which they descended.
* `2Sa 17:21` And it came to pass after they had departed, that they came out of the well and went and told king David and said to David, "Arise and pass *_quickly_* over the water, for in this manner Ahithophel has counseled against you."
* `2Ki 1:11` And again he sent to him another captain of fifty with his fifty. And he answered and said to him, "O man of God, thus has the king said: 'Come down *_quickly_*.'"
* `2Ch 18:8` And the king of Israel called for one of his officers and said, "*_Quickly_* bring Micaiah the son of Imla."
* `Pro 7:22` He goes after her *_quickly_*, like an ox goes to the slaughter, or like a fool to the correction of the stocks,
* `Ecc 4:12` And if one prevails against him, two shall withstand him. A three-fold cord is not *_quickly_* broken.
* `Mth 5:25` Agree with your adversary *_quickly_* while you are in the way with him, lest at any time the adversary deliver you to the judge, and the judge deliver you to the officer, and you be cast into prison.
* `Mth 28:7` And go *_quickly_* and tell his disciples, 'He has risen from the dead, and behold, he goes before you into Galilee. There you shall see him.' Behold, I have told you."
* `Mth 28:8` And they departed *_quickly_* from the sepulcher with fear and great joy and ran to bring word to his disciples.
* `Mrk 16:8` And they went out *_quickly_* and fled from the sepulcher, for they trembled and were amazed. They did not say anything to any man, for they were afraid.
* `Luk 14:21` So that servant came and told his lord these things. Then the master of the house being angry, said to his servant, 'Go out *_quickly_* into the streets and lanes of the city and bring in here the poor, the maimed, the lame, and the blind.'
* `Luk 16:6` And he said, 'One hundred measures of oil.' And he said to him, 'Take your bill, sit down *_quickly_*, and write fifty.'
* `Jhn 11:29` As soon as she heard that, she arose *_quickly_* and came to him.
* `Jhn 13:27` And after the piece of bread, Satan entered into him. Then Jesus said to him, "What you do, do *_quickly_*."
* `Act 12:7` And behold, the angel of the Lord came upon him, and a light shined in the prison, and he smote Peter on the side and raised him up, saying, "Arise *_quickly_*." And his chains fell off from his hands.
* `Act 22:18` And saw him saying to me, 'Make haste, and depart *_quickly_* from Jerusalem, for they will not receive your testimony concerning me.'
* `Gal 1:6` I marvel that you are so *_quickly_* deserting him who called you into the grace of Christ to another gospel,
* `Heb 13:19` But I implore you the rather to do this so that I may be restored to you more *_quickly_*.
* `Rev 2:5` Remember therefore from where you have fallen, and repent and do the first works. Otherwise, I will come to you *_quickly_* and will remove your candlestick out of its place unless you repent.
* `Rev 2:16` Repent, or else I will come to you *_quickly_* and will fight against them with the sword of my mouth.
* `Rev 3:11` Behold, I come *_quickly_*. Hold firmly to that which you have so that no man takes your crown.
* `Rev 11:14` The second woe is past, and behold, the third woe comes *_quickly_*.
* `Rev 22:7` "Behold, I come *_quickly_*. Blessed is he who keeps the sayings of the prophecy of this book."
* `Rev 22:12` "And behold, I come *_quickly_*. And my reward is with me to give to every man according as his work shall be.
* `Rev 22:20` He who testifies these things says, "Surely I come *_quickly_*." Amen. Even so, come, Lord Jesus.

_42 verses containing QUICKLY_

== QUICKSANDS

* `Act 27:17` And when they hoisted it up, they used ropes to undergird the ship. Then, fearing that they would fall into the *_quicksands_*, they struck sail and were thus driven.

_1 verse containing QUICKSANDS_

== QUIET

* `Jdg 16:2` And it was told to the Gazites, saying, "Samson has come here." And they encompassed him and laid wait for him all night in the gate of the city. They were *_quiet_* all the night, saying, "In the morning when it is day we shall kill him."
* `Jdg 18:7` Then the five men departed and came to Laish and saw the people who were in it, how they dwelt carelessly after the manner of the Zidonians, *_quiet_* and secure. And there was no magistrate in the land who might put them to shame in anything. And they were far from the Zidonians and had no business with any man.
* `Jdg 18:27` And they took the things which Micah had made and the priest which he had, and came to Laish, to a people who were *_quiet_* and secure, and they smote them with the edge of the sword and burnt the city with fire.
* `2Ki 11:20` And all the people of the land rejoiced, and the city was *_quiet_*, because they slew Athaliah with the sword at the king's house.
* `1Ch 4:40` And they found rich and good pasture. And the land was wide, *_quiet_*, and peaceable, for those of Ham had dwelt there of old.
* `2Ch 14:1` So Abijah slept with his fathers, and they buried him in the city of David. And Asa his son reigned in his stead. In his days the land was *_quiet_* for ten years.
* `2Ch 14:5` He also took away out of all the cities of Judah the high places and the images. And the kingdom was *_quiet_* before him.
* `2Ch 20:30` Thus the realm of Jehoshaphat was *_quiet_*, for his God gave him rest on all sides.
* `2Ch 23:21` And all the people of the land rejoiced and the city was *_quiet_* after they had slain Athaliah with the sword.
* `Job 3:13` For now I should have lain still and been *_quiet_*. I should have slept. Then I would have been at rest
* `Job 3:26` I was not in safety, neither did I have rest, neither was I *_quiet_*, yet trouble came."
* `Job 21:23` One dies in his full strength, being wholly at ease and *_quiet_*.
* `Psa 35:20` For they do not speak peace, but they devise deceitful matters against those who are *_quiet_* in the land.
* `Psa 107:30` Then they are glad because they are *_quiet_*. Thus he brings them to their desired haven.
* `Pro 1:33` But whoever listens to me shall dwell in safety and shall be *_quiet_* from fear of evil."
* `Ecc 9:17` The words of wise men are heard in *_quiet_* more than the cry of him who rules among fools.
* `Isa 7:4` And say to him, 'Take heed and be *_quiet_*. Do not fear, neither be faint-hearted because of the two tails of these smoking fire-brands—because of the fierce anger of Rezin with Syria and of the son of Remaliah.
* `Isa 14:7` The whole earth is at rest and is *_quiet_*. They break forth into singing.
* `Isa 32:18` And my people shall dwell in a peaceable habitation, in sure dwellings, and in *_quiet_* resting-places,
* `Isa 33:20` Look upon Zion, the city of our solemnities. Your eyes shall see Jerusalem, a *_quiet_* habitation, a tabernacle that shall not be taken down. Not one of its stakes shall ever be removed, neither shall any of its cords be broken.
* `Jer 30:10` 'Therefore, do not fear, O my servant Jacob,' says the LORD, 'neither be dismayed, O Israel, for behold, I will save you from afar and your offspring from the land of their captivity, and Jacob shall return and be in rest and *_quiet_*, and no one shall make him afraid.
* `Jer 47:6` O sword of the LORD, how long will it be before you are *_quiet_*? Put yourself up into your scabbard. Rest, and be still.
* `Jer 47:7` How can it be *_quiet_*, seeing the LORD has given it a charge against Ashkelon and against the sea shore? There he has appointed it."
* `Jer 49:23` [Concerning Damascus.] "Hamath is confounded, and also Arpad, for they have heard evil tidings. They are faint-hearted. There is sorrow on the sea. It cannot be *_quiet_*.
* `Jer 51:59` This is the word which Jeremiah the prophet commanded Seraiah the son of Neriah, the son of Maaseiah, when he went with Zedekiah the king of Judah into Babylon in the fourth year of his reign. And this Seraiah was a *_quiet_* prince.
* `Ezk 16:42` Thus I will make my fury toward you to rest and my jealousy shall depart from you. I will be *_quiet_* and will no longer be angry.
* `Nah 1:12` Thus says the LORD: "Though they are *_quiet_* and likewise many, yet thus they shall be cut down, and he shall pass away. Though I have afflicted you, I will no longer afflict you.
* `Act 19:36` Seeing then that these things cannot be contradicted, you ought to be *_quiet_* and to do nothing rashly.
* `1Th 4:11` And that you make it your ambition to be *_quiet_*, to do your own business, and to work with your own hands, as we commanded you,
* `1Ti 2:2` For kings, and for all who are in authority, so that we may lead a *_quiet_* and peaceable life in all godliness and honesty.
* `1Pe 3:4` But let it be the hidden person of the heart, in that which is not corruptible, even the ornament of a meek and *_quiet_* spirit, which is in the sight of God of great price.

_31 verses containing QUIET_

== QUIETED

* `Psa 131:2` Surely I have behaved and *_quieted_* myself like a child who is weaned by his mother. My soul is even like a weaned child.
* `Zch 6:8` Then he cried out to me and spoke to me, saying, "Behold, these which go toward the north country have *_quieted_* my Spirit in the north country."

_2 verses containing QUIETED_

== QUIETLY

* `2Sa 3:27` And when Abner had returned to Hebron, Joab took him aside in the gate to speak with him *_quietly_* and smote him there under the fifth rib so that he died for the blood of Asahel his brother.
* `Lam 3:26` It is good that a man should both hope and *_quietly_* wait for the salvation of the LORD.

_2 verses containing QUIETLY_

== QUIETNESS

* `Jdg 8:28` Thus Midian was subdued before the children of Israel, so that they raised their heads no more. And the country was in *_quietness_* for forty years in the days of Gideon.
* `1Ch 22:9` Behold, a son shall be born to you who shall be a man of rest. And I will give him rest from all his enemies around, for his name shall be Solomon, and I will give peace and *_quietness_* to Israel in his days.
* `Job 20:20` Surely he shall not feel *_quietness_* in his belly. He shall not save anything of that in which he desired.
* `Job 34:29` When he gives *_quietness_*, who then can make trouble? And when he hides his face, who then can behold him, whether it be done against a nation or against a man only?
* `Pro 17:1` Better is a dry morsel and *_quietness_* with it, than a house full of sacrifices with strife.
* `Ecc 4:6` Better is a handful with *_quietness_*, than both the hands full with toil and vexation of spirit.
* `Isa 30:15` For thus says the Lord GOD, the Holy One of Israel: "In returning and rest you shall be saved. In *_quietness_* and in confidence your strength shall be." And you have not been willing.
* `Isa 32:17` And the work of righteousness shall be peace, and the effect of righteousness shall be *_quietness_* and assurance forever.
* `Act 24:2` And when he was called forth, Tertullus began to accuse him, saying, "Seeing that by you we enjoy great *_quietness_* and that very worthy deeds are done to this nation by your providence,
* `2Th 3:12` Now those who are such we command and exhort by our Lord Jesus Christ that they work with *_quietness_* and eat their own bread.

_10 verses containing QUIETNESS_

== QUIETS

* `Job 37:17` You whose garments are warm, when he *_quiets_* the earth by the south wind?

_1 verse containing QUIETS_

== QUITE

* `Gen 31:15` Are we not regarded by him as strangers? For he has sold us and has also *_quite_* consumed our money.
* `Exo 23:24` You shall not bow down to their gods, nor serve them, nor do after their works, but you shall utterly overthrow them and *_quite_* break down their images.
* `Num 17:10` And the LORD said to Moses, "Bring Aaron's rod back before the testimony to be kept for a token against the rebels, and you shall *_quite_* take away their murmurings from me so that they do not die."
* `Num 33:52` You shall drive out all the inhabitants of the land from before you, destroy all their pictures, destroy all their molten images, and *_quite_* demolish all their high places.
* `Jsh 3:17` And the priests who bore the ark of the covenant of the LORD stood firm on dry ground in the midst of the Jordan, and all the Israelites passed over on dry ground until all the people had *_quite_* passed over the Jordan.
* `Jsh 4:1` And it came to pass when all the people had *_quite_* passed over the Jordan, that the LORD spoke to Joshua, saying,
* `Jsh 4:11` And it came to pass when all the people had *_quite_* passed over, that the ark of the LORD and the priests passed over in the presence of the people.
* `2Sa 3:24` Then Joab came to the king and said, "What have you done? Behold, Abner came to you. Why is it that you have sent him away, and he is *_quite_* gone?
* `Job 6:13` Is my help not in me? And is wisdom driven *_quite_* from me?
* `Hab 3:9` Your bow was made *_quite_* ready, according to the oaths of the tribes, even your word. [Selah.] You cleaved the earth with rivers.
* `2Pe 2:18` For when they speak great swelling words of vanity, they allure through the lusts of the flesh, through much wantonness, those who had *_quite_* escaped from those who live in error.

_11 verses containing QUITE_

== QUIVER

* `Gen 27:3` Now therefore, take, I pray you, your weapons, your *_quiver_* and your bow, and go out to the field and hunt some wild game for me.
* `Job 39:23` The *_quiver_* rattles against him, the glittering spear and the shield.
* `Psa 127:5` Happy is the man who has his *_quiver_* full of them. They shall not be ashamed, but they shall speak with the enemies in the gate.
* `Isa 22:6` And Elam bore the *_quiver_* with chariots of men and horsemen, and Kir uncovered the shield.
* `Isa 49:2` And he has made my mouth like a sharp sword. In the shadow of his hand he has hid me. He made me a polished shaft, and in his *_quiver_* he has hid me.
* `Jer 5:16` Their *_quiver_* is as an open sepulcher. They are all mighty men.
* `Lam 3:13` [HE] He has caused the arrows of his *_quiver_* to enter into my kidneys.

_7 verses containing QUIVER_

== QUIVERED

* `Hab 3:16` When I heard, my belly trembled. My lips *_quivered_* at the voice. Rottenness entered into my bones, and I trembled in myself, so that I might rest in the day of trouble. When he comes up to the people, he will invade them with his troops.

_1 verse containing QUIVERED_

