= CONSIDER - CORMORANT
:toc:

== CONSIDER

* `Exo 33:13` Now therefore, I pray you, if I have found grace in your sight, show me now your way so that I may know you and that I may find grace in your sight. And *_consider_* that this nation is your people."
* `Lev 11:11` They shall even be an abomination to you. You shall not eat their flesh, but you shall *_consider_* their carcasses as an abomination.
* `Lev 11:13` 'And these you shall *_consider_* as an abomination among the birds, and they shall not be eaten, for they are an abomination: the eagle, the vulture, the osprey,
* `Lev 13:13` Then the priest shall *_consider_*, and behold, if the leprosy has covered all his flesh, he shall pronounce him clean who has the plague. It is all turned white. He is clean.
* `Deu 4:39` Know therefore this day, and *_consider_* it in your heart, that the LORD, he is God in heaven above and upon the earth beneath. There is no one else.
* `Deu 8:5` You shall also *_consider_* in your heart, that as a man chastens his son, so the LORD your God chastens you.
* `Deu 32:7` Remember the days of old. *_Consider_* the years of many generations. Ask your father, and he will declare to you. [Ask] your elders, and they will tell you.
* `Deu 32:29` O that they were wise, that they understood this, that they would *_consider_* their latter end!
* `Jdg 18:14` Then the five men who went to explore the country of Laish answered and said to their brothers, "Do you know that there is in these houses an ephod, teraphim, an engraved image, and a molten image? Now therefore, *_consider_* what you have to do."
* `Jdg 19:30` And it was so, that all who saw it, said, "There has been no such deed done nor seen from the day that the children of Israel came from the land of Egypt to this day. *_Consider_* it, take advice, and speak your minds."
* `1Sa 12:24` Only fear the LORD and serve him in truth with all your heart. For *_consider_* what great things he has done for you.
* `1Sa 25:17` Now therefore, know and *_consider_* what you will do, for evil is determined against our master and against all his household. For he is such a son of Belial that a man cannot speak to him."
* `2Sa 24:13` So Gad came to David and told him. And he said to him, "Shall seven years of famine come upon you in your land? Or will you flee three months before your enemies while they pursue you? Or shall there be three days' pestilence in your land? Now *_consider_*, and see what answer I shall return to him who sent me."
* `2Ki 5:7` And it came to pass when the king of Israel had read the letter, that he rent his clothes and said, "Am I God, to kill and to make alive, that this man sends to me to recover a man of his leprosy? Therefore, *_consider_*, I pray you, and see how he seeks a quarrel against me."
* `Job 11:11` For he knows vain men. He sees wickedness also. Will he not then *_consider_* it?
* `Job 23:15` Therefore, I am troubled at his presence. When I *_consider_*, I am afraid of him.
* `Job 34:27` Because they turned back from him and would not *_consider_* any of his ways,
* `Job 37:14` Listen to this, O Job. Stand still and *_consider_* the wondrous works of God.
* `Psa 5:1` [To the Chief Musician upon Nehiloth. A Psalm of David.] Give ear to my words, O LORD. *_Consider_* my meditation.
* `Psa 8:3` When I *_consider_* your heavens, the work of your fingers, the moon and the stars, which you have ordained,
* `Psa 9:13` Have mercy upon me, O LORD. *_Consider_* my trouble which I suffer from those who hate me, and lift me up from the gates of death
* `Psa 13:3` *_Consider_* and hear me, O LORD my God. Lighten my eyes, lest I sleep the sleep of death,
* `Psa 25:19` [QOF] *_Consider_* my enemies, for they are many, and they hate me with cruel hatred.
* `Psa 37:10` For yet a little while, and the wicked shall not be. You shall even diligently *_consider_* his place, and it shall not be.
* `Psa 45:10` Listen, O daughter. *_Consider_*, and incline your ear. Forget your own people and your father's house,
* `Psa 48:13` Mark well her bulwarks, and *_consider_* her palaces so that you may tell it to the generation following.
* `Psa 50:22` Now *_consider_* this, you who forget God, lest I tear you in pieces and there be no one to deliver:
* `Psa 64:9` And all men shall fear and declare the work of God, for they shall wisely *_consider_* his work.
* `Psa 119:95` The wicked have waited for me to destroy me, but I will *_consider_* your testimonies.
* `Psa 119:153` [RESH] *_Consider_* my affliction and deliver me, for I do not forget your law.
* `Psa 119:159` *_Consider_* how I love your precepts. Revive me, O LORD, according to your loving-kindness.
* `Pro 6:6` Go to the ant, you sluggard. *_Consider_* her ways and be wise.
* `Pro 23:1` When you sit to eat with a ruler, *_consider_* diligently what is before you,
* `Pro 24:12` If you say, "Behold, we did not know it," does he who ponders the heart not *_consider_* it? And he who keeps your soul, does he not know it? And will he not render to every man according to his works?
* `Pro 28:22` He who hastens to be rich has an evil eye and does not *_consider_* that poverty shall come upon him.
* `Ecc 5:1` Keep your foot when you go to the house of God, and be more ready to hear than to give the sacrifice of fools, for they do not *_consider_* that they do evil.
* `Ecc 7:13` *_Consider_* the work of God, for who can make straight that which he has made crooked?
* `Ecc 7:14` In the day of prosperity be joyful, but in the day of adversity *_consider_* this: God also has set one over against the other, to the end that man should find nothing after him.
* `Isa 1:3` The ox knows his owner and the donkey his master's crib, but Israel does not know, my people do not *_consider_*."
* `Isa 5:12` And the harp, the psaltery, the tambourine, pipe, and wine are in their feasts, but they do not regard the work of the LORD, neither *_consider_* the operation of his hands.
* `Isa 14:16` Those who see you shall narrowly look upon you and *_consider_* you, saying, 'Is this the man who made the earth to tremble, who shook kingdoms,
* `Isa 18:4` For thus the LORD said to me: "I will take my rest, and I will *_consider_* in my dwelling-place like a clear heat upon herbs and like a cloud of dew in the heat of harvest."
* `Isa 41:20` So that they may see, know, *_consider_*, and understand together, that the hand of the LORD has done this, and the Holy One of Israel has created it.
* `Isa 41:22` "Let them bring them forth and show us what shall happen. Let them show the former things, what they are, so that we may *_consider_* them and know the latter end of them. Or declare to us things to come.
* `Isa 43:18` "Do not remember the former things, neither *_consider_* the things of old.
* `Isa 52:15` So he shall sprinkle many nations. The kings shall shut their mouths at him, for that which had not been told to them they shall see, and that which they had not heard they shall *_consider_*.
* `Jer 2:10` For pass over to the coastlands of Chittim and see. And send to Kedar and *_consider_* diligently and see if there is such a thing.
* `Jer 9:17` Thus says the LORD of hosts: "*_Consider_*, and call for the mourning women so that they may come, and send for skillful women so that they may come.
* `Jer 23:20` The anger of the LORD shall not return until he has executed and until he has performed the thoughts of his heart. In the latter days you shall *_consider_* it perfectly.
* `Jer 30:24` The fierce anger of the LORD shall not return until he has done it and until he has performed the intents of his heart. In the latter days you shall *_consider_* it.
* `Jer 33:24` "Do you not *_consider_* what this people has spoken, saying, 'The two families which the LORD has chosen, he has even cast them off'? Thus they have despised my people so that they should no longer be a nation before them.
* `Lam 1:11` [KAF] All her people sigh. They seek bread. They have given their pleasant things for food to relieve the soul. See, O LORD, and *_consider_*, for I have become vile.
* `Lam 2:20` [RESH] Behold, O LORD, and *_consider_* to whom you have done this. Shall the women eat their fruit, the children which they nursed? Shall the priest and the prophet be slain in the sanctuary of the Lord?
* `Lam 5:1` Remember, O LORD, what has come upon us. *_Consider_* and behold our reproach.
* `Ezk 12:3` Therefore, son of man, prepare stuff for exile and move by day in their sight. And you shall move from your place to another place in their sight. It may be that they will *_consider_*, though they are a rebellious house.
* `Dan 9:23` At the beginning of your supplications the commandment came forth, and I have come to show you, for you are greatly beloved. Therefore, understand the matter and *_consider_* the vision.
* `Hos 7:2` And they do not *_consider_* in their hearts that I remember all their wickedness. Now their own doings have beset them around. They are before my face.
* `Hag 1:5` Now therefore, thus says the LORD of hosts: "*_Consider_* your ways.
* `Hag 1:7` Thus says the LORD of hosts: "*_Consider_* your ways.
* `Hag 2:15` And now, I pray you, *_consider_* from this day onward, before stone was laid upon stone in the temple of the LORD.
* `Hag 2:18` '*_Consider_* now from this day onward, from the twenty-fourth day of the ninth month, even from the day that the foundation of the LORD'S temple was laid, *_consider_* it.
* `Mth 6:28` And why are you anxious for clothing? *_Consider_* the lilies of the field and how they grow: they do not toil, neither do they spin,
* `Mth 7:3` And why do you behold the mote that is in your brother's eye, but do not *_consider_* the beam that is in your own eye?
* `Mrk 6:52` For they did not *_consider_* the miracle of the loaves, but their heart was hardened.
* `Luk 12:24` *_Consider_* the ravens: they neither sow nor reap, which neither have store-house, nor barn, and God feeds them. How much more are you better than the birds?
* `Luk 12:27` *_Consider_* the lilies, how they grow: they do not toil, they do not spin, and yet I say to you, that Solomon in all his glory was not arrayed like one of these.
* `Jhn 11:50` Nor *_consider_* that it is expedient for us that one man should die for the people, and that the whole nation not perish."
* `Act 15:6` And the apostles and elders came together to *_consider_* this matter.
* `Rom 4:19` And not having been weak in faith, he did not *_consider_* his own body now dead when he was about one hundred years old, neither yet the deadness of Sarah's womb.
* `2Co 10:7` Do you look at things after the outward appearance? If any man trusts to himself that he is Christ's, let him *_consider_* this within himself again: that as he is Christ's, even so are we Christ's.
* `2Ti 2:7` *_Consider_* what I say, and may the Lord give you understanding in all things.
* `Heb 3:1` Therefore, holy brothers, partakers of the heavenly calling, *_consider_* the Apostle and High Priest of our profession, Christ Jesus,
* `Heb 7:4` Now *_consider_* how great this man was, to whom even the patriarch Abraham gave the tenth of the plunder.
* `Heb 10:24` And let us *_consider_* one another to excite to love and to good works,
* `Heb 12:3` *_Consider_* him who endured such contradiction of sinners against himself, lest you be wearied and faint in your minds.

_75 verses containing CONSIDER_

== CONSIDERED

* `1Ki 3:21` And when I rose in the morning to nurse my child, behold, it was dead. But when I had *_considered_* it in the morning, behold, it was not my son which I bore."
* `1Ki 5:8` And Hiram sent to Solomon, saying, "I have *_considered_* the things which you sent to me for, and I will perform all your desire concerning timber of cedar and concerning timber of fir.
* `Job 1:8` And the LORD said to Satan, "Have you *_considered_* my servant Job, that there is no one like him on the earth, an upright and a just man, one who fears God and shuns evil?"
* `Job 2:3` And the LORD said to Satan, "Have you *_considered_* my servant Job, that there is no one like him on the earth, an upright and a just man, one who fears God and shuns evil? And still he holds firmly to his integrity, although you moved me against him to destroy him without cause."
* `Psa 31:7` I will be glad and rejoice in your mercy, for you have *_considered_* my trouble. You have known my soul in adversities,
* `Psa 77:5` I have *_considered_* the days of old, the years of ancient times.
* `Psa 119:59` I *_considered_* my ways and turned my feet to your testimonies.
* `Pro 24:32` Then I saw and *_considered_* it well. I looked upon it and received instruction.
* `Ecc 2:11` Then I *_considered_* all the works that my hands had wrought and the labor that I had labored to do, and behold, all was vanity and vexation of spirit, and there was no profit under the sun.
* `Ecc 4:1` Thus I returned, and *_considered_* all the oppressions that are done under the sun. And behold, the tears of those who were oppressed, and they had no comforter. And on the side of their oppressors there was power, but they had no comforter.
* `Ecc 4:4` Again, I *_considered_* all labor and every right work, that for this, a man is envied by his neighbor. This is also vanity and vexation of spirit.
* `Ecc 4:15` I *_considered_* all the living who walk under the sun, that they were with the second youth who shall stand up in his stead.
* `Ecc 9:1` For all this I *_considered_* in my heart even to declare all this: that the righteous and the wise, and their works, are in the hand of God. No man knows either love or hatred by all that is before them.
* `Dan 7:8` I *_considered_* the horns, and behold, there came up among them another little horn, before which there were three of the first horns plucked up by the roots. And behold, in this horn were eyes like the eyes of a man and a mouth speaking great things.
* `Luk 1:29` And when she saw him, she was troubled at his saying and *_considered_* what kind of salutation this might be.
* `Act 11:6` Upon which when I had fastened my eyes, I *_considered_*, and saw four-footed beasts of the earth, wild beasts, creeping animals, and birds of the air.
* `Act 12:12` And when he had *_considered_* the thing, he came to the house of Mary the mother of John whose surname was Mark, where many were assembled and praying.

_17 verses containing CONSIDERED_

== CONSIDERING

* `Isa 57:1` The righteous perish, and no man lays it to heart. And merciful men are taken away, no one *_considering_* that the righteous is taken away from the evil to come.
* `Dan 8:5` And as I was *_considering_*, behold, a male goat came from the west on the face of the whole earth, and did not touch the ground. And the goat had a notable horn between his eyes.
* `Gal 6:1` Brothers, if a man is overtaken in a fault, you who are spiritual, restore such a one in the spirit of meekness, *_considering_* yourself, lest you also be tempted.
* `Heb 13:7` Remember your leaders, who spoke to you the word of God. Follow their faith, *_considering_* the end of their manner of life.

_4 verses containing CONSIDERING_

== CONSIDERS

* `Psa 33:15` He fashions their hearts alike. He *_considers_* all their works.
* `Psa 41:1` [To the Chief Musician. A Psalm of David.] Blessed is he who *_considers_* the poor. The LORD will deliver him in the time of trouble.
* `Pro 21:12` The righteous man wisely *_considers_* the house of the wicked, but God overthrows the wicked for their wickedness.
* `Pro 29:7` The righteous *_considers_* the cause of the poor, but the wicked does not regard to know it.
* `Pro 31:16` [ZAYIN] She *_considers_* a field and buys it. With the fruit of her hands she plants a vineyard.
* `Isa 44:19` And no one *_considers_* in his heart, neither is there knowledge nor understanding to say, "I have burned part of it in the fire. I have also baked bread upon its coals. I have roasted flesh and eaten it. And shall I make the rest of it an abomination? Shall I fall down to a block of wood?"
* `Ezk 18:14` "Now behold, if he begets a son, who sees all his father's sins which he has done, and *_considers_*, and does not do such things,
* `Ezk 18:28` Because he *_considers_* and turns away from all his transgressions that he has committed, he shall surely live. He shall not die.

_8 verses containing CONSIDERS_

== CONSIST

* `Luk 12:15` And he said to them, "Take heed, and beware of covetousness, for a man's life does not *_consist_* in the abundance of the things which he possesses."
* `Col 1:17` And he is before all things, and by him all things *_consist_*.

_2 verses containing CONSIST_

== CONSOLATION

* `Jer 16:7` Neither shall men tear themselves for them in mourning to comfort them for the dead; neither shall men give them the cup of *_consolation_* to drink for their father or for their mother.
* `Luk 2:25` And behold, there was a man in Jerusalem whose name was Simeon, and the same man was just and devout, waiting for the *_consolation_* of Israel. And the Holy Spirit was upon him.
* `Luk 6:24` But woe to you who are rich! For you have received your *_consolation_*.
* `Act 4:36` And Joseph, who by the apostles was surnamed Barnabas (which is, being interpreted, The Son of *_Consolation_*), a Levite and from the country of Cyprus,
* `Act 15:31` Which, when they had read, they rejoiced for the *_consolation_*.
* `Rom 15:5` Now may the God of patience and *_consolation_* grant you to be like-minded toward one another according to Christ Jesus,
* `2Co 1:3` Blessed be God, even the Father of our Lord Jesus Christ, the Father of mercies, and the God of all *_consolation_*,
* `2Co 1:4` Who comforts us in all our tribulation so that we may be able to comfort those who are in any trouble by the *_consolation_* with which we ourselves are comforted by God.
* `2Co 1:5` For as the sufferings of Christ abound in us, so our *_consolation_* also abounds by Christ.
* `2Co 1:6` And whether we are afflicted, it is for your *_consolation_* and salvation, which is effectual in the enduring of the same sufferings which we also suffer, or whether we are comforted, it is for your *_consolation_* and salvation.
* `2Co 1:7` And our hope for you is steadfast, knowing, that as you are partakers of the sufferings, so you shall also be of the *_consolation_*.
* `2Co 7:7` And not by his coming only, but by the *_consolation_* with which he was comforted in you when he told us your earnest desire, your mourning, and your fervent mind toward me, so that I rejoiced the more.
* `Phl 2:1` If there is therefore any *_consolation_* in Christ, if any comfort of love, if any fellowship of the Spirit, if any inner affections and mercies,
* `2Th 2:16` Now may our Lord Jesus Christ himself and God, even our Father, who has loved us and has given us everlasting *_consolation_* and good hope through grace,
* `Phm 1:7` For we have great joy and *_consolation_* in your love because the hearts of the saints are refreshed by you, brother.
* `Heb 6:18` So that by two immutable things, in which it was impossible for God to lie, we might have a strong *_consolation_*, who have fled for refuge to lay hold upon the hope set before us.

_16 verses containing CONSOLATION_

== CONSOLATIONS

* `Job 15:11` Are the *_consolations_* of God small with you? Is there any secret thing with you?
* `Job 21:2` "Hear diligently my speech, and let this be your *_consolations_*.
* `Isa 66:11` So that you may nurse and be satisfied with the breasts of her *_consolations_*, so that you may draw milk and be delighted with the abundance of her glory."

_3 verses containing CONSOLATIONS_

== CONSORTED

* `Act 17:4` And some of them believed and *_consorted_* with Paul and Silas, along with a great multitude of the devout Greeks and many of the chief women.

_1 verse containing CONSORTED_

== CONSPIRACY

* `2Sa 15:12` And Absalom sent for Ahithophel the Gilonite, David's counselor, from his city, even from Giloh, while he offered sacrifices. And the *_conspiracy_* was strong, for the people increased continually with Absalom.
* `2Ki 12:20` And his servants arose and made a *_conspiracy_* and slew Joash in the house of Millo, which goes down to Silla.
* `2Ki 14:19` Now they made a *_conspiracy_* against him in Jerusalem, and he fled to Lachish. But they sent after him to Lachish and slew him there.
* `2Ki 15:15` And the rest of the acts of Shallum and his *_conspiracy_* which he made, behold, they are written in the book of the chronicles of the kings of Israel.
* `2Ki 15:30` And Hoshea the son of Elah made a *_conspiracy_* against Pekah the son of Remaliah, smote him, slew him, and reigned in his stead, in the twentieth year of Jotham the son of Uzziah.
* `2Ki 17:4` And the king of Assyria found *_conspiracy_* in Hoshea, for he had sent messengers to So king of Egypt and brought no present to the king of Assyria as he had done year by year. Therefore, the king of Assyria shut him up and bound him in prison.
* `2Ch 25:27` Now after the time that Amaziah turned away from following the LORD, they made a *_conspiracy_* against him in Jerusalem, and he fled to Lachish. But they sent to Lachish after him and slew him there.
* `Jer 11:9` And the LORD said to me, "A *_conspiracy_* is found among the men of Judah and among the inhabitants of Jerusalem.
* `Ezk 22:25` There is a *_conspiracy_* of her prophets in the midst of her, like a roaring lion ravening the prey. They have devoured souls. They have taken the treasure and precious things. They have made her many widows in the midst of her.
* `Act 23:13` And they were more than forty who had made this *_conspiracy_*.

_10 verses containing CONSPIRACY_

== CONSPIRATORS

* `2Sa 15:31` And someone told David, saying, "Ahithophel is among the *_conspirators_* with Absalom." And David said, "O LORD, I pray you, turn the counsel of Ahithophel into foolishness."

_1 verse containing CONSPIRATORS_

== CONSPIRED

* `Gen 37:18` And when they saw him afar off, even before he came near to them, they *_conspired_* against him to slay him.
* `1Sa 22:8` For all of you have *_conspired_* against me. And there is no one who shows me that my son has made a league with the son of Jesse, and there is not one of you who is sorry for me or shows to me that my son has stirred up my servant against me to lie in wait, as at this day."
* `1Sa 22:13` And Saul said to him, "Why have you *_conspired_* against me—you and the son of Jesse—in that you have given him bread and a sword and have inquired of God for him so that he should rise against me to lie in wait, as at this day?"
* `1Ki 15:27` And Baasha the son of Ahijah from the house of Issachar *_conspired_* against him. And Baasha smote him at Gibbethon, which belonged to the Philistines, for Nadab and all Israel laid siege to Gibbethon.
* `1Ki 16:9` And his servant Zimri, captain of half his chariots, *_conspired_* against him as he was in Tirzah drinking himself drunk in the house of Arza, steward of his house in Tirzah.
* `1Ki 16:16` And the people who were encamped heard it said, "Zimri has *_conspired_* and has also slain the king." Therefore, all Israel made Omri, the captain of the host, king over Israel that day in the camp.
* `2Ki 9:14` So Jehu the son of Jehoshaphat the son of Nimshi *_conspired_* against Joram. (Now Joram had kept Ramoth-gilead—he and all Israel—because of Hazael king of Syria.
* `2Ki 10:9` And it came to pass in the morning, that he went out and stood and said to all the people, "You are righteous. Behold, I *_conspired_* against my master and slew him. But who slew all these?
* `2Ki 15:10` And Shallum the son of Jabesh *_conspired_* against him, smote him before the people, slew him, and reigned in his stead.
* `2Ki 15:25` But Pekah the son of Remaliah, a captain of his, *_conspired_* against him and smote him in Samaria at the palace of the king's house, with Argob and Arieh. Fifty men of the Gileadites were with him. And he killed him and reigned in his stead.
* `2Ki 21:23` And the servants of Amon *_conspired_* against him and slew the king in his own house.
* `2Ki 21:24` And the people of the land slew all those who had *_conspired_* against king Amon, and the people of the land made Josiah his son king in his stead.
* `2Ch 24:21` And they *_conspired_* against him and stoned him with stones at the commandment of the king in the court of the house of the LORD.
* `2Ch 24:25` And when they had departed from him (for they left him in great diseases), his own servants *_conspired_* against him for the blood of the sons of Jehoiada the priest and slew him on his bed, and he died. And they buried him in the city of David, but they did not bury him in the sepulchers of the kings.
* `2Ch 24:26` And these are those who *_conspired_* against him: Zabad the son of Shimeath the Ammonitess, and Jehozabad the son of Shimrith the Moabitess.
* `2Ch 33:24` And his servants *_conspired_* against him and slew him in his own house.
* `2Ch 33:25` But the people of the land slew all those who had *_conspired_* against king Amon. And the people of the land made Josiah his son king in his stead.
* `Neh 4:8` And all of them *_conspired_* together to come and to fight against Jerusalem and to hinder it.
* `Amo 7:10` Then Amaziah the priest of Beth-el sent to Jeroboam king of Israel, saying, "Amos has *_conspired_* against you in the midst of the house of Israel. The land is not able to bear all his words.

_19 verses containing CONSPIRED_

== CONSTANT

* `1Ch 28:7` Moreover, I will establish his kingdom forever if he is *_constant_* to do my commandments and my judgments, as at this day.'

_1 verse containing CONSTANT_

== CONSTANTLY

* `Act 12:15` And they said to her, "You are insane." But she *_constantly_* affirmed that it was even so. Then they said, "It is his angel."
* `Tit 3:8` This is a faithful saying, and these things I wish that you affirm *_constantly_* so that those who have believed in God may be careful to maintain good works. These things are good and profitable to men.

_2 verses containing CONSTANTLY_

== CONSTELLATIONS

* `Isa 13:10` For the stars of heaven and its *_constellations_* shall not give their light. The sun shall be darkened in his going forth, and the moon shall not cause her light to shine.

_1 verse containing CONSTELLATIONS_

== CONSTERNATION

* `2Ch 32:18` Then they cried with a loud voice in the Jews' speech to the people of Jerusalem who were on the wall to terrify them and to fill them with *_consternation_* so that they might take the city.

_1 verse containing CONSTERNATION_

== CONSTRAIN

* `Gal 6:12` As many as desire to make a fair show in the flesh, they *_constrain_* you to be circumcised—only lest they should suffer persecution for the cross of Christ.

_1 verse containing CONSTRAIN_

== CONSTRAINED

* `2Ki 4:8` And it fell on a day, that Elisha passed to Shunem where a distinguished woman was, and she *_constrained_* him to eat bread. And so it was, that as often as he passed by, he turned in there to eat bread.
* `Job 37:10` By the breath of God frost is given, and the breadth of the waters is *_constrained_*.
* `Mth 14:22` And immediately Jesus *_constrained_* his disciples to get into a boat and to go before him to the other side while he sent the multitudes away.
* `Mth 27:32` And as they came out, they found a man of Cyrene, Simon by name. They *_constrained_* him to bear his cross.
* `Mrk 6:45` And immediately he *_constrained_* his disciples to get into the boat and to go to the other side ahead of him to Bethsaida while he sent the people away.
* `Mrk 15:21` And they *_constrained_* someone who was passing by, Simon of Cyrene (the father of Alexander and Rufus), who was coming from the country, to bear his cross.
* `Luk 24:29` But they *_constrained_* him, saying, "Abide with us, for it is toward evening and the day is far spent." And he went in to stay with them.
* `Act 7:26` And the next day he showed himself to them as they were contending and would have *_constrained_* them to be at peace again, saying, 'Sirs, you are brothers. Why do you do wrong to one another?'
* `Act 16:15` And when she was baptized, along with her household, she implored us, saying, "If you have judged me to be faithful to the Lord, come into my house and stay there." And she *_constrained_* us.
* `Act 28:19` But when the Jews spoke against it, I was *_constrained_* to appeal to Caesar, not that I had anything to accuse my nation of.

_10 verses containing CONSTRAINED_

== CONSTRAINS

* `Job 32:18` For I am full of matter, and the spirit within me *_constrains_* me.
* `Mth 5:41` And whoever *_constrains_* you to go one mile, go with him two.
* `2Co 5:14` For the love of Christ *_constrains_* us because we thus judge: that if one died for all, then all were dead,

_3 verses containing CONSTRAINS_

== CONSTRAINT

* `Job 36:16` Even so he would have enticed you out of distress into a broad place where there is no *_constraint_*, and that which should be set on your table would be full of fatness.
* `2Co 9:7` Let every man give according as he purposes in his heart, not grudgingly or by *_constraint_*, for "God loves a cheerful giver."
* `1Pe 5:2` Feed the flock of God which is among you, taking the oversight of it—not by *_constraint_*, but willingly; not for filthy lucre, but from a ready mind;

_3 verses containing CONSTRAINT_

== CONSULT

* `Psa 62:4` They only *_consult_* to cast him down from his excellence. They delight in lies. They bless with their mouth, but they curse inwardly. [Selah.]
* `Luk 14:31` Or what king going to make war against another king does not sit down first and *_consult_* whether he is able with ten thousand to meet him who comes against him with twenty thousand?

_2 verses containing CONSULT_

== CONSULTATION

* `Mrk 15:1` And immediately in the morning the chief priests held a *_consultation_* with the elders, scribes, and the whole council, and bound Jesus, carried him away, and delivered him to Pilate.

_1 verse containing CONSULTATION_

== CONSULTED

* `1Ki 12:6` And king Rehoboam *_consulted_* with the old men who stood before Solomon his father while he still lived and said, "How do you advise that I may answer this people?"
* `1Ki 12:8` But he forsook the counsel of the old men which they had given him and *_consulted_* with the young men who had grown up with him, and who stood before him.
* `1Ch 13:1` And David *_consulted_* with the captains of thousands and of hundreds and with every leader.
* `2Ch 20:21` And when he had *_consulted_* with the people, he appointed singers to the LORD who should praise the beauty of his holiness as they went out before the army, and to say, "Praise the LORD, for his mercy endures forever."
* `Neh 5:7` Then I *_consulted_* with myself, and I rebuked the nobles and the rulers, and said to them, "You exact interest, each from his brother." And I set a great assembly against them.
* `Psa 83:3` They have taken crafty counsel against your people and *_consulted_* against your hidden ones.
* `Psa 83:5` For they have *_consulted_* together with one consent. They are confederated against you:
* `Ezk 21:21` For the king of Babylon stood at the parting of the way, at the head of the two ways, to use divination: he shook the arrows, he *_consulted_* with images, and he examined the liver.
* `Dan 6:7` All the presidents of the kingdom, the governors, the princes, the counselors, and the captains have *_consulted_* together to establish a royal statute and to make a firm decree, that whoever asks a petition of any god or man for thirty days, except of you, O king, he shall be cast into the den of lions.
* `Mic 6:5` O my people, remember now what Balak king of Moab *_consulted_*, and what Balaam the son of Beor answered him, [and what I did] from Shittim to Gilgal, so that you may know the righteousness of the LORD."
* `Mth 26:4` And *_consulted_* that they might take Jesus by subtlety and kill him.
* `Jhn 12:10` But the chief priests *_consulted_* that they might also put Lazarus to death,

_12 verses containing CONSULTED_

== CONSULTER

* `Deu 18:11` A charmer, a *_consulter_* with familiar spirits, a wizard, or a necromancer.

_1 verse containing CONSULTER_

== CONSUME

* `Gen 41:30` And there shall arise after them seven years of famine, and all the plenty shall be forgotten in the land of Egypt, and the famine shall *_consume_* the land.
* `Exo 32:10` Now therefore, leave me alone so that my wrath may wax hot against them and that I may *_consume_* them, and I will make of you a great nation."
* `Exo 32:12` Why should the Egyptians speak and say, 'For evil he brought them out to slay them in the mountains and to *_consume_* them from the face of the earth'? Turn from your fierce wrath and repent of this evil against your people.
* `Exo 33:3` Go up to a land flowing with milk and honey. But I will not go up in the midst of you, for you are a stiff-necked people, lest I *_consume_* you in the way."
* `Exo 33:5` For the LORD had said to Moses, "Say to the children of Israel, 'You are a stiff-necked people. I will come up into the midst of you in a moment and *_consume_* you. And now, take off your ornaments from you so that I may know what to do to you.'"
* `Lev 26:16` I also will do this to you: I will even appoint over you terror, consumption, and the fever that shall *_consume_* the eyes and cause sorrow of heart. And you shall sow your seed in vain, for your enemies shall eat it.
* `Num 16:21` "Separate yourselves from among this congregation so that I may *_consume_* them in a moment."
* `Num 16:45` "Get away from among this congregation so that I may *_consume_* them as in a moment." And they fell upon their faces.
* `Num 25:11` "Phinehas, the son of Eleazar, the son of Aaron the priest, has turned my wrath away from the children of Israel (while he was zealous for my sake among them) so that I did not *_consume_* the children of Israel in my jealousy.
* `Deu 5:25` Now therefore, why should we die? For this great fire will *_consume_* us. If we hear the voice of the LORD our God anymore, then we shall die.
* `Deu 7:16` And you shall *_consume_* all the people which the LORD your God shall deliver to you. Your eye shall have no pity upon them, neither shall you serve their gods, for that will be a snare to you.
* `Deu 7:22` And the LORD your God will drive out those nations before you little by little. You may not *_consume_* them at once, lest the beasts of the field increase upon you.
* `Deu 28:38` "You shall carry much seed into the field and shall gather in little, for the locust shall *_consume_* it.
* `Deu 28:42` All your trees and fruit of your land the locust shall *_consume_*.
* `Deu 32:22` For a fire is kindled in my anger, and shall burn to the lowest hell, *_consume_* the earth with her increase, and set on fire the foundations of the mountains.
* `Jsh 24:20` If you forsake the LORD and serve strange gods, then he will turn and do you hurt and *_consume_* you, after he has done you good."
* `1Sa 2:33` And the man of yours, whom I shall not cut off from my altar, is to *_consume_* your eyes and to grieve your heart. And all the increase of your house shall die in the flower of their age.
* `2Ki 1:10` And Elijah answered and said to the captain of fifty, "If I am a man of God, then let fire come down from heaven and *_consume_* you and your fifty." And fire came down from heaven and consumed him and his fifty.
* `2Ki 1:12` And Elijah answered and said to them, "If I am a man of God, let fire come down from heaven and *_consume_* you and your fifty." And the fire of God came down from heaven and consumed him and his fifty.
* `2Ch 8:8` But of their children who were left after them in the land, whom the children of Israel did not *_consume_*—Solomon made them to pay tribute until this day.
* `Neh 9:31` Nevertheless, for your great mercies' sake you did not utterly *_consume_* them, nor forsake them, for you are a gracious and merciful God.
* `Est 9:24` Because Haman the son of Hammedatha, the Agagite, the enemy of all the Jews, had devised against the Jews to destroy them and had cast Pur (that is, the lot) to *_consume_* them and to destroy them.
* `Job 15:34` For the congregation of hypocrites shall be desolate, and fire shall *_consume_* the tabernacles of bribery.
* `Job 20:26` All darkness shall be hid in his secret places. A fire not blown shall *_consume_* him. It shall go ill with him who is left in his tabernacle.
* `Job 24:19` As drought and heat *_consume_* the snow-waters, so does the grave to those who have sinned.
* `Psa 37:20` But the wicked shall perish, and the enemies of the LORD shall be like the fat of lambs. They shall *_consume_*. Into smoke they shall *_consume_* away.
* `Psa 39:11` When you, with rebukes, correct man for iniquity, you make his beauty to *_consume_* away like a moth. Surely every man is vanity." [Selah.]
* `Psa 49:14` Like sheep they are laid in the grave. Death shall feed on them. The upright shall have dominion over them in the morning. Their beauty shall *_consume_* in the grave from their dwelling.
* `Psa 59:13` *_Consume_* them in wrath, *_consume_* them, so that they may not be. And let them know that God rules in Jacob to the ends of the earth. [Selah.]
* `Isa 7:20` In the same day the Lord will shave with a razor that is hired from beyond the river (namely, by the king of Assyria) the head and the hair of the feet. And it shall also *_consume_* the beard.
* `Isa 10:18` And it shall *_consume_* the glory of his forest and of his fruitful field, both soul and body, and they shall be as when a standard-bearer faints.
* `Isa 27:10` Yet the fortified city shall be desolate and the habitation forsaken and left like a wilderness. There the calf shall feed, and there he shall lie down and *_consume_* its branches.
* `Jer 8:13` "I will surely *_consume_* them," says the LORD. "There shall be no grapes on the vine nor figs on the fig-tree, and the leaf shall fade. And the things that I have given to them shall pass away from them."'"
* `Jer 14:12` When they fast, I will not hear their cry. And when they offer a burnt-offering and an oblation, I will not accept them. But I will *_consume_* them by the sword, by the famine, and by the pestilence."
* `Jer 49:27` "And I will kindle a fire in the wall of Damascus, and it shall *_consume_* the palaces of Ben-hadad."
* `Ezk 4:17` So that they may lack bread and water. And they will be astonished with one another and *_consume_* away for their iniquity."
* `Ezk 13:13` Therefore, thus says the Lord GOD: "I will even rend it with a stormy wind in my fury, and there shall be an overflowing shower in my anger and great hailstones in my fury to *_consume_* it.
* `Ezk 20:13` But the house of Israel rebelled against me in the wilderness. They did not walk in my statutes and they despised my judgments, which if a man does, he shall even live in them, and they greatly profaned my sabbaths. Then I said that I would pour out my fury upon them in the wilderness to *_consume_* them.
* `Ezk 21:28` "And you, son of man, prophesy and say, 'Thus says the Lord GOD concerning the Ammonites and concerning their reproach,' even say, 'The sword, the sword is drawn. For the slaughter it is furbished to *_consume_* because of the glittering—
* `Ezk 22:15` And I will scatter you among the heathen and disperse you in the countries, and I will *_consume_* your filthiness out of you.
* `Ezk 24:10` Heap on wood, kindle the fire, *_consume_* the flesh, spice it well, and let the bones be burned.
* `Ezk 35:12` And you shall know that I am the LORD and that I have heard all your blasphemies which you have spoken against the mountains of Israel, saying, 'They are laid desolate. They are given to us to *_consume_*.'
* `Dan 2:44` "And in the days of these kings the God of heaven shall set up a kingdom which shall never be destroyed. And the kingdom shall not be left to other people, but it shall break in pieces and *_consume_* all these kingdoms, and it shall stand forever.
* `Dan 7:26` But the judgment shall sit, and they shall take away his dominion to *_consume_* and to destroy it to the end.
* `Hos 11:6` And the sword shall abide on his cities, *_consume_* his branches, and devour them because of their own counsels.
* `Zph 1:2` "I will utterly *_consume_* all things from off the land," says the LORD.
* `Zph 1:3` "I will *_consume_* man and beast. I will *_consume_* the birds of the heaven, the fish of the sea, and the stumbling-blocks with the wicked. And I will cut off man from off the land," says the LORD.
* `Zch 5:4` I will bring it forth," says the LORD of hosts, "and it shall enter into the house of the thief and into the house of him who swears falsely by my name. And it shall remain in the midst of his house and shall *_consume_* it with its timber and its stones."
* `Zch 14:12` And this shall be the plague with which the LORD will smite all the people who have fought against Jerusalem: their flesh shall *_consume_* away while they stand upon their feet, their eyes shall *_consume_* away in their holes, and their tongue shall *_consume_* away in their mouth.
* `Luk 9:54` And when his disciples, James and John, saw this, they said, "Lord, do you wish that we command fire to come down from heaven and *_consume_* them, even as Elijah did?"
* `2Th 2:8` And then that Wicked One is revealed, whom the Lord will *_consume_* with the spirit of his mouth and will destroy with the brightness of his coming,

_51 verses containing CONSUME_

== CONSUMED

* `Gen 19:15` And when the morning arose, the angels hastened Lot, saying, "Arise, take your wife and your two daughters who are here, lest you be *_consumed_* in the iniquity of the city."
* `Gen 19:17` And it came to pass when they had brought them forth abroad, that he said, "Escape for your life. Do not look behind you, neither stay in all the plain. Escape to the mountain, lest you be *_consumed_*."
* `Gen 31:15` Are we not regarded by him as strangers? For he has sold us and has also quite *_consumed_* our money.
* `Gen 31:40` Thus I was: in the day the drought *_consumed_* me, and the frost by night, and my sleep departed from my eyes.
* `Gen 43:2` And it came to pass, when they had *_consumed_* the grain which they had brought from Egypt, their father said to them, "Go back, buy us a little food."
* `Exo 3:2` And the angel of the LORD appeared to him in a flame of fire out of the midst of a bush. And he looked, and behold, the bush burned with fire, and the bush was not *_consumed_*.
* `Exo 15:7` And in the greatness of your excellence you have overthrown those who rose up against you. You sent forth your wrath, which *_consumed_* them like stubble.
* `Exo 22:6` "If fire breaks out and catches in thorns and then stacks of grain, standing grain, or a field is *_consumed_*, he who kindled the fire shall surely make restitution.
* `Lev 6:10` And the priest shall put on his linen garment and put his linen breeches on his body. And he shall take up the ashes which the fire has *_consumed_* with the burnt-offering on the altar and put them beside the altar.
* `Lev 9:24` And a fire came out from before the LORD and *_consumed_* upon the altar the burnt-offering and the fat, which when all the people saw, they shouted and fell on their faces.
* `Num 11:1` And when the people complained, it displeased the LORD. And the LORD heard it and his anger was kindled, and the fire of the LORD burnt among them and *_consumed_* those who were in the uttermost parts of the camp.
* `Num 12:12` Do not let her be as one dead, of whom the flesh is half *_consumed_* at the time of his birth."
* `Num 14:35` I, the LORD, have spoken. I will surely do it to all this evil congregation who are gathered against me. In this wilderness they shall be *_consumed_*, and there they shall die.'"
* `Num 16:26` And he spoke to the congregation, saying, "Depart, I pray you, from the tents of these wicked men and touch nothing of theirs, lest you be *_consumed_* in all their sins."
* `Num 16:35` And a fire came out from the LORD and *_consumed_* the two hundred and fifty men who offered incense.
* `Num 17:13` Whoever approaches the tabernacle of the LORD shall die. Shall we be *_consumed_* with dying?"
* `Num 21:28` For a fire has gone out of Heshbon, a flame from the city of Sihon. It has *_consumed_* Ar of Moab and the lords of the high places of Arnon.
* `Num 32:13` And the LORD'S anger was kindled against Israel and he made them wander in the wilderness forty years until all the generation who had done evil in the sight of the LORD was *_consumed_*.
* `Deu 2:15` For indeed the hand of the LORD was against them, to destroy them from among the host until they were *_consumed_*.
* `Deu 2:16` "So it came to pass when all the men of war were *_consumed_* and dead from among the people,
* `Deu 28:21` The LORD shall make the pestilence cleave to you until he has *_consumed_* you from off the land where you go to possess it.
* `Jsh 5:6` For the children of Israel walked forty years in the wilderness until all the people who were men of war who came out of Egypt were *_consumed_* because they did not obey the voice of the LORD, to whom the LORD swore that he would not show them the land which the LORD swore to their fathers that he would give us, a land that flows with milk and honey.
* `Jsh 8:24` And it came to pass when Israel had made an end of slaying all the inhabitants of Ai in the field, in the wilderness in which they chased them, and when they had all fallen on the edge of the sword until they were *_consumed_*, that all the Israelites returned to Ai and smote it with the edge of the sword.
* `Jsh 10:20` And it came to pass when Joshua and the children of Israel had made an end of slaying them with a very great slaughter until they were *_consumed_*, that the rest who remained of them entered into fortified cities.
* `Jdg 6:21` Then the angel of the LORD put forth the end of the staff that was in his hand and touched the flesh and the unleavened cakes. And there rose fire out of the rock and *_consumed_* the flesh and the unleavened cakes. Then the angel of the LORD departed from his sight.
* `1Sa 12:25` But if you still do wickedly, you will be *_consumed_*—both you and your king."
* `1Sa 15:18` And the LORD sent you on a journey and said, 'Go, and utterly destroy the sinners the Amalekites and fight against them until they are *_consumed_*.'
* `2Sa 21:5` And they answered the king, "The man who *_consumed_* us and who devised against us that we should be destroyed from remaining within the borders of Israel,
* `2Sa 22:38` I have pursued my enemies and destroyed them, and did not turn back until I had *_consumed_* them.
* `2Sa 22:39` And I have *_consumed_* them and wounded them so that they could not arise. Indeed, they have fallen under my feet.
* `1Ki 18:38` Then the fire of the LORD fell and *_consumed_* the burnt-sacrifice, the wood, the stones, and the dust, and licked up the water that was in the trench.
* `1Ki 22:11` And Zedekiah the son of Chenaanah made him horns of iron. And he said, "Thus says the LORD: 'With these you shall push the Syrians until you have *_consumed_* them.'"
* `2Ki 1:10` And Elijah answered and said to the captain of fifty, "If I am a man of God, then let fire come down from heaven and consume you and your fifty." And fire came down from heaven and *_consumed_* him and his fifty.
* `2Ki 1:12` And Elijah answered and said to them, "If I am a man of God, let fire come down from heaven and consume you and your fifty." And the fire of God came down from heaven and *_consumed_* him and his fifty.
* `2Ki 7:13` And one of his servants answered and said, "Let some take, I pray you, five of the horses that remain, which are left in the city (behold, they are like all the multitude of Israel who are left in it, behold, I say, they are even like all the multitude of the Israelites who are *_consumed_*), and let us send and see."
* `2Ki 13:17` And he said, "Open the window eastward." And he opened it. Then Elisha said, "Shoot." And he shot. And he said, "The arrow of the LORD'S deliverance, and the arrow of deliverance from Syria, for you shall smite the Syrians in Aphek until you have *_consumed_* them."
* `2Ki 13:19` And the man of God was angry with him and said, "You should have smitten five or six times. Then you would have smitten Syria until you had *_consumed_* it, whereas now you shall smite Syria only three times."
* `2Ch 7:1` Now when Solomon had made an end of praying, the fire came down from heaven and *_consumed_* the burnt-offering and the sacrifices. And the glory of the LORD filled the house.
* `2Ch 18:10` And Zedekiah the son of Chenaanah had made him horns of iron and said, "Thus says the LORD: 'With these you shall push Syria until they are *_consumed_*.'"
* `Ezr 9:14` Should we again break your commandments and intermarry with the people of these abominations? Would you not be angry with us until you had *_consumed_* us so that there should be no remnant nor escaping?
* `Neh 2:3` And said to the king, "Let the king live forever. Why should my countenance not be sad when the city, the place of my fathers' sepulchers, lies waste and its gates are *_consumed_* with fire?"
* `Neh 2:13` And I went out by night by the gate of the valley, even before the dragon-well and to the dung-port, and viewed the walls of Jerusalem, which were broken down and their gates were *_consumed_* with fire.
* `Job 1:16` While he was still speaking, another also came, saying, "The fire of God has fallen from heaven and has burned up the sheep and the servants and *_consumed_* them, and only I have escaped alone to tell you."
* `Job 4:9` By the blast of God they perish, and by the breath of his nostrils they are *_consumed_*.
* `Job 6:17` In the time when they become warm, they vanish. When it is hot, they are *_consumed_* out of their place.
* `Job 7:9` As the cloud is *_consumed_* and vanishes away, so he who goes down to the grave shall come up no more.
* `Job 19:27` Whom I shall see for myself, and my eyes shall behold, and not another. My heart is *_consumed_* within me.
* `Job 33:21` His flesh is *_consumed_* away so that it cannot be seen. And his bones that were not seen stick out.
* `Psa 6:7` My eye is *_consumed_* because of grief. It grows old because of all my enemies.
* `Psa 18:37` I have pursued my enemies and overtaken them, neither did I turn back until they were *_consumed_*.
* `Psa 31:9` Have mercy upon me, O LORD, for I am in trouble. My eye is *_consumed_* with grief, even my soul and my belly.
* `Psa 31:10` For my life is spent with grief and my years with sighing. My strength fails because of my iniquity and my bones are *_consumed_*.
* `Psa 39:10` Remove your stroke away from me. I am *_consumed_* by the blow of your hand.
* `Psa 71:13` Let them be confounded and *_consumed_* who are adversaries to my soul. Let them be covered with reproach and dishonor who seek my hurt.
* `Psa 73:19` How they are brought into desolation in a moment! They are utterly *_consumed_* with terrors.
* `Psa 78:33` Therefore, he *_consumed_* their days in vanity and their years in trouble.
* `Psa 78:63` The fire *_consumed_* their young men, and their young women were not given to marriage.
* `Psa 90:7` For we are *_consumed_* by your anger, and by your wrath we are troubled.
* `Psa 102:3` For my days are *_consumed_* like smoke, and my bones are burned like a hearth.
* `Psa 104:35` Let sinners be *_consumed_* out of the earth, and let the wicked be no more. Bless the LORD, O my soul. Praise the LORD.
* `Psa 119:87` They had almost *_consumed_* me upon earth, but I did not forsake your precepts.
* `Psa 119:139` My zeal has *_consumed_* me because my enemies have forgotten your words.
* `Pro 5:11` And you mourn at the last when your flesh and your body are *_consumed_*
* `Isa 1:28` And the destruction of the transgressors and of the sinners shall be together, and those who forsake the LORD shall be *_consumed_*.
* `Isa 16:4` Let my outcasts dwell with you, Moab. Be a covert to them from the face of the destroyer. For the extortioner is at an end. Devastation ceases. The oppressors are *_consumed_* out of the land.
* `Isa 29:20` For the terrible one is brought to nothing and the scoffer is *_consumed_*, and all who watch for iniquity are cut off,
* `Isa 64:7` And there is no one who calls upon your name, who stirs up himself to take hold of you, for you have hid your face from us and have *_consumed_* us because of our iniquities.
* `Isa 66:17` "Those who sanctify themselves and purify themselves in the gardens, following one in the midst, eating swine's flesh, abominable things, and the mouse, they shall be *_consumed_* together," says the LORD.
* `Jer 5:3` O LORD, are your eyes not upon the truth? You have stricken them, but they have not grieved. You have *_consumed_* them, but they have refused to receive correction. They have made their faces harder than a rock. They have refused to return.
* `Jer 6:29` The bellows is burned. The lead is *_consumed_* by the fire. The founder melts in vain, for the wicked are not plucked away.
* `Jer 9:16` I will also scatter them among the heathen, whom neither they nor their fathers have known. And I will send a sword after them until I have *_consumed_* them."
* `Jer 10:25` Pour out your fury upon the heathen who do not know you and upon the families who do not call on your name, for they have eaten up Jacob. They have devoured him and *_consumed_* him, and have made his habitation desolate.
* `Jer 12:4` How long shall the land mourn and the herbs of every field wither for the wickedness of those who dwell therein? The beasts are *_consumed_*, and also the birds, because they said, "He will not see our last end."
* `Jer 14:15` Therefore, thus says the LORD concerning the prophets who prophesy in my name, and I did not send them, yet they say, 'Sword and famine shall not be in this land': 'By sword and famine those prophets shall be *_consumed_*.
* `Jer 16:4` "They shall die by grievous deaths. They shall not be lamented, neither shall they be buried, but they shall be like dung upon the face of the earth. And they shall be *_consumed_* by the sword and by famine, and their carcasses shall be food for the birds of heaven and for the beasts of the earth."
* `Jer 20:18` Why was I brought into the world to see labor and sorrow so that my days should be *_consumed_* with shame?
* `Jer 24:10` And I will send the sword, the famine, and the pestilence among them until they are *_consumed_* from off the land that I gave to them and to their fathers.'"
* `Jer 27:8` 'And it shall come to pass, that the nation and kingdom which will not serve the same Nebuchadnezzar king of Babylon, and which will not put their neck under the yoke of the king of Babylon, that nation I will punish,' says the LORD, 'with the sword, with the famine, and with the pestilence until I have *_consumed_* them by his hand.
* `Jer 36:23` And it came to pass, that when Jehudi had read three or four leaves, he cut it with the scribe's pen-knife and cast it into the fire that was on the hearth until all the scroll was *_consumed_* in the fire that was on the hearth.
* `Jer 37:21` Then Zedekiah the king commanded that they should commit Jeremiah into the court of the prison and that they should give him a piece of bread daily out of the baker's street until all the bread in the city was *_consumed_*. Thus Jeremiah remained in the court of the prison.
* `Jer 44:12` And I will take the remnant of Judah who have set their faces to go into the land of Egypt to sojourn there, and they shall all be *_consumed_* and fall in the land of Egypt. They shall even be *_consumed_* by the sword and by the famine. They shall die, from the least even to the greatest, by the sword and by the famine. And they shall be an object of horror, an astonishment, a curse, and a reproach.
* `Jer 44:18` But since we ceased to burn incense to the queen of heaven and to pour out drink-offerings to her, we have lacked all things and have been *_consumed_* by the sword and by the famine.
* `Jer 44:27` Behold, I will watch over them for evil and not for good. And all the men of Judah who are in the land of Egypt shall be *_consumed_* by the sword and by the famine until there is an end of them.
* `Jer 49:37` For I will cause Elam to be dismayed before their enemies and before those who seek their life. And I will bring evil upon them, even my fierce anger," says the LORD, "and I will send the sword after them until I have *_consumed_* them.
* `Lam 2:22` [TAV] You have called, as in the day of a solemn assembly, my terrors on every side. And in the day of the LORD'S anger no one escaped or remained. Those whom I have swaddled and brought up, my enemy has *_consumed_*.
* `Lam 3:22` [HET] It is because of the LORD'S mercies that we are not *_consumed_*, because his compassions do not fail.
* `Ezk 5:12` A third part of you shall die with the pestilence, and with famine they shall be *_consumed_* in the midst of you. And a third part shall fall by the sword around you. And I will scatter a third part into all the winds and draw out a sword after them.
* `Ezk 13:14` Thus I will break down the wall that you have daubed with untempered mortar and bring it down to the ground so that its foundation shall be made bare. It shall fall, and you shall be *_consumed_* in the midst of it. And you shall know that I am the LORD.
* `Ezk 19:12` But she was plucked up in fury, she was cast down to the ground, and the east wind dried up her fruit. Her strong rods were broken and withered. The fire *_consumed_* them.
* `Ezk 22:31` Therefore, I have poured out my indignation upon them. I have *_consumed_* them with the fire of my wrath. Their own way I have recompensed upon their heads," says the Lord GOD.
* `Ezk 24:11` Then set it empty upon its coals so that its brass may be hot and may burn, and that its filthiness may be melted in it so that its scum may be *_consumed_*.
* `Ezk 34:29` And I will raise up for them a plant of renown, and they shall no longer be *_consumed_* with hunger in the land, neither bear the shame of the heathen anymore.
* `Ezk 43:8` In their setting of their threshold by my thresholds, and their post by my posts, and the wall between me and them, they have even defiled my holy name by their abominations that they have committed; therefore, I have *_consumed_* them in my anger.
* `Ezk 47:12` And by the river upon its bank, on this side and on that side, all trees for food shall grow, whose leaf shall not fade, neither shall their fruit be *_consumed_*. They shall bring forth new fruit according to their months, because their waters issued out of the sanctuary. And their fruit shall be for food and their leaf for medicine."
* `Dan 11:16` But he who comes against him shall do according to his own will, and no one shall stand before him. And he shall stand in the glorious land, which by his hand shall be *_consumed_*.
* `Joe 2:25` "And I will restore to you the years that the swarming-locust, the licking-locust, the ravaging-locust, and the cutting-locust *_consumed_*—my great army which I sent among you.
* `Mal 3:6` "For I am the LORD and I do not change; therefore, you sons of Jacob are not *_consumed_*.
* `Gal 5:15` But if you bite and devour one another, take heed that you are not *_consumed_* by one another.

_98 verses containing CONSUMED_

== CONSUMES

* `Job 22:20` 'Surely our substance is not cut down, and the fire *_consumes_* their remnant.'
* `Job 31:12` For it is a fire that *_consumes_* to destruction and would root out all my increase.
* `Isa 5:24` Therefore, as the fire devours the stubble and the flame *_consumes_* the chaff, so their root shall be as rottenness and their blossom shall go up like dust, because they have cast away the law of the LORD of hosts and despised the word of the Holy One of Israel.

_3 verses containing CONSUMES_

== CONSUMING

* `Lev 11:22` Even these of them you may eat: the swarming-locust after its kind, the *_consuming_*-locust after its kind, the cricket after its kind, and the locust after its kind.
* `Deu 4:24` For the LORD your God is a *_consuming_* fire, even a jealous God.
* `Deu 9:3` Understand therefore this day, that the LORD your God is he who goes over before you as a *_consuming_* fire. He shall destroy them and he shall bring them down before your face. So you shall drive them out and destroy them quickly, as the LORD has said to you.
* `Heb 12:29` For "our God is a *_consuming_* fire."

_4 verses containing CONSUMING_

== CONSUMING-LOCUST

* `Lev 11:22` Even these of them you may eat: the swarming-locust after its kind, the *_consuming-locust_* after its kind, the cricket after its kind, and the locust after its kind.

_1 verse containing CONSUMING-LOCUST_

== CONSUMMATION

* `Dan 9:27` And he shall confirm the covenant with many for one week. And in the midst of the week he shall cause the sacrifice and the oblation to cease. And on the wing of abominations, he shall come to make it desolate, even until the *_consummation_*, and that which is determined shall be poured upon the desolate."

_1 verse containing CONSUMMATION_

== CONSUMPTION

* `Lev 26:16` I also will do this to you: I will even appoint over you terror, *_consumption_*, and the fever that shall consume the eyes and cause sorrow of heart. And you shall sow your seed in vain, for your enemies shall eat it.
* `Deu 28:22` The LORD shall smite you with a *_consumption_*, with a fever, with an inflammation, with an extreme burning, with the sword, with blight, and with mildew. And they shall pursue you until you perish.
* `Isa 10:22` For though your people Israel are like the sand of the sea, yet a remnant of them shall return. The *_consumption_* decreed shall overflow with righteousness.
* `Isa 10:23` For the Lord GOD of hosts will make a *_consumption_*, even determined, in the midst of all the land.
* `Isa 28:22` Now therefore, do not be mockers, lest your bonds be made strong, for I have heard from the Lord GOD of hosts a *_consumption_*, even determined upon the whole earth.

_5 verses containing CONSUMPTION_

== CONTAIN

* `1Ki 8:27` "But will God indeed dwell on the earth? Behold, the heaven and heaven of heavens cannot *_contain_* you. How much less this house that I have built?
* `1Ki 18:32` And with the stones he built an altar in the name of the LORD. And he made a trench around the altar, as great as would *_contain_* two measures of seed.
* `2Ch 2:6` But who is able to build him a house, seeing the heaven and heaven of heavens cannot *_contain_* him? Who am I then that I should build him a house, except only to burn sacrifice before him?
* `2Ch 6:18` "But will God indeed dwell with men on the earth? Behold, heaven and the heaven of heavens cannot *_contain_* you. How much less this house which I have built!
* `Ezk 45:11` The ephah and the bath shall be of one measure, so that the bath may *_contain_* the tenth part of a homer and the ephah the tenth part of a homer. Its measure shall be after the homer.
* `Jhn 21:25` And there are also many other things which Jesus did, which, if they should all be written, I suppose that even the world itself could not *_contain_* the books that would be written. Amen.
* `1Co 7:9` But if they cannot *_contain_*, let them marry, for it is better to marry than to burn.

_7 verses containing CONTAIN_

== CONTAINED

* `1Ki 7:26` And it was a hand-breadth thick, and its brim was wrought like the brim of a cup, with flowers of lilies. It *_contained_* two thousand baths.
* `1Ki 7:38` Then he made ten basins of brass. One basin *_contained_* forty baths, and every basin was four cubits. And upon each of the ten bases was one basin.
* `Rom 2:14` For when the Gentiles, who do not have the law, do by nature the things *_contained_* in the law, these not having the law are a law to themselves,
* `Eph 2:15` Having abolished in his flesh the enmity, even the law of commandments *_contained_* in ordinances, to make in himself one new man of the two, so making peace,
* `1Pe 2:6` Therefore, it is also *_contained_* in the Scripture, "Behold, I lay in Zion a chief corner-stone, elect, precious. And he who believes in him shall not be confounded."

_5 verses containing CONTAINED_

== CONTAINING

* `Jhn 2:6` And six water-pots of stone were set there, after the manner of the purifying of the Jews, *_containing_* two or three measures apiece.

_1 verse containing CONTAINING_

== CONTAINS

* `Deu 10:14` Behold, the heaven and the heaven of heavens belongs to the LORD your God, and also the earth, with all that it *_contains_*.
* `Ezk 23:32` "Thus says the Lord GOD: 'You shall drink from your sister's cup deep and large. You shall be treated with scorn and had in derision. It *_contains_* much.

_2 verses containing CONTAINS_

== CONTEMPT

* `Est 1:18` This day, the ladies of Persia and Media who have heard of the deed of the queen will say the same thing to all the king's princes. Thus there will arise too much *_contempt_* and wrath.
* `Job 12:21` He pours *_contempt_* upon princes and weakens the strength of the mighty.
* `Job 31:34` Because I feared a great multitude, and the *_contempt_* of families terrified me, so that I kept silence and did not go out of the door,
* `Psa 107:40` He pours *_contempt_* upon princes and causes them to wander in the wilderness where there is no way.
* `Psa 119:22` Remove from me reproach and *_contempt_*, for I have kept your testimonies.
* `Psa 123:3` Have mercy upon us, O LORD, have mercy upon us, for we are exceedingly filled with *_contempt_*.
* `Psa 123:4` Our soul is exceedingly filled with the scorning of those who are at ease and with the *_contempt_* of the proud.
* `Pro 18:3` When the wicked comes, then *_contempt_* also comes, and with ignominy comes reproach.
* `Isa 9:1` Nevertheless, there shall be no more gloom to her who was in anguish. In the former time, he brought into *_contempt_* the land of Zebulun and the land of Naphtali, but in the latter time, he has made glorious the way of the sea, the land beyond the Jordan, Galilee of the nations.
* `Isa 23:9` The LORD of hosts has purposed it to stain the pride of all glory and to bring into *_contempt_* all the honorable of the earth.
* `Ezk 25:6` For thus says the Lord GOD: "Because you have clapped your hands and stomped your feet and rejoiced in heart with all your *_contempt_* against the land of Israel,
* `Dan 12:2` And many of those who sleep in the dust of the earth shall awake, some to everlasting life, and some to shame and everlasting *_contempt_*.

_12 verses containing CONTEMPT_

== CONTEMPTIBLE

* `Est 1:17` For this deed of the queen will come abroad to all women to make their husbands *_contemptible_* in their eyes when they say, 'King Ahasuerus commanded Vashti the queen to be brought in before him, but she did not come.'
* `Mal 1:7` "You offer polluted bread upon my altar." But you say, "In what have we polluted you?" In that you say, "The table of the LORD is *_contemptible_*."
* `Mal 1:12` "But you have profaned it, in that you say, 'The table of the LORD is polluted, and its fruit, even his provision, is *_contemptible_*.'
* `Mal 2:9` "Therefore, I have also made you *_contemptible_* and base before all the people, according as you have not kept my ways, but have been partial in the law."
* `2Co 10:10` "For his letters," they say, "are weighty and powerful, but his bodily presence is weak and his speech *_contemptible_*."

_5 verses containing CONTEMPTIBLE_

== CONTEMPTUOUSLY

* `Psa 31:18` Let the lying lips be put to silence, which speak grievous things proudly and *_contemptuously_* against the righteous.

_1 verse containing CONTEMPTUOUSLY_

== CONTEND

* `Gen 26:22` And he departed from there and dug another well. And for that they did not *_contend_*. And he called its name Rehoboth and he said, "For now the LORD has made room for us, and we shall be fruitful in the land."
* `Gen 45:24` So he sent his brothers away and they departed. And he said to them, "See that you do not *_contend_* on the way."
* `Exo 21:18` "And if men *_contend_* together, and one smites another with a stone or with his fist, and he does not die but remains in his bed,
* `Exo 21:22` "If men *_contend_* and hurt a woman with child so that her fruit departs from her, and yet no mischief follows, he shall surely be punished according as the woman's husband will lay upon him. And he shall pay as the judges determine.
* `Deu 2:9` And the LORD said to me, 'Do not distress the Moabites, neither *_contend_* with them in battle, for I will not give you any of their land for a possession, because I have given Ar to the children of Lot for a possession.'
* `Deu 2:24` 'Arise, take your journey and pass over the Arnon River. Behold, I have given into your hand Sihon the Amorite, king of Heshbon, and his land. Begin to possess it and *_contend_* with him in battle.
* `2Sa 22:27` With the pure you will show yourself pure, and with the perverse you will *_contend_*.
* `Job 9:3` If he will *_contend_* with him, he cannot answer him one of a thousand.
* `Job 10:2` I will say to God, 'Do not condemn me. Show me why you *_contend_* with me.
* `Job 13:8` Will you accept his person? Will you *_contend_* for God?
* `Psa 18:26` With the pure you will show yourself pure. With the perverse you will *_contend_*.
* `Pro 28:4` Those who forsake the law praise the wicked, but those who keep the law *_contend_* with them.
* `Ecc 6:10` That which has been is named already, and it is known what man is, for he cannot *_contend_* with him who is mightier than he is.
* `Isa 41:11` Behold, all those who were incensed against you shall be ashamed and confounded. They shall be as nothing. And those who *_contend_* with you shall perish.
* `Isa 45:9` Woe to him who contends with his Maker! Let the potsherd *_contend_* with the potsherds of the earth. Shall the clay say to him who fashions it, 'What are you making?' Or shall your work say, 'He has no hands'?
* `Isa 49:25` But thus says the LORD: "Even the captives of the mighty shall be taken away, and the prey of the terrible shall be delivered, for I will *_contend_* with him who contends with you, and I will save your children.
* `Isa 50:8` He is near who justifies me. Who will *_contend_* with me? Let us stand together. Who is my adversary? Let him come near to me.
* `Isa 57:16` For I will not *_contend_* forever, neither will I always be angry, for the spirit would fail before me—the souls which I have made.
* `Jer 12:5` "If you have run with the footmen, and they have wearied you, then how can you *_contend_* with horses? And if in the land of peace, in which you have trusted, they wearied you, then how will you do in the swelling of the Jordan?
* `Jer 18:19` Give heed to me, O LORD, and listen to the voice of those who *_contend_* with me.
* `Hos 4:4` Yet let no man *_contend_* nor reprove another, for your people are as those who *_contend_* with the priest.
* `Amo 7:4` Thus the Lord GOD has shown to me, and behold, the Lord GOD called to *_contend_* by fire, and it devoured the great deep and ate up a part.
* `Mic 6:1` Hear now what the LORD says. "Arise, *_contend_* before the mountains and let the hills hear your voice.
* `Mth 12:19` He shall not *_contend_*, nor cry, neither shall any man hear his voice in the streets.
* `2Ti 2:14` Put others in remembrance of these things, charging them before the Lord that they do not *_contend_* about words to no profit, but to the subverting of the hearers.
* `2Ti 2:24` And the servant of the Lord must not *_contend_*, but be gentle to all men, apt to teach, patient,
* `Jde 1:3` Beloved, when I gave all diligence to write to you concerning the common salvation, it was needful for me to write to you and exhort you that you should earnestly *_contend_* for the faith, which was once delivered to the saints.

_27 verses containing CONTEND_

== CONTENDED

* `Gen 26:20` And the herdsmen of Gerar *_contended_* with Isaac's herdsmen, saying, "The water is ours." And he called the name of the well Esek because they strove with him.
* `Gen 26:21` And they dug another well and *_contended_* for that also, and he called its name Sitnah.
* `Exo 17:2` Therefore, the people *_contended_* with Moses and said, "Give us water so that we may drink." And Moses said to them, "Why do you chide with me? Why do you test the LORD?"
* `Neh 13:11` Then I *_contended_* with the rulers, and said, "Why is the house of God forsaken?" Then I assembled them and set them in their place.
* `Neh 13:17` Then I *_contended_* with the nobles of Judah, and said to them, "What evil thing is this that you do, profaning the sabbath day?
* `Neh 13:25` And I *_contended_* with them, cursed them, smote some of them, plucked off their hair, and made them swear by God, saying, "You shall not give your daughters to their sons, nor take their daughters to your sons or for yourselves.
* `Job 31:13` If I despised the cause of my man-servant or of my woman-servant when they *_contended_* with me,
* `Isa 41:12` You shall seek them and shall not find them, even those who *_contended_* with you. Those who war against you shall be as nothing, as a thing that does not exist.
* `Jhn 6:52` The Jews therefore *_contended_* among themselves, saying, "How can this man give us his flesh to eat?"
* `Act 11:2` And when Peter had come to Jerusalem, those who were of the circumcision *_contended_* with him,
* `Act 23:9` And there arose a great cry. And the scribes who were from the Pharisees' part arose and *_contended_*, saying, "We find no evil in this man. But if a spirit or an angel has spoken to him, let us not fight against God."

_11 verses containing CONTENDED_

== CONTENDING

* `Act 7:26` And the next day he showed himself to them as they were *_contending_* and would have constrained them to be at peace again, saying, 'Sirs, you are brothers. Why do you do wrong to one another?'
* `Jde 1:9` Yet Michael the archangel, when *_contending_* with the devil and disputing about the body of Moses, did not dare bring against him a railing accusation, but said, "May the Lord rebuke you."

_2 verses containing CONTENDING_

== CONTENDS

* `Job 40:2` "Shall he who *_contends_* with the Almighty instruct him? He who reproves God, let him answer it."
* `Pro 29:9` If a wise man *_contends_* with a foolish man, whether he rages or laughs, there is no rest.
* `Isa 45:9` Woe to him who *_contends_* with his Maker! Let the potsherd contend with the potsherds of the earth. Shall the clay say to him who fashions it, 'What are you making?' Or shall your work say, 'He has no hands'?
* `Isa 49:25` But thus says the LORD: "Even the captives of the mighty shall be taken away, and the prey of the terrible shall be delivered, for I will contend with him who *_contends_* with you, and I will save your children.

_4 verses containing CONTENDS_

== CONTENT

* `Gen 37:27` Come, and let us sell him to the Ishmaelites, and do not let our hand be upon him, for he is our brother, our flesh." And his brothers were *_content_*.
* `Exo 2:21` And Moses was *_content_* to dwell with the man. And he gave Zipporah his daughter to Moses.
* `Lev 10:20` And when Moses heard that, he was *_content_*.
* `Jsh 7:7` And Joshua said, "Alas, O Lord GOD, why have you at all brought this people over the Jordan to deliver us into the hand of the Amorites to destroy us? O that we had been *_content_* and dwelt on the other side of the Jordan.
* `Jdg 17:11` And the Levite was *_content_* to dwell with the man, and the young man became like one of his sons to him.
* `Jdg 19:6` And the both of them sat down and ate and drank together, for the young woman's father had said to the man, "Be *_content_*, I pray you, and stay all night, and let your heart be merry."
* `2Ki 5:23` And Naaman said, "Be *_content_*, take two talents." And he urged him, and bound two talents of silver in two bags with two changes of garments and laid them upon two of his servants. And they bore them before him.
* `2Ki 6:3` And someone said, "Be *_content_*, I pray you, and go with your servants." And he answered, "I will go."
* `Job 6:28` Now therefore, be *_content_*, look upon me, for it is evident to you if I lie.
* `Pro 6:35` He will not regard any ransom, neither will he rest *_content_*, though you give many gifts.
* `Mrk 15:15` And so Pilate, willing to *_content_* the people, released Barabbas to them, and having scourged Jesus, delivered him to be crucified.
* `Luk 3:14` And the soldiers likewise asked him, saying, "And what shall we do?" And he said to them, "Do violence to no man, neither accuse any falsely, and be *_content_* with your wages."
* `Phl 4:11` It is not that I speak from being in need. For I have learned, in whatever state I am, to be *_content_* with that.
* `1Ti 6:8` And having food and clothing, with these let us be *_content_*.
* `Heb 13:5` Let your manner of life be without covetousness, and be *_content_* with such things as you have, for he has said, "I will never leave you, nor forsake you,"
* `3Jn 1:10` Therefore, if I come, I will remember his deeds which he does, prating against us with malicious words. And not *_content_* with that, he himself does not receive the brothers and forbids those who would and casts them out of the church.

_16 verses containing CONTENT_

== CONTENTION

* `Pro 13:10` Only by pride comes *_contention_*, but with the well-advised is wisdom.
* `Pro 17:14` The beginning of strife is like when one lets out water; therefore, withdraw from *_contention_* before it is meddled with.
* `Pro 18:6` A fool's lips enter into *_contention_*, and his mouth calls for strokes.
* `Pro 22:10` Cast out the scorner and *_contention_* shall end, even strife and reproach shall cease.
* `Jer 15:10` Woe is me, my mother, that you have borne me, a man of strife and a man of *_contention_* to the whole earth! I have neither lent on usury, nor have men lent to me on usury, yet every one of them curses me.
* `Hab 1:3` Why do you show me iniquity and cause me to behold grievance? For devastation and violence are before me. And there is strife, and *_contention_* rises up.
* `Act 15:39` And the *_contention_* was so sharp between them that they departed, separating one from the other. And so Barnabas took Mark and sailed to Cyprus.
* `Phl 1:16` The former preach Christ from *_contention_*, not sincerely, supposing to add affliction to my bonds,
* `1Th 2:2` But even after we had suffered before and were shamefully treated at Phillippi, as you know, we were bold in our God to speak to you the gospel of God with much *_contention_*.

_9 verses containing CONTENTION_

== CONTENTIONS

* `Pro 18:18` The lot causes *_contentions_* to cease and parts between the mighty.
* `Pro 18:19` A brother offended is harder to be won than a strong city, and their *_contentions_* are like the bars of a castle.
* `Pro 19:13` A foolish son is the calamity of his father, and the *_contentions_* of a wife are a continual dropping.
* `Pro 23:29` Who has woe? Who has sorrow? Who has *_contentions_*? Who has babbling? Who has wounds without cause? Who has redness of eyes?
* `1Co 1:11` For it has been declared to me concerning you, my brothers, by those who are of the house of Chloe, that there are *_contentions_* among you.
* `2Ti 2:23` But avoid foolish and unlearned questions, knowing that they engender *_contentions_*.
* `Tit 3:9` But avoid foolish questions, genealogies, *_contentions_*, and strivings about the law, for they are unprofitable and vain.

_7 verses containing CONTENTIONS_

== CONTENTIOUS

* `Pro 21:19` It is better to dwell in the wilderness than with a *_contentious_* and angry woman.
* `Pro 26:21` As coals are to burning coals and wood to fire, so is a *_contentious_* man to kindle strife.
* `Pro 27:15` A continual dropping on a very rainy day and a *_contentious_* woman are alike.
* `Rom 2:8` But to those who are *_contentious_* and do not obey the truth, but obey unrighteousness, he will give indignation and wrath.
* `1Co 11:16` But if any man seems to be *_contentious_*, we have no such custom, neither do the churches of God.

_5 verses containing CONTENTIOUS_

== CONTENTMENT

* `1Ti 6:6` But godliness with *_contentment_* is great gain.

_1 verse containing CONTENTMENT_

== CONTINUAL

* `Exo 29:42` This shall be a *_continual_* burnt-offering throughout your generations at the door of the Tabernacle of the Congregation before the LORD, where I will meet you to speak there to you.
* `Num 4:7` And upon the table of show-bread they shall spread a cloth of blue and put on it the dishes, the spoons, the bowls, and covers to cover with. And the *_continual_* bread shall be upon it.
* `Num 28:3` And you shall say to them, 'This is the offering made by fire which you shall offer to the LORD: two lambs of the first year without spot day by day for a *_continual_* burnt-offering,
* `Num 28:6` It is a *_continual_* burnt-offering, which was ordained at mount Sinai for a sweet savor, a sacrifice made by fire to the LORD;
* `Num 28:10` This is the burnt-offering of every sabbath, besides the *_continual_* burnt-offering and its drink-offering.
* `Num 28:15` And one kid of the goats for a sin-offering to the LORD shall be offered, besides the *_continual_* burnt-offering and its drink-offering.
* `Num 28:23` You shall offer these besides the burnt-offering in the morning, which is for a *_continual_* burnt-offering.
* `Num 28:24` After this manner you shall offer daily, throughout the seven days, the food of the sacrifice made by fire, a sweet savor to the LORD. It shall be offered besides the *_continual_* burnt-offering and its drink-offering.
* `Num 28:31` You shall offer them besides the *_continual_* burnt-offering and its food-offering (they shall be to you without blemish) and their drink-offerings.'"
* `Num 29:11` One kid of the goats for a sin-offering, besides the sin-offering of atonement, the *_continual_* burnt-offering and its food-offering, and their drink-offerings.
* `Num 29:16` And one kid of the goats for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `Num 29:19` And one kid of the goats for a sin-offering besides the *_continual_* burnt-offering, its food-offering, and their drink-offerings.
* `Num 29:22` And one goat for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `Num 29:25` And one kid of the goats for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `Num 29:28` And one goat for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `Num 29:31` And one goat for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `Num 29:34` And one goat for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `Num 29:38` And one goat for a sin-offering, besides the *_continual_* burnt-offering, its food-offering, and its drink-offering.
* `2Ki 25:30` And his allowance was a *_continual_* allowance given to him by the king, a daily rate for every day, all the days of his life.
* `2Ch 2:4` Behold, I build a house to the name of the LORD my God to dedicate it to him, to burn before him sweet incense, for the *_continual_* show-bread and for the burnt-offerings morning and evening, on the sabbaths, on the new moons, and on the solemn feasts of the LORD our God. This is an ordinance forever to Israel.
* `Ezr 3:5` And afterward, the *_continual_* burnt-offering, the offerings of the new moons and of all the set feasts of the LORD that were consecrated, and those of everyone who willingly offered a voluntary-offering to the LORD.
* `Neh 10:33` For the show-bread, for the *_continual_* food-offering, for the *_continual_* burnt-offering, for the sabbaths, for the new moons, for the set feasts, for the holy things, and for the sin-offerings to make an atonement for Israel, and for all the work of the house of our God.
* `Pro 15:15` All the days of the afflicted are evil, but he who is of a merry heart has a *_continual_* feast.
* `Pro 19:13` A foolish son is the calamity of his father, and the contentions of a wife are a *_continual_* dropping.
* `Pro 27:15` A *_continual_* dropping on a very rainy day and a contentious woman are alike.
* `Isa 14:6` He who smote the people in wrath with a *_continual_* stroke, he who ruled the nations in anger is persecuted, and no one hinders.
* `Jer 20:8` For as often as I speak, I cry out. I proclaim, "Violence and destruction," because the word of the LORD has become to me a *_continual_* reproach and derision.
* `Jer 48:5` For in the ascent of Luhith *_continual_* weeping shall go up. For in the descent of Horonaim the enemies have heard a cry of destruction.
* `Jer 52:34` And for his food there was a *_continual_* diet given to him by the king of Babylon, every day a portion until the day of his death, all the days of his life.
* `Ezk 39:14` "And they shall sever out men of *_continual_* employment, passing through the land to bury with the passengers those who remain upon the face of the earth to cleanse it. After the end of seven months they shall search.
* `Ezk 46:15` Thus they shall prepare the lamb, the food-offering, and the oil every morning for a *_continual_* burnt-offering."
* `Luk 18:5` Yet because this widow troubles me, I will avenge her, lest by her *_continual_* coming she weary me.'"
* `Rom 9:2` That I have great heaviness and *_continual_* sorrow in my heart.

_33 verses containing CONTINUAL_

== CONTINUALLY

* `Gen 6:5` And GOD saw that the wickedness of man was great in the earth, and that every imagination of the thoughts of his heart was only evil *_continually_*.
* `Gen 8:3` And the waters returned from off the earth *_continually_*. And after the end of the hundred and fifty days the waters were abated.
* `Gen 8:5` And the waters decreased *_continually_* until the tenth month. In the tenth month, on the first day of the month, the tops of the mountains were seen.
* `Exo 28:29` And Aaron shall bear the names of the children of Israel in the breast-plate of judgment upon his heart when he enters into the holy place for a memorial before the LORD *_continually_*.
* `Exo 28:30` And you shall put in the breast-plate of judgment the Urim and the Thummim, and they shall be upon Aaron's heart when he goes in before the LORD. And Aaron shall bear the judgment of the children of Israel upon his heart before the LORD *_continually_*.
* `Exo 29:38` "Now this is that which you shall offer upon the altar: two lambs of the first year, day by day *_continually_*.
* `Lev 6:13` The fire shall *_continually_* be burning upon the altar. It shall never go out.
* `Lev 24:2` "Command the children of Israel that they bring to you pure olive oil beaten for the light to cause the lamps to burn *_continually_*.
* `Lev 24:3` Outside the veil of the testimony, in the Tabernacle of the Congregation, Aaron shall order it from the evening to the morning before the LORD *_continually_*. It shall be a statute forever in your generations.
* `Lev 24:4` You shall order the lamps upon the pure candlestick before the LORD *_continually_*.
* `Lev 24:8` Every sabbath he shall set it in order before the LORD *_continually_*, being taken from the children of Israel by an everlasting covenant.
* `Jsh 6:13` And seven priests bearing seven trumpets of rams' horns before the ark of the LORD went on *_continually_* and blew with the trumpets. And the armed men went before them, but the rear-guard came after the ark of the LORD, the priests going on and blowing with the trumpets.
* `1Sa 18:29` And Saul was even more afraid of David. And Saul became David's enemy *_continually_*.
* `2Sa 9:7` And David said to him, "Do not fear, for I will surely show you kindness for the sake of Jonathan your father and will restore to you all the land of Saul your father, and you shall eat bread at my table *_continually_*."
* `2Sa 9:13` So Mephibosheth dwelt in Jerusalem, for he ate *_continually_* at the king's table. And he was lame in both his feet.
* `2Sa 15:12` And Absalom sent for Ahithophel the Gilonite, David's counselor, from his city, even from Giloh, while he offered sacrifices. And the conspiracy was strong, for the people increased *_continually_* with Absalom.
* `2Sa 19:13` And say to Amasa, 'Are you not of my bone and of my flesh? May God do so to me and more also, if you are not captain of the host before me *_continually_* in place of Joab.'"
* `1Ki 10:8` Happy are your men. Happy are these your servants who stand *_continually_* before you and who hear your wisdom.
* `2Ki 4:9` And she said to her husband, "Behold now, I perceive that this is a holy man of God who passes by us *_continually_*.
* `2Ki 25:29` And he changed his prison garments. And he ate bread *_continually_* before him all the days of his life.
* `1Ch 16:6` Benaiah and Jahaziel the priests with trumpets *_continually_* before the ark of the covenant of God.
* `1Ch 16:11` Seek the LORD and his strength. Seek his face *_continually_*.
* `1Ch 16:37` So he left there before the ark of the covenant of the LORD Asaph and his brothers to minister before the ark *_continually_*, as every day's work required,
* `1Ch 16:40` To offer burnt-offerings to the LORD upon the altar of the burnt-offering *_continually_* morning and evening and to do according to all that is written in the law of the LORD, which he commanded Israel.
* `1Ch 23:31` And to offer all burnt-sacrifices to the LORD on the sabbaths, in the new moons, and on the set feasts, by number, according to the order commanded to them, *_continually_* before the LORD;
* `2Ch 9:7` Happy are your men and happy are these servants of yours who stand *_continually_* before you and hear your wisdom.
* `2Ch 12:15` Now the acts of Rehoboam, first and last, are they not written in the book of Shemaiah the prophet and of Iddo the seer concerning genealogies? And there were wars between Rehoboam and Jeroboam *_continually_*.
* `2Ch 24:14` And when they had finished it, they brought the rest of the money before the king and Jehoiada, of which were made vessels for the house of the LORD, even vessels to minister and to offer with, and spoons and vessels of gold and silver. And they offered burnt-offerings in the house of the LORD *_continually_* all the days of Jehoiada.
* `Job 1:5` And it was so, when the days of their feasting had ended, that Job sent and sanctified them, rose early in the morning, and offered burnt-offerings according to the number of them all, for Job said, "It may be that my sons have sinned and cursed God in their hearts." Thus Job did *_continually_*.
* `Psa 25:15` [SAMEKH] My eyes are *_continually_* toward the LORD, for he will pluck my feet out of the net.
* `Psa 34:1` [A Psalm of David: when he changed his behavior before Abimelech, who drove him away, and he departed.] I will bless the LORD at all times. His praise shall *_continually_* be in my mouth.
* `Psa 35:27` Let them shout for joy and be glad who favor my righteous cause. Let them even say *_continually_*, "Let the LORD be magnified, who has pleasure in the prosperity of his servant."
* `Psa 38:17` For I am ready to fall, and my sorrow is *_continually_* before me.
* `Psa 40:11` Do not withhold your tender mercies from me, O LORD. Let your loving-kindness and your truth *_continually_* preserve me.
* `Psa 40:16` Let all those who seek you rejoice and be glad in you. Let those who love your salvation say *_continually_*, "May the LORD be magnified."
* `Psa 42:3` My tears have been my food day and night while they *_continually_* say to me, "Where is your God?"
* `Psa 44:15` My disgrace is *_continually_* before me, and the shame of my face has covered me,
* `Psa 50:8` I will not reprove you for your sacrifices or your burnt-offerings which have been *_continually_* before me.
* `Psa 52:1` [To the Chief Musician. Maschil. A Psalm of David: when Doeg the Edomite came and told Saul and said to him, "David has come to the house of Ahimelech."] Why do you boast yourself in mischief, O mighty man? The goodness of God endures *_continually_*.
* `Psa 58:7` Let them melt away like waters which run *_continually_*. When he bends his bow to shoot his arrows, let them be as though they were cut off.
* `Psa 69:23` Let their eyes be darkened so that they do not see, and make their loins *_continually_* shake.
* `Psa 70:4` Let all those who seek you rejoice and be glad in you. And let those who love your salvation say *_continually_*, "Let God be magnified."
* `Psa 71:3` Be my strong habitation to which I may *_continually_* resort. You have given commandment to save me, for you are my rock and my fortress.
* `Psa 71:6` I have been sustained by you from my birth. You are he who brought me into life. My praise shall be *_continually_* of you.
* `Psa 71:14` But I will hope *_continually_* and will praise you more and more.
* `Psa 72:15` And he shall live, and to him the gold of Sheba shall be given. Prayer shall also be made for him *_continually_*, and daily he shall be praised.
* `Psa 73:23` Nevertheless, I am *_continually_* with you. You have held me by my right hand.
* `Psa 74:23` Do not forget the voice of your enemies. The tumult of those who rise against you increases *_continually_*.
* `Psa 109:10` Let his children *_continually_* wander around and beg. Let them also seek their bread out of their desolate places.
* `Psa 109:15` Let them be before the LORD *_continually_* so that he may cut off their memory from the earth.
* `Psa 109:19` Let it be to him as the garment which covers him and for a girdle with which he is girded *_continually_*.
* `Psa 119:44` And I shall keep your law *_continually_* forever and ever.
* `Psa 119:109` My soul is *_continually_* in my hand, yet I do not forget your law.
* `Psa 119:117` Support me, and I shall be safe and will have respect for your statutes *_continually_*.
* `Psa 140:2` Who devise mischiefs in their heart. *_Continually_* they are assembled for war.
* `Pro 6:14` Perverseness is in his heart. He devises mischief *_continually_*. He sows discord.
* `Pro 6:21` Bind them *_continually_* upon your heart and tie them around your neck.
* `Ecc 1:6` The wind goes toward the south and turns around to the north. It whirls around *_continually_*. And the wind returns again according to its circuits.
* `Isa 21:8` Then he cried like a lion, "My lord, I stand *_continually_* upon the watch-tower in the day time, and I am set in my ward whole nights.
* `Isa 49:16` Behold, I have engraved you upon the palms of my hands. Your walls are *_continually_* before me.
* `Isa 51:13` That you forget the LORD your maker, who has stretched forth the heavens and laid the foundations of the earth, and that you have feared *_continually_* every day because of the fury of the oppressor, as if he were ready to destroy? And where is the fury of the oppressor?
* `Isa 52:5` Now therefore, what do I have here," says the LORD, "that my people are taken away for nothing? Those who rule over them make them to howl," says the LORD, "and my name *_continually_* every day is blasphemed.
* `Isa 58:11` And the LORD will guide you *_continually_*, satisfy your soul in drought, and make your bones fat. And you shall be like a watered garden and like a spring of water, whose waters do not fail.
* `Isa 60:11` Therefore, your gates shall be open *_continually_*. They shall not be shut, day or night, so that men may bring to you the forces of the Gentiles, with their kings being led in procession.
* `Isa 65:3` A people who provokes me to anger *_continually_* to my face, who sacrifices in gardens and burns incense upon altars of brick,
* `Jer 6:7` As a fountain casts out her waters, so she casts out her wickedness. Violence and devastation is heard in her. *_Continually_* before me are grief and wounds.
* `Jer 33:18` Neither shall the priests the Levites lack a man before me to offer burnt-offerings, to kindle food-offerings, and to do sacrifice *_continually_*.'"
* `Jer 52:33` And he changed his prison garments and *_continually_* ate bread before him all the days of his life.
* `Ezk 46:14` And you shall prepare a food-offering for it every morning, the sixth part of an ephah and the third part of a hin of oil to temper with the fine flour, a food-offering *_continually_* by a perpetual ordinance to the LORD.
* `Dan 6:16` Then the king commanded, and they brought Daniel and cast him into the den of lions. Now the king spoke and said to Daniel, "Your God whom you serve *_continually_*, he will deliver you."
* `Dan 6:20` And when he came to the den, he cried with a lamentable voice to Daniel, and the king spoke and said to Daniel, "O Daniel, servant of the living God, is your God, whom you serve *_continually_*, able to deliver you from the lions?"
* `Hos 4:18` Their drink is sour. They have been guilty of lewd deeds *_continually_*. Her rulers have thoroughly loved shame.
* `Hos 12:6` Therefore, turn to your God. Keep mercy and judgment and wait on your God *_continually_*.
* `Oba 1:16` For as you have drank upon my holy mountain, so all the heathen shall drink *_continually_*. Indeed, they shall drink and they shall swallow down, and they shall be as though they had never existed.
* `Nah 3:19` There is no healing of your breach. Your wound is grievous. All who hear your fame shall clap the hands over you. For upon whom has your wickedness not passed *_continually_*?
* `Hab 1:17` Shall they therefore empty their net and not spare *_continually_* to slay the nations?
* `Luk 24:53` And were *_continually_* in the temple, praising and blessing God. Amen.
* `Act 6:4` But we will give ourselves *_continually_* to prayer and to the ministry of the word."
* `Act 10:7` And when the angel who spoke to Cornelius had departed, he called two of his household servants and a devout soldier from among those who waited on him *_continually_*.
* `Rom 13:6` For because of this you also pay tribute, for they are God's ministers, attending *_continually_* upon this very thing.
* `Heb 7:3` Without father, without mother, without descent, having neither beginning of days, nor end of life, but made like the Son of God, abides a priest *_continually_*.
* `Heb 10:1` For the law, having a shadow of good things to come, and not the very image of the things, can never with those sacrifices, which they offered year by year *_continually_*, make perfect those who draw near.
* `Heb 13:15` Therefore, by him, let us offer the sacrifice of praise to God *_continually_*, that is, "the fruit of our lips," giving thanks to his name.

_83 verses containing CONTINUALLY_

== CONTINUANCE

* `Rom 2:7` To those who, by patient *_continuance_* in well-doing, seek for glory, honor, and immortality, he will give eternal life,

_1 verse containing CONTINUANCE_

== CONTINUE

* `Exo 9:2` For if you refuse to let them go and *_continue_* to hold them,
* `Lev 12:4` And she shall then *_continue_* in the blood of her purifying for thirty-three days. She shall not touch any hallowed thing or come into the sanctuary until the days of her purifying are fulfilled.
* `Lev 12:5` But if she bears a female child, then she shall be unclean for two weeks, as in her separation. And she shall *_continue_* in the blood of her purifying for sixty-six days.
* `Deu 25:3` Forty stripes he may give him, but no more. Otherwise, if he should *_continue_* and beat him with many more stripes than these, then your brother would be dishonored in your eyes.
* `1Sa 12:14` If you will fear the LORD, serve him, obey his voice, and do not rebel against the commandment of the LORD, then both you and also the king who reigns over you shall *_continue_* following the LORD your God.
* `1Sa 13:14` But now your kingdom shall not *_continue_*. The LORD has sought for himself a man after his own heart and the LORD has commanded him to be captain over his people because you have not kept that which the LORD commanded you."
* `2Sa 7:29` And now, let it please you to bless the house of your servant so that it may *_continue_* forever before you. For you, O Lord GOD, have spoken it, and with your blessing let the house of your servant be blessed forever."
* `2Sa 19:35` I am this day eighty years old. And can I discern between good and evil? Can your servant taste what I eat or what I drink? Can I hear anymore the voice of singing-men and singing-women? Why then should your servant *_continue_* to be a burden to my lord the king?
* `1Ki 2:4` So that the LORD may *_continue_* his word which he spoke concerning me, saying, 'If your children take heed to their way to walk before me in truth with all their heart and with all their soul, there shall not fail you,' he said, 'a man on the throne of Israel.'
* `Job 14:2` He comes forth like a flower and is cut down. He also flees like a shadow and does not *_continue_*.
* `Job 15:29` He shall not be rich, neither shall his substance *_continue_*, neither shall he prolong its perfection upon the earth.
* `Job 17:2` Are there not mockers with me? And does my eye not *_continue_* in their provocation?
* `Psa 36:10` O *_continue_* your loving-kindness to those who know you, and your righteousness to the upright in heart.
* `Psa 49:11` Their inward thought is that their houses shall *_continue_* forever and their dwelling places to all generations. They call their lands after their own names.
* `Psa 102:28` The children of your servants shall *_continue_*, and their offspring shall be established before you."
* `Psa 119:91` They *_continue_* this day according to your ordinances, for all are your servants.
* `Isa 5:11` Woe to those who rise early in the morning so that they may follow strong drink, who *_continue_* until night until wine inflames them!
* `Dan 11:8` And he shall also carry captive into Egypt their gods, with their princes, and with their precious vessels of silver and of gold, and he shall *_continue_* more years than the king of the north.
* `Mth 15:32` Then Jesus called his disciples to him, and said, "I have compassion on the multitude, because they *_continue_* with me now three days and have nothing to eat. I will not send them away fasting, lest they faint in the way."
* `Jhn 8:31` Then Jesus said to those Jews who believed in him, "If you *_continue_* in my word, you are my disciples indeed.
* `Jhn 15:9` As the Father has loved me, so I have loved you. *_Continue_* in my love.
* `Act 13:43` Now when the congregation was broken up, many of the Jews and religious proselytes followed Paul and Barnabas, who, speaking to them, persuaded them to *_continue_* in the grace of God.
* `Act 14:22` Confirming the souls of the disciples, exhorting them to *_continue_* in the faith, and saying, "We must through much tribulation enter into the kingdom of God."
* `Act 26:22` Having therefore obtained help from God, I *_continue_* to this day, testifying both to small and great, saying no other things than those which the prophets and Moses said should come:
* `Rom 6:1` What shall we say then? Shall we *_continue_* in sin so that grace may abound?
* `Rom 11:22` Behold therefore the goodness and severity of God: on those who fell, severity, but toward you, goodness, if you *_continue_* in his goodness. Otherwise, you also shall be cut off.
* `Rom 12:12` Rejoice in hope, be patient in tribulation, *_continue_* steadfastly in prayer.
* `1Co 7:20` Let every man *_continue_* in the same calling in which he was called.
* `1Co 7:24` Brothers, let every man in the state in which he is called *_continue_* in it with God.
* `Gal 2:5` To whom we gave place by subjection, not even for an hour, so that the truth of the gospel might *_continue_* with you.
* `Gal 3:10` For as many as are of the works of the law are under the curse, for it is written, "Accursed is everyone who does not *_continue_* in all things which are written in the book of the law to do them."
* `Phl 1:25` And having this confidence, I know that I shall abide and *_continue_* with you all for your furtherance and joy of faith,
* `Col 1:23` If you *_continue_* in the faith grounded and settled and are not moved away from the hope of the gospel which you have heard and which has been preached to every creature which is under heaven, of which I, Paul, am made a minister.
* `Col 4:2` *_Continue_* in prayer and watch in the same with thanksgiving,
* `1Ti 2:15` But she will be saved in child-bearing, if they *_continue_* in faith, charity, and holiness, with sobriety.
* `1Ti 4:16` Take heed to yourself and to your doctrine. *_Continue_* in them. For in doing this you will both save yourself and those who hear you.
* `2Ti 3:14` But *_continue_* in the things which you have learned and have been assured of, knowing from whom you have learned them,
* `Heb 7:23` And they truly were many priests because they were not allowed to *_continue_* by reason of death.
* `Heb 8:9` Not according to the covenant that I made with their fathers in the day when I took them by the hand to lead them out of the land of Egypt, for they did not *_continue_* in my covenant, and I did not regard them,' says the Lord.
* `Heb 13:1` Let brotherly love *_continue_*.
* `2Pe 3:4` And saying, "Where is the promise of his coming? For ever since the fathers fell asleep, all things *_continue_* as they were from the beginning of the creation."
* `1Jn 2:24` Let that therefore abide in you which you have heard from the beginning. If that which you have heard from the beginning remains in you, you also shall *_continue_* in the Son and in the Father.
* `Rev 13:5` And there was given to him a mouth speaking great things and blasphemies, and power was given to him to *_continue_* forty-two months.

_43 verses containing CONTINUE_

== CONTINUED

* `Gen 40:4` And the captain of the guard charged Joseph with them, and he served them, and they *_continued_* a season in custody.
* `Jdg 5:17` Gilead stayed beyond the Jordan. And why did Dan remain in ships? Asher *_continued_* on the sea-shore and stayed in his breaches.
* `Rth 1:2` And the name of the man was Elimelech, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of Beth-lehem-judah. And they came into the country of Moab and *_continued_* there.
* `Rth 2:7` And she said, 'I pray you, let me glean and gather after the reapers among the sheaves.' So she came and has *_continued_* even from the morning until now, and she rested a little in the house."
* `1Sa 1:12` And it came to pass as she *_continued_* praying before the LORD, that Eli observed her mouth.
* `1Sa 2:26` And the child Samuel *_continued_* to grow and was in favor both with the LORD and also with men.
* `2Sa 6:11` And the ark of the LORD *_continued_* in the house of Obed-edom the Gittite for three months. And the LORD blessed Obed-edom and all his household.
* `1Ki 22:1` And they *_continued_* three years without war between Syria and Israel.
* `2Ch 29:28` And all the congregation worshiped, the singers sang, and the trumpeters sounded. And all this *_continued_* until the burnt-offering was finished.
* `2Ch 32:16` And his servants *_continued_* to speak against the LORD God and against his servant Hezekiah.
* `Neh 5:16` And I also *_continued_* in the work of this wall, neither did we buy any land. And all my servants were gathered there to the work.
* `Job 27:1` Moreover, Job *_continued_* his parable and said,
* `Job 29:1` Moreover, Job *_continued_* his parable and said,
* `Psa 72:17` His name shall endure forever. His name shall be *_continued_* as long as the sun. And men shall be blessed in him. All nations shall call him blessed.
* `Isa 64:5` You meet him who rejoices and works righteousness, those who remember you in your ways. Behold, you are angry, for we have sinned. We *_continued_* in them, and we shall be saved.
* `Ezk 41:7` And the side-chambers broadened, winding around upward, for the winding around of the house conveyed upward around the house. Therefore, the breadth of the house *_continued_* upward, and thus one ascends from the lowest chamber to the highest by the middle.
* `Dan 1:21` And Daniel *_continued_* even to the first year of king Cyrus.
* `Luk 6:12` And it came to pass in those days, that he went out to a mountain to pray and *_continued_* all night in prayer to God.
* `Luk 22:28` "You are those who have *_continued_* with me in my temptations.
* `Jhn 2:12` After this he went down to Capernaum—he, his mother, his brothers, and his disciples—and they *_continued_* there not many days.
* `Jhn 8:7` So when they *_continued_* asking him, he raised himself and said to them, "He who is without sin among you, let him cast the first stone at her."
* `Act 1:14` All of these *_continued_* with one accord in prayer and supplication, with the women and Mary the mother of Jesus, and with his brothers.
* `Act 2:42` And they *_continued_* steadfastly in the apostles' doctrine and fellowship, in breaking of bread, and in prayers.
* `Act 8:13` Then Simon himself believed also. And when he was baptized, he *_continued_* with Philip and wondered, beholding the miracles and signs which were done.
* `Act 12:16` But Peter *_continued_* knocking. And when they had opened the door and saw him, they were astonished.
* `Act 15:35` But Paul and Barnabas *_continued_* in Antioch teaching and preaching the word of the Lord, with many others also.
* `Act 18:11` And he *_continued_* there one year and six months teaching the word of God among them.
* `Act 19:10` And this *_continued_* for two years so that all those who dwelt in Asia heard the word of the Lord Jesus—both Jews and Greeks.
* `Act 20:7` And upon the first day of the week, when the disciples came together to break bread, Paul preached to them (ready to depart on the next day) and *_continued_* his speech until midnight.
* `Act 27:33` And as the day was about to come, Paul implored them all to take food, saying, "This day is the fourteenth day that you have waited and *_continued_* fasting, having taken nothing.
* `1Jn 2:19` They went out from us, but they did not belong to us. For if they had belonged to us, they would no doubt have *_continued_* with us. But they went out so that they might be made manifest that none of them belonged to us.

_31 verses containing CONTINUED_

== CONTINUES

* `1Ti 5:5` Now she who is a widow indeed and desolate trusts in God and *_continues_* in supplications and prayers night and day.
* `Heb 7:24` But this man, because he *_continues_* forever, has an unchangeable priesthood;
* `Jms 1:25` But he who looks into the perfect law of liberty and *_continues_* in it, not being a forgetful hearer, but a doer of the work, this man shall be blessed in his deed.

_3 verses containing CONTINUES_

== CONTINUING

* `Jer 30:23` Behold, the whirlwind of the LORD goes forth with fury, a *_continuing_* whirlwind. It shall fall with pain upon the head of the wicked.
* `Act 2:46` And they, *_continuing_* daily with one accord in the temple and breaking bread from house to house, ate their food with gladness and singleness of heart,
* `Heb 13:14` For here we have no *_continuing_* city, but we seek one to come.

_3 verses containing CONTINUING_

== CONTRACT

* `Jer 32:10` And I signed the *_contract_* and sealed it, took witnesses, and weighed him the money in the balances.

_1 verse containing CONTRACT_

== CONTRADICTED

* `Act 19:36` Seeing then that these things cannot be *_contradicted_*, you ought to be quiet and to do nothing rashly.

_1 verse containing CONTRADICTED_

== CONTRADICTING

* `Act 13:45` But when the Jews saw the multitudes, they were filled with envy and spoke against those things which were uttered by Paul, *_contradicting_* and blaspheming.

_1 verse containing CONTRADICTING_

== CONTRADICTION

* `Heb 6:16` For men truly swear by the greater, and an oath for confirmation is to them an end of all *_contradiction_*.
* `Heb 7:7` And without all *_contradiction_* the less is blessed by the better.
* `Heb 12:3` Consider him who endured such *_contradiction_* of sinners against himself, lest you be wearied and faint in your minds.

_3 verses containing CONTRADICTION_

== CONTRARILY

* `1Co 12:22` *_Contrarily_*, much rather those members of the body which seem to be more feeble are necessary,

_1 verse containing CONTRARILY_

== CONTRARY

* `Lev 26:21` 'And if you walk *_contrary_* to me and will not listen to me, I will bring seven times more plagues upon you according to your sins.
* `Lev 26:23` 'And if you will not be reformed by me by these things, but will walk *_contrary_* to me,
* `Lev 26:24` Then I will also walk *_contrary_* to you and I will punish you seven times for your sins.
* `Lev 26:27` 'And if you will not for all this listen to me, but walk *_contrary_* to me,
* `Lev 26:28` Then I will walk *_contrary_* to you also in fury, and I, even I, will chastise you seven times for your sins.
* `Lev 26:40` 'If they confess their iniquity and the iniquity of their fathers, with their trespass which they trespassed against me, and that they also have walked *_contrary_* to me,
* `Lev 26:41` And that I also have walked *_contrary_* to them and have brought them into the land of their enemies, if then their uncircumcised hearts are humbled and they then accept the punishment of their iniquity,
* `Est 9:1` Now in the twelfth month (that is, the month Adar), on the thirteenth day of the same, when the king's commandment and his decree drew near to be put in execution, on the day that the enemies of the Jews hoped to have power over them (though it was turned to the *_contrary_*, that the Jews had rule over those who hated them),
* `Ezk 16:34` And the *_contrary_* is in you from other women in your unlawful commerce, whereas no one follows you to commit lewdness. And in that you give a reward, and no reward is given to you, therefore you are *_contrary_*."
* `Mth 14:24` But the boat was now in the midst of the sea, tossed with waves, for the wind was *_contrary_*.
* `Mrk 6:48` And he saw them toiling in rowing, for the wind was *_contrary_* to them. And about the fourth watch of the night he comes to them, walking upon the sea, and would have passed by them.
* `Act 17:7` Whom Jason has received, and they all do *_contrary_* to the decrees of Caesar, saying that there is another king, Jesus."
* `Act 18:13` Saying, "This man persuades men to worship God *_contrary_* to the law."
* `Act 23:3` Then Paul said to him, "God shall smite you, you whited wall. And do you sit to judge me according to the law, and *_contrary_* to the law command me to be smitten?"
* `Act 26:9` "I truly thought with myself that I ought to do many things *_contrary_* to the name of Jesus of Nazareth,
* `Act 27:4` And when we had launched from there, we sailed under Cyprus, because the winds were *_contrary_*.
* `Rom 11:24` For if you were cut out of the olive-tree which is wild by nature and were grafted in *_contrary_* to nature into a good olive-tree, how much more shall these, which are the natural branches, be grafted into their own olive-tree?
* `Rom 16:17` Now I implore you, brothers, mark those who cause divisions and offenses *_contrary_* to the doctrine which you have learned, and avoid them.
* `Gal 2:7` But on the *_contrary_*, when they saw that the gospel of the uncircumcision was committed to me as the gospel of the circumcision was to Peter
* `Gal 5:17` For the flesh lusts against the Spirit, and the Spirit is against the flesh. And these are *_contrary_* to one another so that you cannot do the things that you wish.
* `Col 2:14` Blotting out the hand-writing of ordinances that was against us, which was *_contrary_* to us, and took it out of the way, nailing it to his cross.
* `1Th 2:15` Who killed both the Lord Jesus and their own prophets and have persecuted us. And they do not please God and are *_contrary_* to all men,
* `1Ti 1:10` For lewd persons, for those who defile themselves with mankind, for kidnappers, for liars, for perjured persons, and if there is any other thing that is *_contrary_* to sound doctrine,
* `Tit 2:8` Sound speech that cannot be condemned, so that he who is of the *_contrary_* part may be ashamed, having no evil thing to say concerning you.
* `1Pe 3:9` Not rendering evil for evil or railing for railing, but on the *_contrary_*, blessing, knowing that you are called to this, so that you should inherit a blessing.

_25 verses containing CONTRARY_

== CONTRIBUTE

* `Rom 12:13` *_Contribute_* to the needs of the saints and pursue hospitality.

_1 verse containing CONTRIBUTE_

== CONTRIBUTION

* `Rom 15:26` For it has pleased them of Macedonia and Achaia to make a certain *_contribution_* for the poor of the saints who are at Jerusalem.
* `2Co 9:13` Because of the proof of this ministration, they glorify God for your professed subjection to the gospel of Christ and for your liberal *_contribution_* to them and to all men,

_2 verses containing CONTRIBUTION_

== CONTRITE

* `Psa 34:18` The LORD is near to those who are of a broken heart and saves those who are of a *_contrite_* spirit.
* `Psa 51:17` The sacrifices of God are a broken spirit. A broken and a *_contrite_* heart, O God, you will not despise.
* `Isa 57:15` For thus says the high and lofty One who inhabits eternity, whose name is Holy: "I dwell in the high and holy place, with him also who is of a *_contrite_* and humble spirit, to revive the spirit of the humble and to revive the heart of the *_contrite_* ones.
* `Isa 66:2` For all these things my hand has made, and all these things have been," says the LORD. "But to this man I will look, even to him who is poor and of a *_contrite_* spirit and trembles at my word.

_4 verses containing CONTRITE_

== CONTROVERSIES

* `2Ch 19:8` Moreover, in Jerusalem, Jehoshaphat set some of the Levites, priests, and chief of the fathers of Israel for the judgment of the LORD and for *_controversies_* when they returned to Jerusalem.

_1 verse containing CONTROVERSIES_

== CONTROVERSY

* `Deu 17:8` "If there arises a matter too hard for you in judgment between blood and blood, between plea and plea, and between stroke and stroke, being matters of *_controversy_* within your gates, then you shall arise and go up to the place which the LORD your God chooses.
* `Deu 19:17` Then both the men between whom the *_controversy_* is shall stand before the LORD, before the priests and the judges who shall be in those days.
* `Deu 21:5` And the priests the sons of Levi shall come near (for the LORD your God has chosen them to minister to him and to bless in the name of the LORD) and by their word every *_controversy_* and every stroke shall be tried.
* `Deu 25:1` "If there is a *_controversy_* between men and they come to judgment so that the judges may judge them, then they shall justify the righteous and condemn the wicked.
* `2Sa 15:2` And Absalom rose early and stood beside the way of the gate. And it was so, that when any man who had a *_controversy_* came to the king for judgment, Absalom called to him and said, "Of what city are you?" And he said, "Your servant is one of the tribes of Israel."
* `Isa 34:8` For it is the day of the LORD'S vengeance, and the year of recompenses for the *_controversy_* of Zion.
* `Jer 25:31` A noise shall come even to the ends of the earth, for the LORD has a *_controversy_* with the nations. He will plead with all flesh. He will give those who are wicked to the sword,' says the LORD."
* `Ezk 44:24` And in *_controversy_* they shall stand in judgment and judge it according to my judgments. And they shall keep my laws and my statutes in all my assemblies and hallow my sabbaths.
* `Hos 4:1` Hear the word of the LORD, children of Israel, for the LORD has a *_controversy_* with the inhabitants of the land, because there is no truth, nor mercy, nor knowledge of God in the land.
* `Hos 12:2` The LORD also has a *_controversy_* with Judah and will punish Jacob according to his ways. According to his doings he will recompense him.
* `Mic 6:2` Hear, O mountains, the LORD'S *_controversy_*, and you strong foundations of the earth, for the LORD has a *_controversy_* with his people and he will plead with Israel.
* `1Ti 3:16` And without *_controversy_*, the mystery of godliness is great. God was manifest in the flesh, justified in the Spirit, seen by angels, preached to the Gentiles, believed in by the world, and received up into glory.

_12 verses containing CONTROVERSY_

== CONVENE

* `Num 8:9` And you shall bring the Levites before the Tabernacle of the Congregation and you shall *_convene_* the whole assembly of the children of Israel.
* `Num 20:8` "Take the rod and *_convene_* the assembly—you and Aaron your brother—and speak to the rock before their eyes, and it shall give forth its water. And you shall bring forth to them water out of the rock, and you shall give drink to the congregation and their beasts."
* `Deu 31:12` *_Convene_* the people—men, women, children, and your stranger who is within your gates—so that they may hear and learn to fear the LORD your God, and observe to do all the words of this law,
* `Dan 3:2` Then Nebuchadnezzar the king sent to *_convene_* the princes, the governors, the captains, the judges, the treasurers, the counselors, the sheriffs, and all the rulers of the provinces to come to the dedication of the image which Nebuchadnezzar the king had set up.

_4 verses containing CONVENE_

== CONVENED

* `Num 10:7` But when the congregation is to be *_convened_*, you shall blow, but you shall not sound an alarm.
* `Jsh 24:1` And Joshua *_convened_* all the tribes of Israel to Shechem and called for the elders of Israel and for their heads, for their judges, and for their officers, and they presented themselves before God.
* `1Sa 5:11` So they sent and *_convened_* all the lords of the Philistines and said, "Send the ark of the God of Israel away, and let it go back to its own place so that it does not slay us and our people." For there was a deadly destruction throughout all the city. The hand of God was very heavy there.
* `2Ki 10:18` And Jehu *_convened_* all the people and said to them, "Ahab served Baal a little, but Jehu shall serve him much.
* `2Ch 24:5` And he *_convened_* the priests and the Levites and said to them, "Go out to the cities of Judah and gather from all Israel money to repair the house of your God from year to year, and see that you hasten the matter." But the Levites did not hasten it.
* `2Ch 29:20` Then Hezekiah the king rose early, *_convened_* the rulers of the city, and went up to the house of the LORD.
* `2Ch 34:29` Then the king sent and *_convened_* all the elders of Judah and Jerusalem.
* `Jhn 11:47` Then the chief priests and the Pharisees *_convened_* a council, and said, "What do we do? For this man performs many miracles.
* `Act 15:30` So when they were dismissed, they came to Antioch. And when they had *_convened_* the multitude, they delivered the epistle,

_9 verses containing CONVENED_

== CONVENIENT

* `Jer 40:5` Now while he had not yet gone back, he said, "Go back also to Gedaliah the son of Ahikam the son of Shaphan, whom the king of Babylon has made governor over the cities of Judah, and dwell with him among the people, or go wherever it seems *_convenient_* for you to go." So the captain of the guard gave him provisions and a reward and let him go.
* `Mrk 6:21` And when a *_convenient_* day had come, Herod, on his birthday, made a supper for his lords, high captains, and chief men of Galilee.
* `Act 24:25` And as he reasoned of righteousness, temperance, and judgment to come, Felix trembled, and answered, "Depart for this time. When I have a *_convenient_* season, I will call for you."
* `1Co 16:12` As concerning our brother Apollos, I greatly desired him to come to you with the brothers, but his will was not at all to come at this time. But he will come when he has *_convenient_* time.

_4 verses containing CONVENIENT_

== CONVENIENTLY

* `Mrk 14:11` And when they heard it, they were glad and promised to give him money. And he sought how he might *_conveniently_* betray him.

_1 verse containing CONVENIENTLY_

== CONVERSANT

* `1Sa 25:15` But the men were very good to us, and we were not hurt, neither did we miss anything as long as we were *_conversant_* with them when we were in the fields.

_1 verse containing CONVERSANT_

== CONVERSION

* `Act 15:3` And being brought on their way by the church, they passed through Phenice and Samaria declaring the *_conversion_* of the Gentiles. And they caused great joy to all the brothers.

_1 verse containing CONVERSION_

== CONVERT

* `Isa 6:10` Make the heart of this people fat, make their ears heavy, and shut their eyes, lest they see with their eyes, hear with their ears, understand with their heart, and *_convert_* and be healed."
* `Jms 5:19` Brothers, if any one of you should err from the truth, and someone should *_convert_* him,

_2 verses containing CONVERT_

== CONVERTED

* `Psa 51:13` Then I will teach transgressors your ways, and sinners shall be *_converted_* to you.
* `Isa 60:5` Then you shall see and flow together, and your heart shall fear and be enlarged, because the abundance of the sea shall be *_converted_* to you, the forces of the Gentiles shall come to you.
* `Mth 13:15` For this people's heart has become callous, their ears are dull of hearing, and their eyes they have closed, or else perhaps they should see with their eyes, hear with their ears, and should understand with their heart and should be *_converted_*, and I should heal them.'
* `Mth 18:3` And said, "Truly I say to you, unless you are *_converted_* and become as little children, you shall not enter into the kingdom of heaven.
* `Mrk 4:12` So that 'seeing they may see and not perceive, and hearing they may hear and not understand, lest at any time they should be *_converted_* and their sins should be forgiven.'"
* `Luk 22:32` But I have prayed for you, that your faith may not fail. When you are *_converted_*, strengthen your brothers."
* `Jhn 12:40` "He has blinded their eyes and hardened their heart so that they should not see with their eyes, nor understand with their heart, and be *_converted_*, and I should heal them."
* `Act 3:19` Therefore, repent and be *_converted_* so that your sins may be blotted out, and that times of refreshing may come from the presence of the Lord,
* `Act 28:27` For the heart of this people has become callous, their ears are dull of hearing, and their eyes they have closed, lest they should see with their eyes, hear with their ears, understand with their heart, and be *_converted_*, and I should heal them."'

_9 verses containing CONVERTED_

== CONVERTING

* `Psa 19:7` The law of the LORD is perfect, *_converting_* the soul. The testimony of the LORD is sure, making the simple wise.

_1 verse containing CONVERTING_

== CONVERTS

* `Isa 1:27` Zion shall be redeemed with judgment, and her *_converts_* with righteousness.
* `Jms 5:20` Let him know, that he who *_converts_* a sinner from the error of his way will save a soul from death and will hide a multitude of sins.

_2 verses containing CONVERTS_

== CONVEY

* `1Ki 5:9` My servants shall bring them down from Lebanon to the sea, and I will *_convey_* them by sea in rafts to the place that you shall appoint me and cause them to be discharged there, and you shall receive them. And you shall accomplish my desire in giving food for my household."
* `2Ch 2:16` And we will cut wood out of Lebanon, as much as you shall need, and we will bring it to you in rafts by sea to Joppa, and you may *_convey_* it to Jerusalem."
* `Neh 2:7` Moreover, I said to the king, "If it should please the king, let letters be given to me for the governors beyond the river so that they may *_convey_* me over until I come into Judah,

_3 verses containing CONVEY_

== CONVEYED

* `2Ch 12:11` And when the king entered into the house of the LORD, the guard came and *_conveyed_* them and brought them back into the guard-chamber.
* `Ezk 41:7` And the side-chambers broadened, winding around upward, for the winding around of the house *_conveyed_* upward around the house. Therefore, the breadth of the house continued upward, and thus one ascends from the lowest chamber to the highest by the middle.
* `Jhn 5:13` And he who was healed did not know who it was, for Jesus had *_conveyed_* himself away, a multitude being in that place.

_3 verses containing CONVEYED_

== CONVICT

* `Tit 1:9` Holding firm to the faithful word as he has been taught, so that he may be able by sound doctrine both to exhort and to *_convict_* the gainsayers.
* `Jde 1:15` To execute judgment upon all and to *_convict_* all who are ungodly among them of all their ungodly deeds which they have impiously committed and of all their hard speeches which ungodly sinners have spoken against him."

_2 verses containing CONVICT_

== CONVICTED

* `Jhn 8:9` And those who heard it, being *_convicted_* by their own conscience, went out one by one, beginning at the eldest, even to the last. And Jesus was left alone with the woman standing in the midst.
* `Jms 2:9` But if you have respect to persons, you commit sin and are *_convicted_* by the law as transgressors.

_2 verses containing CONVICTED_

== CONVICTS

* `Jhn 8:46` Which of you *_convicts_* me of sin? And if I speak the truth, why do you not believe me?

_1 verse containing CONVICTS_

== CONVINCED

* `Job 32:12` I even attended to you, and behold, there was none of you who *_convinced_* Job, or who answered his words,
* `Act 18:28` For he mightily *_convinced_* the Jews publicly, showing by the Scriptures that Jesus was Christ.
* `1Co 14:24` But if all prophesy, and someone who does not believe or someone unlearned comes in, he is *_convinced_* by all and he is judged by all.

_3 verses containing CONVINCED_

== CONVOCATION

* `Exo 12:16` And on the first day there shall be a holy *_convocation_*, and on the seventh day there shall be a holy *_convocation_* to you. No manner of work shall be done in them, except that which every man must eat. That only may be done by you.
* `Lev 23:3` 'Six days work shall be done, but the seventh day is the sabbath of rest, a holy *_convocation_*. You shall do no work. It is the sabbath of the LORD in all your dwellings.
* `Lev 23:7` On the first day you shall have a holy *_convocation_*. You shall do no servile work on it.
* `Lev 23:8` But you shall offer an offering made by fire to the LORD for seven days. On the seventh day is a holy *_convocation_*, you shall do no servile work on it.'"
* `Lev 23:21` And you shall proclaim on the same day that it may be a holy *_convocation_* to you. You shall do no servile work on it. It shall be a statute forever in all your dwellings throughout your generations.
* `Lev 23:24` "Speak to the children of Israel, saying, 'In the seventh month, on the first day of the month, you shall have a sabbath, a memorial of blowing of trumpets, a holy *_convocation_*.
* `Lev 23:27` "Also on the tenth day of this seventh month there shall be a day of atonement. It shall be a holy *_convocation_* to you, and you shall afflict your souls and offer an offering made by fire to the LORD.
* `Lev 23:35` On the first day there shall be a holy *_convocation_*. You shall do no servile work on it.
* `Lev 23:36` Seven days you shall offer an offering made by fire to the LORD. On the eighth day there shall be a holy *_convocation_* to you and you shall offer an offering made by fire to the LORD. It is a solemn assembly and you shall do no servile work on it.
* `Num 28:18` On the first day there shall be a holy *_convocation_*. You shall do no manner of servile work.
* `Num 28:25` And on the seventh day you shall have a holy *_convocation_*. You shall do no servile work.
* `Num 28:26` 'Also, in the day of the first-fruits, when you bring a new food-offering to the LORD, after your weeks have ended, you shall have a holy *_convocation_*. You shall do no servile work.
* `Num 29:1` "'And in the seventh month, on the first day of the month, you shall have a holy *_convocation_*. You shall do no servile work. It is a day of blowing the trumpets for you.
* `Num 29:7` 'And you shall have on the tenth day of this seventh month a holy *_convocation_*, and you shall afflict your souls. You shall not do any work.
* `Num 29:12` 'And on the fifteenth day of the seventh month you shall have a holy *_convocation_*. You shall do no servile work and you shall keep a feast to the LORD seven days.

_15 verses containing CONVOCATION_

== CONVOCATIONS

* `Lev 23:2` "Speak to the children of Israel and say to them, 'Concerning the feasts of the LORD which you shall proclaim to be holy *_convocations_*, even these are my feasts.
* `Lev 23:4` 'These are the feasts of the LORD, holy *_convocations_*, which you shall proclaim in their seasons.
* `Lev 23:37` 'These are the feasts of the LORD which you shall proclaim to be holy *_convocations_* to offer an offering made by fire to the LORD, a burnt-offering, a food-offering, a sacrifice, and drink-offerings, everything upon its day,

_3 verses containing CONVOCATIONS_

== CONVULSED

* `Mrk 1:26` And when the unclean spirit had *_convulsed_* him and cried with a loud voice, he came out of him.
* `Mrk 9:20` And they brought him to him. And when he saw him, immediately the spirit *_convulsed_* him, and he fell on the ground and wallowed, foaming.
* `Luk 9:42` And as he was still coming, the demon threw him down and *_convulsed_* him. And Jesus rebuked the unclean spirit, healed the child, and delivered him back to his father.

_3 verses containing CONVULSED_

== CONVULSES

* `Mrk 9:18` And wherever he takes him, he *_convulses_* him, and he foams and gnashes with his teeth and pines away. And I spoke to your disciples so that they should cast him out, and they could not."
* `Luk 9:39` And behold, a spirit takes him and he suddenly cries out, and it *_convulses_* him so that he foams, and bruising him, it hardly departs from him.

_2 verses containing CONVULSES_

== COOK

* `1Sa 9:23` And Samuel said to the *_cook_*, "Bring the portion which I gave you, of which I said to you, 'Set it by you.'"
* `1Sa 9:24` And the *_cook_* took up the shoulder and that which was upon it and set it before Saul. And Samuel said, "Behold that which is left! Set it before you and eat, because it has been kept for you for the appointed time, for I said, 'I have invited the people.'" So Saul ate with Samuel that day.

_2 verses containing COOK_

== COOKS

* `1Sa 8:13` And he will take your daughters to be confectioners, to be *_cooks_*, and to be bakers.

_1 verse containing COOKS_

== COOL

* `Gen 3:8` And they heard the voice of the LORD God walking in the garden in the *_cool_* of the day. And Adam and his wife hid themselves from the presence of the LORD God amongst the trees of the garden.
* `Luk 16:24` And he cried, and said, 'Father Abraham, have mercy on me, and send Lazarus so that he may dip the tip of his finger in water and *_cool_* my tongue, for I am tormented in this flame.'

_2 verses containing COOL_

== COOS

* `Act 21:1` And it came to pass, that after we were separated from them and had launched, we came with a straight course to *_Coos_*, and the day following to Rhodes, and from there to Patara.

_1 verse containing COOS_

== COPIED

* `Pro 25:1` [These are also proverbs of Solomon, which the men of Hezekiah king of Judah *_copied_* out.]

_1 verse containing COPIED_

== COPING

* `1Ki 7:9` All these were of costly stones, according to the measures of hewn stones sawed with saws inside and outside, even from the foundation to the *_coping_* and likewise on the outside toward the great court.

_1 verse containing COPING_

== COPPER

* `Ezr 8:27` Twenty basins of gold of one thousand drams, and two vessels of fine *_copper_*, precious as gold.
* `2Ti 4:14` Alexander the *_copper_*-smith did me much evil—may the Lord reward him according to his works—

_2 verses containing COPPER_

== COPPER-SMITH

* `2Ti 4:14` Alexander the *_copper-smith_* did me much evil—may the Lord reward him according to his works—

_1 verse containing COPPER-SMITH_

== COPULATION

* `Lev 15:16` 'And if any man's seed of *_copulation_* shall go from him, then he shall wash all his flesh in water and be unclean until the evening.
* `Lev 15:17` And every garment and every skin on which is the seed of *_copulation_* shall be washed with water and be unclean until the evening.
* `Lev 15:18` The woman also with whom a man lies with seed of *_copulation_*, they shall both bathe themselves in water and be unclean until the evening.

_3 verses containing COPULATION_

== COPY

* `Deu 17:18` "And it shall be when he sits upon the throne of his kingdom, that he shall write himself a *_copy_* of this law in a book out of that which is before the priests the Levites.
* `Jsh 8:32` And he wrote there upon the stones a *_copy_* of the law of Moses, which he wrote in the presence of the children of Israel.
* `Ezr 4:11` This is the *_copy_* of the letter that they sent to him, even to Artaxerxes the king: "Your servants the men on this side of the river, and at such a time.
* `Ezr 4:23` Now when the *_copy_* of king Artaxerxes' letter was read before Rehum, Shimshai the scribe, and their companions, they went up in haste to Jerusalem to the Jews and made them to cease by force and power.
* `Ezr 5:6` This is the *_copy_* of the letter that Tatnai, governor on this side of the river, Shethar-boznai, and his companions the Apharsachites, who were on this side of the river, sent to Darius the king.
* `Ezr 7:11` Now this is the *_copy_* of the letter that the king Artaxerxes gave to Ezra the priest, the scribe, even a scribe of the words of the commandments of the LORD and of his statutes to Israel:
* `Est 3:14` The *_copy_* of the writing for a commandment to be given in every province was published to all people that they should be ready for that day.
* `Est 4:8` Also he gave him the *_copy_* of the writing of the decree that was given at Shushan to destroy them to show it to Esther, to declare it to her, and to charge her that she should go before the king to make supplication to him and to make request before him for her people.
* `Est 8:13` The *_copy_* of the writing for a commandment to be given in every province was published to all people so that the Jews would be ready for that day to avenge themselves on their enemies.

_9 verses containing COPY_

== COR

* `Ezk 45:14` Concerning the ordinance of oil, the bath of oil, you shall offer the tenth part of a bath out of the *_cor_*, which is a homer of ten baths (for ten baths are a homer);

_1 verse containing COR_

== CORAL

* `Job 28:18` No mention shall be made of *_coral_* or of pearls, for the price of wisdom is above rubies.
* `Ezk 27:16` Syria was your merchant by reason of the multitude of the wares of your making. They occupied in your fairs with emeralds, purple, embroidered work, fine linen, *_coral_*, and agate.

_2 verses containing CORAL_

== CORBAN

* `Mrk 7:11` But you say, 'If a man says to his father or mother, "Whatever you might be profited by me is *_Corban_*," (that is to say, a gift to God) he shall be free.'

_1 verse containing CORBAN_

== CORD

* `Jsh 2:15` Then she let them down by a *_cord_* through the window, for her house was upon the town-wall, and she dwelt upon the wall.
* `Jsh 2:18` Behold, when we come into the land, you shall bind this line of scarlet *_cord_* in the window by which you let us down. And you shall bring your father, your mother, your brothers, and all your father's household home to you.
* `Job 30:11` Because he has loosened my *_cord_* and afflicted me, they have also let loose the bridle before me.
* `Job 41:1` "Can you draw out leviathan with a hook, or his tongue with a *_cord_* which you let down?
* `Ecc 4:12` And if one prevails against him, two shall withstand him. A three-fold *_cord_* is not quickly broken.
* `Ecc 12:6` Remember your Creator before the silver *_cord_* is removed, the golden bowl is broken, the pitcher is broken at the fountain, or the wheel broken at the cistern,

_6 verses containing CORD_

== CORDS

* `Exo 35:18` The pins of the tabernacle, the pins of the court, and their *_cords_*;
* `Exo 39:40` The hangings of the court with its pillars and its sockets, the hanging for the court-gate with its *_cords_* and its pins, and all the vessels of the service of the tabernacle for the tent of the congregation;
* `Num 3:26` The hangings of the court, the curtain for the door of the court which surrounds the tabernacle and the altar, and its *_cords_*, for all its service.
* `Num 3:37` The pillars of the court all around, their sockets, their pins, and their *_cords_*.
* `Num 4:26` The hangings of the court, the hanging for the door of the gate of the court which surrounds the tabernacle and the altar, their *_cords_*, all the instruments of their service, and all that is made for them. Thus they shall serve.
* `Num 4:32` The pillars of the court all around and their sockets, their pins, and their *_cords_*, with all their instruments and with all their service. And by name you shall reckon the instruments of the charge of their burden.
* `Jdg 15:13` And they spoke to him, saying, "No, but we will bind you firmly and deliver you into their hand. But surely we will not kill you." And they bound him with two new *_cords_* and brought him up from the rock.
* `Jdg 15:14` And when he came to Lehi, the Philistines shouted against him. And the Spirit of the LORD came mightily upon him, and the *_cords_* that were upon his arms became like flax that was burnt with fire, and the bonds dropped off his hands.
* `Jdg 16:7` And Samson said to her, "If they bind me with seven green *_cords_* that were never dried, then I shall become weak and be like any other man."
* `Jdg 16:8` Then the lords of the Philistines brought to her seven green *_cords_* which had not been dried, and she bound him with them.
* `Jdg 16:9` (Now there were men lying in wait, abiding with her in the chamber.) And she said to him, "The Philistines are upon you, Samson." And he broke the *_cords_* as a thread of tow is broken when it touches the fire. So his strength was not known.
* `Est 1:6` Where white, green, and blue hangings were fastened with *_cords_* of fine linen and purple to silver rings and pillars of marble. The couches were of gold and silver upon a pavement of red, blue, white, and black marble.
* `Job 36:8` And if they are bound in fetters and are held in *_cords_* of affliction,
* `Job 38:31` Can you bind the sweet influences of Pleiades, or loosen the *_cords_* of Orion?
* `Psa 2:3` "Let us break their bonds apart and cast away their *_cords_* from us."
* `Psa 118:27` God is the LORD, who has shown us light. Bind the sacrifice with *_cords_*, even to the horns of the altar.
* `Psa 129:4` The LORD is righteous. He has cut apart the *_cords_* of the wicked.
* `Psa 140:5` The proud have hid a snare for me, and also *_cords_*. They have spread a net by the wayside. They have set traps for me. [Selah.]
* `Pro 5:22` His own iniquities shall take the wicked himself, and he shall be held with the *_cords_* of his sins.
* `Isa 5:18` Woe to those who draw iniquity with *_cords_* of vanity and sin as with a cart-rope,
* `Isa 33:20` Look upon Zion, the city of our solemnities. Your eyes shall see Jerusalem, a quiet habitation, a tabernacle that shall not be taken down. Not one of its stakes shall ever be removed, neither shall any of its *_cords_* be broken.
* `Isa 54:2` "Enlarge the place of your tent, and let them extend the curtains of your habitations. Do not spare, lengthen your *_cords_*, and strengthen your stakes,
* `Jer 10:20` My tabernacle is laid waste and all my *_cords_* are broken. My children have gone from me and they are no more. There is no one to stretch forth my tent anymore and to set up my curtains.
* `Jer 38:6` Then they took Jeremiah and cast him into the dungeon of Malchiah the son of Hammelech that was in the court of the prison. And they let Jeremiah down with *_cords_*. And in the dungeon there was no water, but mire. So Jeremiah sunk in the mire.
* `Jer 38:11` So Ebed-melech took the men with him and went into the house of the king under the treasury, took from there old cast cloths and old decayed rags, and let them down by *_cords_* into the dungeon to Jeremiah.
* `Jer 38:12` And Ebed-melech the Cushite said to Jeremiah, "Now put these old cast cloths and decayed rags under your armpits under the *_cords_*." And Jeremiah did so.
* `Jer 38:13` So they drew Jeremiah up with *_cords_* and took him out of the dungeon. And Jeremiah remained in the court of the prison.
* `Ezk 27:24` These were your merchants in all sorts of things, in blue clothes, embroidered work, and in chests of rich apparel, bound with *_cords_* and made of cedar, among your merchandise.
* `Hos 11:4` I drew them with *_cords_* of a man, with ropes of love. And I was to them as those who take off the yoke from their jaws, and I bent down to them and fed them.
* `Jhn 2:15` And when he had made a scourge of small *_cords_*, he drove them all out of the temple, with the sheep and the oxen, and poured out the changers' money and overthrew the tables,

_30 verses containing CORDS_

== CORIANDER-SEED

* `Exo 16:31` And the house of Israel called its name Manna. And it was like *_coriander-seed_*, white, and its taste was like wafers made with honey.
* `Num 11:7` And the manna was like *_coriander-seed_*, and its color like the color of bdellium.

_2 verses containing CORIANDER-SEED_

== CORINTH

* `Act 18:1` After these things, Paul departed from Athens and came to *_Corinth_*.
* `Act 19:1` And it came to pass, that while Apollos was at *_Corinth_*, Paul, having passed through the upper region, came to Ephesus, and finding some disciples,
* `1Co 1:2` To the church of God which is at *_Corinth_*, to those who are sanctified in Christ Jesus, called to be saints, with all who in every place call upon the name of Jesus Christ our Lord—both theirs and ours:
* `2Co 1:1` Paul, an apostle of Jesus Christ by the will of God, and Timothy our brother, to the church of God which is at *_Corinth_*, with all the saints who are in all Achaia:
* `2Co 1:23` Moreover, I call God for a witness upon my soul, that to spare you, I have not yet come to *_Corinth_*.
* `2Ti 4:20` Erastus stayed at *_Corinth_*, but Trophimus I have left sick at Miletum.

_6 verses containing CORINTH_

== CORINTHIANS

* `Act 18:8` And Crispus the chief ruler of the synagogue believed in the Lord with all his house. And many of the *_Corinthians_*, when they heard, believed and were baptized.
* `2Co 6:11` O *_Corinthians_*, our mouth is open to you, our heart is enlarged.

_2 verses containing CORINTHIANS_

== CORMORANT

* `Lev 11:17` The little owl, the *_cormorant_*, the great owl,
* `Deu 14:17` The pelican, the vulture, the *_cormorant_*,
* `Isa 34:11` But the *_cormorant_* and the bittern shall possess it. The owl and the raven shall dwell in it. And he shall stretch out upon it the line of confusion and the stones of emptiness.
* `Zph 2:14` And flocks shall lie down in the midst of her, all the beasts of the nations. Both the *_cormorant_* and the bittern shall lodge in its upper lintels. Their voice shall sing in the windows. Desolation shall be in the thresholds, for he shall uncover the cedar work.

_4 verses containing CORMORANT_

