= JAAKOBAH - JAWS
:toc:

== JAAKOBAH

* `1Ch 4:36` Elioenai, *_Jaakobah_*, Jeshohaiah, Asaiah, Adiel, Jesimiel, Benaiah,

_1 verse containing JAAKOBAH_

== JAALA

* `Neh 7:58` The children of *_Jaala_*, the children of Darkon, the children of Giddel,

_1 verse containing JAALA_

== JAALAH

* `Ezr 2:56` The children of *_Jaalah_*, the children of Darkon, the children of Giddel,

_1 verse containing JAALAH_

== JAALAM

* `Gen 36:5` And Aholibamah bore Jeush, *_Jaalam_*, and Korah. These are the sons of Esau who were born to him in the land of Canaan.
* `Gen 36:14` And these are the sons of Aholibamah, the daughter of Anah, the daughter of Zibeon, Esau's wife, and she bore to Esau, Jeush, *_Jaalam_*, and Korah.
* `Gen 36:18` And these are the sons of Aholibamah, Esau's wife: chief Jeush, chief *_Jaalam_*, chief Korah. These are the chiefs, descendants of Aholibamah the daughter of Anah, Esau's wife.
* `1Ch 1:35` The sons of Esau: Eliphaz, Reuel, Jeush, *_Jaalam_*, and Korah.

_4 verses containing JAALAM_

== JAANAI

* `1Ch 5:12` Joel the chief, Shapham the next, *_Jaanai_*, and Shaphat in Bashan.

_1 verse containing JAANAI_

== JAAR

* `Psa 132:6` Behold, we heard of it at Ephratah. We found it in the fields of *_Jaar_*.

_1 verse containing JAAR_

== JAAREOREGIM

* `2Sa 21:19` And there was again a battle in Gob with the Philistines where Elhanan the son of *_Jaareoregim_*, a Beth-lehemite, slew the brother of Goliath the Gittite, the staff of whose spear was like a weaver's beam.

_1 verse containing JAAREOREGIM_

== JAASAU

* `Ezr 10:37` Mattaniah, Mattenai, *_Jaasau_*,

_1 verse containing JAASAU_

== JAASIEL

* `1Ch 27:21` Of the half tribe of Manasseh in Gilead, Iddo the son of Zechariah; of Benjamin, *_Jaasiel_* the son of Abner;

_1 verse containing JAASIEL_

== JAAZANIAH

* `2Ki 25:23` And when all the captains of the armies—they and their men—heard that the king of Babylon had made Gedaliah governor, they came to Gedaliah at Mizpah, even Ishmael the son of Nethaniah, Johanan the son of Careah, Seraiah the son of Tanhumeth the Netophathite, and *_Jaazaniah_* the son of a Maachathite—they and their men.
* `Jer 35:3` Then I took *_Jaazaniah_* the son of Jeremiah the son of Habaziniah, his brothers, all his sons, and the whole house of the Rechabites,
* `Ezk 8:11` And there stood before them seventy men of the elders of the house of Israel, and in the midst of them stood *_Jaazaniah_* the son of Shaphan, each with his censer in his hand, and a thick cloud of incense went up.
* `Ezk 11:1` Moreover, the Spirit lifted me up and brought me to the east-gate of the LORD'S house, which looks eastward. And behold, at the door of the gate were twenty-five men, among whom I saw *_Jaazaniah_* the son of Azur and Pelatiah the son of Benaiah, princes of the people.

_4 verses containing JAAZANIAH_

== JAAZER

* `Num 21:32` And Moses sent to explore *_Jaazer_*, and they took its villages and drove out the Amorites who were there.
* `Num 32:35` Atroth, Shophan, *_Jaazer_*, Jogbehah,

_2 verses containing JAAZER_

== JAAZIAH

* `1Ch 24:26` The sons of Merari were Mahli and Mushi. The son of *_Jaaziah_*: Beno.
* `1Ch 24:27` The sons of Merari by *_Jaaziah_*: Beno, Shoham, Zaccur, and Ibri.

_2 verses containing JAAZIAH_

== JAAZIEL

* `1Ch 15:18` And with them their brothers of the second degree: Zechariah, Ben, *_Jaaziel_*, Shemiramoth, Jehiel, Unni, Eliab, Benaiah, Maaseiah, Mattithiah, Elipheleh, Mikneiah, Obed-edom, and Jeiel, the gatekeepers.

_1 verse containing JAAZIEL_

== JABAL

* `Gen 4:20` And Adah bore *_Jabal_*. He was the father of those who dwell in tents and of those who have livestock.

_1 verse containing JABAL_

== JABBOK

* `Gen 32:22` And he arose that night and took his two wives, his two women-servants, and his eleven sons and passed over the ford of the *_Jabbok_*.
* `Num 21:24` And Israel smote him with the edge of the sword and possessed his land from Arnon to *_Jabbok_*, even to the children of Ammon, for the border of the children of Ammon was strong.
* `Deu 2:37` Only to the land of the children of Ammon you did not come, nor to any place of the *_Jabbok_* River, nor to the cities on the mountains, nor to whatever the LORD our God had forbidden us."
* `Deu 3:16` And to the Reubenites and to the Gadites I gave from Gilead even to the Arnon River, to the middle of the valley for a border, even to the *_Jabbok_* River, which is the border of the children of Ammon,
* `Jsh 12:2` Sihon king of the Amorites, who dwelt in Heshbon and ruled from Aroer, which is upon the bank of the Arnon River, and from the middle of the river and from half Gilead, even to the *_Jabbok_* River, which is the border of the children of Ammon;
* `Jdg 11:13` And the king of the children of Ammon answered to the messengers of Jephthah, "Because Israel took away my land when they came out of Egypt, from Arnon even to *_Jabbok_*, and to the Jordan. Now therefore, restore those lands again peaceably."
* `Jdg 11:22` And they possessed all the borders of the Amorites, from Arnon even to *_Jabbok_*, and from the wilderness even to the Jordan.

_7 verses containing JABBOK_

== JABESH

* `Jdg 21:8` And they said, "Who from among the tribes of Israel did not come up to Mizpeh to the LORD?" And behold, no one came to the camp from *_Jabesh_*-gilead to the assembly.
* `Jdg 21:9` For the people were numbered, and behold, there were none of the inhabitants of *_Jabesh_*-gilead there.
* `Jdg 21:10` And the congregation sent there twelve thousand men of the most valiant, and commanded them, saying, "Go and smite the inhabitants of *_Jabesh_*-gilead with the edge of the sword, along with the women and the children.
* `Jdg 21:12` And they found among the inhabitants of *_Jabesh_*-gilead four hundred young virgins who had known no man by lying with any male, and they brought them to the camp to Shiloh, which is in the land of Canaan.
* `Jdg 21:14` And Benjamin came back at that time. And they gave them the women which they had saved alive from the women of *_Jabesh_*-gilead, yet they did not suffice them.
* `1Sa 11:1` Then Nahash the Ammonite came up and encamped against *_Jabesh_*-gilead. And all the men of *_Jabesh_* said to Nahash, "Make a covenant with us, and we will serve you."
* `1Sa 11:3` And the elders of *_Jabesh_* said to him, "Give us seven days respite so that we may send messengers to all the borders of Israel. And then, if there is no man to save us, we will come out to you."
* `1Sa 11:5` And behold, Saul came after the herd out of the field, and Saul said, "What ails the people so that they weep?" And they told him the tidings of the men of *_Jabesh_*.
* `1Sa 11:9` And they said to the messengers who came, "Thus you shall say to the men of *_Jabesh_*-gilead: 'Tomorrow by the time the sun is hot, you shall have help.'" And the messengers came and declared it to the men of *_Jabesh_*, and they were glad.
* `1Sa 11:10` Therefore, the men of *_Jabesh_* said, "Tomorrow we will come out to you, and you shall do with us all that seems good to you."
* `1Sa 31:11` And when the inhabitants of *_Jabesh_*-gilead heard of that which the Philistines had done to Saul,
* `1Sa 31:12` All the valiant men arose and went all night, took the body of Saul and the bodies of his sons from the wall of Beth-shan, and came to *_Jabesh_* and burnt them there.
* `1Sa 31:13` And they took their bones and buried them under a tree at *_Jabesh_* and fasted seven days.
* `2Sa 2:4` And the men of Judah came, and there they anointed David king over the house of Judah. And they told David, saying, "The men of *_Jabesh_*-gilead were those who buried Saul."
* `2Sa 2:5` And David sent messengers to the men of *_Jabesh_*-gilead and said to them, "Blessed are you of the LORD in that you have shown this kindness to your lord, even to Saul, and have buried him.
* `2Sa 21:12` And David went and took the bones of Saul and the bones of Jonathan his son from the men of *_Jabesh_*-gilead who had stolen them from the street of Beth-shan, where the Philistines had hanged them when the Philistines had slain Saul in Gilboa.
* `2Ki 15:10` And Shallum the son of *_Jabesh_* conspired against him, smote him before the people, slew him, and reigned in his stead.
* `2Ki 15:13` Shallum the son of *_Jabesh_* began to reign in the thirty-ninth year of Uzziah king of Judah, and he reigned a full month in Samaria.
* `2Ki 15:14` For Menahem the son of Gadi went up from Tirzah, came to Samaria, smote Shallum the son of *_Jabesh_* in Samaria, slew him, and reigned in his stead.
* `1Ch 10:11` And when all *_Jabesh_*-gilead heard all that the Philistines had done to Saul,
* `1Ch 10:12` They arose—all the valiant men—and took away the body of Saul and the bodies of his sons, brought them to *_Jabesh_*, buried their bones under the oak in *_Jabesh_*, and fasted seven days.

_21 verses containing JABESH_

== JABESH-GILEAD

* `Jdg 21:8` And they said, "Who from among the tribes of Israel did not come up to Mizpeh to the LORD?" And behold, no one came to the camp from *_Jabesh-gilead_* to the assembly.
* `Jdg 21:9` For the people were numbered, and behold, there were none of the inhabitants of *_Jabesh-gilead_* there.
* `Jdg 21:10` And the congregation sent there twelve thousand men of the most valiant, and commanded them, saying, "Go and smite the inhabitants of *_Jabesh-gilead_* with the edge of the sword, along with the women and the children.
* `Jdg 21:12` And they found among the inhabitants of *_Jabesh-gilead_* four hundred young virgins who had known no man by lying with any male, and they brought them to the camp to Shiloh, which is in the land of Canaan.
* `Jdg 21:14` And Benjamin came back at that time. And they gave them the women which they had saved alive from the women of *_Jabesh-gilead_*, yet they did not suffice them.
* `1Sa 11:1` Then Nahash the Ammonite came up and encamped against *_Jabesh-gilead_*. And all the men of Jabesh said to Nahash, "Make a covenant with us, and we will serve you."
* `1Sa 11:9` And they said to the messengers who came, "Thus you shall say to the men of *_Jabesh-gilead_*: 'Tomorrow by the time the sun is hot, you shall have help.'" And the messengers came and declared it to the men of Jabesh, and they were glad.
* `1Sa 31:11` And when the inhabitants of *_Jabesh-gilead_* heard of that which the Philistines had done to Saul,
* `2Sa 2:4` And the men of Judah came, and there they anointed David king over the house of Judah. And they told David, saying, "The men of *_Jabesh-gilead_* were those who buried Saul."
* `2Sa 2:5` And David sent messengers to the men of *_Jabesh-gilead_* and said to them, "Blessed are you of the LORD in that you have shown this kindness to your lord, even to Saul, and have buried him.
* `2Sa 21:12` And David went and took the bones of Saul and the bones of Jonathan his son from the men of *_Jabesh-gilead_* who had stolen them from the street of Beth-shan, where the Philistines had hanged them when the Philistines had slain Saul in Gilboa.
* `1Ch 10:11` And when all *_Jabesh-gilead_* heard all that the Philistines had done to Saul,

_12 verses containing JABESH-GILEAD_

== JABEZ

* `1Ch 2:55` And the families of the scribes who dwelt at *_Jabez_*: the Tirathites, the Shimeathites, and Suchathites. These are the Kenites who came from Hemath, the father of the house of Rechab.
* `1Ch 4:9` And *_Jabez_* was more honorable than his brothers. And his mother called his name *_Jabez_*, saying, "Because I bore him with sorrow."
* `1Ch 4:10` And *_Jabez_* called on the God of Israel, saying, "Oh that you would bless me indeed and enlarge my border, and that your hand might be with me, and that you would keep me from evil so that it may not grieve me!" And God granted him that which he requested.

_3 verses containing JABEZ_

== JABIN

* `Jsh 11:1` And it came to pass when *_Jabin_* king of Hazor had heard those things, that he sent to Jobab king of Madon, to the king of Shimron, to the king Achshaph,
* `Jdg 4:2` And the LORD sold them into the hand of *_Jabin_* king of Canaan who reigned in Hazor, the captain of whose host was Sisera, who dwelt in Harosheth of the Gentiles.
* `Jdg 4:7` And I will draw out to you Sisera the captain of *_Jabin_*'s army, along with his chariots and his multitude, at the Kishon River, and I will deliver him into your hand'?"
* `Jdg 4:17` But Sisera fled away on his feet to the tent of Jael the wife of Heber the Kenite, for there was peace between *_Jabin_* the king of Hazor and the house of Heber the Kenite.
* `Jdg 4:23` So God subdued on that day *_Jabin_* the king of Canaan before the children of Israel.
* `Jdg 4:24` And the hand of the children of Israel prospered and prevailed against *_Jabin_* the king of Canaan until they had destroyed *_Jabin_* king of Canaan.
* `Psa 83:9` Do to them as to the Midianites, as to Sisera and to *_Jabin_* at the brook of Kison,

_7 verses containing JABIN_

== JABNEEL

* `Jsh 15:11` And the border went out to the side of Ekron northward. And the border was drawn to Shicron, passed along to mount Baalah, and went out to *_Jabneel_*. And the terminations of the border were at the sea.
* `Jsh 19:33` And their border was from Heleph, from Allon to Zaanannim, Adami, Nekeb, and *_Jabneel_*, to Lakum; and the limits thereof were at the Jordan;

_2 verses containing JABNEEL_

== JABNEH

* `2Ch 26:6` And he went forth and warred against the Philistines and broke down the wall of Gath, the wall of *_Jabneh_*, and the wall of Ashdod, and built cities around Ashdod and among the Philistines.

_1 verse containing JABNEH_

== JACHAN

* `1Ch 5:13` And their brothers of the house of their fathers were Michael, Meshullam, Sheba, Jorai, *_Jachan_*, Zia, and Heber, seven.

_1 verse containing JACHAN_

== JACHIN

* `Gen 46:10` And the sons of Simeon: Jemuel, Jamin, Ohad, *_Jachin_*, Zohar, and Shaul the son of a Canaanitish woman.
* `Exo 6:15` And the sons of Simeon: Jemuel, Jamin, Ohad, *_Jachin_*, Zohar, and Shaul the son of a Canaanitish woman. These are the families of Simeon.
* `Num 26:12` The sons of Simeon after their families: of Nemuel, the family of the Nemuelites; of Jamin, the family of the Jaminites; of *_Jachin_*, the family of the Jachinites;
* `1Ki 7:21` And he set up the pillars in the porch of the temple. And he set up the right pillar and called its name *_Jachin_*, and he set up the left pillar and called its name Boaz.
* `1Ch 9:10` And of the priests: Jedaiah, Jehoiarib, *_Jachin_*,
* `1Ch 24:17` The twenty-first to *_Jachin_*, the twenty-second to Gamul,
* `2Ch 3:17` And he erected the pillars before the temple: one on the right hand and the other on the left. And he called the name of the one on the right hand *_Jachin_* and the name of the one on the left Boaz.
* `Neh 11:10` Of the priests: Jedaiah the son of Joiarib, *_Jachin_*;

_8 verses containing JACHIN_

== JACHINITES

* `Num 26:12` The sons of Simeon after their families: of Nemuel, the family of the Nemuelites; of Jamin, the family of the Jaminites; of Jachin, the family of the *_Jachinites_*;

_1 verse containing JACHINITES_

== JACINTH

* `Exo 28:19` And the third row a *_jacinth_*, an agate, and an amethyst.
* `Exo 39:12` The third row, a *_jacinth_*, an agate, and an amethyst;
* `Rev 9:17` And thus I saw the horses in the vision and those who sat on them, having breast-plates of fire, of *_jacinth_*, and brimstone. And the heads of the horses were like the heads of lions, and out of their mouths issued fire, smoke, and brimstone.
* `Rev 21:20` The fifth, sardonyx; the sixth, sardius; the seventh, chrysolite; the eighth, beryl; the ninth, a topaz; the tenth, a chrysoprase; the eleventh, a *_jacinth_*; and the twelfth, an amethyst.

_4 verses containing JACINTH_

== JACKALS

* `Job 30:29` I am a brother to *_jackals_* and a companion to owls.
* `Psa 44:19` Though you have severely broken us in the place of *_jackals_* and covered us with the shadow of death.
* `Isa 13:22` And the wolves shall cry in their desolate houses, and *_jackals_* in their pleasant palaces. And her time is near to come, and her days shall not be prolonged.
* `Isa 34:13` And thorns shall come up in her palaces, nettles and brambles in her fortresses, and it shall be a habitation of *_jackals_* and a court for owls.
* `Isa 35:7` And the parched ground shall become a pool, and the thirsty land springs of water. In the habitation of *_jackals_*, where each lay, there shall be grass with reeds and rushes.
* `Isa 43:20` The beast of the field shall honor me, the *_jackals_* and the owls, because I give waters in the wilderness and rivers in the desert to give drink to my people, my chosen.
* `Jer 9:11` And I will make Jerusalem heaps and a den of *_jackals_*, and I will make the cities of Judah desolate without an inhabitant."
* `Jer 10:22` The voice of tidings, behold, it comes with a great commotion from the north country to make the cities of Judah desolate and a den of *_jackals_*.
* `Jer 14:6` And the wild donkeys stood in the high places, they snuffed up the wind like *_jackals_*. Their eyes failed because there was no grass.
* `Jer 49:33` "And Hazor shall be a dwelling for *_jackals_* and a desolation forever. No man shall abide there, nor any son of man dwell in it."
* `Jer 51:37` And Babylon shall become heaps, a dwelling-place for *_jackals_*, an astonishment, and a hissing, without an inhabitant.
* `Lam 4:3` [GIMEL] Even the *_jackals_* draw out the breast to nurse their young ones. The daughter of my people has become cruel, like the ostriches in the wilderness.
* `Mic 1:8` Therefore, I will wail and howl. I will go stripped and naked. I will make a wailing like the *_jackals_* and mourning as the owls.
* `Mal 1:3` And I hated Esau, and laid his mountains and his heritage waste for the *_jackals_* of the wilderness."

_14 verses containing JACKALS_

== JACOB

* `Gen 25:26` And after that, his brother was born, and his hand took hold of Esau's heel. And his name was called *_Jacob_*. And Isaac was sixty years old when she bore them.
* `Gen 25:27` And the boys grew. And Esau was a skillful hunter, a man of the field, and *_Jacob_* was a plain man dwelling in tents.
* `Gen 25:28` And Isaac loved Esau because he ate his wild game, but Rebekah loved *_Jacob_*.
* `Gen 25:29` And *_Jacob_* boiled pottage, and Esau came from the field and he was faint.
* `Gen 25:30` And Esau said to *_Jacob_*, "Feed me, I pray you, with that same red pottage, for I am faint." Therefore, his name was called Edom.
* `Gen 25:31` And *_Jacob_* said, "Sell to me this day your birth-right."
* `Gen 25:33` And *_Jacob_* said, "Swear to me this day." And he swore to him and sold his birth-right to *_Jacob_*.
* `Gen 25:34` Then *_Jacob_* gave Esau bread and pottage of lentils, and he ate and drank and rose and went his way. Thus Esau despised his birth-right.
* `Gen 27:6` And Rebekah spoke to *_Jacob_* her son, saying, "Behold, I heard your father speak to Esau your brother, saying,
* `Gen 27:11` And *_Jacob_* said to Rebekah his mother, "Behold, Esau my brother is a hairy man, and I am a smooth man.
* `Gen 27:15` And Rebekah took fine clothing of her eldest son Esau, which was with her in the house, and put it upon *_Jacob_* her younger son.
* `Gen 27:17` And she gave the savory food and the bread which she had prepared into the hand of her son *_Jacob_*.
* `Gen 27:19` And *_Jacob_* said to his father, "I am Esau your first-born. I have done according as you told me. Arise, I pray you, sit and eat some of my wild game so that your soul may bless me."
* `Gen 27:21` And Isaac said to *_Jacob_*, "Come near, I pray you, so that I may feel you, my son, whether you are my very son Esau or not."
* `Gen 27:22` And *_Jacob_* went near to Isaac his father. And he felt him and said, "The voice is *_Jacob_*'s voice, but the hands are the hands of Esau."
* `Gen 27:30` And it came to pass as soon as Isaac had made an end of blessing *_Jacob_*, and *_Jacob_* had scarcely gone out from the presence of Isaac his father, that Esau his brother came in from his hunting.
* `Gen 27:36` And he said, "Is he not rightly named *_Jacob_*? For he has supplanted me twice: he took away my birth-right, and behold, now he has taken away my blessing." And he said, "Have you not reserved a blessing for me?"
* `Gen 27:41` And Esau hated *_Jacob_* because of the blessing with which his father blessed him. And Esau said in his heart, "The days of mourning for my father are at hand. Then I will slay my brother *_Jacob_*."
* `Gen 27:42` And these words of Esau her elder son were told to Rebekah. And she sent and called *_Jacob_* her younger son and said to him, "Behold, your brother Esau, as concerning you, comforts himself, purposing to kill you.
* `Gen 27:46` And Rebekah said to Isaac, "I am weary of my life because of the daughters of Heth. If *_Jacob_* takes a wife from the daughters of Heth, such as these, who are from the daughters of the land, what good will my life do me?"
* `Gen 28:1` And Isaac called *_Jacob_*, blessed him, and charged him, and said to him, "You shall not take a wife from the daughters of Canaan.
* `Gen 28:5` And Isaac sent away *_Jacob_*. And he went to Padan-aram, to Laban, son of Bethuel the Syrian, the brother of Rebekah, *_Jacob_*'s and Esau's mother.
* `Gen 28:6` When Esau saw that Isaac had blessed *_Jacob_* and sent him away to Padan-aram to take for himself a wife from there, and that as he blessed him, he gave him a charge, saying, "You shall not take a wife from the daughters of Canaan,"
* `Gen 28:7` And that *_Jacob_* obeyed his father and his mother and had gone to Padan-aram,
* `Gen 28:10` And *_Jacob_* went out from Beer-sheba and went toward Haran.
* `Gen 28:16` And *_Jacob_* awoke out of his sleep and he said, "Surely the LORD is in this place, and I did not know it."
* `Gen 28:18` And *_Jacob_* rose early in the morning and took the stone that he had put for his head-rest, set it up for a pillar, and poured oil on top of it.
* `Gen 28:20` And *_Jacob_* vowed a vow, saying, "If God will be with me, keep me in this way that I go, and give me bread to eat and clothing to put on,
* `Gen 29:1` Then *_Jacob_* went on his journey and came into the land of the people of the east.
* `Gen 29:4` And *_Jacob_* said to them, "My brothers, where are you from?" And they said, "We are from Haran."
* `Gen 29:10` And it came to pass when *_Jacob_* saw Rachel, the daughter of Laban his mother's brother, and the sheep of Laban his mother's brother, that *_Jacob_* went near and rolled the stone from the well's mouth and watered the flock of Laban his mother's brother.
* `Gen 29:11` And *_Jacob_* kissed Rachel and lifted up his voice and wept.
* `Gen 29:12` And *_Jacob_* told Rachel that he was her father's brother and that he was Rebekah's son. And she ran and told her father.
* `Gen 29:13` And it came to pass when Laban heard the tidings of *_Jacob_* his sister's son, that he ran to meet him, embraced him, kissed him, and brought him to his house. And he told Laban all these things.
* `Gen 29:15` And Laban said to *_Jacob_*, "Because you are my brother, should you therefore serve me for nothing? Tell me, what shall your wages be?"
* `Gen 29:18` And *_Jacob_* loved Rachel and said, "I will serve you seven years for Rachel your younger daughter."
* `Gen 29:20` And *_Jacob_* served seven years for Rachel, and they seemed to him only a few days because of the love he had for her.
* `Gen 29:21` And *_Jacob_* said to Laban, "Give me my wife (for my days are fulfilled) so that I may go in to her."
* `Gen 29:28` And *_Jacob_* did so and fulfilled her week. And he gave him Rachel, his daughter, for a wife also.
* `Gen 30:1` And when Rachel saw that she bore *_Jacob_* no children, Rachel envied her sister and said to *_Jacob_*, "Give me children, or else I die."
* `Gen 30:2` And *_Jacob_*'s anger was kindled against Rachel and he said, "Am I in God's stead, who has withheld from you the fruit of the womb?"
* `Gen 30:4` And she gave him Bilhah her servant for a wife, and *_Jacob_* went in to her.
* `Gen 30:5` And Bilhah conceived and bore *_Jacob_* a son.
* `Gen 30:7` And Bilhah, Rachel's servant, conceived again and bore *_Jacob_* a second son.
* `Gen 30:9` When Leah saw that she had ceased bearing, she took Zilpah her servant and gave her to *_Jacob_* for a wife.
* `Gen 30:10` And Zilpah, Leah's servant, bore *_Jacob_* a son.
* `Gen 30:12` And Zilpah, Leah's servant, bore *_Jacob_* a second son.
* `Gen 30:16` And *_Jacob_* came from the field in the evening, and Leah went out to meet him and said, "You must come in to me. For surely I have hired you with my son's mandrakes." And he lay with her that night.
* `Gen 30:17` And God listened to Leah, and she conceived and bore *_Jacob_* a fifth son.
* `Gen 30:19` And Leah conceived again and bore *_Jacob_* a sixth son.
* `Gen 30:25` And it came to pass when Rachel had borne Joseph, that *_Jacob_* said to Laban, "Send me away so that I may go to my own place and to my country.
* `Gen 30:31` And he said, "What shall I give you?" And *_Jacob_* said, "You shall not give me anything. If you will do this thing for me, I will again feed and keep your flock.
* `Gen 30:36` And he set three days' journey between himself and *_Jacob_*. And *_Jacob_* fed the rest of Laban's flocks.
* `Gen 30:37` And *_Jacob_* took for himself rods of green poplar, hazel, and plane-tree, and peeled white streaks in them and made the white appear which was in the rods.
* `Gen 30:40` And *_Jacob_* separated the lambs, and set the faces of the flocks toward the striped and all the brown in the flock of Laban. And he put his own flocks by themselves, and did not put them with Laban's flock.
* `Gen 30:41` And it came to pass whenever the stronger flock conceived, that *_Jacob_* laid the rods before the eyes of the flock in the gutters so that they might conceive among the rods.
* `Gen 30:42` But when the flock was feeble, he did not put them in. So the feebler were Laban's, and the stronger *_Jacob_*'s.
* `Gen 31:1` And he heard the words of Laban's sons, saying, "*_Jacob_* has taken away all that was our father's, and from that which was our father's he has obtained all this glory."
* `Gen 31:2` And *_Jacob_* beheld the countenance of Laban, and behold, it was not toward him as before.
* `Gen 31:3` And the LORD said to *_Jacob_*, "Return to the land of your fathers and to your kindred, and I will be with you."
* `Gen 31:4` And *_Jacob_* sent and called Rachel and Leah into the field where his flock was,
* `Gen 31:11` And the angel of God spoke to me in a dream, saying, '*_Jacob_*.' And I said, 'Here I am.'
* `Gen 31:17` Then *_Jacob_* arose and set his sons and his wives upon camels.
* `Gen 31:20` And *_Jacob_* deceived Laban the Syrian, in that he did not tell him that he was about to depart.
* `Gen 31:22` And it was told to Laban on the third day that *_Jacob_* had fled.
* `Gen 31:24` And God came to Laban, the Syrian, in a dream by night and said to him, "Take heed that you do not speak to *_Jacob_* either good or bad."
* `Gen 31:25` Then Laban overtook *_Jacob_*. Now *_Jacob_* had pitched his tent on the mountain, and Laban, with his brothers, pitched on the mountain of Gilead.
* `Gen 31:26` And Laban said to *_Jacob_*, "What have you done that you have deceived me and carried away my daughters as captives taken with the sword?
* `Gen 31:29` It is in the power of my hand to do you hurt, but the God of your father spoke to me last night, saying, 'Take heed that you do not speak to *_Jacob_* either good or bad.'
* `Gen 31:31` And *_Jacob_* answered and said to Laban, "Because I was afraid, for I thought it may be that you would take your daughters from me by force.
* `Gen 31:32` With whomever you find your gods, do not let him live. Before our brothers, discern what is yours with me and take it." For *_Jacob_* did not know that Rachel had stolen them.
* `Gen 31:33` And Laban went into *_Jacob_*'s tent, into Leah's tent, and into the two women-servants' tents, but he did not find them. Then he went out of Leah's tent and entered into Rachel's tent.
* `Gen 31:36` And *_Jacob_* was angry and chided with Laban. And *_Jacob_* answered and said to Laban, "What is my trespass? What is my sin that you have so eagerly pursued after me?
* `Gen 31:43` And Laban answered and said to *_Jacob_*, "These daughters are my daughters, these children are my children, the flocks are my flocks, and all that you see is mine. But what can I do this day to these daughters of mine, or to their children which they have borne?
* `Gen 31:45` And *_Jacob_* took a stone and set it up for a pillar.
* `Gen 31:46` And *_Jacob_* said to his brothers, "Gather stones." And they took stones and made a heap, and they ate there upon the heap.
* `Gen 31:47` And Laban called it Jegar-sahadutha, but *_Jacob_* called it Galeed.
* `Gen 31:51` And Laban said to *_Jacob_*, "Behold this heap and behold this pillar which I have set between you and me.
* `Gen 31:53` May the God of Abraham, and the God of Nahor, the God of their father, judge between us." And *_Jacob_* swore by the Fear of his father Isaac.
* `Gen 31:54` Then *_Jacob_* offered sacrifice upon the mountain and called his brothers to eat bread. And they ate bread and stayed all night on the mountain.
* `Gen 32:1` And *_Jacob_* went on his way, and the angels of God met him.
* `Gen 32:2` And when *_Jacob_* saw them, he said, "This is God's host." And he called the name of that place Mahanaim.
* `Gen 32:3` And *_Jacob_* sent messengers before him to Esau his brother, to the land of Seir, the country of Edom.
* `Gen 32:4` And he commanded them, saying, "Thus you shall speak to my lord Esau: 'Your servant *_Jacob_* says thus: "I have sojourned with Laban and stayed there until now.
* `Gen 32:6` And the messengers returned to *_Jacob_*, saying, "We came to your brother Esau, and he is also coming to meet you, and four hundred men are with him."
* `Gen 32:7` Then *_Jacob_* was greatly afraid and distressed. And he divided the people who were with him, along with the flocks, herds, and camels, into two bands,
* `Gen 32:9` And *_Jacob_* said, "O God of my father Abraham, and God of my father Isaac, the LORD who said to me, 'Return to your country and to your kindred, and I will deal well with you,'
* `Gen 32:18` Then you shall say, 'They are your servant *_Jacob_*'s. It is a present sent to my lord Esau. And behold he is also behind us.'"
* `Gen 32:20` And say moreover, 'Behold, your servant *_Jacob_* is behind us.'" For he said, "I will appease him with the present that goes before me, and afterward, I will see his face. Perhaps he will accept me."
* `Gen 32:24` And *_Jacob_* was left alone. And there a man wrestled with him until the breaking of the day.
* `Gen 32:25` And when [the man] saw that he did not prevail against him, he touched the hollow of [*_Jacob_*'s] thigh, and the hollow of *_Jacob_*'s thigh was out of joint as he wrestled with him.
* `Gen 32:26` And [the man] said, "Let me go, for the day breaks." And [*_Jacob_*] said, "I will not let you go unless you bless me."
* `Gen 32:27` And [the man] said to him, "What is your name?" And he said, "*_Jacob_*."
* `Gen 32:28` And he said, "Your name shall no longer be called *_Jacob_*, but Israel. For as a prince you have power with God and with men, and have prevailed."
* `Gen 32:29` And *_Jacob_* asked him and said, "Tell me, I pray you, your name." And he said, "Why is it that you ask for my name?" And he blessed him there.
* `Gen 32:30` And *_Jacob_* called the name of the place Peniel, saying, "For I have seen God face to face, and my life is preserved."
* `Gen 32:32` Therefore, the children of Israel do not eat of the sinew which shrunk, which is upon the hollow of the thigh, to this day, because he touched the hollow of *_Jacob_*'s thigh in the sinew that shrunk.
* `Gen 33:1` And *_Jacob_* lifted up his eyes and looked, and behold, Esau came, and with him four hundred men. And he divided the children between Leah, Rachel, and the two women-servants.
* `Gen 33:10` And *_Jacob_* said, "No, I pray you, if now I have found grace in your sight, then receive my present at my hand. For therefore I have seen your face as though I had seen the face of God, and you have been pleased with me.
* `Gen 33:17` And *_Jacob_* journeyed to Succoth and built himself a house and made booths for his livestock. Therefore, the name of the place is called Succoth.
* `Gen 33:18` And *_Jacob_* came to Shalem, a city of Shechem, which is in the land of Canaan, when he came from Padan-aram, and pitched his tent before the city.
* `Gen 34:1` And Dinah the daughter of Leah, which she bore to *_Jacob_*, went out to see the daughters of the land.
* `Gen 34:3` And his soul cleaved to Dinah the daughter of *_Jacob_*, and he loved the young woman and spoke kindly to the young woman.
* `Gen 34:5` And *_Jacob_* heard that he had defiled Dinah his daughter. But his sons were with his livestock in the field, and *_Jacob_* held his peace until they had come.
* `Gen 34:6` And Hamor the father of Shechem went out to *_Jacob_* to speak with him.
* `Gen 34:7` And the sons of *_Jacob_* came from the field when they heard it, and the men were grieved and were very angry because he had wrought folly in Israel in lying with *_Jacob_*'s daughter, which thing ought not to be done.
* `Gen 34:13` And the sons of *_Jacob_* answered Shechem and Hamor his father deceitfully and said (because he had defiled Dinah their sister),
* `Gen 34:19` And the young man did not defer to do the thing because he had delight in *_Jacob_*'s daughter. And he was more honorable than all the house of his father.
* `Gen 34:25` And it came to pass on the third day, when they were sore, that two of the sons of *_Jacob_*, Simeon and Levi, Dinah's brothers, each took his sword and came upon the city boldly and slew all the males.
* `Gen 34:27` The sons of *_Jacob_* came upon the slain and plundered the city because they had defiled their sister.
* `Gen 34:30` And *_Jacob_* said to Simeon and Levi, "You have troubled me to make me odious among the inhabitants of the land, among the Canaanites and the Perizzites. And I being few in number, they will assemble themselves against me and slay me, and I shall be destroyed—I and my house."
* `Gen 35:1` And God said to *_Jacob_*, "Arise, go up to Beth-el and dwell there. And make there an altar to God, who appeared to you when you fled from the face of Esau your brother."
* `Gen 35:2` Then *_Jacob_* said to his household and to all who were with him, "Put away the strange gods which are among you, and be clean and change your garments.
* `Gen 35:4` And they gave to *_Jacob_* all the strange gods which were in their hand and the earrings which were in their ears. And *_Jacob_* hid them under the oak which was by Shechem.
* `Gen 35:5` And they journeyed. And the terror of God was on the cities that were around them, and they did not pursue after the sons of *_Jacob_*.
* `Gen 35:6` So *_Jacob_* came to Luz, which is in the land of Canaan (that is Beth-el)—he and all the people who were with him.
* `Gen 35:9` And God appeared to *_Jacob_* again when he came out of Padan-aram, and he blessed him.
* `Gen 35:10` And God said to him, "Your name is *_Jacob_*. Your name shall not be called *_Jacob_* anymore, but Israel shall be your name." And he called his name Israel.
* `Gen 35:14` And *_Jacob_* set up a pillar in the place where he talked with him, even a pillar of stone, and he poured a drink-offering thereon and he poured oil thereon.
* `Gen 35:15` And *_Jacob_* called the name of the place where God spoke with him Beth-el.
* `Gen 35:20` And *_Jacob_* set a pillar on her grave. That is the pillar of Rachel's grave to this day.
* `Gen 35:22` And it came to pass when Israel dwelt in that land, that Reuben went and lay with Bilhah his father's concubine. And Israel heard it. Now the sons of *_Jacob_* were twelve.
* `Gen 35:23` The sons of Leah: Reuben (*_Jacob_*'s first-born), Simeon, Levi, Judah, Issachar, and Zebulun.
* `Gen 35:26` And the sons of Zilpah, Leah's servant: Gad and Asher. These are the sons of *_Jacob_* who were born to him in Padan-aram.
* `Gen 35:27` And *_Jacob_* came to Isaac his father at Mamre, near Kirjath-arbah (which is Hebron), where Abraham and Isaac sojourned.
* `Gen 35:29` And Isaac expired and died and was gathered to his people, being old and full of days. And his sons Esau and *_Jacob_* buried him.
* `Gen 36:6` And Esau took his wives, his sons, his daughters, all the persons of his house, his livestock, all his beasts, and all his substance which he had acquired in the land of Canaan, and went into the country from the face of his brother *_Jacob_*.
* `Gen 37:1` And *_Jacob_* dwelt in the land in which his father was a stranger, in the land of Canaan.
* `Gen 37:2` These are the generations of *_Jacob_*. Joseph being seventeen years old was feeding the flock with his brothers, and the boy was with the sons of Bilhah and with the sons of Zilpah, his father's wives. And Joseph brought to his father their evil report.
* `Gen 37:34` And *_Jacob_* rent his clothes, put sackcloth on his loins, and mourned for his son many days.
* `Gen 42:1` Now when *_Jacob_* saw that there was grain in Egypt, *_Jacob_* said to his sons, "Why do you look at one another?"
* `Gen 42:4` But Benjamin, Joseph's brother, *_Jacob_* did not send with his brothers, for he said, "Lest perhaps mischief befalls him."
* `Gen 42:29` And they came to *_Jacob_* their father in the land of Canaan and told him all that befell them, saying,
* `Gen 42:36` And *_Jacob_* their father said to them, "You have bereaved me. Joseph is no more, Simeon is no more, and you will take Benjamin away. All these things are against me."
* `Gen 45:25` And they went up from Egypt and came into the land of Canaan to *_Jacob_* their father,
* `Gen 45:26` And told him, saying, "Joseph is still alive and he is governor over all the land of Egypt." And *_Jacob_*'s heart fainted, for he did not believe them.
* `Gen 45:27` And they told him all the words of Joseph which he had said to them. And when he saw the wagons which Joseph had sent to carry him, the spirit of *_Jacob_* their father revived.
* `Gen 46:2` And God spoke to Israel in the visions of the night and said, "*_Jacob_*, *_Jacob_*." And he said, "Here I am."
* `Gen 46:5` And *_Jacob_* rose up from Beer-sheba. And the sons of Israel carried *_Jacob_* their father, their little ones, and their wives in the wagons which Pharaoh had sent to carry him.
* `Gen 46:6` And they took their livestock and their goods which they had acquired in the land of Canaan and came into Egypt—*_Jacob_* and all his family with him:
* `Gen 46:8` And these are the names of the children of Israel who came into Egypt—*_Jacob_* and his sons: Reuben, *_Jacob_*'s first-born.
* `Gen 46:15` These are the sons of Leah, which she bore to *_Jacob_* in Padan-aram, with his daughter Dinah. All the souls of his sons and his daughters were thirty-three.
* `Gen 46:18` These are the sons of Zilpah, whom Laban gave to Leah his daughter. And these she bore to *_Jacob_*, even sixteen souls.
* `Gen 46:19` The sons of Rachel *_Jacob_*'s wife: Joseph and Benjamin.
* `Gen 46:22` These are the sons of Rachel who were born to *_Jacob_*. All the souls were fourteen.
* `Gen 46:25` These are the sons of Bilhah, whom Laban gave to Rachel his daughter, and she bore these to *_Jacob_*. All the souls were seven.
* `Gen 46:26` All the souls who came with *_Jacob_* into Egypt, who came out of his loins, besides *_Jacob_*'s sons' wives, all the souls were sixty-six.
* `Gen 46:27` And the sons of Joseph who were born to him in Egypt were two souls. All the souls of the house of *_Jacob_*, who came into Egypt, were seventy.
* `Gen 47:7` And Joseph brought in *_Jacob_* his father and set him before Pharaoh, and *_Jacob_* blessed Pharaoh.
* `Gen 47:8` And Pharaoh said to *_Jacob_*, "How old are you?"
* `Gen 47:9` And *_Jacob_* said to Pharaoh, "The days of the years of my pilgrimage are one hundred and thirty years. Few and evil have been the days of the years of my life, nor have they attained to the days of the years of the life of my fathers in the days of their pilgrimage."
* `Gen 47:10` And *_Jacob_* blessed Pharaoh and went out from before Pharaoh.
* `Gen 47:28` And *_Jacob_* lived in the land of Egypt for seventeen years. So the whole age of *_Jacob_* was one hundred and forty-seven years.
* `Gen 48:2` And someone told *_Jacob_*, and said, "Behold, your son Joseph comes to you." And Israel strengthened himself and sat upon the bed.
* `Gen 48:3` And *_Jacob_* said to Joseph, "God Almighty appeared to me at Luz in the land of Canaan and blessed me,
* `Gen 49:1` And *_Jacob_* called to his sons and said, "Assemble yourselves so that I may tell you that which shall befall you in the last days.
* `Gen 49:2` "Assemble yourselves and hear, sons of *_Jacob_*, and listen to Israel your father.
* `Gen 49:7` Cursed is their anger, for it was fierce, and their wrath, for it was cruel. I will divide them in *_Jacob_* and scatter them in Israel.
* `Gen 49:24` But his bow remained in strength, and the arms of his hands were made strong by the hands of the mighty God of *_Jacob_* (from there is the shepherd, the stone of Israel),
* `Gen 49:33` And when *_Jacob_* had made an end of commanding his sons, he drew his feet into the bed and expired, and was gathered to his people.
* `Gen 50:24` And Joseph said to his brothers, "I die, but God will surely visit you and bring you out of this land to the land which he swore to Abraham, to Isaac, and to *_Jacob_*."
* `Exo 1:1` Now these are the names of the children of Israel who came into Egypt, every man and his household came with *_Jacob_*:
* `Exo 1:5` And all the souls who descended from *_Jacob_* were seventy souls, and Joseph was in Egypt already.
* `Exo 2:24` And God heard their groaning, and God remembered his covenant with Abraham, with Isaac, and with *_Jacob_*.
* `Exo 3:6` Moreover, he said, "I am the God of your father, the God of Abraham, the God of Isaac, and the God of *_Jacob_*." And Moses hid his face because he was afraid to look upon God.
* `Exo 3:15` And God said again to Moses, "Thus you shall say to the children of Israel: 'The LORD God of your fathers, the God of Abraham, the God of Isaac, and the God of *_Jacob_* has sent me to you.' This is my name forever, and this is my memorial to all generations.
* `Exo 3:16` Go and assemble the elders of Israel and say to them, 'The LORD God of your fathers, the God of Abraham, of Isaac, and of *_Jacob_* appeared to me, saying, "I have surely visited you and seen that which is done to you in Egypt.
* `Exo 4:5` "This is so that they may believe that the LORD God of their fathers, the God of Abraham, the God of Isaac, and the God of *_Jacob_* has appeared to you."
* `Exo 6:3` And I appeared to Abraham, to Isaac, and to *_Jacob_* by the name of God Almighty, but by my name, YAHWEH, I was not known to them.
* `Exo 6:8` And I will bring you into the land, concerning which I swore to give it to Abraham, to Isaac, and to *_Jacob_*, and I will give it to you for a heritage. I am the LORD.'"
* `Exo 19:3` And Moses went up to God, and the LORD called to him from the mountain, saying, "Thus you shall say to the house of *_Jacob_*, and tell the children of Israel:
* `Exo 33:1` And the LORD said to Moses, "Depart and go up from here—you and the people which you have conducted from the land of Egypt—to the land which I swore to Abraham, to Isaac, and to *_Jacob_*, saying, 'To your offspring I will give it.'
* `Lev 26:42` Then I will remember my covenant with *_Jacob_*, and I will also remember my covenant with Isaac and also my covenant with Abraham, and I will remember the land.
* `Num 23:7` And he took up his parable and said, "Balak the king of Moab has brought me from Aram, out of the mountains of the east, saying, 'Come, curse *_Jacob_* for me, and come, defy Israel.'
* `Num 23:10` Who can count the dust of *_Jacob_* and the number of the fourth part of Israel? Let me die the death of the righteous, and let my last end be like his!"
* `Num 23:21` He has not beheld iniquity in *_Jacob_*, neither has he seen perverseness in Israel. The LORD his God is with him, and the shout of a king is among them.
* `Num 23:23` Surely there is no enchantment against *_Jacob_*, neither is there any divination against Israel. According to this time it shall be said of *_Jacob_* and of Israel, 'What God has wrought!'
* `Num 24:5` How beautiful your tents are, O *_Jacob_*, and your tabernacles, O Israel!
* `Num 24:17` I shall see him, but not now. I shall behold him, but not near. There shall come a Star out of *_Jacob_*, and a Scepter shall rise out of Israel and shall smite the corners of Moab and destroy all the children of Sheth.
* `Num 24:19` Out of *_Jacob_* shall come he who has dominion, and shall destroy him who remains of the city."
* `Num 32:11` 'Surely none of the men who came up from Egypt, from twenty years old and upward, shall see the land which I swore to Abraham, to Isaac, and to *_Jacob_* because they have not wholly followed me,
* `Deu 1:8` Behold, I have set the land before you. Go in and possess the land which the LORD swore to your fathers, Abraham, Isaac, and *_Jacob_*, to give to them and to their posterity after them.'
* `Deu 6:10` "And it shall be, when the LORD your God has brought you into the land which he swore to your fathers, to Abraham, to Isaac, and to *_Jacob_*, to give you great and beautiful cities which you did not build,
* `Deu 9:5` Not for your righteousness or for the uprightness of your heart do you go to possess their land, but for the wickedness of these nations the LORD your God drives them out from before you so that he may perform the word which the LORD swore to your fathers, Abraham, Isaac, and *_Jacob_*.
* `Deu 9:27` Remember your servants, Abraham, Isaac, and *_Jacob_*. Do not look to the stubbornness of this people, nor to their wickedness, nor to their sin,
* `Deu 29:13` So that he may establish you today for a people to himself, and that he may be to you a God, as he has said to you and as he has sworn to your fathers, to Abraham, to Isaac, and to *_Jacob_*.
* `Deu 30:20` To love the LORD your God, to obey his voice, and to cleave to him (for he is your life and the length of your days), so that you may dwell in the land which the LORD swore to your fathers, to Abraham, to Isaac, and to *_Jacob_*, to give them."
* `Deu 32:9` For the LORD'S portion is his people. *_Jacob_* is the lot of his inheritance.
* `Deu 33:4` Moses commanded us a law, even the inheritance of the congregation of *_Jacob_*.
* `Deu 33:10` They shall teach *_Jacob_* your judgments and Israel your law. They shall put incense before you and whole burnt sacrifice upon your altar.
* `Deu 33:28` Israel then shall dwell in safety alone. The fountain of *_Jacob_* shall be upon a land of grain and wine. His heavens shall also drop down dew.
* `Deu 34:4` And the LORD said to him, "This is the land which I swore to Abraham, to Isaac, and to *_Jacob_*, saying, 'I will give it to your offspring.' I have caused you to see it with your eyes, but you shall not go over there."
* `Jsh 24:4` And I gave *_Jacob_* and Esau to Isaac. And I gave mount Seir to Esau to possess it, but *_Jacob_* and his children went down into Egypt.
* `Jsh 24:32` And the bones of Joseph which the children of Israel brought out of Egypt, they buried in Shechem in a parcel of ground which *_Jacob_* bought of the sons of Hamor the father of Shechem for one hundred pieces of silver. And it became the inheritance of the children of Joseph.
* `1Sa 12:8` When *_Jacob_* had come into Egypt, and your fathers cried to the LORD, the LORD sent Moses and Aaron, who brought forth your fathers from Egypt and made them dwell in this place.
* `2Sa 23:1` Now these are the last words of David. David the son of Jesse and the man who was raised on high, the anointed of the God of *_Jacob_* and the sweet psalmist of Israel, said,
* `1Ki 18:31` And Elijah took twelve stones, according to the number of the tribes of the sons of *_Jacob_*, to whom the word of the LORD came, saying, "Israel shall be your name."
* `2Ki 13:23` And the LORD was gracious to them, had compassion on them, and had respect to them, because of his covenant with Abraham, Isaac, and *_Jacob_*, and would not destroy them, neither did he reject them from his presence to this day.
* `2Ki 17:34` To this day they do according to the former manners. They do not fear the LORD, neither do they follow their statutes, follow their ordinances, or follow the law and commandment which the LORD commanded the children of *_Jacob_*, whom he named Israel,
* `1Ch 16:13` O offspring of Israel his servant, children of *_Jacob_*, his chosen ones.
* `1Ch 16:17` And which he confirmed to *_Jacob_* for a law and to Israel for an everlasting covenant,
* `Psa 14:7` Oh that the salvation of Israel would come out of Zion! When the LORD brings back the captivity of his people, *_Jacob_* shall rejoice and Israel shall be glad.
* `Psa 20:1` [To the Chief Musician. A Psalm of David.] May the LORD hear you in the day of trouble. May the name of the God of *_Jacob_* defend you,
* `Psa 22:23` You who fear the LORD, praise him. All you offspring of *_Jacob_*, glorify him. And fear him, all you offspring of Israel.
* `Psa 24:6` This is the generation of those who seek him, who seek your face, O *_Jacob_*. [Selah.]
* `Psa 44:4` You are my King, O God. Command deliverances for *_Jacob_*.
* `Psa 46:7` The LORD of hosts is with us. The God of *_Jacob_* is our refuge. [Selah.]
* `Psa 46:11` The LORD of hosts is with us. The God of *_Jacob_* is our refuge. [Selah.]
* `Psa 47:4` He shall choose our inheritance for us, the excellence of *_Jacob_* whom he loved. [Selah.]
* `Psa 53:6` O that the salvation of Israel would come out of Zion! When God brings back the captivity of his people, *_Jacob_* shall rejoice and Israel shall be glad.
* `Psa 59:13` Consume them in wrath, consume them, so that they may not be. And let them know that God rules in *_Jacob_* to the ends of the earth. [Selah.]
* `Psa 75:9` But I will declare it forever. I will sing praises to the God of *_Jacob_*.
* `Psa 76:6` At your rebuke, O God of *_Jacob_*, both the chariot and horse are cast into a dead sleep.
* `Psa 77:15` You have with your arm redeemed your people, the sons of *_Jacob_* and Joseph. [Selah.]
* `Psa 78:5` For he established a testimony in *_Jacob_* and appointed a law in Israel, which he commanded our fathers, that they should make them known to their children,
* `Psa 78:21` Therefore, the LORD heard this and was angry. Thus a fire was kindled against *_Jacob_*, and anger also came up against Israel,
* `Psa 78:71` From following the ewes great with young he brought him to feed *_Jacob_* his people and Israel his inheritance.
* `Psa 79:7` For they have devoured *_Jacob_* and laid waste his dwelling-place.
* `Psa 81:1` [To the Chief Musician upon Gittith. A Psalm of Asaph.] Sing aloud to God our strength. Make a joyful noise to the God of *_Jacob_*.
* `Psa 81:4` For this was a statute for Israel and a law of the God of *_Jacob_*.
* `Psa 84:8` O LORD God of hosts, hear my prayer. Give ear, O God of *_Jacob_*. [Selah.]
* `Psa 85:1` [To the Chief Musician. A Psalm for the Sons of Korah.] LORD, you have been favorable to your land. You have brought back the captivity of *_Jacob_*.
* `Psa 87:2` The LORD loves the gates of Zion more than all the dwellings of *_Jacob_*.
* `Psa 94:7` Yet they say, "The LORD will not see, neither will the God of *_Jacob_* regard it."
* `Psa 99:4` The king's strength also loves judgment. You establish equity. You execute judgment and righteousness in *_Jacob_*.
* `Psa 105:6` O you offspring of Abraham his servant, you children of *_Jacob_* his chosen.
* `Psa 105:10` And confirmed the same to *_Jacob_* for a law and to Israel for an everlasting covenant,
* `Psa 105:23` Israel also came into Egypt, and *_Jacob_* sojourned in the land of Ham.
* `Psa 114:1` When Israel went out of Egypt, the house of *_Jacob_* from a people of a foreign language,
* `Psa 114:7` Tremble, you earth, at the presence of the Lord, at the presence of the God of *_Jacob_*,
* `Psa 132:2` How he swore to the LORD and vowed to the mighty God of *_Jacob_*:
* `Psa 132:5` Until I find a place for the LORD, a habitation for the mighty God of *_Jacob_*."
* `Psa 135:4` For the LORD has chosen *_Jacob_* for himself, Israel for his peculiar treasure.
* `Psa 146:5` Happy is he who has the God of *_Jacob_* for his help, whose hope is in the LORD his God,
* `Psa 147:19` He shows his word to *_Jacob_*, his statutes and his judgments to Israel.
* `Isa 2:3` And many people shall go and say, "Come, and let us go up to the mountain of the LORD, to the house of the God of *_Jacob_*. And he will teach us his ways, and we will walk in his paths." For out of Zion the law shall go forth, and the word of the LORD from Jerusalem.
* `Isa 2:5` O house of *_Jacob_*, come, and let us walk in the light of the LORD.
* `Isa 2:6` Therefore, you have forsaken your people the house of *_Jacob_*, because they are replenished from the east and are soothsayers like the Philistines, and they please themselves in the children of strangers.
* `Isa 8:17` And I will wait upon the LORD, who hides his face from the house of *_Jacob_*, and I will look for him.
* `Isa 9:8` The Lord sent a word into *_Jacob_* and it has fallen upon Israel.
* `Isa 10:20` And it shall come to pass in that day, that the remnant of Israel and those who have escaped of the house of *_Jacob_* shall no longer again lean upon him who smote them, but shall lean upon the LORD, the Holy One of Israel, in truth.
* `Isa 10:21` The remnant shall return, even the remnant of *_Jacob_*, to the mighty God.
* `Isa 14:1` For the LORD will have mercy on *_Jacob_* and will again choose Israel and set them in their own land. And the strangers shall be joined with them and they shall cleave to the house of *_Jacob_*.
* `Isa 17:4` "And in that day it shall come to pass, that the glory of *_Jacob_* shall be diminished and the fatness of his flesh shall become lean.
* `Isa 27:6` He shall cause those who descend from *_Jacob_* to take root. Israel shall blossom and bud and fill the face of the world with fruit.
* `Isa 27:9` By this therefore, the iniquity of *_Jacob_* shall be purged, and this is all the fruit to take away his sin: when he makes all the stones of the altar like chalk-stones that are beaten apart, the groves and images shall not stand up.
* `Isa 29:22` Therefore, thus says the LORD, who redeemed Abraham, concerning the house of *_Jacob_*: "*_Jacob_* shall not now be ashamed, neither shall his face now become pale.
* `Isa 29:23` But when he sees his children, the work of my hands, in the midst of him, they shall sanctify my name and sanctify the Holy One of *_Jacob_*, and shall fear the God of Israel.
* `Isa 40:27` Why do you say, O *_Jacob_*, and speak, O Israel, "My way is hid from the LORD, and my judgment is passed over by my God"?
* `Isa 41:8` "But you, Israel, are my servant, *_Jacob_* whom I have chosen, the offspring of Abraham my friend,
* `Isa 41:14` Do not fear, you worm *_Jacob_* and you men of Israel. I will help you," says the LORD, "and your Redeemer is the Holy One of Israel.
* `Isa 41:21` Produce your cause," says the LORD. "Bring forth your strong reasons," says the King of *_Jacob_*.
* `Isa 42:24` Who gave *_Jacob_* for plunder and Israel to the robbers? Was it not the LORD, he against whom we have sinned? For they would not walk in his ways, neither were they obedient to his law.
* `Isa 43:1` But now thus says the LORD who created you, O *_Jacob_*, and he who formed you, O Israel: "Do not fear, for I have redeemed you. I have called you by your name. You are mine.
* `Isa 43:22` Yet you have not called upon me, O *_Jacob_*, but you have been weary of me, O Israel.
* `Isa 43:28` Therefore, I have profaned the princes of the sanctuary, and have given *_Jacob_* to the curse and Israel to reproaches."
* `Isa 44:1` "Yet now hear, O *_Jacob_* my servant, and Israel, whom I have chosen.
* `Isa 44:2` Thus says the LORD who made you and formed you from the womb, who will help you: 'Do not fear, O *_Jacob_*, my servant, and you, Jesurun, whom I have chosen,
* `Isa 44:5` One shall say, 'I am the LORD'S,' and another shall call himself by the name of *_Jacob_*, and another shall write with his hand, 'To the LORD,' and surname himself by the name of Israel.
* `Isa 44:21` "Remember these, O *_Jacob_* and Israel, for you are my servant. I have formed you. You are my servant. O Israel, you shall not be forgotten by me.
* `Isa 44:23` Sing, O heavens, for the LORD has done it. Shout, you lower parts of the earth. Break forth into singing, you mountains, O forest, and every tree therein, for the LORD has redeemed *_Jacob_* and glorified himself in Israel.
* `Isa 45:4` For *_Jacob_* my servant's sake and Israel my elect, I have even called you by your name. I have surnamed you, though you have not known me.
* `Isa 45:19` I have not spoken in secret, in a dark place of the earth. I have not said to the offspring of *_Jacob_*, 'Seek me in vain.' I, the LORD, speak righteousness. I declare things that are right.
* `Isa 46:3` "Listen to me, O house of *_Jacob_*, and all the remnant of the house of Israel, which are borne by me from the birth, which are carried from the womb.
* `Isa 48:1` "Hear this, O house of *_Jacob_*, who are called by the name of Israel and have come forth out of the waters of Judah, who swear by the name of the LORD and make mention of the God of Israel, but not in truth nor in righteousness.
* `Isa 48:12` Listen to me, O *_Jacob_*, and Israel my called. I am he. I am the first. I am also the last.
* `Isa 48:20` Go forth from Babylon. Flee from the Chaldeans. With a voice of singing declare, tell this, and utter it even to the end of the earth, saying, "The LORD has redeemed his servant *_Jacob_*."
* `Isa 49:5` And now, the LORD says, who formed me from the womb to be his servant to bring *_Jacob_* back to him, though Israel is not gathered (yet I shall be glorious in the eyes of the LORD, and my God shall be my strength),
* `Isa 49:6` And he said, "It is a light thing that you should be my servant to raise up the tribes of *_Jacob_* and to restore the preserved of Israel. I will also give you as a light to the Gentiles so that you may be my salvation to the end of the earth."
* `Isa 49:26` And I will feed those who oppress you with their own flesh, and they shall be drunken with their own blood, as with sweet wine. And all flesh shall know that I, the LORD, am your Savior and your Redeemer, the mighty One of *_Jacob_*."
* `Isa 58:1` "Cry aloud, do not spare. Lift up your voice like a trumpet. Show my people their transgression, and the house of *_Jacob_* their sins.
* `Isa 58:14` Then you shall delight yourself in the LORD, and I will cause you to ride upon the high places of the earth and feed you with the heritage of *_Jacob_* your father. For the mouth of the LORD has spoken it."
* `Isa 59:20` "And the Redeemer will come to Zion and to those in *_Jacob_* who turn from transgression," says the LORD.
* `Isa 60:16` You shall also drink the milk of the Gentiles and shall nurse from the breast of kings. And you shall know that I, the LORD, am your Savior and your Redeemer, the mighty one of *_Jacob_*.
* `Isa 65:9` And I will bring forth offspring out of *_Jacob_*, and out of Judah an inheritor of my mountains. And my elect shall inherit it and my servants shall dwell there.
* `Jer 2:4` Hear the word of the LORD, O house of *_Jacob_* and all the families of the house of Israel.
* `Jer 5:20` "Declare this in the house of *_Jacob_* and publish it in Judah, saying,
* `Jer 10:16` The portion of *_Jacob_* is not like them, for he is the former of all things, and Israel is the rod of his inheritance. The LORD of hosts is his name.
* `Jer 10:25` Pour out your fury upon the heathen who do not know you and upon the families who do not call on your name, for they have eaten up *_Jacob_*. They have devoured him and consumed him, and have made his habitation desolate.
* `Jer 30:7` Alas! For that day is great so that none is like it. It is even the time of *_Jacob_*'s trouble, but he shall be saved out of it.
* `Jer 30:10` 'Therefore, do not fear, O my servant *_Jacob_*,' says the LORD, 'neither be dismayed, O Israel, for behold, I will save you from afar and your offspring from the land of their captivity, and *_Jacob_* shall return and be in rest and quiet, and no one shall make him afraid.
* `Jer 30:18` Thus says the LORD: 'Behold, I will bring back the captivity of *_Jacob_*'s tents and have mercy on his dwelling places, and the city shall be built upon her own heap, and the palace shall remain after its manner.
* `Jer 31:7` For thus says the LORD: "Sing with gladness for *_Jacob_* and shout among the chief of the nations. Publish, praise, and say, 'O LORD, save your people, the remnant of Israel.'
* `Jer 31:11` For the LORD has redeemed *_Jacob_* and ransomed him from the hand of him who was stronger than he is.
* `Jer 33:26` Then I will cast away the offspring of *_Jacob_* and David my servant so that I will not take any of his offspring to be rulers over the offspring of Abraham, Isaac, and *_Jacob_*. For I will cause their captivity to return and have mercy on them.'"
* `Jer 46:27` "But do not fear, O my servant *_Jacob_*, and do not be dismayed, O Israel, for behold, I will save you from afar and your offspring from the land of their captivity. And *_Jacob_* shall return and be in rest and at ease, and no one shall make him afraid.
* `Jer 46:28` Do not fear, O *_Jacob_* my servant," says the LORD, "for I am with you. I will make a full end of all the nations where I have driven you, but I will not make a full end of you, but correct you in measure. Yet I will not leave you wholly unpunished."
* `Jer 51:19` The portion of *_Jacob_* is not like them, for he is the former of all things, and Israel is the rod of his inheritance. The LORD of hosts is his name.
* `Lam 1:17` [PE] Zion spreads forth her hands, and there is no one to comfort her. The LORD has commanded concerning *_Jacob_*, that his adversaries should be around him. Jerusalem has become an unclean thing among them.
* `Lam 2:2` [BET] The Lord has swallowed up all the habitations of *_Jacob_* and has not pitied. He has thrown down in his wrath the strongholds of the daughter of Judah. He has brought them down to the ground. He has polluted the kingdom and its princes.
* `Lam 2:3` [GIMEL] He has cut off in his fierce anger all the horn of Israel. He has drawn back his right hand from before the enemy, and he burned against *_Jacob_* like a flaming fire, which devours on every side.
* `Ezk 20:5` And say to them, 'Thus says the Lord GOD: "In the day when I chose Israel and lifted up my hand to the offspring of the house of *_Jacob_* and made myself known to them in the land of Egypt, when I lifted up my hand to them, saying, 'I am the LORD your God,'
* `Ezk 28:25` 'Thus says the Lord GOD: "When I have gathered the house of Israel from the people among whom they are scattered and have been sanctified in them in the sight of the heathen, they shall dwell in their land that I have given to my servant *_Jacob_*.
* `Ezk 37:25` And they shall dwell in the land that I have given to *_Jacob_* my servant, in which your fathers have dwelt, and they shall dwell in it—even they, their children, and their children's children forever. And my servant David shall be their prince forever.
* `Ezk 39:25` Therefore, thus says the Lord GOD: "Now I will bring back the captivity of *_Jacob_* and have mercy upon the whole house of Israel, and I will be jealous for my holy name.
* `Hos 10:11` And Ephraim is as a heifer that is taught and loves to tread out the grain. But I passed over upon her fair neck. I will make Ephraim to ride. Judah shall plow, and *_Jacob_* shall break his clods.
* `Hos 12:2` The LORD also has a controversy with Judah and will punish *_Jacob_* according to his ways. According to his doings he will recompense him.
* `Hos 12:12` And *_Jacob_* fled into the country of Syria. And Israel served to get a wife, and for a wife he kept sheep.
* `Amo 3:13` Hear, and testify in the house of *_Jacob_*," says the Lord GOD, the God of hosts,
* `Amo 6:8` "The Lord GOD has sworn by himself," says the LORD the God of hosts, "I abhor the excellence of *_Jacob_* and hate his palaces; therefore, I will deliver up the city with all its abundance.
* `Amo 7:2` And it came to pass, that when they had made an end of eating the grass of the land, then I said, "O Lord GOD, forgive, I implore you. By whom shall *_Jacob_* arise? For he is small."
* `Amo 7:5` Then I said, "O Lord GOD, cease, I implore you. By whom shall *_Jacob_* arise? For he is small."
* `Amo 8:7` The LORD has sworn by the excellence of *_Jacob_*, "Surely I will never forget any of their works.
* `Amo 9:8` Behold, the eyes of the Lord GOD are upon the sinful kingdom, and I will destroy it from off the face of the earth, except that I will not utterly destroy the house of *_Jacob_*," says the LORD.
* `Oba 1:10` "For your violence against your brother *_Jacob_*, shame shall cover you, and you shall be cut off forever.
* `Oba 1:17` But upon mount Zion there shall be deliverance and there shall be holiness. And the house of *_Jacob_* shall possess their possessions.
* `Oba 1:18` And the house of *_Jacob_* shall be a fire, the house of Joseph a flame, and the house of Esau for stubble, and they shall kindle in them and devour them. And there shall not be any remaining of the house of Esau." For the LORD has spoken it.
* `Mic 1:5` "All this is for the transgression of *_Jacob_* and for the sins of the house of Israel. What is the transgression of *_Jacob_*? Is it not Samaria? And what are the high places of Judah? Are they not Jerusalem?
* `Mic 2:7` Shall it be said, O house of *_Jacob_*, 'Is the Spirit of the LORD shortened? Are these his doings?' Do my words not do good to him who walks uprightly?
* `Mic 2:12` I will surely assemble, O *_Jacob_*, all of you. I will surely gather the remnant of Israel. I will put them together as the sheep of Bozrah, as the flock in the midst of their fold. They shall make great noise by reason of the multitude of men.
* `Mic 3:1` And I said, "Hear, I pray you, O heads of *_Jacob_* and you princes of the house of Israel. Is it not for you to know judgment?
* `Mic 3:8` But truly I am full of power by the Spirit of the LORD, and of judgment and of might, to declare to *_Jacob_* his transgression and to Israel his sin.
* `Mic 3:9` Hear this, I pray you, you heads of the house of *_Jacob_* and princes of the house of Israel, who abhor judgment and pervert all equity.
* `Mic 4:2` And many nations shall come and say, "Come, and let us go up to the mountain of the LORD and to the house of the God of *_Jacob_*, and he will teach us of his ways, and we will walk in his paths." For the law shall go forth from Zion and the word of the LORD from Jerusalem.
* `Mic 5:7` And the remnant of *_Jacob_* shall be in the midst of many people as a dew from the LORD, as the showers upon the grass, which do not wait for man, nor delay for the sons of men.
* `Mic 5:8` And the remnant of *_Jacob_* shall be among the Gentiles in the midst of many people as a lion among the beasts of the forest, as a young lion among the flocks of sheep, who, if he goes through, both treads down and tears in pieces, and no one can deliver.
* `Mic 7:20` You will give the truth to *_Jacob_* and the mercy to Abraham, which you have sworn to our fathers from the days of old.
* `Nah 2:2` For the LORD has turned away the excellence of *_Jacob_*, as the excellence of Israel. For the emptiers have emptied them out and marred their vine branches.
* `Mal 1:2` "I have loved you," says the LORD. Yet you say, "In what have you loved us?" "Was Esau not *_Jacob_*'s brother?" says the LORD. "Yet I loved *_Jacob_*,
* `Mal 2:12` The LORD will cut off the man who does this, the master and the scholar, out of the tabernacles of *_Jacob_*, and him who offers an offering to the LORD of hosts.
* `Mal 3:6` "For I am the LORD and I do not change; therefore, you sons of *_Jacob_* are not consumed.
* `Mth 1:2` Abraham begot Isaac, Isaac begot *_Jacob_*, *_Jacob_* begot Judah and his brothers,
* `Mth 1:15` Eliud begot Eleazar, Eleazar begot Matthan, Matthan begot *_Jacob_*,
* `Mth 1:16` And *_Jacob_* begot Joseph the husband of Mary, by whom Jesus was born, who is called Christ.
* `Mth 8:11` And I say to you, that many shall come from the east and the west and shall sit down with Abraham, Isaac, and *_Jacob_* in the kingdom of heaven.
* `Mth 22:32` 'I am the God of Abraham, the God of Isaac, and the God of *_Jacob_*'? God is not the God of the dead, but of the living."
* `Mrk 12:26` And concerning the dead, that they rise, have you not read in the book of Moses, how in the bush God spoke to him, saying, 'I am the God of Abraham, the God of Isaac, and the God of *_Jacob_*'?
* `Luk 1:33` And he will reign over the house of *_Jacob_* forever, and of his kingdom there will be no end."
* `Luk 3:34` Who was the son of *_Jacob_*, who was the son of Isaac, who was the son of Abraham, who was the son of Terah, who was the son of Nahor,
* `Luk 13:28` There shall be weeping and gnashing of teeth when you see Abraham, Isaac, *_Jacob_*, and all the prophets in the kingdom of God, and you yourselves excluded.
* `Luk 20:37` But that the dead are raised, even Moses showed it at the bush when he calls the Lord 'the God of Abraham, the God of Isaac, and the God of *_Jacob_*.'
* `Jhn 4:5` Then he comes to a city of Samaria, which is called Sychar, near the parcel of ground that *_Jacob_* gave to his son Joseph.
* `Jhn 4:6` Now *_Jacob_*'s well was there. Jesus therefore, being wearied with his journey, sat down on the well. And it was about the sixth hour.
* `Jhn 4:12` Are you greater than our father *_Jacob_* who gave us the well and drank from it himself, with his children and his livestock?"
* `Act 3:13` The God of Abraham, of Isaac, and of *_Jacob_*, the God of our fathers, has glorified his Son Jesus, whom you delivered up and denied in the presence of Pilate, when he was determined to let him go.
* `Act 7:8` And he gave him the covenant of circumcision. And so Abraham begot Isaac and circumcised him on the eighth day. Then Isaac begot *_Jacob_*, and *_Jacob_* begot the twelve patriarchs.
* `Act 7:12` But when *_Jacob_* heard that there was grain in Egypt, he sent out our fathers first.
* `Act 7:14` Then Joseph sent and called his father *_Jacob_* and all his kindred to him, seventy-five souls.
* `Act 7:15` So *_Jacob_* went down into Egypt and died—he and our fathers.
* `Act 7:32` Saying, 'I am the God of your fathers, the God of Abraham, the God of Isaac, and the God of *_Jacob_*.' Then Moses trembled and dared not behold.
* `Act 7:46` Who found favor before God and asked to find a tabernacle for the God of *_Jacob_*.
* `Rom 9:13` As it is written, "*_Jacob_* I have loved, but Esau I have hated."
* `Rom 11:26` And so all Israel shall be saved, as it is written, "The Deliverer will come out of Zion, and he will turn away ungodliness from *_Jacob_*.
* `Heb 11:9` By faith he sojourned in the land of promise, as in a foreign country, dwelling in tabernacles with Isaac and *_Jacob_*, the heirs with him of the same promise.
* `Heb 11:20` By faith Isaac blessed *_Jacob_* and Esau concerning things to come.
* `Heb 11:21` By faith *_Jacob_*, when he was dying, blessed both the sons of Joseph "and worshiped while leaning upon the top of his staff."

_346 verses containing JACOB_

== JADA

* `1Ch 2:28` And the sons of Onam were Shammai and *_Jada_*. And the sons of Shammai: Nadab and Abishur.
* `1Ch 2:32` And the sons of *_Jada_* the brother of Shammai: Jether and Jonathan. And Jether died without children.

_2 verses containing JADA_

== JADAU

* `Ezr 10:43` Of the sons of Nebo: Jeiel, Mattithiah, Zabad, Zebina, *_Jadau_*, Joel, and Benaiah.

_1 verse containing JADAU_

== JADDUA

* `Neh 10:21` Meshezabeel, Zadok, *_Jaddua_*,
* `Neh 12:11` Joiada begot Jonathan, and Jonathan begot *_Jaddua_*.
* `Neh 12:22` As for the Levites, in the days of Eliashib, Joiada, Johanan, and *_Jaddua_*, the chiefs of the fathers were recorded, and also the priests in the reign of Darius the Persian.

_3 verses containing JADDUA_

== JADON

* `Neh 3:7` And next to them Melatiah the Gibeonite and *_Jadon_* the Meronothite, the men of Gibeon and of Mizpah, repaired to the throne of the governor on this side of the river.

_1 verse containing JADON_

== JAEL

* `Jdg 4:17` But Sisera fled away on his feet to the tent of *_Jael_* the wife of Heber the Kenite, for there was peace between Jabin the king of Hazor and the house of Heber the Kenite.
* `Jdg 4:18` And *_Jael_* went out to meet Sisera, and said to him, "Turn aside, my lord, turn aside to me. Do not fear." And when he had turned aside to her into the tent, she covered him with a mantle.
* `Jdg 4:21` Then *_Jael_*, Heber's wife, took a nail of the tent and took a hammer in her hand, went softly to him, and smote the nail into his temples and fastened it into the ground, for he was fast asleep and weary. So he died.
* `Jdg 4:22` And behold, as Barak pursued Sisera, *_Jael_* came out to meet him and said to him, "Come, and I will show you the man whom you seek." And when he came into her tent, behold, Sisera lay dead, and the nail was in his temples.
* `Jdg 5:6` "In the days of Shamgar the son of Anath, in the days of *_Jael_*, the highways were unoccupied, and the travelers walked through by-ways.
* `Jdg 5:24` "Blessed above women *_Jael_* the wife of Heber the Kenite shall be, blessed she shall be above women in the tent.

_6 verses containing JAEL_

== JAGUR

* `Jsh 15:21` And the uttermost cities of the tribe of the children of Judah toward the border of Edom southward were Kabzeel, Eder, *_Jagur_*,

_1 verse containing JAGUR_

== JAHATH

* `1Ch 4:2` And Reaiah the son of Shobal begot *_Jahath_*, and *_Jahath_* begot Ahumai and Lahad. These are the families of the Zorathites.
* `1Ch 6:20` Of Gershom: Libni his son, *_Jahath_* his son, Zimmah his son,
* `1Ch 6:43` The son of *_Jahath_*, the son of Gershom, the son of Levi;
* `1Ch 23:10` And the sons of Shimei were *_Jahath_*, Zina, Jeush and Beriah. These four were the sons of Shimei.
* `1Ch 23:11` And *_Jahath_* was the chief and Zizah the second, but Jeush and Beriah did not have many sons; therefore, they were in one reckoning according to their father's house.
* `1Ch 24:22` Of the Izharites: Shelomoth. Of the sons of Shelomoth: *_Jahath_*.
* `2Ch 34:12` And the men did the work faithfully. And their overseers were *_Jahath_* and Obadiah, the Levites, of the sons of Merari; and Zechariah and Meshullam, of the sons of the Kohathites, to superintend it; and others of the Levites, all who had skill in instruments of music.

_7 verses containing JAHATH_

== JAHAZ

* `Num 21:23` And Sihon would not allow Israel to pass through his border. But Sihon collected all his people and went out against Israel into the wilderness, and he came to *_Jahaz_* and fought against Israel.
* `Deu 2:32` "Then Sihon came out against us—he and all his people—to fight at *_Jahaz_*.
* `Jdg 11:20` But Sihon did not trust Israel to pass through his border. So Sihon collected all his people, encamped in *_Jahaz_*, and fought against Israel.
* `Isa 15:4` And Heshbon shall cry, along with Elealeh. Their voice shall be heard even to *_Jahaz_*; therefore, the armed soldiers of Moab shall cry out. His life shall be grievous to him.
* `Jer 48:34` "From the cry of Heshbon even to Elealeh, and even to *_Jahaz_*, they have uttered their voice, from Zoar even to Horonaim, as a heifer of three years old. For the waters also of Nimrim shall be desolate.

_5 verses containing JAHAZ_

== JAHAZA

* `Jsh 13:18` *_Jahaza_*, Kedemoth, Mephaath,

_1 verse containing JAHAZA_

== JAHAZAH

* `Jsh 21:36` And out of the tribe of Reuben, Bezer with its suburbs, *_Jahazah_* with its suburbs,
* `Jer 48:21` "And judgment has come upon the plain country: upon Holon, upon *_Jahazah_*, upon Mephaath,

_2 verses containing JAHAZAH_

== JAHAZIAH

* `Ezr 10:15` Only Jonathan the son of Asahel and *_Jahaziah_* the son of Tikvah were employed about this matter. And Meshullam and Shabbethai the Levite helped them.

_1 verse containing JAHAZIAH_

== JAHAZIEL

* `1Ch 12:4` Ismaiah the Gibeonite (a mighty man among the thirty, and over the thirty), and Jeremiah, *_Jahaziel_*, Johanan, Josabad the Gederathite,
* `1Ch 16:6` Benaiah and *_Jahaziel_* the priests with trumpets continually before the ark of the covenant of God.
* `Ezr 8:5` Of the sons of Shechaniah: the son of *_Jahaziel_*, and with him three hundred males.

_3 verses containing JAHAZIEL_

== JAHDAI

* `1Ch 2:47` And the sons of *_Jahdai_*: Regem, Jotham, Geshan, Pelet, Ephah, and Shaaph.

_1 verse containing JAHDAI_

== JAHDIEL

* `1Ch 5:24` And these were the heads of the house of their fathers: even Epher, Ishi, Eliel, Azriel, Jeremiah, Hodaviah, and *_Jahdiel_*, mighty men of valor, famous men, and heads of the house of their fathers.

_1 verse containing JAHDIEL_

== JAHDO

* `1Ch 5:14` These are the children of Abihail the son of Huri, the son of Jaroah, the son of Gilead, the son of Michael, the son of Jeshishai, the son of *_Jahdo_*, the son of Buz.

_1 verse containing JAHDO_

== JAHLEEL

* `Gen 46:14` And the sons of Zebulun: Sered, Elon, and *_Jahleel_*.
* `Num 26:26` Of the sons of Zebulun after their families: of Sered, the family of the Sardites; of Elon, the family of the Elonites; of *_Jahleel_*, the family of the Jahleelites.

_2 verses containing JAHLEEL_

== JAHLEELITES

* `Num 26:26` Of the sons of Zebulun after their families: of Sered, the family of the Sardites; of Elon, the family of the Elonites; of Jahleel, the family of the *_Jahleelites_*.

_1 verse containing JAHLEELITES_

== JAHMAI

* `1Ch 7:2` And the sons of Tola: Uzzi, Rephaiah, Jeriel, *_Jahmai_*, Jibsam, and Shemuel, heads of their father's house, namely, of Tola. They were valiant men of might in their generations whose number was in the days of David twenty-two thousand and six hundred.

_1 verse containing JAHMAI_

== JAHZAH

* `1Ch 6:78` And on the other side of the Jordan by Jericho, on the east side of the Jordan, were given them out of the tribe of Reuben, Bezer in the wilderness with its suburbs, *_Jahzah_* with its suburbs,

_1 verse containing JAHZAH_

== JAHZEEL

* `Gen 46:24` And the sons of Naphtali: *_Jahzeel_*, Guni, Jezer, and Shillem.
* `Num 26:48` Of the sons of Naphtali after their families: of *_Jahzeel_*, the family of the Jahzeelites; of Guni, the family of the Gunites;

_2 verses containing JAHZEEL_

== JAHZEELITES

* `Num 26:48` Of the sons of Naphtali after their families: of Jahzeel, the family of the *_Jahzeelites_*; of Guni, the family of the Gunites;

_1 verse containing JAHZEELITES_

== JAHZERAH

* `1Ch 9:12` And Adaiah the son of Jeroham, the son of Pashur, the son of Malchijah; and Maasiai the son of Adiel, the son of *_Jahzerah_*, the son of Meshullam, the son of Meshillemith, the son of Immer;

_1 verse containing JAHZERAH_

== JAHZIEL

* `1Ch 7:13` The sons of Naphtali: *_Jahziel_*, Guni, Jezer, and Shallum, the sons of Bilhah.

_1 verse containing JAHZIEL_

== JAILER

* `Act 16:23` And when they had laid many stripes upon them, they cast them into prison, charging the *_jailer_* to keep them safely,

_1 verse containing JAILER_

== JAIR

* `Num 32:41` And *_Jair_* the son of Manasseh went and took its small towns and called them Havoth-*_jair_*.
* `Deu 3:14` *_Jair_* the son of Manasseh took all the country of Argob to the borders of Geshuri and Maachathi and called them after his own name, Bashan-havoth-*_jair_*, to this day.
* `Jsh 13:30` And their border was from Mahanaim, all Bashan, all the kingdom of Og king of Bashan, and all the towns of *_Jair_*, which are in Bashan, sixty cities;
* `Jdg 10:3` And after him arose *_Jair_*, a Gileadite, and judged Israel for twenty-two years.
* `Jdg 10:4` And he had thirty sons who rode on thirty donkey colts, and they had thirty cities, which are called Havoth-*_jair_* to this day, which are in the land of Gilead.
* `Jdg 10:5` And *_Jair_* died and was buried in Camon.
* `1Ki 4:13` The son of Geber, in Ramoth-gilead—to him pertained the towns of *_Jair_* the son of Manasseh, which are in Gilead, and also to him pertained the region of Argob, which is in Bashan, sixty great cities with walls and brazen bars;
* `1Ch 2:22` And Segub begot *_Jair_* who had twenty-three cities in the land of Gilead.
* `1Ch 2:23` And he took Geshur and Aram with the towns of *_Jair_* from them, with Kenath and its towns, even sixty cities. All these belonged to the sons of Machir, the father of Gilead.
* `1Ch 20:5` And there was war again with the Philistines. And Elhanan the son of *_Jair_* slew Lahmi the brother of Goliath the Gittite, whose spear-staff was like a weaver's beam.
* `Est 2:5` Now in the palace of Shushan there was a certain Jew, whose name was Mordecai, the son of *_Jair_*, the son of Shimei, the son of Kish, a Benjaminite,

_11 verses containing JAIR_

== JAIRITE

* `2Sa 20:26` And Ira the *_Jairite_* was also a chief minister to David.

_1 verse containing JAIRITE_

== JAIRUS

* `Mrk 5:22` And behold, there comes one of the rulers of the synagogue, *_Jairus_* by name, and when he saw him, he fell at his feet,
* `Luk 8:41` And behold, there came a man named *_Jairus_*, and he was a ruler of the synagogue. He fell down at the feet of Jesus and implored him that he would come into his house.

_2 verses containing JAIRUS_

== JAKAN

* `Deu 10:6` "And the children of Israel took their journey from Beeroth of the children of *_Jakan_* to Mosira. Aaron died there, and he was buried there. And Eleazar his son ministered in the priest's office in his stead.
* `1Ch 1:42` The sons of Ezer: Bilhan, Zavan, and *_Jakan_*. The sons of Dishan: Uz and Aran.

_2 verses containing JAKAN_

== JAKEH

* `Pro 30:1` [The words of Agur the son of *_Jakeh_*, even the prophecy. The man spoke to Ithiel, even to Ithiel and Ucal.]

_1 verse containing JAKEH_

== JAKIM

* `1Ch 8:19` And *_Jakim_*, Zichri, Zabdi,
* `1Ch 24:12` The eleventh to Eliashib, the twelfth to *_Jakim_*,

_2 verses containing JAKIM_

== JALON

* `1Ch 4:17` And the sons of Ezra were Jethur, Mered, Epher, and *_Jalon_*. Mered took a wife and she bore Miriam, Shammai, and Ishbah the father of Eshtemoa.

_1 verse containing JALON_

== JAMBRES

* `2Ti 3:8` Now as Jannes and *_Jambres_* withstood Moses, so do these also resist the truth—men corrupted in mind, reprobate concerning the faith.

_1 verse containing JAMBRES_

== JAMES

* `Mth 4:21` And going on from there, he saw two other brothers, *_James_* the son of Zebedee and John his brother, in a boat with Zebedee their father, mending their nets, and he called them.
* `Mth 10:2` Now the names of the twelve apostles are these: The first, Simon, who is called Peter, and Andrew his brother; *_James_* the son of Zebedee, and John his brother;
* `Mth 10:3` Philip, and Bartholomew; Thomas, and Matthew the tax collector; *_James_* the son of Alpheus, and Lebbeus, whose surname was Thaddeus;
* `Mth 13:55` Is this not the carpenter's son? Is his mother not called Mary? And his brothers, *_James_*, Joseph, Simon, and Judas?
* `Mth 17:1` And after six days, Jesus takes Peter, *_James_*, and John his brother, and brings them upon a high mountain separately.
* `Mth 27:56` Among whom was Mary Magdalene, Mary the mother of *_James_* and Joseph, and the mother of Zebedee's children.
* `Mrk 1:19` And when he had gone a little farther from there, he saw *_James_* the son of Zebedee and John his brother, who also were in the boat mending their nets.
* `Mrk 1:29` And immediately, when they had come out of the synagogue, they entered into the house of Simon and Andrew, with *_James_* and John.
* `Mrk 3:17` *_James_* the son of Zebedee and John the brother of *_James_* (he surnamed them Boanerges, which is, Sons of Thunder),
* `Mrk 3:18` Andrew, Philip, Bartholomew, Matthew, Thomas, *_James_* the son of Alpheus, Thaddeus, Simon the Canaanite,
* `Mrk 5:37` And he allowed no man to follow him, except Peter, *_James_*, and John the brother of *_James_*.
* `Mrk 6:3` Is this not the carpenter, the son of Mary, the brother of *_James_*, Joseph, Judas, and Simon? And are his sisters not here with us?" And they were offended at him.
* `Mrk 9:2` And after six days, Jesus takes with him Peter, *_James_*, and John, and leads them up upon a high mountain separately by themselves. And he was transfigured before them,
* `Mrk 10:35` And *_James_* and John the sons of Zebedee come to him, saying, "Master, we wish that you should do for us whatever we desire."
* `Mrk 10:41` And when the ten heard it, they began to be much displeased with *_James_* and John.
* `Mrk 13:3` And as he sat upon the Mount of Olives, over against the temple, Peter, *_James_*, John, and Andrew asked him privately,
* `Mrk 14:33` And he takes with him Peter, *_James_*, and John and began to be greatly amazed and to be very heavy,
* `Mrk 15:40` There were also women looking on at a distance, among whom were Mary Magdalene, Mary (the mother of *_James_* the younger and Joseph), Salome
* `Mrk 16:1` And when the sabbath was past, Mary Magdalene, Mary (the mother of *_James_*), and Salome had bought sweet spices so that they might come and anoint him.
* `Luk 5:10` And so were *_James_* and John the sons of Zebedee, who were partners with Simon. And Jesus said to Simon, "Do not fear. From now on you shall catch men."
* `Luk 6:14` Simon (whom he also named Peter) and Andrew his brother, *_James_* and John, Philip and Bartholomew,
* `Luk 6:15` Matthew and Thomas, *_James_* the son of Alpheus, Simon called Zelotes,
* `Luk 6:16` Judas the brother of *_James_*, and Judas Iscariot (who also was the traitor).
* `Luk 8:51` And when he came into the house, he allowed no man to go in except Peter, *_James_*, John, and the father and the mother of the girl.
* `Luk 9:28` And it came to pass, about eight days after these sayings, he took Peter, John, and *_James_* and went up upon a mountain to pray.
* `Luk 9:54` And when his disciples, *_James_* and John, saw this, they said, "Lord, do you wish that we command fire to come down from heaven and consume them, even as Elijah did?"
* `Luk 24:10` It was Mary Magdalene, Joanna, Mary the mother of *_James_*, and other women who were with them who told these things to the apostles.
* `Act 1:13` And when they had arrived, they went into the upper room where they were staying, namely, Peter, *_James_*, John, Andrew, Philip, Thomas, Bartholomew, Matthew, *_James_* the son of Alpheus, Simon Zelotes, and Judas the brother of *_James_*.
* `Act 12:2` And he killed *_James_* the brother of John with the sword.
* `Act 12:17` But he, beckoning to them with the hand to hold their peace, declared to them how the Lord had brought him out of the prison. And he said, "Go, show these things to *_James_* and to the brothers." And he departed and went into another place.
* `Act 15:13` And after they held their peace, *_James_* answered, saying, "Men, brothers, listen to me.
* `Act 21:18` And the day following Paul went in with us to *_James_*, and all the elders were present.
* `1Co 15:7` After that, he was seen by *_James_*, then by all the apostles.
* `Gal 1:19` But I saw none of the other apostles except *_James_* the Lord's brother.
* `Gal 2:9` And when *_James_*, Cephas, and John, who seemed to be pillars, perceived the grace that was given to me, they gave to Barnabas and me the right hands of fellowship so that we should go to the heathen and they to the circumcision.
* `Gal 2:12` For before some came from *_James_*, he used to eat with the Gentiles, but when they had come, he withdrew and separated himself, fearing those who were of the circumcision.
* `Jms 1:1` *_James_*, a servant of God and of the Lord Jesus Christ, to the twelve tribes which are scattered abroad: Greetings.
* `Jde 1:1` Jude, the servant of Jesus Christ and brother of *_James_*, to those who are sanctified by God the Father, preserved in Jesus Christ, and called:

_38 verses containing JAMES_

== JAMIN

* `Gen 46:10` And the sons of Simeon: Jemuel, *_Jamin_*, Ohad, Jachin, Zohar, and Shaul the son of a Canaanitish woman.
* `Exo 6:15` And the sons of Simeon: Jemuel, *_Jamin_*, Ohad, Jachin, Zohar, and Shaul the son of a Canaanitish woman. These are the families of Simeon.
* `Num 26:12` The sons of Simeon after their families: of Nemuel, the family of the Nemuelites; of *_Jamin_*, the family of the Jaminites; of Jachin, the family of the Jachinites;
* `1Ch 2:27` And the sons of Ram the first-born of Jerahmeel were Maaz, *_Jamin_*, and Eker.
* `1Ch 4:24` The sons of Simeon were Nemuel, *_Jamin_*, Jarib, Zerah, and Shaul;
* `Neh 8:7` Also Jeshua, Bani, Sherebiah, *_Jamin_*, Akkub, Shabbethai, Hodijah, Maaseiah, Kelita, Azariah, Jozabad, Hanan, Pelaiah, and the Levites caused the people to understand the law. And the people stood in their place.

_6 verses containing JAMIN_

== JAMINITES

* `Num 26:12` The sons of Simeon after their families: of Nemuel, the family of the Nemuelites; of Jamin, the family of the *_Jaminites_*; of Jachin, the family of the Jachinites;

_1 verse containing JAMINITES_

== JAMLECH

* `1Ch 4:34` And Meshobab, *_Jamlech_*, Joshah the son of Amaziah,

_1 verse containing JAMLECH_

== JANGLING

* `1Ti 1:6` From which some, having swerved, have turned aside to vain *_jangling_*,

_1 verse containing JANGLING_

== JANNA

* `Luk 3:24` Who was the son of Matthat, who was the son of Levi, who was the son of Melchi, who was the son of *_Janna_*, who was the son of Joseph,

_1 verse containing JANNA_

== JANNES

* `2Ti 3:8` Now as *_Jannes_* and Jambres withstood Moses, so do these also resist the truth—men corrupted in mind, reprobate concerning the faith.

_1 verse containing JANNES_

== JANOAH

* `2Ki 15:29` In the days of Pekah king of Israel, Tiglath-pileser king of Assyria, came and took Ijon, Abel-beth-maachah, *_Janoah_*, Kedesh, Hazor, Gilead, and Galilee, all the land of Naphtali, and carried them captive to Assyria.

_1 verse containing JANOAH_

== JANOHAH

* `Jsh 16:6` And the border went out toward the sea to Michmethah on the north side, and the border went around eastward to Taanath-shiloh, and passed by it on the east to *_Janohah_*,
* `Jsh 16:7` And it went down from *_Janohah_* to Ataroth, and to Naarath, and came to Jericho, and terminated at the Jordan.

_2 verses containing JANOHAH_

== JANUM

* `Jsh 15:53` *_Janum_*, Beth-tappuah, Aphekah,

_1 verse containing JANUM_

== JAPHETH

* `Gen 5:32` And Noah was five hundred years old, and Noah begot Shem, Ham, and *_Japheth_*.
* `Gen 6:10` And Noah begot three sons: Shem, Ham, and *_Japheth_*.
* `Gen 7:13` In the same day Noah, along with Shem, Ham, and *_Japheth_* (the sons of Noah), Noah's wife, and the three wives of his sons with them, entered into the ark—
* `Gen 9:18` And the sons of Noah who went forth from the ark were Shem, Ham, and *_Japheth_*. And Ham was the father of Canaan.
* `Gen 9:23` And Shem and *_Japheth_* took a garment, laid it upon both their shoulders, went backward, and covered the nakedness of their father. Their faces were backward and they did not see their father's nakedness.
* `Gen 9:27` God shall enlarge *_Japheth_*, and he shall dwell in the tents of Shem, and Canaan shall be his servant."
* `Gen 10:1` Now these are the generations of the sons of Noah: Shem, Ham, and *_Japheth_*. And to them sons were born after the flood.
* `Gen 10:2` The sons of *_Japheth_*: Gomer, Magog, Madai, Javan, Tubal, Meshech, and Tiras.
* `Gen 10:21` To Shem also, the father of all the children of Eber, the brother of *_Japheth_* the elder, even to him children were born.
* `1Ch 1:4` Noah, Shem, Ham, and *_Japheth_*.
* `1Ch 1:5` The sons of *_Japheth_*: Gomer, Magog, Madai, Javan, Tubal, Meshech, and Tiras.

_11 verses containing JAPHETH_

== JAPHIA

* `Jsh 10:3` Therefore, Adoni-zedec king of Jerusalem sent to Hoham king of Hebron, to Piram king of Jarmuth, to *_Japhia_* king of Lachish, and to Debir king of Eglon, saying,
* `Jsh 19:12` Turned from Sarid eastward, toward the sunrise, to the border of Chisloth-tabor, then goes out to Daberath, then goes up to *_Japhia_*;
* `2Sa 5:15` Ibhar, Elishua, Nepheg, *_Japhia_*,
* `1Ch 3:7` Nogah, Nepheg, *_Japhia_*,
* `1Ch 14:6` Nogah, Nepheg, *_Japhia_*,

_5 verses containing JAPHIA_

== JAPHLET

* `1Ch 7:32` And Heber begot *_Japhlet_*, Shomer, Hotham, and Shua their sister.
* `1Ch 7:33` And the sons of *_Japhlet_*: Pasach, Bimhal, and Ashvath. These are the children of *_Japhlet_*.

_2 verses containing JAPHLET_

== JAPHLETI

* `Jsh 16:3` And goes down westward to the border of *_Japhleti_*, to the border of Beth-horon the nether, and to Gezer, and its limits are at the sea.

_1 verse containing JAPHLETI_

== JAPHO

* `Jsh 19:46` Me-jarkon, and Rakkon, with the border before *_Japho_*.

_1 verse containing JAPHO_

== JARAH

* `1Ch 9:42` And Ahaz begot *_Jarah_*, and *_Jarah_* begot Alemeth, Azmaveth, and Zimri. And Zimri begot Moza.

_1 verse containing JARAH_

== JAREB

* `Hos 5:13` When Ephraim saw his sickness and Judah saw his wound, Ephraim went to the Assyrian and sent to king *_Jareb_*. Yet he could not heal you, nor cure you of your wound.
* `Hos 10:6` It shall also be carried to Assyria for a present to king *_Jareb_*. Ephraim shall receive shame, and Israel shall be ashamed of his own counsel.

_2 verses containing JAREB_

== JARED

* `Gen 5:15` And Mahalaleel lived sixty-five years and begot *_Jared_*.
* `Gen 5:16` And Mahalaleel lived after he begot *_Jared_* eight hundred and thirty years and begot sons and daughters.
* `Gen 5:18` And *_Jared_* lived one hundred and sixty-two years and he begot Enoch.
* `Gen 5:19` And *_Jared_* lived after he begot Enoch eight hundred years and begot sons and daughters.
* `Gen 5:20` And all the days of *_Jared_* were nine hundred and sixty-two years, and he died.
* `Luk 3:37` Who was the son of Methuselah, who was the son of Enoch, who was the son of *_Jared_*, who was the son of Mahalaleel, who was the son of Cainan,

_6 verses containing JARED_

== JARESIAH

* `1Ch 8:27` *_Jaresiah_*, Eliah, and Zichri were the sons of Jeroham.

_1 verse containing JARESIAH_

== JARHA

* `1Ch 2:34` Now Sheshan had no sons, but daughters. And Sheshan had a servant, an Egyptian, whose name was *_Jarha_*.
* `1Ch 2:35` And Sheshan gave his daughter to *_Jarha_* his servant for a wife, and she bore him Attai.

_2 verses containing JARHA_

== JARIB

* `1Ch 4:24` The sons of Simeon were Nemuel, Jamin, *_Jarib_*, Zerah, and Shaul;
* `Ezr 8:16` Then I sent for Eliezer, for Ariel, for Shemaiah, for Elnathan, for *_Jarib_*, for Elnathan, for Nathan, for Zechariah, and for Meshullam, chief men, and also for Joiarib and for Elnathan, men of understanding.
* `Ezr 10:18` And among the sons of the priests there were found some who had taken foreign wives, namely, of the sons of Jeshua the son of Jozadak and his brothers: Maaseiah, Eliezer, *_Jarib_*, and Gedaliah.

_3 verses containing JARIB_

== JARMUTH

* `Jsh 10:3` Therefore, Adoni-zedec king of Jerusalem sent to Hoham king of Hebron, to Piram king of *_Jarmuth_*, to Japhia king of Lachish, and to Debir king of Eglon, saying,
* `Jsh 10:5` Therefore, the five kings of the Amorites, the king of Jerusalem, the king of Hebron, the king of *_Jarmuth_*, the king of Lachish, and the king of Eglon assembled themselves and went up—they and all their hosts—and encamped before Gibeon and made war against it.
* `Jsh 10:23` And they did so, and brought those five kings to him out of the cave: the king of Jerusalem, the king of Hebron, the king of *_Jarmuth_*, the king of Lachish, and the king of Eglon.
* `Jsh 12:11` The king of *_Jarmuth_*, one; the king of Lachish, one;
* `Jsh 15:35` *_Jarmuth_*, Adullam, Socoh, Azekah,
* `Jsh 21:29` *_Jarmuth_* with its suburbs, and En-gannim with its suburbs; four cities.
* `Neh 11:29` At En-rimmon, at Zareah, at *_Jarmuth_*,

_7 verses containing JARMUTH_

== JAROAH

* `1Ch 5:14` These are the children of Abihail the son of Huri, the son of *_Jaroah_*, the son of Gilead, the son of Michael, the son of Jeshishai, the son of Jahdo, the son of Buz.

_1 verse containing JAROAH_

== JASHEN

* `2Sa 23:32` Eliahba the Shaalbonite, (of the sons of *_Jashen_*) Jonathan,

_1 verse containing JASHEN_

== JASHER

* `Jsh 10:13` And the sun stood still and the moon stayed until the people had avenged themselves upon their enemies. Is this not written in the book of *_Jasher_*? So the sun stood still in the midst of the heavens and did not hasten to go down about a whole day.
* `2Sa 1:18` (He also told them to teach the children of Judah the song of the bow, as it is written in the book of *_Jasher_*):

_2 verses containing JASHER_

== JASHOBEAM

* `1Ch 11:11` And this is the number of the mighty men whom David had: *_Jashobeam_* a Hachmonite, the chief of the captains. He lifted his spear against three hundred slain by him at one time.
* `1Ch 12:6` Elkanah, Jesiah, Azareel, Joezer, and *_Jashobeam_* (the Korhites),
* `1Ch 27:2` Over the first course for the first month was *_Jashobeam_* the son of Zabdiel. And in his course were twenty-four thousand.

_3 verses containing JASHOBEAM_

== JASHUB

* `Num 26:24` Of *_Jashub_*, the family of the Jashubites; of Shimron, the family of the Shimronites.
* `1Ch 7:1` Now the sons of Issachar were Tola, Puah, *_Jashub_*, and Shimron, four.
* `Ezr 10:29` And of the sons of Bani: Meshullam, Malluch, Adaiah, *_Jashub_*, Sheal, and Ramoth.
* `Isa 7:3` Then the LORD said to Isaiah, "Go forth now to meet Ahaz—you and Shear-*_jashub_* your son—at the end of the conduit of the upper pool in the highway of the fuller's field,

_4 verses containing JASHUB_

== JASHUBI-LEHEM

* `1Ch 4:22` Jokim, the men of Chozeba, Joash, Saraph who had the dominion in Moab, and *_Jashubi-lehem_*. And these records are ancient.

_1 verse containing JASHUBI-LEHEM_

== JASHUBITES

* `Num 26:24` Of Jashub, the family of the *_Jashubites_*; of Shimron, the family of the Shimronites.

_1 verse containing JASHUBITES_

== JASIEL

* `1Ch 11:47` Eliel, Obed, and *_Jasiel_* the Mesobaite.

_1 verse containing JASIEL_

== JASON

* `Act 17:5` But the Jews who did not believe, being moved with envy, took for themselves some vile fellows of the baser sort, and gathering a company, set all the city in an uproar. They assaulted the house of *_Jason_* and sought to bring them out to the people.
* `Act 17:6` And when they did not find them, they drew *_Jason_* and some brothers to the rulers of the city, crying, "These who have turned the world upside down have come here also,
* `Act 17:7` Whom *_Jason_* has received, and they all do contrary to the decrees of Caesar, saying that there is another king, Jesus."
* `Act 17:9` And when they had received a pledge from *_Jason_* and from the others, they let them go.
* `Rom 16:21` Timothy my fellow worker, and Lucius, *_Jason_*, and Sosipater my kinsmen salute you.

_5 verses containing JASON_

== JASPER

* `Exo 28:20` And the fourth row a beryl, an onyx, and a *_jasper_*. They shall be set in gold in their enclosings.
* `Exo 39:13` And the fourth row, a beryl, an onyx, and a *_jasper_*. They were enclosed in settings of gold in their enclosings.
* `Ezk 28:13` You have been in Eden the garden of God. Every precious stone was your covering: the sardius, topaz, the diamond, the beryl, the onyx, the *_jasper_*, the sapphire, the emerald, the carbuncle, and gold. The workmanship of your tambourines and of your pipes was prepared in you in the day that you were created.
* `Rev 4:3` And he who sat was in appearance like a *_jasper_* and a sardius stone. And there was a rainbow around the throne in sight like an emerald.
* `Rev 21:11` Having the glory of God. And her light was like a stone most precious, even like a *_jasper_*-stone, clear as crystal.
* `Rev 21:18` And the building of its wall was of *_jasper_*. And the city was pure gold, like clear glass.
* `Rev 21:19` And the foundations of the wall of the city were garnished with all manner of precious stones. The first foundation was *_jasper_*; the second, sapphire; the third, a chalcedony; the fourth, an emerald;

_7 verses containing JASPER_

== JASPER-STONE

* `Rev 21:11` Having the glory of God. And her light was like a stone most precious, even like a *_jasper-stone_*, clear as crystal.

_1 verse containing JASPER-STONE_

== JATHNIEL

* `1Ch 26:2` And the sons of Meshelemiah were Zechariah the first-born, Jediael the second, Zebadiah the third, *_Jathniel_* the fourth,

_1 verse containing JATHNIEL_

== JATTIR

* `Jsh 15:48` And in the mountains, Shamir, *_Jattir_*, Socoh,
* `Jsh 21:14` *_Jattir_* with its suburbs, Eshtemoa with its suburbs,
* `1Sa 30:27` To those who were in Beth-el, to those who were in south Ramoth, to those who were in *_Jattir_*,
* `1Ch 6:57` And to the sons of Aaron they gave the cities of Judah, namely, Hebron (the city of refuge), Libnah with its suburbs, *_Jattir_*, Eshtemoa with its suburbs,

_4 verses containing JATTIR_

== JAVAN

* `Gen 10:2` The sons of Japheth: Gomer, Magog, Madai, *_Javan_*, Tubal, Meshech, and Tiras.
* `Gen 10:4` And the sons of *_Javan_*: Elishah, Tarshish, Kittim, and Dodanim.
* `1Ch 1:5` The sons of Japheth: Gomer, Magog, Madai, *_Javan_*, Tubal, Meshech, and Tiras.
* `1Ch 1:7` And the sons of *_Javan_*: Elisha, Tarshish, Kittim, and Dodanim.
* `Isa 66:19` And I will set a sign among them, and I will send those who escape of them to the nations—to Tarshish, Pul, and Lud, who draw the bow, to Tubal, to *_Javan_*, and to the coastlands afar off—who have not heard my fame, neither have seen my glory. And they shall declare my glory among the Gentiles.
* `Ezk 27:13` *_Javan_*, Tubal, and Meshech, they were your merchants. They traded in the persons of men and vessels of brass in your market.
* `Ezk 27:19` Dan and also *_Javan_* going to and fro occupied in your fairs. Bright iron, cassia, and calamus were in your market.

_7 verses containing JAVAN_

== JAVELIN

* `Num 25:7` And when Phinehas, the son of Eleazar, the son of Aaron the priest, saw it, he rose from among the congregation and took a *_javelin_* in his hand.
* `1Sa 17:6` And he had greaves of brass upon his legs and a *_javelin_* of brass between his shoulders.
* `1Sa 18:10` And it came to pass on the next day, that the evil spirit from God came upon Saul, and he prophesied in the midst of the house. And David played with his hand, as at other times. And there was a *_javelin_* in Saul's hand.
* `1Sa 18:11` And Saul cast the *_javelin_*, for he said, "I will smite David even to the wall." And David escaped from his presence twice.
* `1Sa 19:9` And the evil spirit from the LORD was upon Saul as he sat in his house with his *_javelin_* in his hand. And David played with his hand.
* `1Sa 19:10` And Saul sought to smite David even to the wall with the *_javelin_*, but he slipped away from Saul's presence as he drove the *_javelin_* into the wall. And David fled and escaped that night.
* `1Sa 20:33` And Saul cast a *_javelin_* at him to smite him—by which Jonathan knew that it was determined by his father to slay David.

_7 verses containing JAVELIN_

== JAW

* `Jdg 15:15` And he found a fresh *_jaw_*-bone of a donkey, and put forth his hand, took it, and slew a thousand men with it.
* `Jdg 15:16` And Samson said, "With the *_jaw_*-bone of a donkey, heaps upon heaps, with the *_jaw_* of a donkey, I have slain a thousand men."
* `Jdg 15:17` And it came to pass when he had made an end of speaking, that he cast away the *_jaw_*-bone out of his hand and called that place Ramath-lehi.
* `Jdg 15:19` But God cleaved a hollow place that was in the *_jaw_*, and water came out of it. And when he had drank, his spirit came back, and he revived. Therefore, he called its name, En-hakkore, which is in Lehi to this day.
* `Job 41:2` Can you put a hook into his nose, or bore his *_jaw_* through with a thorn?
* `Pro 30:14` There is a generation whose teeth are like swords and their *_jaw_*-teeth are like knives to devour the poor from off the earth and the needy from among men.

_6 verses containing JAW_

== JAW-BONE

* `Jdg 15:15` And he found a fresh *_jaw-bone_* of a donkey, and put forth his hand, took it, and slew a thousand men with it.
* `Jdg 15:16` And Samson said, "With the *_jaw-bone_* of a donkey, heaps upon heaps, with the jaw of a donkey, I have slain a thousand men."
* `Jdg 15:17` And it came to pass when he had made an end of speaking, that he cast away the *_jaw-bone_* out of his hand and called that place Ramath-lehi.

_3 verses containing JAW-BONE_

== JAW-TEETH

* `Pro 30:14` There is a generation whose teeth are like swords and their *_jaw-teeth_* are like knives to devour the poor from off the earth and the needy from among men.

_1 verse containing JAW-TEETH_

== JAWS

* `Job 29:17` And I broke the *_jaws_* of the wicked and plucked the prey out of his teeth.
* `Psa 22:15` My strength is dried up like a potsherd, and my tongue cleaves to my *_jaws_*. And you have brought me into the dust of death.
* `Isa 30:28` And his breath, as an overflowing stream, shall reach to the midst of the neck, to sift the nations with the sieve of vanity. And there shall be a bridle in the *_jaws_* of the people, causing them to err.
* `Ezk 29:4` But I will put hooks in your *_jaws_*, and I will cause the fish of your rivers to stick to your scales. And I will bring you out of the midst of your rivers, and all the fish of your rivers shall stick to your scales.
* `Ezk 38:4` And I will turn you back and put hooks into your *_jaws_*, and I will bring you forth with all your army—horses and horsemen all clothed with all sorts of armor, even a great company with bucklers and shields, all of them handling swords;
* `Hos 11:4` I drew them with cords of a man, with ropes of love. And I was to them as those who take off the yoke from their *_jaws_*, and I laid food for them.

_6 verses containing JAWS_

