= ELEAD - EMORITE
:toc:

== ELEAD

* `1Ch 7:21` Zabad his son, Shuthelah his son, Ezer, and *_Elead_*, whom the men of Gath who were born in that land slew because they came down to take away their livestock.

_1 verse containing ELEAD_

== ELEALEH

* `Num 32:3` "Ataroth, Dibon, Jazer, Nimrah, Heshbon, *_Elealeh_*, Shebam, Nebo, and Beon,
* `Num 32:37` And the children of Reuben built Heshbon, *_Elealeh_*, Kirjathaim,
* `Isa 15:4` And Heshbon shall cry, along with *_Elealeh_*. Their voice shall be heard even to Jahaz; therefore, the armed soldiers of Moab shall cry out. His life shall be grievous to him.
* `Isa 16:9` Therefore, I will wail with the weeping of Jazer for the vine of Sibmah. I will water you with my tears, O Heshbon and *_Elealeh_*, for on your summer fruits and on your harvest the battle shout has fallen.
* `Jer 48:34` "From the cry of Heshbon even to *_Elealeh_*, and even to Jahaz, they have uttered their voice, from Zoar even to Horonaim, as a heifer of three years old. For the waters also of Nimrim shall be desolate.

_5 verses containing ELEALEH_

== ELEASAH

* `1Ch 2:39` Azariah begot Helez, Helez begot *_Eleasah_*,
* `1Ch 2:40` *_Eleasah_* begot Sisamai, Sisamai begot Shallum,
* `1Ch 8:37` And Moza begot Bineah. Rapha was his son, *_Eleasah_* his son, Azel his son.
* `1Ch 9:43` And Moza begot Binea, and Rephaiah his son, *_Eleasah_* his son, and Azel his son.

_4 verses containing ELEASAH_

== ELEAZAR

* `Exo 6:23` And Aaron took for himself Elisheba, daughter of Amminadab, sister of Naashon, for a wife. And she bore him Nadab, Abihu, *_Eleazar_*, and Ithamar.
* `Exo 6:25` And *_Eleazar_*, Aaron's son, took for himself one of the daughters of Putiel for a wife. And she bore to him Phinehas. These are the heads of the fathers of the Levites according to their families.
* `Exo 28:1` "And bring to you Aaron your brother and his sons with him from among the children of Israel so that he may minister to me in the priest's office, even Aaron and Nadab, Abihu, *_Eleazar_*, and Ithamar, Aaron's sons.
* `Lev 10:6` And Moses said to Aaron and to *_Eleazar_* and to Ithamar his sons, "Do not uncover your heads, neither rend your clothes, lest you die, and lest wrath come upon all the people. But let your brothers, the whole house of Israel, bewail the burning which the LORD has kindled.
* `Lev 10:12` And Moses spoke to Aaron and to *_Eleazar_* and Ithamar, his sons who were left, "Take the food-offering that remains of the offerings of the LORD made by fire and eat it without leaven beside the altar, for it is most holy.
* `Lev 10:16` And Moses diligently sought the goat of the sin-offering, and behold, it was burnt. And he was angry with *_Eleazar_* and Ithamar, the sons of Aaron who were left alive, saying,
* `Num 3:2` And these are the names of the sons of Aaron: Nadab the first-born, Abihu, *_Eleazar_*, and Ithamar.
* `Num 3:4` And Nadab and Abihu died before the LORD when they offered strange fire before the LORD in the wilderness of Sinai, and they had no children. And *_Eleazar_* and Ithamar ministered in the priest's office in the sight of Aaron their father.
* `Num 3:32` And *_Eleazar_* the son of Aaron the priest shall be chief over the chief of the Levites and have the oversight of those who keep the charge of the sanctuary.
* `Num 4:16` "And to the office of *_Eleazar_* the son of Aaron the priest pertain the oil for the light, the sweet incense, the daily food-offering, the anointing oil, the oversight of all the tabernacle, and of all that is in it, in the sanctuary, and in its vessels."
* `Num 16:37` "Speak to *_Eleazar_* the son of Aaron the priest that he take up the censers out of the burning, and you scatter the fire yonder, for they are hallowed.
* `Num 16:39` And *_Eleazar_* the priest took the brazen censers, with which those who were burnt had offered, and they were made broad plates for a covering of the altar
* `Num 19:3` And you shall give her to *_Eleazar_* the priest so that he may bring her forth outside the camp, and someone shall slay her before his face.
* `Num 19:4` And *_Eleazar_* the priest shall take some of her blood with his finger and sprinkle some of her blood directly before the Tabernacle of the Congregation seven times.
* `Num 20:25` Take Aaron and *_Eleazar_* his son and bring them up to mount Hor.
* `Num 20:26` And strip Aaron of his garments and put them upon *_Eleazar_* his son. And Aaron shall be gathered to his people and shall die there."
* `Num 20:28` And Moses stripped Aaron of his garments and put them upon *_Eleazar_* his son. And Aaron died there on the top of the mountain. And Moses and *_Eleazar_* came down from the mountain.
* `Num 25:7` And when Phinehas, the son of *_Eleazar_*, the son of Aaron the priest, saw it, he rose from among the congregation and took a javelin in his hand.
* `Num 25:11` "Phinehas, the son of *_Eleazar_*, the son of Aaron the priest, has turned my wrath away from the children of Israel (while he was zealous for my sake among them) so that I did not consume the children of Israel in my jealousy.
* `Num 26:1` And it came to pass after the plague, that the LORD spoke to Moses and to *_Eleazar_* the son of Aaron the priest, saying,
* `Num 26:3` And Moses and *_Eleazar_* the priest spoke with them in the plains of Moab by the Jordan near Jericho, saying,
* `Num 26:60` And to Aaron was born Nadab, Abihu, *_Eleazar_*, and Ithamar.
* `Num 26:63` These are those who were numbered by Moses and *_Eleazar_* the priest, who numbered the children of Israel in the plains of Moab by the Jordan near Jericho.
* `Num 27:2` And they stood before Moses, before *_Eleazar_* the priest, and before the princes and all the congregation by the door of the Tabernacle of the Congregation, saying,
* `Num 27:19` And set him before *_Eleazar_* the priest and before all the congregation, and give him a charge in their sight.
* `Num 27:21` And he shall stand before *_Eleazar_* the priest, who shall ask counsel for him after the judgment of Urim before the LORD. At his word they shall go out and at his word they shall come in—both he and all the children of Israel with him, even all the congregation."
* `Num 27:22` And Moses did as the LORD commanded him. And he took Joshua and set him before *_Eleazar_* the priest and before all the congregation,
* `Num 31:6` And Moses sent them to the war, one thousand of every tribe, along with Phinehas the son of *_Eleazar_* the priest, to the war, with the holy instruments and the trumpets to blow in his hand.
* `Num 31:12` And they brought the captives, the plunder, and the loot to Moses and *_Eleazar_* the priest and to the congregation of the children of Israel, to the camp at the plains of Moab, which are by the Jordan near Jericho.
* `Num 31:13` And Moses and *_Eleazar_* the priest and all the princes of the congregation went forth to meet them outside the camp.
* `Num 31:21` And *_Eleazar_* the priest said to the men of war who went to the battle, "This is the ordinance of the law which the LORD commanded Moses:
* `Num 31:26` "Take the sum of the plunder that was taken, both of man and of beast—you, *_Eleazar_* the priest, and the chief fathers of the congregation—
* `Num 31:29` Take it from their half and give it to *_Eleazar_* the priest for a heave-offering of the LORD.
* `Num 31:31` And Moses and *_Eleazar_* the priest did as the LORD commanded Moses.
* `Num 31:41` And Moses gave the tribute, which was the LORD'S heave-offering, to *_Eleazar_* the priest, as the LORD commanded Moses.
* `Num 31:51` And Moses and *_Eleazar_* the priest took their gold, even all wrought jewels.
* `Num 31:54` And Moses and *_Eleazar_* the priest took the gold from the captains of thousands and of hundreds and brought it into the Tabernacle of the Congregation for a memorial for the children of Israel before the LORD.
* `Num 32:2` The children of Gad and the children of Reuben came and spoke to Moses, to *_Eleazar_* the priest, and to the princes of the congregation, saying,
* `Num 32:28` So concerning them Moses commanded *_Eleazar_* the priest, Joshua the son of Nun, and the chief fathers of the tribes of the children of Israel,
* `Num 34:17` "These are the names of the men who shall divide the land to you: *_Eleazar_* the priest and Joshua the son of Nun.
* `Deu 10:6` "And the children of Israel took their journey from Beeroth of the children of Jakan to Mosira. Aaron died there, and he was buried there. And *_Eleazar_* his son ministered in the priest's office in his stead.
* `Jsh 14:1` And these are the countries which the children of Israel inherited in the land of Canaan, which *_Eleazar_* the priest, Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel distributed for inheritance to them.
* `Jsh 17:4` And they came near before *_Eleazar_* the priest, and before Joshua the son of Nun, and before the princes, saying, "The LORD commanded Moses to give us an inheritance among our brothers." Therefore, according to the commandment of the LORD, he gave them an inheritance among the brothers of their father.
* `Jsh 19:51` These are the inheritances which *_Eleazar_* the priest, and Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel divided for an inheritance by lot in Shiloh before the LORD, at the door of the Tabernacle of the Congregation. So they made an end of dividing the country.
* `Jsh 21:1` Then the heads of the fathers of the Levites came near to *_Eleazar_* the priest, to Joshua the son of Nun, and to the heads of the fathers of the tribes of the children of Israel.
* `Jsh 22:13` And the children of Israel sent Phinehas the son of *_Eleazar_* the priest to the children of Reuben, to the children of Gad, and to the half-tribe of Manasseh into the land of Gilead,
* `Jsh 22:31` And Phinehas the son of *_Eleazar_* the priest said to the children of Reuben, to the children of Gad, and to the children of Manasseh, "This day we perceive that the LORD is among us because you have not committed this trespass against the LORD. Now you have delivered the children of Israel out of the hand of the LORD."
* `Jsh 22:32` And Phinehas the son of *_Eleazar_* the priest, along with the princes, returned from the children of Reuben and from the children of Gad in the land of Gilead to the land of Canaan, to the children of Israel, and brought them word again.
* `Jsh 24:33` And *_Eleazar_* the son of Aaron died, and they buried him on a hill that pertained to Phinehas his son, which was given to him on mount Ephraim.
* `Jdg 20:28` And Phinehas, the son of *_Eleazar_*, the son of Aaron, stood before it in those days), saying, "Shall I yet again go out to battle against the children of Benjamin my brother, or shall I cease?" And the LORD said, "Go up, for tomorrow I will deliver them into your hand."
* `1Sa 7:1` And the men of Kirjath-jearim came and brought up the ark of the LORD. And they brought it into the house of Abinadab on the hill and sanctified *_Eleazar_* his son to keep the ark of the LORD.
* `2Sa 23:9` And after him was *_Eleazar_* the son of Dodo the Ahohite, one of the three mighty men with David, when they defied the Philistines who were assembled there to battle and the men of Israel had gone away.
* `1Ch 6:3` And the children of Amram: Aaron, Moses, and Miriam. The sons also of Aaron: Nadab, Abihu, *_Eleazar_*, and Ithamar.
* `1Ch 6:4` *_Eleazar_* begot Phinehas, Phinehas begot Abishua,
* `1Ch 6:50` And these are the sons of Aaron: *_Eleazar_* his son, Phinehas his son, Abishua his son,
* `1Ch 9:20` And Phinehas the son of *_Eleazar_* was the ruler over them in time past, and the LORD was with him.
* `1Ch 11:12` And after him was *_Eleazar_* the son of Dodo, the Ahohite, who was one of the three mighty men.
* `1Ch 23:21` The sons of Merari: Mahli and Mushi. The sons of Mahli: *_Eleazar_* and Kish.
* `1Ch 23:22` And *_Eleazar_* died and had no sons, but daughters, and their brothers the sons of Kish took them.
* `1Ch 24:1` Now these are the divisions of the sons of Aaron: The sons of Aaron: Nadab, Abihu, *_Eleazar_*, and Ithamar.
* `1Ch 24:2` But Nadab and Abihu died before their father and had no children; therefore, *_Eleazar_* and Ithamar executed the priest's office.
* `1Ch 24:3` And David distributed them, both Zadok of the sons of *_Eleazar_* and Ahimelech of the sons of Ithamar, according to their offices in their service.
* `1Ch 24:4` And there were more chief men found among the sons of *_Eleazar_* than among the sons of Ithamar, and thus they were divided. Among the sons of *_Eleazar_* there were sixteen chief men of the house of their fathers and eight among the sons of Ithamar according to the house of their fathers.
* `1Ch 24:5` Thus they were divided by lot, one sort with another, for the governors of the sanctuary and governors of the house of God were of the sons of *_Eleazar_* and of the sons of Ithamar.
* `1Ch 24:6` And Shemaiah the son of Nethaneel the scribe, one of the Levites, recorded them before the king, the princes, Zadok the priest, Ahimelech the son of Abiathar, and before the chief of the fathers of the priests and Levites. One principal household being taken for *_Eleazar_* and one taken for Ithamar.
* `1Ch 24:28` Of Mahli came *_Eleazar_*, who had no sons.
* `Ezr 7:5` The son of Abishua, the son of Phinehas, the son of *_Eleazar_*, the son of Aaron the chief priest—
* `Ezr 8:33` Now on the fourth day the silver, the gold, and the vessels were weighed in the house of our God by the hand of Meremoth the son of Uriah the priest, and with him was *_Eleazar_* the son of Phinehas, and with them were the Levites Jozabad the son of Jeshua and Noadiah the son of Binnui.
* `Ezr 10:25` Moreover, of Israel: of the sons of Parosh: Ramiah, Jeziah, Malchiah, Miamin, *_Eleazar_*, Malchijah, and Benaiah.
* `Neh 12:42` And Maaseiah, Shemaiah, *_Eleazar_*, Uzzi, Jehohanan, Malchijah, Elam, and Ezer. And the singers sang loud with Jezrahiah their overseer.
* `Mth 1:15` Eliud begot *_Eleazar_*, *_Eleazar_* begot Matthan, Matthan begot Jacob,

_71 verses containing ELEAZAR_

== ELECT

* `Isa 42:1` "Behold my servant, whom I uphold, my *_elect_*, in whom my soul delights. I have put my Spirit upon him. He shall bring forth judgment to the Gentiles.
* `Isa 45:4` For Jacob my servant's sake and Israel my *_elect_*, I have even called you by your name. I have surnamed you, though you have not known me.
* `Isa 65:9` And I will bring forth offspring out of Jacob, and out of Judah an inheritor of my mountains. And my *_elect_* shall inherit it and my servants shall dwell there.
* `Isa 65:22` They shall not build and another inhabit. They shall not plant and another eat. For the days of my people shall be like the days of a tree, and my *_elect_* shall long enjoy the work of their hands.
* `Mth 24:22` And unless those days should be shortened, no flesh would be saved, but for the *_elect_*'s sake those days shall be shortened.
* `Mth 24:24` For false Christs and false prophets will arise and will show great signs and wonders in such a way that, if it were possible, they would deceive the very *_elect_*.
* `Mth 24:31` And he will send his angels with a great sound of a trumpet, and they will gather his *_elect_* from the four winds, 'from one end of heaven to the other.'
* `Mrk 13:20` And unless the Lord had shortened those days, no flesh would be saved. But for the *_elect_*'s sake, whom he has chosen, he has shortened the days.
* `Mrk 13:22` For false Christs and false prophets will rise and will show signs and wonders to lead astray, if it were possible, even the *_elect_*.
* `Mrk 13:27` And then he will send his angels and will assemble his *_elect_* from the four winds, 'from the uttermost part of the earth to the uttermost part of heaven.'
* `Luk 18:7` And will God not avenge his own *_elect_*, who cry day and night to him, though he bears long with them?
* `Rom 8:33` Who will lay anything to the charge of God's *_elect_*? It is God who justifies.
* `Rom 11:7` What then? Israel has not obtained that which he seeks for, but the *_elect_* have obtained it, and the rest were blinded.
* `Col 3:12` Put on therefore, as the *_elect_* of God, holy and beloved, hearts of mercies, kindness, humbleness of mind, meekness, patience,
* `1Ti 5:21` I charge you before God and the Lord Jesus Christ and the *_elect_* angels, that you observe these things without preferring one before another, doing nothing by partiality.
* `2Ti 2:10` Therefore, I endure all things for the sake of the *_elect_* so that they may also obtain the salvation which is in Christ Jesus with eternal glory.
* `Tit 1:1` Paul, a servant of God and an apostle of Jesus Christ, according to the faith of God's *_elect_* and the acknowledging of the truth which is according to godliness,
* `1Pe 1:2` *_Elect_* according to the foreknowledge of God the Father, through sanctification of the Spirit, to obedience and sprinkling of the blood of Jesus Christ: Grace to you and peace be multiplied.
* `1Pe 2:6` Therefore, it is also contained in the Scripture, "Behold, I lay in Zion a chief corner-stone, *_elect_*, precious. And he who believes in him shall not be confounded."
* `2Jn 1:1` The elder to the *_elect_* lady and her children, whom I love in the truth, and not I only, but also all those who have known the truth,
* `2Jn 1:13` The children of your *_elect_* sister greet you. Amen.

_21 verses containing ELECT_

== ELECTED

* `1Pe 5:13` The church that is at Babylon, *_elected_* together with you, salutes you, and so does Mark my son.

_1 verse containing ELECTED_

== ELECTION

* `Rom 9:11` (For the children not yet being born, neither having done any good or evil, so that the purpose of God according to *_election_* might stand, not of works, but of him who calls),
* `Rom 11:5` Even so then at this present time also there is a remnant according to the *_election_* of grace.
* `Rom 11:28` As concerning the gospel, they are enemies for your sake, but as concerning the *_election_*, they are beloved for the fathers' sake.
* `1Th 1:4` Knowing, brothers beloved by God, your *_election_*.
* `2Pe 1:10` Therefore, brothers, give more diligence to make your calling and *_election_* sure. For if you do these things, you shall never fall.

_5 verses containing ELECTION_

== ELEMENTS

* `Gal 4:3` Even so we, when we were children, were in bondage under the *_elements_* of the world.
* `Gal 4:9` But now, after you have known God, or rather are known by God, how do you turn back to the weak and beggarly *_elements_* to which you desire again to be in bondage?
* `2Pe 3:10` But the day of the Lord will come as a thief in the night, in which the heavens will pass away with a great noise, the *_elements_* will melt with fervent heat, and the earth and the works that are therein will be burned up.
* `2Pe 3:12` Looking for and hastening to the coming of the day of God, in which the heavens being on fire will be dissolved and the *_elements_* will melt with fervent heat?

_4 verses containing ELEMENTS_

== ELEPH

* `Jsh 18:28` Zelah, *_Eleph_*, Jebusi (which is Jerusalem), Gibeath, and Kirjath; fourteen cities with their villages. This is the inheritance of the children of Benjamin according to their families.

_1 verse containing ELEPH_

== ELEVATED

* `Isa 6:1` In the year that king Uzziah died I also saw the Lord sitting upon a throne, high and *_elevated_*, and his train filled the temple.

_1 verse containing ELEVATED_

== ELEVATION

* `Psa 48:2` Beautiful in *_elevation_*, the joy of the whole earth, is mount Zion, on the sides of the north, the city of the great King.

_1 verse containing ELEVATION_

== ELEVEN

* `Gen 32:22` And he arose that night and took his two wives, his two women-servants, and his *_eleven_* sons and passed over the ford of the Jabbok.
* `Gen 37:9` And he dreamed yet another dream and told it to his brothers, and said, "Behold, I have dreamed a dream again, and behold, the sun and the moon and the *_eleven_* stars made obeisance to me."
* `Exo 26:7` "And you shall make curtains of goats' hair to be a covering upon the tabernacle. *_Eleven_* curtains you shall make.
* `Exo 26:8` The length of one curtain shall be thirty cubits and the breadth of one curtain four cubits, and the *_eleven_* curtains shall be all of one measure.
* `Exo 36:14` And he made curtains of goats' hair for the tent over the tabernacle. He made them *_eleven_* curtains.
* `Exo 36:15` The length of one curtain was thirty cubits and four cubits was the breadth of one curtain. The *_eleven_* curtains were of one size.
* `Num 29:20` 'And on the third day *_eleven_* bulls, two rams, and fourteen lambs of the first year without blemish;
* `Deu 1:2` (There are *_eleven_* days journey from Horeb by the way of mount Seir to Kadesh-barnea.)
* `Jsh 15:51` Goshen, Holon, and Giloh; *_eleven_* cities with their villages.
* `Jdg 16:5` And the lords of the Philistines came to her, and said to her, "Entice him, and see in what his great strength lies and by what means we may prevail against him so that we may bind him to afflict him. And we will each give you *_eleven_* hundred pieces of silver."
* `Jdg 17:2` And he said to his mother, "The *_eleven_* hundred shekels of silver that were taken from you, about which you cursed and also spoke about in my ears, behold, the silver is with me. I took it." And his mother said, "Blessed are you of the LORD, my son."
* `Jdg 17:3` And when he had restored the *_eleven_* hundred shekels of silver to his mother, his mother said, "I had wholly dedicated the silver to the LORD from my hand for my son to make an engraved image and a molten image. Now therefore, I will restore it to you."
* `2Ki 23:36` Jehoiakim was twenty-five years old when he began to reign, and he reigned *_eleven_* years in Jerusalem. And his mother's name was Zebudah, the daughter of Pedaiah of Rumah.
* `2Ki 24:18` Zedekiah was twenty-one years old when he began to reign, and he reigned *_eleven_* years in Jerusalem. And his mother's name was Hamutal, the daughter of Jeremiah of Libnah.
* `2Ch 36:5` Jehoiakim was twenty-five years old when he began to reign, and he reigned *_eleven_* years in Jerusalem. And he did that which was evil in the sight of the LORD his God.
* `2Ch 36:11` Zedekiah was twenty-one years old when he began to reign, and reigned *_eleven_* years in Jerusalem.
* `Jer 52:1` Zedekiah was twenty-one years old when he began to reign, and he reigned *_eleven_* years in Jerusalem. And his mother's name was Hamutal, the daughter of Jeremiah of Libnah.
* `Ezk 40:49` The length of the porch was twenty cubits and the breadth *_eleven_* cubits. And he brought me by the steps by which they went up to it. And there were pillars by the posts, one on this side and another on that side.
* `Mth 28:16` Then the *_eleven_* disciples went away into Galilee to a mountain where Jesus had appointed them.
* `Mrk 16:14` Afterward, he appeared to the *_eleven_* as they sat at the table and rebuked them for their unbelief and hardness of heart because they did not believe those who had seen him after he was risen.
* `Luk 24:9` And returned from the sepulcher and told all these things to the *_eleven_* and to all the rest.
* `Luk 24:33` And they rose the same hour, returned to Jerusalem, and found the *_eleven_* assembled and those who were with them,
* `Act 1:26` And they gave forth their lots, and the lot fell upon Matthias and he was numbered with the *_eleven_* apostles.
* `Act 2:14` But Peter, standing up with the *_eleven_*, lifted up his voice and said to them, "Men of Judea and all you who dwell at Jerusalem, may this be known to you, and listen to my words.

_24 verses containing ELEVEN_

== ELEVENTH

* `Num 7:72` On the *_eleventh_* day Pagiel the son of Ocran, prince of the children of Asher, offered.
* `Deu 1:3` And it came to pass in the fortieth year, in the *_eleventh_* month, on the first day of the month, that Moses spoke to the children of Israel according to all that the LORD had given him in commandment to them,
* `1Ki 6:38` And in the *_eleventh_* year, in the month of Bul (which is the eighth month), the house was finished throughout all its parts and according to all its fashion. So he was seven years in building it.
* `2Ki 9:29` And in the *_eleventh_* year of Joram the son of Ahab, Ahaziah began to reign over Judah.
* `2Ki 25:2` And the city was besieged until the *_eleventh_* year of king Zedekiah.
* `1Ch 12:13` Jeremiah the tenth, and Machbanai the *_eleventh_*.
* `1Ch 24:12` The *_eleventh_* to Eliashib, the twelfth to Jakim,
* `1Ch 25:18` The *_eleventh_* to Azareel—he, his sons, and his brothers were twelve;
* `1Ch 27:14` The *_eleventh_* captain for the *_eleventh_* month was Benaiah the Pirathonite, of the children of Ephraim. And in his course were twenty-four thousand.
* `Jer 1:3` It also came in the days of Jehoiakim the son of Josiah king of Judah, to the end of the *_eleventh_* year of Zedekiah the son of Josiah king of Judah, to the carrying away of Jerusalem captive in the fifth month.]
* `Jer 39:2` And in the *_eleventh_* year of Zedekiah, in the fourth month, on the ninth day of the month, the city was broken up.
* `Jer 52:5` So the city was besieged until the *_eleventh_* year of king Zedekiah.
* `Ezk 26:1` And it came to pass in the *_eleventh_* year, on the first day of the month, that the word of the LORD came to me, saying,
* `Ezk 30:20` And it came to pass in the *_eleventh_* year, in the first month, on the seventh day of the month, that the word of the LORD came to me, saying,
* `Ezk 31:1` And it came to pass in the *_eleventh_* year, in the third month, on the first day of the month, that the word of the LORD came to me, saying,
* `Zch 1:7` On the twenty-fourth day of the *_eleventh_* month, which is the month Sebat, in the second year of Darius, the word of the LORD came to the prophet Zechariah, the son of Barachiah, the son of Iddo, saying,
* `Mth 20:6` And about the *_eleventh_* hour he went out and found others standing idle, and says to them, 'Why do you stand here all day idle?'
* `Mth 20:9` And when those who were hired about the *_eleventh_* hour came, they each received a denarius.
* `Rev 21:20` The fifth, sardonyx; the sixth, sardius; the seventh, chrysolite; the eighth, beryl; the ninth, a topaz; the tenth, a chrysoprase; the *_eleventh_*, a jacinth; and the twelfth, an amethyst.

_19 verses containing ELEVENTH_

== ELHANAN

* `2Sa 21:19` And there was again a battle in Gob with the Philistines where *_Elhanan_* the son of Jaareoregim, a Beth-lehemite, slew the brother of Goliath the Gittite, the staff of whose spear was like a weaver's beam.
* `2Sa 23:24` Asahel the brother of Joab was one of the thirty, along with *_Elhanan_* the son of Dodo of Beth-lehem,
* `1Ch 11:26` Also the valiant men of the armies were Asahel the brother of Joab, *_Elhanan_* the son of Dodo of Beth-lehem,
* `1Ch 20:5` And there was war again with the Philistines. And *_Elhanan_* the son of Jair slew Lahmi the brother of Goliath the Gittite, whose spear-staff was like a weaver's beam.

_4 verses containing ELHANAN_

== ELI

* `1Sa 1:3` And this man went up from his city yearly to worship and to sacrifice to the LORD of hosts in Shiloh. And the two sons of *_Eli_*, Hophni and Phinehas, the priests of the LORD, were there.
* `1Sa 1:9` So Hannah rose after they had eaten in Shiloh and after they had drank. (Now *_Eli_* the priest sat upon a seat by a post of the temple of the LORD.)
* `1Sa 1:12` And it came to pass, as she continued praying before the LORD, that *_Eli_* observed her mouth.
* `1Sa 1:13` Now Hannah spoke in her heart. Only her lips moved, but her voice was not heard. Therefore, *_Eli_* thought she had been drunken.
* `1Sa 1:14` And *_Eli_* said to her, "How long will you be drunken? Put away your wine from you."
* `1Sa 1:17` Then *_Eli_* answered and said, "Go in peace. And may the God of Israel grant you your petition that you have asked of him."
* `1Sa 1:25` And they slew a bull and brought the child to *_Eli_*.
* `1Sa 2:11` And Elkanah went to his house in Ramah. And the child ministered to the LORD before *_Eli_* the priest.
* `1Sa 2:12` Now the sons of *_Eli_* were sons of Belial. They did not know the LORD.
* `1Sa 2:20` And *_Eli_* blessed Elkanah and his wife and said, "May the LORD give you children from this woman for the loan which is lent to the LORD." And they went to their own home.
* `1Sa 2:22` Now *_Eli_* was very old and heard all that his sons did to all Israel and how they lay with the women who assembled at the door of the Tabernacle of the Congregation.
* `1Sa 2:27` And there came a man of God to *_Eli_* and said to him, "Thus says the LORD: 'Did I plainly appear to the house of your father when they were in Egypt in Pharaoh's house?
* `1Sa 3:1` And the child Samuel ministered to the LORD before *_Eli_*. And the word of the LORD was precious in those days. There was no open vision.
* `1Sa 3:2` And it came to pass at that time, when *_Eli_* was laid down in his place and his eyes began to grow dim so that he could not see,
* `1Sa 3:5` And he ran to *_Eli_* and said, "Here I am. You called me." And he said, "I did not call. Lie down again." And he went and lay down.
* `1Sa 3:6` And the LORD called yet again, "Samuel." And Samuel arose and went to *_Eli_* and said, "Here I am. You did call me." And he answered, "I did not call, my son. Lie down again."
* `1Sa 3:8` And the LORD called Samuel again the third time. And he arose and went to *_Eli_* and said, "Here I am. You called me." And *_Eli_* perceived that the LORD had called the child.
* `1Sa 3:9` Therefore, *_Eli_* said to Samuel, "Go, lie down. And it shall be, if he calls you, that you shall say, 'Speak, LORD, for your servant hears.'" So Samuel went and lay down in his place.
* `1Sa 3:12` In that day, I will perform against *_Eli_* all things which I have spoken concerning his house. When I begin, I will also make an end.
* `1Sa 3:14` And therefore, I have sworn to the house of *_Eli_*, that the iniquity of *_Eli_*'s house shall not be purged with sacrifice nor offering forever."
* `1Sa 3:15` And Samuel lay until the morning and opened the doors of the house of the LORD. And Samuel feared to show *_Eli_* the vision.
* `1Sa 3:16` Then *_Eli_* called Samuel and said, "Samuel, my son." And he answered, "Here I am."
* `1Sa 4:4` So the people sent to Shiloh so that they might bring from there the ark of the covenant of the LORD of hosts, who dwells between the cherubim. And the two sons of *_Eli_*, Hophni and Phinehas, were there with the ark of the covenant of God.
* `1Sa 4:11` And the ark of God was taken. And the two sons of *_Eli_*, Hophni and Phinehas, were slain.
* `1Sa 4:13` And when he came, behold, *_Eli_* sat upon a seat by the wayside watching, for his heart trembled for the ark of God. And when the man came into the city and told it, all the city cried out.
* `1Sa 4:14` And when *_Eli_* heard the noise of the crying, he said, "What does the noise of this tumult mean?" And the man came in hastily and told *_Eli_*.
* `1Sa 4:15` Now *_Eli_* was ninety-eight years old and his eyes were dim so that he could not see.
* `1Sa 4:16` And the man said to *_Eli_*, "I am he who came out of the army, and I fled today out of the army." And he said, "How did the matter go, my son?"
* `1Sa 14:3` Along with Ahiah, the son of Ahitub, Ichabod's brother, the son of Phinehas, the son of *_Eli_*, the LORD'S priest in Shiloh, wearing an ephod. And the people did not know that Jonathan was gone.
* `1Ki 2:27` So Solomon removed Abiathar from being priest to the LORD so that he might fulfill the word of the LORD which he spoke concerning the house of *_Eli_* in Shiloh.
* `Mth 27:46` And about the ninth hour Jesus cried with a loud voice, saying, "*_Eli_*, *_Eli_*, lama sabachthani?" (That is to say, "My God, my God, why have you forsaken me?")

_31 verses containing ELI_

== ELIAB

* `Num 1:9` Of Zebulun, *_Eliab_* the son of Helon;
* `Num 2:7` Then the tribe of Zebulun, and *_Eliab_* the son of Helon shall be captain of the children of Zebulun.
* `Num 7:24` On the third day *_Eliab_* the son of Helon, prince of the children of Zebulun, offered.
* `Num 7:29` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of *_Eliab_* the son of Helon.
* `Num 10:16` And over the host of the tribe of the children of Zebulun was *_Eliab_* the son of Helon.
* `Num 16:1` Now Korah, the son of Izhar, the son of Kohath, the son of Levi, and Dathan and Abiram, the sons of *_Eliab_*, and On, the son of Peleth, sons of Reuben, took men,
* `Num 16:12` And Moses sent to call Dathan and Abiram, the sons of *_Eliab_*, who said, "We will not come up.
* `Num 26:8` And the son of Phallu: *_Eliab_*.
* `Num 26:9` And the sons of *_Eliab_*: Nemuel, Dathan, and Abiram. These are the Dathan and Abiram who were famous in the congregation, who strove against Moses and against Aaron in the company of Korah when they strove against the LORD.
* `Deu 11:6` And what he did to Dathan and Abiram, the sons of *_Eliab_*, the son of Reuben, how the earth opened her mouth, and swallowed them up, along with their households, their tents, and all the substance that was in their possession, in the midst of all Israel.
* `1Sa 16:6` And it came to pass when they had come, that he looked on *_Eliab_* and said, "Surely the LORD'S anointed is before him."
* `1Sa 17:13` And the three eldest sons of Jesse went and followed Saul to the battle. And the names of his three sons who went to the battle were *_Eliab_* the first-born, next to him Abinadab, and the third Shammah.
* `1Sa 17:28` And *_Eliab_* his eldest brother heard when he spoke to the men. And *_Eliab_*'s anger was kindled against David and he said, "Why did you come down here? And with whom have you left those few sheep in the wilderness? I know your pride and the wickedness of your heart. For you have come down so that you may see the battle."
* `1Ch 2:13` And Jesse begot his first-born *_Eliab_*, and Abinadab the second, Shimma the third,
* `1Ch 6:27` *_Eliab_* his son, Jeroham his son, and Elkanah his son.
* `1Ch 12:9` Ezer the first, Obadiah the second, *_Eliab_* the third,
* `1Ch 15:18` And with them their brothers of the second degree: Zechariah, Ben, Jaaziel, Shemiramoth, Jehiel, Unni, *_Eliab_*, Benaiah, Maaseiah, Mattithiah, Elipheleh, Mikneiah, Obed-edom, and Jeiel, the gatekeepers.
* `1Ch 15:20` And Zechariah, Aziel, Shemiramoth, Jehiel, Unni, *_Eliab_*, Maaseiah, and Benaiah with psalteries on Alamoth;
* `1Ch 16:5` Asaph the chief, and next to him Zechariah, Jeiel, Shemiramoth, Jehiel, Mattithiah, *_Eliab_*, Benaiah, and Obed-edom; and Jeiel with psalteries and with harps; but Asaph made a sound with cymbals;
* `2Ch 11:18` And Rehoboam took for himself Mahalath the daughter of Jerimoth the son of David for a wife, and Abihail the daughter of *_Eliab_* the son of Jesse,

_20 verses containing ELIAB_

== ELIADA

* `2Sa 5:16` Elishama, *_Eliada_*, and Eliphalet.
* `1Ch 3:8` Elishama, *_Eliada_*, and Eliphelet, nine.
* `2Ch 17:17` And of Benjamin: *_Eliada_* a mighty man of valor, and with him two hundred thousand armed men with bow and shield;

_3 verses containing ELIADA_

== ELIADAH

* `1Ki 11:23` And God stirred him up another adversary: Rezon the son of *_Eliadah_*, who fled from his lord Hadadezer king of Zobah.

_1 verse containing ELIADAH_

== ELIAH

* `1Ch 8:27` Jaresiah, *_Eliah_*, and Zichri were the sons of Jeroham.
* `Ezr 10:26` And of the sons of Elam: Mattaniah, Zechariah, Jehiel, Abdi, Jeremoth, and *_Eliah_*.

_2 verses containing ELIAH_

== ELIAHBA

* `2Sa 23:32` *_Eliahba_* the Shaalbonite, (of the sons of Jashen) Jonathan,
* `1Ch 11:33` Azmaveth the Baharumite, *_Eliahba_* the Shaalbonite,

_2 verses containing ELIAHBA_

== ELIAKIM

* `2Ki 18:18` And when they had called to the king, there came out to them *_Eliakim_* the son of Hilkiah who was over the household, Shebna the scribe, and Joah the son of Asaph the recorder.
* `2Ki 18:26` Then *_Eliakim_* the son of Hilkiah, Shebna, and Joah said to Rab-shakeh, "Speak, I pray you, to your servants in the Syrian language, for we understand it. And do not talk with us in the Jews' language in the ears of the people who are on the wall."
* `2Ki 18:37` Then *_Eliakim_* the son of Hilkiah who was over the household, Shebna the scribe, and Joah the son of Asaph the recorder, came to Hezekiah with their clothes rent and told him the words of Rab-shakeh.
* `2Ki 19:2` And he sent *_Eliakim_* who was over the household, Shebna the scribe, and the elders of the priests, covered with sackcloth, to Isaiah the prophet the son of Amoz.
* `2Ki 23:34` And Pharaoh-nechoh made *_Eliakim_* the son of Josiah king in place of Josiah his father and turned his name to Jehoiakim, and he took Jehoahaz away. And he came to Egypt and died there.
* `2Ch 36:4` And the king of Egypt made *_Eliakim_* his brother king over Judah and Jerusalem and changed his name to Jehoiakim. And Necho took Jehoahaz his brother and carried him to Egypt.
* `Neh 12:41` And the priests, *_Eliakim_*, Maaseiah, Miniamin, Michaiah, Elioenai, Zechariah, and Hananiah, with trumpets;
* `Isa 22:20` And it shall come to pass in that day, that I will call my servant *_Eliakim_* the son of Hilkiah,
* `Isa 36:3` Then *_Eliakim_*, Hilkiah's son, who was over the house, Shebna the scribe, and Joah, Asaph's son the recorder, came forth to him.
* `Isa 36:11` Then *_Eliakim_*, Shebna, and Joah said to Rabshakeh, "Speak, I pray you, to your servants in the Syrian language, for we understand it. And do not speak to us in the Jew's language, in the ears of the people who are on the wall."
* `Isa 36:22` Then *_Eliakim_* the son of Hilkiah, who was over the household, Shebna the scribe, and Joah, the son of Asaph, the recorder, came to Hezekiah with their clothes rent and told him the words of Rabshakeh.
* `Isa 37:2` And he sent *_Eliakim_*, who was over the household, Shebna the scribe, and the elders of the priests covered with sackcloth to Isaiah the prophet the son of Amoz.
* `Mth 1:13` Zerubbabel begot Abiud, Abiud begot *_Eliakim_*, *_Eliakim_* begot Azor,
* `Luk 3:30` Who was the son of Simeon, who was the son of Judah, who was the son of Joseph, who was the son of Jonam, who was the son of *_Eliakim_*,

_14 verses containing ELIAKIM_

== ELIAM

* `2Sa 11:3` And David sent and inquired about the woman. And someone said, "Is this not Bath-sheba, the daughter of *_Eliam_*, the wife of Uriah the Hittite?"
* `2Sa 23:34` Eliphelet the son of Ahasbai the son of the Maachathite, *_Eliam_* the son of Ahithophel the Gilonite,

_2 verses containing ELIAM_

== ELIASAPH

* `Num 1:14` Of Gad, *_Eliasaph_* the son of Deuel;
* `Num 2:14` Then the tribe of Gad, and the captain of the sons of Gad shall be *_Eliasaph_* the son of Reuel.
* `Num 3:24` And the chief of the house of the father of the Gershonites shall be *_Eliasaph_* the son of Lael.
* `Num 7:42` On the sixth day *_Eliasaph_* the son of Deuel, prince of the children of Gad, offered.
* `Num 7:47` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of *_Eliasaph_* the son of Deuel.
* `Num 10:20` And over the host of the tribe of the children of Gad was *_Eliasaph_* the son of Deuel.

_6 verses containing ELIASAPH_

== ELIASHIB

* `1Ch 3:24` And the sons of Elioenai were Hodaiah, *_Eliashib_*, Pelaiah, Akkub, Johanan, Delaiah, and Anani, seven.
* `1Ch 24:12` The eleventh to *_Eliashib_*, the twelfth to Jakim,
* `Ezr 10:6` Then Ezra arose from before the house of God and went into the chamber of Johanan the son of *_Eliashib_*. And when he came there, he ate no bread nor drank water, for he mourned because of the transgression of those who had been carried away.
* `Ezr 10:24` Of the singers: *_Eliashib_*. And of the gatekeepers: Shallum, Telem, and Uri.
* `Ezr 10:27` And of the sons of Zattu: Elioenai, *_Eliashib_*, Mattaniah, Jeremoth, Zabad, and Aziza.
* `Ezr 10:36` Vaniah, Meremoth, *_Eliashib_*,
* `Neh 3:1` Then *_Eliashib_* the high priest arose with his brothers the priests, and they built the sheep-gate. They sanctified it and set up its doors. Even to the tower of Meah they sanctified it, to the tower of Hananeel.
* `Neh 3:20` After him Baruch the son of Zabbai earnestly repaired the other piece, from the turning of the wall to the door of the house of *_Eliashib_* the high priest.
* `Neh 3:21` After him Meremoth the son of Urijah, the son of Koz, repaired another piece, from the door of the house of *_Eliashib_*, even to the end of the house of *_Eliashib_*.
* `Neh 12:10` And Jeshua begot Joiakim, Joiakim also begot *_Eliashib_*, *_Eliashib_* begot Joiada,
* `Neh 12:22` As for the Levites, in the days of *_Eliashib_*, Joiada, Johanan, and Jaddua, the chiefs of the fathers were recorded, and also the priests in the reign of Darius the Persian.
* `Neh 12:23` The sons of Levi, the chief of the fathers, were written in the book of the chronicles, even until the days of Johanan the son of *_Eliashib_*.
* `Neh 13:4` And before this, *_Eliashib_* the priest, having the oversight of the chamber of the house of our God, was allied to Tobiah.
* `Neh 13:7` And I came to Jerusalem and discerned the evil that *_Eliashib_* did for Tobiah in preparing for him a chamber in the courts of the house of God.
* `Neh 13:28` And one of the sons of Joiada, the son of *_Eliashib_* the high priest, was son-in-law to Sanballat the Horonite; therefore, I chased him away from me.

_15 verses containing ELIASHIB_

== ELIATHAH

* `1Ch 25:4` Of Heman, the sons of Heman: Bukkiah, Mattaniah, Uzziel, Shebuel, Jerimoth, Hananiah, Hanani, *_Eliathah_*, Giddalti, Romamti-ezer, Joshbekashah, Mallothi, Hothir, and Mahazioth.
* `1Ch 25:27` The twentieth to *_Eliathah_*—he, his sons, and his brothers were twelve;

_2 verses containing ELIATHAH_

== ELIDAD

* `Num 34:21` Of the tribe of Benjamin, *_Elidad_* the son of Chislon;

_1 verse containing ELIDAD_

== ELIEL

* `1Ch 5:24` And these were the heads of the house of their fathers: even Epher, Ishi, *_Eliel_*, Azriel, Jeremiah, Hodaviah, and Jahdiel, mighty men of valor, famous men, and heads of the house of their fathers.
* `1Ch 6:34` The son of Elkanah, the son of Jeroham, the son of *_Eliel_*, the son of Toah,
* `1Ch 8:20` Elienai, Zilthai, *_Eliel_*,
* `1Ch 8:22` And Ishpan, Heber, *_Eliel_*,
* `1Ch 11:46` *_Eliel_* the Mehavite, Jeribai and Joshaviah the sons of Elnaam, Ithmah the Moabite,
* `1Ch 11:47` *_Eliel_*, Obed, and Jasiel the Mesobaite.
* `1Ch 12:11` Attai the sixth, *_Eliel_* the seventh,
* `1Ch 15:9` Of the sons of Hebron: *_Eliel_* the chief and his brothers eighty.
* `1Ch 15:11` And David called for Zadok and Abiathar the priests, for the Levites, for Uriel, Asaiah, Joel, Shemaiah, *_Eliel_*, and Amminadab,
* `2Ch 31:13` And Jehiel, Azaziah, Nahath, Asahel, Jerimoth, Jozabad, *_Eliel_*, Ismachiah, Mahath, and Benaiah were overseers under the hand of Conaniah and Shimei his brother, at the commandment of Hezekiah the king and Azariah the ruler of the house of God.

_10 verses containing ELIEL_

== ELIENAI

* `1Ch 8:20` *_Elienai_*, Zilthai, Eliel,

_1 verse containing ELIENAI_

== ELIEZER

* `Gen 15:2` And Abram said, "Lord GOD, what will you give me, seeing I go childless, and the steward of my house is this *_Eliezer_* of Damascus?"
* `Exo 18:4` And the name of the other was *_Eliezer_* ("For the God of my father," he said, "was my help and delivered me from the sword of Pharaoh").
* `1Ch 7:8` And the sons of Becher: Zemira, Joash, *_Eliezer_*, Elioenai, Omri, Jerimoth, Abiah, Anathoth, and Alameth. All these are the sons of Becher.
* `1Ch 15:24` And Shebaniah, Jehoshaphat, Nethaneel, Amasai, Zechariah, Benaiah, and *_Eliezer_* the priests blew with the trumpets before the ark of God. And Obed-edom and Jehiah were door-keepers for the ark.
* `1Ch 23:15` The sons of Moses were Gershom and *_Eliezer_*.
* `1Ch 23:17` And the son of *_Eliezer_* was Rehabiah the chief. And *_Eliezer_* had no other sons, but the sons of Rehabiah were very many.
* `1Ch 26:25` And his brothers, by *_Eliezer_*, were Rehabiah his son, Jeshaiah his son, Joram his son, Zichri his son, and Shelomith his son.
* `1Ch 27:16` Furthermore, over the tribes of Israel, the ruler of the Reubenites was *_Eliezer_* the son of Zichri; of the Simeonites, Shephatiah the son of Maachah;
* `2Ch 20:37` Then *_Eliezer_* the son of Dodavah of Mareshah prophesied against Jehoshaphat, saying, "Because you have joined yourself with Ahaziah, the LORD has broken your works." And the ships were broken so that they were not able to go to Tarshish.
* `Ezr 8:16` Then I sent for *_Eliezer_*, for Ariel, for Shemaiah, for Elnathan, for Jarib, for Elnathan, for Nathan, for Zechariah, and for Meshullam, chief men, and also for Joiarib and for Elnathan, men of understanding.
* `Ezr 10:18` And among the sons of the priests there were found some who had taken foreign wives, namely, of the sons of Jeshua the son of Jozadak and his brothers: Maaseiah, *_Eliezer_*, Jarib, and Gedaliah.
* `Ezr 10:23` Also of the Levites: Jozabad, Shimei, Kelaiah (the same is Kelita), Pethahiah, Judah, and *_Eliezer_*.
* `Ezr 10:31` And of the sons of Harim: *_Eliezer_*, Ishijah, Malchiah, Shemaiah, Shimeon,
* `Luk 3:29` Who was the son of Joshua, who was the son of *_Eliezer_*, who was the son of Jorim, who was the son of Matthat, who was the son of Levi,

_14 verses containing ELIEZER_

== ELIHOENAI

* `Ezr 8:4` Of the sons of Pahath-moab: *_Elihoenai_* the son of Zerahiah, and with him two hundred males.

_1 verse containing ELIHOENAI_

== ELIHOREPH

* `1Ki 4:3` *_Elihoreph_* and Ahiah the sons of Shisha were scribes, Jehosaphat the son of Ahilud the recorder,

_1 verse containing ELIHOREPH_

== ELIHU

* `1Sa 1:1` Now there was a certain man of Ramathaim-zophim, of mount Ephraim, and his name was Elkanah, the son of Jeroham, the son of *_Elihu_*, the son of Tohu, the son of Zuph, an Ephrathite.
* `1Ch 12:20` And as he went to Ziklag, there fell to him from Manasseh, Adnah, Jozabad, Jediael, Michael, Jozabad, *_Elihu_*, and Zilthai—captains of the thousands who were of Manasseh.
* `1Ch 26:7` The sons of Shemaiah: Othni, Rephael, Obed, Elzabad (whose brothers were strong men), *_Elihu_*, and Semachiah.
* `1Ch 27:18` Of Judah, *_Elihu_*, one of the brothers of David; of Issachar, Omri the son of Michael;
* `Job 32:2` Then the wrath of *_Elihu_* the son of Barachel the Buzite, of the kindred of Ram, was kindled against Job because he justified himself rather than God.
* `Job 32:4` Now *_Elihu_* had waited to speak to Job because they were older than he was.
* `Job 32:5` When *_Elihu_* saw that there was no answer in the mouth of these three men, his wrath was kindled.
* `Job 32:6` And *_Elihu_* the son of Barachel the Buzite answered and said, "I am young, and you are very old; therefore, I was afraid and dared not show you my opinion.
* `Job 34:1` Furthermore, *_Elihu_* answered and said,
* `Job 35:1` *_Elihu_* spoke moreover and said,
* `Job 36:1` *_Elihu_* also proceeded and said,

_11 verses containing ELIHU_

== ELIJAH

* `1Ki 17:1` And *_Elijah_* the Tishbite who was of the inhabitants of Gilead said to Ahab, "As the LORD God of Israel lives, before whom I stand, there shall not be dew nor rain these years, but according to my word."
* `1Ki 17:13` And *_Elijah_* said to her, "Do not fear. Go and do as you have said. But make me a little cake of it first and bring it to me, and afterward make some for yourself and for your son.
* `1Ki 17:15` And she went and did according to the saying of *_Elijah_*. And she and he and her house ate many days.
* `1Ki 17:16` And the barrel of meal did not waste, neither did the cruse of oil fail, according to the word of the LORD which he spoke by *_Elijah_*.
* `1Ki 17:18` And she said to *_Elijah_*, "What have I to do with you, O man of God? Have you come to me to call my sin to remembrance and to slay my son?"
* `1Ki 17:22` And the LORD heard the voice of *_Elijah_*. And the soul of the child came into him again and he revived.
* `1Ki 17:23` And *_Elijah_* took the child, brought him down from the chamber into the house, and delivered him to his mother. And *_Elijah_* said, "Behold, your son lives."
* `1Ki 17:24` And the woman said to *_Elijah_*, "Now by this I know that you are a man of God, and that the word of the LORD in your mouth is truth."
* `1Ki 18:1` And it came to pass after many days, that the word of the LORD came to *_Elijah_* in the third year, saying, "Go, show yourself to Ahab, and I will send rain upon the earth."
* `1Ki 18:2` And *_Elijah_* went to show himself to Ahab. And there was a grievous famine in Samaria.
* `1Ki 18:7` And as Obadiah was on the way, behold, *_Elijah_* met him. And he knew him and fell on his face and said, "Is it you, my lord *_Elijah_*?"
* `1Ki 18:8` And he answered him, "I am. Go, tell your lord, 'Behold, *_Elijah_* is here.'"
* `1Ki 18:11` And now you say, 'Go, tell your lord, "Behold, *_Elijah_* is here."'
* `1Ki 18:14` And now you say, 'Go, tell your lord, "Behold, *_Elijah_* is here,"' and he will slay me."
* `1Ki 18:15` And *_Elijah_* said, "As the LORD of hosts lives, before whom I stand, I will surely show myself to him today."
* `1Ki 18:16` So Obadiah went to meet Ahab and told him. And Ahab went to meet *_Elijah_*.
* `1Ki 18:17` And it came to pass, when Ahab saw *_Elijah_*, that Ahab said to him, "Are you he who troubles Israel?"
* `1Ki 18:21` And *_Elijah_* came to all the people and said, "How long do you hesitate between two opinions? If the LORD is God, follow him, but if Baal, then follow him." And the people did not answer him a word.
* `1Ki 18:22` Then *_Elijah_* said to the people, "I, even I only, remain a prophet of the LORD, but Baal's prophet's are four hundred and fifty men.
* `1Ki 18:25` And *_Elijah_* said to the prophets of Baal, "Choose one bull for yourselves and dress it first, for you are many. And call on the name of your gods, but put no fire under it."
* `1Ki 18:27` And it came to pass at noon, that *_Elijah_* mocked them and said, "Cry aloud, for he is a god! Either he is talking, he is pursuing, he is on a journey, or perhaps he sleeps and must be awakened."
* `1Ki 18:30` And *_Elijah_* said to all the people, "Come near to me." And all the people came near to him. And he repaired the altar of the LORD that was broken down.
* `1Ki 18:31` And *_Elijah_* took twelve stones, according to the number of the tribes of the sons of Jacob, to whom the word of the LORD came, saying, "Israel shall be your name."
* `1Ki 18:36` And it came to pass at the time of the offering of the evening sacrifice, that *_Elijah_* the prophet came near and said, "LORD God of Abraham, Isaac, and of Israel, let it be known this day that you are God in Israel and that I am your servant, and that I have done all these things at your word.
* `1Ki 18:40` And *_Elijah_* said to them, "Take the prophets of Baal. Let not one of them escape." And they took them. And *_Elijah_* brought them down to the brook Kishon and slew them there.
* `1Ki 18:41` And *_Elijah_* said to Ahab, "Go up, eat and drink, for there is a sound of abundance of rain."
* `1Ki 18:42` So Ahab went up to eat and to drink. And *_Elijah_* went up to the top of Carmel, and he cast himself down upon the earth and put his face between his knees,
* `1Ki 18:46` And the hand of the LORD was on *_Elijah_*. And he girded his loins and ran before Ahab to the entrance of Jezreel.
* `1Ki 19:1` And Ahab told Jezebel all that *_Elijah_* had done and how he had slain all the prophets with the sword.
* `1Ki 19:2` Then Jezebel sent a messenger to *_Elijah_*, saying, "So let the gods do to me and more also, if I do not make your life as the life of one of them by tomorrow about this time."
* `1Ki 19:9` And he came to a cave there and lodged there. And behold, the word of the LORD came to him, and he said to him, "What are you doing here, *_Elijah_*?"
* `1Ki 19:13` And it was so, when *_Elijah_* heard it, that he wrapped his face in his mantle, went out, and stood in the entrance of the cave. And behold, there came a voice to him and said, "What are you doing here, *_Elijah_*?"
* `1Ki 19:19` So he departed from there and found Elisha the son of Shaphat, who was plowing with twelve yoke of oxen before him, and he with the twelfth. And *_Elijah_* passed by him and cast his mantle upon him.
* `1Ki 19:20` And he left the oxen and ran after *_Elijah_* and said, "Let me, I pray you, kiss my father and my mother and then I will follow you." And he said to him, "Go back again. For what have I done to you?"
* `1Ki 19:21` And he returned from following him, took a yoke of oxen, slew them, boiled their flesh with the instruments of the oxen, and gave to the people, and they ate. Then he arose, went after *_Elijah_*, and ministered to him.
* `1Ki 21:17` And the word of the LORD came to *_Elijah_* the Tishbite, saying,
* `1Ki 21:20` And Ahab said to *_Elijah_*, "Have you found me, O my enemy?" And he answered, "I have found you because you have sold yourself to work evil in the sight of the LORD.
* `1Ki 21:28` And the word of the LORD came to *_Elijah_* the Tishbite, saying,
* `2Ki 1:3` But the angel of the LORD said to *_Elijah_* the Tishbite, "Arise, go up to meet the messengers of the king of Samaria and say to them, 'Is it not because there is not a God in Israel that you go to inquire of Baal-zebub the god of Ekron?'
* `2Ki 1:4` Now therefore, thus says the LORD: 'You shall not come down from that bed on which you have gone up, but shall surely die.'" And *_Elijah_* departed.
* `2Ki 1:8` And they answered him, "He was a hairy man and girt with a girdle of leather around his loins." And he said, "It is *_Elijah_* the Tishbite."
* `2Ki 1:10` And *_Elijah_* answered and said to the captain of fifty, "If I am a man of God, then let fire come down from heaven and consume you and your fifty." And fire came down from heaven and consumed him and his fifty.
* `2Ki 1:12` And *_Elijah_* answered and said to them, "If I am a man of God, let fire come down from heaven and consume you and your fifty." And the fire of God came down from heaven and consumed him and his fifty.
* `2Ki 1:13` And again he sent a third captain of fifty with his fifty. And the third captain of fifty went up, came and fell on his knees before *_Elijah_*, and implored him and said to him, "O man of God, I pray you, let my life and the life of these fifty your servants be precious in your sight.
* `2Ki 1:15` And the angel of the LORD said to *_Elijah_*, "Go down with him. Do not be afraid of him." And he arose and went down with him to the king.
* `2Ki 1:17` So he died according to the word of the LORD which *_Elijah_* had spoken. And Jehoram reigned in his stead in the second year of Jehoram the son of Jehoshaphat king of Judah, because he had no son.
* `2Ki 2:1` And it came to pass, when the LORD would take up *_Elijah_* into heaven by a whirlwind, that *_Elijah_* went with Elisha from Gilgal.
* `2Ki 2:2` And *_Elijah_* said to Elisha, "Stay here, I pray you, for the LORD has sent me to Beth-el." And Elisha said, "As the LORD lives and as your soul lives, I will not leave you." So they went down to Beth-el.
* `2Ki 2:4` And *_Elijah_* said to him, "Elisha, stay here, I pray you, for the LORD has sent me to Jericho." And he said, "As the LORD lives and as your soul lives, I will not leave you." So they came to Jericho.
* `2Ki 2:6` And *_Elijah_* said to him, "Stay here, I pray you, for the LORD has sent me to the Jordan." And he said, "As the LORD lives and as your soul lives, I will not leave you." And the two of them went on.
* `2Ki 2:8` And *_Elijah_* took his mantle and wrapped it together and smote the waters, and they were divided here and there so that the two of them went over on dry ground.
* `2Ki 2:9` And it came to pass, when they had gone over, that *_Elijah_* said to Elisha, "Ask what I shall do for you before I am taken away from you." And Elisha said, "I pray you, let a double portion of your spirit be upon me."
* `2Ki 2:11` And it came to pass, as they still went on and talked, that behold, there appeared a chariot of fire and horses of fire and parted them both apart. And *_Elijah_* went up by a whirlwind into heaven.
* `2Ki 2:13` He also took up the mantle of *_Elijah_* that fell from him and went back and stood by the bank of the Jordan.
* `2Ki 2:14` And he took the mantle of *_Elijah_* that fell from him and smote the waters and said, "Where is the LORD God of *_Elijah_*?" And when he also had smitten the waters, they parted here and there, and Elisha went over.
* `2Ki 2:15` And when the sons of the prophets who were viewing at Jericho saw him, they said, "The spirit of *_Elijah_* rests on Elisha." And they came to meet him and bowed themselves to the ground before him.
* `2Ki 3:11` But Jehoshaphat said, "Is there not a prophet of the LORD here that we may inquire of the LORD by him?" And one of the king of Israel's servants answered and said, "Here is Elisha the son of Shaphat who poured water on the hands of *_Elijah_*."
* `2Ki 9:36` Therefore, they came back and told him. And he said, "This is the word of the LORD which he spoke by his servant *_Elijah_* the Tishbite, saying, 'In the portion of Jezreel, dogs shall eat the flesh of Jezebel.
* `2Ki 10:10` Know now that there shall fall to the earth nothing of the word of the LORD which the LORD spoke concerning the house of Ahab, for the LORD has done that which he spoke by his servant *_Elijah_*."
* `2Ki 10:17` And when he came to Samaria, he slew all who remained to Ahab in Samaria until he had destroyed him, according to the saying of the LORD which he spoke to *_Elijah_*.
* `2Ch 21:12` And a writing came to him from *_Elijah_* the prophet, saying, "Thus says the LORD God of David your father: 'Because you have not walked in the ways of Jehoshaphat your father, nor in the ways of Asa king of Judah,
* `Ezr 10:21` And of the sons of Harim: Maaseiah, *_Elijah_*, Shemaiah, Jehiel, and Uzziah.
* `Mal 4:5` "Behold, I will send you *_Elijah_* the prophet before the coming of the great and dreadful day of the LORD.
* `Mth 11:14` And if you will receive it, this is *_Elijah_* who was to come.
* `Mth 16:14` And they said, "Some say that you are John the Baptist, some *_Elijah_*, and others Jeremiah or one of the prophets."
* `Mth 17:3` And behold, Moses and *_Elijah_* appeared to them talking with him.
* `Mth 17:4` Then Peter answered, and said to Jesus, "Lord, it is good for us to be here. If you wish, let us make here three tabernacles: one for you, one for Moses, and one for *_Elijah_*."
* `Mth 17:10` And his disciples asked him, saying, "Why then do the scribes say that *_Elijah_* must come first?"
* `Mth 17:11` And Jesus answered and said to them, "*_Elijah_* truly will come first and restore all things.
* `Mth 17:12` But I say to you, that *_Elijah_* has come already, and they did not know him, but have done to him whatever they pleased. Likewise, the Son of man will also suffer by them."
* `Mth 27:47` Some of those who stood there, when they heard that, said, "This man calls for *_Elijah_*."
* `Mth 27:49` The rest said, "Forbear. Let us see whether *_Elijah_* will come to save him."
* `Mrk 6:15` Others said, "It is *_Elijah_*." And others said, "It is a prophet, or like one of the prophets."
* `Mrk 8:28` And they answered, "'John the Baptist.' But some say, '*_Elijah_*,' and others, 'One of the prophets.'"
* `Mrk 9:4` And *_Elijah_* appeared to them with Moses, and they were talking with Jesus.
* `Mrk 9:5` And Peter answered and said to Jesus, "Master, it is good for us to be here. Let us make three tabernacles: one for you, one for Moses, and one for *_Elijah_*."
* `Mrk 9:11` And they asked him, saying, "Why do the scribes say that *_Elijah_* must come first?"
* `Mrk 9:12` And he answered and told them, "*_Elijah_* truly comes first and restores all things. How is it written concerning the Son of man that he must suffer many things and be set at nothing?
* `Mrk 9:13` But I say to you, that *_Elijah_* has indeed come, and they have done to him whatever they pleased, as it is written concerning him."
* `Mrk 15:35` And some of those who stood by, when they heard it, said, "Behold, he calls *_Elijah_*."
* `Mrk 15:36` And someone ran and filled a sponge full of vinegar, put it on a reed, and gave it to him to drink, saying, "Wait. Let us see whether *_Elijah_* will come to take him down."
* `Luk 1:17` And he shall go before him in the spirit and power of *_Elijah_* to 'turn the hearts of the fathers to the children' and the disobedient to the wisdom of the just, to make ready a people prepared for the Lord."
* `Luk 4:25` But I tell you in truth, many widows were in Israel in the days of *_Elijah_* when the heaven was shut three years and six months when great famine was throughout all the land.
* `Luk 4:26` But *_Elijah_* was sent to none of them, except to Zarephath, a city of Sidon, to a woman who was a widow.
* `Luk 9:8` And by some that *_Elijah_* had appeared, and by others that one of the ancient prophets had risen again.
* `Luk 9:19` They, answering, said, "'John the Baptist,' but some say, '*_Elijah_*,' and others say, 'One of the ancient prophets has risen again.'"
* `Luk 9:30` And behold, two men talked with him who were Moses and *_Elijah_*,
* `Luk 9:33` And it came to pass, as they departed from him, Peter said to Jesus, "Master, it is good for us to be here. Let us make three tabernacles: one for you, one for Moses, and one for *_Elijah_*," not knowing what he said.
* `Luk 9:54` And when his disciples, James and John, saw this, they said, "Lord, do you wish that we command fire to come down from heaven and consume them, even as *_Elijah_* did?"
* `Jhn 1:21` And they asked him, "What then? Are you *_Elijah_*?" And he says, "I am not." "Are you that prophet?" And he answered, "No."
* `Jhn 1:25` And they asked him, and said to him, "Why do you baptize then, if you are not that Christ, nor *_Elijah_*, neither that prophet?"
* `Rom 11:2` "God has not cast away his people" which he foreknew. Do you not know what the Scripture says of *_Elijah_*, how he makes intercession to God against Israel?
* `Jms 5:17` *_Elijah_* was a man subject to similar passions as we are, and he prayed earnestly that it might not rain, and it did not rain on the earth for three years and six months.

_93 verses containing ELIJAH_

== ELIKA

* `2Sa 23:25` Shammah the Harodite, *_Elika_* the Harodite,

_1 verse containing ELIKA_

== ELIM

* `Exo 15:27` And they came to *_Elim_*, where there were twelve wells of water and seventy palm-trees. And they encamped there by the waters.
* `Exo 16:1` And they took their journey from *_Elim_*, and all the congregation of the children of Israel came to the wilderness of Sin, which is between *_Elim_* and Sinai, on the fifteenth day of the second month after their departure from the land of Egypt.
* `Num 33:9` And they departed from Marah and came to *_Elim_*. And in *_Elim_* there were twelve fountains of water and seventy palm-trees, and they encamped there.
* `Num 33:10` And they departed from *_Elim_* and encamped by the Red Sea.
* `Isa 15:8` For the cry has gone around the borders of Moab, her howling to Eglaim and her howling to Beer-*_elim_*.

_5 verses containing ELIM_

== ELIMELECH

* `Rth 1:2` And the name of the man was *_Elimelech_*, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, Ephrathites of Beth-lehem-judah. And they came into the country of Moab and continued there.
* `Rth 1:3` And *_Elimelech_*, Naomi's husband, died, and she was left, she and her two sons.
* `Rth 2:1` And Naomi had a kinsman of her husband's, a mighty man of wealth, of the family of *_Elimelech_*, and his name was Boaz.
* `Rth 2:3` And she went, and came and gleaned in the field after the reapers. And she happened to come to a part of the field belonging to Boaz, who was of the kindred of *_Elimelech_*.
* `Rth 4:3` And he said to the kinsman, "Naomi, who has come back out of the country of Moab, sells a parcel of land, which was our brother *_Elimelech_*'s.
* `Rth 4:9` And Boaz said to the elders and to all the people, "You are witnesses this day that I have bought all that was *_Elimelech_*'s and all that was Chilion's and Mahlon's from the hand of Naomi.

_6 verses containing ELIMELECH_

== ELIOENAI

* `1Ch 3:23` And the sons of Neariah: *_Elioenai_*, Hezekiah, and Azrikam, three.
* `1Ch 3:24` And the sons of *_Elioenai_* were Hodaiah, Eliashib, Pelaiah, Akkub, Johanan, Delaiah, and Anani, seven.
* `1Ch 4:36` *_Elioenai_*, Jaakobah, Jeshohaiah, Asaiah, Adiel, Jesimiel, Benaiah,
* `1Ch 7:8` And the sons of Becher: Zemira, Joash, Eliezer, *_Elioenai_*, Omri, Jerimoth, Abiah, Anathoth, and Alameth. All these are the sons of Becher.
* `1Ch 26:3` Elam the fifth, Jehohanan the sixth, and *_Elioenai_* the seventh.
* `Ezr 10:22` And of the sons of Pashur: *_Elioenai_*, Maaseiah, Ishmael, Nethaneel, Jozabad, and Elasah.
* `Ezr 10:27` And of the sons of Zattu: *_Elioenai_*, Eliashib, Mattaniah, Jeremoth, Zabad, and Aziza.
* `Neh 12:41` And the priests, Eliakim, Maaseiah, Miniamin, Michaiah, *_Elioenai_*, Zechariah, and Hananiah, with trumpets;

_8 verses containing ELIOENAI_

== ELIPHALET

* `2Sa 5:16` Elishama, Eliada, and *_Eliphalet_*.
* `1Ch 14:7` Elishama, Beeliada, and *_Eliphalet_*.

_2 verses containing ELIPHALET_

== ELIPHAZ

* `Gen 36:4` And Adah bore to Esau, *_Eliphaz_*; and Bashemath bore Reuel;
* `Gen 36:10` These are the names of Esau's sons: *_Eliphaz_* the son of Adah the wife of Esau, and Reuel the son of Bashemath the wife of Esau.
* `Gen 36:11` And the sons of *_Eliphaz_* were, Teman, Omar, Zepho, Gatam, and Kenaz.
* `Gen 36:12` And Timna was a concubine to *_Eliphaz_*, Esau's son, and she bore Amalek to *_Eliphaz_*. These are the sons of Adah, Esau's wife.
* `Gen 36:15` These are the chiefs of the sons of Esau. The sons of *_Eliphaz_* the first-born son of Esau: chief Teman, chief Omar, chief Zepho, chief Kenaz,
* `Gen 36:16` Chief Korah, chief Gatam, and chief Amalek. These are the chiefs, descendants of *_Eliphaz_*, in the land of Edom. These are the sons of Adah.
* `1Ch 1:35` The sons of Esau: *_Eliphaz_*, Reuel, Jeush, Jaalam, and Korah.
* `1Ch 1:36` The sons of *_Eliphaz_*: Teman, Omar, Zephi, Gatam, Kenaz, Timna, and Amalek.
* `Job 2:11` Now when Job's three friends heard of all this evil that had come upon him, they each came from his own place: *_Eliphaz_* the Temanite, Bildad the Shuhite, and Zophar the Naamathite—for they had made an appointment together to come to mourn with him and to comfort him.
* `Job 4:1` Then *_Eliphaz_* the Temanite answered and said,
* `Job 15:1` Then *_Eliphaz_* the Temanite answered and said,
* `Job 22:1` Then *_Eliphaz_* the Temanite answered and said,
* `Job 42:7` And it was so, that after the LORD had spoken these words to Job, the LORD said to *_Eliphaz_* the Temanite, "My wrath is kindled against you and against your two friends, for you have not spoken about me the thing that is right, as my servant Job has.
* `Job 42:9` So *_Eliphaz_* the Temanite, Bildad the Shuhite, and Zophar the Naamathite went and did according as the LORD commanded them. The LORD also accepted Job.

_14 verses containing ELIPHAZ_

== ELIPHEL

* `1Ch 11:35` Ahiam the son of Sacar the Hararite, *_Eliphel_* the son of Ur,

_1 verse containing ELIPHEL_

== ELIPHELEH

* `1Ch 15:18` And with them their brothers of the second degree: Zechariah, Ben, Jaaziel, Shemiramoth, Jehiel, Unni, Eliab, Benaiah, Maaseiah, Mattithiah, *_Elipheleh_*, Mikneiah, Obed-edom, and Jeiel, the gatekeepers.
* `1Ch 15:21` And Mattithiah, *_Elipheleh_*, Mikneiah, Obed-edom, Jeiel, and Azaziah with harps on the Sheminith to excel.

_2 verses containing ELIPHELEH_

== ELIPHELET

* `2Sa 23:34` *_Eliphelet_* the son of Ahasbai the son of the Maachathite, Eliam the son of Ahithophel the Gilonite,
* `1Ch 3:6` And also Ibhar, Elishama, *_Eliphelet_*,
* `1Ch 3:8` Elishama, Eliada, and *_Eliphelet_*, nine.
* `1Ch 8:39` And the sons of Eshek his brother were Ulam his first-born, Jehush the second, and *_Eliphelet_* the third.
* `Ezr 8:13` And of the last sons of Adonikam, whose names are these: *_Eliphelet_*, Jeiel, and Shemaiah, and with them sixty males.
* `Ezr 10:33` Of the sons of Hashum: Mattenai, Mattathah, Zabad, *_Eliphelet_*, Jeremai, Manasseh, and Shimei.

_6 verses containing ELIPHELET_

== ELISHA

* `1Ki 19:16` And Jehu the son of Nimshi you shall anoint to be king over Israel. And *_Elisha_* the son of Shaphat of Abel-meholah you shall anoint to be prophet in your stead.
* `1Ki 19:17` And it shall come to pass, that he who escapes the sword of Hazael, Jehu shall slay. And he who escapes from the sword of Jehu, *_Elisha_* shall slay.
* `1Ki 19:19` So he departed from there and found *_Elisha_* the son of Shaphat, who was plowing with twelve yoke of oxen before him, and he with the twelfth. And Elijah passed by him and cast his mantle upon him.
* `2Ki 2:1` And it came to pass, when the LORD would take up Elijah into heaven by a whirlwind, that Elijah went with *_Elisha_* from Gilgal.
* `2Ki 2:2` And Elijah said to *_Elisha_*, "Stay here, I pray you, for the LORD has sent me to Beth-el." And *_Elisha_* said, "As the LORD lives and as your soul lives, I will not leave you." So they went down to Beth-el.
* `2Ki 2:3` And the sons of the prophets who were at Beth-el came forth to *_Elisha_* and said to him, "Do you know that the LORD will take away your master from your head today?" And he said, "Yes, I know it. Hold your peace."
* `2Ki 2:4` And Elijah said to him, "*_Elisha_*, stay here, I pray you, for the LORD has sent me to Jericho." And he said, "As the LORD lives and as your soul lives, I will not leave you." So they came to Jericho.
* `2Ki 2:5` And the sons of the prophets who were at Jericho came to *_Elisha_* and said to him, "Do you know that the LORD will take away your master from your head today?" And he answered, "Yes, I know it. Hold your peace."
* `2Ki 2:9` And it came to pass, when they had gone over, that Elijah said to *_Elisha_*, "Ask what I shall do for you before I am taken away from you." And *_Elisha_* said, "I pray you, let a double portion of your spirit be upon me."
* `2Ki 2:12` And *_Elisha_* saw it and he cried, "My father, my father, the chariot of Israel and the horsemen thereof." And he saw him no more. And he took hold of his own clothes and rent them in two pieces.
* `2Ki 2:14` And he took the mantle of Elijah that fell from him and smote the waters and said, "Where is the LORD God of Elijah?" And when he also had smitten the waters, they parted here and there, and *_Elisha_* went over.
* `2Ki 2:15` And when the sons of the prophets who were viewing at Jericho saw him, they said, "The spirit of Elijah rests on *_Elisha_*." And they came to meet him and bowed themselves to the ground before him.
* `2Ki 2:19` And the men of the city said to *_Elisha_*, "Behold, I pray you, the location of this city is pleasant, as my lord sees, but the water is bad and the ground barren."
* `2Ki 2:22` So the waters were healed to this day, according to the saying of *_Elisha_* which he spoke.
* `2Ki 3:11` But Jehoshaphat said, "Is there not a prophet of the LORD here that we may inquire of the LORD by him?" And one of the king of Israel's servants answered and said, "Here is *_Elisha_* the son of Shaphat who poured water on the hands of Elijah."
* `2Ki 3:13` And *_Elisha_* said to the king of Israel, "What have I to do with you? Go to the prophets of your father and to the prophets of your mother." And the king of Israel said to him, "No, for the LORD has called these three kings together to deliver them into the hand of Moab."
* `2Ki 3:14` And *_Elisha_* said, "As the LORD of hosts lives, before whom I stand, surely, were it not that I regard the presence of Jehoshaphat the king of Judah, I would not look toward you, nor see you.
* `2Ki 4:1` Now there cried a certain woman of the wives of the sons of the prophets to *_Elisha_*, saying, "Your servant my husband is dead. And you know that your servant feared the LORD. And the creditor has come to take for himself my two sons to be slaves."
* `2Ki 4:2` And *_Elisha_* said to her, "What shall I do for you? Tell me, what do you have in the house?" And she said, "Your servant does not have anything in the house, except for a pot of oil."
* `2Ki 4:8` And it fell on a day, that *_Elisha_* passed to Shunem where a distinguished woman was, and she constrained him to eat bread. And so it was, that as often as he passed by, he turned in there to eat bread.
* `2Ki 4:17` And the woman conceived and bore a son at that season that *_Elisha_* had said to her, according to the time of life.
* `2Ki 4:32` And when *_Elisha_* had come into the house, behold, the child was dead and laid upon his bed.
* `2Ki 4:38` And *_Elisha_* came back to Gilgal. And there was a famine in the land. And the sons of the prophets were sitting before him. And he said to his servant, "Set on the great pot and boil pottage for the sons of the prophets."
* `2Ki 5:8` And it was so, when *_Elisha_* the man of God had heard that the king of Israel had rent his clothes, that he sent to the king, saying, "Why have you rent your clothes? I pray you, let him come to me and he shall know that there is a prophet in Israel."
* `2Ki 5:9` So Naaman came with his horses and with his chariot and stood at the door of the house of *_Elisha_*.
* `2Ki 5:10` And *_Elisha_* sent a messenger to him, saying, "Go and wash in the Jordan seven times, and your flesh shall come back to you and you shall be clean."
* `2Ki 5:20` But Gehazi, the servant of *_Elisha_* the man of God, thought, "Behold, my master has spared Naaman this Syrian in not receiving at his hands that which he brought. But as the LORD lives, I will run after him and take something from him."
* `2Ki 5:25` But he went in and stood before his master, and *_Elisha_* said to him, "Where did you come from, Gehazi?" And he said, "Your servant went nowhere."
* `2Ki 6:1` And the sons of the prophets said to *_Elisha_*, "Behold now, the place where we dwell with you is too narrow for us.
* `2Ki 6:12` And one of his servants said, "No one, my lord, O king, but *_Elisha_*, the prophet who is in Israel, tells the king of Israel the words that you speak in your bed-chamber."
* `2Ki 6:17` And *_Elisha_* prayed and said, "LORD, I pray you, open his eyes so that he may see." And the LORD opened the eyes of the young man, and he saw, and behold, the mountain was full of horses and chariots of fire around *_Elisha_*.
* `2Ki 6:18` And when they came down to him, *_Elisha_* prayed to the LORD and said, "Smite this people, I pray you, with blindness." And he smote them with blindness according to the word of *_Elisha_*.
* `2Ki 6:19` And *_Elisha_* said to them, "This is not the way, neither is this the city. Follow me, and I will bring you to the man whom you seek." But he led them to Samaria.
* `2Ki 6:20` And it came to pass, when they had come into Samaria, that *_Elisha_* said, "LORD, open the eyes of these men so that they may see." And the LORD opened their eyes, and they saw, and behold, they were in the midst of Samaria.
* `2Ki 6:21` And the king of Israel said to *_Elisha_* when he saw them, "My father, shall I smite them? Shall I smite them?"
* `2Ki 6:31` Then he said, "May God do so and more also to me, if the head of *_Elisha_* the son of Shaphat stands on him this day."
* `2Ki 6:32` But *_Elisha_* sat in his house, and the elders sat with him, and the king sent a man from before him. But before the messenger came to him, he said to the elders, "See how this son of a murderer has sent to take away my head? Look, when the messenger comes, shut the door and hold the door firmly against him. Is the sound of his master's feet not behind him?"
* `2Ki 7:1` Then *_Elisha_* said, "Hear the word of the LORD. Thus says the LORD: 'Tomorrow about this time a measure of fine flour shall be sold for a shekel and two measures of barley for a shekel in the gate of Samaria.'"
* `2Ki 8:1` Then *_Elisha_* spoke to the woman, whose son he had restored to life, saying, "Arise, and go—you and your household—and sojourn wherever you can sojourn, for the LORD has called for a famine, and it shall also come upon the land seven years."
* `2Ki 8:4` And the king talked with Gehazi the servant of the man of God, saying, "Tell me, I pray you, all the great things that *_Elisha_* has done."
* `2Ki 8:5` And it came to pass, as he was telling the king how [*_Elisha_*] had restored a dead body to life, that behold, the woman, whose son he had restored to life, cried to the king for her house and for her land. And Gehazi said, "My lord, O king, this is the woman and this is her son whom *_Elisha_* restored to life."
* `2Ki 8:7` And *_Elisha_* came to Damascus. And Ben-hadad the king of Syria was sick. And it was told to him, saying, "The man of God has come here."
* `2Ki 8:10` And *_Elisha_* said to him, "Go, say to him, 'You may certainly recover,' but the LORD has shown me that he shall surely die."
* `2Ki 8:13` And Hazael said, "But what, is your servant a dog that he should do this great thing?" And *_Elisha_* answered, "The LORD has shown me that you will be king over Syria."
* `2Ki 8:14` So he departed from *_Elisha_* and came to his master, who said to him, "What did *_Elisha_* say to you?" And he answered, "He told me that you should surely recover."
* `2Ki 9:1` And *_Elisha_* the prophet called one of the children of the prophets and said to him, "Gird up your loins, take this vial of oil in your hand, and go to Ramoth-gilead.
* `2Ki 13:14` Now *_Elisha_* had fallen sick with his disease of which he died. And Joash the king of Israel came down to him and wept over his face and said, "O my father, my father, the chariot of Israel and the horsemen thereof."
* `2Ki 13:15` And *_Elisha_* said to him, "Take a bow and arrows." And he took a bow and arrows.
* `2Ki 13:16` And he said to the king of Israel, "Put your hand upon the bow." And he put his hand upon it. And *_Elisha_* put his hands upon the king's hands.
* `2Ki 13:17` And he said, "Open the window eastward." And he opened it. Then *_Elisha_* said, "Shoot." And he shot. And he said, "The arrow of the LORD'S deliverance, and the arrow of deliverance from Syria, for you shall smite the Syrians in Aphek until you have consumed them."
* `2Ki 13:20` And *_Elisha_* died, and they buried him. And the bands of the Moabites invaded the land at the coming in of the year.
* `2Ki 13:21` And it came to pass, as they were burying a man, that behold, they spied a band of men, and they cast the man into the sepulcher of *_Elisha_*. And when the man was let down and touched the bones of *_Elisha_*, he revived and stood on his feet.
* `1Ch 1:7` And the sons of Javan: *_Elisha_*, Tarshish, Kittim, and Dodanim.
* `Luk 4:27` And many lepers were in Israel in the time of *_Elisha_* the prophet, and not one of them was cleansed, except Naaman the Syrian."

_54 verses containing ELISHA_

== ELISHAH

* `Gen 10:4` And the sons of Javan: *_Elishah_*, Tarshish, Kittim, and Dodanim.
* `Ezk 27:7` Fine linen with embroidered work from Egypt was that which you spread forth to be your sail. Blue and purple from the coastlands of *_Elishah_* was that which covered you.

_2 verses containing ELISHAH_

== ELISHAMA

* `Num 1:10` Of the children of Joseph, of Ephraim, *_Elishama_* the son of Ammihud, and of Manasseh, Gamaliel the son of Pedahzur;
* `Num 2:18` "On the west side shall be the standard of the camp of Ephraim according to their armies, and the captain of the sons of Ephraim shall be *_Elishama_* the son of Ammihud.
* `Num 7:48` On the seventh day *_Elishama_* the son of Ammihud, prince of the children of Ephraim, offered.
* `Num 7:53` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of *_Elishama_* the son of Ammihud.
* `Num 10:22` And the standard of the camp of the children of Ephraim moved forward according to their armies. And over his host was *_Elishama_* the son of Ammihud.
* `2Sa 5:16` *_Elishama_*, Eliada, and Eliphalet.
* `2Ki 25:25` But it came to pass in the seventh month, that Ishmael the son of Nethaniah, the son of *_Elishama_*, of the royal family, came, and ten men with him, and smote Gedaliah so that he died, along with the Jews and the Chaldeans who were with him at Mizpah.
* `1Ch 2:41` Shallum begot Jekamiah, and Jekamiah begot *_Elishama_*.
* `1Ch 3:6` And also Ibhar, *_Elishama_*, Eliphelet,
* `1Ch 3:8` *_Elishama_*, Eliada, and Eliphelet, nine.
* `1Ch 7:26` Laadan his son, Ammihud his son, *_Elishama_* his son,
* `1Ch 14:7` *_Elishama_*, Beeliada, and Eliphalet.
* `2Ch 17:8` And with them he sent Levites, even Shemaiah, Nethaniah, Zebadiah, Asahel, Shemiramoth, Jehonathan, Adonijah, Tobijah, and Tob-adonijah, Levites; and with them *_Elishama_* and Jehoram, priests.
* `Jer 36:12` He went down into the king's house, into the scribe's chamber, and behold, all the princes sat there, even *_Elishama_* the scribe, Delaiah the son of Shemaiah, Elnathan the son of Achbor, Gemariah the son of Shaphan, Zedekiah the son of Hananiah, and all the princes.
* `Jer 36:20` And they went to the king in the court, but they laid up the scroll in the chamber of *_Elishama_* the scribe and told all the words in the ears of the king.
* `Jer 36:21` So the king sent Jehudi to bring the scroll, and he took it out of the chamber of *_Elishama_* the scribe. And Jehudi read it in the ears of the king and in the ears of all the princes who stood beside the king.
* `Jer 41:1` Now it came to pass in the seventh month, that Ishmael the son of Nethaniah, the son of *_Elishama_*, of the royal family, and the princes of the king, even ten men with him, came to Gedaliah the son of Ahikam at Mizpah. And there they ate bread together in Mizpah.

_17 verses containing ELISHAMA_

== ELISHAPHAT

* `2Ch 23:1` And in the seventh year Jehoiada strengthened himself and took the captains of hundreds, even Azariah the son of Jeroham, Ishmael the son of Jehohanan, Azariah the son of Obed, Maaseiah the son of Adaiah, and *_Elishaphat_* the son of Zichri, into covenant with him.

_1 verse containing ELISHAPHAT_

== ELISHEBA

* `Exo 6:23` And Aaron took for himself *_Elisheba_*, daughter of Amminadab, sister of Naashon, for a wife. And she bore him Nadab, Abihu, Eleazar, and Ithamar.

_1 verse containing ELISHEBA_

== ELISHUA

* `2Sa 5:15` Ibhar, *_Elishua_*, Nepheg, Japhia,
* `1Ch 14:5` Ibhar, *_Elishua_*, Elpalet,

_2 verses containing ELISHUA_

== ELIUD

* `Mth 1:14` Azor begot Zadok, Zadok begot Achim, Achim begot *_Eliud_*,
* `Mth 1:15` *_Eliud_* begot Eleazar, Eleazar begot Matthan, Matthan begot Jacob,

_2 verses containing ELIUD_

== ELIZABETH

* `Luk 1:5` There was in the days of Herod the king of Judea, a certain priest named Zechariah, of the course of Abia. And his wife was of the daughters of Aaron, and her name was *_Elizabeth_*.
* `Luk 1:7` And they had no child because *_Elizabeth_* was barren and they were both far advanced in years.
* `Luk 1:13` But the angel said to him, "Do not fear, Zechariah, for your prayer is heard. Your wife *_Elizabeth_* shall bear you a son, and you shall call his name John.
* `Luk 1:24` And after those days his wife *_Elizabeth_* conceived and secluded herself five months, saying,
* `Luk 1:36` And behold, your cousin *_Elizabeth_*, she has also conceived a son in her old age, and this is the sixth month with her who was called barren.
* `Luk 1:40` And entered into the house of Zechariah and saluted *_Elizabeth_*.
* `Luk 1:41` And it came to pass, that when *_Elizabeth_* heard the salutation of Mary, the baby leaped in her womb, and *_Elizabeth_* was filled with the Holy Spirit.
* `Luk 1:57` Now *_Elizabeth_*'s full time came that she should deliver, and she brought forth a son.

_8 verses containing ELIZABETH_

== ELIZAPHAN

* `Num 3:30` And the chief of the house of the father of the families of the Kohathites shall be *_Elizaphan_* the son of Uzziel.
* `Num 34:25` The prince of the tribe of the children of Zebulun, *_Elizaphan_* the son of Parnach;
* `1Ch 15:8` Of the sons of *_Elizaphan_*: Shemaiah the chief and his brothers two hundred.
* `2Ch 29:13` And of the sons of *_Elizaphan_*: Shimri and Jeiel; and of the sons of Asaph: Zechariah and Mattaniah;

_4 verses containing ELIZAPHAN_

== ELIZUR

* `Num 1:5` And these are the names of the men who shall stand with you: of the tribe of Reuben, *_Elizur_* the son of Shedeur;
* `Num 2:10` "On the south side shall be the standard of the camp of Reuben according to their armies, and the captain of the children of Reuben shall be *_Elizur_* the son of Shedeur.
* `Num 7:30` On the fourth day *_Elizur_* the son of Shedeur, prince of the children of Reuben, offered.
* `Num 7:35` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of *_Elizur_* the son of Shedeur.
* `Num 10:18` And the standard of the camp of Reuben moved forward according to their armies. And over his host was *_Elizur_* the son of Shedeur.

_5 verses containing ELIZUR_

== ELKANAH

* `Exo 6:24` And the sons of Korah: Assir, *_Elkanah_*, and Abiasaph. These are the families of the Korhites.
* `1Sa 1:1` Now there was a certain man of Ramathaim-zophim, of mount Ephraim, and his name was *_Elkanah_*, the son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephrathite.
* `1Sa 1:4` And when the time was that *_Elkanah_* offered, he gave portions to Peninnah his wife and to all her sons and her daughters.
* `1Sa 1:8` Then *_Elkanah_* her husband said to her, "Hannah, why do you weep? And why do you not eat? And why is your heart grieved? Am I not better to you than ten sons?"
* `1Sa 1:19` And they rose early in the morning, worshiped before the LORD, and returned and came to their house in Ramah. And *_Elkanah_* knew Hannah his wife, and the LORD remembered her.
* `1Sa 1:21` And the man *_Elkanah_* and all his house went up to offer to the LORD the yearly sacrifice and his vow.
* `1Sa 1:23` And *_Elkanah_* her husband said to her, "Do what seems good to you. Stay until you have weaned him. Only may the LORD establish his word." So the woman stayed and nursed her son until she weaned him.
* `1Sa 2:11` And *_Elkanah_* went to his house in Ramah. And the child ministered to the LORD before Eli the priest.
* `1Sa 2:20` And Eli blessed *_Elkanah_* and his wife and said, "May the LORD give you children from this woman for the loan which is lent to the LORD." And they went to their own home.
* `1Ch 6:23` *_Elkanah_* his son, Ebiasaph his son, Assir his son,
* `1Ch 6:25` And the sons of *_Elkanah_*: Amasai and Ahimoth.
* `1Ch 6:26` As for *_Elkanah_*, the sons of *_Elkanah_*: Zophai his son, Nahath his son,
* `1Ch 6:27` Eliab his son, Jeroham his son, and *_Elkanah_* his son.
* `1Ch 6:34` The son of *_Elkanah_*, the son of Jeroham, the son of Eliel, the son of Toah,
* `1Ch 6:35` The son of Zuph, the son of *_Elkanah_*, the son of Mahath, the son of Amasai,
* `1Ch 6:36` The son of *_Elkanah_*, the son of Joel, the son of Azariah, the son of Zephaniah,
* `1Ch 9:16` And Obadiah the son of Shemaiah, the son of Galal, the son of Jeduthun; and Berechiah the son of Asa, the son of *_Elkanah_*, who dwelt in the villages of the Netophathites.
* `1Ch 12:6` *_Elkanah_*, Jesiah, Azareel, Joezer, and Jashobeam (the Korhites),
* `1Ch 15:23` And Berechiah and *_Elkanah_* were door-keepers for the ark.
* `2Ch 28:7` And Zichri, a mighty man of Ephraim, slew Maaseiah the king's son, Azrikam the governor of the house, and *_Elkanah_* who was next to the king.

_20 verses containing ELKANAH_

== ELKOSHITE

* `Nah 1:1` [The burden of Nineveh. The book of the vision of Nahum the *_Elkoshite_*.]

_1 verse containing ELKOSHITE_

== ELLASAR

* `Gen 14:1` And it came to pass in the days of Amraphel king of Shinar, Arioch king of *_Ellasar_*, Chedorlaomer king of Elam, and Tidal king of nations,
* `Gen 14:9` With Chedorlaomer the king of Elam, Tidal king of nations, Amraphel king of Shinar, and Arioch king of *_Ellasar_*—four kings against five.

_2 verses containing ELLASAR_

== ELMADAM

* `Luk 3:28` Who was the son of Melchi, who was the son of Addi, who was the son of Cosam, who was the son of *_Elmadam_*, who was the son of Er,

_1 verse containing ELMADAM_

== ELMS

* `Hos 4:13` They sacrifice upon the tops of the mountains and burn incense upon the hills, under oaks, poplars, and *_elms_*, because their shade is agreeable. Therefore, your daughters shall be guilty of lewdness and your spouses shall commit adultery.

_1 verse containing ELMS_

== ELNAAM

* `1Ch 11:46` Eliel the Mehavite, Jeribai and Joshaviah the sons of *_Elnaam_*, Ithmah the Moabite,

_1 verse containing ELNAAM_

== ELNATHAN

* `2Ki 24:8` Jehoiachin was eighteen years old when he began to reign, and he reigned three months in Jerusalem. And his mother's name was Nehushta, the daughter of *_Elnathan_* of Jerusalem.
* `Ezr 8:16` Then I sent for Eliezer, for Ariel, for Shemaiah, for *_Elnathan_*, for Jarib, for *_Elnathan_*, for Nathan, for Zechariah, and for Meshullam, chief men, and also for Joiarib and for *_Elnathan_*, men of understanding.
* `Jer 26:22` And Jehoiakim the king sent men into Egypt, namely, *_Elnathan_* the son of Achbor and some men with him into Egypt.
* `Jer 36:12` He went down into the king's house, into the scribe's chamber, and behold, all the princes sat there, even Elishama the scribe, Delaiah the son of Shemaiah, *_Elnathan_* the son of Achbor, Gemariah the son of Shaphan, Zedekiah the son of Hananiah, and all the princes.
* `Jer 36:25` Nevertheless, *_Elnathan_*, Delaiah, and Gemariah had made intercession to the king that he would not burn the scroll, but he would not hear them.

_5 verses containing ELNATHAN_

== ELOI

* `Mrk 15:34` And at the ninth hour Jesus cried with a loud voice, saying, "*_Eloi_*, *_Eloi_*, lama sabachthani?" (which is, being interpreted, "My God, my God, why have you forsaken me?")

_1 verse containing ELOI_

== ELON

* `Gen 26:34` And Esau was forty years old when he took for a wife Judith the daughter of Beeri the Hittite and Bashemath the daughter of *_Elon_* the Hittite,
* `Gen 36:2` Esau took his wives from the daughters of Canaan: Adah the daughter of *_Elon_* the Hittite; Aholibamah the daughter of Anah, the daughter of Zibeon the Hivite;
* `Gen 46:14` And the sons of Zebulun: Sered, *_Elon_*, and Jahleel.
* `Num 26:26` Of the sons of Zebulun after their families: of Sered, the family of the Sardites; of *_Elon_*, the family of the Elonites; of Jahleel, the family of the Jahleelites.
* `Jsh 19:43` *_Elon_*, Thimnathah, Ekron,
* `Jdg 12:11` And after him *_Elon_*, a Zebulonite, judged Israel, and he judged Israel for ten years.
* `Jdg 12:12` And *_Elon_* the Zebulonite died and was buried in Ajalon in the country of Zebulun.
* `1Ki 4:9` The son of Dekar, in Makaz, in Shaalbim, Beth-shemesh, and *_Elon_*-beth-hanan;

_8 verses containing ELON_

== ELON-BETH-HANAN

* `1Ki 4:9` The son of Dekar, in Makaz, in Shaalbim, Beth-shemesh, and *_Elon-beth-hanan_*;

_1 verse containing ELON-BETH-HANAN_

== ELONITES

* `Num 26:26` Of the sons of Zebulun after their families: of Sered, the family of the Sardites; of Elon, the family of the *_Elonites_*; of Jahleel, the family of the Jahleelites.

_1 verse containing ELONITES_

== ELOQUENT

* `Exo 4:10` And Moses said to the LORD, "O my Lord, I am not *_eloquent_*, neither before, nor since you have spoken to your servant, but I am slow of speech and of a slow tongue."
* `Isa 3:3` The captain of fifty, the honorable man, the counselor, the skillful craftsman, and the *_eloquent_* orator.
* `Act 18:24` And a certain Jew named Apollos, born at Alexandria, an *_eloquent_* man and mighty in the Scriptures, came to Ephesus.

_3 verses containing ELOQUENT_

== ELOTH

* `1Ki 9:26` And king Solomon made a navy of ships in Ezion-geber, which is beside *_Eloth_*, on the shore of the Red Sea in the land of Edom.
* `2Ch 8:17` Then Solomon went to Ezion-geber and to *_Eloth_*, at the sea side in the land of Edom.
* `2Ch 26:2` He built *_Eloth_* and restored it to Judah after the king slept with his fathers.

_3 verses containing ELOTH_

== ELPAAL

* `1Ch 8:11` And by Hushim he begot Ahitub and *_Elpaal_*.
* `1Ch 8:12` The sons of *_Elpaal_*: Eber, Misham, Shamed (who built Ono and Lod, with its town),
* `1Ch 8:18` Ishmerai, Jezliah, and Jobab were the sons of *_Elpaal_*.

_3 verses containing ELPAAL_

== ELPALET

* `1Ch 14:5` Ibhar, Elishua, *_Elpalet_*,

_1 verse containing ELPALET_

== ELSE

* `Gen 19:12` And the men said to Lot, "Do you have anyone *_else_* here? Sons-in-law, your sons, your daughters, and whomever you have in the city, bring them out of this place.
* `Gen 30:1` And when Rachel saw that she bore Jacob no children, Rachel envied her sister and said to Jacob, "Give me children, or *_else_* I die."
* `Gen 42:16` Send one of you and let him bring your brother. You shall be kept in prison so that your words may be proved whether there is any truth in you. Or *_else_*, by the life of Pharaoh, surely you are spies."
* `Exo 8:21` Or *_else_*, if you will not let my people go, behold, I will send swarms of flies upon you, upon your servants, upon your people, and into your houses. And the houses of the Egyptians shall be full of swarms of flies, and also the ground on which they are.
* `Exo 10:4` Or *_else_*, if you refuse to let my people go, behold, tomorrow I will bring the locusts into your border.
* `Num 20:19` And the children of Israel said to him, "We will go by the highway, and if I and my livestock drink your water, then I will pay for it. I will only, without doing anything *_else_*, go through on my feet."
* `Deu 4:39` Know therefore this day, and consider it in your heart, that the LORD, he is God in heaven above and upon the earth beneath. There is no one *_else_*.
* `Jdg 7:14` And his fellow answered, and said, "This is nothing *_else_* but the sword of Gideon the son of Joash, a man of Israel. For into his hand, God has delivered Midian and all the host."
* `2Sa 3:35` And when all the people came to cause David to eat food while it was still day, David swore, saying, "May God do so to me and more also if I taste bread or anything *_else_* until the sun is down."
* `2Sa 15:14` And David said to all his servants who were with him at Jerusalem, "Arise and let us flee, or *_else_* we shall not escape from Absalom. Make speed to depart, lest he should overtake us suddenly and bring evil upon us and smite the city with the edge of the sword."
* `1Ki 8:60` So that all the people of the earth may know that the LORD is God and that there is no one *_else_*.
* `1Ki 20:39` And as the king passed by, he cried to the king, and said, "Your servant went out into the midst of the battle, and behold, a man turned aside and brought a man to me and said, 'Keep this man. If by any means he is missing, then your life shall be for his life, or *_else_* you shall pay a talent of silver.'
* `1Ki 21:6` And he said to her, "Because I spoke to Naboth the Jezreelite and said to him, 'Give me your vineyard for money, or *_else_*, if it pleases you, I will give you another vineyard for it.' And he answered, 'I will not give you my vineyard.'"
* `1Ch 21:12` Either three years of famine, or three months to be destroyed before your foes while the sword of your enemies overtakes you, or *_else_* three days of the sword of the LORD, even the pestilence in the land and the angel of the LORD destroying throughout all the borders of Israel.' Now therefore, advise yourself what word I shall bring back to him who sent me."
* `2Ch 23:7` And the Levites shall encompass the king, each with his weapons in his hand. And whoever *_else_* comes into the house, he shall be put to death. But be with the king when he comes in and when he goes out."
* `Psa 51:16` For you do not desire sacrifice, or *_else_* I would give it. You do not delight in burnt-offering.
* `Ecc 2:25` For who can eat, or who *_else_* can hasten to it more than I?
* `Isa 45:5` I am the LORD, and there is no one *_else_*. There is no God besides me. I girded you, though you have not known me,
* `Isa 45:6` So that they may know from the rising of the sun and from the west, that there is no one besides me. I am the LORD, and there is no one *_else_*.
* `Isa 45:14` Thus says the LORD: "The labor of Egypt and merchandise of Cush, along with the Sabeans, men of stature, shall come over to you, and they shall be yours. They shall come after you. In chains they shall come over, and they shall fall down to you. They shall make supplication to you, saying, 'Surely God is in you, and there is no one *_else_*. There is no other God.'"
* `Isa 45:18` For thus says the LORD who created the heavens (God himself who formed the earth and made it, who has established it, who did not create it in vain, who formed it to be inhabited): "I am the LORD, and there is no one *_else_*.
* `Isa 45:22` Look to me and be saved, all the ends of the earth, for I am God, and there is no one *_else_*.
* `Isa 46:9` Remember the former things of old, for I am God, and there is no one *_else_*. I am God, and there is no one like me,
* `Isa 47:8` Now therefore, hear this, you who are given to pleasures, who dwell carelessly, who say in your heart, 'I am, and no one *_else_* besides me. I shall not sit as a widow, neither shall I know the loss of children.'
* `Isa 47:10` For you have trusted in your wickedness. You have said, 'No one sees me.' Your wisdom and your knowledge, it has perverted you. And you have said in your heart, 'I am, and no one *_else_* besides me.'
* `Jer 9:7` Therefore, thus says the LORD of hosts: "Behold, I will melt them and try them. For what *_else_* shall I do for the daughter of my people?
* `Joe 2:27` And you shall know that I am in the midst of Israel and that I am the LORD your God, and no one *_else_*. And my people shall never be ashamed.
* `Mth 6:24` "No man can serve two masters, for either he will hate one and love the other, or *_else_* he will hold to one and despise the other. You cannot serve God and mammon.
* `Mth 9:17` Men do not put new wine into old bottles, or *_else_* the bottles break, the wine runs out, and the bottles perish. But they put new wine into new bottles and both are preserved."
* `Mth 12:29` Or *_else_*, how can one enter into a strong man's house and seize his goods unless he first binds the strong man? Then he will plunder his house.
* `Mth 12:33` "Either make the tree good and its fruit good, or *_else_* make the tree corrupt and its fruit corrupt, for the tree is known by its fruit.
* `Mth 13:15` For this people's heart has become callous, their ears are dull of hearing, and their eyes they have closed, or *_else_* perhaps they should see with their eyes, hear with their ears, and should understand with their heart and should be converted, and I should heal them.'
* `Mrk 2:21` "No man also sews a patch of new cloth on an old garment, or *_else_* the new piece that filled it up takes away from the old and the rent is made worse.
* `Mrk 2:22` And no man puts new wine into old bottles, or *_else_* the new wine bursts the bottles, and the wine is spilled and the bottles will be marred. But new wine must be put into new bottles."
* `Luk 5:36` And he also spoke a parable to them: "No man puts a patch of a new garment upon an old, or *_else_* the new makes a rent and the piece that was taken out of the new does not agree with the old.
* `Luk 5:37` And no man puts new wine into old bottles, or *_else_* the new wine will burst the bottles and be spilled and the bottles will perish.
* `Luk 14:29` Or *_else_*, after he has laid the foundation and is not able to finish it, all who behold it begin to mock him,
* `Luk 14:32` Or *_else_*, while the other is yet a great way off, he sends an embassy and desires conditions of peace.
* `Luk 16:13` No servant can serve two masters. For either he will hate one and love the other, or *_else_* he will hold to one and despise the other. You cannot serve God and mammon."
* `Jhn 14:11` Believe me that I am in the Father and the Father in me, or *_else_* believe me for the very works' sake.
* `Act 17:21` For all the Athenians and strangers who were there spent their time in nothing *_else_* but either to tell or to hear some new thing.
* `Act 24:20` Or *_else_*, let these same here say if they have found any evil-doing in me while I stood before the council,
* `Rom 2:15` In that they show the work of the law written in their hearts, their conscience also bearing testimony and their thoughts between one another accusing, or *_else_* excusing one another—
* `1Co 14:16` Or *_else_*, when you bless with the spirit, how shall he who occupies the room of the unlearned say, "Amen," at your giving of thanks, seeing he does not understand what you say?
* `1Co 15:29` Or *_else_*, what will those do who are baptized for the dead if the dead do not rise at all? Why are they then baptized for the dead?
* `Phl 1:27` Only let your manner of life be worthy of the gospel of Christ, so that whether I come and see you or *_else_* am absent, I may hear of your affairs, that you stand firm in one spirit, with one mind striving together for the faith of the gospel,
* `Rev 2:16` Repent, or *_else_* I will come to you quickly and will fight against them with the sword of my mouth.

_47 verses containing ELSE_

== ELSEWHERE

* `Psa 84:10` For a day in your courts is better than a thousand [*_elsewhere_*]. I would rather be a door-keeper in the house of my God than dwell in the tents of wickedness.

_1 verse containing ELSEWHERE_

== ELTEKEH

* `Jsh 19:44` *_Eltekeh_*, Gibbethon, Baalath,
* `Jsh 21:23` And out of the tribe of Dan, *_Eltekeh_* with its suburbs, Gibbethon with its suburbs,

_2 verses containing ELTEKEH_

== ELTEKON

* `Jsh 15:59` Maarath, Beth-anoth, and *_Eltekon_*; six cities with their villages.

_1 verse containing ELTEKON_

== ELTOLAD

* `Jsh 15:30` *_Eltolad_*, Chesil, Hormah,
* `Jsh 19:4` *_Eltolad_*, Bethul, Hormah,

_2 verses containing ELTOLAD_

== ELUL

* `Neh 6:15` So the wall was finished on the twenty-fifth day of the month *_Elul_*, in fifty-two days.

_1 verse containing ELUL_

== ELUZAI

* `1Ch 12:5` *_Eluzai_*, Jerimoth, Bealiah, Shemariah, Shephatiah the Haruphite,

_1 verse containing ELUZAI_

== ELYMAS

* `Act 13:8` But *_Elymas_* the sorcerer (for that is his name by interpretation) withstood them, seeking to turn away the deputy from the faith.

_1 verse containing ELYMAS_

== ELZABAD

* `1Ch 12:12` Johanan the eighth, *_Elzabad_* the ninth,
* `1Ch 26:7` The sons of Shemaiah: Othni, Rephael, Obed, *_Elzabad_* (whose brothers were strong men), Elihu, and Semachiah.

_2 verses containing ELZABAD_

== ELZAPHAN

* `Exo 6:22` And the sons of Uzziel: Mishael, *_Elzaphan_*, and Zithri.
* `Lev 10:4` And Moses called Mishael and *_Elzaphan_*, the sons of Uzziel the uncle of Aaron, and said to them, "Come near, carry your brothers from before the sanctuary out of the camp."

_2 verses containing ELZAPHAN_

== EMBALM

* `Gen 50:2` And Joseph commanded his servants the physicians to *_embalm_* his father. And the physicians embalmed Israel.

_1 verse containing EMBALM_

== EMBALMED

* `Gen 50:2` And Joseph commanded his servants the physicians to embalm his father. And the physicians *_embalmed_* Israel.
* `Gen 50:3` And forty days were fulfilled for him (for thus they fulfilled the days of those who are *_embalmed_*), and the Egyptians mourned for him seventy days.
* `Gen 50:26` So Joseph died, being one hundred and ten years old. And they *_embalmed_* him, and he was put in a coffin in Egypt.

_3 verses containing EMBALMED_

== EMBASSY

* `Luk 14:32` Or else, while the other is yet a great way off, he sends an *_embassy_* and desires conditions of peace.

_1 verse containing EMBASSY_

== EMBOLDENED

* `1Co 8:10` For if any man sees you, who have knowledge, eating in the idol's temple, will the conscience of him who is weak not be *_emboldened_* to eat those things which are offered to idols?

_1 verse containing EMBOLDENED_

== EMBOLDENS

* `Job 16:3` Shall vain words have an end? Or what *_emboldens_* you that you answer?

_1 verse containing EMBOLDENS_

== EMBRACE

* `2Ki 4:16` And he said, "About this season, according to the time of life, you shall *_embrace_* a son." And she said, "No, my lord, man of God, do not lie to your servant."
* `Job 24:8` They are wet with the showers of the mountains and *_embrace_* the rock for lack of a shelter.
* `Pro 4:8` Exalt her, and she shall promote you. She shall bring you to honor when you *_embrace_* her.
* `Pro 5:20` And why will you, my son, be ravished with a strange woman and *_embrace_* the bosom of a stranger?
* `Ecc 3:5` A time to cast away stones, and a time to gather stones; a time to *_embrace_*, and a time to refrain from embracing;
* `Sos 8:3` His left hand should be under my head and his right hand should *_embrace_* me.
* `Lam 4:5` [HE] Those who fed delicately are desolate in the streets. Those who were brought up in scarlet *_embrace_* dunghills.

_7 verses containing EMBRACE_

== EMBRACED

* `Gen 29:13` And it came to pass when Laban heard the tidings of Jacob his sister's son, that he ran to meet him, *_embraced_* him, kissed him, and brought him to his house. And he told Laban all these things.
* `Gen 33:4` And Esau ran to meet him, *_embraced_* him, fell on his neck, and kissed him, and they wept.
* `Gen 48:10` (Now the eyes of Israel were dim with age so that he could not see.) And he brought them near to him, and he kissed them and *_embraced_* them.
* `Act 20:1` And after the uproar had ceased, Paul called the disciples to him, *_embraced_* them, and departed to go into Macedonia.

_4 verses containing EMBRACED_

== EMBRACES

* `Sos 2:6` His left hand is under my head and his right hand *_embraces_* me.

_1 verse containing EMBRACES_

== EMBRACING

* `Ecc 3:5` A time to cast away stones, and a time to gather stones; a time to embrace, and a time to refrain from *_embracing_*;
* `Act 20:10` And Paul went down and fell on him, and *_embracing_* him, said, "Do not trouble yourselves, for his life is in him."

_2 verses containing EMBRACING_

== EMBROIDER

* `Exo 28:39` "And you shall *_embroider_* the coat of fine linen, you shall make the miter of fine linen, and you shall make the girdle of needle-work.

_1 verse containing EMBROIDER_

== EMBROIDERED

* `Exo 28:4` And these are the garments which they shall make: a breast-plate, an ephod, a robe, an *_embroidered_* coat, a miter, and a girdle. And they shall make holy garments for Aaron your brother and his sons so that he may minister to me in the priest's office.
* `Ezk 16:10` I also clothed you with *_embroidered_* work, shod you with badgers' skin, girded you with fine linen, and I covered you with silk.
* `Ezk 16:13` Thus you were decked with gold and silver, and your clothing was of fine linen, silk, and *_embroidered_* work. You ate fine flour, honey, and oil. You were exceedingly beautiful and you prospered into a kingdom.
* `Ezk 16:18` And you have taken your *_embroidered_* garments and covered them, and you have set my oil and my incense before them.
* `Ezk 26:16` Then all the princes of the sea shall come down from their thrones, lay away their robes, and take off their *_embroidered_* garments. They shall clothe themselves with trembling. They shall sit upon the ground and shall tremble at every moment and be astonished at you.
* `Ezk 27:7` Fine linen with *_embroidered_* work from Egypt was that which you spread forth to be your sail. Blue and purple from the coastlands of Elishah was that which covered you.
* `Ezk 27:16` Syria was your merchant by reason of the multitude of the wares of your making. They occupied in your fairs with emeralds, purple, *_embroidered_* work, fine linen, coral, and agate.
* `Ezk 27:24` These were your merchants in all sorts of things, in blue clothes, *_embroidered_* work, and in chests of rich apparel, bound with cords and made of cedar, among your merchandise.

_8 verses containing EMBROIDERED_

== EMBROIDERER

* `Exo 35:35` He has filled them with wisdom of heart to work all manner of work of the engraver, of the skillful workmen, of the *_embroiderer_*, in blue, in purple, in scarlet, and in fine linen, and of the weaver, even of those who do any work, and of those who devise skillful work."
* `Exo 38:23` And with him was Aholiab, son of Ahisamach, of the tribe of Dan, an engraver, a skillful workman, and an *_embroiderer_* in blue, in purple, in scarlet, and fine linen.

_2 verses containing EMBROIDERER_

== EMBRYO

* `Jer 1:5` "Before I formed you in *_embryo_* I knew you. And before you were born I sanctified you and ordained you a prophet to the nations."

_1 verse containing EMBRYO_

== EMERALD

* `Exo 28:18` And the second row shall be an *_emerald_*, a sapphire, and a diamond.
* `Exo 39:11` The second row, an *_emerald_*, a sapphire, and a diamond;
* `Ezk 28:13` You have been in Eden the garden of God. Every precious stone was your covering: the sardius, topaz, the diamond, the beryl, the onyx, the jasper, the sapphire, the *_emerald_*, the carbuncle, and gold. The workmanship of your tambourines and of your pipes was prepared in you in the day that you were created.
* `Rev 4:3` And he who sat was in appearance like a jasper and a sardius stone. And there was a rainbow around the throne in sight like an *_emerald_*.
* `Rev 21:19` And the foundations of the wall of the city were garnished with all manner of precious stones. The first foundation was jasper; the second, sapphire; the third, a chalcedony; the fourth, an *_emerald_*;

_5 verses containing EMERALD_

== EMERALDS

* `Ezk 27:16` Syria was your merchant by reason of the multitude of the wares of your making. They occupied in your fairs with *_emeralds_*, purple, embroidered work, fine linen, coral, and agate.

_1 verse containing EMERALDS_

== EMERODS

* `Deu 28:27` "The LORD will smite you with the boil of Egypt, with the *_emerods_*, with the scab, and with the itch, of which you cannot be healed.
* `1Sa 5:6` But the hand of the LORD was heavy upon those of Ashdod, and he destroyed them and smote them with *_emerods_*, even Ashdod and its borders.
* `1Sa 5:9` And it was so, that after they had carried it there, the hand of the LORD was against the city with a very great destruction, and he smote the men of the city both small and great, and they had *_emerods_* in their secret parts.
* `1Sa 5:12` And the men who did not die were smitten with the *_emerods_*, and the cry of the city went up to heaven.
* `1Sa 6:4` Then they said, "What shall be the trespass-offering which we shall return to him?" They answered, "Five golden *_emerods_* and five golden mice, according to the number of the lords of the Philistines, for one plague was on you all and on your lords.
* `1Sa 6:5` Therefore, you shall make images of your *_emerods_* and images of your mice that mar the land, and you shall give glory to the God of Israel. It may be that he will lighten his hand from off you, from off your gods, and from off your land.
* `1Sa 6:11` And they laid the ark of the LORD upon the cart and the coffer with the mice of gold and the images of their *_emerods_*.
* `1Sa 6:17` And these are the golden *_emerods_* which the Philistines returned for a trespass-offering to the LORD: for Ashdod, one; for Gaza, one; for Askelon, one; for Gath, one; for Ekron, one;

_8 verses containing EMERODS_

== EMIMS

* `Deu 2:10` (The *_Emims_* dwelt in it in times past, a people great and many and tall as the Anakims,
* `Deu 2:11` Who also were accounted Rephaim, as the Anakims, but the Moabites call them *_Emims_*.

_2 verses containing EMIMS_

== EMINENT

* `Ezk 16:24` That you have also built for yourself an *_eminent_* place and have made yourself a high place in every street.
* `Ezk 16:31` In that you build your *_eminent_* place in the head of every way and make your high place in every street. But you have not been like a harlot, in that you scorn payment.
* `Ezk 16:39` And I will also give you into their hand, and they shall throw down your *_eminent_* place and break down your high places. They shall also strip you of your clothes, take your fair jewels, and leave you naked and bare.
* `Ezk 17:22` Thus says the Lord GOD: "I will also take from the highest branch of the high cedar, and will set it. I will crop off from the top of its young twigs a tender one and plant it upon a high and *_eminent_* mountain.

_4 verses containing EMINENT_

== EMINS

* `Gen 14:5` And in the fourteenth year, Chedorlaomer and the kings who were with him came and smote the Rephaims in Ashteroth Karnaim, the Zuzims in Ham, the *_Emins_* in Shaveh Kiriathaim,

_1 verse containing EMINS_

== EMMAUS

* `Luk 24:13` And behold, two of them went that same day to a village called *_Emmaus_*, which was from Jerusalem about sixty furlongs.

_1 verse containing EMMAUS_

== EMORITE

* `Gen 10:16` The Jebusite, the *_Emorite_*, the Girgasite,

_1 verse containing EMORITE_

