= ENRAGED - ESLI
:toc:

== ENRAGED

* `Psa 102:8` My enemies reproach me all the day, and those who are *_enraged_* against me have sworn against me.
* `Jer 25:16` And they shall drink and be moved and *_enraged_* because of the sword that I will send among them."
* `Act 26:11` And I punished them often in every synagogue and compelled them to blaspheme, and being exceedingly *_enraged_* against them, I persecuted them even to foreign cities.

_3 verses containing ENRAGED_

== ENRICH

* `1Sa 17:25` And the men of Israel said, "Have you seen this man who has come up? Surely to defy Israel he has come. And it shall be, that the man who kills him, the king will *_enrich_* him with great riches, give him his daughter, and make his father's house free in Israel."
* `Psa 65:9` You visit the earth and water it. You greatly *_enrich_* it with the river of God, which is full of water. You prepare their grain when you have thus provided for it.

_2 verses containing ENRICH_

== ENRICHED

* `Ezk 27:33` When your wares went forth out of the seas, you filled many people. You *_enriched_* the kings of the earth with the multitude of your riches and of your merchandise.
* `1Co 1:5` That in everything you are *_enriched_* by him, in all utterance and in all knowledge,
* `2Co 9:11` Being *_enriched_* in everything to all bountifulness, which through us causes thanksgiving to God.

_3 verses containing ENRICHED_

== ENROLLED

* `1Ti 5:9` Let a woman be *_enrolled_* as a widow not under sixty years old, having been the wife of one man,

_1 verse containing ENROLLED_

== ENSIGN

* `Num 2:2` "Every man of the children of Israel shall pitch by his own standard with the *_ensign_* of their father's house. Far off around the Tabernacle of the Congregation they shall pitch.
* `Isa 5:26` And he will lift up an *_ensign_* to the nations from afar and will hiss to them from the end of the earth, and behold, they shall come with speed swiftly.
* `Isa 11:10` And in that day there shall be a root of Jesse which shall stand for an *_ensign_* of the people. The Gentiles shall seek it. And his rest shall be glorious.
* `Isa 11:12` And he shall set up an *_ensign_* for the nations, and shall assemble the outcasts of Israel and gather the dispersed of Judah from the four corners of the earth.
* `Isa 18:3` All you inhabitants of the world and dwellers on the earth, see when he lifts up an *_ensign_* on the mountains. And when he blows a trumpet, hear.
* `Isa 30:17` One thousand shall flee at the rebuke of one. At the rebuke of five you shall flee until you are left like a beacon upon the top of a mountain and like an *_ensign_* on a hill.
* `Isa 31:9` And he shall pass over to his stronghold for fear, and his princes shall be afraid of the *_ensign_*," says the LORD, whose fire is in Zion and his furnace in Jerusalem.
* `Zch 9:16` And the LORD their God will save them in that day as the flock of his people, for they shall be as the stones of a crown, lifted up as an *_ensign_* upon his land.

_8 verses containing ENSIGN_

== ENSIGNS

* `Psa 74:4` Your enemies roar in the midst of your congregations. They set up their *_ensigns_* for signs.

_1 verse containing ENSIGNS_

== ENSLAVED

* `Rom 6:18` Being then made free from sin, you became *_enslaved_* to righteousness.

_1 verse containing ENSLAVED_

== ENSNARED

* `Job 34:30` This is so that the hypocrite may not reign, lest the people should be *_ensnared_*.
* `Isa 8:15` And many among them shall stumble, fall, be broken, be *_ensnared_*, and be taken."

_2 verses containing ENSNARED_

== ENTANGLED

* `2Pe 2:20` For if, after they have escaped the pollutions of the world through the knowledge of the Lord and Savior Jesus Christ, they are again *_entangled_* in them and overcome, the latter end is worse with them than the beginning.

_1 verse containing ENTANGLED_

== ENTANGLES

* `2Ti 2:4` No man who wars *_entangles_* himself with the affairs of this life so that he may please him who has chosen him to be a soldier.

_1 verse containing ENTANGLES_

== ENTER

* `Gen 12:11` And it came to pass, when he had come near to *_enter_* into Egypt, that he said to Sarai his wife, "Behold now, I know that you are a fair woman to look upon;
* `Exo 28:43` And they shall be upon Aaron and upon his sons when they *_enter_* into the Tabernacle of the Congregation or when they come near to the altar to minister in the holy place so that they do not bear iniquity and die. It shall be a statute forever to him and to his offspring after him."
* `Exo 40:35` And Moses was not able to *_enter_* into the tent of the congregation because the cloud stayed upon it and the glory of the LORD filled the tabernacle.
* `Num 4:3` From thirty years old and upward, even until fifty years old, all who *_enter_* into the host to do the work in the Tabernacle of the Congregation.
* `Num 4:23` From thirty years old and upward until fifty years old you shall number them—all who *_enter_* in to perform the service to do the work in the Tabernacle of the Congregation.
* `Num 5:24` And he shall cause the woman to drink the bitter water that causes the curse. And the water that causes the curse shall *_enter_* into her and become bitter.
* `Num 5:27` And when he has made her to drink the water, it shall come to pass, that if she is defiled and has done trespass against her husband, that the water that causes the curse shall *_enter_* into her and become bitter, and her belly shall swell and her thigh shall perish, and the woman shall be a curse among her people.
* `Num 20:24` "Aaron shall be gathered to his people, for he shall not *_enter_* into the land which I have given to the children of Israel because you rebelled against my word at the water of Meribah.
* `Deu 4:21` "Furthermore, the LORD was angry with me for your sakes, and swore that I should not go over the Jordan, and that I should not *_enter_* that good land which the LORD your God gives you for an inheritance.
* `Deu 23:1` "He who is wounded or mutilated in his secrets shall not *_enter_* into the congregation of the LORD.
* `Deu 23:2` An illegitimate son shall not *_enter_* into the congregation of the LORD. Even to his tenth generation he shall not *_enter_* into the congregation of the LORD.
* `Deu 23:3` An Ammonite or Moabite shall not *_enter_* into the congregation of the LORD. Even to their tenth generation they shall not *_enter_* into the congregation of the LORD forever,
* `Deu 23:8` The children who are begotten by them shall *_enter_* into the congregation of the LORD in their third generation.
* `Deu 27:3` And you shall write upon them all the words of this law when you have passed over so that you may *_enter_* the land which the LORD your God gives you, a land that flows with milk and honey, as the LORD God of your fathers has promised you.
* `Deu 29:12` So that you should *_enter_* into covenant with the LORD your God and into his oath, which the LORD your God makes with you this day,
* `Jsh 10:19` And do not stay, but pursue your enemies and smite the hindmost of them. Do not allow them to *_enter_* into their cities, for the LORD your God has delivered them into your hand."
* `Jdg 18:9` And they said, "Arise, so that we may go up against them. For we have seen the land, and behold, it is very good. And are you still? Do not be slothful to go and to *_enter_* to possess the land.
* `1Sa 9:13` As soon as you *_enter_* the city, you will immediately find him before he goes up to the high place to eat. For the people will not eat until he comes because he blesses the sacrifice. And afterward, those who are invited will eat. Now therefore, go up, for about this time you will find him."
* `1Ki 12:18` Then king Rehoboam sent Adoram, who was over the tribute. And all Israel stoned him with stones so that he died. Therefore, king Rehoboam made speed to *_enter_* his chariot to flee to Jerusalem.
* `1Ki 14:12` Therefore, arise, depart to your own house. And when your feet *_enter_* into the city, the child shall die.
* `1Ki 22:30` And the king of Israel said to Jehoshaphat, "I will disguise myself and *_enter_* into the battle, but you put on your robes." And the king of Israel disguised himself and went into the battle.
* `2Ki 7:4` If we say, 'We will *_enter_* into the city,' then the famine is in the city, and we shall die there. And if we sit still here, we die also. Now therefore, come, and let us fall to the army of the Syrians. If they save us alive, we shall live, and if they kill us, then we shall die."
* `2Ki 11:5` And he commanded them, saying, "This is the thing that you shall do: a third part of you who *_enter_* in on the sabbath shall even be keepers of the watch of the king's house,
* `2Ki 19:23` By your messengers you have reproached the Lord and have said, "With the multitude of my chariots I have come up to the height of the mountains, to the sides of Lebanon, and will cut down its tall cedar trees and its choice fir trees. And I will *_enter_* into the lodgings of his borders and into the forest of his Carmel.
* `2Ch 7:2` And the priests could not *_enter_* into the house of the LORD because the glory of the LORD had filled the LORD'S house.
* `2Ch 23:19` And he set the gatekeepers at the gates of the house of the LORD so that no one who was unclean in anything should *_enter_*.
* `2Ch 27:2` And he did that which was right in the sight of the LORD, according to all that his father Uzziah did; however, he did not *_enter_* into the temple of the LORD. And the people yet again acted corruptly.
* `2Ch 30:8` Now do not be stiff-necked as your fathers were, but yield yourselves to the LORD and *_enter_* into his sanctuary which he has sanctified forever, and serve the LORD your God so that the fierceness of his wrath may turn away from you.
* `Neh 2:8` And a letter to Asaph the keeper of the king's forest so that he may give me timber to make beams for the gates of the palace which belonged to the house, for the wall of the city, and for the house that I shall *_enter_*." And the king granted me, according to the good hand of my God upon me.
* `Est 4:2` And he came as far as the king's gate, for no one could *_enter_* into the king's gate clothed with sackcloth.
* `Job 22:4` Will he reprove you for fear of you? Will he *_enter_* with you into judgment?
* `Job 34:23` For he will not lay upon man more than right, that he should *_enter_* into judgment with God.
* `Psa 37:15` Their sword shall *_enter_* into their own heart, and their bows shall be broken.
* `Psa 45:15` With gladness and rejoicing they shall be brought. They shall *_enter_* into the king's palace.
* `Psa 95:11` To whom I swore in my wrath, "They shall not *_enter_* into my rest."
* `Psa 100:4` *_Enter_* into his gates with thanksgiving and into his courts with praise. Be thankful to him and bless his name.
* `Psa 118:19` Open to me the gates of righteousness. I will *_enter_* them, and I will praise the LORD.
* `Psa 118:20` This is the gate of the LORD, into which the righteous shall *_enter_*.
* `Psa 143:2` And do not *_enter_* into judgment with your servant, for in your sight no living man is righteous.
* `Pro 4:14` Do not *_enter_* into the path of the wicked, and do not go in the way of evil men.
* `Pro 18:6` A fool's lips *_enter_* into contention, and his mouth calls for strokes.
* `Pro 23:10` Do not remove the old landmark, and do not *_enter_* into the fields of the fatherless,
* `Isa 2:10` *_Enter_* into the rock and hide in the dust from before the fear of the LORD and the glory of his majesty.
* `Isa 3:14` The LORD will *_enter_* into judgment with the elders of his people and with their princes: "For you have eaten up the vineyard. The plunder of the poor is in your houses."
* `Isa 24:10` The city of confusion is broken down. Every house is shut up so that no man may *_enter_*.
* `Isa 26:2` Open the gates so that the righteous nation which keeps the truth may *_enter_* in.
* `Isa 26:20` Come, my people, *_enter_* into your chambers and shut your doors around you. Hide yourself for a little while until the indignation has passed.
* `Isa 36:6` Behold, you trust in the staff of this broken reed, on Egypt, on which if a man leans, it will *_enter_* his hand and pierce it. Thus Pharaoh king of Egypt is to all who trust in him.
* `Isa 37:24` By your servants you have reproached the Lord and have said, 'By the multitude of my chariots I have come up to the height of the mountains, to the sides of Lebanon, and I will cut down its tall cedars and its choice fir-trees, and I will *_enter_* into the height of its border, the forest of its fruitful field.
* `Isa 57:2` He shall *_enter_* into peace. They shall rest in their beds, each one walking in his uprightness.
* `Isa 59:14` And judgment is turned away backward, and justice stands afar off. For truth has fallen in the street, and equity cannot *_enter_*.
* `Jer 7:2` "Stand in the gate of the LORD'S house and proclaim this word there and say, 'Hear the word of the LORD, all you of Judah, who *_enter_* in at these gates to worship the LORD.'"
* `Jer 8:14` Why do we sit still? Assemble yourselves, and let us *_enter_* into the fortified cities and be silent there. For the LORD our God has put us to silence and given us water of gall to drink because we have sinned against the LORD.
* `Jer 14:18` If I go forth into the field, then behold the slain with the sword! And if I *_enter_* into the city, then behold those who are sick with famine! Even both the prophet and the priest have gone into a land that they do not know.'"
* `Jer 16:5` For thus says the LORD: "Do not *_enter_* into the house of mourning, neither go to lament nor bemoan them, for I have taken away my peace from this people," says the LORD, "even loving-kindness and mercies.
* `Jer 17:20` And say to them, 'Hear the word of the LORD, you kings of Judah, and all Judah, and all the inhabitants of Jerusalem, who *_enter_* by these gates.
* `Jer 17:25` Then there shall *_enter_* into the gates of this city kings and princes sitting upon the throne of David, riding in chariots and on horses—they and their princes, the men of Judah, and the inhabitants of Jerusalem—and this city shall remain forever.
* `Jer 21:13` Behold, I am against you, O inhabitant of the valley and rock of the plain," says the LORD, "who say, 'Who shall come down against us? Or who shall *_enter_* into our habitations?'
* `Jer 22:2` And say, 'Hear the word of the LORD, O king of Judah, who sits upon the throne of David—you, your servants, and your people who *_enter_* by these gates.
* `Jer 22:4` For if you do this thing indeed, then there shall *_enter_* by the gates of this house kings sitting upon the throne of David, riding in chariots and on horses—he, his servants, and his people.
* `Jer 41:17` And they departed and dwelt in the habitation of Chimham, which is by Beth-lehem, to go to *_enter_* into Egypt
* `Jer 42:15` Then therefore, hear the word of the LORD, you remnant of Judah. Thus says the LORD of hosts, the God of Israel: "If you wholly set your faces to *_enter_* into Egypt and go to sojourn there,
* `Jer 42:18` "For thus says the LORD of hosts, the God of Israel: 'As my anger and my fury has been poured forth upon the inhabitants of Jerusalem, so my fury shall be poured forth upon you when you *_enter_* into Egypt. And you shall be an object of horror, an astonishment, a curse, and a reproach, and you shall see this place no more.'
* `Lam 1:10` [YOD] The adversary has spread out his hand upon all her pleasant things, for she has seen that the heathen entered into her sanctuary, whom you commanded that they should not *_enter_* into your congregation.
* `Lam 3:13` [HE] He has caused the arrows of his quiver to *_enter_* into my kidneys.
* `Ezk 7:22` My face I will also turn from them, and they shall pollute my secret place, for the robbers shall *_enter_* into it and defile it.
* `Ezk 13:9` "And my hand shall be upon the prophets who see vanity and who divine lies. They shall not be in the assembly of my people, neither shall they be written in the writing of the house of Israel, neither shall they *_enter_* into the land of Israel. And you shall know that I am the Lord GOD.
* `Ezk 20:38` And I will purge out from among you the rebels and those who transgress against me. I will bring them forth out of the country where they sojourn, and they shall not *_enter_* into the land of Israel. And you shall know that I am the LORD.
* `Ezk 26:10` By reason of the abundance of his horses their dust shall cover you. Your walls shall shake at the noise of the horsemen, of the wheels, and of the chariots when he enters into your gates as men *_enter_* into a city in which a breach is made.
* `Ezk 37:5` Thus says the Lord GOD to these bones: "Behold, I will cause breath to *_enter_* into you, and you shall live.
* `Ezk 42:14` When the priests *_enter_* therein, they shall not go out of the holy place into the outer court, but there they shall lay their garments in which they minister, for they are holy, and shall put on other garments, and shall approach to those things which are for the people."
* `Ezk 44:2` Then the LORD said to me, "This gate shall be shut, it shall not be opened, and no man shall *_enter_* in by it. Because the LORD, the God of Israel, has entered in by it, therefore it shall be shut.
* `Ezk 44:3` It is for the prince. The prince, he shall sit in it to eat bread before the LORD. He shall *_enter_* by the way of the porch of that gate and shall go out by the way of the same."
* `Ezk 44:9` 'Thus says the Lord GOD: "No stranger uncircumcised in heart or uncircumcised in flesh shall *_enter_* into my sanctuary, not even a stranger who is among the children of Israel.
* `Ezk 44:16` "They shall *_enter_* into my sanctuary and they shall come near to my table to minister to me, and they shall keep my charge.
* `Ezk 44:17` And it shall come to pass when they *_enter_* in at the gates of the inner court, that they shall be clothed with linen garments. No wool shall come upon them while they minister in the gates of the inner court and within.
* `Ezk 44:21` No priest shall drink wine when they *_enter_* into the inner court.
* `Ezk 46:2` And the prince shall *_enter_* by the way of the porch of that gate outside and shall stand by the post of the gate. And the priest shall prepare his burnt-offering and his peace-offerings, and he shall worship at the threshold of the gate. Then he shall go forth, but the gate shall not be shut until the evening.
* `Dan 11:7` But out of a branch of her roots one shall stand up in his estate, who shall come with an army, *_enter_* into the fortress of the king of the north, deal against them, and prevail.
* `Dan 11:17` He shall also set his face to *_enter_* with the strength of his whole kingdom, and upright ones with him. He shall do so. And he shall give him the daughter of women, corrupting her, but she shall not stand on his side, neither be for him.
* `Dan 11:24` He shall *_enter_* peaceably even upon the fattest places of the province, and he shall do that which his fathers have not done, nor his fathers' fathers. He shall scatter among them the plunder, loot, and riches, and he shall devise his plans against the strongholds, even for a time.
* `Dan 11:40` "And at the time of the end the king of the south shall war against him. And the king of the north shall come against him like a whirlwind, with chariots, with horsemen, and with many ships, and he shall *_enter_* into the countries and shall overflow and pass over.
* `Dan 11:41` He shall also *_enter_* into the glorious land, and many countries shall be overthrown, but these shall escape out of his hand: Edom, Moab, and the chief of the children of Ammon.
* `Hos 11:9` I will not execute the fierceness of my anger. I will not return to destroy Ephraim, for I am God and not man, the Holy One in the midst of you, and I will not *_enter_* into the city.
* `Joe 2:9` They shall run to and fro in the city. They shall run upon the wall. They shall climb upon the houses. They shall *_enter_* in at the windows like a thief.
* `Amo 5:5` But do not seek Beth-el, nor *_enter_* into Gilgal, and do not pass to Beer-sheba, for Gilgal shall surely go into captivity and Beth-el shall come to nothing.
* `Jna 3:4` And Jonah began to *_enter_* into the city for a day's journey and he cried, and said, "Yet forty days and Nineveh shall be overthrown."
* `Zch 5:4` I will bring it forth," says the LORD of hosts, "and it shall *_enter_* into the house of the thief and into the house of him who swears falsely by my name. And it shall remain in the midst of his house and shall consume it with its timber and its stones."
* `Mth 5:20` "For I say to you, that unless your righteousness exceeds the righteousness of the scribes and Pharisees, you shall in no case *_enter_* into the kingdom of heaven.
* `Mth 6:6` But you, when you pray, *_enter_* into your inner room, and when you have shut your door, pray to your Father who is in secret. And your Father who sees in secret will reward you openly.
* `Mth 7:13` "*_Enter_* in at the narrow gate. For the gate is wide and the way is broad that leads to destruction, and there are many who go in by it.
* `Mth 7:21` "Not everyone who says to me, 'Lord, Lord,' shall *_enter_* into the kingdom of heaven, but he who does the will of my Father who is in heaven.
* `Mth 10:5` These twelve Jesus sent forth and commanded them, saying, "Do not go into the way of the Gentiles, and do not *_enter_* into any city of the Samaritans.
* `Mth 10:11` And into whatever city or town you *_enter_*, inquire who in it is worthy and abide there until you go from there.
* `Mth 12:29` Or else, how can one *_enter_* into a strong man's house and seize his goods unless he first binds the strong man? Then he will plunder his house.
* `Mth 12:45` Then he goes, and takes with himself seven other spirits more wicked than himself, and they *_enter_* in and dwell there. And the last state of that man is worse than the first. Thus it shall also be to this wicked generation."
* `Mth 18:3` And said, "Truly I say to you, unless you are converted and become as little children, you shall not *_enter_* into the kingdom of heaven.
* `Mth 18:8` "Therefore, if your hand or your foot causes you to sin, cut them off and cast them from you. It is better for you to *_enter_* into life lame or maimed than to have two hands or two feet and be cast into everlasting fire.
* `Mth 18:9` And if your eye causes you to sin, pluck it out and cast it from you. It is better for you to *_enter_* into life with one eye than to have two eyes and be cast into hell-fire.
* `Mth 19:17` And he said to him, "Why do you call me good? There is no one good but one: God. But if you wish to *_enter_* into life, keep the commandments."
* `Mth 19:23` Then Jesus said to his disciples, "Truly I say to you, that a rich man shall *_enter_* into the kingdom of heaven with difficulty.
* `Mth 19:24` And again I say to you, it is easier for a camel to go through the eye of a needle than for a rich man to *_enter_* into the kingdom of God."
* `Mth 25:21` His lord said to him, 'Well done you good and faithful servant. You have been faithful over a few things, I will make you ruler over many things. *_Enter_* into the joy of your lord.'
* `Mth 25:23` His lord said to him, 'Well done, good and faithful servant. You have been faithful over a few things, I will make you ruler over many things. *_Enter_* into the joy of your lord.'
* `Mth 26:41` Watch and pray so that you do not *_enter_* into temptation. The spirit indeed is willing, but the flesh is weak."
* `Mrk 1:45` But he went out and began to publish it much and to blaze abroad the matter; therefore, Jesus could no longer openly *_enter_* into the city, but was outside in desolate places. And they came to him from every quarter.
* `Mrk 3:27` No man can *_enter_* into a strong man's house and seize his goods unless he first binds the strong man. And then he will plunder his house.
* `Mrk 5:12` And all the demons implored him, saying, "Send us into the swine so that we may *_enter_* into them."
* `Mrk 6:10` And he said to them, "In whatever place you *_enter_* into a house, abide there until you depart from that place.
* `Mrk 7:19` Because it does not *_enter_* into his heart, but into the belly, and goes out into the latrine, purging all kinds of food?"
* `Mrk 9:25` When Jesus saw that the people came running together, he rebuked the foul spirit, saying to him, "You mute and deaf spirit, I charge you, come out of him and *_enter_* into him no more."
* `Mrk 9:43` And if your hand causes you to fall into sin, cut it off. It is better for you to *_enter_* life maimed than with two hands to go into hell, into the fire that shall never be quenched,
* `Mrk 9:45` And if your foot causes you to fall into sin, cut it off. It is better for you to *_enter_* lame into life than with two feet to be cast into hell, into the fire that never shall be quenched,
* `Mrk 9:47` And if your eye causes you to fall into sin, pluck it out. It is better for you to *_enter_* into the kingdom of God with one eye than with two eyes to be cast into hell-fire,
* `Mrk 10:15` Truly I say to you, whoever does not receive the kingdom of God as a little child, he shall not *_enter_* it."
* `Mrk 10:23` And Jesus looked around and says to his disciples, "How hardly those who have riches shall *_enter_* into the kingdom of God!"
* `Mrk 10:24` And the disciples were astonished at his words. But Jesus answers again, and says to them, "Children, how hard it is for those who trust in riches to *_enter_* into the kingdom of God!
* `Mrk 10:25` It is easier for a camel to go through the eye of a needle than for a rich man to *_enter_* into the kingdom of God."
* `Mrk 13:15` And he who is on the house-top must not go down into the house, neither *_enter_* it, to take anything out of his house.
* `Mrk 14:38` Watch and pray, lest you *_enter_* into temptation. The spirit truly is ready, but the flesh is weak."
* `Luk 7:6` Then Jesus went with them. And when he was not far from the house, the centurion sent friends to him, saying to him, "Lord, do not trouble yourself, for I am not worthy that you should *_enter_* under my roof;
* `Luk 8:16` "No man, when he has lit a candle, covers it with a vessel or puts it under a bed, but sets it on a candlestick so that those who *_enter_* in may see the light.
* `Luk 8:32` Now there was a herd of many swine feeding on the mountain. And they implored him that he would allow them to *_enter_* into them. And he allowed them.
* `Luk 9:4` And into whatever house you *_enter_*, abide there, and from there depart.
* `Luk 10:5` And into whatever house you *_enter_*, first say, 'Peace be to this house.'
* `Luk 10:8` And into whatever city you *_enter_* and they receive you, eat such things as are set before you.
* `Luk 10:10` But into whatever city you *_enter_* and they do not receive you, go out into the streets of the same, and say,
* `Luk 11:26` Then he goes and takes with him seven other spirits more wicked than himself, and they *_enter_* in and dwell there. Then the last state of that man is worse than the first."
* `Luk 13:24` "Strive to *_enter_* in at the narrow gate. For I say to you, many will seek to *_enter_* in and shall not be able.
* `Luk 18:17` Truly I say to you, whoever does not receive the kingdom of God as a little child shall in no way *_enter_* into it."
* `Luk 18:24` And when Jesus saw that he was very sorrowful, he said, "How hardly those who have riches will *_enter_* into the kingdom of God!
* `Luk 18:25` For it is easier for a camel to go through a needle's eye than for a rich man to *_enter_* into the kingdom of God."
* `Luk 21:21` Then let those who are in Judea flee to the mountains, and let those who are in the midst of it depart from it, and do not let those who are in the countries *_enter_* into it.
* `Luk 22:40` And when he was at the place, he said to them, "Pray so that you do not *_enter_* into temptation."
* `Luk 22:46` And said to them, "Why do you sleep? Rise and pray, lest you *_enter_* into temptation."
* `Luk 24:26` Did Christ not have to suffer these things and to *_enter_* into his glory?"
* `Jhn 3:4` Nicodemus says to him, "How can a man be born when he is old? Can he *_enter_* the second time into his mother's womb and be born?"
* `Jhn 3:5` Jesus answered, "Truly, truly, I say to you, unless a man is born of water and of the Spirit, he cannot *_enter_* into the kingdom of God.
* `Jhn 10:1` "Truly, truly, I say to you, he who does not *_enter_* by the door into the sheep-fold, but climbs up some other way, the same is a thief and a robber.
* `Act 14:22` Confirming the souls of the disciples, exhorting them to continue in the faith, and saying, "We must through much tribulation *_enter_* into the kingdom of God."
* `Act 20:29` For I know this, that after my departure, grievous wolves will *_enter_* in among you, not sparing the flock.
* `Heb 3:11` So I swore in my wrath, 'They shall not *_enter_* into my rest.'"
* `Heb 3:18` And to whom did he swear that they should not *_enter_* into his rest, but to those who did not believe?
* `Heb 3:19` So we see that they could not *_enter_* in because of unbelief.
* `Heb 4:3` For we who have believed *_enter_* into rest, as he said, "As I have sworn in my wrath that they shall not *_enter_* into my rest," although the works were finished from the foundation of the world.
* `Heb 4:5` And in this place again, "They shall not *_enter_* into my rest."
* `Heb 4:6` Seeing therefore it remains that some must *_enter_* into it, and those to whom it was first preached did not *_enter_* because of unbelief,
* `Heb 4:11` Let us labor therefore to *_enter_* into that rest, lest any man fall after the same example of unbelief.
* `Heb 10:19` Therefore, brothers, having boldness to *_enter_* into the holiest by the blood of Jesus,
* `Rev 15:8` And the temple was filled with smoke from the glory of God and from his power, and no man was able to *_enter_* into the temple until the seven plagues of the seven angels were fulfilled.
* `Rev 21:27` And there shall in no way *_enter_* into it anything that defiles, neither whatever works abomination or makes a lie, but those who are written in the Lamb's book of life.
* `Rev 22:14` "Blessed are those who do his commandments so that they may have right to the tree of life and may *_enter_* in through the gates into the city.

_152 verses containing ENTER_

== ENTERED

* `Gen 7:13` In the same day Noah, along with Shem, Ham, and Japheth (the sons of Noah), Noah's wife, and the three wives of his sons with them, *_entered_* into the ark—
* `Gen 7:16` And those that *_entered_* went in male and female of all flesh, as God had commanded him. And the LORD shut him in.
* `Gen 19:3` And he urged them greatly, and they turned aside to him and *_entered_* into his house. And he made them a feast and baked unleavened bread, and they ate.
* `Gen 19:23` The sun had risen upon the earth when Lot *_entered_* into Zoar.
* `Gen 23:10` And Ephron dwelt among the children of Heth. And Ephron the Hittite answered Abraham in the audience of the children of Heth, of all who *_entered_* the gates of his city, saying,
* `Gen 23:18` To Abraham for a possession in the presence of the children of Heth, before all who *_entered_* the gate of his city.
* `Gen 31:33` And Laban went into Jacob's tent, into Leah's tent, and into the two women-servants' tents, but he did not find them. Then he went out of Leah's tent and *_entered_* into Rachel's tent.
* `Gen 43:30` And Joseph made haste, for his heart yearned toward his brother, and he sought a place to weep. And he *_entered_* into his chamber and wept there.
* `Exo 33:9` And it came to pass, as Moses *_entered_* into the tabernacle, the cloudy pillar descended and stood at the door of the tabernacle, and the LORD talked with Moses.
* `Num 7:89` And when Moses had *_entered_* into the Tabernacle of the Congregation to speak with him, he heard the voice speaking to him from above the mercy-seat that was upon the ark of testimony, from between the two cherubim. And he spoke to him.
* `Jsh 2:3` And the king of Jericho sent to Rahab, saying, "Bring forth the men who have come to you, who have *_entered_* into your house, for they have come to search out all the country."
* `Jsh 8:19` And the ambush arose quickly out of their place, and they ran as soon as he had stretched out his hand. And they *_entered_* into the city, took it, and hastened to set the city on fire.
* `Jsh 10:20` And it came to pass when Joshua and the children of Israel had made an end of slaying them with a very great slaughter until they were consumed, that the rest who remained of them *_entered_* into fortified cities.
* `Jdg 3:22` And the hilt also *_entered_* after the blade, and the fat closed upon the blade so that he could not draw the dagger out of his belly. And the dirt came out.
* `Jdg 6:5` For they came up with their livestock and their tents, and they came as swarming-locusts for multitude, for both they and their camels were without number. And they *_entered_* into the land to destroy it.
* `Jdg 9:46` And when all the men of the tower of Shechem heard that, they *_entered_* into a hold of the house of the god Berith.
* `2Sa 10:14` And when the children of Ammon saw that the Syrians had fled, they also fled before Abishai and *_entered_* into the city. So Joab returned from the children of Ammon and came to Jerusalem.
* `2Sa 17:13` Moreover, if he has *_entered_* into a city, then all Israel shall bring ropes to that city, and we will draw it into the river until there is not one small stone found there."
* `2Sa 22:7` "In my distress I called upon the LORD and cried to my God. And he heard my voice out of his temple, and my cry *_entered_* into his ears.
* `2Ki 7:8` And when these lepers came to the uttermost part of the camp, they went into one tent, ate and drank, and carried from there silver, gold, and clothing, and went and hid it. And they came back, *_entered_* into another tent, and carried from there also, and went and hid it.
* `2Ki 9:31` And as Jehu *_entered_* the gate, she said, "Did Zimri have peace, who slew his master?"
* `1Ch 19:15` And when the children of Ammon saw that the Syrians had fled, they likewise fled before Abishai his brother and *_entered_* into the city. Then Joab came to Jerusalem.
* `2Ch 12:11` And when the king *_entered_* into the house of the LORD, the guard came and conveyed them and brought them back into the guard-chamber.
* `2Ch 15:12` And they *_entered_* into a covenant to seek the LORD God of their fathers with all their heart and with all their soul,
* `2Ch 32:1` After these things and their establishment, Sennacherib king of Assyria came, *_entered_* into Judah, encamped against the fortified cities, and thought to win them for himself.
* `Neh 2:15` Then I went up in the night by the brook, viewed the wall, turned back, and *_entered_* by the gate of the valley, and so returned.
* `Neh 10:29` They united with their brothers, their nobles, and *_entered_* into a curse and into an oath to walk in God's law, which was given by Moses the servant of God, and to observe and do all the commandments of the LORD our Lord, his judgments, and his statutes,
* `Job 38:16` Have you *_entered_* into the springs of the sea? Or have you walked in the search of the depth?
* `Job 38:22` Have you *_entered_* into the treasures of the snow? Or have you seen the treasures of the hail,
* `Jer 2:7` And I brought you into a plentiful country to eat its fruit and its goodness, but when you *_entered_*, you defiled my land and made my heritage an abomination.
* `Jer 9:21` For death has come up into our windows and has *_entered_* into our palaces to cut off the children from outside and the young men from the streets.
* `Jer 34:10` Now when all the princes and all the people who had *_entered_* into the covenant heard that everyone should liberate his man-servant and everyone his woman-servant so that no one should retain them in service anymore, they obeyed and let them go.
* `Jer 37:16` So Jeremiah had *_entered_* into the dungeon and into the cabins, and Jeremiah had remained there many days.
* `Lam 1:10` [YOD] The adversary has spread out his hand upon all her pleasant things, for she has seen that the heathen *_entered_* into her sanctuary, whom you commanded that they should not enter into your congregation.
* `Lam 4:12` [LAMED] The kings of the earth and all the inhabitants of the world would not have believed that the adversary and the enemy would have *_entered_* into the gates of Jerusalem.
* `Ezk 2:2` And the Spirit *_entered_* into me when he spoke to me and set me upon my feet, and I heard him who spoke to me.
* `Ezk 3:24` Then the Spirit *_entered_* into me, set me upon my feet, and spoke with me, and said to me, "Go, shut yourself within your house.
* `Ezk 10:2` And he spoke to the man clothed with linen, and said, "Go in between the wheels, even under the cherub, and fill your hand with coals of fire from between the cherubim and scatter them over the city." And he *_entered_* in my sight.
* `Ezk 16:8` "Now when I passed by you and looked upon you, behold, your time was the time of love. And I spread my skirt over you and covered your nakedness. I even swore to you and *_entered_* into a covenant with you," says the Lord GOD, "and you became mine.
* `Ezk 36:20` And when they *_entered_* among the heathen where they went, they profaned my holy name when they said to them, 'These are the people of the LORD and have gone forth out of his land.'
* `Ezk 44:2` Then the LORD said to me, "This gate shall be shut, it shall not be opened, and no man shall enter in by it. Because the LORD, the God of Israel, has *_entered_* in by it, therefore it shall be shut.
* `Dan 10:3` I ate no pleasant bread, neither flesh nor wine *_entered_* my mouth, neither did I anoint myself at all, until three whole weeks were fulfilled.
* `Oba 1:11` In the day that you stood on the other side, in the day that the strangers carried away his forces captive and foreigners *_entered_* into his gates and cast lots upon Jerusalem, even you were as one of them.
* `Oba 1:13` You should not have *_entered_* into the gate of my people in the day of their calamity. Indeed, you should not have looked upon their affliction in the day of their calamity, nor have laid hands on their substance in the day of their calamity,
* `Hab 3:16` When I heard, my belly trembled. My lips quivered at the voice. Rottenness *_entered_* into my bones, and I trembled in myself, so that I might rest in the day of trouble. When he comes up to the people, he will invade them with his troops.
* `Mth 8:5` And when Jesus had *_entered_* into Capernaum, a centurion came to him, imploring him,
* `Mth 8:23` And when he had *_entered_* into a boat, his disciples followed him.
* `Mth 9:1` And he *_entered_* into a boat, passed over, and came into his own city.
* `Mth 12:4` How he *_entered_* into the house of God and ate the show-bread, which it was not lawful for him to eat, neither for those who were with him, but only for the priests?
* `Mth 24:38` For as in the days that were before the flood—they were eating and drinking, marrying and giving in marriage, until the day that Noah *_entered_* into the ark,
* `Mrk 1:21` And they went into Capernaum, and immediately on the sabbath he *_entered_* into the synagogue and taught.
* `Mrk 1:29` And immediately, when they had come out of the synagogue, they *_entered_* into the house of Simon and Andrew, with James and John.
* `Mrk 2:1` And again he *_entered_* into Capernaum after some days, and it was understood that he was in the house.
* `Mrk 3:1` And he *_entered_* again into the synagogue, and there was a man there who had a withered hand.
* `Mrk 4:1` And he began again to teach by the sea-side. And there was gathered to him a great multitude so that he *_entered_* into a boat and sat on the sea, while the whole multitude was by the sea on the land.
* `Mrk 5:13` And immediately Jesus gave them leave. And the unclean spirits went out and *_entered_* into the swine, and the herd ran violently down a steep place into the sea (they were about two thousand) and were choked in the sea.
* `Mrk 6:56` And wherever he *_entered_*, into villages, cities, or country, they laid the sick in the streets and implored him that they might touch at least the fringe of his garment. And as many as touched him were healed.
* `Mrk 7:17` And when he had *_entered_* into the house from the people, his disciples asked him concerning the parable.
* `Mrk 7:24` And from there he arose and went into the borders of Tyre and Sidon. He *_entered_* into a house and wished to have no man know it, but he could not be hid.
* `Mrk 8:10` And immediately he *_entered_* into a boat with his disciples and came into the parts of Dalmanutha.
* `Mrk 8:13` And having left them, and having *_entered_* into the boat again, he departed to the other side.
* `Mrk 11:2` And says to them, "Go into the village over against you. And as soon as you have *_entered_* into it, you shall find a colt tied, on which never a man sat. Untie him and bring him.
* `Mrk 11:11` And Jesus *_entered_* into Jerusalem and into the temple. And when he had looked around at all things, it being now evening, he went out to Bethany with the twelve.
* `Luk 1:40` And *_entered_* into the house of Zechariah and saluted Elizabeth.
* `Luk 4:38` And he arose out of the synagogue and *_entered_* into Simon's house. And the mother of Simon's wife was taken with a violent fever, and they implored him for her.
* `Luk 5:3` And he *_entered_* into one of the boats, which was Simon's, and prayed him that he would thrust out a little from the land. And he sat down and taught the people out of the boat.
* `Luk 6:6` And it also came to pass on another sabbath, that he *_entered_* into the synagogue and taught. And there was a man whose right hand was withered.
* `Luk 7:1` Now when he had ended all his sayings in the audience of the people, he *_entered_* into Capernaum.
* `Luk 7:44` And he turned to the woman, and said to Simon, "Do you see this woman? I *_entered_* into your house and you gave me no water for my feet, but she has washed my feet with tears and wiped them with the hair of her head.
* `Luk 8:30` And Jesus asked him, saying, "What is your name?" And he said, "Legion," because many demons had *_entered_* into him.
* `Luk 8:33` Then the demons went out of the man and *_entered_* into the swine. And the herd ran violently down a steep place into the lake and were choked.
* `Luk 9:34` While he was thus speaking, there came a cloud and overshadowed them, and they feared as they *_entered_* into the cloud.
* `Luk 9:52` And sent messengers before his face. And they went and *_entered_* into a village of the Samaritans to make ready for him.
* `Luk 10:38` Now it came to pass, as they were going, he *_entered_* into a certain village. And a certain woman, named Martha, received him into her house.
* `Luk 11:52` Woe to you, lawyers! For you have taken away the key of knowledge. You have not *_entered_* in yourselves, and you hindered those who were entering in."
* `Luk 17:12` And as he *_entered_* into a certain village, ten men who were lepers met him there, who stood at a distance.
* `Luk 17:27` They ate, they drank, they married wives, and they were given in marriage until the day that Noah *_entered_* into the ark, and the flood came and destroyed them all.
* `Luk 19:1` And Jesus *_entered_* and passed through Jericho.
* `Luk 22:3` Then Satan *_entered_* into Judas, surnamed Iscariot, being of the number of the twelve.
* `Luk 22:10` And he said to them, "Behold, when you have *_entered_* into the city, a man bearing a pitcher of water shall meet you there. Follow him into the house where he enters.
* `Luk 24:3` And they *_entered_* in and did not find the body of the Lord Jesus.
* `Jhn 4:38` I sent you to reap that on which you bestowed no labor. Other men labored, and you have *_entered_* into their labors."
* `Jhn 6:17` *_Entered_* into a boat, and went over the sea toward Capernaum. It was now dark and Jesus had not come to them.
* `Jhn 6:22` The day following, when the people who stood on the other side of the sea saw that there was no other boat there, except that one into which his disciples had *_entered_*, and that Jesus did not go with his disciples into the boat, but that his disciples had gone away alone
* `Jhn 13:27` And after the piece of bread, Satan *_entered_* into him. Then Jesus said to him, "What you do, do quickly."
* `Jhn 18:1` When Jesus had spoken these words, he went forth with his disciples over the brook Kedron, where there was a garden, into which he and his disciples *_entered_*.
* `Jhn 18:15` And Simon Peter followed Jesus, and so did another disciple. Since that disciple was known to the high priest, he *_entered_* with Jesus into the palace of the high priest.
* `Jhn 18:33` Then Pilate *_entered_* into the judgment-hall again and called Jesus and said to him, "Are you the King of the Jews?"
* `Jhn 21:3` Simon Peter says to them, "I am going fishing." They say to him, "We also will go with you." They went forth and *_entered_* into a boat immediately. And that night they caught nothing.
* `Act 3:2` And a certain man lame from his mother's womb was carried, whom they laid daily at the gate of the temple which is called Beautiful to ask for alms from those who *_entered_* into the temple.
* `Act 3:8` And leaping up, he stood, walked, and *_entered_* with them into the temple, walking, leaping, and praising God.
* `Act 5:21` And when they heard this, they *_entered_* into the temple at dawn and taught. But the high priest and those who were with him came and called the council together—all the senate of the children of Israel—and sent to the prison to have them brought.
* `Act 7:45` Which also our fathers, in their turn, brought in with Joshua when they *_entered_* into the possession of the nations, whom God drove out before the face of our fathers until the days of David,
* `Act 9:17` And Ananias went and *_entered_* into the house, and putting his hands on him, said, "Brother Saul, the Lord—even Jesus who appeared to you in the way as you came—has sent me so that you may receive your sight and be filled with the Holy Spirit."
* `Act 10:24` And on the next day, they *_entered_* into Caesarea. And Cornelius waited for them and had called together his kinsmen and near friends.
* `Act 11:8` But I said, 'Not so, Lord, for nothing common or unclean has at any time *_entered_* into my mouth.'
* `Act 11:12` And the Spirit told me to go with them, doubting nothing. Moreover, these six brothers accompanied me, and we *_entered_* into the man's house.
* `Act 16:40` And they went out of the prison and *_entered_* into the house of Lydia. And when they had seen the brothers, they comforted them and departed.
* `Act 18:7` And he departed from there and *_entered_* into the house of a certain man named Justus, one who worshiped God, whose house joined close to the synagogue.
* `Act 18:19` And he came to Ephesus and left them there. But he himself *_entered_* into the synagogue and reasoned with the Jews.
* `Act 21:8` And the next day, we who were of Paul's company departed and came to Caesarea. And we *_entered_* into the house of Philip the evangelist, who was one of the seven, and stayed with him.
* `Act 21:26` Then Paul took the men, and the next day he purified himself with them and *_entered_* into the temple, declaring the accomplishment of the days of purification until an offering should be offered for each of them.
* `Act 23:16` And when the son of Paul's sister heard of their lying in wait, he went and *_entered_* into the castle and told Paul.
* `Act 25:23` So on the next day, Agrippa and Bernice had come with great pomp and had *_entered_* into the place of hearing with the chief captains and principal men of the city. And at the command of Festus, Paul was brought forth.
* `Act 28:8` And it came to pass that the father of Publius lay sick with a fever and dysentery, to whom Paul *_entered_* in, prayed, laid his hands on him, and healed him.
* `Rom 5:12` Therefore, as sin *_entered_* into the world by one man, and death by sin, so also death passed upon all men, for all have sinned.
* `Rom 5:20` Moreover, the law *_entered_* so that the offense might abound. But where sin abounded, grace abounded much more,
* `1Co 2:9` But as it is written, "'Eye has not seen, nor ear heard,' neither have *_entered_* into the heart of man, 'the things which God has prepared for those who love him.'"
* `Heb 4:10` For he who has *_entered_* into his rest, he also has ceased from his own works, as God did from his.
* `Heb 6:20` Where the forerunner has for us *_entered_*, even Jesus, made a high "priest forever after the order of Melchizedek."
* `Heb 9:12` Neither by the blood of goats and calves, but by his own blood, he *_entered_* in once into the holy place, having obtained eternal redemption for us.
* `Heb 9:24` For Christ has not *_entered_* into the holy places made with hands, which are the figures of the true, but into heaven itself, now to appear in the presence of God for us,
* `Jms 5:4` Behold, the hire of the laborers who have reaped your fields, which is by you kept back by fraud, cries. And the cries of those who have reaped have *_entered_* into the ears of the Lord of Sabaoth.
* `2Jn 1:7` For many deceivers have *_entered_* into the world who do not confess that Jesus Christ has come in the flesh. This is a deceiver and an antichrist.
* `Rev 11:11` And after three and a half days, the Spirit of life from God *_entered_* into them and they stood upon their feet, and great fear fell upon those who saw them.

_115 verses containing ENTERED_

== ENTERING

* `Deu 11:10` For the land that you are *_entering_* to possess is not like the land of Egypt, from where you came out, where you sowed your seed and watered it with your foot like a garden of herbs.
* `Deu 11:11` But the land that you are *_entering_* to possess is a land of hills and valleys, and drinks water from the rain of heaven,
* `Jsh 8:29` And the king of Ai he hanged on a tree until evening. And as soon as the sun was down, Joshua commanded that they should take his carcass down from the tree, cast it at the *_entering_* of the gate of the city, and raise upon it a great heap of stones, which remains to this day.
* `Jsh 13:5` And the land of the Giblites and all Lebanon toward the sunrise, from Baal-gad under mount Hermon to the *_entering_* into Hamath.
* `Jsh 20:4` And when he who flees to one of those cities stands at the *_entering_* of the gate of the city and declares his cause in the ears of the elders of that city, they shall take him into the city to them and give him a place so that he may dwell among them.
* `1Sa 23:7` And it was told to Saul that David had come to Keilah. And Saul said, "God has delivered him into my hand, for he is shut in by *_entering_* into a town that has gates and bars."
* `2Ki 14:25` He restored the border of Israel from the *_entering_* of Hamath to the sea of the plain, according to the word of the LORD God of Israel which he spoke by the hand of his servant Jonah, the son of Amittai, the prophet, who was of Gath-hepher.
* `2Ch 23:4` This is the thing that you shall do: a third part of you *_entering_* on the sabbath, of the priests and of the Levites, shall be gatekeepers of the doors,
* `Isa 23:1` [The burden of Tyre.] Howl, you ships of Tarshish, for it is laid waste, so that there is no house, no *_entering_* in. From the land of Chittim it is revealed to them.
* `Jer 17:27` But if you will not listen to me to hallow the sabbath day and to bear no burdens while *_entering_* at the gates of Jerusalem on the sabbath day, then I will kindle a fire in its gates, and it shall devour the palaces of Jerusalem and shall not be quenched."'"
* `Mth 23:13` "But woe to you, scribes and Pharisees! Hypocrites! For you shut up the kingdom of heaven against men. For you neither go in yourselves, neither do you allow those who are *_entering_* to go in.
* `Mrk 4:19` And the cares of this world, the deceitfulness of riches, and the lusts of other things *_entering_* in, choke the word, and it becomes unfruitful.
* `Mrk 7:15` There is nothing from outside a man, that *_entering_* into him can defile him; however, it is the things which come out of him that defile the man.
* `Mrk 16:5` And *_entering_* into the sepulcher, they saw a young man sitting on the right side, clothed in a long white garment, and they were frightened.
* `Luk 11:52` Woe to you, lawyers! For you have taken away the key of knowledge. You have not entered in yourselves, and you hindered those who were *_entering_* in."
* `Luk 19:30` Saying, "Go into the village over against you, in which at your *_entering_* you will find a colt tied on which no man has ever sat. Untie him and bring him here.
* `Act 8:3` As for Saul, he made havoc of the church, *_entering_* into every house and hauling off men and women and committing them to prison.
* `Act 27:2` And *_entering_* into a ship of Adramyttium, we launched, meaning to sail by the coasts of Asia. Aristarchus, a Macedonian of Thessalonica, was with us.
* `1Th 1:9` For they themselves report concerning us what manner of *_entering_* in we had to you and how you turned to God from idols to serve the living and true God,
* `1Th 2:1` For you yourselves, brothers, know our *_entering_* in to you, that it was not in vain.
* `Heb 4:1` Let us therefore fear while a promise of *_entering_* into his rest remains, lest any of you should seem to come short of it.

_21 verses containing ENTERING_

== ENTERPRISE

* `Job 5:12` He disappoints the devices of the crafty so that their hands cannot perform their *_enterprise_*.

_1 verse containing ENTERPRISE_

== ENTERS

* `Exo 28:29` And Aaron shall bear the names of the children of Israel in the breast-plate of judgment upon his heart when he *_enters_* into the holy place for a memorial before the LORD continually.
* `Lev 14:36` The priest shall command that they empty the house before the priest *_enters_* to see the plague so that all that is in the house may not be made unclean. And afterward, the priest shall go in to see the house.
* `Num 4:30` From thirty years old and upward even to fifty years old you shall number them—everyone who *_enters_* into the service to do the work of the Tabernacle of the Congregation.
* `Num 4:35` From thirty years old and upward even to fifty years old, everyone who *_enters_* into the service for the work in the Tabernacle of the Congregation.
* `Num 4:39` From thirty years old and upward even to fifty years old, everyone who *_enters_* into the service for the work in the Tabernacle of the Congregation,
* `Num 4:43` From thirty years old and upward even to fifty years old, everyone who *_enters_* into the service for the work in the Tabernacle of the Congregation,
* `2Ch 31:16` Besides their genealogy of males, from three years old and upward, even to everyone who *_enters_* into the house of the LORD, his daily portion for their service in their charges according to their courses.
* `Pro 2:10` When wisdom *_enters_* into your heart and knowledge is pleasant to your soul,
* `Pro 17:10` A reproof *_enters_* more into a wise man than one hundred stripes into a fool.
* `Ezk 21:14` "You therefore, son of man, prophesy, and smite your hands together, and let the sword be doubled the third time—the sword of the slain. It is the sword of the great men who are slain which *_enters_* into their private chambers.
* `Ezk 26:10` By reason of the abundance of his horses their dust shall cover you. Your walls shall shake at the noise of the horsemen, of the wheels, and of the chariots when he *_enters_* into your gates as men enter into a city in which a breach is made.
* `Ezk 42:12` And according to the doors of the chambers that were toward the south was a door in the head of the way, even the way directly before the wall toward the east, as one *_enters_* into them.
* `Ezk 46:8` And when the prince *_enters_*, he shall go in by the way of the porch of that gate and he shall go forth by the way of it.
* `Ezk 46:9` But when the people of the land come before the LORD in the solemn feasts, he who *_enters_* in by the way of the north gate to worship shall go out by the way of the south gate, and he who *_enters_* by the way of the south gate shall go forth by the way of the north gate. He shall not return by the way of the gate by which he came in, but shall go forth over against it.
* `Mth 15:17` Do you not yet understand, that whatever *_enters_* in at the mouth goes into the belly and is cast out into the latrine?
* `Mrk 5:40` And they derided him. But when he had put them all out, he takes the father and the mother of the girl and those who were with him and *_enters_* in where the girl was lying.
* `Mrk 7:18` And he says to them, "Are you so void of understanding also? Do you not perceive, that whatever thing from outside *_enters_* into the man, it cannot defile him,
* `Luk 22:10` And he said to them, "Behold, when you have entered into the city, a man bearing a pitcher of water shall meet you there. Follow him into the house where he *_enters_*.
* `Jhn 10:2` But he who *_enters_* by the door is the shepherd of the sheep.
* `Jhn 10:9` I am the door. If any man *_enters_* through me, he shall be saved and shall go in and out and find pasture.
* `Heb 6:19` This hope we have as an anchor of the soul, both sure and steadfast, and which *_enters_* into that within the veil,
* `Heb 9:25` Nor yet that he should offer himself often, as the high priest *_enters_* into the holy place every year with blood of others.

_22 verses containing ENTERS_

== ENTERTAIN

* `Jdg 16:25` And it came to pass when their hearts were merry, that they said, "Call for Samson so that he may *_entertain_* us." And they called for Samson out of the prison-house, and he entertained them. And they set him between the pillars.

_1 verse containing ENTERTAIN_

== ENTERTAINED

* `Jdg 16:25` And it came to pass when their hearts were merry, that they said, "Call for Samson so that he may entertain us." And they called for Samson out of the prison-house, and he *_entertained_* them. And they set him between the pillars.
* `Jdg 16:27` Now the house was full of men and women. And all the lords of the Philistines were there. And there were upon the roof about three thousand men and women that beheld while Samson *_entertained_*.
* `Heb 13:2` Do not be forgetful to show hospitality to strangers, for by this some have *_entertained_* angels unintentionally.

_3 verses containing ENTERTAINED_

== ENTICE

* `Jdg 14:15` And it came to pass on the seventh day, that they said to Samson's wife, "*_Entice_* your husband so that he may declare to us the riddle, lest we burn you and your father's house with fire. Have you called us to take what we possess? Is it not so?"
* `Jdg 16:5` And the lords of the Philistines came to her and said to her, "*_Entice_* him, and see in what his great strength lies and by what means we may prevail against him so that we may bind him to afflict him. And we will each give you eleven hundred pieces of silver."
* `2Ch 18:19` And the LORD said, 'Who shall *_entice_* Ahab king of Israel that he may go up and fall at Ramoth-gilead?' And one spoke saying after this manner and another saying after that manner.
* `2Ch 18:20` Then a spirit came out and stood before the LORD and said, 'I will *_entice_* him.' And the LORD said to him, 'With what?'
* `2Ch 18:21` And he said, 'I will go out and be a lying spirit in the mouth of all his prophets.' And the LORD said, 'You shall *_entice_* him and you shall also prevail. Go out and do even so.'
* `Pro 1:10` My son, if sinners *_entice_* you, do not consent.

_6 verses containing ENTICE_

== ENTICED

* `Job 31:27` And my heart has been secretly *_enticed_* or my mouth has kissed my hand,
* `Job 36:16` Even so he would have *_enticed_* you out of distress into a broad place where there is no constraint, and that which should be set on your table would be full of fatness.
* `Jer 20:10` For I heard the defaming of many, "Fear is on every side. Report," they say, "and we will report it." All my familiar friends watched for my fall, saying, "Perhaps he will be *_enticed_*, and we shall prevail against him and take our revenge on him."
* `Jer 38:22` 'And behold, all the women who are left in the king of Judah's house shall be brought forth to the king of Babylon's princes, and those women shall say, "Your friends have *_enticed_* you and have prevailed against you. Your feet are sunk in the mire, and they have turned away from you."
* `Jms 1:14` But every man is tempted when he is drawn away by his own lust and *_enticed_*.

_5 verses containing ENTICED_

== ENTICES

* `Exo 22:16` "And if a man *_entices_* a virgin who is not betrothed and lies with her, he shall surely endow her to be his wife.
* `Deu 13:6` "If your brother, the son of your mother, your son, your daughter, the wife of your bosom, or your friend who is as your own soul, *_entices_* you secretly, saying, 'Let us go and serve other gods,' which you have not known—you, nor your fathers—
* `Pro 16:29` A violent man *_entices_* his neighbor and leads him into the way that is not good.
* `Jer 43:3` But Baruch the son of Neriah *_entices_* you against us to deliver us into the hand of the Chaldeans so that they may put us to death and carry us away as captives into Babylon."

_4 verses containing ENTICES_

== ENTICING

* `1Co 2:4` And my speech and my preaching was not with *_enticing_* words of man's wisdom, but in demonstration of the Spirit and of power,
* `Col 2:4` And this I say, lest any man should deceive you with *_enticing_* words.

_2 verses containing ENTICING_

== ENTIRE

* `Act 21:40` And when he had given him license, Paul stood on the stairs and beckoned with the hand to the people. And when *_entire_* silence was made, he addressed them, speaking in the Hebrew language.
* `Jms 1:4` But let patience have her perfect work so that you may be perfect and *_entire_*, lacking nothing.

_2 verses containing ENTIRE_

== ENTIRELY

* `1Ki 7:23` And he made a molten sea, ten cubits from one brim to the other. It was *_entirely_* round and its height was five cubits, and a line of thirty cubits encompassed it.
* `Isa 24:19` The earth is utterly broken down, the earth is *_entirely_* dissolved, the earth is exceedingly moved.

_2 verses containing ENTIRELY_

== ENTRAILS

* `Exo 12:9` Do not eat any of it raw or boiled at all with water, but roasted with fire, its head with its legs and with its *_entrails_*.

_1 verse containing ENTRAILS_

== ENTRANCE

* `Exo 35:15` The incense-altar and its staffs; the anointing oil and the sweet incense; the hanging for the door at the *_entrance_* of the tabernacle;
* `Num 34:8` From mount Hor you shall designate your border to the *_entrance_* of Hamath, and the limits of the border shall be at Zedad.
* `Jdg 1:24` And the spies saw a man coming out of the city and they said to him, "Show us, we pray you, the *_entrance_* into the city, and we will show you mercy."
* `Jdg 1:25` And when he showed them the *_entrance_* into the city, they smote the city with the edge of the sword, but they let the man and all his family go.
* `Jdg 3:3` The five lords of the Philistines, all the Canaanites, the Sidonians, and the Hivites who dwelt on mount Lebanon, from mount Baal-hermon to the *_entrance_* of Hamath.
* `Jdg 9:35` And Gaal the son of Ebed went out and stood in the *_entrance_* of the gate of the city. And Abimelech and the people who were with him rose from lying in wait.
* `Jdg 9:40` And Abimelech chased him, and he fled before him, and many were overthrown and wounded, even to the *_entrance_* of the gate.
* `Jdg 9:44` And Abimelech and the company that was with him rushed forward and stood in the *_entrance_* of the gate of the city. And the two other companies ran upon all the people who were in the fields and slew them.
* `Jdg 18:16` And the six hundred men appointed with their weapons of war, who were of the children of Dan, stood by the *_entrance_* of the gate.
* `Jdg 18:17` And the five men who went to explore the land went up, came in there, and took the engraved image, the ephod, the teraphim, and the molten image. And the priest stood in the *_entrance_* of the gate with the six hundred men who were appointed with weapons of war.
* `1Sa 17:52` And the men of Israel and of Judah arose, shouted, and pursued the Philistines to the *_entrance_* of the valley and to the gates of Ekron. And the wounded of the Philistines fell down along the way to Shaaraim, even to Gath and to Ekron.
* `2Sa 10:8` And the children of Ammon came out and put the battle in array at the *_entrance_* of the gate. And the Syrians of Zoba and of Rehob and the men of Tob and Maacah were by themselves in the field.
* `2Sa 11:23` And the messenger said to David, "Surely the men prevailed against us and came out to us into the field, and we were upon them even to the *_entrance_* of the gate.
* `1Ki 6:31` And for the *_entrance_* of the oracle he made doors of olive tree. The lintel and side-posts were a fifth part of the wall.
* `1Ki 8:65` And at that time Solomon held a feast, and all Israel with him, a great congregation, from the *_entrance_* into Hamath to the river of Egypt, before the LORD our God, seven days and seven days, even fourteen days.
* `1Ki 18:46` And the hand of the LORD was on Elijah. And he girded his loins and ran before Ahab to the *_entrance_* of Jezreel.
* `1Ki 19:13` And it came to pass when Elijah heard it, that he wrapped his face in his mantle, went out, and stood in the *_entrance_* of the cave. And behold, there came a voice to him and said, "What are you doing here, Elijah?"
* `1Ki 22:10` And the king of Israel and Jehoshaphat the king of Judah sat each on his throne, having put on their robes, in a void place in the *_entrance_* of the gate of Samaria. And all the prophets prophesied before them.
* `2Ki 7:3` And there were four leprous men at the *_entrance_* of the gate. And they said to one another, "Why do we sit here until we die?
* `2Ki 10:8` And a messenger came and told him, saying, "They have brought the heads of the king's sons." And he said, "Lay them in two heaps at the *_entrance_* of the gate until the morning."
* `2Ki 23:8` And he brought all the priests out of the cities of Judah and defiled the high places where the priests had burned incense, from Geba to Beer-sheba, and broke down the high places of the gates that were in the *_entrance_* of the gate of Joshua the governor of the city, which were on a man's left hand at the gate of the city.
* `2Ki 23:11` And he took away the horses that the kings of Judah had given to the sun at the *_entrance_* of the house of the LORD, by the chamber of Nathan-melech the chamberlain which was in the suburbs, and burned the chariots of the sun with fire.
* `1Ch 4:39` And they went to the *_entrance_* of Gedor, even to the east side of the valley, to seek pasture for their flocks.
* `1Ch 5:9` And eastward he inhabited to the *_entrance_* of the wilderness from the Euphrates River because their livestock had multiplied in the land of Gilead.
* `1Ch 13:5` So David assembled all Israel from Shihor of Egypt even to the *_entrance_* of Hemath to bring the ark of God from Kirjath-jearim.
* `2Ch 7:8` Also at the same time Solomon kept the feast seven days, and all Israel with him, a very great congregation, from the *_entrance_* of Hamath to the river of Egypt.
* `2Ch 12:10` And king Rehoboam made shields of brass in their place and committed them to the hands of the chief of the guard who kept the *_entrance_* of the king's house.
* `2Ch 18:9` And the king of Israel and Jehoshaphat king of Judah each sat on his throne clothed in their robes, and they sat in a void place at the *_entrance_* of the gate of Samaria. And all the prophets prophesied before them.
* `2Ch 23:13` And she looked, and behold, the king stood at his pillar at the *_entrance_*, and the princes and the trumpets by the king. And all the people of the land rejoiced and sounded with trumpets, and the singers with instruments of music were leading the singing of praise. Then Athaliah rent her clothes and said, "Treason, treason."
* `2Ch 23:15` So they laid hands on her, and when she had come to the *_entrance_* of the horse gate by the king's house, they slew her there.
* `2Ch 26:8` And the Ammonites gave gifts to Uzziah. And his name spread abroad even to the *_entrance_* of Egypt, for he strengthened himself exceedingly.
* `2Ch 33:14` Now after this, he built a wall outside the city of David on the west side of Gihon, in the valley, even to the *_entrance_* at the fish-gate, and he encircled Ophel with it and raised it up a very great height. And he put captains of war in all the fortified cities of Judah.
* `Psa 119:130` The *_entrance_* of your words gives light. It gives understanding to the simple.
* `Pro 8:3` She cries at the gates, at the entry of the city, at the *_entrance_* of the doors,
* `Jer 1:15` For behold, I will call all the families of the kingdoms of the north," says the LORD, "and they shall come and shall each set his throne at the *_entrance_* of the gates of Jerusalem, and against all its walls around and against all the cities of Judah.
* `Ezk 40:15` And from the face of the gate of the *_entrance_* to the face of the porch of the inner gate was fifty cubits.
* `Ezk 44:5` And the LORD said to me, "Son of man, mark well and behold with your eyes and hear with your ears all that I say to you concerning all the ordinances of the house of the LORD and all its laws, and mark well the *_entrance_* of the house with every going forth of the sanctuary.
* `Amo 6:14` But behold, I will raise up against you a nation, O house of Israel," says the LORD the God of hosts, "and they shall afflict you from the *_entrance_* of Hamath to the river of the wilderness."
* `2Pe 1:11` For in this way an *_entrance_* into the everlasting kingdom of our Lord and Savior Jesus Christ shall be abundantly ministered to you.

_39 verses containing ENTRANCE_

== ENTRANCES

* `Ezk 43:11` And if they are ashamed of all that they have done, show them the form of the house, its fashion, its exits, its *_entrances_*, all its forms, all its ordinances, all its forms, and all its laws, and write it in their sight so that they may keep its whole form and all its ordinances and do them.
* `Mic 5:6` And they shall waste the land of Assyria with the sword and the land of Nimrod in its *_entrances_*. Thus he will deliver us from the Assyrian when he comes into our land and treads within our borders.

_2 verses containing ENTRANCES_

== ENTREAT

* `Gen 23:8` And he spoke with them, saying, "If it is your mind that I should bury my dead out of my sight, hear me, and *_entreat_* for me to Ephron the son of Zohar,
* `Exo 8:8` Then Pharaoh called for Moses and Aaron and said, "*_Entreat_* the LORD that he may take away the frogs from me and from my people, and I will let the people go so that they may do sacrifice to the LORD."
* `Exo 8:9` And Moses said to Pharaoh, "Glory over me in this: when shall I *_entreat_* for you, for your servants, and for your people to destroy the frogs from you and your houses so that they may remain in the river only?"
* `Exo 8:28` And Pharaoh said, "I will let you go so that you may sacrifice to the LORD your God in the wilderness. Only you shall not go very far away. *_Entreat_* for me."
* `Exo 8:29` And Moses said, "Behold, I go out from you, and I will *_entreat_* the LORD so that the swarms of flies may depart from Pharaoh, from his servants, and from his people tomorrow. But do not let Pharaoh deal deceitfully anymore in not letting the people go to sacrifice to the LORD."
* `Exo 9:28` *_Entreat_* the LORD (for it is enough) that there be no more mighty thunderings and hail, and I will let you go, and you shall stay no longer."
* `Exo 10:17` Now therefore, forgive, I pray you, my sin only this once and *_entreat_* the LORD your God so that he may take away from me this death only."
* `Rth 1:16` And Ruth said, "Do not *_entreat_* me to leave you, or to return from following you. For where you go, I will go, and where you lodge, I will lodge. Your people shall be my people and your God my God.
* `1Sa 2:25` If one man sins against another, the judge shall judge him, but if a man sins against the LORD, who shall *_entreat_* for him?" Nevertheless, they did not listen to the voice of their father because the LORD was inclined to slay them.
* `1Ki 13:6` And the king answered and said to the man of God, "*_Entreat_* now the face of the LORD your God and pray for me so that my hand may be restored to me again." And the man of God implored the LORD, and the king's hand was restored to him again and became as it was before.
* `Psa 45:12` And the daughter of Tyre shall be there with a gift. Even the rich among the people shall *_entreat_* your favor.
* `Pro 19:6` Many will *_entreat_* the favor of the prince. And every man is a friend to him who gives gifts.
* `1Co 4:13` Being defamed, we *_entreat_*. We are made as the filth of the world, the offscouring of all things to this day.
* `2Co 6:1` And working together [with him], we *_entreat_* also that you do not receive the grace of God in vain.
* `Phl 4:3` And I *_entreat_* you also, true companion, help those women who labored with me in the gospel, with Clement also, and with my other fellow-laborers, whose names are in the book of life.
* `1Ti 5:1` Do not rebuke an elder, but *_entreat_* him as a father, and the younger men as brothers,

_16 verses containing ENTREAT_

== ENTREATED

* `Gen 25:21` And Isaac *_entreated_* the LORD for his wife, because she was barren. And the LORD granted him his request, and Rebekah his wife conceived.
* `Exo 8:30` And Moses went out from Pharaoh and *_entreated_* the LORD.
* `Exo 10:18` And he went out from Pharaoh and *_entreated_* the LORD.
* `Jdg 13:8` Then Manoah *_entreated_* the LORD, and said, "O my Lord, let the man of God whom you sent come back to us and teach us what we shall do to the child who shall be born."
* `2Sa 21:14` And the bones of Saul and Jonathan his son they buried in the country of Benjamin in Zelah in the sepulcher of Kish his father. And they performed all that the king commanded. And after that God was *_entreated_* for the land.
* `2Sa 24:25` And David built an altar to the LORD there and offered burnt-offerings and peace-offerings. So the LORD was *_entreated_* for the land, and the plague was stayed from Israel.
* `1Ch 5:20` And they were helped against them, and the Hagarites and all who were with them were delivered into their hand, for they cried to God in the battle, and he was *_entreated_* by them because they put their trust in him.
* `2Ch 33:13` And he prayed to him, and God was *_entreated_* by him, heard his supplication, and brought him back to Jerusalem into his kingdom. Then Manasseh knew that the LORD is God.
* `2Ch 33:19` His prayer also, and how God was *_entreated_* by him, and all his sin, his trespass, and the places in which he built high places, and set up groves and engraved images, before he was humbled, behold, they are written among the sayings of the seers.
* `Ezr 8:23` So we fasted and implored our God for this. And he was *_entreated_* by us.
* `Job 19:16` I called my servant, and he gave me no answer. I *_entreated_* him with my mouth.
* `Job 19:17` My breath is strange to my wife, and I *_entreated_* to the children of my mother's womb.
* `Psa 119:58` I *_entreated_* your favor with my whole heart. Be merciful to me according to your word.
* `Isa 19:22` And the LORD will smite Egypt. He will smite and heal it. And they shall return even to the LORD, and he will be *_entreated_* by them and will heal them.
* `Luk 15:28` And he was angry and would not go in. Therefore, his father came out and *_entreated_* him.
* `Act 8:31` And he said, "How can I unless someone guides me?" And he *_entreated_* Philip to come up and sit with him.
* `Act 28:14` There we found brothers and were *_entreated_* to stay with them seven days. And so we came to Rome.
* `Heb 12:19` To the sound of a trumpet, or the voice of words, which those who heard the voice *_entreated_* that the word should not be spoken to them anymore.
* `Jms 3:17` But the wisdom that is from above is first pure, then peaceable, gentle, easy to be *_entreated_*, full of mercy and good fruits, without partiality, and without hypocrisy.

_19 verses containing ENTREATED_

== ENTREATIES

* `Pro 18:23` The poor uses *_entreaties_*, but the rich answers roughly.

_1 verse containing ENTREATIES_

== ENTREATY

* `2Co 8:4` Praying us with much *_entreaty_* that we would receive the gift and the fellowship of the ministering to the saints.

_1 verse containing ENTREATY_

== ENTRIES

* `Ezk 40:38` And the chambers and its *_entries_* were by the posts of the gates, where they washed the burnt-offering.

_1 verse containing ENTRIES_

== ENTRY

* `2Ki 16:18` And the covert for the sabbath that they had built in the house and the king's *_entry_* outside, he turned from the house of the LORD for the king of Assyria.
* `1Ch 9:19` And Shallum the son of Kore, the son of Ebiasaph, the son of Korah, and his brothers of the house of his father, the Korahites, were over the work of the service, keepers of the gates of the tabernacle, and their fathers, being over the host of the LORD, were keepers of the *_entry_*.
* `2Ch 4:22` And the snuffers, the basins, the spoons, and the censers, of pure gold; and the *_entry_* of the house, its inner doors for the holy of holies, and the doors of the house of the temple were of gold.
* `Pro 8:3` She cries at the gates, at the *_entry_* of the city, at the entrance of the doors,
* `Jer 19:2` And go forth to the valley of the son of Hinnom, which is by the *_entry_* of the east gate, and proclaim there the words that I shall tell you,
* `Jer 26:10` When the princes of Judah heard these things, they came up from the king's house to the house of the LORD and sat down in the *_entry_* of the new gate of the LORD'S house.
* `Jer 36:10` Then Baruch read in the book the words of Jeremiah in the house of the LORD, in the chamber of Gemariah the son of Shaphan the scribe, in the higher court, at the *_entry_* of the new gate of the LORD'S house, in the ears of all the people.
* `Jer 38:14` Then Zedekiah the king sent and took Jeremiah the prophet to him into the third *_entry_* that is in the house of the LORD. And the king said to Jeremiah, "I will ask you a thing. Hide nothing from me."
* `Jer 43:9` "Take great stones in your hand and hide them in the clay in the brick-kiln, which is at the *_entry_* of Pharaoh's house in Tahpanhes, in the sight of the men of Judah,
* `Ezk 8:5` Then he said to me, "Son of man, lift up your eyes now toward the north." So I lifted up my eyes toward the north, and behold, northward at the gate of the altar, in the *_entry_*, was this image of jealousy.
* `Ezk 27:3` And say to Tyre, who is situated at the *_entry_* of the sea, who is a merchant of the people for many coastlands, 'Thus says the Lord GOD: "O Tyre, you have said, 'I am of perfect beauty.'
* `Ezk 40:11` And he measured the breadth of the *_entry_* of the gate, ten cubits, and the length of the gate, thirteen cubits.
* `Ezk 40:40` And at the side outside, as one goes up to the *_entry_* of the north gate, were two tables, and on the other side, which was at the porch of the gate, were two tables.
* `Ezk 42:9` And from under these chambers was the *_entry_* on the east side, as one goes into them from the outer court.
* `Ezk 46:19` Afterward, he brought me through the *_entry_*, which was at the side of the gate, into the holy chambers of the priests, which looked toward the north, and behold, there was a place on the two sides westward.

_15 verses containing ENTRY_

== ENVIED

* `Gen 26:14` For he had possessions of flocks and possessions of herds, and very many servants. And the Philistines *_envied_* him.
* `Gen 30:1` And when Rachel saw that she bore Jacob no children, Rachel *_envied_* her sister and said to Jacob, "Give me children, or else I die."
* `Gen 37:11` And his brothers *_envied_* him, but his father observed the saying.
* `Psa 106:16` In the camp they also *_envied_* Moses and Aaron, the saint of the LORD.
* `Ecc 4:4` Again, I considered all labor and every right work, that for this, a man is *_envied_* by his neighbor. This is also vanity and vexation of spirit.
* `Ezk 31:9` I have made him fair by the multitude of his branches so that all the trees of Eden that were in the garden of God *_envied_* him.

_6 verses containing ENVIED_

== ENVIES

* `1Pe 2:1` Therefore, laying aside all malice, all guile, hypocrisies, *_envies_*, and all evil-speakings,

_1 verse containing ENVIES_

== ENVIOUS

* `Psa 37:1` [A Psalm of David.] Do not fret yourself because of evildoers, neither be *_envious_* against the workers of iniquity.
* `Psa 73:3` For I was *_envious_* at the foolish when I saw the prosperity of the wicked.
* `Pro 24:1` Do not be *_envious_* against evil men, neither desire to be with them,
* `Pro 24:19` Do not fret yourself because of evil men, neither be *_envious_* of the wicked,

_4 verses containing ENVIOUS_

== ENVY

* `Num 11:29` And Moses said to him, "Do you *_envy_* for my sake? I wish that all the LORD'S people were prophets and that the LORD would put his Spirit upon them."
* `Job 5:2` For wrath kills the foolish man, and *_envy_* slays the silly one.
* `Pro 3:31` Do not *_envy_* the oppressor, and choose none of his ways,
* `Pro 14:30` A sound heart is the life of the flesh, but *_envy_* the rottenness of the bones.
* `Pro 23:17` Do not let your heart *_envy_* sinners, but be in the fear of the LORD all the day long.
* `Pro 27:4` Wrath is cruel and anger is outrageous, but who is able to stand before *_envy_*?
* `Ecc 9:6` Also their love, their hatred, and their *_envy_* has now perished, neither do they have anymore a portion forever in anything that is done under the sun.
* `Isa 11:13` The *_envy_* of Ephraim shall also depart, and the adversaries of Judah shall be cut off. Ephraim shall not *_envy_* Judah, and Judah shall not distress Ephraim.
* `Ezk 35:11` Therefore, as I live," says the Lord GOD, "I will even do according to your anger and according to your *_envy_* which you have used out of your hatred against them, and I will make myself known among them when I have judged you.
* `Mth 27:18` (For he knew that for *_envy_* they had delivered him.)
* `Mrk 15:10` (For he knew that the chief priests had delivered him for *_envy_*.)
* `Act 7:9` "And the patriarchs, moved with *_envy_*, sold Joseph into Egypt. But God was with him
* `Act 13:45` But when the Jews saw the multitudes, they were filled with *_envy_* and spoke against those things which were uttered by Paul, contradicting and blaspheming.
* `Act 17:5` But the Jews who did not believe, being moved with *_envy_*, took for themselves some vile fellows of the baser sort, and gathering a company, set all the city in an uproar. They assaulted the house of Jason and sought to bring them out to the people.
* `Rom 1:29` Being filled with all unrighteousness, fornication, wickedness, covetousness, maliciousness; full of *_envy_*, murder, debate, deceit, malignity; whisperers,
* `1Co 13:4` Charity is patient and is kind. Charity does not *_envy_*. Charity does not vaunt itself, is not puffed up,
* `Phl 1:15` Some indeed preach Christ even from *_envy_* and strife, and some also from good will.
* `1Ti 6:4` He is proud, knowing nothing, but doting about questions and strifes of words, from which comes *_envy_*, strife, railings, evil surmisings,
* `Tit 3:3` For we ourselves were also sometimes foolish, disobedient, deceived, serving diverse lusts and pleasures, living in malice and *_envy_*, hateful, and hating one another.
* `Jms 4:5` Do you think that the Scripture says in vain, "The spirit which dwells in us earnestly desires to *_envy_*"?

_20 verses containing ENVY_

== ENVYING

* `Rom 13:13` Let us walk honestly, as in the day, not in rioting and drunkenness, not in lewdness and wantonness, and not in strife and *_envying_*.
* `1Co 3:3` Because you are still carnal. For whereas there is among you *_envying_*, strife, and divisions, are you not carnal and walk as men?
* `Gal 5:26` Let us not be desirous of vain-glory, provoking one another, *_envying_* one another.
* `Jms 3:14` But if you have bitter *_envying_* and strife in your hearts, do not glory and do not lie against the truth.
* `Jms 3:16` For where *_envying_* and strife is, there is confusion and every evil work.

_5 verses containing ENVYING_

== ENVYINGS

* `2Co 12:20` For I fear, lest, when I come, I shall not find you such as I wish, and that I shall be found by you such as you do not wish, lest there be debates, *_envyings_*, wraths, strifes, backbitings, whisperings, conceits, tumults,
* `Gal 5:21` *_Envyings_*, murders, drunkenness, revelings, and such like these, of which I tell you before, as I have also told you in time past, that those who do such things shall not inherit the kingdom of God.

_2 verses containing ENVYINGS_

== EPAPHRAS

* `Col 1:7` As you also learned from *_Epaphras_* our dear fellow-servant, who is for you a faithful minister of Christ,
* `Col 4:12` *_Epaphras_*, who is one of you, a servant of Christ, salutes you, always laboring fervently for you in prayers, that you may stand perfect and complete in all the will of God.
* `Phm 1:23` *_Epaphras_*, my fellow-prisoner in Christ Jesus, salutes you,

_3 verses containing EPAPHRAS_

== EPAPHRODITUS

* `Phl 2:25` Yet I supposed it necessary to send to you *_Epaphroditus_*, my brother, companion in labor, and fellow-soldier, but your messenger, and he who ministered to my needs.
* `Phl 4:18` But I have all and abound. I am full, having received from *_Epaphroditus_* the things which were sent from you, an odor of a sweet smell, a sacrifice acceptable, well-pleasing to God.

_2 verses containing EPAPHRODITUS_

== EPENETUS

* `Rom 16:5` Likewise, greet the church that is in their house. Salute my well-beloved *_Epenetus_*, who is the first-fruits of Achaia to Christ.

_1 verse containing EPENETUS_

== EPHAH

* `Gen 25:4` And the sons of Midian: *_Ephah_*, Epher, Hanoch, Abidah, and Eldaah. All these were the children of Keturah.
* `Exo 16:36` (Now an omer is the tenth part of an *_ephah_*.)
* `Lev 5:11` 'But if he is not able to bring two turtle-doves or two young pigeons, then he who sinned shall bring for his offering the tenth part of an *_ephah_* of fine flour for a sin-offering. He shall put no oil upon it, neither shall he put any frankincense upon it, for it is a sin-offering.
* `Lev 6:20` "This is the offering of Aaron and of his sons, which they shall offer to the LORD in the day when he is anointed: the tenth part of an *_ephah_* of fine flour for a perpetual food-offering, half of it in the morning and half of it at night.
* `Lev 19:36` Just balances, just weights, a just *_ephah_*, and a just hin you shall have. I am the LORD your God who brought you out of the land of Egypt.
* `Num 5:15` Then the man shall bring his wife to the priest and bring her offering for her, the tenth part of an *_ephah_* of barley-meal. He shall pour no oil upon it nor put frankincense upon it, for it is an offering of jealousy, an offering of memorial, bringing iniquity to remembrance.
* `Num 28:5` And a tenth part of an *_ephah_* of flour for a food-offering, mingled with a fourth part of a hin of beaten oil—
* `Jdg 6:19` And Gideon went in and made ready a kid and unleavened cakes of an *_ephah_* of flour. He put the flesh in a basket and he put the broth in a pot, and he brought it out to him under the oak and presented it.
* `Rth 2:17` So she gleaned in the field until evening and beat out that which she had gleaned, and it was about an *_ephah_* of barley.
* `1Sa 1:24` And when she had weaned him, she took him up with her, with three bulls, one *_ephah_* of flour, and a bottle of wine, and brought him to the house of the LORD in Shiloh. And the child was young.
* `1Sa 17:17` And Jesse said to David his son, "Now take for your brothers an *_ephah_* of this parched grain and these ten loaves, and run to the camp to your brothers.
* `1Ch 1:33` And the sons of Midian: *_Ephah_*, Epher, Henoch, Abida, and Eldaah. All these are the sons of Keturah.
* `1Ch 2:46` And *_Ephah_*, Caleb's concubine, bore Haran, Moza, and Gazez. And Haran begot Gazez.
* `1Ch 2:47` And the sons of Jahdai: Regem, Jotham, Geshan, Pelet, *_Ephah_*, and Shaaph.
* `Isa 5:10` Even ten acres of vineyard shall yield one bath, and the seed of a homer shall yield an *_ephah_*."
* `Isa 60:6` The multitude of camels shall cover you, dromedaries of Midian and *_Ephah_*. All those from Sheba shall come. They shall bring gold and incense and show forth the praises of the LORD.
* `Ezk 45:10` "You shall have just balances, a just *_ephah_* and a just bath.
* `Ezk 45:11` The *_ephah_* and the bath shall be of one measure, so that the bath may contain the tenth part of a homer and the *_ephah_* the tenth part of a homer. Its measure shall be after the homer.
* `Ezk 45:13` "This is the oblation that you shall offer: the sixth part of an *_ephah_* of a homer of wheat, and you shall give the sixth part of an *_ephah_* of a homer of barley;
* `Ezk 45:24` And he shall prepare a food-offering of an *_ephah_* for a bull, an *_ephah_* for a ram, and a hin of oil for an *_ephah_*.
* `Ezk 46:5` And the food-offering shall be an *_ephah_* for a ram, and the food-offering for the lambs as he shall be able to give, and a hin of oil to an *_ephah_*.
* `Ezk 46:7` And he shall prepare a food-offering, an *_ephah_* for a bull and an *_ephah_* for a ram, and for the lambs according as his hand shall be able, along with a hin of oil to an *_ephah_*.
* `Ezk 46:11` "And in the feasts and in the solemnities the food-offering shall be an *_ephah_* to a bull and an *_ephah_* to a ram, and to the lambs as he is able to give, along with a hin of oil to an *_ephah_*.
* `Ezk 46:14` And you shall prepare a food-offering for it every morning, the sixth part of an *_ephah_* and the third part of a hin of oil to temper with the fine flour, a food-offering continually by a perpetual ordinance to the LORD.
* `Amo 8:5` Saying, 'When will the new moon be gone so that we may sell grain, and the sabbath so that we may set forth wheat, making the *_ephah_* small and the shekel great, and falsifying the balances by deceit,
* `Zch 5:6` And I said, "What is it?" And he said, "This is an *_ephah_* that goes forth." He said moreover, "This is their resemblance through all the earth.
* `Zch 5:7` And behold, there was a talent of lead lifted up. And this is a woman who sits in the midst of the *_ephah_*."
* `Zch 5:8` And he said, "This is wickedness." And he cast it into the midst of the *_ephah_*, and he cast the weight of lead upon its mouth.
* `Zch 5:9` Then I lifted up my eyes and looked, and behold, there came out two women, and the wind was in their wings, for they had wings like the wings of a stork. And they lifted up the *_ephah_* between the earth and the heaven.
* `Zch 5:10` Then I said to the angel who talked with me, "To where do these bear the *_ephah_*?"

_30 verses containing EPHAH_

== EPHAI

* `Jer 40:8` They came to Gedaliah at Mizpah, even Ishmael the son of Nethaniah, Johanan and Jonathan the sons of Kareah, Seraiah the son of Tanhumeth, the sons of *_Ephai_* the Netophathite, and Jezaniah the son of a Maachathite—they and their men.

_1 verse containing EPHAI_

== EPHER

* `Gen 25:4` And the sons of Midian: Ephah, *_Epher_*, Hanoch, Abidah, and Eldaah. All these were the children of Keturah.
* `1Ch 1:33` And the sons of Midian: Ephah, *_Epher_*, Henoch, Abida, and Eldaah. All these are the sons of Keturah.
* `1Ch 4:17` And the sons of Ezra were Jethur, Mered, *_Epher_*, and Jalon. Mered took a wife and she bore Miriam, Shammai, and Ishbah the father of Eshtemoa.
* `1Ch 5:24` And these were the heads of the house of their fathers: even *_Epher_*, Ishi, Eliel, Azriel, Jeremiah, Hodaviah, and Jahdiel, mighty men of valor, famous men, and heads of the house of their fathers.

_4 verses containing EPHER_

== EPHES-DAMMIM

* `1Sa 17:1` Now the Philistines collected their armies to battle and were assembled at Shochoh, which belongs to Judah, and encamped between Shochoh and Azekah in *_Ephes-dammim_*.

_1 verse containing EPHES-DAMMIM_

== EPHESIAN

* `Act 21:29` For they had seen Trophimus, an *_Ephesian_*, with him before in the city, whom they supposed that Paul had brought into the temple.

_1 verse containing EPHESIAN_

== EPHESIANS

* `Act 19:28` And when they heard these sayings, they were full of wrath and cried out, saying, "Diana of the *_Ephesians_* is great."
* `Act 19:34` But when they knew that he was a Jew, all with one voice for about two hours cried out, "Diana of the *_Ephesians_* is great."
* `Act 19:35` And when the town-clerk had appeased the people, he said, "Men of Ephesus, what man is there who does not know that the city of the *_Ephesians_* is a worshiper of the great goddess Diana and of the image which fell down from the sky?

_3 verses containing EPHESIANS_

== EPHESUS

* `Act 18:19` And he came to *_Ephesus_* and left them there. But he himself entered into the synagogue and reasoned with the Jews.
* `Act 18:21` But bid them farewell, saying, "I must by all means keep this feast that comes in Jerusalem. But I will return to you, if God wills." And he sailed from *_Ephesus_*.
* `Act 18:24` And a certain Jew named Apollos, born at Alexandria, an eloquent man and mighty in the Scriptures, came to *_Ephesus_*.
* `Act 19:1` And it came to pass, that while Apollos was at Corinth, Paul, having passed through the upper region, came to *_Ephesus_*, and finding some disciples,
* `Act 19:17` And this was known to all the Jews and Greeks also dwelling at *_Ephesus_*. And fear fell on them all, and the name of the Lord Jesus was magnified.
* `Act 19:26` Moreover, you see and hear, that not at *_Ephesus_* alone, but almost throughout all Asia, this Paul has persuaded and turned away many people, saying that they are no gods which are made with hands.
* `Act 19:35` And when the town-clerk had appeased the people, he said, "Men of *_Ephesus_*, what man is there who does not know that the city of the Ephesians is a worshiper of the great goddess Diana and of the image which fell down from the sky?
* `Act 20:16` For Paul had determined to sail by *_Ephesus_* because he would not spend the time in Asia, for he hastened, if it were possible for him, to be at Jerusalem on the day of Pentecost.
* `Act 20:17` And from Miletus he sent to *_Ephesus_* and called the elders of the church.
* `1Co 15:32` If after the manner of men I have fought with beasts at *_Ephesus_*, what advantage is it to me? If the dead do not rise, "Let us eat and drink, for tomorrow we die."
* `1Co 16:8` But I shall remain at *_Ephesus_* until Pentecost,
* `Eph 1:1` Paul, an apostle of Jesus Christ by the will of God, to the saints who are at *_Ephesus_* and to the faithful in Christ Jesus:
* `1Ti 1:3` As I implored you when I went into Macedonia, remain at *_Ephesus_* so that you might charge some that they teach no other doctrine,
* `2Ti 1:18` May the Lord grant to him that he may find mercy from the Lord in that day. And in all that he ministered to me at *_Ephesus_*, you know very well.
* `2Ti 4:12` And I have sent Tychicus to *_Ephesus_*.
* `Rev 1:11` Saying, "I am Alpha and Omega, the first and the last," and, "What you see, write in a book and send it to the seven churches which are in Asia: to *_Ephesus_*, to Smyrna, to Pergamos, to Thyatira, to Sardis, to Philadelphia, and to Laodicea."
* `Rev 2:1` "To the angel of the church of *_Ephesus_*, write: 'He who holds the seven stars in his right hand, who walks in the midst of the seven golden candlesticks, says these things:

_17 verses containing EPHESUS_

== EPHLAL

* `1Ch 2:37` Zabad begot *_Ephlal_*, *_Ephlal_* begot Obed,

_1 verse containing EPHLAL_

== EPHOD

* `Exo 25:7` Onyx stones, and stones to be set in the *_ephod_* and in the breast-plate.
* `Exo 28:4` And these are the garments which they shall make: a breast-plate, an *_ephod_*, a robe, an embroidered coat, a miter, and a girdle. And they shall make holy garments for Aaron your brother and his sons so that he may minister to me in the priest's office.
* `Exo 28:6` "And they shall make the *_ephod_* of gold, and of blue, purple, and scarlet, and of fine twined linen, with skillful work.
* `Exo 28:8` And the skillfully woven girdle of the *_ephod_*, which is upon it, shall be of the same, according to its work, even of gold, of blue, purple, and scarlet, and of fine twined linen.
* `Exo 28:12` And you shall put the two stones upon the shoulders of the *_ephod_* for stones of memorial to the children of Israel. And Aaron shall bear their names before the LORD upon his two shoulders for a memorial.
* `Exo 28:15` "And you shall make the breast-plate of judgment with skillful work. After the work of the *_ephod_* you shall make it. Of gold, of blue, purple, and scarlet, and of fine twined linen you shall make it.
* `Exo 28:25` And the other two ends of the two wreathed chains you shall fasten in the two settings and put them on the shoulder-pieces of the *_ephod_* before it.
* `Exo 28:26` And you shall make two rings of gold, and you shall put them upon the two ends of the breast-plate in its border, which is in the side of the *_ephod_* inward.
* `Exo 28:27` And two other rings of gold you shall make and shall put them on the two sides of the *_ephod_* underneath, toward its forepart, over against the other coupling thereof, above the skillfully woven girdle of the *_ephod_*.
* `Exo 28:28` And they shall bind the breast-plate by its rings to the rings of the *_ephod_* with a lace of blue so that it may be above the skillfully woven girdle of the *_ephod_* and that the breast-plate does not come loose from the *_ephod_*.
* `Exo 28:31` "And you shall make the robe of the *_ephod_* all of blue.
* `Exo 29:5` And you shall take the garments and put upon Aaron the coat, the robe of the *_ephod_*, the *_ephod_*, the breast-plate, and gird him with the skillfully woven girdle of the *_ephod_*.
* `Exo 35:9` And onyx stones and stones to be set for the *_ephod_* and for the breast-plate.
* `Exo 35:27` And the rulers brought onyx stones and stones to be set for the *_ephod_* and for the breast-plate,
* `Exo 39:2` And he made the *_ephod_* of gold, blue, purple, scarlet, and fine twined linen.
* `Exo 39:5` And the skillfully woven girdle of his *_ephod_* that was upon it was of the same, according to the work thereof, of gold, blue, purple, scarlet, and fine twined linen, as the LORD commanded Moses.
* `Exo 39:7` And he put them on the shoulders of the *_ephod_* so that they should be stones for a memorial to the children of Israel, as the LORD commanded Moses.
* `Exo 39:8` And he made the breast-plate of skillful work like the work of the *_ephod_* of gold, blue, purple, scarlet, and fine twined linen.
* `Exo 39:18` And the two ends of the two wreathed chains they fastened in the two settings and put them on the shoulder-pieces of the *_ephod_* before it.
* `Exo 39:19` And they made two rings of gold and put them on the two ends of the breast-plate upon its border, which was on the side of the *_ephod_* inward.
* `Exo 39:20` And they made two other golden rings and put them on the two sides of the *_ephod_* underneath toward its forepart, over against the other coupling thereof, above the skillfully woven girdle of the *_ephod_*.
* `Exo 39:21` And they bound the breast-plate by its rings to the rings of the *_ephod_* with a lace of blue so that it might be above the skillfully woven girdle of the *_ephod_* and that the breast-plate might not come loose from the *_ephod_*, as the LORD commanded Moses.
* `Exo 39:22` And he made the robe of the *_ephod_* of woven work, all of blue.
* `Lev 8:7` And he put upon him the coat, girded him with the girdle, clothed him with the robe, and put the *_ephod_* upon him. And he girded him with the skillfully woven girdle of the *_ephod_* and bound it to him with it.
* `Num 34:23` The prince of the children of Joseph, for the tribe of the children of Manasseh, Hanniel the son of *_Ephod_*;
* `Jdg 8:27` And Gideon made from it an *_ephod_* and put it in his city, even in Ophrah. And all Israel went astray after it there, and it became a snare to Gideon and to his house.
* `Jdg 17:5` And the man Micah had a house of gods, and he made an *_ephod_* and teraphim and consecrated one of his sons, who became his priest.
* `Jdg 18:14` Then the five men who went to explore the country of Laish answered and said to their brothers, "Do you know that there is in these houses an *_ephod_*, teraphim, an engraved image, and a molten image? Now therefore, consider what you have to do."
* `Jdg 18:17` And the five men who went to explore the land went up, came in there, and took the engraved image, the *_ephod_*, the teraphim, and the molten image. And the priest stood in the entrance of the gate with the six hundred men who were appointed with weapons of war.
* `Jdg 18:18` And these went into Micah's house and brought the carved image, the *_ephod_*, the teraphim, and the molten image. Then the priest said to them, "What are you doing?"
* `Jdg 18:20` And the priest's heart was glad and he took the *_ephod_*, the teraphim, and the engraved image and went in the midst of the people.
* `1Sa 2:18` But Samuel ministered before the LORD, being a child, girded with a linen *_ephod_*.
* `1Sa 2:28` And did I choose him out of all the tribes of Israel to be my priest, to offer upon my altar, to burn incense, to wear an *_ephod_* before me? And did I give to the house of your father all the offerings made by fire of the children of Israel?
* `1Sa 14:3` Along with Ahiah, the son of Ahitub, Ichabod's brother, the son of Phinehas, the son of Eli, the LORD'S priest in Shiloh, wearing an *_ephod_*. And the people did not know that Jonathan was gone.
* `1Sa 21:9` And the priest said, "The sword of Goliath the Philistine, whom you slew in the valley of Elah, behold, it is here wrapped in a cloth behind the *_ephod_*. If you will take that, take it, for there is no other except that here." And David said, "There is none like that. Give it to me."
* `1Sa 22:18` And the king said to Doeg, "Turn, and fall upon the priests." And Doeg the Edomite turned and he fell upon the priests and slew on that day eighty-five persons who wore a linen *_ephod_*.
* `1Sa 23:6` And it came to pass when Abiathar the son of Ahimelech fled to David at Keilah, that he came down with an *_ephod_* in his hand.
* `1Sa 23:9` And David knew that Saul secretly plotted mischief against him. And he said to Abiathar the priest, "Bring the *_ephod_* here."
* `1Sa 30:7` And David said to Abiathar the priest, Ahimelech's son, "I pray you, bring the *_ephod_* here to me." And Abiathar brought the *_ephod_* there to David.
* `2Sa 6:14` And David danced before the LORD with all his might. And David was girded with a linen *_ephod_*.
* `1Ch 15:27` And David was clothed with a robe of fine linen, along with all the Levites who bore the ark, the singers, and Chenaniah the master of the song with the singers. David also had upon him an *_ephod_* of linen.
* `Hos 3:4` For the children of Israel shall abide many days without a king, without a prince, without a sacrifice, without an image, without an *_ephod_*, and without teraphim.

_42 verses containing EPHOD_

== EPHRAIM

* `Gen 41:52` And the name of the second he called *_Ephraim_*. "For God has caused me to be fruitful in the land of my affliction."
* `Gen 46:20` And to Joseph in the land of Egypt were born Manasseh and *_Ephraim_*, whom Asenath the daughter of Poti-pherah priest of On bore to him.
* `Gen 48:1` And it came to pass after these things, that someone told Joseph, "Behold, your father is sick." And he took with him his two sons, Manasseh and *_Ephraim_*.
* `Gen 48:5` And now, your two sons, *_Ephraim_* and Manasseh, who were born to you in the land of Egypt, before I came to you into Egypt, are mine. As Reuben and Simeon, they shall be mine.
* `Gen 48:13` And Joseph took them both, *_Ephraim_* in his right hand toward Israel's left hand and Manasseh in his left hand toward Israel's right hand, and brought them near to him.
* `Gen 48:14` And Israel stretched out his right hand and laid it upon *_Ephraim_*'s head, who was the younger, and his left hand upon Manasseh's head, guiding his hands by design, for Manasseh was the first-born.
* `Gen 48:17` And when Joseph saw that his father laid his right hand upon the head of *_Ephraim_*, it displeased him. And he lifted his father's hand to move it from *_Ephraim_*'s head to Manasseh's head.
* `Gen 48:20` And he blessed them that day, saying, "In you Israel shall bless, saying, 'May God make you as *_Ephraim_* and as Manasseh.'" And he set *_Ephraim_* before Manasseh.
* `Gen 50:23` And Joseph saw *_Ephraim_*'s children to the third generation. The children also of Machir, the son of Manasseh, were brought up upon Joseph's knees.
* `Num 1:10` Of the children of Joseph, of *_Ephraim_*, Elishama the son of Ammihud, and of Manasseh, Gamaliel the son of Pedahzur;
* `Num 1:32` Of the children of Joseph, namely, of the children of *_Ephraim_*—by their generations, after their families, by the house of their fathers, according to the number of the names, from twenty years old and upward, all who were able to go forth to war—
* `Num 1:33` Those who were numbered of them, even of the tribe of *_Ephraim_*, were forty thousand and five hundred.
* `Num 2:18` "On the west side shall be the standard of the camp of *_Ephraim_* according to their armies, and the captain of the sons of *_Ephraim_* shall be Elishama the son of Ammihud.
* `Num 2:24` All who were numbered of the camp of *_Ephraim_* were one hundred and eight thousand and one hundred throughout their armies. And they shall go forward in the third rank.
* `Num 7:48` On the seventh day Elishama the son of Ammihud, prince of the children of *_Ephraim_*, offered.
* `Num 10:22` And the standard of the camp of the children of *_Ephraim_* moved forward according to their armies. And over his host was Elishama the son of Ammihud.
* `Num 13:8` Of the tribe of *_Ephraim_*, Oshea the son of Nun;
* `Num 26:28` The sons of Joseph after their families were Manasseh and *_Ephraim_*.
* `Num 26:35` These are the sons of *_Ephraim_* after their families: of Shuthelah, the family of the Shuthalhites; of Becher, the family of the Bachrites; of Tahan, the family of the Tahanites.
* `Num 26:37` These are the families of the sons of *_Ephraim_* according to those who were numbered of them, thirty-two thousand and five hundred. These are the sons of Joseph after their families.
* `Num 34:24` The prince of the tribe of the children of *_Ephraim_*, Kemuel the son of Shiphtan;
* `Deu 33:17` His glory is like the first-born of his bull, and his horns are like the horns of wild oxen. With them he shall push the people together to the ends of the earth. And they are the tens of thousands of *_Ephraim_*, and they are the thousands of Manasseh."
* `Deu 34:2` All Naphtali, the land of *_Ephraim_*, Manasseh, all the land of Judah, to the utmost sea,
* `Jsh 14:4` For the children of Joseph were two tribes, Manasseh and *_Ephraim_*; therefore, they gave no part to the Levites in the land, except cities to dwell in with their suburbs for their livestock and for their substance.
* `Jsh 16:4` So the children of Joseph, Manasseh and *_Ephraim_*, took their inheritance.
* `Jsh 16:5` And the border of the children of *_Ephraim_* according to their families was this: even the border of their inheritance on the east side was Ataroth-adar, to Beth-horon the upper,
* `Jsh 16:8` The border went out from Tappuah westward to the Kanah River, and its limits were at the sea. This is the inheritance of the tribe of the children of *_Ephraim_* by their families.
* `Jsh 16:9` And the separate cities for the children of *_Ephraim_* were among the inheritance of the children of Manasseh, all the cities with their villages.
* `Jsh 17:8` Now Manasseh had the land of Tappuah, but Tappuah on the border of Manasseh belonged to the children of *_Ephraim_*.
* `Jsh 17:9` And the border descended to the Kanah River, southward of the river. These cities of *_Ephraim_* are among the cities of Manasseh. Then the border of Manasseh also was on the north side of the river, and its limits were at the sea.
* `Jsh 17:10` Southward it was *_Ephraim_*'s, and northward it was Manasseh's, and the sea is his border. And they met together in Asher on the north and in Issachar on the east.
* `Jsh 17:15` And Joshua answered them, "If you are a great people, then go up to the forest and cut down for yourself there in the land of the Perizzites and of the Rephaim, since mount *_Ephraim_* is too narrow for you."
* `Jsh 17:17` And Joshua spoke to the house of Joseph, even to *_Ephraim_* and to Manasseh, saying, "You are a great people, and have great power. You shall not have one lot only.
* `Jsh 19:50` According to the word of the LORD they gave him the city which he asked, even Timnath-serah in the mountains of *_Ephraim_*. And he built the city and dwelt in it.
* `Jsh 20:7` And they appointed Kedesh in Galilee in the mountains of Naphtali, Shechem in the mountains of *_Ephraim_*, and Kirjath-arba (which is Hebron) in the mountains of Judah.
* `Jsh 21:5` And the rest of the children of Kohath had by lot out of the families of the tribe of *_Ephraim_*, out of the tribe of Dan, and out of the half-tribe of Manasseh, ten cities.
* `Jsh 21:20` And the families of the children of Kohath, the Levites who remained of the children of Kohath, even they had the cities of their lot out of the tribe of *_Ephraim_*.
* `Jsh 21:21` For they gave them Shechem with its suburbs in the mountains of *_Ephraim_* to be a city of refuge for the slayer, Gezer with its suburbs,
* `Jsh 24:30` And they buried him in the border of his inheritance in Timnath-serah, which is in the mountains of *_Ephraim_* on the north side of the hill of Gaash.
* `Jsh 24:33` And Eleazar the son of Aaron died, and they buried him on a hill that pertained to Phinehas his son, which was given to him on mount *_Ephraim_*.
* `Jdg 1:29` *_Ephraim_* did not expel the Canaanites who dwelt in Gezer, but the Canaanites dwelt in Gezer among them.
* `Jdg 2:9` And they buried him in the border of his inheritance in Timnath-heres, on the mountain of *_Ephraim_*, on the north side of the hill of Gaash.
* `Jdg 3:27` And it came to pass when he had come, that he blew a trumpet on the mountain of *_Ephraim_*, and the children of Israel went down with him from the mountain, and he before them.
* `Jdg 4:5` And she dwelt under the palm-tree of Deborah between Ramah and Beth-el in the mountains of *_Ephraim_*, and the children of Israel came up to her for judgment.
* `Jdg 5:14` Out of *_Ephraim_* there was a root of them against Amalek. After you was Benjamin among your people. Out of Machir governors came down, and out of Zebulun those who handle the pen of the writer.
* `Jdg 7:24` And Gideon sent messengers throughout all mount *_Ephraim_*, saying, "Come down against the Midianites and take the waters before them to Beth-barah and the Jordan." Then all the men of *_Ephraim_* assembled and took the waters to Beth-barah and the Jordan.
* `Jdg 8:1` And the men of *_Ephraim_* said to him, "Why have you treated us like this, not calling for us when you went to fight with the Midianites?" And they chided with him sharply.
* `Jdg 8:2` And he said to them, "What have I done now in comparison of you? Is the gleaning of the grapes of *_Ephraim_* not better than the vintage of Abiezer?
* `Jdg 10:1` And after Abimelech there arose to defend Israel Tola the son of Puah, the son of Dodo, a man of Issachar. And he dwelt in Shamir in the mountains of *_Ephraim_*.
* `Jdg 10:9` Moreover, the children of Ammon passed over the Jordan to fight also against Judah, against Benjamin, and against the house of *_Ephraim_*, so that Israel was greatly distressed.
* `Jdg 12:1` And the men of *_Ephraim_* assembled and went northward and said to Jephthah, "Why did you pass over to fight against the children of Ammon and did not call us to go with you? We will burn your house upon you with fire."
* `Jdg 12:4` Then Jephthah collected all the men of Gilead and fought with *_Ephraim_*. And the men of Gilead smote *_Ephraim_*, because they said, "You Gileadites are fugitives of *_Ephraim_* among the Ephraimites and among the Manassites."
* `Jdg 12:15` And Abdon the son of Hillel the Pirathonite died and was buried in Pirathon in the land of *_Ephraim_* on the mountain of the Amalekites.
* `Jdg 17:1` And there was a man from mount *_Ephraim_*, whose name was Micah.
* `Jdg 17:8` And the man departed out of the city from Beth-lehem-judah to sojourn where he could find a place. And he came to mount *_Ephraim_* to the house of Micah as he journeyed.
* `Jdg 18:2` And the children of Dan sent from their family five men from their borders, men of valor, from Zorah and from Eshtaol, to explore the land and to search it. And they said to them, "Go, search the land." When they came to mount *_Ephraim_*, to the house of Micah, they lodged there.
* `Jdg 18:13` And they passed from there to mount *_Ephraim_* and came to the house of Micah.
* `Jdg 19:1` And it came to pass in those days when there was no king in Israel, that there was a certain Levite dwelling on the side of mount *_Ephraim_*, who took for himself a concubine out of Beth-lehem-judah.
* `Jdg 19:16` And behold, there came an old man from his work out of the field at evening, who was also of mount *_Ephraim_*, and he dwelt in Gibeah. But the men of the place were Benjaminites.
* `Jdg 19:18` And he said to him, "We are passing from Beth-lehem-Judah toward the side of mount *_Ephraim_*. I am from there. And I went to Beth-lehem-judah, but I am now going to the house of the LORD. And there is no man who receives me into his house.
* `1Sa 1:1` Now there was a certain man of Ramathaim-zophim, of mount *_Ephraim_*, and his name was Elkanah, the son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephrathite.
* `1Sa 9:4` And he passed through mount *_Ephraim_* and passed through the land of Shalisha, but they did not find them. Then they passed through the land of Shalim, and they were not there. And he passed through the land of the Benjaminites, but they did not find them.
* `1Sa 14:22` Likewise, all the men of Israel who had hid themselves in the mountains of *_Ephraim_*, when they heard that the Philistines fled, even they also followed hard after them in the battle.
* `2Sa 2:9` And he made him king over Gilead, over the Ashurites, over Jezreel, over *_Ephraim_*, over Benjamin, and over all Israel.
* `2Sa 13:23` And it came to pass after two full years, that Absalom had sheep-shearers in Baal-hazor, which is beside *_Ephraim_*, and Absalom invited all the king's sons.
* `2Sa 18:6` So the people went out into the field against Israel, and the battle was in the forest of *_Ephraim_*.
* `2Sa 20:21` The matter is not so. But a man of mount *_Ephraim_*, Sheba the son of Bichri by name, has lifted up his hand against the king, even against David. Deliver him only, and I will depart from the city." And the woman said to Joab, "Behold, his head shall be thrown to you over the wall."
* `1Ki 4:8` And these are their names: the son of Hur, in the mountains of *_Ephraim_*;
* `1Ki 12:25` Then Jeroboam built Shechem on mount *_Ephraim_* and dwelt in it, and he went out from there and built Penuel.
* `2Ki 5:22` And he said, "All is well. My master has sent me, saying, 'Behold, even now two young men from the sons of the prophets have come to me from mount *_Ephraim_*. Give them, I pray you, a talent of silver and two changes of garments.'"
* `2Ki 14:13` And Jehoash king of Israel took Amaziah king of Judah, the son of Jehoash the son of Ahaziah, at Beth-shemesh, and came to Jerusalem and broke down the wall of Jerusalem from the gate of *_Ephraim_* to the corner gate, four hundred cubits.
* `1Ch 6:66` And some of the families of the sons of Kohath had cities of their borders out of the tribe of *_Ephraim_*.
* `1Ch 6:67` And they gave them the cities of refuge: Shechem in the mountains of *_Ephraim_* with its suburbs, Gezer with its suburbs,
* `1Ch 7:20` And the sons of *_Ephraim_*: Shuthelah, Bered his son, Tahath his son, Eladah his son, Tahath his son,
* `1Ch 7:22` And *_Ephraim_* their father mourned many days, and his brothers came to comfort him.
* `1Ch 9:3` And in Jerusalem dwelt some of the children of Judah, some of the children of Benjamin, and some of the children of *_Ephraim_* and Manasseh:
* `1Ch 12:30` And of the children of *_Ephraim_* twenty thousand and eight hundred, mighty men of valor, famous throughout the house of their fathers.
* `1Ch 27:10` The seventh captain for the seventh month was Helez the Pelonite, of the children of *_Ephraim_*. And in his course were twenty-four thousand.
* `1Ch 27:14` The eleventh captain for the eleventh month was Benaiah the Pirathonite, of the children of *_Ephraim_*. And in his course were twenty-four thousand.
* `1Ch 27:20` Of the children of *_Ephraim_*, Hoshea the son of Azaziah; of the half tribe of Manasseh, Joel the son of Pedaiah;
* `2Ch 13:4` And Abijah stood upon mount Zemaraim, which is in the mountains of *_Ephraim_*, and said, "Hear me, Jeroboam and all Israel.
* `2Ch 15:8` And when Asa heard these words and the prophecy of Oded the prophet, he took courage and put away the abominable idols out of all the land of Judah and Benjamin and out of the cities which he had taken from mount *_Ephraim_*, and renewed the altar of the LORD that was before the porch of the LORD.
* `2Ch 15:9` And he gathered all Judah and Benjamin and the strangers with them out of *_Ephraim_* and Manasseh and out of Simeon, for they resorted to him out of Israel in multitudes when they saw that the LORD his God was with him.
* `2Ch 17:2` And he placed forces in all the fortified cities of Judah and set garrisons in the land of Judah and in the cities of *_Ephraim_*, which Asa his father had taken.
* `2Ch 19:4` And Jehoshaphat dwelt at Jerusalem. And he went out again through the people from Beer-sheba to mount *_Ephraim_* and brought them back to the LORD God of their fathers.
* `2Ch 25:7` But a man of God came to him, saying, "O king, do not let the army of Israel go with you, for the LORD is not with Israel, namely, with all the children of *_Ephraim_*.
* `2Ch 25:10` Then Amaziah separated them, namely, the army that had come to him out of *_Ephraim_*, to go home again. Therefore, their anger was greatly kindled against Judah and they returned home in great anger.
* `2Ch 25:23` And Joash the king of Israel took Amaziah king of Judah, the son of Joash, the son of Jehoahaz, at Beth-shemesh, and brought him to Jerusalem and broke down the wall of Jerusalem from the gate of *_Ephraim_* to the corner gate, four hundred cubits.
* `2Ch 28:7` And Zichri, a mighty man of *_Ephraim_*, slew Maaseiah the king's son, Azrikam the governor of the house, and Elkanah who was next to the king.
* `2Ch 28:12` Then some of the heads of the children of *_Ephraim_*, Azariah the son of Johanan, Berechiah the son of Meshillemoth, Jehizkiah the son of Shallum, and Amasa the son of Hadlai, stood up against those who came from the war.
* `2Ch 30:1` And Hezekiah sent to all Israel and Judah, and also wrote letters to *_Ephraim_* and Manasseh, that they should come to the house of the LORD at Jerusalem to keep the passover to the LORD God of Israel.
* `2Ch 30:10` So the posts passed from city to city through the country of *_Ephraim_* and Manasseh and even to Zebulun, but they laughed them to scorn and mocked them.
* `2Ch 30:18` For a multitude of the people, even many of *_Ephraim_*, Manasseh, Issachar, and Zebulun, had not cleansed themselves, yet they ate the passover in a way other than it was written. But Hezekiah prayed for them, saying, "May the good LORD pardon everyone
* `2Ch 31:1` Now when all this was finished, all Israel who were present went out to the cities of Judah and broke the images in pieces, cut down the groves, and threw down the high places and the altars out of all Judah, Benjamin, *_Ephraim_*, and Manasseh until they had utterly destroyed them all. Then all the children of Israel each returned to his possession into their own cities.
* `2Ch 34:6` And he did the same in the cities of Manasseh, *_Ephraim_*, Simeon, and even to Naphtali, with their mattocks around.
* `2Ch 34:9` And when they came to Hilkiah the high priest, they delivered the money that was brought into the house of God, which the Levites who kept the doors had collected from the hand of Manasseh and *_Ephraim_*, from all the remnant of Israel, from all Judah and Benjamin, and from the inhabitants of Jerusalem.
* `Neh 8:16` So the people went forth, brought them, and made themselves booths, each upon the roof of his house, in their courts, in the courts of the house of God, in the street of the water-gate, and in the street of the gate of *_Ephraim_*.
* `Neh 12:39` And from above the gate of *_Ephraim_*, above the old gate, above the fish-gate, the tower of Hananeel, and the tower of Meah, even to the sheep-gate. And they stood still in the prison-gate.
* `Psa 60:7` Gilead is mine. And Manasseh is mine. *_Ephraim_* also is the strength of my head. Judah is my lawgiver.
* `Psa 78:9` The children of *_Ephraim_*, being armed and carrying bows, turned back in the day of battle.
* `Psa 78:67` Moreover, he refused the tabernacle of Joseph and did not choose the tribe of *_Ephraim_*,
* `Psa 80:2` Before *_Ephraim_* and Benjamin and Manasseh, stir up your strength and come and save us.
* `Psa 108:8` Gilead is mine. Manasseh is mine. *_Ephraim_* also is the strength of my head. Judah is my lawgiver.
* `Isa 7:2` And it was told to the house of David, saying, "Syria is confederated with *_Ephraim_*." And his heart and the heart of his people shook like trees of the forest shaken by the wind.
* `Isa 7:5` Because Syria, *_Ephraim_*, and the son of Remaliah have taken evil counsel against you, saying,
* `Isa 7:8` For the head of Syria is Damascus, and the head of Damascus is Rezin. And within sixty-five years *_Ephraim_* shall be broken so that it is not a people.
* `Isa 7:9` And the head of *_Ephraim_* is Samaria, and the head of Samaria is Remaliah's son. If you will not believe, surely you shall not be established."'"
* `Isa 7:17` "The LORD will bring upon you, upon your people, and upon your father's house days that have not come since the day that *_Ephraim_* departed from Judah—the king of Assyria."
* `Isa 9:9` And all the people shall know, even *_Ephraim_* and the inhabitant of Samaria, who say in the pride and stoutness of heart,
* `Isa 9:21` Manasseh is against *_Ephraim_*, *_Ephraim_* is against Manasseh, and together they are against Judah. For all this his anger is not turned away, but his hand is still stretched out.
* `Isa 11:13` The envy of *_Ephraim_* shall also depart, and the adversaries of Judah shall be cut off. *_Ephraim_* shall not envy Judah, and Judah shall not distress *_Ephraim_*.
* `Isa 17:3` The fortress shall also cease from *_Ephraim_*, and the kingdom from Damascus, and the remnant of Syria. They shall be like the glory of the children of Israel," says the LORD of hosts.
* `Isa 28:1` Woe to the crown of pride, to the drunkards of *_Ephraim_*, whose glorious beauty is a fading flower, who are on the head of the rich valleys of those who are overcome with wine!
* `Isa 28:3` The crown of pride of the drunkards of *_Ephraim_* shall be trodden under feet.
* `Jer 4:15` For a voice declares from Dan and publishes affliction from mount *_Ephraim_*.
* `Jer 7:15` And I will cast you out of my sight, as I have cast out all your brothers, even all the offspring of *_Ephraim_*.
* `Jer 31:6` For there shall be a day that the watchmen upon the mountains of *_Ephraim_* shall cry, 'Arise, and let us go up to Zion to the LORD our God.'"
* `Jer 31:9` They shall come with weeping, and with supplications I will lead them. I will cause them to walk by the rivers of waters in a straight way, wherein they shall not stumble, for I am a father to Israel, and *_Ephraim_* is my first-born."
* `Jer 31:18` I have surely heard *_Ephraim_* bemoaning himself, saying, 'You have chastised me, and I was chastised, like a bull unaccustomed to the yoke. Turn me, and I shall be turned, for you are the LORD my God.
* `Jer 31:20` Is *_Ephraim_* my dear son? Is he a pleasant child? For since I spoke against him, I earnestly remember him still; therefore, my heart yearns for him. I will surely have mercy upon him," says the LORD.
* `Jer 50:19` And I will bring Israel back to his habitation, and he shall feed on Carmel and Bashan, and his soul shall be satisfied upon mount *_Ephraim_* and Gilead.
* `Ezk 37:16` "Moreover, son of man, take one stick and write upon it, 'For Judah and for the children of Israel his companions.' Then take another stick and write upon it, 'For Joseph, the stick of *_Ephraim_*, and for all the house of Israel his companions.'
* `Ezk 37:19` Say to them, 'Thus says the Lord GOD: "Behold, I will take the stick of Joseph—which is in the hand of *_Ephraim_*—and the tribes of Israel his fellows, and I will put them with him, even with the stick of Judah. And I will make them one stick, and they shall be one in my hand."'
* `Ezk 48:5` And by the border of Manasseh, from the east side to the west side, a portion for *_Ephraim_*.
* `Ezk 48:6` And by the border of *_Ephraim_*, from the east side even to the west side, a portion for Reuben.
* `Hos 4:17` *_Ephraim_* is joined to idols. Leave him alone.
* `Hos 5:3` I know *_Ephraim_*, and Israel is not hid from me. For now, O *_Ephraim_*, you are guilty of lewdness, and Israel is defiled.
* `Hos 5:5` And the pride of Israel testifies to his face; therefore, Israel and *_Ephraim_* shall fall in their iniquity. Judah shall also fall with them.
* `Hos 5:9` *_Ephraim_* shall be desolate in the day of rebuke. Among the tribes of Israel I have made known that which shall surely be.
* `Hos 5:11` *_Ephraim_* is oppressed and broken in judgment because he willingly walked after the commandment.
* `Hos 5:12` Therefore, I will be to *_Ephraim_* as a moth and to the house of Judah as rottenness.
* `Hos 5:13` When *_Ephraim_* saw his sickness and Judah saw his wound, *_Ephraim_* went to the Assyrian and sent to king Jareb. Yet he could not heal you, nor cure you of your wound.
* `Hos 5:14` For I will be to *_Ephraim_* as a lion, and as a young lion to the house of Judah. I, even I, will tear and go away. I will take away, and no one shall rescue him.
* `Hos 6:4` "O *_Ephraim_*, what shall I do to you? O Judah, what shall I do to you? For your goodness is as the morning cloud, and as the early dew it goes away.
* `Hos 6:10` I have seen a horrible thing in the house of Israel. There is the prostitution of *_Ephraim_*, Israel is defiled.
* `Hos 7:1` "When I would have healed Israel, then the iniquity of *_Ephraim_* and the wickedness of Samaria was disclosed, for they commit falsehood. And the thief comes in, and the troop of robbers raids outside.
* `Hos 7:8` *_Ephraim_*, he has mixed himself among the people. *_Ephraim_* is a cake not turned.
* `Hos 7:11` *_Ephraim_* is also like a silly dove without heart. They call to Egypt. They go to Assyria.
* `Hos 8:9` For they have gone up to Assyria, a wild donkey alone by himself. *_Ephraim_* has hired lovers.
* `Hos 8:11` Because *_Ephraim_* has made many altars to sin, altars shall be for him to sin.
* `Hos 9:3` They shall not dwell in the LORD'S land, but *_Ephraim_* shall return to Egypt and they shall eat unclean things in Assyria.
* `Hos 9:8` The watchman of *_Ephraim_* was with my God, but the prophet is a snare of a fowler in all his ways and hatred in the house of his God.
* `Hos 9:11` As for *_Ephraim_*, their glory shall fly away like a bird from the birth, from the womb, and from the conception.
* `Hos 9:13` *_Ephraim_*, as I saw Tyre, is planted in a pleasant place. But *_Ephraim_* shall bring forth his children to the murderer.
* `Hos 9:16` *_Ephraim_* is smitten. Their root is dried up. They shall bear no fruit. Even though they bring forth, yet I will slay even the beloved fruit of their womb."
* `Hos 10:6` It shall also be carried to Assyria for a present to king Jareb. *_Ephraim_* shall receive shame, and Israel shall be ashamed of his own counsel.
* `Hos 10:11` And *_Ephraim_* is as a heifer that is taught and loves to tread out the grain. But I passed over upon her fair neck. I will make *_Ephraim_* to ride. Judah shall plow, and Jacob shall break his clods.
* `Hos 11:3` I taught *_Ephraim_* also to go, taking them by their arms, but they did not know that I healed them.
* `Hos 11:8` How shall I give you up, *_Ephraim_*? How shall I deliver you, Israel? How shall I make you as Admah? How shall I set you as Zeboim? My heart is turned within me. My repentings are kindled together.
* `Hos 11:9` I will not execute the fierceness of my anger. I will not return to destroy *_Ephraim_*, for I am God and not man, the Holy One in the midst of you, and I will not enter into the city.
* `Hos 11:12` *_Ephraim_* encompasses me with lies, and the house of Israel with deceit, but Judah still rules with God and is faithful with the saints.
* `Hos 12:1` *_Ephraim_* feeds on wind and follows after the east wind. He daily multiplies lies and desolation. They make a covenant with the Assyrians, and oil is carried into Egypt.
* `Hos 12:8` And *_Ephraim_* said, "Yet I have become rich. I have found substance for myself. In all my labors they shall find no iniquity in me that is sin."
* `Hos 12:14` *_Ephraim_* provoked him to anger most bitterly; therefore, he will leave his blood upon him, and his Lord will return his reproach to him."
* `Hos 13:1` "When *_Ephraim_* spoke, there was trembling. He exalted himself in Israel. But when he offended in Baal, he died.
* `Hos 13:12` The iniquity of *_Ephraim_* is bound up. His sin is hid.
* `Hos 14:8` *_Ephraim_* shall say, 'What have I to do anymore with idols?' I have heard him and observed him. I am like a green fir-tree. Your fruit is found from me."
* `Oba 1:19` And those of the south shall possess the mountain of Esau, and those of the plain, the Philistines. And they shall possess the fields of *_Ephraim_* and the fields of Samaria. And Benjamin shall possess Gilead.
* `Zch 9:10` And I will cut off the chariot from *_Ephraim_* and the horse from Jerusalem, and the battle-bow shall be cut off. And he shall speak peace to the heathen. And his dominion shall be from sea to sea, and from the river to the ends of the earth.
* `Zch 9:13` When I have bent Judah for me, filled the bow with *_Ephraim_*, and raised up your sons, O Zion, against your sons, O Greece, and made you as the sword of a mighty man.
* `Zch 10:7` And those of *_Ephraim_* shall be like a mighty man, and their heart shall rejoice as through wine. Even their children shall see it and be glad. Their heart shall rejoice in the LORD.
* `Jhn 11:54` Jesus therefore no longer walked openly among the Jews, but went from there to a country near the wilderness, into a city called *_Ephraim_*, and stayed there with his disciples.

_162 verses containing EPHRAIM_

== EPHRAIMITE

* `Jdg 12:5` And the Gileadites took the passages of the Jordan before the Ephraimites. And it was so, that when those Ephraimites who had escaped, said, "Let me go over," that the men of Gilead said to him, "Are you an *_Ephraimite_*?" If he said, "No,"

_1 verse containing EPHRAIMITE_

== EPHRAIMITES

* `Jsh 16:10` And they did not expel the Canaanites who dwelt in Gezer. But the Canaanites dwell among the *_Ephraimites_* to this day and serve under tribute.
* `Jdg 12:4` Then Jephthah collected all the men of Gilead and fought with Ephraim. And the men of Gilead smote Ephraim, because they said, "You Gileadites are fugitives of Ephraim among the *_Ephraimites_* and among the Manassites."
* `Jdg 12:5` And the Gileadites took the passages of the Jordan before the *_Ephraimites_*. And it was so, that when those *_Ephraimites_* who had escaped, said, "Let me go over," that the men of Gilead said to him, "Are you an Ephraimite?" If he said, "No,"
* `Jdg 12:6` Then they said to him, "Now say, 'Shibboleth,'" and he said, "Sibboleth," for he could not frame to pronounce it right. Then they took him and slew him at the passages of the Jordan. And there fell at that time of the *_Ephraimites_* forty-two thousand.

_4 verses containing EPHRAIMITES_

== EPHRATAH

* `Rth 4:11` And all the people who were in the gate and the elders said, "We are witnesses. May the LORD make the woman who has come into your house like Rachel and like Leah, both of whom built the house of Israel. And may you do worthily in *_Ephratah_* and be famous in Beth-lehem.
* `1Ch 2:24` And after Hezron was dead in Caleb-*_ephratah_*, then Abiah, Hezron's wife, bore him Ashur the father of Tekoa.
* `1Ch 2:50` These were the sons of Caleb. The sons of Hur, the first-born of *_Ephratah_*: Shobal the father of Kirjath-jearim,
* `1Ch 4:4` And Penuel the father of Gedor, and Ezer the father of Hushah. These are the sons of Hur, the first-born of *_Ephratah_*, the father of Beth-lehem.
* `Psa 132:6` Behold, we heard of it at *_Ephratah_*. We found it in the fields of Jaar.
* `Mic 5:2` "But you, Beth-lehem *_Ephratah_*, though you are little among the thousands of Judah, yet out of you he shall come forth to me who is to be ruler in Israel, whose goings forth have been from of old, from everlasting."

_6 verses containing EPHRATAH_

== EPHRATH

* `Gen 35:16` And they journeyed from Beth-el. And there was only a little distance to come to *_Ephrath_*, and Rachel travailed and had hard labor.
* `Gen 35:19` And Rachel died and was buried on the way to *_Ephrath_*, which is Beth-lehem.
* `Gen 48:7` And as for me, when I came from Padan, Rachel died beside me in the land of Canaan, on the way when there was only a little distance to come to *_Ephrath_*, and I buried her there on the way of *_Ephrath_* (the same is Beth-lehem)."
* `1Ch 2:19` And when Azubah was dead, Caleb took to him *_Ephrath_* who bore to him Hur,

_4 verses containing EPHRATH_

== EPHRATHITE

* `1Sa 1:1` Now there was a certain man of Ramathaim-zophim, of mount Ephraim, and his name was Elkanah, the son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an *_Ephrathite_*.
* `1Sa 17:12` Now David was the son of that *_Ephrathite_* of Beth-lehem-judah, whose name was Jesse, who had eight sons and was an old man in the days of Saul and aged among men.
* `1Ki 11:26` And Jeroboam the son of Nebat, an *_Ephrathite_* of Zereda, Solomon's servant, whose mother's name was Zeruah, a widow woman, even he raised his hand against the king.

_3 verses containing EPHRATHITE_

== EPHRATHITES

* `Rth 1:2` And the name of the man was Elimelech, the name of his wife Naomi, and the name of his two sons Mahlon and Chilion, *_Ephrathites_* of Beth-lehem-judah. And they came into the country of Moab and continued there.

_1 verse containing EPHRATHITES_

== EPHRON

* `Gen 23:8` And he spoke with them, saying, "If it is your mind that I should bury my dead out of my sight, hear me, and entreat for me to *_Ephron_* the son of Zohar,
* `Gen 23:10` And *_Ephron_* dwelt among the children of Heth. And *_Ephron_* the Hittite answered Abraham in the audience of the children of Heth, of all who entered the gates of his city, saying,
* `Gen 23:13` And he spoke to *_Ephron_* in the audience of the people of the land, saying, "But if you will give it, I pray you, hear me. I will give you money for the field. Take it from me, and I will bury my dead there."
* `Gen 23:14` And *_Ephron_* answered Abraham, saying to him,
* `Gen 23:16` And Abraham listened to *_Ephron_*. And Abraham weighed to *_Ephron_* the silver which he had named in the audience of the sons of Heth, four hundred shekels of silver, current money with the merchant.
* `Gen 23:17` And the field of *_Ephron_*, which was in Machpelah, which was before Mamre, the field and the cave which was in it, and all the trees that were in the field, that were throughout all its borders, were made sure
* `Gen 25:9` And his sons Isaac and Ishmael buried him in the cave of Machpelah, in the field of *_Ephron_* the son of Zohar the Hittite, which is before Mamre,
* `Gen 49:29` And he charged them and said to them, "I am to be gathered to my people. Bury me with my fathers in the cave that is in the field of *_Ephron_* the Hittite,
* `Gen 49:30` In the cave that is in the field of Machpelah, which is before Mamre, in the land of Canaan, which Abraham bought with the field of *_Ephron_* the Hittite as a possession for a burying-place.
* `Gen 50:13` For his sons carried him into the land of Canaan and buried him in the cave of the field of Machpelah near Mamre, which Abraham bought with the field as a possession for a burying-place from *_Ephron_* the Hittite.
* `Jsh 15:9` And the border was drawn from the top of the hill to the fountain of the water of Nephtoah, and went out to the cities of mount *_Ephron_*. And the border was drawn to Baalah, which is Kirjath-jearim.
* `2Ch 13:19` And Abijah pursued Jeroboam and took cities from him: Beth-el with its towns, Jeshanah with its towns, and *_Ephron_* with its towns.

_12 verses containing EPHRON_

== EPICUREANS

* `Act 17:18` Then some philosophers of the *_Epicureans_* and of the Stoics encountered him. And some said, "What will this babbler say?" and others said, "He seems to be a proclaimer of strange gods," because he preached to them Jesus and the resurrection.

_1 verse containing EPICUREANS_

== EPISTLE

* `Act 15:30` So when they were dismissed, they came to Antioch. And when they had convened the multitude, they delivered the *_epistle_*,
* `Act 23:33` When they came to Caesarea and delivered the *_epistle_* to the governor, they also presented Paul before him.
* `Rom 16:22` I, Tertius, who wrote this *_epistle_*, salute you in the Lord.
* `1Co 5:9` I have written to you in this *_epistle_* not to associate with persons guilty of lewdness—
* `2Co 3:2` You are our *_epistle_* written in our hearts, known and read by all men,
* `2Co 3:3` Because you are manifestly declared to be the *_epistle_* of Christ ministered by us, written not with ink, but with the Spirit of the living God, not on tablets of stone, but on fleshly tablets of the heart.
* `2Co 7:8` For though I made you sorry with a letter, I do not repent, though I did repent. For I perceive that the same *_epistle_* has made you sorry, though it was only for a season.
* `Col 4:16` And when this *_epistle_* is read among you, see to it that it also be read in the church of the Laodiceans and that you likewise read the *_epistle_* from Laodicea.
* `1Th 5:27` I charge you by the Lord that this *_epistle_* be read to all the holy brothers.
* `2Th 2:15` Therefore, brothers, stand firm and hold the traditions which you have been taught, whether by word, or our *_epistle_*.
* `2Th 3:14` And if any man does not obey our word by this *_epistle_*, note that man and have no company with him so that he may be ashamed.
* `2Th 3:17` The salutation of Paul with my own hand, which is the token in every *_epistle_*. Thus I write.
* `2Pe 3:1` This, beloved, is the second *_epistle_* I now write to you, in both of which I stir up your pure minds by way of remembrance,

_13 verses containing EPISTLE_

== EPISTLES

* `2Co 3:1` Do we begin again to commend ourselves? Or do we need, as some others, *_epistles_* of commendation to you, or letters of commendation from you.
* `2Pe 3:16` As also in all his *_epistles_*, speaking in them about these things, in which are some things hard to understand, which those who are unlearned and unstable wrest, as they also do the other Scriptures, to their own destruction.

_2 verses containing EPISTLES_

== EQUAL

* `Job 28:17` The gold and the crystal cannot *_equal_* it, and its exchange shall not be for jewels of fine gold.
* `Job 28:19` The topaz of Cush shall not *_equal_* it, neither shall it be valued with pure gold.
* `Psa 17:2` Let my sentence come forth from your presence. Let your eyes behold the things that are *_equal_*.
* `Psa 55:13` But it was you, a man my *_equal_*, my guide, and my acquaintance.
* `Pro 26:7` The legs of the lame are not *_equal_*, and so is a parable in the mouth of fools.
* `Isa 40:25` "To whom then will you compare me, or who is my *_equal_*?" says the Holy One.
* `Isa 46:5` To whom will you compare me and make me *_equal_*, and compare me so that we may be alike?
* `Lam 2:13` [MEM] What thing shall I take to witness for you? What thing shall I compare to you, O daughter of Jerusalem? What shall I *_equal_* to you so that I may comfort you, O virgin daughter of Zion? For your breach is great like the sea. Who can heal you?
* `Ezk 18:25` Yet you say, 'The way of the Lord is not *_equal_*.' Hear now, O house of Israel. Is my way not *_equal_*? Are your ways not unequal?
* `Ezk 18:29` Yet the house of Israel says, 'The way of the Lord is not *_equal_*.' O house of Israel, are my ways not *_equal_*? Are your ways not unequal?
* `Ezk 33:17` "Yet the children of your people say, 'The way of the Lord is not *_equal_*.' But as for them, their way is not *_equal_*.
* `Ezk 33:20` Yet you say, 'The way of the Lord is not *_equal_*.' O house of Israel, I will judge each of you after his ways."
* `Mth 20:12` Saying, 'These last have worked only one hour, and you have made them *_equal_* to us who have borne the burden and heat of the day.'
* `Luk 20:36` Neither can they die anymore, because they are *_equal_* to the angels and are the children of God, being the children of the resurrection.
* `Jhn 5:18` Therefore, the Jews sought the more to kill him because he not only had broken the sabbath, but also said that God was his Father, making himself *_equal_* with God.
* `Col 4:1` Masters, give to your servants that which is just and *_equal_*, knowing that you also have a Master in heaven.
* `Rev 21:16` And the city lies square, and the length is as large as the breadth. And he measured the city with the reed: twelve thousand furlongs. Its length, its breadth, and its height are *_equal_*.

_17 verses containing EQUAL_

== EQUALITY

* `2Co 8:14` But that there may be *_equality_*. Your abundance at this time may be a supply for their need so that their abundance may also be a supply for your need. This is so that there may be *_equality_*,
* `Phl 2:6` Who, being in the form of God, did not deem *_equality_* with God as something to be grasped,

_2 verses containing EQUALITY_

== EQUALLY

* `Exo 36:22` One board had two tenons, *_equally_* distant from one another. He did this for all the boards of the tabernacle.
* `2Pe 1:1` Simon Peter, a servant and an apostle of Jesus Christ, to those who have obtained an *_equally_* precious faith with us through the righteousness of God and our Savior Jesus Christ:

_2 verses containing EQUALLY_

== EQUALS

* `Gal 1:14` And profited in the Jews' religion above many of my *_equals_* in my own nation, being more exceedingly zealous of the traditions of my fathers.

_1 verse containing EQUALS_

== EQUITY

* `Psa 98:9` Before the LORD, for he comes to judge the earth. With righteousness he will judge the world, and the people with *_equity_*.
* `Psa 99:4` The king's strength also loves judgment. You establish *_equity_*. You execute judgment and righteousness in Jacob.
* `Pro 1:3` To receive the instruction of wisdom, justice, judgment, and *_equity_*,
* `Pro 2:9` Then you shall understand righteousness, judgment, *_equity_*, and every good path.
* `Pro 17:26` Also to punish the just is not good, nor to strike princes for *_equity_*.
* `Ecc 2:21` For there is a man whose labor is in wisdom, in knowledge, and in *_equity_*, yet to a man who has not labored in it, he shall leave it for his portion. This also is vanity and a great evil.
* `Isa 11:4` But with righteousness he will judge the poor and reprove with *_equity_* for the meek of the earth. He will smite the earth with the rod of his mouth, and with the breath of his lips he will slay the wicked.
* `Isa 59:14` And judgment is turned away backward, and justice stands afar off. For truth has fallen in the street, and *_equity_* cannot enter.
* `Mic 3:9` Hear this, I pray you, you heads of the house of Jacob and princes of the house of Israel, who abhor judgment and pervert all *_equity_*.
* `Mal 2:6` The law of truth was in his mouth and iniquity was not found in his lips. He walked with me in peace and *_equity_* and turned many away from iniquity.

_10 verses containing EQUITY_

== ER

* `Gen 38:3` And she conceived and bore a son, and he called his name *_Er_*.
* `Gen 38:6` And Judah took a wife for *_Er_* his first-born, whose name was Tamar.
* `Gen 38:7` And *_Er_*, Judah's first-born, was wicked in the sight of the LORD, and the LORD slew him.
* `Gen 46:12` And the sons of Judah: *_Er_*, Onan, Shelah, Pharez, and Zerah, but *_Er_* and Onan died in the land of Canaan. And the sons of Pharez were Hezron and Hamul.
* `Num 26:19` The sons of Judah were *_Er_* and Onan. And *_Er_* and Onan died in the land of Canaan.
* `1Ch 2:3` The sons of Judah: *_Er_*, Onan, and Shelah. These three were born to him by the daughter of Shua the Canaanitess. And *_Er_*, the first-born of Judah, was evil in the sight of the LORD, and he slew him.
* `1Ch 4:21` The sons of Shelah the son of Judah were *_Er_* the father of Lecah, Laadah the father of Mareshah, the families of the house of those who wrought fine linen, of the house of Ashbea,
* `Luk 3:28` Who was the son of Melchi, who was the son of Addi, who was the son of Cosam, who was the son of Elmadam, who was the son of *_Er_*,

_8 verses containing ER_

== ERAN

* `Num 26:36` And these are the sons of Shuthelah: of *_Eran_*, the family of the Eranites.

_1 verse containing ERAN_

== ERANITES

* `Num 26:36` And these are the sons of Shuthelah: of Eran, the family of the *_Eranites_*.

_1 verse containing ERANITES_

== ERASTUS

* `Act 19:22` So he sent into Macedonia two of those who ministered to him, Timothy and *_Erastus_*, but he himself stayed in Asia for a season.
* `Rom 16:23` Gaius, my host and also of the whole church, salutes you. *_Erastus_* the chamberlain of the city salutes you, and also Quartus, a brother.
* `2Ti 4:20` *_Erastus_* stayed at Corinth, but Trophimus I have left sick at Miletum.

_3 verses containing ERASTUS_

== ERECH

* `Gen 10:10` And the beginning of his kingdom was Babel, *_Erech_*, Accad, and Calneh, in the land of Shinar.

_1 verse containing ERECH_

== ERECT

* `1Ch 21:18` Then the angel of the LORD commanded Gad to say to David that David should go up and *_erect_* an altar to the LORD in the threshing-floor of Ornan the Jebusite.
* `Ezr 5:9` Then we asked those elders, and said this to them: 'Who commanded you to build this house and to *_erect_* these walls?'

_2 verses containing ERECT_

== ERECTED

* `Gen 12:7` And the LORD appeared to Abram and said, "To your offspring I will give this land." And there he *_erected_* an altar to the LORD who appeared to him.
* `Gen 12:8` And he departed from there to a mountain on the east of Beth-el and pitched his tent, having Beth-el on the west and Hai on the east. And there he *_erected_* an altar to the LORD and called upon the name of the LORD.
* `Gen 33:20` And he *_erected_* an altar there and called it El-elohe-Israel.
* `Gen 35:7` And he *_erected_* there an altar and called the place El-beth-el because there God appeared to him when he fled from the face of his brother.
* `Num 9:15` And on the day that the tabernacle was *_erected_*, the cloud covered the tabernacle, namely, the tent of the testimony. And at evening, there was upon the tabernacle something like the appearance of fire until the morning.
* `1Ki 16:32` And he *_erected_* an altar for Baal in the house of Baal, which he had built in Samaria.
* `2Ch 3:17` And he *_erected_* the pillars before the temple: one on the right hand and the other on the left. And he called the name of the one on the right hand Jachin and the name of the one on the left Boaz.
* `Ezr 5:11` And thus they returned us answer, saying, 'We are the servants of the God of heaven and earth and build the house that was *_erected_* these many years ago, which a great king of Israel built and set up.

_8 verses containing ERECTED_

== ERI

* `Gen 46:16` And the sons of Gad: Ziphion, Haggai, Shuni, Ezbon, *_Eri_*, Arodi, and Areli.
* `Num 26:16` Of Ozni, the family of the Oznites; of *_Eri_*, the family of the Erites;

_2 verses containing ERI_

== ERITES

* `Num 26:16` Of Ozni, the family of the Oznites; of Eri, the family of the *_Erites_*;

_1 verse containing ERITES_

== ERR

* `2Ch 33:9` So Manasseh made Judah and the inhabitants of Jerusalem to *_err_* and to do worse than the heathen, whom the LORD had destroyed before the children of Israel.
* `Psa 95:10` Forty long years I was grieved with this generation, and said, "It is a people who *_err_* in their heart, and they have not known my ways,"
* `Psa 119:21` You have rebuked the proud who are cursed, who *_err_* from your commandments.
* `Psa 119:110` The wicked have laid a snare for me, yet I did not *_err_* from your precepts.
* `Psa 119:118` You have trodden down all those who *_err_* from your statutes, for their deceit is falsehood.
* `Pro 14:22` Do those who devise evil not *_err_*? But mercy and truth shall be to those who devise good.
* `Pro 19:27` Cease, my son, to hear the instruction that causes you to *_err_* from the words of knowledge.
* `Isa 3:12` As for my people, children are their oppressors and women rule over them. O my people, those who lead you cause you to *_err_* and destroy the way of your paths.
* `Isa 9:16` For the leaders of this people cause them to *_err_*, and those who are led by them are destroyed.
* `Isa 19:14` The LORD has mingled a perverse spirit in the midst of it. And they have caused Egypt to *_err_* in every work of it, as a drunken man staggers in his vomit.
* `Isa 28:7` But they also have erred through wine, and through strong drink are out of the way. The priest and the prophet have erred through strong drink. They are overwhelmed with wine. They are out of the way through strong drink. They *_err_* in vision. They stumble in judgment.
* `Isa 30:28` And his breath is like an overflowing stream, reaching to the midst of the neck, to sift the nations with the sieve of vanity. And a bridle shall be put in the jaws of the people, causing them to *_err_*.
* `Isa 35:8` And a highway shall be there, a road, and it shall be called, The Way of Holiness. The unclean shall not pass over it, but it shall be for those who are way-faring men. And fools shall not *_err_* therein.
* `Isa 63:17` O LORD, why have you made us to *_err_* from your ways and hardened our heart from your fear? Return for your servants' sake, the tribes of your inheritance.
* `Jer 23:13` "And I have seen folly in the prophets of Samaria. They prophesied in Baal and caused my people Israel to *_err_*.
* `Jer 23:32` Behold, I am against those who prophesy false dreams," says the LORD, "who tell them and cause my people to *_err_* by their lies and by their lightness, yet I did not send them nor command them. Therefore, they shall not profit this people at all," says the LORD.
* `Hos 4:12` My people ask counsel from their wooden idols, and their staff declares to them, for the spirit of lewdness has caused them to *_err_*, and they have gone astray from under their God.
* `Amo 2:4` Thus says the LORD: "For three transgressions of Judah, and for four, I will not turn away their punishment, because they have despised the law of the LORD and have not kept his commandments. And their lies caused them to *_err_*, after which their fathers have walked.
* `Mth 22:29` Jesus answered and said to them, "You *_err_*, not knowing the Scriptures, nor the power of God.
* `Mrk 12:24` And Jesus answering, said to them, "Do you not therefore *_err_* because you do not know the Scriptures, neither the power of God?
* `Mrk 12:27` He is not the God of the dead, but the God of the living. You therefore greatly *_err_*."
* `Heb 3:10` Therefore, I was grieved with that generation, and said, 'They always *_err_* in their heart, and they have not known my ways.'
* `Jms 1:16` Do not *_err_*, my beloved brothers.
* `Jms 5:19` Brothers, if any one of you should *_err_* from the truth, and someone should convert him,

_24 verses containing ERR_

== ERRAND

* `Gen 24:33` And there was food set before him to eat. But he said, "I will not eat until I have told my *_errand_*." And he said, "Speak on."
* `Jdg 3:19` But he himself turned back from the quarries that were by Gilgal and said, "I have a secret *_errand_* for you, O king." He said, "Keep silence." And all who stood by him went out from him.
* `2Ki 9:5` And when he came, behold, the captains of the host were sitting, and he said, "I have an *_errand_* to you, O captain." And Jehu said, "To which of us all?" And he said, "To you, O captain."

_3 verses containing ERRAND_

== ERRED

* `Lev 5:18` And he shall bring a ram without blemish out of the flock, with your estimation, for a trespass-offering to the priest. And the priest shall make an atonement for him concerning his ignorance wherein he *_erred_* and did not know it, and he shall be forgiven.
* `Num 15:22` 'And if you have *_erred_* and not observed all these commandments which the LORD has spoken to Moses,
* `1Sa 26:21` Then Saul said, "I have sinned. Return, my son David, for I will no longer do you harm because my soul was precious in your eyes this day. Behold, I have played the fool and have *_erred_* exceedingly."
* `Job 6:24` Teach me, and I will hold my tongue. And cause me to understand in what I have *_erred_*.
* `Job 19:4` And if it is indeed that I have *_erred_*, my error remains with myself.
* `Isa 28:7` But they also have *_erred_* through wine, and through strong drink are out of the way. The priest and the prophet have *_erred_* through strong drink. They are overwhelmed with wine. They are out of the way through strong drink. They err in vision. They stumble in judgment.
* `Isa 29:24` Those who also *_erred_* in spirit shall come to understanding, and those who murmured shall learn doctrine."
* `1Ti 6:10` For the love of money is the root of all evil, which, while some have coveted, they have *_erred_* from the faith and pierced themselves through with many sorrows.
* `1Ti 6:21` Which some, professing, have *_erred_* concerning the faith. Grace be with you. Amen.
* `2Ti 2:18` Who have *_erred_* concerning the truth, saying that the resurrection is past already, and they overthrow the faith of some.

_10 verses containing ERRED_

== ERROR

* `2Sa 6:7` And the anger of the LORD was kindled against Uzzah, and God smote him there for his *_error_*. And there he died by the ark of God.
* `Job 19:4` And if it is indeed that I have erred, my *_error_* remains with myself.
* `Ecc 5:6` Do not allow your mouth to cause your flesh to sin, neither say before the angel that it was an *_error_*. Why should God be angry at your voice and destroy the work of your hands?
* `Ecc 10:5` There is an evil which I have seen under the sun, as an *_error_* which proceeds from the ruler:
* `Isa 32:6` For the vile person will speak villainy, and his heart will work iniquity, to practice hypocrisy and to utter *_error_* against the LORD, to make the soul of the hungry empty, and to cause the drink of the thirsty to fail.
* `Dan 6:4` Then the presidents and princes sought to find occasion against Daniel concerning the kingdom, but they could find no occasion nor fault, because he was faithful, neither was there any *_error_* or fault found in him.
* `Mth 27:64` Therefore, command that the sepulcher be made secure until the third day, lest his disciples come by night and steal him away and say to the people, 'He has risen from the dead.' Thus the last *_error_* will be worse than the first."
* `Rom 1:27` And likewise also, the men, leaving the natural use of the woman, burned in their lust toward one another, men with men working that which is unseemly and receiving in themselves that recompense of their *_error_* which was proper.
* `Jms 5:20` Let him know, that he who converts a sinner from the *_error_* of his way will save a soul from death and will hide a multitude of sins.
* `2Pe 2:18` For when they speak great swelling words of vanity, they allure through the lusts of the flesh, through much wantonness, those who had quite escaped from those who live in *_error_*.
* `2Pe 3:17` You therefore, beloved, seeing you know these things beforehand, beware lest you also, being led away with the *_error_* of the wicked, fall from your own steadfastness.
* `1Jn 4:6` We are of God. He who knows God hears us. He who is not of God does not hear us. By this we know the Spirit of truth and the spirit of *_error_*.
* `Jde 1:11` Woe to them! For they have gone in the way of Cain, have run greedily after the *_error_* of Balaam for reward, and have perished in the gainsaying of Korah.

_13 verses containing ERROR_

== ERRORS

* `Psa 19:12` Who can understand his *_errors_*? Cleanse me from secret faults.
* `Jer 10:15` They are vanity and the work of *_errors_*. In the time of their visitation they shall perish.
* `Jer 51:18` They are vanity, the work of *_errors_*. In the time of their visitation they shall perish.
* `Heb 9:7` But into the second went the high priest alone once every year, not without blood, which he offered for himself and for the *_errors_* of the people.

_4 verses containing ERRORS_

== ERRS

* `Pro 10:17` He is in the way of life who keeps instruction, but he who refuses reproof *_errs_*.
* `Ezk 45:20` And thus you shall do the seventh day of the month for everyone who *_errs_* and for him who is simple. Thus you shall reconcile the house.

_2 verses containing ERRS_

== ESAR-HADDON

* `2Ki 19:37` And it came to pass as he was worshiping in the house of Nisroch his god, that Adrammelech and Sharezer his sons smote him with the sword, and they escaped into the land of Armenia. And *_Esar-haddon_* his son reigned in his stead.
* `Ezr 4:2` They came to Zerubbabel and to the chief of the fathers, and said to them, "Let us build with you, for we seek your God, as you do, and we have sacrificed to him since the days of *_Esar-haddon_* king of Assur, who brought us up here."
* `Isa 37:38` And it came to pass as he was worshiping in the house of Nisroch his god, that Adrammelech and Sharezer his sons smote him with the sword, and they escaped into the land of Armenia. And *_Esar-haddon_* his son reigned in his stead.

_3 verses containing ESAR-HADDON_

== ESAU

* `Gen 25:25` And the first was born red, and the whole of him was like a hairy garment. And they called his name *_Esau_*.
* `Gen 25:26` And after that, his brother was born, and his hand took hold of *_Esau_*'s heel. And his name was called Jacob. And Isaac was sixty years old when she bore them.
* `Gen 25:27` And the boys grew. And *_Esau_* was a skillful hunter, a man of the field, and Jacob was a plain man dwelling in tents.
* `Gen 25:28` And Isaac loved *_Esau_* because he ate his wild game, but Rebekah loved Jacob.
* `Gen 25:29` And Jacob boiled pottage, and *_Esau_* came from the field and he was faint.
* `Gen 25:30` And *_Esau_* said to Jacob, "Feed me, I pray you, with that same red pottage, for I am faint." Therefore, his name was called Edom.
* `Gen 25:32` And *_Esau_* said, "Behold, I am at the point to die, and what profit shall this birth-right bring to me?"
* `Gen 25:34` Then Jacob gave *_Esau_* bread and pottage of lentils, and he ate and drank and rose and went his way. Thus *_Esau_* despised his birth-right.
* `Gen 26:34` And *_Esau_* was forty years old when he took for a wife Judith the daughter of Beeri the Hittite and Bashemath the daughter of Elon the Hittite,
* `Gen 27:1` And it came to pass, that when Isaac was old and his eyes were dim so that he could not see, he called *_Esau_* his eldest son and said to him, "My son." And he said to him, "Behold, here I am."
* `Gen 27:5` And Rebekah heard when Isaac spoke to *_Esau_* his son. And *_Esau_* went to the field to hunt for wild game and to bring it.
* `Gen 27:6` And Rebekah spoke to Jacob her son, saying, "Behold, I heard your father speak to *_Esau_* your brother, saying,
* `Gen 27:11` And Jacob said to Rebekah his mother, "Behold, *_Esau_* my brother is a hairy man, and I am a smooth man.
* `Gen 27:15` And Rebekah took fine clothing of her eldest son *_Esau_*, which was with her in the house, and put it upon Jacob her younger son.
* `Gen 27:19` And Jacob said to his father, "I am *_Esau_* your first-born. I have done according as you told me. Arise, I pray you, sit and eat some of my wild game so that your soul may bless me."
* `Gen 27:21` And Isaac said to Jacob, "Come near, I pray you, so that I may feel you, my son, whether you are my very son *_Esau_* or not."
* `Gen 27:22` And Jacob went near to Isaac his father. And he felt him and said, "The voice is Jacob's voice, but the hands are the hands of *_Esau_*."
* `Gen 27:23` And he did not discern him because his hands were hairy, like his brother *_Esau_*'s hands. So he blessed him.
* `Gen 27:24` And he said, "Are you my very son *_Esau_*?" And he said, "I am."
* `Gen 27:30` And it came to pass as soon as Isaac had made an end of blessing Jacob, and Jacob had scarcely gone out from the presence of Isaac his father, that *_Esau_* his brother came in from his hunting.
* `Gen 27:32` And Isaac his father said to him, "Who are you?" And he said, "I am your son, your first-born, *_Esau_*."
* `Gen 27:34` And when *_Esau_* heard the words of his father, he cried with a great and exceedingly bitter cry and said to his father, "Bless me, even me also, O my father."
* `Gen 27:37` And Isaac answered and said to *_Esau_*, "Behold, I have made him your lord, and all his brothers I have given to him for servants, and with grain and wine I have sustained him. And what shall I do now to you, my son?"
* `Gen 27:38` And *_Esau_* said to his father, "Have you but one blessing, my father? Bless me, even me also, O my father." And *_Esau_* lifted up his voice and wept.
* `Gen 27:41` And *_Esau_* hated Jacob because of the blessing with which his father blessed him. And *_Esau_* said in his heart, "The days of mourning for my father are at hand. Then I will slay my brother Jacob."
* `Gen 27:42` And these words of *_Esau_* her elder son were told to Rebekah. And she sent and called Jacob her younger son and said to him, "Behold, your brother *_Esau_*, as concerning you, comforts himself, purposing to kill you.
* `Gen 28:5` And Isaac sent away Jacob. And he went to Padan-aram, to Laban, son of Bethuel the Syrian, the brother of Rebekah, Jacob's and *_Esau_*'s mother.
* `Gen 28:6` When *_Esau_* saw that Isaac had blessed Jacob and sent him away to Padan-aram to take for himself a wife from there, and that as he blessed him, he gave him a charge, saying, "You shall not take a wife from the daughters of Canaan,"
* `Gen 28:8` And *_Esau_* seeing that the daughters of Canaan did not please Isaac his father,
* `Gen 28:9` Then *_Esau_* went to Ishmael and took, besides the wives which he had, Mahalath the daughter of Ishmael, Abraham's son, the sister of Nebajoth, to be his wife.
* `Gen 32:3` And Jacob sent messengers before him to *_Esau_* his brother, to the land of Seir, the country of Edom.
* `Gen 32:4` And he commanded them, saying, "Thus you shall speak to my lord *_Esau_*: 'Your servant Jacob says thus: "I have sojourned with Laban and stayed there until now.
* `Gen 32:6` And the messengers returned to Jacob, saying, "We came to your brother *_Esau_*, and he is also coming to meet you, and four hundred men are with him."
* `Gen 32:8` And said, "If *_Esau_* comes to one company and smites it, then the other company which is left will escape."
* `Gen 32:11` Deliver me, I pray you, from the hand of my brother, from the hand of *_Esau_*, for I fear him, lest he should come and smite me with the mothers and the children.
* `Gen 32:13` And he lodged there that same night and took from that which came to his hand a present for *_Esau_* his brother:
* `Gen 32:17` And he commanded the foremost, saying, "When *_Esau_* my brother meets you and asks you, saying, 'Whose are you? And where do you go? And whose are these before you?'
* `Gen 32:18` Then you shall say, 'They are your servant Jacob's. It is a present sent to my lord *_Esau_*. And behold he is also behind us.'"
* `Gen 32:19` And likewise he commanded the second, the third, and all who followed the droves, saying, "In this manner you shall speak to *_Esau_* when you find him.
* `Gen 33:1` And Jacob lifted up his eyes and looked, and behold, *_Esau_* came, and with him four hundred men. And he divided the children between Leah, Rachel, and the two women-servants.
* `Gen 33:4` And *_Esau_* ran to meet him, embraced him, fell on his neck, and kissed him, and they wept.
* `Gen 33:9` And *_Esau_* said, "I have enough, my brother. Keep what you have to yourself."
* `Gen 33:15` And *_Esau_* said, "Let me now leave with you some of the people who are with me." And he said, "What need is there? Let me find grace in the sight of my lord."
* `Gen 33:16` So *_Esau_* returned that day on his way to Seir.
* `Gen 35:1` And God said to Jacob, "Arise, go up to Beth-el and dwell there. And make there an altar to God, who appeared to you when you fled from the face of *_Esau_* your brother."
* `Gen 35:29` And Isaac expired and died and was gathered to his people, being old and full of days. And his sons *_Esau_* and Jacob buried him.
* `Gen 36:1` Now these are the generations of *_Esau_*, who is Edom.
* `Gen 36:2` *_Esau_* took his wives from the daughters of Canaan: Adah the daughter of Elon the Hittite; Aholibamah the daughter of Anah, the daughter of Zibeon the Hivite;
* `Gen 36:4` And Adah bore to *_Esau_*, Eliphaz; and Bashemath bore Reuel;
* `Gen 36:5` And Aholibamah bore Jeush, Jaalam, and Korah. These are the sons of *_Esau_* who were born to him in the land of Canaan.
* `Gen 36:6` And *_Esau_* took his wives, his sons, his daughters, all the persons of his house, his livestock, all his beasts, and all his substance which he had acquired in the land of Canaan, and went into the country from the face of his brother Jacob.
* `Gen 36:8` Thus *_Esau_* dwelt in the mountains of Seir. *_Esau_* is Edom.
* `Gen 36:9` And these are the generations of *_Esau_* the father of the Edomites in the mountains of Seir.
* `Gen 36:10` These are the names of *_Esau_*'s sons: Eliphaz the son of Adah the wife of *_Esau_*, and Reuel the son of Bashemath the wife of *_Esau_*.
* `Gen 36:12` And Timna was a concubine to Eliphaz, *_Esau_*'s son, and she bore Amalek to Eliphaz. These are the sons of Adah, *_Esau_*'s wife.
* `Gen 36:13` And these are the sons of Reuel: Nahath, Zerah, Shammah, and Mizzah. These are the sons of Bashemath, *_Esau_*'s wife.
* `Gen 36:14` And these are the sons of Aholibamah, the daughter of Anah, the daughter of Zibeon, *_Esau_*'s wife, and she bore to *_Esau_*, Jeush, Jaalam, and Korah.
* `Gen 36:15` These are the chiefs of the sons of *_Esau_*. The sons of Eliphaz the first-born son of *_Esau_*: chief Teman, chief Omar, chief Zepho, chief Kenaz,
* `Gen 36:17` And these are the sons of Reuel, *_Esau_*'s son: chief Nahath, chief Zerah, chief Shammah, chief Mizzah. These are the chiefs, descendants of Reuel, in the land of Edom. These are the sons of Bashemath, *_Esau_*'s wife.
* `Gen 36:18` And these are the sons of Aholibamah, *_Esau_*'s wife: chief Jeush, chief Jaalam, chief Korah. These are the chiefs, descendants of Aholibamah the daughter of Anah, *_Esau_*'s wife.
* `Gen 36:19` These are the sons of *_Esau_* (who is Edom) and these are their chiefs.
* `Gen 36:40` And these are the names of the chiefs, descendants of *_Esau_*, according to their families, after their places, by their names: chief Timnah, chief Alvah, chief Jetheth,
* `Gen 36:43` Chief Magdiel, and chief Iram. These are the chiefs of Edom, according to their habitations, in the land of their possession. He is *_Esau_* the father of the Edomites.
* `Deu 2:4` And command the people, saying, "You are to pass through the border of your brothers, the children of *_Esau_*, who dwell in Seir, and they will be afraid of you. Therefore, take good heed to yourselves.
* `Deu 2:5` Do not meddle with them, for I will not give you any of their land, not even so much as a foot-breadth, because I have given mount Seir to *_Esau_* for a possession.
* `Deu 2:8` "And when we passed by from our brothers, the children of *_Esau_*, who dwelt in Seir, through the way of the plain from Elath and from Ezion-gaber, we turned and passed by the way of the wilderness of Moab.
* `Deu 2:12` The Horims also dwelt formerly in Seir, but the children of *_Esau_* succeeded them when they had destroyed them from before them and dwelt in their stead, as Israel did to the land of his possession, which the LORD gave to them.)
* `Deu 2:22` As he did to the children of *_Esau_*, who dwelt in Seir when he destroyed the Horims from before them. And they succeeded them and dwelt in their stead even to this day.
* `Deu 2:29` (As the children of *_Esau_* who dwell in Seir and the Moabites who dwell in Ar did to me), until I pass over the Jordan into the land which the LORD our God gives us.'
* `Jsh 24:4` And I gave Jacob and *_Esau_* to Isaac. And I gave mount Seir to *_Esau_* to possess it, but Jacob and his children went down into Egypt.
* `1Ch 1:34` And Abraham begot Isaac. The sons of Isaac: *_Esau_* and Israel.
* `1Ch 1:35` The sons of *_Esau_*: Eliphaz, Reuel, Jeush, Jaalam, and Korah.
* `Jer 49:8` Flee, turn back, dwell deep, O inhabitants of Dedan, for I will bring the calamity of *_Esau_* upon him, the time that I will visit him.
* `Jer 49:10` But I have made *_Esau_* bare, I have uncovered his secret places, and he shall not be able to hide himself. His offspring is laid waste, along with his brothers and his neighbors, and he is no more.
* `Oba 1:6` How the things of *_Esau_* are searched out! How his hidden things are sought!
* `Oba 1:8` Shall I not in that day," says the LORD, "even destroy the wise men out of Edom and understanding out of the mountain of *_Esau_*?
* `Oba 1:9` And your mighty men, O Teman, shall be dismayed, to the end that everyone of the mountain of *_Esau_* may be cut off by slaughter.
* `Oba 1:18` And the house of Jacob shall be a fire, the house of Joseph a flame, and the house of *_Esau_* for stubble, and they shall kindle in them and devour them. And there shall not be any remaining of the house of *_Esau_*." For the LORD has spoken it.
* `Oba 1:19` And those of the south shall possess the mountain of *_Esau_*, and those of the plain, the Philistines. And they shall possess the fields of Ephraim and the fields of Samaria. And Benjamin shall possess Gilead.
* `Oba 1:21` And saviors shall come upon mount Zion to judge the mountain of *_Esau_*, and the kingdom shall be the LORD'S.
* `Mal 1:2` "I have loved you," says the LORD. Yet you say, "In what have you loved us?" "Was *_Esau_* not Jacob's brother?" says the LORD. "Yet I loved Jacob,
* `Mal 1:3` And I hated *_Esau_*, and laid his mountains and his heritage waste for the jackals of the wilderness."
* `Rom 9:13` As it is written, "Jacob I have loved, but *_Esau_* I have hated."
* `Heb 11:20` By faith Isaac blessed Jacob and *_Esau_* concerning things to come.
* `Heb 12:16` Lest there be any fornicator or profane person like *_Esau_*, who sold his birth-right for one morsel of food.

_85 verses containing ESAU_

== ESCAPE

* `Gen 19:17` And it came to pass when they had brought them forth abroad, that he said, "*_Escape_* for your life. Do not look behind you, neither stay in all the plain. *_Escape_* to the mountain, lest you be consumed."
* `Gen 19:19` Behold now, your servant has found grace in your sight, and you have magnified your mercy, which you have shown to me in saving my life. But I cannot *_escape_* to the mountain, lest some evil should take me and I die.
* `Gen 19:20` Behold now, this city is near to flee to and it is a small one. Oh, let me *_escape_* there (Is it not a small one?) and my soul shall live!"
* `Gen 19:22` Hasten, *_escape_* there, for I cannot do anything until you get there." Therefore, the name of the city was called Zoar.
* `Gen 32:8` And said, "If Esau comes to one company and smites it, then the other company which is left will *_escape_*."
* `Jsh 8:22` And the other issued out of the city against them so that they were in the midst of Israel, some on this side and some on that side. And they smote them so that they let none of them remain or *_escape_*.
* `Jdg 3:29` And they slew of Moab at that time about ten thousand men, all lusty and all men of valor, and there did not *_escape_* a man.
* `1Sa 27:1` And David said in his heart, "I shall now perish one day by the hand of Saul. There is nothing better for me than that I should speedily *_escape_* into the land of the Philistines. And Saul will despair of seeking for me anymore in any border of Israel, and I shall *_escape_* from his hand."
* `1Sa 30:17` And David smote them from the twilight even to the evening of the next day. And there did not *_escape_* a man of them, except four hundred young men, who rode upon camels and fled.
* `2Sa 15:14` And David said to all his servants who were with him at Jerusalem, "Arise and let us flee, or else we shall not *_escape_* from Absalom. Make speed to depart, lest he should overtake us suddenly and bring evil upon us and smite the city with the edge of the sword."
* `2Sa 20:6` And David said to Abishai, "Now Sheba the son of Bichri shall do us more harm than Absalom did. Take your lord's servants and pursue him, lest he get for himself fortified cities and *_escape_* us."
* `1Ki 18:40` And Elijah said to them, "Take the prophets of Baal. Let not one of them *_escape_*." And they took them. And Elijah brought them down to the brook Kishon and slew them there.
* `2Ki 9:15` But king Joram had returned to be healed in Jezreel of the wounds which the Syrians had given him when he fought with Hazael king of Syria.) And Jehu said, "If this is how you would have it, then let no one go forth nor *_escape_* from the city to go to tell it in Jezreel."
* `2Ki 10:24` And when they went in to offer sacrifices and burnt-offerings, Jehu appointed eighty men outside and said, "If any of the men whom I have brought into your hands *_escape_*, he who lets him go, his life shall be for the life of him."
* `2Ki 19:31` For out of Jerusalem a remnant shall go forth, and out of mount Zion those who *_escape_*. The zeal of the LORD of hosts shall do this.
* `Ezr 9:8` And now for a brief moment, grace has been shown from the LORD our God, to leave us a remnant to *_escape_* and to give us a nail in his holy place, so that our God may lighten our eyes and give us a little reviving in our bondage.
* `Est 4:13` Then Mordecai commanded to answer Esther, "Do not think to yourself that you shall *_escape_* in the king's house more than all the Jews.
* `Job 11:20` But the eyes of the wicked shall fail. They shall not *_escape_*. Their hope shall be the expiration of the breath."
* `Psa 55:8` "I would hasten my *_escape_* from the windy storm and tempest."
* `Psa 56:7` Shall they *_escape_* by iniquity? In your anger cast down the people, O God.
* `Psa 71:2` Deliver me in your righteousness and cause me to *_escape_*. Incline your ear to me and save me.
* `Psa 141:10` Let the wicked fall into their own nets while I *_escape_*.
* `Pro 19:5` A false witness shall not be unpunished, and he who speaks lies shall not *_escape_*.
* `Ecc 7:18` It is good that you should take hold of this, and also do not withdraw your hand from this, for he who fears God shall *_escape_* from them all.
* `Ecc 7:26` And I find more bitter than death the woman whose heart is snares and nets, and her hands as bonds. Whoever pleases God shall *_escape_* from her, but the sinner shall be taken by her.
* `Isa 20:6` And the inhabitant of this coastland shall say in that day, 'Behold, such is our expectation where we flee for help to be delivered from the king of Assyria. And how shall we *_escape_*?'"
* `Isa 37:32` For out of Jerusalem a remnant shall go forth, and out of mount Zion those who *_escape_*. The zeal of the LORD of hosts will do this."'
* `Isa 66:19` And I will set a sign among them, and I will send those who *_escape_* of them to the nations—to Tarshish, Pul, and Lud, who draw the bow, to Tubal, to Javan, and to the coastlands afar off—who have not heard my fame, neither have seen my glory. And they shall declare my glory among the Gentiles.
* `Jer 11:11` Therefore, thus says the LORD: "Behold, I will bring evil upon them which they shall not be able to *_escape_*. And though they shall cry to me, I will not listen to them.
* `Jer 25:35` And the shepherds shall have no way to flee, nor the principal of the flock to *_escape_*.
* `Jer 32:4` And Zedekiah king of Judah shall not *_escape_* from the hand of the Chaldeans, but shall surely be delivered into the hand of the king of Babylon and shall speak with him mouth to mouth, and his eyes shall behold his eyes.
* `Jer 34:3` And you shall not *_escape_* from his hand, but shall surely be taken and delivered into his hand. And your eyes shall behold the eyes of the king of Babylon, and he shall speak with you mouth to mouth, and you shall go to Babylon.'"'
* `Jer 38:18` But if you will not go forth to the king of Babylon's princes, then this city shall be given into the hand of the Chaldeans, and they shall burn it with fire, and you shall not *_escape_* from their hand.'"
* `Jer 38:23` 'So they shall bring out all your wives and your children to the Chaldeans. And you shall not *_escape_* out of their hand, but shall be taken by the hand of the king of Babylon, and you shall cause this city to be burned with fire.'"
* `Jer 42:17` Thus it shall be with all the men who set their faces to go into Egypt to sojourn there. They shall die by the sword, by the famine, and by the pestilence. And none of them shall remain or *_escape_* from the evil that I will bring upon them."'
* `Jer 44:14` So that none of the remnant of Judah who have gone into the land of Egypt to sojourn there shall *_escape_* or remain to return into the land of Judah, to which they have a desire to return to dwell there. For none shall return but those who *_escape_*.'"
* `Jer 44:28` Yet a small number who *_escape_* the sword shall return from the land of Egypt into the land of Judah, and all the remnant of Judah who have gone into the land of Egypt to sojourn there shall know whose words shall stand—mine, or theirs.
* `Jer 46:6` Do not let the swift flee away nor the mighty man *_escape_*! They shall stumble and fall toward the north by the Euphrates River.
* `Jer 48:8` And the destroyer shall come upon every city, and no city shall *_escape_*. The valley shall also perish, and the plain shall be destroyed, as the LORD has spoken.
* `Jer 50:28` The voice of those who flee and *_escape_* from the land of Babylon declares in Zion the vengeance of the LORD our God, the vengeance of his temple.
* `Jer 50:29` "Call together the archers against Babylon. All you who bend the bow, encamp against it on every side. Let none thereof *_escape_*. Recompense her according to her work. According to all that she has done, do to her, for she has been proud against the LORD, against the Holy One of Israel.
* `Ezk 6:8` "Yet I will leave a remnant so that you may have some who shall *_escape_* the sword among the nations when you are scattered through the countries.
* `Ezk 6:9` And those of you who *_escape_* shall remember me among the nations where they shall be carried captives, because I am broken with their apostate heart, which has departed from me, and with their eyes which go astray after their idols. And they shall loathe themselves for the evils which they have committed in all their abominations.
* `Ezk 7:16` But those of them who *_escape_* shall *_escape_* and be on the mountains like doves of the valleys, all of them mourning, each for his iniquity.
* `Ezk 17:15` But he rebelled against him in sending his ambassadors into Egypt so that they might give him horses and many people. Shall he prosper? Shall he *_escape_* who does such things? Or shall he break the covenant and be delivered?
* `Ezk 17:18` Seeing that he despised the oath by breaking the covenant, when behold, he had given his hand and has done all these things, he shall not *_escape_*.'"
* `Dan 4:14` He cried aloud, and said thus: "Hew down the tree and cut off its branches, shake off its leaves and scatter its fruit. Let the beasts *_escape_* from under it and the birds from its branches.
* `Dan 11:41` He shall also enter into the glorious land, and many countries shall be overthrown, but these shall *_escape_* out of his hand: Edom, Moab, and the chief of the children of Ammon.
* `Dan 11:42` He shall stretch forth his hand also upon the countries, and the land of Egypt shall not *_escape_*.
* `Joe 2:3` A fire devours before them, and behind them a flame burns. The land is as the garden of Eden before them, and behind them a desolate wilderness, and nothing shall *_escape_* them.
* `Mth 23:33` You serpents, you generation of vipers, how can you *_escape_* the condemnation of hell?
* `Luk 21:36` Therefore, be watchful all the time, praying that you may be accounted worthy to *_escape_* all these things that shall come to pass and to stand before the Son of man."
* `Act 27:42` And the soldiers' counsel was to kill the prisoners, lest any of them should swim out and *_escape_*.
* `Rom 2:3` And do you think this, O man, who judges those who do such things and does the same, that you shall *_escape_* the judgment of God?
* `1Co 10:13` There has no temptation taken you but such as is common to man. But God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make a way to *_escape_* so that you may be able to bear it.
* `1Th 5:3` For when they say, "Peace and safety," then sudden destruction comes upon them, as travail upon a woman with child, and they shall not *_escape_*.
* `Heb 2:3` How shall we *_escape_* if we neglect so great a salvation? It was spoken at the first by the Lord and was confirmed to us by those who heard him,
* `Heb 12:25` See that you do not refuse him who speaks. For if those did not *_escape_* who refused him who spoke on earth, much more we shall not *_escape_* if we turn away from him who speaks from heaven.

_58 verses containing ESCAPE_

== ESCAPED

* `Gen 14:13` And someone who had *_escaped_* came and told Abram the Hebrew. For he dwelt in the plain of Mamre the Amorite, brother of Eshcol, and brother of Aner, and these were confederates with Abram.
* `Exo 10:5` And they shall cover the face of the earth so that no one will be able to see the earth. And they shall eat the remnant of that which has *_escaped_*, which remains to you from the hail, and shall eat every tree which grows for you out of the field.
* `Deu 23:15` "You shall not deliver to his master the servant who has *_escaped_* from his master to you.
* `Jdg 3:26` And Ehud *_escaped_* while they waited and passed beyond the quarries and *_escaped_* to Seirath.
* `Jdg 12:5` And the Gileadites took the passages of the Jordan before the Ephraimites. And it was so, that when those Ephraimites who had *_escaped_*, said, "Let me go over," that the men of Gilead said to him, "Are you an Ephraimite?" If he said, "No,"
* `1Sa 14:41` Therefore, Saul said to the LORD God of Israel, "Give a perfect lot." And Saul and Jonathan were taken, but the people *_escaped_*.
* `1Sa 18:11` And Saul cast the javelin, for he said, "I will smite David even to the wall." And David *_escaped_* from his presence twice.
* `1Sa 19:10` And Saul sought to smite David even to the wall with the javelin, but he slipped away from Saul's presence as he drove the javelin into the wall. And David fled and *_escaped_* that night.
* `1Sa 19:12` So Michal let David down through a window, and he went, fled, and *_escaped_*.
* `1Sa 19:17` And Saul said to Michal, "Why have you deceived me like this and sent away my enemy so that he has *_escaped_*?" And Michal answered Saul, "He said to me, 'Let me go. Why should I kill you?'"
* `1Sa 19:18` So David fled and *_escaped_*, and he came to Samuel at Ramah and told him all that Saul had done to him. And he and Samuel went and dwelt in Naioth.
* `1Sa 22:1` David therefore departed from there and *_escaped_* to the cave of Adullam. And when his brothers and all his father's house heard it, they went down there to him.
* `1Sa 22:20` And one of the sons of Ahimelech the son of Ahitub, named Abiathar, *_escaped_* and fled after David.
* `1Sa 23:13` Then David and his men who were about six hundred arose and departed from Keilah and went wherever they could go. And it was told to Saul that David had *_escaped_* from Keilah, and he forbore to go forth.
* `2Sa 1:3` And David said to him, "From where did you come?" And he said to him, "Out of the camp of Israel I have *_escaped_*."
* `2Sa 4:6` And they came there into the midst of the house, as though they would have fetched wheat, and they smote him under the fifth rib. And Rechab and Baanah his brother *_escaped_*.
* `1Ki 20:20` And they each slew his man. And the Syrians fled, and Israel pursued them, but Ben-hadad the king of Syria *_escaped_* on a horse with the horsemen.
* `2Ki 19:30` And the remnant of the house of Judah who have *_escaped_* shall again take root downward and bear fruit upward.
* `2Ki 19:37` And it came to pass as he was worshiping in the house of Nisroch his god, that Adrammelech and Sharezer his sons smote him with the sword, and they *_escaped_* into the land of Armenia. And Esar-haddon his son reigned in his stead.
* `1Ch 4:43` And they smote the rest of the Amalekites who had *_escaped_* and have dwelt there to this day.
* `2Ch 16:7` And at that time Hanani the seer came to Asa king of Judah and said to him, "Because you have relied on the king of Syria and have not relied on the LORD your God, therefore the host of the king of Syria has *_escaped_* out of your hand.
* `2Ch 20:24` And when Judah came toward the watch-tower in the wilderness, they looked to the multitude, and behold, they were dead bodies fallen to the earth and no one *_escaped_*.
* `2Ch 30:6` So the posts went with the letters from the king and his princes throughout all Israel and Judah, and according to the commandment of the king, saying, "Children of Israel, turn back to the LORD God of Abraham, Isaac, and Israel, and he will return to the remnant of you who have *_escaped_* from the hand of the kings of Assyria.
* `2Ch 36:20` And those who had *_escaped_* from the sword he carried away to Babylon, where they were servants to him and his sons until the reign of the kingdom of Persia,
* `Ezr 9:15` O LORD, God of Israel, you are righteous, for we are left a remnant that has *_escaped_*. Behold, we are before you in our trespasses, for we cannot stand before you because of this."
* `Neh 1:2` That Hanani, one of my brothers, came—he and some men of Judah. And I asked them concerning the Jews who had *_escaped_*, who were left of the captivity, and concerning Jerusalem.
* `Job 1:15` And the Sabeans fell upon them and took them away. They have even slain the servants with the edge of the sword, and only I alone have *_escaped_* to tell you."
* `Job 1:16` While he was still speaking, another also came, saying, "The fire of God has fallen from heaven and has burned up the sheep and the servants and consumed them, and only I have *_escaped_* alone to tell you."
* `Job 1:17` While he was still speaking, another also came, saying, "The Chaldeans made three bands and fell upon the camels and have carried them away. They have even slain the servants with the edge of the sword, and only I alone have *_escaped_* to tell you."
* `Job 1:19` And behold, there came a great wind from the wilderness and smote the four corners of the house, and it fell upon the young men, and they are dead, and only I alone have *_escaped_* to tell you."
* `Job 19:20` My bone cleaves to my skin and to my flesh, and I have *_escaped_* with the skin of my teeth.
* `Psa 124:7` Our soul has *_escaped_* like a bird out of the snare of the fowlers. The snare is broken, and we have *_escaped_*.
* `Isa 4:2` In that day the Branch of the LORD shall be beautiful and glorious, and the fruit of the earth shall be for beauty and glory for those of Israel who have *_escaped_*.
* `Isa 10:20` And it shall come to pass in that day, that the remnant of Israel and those who have *_escaped_* of the house of Jacob shall no longer again lean upon him who smote them, but shall lean upon the LORD, the Holy One of Israel, in truth.
* `Isa 37:31` And the remnant of the house of Judah who have *_escaped_* shall again take root downward and bear fruit upward.
* `Isa 37:38` And it came to pass as he was worshiping in the house of Nisroch his god, that Adrammelech and Sharezer his sons smote him with the sword, and they *_escaped_* into the land of Armenia. And Esar-haddon his son reigned in his stead.
* `Isa 45:20` Assemble yourselves and come. Draw near together, you who have *_escaped_* of the nations. They have no knowledge who set up the wood of their engraved image and pray to a god that cannot save.
* `Jer 41:15` But Ishmael the son of Nethaniah *_escaped_* from Johanan with eight men and went to the Ammonites.
* `Jer 51:50` You who have *_escaped_* the sword, go away, do not stand still. Remember the LORD afar off and let Jerusalem come into your mind.
* `Lam 2:22` [TAV] You have called, as in the day of a solemn assembly, my terrors on every side. And in the day of the LORD'S anger no one *_escaped_* or remained. Those whom I have swaddled and brought up, my enemy has consumed.
* `Ezk 24:27` In that day your mouth shall be opened to him who has *_escaped_*, and you shall speak and no longer be mute. And you shall be a sign to them. And they shall know that I am the LORD.'"
* `Ezk 33:21` And it came to pass in the twelfth year of our captivity, in the tenth month, on the fifth day of the month, that someone who had *_escaped_* out of Jerusalem came to me, saying, "The city is smitten."
* `Ezk 33:22` Now the hand of the LORD was upon me in the evening before he who had *_escaped_* came, and he had opened my mouth before he came to me in the morning. And my mouth was opened and I was no longer mute.
* `Oba 1:14` Neither should you have stood in the cross-way to cut off those of his who *_escaped_*, neither should you have delivered up those of his who remained in the day of distress.
* `Jhn 10:39` Therefore, they sought again to take him, but he *_escaped_* from their hand.
* `Act 27:44` And the rest, some on boards and some on broken pieces of the ship. And so it came to pass, that they all *_escaped_* safely to land.
* `Act 28:1` And when they had *_escaped_*, they knew that the island was called Melita.
* `Act 28:4` And when the barbarians saw the animal hang on his hand, they said among themselves, "No doubt this man is a murderer, whom, though he has *_escaped_* the sea, yet vengeance does not allow to live."
* `2Co 11:33` And through a window in a basket I was let down by the wall and *_escaped_* his hands.
* `Heb 11:34` Quenched the violence of fire, *_escaped_* the edge of the sword, out of weakness were made strong, became valiant in fight, and turned to flight the armies of the foreigners.
* `2Pe 1:4` Through which exceedingly great and precious promises are given to us, so that by these you might be partakers of the divine nature, having *_escaped_* the corruption that is in the world through lust.
* `2Pe 2:18` For when they speak great swelling words of vanity, they allure through the lusts of the flesh, through much wantonness, those who had quite *_escaped_* from those who live in error.
* `2Pe 2:20` For if, after they have *_escaped_* the pollutions of the world through the knowledge of the Lord and Savior Jesus Christ, they are again entangled in them and overcome, the latter end is worse with them than the beginning.

_53 verses containing ESCAPED_

== ESCAPES

* `1Ki 19:17` And it shall come to pass, that he who *_escapes_* the sword of Hazael, Jehu shall slay. And he who *_escapes_* from the sword of Jehu, Elisha shall slay.
* `Isa 15:9` For the waters of Dimon shall be full of blood, for I will bring more upon Dimon, lions upon him who *_escapes_* of Moab and upon the remnant of the land.
* `Jer 48:19` O inhabitant of Aroer, stand by the way and watch. Ask him who flees and her who *_escapes_*, and say, 'What has been done?'
* `Ezk 24:26` That he who *_escapes_* in that day shall come to you to cause you to hear it with your ears?
* `Amo 9:1` I saw the Lord standing upon the altar, and he said, "Smite the lintel of the door, so that the posts may shake. Cut them in the head, all of them. I will slay the last of them with the sword. He who flees of them shall not flee away, and he who *_escapes_* of them shall not be delivered.

_5 verses containing ESCAPES_

== ESCAPING

* `Ezr 9:14` Should we again break your commandments and intermarry with the people of these abominations? Would you not be angry with us until you had consumed us so that there should be no remnant nor *_escaping_*?

_1 verse containing ESCAPING_

== ESEK

* `Gen 26:20` And the herdsmen of Gerar contended with Isaac's herdsmen, saying, "The water is ours." And he called the name of the well *_Esek_* because they strove with him.

_1 verse containing ESEK_

== ESH-BAAL

* `1Ch 8:33` And Ner begot Kish, Kish begot Saul, and Saul begot Jonathan, Malchi-shua, Abinadab, and *_Esh-baal_*.
* `1Ch 9:39` And Ner begot Kish, Kish begot Saul, and Saul begot Jonathan, Malchi-shua, Abinadab, and *_Esh-baal_*.

_2 verses containing ESH-BAAL_

== ESHBAN

* `Gen 36:26` And these are the children of Dishon: Hemdan, *_Eshban_*, Ithran, and Cheran.
* `1Ch 1:41` The son of Anah: Dishon. And the sons of Dishon: Amram, *_Eshban_*, Ithran, and Cheran.

_2 verses containing ESHBAN_

== ESHCOL

* `Gen 14:13` And someone who had escaped came and told Abram the Hebrew. For he dwelt in the plain of Mamre the Amorite, brother of *_Eshcol_*, and brother of Aner, and these were confederates with Abram.
* `Gen 14:24` Except that which the young men have eaten and the portion of the men who went with me: Aner, *_Eshcol_*, and Mamre. Let them take their portion."
* `Num 13:23` And they came to the brook of *_Eshcol_* and cut down from there a branch with one cluster of grapes, and they bore it between two upon a staff, and they brought some of the pomegranates and some of the figs.
* `Num 13:24` The place was called the Brook of *_Eshcol_* because of the cluster of grapes which the children of Israel cut down from there.
* `Num 32:9` For when they went up to the valley of *_Eshcol_* and saw the land, they discouraged the heart of the children of Israel so that they should not go into the land which the LORD had given them.
* `Deu 1:24` And they turned and ascended the mountain and came to the valley of *_Eshcol_* and explored it.

_6 verses containing ESHCOL_

== ESHEAN

* `Jsh 15:52` Arab, Dumah, *_Eshean_*,

_1 verse containing ESHEAN_

== ESHEK

* `1Ch 8:39` And the sons of *_Eshek_* his brother were Ulam his first-born, Jehush the second, and Eliphelet the third.

_1 verse containing ESHEK_

== ESHKALONITES

* `Jsh 13:3` From Sihor, which is before Egypt, even to the borders of Ekron northward, which is counted to the Canaanite; five lords of the Philistines, the Gazathites, and the Ashdothites, the *_Eshkalonites_*, the Gittites, and the Ekronites; also the Avites,

_1 verse containing ESHKALONITES_

== ESHTAOL

* `Jsh 15:33` And in the valley, *_Eshtaol_*, Zoreah, Ashnah,
* `Jsh 19:41` And the border of their inheritance was Zorah, *_Eshtaol_*, Ir-shemesh,
* `Jdg 13:25` And the Spirit of the LORD began to move him at times in the camp of Dan, between Zorah and *_Eshtaol_*.
* `Jdg 16:31` Then his brothers and all the house of his father came down, took him, brought him up, and buried him between Zorah and *_Eshtaol_* in the burying-place of Manoah his father. And he judged Israel for twenty years.
* `Jdg 18:2` And the children of Dan sent from their family five men from their borders, men of valor, from Zorah and from *_Eshtaol_*, to explore the land and to search it. And they said to them, "Go, search the land." When they came to mount Ephraim, to the house of Micah, they lodged there.
* `Jdg 18:8` And they came to their brothers at Zorah and *_Eshtaol_*, and their brothers said to them, "What do you say?"
* `Jdg 18:11` And there went from there of the family of the Danites, out of Zorah and out of *_Eshtaol_*, six hundred men appointed with weapons of war.

_7 verses containing ESHTAOL_

== ESHTAULITES

* `1Ch 2:53` And the families of Kirjath-jearim: the Ithrites, the Puhites, the Shumathites, and the Mishraites. From them came the Zereathites and the *_Eshtaulites_*.

_1 verse containing ESHTAULITES_

== ESHTEMOA

* `Jsh 21:14` Jattir with its suburbs, *_Eshtemoa_* with its suburbs,
* `1Sa 30:28` To those who were in Aroer, to those who were in Siphmoth, to those who were in *_Eshtemoa_*,
* `1Ch 4:17` And the sons of Ezra were Jethur, Mered, Epher, and Jalon. Mered took a wife and she bore Miriam, Shammai, and Ishbah the father of *_Eshtemoa_*.
* `1Ch 4:19` And the sons of his wife Hodiah the sister of Naham: the father of Keilah the Garmite, and *_Eshtemoa_* the Maachathite.
* `1Ch 6:57` And to the sons of Aaron they gave the cities of Judah, namely, Hebron (the city of refuge), Libnah with its suburbs, Jattir, *_Eshtemoa_* with its suburbs,

_5 verses containing ESHTEMOA_

== ESHTEMOH

* `Jsh 15:50` Anab, *_Eshtemoh_*, Anim,

_1 verse containing ESHTEMOH_

== ESHTON

* `1Ch 4:11` And Chelub the brother of Shuah begot Mehir, who was the father of *_Eshton_*.
* `1Ch 4:12` And *_Eshton_* begot Beth-rapha, Paseah, and Tehinnah the father of Ir-nahash. These are the men of Rechah.

_2 verses containing ESHTON_

== ESLI

* `Luk 3:25` Who was the son of Mattathias, who was the son of Amos, who was the son of Nahum, who was the son of *_Esli_*, who was the son of Naggai,

_1 verse containing ESLI_

