# These lists contain the word list file names for each letter of the alphabet.

a_list = ["aaron - accepts", "access - admonition", "adna - ahban", "ahead - almug", "aloes - anathoth", "ancestors - appetite", "apphia - around", "arpad - assos", "assuage - azzur"]
b_list = ["baal - baptizing", "bar - becoming", "bed - benches", "bend - bethul", "betonim - blaze", "bleating - bounty", "bow - broom", "broth - by-word"]
c_list = ["cabon - carvings", "case - charming", "chase - chozeba", "christ - clusters", "cnidus - compete", "complain - consenting", "consider - cormorant", "corn - crafty", "crag - cyrus"]
d_list = ["dabareh - debts", "decapolis - delivery", "delusion - devises", "devoted - discuss", "disdained - dizahab", "doctrine - drought", "drove - dysentery"]
e_list = ["each - eldest", "elead - emorite", "empire - enough", "enraged - esli", "especially - examples", "exceed - ezri"]
f_list = ["fables - feathers", "fed - filthy", "finally - foams", "fodder - forsook", "fort - fury"]
g_list = ["gaal - genubath", "gera - glittering", "gloom - gray-headed", "great - gutters"]
h_list = ["ha - hanes", "hang - hasupha", "hatach - hedges", "heed - hezronites", "hid - honers", "hoods - howlings", "hubs - hyssop"]
i_list = ["ibex - incurable", "indebted - intruding", "invade - izri"]
j_list = ["jaakobah - jaws", "jazer - jerushah", "jesaiah - joktheel", "jonadab - juttah"]
k_list = ["kab - kinds", "king - kushaiah"]
l_list = ["laadah - lazarus", "lead - licks", "lid - lobe", "lock - lystra"]
m_list = ["maacah - mamre", "man - mazzaroth", "me-jarkon - mephibosheth", "merab - millstones", "mina - molten", "moment - mouths", "movable - mystery"]
n_list = ["naam - negligent", "nehelamite - nodab", "nogah - nymphas"]
o_list = ["oak - olympas", "omar - othniel", "ought - oznites"]
p_list = ["paarai - parvaim", "pas-dammim - peor", "perazim - pestle", "peter - pity", "place - pontus", "pool - preparing", "presbytery - prolongs", "promise - pruning-hooks", "psalm - putting"]
q_list = ["quadrans - quivered"]
r_list = ["raamah - razor", "reach - refuses", "regard - rent", "repaid - returns", "reu - rizpah", "road - ruth"]
s_list = ["sabachthani - sarsechim", "sat - scythian", "sea - senuah", "seorim - shalmaneser", "shama - shelumiel", "shem - shiza", "shoa - sidonians", "siege - sivan", "six - smyrna", "snail - sotai", "sought - spouses", "sprang - stirs", "stock - stump", "suah - supreme", "sur - syrophenician"]
t_list = ["taanach - teeth", "tehaphnehes - thanksgivings", "theater - thousands", "thread - toah", "tob - traversing", "treacherous - truth", "try - tyre"]
u_list = ["ucal - unruly", "unsavory - uzzielites"]
v_list = ["vagabond - vexed", "vial - vultures"]
w_list = ["wafer - waves", "wax - whose", "why - wolves", "woman - wrung"]
x_list = [""]
y_list = ["yah - youths"]
z_list = ["zaanaim - zeruiah", "zetham - zuzims"]
