= SHAMA - SHELUMIEL
:toc:

== SHAMA

* `1Ch 11:44` Uzzia the Ashterathite, *_Shama_* and Jehiel the sons of Hothan the Aroerite,

_1 verse containing SHAMA_

== SHAMARIAH

* `2Ch 11:19` Who bore him children: Jeush, *_Shamariah_*, and Zaham.

_1 verse containing SHAMARIAH_

== SHAME

* `Exo 32:25` And when Moses saw that the people were naked (for Aaron had made them naked to their *_shame_* among their enemies),
* `Jdg 18:7` Then the five men departed and came to Laish and saw the people who were in it, how they dwelt carelessly after the manner of the Zidonians, quiet and secure. And there was no magistrate in the land who might put them to *_shame_* in anything. And they were far from the Zidonians and had no business with any man.
* `1Sa 20:30` Then Saul's anger was kindled against Jonathan and he said to him, "You son of the perverse rebellious woman, do I not know that you have chosen the son of Jesse to your own *_shame_* and to the *_shame_* of your mother's nakedness?
* `1Sa 20:34` So Jonathan arose from the table in fierce anger and ate no food on the second day of the month, for he was grieved for David because his father had done him *_shame_*.
* `2Sa 13:13` And I, where shall I cause my *_shame_* to go? And as for you, you will be as one of the fools in Israel. Now therefore, I pray you, speak to the king, for he will not withhold me from you."
* `2Ch 32:21` And the LORD sent an angel who cut off all the mighty men of valor and the leaders and captains in the camp of the king of Assyria. So he returned with *_shame_* of face to his own land. And when he had come into the house of his god, those who came forth from his own body slew him there with the sword.
* `Job 8:22` Those who hate you shall be clothed with *_shame_*. And the dwelling place of the wicked shall come to nothing."
* `Job 10:15` If I am wicked, woe to me. And if I am righteous, yet I will not lift up my head. I am full of *_shame_*; therefore, see my affliction.
* `Psa 4:2` O sons of men, how long will you turn my glory into *_shame_*? How long will you love vanity and seek after falsehood? [Selah.]
* `Psa 35:4` Let them be confounded and put to *_shame_* who seek after my soul. Let them be turned back and brought to *_shame_* who devise my hurt.
* `Psa 35:26` Let them be ashamed and confounded together who rejoice at my hurt. Let them be clothed with *_shame_* and dishonor who magnify themselves against me.
* `Psa 40:14` Let them be ashamed and confounded together who seek after my soul to destroy it. Let them be driven backward and put to *_shame_* who wish me evil.
* `Psa 40:15` Let them be desolate by reason of their *_shame_* who say to me, "Aha, aha."
* `Psa 44:7` But you have saved us from our enemies and have put them to *_shame_* who hated us.
* `Psa 44:9` But you have cast off and put us to *_shame_* and do not go forth with our armies.
* `Psa 44:15` My disgrace is continually before me, and the *_shame_* of my face has covered me,
* `Psa 53:5` There they were in great fear, where no fear was, for God has scattered the bones of him who encamps against you. You have put them to *_shame_* because God has despised them.
* `Psa 69:7` Because for your sake I have borne reproach. *_Shame_* has covered my face.
* `Psa 69:19` You have known my reproach, my *_shame_*, and my dishonor. My adversaries are all before you.
* `Psa 70:2` Let them be ashamed and confounded who seek after my soul. Let them be turned backward and put to *_shame_* who desire my hurt.
* `Psa 70:3` Let them be turned back for a reward of their *_shame_* who say, "Aha, aha."
* `Psa 71:1` In you, O LORD, I put my trust. Let me never be put to *_shame_*.
* `Psa 71:24` My tongue shall also talk of your righteousness all the day long. For they are confounded, for they are brought to *_shame_* who seek my hurt.
* `Psa 83:16` Fill their faces with *_shame_* so that they may seek your name, O LORD.
* `Psa 83:17` Let them be confounded and troubled forever. Let them even be put to *_shame_* and perish,
* `Psa 89:45` The days of his youth you have shortened. You have covered him with *_shame_*. [Selah.]
* `Psa 109:29` Let my adversaries be clothed with *_shame_*, and let them cover themselves with their own *_shame_* as with a mantle.
* `Psa 119:31` I have adhered to your testimonies. O LORD, do not put me to *_shame_*.
* `Psa 132:18` His enemies I will clothe with *_shame_*, but upon himself his crown shall flourish."
* `Pro 3:35` The wise shall inherit glory, but *_shame_* shall be the promotion of fools.
* `Pro 9:7` He who reproves a scorner gets *_shame_* for himself. And he who rebukes a wicked man gets himself a blot.
* `Pro 10:5` He who gathers in summer is a wise son, but he who sleeps in harvest is a son who causes *_shame_*.
* `Pro 11:2` When pride comes, *_shame_* comes, but with the lowly is wisdom.
* `Pro 12:16` A fool's wrath is presently known, but a prudent man covers *_shame_*.
* `Pro 13:5` A righteous man hates lying, but a wicked man is loathsome and comes to *_shame_*.
* `Pro 13:18` Poverty and *_shame_* shall be to him who refuses instruction, but he who regards reproof shall be honored.
* `Pro 14:35` The king's favor is toward a wise servant, but his wrath is against him who causes *_shame_*.
* `Pro 17:2` A wise servant shall have rule over a son who causes *_shame_*, and shall have part of the inheritance among the brothers.
* `Pro 18:13` He who answers a matter before he hears it, it is folly and *_shame_* to him.
* `Pro 19:26` He who wastes his father and chases away his mother is a son who causes *_shame_* and brings reproach.
* `Pro 25:8` Do not go forth hastily to strive, lest you not know what to do in the end thereof when your neighbor has put you to *_shame_*.
* `Pro 25:10` Lest he who hears it put you to *_shame_*, and your infamy not turn away.
* `Pro 29:15` The rod and reproof give wisdom, but a child left to himself brings his mother to *_shame_*.
* `Isa 20:4` So the king of Assyria shall lead away the Egyptians prisoners and the Cushites captives, young and old, naked and barefoot, even with their backsides uncovered, to the *_shame_* of Egypt.
* `Isa 22:18` With violence he will surely turn and toss you like a ball into a wide country. There you shall die, and there the chariots of your glory shall be the *_shame_* of your lord's house.'
* `Isa 26:11` LORD, when your hand is lifted up, they will not see. But they shall see your zeal for the people and be put to *_shame_*. Even the fire of your enemies shall devour them.
* `Isa 30:3` Therefore, the strength of Pharaoh shall be your *_shame_*, and refuge in the shadow of Egypt your disgrace.
* `Isa 30:5` They were all ashamed of a people who could not profit them, neither be a help nor profit, but a *_shame_*, and also a reproach."
* `Isa 47:3` Your nakedness shall be uncovered. Even your *_shame_* shall be seen. I will take vengeance, and I will spare no man."
* `Isa 50:6` I gave my back to the smiters and my cheeks to those who plucked off the hair. I did not hide my face from *_shame_* and spitting.
* `Isa 54:4` Do not fear, for you shall not be ashamed. Do not be confounded, for you shall not be put to *_shame_*. For you shall forget the *_shame_* of your youth, and shall not remember the reproach of your widowhood anymore.
* `Isa 61:7` Instead of your *_shame_* you shall have double. Instead of disgrace they shall rejoice in their portion. Therefore, in their land they shall possess the double. Everlasting joy shall be to them.
* `Jer 3:25` We lie down in our *_shame_*, and our disgrace covers us, for we have sinned against the LORD our God—we and our fathers—from our youth even to this day. We have not obeyed the voice of the LORD our God."
* `Jer 7:19` Do they provoke me to anger?" says the LORD. "Do they not provoke themselves to the *_shame_* of their own faces?"
* `Jer 13:26` Therefore, I will uncover your skirts upon your face so that your *_shame_* may appear.
* `Jer 20:18` Why was I brought into the world to see labor and sorrow so that my days should be consumed with *_shame_*?
* `Jer 23:40` And I will bring upon you an everlasting reproach and a perpetual *_shame_* which shall not be forgotten."
* `Jer 46:12` The nations have heard of your *_shame_*, and your cry has filled the land. For the mighty man has stumbled against the mighty, and they have fallen both together.
* `Jer 48:39` "They shall howl, saying, 'How it is broken down! How Moab has turned the back with *_shame_*!' So Moab shall be a derision and a dismaying to all who are around him."
* `Jer 51:51` We are confounded because we have heard reproach. *_Shame_* has covered our faces, for strangers have come into the sanctuaries of the LORD'S house.
* `Ezk 7:18` They shall also gird themselves with sackcloth, horror shall cover them, *_shame_* shall be upon all faces, and baldness upon all their heads.
* `Ezk 16:52` You also, who have judged your sisters, bear your own *_shame_* for your sins that you have committed which are more abominable than theirs. They are more righteous than you. Indeed, be also confounded and bear your *_shame_*, in that you have justified your sisters.
* `Ezk 16:54` So that you may bear your own *_shame_* and be confounded in all that you have done, in that you are a comfort to them.
* `Ezk 16:63` So that you may remember and be confounded and never open your mouth anymore because of your *_shame_*, when I am pacified toward you for all that you have done," says the Lord GOD.
* `Ezk 32:24` "There is Elam and all her multitude around her grave. All of them are slain, fallen by the sword, who have gone down uncircumcised into the nether parts of the earth, who caused their terror in the land of the living. Yet they have borne their *_shame_* with those who go down to the pit.
* `Ezk 32:25` They have set her a bed in the midst of the slain with all her multitude. Her graves are around him. All of them are uncircumcised, slain by the sword. Though their terror was caused in the land of the living, yet they have borne their *_shame_* with those who go down to the pit. He is put in the midst of those who are slain.
* `Ezk 32:30` "There are the princes of the north—all of them and all the Zidonians—who have gone down with the slain. With their terror they are ashamed of their might, and they lie uncircumcised with those who are slain by the sword, and bear their *_shame_* with those who go down to the pit.
* `Ezk 34:29` And I will raise up for them a plant of renown, and they shall no longer be consumed with hunger in the land, neither bear the *_shame_* of the heathen anymore.
* `Ezk 36:6` Prophesy therefore concerning the land of Israel, and say to the mountains, to the hills, to the rivers, and to the valleys, 'Thus says the Lord GOD: "Behold, I have spoken in my jealousy and in my fury, because you have borne the *_shame_* of the heathen."
* `Ezk 36:7` Therefore, thus says the Lord GOD: "I have lifted up my hand. Surely the heathen who are around you, they shall bear their *_shame_*.
* `Ezk 36:15` "I will not cause men to hear in you the *_shame_* of the heathen anymore, neither shall you bear the reproach of the people anymore, neither shall you cause your nations to fall anymore," says the Lord GOD.'"
* `Ezk 39:26` And they shall bear their *_shame_* and all their trespasses by which they have trespassed against me when they dwell safely in their land and no one makes them afraid,
* `Ezk 44:13` And they shall not come near to me to do the office of a priest to me, nor to come near to any of my holy things in the holy of holies, but they shall bear their *_shame_* and their abominations which they have committed.
* `Dan 12:2` And many of those who sleep in the dust of the earth shall awake, some to everlasting life, and some to *_shame_* and everlasting contempt.
* `Hos 4:7` As they were increased, so they sinned against me; therefore, I will change their glory into *_shame_*.
* `Hos 4:18` Their drink is sour. They have been guilty of lewd deeds continually. Her rulers have thoroughly loved *_shame_*.
* `Hos 9:10` I found Israel like grapes in the wilderness. I saw your fathers as the first-fruits on the fig-tree in her first season. But they went to Baal-peor and separated themselves to that *_shame_*, and their abominations were according as they loved.
* `Hos 10:6` It shall also be carried to Assyria for a present to king Jareb. Ephraim shall receive *_shame_*, and Israel shall be ashamed of his own counsel.
* `Oba 1:10` "For your violence against your brother Jacob, *_shame_* shall cover you, and you shall be cut off forever.
* `Mic 1:11` Pass on, you inhabitant of Saphir, having your *_shame_* exposed. The inhabitant of Zaanan did not come forth in the mourning of Beth-ezel. He shall receive from you his standing.
* `Mic 7:10` Then she who is my enemy shall see it, and *_shame_* shall cover her who said to me, "Where is the LORD your God?" My eyes shall behold her. Now she shall be trodden down as the mire of the streets.
* `Nah 3:5` "Behold, I am against you," says the LORD of hosts, "and I will lift your skirts over your face and I will show the nations your nakedness and the kingdoms your *_shame_*.
* `Hab 2:10` You have devised *_shame_* to your house by cutting off many people and have sinned against your soul.
* `Hab 2:16` You are filled with *_shame_* and not glory. You shall also drink and let your uncircumcision be uncovered. The cup of the LORD'S right hand shall be turned to you, and shameful vomiting shall be on your glory.
* `Zph 3:5` The just LORD is in the midst of her. He will not do iniquity. Every morning he brings his judgment to light. He does not fail. But the unjust knows no *_shame_*.
* `Zph 3:19` Behold, at that time I will deal with all who afflict you. And I will save her who is lame and gather her who was driven out. And I will get them praise and fame in every land where they have been put to *_shame_*.
* `Luk 14:9` And he who invited you and him comes and says to you, 'Give this man place,' and you begin with *_shame_* to take the lowest place.
* `Act 5:41` And they departed from the presence of the council, rejoicing that they were counted worthy to suffer *_shame_* for his name.
* `1Co 4:14` I do not write these things to *_shame_* you, but as my beloved sons I warn you.
* `1Co 6:5` I speak to your *_shame_*. Is it so, that there is not a wise man among you? Not even one who will be able to judge between his brothers?
* `1Co 11:6` For if the woman is not covered, let her also be shorn, but if it is a *_shame_* for a woman to be shorn or shaved, let her be covered.
* `1Co 11:14` Does even nature itself not teach you, that if a man has long hair, it is a *_shame_* to him?
* `1Co 11:22` What? Do you not have houses to eat and to drink in? Or do you despise the church of God and *_shame_* those who do not have? What shall I say to you? Shall I praise you in this? I do not praise you.
* `1Co 14:35` And if they will learn anything, let them ask their husbands at home, for it is a *_shame_* for women to speak in the church.
* `1Co 15:34` Awake to righteousness and do not sin, for some do not have the knowledge of God. I speak this to your *_shame_*.
* `Eph 5:12` For it is a *_shame_* even to speak of those things which are done by them in secret.
* `Phl 3:19` Whose end is destruction, whose god is their belly, and whose glory is in their *_shame_*, who mind earthly things.)
* `Heb 6:6` If they fall away, to renew them again to repentance, seeing they crucify to themselves the Son of God again and put him to an open *_shame_*.
* `Heb 12:2` Looking to Jesus the author and finisher of our faith, who, for the joy that was set before him, endured the cross, despising the *_shame_*, and has sat down at the right hand of the throne of God.
* `Jde 1:13` They are raging waves of the sea foaming out their own *_shame_*. They are wandering stars to whom the blackness of darkness is reserved forever.
* `Rev 3:18` I counsel you to buy from me gold tried in the fire so that you may be rich, and white clothing so that you may be clothed and the *_shame_* of your nakedness may not appear, and anoint your eyes with eye-salve so that you may see.
* `Rev 16:15` "Behold, I come as a thief. Blessed is he who watches and keeps his garments, lest he walk naked and they see his *_shame_*."

_102 verses containing SHAME_

== SHAMED

* `Gen 38:23` And Judah said, "Let her keep it, lest we be *_shamed_*. Behold, I sent this kid, and you have not found her."
* `2Sa 19:5` And Joab came into the house to the king and said, "You have *_shamed_* this day the faces of all your servants, who this day have saved your life, the lives of your sons and of your daughters, the lives of your wives, and the lives of your concubines,
* `1Ch 8:12` The sons of Elpaal: Eber, Misham, *_Shamed_* (who built Ono and Lod, with its town),
* `Psa 14:6` You have *_shamed_* the counsel of the poor because the LORD is his refuge.

_4 verses containing SHAMED_

== SHAMEFUL

* `Jer 3:24` "For the *_shameful_* thing has devoured the labor of our fathers from our youth—their flocks and their herds, their sons and their daughters.
* `Jer 11:13` For according to the number of your cities were your gods, O Judah, and according to the number of the streets of Jerusalem you have set up altars to that *_shameful_* thing, even altars to burn incense to Baal.
* `Hab 2:16` You are filled with shame and not glory. You shall also drink and let your uncircumcision be uncovered. The cup of the LORD'S right hand shall be turned to you, and *_shameful_* vomiting shall be on your glory.

_3 verses containing SHAMEFUL_

== SHAMEFULLY

* `Hos 2:5` For their mother has played the harlot. She who conceived them has done *_shamefully_*. For she said, 'I will go after my lovers who give me my bread and my water, my wool and my flax, my oil and my drink.'
* `Mrk 12:4` And again, he sent to them another servant, and at him they cast stones and wounded him in the head and sent him away *_shamefully_* handled.
* `Luk 20:11` And again he sent another servant, and they beat him also, treated him *_shamefully_*, and sent him away empty.
* `1Th 2:2` But even after we had suffered before and were *_shamefully_* treated at Phillippi, as you know, we were bold in our God to speak to you the gospel of God with much contention.

_4 verses containing SHAMEFULLY_

== SHAMELESSLY

* `2Sa 6:20` Then David returned to bless his household. And Michal the daughter of Saul came out to meet David and said, "How glorious the king of Israel was today, who uncovered himself today in the eyes of his servants' women-servants, as one of the vain fellows *_shamelessly_* uncovers himself!"

_1 verse containing SHAMELESSLY_

== SHAMER

* `1Ch 6:46` The son of Amzi, the son of Bani, the son of *_Shamer_*,
* `1Ch 7:34` And the sons of *_Shamer_*: Ahi, Rohgah, Jehubbah, and Aram.

_2 verses containing SHAMER_

== SHAMES

* `Pro 28:7` He who keeps the law is a wise son, but he who is a companion of riotous men *_shames_* his father.

_1 verse containing SHAMES_

== SHAMGAR

* `Jdg 3:31` And after him was *_Shamgar_* the son of Anath, who slew of the Philistines six hundred men with an ox-goad, and he also delivered Israel.
* `Jdg 5:6` "In the days of *_Shamgar_* the son of Anath, in the days of Jael, the highways were unoccupied, and the travelers walked through by-ways.

_2 verses containing SHAMGAR_

== SHAMHUTH

* `1Ch 27:8` The fifth captain for the fifth month was *_Shamhuth_* the Izrahite. And in his course were twenty-four thousand.

_1 verse containing SHAMHUTH_

== SHAMIR

* `Jsh 15:48` And in the mountains, *_Shamir_*, Jattir, Socoh,
* `Jdg 10:1` And after Abimelech there arose to defend Israel Tola the son of Puah, the son of Dodo, a man of Issachar. And he dwelt in *_Shamir_* in the mountains of Ephraim.
* `Jdg 10:2` And he judged Israel for twenty-three years, died, and was buried in *_Shamir_*.
* `1Ch 24:24` Of the sons of Uzziel: Michah. Of the sons of Michah: *_Shamir_*.

_4 verses containing SHAMIR_

== SHAMMA

* `1Ch 7:37` Bezer, Hod, *_Shamma_*, Shilshah, Ithran, and Beera.

_1 verse containing SHAMMA_

== SHAMMAH

* `Gen 36:13` And these are the sons of Reuel: Nahath, Zerah, *_Shammah_*, and Mizzah. These are the sons of Bashemath, Esau's wife.
* `Gen 36:17` And these are the sons of Reuel, Esau's son: chief Nahath, chief Zerah, chief *_Shammah_*, chief Mizzah. These are the chiefs, descendants of Reuel, in the land of Edom. These are the sons of Bashemath, Esau's wife.
* `1Sa 16:9` Then Jesse made *_Shammah_* to pass by. And he said, "The LORD has not chosen this one."
* `1Sa 17:13` And the three eldest sons of Jesse went and followed Saul to the battle. And the names of his three sons who went to the battle were Eliab the first-born, next to him Abinadab, and the third *_Shammah_*.
* `2Sa 23:11` And after him was *_Shammah_* the son of Agee the Hararite. And the Philistines were collected into a troop where there was a piece of ground full of lentils, and the people fled from the Philistines.
* `2Sa 23:25` *_Shammah_* the Harodite, Elika the Harodite,
* `2Sa 23:33` *_Shammah_* the Hararite, Ahiam the son of Sharar the Hararite,
* `1Ch 1:37` The sons of Reuel: Nahath, Zerah, *_Shammah_*, and Mizzah.

_8 verses containing SHAMMAH_

== SHAMMAI

* `1Ch 2:28` And the sons of Onam were *_Shammai_* and Jada. And the sons of *_Shammai_*: Nadab and Abishur.
* `1Ch 2:32` And the sons of Jada the brother of *_Shammai_*: Jether and Jonathan. And Jether died without children.
* `1Ch 2:44` And Shema begot Raham the father of Jorkoam, and Rekem begot *_Shammai_*.
* `1Ch 2:45` And the son of *_Shammai_* was Maon, and Maon was the father of Beth-zur.
* `1Ch 4:17` And the sons of Ezra were Jethur, Mered, Epher, and Jalon. Mered took a wife and she bore Miriam, *_Shammai_*, and Ishbah the father of Eshtemoa.

_5 verses containing SHAMMAI_

== SHAMMOTH

* `1Ch 11:27` *_Shammoth_* the Harorite, Helez the Pelonite,

_1 verse containing SHAMMOTH_

== SHAMMUA

* `Num 13:4` And these were their names: Of the tribe of Reuben, *_Shammua_* the son of Zaccur;
* `1Ch 14:4` Now these are the names of his children which he had in Jerusalem: *_Shammua_*, Shobab, Nathan, Solomon,
* `Neh 11:17` And Mattaniah the son of Micha, the son of Zabdi, the son of Asaph, was the principal to begin the thanksgiving in prayer, and Bakbukiah the second among his brothers; and Abda the son of *_Shammua_*, the son of Galal, the son of Jeduthun.
* `Neh 12:18` Of Bilgah, *_Shammua_*; of Shemaiah, Jehonathan;

_4 verses containing SHAMMUA_

== SHAMMUAH

* `2Sa 5:14` And these are the names of those who were born to him in Jerusalem: *_Shammuah_*, Shobab, Nathan, Solomon,

_1 verse containing SHAMMUAH_

== SHAMSHERAI

* `1Ch 8:26` And *_Shamsherai_*, Shehariah, Athaliah,

_1 verse containing SHAMSHERAI_

== SHAPE

* `Luk 3:22` And the Holy Spirit descended in a bodily *_shape_* like a dove upon him, and a voice came from heaven, which said, "You are my beloved Son. In you I am well pleased."
* `Jhn 5:37` "And the Father himself who has sent me has borne testimony concerning me. You have neither heard his voice at any time, nor seen his *_shape_*.

_2 verses containing SHAPE_

== SHAPED

* `Psa 51:5` Behold, I was *_shaped_* in iniquity, and in sin my mother conceived me.

_1 verse containing SHAPED_

== SHAPES

* `Rev 9:7` And the *_shapes_* of the locusts were like horses prepared for battle. And on their heads were something like crowns like gold, and their faces were like the faces of men.

_1 verse containing SHAPES_

== SHAPHAM

* `1Ch 5:12` Joel the chief, *_Shapham_* the next, Jaanai, and Shaphat in Bashan.

_1 verse containing SHAPHAM_

== SHAPHAN

* `2Ki 22:3` And it came to pass in the eighteenth year of king Josiah, that the king sent *_Shaphan_* the scribe, the son of Azaliah, the son of Meshullam, to the house of the LORD, saying,
* `2Ki 22:8` And Hilkiah the high priest said to *_Shaphan_* the scribe, "I have found the book of the law in the house of the LORD." And Hilkiah gave the book to *_Shaphan_*, and he read it.
* `2Ki 22:9` And *_Shaphan_* the scribe came to the king and brought back word to the king and said, "Your servants have gathered the money that was found in the house and have delivered it into the hand of those who do the work, who have the oversight of the house of the LORD."
* `2Ki 22:10` And *_Shaphan_* the scribe told the king, saying, "Hilkiah the priest has delivered a book to me." And *_Shaphan_* read it before the king.
* `2Ki 22:12` And the king commanded Hilkiah the priest, Ahikam the son of *_Shaphan_*, Achbor the son of Michaiah, *_Shaphan_* the scribe, and Asahiah the king's servant, saying,
* `2Ki 22:14` So Hilkiah the priest, Ahikam, Achbor, *_Shaphan_*, and Asahiah went to Huldah the prophetess, the wife of Shallum, the son of Tikvah, the son of Harhas, keeper of the wardrobe (now she dwelt in Jerusalem in the second quarter), and they spoke with her.
* `2Ki 25:22` And as for the people who remained in the land of Judah whom Nebuchadnezzar king of Babylon had left, he made Gedaliah the son of Ahikam, the son of *_Shaphan_*, ruler over them.
* `2Ch 34:8` Now in the eighteenth year of his reign, when he had purged the land and the house, he sent *_Shaphan_* the son of Azaliah, Maaseiah the governor of the city, and Joah the son of Joahaz the recorder to repair the house of the LORD his God.
* `2Ch 34:15` And Hilkiah answered and said to *_Shaphan_* the scribe, "I have found the book of the law in the house of the LORD." And Hilkiah delivered the book to *_Shaphan_*.
* `2Ch 34:16` And *_Shaphan_* carried the book to the king and brought the king word back again, saying, "All that was committed to your servants, they perform.
* `2Ch 34:18` Then *_Shaphan_* the scribe told the king, saying, "Hilkiah the priest has given me a book." And *_Shaphan_* read it before the king.
* `2Ch 34:20` And the king commanded Hilkiah, Ahikam the son of *_Shaphan_*, Abdon the son of Micah, *_Shaphan_* the scribe, and Asaiah a servant of the king, saying,
* `Jer 26:24` Nevertheless, the hand of Ahikam the son of *_Shaphan_* was with Jeremiah, that they should not give him into the hand of the people to put him to death.
* `Jer 29:3` By the hand of Elasah the son of *_Shaphan_* and Gemariah the son of Hilkiah (whom Zedekiah king of Judah sent to Babylon to Nebuchadnezzar king of Babylon), saying,
* `Jer 36:10` Then Baruch read in the book the words of Jeremiah in the house of the LORD, in the chamber of Gemariah the son of *_Shaphan_* the scribe, in the higher court, at the entry of the new gate of the LORD'S house, in the ears of all the people.
* `Jer 36:11` When Michaiah the son of Gemariah, the son of *_Shaphan_*, had heard out of the book all the words of the LORD,
* `Jer 36:12` He went down into the king's house, into the scribe's chamber, and behold, all the princes sat there, even Elishama the scribe, Delaiah the son of Shemaiah, Elnathan the son of Achbor, Gemariah the son of *_Shaphan_*, Zedekiah the son of Hananiah, and all the princes.
* `Jer 39:14` They even sent and took Jeremiah out of the court of the prison and committed him to Gedaliah the son of Ahikam, the son of *_Shaphan_*, so that he should carry him home. So he dwelt among the people.
* `Jer 40:5` Now while he had not yet gone back, he said, "Go back also to Gedaliah the son of Ahikam the son of *_Shaphan_*, whom the king of Babylon has made governor over the cities of Judah, and dwell with him among the people, or go wherever it seems convenient for you to go." So the captain of the guard gave him provisions and a reward and let him go.
* `Jer 40:9` And Gedaliah the son of Ahikam, the son of *_Shaphan_*, swore to them and to their men, saying, "Do not fear to serve the Chaldeans. Dwell in the land and serve the king of Babylon, and it shall be well with you.
* `Jer 40:11` Likewise, when all the Jews who were in Moab, among the Ammonites, in Edom, and who were in all the countries heard that the king of Babylon had left a remnant of Judah and that he had set over them Gedaliah the son of Ahikam the son of *_Shaphan_*,
* `Jer 41:2` Then Ishmael the son of Nethaniah and the ten men who were with him arose and smote Gedaliah the son of Ahikam the son of *_Shaphan_* with the sword and slew him, whom the king of Babylon had made governor over the land.
* `Jer 43:6` Even men, women, children, the king's daughters, and every person that Nebuzar-adan the captain of the guard had left with Gedaliah the son of Ahikam, the son of *_Shaphan_*, and Jeremiah the prophet, and Baruch the son of Neriah.
* `Ezk 8:11` And there stood before them seventy men of the elders of the house of Israel, and in the midst of them stood Jaazaniah the son of *_Shaphan_*, each with his censer in his hand, and a thick cloud of incense went up.

_24 verses containing SHAPHAN_

== SHAPHAT

* `Num 13:5` Of the tribe of Simeon, *_Shaphat_* the son of Hori;
* `1Ki 19:16` And Jehu the son of Nimshi you shall anoint to be king over Israel. And Elisha the son of *_Shaphat_* of Abel-meholah you shall anoint to be prophet in your stead.
* `1Ki 19:19` So he departed from there and found Elisha the son of *_Shaphat_*, who was plowing with twelve yoke of oxen before him, and he with the twelfth. And Elijah passed by him and cast his mantle upon him.
* `2Ki 3:11` But Jehoshaphat said, "Is there not a prophet of the LORD here that we may inquire of the LORD by him?" And one of the king of Israel's servants answered and said, "Here is Elisha the son of *_Shaphat_* who poured water on the hands of Elijah."
* `2Ki 6:31` Then he said, "May God do so and more also to me, if the head of Elisha the son of *_Shaphat_* stands on him this day."
* `1Ch 3:22` And the son of Shechaniah: Shemaiah. And the sons of Shemaiah: Hattush, Igeal, Bariah, Neariah, and *_Shaphat_*, six.
* `1Ch 5:12` Joel the chief, Shapham the next, Jaanai, and *_Shaphat_* in Bashan.
* `1Ch 27:29` And over the herds that fed in Sharon was Shitrai the Sharonite; and over the herds that were in the valleys was *_Shaphat_* the son of Adlai;

_8 verses containing SHAPHAT_

== SHAPHER

* `Num 33:23` And they went from Kehelathah and encamped at mount *_Shapher_*.
* `Num 33:24` And they departed from mount *_Shapher_* and encamped in Haradah.

_2 verses containing SHAPHER_

== SHARAI

* `Ezr 10:40` Machnadebai, Shashai, *_Sharai_*,

_1 verse containing SHARAI_

== SHARAIM

* `Jsh 15:36` *_Sharaim_*, Adithaim, Gederah, and Gederothaim; fourteen cities with their villages.

_1 verse containing SHARAIM_

== SHARAR

* `2Sa 23:33` Shammah the Hararite, Ahiam the son of *_Sharar_* the Hararite,

_1 verse containing SHARAR_

== SHARE

* `1Sa 13:20` But all the Israelites went down to the Philistines, each to sharpen his *_share_*, his colter, his ax, and his mattock,
* `1Sa 30:24` For who will listen to you in this matter? But as his part is who goes down to the battle, so shall his part be who remains by the goods. They shall *_share_* alike."
* `Gal 6:6` Let him who is taught in the word *_share_* all good things with him who teaches.
* `Heb 13:16` But do not forget to do good and to *_share_*, for with such sacrifices God is well pleased.

_4 verses containing SHARE_

== SHARED

* `Phl 4:14` But you have done well that you *_shared_* in my affliction.

_1 verse containing SHARED_

== SHAREZER

* `2Ki 19:37` And it came to pass, as he was worshiping in the house of Nisroch his god, that Adrammelech and *_Sharezer_* his sons smote him with the sword, and they escaped into the land of Armenia. And Esar-haddon his son reigned in his stead.
* `Isa 37:38` And it came to pass as he was worshiping in the house of Nisroch his god, that Adrammelech and *_Sharezer_* his sons smote him with the sword, and they escaped into the land of Armenia. And Esar-haddon his son reigned in his stead.
* `Jer 39:3` And all the princes of the king of Babylon came in and sat in the middle gate, even Nergal-*_sharezer_*, Samgar-nebo, Sarsechim, Rab-saris, Nergal-*_sharezer_*, and Rab-mag, with all the rest of the princes of the king of Babylon.
* `Jer 39:13` So Nebuzar-adan the captain of the guard sent, and Nebushasban, Rab-saris, Nergal-*_sharezer_*, Rab-mag, and all the king of Babylon's princes,

_4 verses containing SHAREZER_

== SHARON

* `1Ch 5:16` And they dwelt in Gilead in Bashan and in its towns and in all the suburbs of *_Sharon_*, upon their borders.
* `1Ch 27:29` And over the herds that fed in *_Sharon_* was Shitrai the Sharonite; and over the herds that were in the valleys was Shaphat the son of Adlai;
* `Sos 2:1` [Lady:] I am the rose of *_Sharon_* and the lily of the valleys.
* `Isa 33:9` The earth mourns and languishes. Lebanon is ashamed and hewn down. *_Sharon_* is like a wilderness. And Bashan and Carmel shake off their fruits.
* `Isa 35:2` It shall blossom abundantly and rejoice, even with joy and singing. The glory of Lebanon shall be given to it, the excellence of Carmel and *_Sharon_*. They shall see the glory of the LORD and the excellence of our God.
* `Isa 65:10` And *_Sharon_* shall be a fold of flocks, and the valley of Achor a place for the herds to lie down in, for my people who have sought me.

_6 verses containing SHARON_

== SHARONITE

* `1Ch 27:29` And over the herds that fed in Sharon was Shitrai the *_Sharonite_*; and over the herds that were in the valleys was Shaphat the son of Adlai;

_1 verse containing SHARONITE_

== SHARP

* `Exo 4:25` Then Zipporah took a *_sharp_* stone, cut off the foreskin of her son, and cast it at his feet, and said, "Surely a bloody husband you are to me."
* `Jsh 5:2` At that time the LORD said to Joshua, "Make yourself *_sharp_* knives and circumcise the children of Israel again a second time."
* `Jsh 5:3` And Joshua made himself *_sharp_* knives and circumcised the children of Israel at the Hill of the Foreskins.
* `1Sa 14:4` And between the passages by which Jonathan sought to go over to the garrison of the Philistines, there was a *_sharp_* rock on one side and a *_sharp_* rock on the other side. And the name of one was Bozez and the name of the other Seneh.
* `Job 41:30` *_Sharp_* stones are under him. He spreads *_sharp_* pointed things upon the mire.
* `Psa 45:5` Your arrows are *_sharp_* in the heart of the king's enemies, by which the people fall under you.
* `Psa 52:2` Your tongue devises mischiefs, like a *_sharp_* razor, working deceitfully.
* `Psa 57:4` My soul is among lions. And I lie even among those who are set on fire, even the sons of men, whose teeth are spears and arrows and their tongue a *_sharp_* sword.
* `Psa 120:4` *_Sharp_* arrows of the mighty with coals of juniper.
* `Pro 5:4` But her end is bitter as wormwood, *_sharp_* as a two-edged sword.
* `Pro 25:18` A man who bears false witness against his neighbor is a maul, a sword, and a *_sharp_* arrow.
* `Isa 5:28` Whose arrows are *_sharp_* and all their bows bent, their horses' hooves shall be counted like flint and their wheels like a whirlwind.
* `Isa 41:15` Behold, I will make you a new *_sharp_* threshing instrument having teeth. You shall thresh the mountains and beat them small, and shall make the hills as chaff.
* `Isa 49:2` And he has made my mouth like a *_sharp_* sword. In the shadow of his hand he has hid me. He made me a polished shaft, and in his quiver he has hid me.
* `Ezk 5:1` "And you, son of man, take a *_sharp_* knife, take a barber's razor, and cause it to pass upon your head and upon your beard. Then take balances to weigh and divide the hair.
* `Act 15:39` And the contention was so *_sharp_* between them that they departed, separating one from the other. And so Barnabas took Mark and sailed to Cyprus.
* `Rev 1:16` And he had in his right hand seven stars. And out of his mouth went a *_sharp_* two-edged sword. And his countenance was as the sun shining in its strength.
* `Rev 2:12` "And to the angel of the church in Pergamos, write: 'He who has the *_sharp_* sword with two edges says these things:
* `Rev 14:14` And I looked, and behold, a white cloud, and someone like the Son of man sat upon the cloud having a golden crown on his head and a *_sharp_* sickle in his hand.
* `Rev 14:17` And another angel came out of the temple which is in heaven, he also having a *_sharp_* sickle.
* `Rev 14:18` And another angel came out from the altar, who had power over fire, and cried with a loud cry to him who had the *_sharp_* sickle, saying, "Thrust in your *_sharp_* sickle and gather the clusters of the vine of the earth, for her grapes are fully ripe."
* `Rev 19:15` And out of his mouth goes a *_sharp_* sword, so that with it he should smite the nations. And he "shall rule them with a rod of iron." And he treads the wine-press of the fierceness and wrath of Almighty God.

_22 verses containing SHARP_

== SHARPEN

* `1Sa 13:20` But all the Israelites went down to the Philistines, each to *_sharpen_* his share, his colter, his ax, and his mattock,

_1 verse containing SHARPEN_

== SHARPENED

* `Psa 140:3` They have *_sharpened_* their tongues like a serpent. Adder's poison is under their lips. [Selah.]
* `Ezk 21:9` "Son of man, prophesy, and say, 'Thus says the LORD:' Say, 'A sword, a sword is *_sharpened_* and also furbished.
* `Ezk 21:10` It is *_sharpened_* to make a grievous slaughter. It is furbished so that it may glitter.' Should we then make mirth? The rod of my son despises every tree.
* `Ezk 21:11` And he has given it to be furbished so that it may be handled. The sword is *_sharpened_* and it is furbished to give it into the hand of the slayer.
* `Ezk 21:15` I have set the point of the sword against all their gates so that their hearts may faint and their ruins are multiplied. Ah! It is made bright. It is *_sharpened_* for the slaughter.

_5 verses containing SHARPENED_

== SHARPENS

* `Job 16:9` He tears me in his wrath and hates me. He gnashes upon me with his teeth. My enemy *_sharpens_* his eyes upon me.
* `Pro 27:17` As iron *_sharpens_* iron, so a man *_sharpens_* the countenance of his friend.

_2 verses containing SHARPENS_

== SHARPER

* `Mic 7:4` The best of them is as a brier. The most upright is *_sharper_* than a thorn hedge. The day of your watchmen and your visitation comes. Now shall be their perplexity.
* `Heb 4:12` For the word of God is living, powerful, and *_sharper_* than any two-edged sword, piercing even to the dividing apart of soul and spirit, of joints and marrow, and is a discerner of the thoughts and intents of the heart.

_2 verses containing SHARPER_

== SHARPLY

* `Jdg 8:1` And the men of Ephraim said to him, "Why have you treated us like this, not calling for us when you went to fight with the Midianites?" And they chided with him *_sharply_*.
* `Tit 1:13` This testimony is true; therefore, rebuke them *_sharply_* so that they may be sound in the faith,

_2 verses containing SHARPLY_

== SHARPNESS

* `2Co 13:10` Therefore, I write these things being absent, lest being present I should use *_sharpness_*, according to the power which the Lord has given me to edification and not to destruction.

_1 verse containing SHARPNESS_

== SHASHAI

* `Ezr 10:40` Machnadebai, *_Shashai_*, Sharai,

_1 verse containing SHASHAI_

== SHASHAK

* `1Ch 8:14` And Ahio, *_Shashak_*, Jeremoth.
* `1Ch 8:25` Iphedeiah, and Penuel were the sons of *_Shashak_*.

_2 verses containing SHASHAK_

== SHAUL

* `Gen 46:10` And the sons of Simeon: Jemuel, Jamin, Ohad, Jachin, Zohar, and *_Shaul_* the son of a Canaanitish woman.
* `Exo 6:15` And the sons of Simeon: Jemuel, Jamin, Ohad, Jachin, Zohar, and *_Shaul_* the son of a Canaanitish woman. These are the families of Simeon.
* `Num 26:13` Of Zerah, the family of the Zarhites; of *_Shaul_*, the family of the Shaulites.
* `1Ch 1:48` And when Samlah was dead, *_Shaul_* of Rehoboth by the river reigned in his stead.
* `1Ch 1:49` And when *_Shaul_* was dead, Baal-hanan the son of Achbor reigned in his stead.
* `1Ch 4:24` The sons of Simeon were Nemuel, Jamin, Jarib, Zerah, and *_Shaul_*;
* `1Ch 6:24` Tahath his son, Uriel his son, Uzziah his son, and *_Shaul_* his son.

_7 verses containing SHAUL_

== SHAULITES

* `Num 26:13` Of Zerah, the family of the Zarhites; of Shaul, the family of the *_Shaulites_*.

_1 verse containing SHAULITES_

== SHAVE

* `Lev 13:33` He shall be shaved, but the itch he shall not *_shave_*, and the priest shall shut him up who has the itch for seven more days.
* `Lev 14:8` And he who is to be cleansed shall wash his clothes, *_shave_* off all his hair, and wash himself in water so that he may be clean. And after that, he shall come into the camp and shall dwell outside his tent for seven days.
* `Lev 14:9` But it shall be on the seventh day, that he shall *_shave_* all his hair off his head, his beard, and his eye-brows, even all his hair he shall *_shave_* off. And he shall wash his clothes and wash his flesh in water, and he shall be clean.
* `Lev 21:5` They shall not make baldness upon their head, neither shall they *_shave_* off the corner of their beard nor make any cuttings in their flesh.
* `Num 6:9` 'And if any man dies very suddenly by him and he has defiled the head of his consecration, then he shall *_shave_* his head on the day of his cleansing. On the seventh day he shall *_shave_* it.
* `Num 6:18` And the Nazarite shall *_shave_* the head of his separation at the door of the Tabernacle of the Congregation and take the hair of the head of his separation and put it in the fire which is under the sacrifice of the peace-offerings.
* `Num 8:7` And thus you shall do to them to cleanse them: sprinkle water of purifying upon them, and let them *_shave_* all their flesh and wash their clothes, and so make themselves clean.
* `Deu 21:12` Then you shall bring her home to your house, and she shall *_shave_* her head and pare her nails.
* `Jdg 16:19` And she made him sleep upon her knees. And she called for a man, and she caused him to *_shave_* off the seven locks of his head. And she began to afflict him, and his strength went from him.
* `Isa 7:20` In the same day the Lord will *_shave_* with a razor that is hired from beyond the river (namely, by the king of Assyria) the head and the hair of the feet. And it shall also consume the beard.
* `Ezk 44:20` They shall not *_shave_* their heads nor allow their locks to grow long. They shall only poll their heads.
* `Mic 1:16` Make yourself bald and *_shave_* yourself for the children of your delight. Enlarge your baldness as the eagle, for they have gone into captivity from you.
* `Act 21:24` Take them, purify yourself with them, and pay their expenses for them so that they may *_shave_* their heads. And all may know that those things of which they were informed concerning you are nothing, but that you yourself also walk orderly and keep the law.

_13 verses containing SHAVE_

== SHAVED

* `Gen 41:14` Then Pharaoh sent and called Joseph, and they brought him hastily out of the dungeon. And he *_shaved_* himself and changed his clothing and came before Pharaoh.
* `Lev 13:33` He shall be *_shaved_*, but the itch he shall not shave, and the priest shall shut him up who has the itch for seven more days.
* `Num 6:19` And the priest shall take the boiled shoulder of the ram, one unleavened cake out of the basket, and one unleavened wafer and put them upon the hands of the Nazarite after the hair of his separation is *_shaved_*.
* `Jdg 16:17` That he told her all his heart, and said to her, "There has not come a razor upon my head, for I have been a Nazarite to God from my birth. If I am *_shaved_*, then my strength will go from me, and I shall become weak and be like any other man."
* `Jdg 16:22` However, the hair of his head began to grow back after he was *_shaved_*.
* `2Sa 10:4` Therefore, Hanun took David's servants and *_shaved_* off one half of their beards and cut off their garments in the middle, even past the small of the back, and sent them away.
* `1Ch 19:4` Therefore, Hanun took David's servants, *_shaved_* them, and cut off their garments in the midst, even past the small of the back, and sent them away.
* `Job 1:20` Then Job arose, rent his mantle, *_shaved_* his head, fell upon the ground, and worshiped,
* `Jer 41:5` That there came men from Shechem, from Shiloh, and from Samaria, even eighty men, having their beards *_shaved_* and their clothes rent and having cut themselves, with offerings and incense in their hand, to bring them to the house of the LORD.
* `Act 18:18` And Paul remained there for some time, and then took his leave of the brothers and sailed from there into Syria, and with him were Priscilla and Aquila. He *_shaved_* his head in Cenchrea, for he had a vow.
* `1Co 11:5` But every woman who prays or prophesies with her head uncovered dishonors her head, for that is even one and the same as if she were *_shaved_*.
* `1Co 11:6` For if the woman is not covered, let her also be shorn, but if it is a shame for a woman to be shorn or *_shaved_*, let her be covered.

_12 verses containing SHAVED_

== SHAVEH

* `Gen 14:5` And in the fourteenth year, Chedorlaomer and the kings who were with him came and smote the Rephaims in Ashteroth Karnaim, the Zuzims in Ham, the Emins in *_Shaveh_* Kiriathaim,
* `Gen 14:17` And the king of Sodom went out to meet him after his return from the slaughter of Chedorlaomer, and of the kings who were with him, at the valley of *_Shaveh_*, which is the king's dale.

_2 verses containing SHAVEH_

== SHAVSHA

* `1Ch 18:16` Zadok the son of Ahitub and Abimelech the son of Abiathar were the priests, *_Shavsha_* was scribe,

_1 verse containing SHAVSHA_

== SHEAF

* `Gen 37:7` For behold, we were binding sheaves in the field, and behold, my *_sheaf_* arose and also stood upright, and behold, your sheaves stood around and made obeisance to my *_sheaf_*."
* `Lev 23:10` "Speak to the children of Israel and say to them, 'When you come into the land which I give to you and reap the harvest thereof, you shall bring a *_sheaf_* of the first-fruits of your harvest to the priest.
* `Lev 23:11` And he shall wave the *_sheaf_* before the LORD to be accepted for you. On the next day after the sabbath the priest shall wave it.
* `Lev 23:12` And you shall offer on the day when you wave the *_sheaf_* a male lamb without blemish of the first year for a burnt-offering to the LORD.
* `Lev 23:15` 'And you shall count for yourselves from the next day after the sabbath, from the day that you brought the *_sheaf_* of the wave-offering, seven complete sabbaths.
* `Deu 24:19` "When you cut down your harvest in your field and forget a *_sheaf_* in the field, you shall not go back to fetch it. It shall be for the stranger, for the fatherless, and for the widow, so that the LORD your God may bless you in all the work of your hands.
* `Job 24:10` They cause him to go naked without clothing and they take away the *_sheaf_* from the hungry,
* `Zch 12:6` "In that day I will make the governors of Judah like a hearth of fire among the wood and like a torch of fire in a *_sheaf_*, and they shall devour all the people around, on the right hand and on the left. And Jerusalem shall be inhabited again in her own place, even in Jerusalem.

_8 verses containing SHEAF_

== SHEAL

* `Ezr 10:29` And of the sons of Bani: Meshullam, Malluch, Adaiah, Jashub, *_Sheal_*, and Ramoth.

_1 verse containing SHEAL_

== SHEALTIEL

* `Ezr 3:2` Then Jeshua the son of Jozadak stood up, with his brothers the priests, Zerubbabel the son of *_Shealtiel_*, and his brothers, and built the altar of the God of Israel to offer burnt-offerings on it as it is written in the law of Moses the man of God.
* `Ezr 3:8` Now in the second year of their coming to the house of God at Jerusalem, in the second month, Zerubbabel the son of *_Shealtiel_*, Jeshua the son of Jozadak, the remnant of their brothers the priests and the Levites, and all those who had come out of the captivity to Jerusalem, began the work and appointed the Levites, from twenty years old and upward, to set forward the work of the house of the LORD.
* `Ezr 5:2` Then Zerubbabel the son of *_Shealtiel_* and Jeshua the son of Jozadak rose up and began to build the house of God which is at Jerusalem. And with them were the prophets of God helping them.
* `Neh 12:1` Now these are the priests and the Levites who went up with Zerubbabel the son of *_Shealtiel_* and Jeshua: Seraiah, Jeremiah, Ezra,
* `Hag 1:1` In the second year of Darius the king, in the sixth month, on the first day of the month, the word of the LORD came by Haggai the prophet to Zerubbabel the son of *_Shealtiel_*, governor of Judah, and to Joshua the son of Josedech, the high priest, saying,
* `Hag 1:12` Then Zerubbabel the son of *_Shealtiel_* and Joshua the son of Josedech, the high priest, with all the remnant of the people, obeyed the voice of the LORD their God and the words of Haggai the prophet, as the LORD their God had sent him, and the people feared before the LORD.
* `Hag 1:14` And the LORD stirred up the spirit of Zerubbabel the son of *_Shealtiel_*, governor of Judah, and the spirit of Joshua the son of Josedech, the high priest, and the spirit of all the remnant of the people, and they came and performed work in the house of the LORD of hosts, their God,
* `Hag 2:2` "Speak now to Zerubbabel the son of *_Shealtiel_*, governor of Judah, and to Joshua the son of Josedech the high priest, and to the remnant of the people, saying,
* `Hag 2:23` In that day,' says the LORD of hosts, 'I will take you, O Zerubbabel, my servant, the son of *_Shealtiel_*,' says the LORD, 'and will make you as a signet, for I have chosen you,' says the LORD of hosts."
* `Mth 1:12` And after they were brought to Babylon, Jechoniah begot *_Shealtiel_*, *_Shealtiel_* begot Zerubbabel,
* `Luk 3:27` Who was the son of Joanan, who was the son of Rhesa, who was the son of Zerubbabel, who was the son of *_Shealtiel_*, who was the son of Neri,

_11 verses containing SHEALTIEL_

== SHEAR

* `Gen 31:19` And Laban went to *_shear_* his sheep, and Rachel had stolen the images that were her father's.
* `Gen 38:13` And it was told to Tamar, saying, "Behold, your father-in-law goes up to Timnath to *_shear_* his sheep."
* `Deu 15:19` "All the first-born males that come from your herd and from your flock you shall sanctify to the LORD your God. You shall do no work with the first-born of your bull, nor *_shear_* the first-born of your sheep.
* `Isa 7:3` Then the LORD said to Isaiah, "Go forth now to meet Ahaz—you and *_Shear_*-jashub your son—at the end of the conduit of the upper pool in the highway of the fuller's field,

_4 verses containing SHEAR_

== SHEAR-JASHUB

* `Isa 7:3` Then the LORD said to Isaiah, "Go forth now to meet Ahaz—you and *_Shear-jashub_* your son—at the end of the conduit of the upper pool in the highway of the fuller's field,

_1 verse containing SHEAR-JASHUB_

== SHEARER

* `Act 8:32` The place of the Scripture which he read was this: "He was led as a sheep to the slaughter, and as a lamb before his *_shearer_* is mute, so he did not open his mouth.

_1 verse containing SHEARER_

== SHEARERS

* `Gen 38:12` And in process of time, the daughter of Shuah, Judah's wife, died. And Judah was comforted and went up to his sheep-*_shearers_* at Timnath—he and his friend Hirah the Adullamite.
* `1Sa 25:7` And now I have heard that you have *_shearers_*. Now your shepherds who were with us, we did not hurt them, neither was there anything missing to them all the while they were in Carmel.
* `1Sa 25:11` Shall I then take my bread, my water, and my flesh that I have killed for my *_shearers_* and give it to men whom I do not know where they are from?"
* `2Sa 13:23` And it came to pass after two full years, that Absalom had sheep-*_shearers_* in Baal-hazor, which is beside Ephraim, and Absalom invited all the king's sons.
* `2Sa 13:24` And Absalom came to the king and said, "Behold now, your servant has sheep-*_shearers_*. Let the king, I implore you, and his servants go with your servant."
* `Isa 53:7` He was oppressed and he was afflicted, yet he did not open his mouth. He is brought as a lamb to the slaughter, and as a sheep before her *_shearers_* is mute, so he did not open his mouth.

_6 verses containing SHEARERS_

== SHEARIAH

* `1Ch 8:38` And Azel had six sons whose names are these: Azrikam, Bocheru, Ishmael, *_Sheariah_*, Obadiah, and Hanan. All these were the sons of Azel.
* `1Ch 9:44` And Azel had six sons whose names are these: Azrikam, Bocheru, Ishmael, *_Sheariah_*, Obadiah, and Hanan. These were the sons of Azel.

_2 verses containing SHEARIAH_

== SHEARING

* `1Sa 25:2` And there was a man in Maon, whose possessions were in Carmel. And the man was very great, and he had three thousand sheep and one thousand goats. And he was *_shearing_* his sheep in Carmel.
* `1Sa 25:4` And David heard in the wilderness that Nabal was *_shearing_* his sheep.
* `2Ki 10:12` And he arose and departed and came to Samaria. And as he was at the *_shearing_*-house on the way,
* `2Ki 10:14` And he said, "Take them alive." And they took them alive and slew them at the pit of the *_shearing_*-house, even forty-two men. He did not leave any of them.

_4 verses containing SHEARING_

== SHEARING-HOUSE

* `2Ki 10:12` And he arose and departed and came to Samaria. And as he was at the *_shearing-house_* on the way,
* `2Ki 10:14` And he said, "Take them alive." And they took them alive and slew them at the pit of the *_shearing-house_*, even forty-two men. He did not leave any of them.

_2 verses containing SHEARING-HOUSE_

== SHEATH

* `1Sa 17:51` Therefore, David ran and stood upon the Philistine, took his sword, drew it out of its *_sheath_*, slew him, and cut off his head with it. And when the Philistines saw their champion was dead, they fled.
* `2Sa 20:8` When they were at the great stone which is in Gibeon, Amasa went before them. And Joab's garment that he had put on was girded to him, and upon it a girdle with a sword fastened upon his loins in its *_sheath_*, and as he went forth it fell out.
* `1Ch 21:27` And the LORD commanded the angel, and he put up his sword back into its *_sheath_*.
* `Ezk 21:3` And say to the land of Israel, 'Thus says the LORD: "Behold, I am against you, and I will draw forth my sword out of its *_sheath_* and will cut off from you the righteous and the wicked.
* `Ezk 21:4` Seeing then that I will cut off from you the righteous and the wicked, therefore my sword shall go forth from its *_sheath_* against all flesh from the south to the north
* `Ezk 21:5` So that all flesh may know that I, the LORD, have drawn my sword out of its *_sheath_*. It shall not return anymore."'
* `Ezk 21:30` Shall I cause it to return into its *_sheath_*? I will judge you in the place where you were created, in the land of your nativity.
* `Jhn 18:11` Then Jesus said to Peter, "Put up your sword into the *_sheath_*. The cup which my Father has given me, shall I not drink it?"

_8 verses containing SHEATH_

== SHEAVES

* `Gen 37:7` For behold, we were binding *_sheaves_* in the field, and behold, my sheaf arose and also stood upright, and behold, your *_sheaves_* stood around and made obeisance to my sheaf."
* `Rth 2:7` And she said, 'I pray you, let me glean and gather after the reapers among the *_sheaves_*.' So she came and has continued even from the morning until now, and she rested a little in the house."
* `Rth 2:15` And when she had risen to glean, Boaz commanded his young men, saying, "Let her glean even among the *_sheaves_*, and do not reproach her.
* `Neh 13:15` In those days I saw in Judah some treading wine presses on the sabbath, bringing in *_sheaves_*, and lading donkeys, and also wine, grapes, figs, and all manner of burdens, which they brought into Jerusalem on the sabbath day. And I testified against them on the day they sold provisions.
* `Psa 126:6` He who goes forth and weeps, bearing precious seed, shall doubtless return with rejoicing, bringing his *_sheaves_* with him.
* `Psa 129:7` With which the reaper does not fill his hand, nor he who binds *_sheaves_*, his bosom;
* `Amo 2:13` Behold, I am pressed under you as a cart is pressed that is full of *_sheaves_*.
* `Mic 4:12` But they do not know the thoughts of the LORD, neither do they understand his counsel, for he will gather them as *_sheaves_* into the floor.

_8 verses containing SHEAVES_

== SHEBA

* `Gen 10:7` And the sons of Cush: Seba, Havilah, Sabtah, Raamah, and Sabtecha. And the sons of Raamah: *_Sheba_* and Dedan.
* `Gen 10:28` Obal, Abimael, *_Sheba_*,
* `Gen 21:14` And Abraham rose early in the morning, took bread and a bottle of water, gave it to Hagar (putting it on her shoulder) and the child, and sent her away. And she departed and wandered in the wilderness of Beer-*_sheba_*.
* `Gen 21:31` Therefore, he called that place Beer-*_sheba_*, because there the both of them swore.
* `Gen 21:32` Thus they made a covenant at Beer-*_sheba_*. Then Abimelech arose, with Phichol the chief captain of his host, and they returned into the land of the Philistines.
* `Gen 21:33` And Abraham planted a grove in Beer-*_sheba_* and there called on the name of the LORD, the Everlasting God.
* `Gen 22:19` So Abraham returned to his young men, and they rose and went together to Beer-*_sheba_*, and Abraham dwelt at Beer-*_sheba_*.
* `Gen 25:3` And Jokshan begot *_Sheba_* and Dedan. And the sons of Dedan were Asshurim, Letushim, and Leummim.
* `Gen 26:23` And he went up from there to Beer-*_sheba_*.
* `Gen 26:33` And he called it Shebah; therefore, the name of the city is Beer-*_sheba_* to this day.
* `Gen 28:10` And Jacob went out from Beer-*_sheba_* and went toward Haran.
* `Gen 46:1` And Israel took his journey with all that he had, and came to Beer-*_sheba_* and offered sacrifices to the God of his father Isaac.
* `Gen 46:5` And Jacob rose up from Beer-*_sheba_*. And the sons of Israel carried Jacob their father, their little ones, and their wives in the wagons which Pharaoh had sent to carry him.
* `Jsh 15:28` Hazar-shual, Beer-*_sheba_*, Bizjothjah,
* `Jsh 19:2` And they had in their inheritance, Beer-*_sheba_* (or *_Sheba_*), Moladah,
* `Jdg 20:1` Then all the children of Israel went out, and the congregation was assembled as one man from Dan even to Beer-*_sheba_*, along with the land of Gilead, to the LORD in Mizpeh.
* `1Sa 3:20` And all Israel, from Dan even to Beer-*_sheba_*, knew that Samuel was established to be a prophet of the LORD.
* `1Sa 8:2` Now the name of his first-born was Joel and the name of his second was Abiah. They were judges in Beer-*_sheba_*.
* `2Sa 3:10` To translate the kingdom from the house of Saul and to set up the throne of David over Israel and over Judah from Dan even to Beer-*_sheba_*."
* `2Sa 11:3` And David sent and inquired about the woman. And someone said, "Is this not Bath-*_sheba_*, the daughter of Eliam, the wife of Uriah the Hittite?"
* `2Sa 12:24` And David comforted Bath-*_sheba_* his wife and went in to her and lay with her. And she bore a son, and he called his name Solomon. And the LORD loved him,
* `2Sa 17:11` Therefore, I counsel that all Israel should be generally gathered to you, from Dan even to Beer-*_sheba_*, as the sand that is by the sea for multitude, and that you should go to battle in your own person.
* `2Sa 20:1` And there happened to be a man of Belial there whose name was *_Sheba_*, the son of Bichri, a Benjaminite. And he blew a trumpet and said, "We have no part in David, neither do we have inheritance in the son of Jesse. Every man to his tents, O Israel."
* `2Sa 20:2` So every man of Israel, withdrawing from David, followed *_Sheba_* the son of Bichri, but the men of Judah adhered to their king, from the Jordan even to Jerusalem.
* `2Sa 20:6` And David said to Abishai, "Now *_Sheba_* the son of Bichri shall do us more harm than Absalom did. Take your lord's servants and pursue him, lest he get for himself fortified cities and escape us."
* `2Sa 20:7` And there went out after him Joab's men, the Cherethites, the Pelethites, and all the mighty men. And they went out of Jerusalem to pursue after *_Sheba_* the son of Bichri.
* `2Sa 20:10` But Amasa took no heed to the sword that was in Joab's hand. So he smote him in the fifth rib and shed out his bowels to the ground and did not strike him again, and he died. So Joab and Abishai his brother pursued after *_Sheba_* the son of Bichri.
* `2Sa 20:13` When he was removed out of the highway, all the people went on after Joab to pursue after *_Sheba_* the son of Bichri.
* `2Sa 20:21` The matter is not so. But a man of mount Ephraim, *_Sheba_* the son of Bichri by name, has lifted up his hand against the king, even against David. Deliver him only, and I will depart from the city." And the woman said to Joab, "Behold, his head shall be thrown to you over the wall."
* `2Sa 20:22` Then the woman went to all the people in her wisdom. And they cut off the head of *_Sheba_* the son of Bichri and cast it out to Joab. And he blew a trumpet and they retired from the city, every man to his tent. And Joab returned to the king at Jerusalem.
* `2Sa 24:2` For the king said to Joab the captain of the host who was with him, "Go now through all the tribes of Israel, from Dan even to Beer-*_sheba_*, and number the people so that I may know the number of the people."
* `2Sa 24:7` And came to the stronghold of Tyre and to all the cities of the Hivites and of the Canaanites. And they went out to the south of Judah, even to Beer-*_sheba_*.
* `2Sa 24:15` So the LORD sent a pestilence upon Israel from the morning even to the time appointed, and seventy thousand men of the people from Dan even to Beer-*_sheba_* died.
* `1Ki 1:11` Therefore, Nathan spoke to Bath-*_sheba_* the mother of Solomon, saying, "Have you not heard that Adonijah the son of Haggith reigns, and David our lord does not know it?
* `1Ki 1:15` And Bath-*_sheba_* went to the king into the chamber. And the king was very old, and Abishag the Shunamite ministered to the king.
* `1Ki 1:16` And Bath-*_sheba_* bowed and did obeisance to the king. And the king said, "What do you wish?"
* `1Ki 1:28` Then king David answered and said, "Call to me Bath-*_sheba_*." And she came into the king's presence and stood before the king.
* `1Ki 1:31` Then Bath-*_sheba_* bowed with her face to the earth and did reverence to the king, and said, "Let my lord king David live forever."
* `1Ki 2:13` And Adonijah the son of Haggith came to Bath-*_sheba_* the mother of Solomon. And she said, "Do you come peaceably?" And he said, "Peaceably."
* `1Ki 2:18` And Bath-*_sheba_* said, "Very well. I will speak for you to the king."
* `1Ki 2:19` Bath-*_sheba_* therefore went to king Solomon to speak to him for Adonijah. And the king rose up to meet her, bowed himself to her, sat down on his throne, and caused a seat to be set for the king's mother, and she sat on his right hand.
* `1Ki 4:25` And Judah and Israel dwelt safely, every man under his vine and under his fig-tree, from Dan even to Beer-*_sheba_*, all the days of Solomon.
* `1Ki 10:1` And when the queen of *_Sheba_* heard of the fame of Solomon concerning the name of the LORD, she came to prove him with hard questions.
* `1Ki 10:4` And when the queen of *_Sheba_* had seen all Solomon's wisdom, the house that he had built,
* `1Ki 10:10` And she gave the king one hundred and twenty talents of gold, a very great quantity of spices, and precious stones. Never again did there come such abundance of spices as these which the queen of *_Sheba_* gave to king Solomon.
* `1Ki 10:13` And king Solomon gave to the queen of *_Sheba_* all her desire, whatever she asked, besides that which Solomon gave her out of his royal bounty. So she turned and went to her own country—she and her servants.
* `1Ki 19:3` And when he saw that, he arose and went for his life and came to Beer-*_sheba_*, which belongs to Judah, and left his servant there.
* `2Ki 12:1` In the seventh year of Jehu, Jehoash began to reign, and he reigned forty years in Jerusalem. And his mother's name was Zibiah of Beer-*_sheba_*.
* `2Ki 23:8` And he brought all the priests out of the cities of Judah and defiled the high places where the priests had burned incense, from Geba to Beer-*_sheba_*, and broke down the high places of the gates that were in the entrance of the gate of Joshua the governor of the city, which were on a man's left hand at the gate of the city.
* `1Ch 1:9` And the sons of Cush: Seba, Havilah, Sabta, Raamah, and Sabtecha. And the sons of Raamah: *_Sheba_* and Dedan.
* `1Ch 1:22` Ebal, Abimael, *_Sheba_*,
* `1Ch 1:32` Now the sons of Keturah, Abraham's concubine: she bore Zimran, Jokshan, Medan, Midian, Ishbak, and Shuah. And the sons of Jokshan: *_Sheba_* and Dedan.
* `1Ch 4:28` And they dwelt at Beer-*_sheba_*, Moladah, Hazar-shual,
* `1Ch 5:13` And their brothers of the house of their fathers were Michael, Meshullam, *_Sheba_*, Jorai, Jachan, Zia, and Heber, seven.
* `1Ch 21:2` And David said to Joab and to the rulers of the people, "Go, number Israel from Beer-*_sheba_* even to Dan, and bring their number to me so that I may know it."
* `2Ch 9:1` And when the queen of *_Sheba_* heard of the fame of Solomon, she came to prove Solomon with hard questions at Jerusalem, with a very great company and camels that bore spices, gold in abundance, and precious stones. And when she had come to Solomon, she spoke with him about all that was in her heart.
* `2Ch 9:3` And when the queen of *_Sheba_* had seen the wisdom of Solomon, the house that he had built,
* `2Ch 9:9` And she gave the king one hundred and twenty talents of gold, spices of great abundance, and precious stones. Never was there any such spice as the queen of *_Sheba_* gave to king Solomon.
* `2Ch 9:12` And king Solomon gave to the queen of *_Sheba_* all her desire, whatever she asked, besides that which she had brought to the king. So she turned and went away to her own land—she and her servants.
* `2Ch 19:4` And Jehoshaphat dwelt at Jerusalem. And he went out again through the people from Beer-*_sheba_* to mount Ephraim and brought them back to the LORD God of their fathers.
* `2Ch 24:1` Joash was seven years old when he began to reign, and he reigned forty years in Jerusalem. His mother's name was Zibiah of Beer-*_sheba_*.
* `2Ch 30:5` So they established a decree to make proclamation throughout all Israel, from Beer-*_sheba_* even to Dan, that they should come to keep the passover to the LORD God of Israel at Jerusalem, for they had not done it for a long time in the manner as it was written.
* `Neh 11:27` At Hazar-shual, at Beer-*_sheba_* and in its villages,
* `Neh 11:30` Zanoah, Adullam, and in their villages, at Lachish and its fields, and at Azekah and in its villages. And they dwelt from Beer-*_sheba_* to the valley of Hinnom.
* `Job 6:19` The troops of Tema looked, the companies of *_Sheba_* waited for them.
* `Psa 51:1` [To the Chief Musician. A Psalm of David: when Nathan the prophet came to him after he had gone in to Bath-*_sheba_*.] Have mercy upon me, O God, according to your loving-kindness. According to the multitude of your tender mercies, blot out my transgressions.
* `Psa 72:10` The kings of Tarshish and of the islands shall bring presents. The kings of *_Sheba_* and Seba shall offer gifts.
* `Psa 72:15` And he shall live, and to him the gold of *_Sheba_* shall be given. Prayer shall also be made for him continually, and daily he shall be praised.
* `Isa 60:6` The multitude of camels shall cover you, dromedaries of Midian and Ephah. All those from *_Sheba_* shall come. They shall bring gold and incense and show forth the praises of the LORD.
* `Jer 6:20` For what purpose does incense come to me from *_Sheba_* and the sweet cane from a distant country? Your burnt-offerings are not acceptable, nor are your sacrifices sweet to me."
* `Ezk 27:22` The merchants of *_Sheba_* and Raamah, they were your merchants. They occupied in your fairs with chief of all spices, with all precious stones and gold.
* `Ezk 27:23` Haran, Canneh, Eden, the merchants of *_Sheba_*, Asshur, and Chilmad were your merchants.
* `Ezk 38:13` *_Sheba_*, Dedan, and the merchants of Tarshish, with all its young lions shall say to you, 'Have you come to take loot? Have you gathered your company to take plunder, to carry away silver and gold, to take away livestock and goods, to take great plunder?'"'
* `Amo 5:5` But do not seek Beth-el, nor enter into Gilgal, and do not pass to Beer-*_sheba_*, for Gilgal shall surely go into captivity and Beth-el shall come to nothing.
* `Amo 8:14` Those who swear by the sin of Samaria, and say, 'Your god, O Dan, lives,' and, 'The manner of Beer-*_sheba_* lives,' even they shall fall and never rise again."

_75 verses containing SHEBA_

== SHEBAH

* `Gen 26:33` And he called it *_Shebah_*; therefore, the name of the city is Beer-sheba to this day.

_1 verse containing SHEBAH_

== SHEBAM

* `Num 32:3` "Ataroth, Dibon, Jazer, Nimrah, Heshbon, Elealeh, *_Shebam_*, Nebo, and Beon,

_1 verse containing SHEBAM_

== SHEBANIAH

* `1Ch 15:24` And *_Shebaniah_*, Jehoshaphat, Nethaneel, Amasai, Zechariah, Benaiah, and Eliezer the priests blew with the trumpets before the ark of God. And Obed-edom and Jehiah were door-keepers for the ark.
* `Neh 9:4` Then, of the Levites, Jeshua, Bani, Kadmiel, *_Shebaniah_*, Bunni, Sherebiah, Bani, and Chenani stood upon the stairs and cried with a loud voice to the LORD their God.
* `Neh 9:5` Then the Levites, Jeshua, Kadmiel, Bani, Hashabniah, Sherebiah, Hodijah, *_Shebaniah_*, and Pethahiah, said, "Stand up and bless the LORD your God forever and ever: Blessed be your glorious name, which is exalted above all blessing and praise.
* `Neh 10:4` Hattush, *_Shebaniah_*, Malluch,
* `Neh 10:10` And their brothers, *_Shebaniah_*, Hodijah, Kelita, Pelaiah, Hanan,
* `Neh 10:12` Zaccur, Sherebiah, *_Shebaniah_*,
* `Neh 12:14` Of Melicu, Jonathan; of *_Shebaniah_*, Joseph;

_7 verses containing SHEBANIAH_

== SHEBARIM

* `Jsh 7:5` And the men of Ai smote about thirty-six of them, and they chased them from before the gate even to *_Shebarim_* and smote them in the going down. Therefore, the hearts of the people melted and became like water.

_1 verse containing SHEBARIM_

== SHEBER

* `1Ch 2:48` Maachah, Caleb's concubine, bore *_Sheber_* and Tirhanah.

_1 verse containing SHEBER_

== SHEBNA

* `2Ki 18:18` And when they had called to the king, there came out to them Eliakim the son of Hilkiah who was over the household, *_Shebna_* the scribe, and Joah the son of Asaph the recorder.
* `2Ki 18:26` Then Eliakim the son of Hilkiah, *_Shebna_*, and Joah said to Rab-shakeh, "Speak, I pray you, to your servants in the Syrian language, for we understand it. And do not talk with us in the Jews' language in the ears of the people who are on the wall."
* `2Ki 18:37` Then Eliakim the son of Hilkiah who was over the household, *_Shebna_* the scribe, and Joah the son of Asaph the recorder, came to Hezekiah with their clothes rent and told him the words of Rab-shakeh.
* `2Ki 19:2` And he sent Eliakim who was over the household, *_Shebna_* the scribe, and the elders of the priests, covered with sackcloth, to Isaiah the prophet the son of Amoz.
* `Isa 22:15` Thus says the Lord GOD of hosts: "Go, get yourself to this treasurer, even to *_Shebna_*, who is over the house, and say,
* `Isa 36:3` Then Eliakim, Hilkiah's son, who was over the house, *_Shebna_* the scribe, and Joah, Asaph's son the recorder, came forth to him.
* `Isa 36:11` Then Eliakim, *_Shebna_*, and Joah said to Rabshakeh, "Speak, I pray you, to your servants in the Syrian language, for we understand it. And do not speak to us in the Jew's language, in the ears of the people who are on the wall."
* `Isa 36:22` Then Eliakim the son of Hilkiah, who was over the household, *_Shebna_* the scribe, and Joah, the son of Asaph, the recorder, came to Hezekiah with their clothes rent and told him the words of Rabshakeh.
* `Isa 37:2` And he sent Eliakim, who was over the household, *_Shebna_* the scribe, and the elders of the priests covered with sackcloth to Isaiah the prophet the son of Amoz.

_9 verses containing SHEBNA_

== SHEBUEL

* `1Ch 23:16` Of the sons of Gershom: *_Shebuel_* was the chief.
* `1Ch 25:4` Of Heman, the sons of Heman: Bukkiah, Mattaniah, Uzziel, *_Shebuel_*, Jerimoth, Hananiah, Hanani, Eliathah, Giddalti, Romamti-ezer, Joshbekashah, Mallothi, Hothir, and Mahazioth.
* `1Ch 26:24` *_Shebuel_* the son of Gershom, the son of Moses, was ruler of the treasures.

_3 verses containing SHEBUEL_

== SHECANIAH

* `1Ch 24:11` The ninth to Jeshuah, the tenth to *_Shecaniah_*,
* `2Ch 31:15` And under him were Eden, Miniamin, Jeshua, Shemaiah, Amariah, and *_Shecaniah_*, in the cities of the priests, in their set office, to give to their brothers by courses, to the great as well as to the small,

_2 verses containing SHECANIAH_

== SHECHANIAH

* `1Ch 3:21` And the sons of Hananiah: Pelatiah, Jesaiah, the sons of Rephaiah, the sons of Arnan, the sons of Obadiah, the sons of *_Shechaniah_*.
* `1Ch 3:22` And the son of *_Shechaniah_*: Shemaiah. And the sons of Shemaiah: Hattush, Igeal, Bariah, Neariah, and Shaphat, six.
* `Ezr 8:3` Of the sons of *_Shechaniah_*, of the sons of Pharosh: Zechariah, and with him were one hundred and fifty reckoned by genealogy of the males.
* `Ezr 8:5` Of the sons of *_Shechaniah_*: the son of Jahaziel, and with him three hundred males.
* `Ezr 10:2` And *_Shechaniah_* the son of Jehiel, one of the sons of Elam, answered and said to Ezra, "We have trespassed against our God and have taken foreign wives from the people of the land, yet now there is hope in Israel concerning this thing.
* `Neh 3:29` After them Zadok the son of Immer repaired over against his house. After him Shemaiah the son of *_Shechaniah_*, the keeper of the east gate, repaired.
* `Neh 6:18` For there were many in Judah bound by oath to him because he was the son-in-law of *_Shechaniah_* the son of Arah, and his son Johanan had taken the daughter of Meshullam the son of Berechiah.
* `Neh 12:3` *_Shechaniah_*, Rehum, Meremoth,

_8 verses containing SHECHANIAH_

== SHECHEM

* `Gen 33:18` And Jacob came to Shalem, a city of *_Shechem_*, which is in the land of Canaan, when he came from Padan-aram, and pitched his tent before the city.
* `Gen 33:19` And he bought a part of a field where he had spread his tent at the hand of the children of Hamor, *_Shechem_*'s father, for one hundred pieces of money.
* `Gen 34:2` And when *_Shechem_*, the son of Hamor the Hivite, prince of the country, saw her, he took her and lay with her and defiled her.
* `Gen 34:4` And *_Shechem_* spoke to his father Hamor, saying, "Get me this young woman for a wife."
* `Gen 34:6` And Hamor the father of *_Shechem_* went out to Jacob to speak with him.
* `Gen 34:8` And Hamor spoke with them, saying, "The soul of my son *_Shechem_* longs for your daughter. I pray you give her to him for a wife.
* `Gen 34:11` And *_Shechem_* said to her father and to her brothers, "Let me find favor in your eyes, and what you shall say to me, I will give.
* `Gen 34:13` And the sons of Jacob answered *_Shechem_* and Hamor his father deceitfully and said (because he had defiled Dinah their sister),
* `Gen 34:18` And their words pleased Hamor and *_Shechem_*, Hamor's son.
* `Gen 34:20` And Hamor and *_Shechem_* his son came to the gate of their city and spoke with the men of their city, saying,
* `Gen 34:24` And all who went out of the gate of his city listened to Hamor and to *_Shechem_* his son. And every male was circumcised, all who went out of the gate of his city.
* `Gen 34:26` And they slew Hamor and *_Shechem_* his son with the edge of the sword and took Dinah out of *_Shechem_*'s house and went out.
* `Gen 35:4` And they gave to Jacob all the strange gods which were in their hand and the earrings which were in their ears. And Jacob hid them under the oak which was by *_Shechem_*.
* `Gen 37:12` And his brothers went to feed their father's flock in *_Shechem_*.
* `Gen 37:13` And Israel said to Joseph, "Do your brothers not feed the flock in *_Shechem_*? Come, and I will send you to them." And he said to him, "Here I am."
* `Gen 37:14` And he said to him, "Go, I pray you, see whether it is well with your brothers and well with the flocks, and bring word back to me." So he sent him from the valley of Hebron, and he came to *_Shechem_*.
* `Num 26:31` Of Asriel, the family of the Asrielites; of *_Shechem_*, the family of the Shechemites;
* `Jsh 17:2` There was also a lot for the rest of the children of Manasseh by their families: for the children of Abiezer, for the children of Helek, for the children of Asriel, for the children of *_Shechem_*, for the children of Hepher, and for the children of Shemida. These were the male children of Manasseh the son of Joseph by their families.
* `Jsh 17:7` And the border of Manasseh was from Asher to Michmethah, that lies before *_Shechem_*, and the border went along on the right hand to the inhabitants of En-tappuah.
* `Jsh 20:7` And they appointed Kedesh in Galilee in the mountains of Naphtali, *_Shechem_* in the mountains of Ephraim, and Kirjath-arba (which is Hebron) in the mountains of Judah.
* `Jsh 21:21` For they gave them *_Shechem_* with its suburbs in the mountains of Ephraim to be a city of refuge for the slayer, Gezer with its suburbs,
* `Jsh 24:1` And Joshua convened all the tribes of Israel to *_Shechem_* and called for the elders of Israel and for their heads, for their judges, and for their officers, and they presented themselves before God.
* `Jsh 24:25` So Joshua made a covenant with the people that day and made for them a statute and an ordinance in *_Shechem_*.
* `Jsh 24:32` And the bones of Joseph which the children of Israel brought out of Egypt, they buried in *_Shechem_* in a parcel of ground which Jacob bought from the sons of Hamor the father of *_Shechem_* for one hundred pieces of silver. And it became the inheritance of the children of Joseph.
* `Jdg 8:31` And his concubine who was in *_Shechem_*, she also bore him a son, whose name he called Abimelech.
* `Jdg 9:1` And Abimelech the son of Jerubbaal went to *_Shechem_* to his mother's brothers and spoke with them and with all the family of the house of his mother's father, saying,
* `Jdg 9:2` "Speak, I pray you, in the ears of all the men of *_Shechem_*, 'Which is better for you, either that all the sons of Jerubbaal, which are seventy persons, should reign over you, or that one should reign over you?' Remember also that I am your bone and your flesh."
* `Jdg 9:3` And his mother's brothers spoke all these words about him in the ears of all the men of *_Shechem_*. And their hearts inclined to follow Abimelech, for they said, "He is our brother."
* `Jdg 9:6` And all the men of *_Shechem_* and all the house of Millo assembled, and they went and made Abimelech king by the oak of the pillar that was in *_Shechem_*.
* `Jdg 9:7` And when they told it to Jotham, he went and stood on the top of mount Gerizim and lifted up his voice and cried and said to them, "Listen to me, men of *_Shechem_*, so that God may listen to you.
* `Jdg 9:18` And you have risen up against my father's house this day and have slain his sons, seventy persons, upon one stone, and have made Abimelech, the son of his woman-servant, king over the men of *_Shechem_*, because he is your brother),
* `Jdg 9:20` But if not, let fire come out from Abimelech and devour the men of *_Shechem_* and the house of Millo. And let fire come out from the men of *_Shechem_* and from the house of Millo and devour Abimelech."
* `Jdg 9:23` God sent an evil spirit between Abimelech and the men of *_Shechem_*, and the men of *_Shechem_* dealt treacherously with Abimelech,
* `Jdg 9:24` So that the cruelty done to the seventy sons of Jerubbaal might come, and their blood might be laid upon Abimelech their brother who slew them and upon the men of *_Shechem_* who aided him in the killing of his brothers.
* `Jdg 9:25` And the men of *_Shechem_* set an ambush for him on the top of the mountains, and they robbed all who came along that way by them. And this was told to Abimelech.
* `Jdg 9:26` And Gaal the son of Ebed came with his brothers and went over to *_Shechem_*. And the men of *_Shechem_* put their confidence in him.
* `Jdg 9:28` And Gaal the son of Ebed said, "Who is Abimelech and who is *_Shechem_* that we should serve him? Is he not the son of Jerubbaal, and Zebul his officer? Serve the men of Hamor the father of *_Shechem_*. For why should we serve him?
* `Jdg 9:31` And he sent messengers to Abimelech privately, saying, "Behold, Gaal the son of Ebed and his brothers have come to *_Shechem_*, and behold, they fortify the city against you.
* `Jdg 9:34` And Abimelech and all the people who were with him rose by night, and they laid wait against *_Shechem_* in four companies.
* `Jdg 9:39` And Gaal went out before the men of *_Shechem_* and fought with Abimelech.
* `Jdg 9:41` And Abimelech dwelt at Arumah, and Zebul thrust out Gaal and his brothers, so that they should not dwell in *_Shechem_*.
* `Jdg 9:46` And when all the men of the tower of *_Shechem_* heard that, they entered into a hold of the house of the god Berith.
* `Jdg 9:47` And it was told to Abimelech that all the men of the tower of *_Shechem_* were assembled.
* `Jdg 9:49` And all the people likewise each cut down his bough, followed Abimelech, put them to the hold, and set the hold on fire upon them. And all the men of the tower of *_Shechem_* died, about one thousand men and women.
* `Jdg 9:57` And God rendered all the evil of the men of *_Shechem_* upon their heads, and upon them came the curse of Jotham the son of Jerubbaal.
* `Jdg 21:19` Then they said, "Behold, there is a yearly feast of the LORD in Shiloh in a place which is on the north side of Beth-el, on the east side of the highway that goes up from Beth-el to *_Shechem_*, and on the south of Lebonah."
* `1Ki 12:1` And Rehoboam went to *_Shechem_*, for all Israel had come to *_Shechem_* to make him king.
* `1Ki 12:25` Then Jeroboam built *_Shechem_* on mount Ephraim and dwelt in it, and went out from there and built Penuel.
* `1Ch 6:67` And they gave them the cities of refuge: *_Shechem_* in the mountains of Ephraim with its suburbs, Gezer with its suburbs,
* `1Ch 7:19` And the sons of Shemida were Ahian, *_Shechem_*, Likhi, and Aniam.
* `1Ch 7:28` And their possessions and habitations were Beth-el and its towns, and eastward Naaram, and westward Gezer with its towns, *_Shechem_* also and its towns, to Gaza and its towns,
* `2Ch 10:1` And Rehoboam went to *_Shechem_*, for all Israel had come to *_Shechem_* to make him king.
* `Psa 60:6` God has spoken in his holiness, "I will rejoice. I will divide *_Shechem_* and measure out the valley of Succoth.
* `Psa 108:7` God has spoken in his holiness: "I will rejoice. I will divide *_Shechem_* and measure out the valley of Succoth.
* `Jer 41:5` That there came men from *_Shechem_*, from Shiloh, and from Samaria, even eighty men, having their beards shaved and their clothes rent and having cut themselves, with offerings and incense in their hand, to bring them to the house of the LORD.
* `Act 7:16` They were carried over into *_Shechem_* and laid in the sepulcher that Abraham bought for a sum of money from the sons of Hamor the father of *_Shechem_*.

_56 verses containing SHECHEM_

== SHECHEMITES

* `Num 26:31` Of Asriel, the family of the Asrielites; of Shechem, the family of the *_Shechemites_*;

_1 verse containing SHECHEMITES_

== SHED

* `Gen 9:6` "Whoever sheds man's blood, by man his blood shall be *_shed_*, for in the image of God he made man.
* `Gen 37:22` And Reuben said to them, "*_Shed_* no blood. Cast him into this pit that is in the wilderness and lay no hand upon him," so that he might deliver him from their hands to bring him back to his father.
* `Exo 22:2` "If a thief is found breaking through and is smitten so that he dies, there shall no blood be *_shed_* for him.
* `Exo 22:3` If the sun has risen upon him, there shall be blood *_shed_* for him, for he should make full restitution. If he has nothing, then he shall be sold for his theft.
* `Lev 17:4` And does not bring it to the door of the Tabernacle of the Congregation to offer an offering to the LORD before the tabernacle of the LORD, blood shall be imputed to that man. He has *_shed_* blood, and that man shall be cut off from among his people.
* `Num 35:33` So you shall not pollute the land in which you are, for blood defiles the land, and the land cannot be cleansed of the blood that is *_shed_* in it except by the blood of him who *_shed_* it.
* `Deu 19:10` So that innocent blood may not be *_shed_* in your land, which the LORD your God gives you for an inheritance, and thus blood be upon you.
* `Deu 21:7` And they shall answer and say, 'Our hands have not *_shed_* this blood, neither have our eyes seen it.
* `1Sa 25:26` "Now therefore, my lord, as the LORD lives and as your soul lives, seeing the LORD has withheld you from coming to *_shed_* blood and from avenging yourself with your own hand, now let your enemies and those who seek evil to my lord be as Nabal.
* `1Sa 25:31` That this will be no grief to you, nor offense of heart to my lord, either that you have *_shed_* blood without cause, or that my lord has avenged himself. But when the LORD has dealt well with my lord, remember your servant."
* `1Sa 25:33` And blessed is your discretion, and blessed are you who have kept me this day from coming to *_shed_* blood and from avenging myself with my own hand.
* `2Sa 20:10` But Amasa took no heed to the sword that was in Joab's hand. So he smote him in the fifth rib and *_shed_* out his bowels to the ground and did not strike him again, and he died. So Joab and Abishai his brother pursued after Sheba the son of Bichri.
* `1Ki 2:31` And the king said to him, "Do as he has said and fall upon him and bury him so that you may take away the innocent blood which Joab *_shed_* from me and from the house of my father.
* `2Ki 21:16` Moreover, Manasseh *_shed_* very much innocent blood until he had filled Jerusalem from one end to another, besides his sin with which he made Judah to sin in doing evil in the sight of the LORD.
* `2Ki 24:4` And also for the innocent blood that he *_shed_*, for he filled Jerusalem with innocent blood which the LORD would not pardon.
* `1Ch 22:8` But the word of the LORD came to me, saying, 'You have *_shed_* blood abundantly and have made great wars. You shall not build a house to my name because you have *_shed_* much blood upon the earth in my sight.
* `1Ch 28:3` But God said to me, 'You shall not build a house for my name because you have been a man of war and have *_shed_* blood.'
* `Psa 79:3` They have *_shed_* their blood like water around Jerusalem, and there was no one to bury them.
* `Psa 79:10` Why should the heathen say, "Where is their God?" Let him be known among the heathen in our sight by avenging the blood of your servants which is *_shed_*.
* `Psa 106:38` And *_shed_* innocent blood, even the blood of their sons and of their daughters, whom they sacrificed to the idols of Canaan. And the land was polluted with blood.
* `Pro 1:16` For their feet run to evil and make haste to *_shed_* blood.
* `Pro 6:17` A proud look, a lying tongue, hands that *_shed_* innocent blood,
* `Isa 59:7` Their feet run to evil, and they make haste to *_shed_* innocent blood. Their thoughts are thoughts of iniquity. Wasting and destruction are in their paths.
* `Jer 7:6` If you do not oppress the stranger, the fatherless, and the widow, and do not *_shed_* innocent blood in this place, neither walk after other gods to your hurt,
* `Jer 22:3` Thus says the LORD: "Execute judgment and righteousness, and deliver him who is laid waste out of the hand of the oppressor. And do no wrong, do no violence to the stranger, the fatherless, nor the widow, neither *_shed_* innocent blood in this place.
* `Lam 4:13` [MEM] It is for the sins of her prophets and the iniquities of her priests, who have *_shed_* the blood of the just in the midst of her.
* `Ezk 16:38` And I will judge you as women who break wedlock and *_shed_* blood are judged. And I will give you blood in fury and jealousy.
* `Ezk 22:4` You have become guilty in your blood that you have *_shed_*, have defiled yourself by your idols which you have made, have caused your days to draw near, and have come even to your years; therefore, I have made you a reproach to the heathen and a mocking to all countries.
* `Ezk 22:6` "Behold, the princes of Israel each used his power to *_shed_* blood in you.
* `Ezk 22:9` In you are men who carry tales to *_shed_* blood. And in you they eat upon the mountains. In the midst of you they commit lewdness.
* `Ezk 22:12` In you they have taken gifts to *_shed_* blood. You have taken interest and increase and you have greedily gained from your neighbors by extortion, and have forgotten me," says the Lord GOD.
* `Ezk 23:45` And the righteous men, they shall judge them after the manner of adulteresses and after the manner of women who *_shed_* blood, because they are adulteresses, and blood is on their hands.
* `Ezk 33:25` Therefore, say to them, 'Thus says the Lord GOD: "You eat with the blood, lift up your eyes toward your idols, and *_shed_* blood. And shall you possess the land?
* `Ezk 35:5` "Because you have had a perpetual hatred and have *_shed_* the blood of the children of Israel by the force of the sword in the time of their calamity, in the time that their iniquity had an end,
* `Ezk 36:18` Therefore, I poured my fury upon them for the blood that they had *_shed_* upon the land and for their idols with which they had polluted it.
* `Joe 3:19` Egypt shall be a desolation and Edom shall be a desolate wilderness for the violence against the children of Judah, because they have *_shed_* innocent blood in their land.
* `Mth 23:35` So that upon you may come all the righteous blood *_shed_* upon the earth, from the blood of righteous Abel, to the blood of Zechariah son of Barachiah, whom you slew between the temple and the altar.
* `Mth 26:28` For this is my blood of the new testament, which is *_shed_* for many for the remission of sins.
* `Mrk 14:24` And he said to them, "This is my blood of the new testament which is *_shed_* for many.
* `Luk 11:50` So that the blood of all the prophets which has been *_shed_* from the foundation of the world may be required of this generation,
* `Luk 22:20` Likewise, he took the cup after supper, saying, "This cup is the new testament in my blood which is *_shed_* for you.
* `Act 22:20` And when the blood of your martyr Stephen was *_shed_*, I also was standing by and consenting to his death and kept the clothing of those who slew him.'
* `Rom 3:15` "Their feet are swift to *_shed_* blood.
* `Rom 5:5` And hope does not make us ashamed, because the love of God is *_shed_* abroad in our hearts by the Holy Spirit who is given to us.
* `Tit 3:6` Which he *_shed_* on us abundantly through Jesus Christ our Savior,
* `Rev 16:6` For they have *_shed_* the blood of saints and prophets, and you have given them blood to drink, for they are worthy."

_46 verses containing SHED_

== SHEDDER

* `Ezk 18:10` "If he begets a son who is a robber, a *_shedder_* of blood, who does the like of any one of these things,

_1 verse containing SHEDDER_

== SHEDDING

* `1Ki 2:5` "Moreover, you also know what Joab the son of Zeruiah did to me and what he did to the two captains of the armies of Israel, to Abner the son of Ner, and to Amasa the son of Jether, whom he slew, *_shedding_* the blood of war in peace and putting the blood of war upon his girdle that was around his loins and in his shoes that were on his feet.
* `Jer 22:17` "But your eyes and your heart are only for your covetousness, for *_shedding_* innocent blood, for oppression, and for doing violence."
* `Ezk 22:27` Her princes in the midst of her are like wolves ravening the prey, *_shedding_* blood, and destroying souls to get dishonest gain.
* `Heb 9:22` And almost all things are by the law cleansed with blood. And without the *_shedding_* of blood there is no remission.

_4 verses containing SHEDDING_

== SHEDEUR

* `Num 1:5` And these are the names of the men who shall stand with you: of the tribe of Reuben, Elizur the son of *_Shedeur_*;
* `Num 2:10` "On the south side shall be the standard of the camp of Reuben according to their armies, and the captain of the children of Reuben shall be Elizur the son of *_Shedeur_*.
* `Num 7:30` On the fourth day Elizur the son of *_Shedeur_*, prince of the children of Reuben, offered.
* `Num 7:35` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of Elizur the son of *_Shedeur_*.
* `Num 10:18` And the standard of the camp of Reuben moved forward according to their armies. And over his host was Elizur the son of *_Shedeur_*.

_5 verses containing SHEDEUR_

== SHEDS

* `Gen 9:6` "Whoever *_sheds_* man's blood, by man his blood shall be shed, for in the image of God he made man.
* `Ezk 22:3` Then say, 'Thus says the Lord GOD: "The city *_sheds_* blood in the midst of it so that her time may come, and makes idols against herself to defile herself.

_2 verses containing SHEDS_

== SHEEP

* `Gen 4:2` And she again bore his brother Abel. And Abel was a keeper of *_sheep_*, but Cain was a tiller of the ground.
* `Gen 12:16` And he treated Abram well for her sake, and he had *_sheep_*, oxen, male donkeys, men-servants, women-servants, female donkeys, and camels.
* `Gen 20:14` And Abimelech took *_sheep_*, oxen, men-servants, and women-servants and gave them to Abraham and restored to him Sarah his wife.
* `Gen 21:27` And Abraham took *_sheep_* and oxen and gave them to Abimelech, and both of them made a covenant.
* `Gen 29:2` And he looked, and behold, a well in the field, and behold, there were three flocks of *_sheep_* lying by it, for out of that well they watered the flocks. And a great stone was upon the well's mouth.
* `Gen 29:3` And there all the flocks were gathered. And they rolled the stone from the well's mouth and watered the *_sheep_*. Then they put the stone back upon the well's mouth in its place.
* `Gen 29:6` And he said to them, "Is he well?" And they said, "He is well, and behold, Rachel his daughter comes with the *_sheep_*."
* `Gen 29:7` And he said, "Behold, it is still the middle of the day, neither is it time that the livestock should be collected. Water the *_sheep_* and go and feed them."
* `Gen 29:8` And they said, "We cannot until all the flocks are collected and until they roll the stone from the well's mouth. Then we water the *_sheep_*."
* `Gen 29:9` And while he was still speaking with them, Rachel came with her father's *_sheep_*, for she kept them.
* `Gen 29:10` And it came to pass when Jacob saw Rachel, the daughter of Laban his mother's brother, and the *_sheep_* of Laban his mother's brother, that Jacob went near and rolled the stone from the well's mouth and watered the flock of Laban his mother's brother.
* `Gen 30:32` I will pass through all your flock today, removing from there all the speckled and spotted *_sheep_*, all the brown ones among the *_sheep_*, and the spotted and speckled among the goats, and of such shall be my hire.
* `Gen 30:33` So my righteousness shall answer for me in time to come when you come for my hire before your face. Each one that is not speckled and spotted among the goats, and brown among the *_sheep_*, shall be accounted stolen with me."
* `Gen 30:35` And he removed that day the male goats that were striped and spotted and all the female goats that were speckled and spotted, each one that had some white in it, and all the brown among the *_sheep_*, and gave them into the hands of his sons.
* `Gen 31:19` And Laban went to shear his *_sheep_*, and Rachel had stolen the images that were her father's.
* `Gen 34:28` They took their *_sheep_*, their oxen, their donkeys, that which was in the city, and that which was in the field.
* `Gen 38:12` And in process of time, the daughter of Shuah, Judah's wife, died. And Judah was comforted and went up to his *_sheep_*-shearers at Timnath—he and his friend Hirah the Adullamite.
* `Gen 38:13` And it was told to Tamar, saying, "Behold, your father-in-law goes up to Timnath to shear his *_sheep_*."
* `Exo 9:3` Behold, the hand of the LORD is upon your livestock which are in the field, and also upon the horses, upon the donkeys, upon the camels, upon the oxen, and upon the *_sheep_*, and there shall be a very grievous pestilence.
* `Exo 12:5` Your lamb shall be without blemish, a male of the first year. You shall take it from the *_sheep_* or from the goats,
* `Exo 20:24` An altar of earth you shall make to me and shall sacrifice thereon your burnt-offerings, your peace-offerings, your *_sheep_*, and your oxen. In all places where I record my name I will come to you and I will bless you.
* `Exo 22:1` "If a man steals an ox or a *_sheep_* and kills it or sells it, he shall restore five oxen for an ox and four *_sheep_* for a *_sheep_*.
* `Exo 22:4` If the theft is certainly found in his hand alive, whether an ox, donkey, or *_sheep_*, he shall restore double.
* `Exo 22:9` For all manner of trespass, whether it is for ox, for donkey, for *_sheep_*, for clothing, or for any manner of lost thing which another challenges to be his, the cause of both parties shall come before the judges. And he whom the judges condemn shall pay double to his neighbor.
* `Exo 22:10` "If a man delivers to his neighbor a donkey, an ox, a *_sheep_*, or any beast to keep and it dies, is hurt, or is driven away, no man seeing it,
* `Exo 22:30` You shall do likewise with your oxen and with your *_sheep_*. Seven days it shall be with his mother. On the eighth day you shall give it to me.
* `Exo 34:19` "Every first-born is mine, even every first-born among your livestock, whether ox or *_sheep_*, that is male.
* `Lev 1:10` 'And if his offering is from the flocks, namely, from the *_sheep_* or from the goats, for a burnt-sacrifice, he shall bring it a male without blemish.
* `Lev 7:23` "Speak to the children of Israel, saying, 'You shall eat no manner of fat from an ox, a *_sheep_*, or a goat.
* `Lev 22:19` You shall offer at your own will a male without blemish from the bulls, from the *_sheep_*, or from the goats.
* `Lev 22:21` And whoever offers a sacrifice of peace-offerings to the LORD to accomplish his vow or a voluntary-offering in bulls or *_sheep_*, it shall be perfect to be accepted. There shall be no blemish in it.
* `Lev 22:27` "When a bull, a *_sheep_*, or a goat is brought forth, it shall remain seven days with its mother. And from the eighth day and thereafter it shall be accepted for an offering made by fire to the LORD.
* `Lev 27:26` 'Only the first-born of the beasts, which should be the LORD'S first-born, no man shall sanctify it, whether ox or *_sheep_*. It is the LORD'S.
* `Num 18:17` But the first-born of a cow, the first-born of a *_sheep_*, or the first-born of a goat, you shall not redeem. They are holy. You shall sprinkle their blood upon the altar and burn their fat for an offering made by fire for a sweet savor to the LORD.
* `Num 22:40` And Balak offered oxen and *_sheep_* and sent to Balaam and to the princes who were with him.
* `Num 27:17` Who may go out before them, who may go in before them, who may lead them out, and who may bring them in, so that the congregation of the LORD is not as *_sheep_* which have no shepherd."
* `Num 31:28` And levy a tribute to the LORD of the men of war who went out to battle, one soul of five hundred, both of the persons, of the bulls, of the donkeys, and of the *_sheep_*.
* `Num 31:32` And the captives, being the rest of the plunder which the men of war had taken, was six hundred and seventy-five thousand *_sheep_*,
* `Num 31:36` And this was the half which was the portion of those who went out to war: in number, three hundred and thirty-seven thousand and five hundred *_sheep_*,
* `Num 31:37` And the LORD'S tribute of the *_sheep_* was six hundred and seventy-five;
* `Num 31:43` (Now the half that pertained to the congregation was three hundred and thirty-seven thousand and five hundred *_sheep_*,
* `Num 32:16` And they came near to him and said, "We will build *_sheep_*-folds here for our livestock and cities for our little ones,
* `Num 32:24` Build yourselves cities for your little ones and folds for your *_sheep_*, and do that which has proceeded out of your mouth."
* `Num 32:36` Beth-nimrah, and Beth-haran—fortified cities—and folds for *_sheep_*.
* `Deu 7:13` And he will love you, bless you, and multiply you. He will also bless your children, and the fruit of your land, your grain, your wine, and your oil, the increase of your cows, and the flocks of your *_sheep_*, in the land which he swore to your fathers to give you.
* `Deu 14:4` These are the beasts which you shall eat: the ox, the *_sheep_*, the goat,
* `Deu 14:26` And you shall bestow that money for whatever your soul desires, for oxen, for *_sheep_*, for wine, for strong drink, or for whatever your soul desires. And you shall eat there before the LORD your God, and you shall rejoice—you and your household.
* `Deu 15:19` "All the first-born males that come from your herd and from your flock you shall sanctify to the LORD your God. You shall do no work with the first-born of your bull, nor shear the first-born of your *_sheep_*.
* `Deu 17:1` "You shall not sacrifice to the LORD your God any bull or *_sheep_* on which there is a blemish or any defect, for that is an abomination to the LORD your God.
* `Deu 18:3` "And this shall be the priest's due from the people, from those who offer a sacrifice, whether ox or *_sheep_*, and they shall give to the priest the shoulder, the two cheeks, and the stomach.
* `Deu 18:4` Also the first-fruit of your grain, of your wine, and of your oil, and the first of the fleece of your *_sheep_*, you shall give him.
* `Deu 22:1` "You shall not see your brother's ox or his *_sheep_* go astray and hide yourself from them. You shall in any case bring them back to your brother.
* `Deu 28:4` "Blessed shall be the fruit of your body, the fruit of your ground, the fruit of your livestock, the increase of your livestock, and the flocks of your *_sheep_*.
* `Deu 28:18` "Cursed shall be the fruit of your body, the fruit of your land, the increase of your cows, and the flocks of your *_sheep_*.
* `Deu 28:31` Your ox shall be slain before your eyes and you shall not eat any of it. Your donkey shall be violently taken away from before your face and shall not be restored to you. Your *_sheep_* shall be given to your enemies and you shall have no one to rescue them.
* `Deu 28:51` And he shall eat the fruit of your livestock and the fruit of your land until you are destroyed. He also shall not leave you either grain, wine, oil, the increase of your livestock, or flocks of your *_sheep_* until he has destroyed you.
* `Deu 32:14` With butter of cows, and milk of *_sheep_*, with fat of lambs, and rams of the breed of Bashan and goats, with the finest of the wheat. And you drank the pure blood of the grape.
* `Jsh 6:21` And they utterly destroyed all that was in the city, both man and woman, young and old, ox, *_sheep_*, and donkey, with the edge of the sword.
* `Jsh 7:24` And Joshua, and all Israel with him, took Achan the son of Zerah, the silver, the garment, the wedge of gold, his sons, his daughters, his oxen, his donkeys, his *_sheep_*, his tent, and all that he had. And they brought them to the valley of Achor.
* `Jdg 5:16` Why did you abide among the *_sheep_*-folds to hear the bleatings of the flocks? For the divisions of Reuben there were great searchings of heart.
* `Jdg 6:4` And they encamped against them and destroyed the increase of the earth as far as Gaza. They left no sustenance for Israel, neither *_sheep_*, ox, or donkey.
* `1Sa 8:17` He will take the tenth of your *_sheep_*. And you will be his servants.
* `1Sa 14:32` And the people flew upon the plunder and took *_sheep_*, oxen, and calves and slew them on the ground. And the people ate them with the blood.
* `1Sa 14:34` And Saul said, "Disperse yourselves among the people and say to them, 'Every man bring me here his ox and every man his *_sheep_*, and slay them here and eat, and do not sin against the LORD in eating with the blood.'" And all the people each brought his ox with him that night and slew them there.
* `1Sa 15:3` Now go and smite Amalek and utterly destroy all that they have, and do not spare them, but slay both man and woman, child and infant, ox and *_sheep_*, camel and donkey.'"
* `1Sa 15:9` But Saul and the people spared Agag and the best of the *_sheep_*, of the oxen, of the fattened calves, the lambs, and all that was good, and would not utterly destroy them. But everything that was vile and refuse, that they utterly destroyed.
* `1Sa 15:14` And Samuel said, "What then does this bleating of the *_sheep_* in my ears and the lowing of the oxen which I hear mean?"
* `1Sa 15:15` And Saul said, "They have brought them from the Amalekites, for the people spared the best of the *_sheep_* and of the oxen to sacrifice to the LORD your God, and the rest we have utterly destroyed."
* `1Sa 15:21` But the people took some of the plunder, *_sheep_* and oxen, the chief of the things which should have been utterly destroyed, to sacrifice to the LORD your God in Gilgal."
* `1Sa 16:11` And Samuel said to Jesse, "Are all your children here?" And he said, "There still remains the youngest, and behold, he keeps the *_sheep_*." And Samuel said to Jesse, "Send and bring him, for we will not sit down until he has come here."
* `1Sa 16:19` Therefore, Saul sent messengers to Jesse and said, "Send to me David your son, who is with the *_sheep_*."
* `1Sa 17:15` But David went and returned from Saul to feed his father's *_sheep_* at Beth-lehem.
* `1Sa 17:20` And David rose early in the morning and left the *_sheep_* with a keeper, and took and went as Jesse had commanded him. And he came to the trench as the host was going forth to the fight and shouting for the battle.
* `1Sa 17:28` And Eliab his eldest brother heard when he spoke to the men. And Eliab's anger was kindled against David and he said, "Why did you come down here? And with whom have you left those few *_sheep_* in the wilderness? I know your pride and the wickedness of your heart. For you have come down so that you may see the battle."
* `1Sa 17:34` And David said to Saul, "Your servant kept his father's *_sheep_*, and there came a lion and a bear and took a lamb out of the flock.
* `1Sa 22:19` And Nob, the city of the priests, he smote with the edge of the sword—both men and women, children and infants, oxen, donkeys, and *_sheep_*, all with the edge of the sword.
* `1Sa 24:3` And he came to the *_sheep_*-folds by the way, where there was a cave, and Saul went in to cover his feet. And David and his men remained in the innermost parts of the cave.
* `1Sa 25:2` And there was a man in Maon, whose possessions were in Carmel. And the man was very great, and he had three thousand *_sheep_* and one thousand goats. And he was shearing his *_sheep_* in Carmel.
* `1Sa 25:4` And David heard in the wilderness that Nabal was shearing his *_sheep_*.
* `1Sa 25:16` They were a wall to us both by night and day all the while we were with them keeping the *_sheep_*.
* `1Sa 25:18` Then Abigail made haste and took two hundred loaves, two bottles of wine, five *_sheep_* ready and dressed, five measures of parched grain, one hundred clusters of raisins, and two hundred cakes of figs, and laid them on donkeys.
* `1Sa 27:9` And David smote the land and left neither man nor woman alive, and took away the *_sheep_*, the oxen, the donkeys, the camels, and the apparel, and returned and came to Achish.
* `2Sa 7:8` "Now therefore, thus you shall say to my servant David: 'Thus says the LORD of hosts: "I took you from the *_sheep_*-fold, from following the *_sheep_*, to be ruler over my people, over Israel.
* `2Sa 13:23` And it came to pass after two full years, that Absalom had *_sheep_*-shearers in Baal-hazor, which is beside Ephraim, and Absalom invited all the king's sons.
* `2Sa 13:24` And Absalom came to the king and said, "Behold now, your servant has *_sheep_*-shearers. Let the king, I implore you, and his servants go with your servant."
* `2Sa 17:29` Honey, butter, *_sheep_*, and cheese of cows for David and for the people who were with him to eat, for they said, "The people are hungry, weary, and thirsty in the wilderness."
* `2Sa 24:17` And David spoke to the LORD when he saw the angel who smote the people and said, "Behold, I have sinned and I have done wickedly. But these *_sheep_*, what have they done? Let your hand, I pray you, be against me and against my father's house."
* `1Ki 1:9` And Adonijah slew *_sheep_*, oxen, and fattened calves by the stone of Zoheleth, which is by En-rogel, and called all his brothers the king's sons and all the men of Judah the king's servants,
* `1Ki 1:19` And he has slain oxen, fattened calves, and *_sheep_* in abundance, and has called all the sons of the king, Abiathar the priest, and Joab the captain of the host, but Solomon your servant he has not called.
* `1Ki 1:25` For he has gone down this day and has slain oxen, fattened calves, and *_sheep_* in abundance, and has called all the king's sons, the captains of the host, and Abiathar the priest. And behold, they eat and drink before him and say, 'God save king Adonijah.'
* `1Ki 4:23` Ten fat oxen, twenty oxen out of the pastures, one hundred *_sheep_*, besides deer, gazelles, and fallow-deer, and fattened birds.
* `1Ki 8:5` And king Solomon and all the congregation of Israel, who were assembled to him, were with him before the ark, sacrificing *_sheep_* and oxen that could not be told nor numbered for multitude.
* `1Ki 8:63` And Solomon offered a sacrifice of peace-offerings which he offered to the LORD: twenty-two thousand oxen and one hundred and twenty thousand *_sheep_*. So the king and all the children of Israel dedicated the house of the LORD.
* `1Ki 22:17` And he said, "I saw all Israel scattered upon the hills, as *_sheep_* that do not have a shepherd. And the LORD said, 'These have no master. Let them each return to his house in peace.'"
* `2Ki 3:4` And Mesha king of Moab was a *_sheep_*-master, and he rendered to the king of Israel one hundred thousand lambs and one hundred thousand rams, with the wool.
* `2Ki 5:26` And he said to him, "Did my heart not go with you when the man turned back from his chariot to meet you? Is it a time to receive money and to receive garments, olive-groves, vineyards, *_sheep_*, oxen, men-servants, and women-servants?
* `1Ch 5:21` And they took away their livestock: fifty thousand of their camels, two hundred and fifty thousand *_sheep_*, and two thousand donkeys; and also one hundred thousand men.
* `1Ch 12:40` Moreover, those who were near them, even as far as Issachar, Zebulun, and Naphtali, brought food on donkeys, on camels, on mules, and on oxen—abundant provision of meal, fig cakes, bunches of raisins, wine, oil, oxen, and *_sheep_*—for there was joy in Israel.
* `1Ch 17:7` Now therefore, thus you shall say to my servant David: 'Thus says the LORD of hosts: "I took you from the *_sheep_*-fold, even from following the *_sheep_*, so that you should be ruler over my people Israel.
* `1Ch 21:17` And David said to God, "Is it not I who commanded the people to be numbered? It is even I who have sinned and done evil indeed, but as for these *_sheep_*, what have they done? Let your hand, I pray you, O LORD my God, be upon me and on my father's house, but not upon your people so that they should be afflicted."
* `2Ch 5:6` Also king Solomon and all the congregation of Israel who were assembled to him before the ark sacrificed *_sheep_* and oxen, which could not be told nor numbered for multitude.
* `2Ch 7:5` And king Solomon offered a sacrifice of twenty-two thousand oxen and one hundred and twenty thousand *_sheep_*. Thus the king and all the people dedicated the house of God.
* `2Ch 14:15` They also smote the tents of livestock and carried away *_sheep_* and camels in abundance and returned to Jerusalem.
* `2Ch 15:11` And they offered to the LORD at the same time from the plunder which they had brought seven hundred oxen and seven thousand *_sheep_*.
* `2Ch 18:2` And after some years he went down to Ahab in Samaria. And Ahab killed *_sheep_* and oxen in abundance for him and for the people who were with him, and persuaded him to go up with him to Ramoth-gilead.
* `2Ch 18:16` Then he said, "I saw all Israel scattered upon the mountains as *_sheep_* that have no shepherd. And the LORD said, 'These have no master. Let them each return therefore to his house in peace.'"
* `2Ch 29:33` And the consecrated things were six hundred oxen and three thousand *_sheep_*.
* `2Ch 30:24` For Hezekiah king of Judah gave to the congregation one thousand bulls and seven thousand *_sheep_*, and the princes gave to the congregation one thousand bulls and ten thousand *_sheep_*. And a great number of priests sanctified themselves.
* `2Ch 31:6` And the children of Israel and Judah who dwelt in the cities of Judah, they also brought in the tithe of oxen and *_sheep_*, and the tithe of holy things which were consecrated to the LORD their God, and laid them by heaps.
* `Neh 3:1` Then Eliashib the high priest arose with his brothers the priests, and they built the *_sheep_*-gate. They sanctified it and set up its doors. Even to the tower of Meah they sanctified it, to the tower of Hananeel.
* `Neh 3:32` And between the ascent of the corner to the *_sheep_*-gate the goldsmiths and the merchants repaired.
* `Neh 5:18` Now that which was prepared for me daily was one ox and six choice *_sheep_*, birds were also prepared for me, and once in ten days an abundance of all sorts of wine. Yet for all this I did not require the bread of the governor, because the bondage was heavy upon this people.
* `Neh 12:39` And from above the gate of Ephraim, above the old gate, above the fish-gate, the tower of Hananeel, and the tower of Meah, even to the *_sheep_*-gate. And they stood still in the prison-gate.
* `Job 1:3` His substance also was seven thousand *_sheep_*, three thousand camels, five hundred yoke of oxen, five hundred female donkeys, and a very great household. This man was the greatest of all the men of the east.
* `Job 1:16` While he was still speaking, another also came, saying, "The fire of God has fallen from heaven and has burned up the *_sheep_* and the servants and consumed them, and only I have escaped alone to tell you."
* `Job 31:20` If his loins have not blessed me and if he has not been warmed with the fleece of my *_sheep_*,
* `Job 42:12` Thus the LORD blessed the latter end of Job more than his beginning, for he had fourteen thousand *_sheep_*, six thousand camels, one thousand yoke of oxen, and one thousand female donkeys.
* `Psa 8:7` All *_sheep_* and oxen and even the beasts of the field,
* `Psa 44:11` You have given us like *_sheep_* appointed for food and scattered us among the heathen.
* `Psa 44:22` Indeed, for your sake we are killed all the day long. We are counted as *_sheep_* for the slaughter.
* `Psa 49:14` Like *_sheep_* they are laid in the grave. Death shall feed on them. The upright shall have dominion over them in the morning. Their beauty shall consume in the grave from their dwelling.
* `Psa 68:13` Though you have lain among the *_sheep_*-folds, the wings of a dove are covered with silver, and her feathers with yellow gold.
* `Psa 74:1` [Maschil of Asaph.] O God, why have you cast us off forever? Why does your anger smoke against the *_sheep_* of your pasture?
* `Psa 78:52` But made his own people to go forth like *_sheep_* and guided them in the wilderness like a flock.
* `Psa 78:70` He also chose David his servant and took him from the *_sheep_*-folds.
* `Psa 79:13` So we your people and *_sheep_* of your pasture will give you thanks forever. We will show forth your praise to all generations.
* `Psa 95:7` For he is our God, and we are the people of his pasture and the *_sheep_* of his hand. Today, if you will hear his voice,
* `Psa 100:3` Know that the LORD himself is God. It is he who has made us, and not we ourselves. We are his people and the *_sheep_* of his pasture.
* `Psa 119:176` I have gone astray like a lost *_sheep_*. Seek your servant, for I do not forget your commandments.
* `Psa 144:13` So that our granaries may be full, affording all manner of store; so that our *_sheep_* may bring forth thousands and ten thousands in our streets;
* `Sos 4:2` Your teeth are like a flock of *_sheep_* that are even shorn, which came up from the washing, all of which bear twins, and not one is barren among them.
* `Sos 6:6` Your teeth are as a flock of *_sheep_* which go up from the washing, of which every one bears twins, and there is not one barren among them.
* `Isa 7:21` And it shall come to pass in that day, that a man shall nourish a young cow and two *_sheep_*.
* `Isa 7:25` And on all hills that are dug with the mattock, the fear of briers and thorns shall not come there, but it shall be for the sending forth of oxen and for the treading of *_sheep_*.
* `Isa 13:14` And it shall be like the chased gazelle and like a *_sheep_* that no man takes up. Every man shall turn to his own people and flee each to his own land.
* `Isa 22:13` And behold, there is joy and gladness, slaying oxen, killing *_sheep_*, eating flesh, and drinking wine. "Let us eat and drink, for tomorrow we shall die."
* `Isa 43:23` You have not brought me the *_sheep_* of your burnt-offerings, neither have you honored me with your sacrifices. I have not caused you to serve with an offering, nor wearied you with incense.
* `Isa 53:6` We have all like *_sheep_* gone astray. We have each turned to his own way, and the LORD has laid on him the iniquity of us all.
* `Isa 53:7` He was oppressed and he was afflicted, yet he did not open his mouth. He is brought as a lamb to the slaughter, and as a *_sheep_* before her shearers is mute, so he did not open his mouth.
* `Jer 12:3` But you, O LORD, know me. You have seen me and tried my heart toward you. Pull them out like *_sheep_* for the slaughter, and prepare them for the day of slaughter.
* `Jer 23:1` "Woe to the pastors who destroy and scatter the *_sheep_* of my pasture!" says the LORD.
* `Jer 50:6` "My people have been lost *_sheep_*. Their shepherds have caused them to go astray. They have turned them away on the mountains. They have gone from mountain to hill. They have forgotten their resting-place.
* `Jer 50:17` "Israel is a scattered *_sheep_*. The lions have driven him away. First the king of Assyria has devoured him, and last this Nebuchadnezzar king of Babylon has broken his bones.
* `Ezk 34:6` My *_sheep_* wandered through all the mountains and upon every high hill. My flock was even scattered upon all the face of the earth, and no one searched or sought for them."'"
* `Ezk 34:11` For thus says the Lord GOD: "Behold, I, even I, will both search for my *_sheep_* and seek them out.
* `Ezk 34:12` As a shepherd seeks out his flock in the day that he is among his *_sheep_* that are scattered, so I will seek out my *_sheep_* and will deliver them out of all places where they have been scattered in the cloudy and dark day.
* `Ezk 34:17` "And as for you, O my flock, thus says the Lord GOD: 'Behold, I judge between *_sheep_* and *_sheep_*, between the rams and the male goats.
* `Ezk 34:20` Therefore, thus says the Lord GOD to them: "Behold, I, even I, will judge between the fat *_sheep_* and between the lean *_sheep_*.
* `Ezk 34:22` Therefore I will save my flock, and they shall no longer be a prey. And I will judge between *_sheep_* and *_sheep_*.
* `Hos 12:12` And Jacob fled into the country of Syria. And Israel served to get a wife, and for a wife he kept *_sheep_*.
* `Joe 1:18` How the beasts groan! The herds of livestock are perplexed because they have no pasture. Even the flocks of *_sheep_* are made desolate.
* `Mic 2:12` I will surely assemble, O Jacob, all of you. I will surely gather the remnant of Israel. I will put them together as the *_sheep_* of Bozrah, as the flock in the midst of their fold. They shall make great noise by reason of the multitude of men.
* `Mic 5:8` And the remnant of Jacob shall be among the Gentiles in the midst of many people as a lion among the beasts of the forest, as a young lion among the flocks of *_sheep_*, who, if he goes through, both treads down and tears in pieces, and no one can deliver.
* `Zch 13:7` "Awake, O sword, against my shepherd and against the man who is my fellow," says the LORD of hosts. "Smite the shepherd and the *_sheep_* shall be scattered. And I will turn my hand upon the little ones.
* `Mth 7:15` "Beware of false prophets who come to you in *_sheep_*'s clothing, but inwardly they are ravening wolves.
* `Mth 9:36` But when he saw the multitudes, he was moved with compassion for them because they fainted and were scattered abroad as *_sheep_* having no shepherd.
* `Mth 10:6` But rather go to the lost *_sheep_* of the house of Israel.
* `Mth 10:16` "Behold, I send you forth as *_sheep_* in the midst of wolves; therefore, be wise as serpents and innocent as doves.
* `Mth 12:11` And he said to them, "What man is there among you who has a *_sheep_*, and if it falls into a pit on the sabbath, will not lay hold upon it and lift it out?
* `Mth 12:12` How much then is a man better than a *_sheep_*? Therefore, it is lawful to do good on the sabbath days."
* `Mth 15:24` But he answered and said, "I was not sent except to the lost *_sheep_* of the house of Israel."
* `Mth 18:12` "What do you think? If a man has one hundred *_sheep_*, and one of them has gone astray, does he not leave the ninety-nine, go to the mountains, and seek that which has gone astray?
* `Mth 18:13` And if he finds it, truly I say to you, he rejoices more over that *_sheep_* than over the ninety-nine which did not go astray.
* `Mth 25:32` And before him all nations shall be gathered, and he will separate them one from another, as a shepherd divides his *_sheep_* from the goats.
* `Mth 25:33` And he will set the *_sheep_* on his right hand, but the goats on the left.
* `Mth 26:31` Then Jesus says to them, "All of you shall be offended because of me this night, for it is written, 'I will smite the shepherd, and the *_sheep_* of the flock shall be scattered abroad.'
* `Mrk 6:34` And Jesus, when he came out, saw many people and was moved with compassion toward them because they were as *_sheep_* not having a shepherd. And he began to teach them many things.
* `Mrk 14:27` And Jesus says to them, "All of you will be offended because of me this night, for it is written, 'I will "smite the shepherd, and the *_sheep_* shall be scattered."'
* `Luk 15:4` "What man of you having one hundred *_sheep_*, if he loses one of them, does not leave the ninety-nine in the wilderness and go after that which is lost until he finds it?
* `Luk 15:6` And when he comes home, he calls together his friends and neighbors, saying to them, 'Rejoice with me, for I have found my *_sheep_* which was lost.'
* `Luk 17:7` "But which of you, having a servant plowing or feeding *_sheep_*, will say to him immediately when he has come from the field, 'Go and sit down to eat'?
* `Jhn 2:14` And he found in the temple those who sold oxen, *_sheep_*, and doves, and the changers of money sitting.
* `Jhn 2:15` And when he had made a scourge of small cords, he drove them all out of the temple, with the *_sheep_* and the oxen, and poured out the changers' money and overthrew the tables,
* `Jhn 5:2` Now there is a pool in Jerusalem by the *_sheep_* market, which is called in the Hebrew language, Bethesda, having five porches.
* `Jhn 10:1` "Truly, truly, I say to you, he who does not enter by the door into the *_sheep_*-fold, but climbs up some other way, the same is a thief and a robber.
* `Jhn 10:2` But he who enters by the door is the shepherd of the *_sheep_*.
* `Jhn 10:3` To him the gatekeeper opens, and the *_sheep_* hear his voice. And he calls his own *_sheep_* by name and leads them out.
* `Jhn 10:4` And when he puts forth his own *_sheep_*, he goes before them, and the *_sheep_* follow him, for they know his voice.
* `Jhn 10:7` Then Jesus said to them again, "Truly, truly, I say to you, I am the door of the *_sheep_*.
* `Jhn 10:8` All who ever came before me are thieves and robbers, but the *_sheep_* did not hear them.
* `Jhn 10:11` "I am the good shepherd. The good shepherd gives his life for the *_sheep_*.
* `Jhn 10:12` But he who is a hireling and not the shepherd, who does not own the *_sheep_*, sees the wolf coming and leaves the *_sheep_* and flees, and the wolf catches them and scatters the *_sheep_*.
* `Jhn 10:13` The hireling flees because he is a hireling and does not care for the *_sheep_*.
* `Jhn 10:15` Even as the Father knows me and I know the Father. And I lay down my life for the *_sheep_*.
* `Jhn 10:16` And I have other *_sheep_* which are not of this fold. I must bring them also, and they shall hear my voice. And there shall be one fold and one shepherd.
* `Jhn 10:26` But you do not believe because you are not among my *_sheep_*, as I said to you.
* `Jhn 10:27` My *_sheep_* hear my voice, and I know them. They follow me,
* `Jhn 21:16` He says to him again the second time, "Simon son of Jonah, do you love me?" He says to him, "Yes, Lord. You know that I love you." He says to him, "Feed my *_sheep_*."
* `Jhn 21:17` He says to him the third time, "Simon son of Jonah, do you love me?" Peter was grieved because he said to him the third time, "Do you love me?" And he said to him, "Lord, you know all things. You know that I love you." Jesus says to him, "Feed my *_sheep_*.
* `Act 8:32` The place of the Scripture which he read was this: "He was led as a *_sheep_* to the slaughter, and as a lamb before his shearer is mute, so he did not open his mouth.
* `Rom 8:36` As it is written, "For your sake we are killed all the day long. We are accounted as *_sheep_* for the slaughter."
* `Heb 11:37` They were stoned. They were sawn apart. They were tempted. They were slain with the sword. They wandered around in *_sheep_*-skins and goat-skins, being destitute, afflicted, tormented
* `Heb 13:20` Now may the God of peace, who brought back from the dead our Lord Jesus, that great Shepherd of the *_sheep_*, through the blood of the everlasting covenant,
* `1Pe 2:25` For you were as *_sheep_* going astray, but are now returned to the Shepherd and Overseer of your souls.
* `Rev 18:13` Cinnamon, odors, ointments, frankincense, wine, oil, fine flour, wheat, beasts, *_sheep_*, horses, chariots, slaves, and souls of men.

_195 verses containing SHEEP_

== SHEEP-FOLD

* `2Sa 7:8` "Now therefore, thus you shall say to my servant David: 'Thus says the LORD of hosts: "I took you from the *_sheep-fold_*, from following the sheep, to be ruler over my people, over Israel.
* `1Ch 17:7` Now therefore, thus you shall say to my servant David: 'Thus says the LORD of hosts: "I took you from the *_sheep-fold_*, even from following the sheep, so that you should be ruler over my people Israel.
* `Jhn 10:1` "Truly, truly, I say to you, he who does not enter by the door into the *_sheep-fold_*, but climbs up some other way, the same is a thief and a robber.

_3 verses containing SHEEP-FOLD_

== SHEEP-FOLDS

* `Num 32:16` And they came near to him and said, "We will build *_sheep-folds_* here for our livestock and cities for our little ones,
* `Jdg 5:16` Why did you abide among the *_sheep-folds_* to hear the bleatings of the flocks? For the divisions of Reuben there were great searchings of heart.
* `1Sa 24:3` And he came to the *_sheep-folds_* by the way, where there was a cave, and Saul went in to cover his feet. And David and his men remained in the innermost parts of the cave.
* `Psa 68:13` Though you have lain among the *_sheep-folds_*, the wings of a dove are covered with silver, and her feathers with yellow gold.
* `Psa 78:70` He also chose David his servant and took him from the *_sheep-folds_*.

_5 verses containing SHEEP-FOLDS_

== SHEEP-GATE

* `Neh 3:1` Then Eliashib the high priest arose with his brothers the priests, and they built the *_sheep-gate_*. They sanctified it and set up its doors. Even to the tower of Meah they sanctified it, to the tower of Hananeel.
* `Neh 3:32` And between the ascent of the corner to the *_sheep-gate_* the goldsmiths and the merchants repaired.
* `Neh 12:39` And from above the gate of Ephraim, above the old gate, above the fish-gate, the tower of Hananeel, and the tower of Meah, even to the *_sheep-gate_*. And they stood still in the prison-gate.

_3 verses containing SHEEP-GATE_

== SHEEP-MASTER

* `2Ki 3:4` And Mesha king of Moab was a *_sheep-master_*, and he rendered to the king of Israel one hundred thousand lambs and one hundred thousand rams, with the wool.

_1 verse containing SHEEP-MASTER_

== SHEEP-SHEARERS

* `Gen 38:12` And in process of time, the daughter of Shuah, Judah's wife, died. And Judah was comforted and went up to his *_sheep-shearers_* at Timnath—he and his friend Hirah the Adullamite.
* `2Sa 13:23` And it came to pass after two full years, that Absalom had *_sheep-shearers_* in Baal-hazor, which is beside Ephraim, and Absalom invited all the king's sons.
* `2Sa 13:24` And Absalom came to the king and said, "Behold now, your servant has *_sheep-shearers_*. Let the king, I implore you, and his servants go with your servant."

_3 verses containing SHEEP-SHEARERS_

== SHEEP-SKINS

* `Heb 11:37` They were stoned. They were sawn apart. They were tempted. They were slain with the sword. They wandered around in *_sheep-skins_* and goat-skins, being destitute, afflicted, tormented

_1 verse containing SHEEP-SKINS_

== SHEET

* `Act 10:11` And saw heaven opened and a certain vessel descending to him like a great *_sheet_* knit at the four corners being let down to the earth,
* `Act 11:5` "I was in the city of Joppa praying, and in a trance I saw a vision: a certain vessel descending, like a great *_sheet_*, let down from heaven by four corners, and it even came to me,

_2 verses containing SHEET_

== SHEETS

* `Jdg 14:12` And Samson said to them, "I will now propose a riddle to you. If you can certainly declare it to me within the seven days of the feast and find it out, then I will give you thirty *_sheets_* and thirty changes of garments.
* `Jdg 14:13` But if you cannot declare it to me, then you shall give me thirty *_sheets_* and thirty changes of garments." And they said to him, "Propose your riddle so that we may hear it."

_2 verses containing SHEETS_

== SHEHARIAH

* `1Ch 8:26` And Shamsherai, *_Shehariah_*, Athaliah,

_1 verse containing SHEHARIAH_

== SHEKEL

* `Gen 24:22` And it came to pass as the camels had finished drinking, that the man took a golden earring weighing half a *_shekel_* and two bracelets for her hands weighing ten shekels of gold,
* `Exo 30:13` This they shall give, everyone who passes among those who are numbered: half a *_shekel_* after the *_shekel_* of the sanctuary (a *_shekel_* is twenty gerahs). A half *_shekel_* shall be the offering of the LORD.
* `Exo 30:15` The rich shall not give more and the poor shall not give less than half a *_shekel_* when they give an offering to the LORD to make an atonement for your souls.
* `Exo 30:24` Of cassia five hundred shekels (after the *_shekel_* of the sanctuary), and of olive-oil a hin.
* `Exo 38:24` All the gold that was occupied for the work in all the work of the holy place, even the gold of the offering, was twenty-nine talents and seven hundred and thirty shekels, after the *_shekel_* of the sanctuary.
* `Exo 38:25` And the silver of those who were numbered of the congregation was one hundred talents and one thousand seven hundred and seventy-five shekels, after the *_shekel_* of the sanctuary—
* `Exo 38:26` A bekah for every man (that is, half a *_shekel_*, after the *_shekel_* of the sanctuary), for everyone who went to be numbered, from twenty years old and upward, for six hundred and three thousand five hundred and fifty men.
* `Lev 5:15` "If a soul commits a trespass and sins through ignorance in the holy things of the LORD, then he shall bring for his trespass to the LORD a ram without blemish out of the flocks, with your estimation in shekels of silver after the *_shekel_* of the sanctuary, for a trespass-offering.
* `Lev 27:3` And your estimation of a male from twenty years old even to sixty years old, even your estimation shall be fifty shekels of silver after the *_shekel_* of the sanctuary.
* `Lev 27:25` And all your estimations shall be according to the *_shekel_* of the sanctuary. Twenty gerahs shall be the *_shekel_*.
* `Num 3:47` You shall even take five shekels apiece by the poll. After the *_shekel_* of the sanctuary you shall take them (the *_shekel_* is twenty gerahs).
* `Num 3:50` From the first-born of the children of Israel he took the money: one thousand three hundred and sixty-five shekels after the *_shekel_* of the sanctuary.
* `Num 7:13` And his offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them were full of fine flour mingled with oil for a food-offering;
* `Num 7:19` He offered for his offering one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:25` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:31` His offering was one silver charger, of the weight of one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:37` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:43` His offering was one silver charger, of the weight of one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:49` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:55` His offering was one silver charger of the weight of one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:61` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:67` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:73` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:79` His offering was one silver charger, the weight of which was one hundred and thirty shekels, and one silver bowl of seventy shekels, after the *_shekel_* of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:85` Each charger of silver weighing one hundred and thirty shekels, each bowl seventy; all the silver vessels weighed two thousand and four hundred shekels, after the *_shekel_* of the sanctuary;
* `Num 7:86` Twelve golden spoons full of incense weighing ten shekels apiece, after the *_shekel_* of the sanctuary; all the gold of the spoons was one hundred and twenty shekels;
* `Num 18:16` And those who are to be redeemed from a month old you shall redeem, according to your estimation, for the money of five shekels, after the *_shekel_* of the sanctuary, which is twenty gerahs.
* `1Sa 9:8` And the servant answered Saul again and said, "Behold, I have here at hand the fourth part of a *_shekel_* of silver. I will give that to the man of God to tell us our way."
* `2Ki 7:1` Then Elisha said, "Hear the word of the LORD. Thus says the LORD: 'Tomorrow about this time a measure of fine flour shall be sold for a *_shekel_* and two measures of barley for a *_shekel_* in the gate of Samaria.'"
* `2Ki 7:16` And the people went out and plundered the tents of the Syrians. So a measure of fine flour was sold for a *_shekel_* and two measures of barley for a *_shekel_*, according to the word of the LORD.
* `2Ki 7:18` And it came to pass as the man of God had spoken to the king, saying, "Two measures of barley for a *_shekel_* and a measure of fine flour for a *_shekel_* shall be tomorrow about this time in the gate of Samaria."
* `Neh 10:32` We also made ordinances for ourselves to charge ourselves yearly with the third part of a *_shekel_* for the service of the house of our God:
* `Ezk 45:12` And the *_shekel_* shall be twenty gerahs. Twenty shekels, twenty-five shekels, fifteen shekels, shall be your maneh.
* `Amo 8:5` Saying, 'When will the new moon be gone so that we may sell grain, and the sabbath so that we may set forth wheat, making the ephah small and the *_shekel_* great, and falsifying the balances by deceit,

_34 verses containing SHEKEL_

== SHEKELS

* `Gen 23:15` "My lord, listen to me. The land is worth four hundred *_shekels_* of silver. What is that between you and me? Therefore, bury your dead."
* `Gen 23:16` And Abraham listened to Ephron. And Abraham weighed to Ephron the silver which he had named in the audience of the sons of Heth, four hundred *_shekels_* of silver, current money with the merchant.
* `Gen 24:22` And it came to pass as the camels had finished drinking, that the man took a golden earring weighing half a shekel and two bracelets for her hands weighing ten *_shekels_* of gold,
* `Exo 21:32` If the ox gores a man-servant or woman-servant, he shall give to their master thirty *_shekels_* of silver, and the ox shall be stoned.
* `Exo 30:23` "Take also for yourself principal spices: of pure myrrh five hundred *_shekels_*, of sweet cinnamon half as much (even two hundred and fifty *_shekels_*), of sweet calamus two hundred and fifty *_shekels_*,
* `Exo 30:24` Of cassia five hundred *_shekels_* (after the shekel of the sanctuary), and of olive-oil a hin.
* `Exo 38:24` All the gold that was occupied for the work in all the work of the holy place, even the gold of the offering, was twenty-nine talents and seven hundred and thirty *_shekels_*, after the shekel of the sanctuary.
* `Exo 38:25` And the silver of those who were numbered of the congregation was one hundred talents and one thousand seven hundred and seventy-five *_shekels_*, after the shekel of the sanctuary—
* `Exo 38:28` And from the one thousand seven hundred and seventy-five *_shekels_* he made hooks for the pillars, overlaid their capitals, and filleted them.
* `Exo 38:29` And the brass of the offering was seventy talents and two thousand and four hundred *_shekels_*.
* `Lev 5:15` "If a soul commits a trespass and sins through ignorance in the holy things of the LORD, then he shall bring for his trespass to the LORD a ram without blemish out of the flocks, with your estimation in *_shekels_* of silver after the shekel of the sanctuary, for a trespass-offering.
* `Lev 27:3` And your estimation of a male from twenty years old even to sixty years old, even your estimation shall be fifty *_shekels_* of silver after the shekel of the sanctuary.
* `Lev 27:4` And if it is a female, then your estimation shall be thirty *_shekels_*.
* `Lev 27:5` And if it is from five years old even to twenty years old, then your estimation shall be of the male twenty *_shekels_*, and for the female ten *_shekels_*.
* `Lev 27:6` And if it is from a month old even to five years old, then your estimation of a male shall be five *_shekels_* of silver, and for a female your estimation shall be three *_shekels_* of silver.
* `Lev 27:7` And if it is from sixty years old and above, if a male, then your estimation shall be fifteen *_shekels_*, and for a female, ten *_shekels_*.
* `Lev 27:16` 'And if a man sanctifies to the LORD some part of a field of his possession, then your estimation shall be according to its seed. A homer of barley seed shall be valued at fifty *_shekels_* of silver.
* `Num 3:47` You shall even take five *_shekels_* apiece by the poll. After the shekel of the sanctuary you shall take them (the shekel is twenty gerahs).
* `Num 3:50` From the first-born of the children of Israel he took the money: one thousand three hundred and sixty-five *_shekels_* after the shekel of the sanctuary.
* `Num 7:13` And his offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them were full of fine flour mingled with oil for a food-offering;
* `Num 7:14` One spoon of ten *_shekels_* of gold, full of incense;
* `Num 7:19` He offered for his offering one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:20` One spoon of gold of ten *_shekels_*, full of incense;
* `Num 7:25` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:26` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:31` His offering was one silver charger, of the weight of one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:32` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:37` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:38` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:43` His offering was one silver charger, of the weight of one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:44` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:49` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:50` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:55` His offering was one silver charger of the weight of one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:56` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:61` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:62` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:67` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:68` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:73` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:74` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:79` His offering was one silver charger, the weight of which was one hundred and thirty *_shekels_*, and one silver bowl of seventy *_shekels_*, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:80` One golden spoon of ten *_shekels_*, full of incense;
* `Num 7:85` Each charger of silver weighing one hundred and thirty *_shekels_*, each bowl seventy; all the silver vessels weighed two thousand and four hundred *_shekels_*, after the shekel of the sanctuary;
* `Num 7:86` Twelve golden spoons full of incense weighing ten *_shekels_* apiece, after the shekel of the sanctuary; all the gold of the spoons was one hundred and twenty *_shekels_*;
* `Num 18:16` And those who are to be redeemed from a month old you shall redeem, according to your estimation, for the money of five *_shekels_*, after the shekel of the sanctuary, which is twenty gerahs.
* `Num 31:52` And all the gold of the offering that they offered to the LORD, from the captains of thousands and from the captains of hundreds, was sixteen thousand seven hundred and fifty *_shekels_*.
* `Deu 22:19` And they shall amerce him one hundred *_shekels_* of silver and give them to the father of the young woman, because he has brought an evil name upon a virgin of Israel. And she shall be his wife. He may not put her away all his days.
* `Deu 22:29` Then the man who lay with her shall give to the young woman's father fifty *_shekels_* of silver, and she shall be his wife. Because he has humbled her, he may not put her away all his days.
* `Jsh 7:21` When I saw among the plunder a fine Babylonish garment, two hundred *_shekels_* of silver, and a wedge of gold of fifty *_shekels_* weight, I coveted them and took them, and behold, they are hid in the earth in the midst of my tent, with the silver under it."
* `Jdg 8:26` And the weight of the golden earrings that he requested was one thousand and seven hundred *_shekels_* of gold, besides ornaments, collars, and purple clothing that was on the kings of Midian, and besides the chains that were around their camels' necks.
* `Jdg 17:2` And he said to his mother, "The eleven hundred *_shekels_* of silver that were taken from you, about which you cursed and also spoke about in my ears, behold, the silver is with me. I took it." And his mother said, "Blessed are you of the LORD, my son."
* `Jdg 17:3` And when he had restored the eleven hundred *_shekels_* of silver to his mother, his mother said, "I had wholly dedicated the silver to the LORD from my hand for my son to make an engraved image and a molten image. Now therefore, I will restore it to you."
* `Jdg 17:4` So he restored the money to his mother, and his mother took two hundred *_shekels_* of silver and gave them to the founder, who made from it an engraved image and a molten image. And they were in the house of Micah.
* `Jdg 17:10` And Micah said to him, "Dwell with me and be to me a father and a priest, and I will give you ten *_shekels_* of silver by the year, a suit of apparel, and your food." So the Levite went in.
* `1Sa 17:5` And he had a helmet of brass upon his head and he was armed with a coat of mail, and the weight of the coat was five thousand *_shekels_* of brass.
* `1Sa 17:7` And the staff of his spear was like a weaver's beam and his spear's head weighed six hundred *_shekels_* of iron. And someone bearing a shield went before him.
* `2Sa 14:26` And when he polled his head (for it was at every year's end that he polled it; because the hair was heavy on him, therefore he polled it), he weighed the hair of his head at two hundred *_shekels_* after the king's weight.
* `2Sa 18:11` And Joab said to the man who told him, "And behold, you saw him, and why did you not smite him there to the ground? And I would have given you ten *_shekels_* of silver and a girdle."
* `2Sa 18:12` And the man said to Joab, "Though I should receive one thousand *_shekels_* of silver in my hand, yet I would not put forth my hand against the king's son. For in our hearing the king charged you, Abishai, and Ittai, saying, 'Beware that no one touch the young man Absalom.'
* `2Sa 21:16` And Ishbi-benob, who was among the sons of the giant, the weight of whose spear was three hundred *_shekels_* of brass in weight, he being girded with a new sword, thought to have slain David.
* `2Sa 24:24` And the king said to Araunah, "No, but I will surely buy it from you at a price. I will not offer burnt-offerings to the LORD my God from that which costs me nothing." So David bought the threshing-floor and the oxen for fifty *_shekels_* of silver.
* `1Ki 10:16` And king Solomon made two hundred bucklers of beaten gold. Six hundred *_shekels_* of gold went to one buckler.
* `1Ki 10:29` And a chariot came up and went out of Egypt for six hundred *_shekels_* of silver, and a horse for one hundred and fifty. And in this manner they exported them to all the kings of the Hittites and to the kings of Syria.
* `2Ki 15:20` And Menahem exacted the money from Israel, even from all the mighty men of wealth, from each man fifty *_shekels_* of silver, to give to the king of Assyria. So the king of Assyria turned back and did not stay there in the land.
* `1Ch 21:25` So David gave to Ornan for the place six hundred *_shekels_* of gold by weight.
* `2Ch 1:17` And they fetched up and brought out of Egypt a chariot for six hundred *_shekels_* of silver and a horse for one hundred and fifty. And so they brought out horses for all the kings of the Hittites and for the kings of Syria by their means.
* `2Ch 3:9` And the weight of the nails was fifty *_shekels_* of gold. And he overlaid the upper chambers with gold.
* `2Ch 9:15` And king Solomon made two hundred bucklers of beaten gold. Six hundred *_shekels_* of beaten gold went to each buckler.
* `2Ch 9:16` And three hundred shields he made of beaten gold. Three hundred *_shekels_* of gold went to each shield. And the king put them in the house of the forest of Lebanon.
* `Neh 5:15` But the former governors who had been before me were burdensome to the people and had taken from them bread and wine, besides forty *_shekels_* of silver. And even their servants bore rule over the people. But I did not do so, because of the fear of God.
* `Jer 32:9` "And I bought the field of Hanameel my uncle's son that was in Anathoth and weighed him the money, even seventeen *_shekels_* of silver.
* `Ezk 4:10` And your food which you shall eat shall be by weight, twenty *_shekels_* a day. From time to time you shall eat it.
* `Ezk 45:12` And the shekel shall be twenty gerahs. Twenty *_shekels_*, twenty-five *_shekels_*, fifteen *_shekels_*, shall be your maneh.

_74 verses containing SHEKELS_

== SHELAH

* `Gen 38:5` And she yet again conceived and bore a son, and called his name *_Shelah_*. And he was at Chezib when she bore him.
* `Gen 38:11` Then Judah said to Tamar his daughter-in-law, "Remain a widow at your father's house until *_Shelah_* my son is grown," for he said, "Lest perhaps he die also as his brothers did." And Tamar went and dwelt in her father's house.
* `Gen 38:14` And she took off her widow's garments and covered herself with a veil, wrapped herself, and sat in an open place, which is by the way to Timnath, for she saw that *_Shelah_* was grown and she was not given to him for a wife.
* `Gen 38:26` And Judah acknowledged them and said, "She has been more righteous than I have because I did not give her to *_Shelah_* my son." And he knew her again no more.
* `Gen 46:12` And the sons of Judah: Er, Onan, *_Shelah_*, Pharez, and Zerah, but Er and Onan died in the land of Canaan. And the sons of Pharez were Hezron and Hamul.
* `Num 26:20` And these were the sons of Judah after their families: of *_Shelah_*, the family of the Shelanites; of Pharez, the family of the Pharezites; of Zerah, the family of the Zarhites.
* `1Ch 1:18` And Arphaxad begot *_Shelah_*, and *_Shelah_* begot Eber.
* `1Ch 1:24` Shem, Arphaxad, *_Shelah_*,
* `1Ch 2:3` The sons of Judah: Er, Onan, and *_Shelah_*. These three were born to him by the daughter of Shua the Canaanitess. And Er, the first-born of Judah, was evil in the sight of the LORD, and he slew him.
* `1Ch 4:21` The sons of *_Shelah_* the son of Judah were Er the father of Lecah, Laadah the father of Mareshah, the families of the house of those who wrought fine linen, of the house of Ashbea,

_10 verses containing SHELAH_

== SHELANITES

* `Num 26:20` And these were the sons of Judah after their families: of Shelah, the family of the *_Shelanites_*; of Pharez, the family of the Pharezites; of Zerah, the family of the Zarhites.

_1 verse containing SHELANITES_

== SHELEMIAH

* `1Ch 26:14` And the lot eastward fell to *_Shelemiah_*. Then for Zechariah his son, a wise counselor, they cast lots, and his lot came out northward.
* `Ezr 10:39` *_Shelemiah_*, Nathan, Adaiah,
* `Ezr 10:41` Azareel, *_Shelemiah_*, Shemariah,
* `Neh 3:30` After him Hananiah the son of *_Shelemiah_* and Hanun the sixth son of Zalaph repaired another piece. After him Meshullam the son of Berechiah repaired over against his chamber.
* `Neh 13:13` And I made treasurers over the treasuries: *_Shelemiah_* the priest, Zadok the scribe, and of the Levites, Pedaiah, and next to them was Hanan the son of Zaccur, the son of Mattaniah, for they were accounted faithful. Their office was to distribute to their brothers.
* `Jer 36:14` Therefore, all the princes sent Jehudi the son of Nethaniah, the son of *_Shelemiah_*, the son of Cushi, to Baruch, saying, "Take in your hand the scroll in which you have read in the ears of the people and come." So Baruch the son of Neriah took the scroll in his hand and came to them.
* `Jer 36:26` But the king commanded Jerahmeel the son of Hammelech, Seraiah the son of Azriel, and *_Shelemiah_* the son of Abdeel to take Baruch the scribe and Jeremiah the prophet, but the LORD hid them.
* `Jer 37:3` And Zedekiah the king sent Jehucal the son of *_Shelemiah_* and Zephaniah the son of Maaseiah the priest to the prophet Jeremiah, saying, "Pray now to the LORD our God for us."
* `Jer 37:13` And when he was in the gate of Benjamin, a captain of the ward was there, whose name was Irijah, the son of *_Shelemiah_*, the son of Hananiah, and he took Jeremiah the prophet, saying, "You are falling away to the Chaldeans."
* `Jer 38:1` Then Shephatiah the son of Mattan, Gedaliah the son of Pashur, Jucal the son of *_Shelemiah_*, and Pashur the son of Malchiah heard the words that Jeremiah had spoken to all the people, saying,

_10 verses containing SHELEMIAH_

== SHELEPH

* `Gen 10:26` And Joktan begot Almodad, *_Sheleph_*, Hazarmaveth, Jerah,
* `1Ch 1:20` And Joktan begot Almodad, *_Sheleph_*, Hazarmaveth, Jerah,

_2 verses containing SHELEPH_

== SHELESH

* `1Ch 7:35` And the sons of his brother Helem: Zophah, Imna, *_Shelesh_*, and Amal.

_1 verse containing SHELESH_

== SHELOMI

* `Num 34:27` The prince of the tribe of the children of Asher, Ahihud the son of *_Shelomi_*;

_1 verse containing SHELOMI_

== SHELOMITH

* `Lev 24:11` And the Israelite woman's son blasphemed the name of the LORD and cursed. And they brought him to Moses (and his mother's name was *_Shelomith_*, the daughter of Dibri, of the tribe of Dan),
* `1Ch 3:19` And the sons of Pedaiah were Zerubbabel and Shimei. And the sons of Zerubbabel: Meshullam and Hananiah, and *_Shelomith_* was their sister;
* `1Ch 23:9` The sons of Shimei: *_Shelomith_*, Haziel, and Haran, three. These were the chief of the fathers of Laadan.
* `1Ch 23:18` The son of Izhar: *_Shelomith_* the chief.
* `1Ch 26:25` And his brothers, by Eliezer, were Rehabiah his son, Jeshaiah his son, Joram his son, Zichri his son, and *_Shelomith_* his son.
* `1Ch 26:26` This *_Shelomith_* and his brothers were over all the treasures of the dedicated things which David the king, the chief fathers who were the captains over thousands and hundreds, and the captains of the host had dedicated.
* `1Ch 26:28` And all that Samuel the seer, Saul the son of Kish, Abner the son of Ner, and Joab the son of Zeruiah had dedicated, and whoever had dedicated anything, it was under the hand of *_Shelomith_* and of his brothers.
* `2Ch 11:20` And after her he took Maachah the daughter of Absalom, who bore him Abijah, Attai, Ziza, and *_Shelomith_*.
* `Ezr 8:10` Of the sons of *_Shelomith_*: the son of Josiphiah, and with him one hundred and sixty males.

_9 verses containing SHELOMITH_

== SHELOMOTH

* `1Ch 24:22` Of the Izharites: *_Shelomoth_*. Of the sons of *_Shelomoth_*: Jahath.

_1 verse containing SHELOMOTH_

== SHELTER

* `Job 24:8` They are wet with the showers of the mountains and embrace the rock for lack of a *_shelter_*.
* `Psa 61:3` For you have been a *_shelter_* for me and a strong tower from the enemy.

_2 verses containing SHELTER_

== SHELTERED

* `Act 27:16` And running under the *_sheltered_* side of a small island which is called Clauda, we were able, with difficulty, to secure the boat.

_1 verse containing SHELTERED_

== SHELUMIEL

* `Num 1:6` Of Simeon, *_Shelumiel_* the son of Zurishaddai;
* `Num 2:12` And those who pitch by him shall be the tribe of Simeon, and the captain of the children of Simeon shall be *_Shelumiel_* the son of Zurishaddai.
* `Num 7:36` On the fifth day *_Shelumiel_* the son of Zurishaddai, prince of the children of Simeon, offered.
* `Num 7:41` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of *_Shelumiel_* the son of Zurishaddai.
* `Num 10:19` And over the host of the tribe of the children of Simeon was *_Shelumiel_* the son of Zurishaddai.

_5 verses containing SHELUMIEL_

