= SHEM - SHIZA
:toc:

== SHEM

* `Gen 5:32` And Noah was five hundred years old, and Noah begot *_Shem_*, Ham, and Japheth.
* `Gen 6:10` And Noah begot three sons: *_Shem_*, Ham, and Japheth.
* `Gen 7:13` In the same day Noah, along with *_Shem_*, Ham, and Japheth (the sons of Noah), Noah's wife, and the three wives of his sons with them, entered into the ark—
* `Gen 9:18` And the sons of Noah who went forth from the ark were *_Shem_*, Ham, and Japheth. And Ham was the father of Canaan.
* `Gen 9:23` And *_Shem_* and Japheth took a garment, laid it upon both their shoulders, went backward, and covered the nakedness of their father. Their faces were backward and they did not see their father's nakedness.
* `Gen 9:26` And he said, "Blessed be the LORD God of *_Shem_*, and Canaan shall be his servant.
* `Gen 9:27` God shall enlarge Japheth, and he shall dwell in the tents of *_Shem_*, and Canaan shall be his servant."
* `Gen 10:1` Now these are the generations of the sons of Noah: *_Shem_*, Ham, and Japheth. And to them sons were born after the flood.
* `Gen 10:21` To *_Shem_* also, the father of all the children of Eber, the brother of Japheth the elder, even to him children were born.
* `Gen 10:22` The children of *_Shem_*: Elam, Ashur, Arphaxad, Lud, and Aram.
* `Gen 10:31` These are the sons of *_Shem_*, after their families, after their languages, in their lands, after their nations.
* `Gen 11:10` These are the generations of *_Shem_*. *_Shem_* was one hundred years old and begot Arphaxad two years after the flood.
* `Gen 11:11` And *_Shem_* lived after he begot Arphaxad five hundred years and begot sons and daughters.
* `1Ch 1:4` Noah, *_Shem_*, Ham, and Japheth.
* `1Ch 1:17` The sons of *_Shem_*: Elam, Asshur, Arphaxad, Lud, Aram, Uz, Hul, Gether, and Meshech.
* `1Ch 1:24` *_Shem_*, Arphaxad, Shelah,
* `Luk 3:36` Who was the son of Cainan, who was the son of Arphaxad, who was the son of *_Shem_*, who was the son of Noah, who was the son of Lamech,

_17 verses containing SHEM_

== SHEMA

* `Jsh 15:26` Aman, *_Shema_*, Moladah,
* `1Ch 2:43` And the sons of Hebron: Korah, Tappuah, Rekem, and *_Shema_*.
* `1Ch 2:44` And *_Shema_* begot Raham the father of Jorkoam, and Rekem begot Shammai.
* `1Ch 5:8` And Bela the son of Azaz, the son of *_Shema_*, the son of Joel, who dwelt in Aroer, even to Nebo, and Baal-meon.
* `1Ch 8:13` Beriah and *_Shema_* (who were heads of the fathers of the inhabitants of Ajalon, who drove away the inhabitants of Gath),
* `Neh 8:4` And Ezra the scribe stood upon a pulpit of wood, which they had made for this purpose. And beside him stood Mattithiah, *_Shema_*, Anaiah, Urijah, Hilkiah, and Maaseiah on his right hand, and on his left hand, Pedaiah, Mishael, Malchiah, Hashum, Hashbadana, Zechariah, and Meshullam.

_6 verses containing SHEMA_

== SHEMAAH

* `1Ch 12:3` The chief was Ahiezer, then Joash (the sons of *_Shemaah_* the Gibeathite), and Jeziel and Pelet (the sons of Azmaveth), and Berachah and Jehu the Antothite,

_1 verse containing SHEMAAH_

== SHEMAIAH

* `1Ki 12:22` But the word of God came to *_Shemaiah_* the man of God, saying,
* `1Ch 3:22` And the son of Shechaniah: *_Shemaiah_*. And the sons of *_Shemaiah_*: Hattush, Igeal, Bariah, Neariah, and Shaphat, six.
* `1Ch 4:37` Ziza the son of Shiphi, the son of Allon, the son of Jedaiah, the son of Shimri, the son of *_Shemaiah_*—
* `1Ch 5:4` The sons of Joel: *_Shemaiah_* his son, Gog his son, Shimei his son,
* `1Ch 9:14` And of the Levites: *_Shemaiah_* the son of Hasshub, the son of Azrikam, the son of Hashabiah, of the sons of Merari;
* `1Ch 9:16` And Obadiah the son of *_Shemaiah_*, the son of Galal, the son of Jeduthun; and Berechiah the son of Asa, the son of Elkanah, who dwelt in the villages of the Netophathites.
* `1Ch 15:8` Of the sons of Elizaphan: *_Shemaiah_* the chief and his brothers two hundred.
* `1Ch 15:11` And David called for Zadok and Abiathar the priests, for the Levites, for Uriel, Asaiah, Joel, *_Shemaiah_*, Eliel, and Amminadab,
* `1Ch 24:6` And *_Shemaiah_* the son of Nethaneel the scribe, one of the Levites, recorded them before the king, the princes, Zadok the priest, Ahimelech the son of Abiathar, and before the chief of the fathers of the priests and Levites. One principal household being taken for Eleazar and one taken for Ithamar.
* `1Ch 26:4` Moreover, the sons of Obed-edom were *_Shemaiah_* the first-born, Jehozabad the second, Joah the third, Sacar the fourth, Nethaneel the fifth,
* `1Ch 26:6` To *_Shemaiah_* his son, sons were also born who ruled throughout the house of their father, for they were mighty men of valor.
* `1Ch 26:7` The sons of *_Shemaiah_*: Othni, Rephael, Obed, Elzabad (whose brothers were strong men), Elihu, and Semachiah.
* `2Ch 11:2` But the word of the LORD came to *_Shemaiah_* the man of God, saying,
* `2Ch 12:5` Then *_Shemaiah_* the prophet came to Rehoboam and to the princes of Judah who were assembled at Jerusalem because of Shishak, and said to them, "Thus says the LORD: 'You have forsaken me, and therefore, I have also left you in the hand of Shishak.'"
* `2Ch 12:7` And when the LORD saw that they humbled themselves, the word of the LORD came to *_Shemaiah_*, saying, "They have humbled themselves; therefore, I will not destroy them, but I will grant them some deliverance. And my wrath shall not be poured out upon Jerusalem by the hand of Shishak.
* `2Ch 12:15` Now the acts of Rehoboam, first and last, are they not written in the book of *_Shemaiah_* the prophet and of Iddo the seer concerning genealogies? And there were wars between Rehoboam and Jeroboam continually.
* `2Ch 17:8` And with them he sent Levites, even *_Shemaiah_*, Nethaniah, Zebadiah, Asahel, Shemiramoth, Jehonathan, Adonijah, Tobijah, and Tob-adonijah, Levites; and with them Elishama and Jehoram, priests.
* `2Ch 29:14` And of the sons of Heman: Jehiel and Shimei; and of the sons of Jeduthun: *_Shemaiah_* and Uzziel.
* `2Ch 31:15` And under him were Eden, Miniamin, Jeshua, *_Shemaiah_*, Amariah, and Shecaniah, in the cities of the priests, in their set office, to give to their brothers by courses, to the great as well as to the small,
* `2Ch 35:9` And also Conaniah, *_Shemaiah_*, Nethaneel, his brothers, and Hashabiah, Jehiel, and Jozabad, chief of the Levites, gave to the Levites for passover-offerings five thousand small livestock, and five hundred oxen.
* `Ezr 8:13` And of the last sons of Adonikam, whose names are these: Eliphelet, Jeiel, and *_Shemaiah_*, and with them sixty males.
* `Ezr 8:16` Then I sent for Eliezer, for Ariel, for *_Shemaiah_*, for Elnathan, for Jarib, for Elnathan, for Nathan, for Zechariah, and for Meshullam, chief men, and also for Joiarib and for Elnathan, men of understanding.
* `Ezr 10:21` And of the sons of Harim: Maaseiah, Elijah, *_Shemaiah_*, Jehiel, and Uzziah.
* `Ezr 10:31` And of the sons of Harim: Eliezer, Ishijah, Malchiah, *_Shemaiah_*, Shimeon,
* `Neh 3:29` After them Zadok the son of Immer repaired over against his house. After him *_Shemaiah_* the son of Shechaniah, the keeper of the east gate, repaired.
* `Neh 6:10` Afterward, I came to the house of *_Shemaiah_* the son of Delaiah, the son of Mehetabeel, who was shut up. And he said, "Let us meet together in the house of God, within the temple, and let us shut the doors of the temple, for they will come to slay you. Indeed, in the night they will come to slay you."
* `Neh 10:8` Maaziah, Bilgai, and *_Shemaiah_*. These were the priests.
* `Neh 11:15` Also of the Levites: *_Shemaiah_* the son of Hashub, the son of Azrikam, the son of Hashabiah, the son of Bunni;
* `Neh 12:6` *_Shemaiah_*, Joiarib, Jedaiah,
* `Neh 12:18` Of Bilgah, Shammua; of *_Shemaiah_*, Jehonathan;
* `Neh 12:34` Judah, Benjamin, *_Shemaiah_*, Jeremiah,
* `Neh 12:35` And some of the priests' sons with trumpets, namely, Zechariah the son of Jonathan, the son of *_Shemaiah_*, the son of Mattaniah, the son of Michaiah, the son of Zaccur, the son of Asaph;
* `Neh 12:36` And his brothers, *_Shemaiah_*, Azarael, Milalai, Gilalai, Maai, Nethaneel, Judah, and Hanani, with the musical instruments of David the man of God, and Ezra the scribe before them.
* `Neh 12:42` And Maaseiah, *_Shemaiah_*, Eleazar, Uzzi, Jehohanan, Malchijah, Elam, and Ezer. And the singers sang loud with Jezrahiah their overseer.
* `Jer 26:20` And there was also a man who prophesied in the name of the LORD, Urijah the son of *_Shemaiah_* of Kirjath-jearim, who prophesied against this city and against this land according to all the words of Jeremiah.
* `Jer 29:24` Thus you shall also speak to *_Shemaiah_* the Nehelamite, saying,
* `Jer 29:31` "Send to all those of the captivity, saying, 'Thus says the LORD concerning *_Shemaiah_* the Nehelamite: "Because *_Shemaiah_* has prophesied to you, and I did not send him, and he caused you to trust in a lie,"
* `Jer 29:32` Therefore, thus says the LORD: "Behold, I will punish *_Shemaiah_* the Nehelamite and his offspring. He shall not have a man to dwell among this people, neither shall he behold the good that I will do for my people," says the LORD, "because he has taught rebellion against the LORD."'"
* `Jer 36:12` He went down into the king's house, into the scribe's chamber, and behold, all the princes sat there, even Elishama the scribe, Delaiah the son of *_Shemaiah_*, Elnathan the son of Achbor, Gemariah the son of Shaphan, Zedekiah the son of Hananiah, and all the princes.

_39 verses containing SHEMAIAH_

== SHEMARIAH

* `1Ch 12:5` Eluzai, Jerimoth, Bealiah, *_Shemariah_*, Shephatiah the Haruphite,
* `Ezr 10:32` Benjamin, Malluch, and *_Shemariah_*.
* `Ezr 10:41` Azareel, Shelemiah, *_Shemariah_*,

_3 verses containing SHEMARIAH_

== SHEMEBER

* `Gen 14:2` That these made war with Bera king of Sodom, Birsha king of Gomorrah, Shinab king of Admah, *_Shemeber_* king of Zeboiim, and the king of Bela, which is Zoar.

_1 verse containing SHEMEBER_

== SHEMER

* `1Ki 16:24` And he bought the hill of Samaria from *_Shemer_* for two talents of silver. He built on the hill and called the name of the city which he built Samaria, after the name of *_Shemer_*, owner of the hill.

_1 verse containing SHEMER_

== SHEMIDA

* `Num 26:32` Of *_Shemida_*, the family of the Shemidaites; and of Hepher, the family of the Hepherites.
* `Jsh 17:2` There was also a lot for the rest of the children of Manasseh by their families: for the children of Abiezer, for the children of Helek, for the children of Asriel, for the children of Shechem, for the children of Hepher, and for the children of *_Shemida_*. These were the male children of Manasseh the son of Joseph by their families.
* `1Ch 7:19` And the sons of *_Shemida_* were Ahian, Shechem, Likhi, and Aniam.

_3 verses containing SHEMIDA_

== SHEMIDAITES

* `Num 26:32` Of Shemida, the family of the *_Shemidaites_*; and of Hepher, the family of the Hepherites.

_1 verse containing SHEMIDAITES_

== SHEMINITH

* `1Ch 15:21` And Mattithiah, Elipheleh, Mikneiah, Obed-edom, Jeiel, and Azaziah with harps on the *_Sheminith_* to excel.
* `Psa 6:1` [To the Chief Musician on Neginoth upon *_Sheminith_*. A Psalm of David.] O LORD, do not rebuke me in your anger, neither chasten me in your hot displeasure.
* `Psa 12:1` [To the Chief Musician upon *_Sheminith_*. A Psalm of David.] Help, LORD, for the godly man ceases, for the faithful fail from among the children of men.

_3 verses containing SHEMINITH_

== SHEMIRAMOTH

* `1Ch 15:18` And with them their brothers of the second degree: Zechariah, Ben, Jaaziel, *_Shemiramoth_*, Jehiel, Unni, Eliab, Benaiah, Maaseiah, Mattithiah, Elipheleh, Mikneiah, Obed-edom, and Jeiel, the gatekeepers.
* `1Ch 15:20` And Zechariah, Aziel, *_Shemiramoth_*, Jehiel, Unni, Eliab, Maaseiah, and Benaiah with psalteries on Alamoth;
* `1Ch 16:5` Asaph the chief, and next to him Zechariah, Jeiel, *_Shemiramoth_*, Jehiel, Mattithiah, Eliab, Benaiah, and Obed-edom; and Jeiel with psalteries and with harps; but Asaph made a sound with cymbals;
* `2Ch 17:8` And with them he sent Levites, even Shemaiah, Nethaniah, Zebadiah, Asahel, *_Shemiramoth_*, Jehonathan, Adonijah, Tobijah, and Tob-adonijah, Levites; and with them Elishama and Jehoram, priests.

_4 verses containing SHEMIRAMOTH_

== SHEMUEL

* `Num 34:20` Of the tribe of the children of Simeon, *_Shemuel_* the son of Ammihud;
* `1Ch 6:33` And these are those who waited with their children. Of the sons of the Kohathites: Heman a singer, the son of Joel, the son of *_Shemuel_*,
* `1Ch 7:2` And the sons of Tola: Uzzi, Rephaiah, Jeriel, Jahmai, Jibsam, and *_Shemuel_*, heads of their father's house, namely, of Tola. They were valiant men of might in their generations whose number was in the days of David twenty-two thousand and six hundred.

_3 verses containing SHEMUEL_

== SHEN

* `1Sa 7:12` Then Samuel took a stone, set it between Mizpeh and *_Shen_*, and called its name Eben-ezer, saying, "Until now the LORD has helped us."

_1 verse containing SHEN_

== SHENAZAR

* `1Ch 3:18` Malchiram, Pedaiah, *_Shenazar_*, Jecamiah, Hoshama, and Nedabiah.

_1 verse containing SHENAZAR_

== SHENIR

* `Deu 3:9` (Which Hermon the Sidonians call Sirion, and the Amorites call it *_Shenir_*),
* `Sos 4:8` Come with me from Lebanon, my spouse, with me from Lebanon. Look from the top of Amana, from the top of *_Shenir_* and Hermon, from the lions' dens, from the mountains of the leopards.

_2 verses containing SHENIR_

== SHEPHAM

* `Num 34:10` 'And you shall designate your east border from Hazar-enan to *_Shepham_*.
* `Num 34:11` And the limit shall go down from *_Shepham_* to Riblah on the east side of Ain. And the border shall descend and shall reach to the side of the sea of Chinnereth eastward.

_2 verses containing SHEPHAM_

== SHEPHATIAH

* `2Sa 3:4` The fourth, Adonijah the son of Haggith; the fifth, *_Shephatiah_* the son of Abital;
* `1Ch 3:3` The fifth, *_Shephatiah_* by Abital; the sixth, Ithream by Eglah his wife.
* `1Ch 9:8` And Ibneiah the son of Jeroham, and Elah the son of Uzzi, the son of Michri, and Meshullam the son of *_Shephatiah_*, the son of Reuel, the son of Ibnijah,
* `1Ch 12:5` Eluzai, Jerimoth, Bealiah, Shemariah, *_Shephatiah_* the Haruphite,
* `1Ch 27:16` Furthermore, over the tribes of Israel, the ruler of the Reubenites was Eliezer the son of Zichri; of the Simeonites, *_Shephatiah_* the son of Maachah;
* `2Ch 21:2` And he had brothers, the sons of Jehoshaphat: Azariah, Jehiel, Zechariah, Azariahu, Michael, and *_Shephatiah_*. All these were the sons of Jehoshaphat king of Israel.
* `Ezr 2:4` The children of *_Shephatiah_*, three hundred and seventy-two;
* `Ezr 2:57` The children of *_Shephatiah_*, the children of Hattil, the children of Pochereth of Zebaim, and the children of Ami.
* `Ezr 8:8` Of the sons of *_Shephatiah_*: Zebadiah the son of Michael, and with him eighty males.
* `Neh 7:9` The children of *_Shephatiah_*, three hundred and seventy-two;
* `Neh 7:59` The children of *_Shephatiah_*, the children of Hattil, the children of Pochereth of Zebaim, and the children of Amon.
* `Neh 11:4` And some of the children of Judah and some of the children of Benjamin dwelt at Jerusalem. Of the children of Judah: Athaiah the son of Uzziah, the son of Zechariah, the son of Amariah, the son of *_Shephatiah_*, the son of Mahalaleel, of the children of Perez;
* `Jer 38:1` Then *_Shephatiah_* the son of Mattan, Gedaliah the son of Pashur, Jucal the son of Shelemiah, and Pashur the son of Malchiah heard the words that Jeremiah had spoken to all the people, saying,

_13 verses containing SHEPHATIAH_

== SHEPHERD

* `Gen 46:34` You shall say, 'Your servants have been keepers of livestock from our youth even until now—both we and also our fathers,' so that you may dwell in the land of Goshen, for every *_shepherd_* is an abomination to the Egyptians."
* `Gen 49:24` But his bow remained in strength, and the arms of his hands were made strong by the hands of the mighty God of Jacob (from there is the *_shepherd_*, the stone of Israel),
* `Num 27:17` Who may go out before them, who may go in before them, who may lead them out, and who may bring them in, so that the congregation of the LORD is not as sheep which have no *_shepherd_*."
* `1Sa 17:40` And he took his staff in his hand, chose for himself five smooth stones out of the brook, and put them in a *_shepherd_*'s bag which he had, even in a pouch. Then, with his sling in his hand, he drew near to the Philistine.
* `1Ki 22:17` And he said, "I saw all Israel scattered upon the hills like sheep that do not have a *_shepherd_*. And the LORD said, 'These have no master. Let them each return to his house in peace.'"
* `2Ch 18:16` Then he said, "I saw all Israel scattered upon the mountains as sheep that have no *_shepherd_*. And the LORD said, 'These have no master. Let them each return therefore to his house in peace.'"
* `Psa 23:1` [A Psalm of David.] The LORD is my *_shepherd_*. I shall lack nothing.
* `Psa 80:1` [To the Chief Musician upon Shoshannim Eduth. A Psalm of Asaph.] Give ear, O *_Shepherd_* of Israel, you who lead Joseph like a flock. You who dwell between the cherubim, shine forth.
* `Ecc 12:11` The words of the wise are as goads and as nails fastened by the masters of assemblies, which are given from one *_shepherd_*.
* `Isa 38:12` My dwelling is plucked up and carried away from me like a *_shepherd_*'s tent. I have cut off my life like a weaver. He will cut me off with pining sickness. From day even to night you will make an end of me.
* `Isa 40:11` He will feed his flock like a *_shepherd_*. He will gather the lambs with his arm and carry them in his bosom, and will gently lead those who are with young.
* `Isa 44:28` Who says of Cyrus, 'He is my *_shepherd_*, and he shall perform all my pleasure,' even saying to Jerusalem, 'You shall be built,' and to the temple, 'Your foundation shall be laid.'"
* `Isa 63:11` Then he remembered the days of old, Moses and his people, saying, "Where is he who brought them out of the sea with the *_shepherd_* of his flock? Where is he who put his Holy Spirit within him,
* `Jer 31:10` Hear the word of the LORD, O nations, and declare it in the coastlands afar off and say, "He who scattered Israel will gather him and keep him as a *_shepherd_* does his flock."
* `Jer 43:12` And I will kindle a fire in the houses of the gods of Egypt, and he shall burn them and carry them away as captives. And he shall array himself with the land of Egypt, as a *_shepherd_* puts on his garment, and he shall go forth from there in peace.
* `Jer 49:19` Behold, he shall come up like a lion from the swelling of the Jordan against the habitation of the strong, but I will suddenly make him run away from her. And who is a chosen man that I may appoint over her? For who is like me? And who will appoint me the time? And who is that *_shepherd_* who will stand before me?"
* `Jer 50:44` "Behold, he shall come up like a lion from the swelling of the Jordan to the habitation of the strong, but I will make them suddenly run away from her. And who is a chosen man whom I may appoint over her? For who is like me? And who will appoint me the time? And who is that *_shepherd_* who will stand before me?"
* `Jer 51:23` With you I will break in pieces the *_shepherd_* and his flock, with you I will break in pieces the farmer and his yoke of oxen, and with you I will break in pieces captains and rulers.
* `Ezk 34:5` And they were scattered, because there is no *_shepherd_*. And they became food to all the beasts of the field when they were scattered.
* `Ezk 34:8` "As I live," says the Lord GOD, "surely because my flock became a prey and my flock became food to every beast of the field, because there was no *_shepherd_*, neither did my shepherds search for my flock, but the shepherds fed themselves and did not feed my flock,
* `Ezk 34:12` As a *_shepherd_* seeks out his flock in the day that he is among his sheep that are scattered, so I will seek out my sheep and will deliver them out of all places where they have been scattered in the cloudy and dark day.
* `Ezk 34:23` "And I will set up one *_shepherd_* over them, and he shall feed them, even my servant David. He shall feed them and be their *_shepherd_*.
* `Ezk 37:24` "And David my servant shall be king over them, and they shall all have one *_shepherd_*. They shall also walk in my judgments and observe my statutes and do them.
* `Amo 3:12` Thus says the LORD: "As the *_shepherd_* rescues out of the mouth of the lion two legs, or a piece of an ear, so the children of Israel shall be rescued who dwell in Samaria on the corner of a bed and in Damascus on a couch.
* `Zch 10:2` For the idols have spoken vanity, and the diviners have seen a lie. They have told false dreams. They comfort in vain. Therefore, they went their way as a flock. They were troubled because there was no *_shepherd_*.
* `Zch 11:15` And the LORD said to me, "Take for yourself yet again the instruments of a foolish *_shepherd_*.
* `Zch 11:16` For behold, I will raise up a *_shepherd_* in the land who shall not visit those who are cut off, neither shall seek the young one, nor heal that which is broken, nor feed that which stands still, but he shall eat the flesh of the fat and tear their hooves in pieces.
* `Zch 11:17` "Woe to the idle *_shepherd_* who leaves the flock! The sword shall be upon his arm and upon his right eye. His arm shall be wholly dried up and his right eye shall be utterly darkened."
* `Zch 13:7` "Awake, O sword, against my *_shepherd_* and against the man who is my fellow," says the LORD of hosts. "Smite the *_shepherd_* and the sheep shall be scattered. And I will turn my hand upon the little ones.
* `Mth 9:36` But when he saw the multitudes, he was moved with compassion for them because they fainted and were scattered abroad as sheep having no *_shepherd_*.
* `Mth 25:32` And before him all nations shall be gathered, and he will separate them one from another, as a *_shepherd_* divides his sheep from the goats.
* `Mth 26:31` Then Jesus says to them, "All of you shall be offended because of me this night, for it is written, 'I will smite the *_shepherd_*, and the sheep of the flock shall be scattered abroad.'
* `Mrk 6:34` And Jesus, when he came out, saw many people and was moved with compassion toward them because they were as sheep not having a *_shepherd_*. And he began to teach them many things.
* `Mrk 14:27` And Jesus says to them, "All of you will be offended because of me this night, for it is written, 'I will "smite the *_shepherd_*, and the sheep shall be scattered."'
* `Jhn 10:2` But he who enters by the door is the *_shepherd_* of the sheep.
* `Jhn 10:11` "I am the good *_shepherd_*. The good *_shepherd_* gives his life for the sheep.
* `Jhn 10:12` But he who is a hireling and not the *_shepherd_*, who does not own the sheep, sees the wolf coming and leaves the sheep and flees, and the wolf catches them and scatters the sheep.
* `Jhn 10:14` I am the good *_shepherd_*. I know my own and my own know me,
* `Jhn 10:16` And I have other sheep which are not of this fold. I must bring them also, and they shall hear my voice. And there shall be one fold and one *_shepherd_*.
* `Heb 13:20` Now may the God of peace, who brought back from the dead our Lord Jesus, that great *_Shepherd_* of the sheep, through the blood of the everlasting covenant,
* `1Pe 2:25` For you were as sheep going astray, but are now returned to the *_Shepherd_* and Overseer of your souls.
* `1Pe 5:4` And when the chief *_Shepherd_* appears, you shall receive a crown of glory that does not fade away.

_42 verses containing SHEPHERD_

== SHEPHERDS

* `Gen 46:32` And the men are *_shepherds_*, for their employment has been to feed livestock. And they have brought their flocks, their herds, and all that they have.'
* `Gen 47:3` And Pharaoh said to his brothers, "What is your occupation?" And they said to Pharaoh, "Your servants are *_shepherds_*—both we and also our fathers."
* `Exo 2:17` And the *_shepherds_* came and drove them away, but Moses stood up and helped them and watered their flock.
* `Exo 2:19` And they said, "An Egyptian delivered us from the hand of the *_shepherds_*, and also drew enough water for us and watered the flock."
* `1Sa 25:7` And now I have heard that you have shearers. Your *_shepherds_* have now been with us, and we did not hurt them, neither was there anything missing to them all the while they were in Carmel.
* `Sos 1:8` [Gentleman:] If you do not know, O fairest among women, go forth by the footsteps of the flock and feed your kids beside the *_shepherds_*' tents.
* `Isa 13:20` It shall never be inhabited, neither shall it be dwelt in from generation to generation, neither shall the Arabian pitch tent there, neither shall the *_shepherds_* make their fold there.
* `Isa 31:4` For thus the LORD has spoken to me: "As the lion and the young lion roaring on his prey when a multitude of *_shepherds_* is called forth against him, and he will not be afraid of their voice nor abase himself for their noise, so the LORD of hosts will come down to fight for mount Zion and for the hill thereof.
* `Isa 56:11` Indeed, they are greedy dogs which can never have enough, and they are *_shepherds_* who cannot understand. They all look to their own way, each for his gain, from his quarter.
* `Jer 6:3` The *_shepherds_* with their flocks shall come to her. They shall pitch their tents against her on every side. They shall each feed in his place.
* `Jer 23:4` And I will set *_shepherds_* over them who shall feed them. And they shall no longer fear nor be dismayed, neither shall they be lacking," says the LORD.
* `Jer 25:34` Howl, you *_shepherds_*, and cry, and wallow yourselves in the ashes, you principal of the flock, for the days of your slaughter and of your dispersions are accomplished, and you shall fall like a precious vessel.
* `Jer 25:35` And the *_shepherds_* shall have no way to flee, nor the principal of the flock to escape.
* `Jer 25:36` A voice of the cry of the *_shepherds_* and a howling of the principal of the flock shall be heard, for the LORD has laid waste their pasture.
* `Jer 33:12` "Thus says the LORD of hosts: 'Again in this place, which is desolate without man and without beast, and in all its cities shall be a habitation of *_shepherds_* causing their flocks to lie down.
* `Jer 50:6` "My people have been lost sheep. Their *_shepherds_* have caused them to go astray. They have turned them away on the mountains. They have gone from mountain to hill. They have forgotten their resting-place.
* `Ezk 34:2` "Son of man, prophesy against the *_shepherds_* of Israel, prophesy, and say to them, 'Thus says the Lord GOD to the *_shepherds_*: "Woe to the *_shepherds_* of Israel who feed themselves! Should the *_shepherds_* not feed the flocks?
* `Ezk 34:7` Therefore, you *_shepherds_*, hear the word of the LORD.
* `Ezk 34:8` "As I live," says the Lord GOD, "surely because my flock became a prey and my flock became food to every beast of the field, because there was no shepherd, neither did my *_shepherds_* search for my flock, but the *_shepherds_* fed themselves and did not feed my flock,
* `Ezk 34:9` Therefore, O *_shepherds_*, hear the word of the LORD.
* `Ezk 34:10` 'Thus says the Lord GOD: "Behold, I am against the *_shepherds_*, and I will require my flock at their hand and cause them to cease from feeding the flock. The *_shepherds_* shall not feed themselves anymore, for I will deliver my flock from their mouth so that they may not be food for them."'"
* `Amo 1:2` And he said, "The LORD will roar from Zion and utter his voice from Jerusalem, and the habitations of the *_shepherds_* shall mourn, and the top of Carmel shall wither."
* `Mic 5:5` And this one will be peace. When the Assyrian comes into our land and treads in our palaces, we shall raise against him seven *_shepherds_* and eight principal men.
* `Nah 3:18` Your *_shepherds_* slumber, O king of Assyria. Your nobles shall dwell in the dust. Your people are scattered upon the mountains and no man gathers them.
* `Zph 2:6` And the sea coast shall be pastures, with cottages for *_shepherds_* and folds for flocks.
* `Zch 10:3` "My anger was kindled against the *_shepherds_*, and I punished the goats, for the LORD of hosts has visited his flock, the house of Judah, and has made them as his majestic horse in the battle.
* `Zch 11:3` There is a voice of the howling of the *_shepherds_*, for their glory is destroyed; a voice of the roaring of young lions, for the pride of the Jordan is laid waste.
* `Zch 11:5` Whose possessors slay them and do not hold themselves guilty. And those who sell them say, 'Blessed be the LORD, for I am rich.' And their own *_shepherds_* do not pity them.
* `Zch 11:8` I also cut off three *_shepherds_* in one month. My soul was impatient with them, and their soul also abhorred me.
* `Luk 2:8` And there were in the same country *_shepherds_* abiding in the field, keeping watch over their flock by night.
* `Luk 2:15` And it came to pass, when the angels had departed from them into heaven, the *_shepherds_* said to one another, "Let us now go even to Bethlehem and see this thing which has come to pass, which the Lord has made known to us."
* `Luk 2:18` And all those who heard it wondered at those things which were told to them by the *_shepherds_*.
* `Luk 2:20` And the *_shepherds_* returned, glorifying and praising God for all the things that they had heard and seen, as it was told to them.

_33 verses containing SHEPHERDS_

== SHEPHI

* `1Ch 1:40` The sons of Shobal: Alian, Manahath, Ebal, *_Shephi_*, and Onam. And the sons of Zibeon: Aiah and Anah.

_1 verse containing SHEPHI_

== SHEPHO

* `Gen 36:23` And the children of Shobal are these: Alvan, Manahath, Ebal, *_Shepho_*, and Onam.

_1 verse containing SHEPHO_

== SHEPHUPHAN

* `1Ch 8:5` Gera, *_Shephuphan_*, and Huram.

_1 verse containing SHEPHUPHAN_

== SHERAH

* `1Ch 7:24` (And his daughter was *_Sherah_*, who built Beth-horon the nether and the upper and Uzzen-*_sherah_*.)

_1 verse containing SHERAH_

== SHEREBIAH

* `Ezr 8:18` And by the good hand of our God upon us they brought us a man of understanding of the sons of Mahli, the son of Levi, the son of Israel: *_Sherebiah_*, with his sons and his brothers, eighteen men.
* `Ezr 8:24` Then I separated twelve of the chief of the priests: *_Sherebiah_*, Hashabiah, and ten of their brothers with them.
* `Neh 8:7` Also Jeshua, Bani, *_Sherebiah_*, Jamin, Akkub, Shabbethai, Hodijah, Maaseiah, Kelita, Azariah, Jozabad, Hanan, Pelaiah, and the Levites caused the people to understand the law. And the people stood in their place.
* `Neh 9:4` Then, of the Levites, Jeshua, Bani, Kadmiel, Shebaniah, Bunni, *_Sherebiah_*, Bani, and Chenani stood upon the stairs and cried with a loud voice to the LORD their God.
* `Neh 9:5` Then the Levites, Jeshua, Kadmiel, Bani, Hashabniah, *_Sherebiah_*, Hodijah, Shebaniah, and Pethahiah, said, "Stand up and bless the LORD your God forever and ever: Blessed be your glorious name, which is exalted above all blessing and praise.
* `Neh 10:12` Zaccur, *_Sherebiah_*, Shebaniah,
* `Neh 12:8` Moreover, the Levites: Jeshua, Binnui, Kadmiel, *_Sherebiah_*, Judah, and Mattaniah who was over the thanksgiving—he and his brothers.
* `Neh 12:24` And the chief of the Levites were Hashabiah, *_Sherebiah_*, and Jeshua the son of Kadmiel, with their brothers over against them, to praise and to give thanks according to the commandment of David the man of God, ward over against ward.

_8 verses containing SHEREBIAH_

== SHERESH

* `1Ch 7:16` And Maachah the wife of Machir bore a son and she called his name Peresh. And the name of his brother was *_Sheresh_*, and his sons were Ulam and Rakem.

_1 verse containing SHERESH_

== SHEREZER

* `Zch 7:2` When those of Beth-el had sent *_Sherezer_*, Regem-melech, and their men to pray before the LORD,

_1 verse containing SHEREZER_

== SHERIFFS

* `Dan 3:2` Then Nebuchadnezzar the king sent to convene the princes, the governors, the captains, the judges, the treasurers, the counselors, the *_sheriffs_*, and all the rulers of the provinces to come to the dedication of the image which Nebuchadnezzar the king had set up.
* `Dan 3:3` Then the princes, the governors, the captains, the judges, the treasurers, the counselors, the *_sheriffs_*, and all the rulers of the provinces were assembled to the dedication of the image that Nebuchadnezzar the king had set up, and they stood before the image that Nebuchadnezzar had set up.

_2 verses containing SHERIFFS_

== SHERUHEN

* `Jsh 19:6` Beth-lebaoth, and *_Sheruhen_*; thirteen cities and their villages;

_1 verse containing SHERUHEN_

== SHESHACH

* `Jer 25:26` All the kings of the north, far and near, with one another, and all the kingdoms of the world which are upon the face of the earth. And the king of *_Sheshach_* shall drink after them.
* `Jer 51:41` How *_Sheshach_* is taken! And how the praise of the whole earth is surprised! How Babylon has become an astonishment among the nations!

_2 verses containing SHESHACH_

== SHESHAI

* `Num 13:22` And they ascended by the south and came to Hebron where Ahiman, *_Sheshai_*, and Talmai, the children of Anak, were. (Now Hebron was built seven years before Zoan in Egypt.)
* `Jsh 15:14` And Caleb drove from there the three sons of Anak: *_Sheshai_*, Ahiman, and Talmai, the children of Anak.
* `Jdg 1:10` And Judah went against the Canaanites who dwelt in Hebron (now the name of Hebron was formerly Kirjath-arba), and they slew *_Sheshai_*, Ahiman, and Talmai.

_3 verses containing SHESHAI_

== SHESHAN

* `1Ch 2:31` And the son of Appaim: Ishi. And the son of Ishi: *_Sheshan_*. And the child of *_Sheshan_*: Ahlai.
* `1Ch 2:34` Now *_Sheshan_* had no sons, but daughters. And *_Sheshan_* had a servant, an Egyptian, whose name was Jarha.
* `1Ch 2:35` And *_Sheshan_* gave his daughter to Jarha his servant for a wife, and she bore him Attai.

_3 verses containing SHESHAN_

== SHESHBAZZAR

* `Ezr 1:8` And Cyrus king of Persia brought them forth by the hand of Mithredath the treasurer, and he numbered them to *_Sheshbazzar_*, the prince of Judah.
* `Ezr 1:11` All the vessels of gold and of silver were five thousand and four hundred. All these *_Sheshbazzar_* brought with those of the captivity who were brought from Babylon to Jerusalem.
* `Ezr 5:14` And also the vessels of gold and silver of the house of God, which Nebuchadnezzar took out of the temple that was in Jerusalem and brought them into the temple of Babylon, Cyrus the king took those out of the temple of Babylon, and they were delivered to someone whose name was *_Sheshbazzar_*, whom he had made governor,
* `Ezr 5:16` Then the same *_Sheshbazzar_* came and laid the foundation of the house of God which is in Jerusalem. And since that time even until now it has been in building, but it is not yet finished.'

_4 verses containing SHESHBAZZAR_

== SHETH

* `Num 24:17` I shall see him, but not now. I shall behold him, but not near. There shall come a Star out of Jacob, and a Scepter shall rise out of Israel and shall smite the corners of Moab and destroy all the children of *_Sheth_*.
* `1Ch 1:1` Adam, *_Sheth_*, Enosh,

_2 verses containing SHETH_

== SHETHAR

* `Ezr 5:3` At the same time Tatnai, governor on this side of the river, *_Shethar_*-boznai, and their companions, came to them and said this to them: "Who has commanded you to build this house and to finish this wall?"
* `Ezr 5:6` This is the copy of the letter that Tatnai, governor on this side of the river, *_Shethar_*-boznai, and his companions the Apharsachites, who were on this side of the river, sent to Darius the king.
* `Ezr 6:6` "Now therefore, Tatnai, governor beyond the river, *_Shethar_*-boznai, and your companions the Apharsachites, who are beyond the river, keep far from there.
* `Ezr 6:13` Then Tatnai, governor on this side of the river, *_Shethar_*-boznai, and their companions, speedily did according to that which Darius the king had sent.
* `Est 1:14` And were close to him: Carshena, *_Shethar_*, Admatha, Tarshish, Meres, Marsena, and Memucan, the seven princes of Persia and Media, who saw the king's face and who sat the first in the kingdom),

_5 verses containing SHETHAR_

== SHETHAR-BOZNAI

* `Ezr 5:3` At the same time Tatnai, governor on this side of the river, *_Shethar-boznai_*, and their companions, came to them and said this to them: "Who has commanded you to build this house and to finish this wall?"
* `Ezr 5:6` This is the copy of the letter that Tatnai, governor on this side of the river, *_Shethar-boznai_*, and his companions the Apharsachites, who were on this side of the river, sent to Darius the king.
* `Ezr 6:6` "Now therefore, Tatnai, governor beyond the river, *_Shethar-boznai_*, and your companions the Apharsachites, who are beyond the river, keep far from there.
* `Ezr 6:13` Then Tatnai, governor on this side of the river, *_Shethar-boznai_*, and their companions, speedily did according to that which Darius the king had sent.

_4 verses containing SHETHAR-BOZNAI_

== SHEVA

* `2Sa 20:25` *_Sheva_* was scribe, Zadok and Abiathar were the priests,
* `1Ch 2:49` She also bore Shaaph the father of Madmannah, *_Sheva_* the father of Machbenah, and the father of Gibea. And the daughter of Caleb was Achsah.

_2 verses containing SHEVA_

== SHIBBOLETH

* `Jdg 12:6` Then they said to him, "Now say, '*_Shibboleth_*,'" and he said, "Sibboleth," for he could not frame to pronounce it right. Then they took him and slew him at the passages of the Jordan. And there fell at that time of the Ephraimites forty-two thousand.

_1 verse containing SHIBBOLETH_

== SHIBMAH

* `Num 32:38` Nebo, Baal-meon (their names being changed), and *_Shibmah_*, and gave other names to the cities which they built.

_1 verse containing SHIBMAH_

== SHICRON

* `Jsh 15:11` And the border went out to the side of Ekron northward. And the border was drawn to *_Shicron_*, passed along to mount Baalah, and went out to Jabneel. And the terminations of the border were at the sea.

_1 verse containing SHICRON_

== SHIELD

* `Gen 15:1` After these things the word of the LORD came to Abram in a vision, saying, "Do not fear, Abram. I am your *_shield_* and your exceedingly great reward."
* `Deu 33:29` Happy are you, O Israel! Who is like you, O people saved by the LORD, the *_shield_* of your help, and he who is the sword of your excellence? And your enemies shall be found liars to you, and you shall tread upon their high places."
* `Jdg 5:8` They chose new gods, then war was in the gates. Was there a *_shield_* or spear seen among forty thousand in Israel?
* `1Sa 17:7` And the staff of his spear was like a weaver's beam and his spear's head weighed six hundred shekels of iron. And someone bearing a *_shield_* went before him.
* `1Sa 17:41` And the Philistine advanced and drew near to David, and the man who bore the *_shield_* went before him.
* `1Sa 17:45` Then David said to the Philistine, "You come to me with a sword, with a spear, and with a *_shield_*, but I come to you in the name of the LORD of hosts, the God of the armies of Israel, whom you have defied.
* `2Sa 1:21` "You mountains of Gilboa, let there be no dew, neither rain upon you, nor fields of offerings, for there the *_shield_* of the mighty is vilely cast away, the *_shield_* of Saul, as though he had not been anointed with oil.
* `2Sa 22:3` My God, my rock in whom I will trust. He is my *_shield_* and the horn of my salvation, my high tower and my refuge, my preserver. You save me from violence.
* `2Sa 22:36` You have also given me the *_shield_* of your salvation, and your gentleness has made me great.
* `1Ki 10:17` And he made three hundred shields of beaten gold. Three minas of gold went to one *_shield_*. And the king put them in the House of the Forest of Lebanon.
* `2Ki 19:32` 'Therefore, thus says the LORD concerning the king of Assyria: "He shall not come into this city, nor shoot an arrow there, nor come before it with *_shield_*, nor cast a siege-mound against it.
* `1Ch 12:8` And some of the Gadites separated themselves to David in the hold in the wilderness, men of might and men of war fit for the battle who could handle *_shield_* and buckler, whose faces were like the faces of lions and were as swift as the gazelles upon the mountains:
* `1Ch 12:24` The children of Judah who bore *_shield_* and spear were six thousand and eight hundred, ready armed for war.
* `1Ch 12:34` And of Naphtali there were one thousand captains, and with them thirty-seven thousand with *_shield_* and spear.
* `2Ch 9:16` And three hundred shields he made of beaten gold. Three hundred shekels of gold went to each *_shield_*. And the king put them in the house of the forest of Lebanon.
* `2Ch 17:17` And of Benjamin: Eliada a mighty man of valor, and with him two hundred thousand armed men with bow and *_shield_*;
* `2Ch 25:5` Moreover, Amaziah assembled Judah and made them captains over thousands and captains over hundreds, according to the houses of their fathers, throughout all Judah and Benjamin. And he numbered them from twenty years old and above and found them to be three hundred thousand choice men, able to go forth to war, who could handle spear and *_shield_*.
* `Job 39:23` The quiver rattles against him, the glittering spear and the *_shield_*.
* `Psa 3:3` But you, O LORD, are a *_shield_* for me, my glory and the lifter up of my head.
* `Psa 5:12` For you, LORD, will bless the righteous. With favor you will compass him as with a *_shield_*.
* `Psa 18:35` You have also given me the *_shield_* of your salvation. Your right hand has held me up, and your gentleness has made me great.
* `Psa 28:7` The LORD is my strength and my *_shield_*. My heart trusted in him, and I am helped; therefore, my heart greatly rejoices, and with my song I will praise him.
* `Psa 33:20` Our soul waits for the LORD. He is our help and our *_shield_*.
* `Psa 35:2` Take hold of *_shield_* and buckler and stand up for my help.
* `Psa 59:11` Do not slay them, lest my people forget. Scatter them by your power and bring them down, O Lord our *_shield_*.
* `Psa 76:3` There he broke the arrows of the bow, the *_shield_*, the sword, and the battle. [Selah.]
* `Psa 84:9` Behold, O God our *_shield_*, and look upon the face of your anointed.
* `Psa 84:11` For the LORD God is a sun and *_shield_*. The LORD will give grace and glory. No good will he withhold from those who walk uprightly.
* `Psa 91:4` He shall cover you with his feathers, and under his wings you shall trust. His truth shall be your *_shield_* and buckler.
* `Psa 115:9` O Israel, trust in the LORD. He is their help and their *_shield_*.
* `Psa 115:10` O house of Aaron, trust in the LORD. He is their help and their *_shield_*.
* `Psa 115:11` You who fear the LORD, trust in the LORD. He is their help and their *_shield_*.
* `Psa 119:114` You are my hiding place and my *_shield_*. I hope in your word.
* `Psa 144:2` My goodness, my fortress, my high tower, and my deliverer; my *_shield_*, and he in whom I trust, who subdues my people under me.
* `Pro 30:5` Every word of God is pure. He is a *_shield_* to those who put their trust in him.
* `Isa 21:5` Prepare the table, watch in the watch-tower, eat, drink. Arise, you princes, and anoint the *_shield_*.
* `Isa 22:6` And Elam bore the quiver with chariots of men and horsemen, and Kir uncovered the *_shield_*.
* `Jer 46:3` "Order the buckler and *_shield_* and draw near to battle.
* `Jer 46:9` Come up, you horses, and rage, you chariots, and let the mighty men come forth—the Cushites and the Libyans who handle the *_shield_*, and the Lydians who handle and bend the bow.
* `Ezk 23:24` And they shall come against you with chariots, wagons, wheels, and with an assembly of people, which shall set against you buckler, *_shield_*, and helmet on every side. And I will set judgment before them, and they shall judge you according to their judgments.
* `Ezk 27:10` "They of Persia, of Lud, and of Phut were in your army, your military men. They hung the *_shield_* and helmet in you. They set forth your splendor.
* `Ezk 38:5` Persia, Cush, and Phut with them, all of them with *_shield_* and helmet;
* `Nah 2:3` The *_shield_* of his mighty men is made red. The valiant men are in scarlet. The chariots shall be with flaming torches in the day of his preparation, and the fir-trees shall be terribly shaken.
* `Eph 6:16` Above all, taking the *_shield_* of faith, with which you will be able to extinguish all the fiery darts of the wicked.

_44 verses containing SHIELD_

== SHIELDS

* `2Sa 8:7` And David took the *_shields_* of gold that were on the servants of Hadadezer and brought them to Jerusalem.
* `1Ki 10:17` And he made three hundred *_shields_* of beaten gold. Three minas of gold went to one shield. And the king put them in the House of the Forest of Lebanon.
* `1Ki 14:26` And he took away the treasures of the house of the LORD and the treasures of the king's house. He even took away everything. And he took away all the *_shields_* of gold which Solomon had made.
* `1Ki 14:27` And king Rehoboam made in their stead brazen *_shields_* and committed them to the hands of the chief of the guard who kept the door of the king's house.
* `2Ki 11:10` And to the captains over hundreds the priest gave king David's spears and *_shields_* that were in the temple of the LORD.
* `1Ch 18:7` And David took the *_shields_* of gold that were on the servants of Hadarezer and brought them to Jerusalem.
* `2Ch 9:16` And three hundred *_shields_* he made of beaten gold. Three hundred shekels of gold went to each shield. And the king put them in the house of the forest of Lebanon.
* `2Ch 11:12` And in every single city he put *_shields_* and spears and made them exceedingly strong, having Judah and Benjamin on his side.
* `2Ch 12:9` So Shishak king of Egypt came up against Jerusalem and took away the treasures of the house of the LORD and the treasures of the king's house. He took everything. He also carried away the *_shields_* of gold which Solomon had made.
* `2Ch 12:10` And king Rehoboam made *_shields_* of brass in their place and committed them to the hands of the chief of the guard who kept the entrance of the king's house.
* `2Ch 14:8` And Asa had an army of three hundred thousand men out of Judah who bore bucklers and spears, and two hundred and eighty thousand out of Benjamin who bore *_shields_* and drew bows. All these were mighty men of valor.
* `2Ch 23:9` Moreover, Jehoiada the priest delivered to the captains of hundreds spears, bucklers, and *_shields_*, which had been king David's, which were in the house of God.
* `2Ch 26:14` And Uzziah prepared for them, even for all the army, *_shields_*, spears, helmets, habergeons, bows, and slings to cast stones.
* `2Ch 32:5` He also strengthened himself, built up all the wall that was broken, raised it up to the towers, built another wall outside, repaired Millo in the city of David, and made darts and *_shields_* in abundance.
* `2Ch 32:27` And Hezekiah had very great riches and honor. And he made himself treasuries for silver, for gold, for precious stones, for spices, for *_shields_*, and for all manner of pleasant jewels,
* `Neh 4:16` And it came to pass from that time forth, that one half of my servants wrought in the work and the other half of them held the spears, the *_shields_*, the bows, and the habergeons. And the rulers were behind all the house of Judah.
* `Psa 47:9` The princes of the people are assembled, even the people of the God of Abraham. For the *_shields_* of the earth belong to God. He is greatly exalted.
* `Sos 4:4` Your neck is like the tower of David built for an armory, on which hang a thousand bucklers, all *_shields_* of mighty men.
* `Isa 37:33` "Therefore, thus says the LORD concerning the king of Assyria: 'He shall not come into this city, nor shoot an arrow there, nor come before it with *_shields_*, nor cast a siege-mound against it.
* `Jer 51:11` Make the arrows bright. Gather the *_shields_*. The LORD has raised up the spirit of the kings of the Medes, for his purpose is against Babylon to destroy it, because it is the vengeance of the LORD, the vengeance of his temple.
* `Ezk 27:11` The men of Arvad with your army were upon your walls on all sides, and the Gammadims were in your towers. They hung their *_shields_* upon your walls on every side. They have made your beauty perfect.
* `Ezk 38:4` And I will turn you back and put hooks into your jaws, and I will bring you forth with all your army—horses and horsemen all clothed with all sorts of armor, even a great company with bucklers and *_shields_*, all of them handling swords;
* `Ezk 39:9` "And those who dwell in the cities of Israel shall go forth and set on fire and burn the weapons: the *_shields_*, the bucklers, the bows and the arrows, the hand-staffs, and the spears. And they shall burn them with fire for seven years

_23 verses containing SHIELDS_

== SHIGGAION

* `Psa 7:1` [*_Shiggaion_* of David: which he sang to the LORD concerning the words of Cush the Benjaminite.] O LORD my God, I put my trust in you. Save me from all those who persecute me, and deliver me,

_1 verse containing SHIGGAION_

== SHIGIONOTH

* `Hab 3:1` [A prayer of Habakkuk the prophet upon *_Shigionoth_*.]

_1 verse containing SHIGIONOTH_

== SHIHON

* `Jsh 19:19` Hapharaim, *_Shihon_*, Anaharath,

_1 verse containing SHIHON_

== SHIHOR

* `Jsh 19:26` Alammelech, Amad, and Misheal, and reaches to Carmel westward, and to *_Shihor_*-libnath,
* `1Ch 13:5` So David assembled all Israel from *_Shihor_* of Egypt even to the entrance of Hemath to bring the ark of God from Kirjath-jearim.

_2 verses containing SHIHOR_

== SHIHOR-LIBNATH

* `Jsh 19:26` Alammelech, Amad, and Misheal, and reaches to Carmel westward, and to *_Shihor-libnath_*,

_1 verse containing SHIHOR-LIBNATH_

== SHILHI

* `1Ki 22:42` Jehoshaphat was thirty-five years old when he began to reign, and he reigned for twenty-five years in Jerusalem. And his mother's name was Azubah, the daughter of *_Shilhi_*.
* `2Ch 20:31` And Jehoshaphat reigned over Judah. He was thirty-five years old when he began to reign, and he reigned twenty-five years in Jerusalem. And his mother's name was Azubah the daughter of *_Shilhi_*.

_2 verses containing SHILHI_

== SHILHIM

* `Jsh 15:32` Lebaoth, *_Shilhim_*, Ain, and Rimmon. All the cities are twenty-nine, with their villages.

_1 verse containing SHILHIM_

== SHILLEM

* `Gen 46:24` And the sons of Naphtali: Jahzeel, Guni, Jezer, and *_Shillem_*.
* `Num 26:49` Of Jezer, the family of the Jezerites; of *_Shillem_*, the family of the Shillemites.

_2 verses containing SHILLEM_

== SHILLEMITES

* `Num 26:49` Of Jezer, the family of the Jezerites; of Shillem, the family of the *_Shillemites_*.

_1 verse containing SHILLEMITES_

== SHILOAH

* `Isa 8:6` "Because this people refuses the waters of *_Shiloah_* that flow gently and rejoices in Rezin and Remaliah's son,

_1 verse containing SHILOAH_

== SHILOH

* `Gen 49:10` The scepter shall not depart from Judah, nor a lawgiver from between his feet, until *_Shiloh_* comes. And to him shall be the gathering of the people.
* `Jsh 16:6` And the border went out toward the sea to Michmethah on the north side, and the border went around eastward to Taanath-*_shiloh_*, and passed by it on the east to Janohah,
* `Jsh 18:1` And the whole congregation of the children of Israel assembled at *_Shiloh_* and set up the Tabernacle of the Congregation there. And the land was subdued before them.
* `Jsh 18:8` And the men arose and departed. And Joshua charged those who went to describe the land, saying, "Go and walk through the land, describe it, and come back to me so that I may cast lots for you here before the LORD in *_Shiloh_*."
* `Jsh 18:9` And the men went and passed through the land, described it by cities in seven parts in a book, and came back to Joshua to the host at *_Shiloh_*.
* `Jsh 18:10` And Joshua cast lots for them in *_Shiloh_* before the LORD. And there Joshua divided the land to the children of Israel according to their divisions.
* `Jsh 19:51` These are the inheritances which Eleazar the priest, and Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel divided for an inheritance by lot in *_Shiloh_* before the LORD, at the door of the Tabernacle of the Congregation. So they made an end of dividing the country.
* `Jsh 21:2` And they spoke to them at *_Shiloh_* in the land of Canaan, saying, "The LORD commanded by the hand of Moses to give us cities to dwell in, with their suburbs for our livestock."
* `Jsh 22:9` And the children of Reuben, the children of Gad, and the half-tribe of Manasseh returned and departed from the children of Israel out of *_Shiloh_*, which is in the land of Canaan, to go to the country of Gilead, to the land of their possession, which they had possessed according to the word of the LORD by the hand of Moses.
* `Jsh 22:12` And when the children of Israel heard of it, the whole congregation of the children of Israel assembled at *_Shiloh_* to go up to war against them.
* `Jdg 18:31` And they set up for themselves Micah's engraved image which he made the whole time that the house of God was in *_Shiloh_*.
* `Jdg 21:12` And they found among the inhabitants of Jabesh-gilead four hundred young virgins who had known no man by lying with any male, and they brought them to the camp at *_Shiloh_*, which is in the land of Canaan.
* `Jdg 21:19` Then they said, "Behold, there is a yearly feast of the LORD in *_Shiloh_* in a place which is on the north side of Beth-el, on the east side of the highway that goes up from Beth-el to Shechem, and on the south of Lebonah."
* `Jdg 21:21` And when you see the daughters of *_Shiloh_* come out to dance in dances, come out of the vineyards and each of you catch his wife from the daughters of *_Shiloh_*, and go to the land of Benjamin.
* `1Sa 1:3` And this man went up from his city yearly to worship and to sacrifice to the LORD of hosts in *_Shiloh_*. And the two sons of Eli, Hophni and Phinehas, the priests of the LORD, were there.
* `1Sa 1:9` So Hannah rose after they had eaten in *_Shiloh_* and after they had drank. (Now Eli the priest sat upon a seat by a post of the temple of the LORD.)
* `1Sa 1:24` And when she had weaned him, she took him up with her, with three bulls, one ephah of flour, and a bottle of wine, and brought him to the house of the LORD in *_Shiloh_*. And the child was young.
* `1Sa 2:14` And he struck it into the pan, kettle, cauldron, or pot, and all that the flesh-hook brought up the priest took for himself. They did so in *_Shiloh_* to all the Israelites who came there.
* `1Sa 3:21` And the LORD appeared again in *_Shiloh_*, for the LORD revealed himself to Samuel in *_Shiloh_* by the word of the LORD.
* `1Sa 4:3` And when the people had come into the camp, the elders of Israel said, "Why has the LORD smitten us today before the Philistines? Let us bring the ark of the covenant of the LORD out of *_Shiloh_* to us, so that when it comes among us, it may save us from the hand of our enemies."
* `1Sa 4:4` So the people sent to *_Shiloh_* so that they might bring from there the ark of the covenant of the LORD of hosts, who dwells between the cherubim. And the two sons of Eli, Hophni and Phinehas, were there with the ark of the covenant of God.
* `1Sa 4:12` And there ran a man of Benjamin out of the army and came to *_Shiloh_* the same day with his clothes rent and with earth upon his head.
* `1Sa 14:3` Along with Ahiah, the son of Ahitub, Ichabod's brother, the son of Phinehas, the son of Eli, the LORD'S priest in *_Shiloh_*, wearing an ephod. And the people did not know that Jonathan was gone.
* `1Ki 2:27` So Solomon removed Abiathar from being priest to the LORD so that he might fulfill the word of the LORD which he spoke concerning the house of Eli in *_Shiloh_*.
* `1Ki 14:2` And Jeroboam said to his wife, "Arise, I pray you, disguise yourself so that you may not be known to be the wife of Jeroboam and go to *_Shiloh_*. Behold, there is Ahijah the prophet who told me that I should be king over this people.
* `1Ki 14:4` And Jeroboam's wife did so, and she arose, went to *_Shiloh_*, and came to the house of Ahijah. But Ahijah could not see, for his eyes were set by reason of his age.
* `Psa 78:60` So that he forsook the tabernacle of *_Shiloh_*, the tent which he placed among men,
* `Jer 7:12` "But go now to my place which was in *_Shiloh_*, where I set my name at the first, and see what I did to it for the wickedness of my people Israel.
* `Jer 7:14` Therefore I will do to this house which is called by my name, in which you trust, and to the place which I gave to you and to your fathers, as I have done to *_Shiloh_*.
* `Jer 26:6` Then I will make this house like *_Shiloh_* and will make this city a curse to all the nations of the earth."'"
* `Jer 26:9` Why have you prophesied in the name of the LORD, saying, 'This house shall be like *_Shiloh_*, and this city shall be desolate without an inhabitant'?" And all the people were gathered against Jeremiah in the house of the LORD.
* `Jer 41:5` That there came men from Shechem, from *_Shiloh_*, and from Samaria, even eighty men, having their beards shaved and their clothes rent and having cut themselves, with offerings and incense in their hand, to bring them to the house of the LORD.

_32 verses containing SHILOH_

== SHILONI

* `Neh 11:5` And Maaseiah the son of Baruch, the son of Col-hozeh, the son of Hazaiah, the son of Adaiah, the son of Joiarib, the son of Zechariah, the son of *_Shiloni_*.

_1 verse containing SHILONI_

== SHILONITE

* `1Ki 11:29` And it came to pass at that time when Jeroboam went out of Jerusalem, that the prophet Ahijah the *_Shilonite_* found him on the way. And he had clad himself with a new garment, and the two of them were alone in the field.
* `1Ki 12:15` Therefore, the king did not listen to the people, for the cause was from the LORD that he might perform his saying which the LORD spoke by Ahijah the *_Shilonite_* to Jeroboam the son of Nebat.
* `1Ki 15:29` And it came to pass when he reigned, that he smote all the house of Jeroboam. He did not leave to Jeroboam any who breathed until he had destroyed him, according to the saying of the LORD which he spoke by his servant Ahijah the *_Shilonite_*,
* `2Ch 9:29` Now the rest of the acts of Solomon, first and last, are they not written in the book of Nathan the prophet, in the prophecy of Ahijah the *_Shilonite_*, and in the visions of Iddo the seer against Jeroboam the son of Nebat?
* `2Ch 10:15` So the king did not listen to the people, for the cause was from God so that the LORD might perform his word which he spoke by the hand of Ahijah the *_Shilonite_* to Jeroboam the son of Nebat.

_5 verses containing SHILONITE_

== SHILONITES

* `1Ch 9:5` And of the *_Shilonites_*: Asaiah the first-born and his sons.

_1 verse containing SHILONITES_

== SHILSHAH

* `1Ch 7:37` Bezer, Hod, Shamma, *_Shilshah_*, Ithran, and Beera.

_1 verse containing SHILSHAH_

== SHIMEA

* `1Ch 3:5` And these were born to him in Jerusalem: *_Shimea_*, Shobab, Nathan, and Solomon, four by Bath-shua the daughter of Ammiel,
* `1Ch 6:30` *_Shimea_* his son, Haggiah his son, and Asaiah his son.
* `1Ch 6:39` And his brother Asaph who stood on his right hand, even Asaph the son of Berechiah, the son of *_Shimea_*,
* `1Ch 20:7` But when he defied Israel, Jonathan the son of *_Shimea_*, David's brother, slew him.

_4 verses containing SHIMEA_

== SHIMEAH

* `2Sa 13:3` But Amnon had a friend whose name was Jonadab, the son of *_Shimeah_* David's brother. And Jonadab was a very subtle man.
* `2Sa 13:32` And Jonadab the son of *_Shimeah_*, David's brother, answered and said, "Do not let my lord suppose that they have slain all the young men, the king's sons, for only Amnon is dead. For by the appointment of Absalom this has been determined from the day that he forced his sister Tamar.
* `2Sa 21:21` And when he defied Israel, Jonathan the son of *_Shimeah_* the brother of David slew him.
* `1Ch 8:32` And Mikloth begot *_Shimeah_*. And these also dwelt with their brothers in Jerusalem over against them.

_4 verses containing SHIMEAH_

== SHIMEAM

* `1Ch 9:38` And Mikloth begot *_Shimeam_*. And they also dwelt with their brothers at Jerusalem over against their brothers.

_1 verse containing SHIMEAM_

== SHIMEATH

* `2Ki 12:21` For his servants, Jozachar the son of *_Shimeath_* and Jehozabad the son of Shomer, smote him, and he died. And they buried him with his fathers in the city of David. And Amaziah his son reigned in his stead.
* `2Ch 24:26` And these are those who conspired against him: Zabad the son of *_Shimeath_* the Ammonitess, and Jehozabad the son of Shimrith the Moabitess.

_2 verses containing SHIMEATH_

== SHIMEATHITES

* `1Ch 2:55` And the families of the scribes who dwelt at Jabez: the Tirathites, the *_Shimeathites_*, and Suchathites. These are the Kenites who came from Hemath, the father of the house of Rechab.

_1 verse containing SHIMEATHITES_

== SHIMEI

* `Num 3:18` And these are the names of the sons of Gershon by their families: Libni and *_Shimei_*.
* `2Sa 16:5` And when king David came to Bahurim, behold, a man came out from there of the family of the house of Saul whose name was *_Shimei_*, the son of Gera. He came forth and cursing as he came.
* `2Sa 16:7` And thus *_Shimei_* said when he cursed: "Come out, come out, you bloody man, and you man of Belial.
* `2Sa 16:13` And as David and his men went along the way, *_Shimei_* went along on the hill's side over against him and cursed as he went, threw stones at him, and cast dust.
* `2Sa 19:16` And *_Shimei_* the son of Gera, a Benjaminite who was from Bahurim, hastened and came down with the men of Judah to meet king David.
* `2Sa 19:18` And a ferry-boat went to carry over the king's household and to do what he thought good. And *_Shimei_* the son of Gera fell down before the king as he came over the Jordan
* `2Sa 19:21` But Abishai the son of Zeruiah answered and said, "Shall *_Shimei_* not be put to death for this because he cursed the LORD'S anointed?"
* `2Sa 19:23` Therefore, the king said to *_Shimei_*, "You shall not die." And the king swore to him.
* `1Ki 1:8` But Zadok the priest, Benaiah the son of Jehoiada, Nathan the prophet, *_Shimei_*, Rei, and the mighty men who belonged to David were not with Adonijah.
* `1Ki 2:8` And behold, you have with you *_Shimei_* the son of Gera, a Benjaminite of Bahurim, who cursed me with a grievous curse in the day when I went to Mahanaim. But he came down to meet me at the Jordan, and I swore to him by the LORD, saying, 'I will not put you to death with the sword.'
* `1Ki 2:36` And the king sent and called for *_Shimei_* and said to him, "Build yourself a house in Jerusalem, dwell there, and do not go forth from there to any place.
* `1Ki 2:38` And *_Shimei_* said to the king, "The saying is good. As my lord the king has said, so your servant will do." And *_Shimei_* dwelt in Jerusalem many days.
* `1Ki 2:39` And it came to pass at the end of three years, that two of the servants of *_Shimei_* ran away to Achish son of Maachah king of Gath. And they told *_Shimei_*, saying, "Behold, your servants are in Gath."
* `1Ki 2:40` And *_Shimei_* arose, saddled his donkey, and went to Gath to Achish to seek his servants. And *_Shimei_* went and brought his servants from Gath.
* `1Ki 2:41` And it was told to Solomon that *_Shimei_* had gone from Jerusalem to Gath and had returned.
* `1Ki 2:42` And the king sent and called for *_Shimei_* and said to him, "Did I not make you swear by the LORD and testify to you, saying, 'Know for certain, on the day you go out and walk anywhere abroad, that you shall surely die'? And you said to me, 'The word that I have heard is good.'
* `1Ki 2:44` The king said moreover to *_Shimei_*, "You know all the wickedness which your heart has known that you did to David my father; therefore, the LORD will return your wickedness upon your own head.
* `1Ki 4:18` *_Shimei_* the son of Elah, in Benjamin;
* `1Ch 3:19` And the sons of Pedaiah were Zerubbabel and *_Shimei_*. And the sons of Zerubbabel: Meshullam and Hananiah, and Shelomith was their sister;
* `1Ch 4:26` And the sons of Mishma: Hamuel his son, Zacchur his son, and *_Shimei_* his son.
* `1Ch 4:27` And *_Shimei_* had sixteen sons and six daughters, but his brothers did not have many children, neither did all their family multiply like the children of Judah.
* `1Ch 5:4` The sons of Joel: Shemaiah his son, Gog his son, *_Shimei_* his son,
* `1Ch 6:17` And these are the names of the sons of Gershom: Libni and *_Shimei_*.
* `1Ch 6:29` The sons of Merari: Mahli, Libni his son, *_Shimei_* his son, Uzza his son,
* `1Ch 6:42` The son of Ethan, the son of Zimmah, the son of *_Shimei_*,
* `1Ch 23:7` Of the Gershonites were Laadan and *_Shimei_*.
* `1Ch 23:9` The sons of *_Shimei_*: Shelomith, Haziel, and Haran, three. These were the chief of the fathers of Laadan.
* `1Ch 23:10` And the sons of *_Shimei_* were Jahath, Zina, Jeush and Beriah. These four were the sons of *_Shimei_*.
* `1Ch 25:17` The tenth to *_Shimei_*—he, his sons, and his brothers were twelve;
* `1Ch 27:27` And over the vineyards was *_Shimei_* the Ramathite; and over the increase of the vineyards for the wine cellars was Zabdi the Shiphmite;
* `2Ch 29:14` And of the sons of Heman: Jehiel and *_Shimei_*; and of the sons of Jeduthun: Shemaiah and Uzziel.
* `2Ch 31:12` And brought in the offerings and the tithes and the dedicated things faithfully, over which Conaniah the Levite was ruler and *_Shimei_* his brother was next.
* `2Ch 31:13` And Jehiel, Azaziah, Nahath, Asahel, Jerimoth, Jozabad, Eliel, Ismachiah, Mahath, and Benaiah were overseers under the hand of Conaniah and *_Shimei_* his brother, at the commandment of Hezekiah the king and Azariah the ruler of the house of God.
* `Ezr 10:23` Also of the Levites: Jozabad, *_Shimei_*, Kelaiah (the same is Kelita), Pethahiah, Judah, and Eliezer.
* `Ezr 10:33` Of the sons of Hashum: Mattenai, Mattathah, Zabad, Eliphelet, Jeremai, Manasseh, and *_Shimei_*.
* `Ezr 10:38` Bani, Binnui, *_Shimei_*,
* `Est 2:5` Now in the palace of Shushan there was a certain Jew, whose name was Mordecai, the son of Jair, the son of *_Shimei_*, the son of Kish, a Benjaminite,
* `Zch 12:13` The family of the house of Levi by itself, and their wives by themselves; the family of *_Shimei_* by itself, and their wives by themselves;

_38 verses containing SHIMEI_

== SHIMEON

* `Ezr 10:31` And of the sons of Harim: Eliezer, Ishijah, Malchiah, Shemaiah, *_Shimeon_*,

_1 verse containing SHIMEON_

== SHIMHI

* `1Ch 8:21` Adaiah, Beraiah, and Shimrath were the sons of *_Shimhi_*.

_1 verse containing SHIMHI_

== SHIMI

* `Exo 6:17` The sons of Gershon: Libni and *_Shimi_*, according to their families.

_1 verse containing SHIMI_

== SHIMITES

* `Num 3:21` Of Gershon was the family of the Libnites and the family of the *_Shimites_*. These are the families of the Gershonites.

_1 verse containing SHIMITES_

== SHIMMA

* `1Ch 2:13` And Jesse begot his first-born Eliab, and Abinadab the second, *_Shimma_* the third,

_1 verse containing SHIMMA_

== SHIMON

* `1Ch 4:20` And the sons of *_Shimon_* were Amnon, Rinnah, Ben-hanan, and Tilon. And the sons of Ishi were Zoheth and Benzoheth.

_1 verse containing SHIMON_

== SHIMRATH

* `1Ch 8:21` Adaiah, Beraiah, and *_Shimrath_* were the sons of Shimhi.

_1 verse containing SHIMRATH_

== SHIMRI

* `1Ch 4:37` Ziza the son of Shiphi, the son of Allon, the son of Jedaiah, the son of *_Shimri_*, the son of Shemaiah—
* `1Ch 11:45` Jediael the son of *_Shimri_* and Joha his brother the Tizite,
* `2Ch 29:13` And of the sons of Elizaphan: *_Shimri_* and Jeiel; and of the sons of Asaph: Zechariah and Mattaniah;

_3 verses containing SHIMRI_

== SHIMRITH

* `2Ch 24:26` And these are those who conspired against him: Zabad the son of Shimeath the Ammonitess, and Jehozabad the son of *_Shimrith_* the Moabitess.

_1 verse containing SHIMRITH_

== SHIMRON

* `Gen 46:13` And the sons of Issachar: Tola, Phuvah, Job, and *_Shimron_*.
* `Num 26:24` Of Jashub, the family of the Jashubites; of *_Shimron_*, the family of the Shimronites.
* `Jsh 11:1` And it came to pass when Jabin king of Hazor had heard those things, that he sent to Jobab king of Madon, to the king of *_Shimron_*, to the king Achshaph,
* `Jsh 12:20` The king of *_Shimron_*-meron, one; the king of Achshaph, one;
* `Jsh 19:15` And Kattath, Nahallal, *_Shimron_*, Idalah, and Beth-lehem; twelve cities with their villages.
* `1Ch 7:1` Now the sons of Issachar were Tola, Puah, Jashub, and *_Shimron_*, four.

_6 verses containing SHIMRON_

== SHIMRON-MERON

* `Jsh 12:20` The king of *_Shimron-meron_*, one; the king of Achshaph, one;

_1 verse containing SHIMRON-MERON_

== SHIMRONITES

* `Num 26:24` Of Jashub, the family of the Jashubites; of Shimron, the family of the *_Shimronites_*.

_1 verse containing SHIMRONITES_

== SHIMSHAI

* `Ezr 4:8` Rehum the chancellor and *_Shimshai_* the scribe wrote a letter against Jerusalem to Artaxerxes the king in this sort.
* `Ezr 4:9` Then wrote Rehum the chancellor, *_Shimshai_* the scribe, and the rest of their companions, the Dianites, the Apharsathchites, the Tarpelites, the Apharsites, the Archevites, the Babylonians, the Susanchites, the Dehavites, and the Elamites,
* `Ezr 4:17` Then the king sent an answer to Rehum the chancellor, to *_Shimshai_* the scribe, and to the rest of their companions who dwell in Samaria, and to the rest beyond the river: "Peace, and at such a time.
* `Ezr 4:23` Now when the copy of king Artaxerxes' letter was read before Rehum, *_Shimshai_* the scribe, and their companions, they went up in haste to Jerusalem to the Jews and made them to cease by force and power.

_4 verses containing SHIMSHAI_

== SHIN

* `Psa 25:21` [*_SHIN_*] Let integrity and uprightness preserve me, for I wait on you.
* `Psa 119:161` [*_SHIN_*] Princes have persecuted me without a cause, but my heart stands in awe of your word.
* `Pro 31:30` [*_SHIN_*] Favor is deceitful and beauty is vain, but a woman who fears the LORD shall be praised.
* `Lam 1:21` [*_SHIN_*] They have heard that I sigh. There is no one to comfort me. All my enemies have heard of my trouble. They are glad that you have done it. You will bring the day that you have called, and they shall be like me.
* `Lam 2:21` [*_SHIN_*] The young and the old lie on the ground in the streets. My virgins and my young men have fallen by the sword. You have slain them in the day of your anger. You have killed and not pitied.
* `Lam 3:61` [*_SHIN_*] You have heard their reproach, O LORD, and all their imaginations against me,
* `Lam 4:21` [*_SHIN_*] Rejoice and be glad, O daughter of Edom, who dwells in the land of Uz. The cup shall also pass through to you. You shall be drunken and shall make yourself naked.

_7 verses containing SHIN_

== SHINAB

* `Gen 14:2` That these made war with Bera king of Sodom, Birsha king of Gomorrah, *_Shinab_* king of Admah, Shemeber king of Zeboiim, and the king of Bela, which is Zoar.

_1 verse containing SHINAB_

== SHINAR

* `Gen 10:10` And the beginning of his kingdom was Babel, Erech, Accad, and Calneh, in the land of *_Shinar_*.
* `Gen 11:2` And it came to pass as they journeyed from the east, that they found a plain in the land of *_Shinar_* and they dwelt there.
* `Gen 14:1` And it came to pass in the days of Amraphel king of *_Shinar_*, Arioch king of Ellasar, Chedorlaomer king of Elam, and Tidal king of nations,
* `Gen 14:9` With Chedorlaomer the king of Elam, Tidal king of nations, Amraphel king of *_Shinar_*, and Arioch king of Ellasar—four kings against five.
* `Isa 11:11` And it shall come to pass in that day, that the Lord will set his hand again the second time to recover the remnant of his people which shall be left from Assyria, from Egypt, from Pathros, from Cush, from Elam, from *_Shinar_*, from Hamath, and from the islands of the sea.
* `Dan 1:2` And the Lord gave Jehoiakim king of Judah into his hand, with part of the vessels of the house of God, which he carried into the land of *_Shinar_* to the house of his god. And he brought the vessels into the treasure-house of his god.
* `Zch 5:11` And he said to me, "To build a house in the land of *_Shinar_* for it. And it shall be established and set there upon her own base."

_7 verses containing SHINAR_

== SHINE

* `Num 6:25` May the LORD make his face *_shine_* upon you and be gracious to you.
* `Job 3:4` Let that day be darkness. Do not let God regard it from above, neither let the light *_shine_* upon it.
* `Job 10:3` Is it good to you that you should oppress, that you should despise the work of your hands and *_shine_* upon the counsel of the wicked?
* `Job 11:17` And your age shall be clearer than the noon-day. You shall *_shine_* forth. You shall be like the morning.
* `Job 18:5` Indeed, the light of the wicked shall be put out, and the spark of his fire shall not *_shine_*.
* `Job 22:28` You shall also decree a thing, and it shall be established to you. And the light shall *_shine_* upon your ways.
* `Job 36:32` With clouds he covers the light and commands it not to *_shine_* by the intervening cloud.
* `Job 37:15` Do you know when God disposed them and caused the light of his cloud to *_shine_*?
* `Job 41:32` He makes a path to *_shine_* after him. One would think the deep to be hoary.
* `Psa 31:16` Make your face to *_shine_* upon your servant. Save me for your mercies' sake.
* `Psa 67:1` [To the Chief Musician on Neginoth. A Psalm or Song.] May God be merciful to us and bless us and cause his face to *_shine_* upon us. [Selah.]
* `Psa 80:1` [To the Chief Musician upon Shoshannim Eduth. A Psalm of Asaph.] Give ear, O Shepherd of Israel, you who lead Joseph like a flock. You who dwell between the cherubim, *_shine_* forth.
* `Psa 80:3` Turn us back, O God, and cause your face to *_shine_*, and we shall be saved.
* `Psa 80:7` Turn us back, O God of hosts, and cause your face to *_shine_*, and we shall be saved.
* `Psa 80:19` Turn us back, O LORD God of hosts, cause your face to *_shine_*, and we shall be saved.
* `Psa 104:15` Wine that rejoices the heart of man, oil to cause his face to *_shine_*, and bread which strengthens man's heart.
* `Psa 119:135` Make your face to *_shine_* upon your servant and teach me your statutes.
* `Ecc 8:1` Who is like the wise man? And who knows the interpretation of a thing? A man's wisdom causes his face to *_shine_*, and the boldness of his face shall be changed.
* `Isa 13:10` For the stars of heaven and its constellations shall not give their light. The sun shall be darkened in his going forth, and the moon shall not cause her light to *_shine_*.
* `Isa 60:1` "Arise, *_shine_*, for your light has come, and the glory of the LORD has risen upon you.
* `Jer 5:28` They have become fat. They *_shine_*. They even surpass the deeds of the wicked. They do not judge the cause, the cause of the fatherless, yet they prosper. And the right of the needy they do not judge.
* `Dan 9:17` Now therefore, O our God, hear the prayer and supplications of your servant and cause your face to *_shine_* upon your sanctuary that is desolate, for the Lord's sake.
* `Dan 12:3` And those who are wise shall *_shine_* as the brightness of the firmament, and those who turn many to righteousness as the stars forever and ever.
* `Mth 5:16` Let your light thus *_shine_* before men so that they may see your good works and glorify your Father who is in heaven.
* `Mth 13:43` Then 'the righteous shall *_shine_* as the sun' in the kingdom of their Father. He who has ears to hear, let him hear.
* `2Co 4:4` In whom the god of this world has blinded the minds of those who do not believe, lest the light of the glorious gospel of Christ, who is the image of God, should *_shine_* to them.
* `2Co 4:6` For God, who commanded the light to *_shine_* out of darkness, has shined into our hearts to give the light of the knowledge of the glory of God in the face of Jesus Christ.
* `Phl 2:15` So that you may be blameless and innocent, the sons of God without rebuke, in the midst of a crooked and perverse nation, among whom you *_shine_* as lights in the world,
* `Rev 8:12` And the fourth angel sounded, and the third part of the sun was smitten, along with the third part of the moon and the third part of the stars, so that the third part of them was darkened. And the day did not *_shine_* for a third part of it, and the night likewise.
* `Rev 18:23` The light of a candle shall no longer *_shine_* in you. The voice of the bridegroom and of the bride shall no longer be heard in you. For your merchants were the great men of the earth, because by your sorceries all nations were deceived.
* `Rev 21:23` And the city had no need of the sun nor of the moon to *_shine_* in it, for the glory of God enlightened it, and the Lamb is its light.

_31 verses containing SHINE_

== SHINED

* `Deu 33:2` And he said, "The LORD came from Sinai, and rose up from Seir to them. He *_shined_* forth from mount Paran, and he came with tens of thousands of saints. From his right hand went a fiery law for them.
* `Job 29:3` When his candle *_shined_* upon my head and by his light I walked through darkness,
* `Job 31:26` If I have beheld the sun when it *_shined_* or the moon walking in brightness,
* `Psa 50:2` Out of Zion, the perfection of beauty, God has *_shined_*.
* `Isa 9:2` The people who walked in darkness have seen a great light. Those who dwell in the land of the shadow of death, upon them the light has *_shined_*.
* `Ezk 43:2` And behold, the glory of the God of Israel came from the way of the east. And his voice was like a noise of many waters. And the earth *_shined_* with his glory.
* `Act 9:3` And as he journeyed, he came near Damascus, and suddenly there *_shined_* around him a light from heaven,
* `Act 12:7` And behold, the angel of the Lord came upon him, and a light *_shined_* in the prison, and he smote Peter on the side and raised him up, saying, "Arise quickly." And his chains fell off from his hands.
* `2Co 4:6` For God, who commanded the light to shine out of darkness, has *_shined_* into our hearts to give the light of the knowledge of the glory of God in the face of Jesus Christ.

_9 verses containing SHINED_

== SHINES

* `Psa 139:12` Even the darkness does not hide from you, but the night *_shines_* like the day. The darkness and the light are both alike to you.
* `Pro 4:18` But the path of the just is like the shining light that *_shines_* more and more to the perfect day.
* `Mth 24:27` For as the lightning comes out of the east and *_shines_* even to the west, so shall the coming of the Son of man also be.
* `Luk 17:24` For as the lightning that lightens from one part under heaven *_shines_* to the other part under heaven, so the Son of man shall also be in his day.
* `Jhn 1:5` And the light *_shines_* in darkness, and the darkness did not overcome it.
* `2Pe 1:19` We have also a more sure word of prophecy, to which you do well that you take heed, as to a light that *_shines_* in a dark place, until the day dawns and the day-star arises in your hearts,
* `1Jn 2:8` Again, a new commandment I write to you, which thing is true in him and in you, because the darkness is past and the true light now *_shines_*.

_7 verses containing SHINES_

== SHINING

* `2Sa 23:4` And he shall be like the light of the morning when the sun rises, even a morning without clouds, like the tender grass springing out of the earth from clear *_shining_* after the rain.'
* `Pro 4:18` But the path of the just is like the *_shining_* light that shines more and more to the perfect day.
* `Isa 4:5` The LORD will create upon every dwelling place of mount Zion and upon her assemblies a cloud and smoke by day and the *_shining_* of a flaming fire by night, for upon all the glory there shall be a defense.
* `Joe 2:10` The earth shall quake before them. The heavens shall tremble. The sun and the moon shall be dark, and the stars shall withdraw their *_shining_*.
* `Joe 3:15` The sun and the moon shall be darkened, and the stars shall withdraw their *_shining_*.
* `Hab 3:11` The sun and moon stood still in their habitation. At the light of your arrows they went, and at the *_shining_* of your glittering spear.
* `Mrk 9:3` And his clothing became *_shining_*, exceedingly white as snow, so as no fuller on earth can whiten them.
* `Luk 11:36` If your whole body therefore is full of light, having no dark part, the whole shall be full of light, as when the bright *_shining_* of a candle gives you light."
* `Luk 24:4` And it came to pass, as they were much perplexed at this, behold, two men stood by them in *_shining_* garments.
* `Jhn 5:35` He was a burning and a *_shining_* light, and you were willing for a season to rejoice in his light.
* `Act 26:13` At mid-day, O king, I saw in the way a light from heaven surpassing the brightness of the sun, *_shining_* around me and those who journeyed with me.
* `Rev 1:16` And he had in his right hand seven stars. And out of his mouth went a sharp two-edged sword. And his countenance was as the sun *_shining_* in its strength.

_12 verses containing SHINING_

== SHIP

* `Pro 30:19` The way of an eagle in the air, the way of a serpent upon a rock, the way of a *_ship_* in the midst of the sea, and the way of a man with a young woman.
* `Isa 33:21` But there the glorious LORD will be for us a place of broad rivers and streams, in which no galley with oars shall go, neither shall gallant *_ship_* pass through it.
* `Ezk 27:5` They have made all your *_ship_*-boards of fir-trees of Senir. They have taken cedars from Lebanon to make masts for you.
* `Jna 1:3` But Jonah arose to flee to Tarshish from the presence of the LORD and went down to Joppa, and he found a *_ship_* going to Tarshish. So he paid its fare and went down into it to go with them to Tarshish from the presence of the LORD.
* `Jna 1:4` But the LORD sent out a great wind into the sea, and there was a mighty tempest in the sea, so that the *_ship_* was in danger of being broken.
* `Jna 1:5` Then the mariners were afraid, and every man cried to his god and cast the wares that were in the *_ship_* into the sea to lighten it of them. But Jonah had gone down into the sides of the *_ship_*, and he lay and was fast asleep.
* `Jna 1:6` So the *_ship_*-master came to him and said to him, "What do you mean, O sleeper? Arise, call upon your God. It may be that God will think upon us so that we do not perish."
* `Act 20:13` And we went before to a *_ship_* and sailed to Assos, intending to take in Paul there. For thus he had appointed, intending himself to go on foot.
* `Act 20:38` Sorrowing most of all for the words which he spoke, that they should see his face no more. And they accompanied him to the *_ship_*.
* `Act 21:2` And finding a *_ship_* sailing over to Phenicia, we went aboard and set forth.
* `Act 21:3` Now when we had come in sight of Cyprus, leaving it on the left hand, we sailed into Syria and landed at Tyre, for there the *_ship_* was to unload her burden.
* `Act 21:6` And when we had taken our leave of one another, we went on board the *_ship_* and they returned home again.
* `Act 27:2` And entering into a *_ship_* of Adramyttium, we launched, meaning to sail by the coasts of Asia. Aristarchus, a Macedonian of Thessalonica, was with us.
* `Act 27:6` And there the centurion found a *_ship_* of Alexandria sailing into Italy and he put us therein.
* `Act 27:10` And said to them, "Sirs, I perceive that this voyage will be with hurt and much damage, not only of the cargo and the *_ship_*, but also of our lives."
* `Act 27:11` Nevertheless, the centurion believed the master and the owner of the *_ship_* more than the things which were spoken by Paul.
* `Act 27:15` And when the *_ship_* was caught and could not bear up into the wind, we let her drive.
* `Act 27:17` And when they hoisted it up, they used ropes to undergird the *_ship_*. Then, fearing that they would fall into the quicksands, they struck sail and were thus driven.
* `Act 27:19` And on the third day, we cast out the tackling of the *_ship_* with our own hands.
* `Act 27:22` And now I exhort you to be of good cheer, for there shall be no loss of life among you, but of the *_ship_*.
* `Act 27:30` And as the sailors were about to flee out of the *_ship_*, when they had let down the boat into the sea under color as though they would cast anchors out of the foreship,
* `Act 27:31` Paul said to the centurion and to the soldiers, "Unless these abide in the *_ship_*, you cannot be saved."
* `Act 27:37` In all, we were two hundred and seventy-six souls on the *_ship_*.
* `Act 27:38` And when they had eaten enough, they lightened the *_ship_* and cast the wheat into the sea.
* `Act 27:39` And when it was day, they did not know the land. But they discovered a certain creek with a shore, into which they purposed, if it were possible, to thrust in the *_ship_*.
* `Act 27:41` And falling into a place where two seas met, they ran the *_ship_* aground. And the forepart stuck firmly and remained immovable, but the back part was broken with the violence of the waves.
* `Act 27:44` And the rest, some on boards and some on broken pieces of the *_ship_*. And so it came to pass, that they all escaped safely to land.
* `Act 28:11` And after three months, we departed in a *_ship_* from Alexandria that had wintered on the island, whose sign was Castor and Pollux.
* `Rev 18:17` For in one hour such great wealth has come to nothing.' And every *_ship_*-master and all the company in ships, along with sailors and as many as trade by sea, stood afar off,

_29 verses containing SHIP_

== SHIP-BOARDS

* `Ezk 27:5` They have made all your *_ship-boards_* of fir-trees of Senir. They have taken cedars from Lebanon to make masts for you.

_1 verse containing SHIP-BOARDS_

== SHIP-MASTER

* `Jna 1:6` So the *_ship-master_* came to him and said to him, "What do you mean, O sleeper? Arise, call upon your God. It may be that God will think upon us so that we do not perish."
* `Rev 18:17` For in one hour such great wealth has come to nothing.' And every *_ship-master_* and all the company in ships, along with sailors and as many as trade by sea, stood afar off,

_2 verses containing SHIP-MASTER_

== SHIPHI

* `1Ch 4:37` Ziza the son of *_Shiphi_*, the son of Allon, the son of Jedaiah, the son of Shimri, the son of Shemaiah—

_1 verse containing SHIPHI_

== SHIPHMITE

* `1Ch 27:27` And over the vineyards was Shimei the Ramathite; and over the increase of the vineyards for the wine cellars was Zabdi the *_Shiphmite_*;

_1 verse containing SHIPHMITE_

== SHIPHRAH

* `Exo 1:15` And the king of Egypt spoke to the Hebrew midwives (of which the name of one was *_Shiphrah_* and the name of the other Puah),

_1 verse containing SHIPHRAH_

== SHIPHTAN

* `Num 34:24` The prince of the tribe of the children of Ephraim, Kemuel the son of *_Shiphtan_*;

_1 verse containing SHIPHTAN_

== SHIPMEN

* `1Ki 9:27` And Hiram sent in the navy his servants, *_shipmen_* who had knowledge of the sea, with the servants of Solomon.

_1 verse containing SHIPMEN_

== SHIPS

* `Gen 49:13` "Zebulun shall dwell at the haven of the sea, and he shall be for a haven of *_ships_*. And his border shall be to Zidon.
* `Num 24:24` And *_ships_* shall come from the coast of Chittim and shall afflict Ashur and shall afflict Eber, and he also shall perish forever."
* `Deu 28:68` And the LORD shall bring you into Egypt again with *_ships_* by the way of which I have said to you, 'You shall no more see it again.' And there you shall be sold to your enemies for men-servants and women-servants, and no man shall buy you."
* `Jdg 5:17` Gilead stayed beyond the Jordan. And why did Dan remain in *_ships_*? Asher continued on the sea-shore and stayed in his breaches.
* `1Ki 9:26` And king Solomon made a navy of *_ships_* in Ezion-geber, which is beside Eloth, on the shore of the Red Sea in the land of Edom.
* `1Ki 22:48` Jehoshaphat made *_ships_* of Tarshish to go to Ophir for gold, but they did not go, for the *_ships_* were broken at Ezion-geber.
* `1Ki 22:49` Then Ahaziah the son of Ahab said to Jehoshaphat, "Let my servants go with your servants in the *_ships_*." But Jehoshaphat would not.
* `2Ch 8:18` And Huram sent to him by the hands of his servants *_ships_* and servants who had knowledge of the sea, and they went with the servants of Solomon to Ophir and took from there four hundred and fifty talents of gold and brought them to king Solomon.
* `2Ch 9:21` For the king's *_ships_* went to Tarshish with the servants of Huram. Once every three years the *_ships_* of Tarshish came bringing gold, silver, ivory, apes, and peacocks.
* `2Ch 20:36` And he joined himself with him to make *_ships_* to go to Tarshish. And they made the *_ships_* in Ezion-geber.
* `2Ch 20:37` Then Eliezer the son of Dodavah of Mareshah prophesied against Jehoshaphat, saying, "Because you have joined yourself with Ahaziah, the LORD has broken your works." And the *_ships_* were broken so that they were not able to go to Tarshish.
* `Job 9:26` They have passed by like the swift *_ships_*, like the eagle that hastens to the prey.
* `Psa 48:7` You break the *_ships_* of Tarshish with an east wind.
* `Psa 104:26` There go the *_ships_*. There is that leviathan which you have made to play therein.
* `Psa 107:23` Those who go down to the sea in *_ships_*, who do business on great waters,
* `Pro 31:14` [HE] She is like the merchant's *_ships_*. She brings her food from afar.
* `Isa 2:16` And upon all the *_ships_* of Tarshish, and upon all pleasant pictures.
* `Isa 23:1` [The burden of Tyre.] Howl, you *_ships_* of Tarshish, for it is laid waste, so that there is no house, no entering in. From the land of Chittim it is revealed to them.
* `Isa 23:14` Howl, you *_ships_* of Tarshish, for your strength is laid waste.
* `Isa 43:14` Thus says the LORD, your Redeemer, the Holy One of Israel: "For your sake I have sent to Babylon and have brought down all their nobles and the Chaldeans, whose cry is in the *_ships_*.
* `Isa 60:9` Surely the coastlands shall wait for me, and the *_ships_* of Tarshish first, to bring your sons from far, their silver and their gold with them, to the name of the LORD your God and to the Holy One of Israel, because he has glorified you.
* `Ezk 27:9` The ancients of Gebal and its wise men were in you as your caulkers. All the *_ships_* of the sea with their mariners were in you to occupy your merchandise.
* `Ezk 27:25` "The *_ships_* of Tarshish sang of you in your market. And you were replenished and made very glorious in the midst of the seas.
* `Ezk 27:29` And all who handle the oar, the mariners, and all the pilots of the sea shall come down from their *_ships_*. They shall stand upon the land.
* `Ezk 30:9` In that day messengers shall go forth from me in *_ships_* to make the careless Cushites afraid, and great pain shall come upon them, as in the day of Egypt, for behold, it comes."
* `Dan 11:30` For the *_ships_* of Chittim shall come against him; therefore, he shall be grieved, return, and have indignation against the holy covenant. He shall do so. And he shall even return and have regard for those who forsake the holy covenant.
* `Dan 11:40` "And at the time of the end the king of the south shall war against him. And the king of the north shall come against him like a whirlwind, with chariots, with horsemen, and with many *_ships_*, and he shall enter into the countries and shall overflow and pass over.
* `Jms 3:4` Behold also the *_ships_*: though they are so great and are driven by fierce winds, yet they are directed with a very small helm, wherever the helmsman wills.
* `Rev 8:9` And the third part of the creatures having life which were in the sea died. And the third part of the *_ships_* were destroyed.
* `Rev 18:17` For in one hour such great wealth has come to nothing.' And every ship-master and all the company in *_ships_*, along with sailors and as many as trade by sea, stood afar off,
* `Rev 18:19` And they cast dust on their heads and cried, weeping and wailing, saying, 'Alas, alas, that great city in which all who had *_ships_* in the sea were made rich by reason of her opulence!' For in one hour she has been made desolate.

_31 verses containing SHIPS_

== SHIPWRECK

* `2Co 11:25` Three times I was beaten with rods, once I was stoned, three times I suffered *_shipwreck_*, a night and a day I have been in the deep;
* `1Ti 1:19` Holding faith and a good conscience, which some having thrust away, have made *_shipwreck_* concerning faith,

_2 verses containing SHIPWRECK_

== SHISHA

* `1Ki 4:3` Elihoreph and Ahiah the sons of *_Shisha_* were scribes, Jehosaphat the son of Ahilud the recorder,

_1 verse containing SHISHA_

== SHISHAK

* `1Ki 11:40` Solomon therefore sought to kill Jeroboam. And Jeroboam arose and fled into Egypt, to *_Shishak_* king of Egypt, and was in Egypt until the death of Solomon.
* `1Ki 14:25` And it came to pass in the fifth year of king Rehoboam, that *_Shishak_* king of Egypt came up against Jerusalem.
* `2Ch 12:2` And it came to pass, that in the fifth year of king Rehoboam, *_Shishak_* king of Egypt came up against Jerusalem because they had transgressed against the LORD,
* `2Ch 12:5` Then Shemaiah the prophet came to Rehoboam and to the princes of Judah who were assembled at Jerusalem because of *_Shishak_*, and said to them, "Thus says the LORD: 'You have forsaken me, and therefore, I have also left you in the hand of *_Shishak_*.'"
* `2Ch 12:7` And when the LORD saw that they humbled themselves, the word of the LORD came to Shemaiah, saying, "They have humbled themselves; therefore, I will not destroy them, but I will grant them some deliverance. And my wrath shall not be poured out upon Jerusalem by the hand of *_Shishak_*.
* `2Ch 12:9` So *_Shishak_* king of Egypt came up against Jerusalem and took away the treasures of the house of the LORD and the treasures of the king's house. He took everything. He also carried away the shields of gold which Solomon had made.

_6 verses containing SHISHAK_

== SHITRAI

* `1Ch 27:29` And over the herds that fed in Sharon was *_Shitrai_* the Sharonite; and over the herds that were in the valleys was Shaphat the son of Adlai;

_1 verse containing SHITRAI_

== SHITTAH-TREE

* `Isa 41:19` I will plant in the wilderness the cedar, the *_shittah-tree_*, the myrtle, and the oil-tree. I will set in the desert the fir-tree, the pine, and the box-tree together,

_1 verse containing SHITTAH-TREE_

== SHITTIM

* `Exo 25:5` Rams' skins dyed red, badgers' skins, *_shittim_* wood,
* `Exo 25:10` "And they shall make an ark of *_shittim_* wood. Two and a half cubits shall be its length, a cubit and a half its breadth, and a cubit and a half its height.
* `Exo 25:13` And you shall make staffs of *_shittim_* wood and overlay them with gold.
* `Exo 25:23` "You shall also make a table of *_shittim_* wood. Its length shall be two cubits, its breadth a cubit, and its height a cubit and a half.
* `Exo 25:28` And you shall make the staffs of *_shittim_* wood and overlay them with gold so that the table may be borne with them.
* `Exo 26:15` "And you shall make boards for the tabernacle of *_shittim_* wood standing up.
* `Exo 26:26` "And you shall make bars of *_shittim_* wood: five for the boards of one side of the tabernacle,
* `Exo 26:32` And you shall hang it upon four pillars of *_shittim_* wood overlaid with gold. Their hooks shall be of gold upon the four sockets of silver.
* `Exo 26:37` And you shall make for the hanging five pillars of *_shittim_* wood and overlay them with gold, and their hooks shall be of gold. And you shall cast five sockets of brass for them."
* `Exo 27:1` "And you shall make an altar of *_shittim_* wood five cubits long and five cubits broad. The altar shall be square, and its height shall be three cubits.
* `Exo 27:6` And you shall make staffs for the altar, staffs of *_shittim_* wood, and overlay them with brass.
* `Exo 30:1` "And you shall make an altar to burn incense upon. Of *_shittim_* wood you shall make it.
* `Exo 30:5` And you shall make the staffs of *_shittim_* wood and overlay them with gold.
* `Exo 35:7` Rams' skins dyed red, badgers' skins, *_shittim_* wood,
* `Exo 35:24` Everyone who offered an offering of silver and brass brought the LORD'S offering. And every man with whom was found *_shittim_* wood for any work of the service brought it.
* `Exo 36:20` And he made boards for the tabernacle of *_shittim_* wood, standing up.
* `Exo 36:31` And he made bars of *_shittim_* wood: five for the boards of one side of the tabernacle,
* `Exo 36:36` And he made for it four pillars of *_shittim_* wood and overlaid them with gold. Their hooks were of gold and he cast for them four sockets of silver.
* `Exo 37:1` And Bezaleel made the ark of *_shittim_* wood. Two and a half cubits was its length, a cubit and a half its breadth, and a cubit and a half its height.
* `Exo 37:4` And he made staffs of *_shittim_* wood and overlaid them with gold.
* `Exo 37:10` And he made the table of *_shittim_* wood. Two cubits was its length, a cubit its breadth, and a cubit and a half its height.
* `Exo 37:15` And he made the staffs of *_shittim_* wood to bear the table and overlaid them with gold.
* `Exo 37:25` And he made the incense-altar of *_shittim_* wood. Its length was a cubit and its breadth a cubit. It was square and two cubits was its height. Its horns were of the same.
* `Exo 37:28` And he made the staffs of *_shittim_* wood and overlaid them with gold.
* `Exo 38:1` And he made the altar of burnt-offering of *_shittim_* wood. Five cubits was its length and five cubits its breadth. It was square and its height was three cubits.
* `Exo 38:6` And he made the staffs of *_shittim_* wood and overlaid them with brass.
* `Num 25:1` And Israel stayed in *_Shittim_*, and the people began to commit lewdness with the daughters of Moab.
* `Num 33:49` And they encamped by the Jordan, from Beth-jeshimoth even to Abel-*_shittim_* in the plains of Moab.
* `Deu 10:3` And I made an ark of *_shittim_* wood, hewed two tablets of stone like the first, and ascended the mountain, having the two tablets in my hand.
* `Jsh 2:1` And Joshua the son of Nun sent from *_Shittim_* two men to spy secretly, saying, "Go, view the land, even Jericho." And they went and came into the house of a harlot named Rahab and lodged there.
* `Jsh 3:1` And Joshua rose early in the morning. And they set out from *_Shittim_* and came to the Jordan—he and all the children of Israel—and lodged there before they passed over.
* `Joe 3:18` And it shall come to pass in that day, that the mountains shall drop down new wine, the hills shall flow with milk, and all the rivers of Judah shall flow with waters, and a fountain shall come forth from the house of the LORD and shall water the valley of *_Shittim_*.
* `Mic 6:5` O my people, remember now what Balak king of Moab consulted, and what Balaam the son of Beor answered him, [and what I did] from *_Shittim_* to Gilgal, so that you may know the righteousness of the LORD."

_33 verses containing SHITTIM_

== SHIZA

* `1Ch 11:42` Adina the son of *_Shiza_* the Reubenite—a captain of the Reubenites, and thirty with him,

_1 verse containing SHIZA_

