= SUAH - SUPREME
:toc:

== SUAH

* `1Ch 7:36` The sons of Zophah: *_Suah_*, Harnepher, Shual, Beri, Imrah,

_1 verse containing SUAH_

== SUBDUE

* `Gen 1:28` And God blessed them, and God said to them, "Be fruitful, multiply, replenish the earth, and *_subdue_* it. And have dominion over the fish of the sea, over the bird of the air, and over every living animal that moves upon the earth."
* `1Ch 17:10` Since the time that I commanded judges to be over my people Israel. Moreover, I will *_subdue_* all your enemies. Furthermore, I tell you that the LORD will build you a house.
* `2Ch 28:10` And now you purpose to *_subdue_* the children of Judah and Jerusalem for men-servants and women-servants for yourselves. But are there not with you, even with you, sins against the LORD your God?
* `Psa 47:3` He shall *_subdue_* the people under us and the nations under our feet.
* `Psa 81:14` I would soon *_subdue_* their enemies and turn my hand against their adversaries.
* `Isa 45:1` Thus says the LORD to his anointed, to Cyrus, whose right hand I have held to *_subdue_* nations before him, and I will ungird the loins of kings, to open before him the two-leaved gates, and the gates shall not be shut:
* `Dan 7:24` And the ten horns out of this kingdom are ten kings who shall arise. And another shall rise after them, and he shall be diverse from the first and he shall *_subdue_* three kings.
* `Zch 9:15` The LORD of hosts will defend them. They shall devour and *_subdue_* with sling-stones. They shall drink and make a noise as through wine. They shall be filled like bowls and as the corners of the altar.
* `Phl 3:21` Who will change our vile body so that it may be fashioned like his glorious body, according to the working by which he is able even to *_subdue_* all things to himself.

_9 verses containing SUBDUE_

== SUBDUED

* `Num 32:22` And the land is *_subdued_* before the LORD, then afterward you shall return and be guiltless before the LORD and before Israel. And this land shall be your possession before the LORD.
* `Num 32:29` And Moses said to them, "If the children of Gad and the children of Reuben will pass with you over the Jordan, every man armed for battle before the LORD, and the land is *_subdued_* before you, then you shall give them the land of Gilead for a possession.
* `Deu 20:20` Only the trees which you know that are not trees for food you shall destroy and cut down. And you shall build bulwarks against the city that makes war with you until it is *_subdued_*."
* `Jsh 18:1` And the whole congregation of the children of Israel assembled at Shiloh and set up the Tabernacle of the Congregation there. And the land was *_subdued_* before them.
* `Jdg 3:30` So Moab was *_subdued_* that day under the hand of Israel. And the land had rest for eighty years.
* `Jdg 4:23` So God *_subdued_* on that day Jabin the king of Canaan before the children of Israel.
* `Jdg 8:28` Thus Midian was *_subdued_* before the children of Israel, so that they raised their heads no more. And the country was in quietness for forty years in the days of Gideon.
* `Jdg 11:33` And he smote them from Aroer even as far as Minnith, even twenty cities, and to the plain of the vineyards, with a very great slaughter. Thus the children of Ammon were *_subdued_* before the children of Israel.
* `1Sa 7:13` So the Philistines were *_subdued_* and they no longer came into the borders of Israel. And the hand of the LORD was against the Philistines all the days of Samuel.
* `2Sa 8:1` And after this it came to pass, that David smote the Philistines and *_subdued_* them. And David took Metheg-ammah out of the hand of the Philistines.
* `2Sa 8:11` Which also king David dedicated to the LORD, with the silver and gold that he had dedicated from all nations which he *_subdued_*:
* `2Sa 22:40` For you have girded me with strength to battle. Those who rose up against me you have *_subdued_* under me.
* `1Ch 18:1` Now after this it came to pass that David smote the Philistines, *_subdued_* them, and took Gath and its towns out of the hand of the Philistines.
* `1Ch 20:4` And it came to pass after this, that there arose war at Gezer with the Philistines. At that time Sibbechai the Hushathite slew Sippai, who was of the children of the giant, and they were *_subdued_*.
* `1Ch 22:18` "Is the LORD your God not with you? And has he not given you rest on every side? For he has given the inhabitants of the land into my hand, and the land is *_subdued_* before the LORD and before his people.
* `Neh 9:24` Thus the children went in and possessed the land, and you *_subdued_* before them the inhabitants of the land, the Canaanites, and gave them into their hands, with their kings and the people of the land, so that they might do with them as they wished.
* `Psa 18:39` For you have girded me with strength to battle. You have *_subdued_* under me those who rose up against me.
* `1Co 15:28` And when all things are *_subdued_* to him, then the Son himself shall also be subject to him who put all things under him so that God may be all in all.
* `Heb 11:33` Who through faith *_subdued_* kingdoms, wrought righteousness, obtained promises, stopped the mouths of lions,

_19 verses containing SUBDUED_

== SUBDUES

* `Psa 18:47` It is God who avenges me and *_subdues_* the people under me.
* `Psa 144:2` My goodness, my fortress, my high tower, and my deliverer; my shield, and he in whom I trust, who *_subdues_* my people under me.
* `Dan 2:40` "And the fourth kingdom shall be strong as iron, because iron breaks in pieces and *_subdues_* all things. And as iron that breaks all these, it shall break in pieces and bruise.

_3 verses containing SUBDUES_

== SUBJECT

* `Luk 2:51` And he went down with them and came to Nazareth, and was *_subject_* to them. But his mother kept all these sayings in her heart.
* `Luk 10:17` And the seventy returned with joy, saying, "Lord, even the demons are *_subject_* to us through your name."
* `Luk 10:20` Nevertheless, do not rejoice in this, that the spirits are *_subject_* to you, but rather rejoice because your names are written in heaven."
* `Rom 8:7` Because the carnal mind is enmity against God, for it is not *_subject_* to the law of God, neither indeed can be.
* `Rom 8:20` For the creature was made *_subject_* to vanity, not willingly, but by reason of him who has subjected the same in hope,
* `Rom 13:1` Let every soul be *_subject_* to the higher powers, for there is no power but from God. The powers that exist are ordained by God.
* `Rom 13:5` Therefore, it is necessary for you to be *_subject_*, not only for wrath, but also for conscience' sake.
* `1Co 14:32` And the spirits of the prophets are *_subject_* to the prophets.
* `1Co 15:28` And when all things are subdued to him, then the Son himself shall also be *_subject_* to him who put all things under him so that God may be all in all.
* `Eph 5:24` Therefore, as the church is *_subject_* to Christ, so let wives be to their own husbands in everything.
* `Col 2:20` Therefore, if you are dead with Christ from the rudiments of the world, why, as though living in the world, are you *_subject_* to ordinances
* `Tit 3:1` Put them in mind to be *_subject_* to principalities and powers, to obey magistrates, to be ready for every good work,
* `Heb 2:8` You have put all things in subjection under his feet." For in that he put all in subjection under him, he left nothing that is not made *_subject_* to him. But now we do not yet see all things subjected to him.
* `Heb 2:15` And deliver those who through fear of death were all their life-time *_subject_* to bondage.
* `Jms 5:17` Elijah was a man *_subject_* to similar passions as we are, and he prayed earnestly that it might not rain, and it did not rain on the earth for three years and six months.
* `1Pe 2:18` Servants, be *_subject_* to your masters with all fear, not only to the good and gentle, but also to the unfair.
* `1Pe 3:22` Who has gone into heaven and is on the right hand of God, with angels, authorities, and powers being made *_subject_* to him.
* `1Pe 5:5` Likewise, you younger ones, submit yourselves to the elder. Indeed, all of you be *_subject_* to one another and be clothed with humility, for "God resists the proud and gives grace to the humble."

_18 verses containing SUBJECT_

== SUBJECTED

* `Jsh 17:13` And it came to pass, that when the children of Israel had become strong, they *_subjected_* the Canaanites to tribute, but did not utterly expel them.
* `Jdg 1:28` And it came to pass when Israel was strong, that they *_subjected_* the Canaanites to tribute and did not utterly expel them.
* `2Ki 23:33` And Pharaoh-nechoh put him in bonds at Riblah in the land of Hamath so that he might not reign in Jerusalem, and *_subjected_* the land to a tribute of one hundred talents of silver and a talent of gold.
* `Ezk 34:27` And the tree of the field shall yield her fruit, and the earth shall yield her increase, and they shall be safe in their land. And they shall know that I am the LORD when I have broken the bars of their yoke and delivered them out of the hand of those who *_subjected_* them to service.
* `Rom 8:20` For the creature was made subject to vanity, not willingly, but by reason of him who has *_subjected_* the same in hope,
* `Heb 2:8` You have put all things in subjection under his feet." For in that he put all in subjection under him, he left nothing that is not made subject to him. But now we do not yet see all things *_subjected_* to him.

_6 verses containing SUBJECTED_

== SUBJECTION

* `Psa 106:42` Their enemies also oppressed them, and they were brought into *_subjection_* under their hand.
* `Jer 25:14` For many nations and great kings shall also reduce them to *_subjection_*. And I will recompense them according to their deeds and according to the works of their own hands.'"
* `Jer 27:7` And all nations shall serve him, his son, and his son's son until the very time of his land comes. And then many nations and great kings shall bring him into *_subjection_*.
* `Jer 30:8` 'For it shall come to pass in that day,' says the LORD of hosts, 'that I will break his yoke from off your neck and will tear off your bonds, and strangers shall no longer bring him into *_subjection_*,
* `Jer 34:11` But afterward, they turned and caused the men-servants and the women-servants whom they had liberated to return, and brought them into *_subjection_* as men-servants and as women-servants.
* `Jer 34:16` But you turned and profaned my name and each caused his man-servant and each his woman-servant, whom he had set at liberty at their pleasure, to return, and brought them into *_subjection_* to be your men-servants and women-servants.'
* `1Co 9:27` But I buffet my body and bring it into *_subjection_*, lest by any means when I have preached to others, I myself should be a cast-away.
* `2Co 9:13` Because of the proof of this ministration, they glorify God for your professed *_subjection_* to the gospel of Christ and for your liberal contribution to them and to all men,
* `Gal 2:5` To whom we gave place by *_subjection_*, not even for an hour, so that the truth of the gospel might continue with you.
* `1Ti 2:11` Let the woman learn in silence with all *_subjection_*.
* `1Ti 3:4` One who rules his own house well, having his children in *_subjection_* with all gravity
* `Heb 2:5` For to the angels he has not put in *_subjection_* the world to come, concerning which we speak.
* `Heb 2:8` You have put all things in *_subjection_* under his feet." For in that he put all in *_subjection_* under him, he left nothing that is not made subject to him. But now we do not yet see all things subjected to him.
* `Heb 12:9` Furthermore, we have had fathers of our flesh who corrected us, and we gave them reverence. Shall we not much rather be in *_subjection_* to the Father of spirits and live?
* `1Pe 3:1` Likewise, wives, be in *_subjection_* to your own husbands so that if any do not obey the word, they also may, without the word, be won by the deportment of the wives
* `1Pe 3:5` For after this manner in former times the holy women who trusted in God also adorned themselves, being in *_subjection_* to their own husbands,

_16 verses containing SUBJECTION_

== SUBMIT

* `Gen 16:9` And the angel of the LORD said to her, "Return to your mistress and *_submit_* yourself under her hands."
* `2Sa 22:45` Strangers shall *_submit_* themselves to me. As soon as they hear, they shall be obedient to me.
* `Psa 18:44` As soon as they hear of me, they shall obey me. The strangers shall *_submit_* themselves to me.
* `Psa 66:3` Say to God, "How awesome you are in your works! Through the greatness of your power your enemies shall *_submit_* themselves to you.
* `1Co 16:16` That you *_submit_* yourselves to such as these and to everyone who helps with us and labors.
* `Eph 5:22` Wives, *_submit_* yourselves to your own husbands, as to the Lord.
* `Col 3:18` Wives, *_submit_* yourselves to your own husbands, as it is fit in the Lord.
* `Heb 13:17` Obey your leaders and *_submit_* yourselves, for they watch for your souls as those who must give account, so that they may do it with joy and not with grief, for that is unprofitable for you.
* `Jms 4:7` *_Submit_* yourselves therefore to God. Resist the devil and he will flee from you.
* `1Pe 2:13` *_Submit_* yourselves to every ordinance of man for the Lord's sake, whether to the king as supreme,
* `1Pe 5:5` Likewise, you younger ones, *_submit_* yourselves to the elder. Indeed, all of you be subject to one another and be clothed with humility, for "God resists the proud and gives grace to the humble."

_11 verses containing SUBMIT_

== SUBMITS

* `Psa 68:30` Rebuke the wild beast of the reeds, the multitude of the bulls with the calves of the people, until each *_submits_* himself with pieces of silver. Scatter the people who delight in war.

_1 verse containing SUBMITS_

== SUBMITTED

* `1Ch 29:24` And all the princes, the mighty men, and all the sons likewise of king David *_submitted_* themselves to Solomon the king.
* `Psa 81:15` The haters of the LORD should have *_submitted_* themselves to him, and their time should have endured forever.
* `Rom 10:3` For they, being ignorant of God's righteousness and seeking to establish their own righteousness, have not *_submitted_* themselves to the righteousness of God.

_3 verses containing SUBMITTED_

== SUBMITTING

* `Eph 5:21` *_Submitting_* yourselves to one another in the fear of God.

_1 verse containing SUBMITTING_

== SUBORNED

* `Act 6:11` Then they *_suborned_* men, who said, "We have heard him speak blasphemous words against Moses and against God."

_1 verse containing SUBORNED_

== SUBSTANCE

* `Gen 7:4` For after seven more days, I will cause it to rain upon the earth forty days and forty nights. And every living *_substance_* that I have made I will destroy from the face of the earth."
* `Gen 7:23` And every living *_substance_* was destroyed which was upon the face of the ground—man, livestock, the creeping animals, and the bird of heaven—and they were destroyed from the earth. And only Noah and those who were with him in the ark remained alive.
* `Gen 12:5` And Abram took Sarai his wife, Lot his brother's son, all their *_substance_* that they had gathered, and the souls whom they had gotten in Haran, and they went to go forth into the land of Canaan. And into the land of Canaan they came.
* `Gen 13:6` And the land was not able to bear them so that they might dwell together, for their *_substance_* was so great that they could not dwell together.
* `Gen 15:14` And also that nation which they shall serve, I will judge. And afterward, they shall come out with great *_substance_*.
* `Gen 34:23` Will their livestock, their *_substance_*, and every beast of theirs not be ours? Only let us consent to them, and they will dwell with us."
* `Gen 36:6` And Esau took his wives, his sons, his daughters, all the persons of his house, his livestock, all his beasts, and all his *_substance_* which he had acquired in the land of Canaan, and went into the country from the face of his brother Jacob.
* `Deu 11:6` And what he did to Dathan and Abiram, the sons of Eliab, the son of Reuben, how the earth opened her mouth, and swallowed them up, along with their households, their tents, and all the *_substance_* that was in their possession, in the midst of all Israel.
* `Deu 33:11` Bless, LORD, his *_substance_*, and accept the work of his hands. Smite through the loins of those who rise against him and of those who hate him, so that they do not rise again."
* `Jsh 14:4` For the children of Joseph were two tribes, Manasseh and Ephraim; therefore, they gave no part to the Levites in the land, except cities to dwell in with their suburbs for their livestock and for their *_substance_*.
* `1Ch 27:31` And over the flocks was Jaziz the Hagerite. All these were the rulers of the *_substance_* which was king David's.
* `1Ch 28:1` And David assembled all the princes of Israel, the princes of the tribes, the captains of the companies that ministered to the king by course, the captains over the thousands, captains over the hundreds, and the stewards over all the *_substance_* and possession of the king and of his sons, with the officers, with the mighty men, and with all the valiant men at Jerusalem.
* `2Ch 21:17` And they came up into Judah, broke into it, and carried away all the *_substance_* that was found in the king's house, and also his sons and his wives, so that there was not a son left to him, except Jehoahaz the youngest of his sons.
* `2Ch 31:3` He also appointed the king's portion of his *_substance_* for the burnt-offerings, namely, for the morning and evening burnt-offerings, and the burnt-offerings for the sabbaths, for the new-moons, and for the set feasts, as it is written in the law of the LORD.
* `2Ch 32:29` Moreover, he provided for himself cities and possessions of flocks and herds in abundance, for God had given him *_substance_* in great abundance.
* `2Ch 35:7` And Josiah gave to the people lambs and kids from the flock, all for the passover-offerings, for all who were present, to the number of thirty thousand, as well as three thousand bulls. These were from the king's *_substance_*.
* `Ezr 8:21` Then I proclaimed a fast there, at the Ahava River, so that we might afflict ourselves before our God to seek from him a right way for us, for our little ones, and for all our *_substance_*.
* `Ezr 10:8` And that whoever would not come within three days, according to the counsel of the princes and the elders, all his *_substance_* should be forfeited and he himself separated from the congregation of those who had been carried away.
* `Job 1:3` His *_substance_* also was seven thousand sheep, three thousand camels, five hundred yoke of oxen, five hundred female donkeys, and a very great household. This man was the greatest of all the men of the east.
* `Job 1:10` Have you not made a hedge around him, around his house, and around all that he has on every side? You have blessed the work of his hands, and his *_substance_* has increased in the land.
* `Job 5:5` The hungry eat up his harvest and take it even out of the thorns, and the robber swallows up their *_substance_*.
* `Job 6:22` Did I say, 'Bring to me,' or, 'Give a reward for me from your *_substance_*,'
* `Job 15:29` He shall not be rich, neither shall his *_substance_* continue, neither shall he prolong its perfection upon the earth.
* `Job 20:18` That for which he labored he shall restore and shall not swallow it. According to his *_substance_* the restitution shall be, and he shall not rejoice in it.
* `Job 22:20` 'Surely our *_substance_* is not cut down, and the fire consumes their remnant.'
* `Job 30:22` You lift me up to the wind and cause me to ride upon it. You dissolve my *_substance_*.
* `Psa 17:14` From men who are your hand, O LORD, from men of the world who have their portion in this life and whose belly you fill with your hidden treasure. They are full of children and leave the rest of their *_substance_* to their babies.
* `Psa 105:21` He made him lord of his house and ruler of all his *_substance_*,
* `Psa 139:15` My *_substance_* was not hid from you when I was made in secret and skillfully formed in the lowest parts of the earth.
* `Psa 139:16` Your eyes saw my *_substance_*, being without form. And in your book they were all written, even the days that were ordained for me, when as yet there were none of them.
* `Pro 1:13` We shall find all precious *_substance_*. We shall fill our houses with plunder.
* `Pro 3:9` Honor the LORD with your *_substance_* and with the first-fruits of all your increase,
* `Pro 6:31` But if he is found, he shall restore seven-fold. He shall give all the *_substance_* of his house.
* `Pro 8:21` So that I may cause those who love me to inherit *_substance_*. And I will fill their treasures.
* `Pro 10:3` The LORD will not allow the soul of the righteous to famish, but he casts away the *_substance_* of the wicked.
* `Pro 12:27` The slothful man does not roast that which he took in hunting, but the *_substance_* of a diligent man is precious.
* `Pro 28:8` He who by usury and unjust gain increases his *_substance_*, he shall gather it for him who will pity the poor.
* `Pro 29:3` He who loves wisdom makes his father glad, but he who keeps company with harlots spends his *_substance_*.
* `Sos 8:7` Many waters cannot quench love, neither can the floods drown it. If a man would give all the *_substance_* of his house for love, it would utterly be despised.
* `Isa 6:13` And if there is a tenth left in it, it shall return and be eaten. As a terebinth and as an oak whose *_substance_* is in them when they cast their leaves, so the holy seed shall be its *_substance_*."
* `Jer 15:13` Your *_substance_* and your treasures I will give as plunder without price, and that for all your sins, even in all your borders.
* `Jer 17:3` O my mountain in the field, I will give your *_substance_* and all your treasures as plunder, and your high places for sin, throughout all your borders.
* `Hos 12:8` And Ephraim said, "Yet I have become rich. I have found *_substance_* for myself. In all my labors they shall find no iniquity in me that is sin."
* `Oba 1:13` You should not have entered into the gate of my people in the day of their calamity. Indeed, you should not have looked upon their affliction in the day of their calamity, nor have laid hands on their *_substance_* in the day of their calamity,
* `Mic 4:13` "Arise and thresh, O daughter of Zion, for I will make your horn iron and I will make your hooves brass. And you shall beat many people in pieces. And I will consecrate their gain to YAHWEH and their *_substance_* to the Lord of the whole earth."
* `Luk 15:13` And not many days after, the younger son gathered everything together, took his journey into a far country, and wasted his *_substance_* there with riotous living.
* `Heb 10:34` For you had compassion on me in my bonds and joyfully took the seizing of your goods, knowing in yourselves that you have in heaven a better and an enduring *_substance_*.
* `Heb 11:1` Now faith is the *_substance_* of things hoped for, the evidence of things not seen.

_48 verses containing SUBSTANCE_

== SUBSTANTIAL

* `Zch 11:13` And the LORD said to me, "Cast it to the potter, the *_substantial_* price at which I was prized by them." And I took the thirty pieces of silver and cast them to the potter in the house of the LORD.

_1 verse containing SUBSTANTIAL_

== SUBTLE

* `2Sa 13:3` But Amnon had a friend whose name was Jonadab, the son of Shimeah David's brother. And Jonadab was a very *_subtle_* man.
* `Pro 7:10` And behold, a woman met him with the attire of a harlot and *_subtle_* of heart.

_2 verses containing SUBTLE_

== SUBTLETY

* `Gen 27:35` And he said, "Your brother came with *_subtlety_* and has taken away your blessing."
* `2Ki 10:19` Now therefore, call to me all the prophets of Baal, all his servants, and all his priests. Let no one be lacking, for I have a great sacrifice to do to Baal. Whoever is lacking, he shall not live." But Jehu did it in *_subtlety_* to the intent that he might destroy the worshipers of Baal.
* `Pro 1:4` To give *_subtlety_* to the simple, to the young man knowledge and discretion,
* `Mth 26:4` And consulted that they might take Jesus by *_subtlety_* and kill him.
* `Act 13:10` And said, "O full of all *_subtlety_* and all mischief, you child of the devil, you enemy of all righteousness, will you not cease to pervert the right ways of the Lord?
* `2Co 11:3` But I fear, lest by any means, as the serpent beguiled Eve through his *_subtlety_*, so your minds should be corrupted from the simplicity that is in Christ.

_6 verses containing SUBTLETY_

== SUBTLY

* `1Sa 23:22` Go, I pray you, prepare further, and know and see his place where his haunt is and who has seen him there, for it is told to me that he deals very *_subtly_*.
* `Psa 105:25` He turned their heart to hate his people, to deal *_subtly_* with his servants.
* `Act 7:19` The same dealt *_subtly_* with our kindred and ill-treated our fathers, making them cast out their young children so that they would not live.

_3 verses containing SUBTLY_

== SUBURBS

* `Lev 25:34` But the field of the *_suburbs_* of their cities may not be sold, for it is their perpetual possession.
* `Num 35:2` "Command the children of Israel that they give to the Levites from the inheritance of their possession cities to dwell in. And you shall also give to the Levites *_suburbs_* for the cities around them.
* `Num 35:3` And they shall have the cities to dwell in. And their *_suburbs_* shall be for their livestock, for their goods, and for all their beasts.
* `Num 35:4` "And the *_suburbs_* of the cities which you shall give to the Levites shall reach from the wall of the city and outward one thousand cubits on all sides.
* `Num 35:5` And you shall measure from outside the city on the east side two thousand cubits, and on the south side two thousand cubits, and on the west side two thousand cubits, and on the north side two thousand cubits, and the city shall be in the midst. This shall be to them the *_suburbs_* of the cities.
* `Num 35:7` So all the cities which you shall give to the Levites shall be forty-eight cities. You shall give them with their *_suburbs_*.
* `Jsh 14:4` For the children of Joseph were two tribes, Manasseh and Ephraim; therefore, they gave no part to the Levites in the land, except cities to dwell in with their *_suburbs_* for their livestock and for their substance.
* `Jsh 21:2` And they spoke to them at Shiloh in the land of Canaan, saying, "The LORD commanded by the hand of Moses to give us cities to dwell in, with their *_suburbs_* for our livestock."
* `Jsh 21:3` And the children of Israel gave to the Levites out of their inheritance, at the commandment of the LORD, these cities and their *_suburbs_*.
* `Jsh 21:8` And the children of Israel gave by lot to the Levites these cities with their *_suburbs_*, as the LORD commanded by the hand of Moses.
* `Jsh 21:11` And they gave them the city of Arba the father of Anak (which city is Hebron) in the hill-country of Judah, with its *_suburbs_* around it.
* `Jsh 21:13` Thus they gave to the children of Aaron the priest Hebron with its *_suburbs_* to be a city of refuge for the slayer, Libnah with its *_suburbs_*,
* `Jsh 21:14` Jattir with its *_suburbs_*, Eshtemoa with its *_suburbs_*,
* `Jsh 21:15` Holon with its *_suburbs_*, Debir with its *_suburbs_*,
* `Jsh 21:16` Ain with its *_suburbs_*, Juttah with its *_suburbs_*, and Beth-shemesh with its *_suburbs_*; nine cities out of those two tribes.
* `Jsh 21:17` And out of the tribe of Benjamin, Gibeon with its *_suburbs_*, Geba with its *_suburbs_*,
* `Jsh 21:18` Anathoth with its *_suburbs_*, and Almon with its *_suburbs_*; four cities.
* `Jsh 21:19` All the cities of the children of Aaron, the priests, were thirteen cities with their *_suburbs_*.
* `Jsh 21:21` For they gave them Shechem with its *_suburbs_* in the mountains of Ephraim to be a city of refuge for the slayer, Gezer with its *_suburbs_*,
* `Jsh 21:22` Kibzaim with its *_suburbs_*, and Beth-horon with its *_suburbs_*; four cities.
* `Jsh 21:23` And out of the tribe of Dan, Eltekeh with its *_suburbs_*, Gibbethon with its *_suburbs_*,
* `Jsh 21:24` Ajalon with its *_suburbs_*, Gath-rimmon with its *_suburbs_*; four cities.
* `Jsh 21:25` And out of the half-tribe of Manasseh, Taanach with its *_suburbs_*, and Gath-rimmon with its *_suburbs_*; two cities.
* `Jsh 21:26` All the cities were ten with their *_suburbs_*, for the families of the children of Kohath who remained.
* `Jsh 21:27` And to the children of Gershon, of the families of the Levites, out of the other half-tribe of Manasseh they gave Golan in Bashan with its *_suburbs_* to be a city of refuge for the slayer, and Beesh-terah with its *_suburbs_*; two cities.
* `Jsh 21:28` And out of the tribe of Issachar, Kishon with its *_suburbs_*, Dabareh with its *_suburbs_*,
* `Jsh 21:29` Jarmuth with its *_suburbs_*, and En-gannim with its *_suburbs_*; four cities.
* `Jsh 21:30` And out of the tribe of Asher, Mishal with its *_suburbs_*, Abdon with its *_suburbs_*,
* `Jsh 21:31` Helkath with its *_suburbs_*, and Rehob with its *_suburbs_*; four cities.
* `Jsh 21:32` And out of the tribe of Naphtali, Kedesh in Galilee with its *_suburbs_* to be a city of refuge for the slayer, Hammoth-dor with its *_suburbs_*, and Kartan with its *_suburbs_*; three cities.
* `Jsh 21:33` All the cities of the Gershonites, according to their families, were thirteen cities with their *_suburbs_*.
* `Jsh 21:34` And to the families of the children of Merari, the rest of the Levites, out of the tribe of Zebulun, Jokneam with its *_suburbs_*, Kartah with its *_suburbs_*,
* `Jsh 21:35` Dimnah with its *_suburbs_*, and Nahalal with its *_suburbs_*; four cities.
* `Jsh 21:36` And out of the tribe of Reuben, Bezer with its *_suburbs_*, Jahazah with its *_suburbs_*,
* `Jsh 21:37` Kedemoth with its *_suburbs_*, and Mephaath with its *_suburbs_*; four cities.
* `Jsh 21:38` And out of the tribe of Gad, Ramoth in Gilead with its *_suburbs_* to be a city of refuge for the slayer, Mahanaim with its *_suburbs_*,
* `Jsh 21:39` Heshbon with its *_suburbs_*, and Jazer with its *_suburbs_*; four cities in all.
* `Jsh 21:41` All the cities of the Levites within the possession of the children of Israel were forty-eight cities with their *_suburbs_*.
* `Jsh 21:42` These cities were each with their *_suburbs_* around them. Thus were all these cities.
* `2Ki 23:11` And he took away the horses that the kings of Judah had given to the sun at the entrance of the house of the LORD, by the chamber of Nathan-melech the chamberlain which was in the *_suburbs_*, and burned the chariots of the sun with fire.
* `1Ch 5:16` And they dwelt in Gilead in Bashan and in its towns and in all the *_suburbs_* of Sharon, upon their borders.
* `1Ch 6:55` They gave them Hebron in the land of Judah and its *_suburbs_* around it.
* `1Ch 6:57` And to the sons of Aaron they gave the cities of Judah, namely, Hebron (the city of refuge), Libnah with its *_suburbs_*, Jattir, Eshtemoa with its *_suburbs_*,
* `1Ch 6:58` Hilen with its *_suburbs_*, Debir with its *_suburbs_*,
* `1Ch 6:59` Ashan with its *_suburbs_*, Beth-shemesh with its *_suburbs_*.
* `1Ch 6:60` And out of the tribe of Benjamin: Geba with its *_suburbs_*, Alemeth with its *_suburbs_*, and Anathoth with its *_suburbs_*. All their cities throughout their families were thirteen cities.
* `1Ch 6:64` And the children of Israel gave to the Levites these cities with their *_suburbs_*.
* `1Ch 6:67` And they gave them the cities of refuge: Shechem in the mountains of Ephraim with its *_suburbs_*, Gezer with its *_suburbs_*,
* `1Ch 6:68` Jokmeam with its *_suburbs_*, Beth-horon with its *_suburbs_*,
* `1Ch 6:69` Ajalon with its *_suburbs_*, and Gath-rimmon with its *_suburbs_*.
* `1Ch 6:70` And out of the half tribe of Manasseh: Aner with its *_suburbs_* and Bileam with its *_suburbs_* for the family of the remnant of the sons of Kohath.
* `1Ch 6:71` To the sons of Gershom were given out of the family of the half tribe of Manasseh, Golan in Bashan with its *_suburbs_* and Ashtaroth with its *_suburbs_*.
* `1Ch 6:72` And out of the tribe of Issachar: Kedesh with its *_suburbs_*, Daberath with its *_suburbs_*,
* `1Ch 6:73` Ramoth with its *_suburbs_*, and Anem with its *_suburbs_*.
* `1Ch 6:74` And out of the tribe of Asher: Mashal with its *_suburbs_*, Abdon with its *_suburbs_*,
* `1Ch 6:75` Hukok with its *_suburbs_*, and Rehob with its *_suburbs_*.
* `1Ch 6:76` And out of the tribe of Naphtali: Kedesh in Galilee with its *_suburbs_*, Hammon with its *_suburbs_*, and Kirjathaim with its *_suburbs_*.
* `1Ch 6:77` To the rest of the children of Merari were given out of the tribe of Zebulun, Rimmon with its *_suburbs_* and Tabor with its *_suburbs_*.
* `1Ch 6:78` And on the other side of the Jordan by Jericho, on the east side of the Jordan, were given them out of the tribe of Reuben, Bezer in the wilderness with its *_suburbs_*, Jahzah with its *_suburbs_*,
* `1Ch 6:79` Kedemoth with its *_suburbs_*, and Mephaath with its *_suburbs_*.
* `1Ch 6:80` And out of the tribe of Gad: Ramoth in Gilead with its *_suburbs_*, Mahanaim with its *_suburbs_*,
* `1Ch 6:81` Heshbon with its *_suburbs_*, and Jazer with its *_suburbs_*.
* `1Ch 13:2` And David said to all the congregation of Israel, "If it seems good to you, and that it is of the LORD our God, let us send abroad to our brothers everywhere who are left in all the land of Israel, and with them also to the priests and Levites who are in their cities and *_suburbs_*, so that they may assemble to us.
* `2Ch 11:14` For the Levites left their *_suburbs_* and their possession and came to Judah and Jerusalem, for Jeroboam and his sons had cast them off from executing the priest's office to the LORD.
* `2Ch 31:19` Also, for the sons of Aaron the priests who were in the fields of the *_suburbs_* of their cities, in every single city, there were men who were expressed by name to give portions to all the males among the priests and to all who were reckoned by genealogies among the Levites.
* `Ezk 27:28` The *_suburbs_* shall shake at the sound of the cry of your pilots.
* `Ezk 45:2` Of this there shall be for the sanctuary five hundred in length, with five hundred in breadth, square around, and fifty cubits around for its *_suburbs_*.
* `Ezk 48:15` "And the five thousand that is left in the breadth over against the twenty-five thousand shall be a profane place for the city, for dwelling and for *_suburbs_*, and the city shall be in the midst of it.
* `Ezk 48:17` And the *_suburbs_* of the city shall be toward the north two hundred and fifty, toward the south two hundred and fifty, toward the east two hundred and fifty, and toward the west two hundred and fifty.

_69 verses containing SUBURBS_

== SUBVERT

* `Lam 3:36` To *_subvert_* a man in his cause, the Lord does not approve.
* `Tit 1:11` Their mouths must be stopped, seeing that they *_subvert_* whole households, teaching things which they ought not for the sake of sordid gain.

_2 verses containing SUBVERT_

== SUBVERTING

* `Act 15:24` Because we have heard that some who went out from us have troubled you with words, *_subverting_* your souls, saying, 'You must be circumcised and keep the law,' to whom we gave no such commandment,
* `2Ti 2:14` Put others in remembrance of these things, charging them before the Lord that they do not contend about words to no profit, but to the *_subverting_* of the hearers.

_2 verses containing SUBVERTING_

== SUCCEED

* `Deu 12:29` "When the LORD your God cuts off the nations from before you where you go to possess them, and you *_succeed_* them and dwell in their land,
* `Deu 19:1` "When the LORD your God has cut off the nations, whose land the LORD your God gives you, and you *_succeed_* them and dwell in their cities and in their houses,
* `Deu 25:6` And it shall be, that the first-born which she bears shall *_succeed_* in the name of his brother who is dead, so that his name may not become extinct in Israel.

_3 verses containing SUCCEED_

== SUCCEEDED

* `Deu 2:12` The Horims also dwelt formerly in Seir, but the children of Esau *_succeeded_* them when they had destroyed them from before them and dwelt in their stead, as Israel did to the land of his possession, which the LORD gave to them.)
* `Deu 2:21` A people great and many and tall as the Anakims. But the LORD destroyed them before them, and they *_succeeded_* them and dwelt in their stead,
* `Deu 2:22` As he did to the children of Esau, who dwelt in Seir when he destroyed the Horims from before them. And they *_succeeded_* them and dwelt in their stead even to this day.

_3 verses containing SUCCEEDED_

== SUCCESS

* `Jsh 1:8` This book of the law shall not depart out of your mouth, but you shall meditate in it day and night so that you may observe to do according to all that is written therein. For then you shall make your way prosperous, and then you shall have good *_success_*.
* `Ecc 10:10` If the iron is blunt and he does not whet the edge, then he must use more strength. But wisdom has the advantage to give *_success_*.

_2 verses containing SUCCESS_

== SUCCESSOR

* `Act 24:27` But after two years, Porcius Festus came as *_successor_* to Felix. And Felix, willing to show the Jews a pleasure, left Paul bound.

_1 verse containing SUCCESSOR_

== SUCCOTH

* `Gen 33:17` And Jacob journeyed to *_Succoth_* and built himself a house and made booths for his livestock. Therefore, the name of the place is called *_Succoth_*.
* `Exo 12:37` And the children of Israel journeyed from Rameses to *_Succoth_*, about six hundred thousand on foot who were men, besides children.
* `Exo 13:20` And they took their journey from *_Succoth_* and encamped in Etham on the edge of the wilderness.
* `Num 33:5` And the children of Israel departed from Rameses and encamped in *_Succoth_*.
* `Num 33:6` And they departed from *_Succoth_* and encamped in Etham, which is on the edge of the wilderness.
* `Jsh 13:27` And in the valley, Beth-aram, Beth-nimrah, *_Succoth_*, and Zaphon, the rest of the kingdom of Sihon king of Heshbon, the Jordan and its border, even to the edge of the sea of Cinneroth, on the other side of the Jordan eastward.
* `Jdg 8:5` And he said to the men of *_Succoth_*, "Give, I pray you, loaves of bread to the people who follow me, for they are faint, and I am pursuing Zebah and Zalmunna, kings of Midian."
* `Jdg 8:6` And the princes of *_Succoth_* said, "Are the hands of Zebah and Zalmunna now in your hand that we should give bread to your army?"
* `Jdg 8:8` And he went up from there to Penuel and spoke to them in the same manner. And the men of Penuel answered him as the men of *_Succoth_* had answered him.
* `Jdg 8:14` And caught a young man of the men of *_Succoth_* and questioned him. And he described to him the princes of *_Succoth_* and its elders, even seventy-seven men.
* `Jdg 8:15` And he came to the men of *_Succoth_*, and said, "Behold Zebah and Zalmunna, with whom you upbraided me, saying, 'Are the hands of Zebah and Zalmunna now in your hand that we should give bread to your men who are weary?'"
* `Jdg 8:16` And he took the elders of the city, and he took thorns and briers from the wilderness, and with them he taught the men of *_Succoth_* a lesson.
* `1Ki 7:46` In the plain of the Jordan the king cast them, in the clay ground between *_Succoth_* and Zarthan.
* `2Ki 17:30` And the men of Babylon made *_Succoth_*-benoth, the men of Cuth made Nergal, the men of Hamath made Ashima,
* `2Ch 4:17` In the plain of the Jordan the king cast them, in the clay ground between *_Succoth_* and Zeredathah.
* `Psa 60:6` God has spoken in his holiness, "I will rejoice. I will divide Shechem and measure out the valley of *_Succoth_*.
* `Psa 108:7` God has spoken in his holiness: "I will rejoice. I will divide Shechem and measure out the valley of *_Succoth_*.

_17 verses containing SUCCOTH_

== SUCCOTH-BENOTH

* `2Ki 17:30` And the men of Babylon made *_Succoth-benoth_*, the men of Cuth made Nergal, the men of Hamath made Ashima,

_1 verse containing SUCCOTH-BENOTH_

== SUCH

* `Gen 27:4` And make me savory food *_such_* as I love and bring it to me so that I may eat, so that my soul may bless you before I die."
* `Gen 27:9` Go now to the flock and bring me from there two good kids of the goats, and I will make them savory food for your father *_such_* as he loves.
* `Gen 27:14` And he went and took and brought them to his mother. And his mother made savory food *_such_* as his father loved.
* `Gen 27:46` And Rebekah said to Isaac, "I am weary of my life because of the daughters of Heth. If Jacob takes a wife from the daughters of Heth, *_such_* as these, who are from the daughters of the land, what good will my life do me?"
* `Gen 30:32` I will pass through all your flock today, removing from there all the speckled and spotted sheep, all the brown ones among the sheep, and the spotted and speckled among the goats, and of *_such_* shall be my hire.
* `Gen 41:19` And behold, seven other cows came out after them, poor, very ill-favored, and lean-fleshed, *_such_* that I never saw worse in all the land of Egypt.
* `Gen 41:38` And Pharaoh said to his servants, "Can we find *_such_* a man as this is, a man in whom the Spirit of God is?"
* `Gen 44:15` And Joseph said to them, "What deed is this that you have done? Do you not know that *_such_* a man as I can certainly divine?"
* `Exo 9:18` Behold, tomorrow about this time I will cause it to rain a very grievous hail *_such_* as has not been in Egypt since its foundation even until now.
* `Exo 9:24` So there was hail, and fire mingled with the hail, very grievous, *_such_* as there had been none like it in all the land of Egypt since it became a nation.
* `Exo 10:14` And the locusts went up over all the land of Egypt and rested in all the borders of Egypt. They were very grievous. Before them there had never been [so many] locusts as this, neither after them will there be *_such_*.
* `Exo 11:6` And there shall be a great cry throughout all the land of Egypt, *_such_* as there has been none like it, nor shall be like it anymore.
* `Exo 12:36` And the LORD gave the people favor in the sight of the Egyptians so that they let them have *_such_* things as they requested. And they plundered the Egyptians.
* `Exo 34:10` And he said, "Behold, I make a covenant. Before all your people I will do wonders *_such_* as have not been done in all the earth, nor in any nation. And all the people among which you are shall see the work of the LORD, for it is an awesome thing that I will do with you.
* `Lev 10:19` And Aaron said to Moses, "Behold, this day they have offered their sin-offering and their burnt-offering before the LORD, and *_such_* things have befallen me. And if I had eaten the sin-offering today, would it have been accepted in the sight of the LORD?"
* `Lev 11:34` Of all food which may be eaten, that on which *_such_* water comes shall be unclean. And all drink that may be drank in every *_such_* vessel shall be unclean.
* `Lev 14:22` And two turtle-doves or two young pigeons, *_such_* as he is able to afford, and one shall be a sin-offering and the other a burnt-offering.
* `Lev 14:30` And he shall offer one of the turtle-doves or of the young pigeons, *_such_* as he can afford,
* `Lev 14:31` Even *_such_* as he is able to afford, one for a sin-offering and the other for a burnt-offering, with the food-offering. And the priest shall make an atonement for him who is to be cleansed before the LORD.
* `Lev 27:9` 'And if it is a beast of which men bring an offering to the LORD, all that any man gives of *_such_* to the LORD shall be holy.
* `Deu 4:32` "For ask now about the days that are past, which were before you, since the day that God created man upon the earth, and ask from one side of heaven to the other, whether *_such_* a great thing as this has ever happened, or anything like it has been heard of.
* `Deu 5:29` O that there were *_such_* a heart in them that they would fear me and keep all my commandments always so that it might be well with them and with their children forever!
* `Deu 13:11` And all Israel shall hear and fear, and they shall no longer do any *_such_* wickedness as this among you.
* `Deu 13:14` Then you shall inquire and make search and ask diligently. And behold, if it is truth and the thing certain that *_such_* abomination is wrought among you,
* `Deu 17:4` And it is told to you, and you have heard of it and inquired diligently, and behold, it is true and the thing certain, that *_such_* abomination is wrought in Israel,
* `Deu 19:20` And those who remain shall hear and fear, and shall no more from now on commit any *_such_* evil among you.
* `Deu 25:16` For all who do *_such_* things, and all who do unrighteously, are an abomination to the LORD your God.
* `Jdg 13:23` But his wife said to him, "If the LORD were pleased to kill us, he would not have received a burnt-offering and a food-offering from our hands, neither would he have shown us all these things, nor would he have told us *_such_* things as these at this time."
* `Jdg 18:23` And they cried to the children of Dan. And they turned their faces and said to Micah, "What ails you that you come with *_such_* a company?"
* `Jdg 19:24` Behold, here is my daughter, a virgin, and his concubine. I will bring them out now, and you may humble them and do with them what seems good to you, but to this man do not do *_such_* a vile thing."
* `Jdg 19:30` And it was so, that all who saw it, said, "There has been no *_such_* deed done nor seen from the day that the children of Israel came from the land of Egypt to this day. Consider it, take advice, and speak your minds."
* `Rth 4:1` Then Boaz went up to the gate and sat down there. And behold, the kinsman of whom Boaz spoke came by. And he said to him, "Ho, *_such_* a one! Turn aside and sit down here." And he turned aside and sat down.
* `1Sa 2:23` And he said to them, "Why do you do *_such_* things? For I hear of your evil dealings by all this people.
* `1Sa 4:7` And the Philistines were afraid, for they said, "God has come into the camp." And they said, "Woe to us! For there has not been *_such_* a thing before.
* `1Sa 21:2` And David said to Ahimelech the priest, "The king has commanded me a business and has said to me, 'Let no man know anything of the business about which I send you and what I have commanded you. And I have appointed my servants to *_such_* and *_such_* a place.'
* `1Sa 25:17` Now therefore, know and consider what you will do, for evil is determined against our master and against all his household. For he is *_such_* a son of Belial that a man cannot speak to him."
* `2Sa 9:8` And he bowed himself and said, "What is your servant that you should look upon *_such_* a dead dog as I am?"
* `2Sa 12:8` And I gave you your master's house and your master's wives into your bosom and gave you the house of Israel and of Judah. And if that had been too little, I would moreover have given to you *_such_* and *_such_* things.
* `2Sa 13:12` And she answered him, "No, my brother, do not force me, for no *_such_* thing ought to be done in Israel. Do not do this folly.
* `2Sa 13:18` And she had a garment of diverse colors upon her, for with *_such_* robes the king's daughters who were virgins were appareled. Then his servant brought her out and bolted the door after her.
* `2Sa 14:13` And the woman said, "Why then have you thought *_such_* a thing against the people of God? For the king speaks this thing as one who is faulty, in that the king does not bring his banished back home.
* `2Sa 17:15` Then Hushai said to Zadok and to Abiathar the priests, "In this manner Ahithophel counseled Absalom and the elders of Israel, and in *_such_* a manner I have counseled.
* `2Sa 19:36` Your servant will go a little way over the Jordan with the king. And why should the king recompense me with *_such_* a reward?
* `1Ki 10:10` And she gave the king one hundred and twenty talents of gold, a very great quantity of spices, and precious stones. Never again did there come *_such_* abundance of spices as these which the queen of Sheba gave to king Solomon.
* `1Ki 10:12` And the king made from the almug trees pillars for the house of the LORD and for the king's house and harps and psalteries for singers. There have not come *_such_* almug trees, nor have they been seen to this day.
* `2Ki 6:8` Then the king of Syria warred against Israel and took counsel with his servants, saying, "In *_such_* and *_such_* a place my camp shall be."
* `2Ki 6:9` And the man of God sent to the king of Israel, saying, "Beware that you do not pass *_such_* a place, for there the Syrians have come down."
* `2Ki 7:19` And that lord answered the man of God and said, "Now, behold, if the LORD should make windows in heaven, might *_such_* a thing be?" And he said, "Behold, you shall see it with your eyes, but shall not eat of it."
* `2Ki 19:29` 'And this shall be a sign to you: you shall eat this year *_such_* things as grow of themselves, and in the second year that which springs of the same, and in the third year sow, reap, plant vineyards, and eat their fruits.
* `2Ki 21:12` Therefore, thus says the LORD God of Israel: 'Behold, I am bringing *_such_* evil upon Jerusalem and Judah so that whoever hears of it, both his ears shall tingle.
* `2Ki 23:22` Surely there was not held *_such_* a passover from the days of the judges who judged Israel, nor in all the days of the kings of Israel, nor of the kings of Judah.
* `2Ki 25:15` And the fire-pans, the bowls, and *_such_* things as were of gold, in gold, and of silver, in silver, the captain of the guard took away.
* `1Ch 29:25` And the LORD magnified Solomon exceedingly in the sight of all Israel and bestowed upon him *_such_* royal majesty as had not been on any king before him in Israel.
* `2Ch 1:12` Wisdom and knowledge are granted to you. And I will give you riches, wealth, and honor, *_such_* as none of the kings have had who have been before you, neither shall there any after you have the like."
* `2Ch 4:6` He also made ten basins and put five on the right hand and five on the left to wash in them. *_Such_* things as they offered for the burnt-offering they washed in them. But the sea was for the priests to wash in.
* `2Ch 9:9` And she gave the king one hundred and twenty talents of gold, spices of great abundance, and precious stones. Never was there any *_such_* spice as the queen of Sheba gave to king Solomon.
* `2Ch 9:11` And the king made terraces from the algum trees for the house of the LORD and for the king's palace, and harps and psalteries for singers. And there were none *_such_* seen before in the land of Judah.
* `2Ch 35:18` And there was no passover like that kept in Israel from the days of Samuel the prophet, neither did all the kings of Israel keep *_such_* a passover as Josiah kept, with the priests, the Levites, all Judah and Israel who were present, and the inhabitants of Jerusalem.
* `Ezr 4:10` And the rest of the nations whom the great and noble Asnapper brought over and set in the cities of Samaria, and the rest who are on this side of the river, and at *_such_* a time.
* `Ezr 4:11` This is the copy of the letter that they sent to him, even to Artaxerxes the king: "Your servants the men on this side of the river, and at *_such_* a time.
* `Ezr 4:17` Then the king sent an answer to Rehum the chancellor, to Shimshai the scribe, and to the rest of their companions who dwell in Samaria, and to the rest beyond the river: "Peace, and at *_such_* a time.
* `Ezr 7:12` "Artaxerxes, king of kings, to Ezra the priest, a scribe of the law of the God of heaven: Perfect peace, and at *_such_* a time.
* `Ezr 7:27` Blessed be the LORD God of our fathers, who has put *_such_* a thing as this in the king's heart, to beautify the house of the LORD which is in Jerusalem,
* `Ezr 9:13` And after all that has come upon us for our evil deeds and for our great trespass, seeing that you, our God, have punished us less than our iniquities deserve and have given us *_such_* deliverance as this,
* `Neh 6:8` Then I sent to him, saying, "There are no *_such_* things done as you say, but you feign them out of your own heart."
* `Neh 6:11` And I said, "Should *_such_* a man as I flee? And who is there who, being as I am, would go into the temple to save his life? I will not go in."
* `Est 2:9` And the young woman pleased him and she obtained kindness from him. And he speedily gave her things for purification, with *_such_* things as belonged to her, and seven attendants who were suitable to be given to her out of the king's house. And he moved her and her attendants to the best place of the house of the women.
* `Est 4:14` For if you altogether hold your peace at this time, then enlargement and deliverance will arise to the Jews from another place, but you and your father's house will be destroyed. And who knows whether you have come to the kingdom for *_such_* a time as this?"
* `Job 12:3` But I have understanding as well as you. I am not inferior to you. Indeed, who does not know *_such_* things as these?
* `Job 14:3` And do you open your eyes upon *_such_* a one and bring me into judgment with you?
* `Job 15:13` That you turn your spirit against God and let *_such_* words go out of your mouth?
* `Job 16:2` "I have heard many *_such_* things. You are all miserable comforters.
* `Job 18:21` Surely *_such_* are the dwellings of the wicked, and this is the place of him who does not know God."
* `Job 23:14` For he performs the thing that is appointed for me. And many *_such_* things are with him.
* `Psa 50:21` These things you have done, and I kept silence. You thought that I was altogether *_such_* a one as yourself. But I will reprove you and set them in order before your eyes.
* `Psa 68:21` But God will wound the head of his enemies and the hairy scalp of *_such_* a one as goes on still in his trespasses.
* `Psa 139:6` *_Such_* knowledge is too wonderful for me. It is high. I cannot attain to it.
* `Psa 144:15` Happy are the people who are in *_such_* a case. Indeed, happy are the people whose God is the LORD.
* `Pro 6:29` *_Such_* is he who goes in to his neighbor's wife. Whoever touches her shall not be innocent.
* `Pro 30:20` *_Such_* is the way of an adulterous woman: she eats and wipes her mouth, and says, "I have done no wickedness."
* `Isa 20:6` And the inhabitant of this coastland shall say in that day, 'Behold, *_such_* is our expectation where we flee for help to be delivered from the king of Assyria. And how shall we escape?'"
* `Isa 66:8` Who has heard *_such_* a thing? Who has seen *_such_* things? Shall the earth be made to bring forth in one day? Or shall a nation be born at once? For as soon as Zion travailed, she brought forth her children.
* `Jer 2:10` For pass over to the coastlands of Chittim and see. And send to Kedar and consider diligently and see if there is *_such_* a thing.
* `Jer 5:9` Shall I not visit for these things?" says the LORD. "And shall my soul not be avenged on *_such_* a nation as this?
* `Jer 5:29` Shall I not visit for these things?' says the LORD. 'Shall my soul not be avenged on *_such_* a nation as this?'
* `Jer 9:9` Shall I not visit them for these things?" says the LORD. "Shall my soul not be avenged on *_such_* a nation as this?
* `Jer 18:13` "Therefore, thus says the LORD: 'Ask now among the heathen, "Who has heard *_such_* things?" The virgin of Israel has done a very horrible thing.
* `Jer 38:4` Therefore, the princes said to the king, "We implore you, let this man be put to death, for thus he weakens the hands of the men of war who remain in this city and the hands of all the people in speaking *_such_* words to them. For this man does not seek the welfare of this people, but the hurt."
* `Lam 5:20` Why do you forget us forever and forsake us for *_such_* a long time?
* `Ezk 16:16` And you took some of your garments, decked your high places with diverse colors, and played the harlot upon them. *_Such_* things shall not come, neither shall it be so.
* `Ezk 17:15` But he rebelled against him in sending his ambassadors into Egypt so that they might give him horses and many people. Shall he prosper? Shall he escape who does *_such_* things? Or shall he break the covenant and be delivered?
* `Ezk 18:14` "Now behold, if he begets a son, who sees all his father's sins which he has done, and considers, and does not do *_such_* things,
* `Dan 2:10` The Chaldeans answered before the king, and said, "There is not a man upon the earth who can disclose the king's matter, for there is no king, lord, nor ruler who has asked *_such_* things of any magician, astrologer, or Chaldean.
* `Dan 10:15` And when he had spoken *_such_* words to me, I set my face toward the ground and I became mute.
* `Dan 12:1` "And at that time Michael shall stand up, the great prince who stands for the children of your people. And there shall be a time of trouble, *_such_* as never was since there was a nation even to that same time. And at that time your people shall be delivered, everyone who is found written in the book.
* `Mth 8:10` When Jesus heard it, he marveled, and said to those who followed, "Truly I say to you, I have not found *_such_* great faith as this, not even in Israel.
* `Mth 9:8` But when the multitude saw it, they marveled and glorified God, who had given *_such_* power to men.
* `Mth 13:54` And when he had come into his own country, he taught them in their synagogue in *_such_* a way that they were astonished and said, "From where does this man get this wisdom and these mighty works?
* `Mth 18:5` And whoever receives one *_such_* little child in my name, receives me.
* `Mth 19:14` But Jesus said, "Allow little children, and do not forbid them to come to me, for of *_such_* is the kingdom of heaven."
* `Mth 24:21` For then shall be great tribulation, *_such_* as has not been since the beginning of the world to this time, nor will there ever be.
* `Mth 24:24` For false Christs and false prophets will arise and will show great signs and wonders in *_such_* a way that, if it were possible, they would deceive the very elect.
* `Mth 24:44` Therefore, you also be ready. For the Son of man comes in *_such_* an hour as you do not think.
* `Mth 26:18` And he said, "Go into the city to *_such_* a man, and say to him, 'The Master says, "My time is at hand. I will keep the passover at your house with my disciples."'"
* `Mrk 4:33` And with many *_such_* parables he spoke the word to them, as they were able to hear it.
* `Mrk 6:2` And when the sabbath had come, he began to teach in the synagogue. And many who heard him were astonished, saying, "From where did this man get these things? And what wisdom is this which is given to him that even *_such_* mighty works are wrought by his hands?
* `Mrk 7:8` For laying aside the commandment of God, you hold the tradition of men, *_such_* as the washing of pots and cups. And you do many other similar things."
* `Mrk 9:37` "Whoever receives one of *_such_* children in my name receives me, and whoever receives me does not receive me, but him who sent me."
* `Mrk 10:14` But when Jesus saw it, he was much displeased and said to them, "Allow the little children to come to me and do not forbid them, for of *_such_* is the kingdom of God.
* `Mrk 13:7` And when you hear of wars and rumors of wars, do not be troubled, for *_such_* things must come. But the end is not yet.
* `Mrk 13:19` For in those days there shall be affliction *_such_* as has not been from the beginning of the creation which God created to this time, neither shall there be.
* `Luk 7:9` When Jesus heard these things, he marveled at him and turned himself around and said to the people who followed him, "I say to you, I have not found *_such_* great faith, not even in Israel."
* `Luk 9:9` And Herod said, "I have beheaded John, but who is this of whom I hear *_such_* things?" And he desired to see him.
* `Luk 10:7` And in the same house remain, eating and drinking *_such_* things as they give, for the laborer is worthy of his hire. Do not go from house to house.
* `Luk 10:8` And into whatever city you enter and they receive you, eat *_such_* things as are set before you.
* `Luk 13:2` And Jesus, answering, said to them, "Do you suppose that these Galileans were sinners above all the Galileans because they suffered *_such_* things?
* `Luk 18:16` But Jesus called them to him, and said, "Allow little children to come to me and do not forbid them, for of *_such_* is the kingdom of God.
* `Jhn 4:23` But the hour comes, and is now, when the true worshipers shall worship the Father in spirit and in truth, for the Father seeks *_such_* to worship him.
* `Jhn 7:32` The Pharisees heard that the people murmured *_such_* things concerning him. And the Pharisees and the chief priests sent officers to take him.
* `Jhn 8:5` Now in the law, Moses commanded us that *_such_* should be stoned, but what do you say?"
* `Jhn 9:16` Therefore, some of the Pharisees said, "This man is not from God because he does not keep the sabbath." Others said, "How can a man who is a sinner do *_such_* miracles?" And there was a division among them.
* `Jhn 14:9` Jesus says to him, "Have I been with you *_such_* a long time and yet you have not known me, Philip? He who has seen me has seen the Father. How then do you say, 'Show us the Father'?
* `Act 14:1` And it came to pass in Iconium, that they went both together into the synagogue of the Jews and spoke in *_such_* a way that a great multitude both of the Jews and also of the Greeks believed.
* `Act 15:24` Because we have heard that some who went out from us have troubled you with words, subverting your souls, saying, 'You must be circumcised and keep the law,' to whom we gave no *_such_* commandment,
* `Act 16:24` Who, having received *_such_* a charge, thrust them into the inner prison and secured their feet in the stocks.
* `Act 18:15` But if it is a question of words and names and of your law, you look to it, for I will be no judge of *_such_* matters."
* `Act 21:25` As concerning the Gentiles who believe, we have written and concluded that they observe no *_such_* thing, except only that they keep themselves from things offered to idols, from blood, from things strangled, and from lewdness."
* `Act 22:22` And they gave him audience to this word and then lifted up their voices, and said, "Away with *_such_* a man from the earth, for it is not fit that he should live."
* `Act 25:18` Against whom, when the accusers stood up, they brought no accusation of *_such_* things as I supposed,
* `Act 25:20` And because I doubted of *_such_* manner of questions, I asked him whether he would go to Jerusalem and there be judged concerning these matters.
* `Act 26:29` And Paul said, "I wish to God that not only you, but also all who hear me this day, were both almost and altogether *_such_* as I am, except these bonds."
* `Act 28:10` They also honored us with many honors, and when we departed, they laded us with *_such_* things as were necessary.
* `Rom 1:32` Who, knowing the judgment of God, that those who commit *_such_* things are worthy of death, not only do the same, but have pleasure in those who do them.
* `Rom 2:2` But we are sure that the judgment of God is according to truth against those who commit *_such_* things.
* `Rom 2:3` And do you think this, O man, who judges those who do *_such_* things and does the same, that you shall escape the judgment of God?
* `Rom 16:18` For those who are *_such_* do not serve our Lord Jesus Christ, but their own belly, and by good words and fair speeches deceive the hearts of the simple.
* `1Co 5:1` It is reported commonly that there is lewdness among you, and *_such_* lewdness as is not so much as named among the Gentiles, that one should have his father's wife.
* `1Co 5:5` Deliver *_such_* a one to Satan for the destruction of the flesh so that the spirit may be saved in the day of the Lord Jesus.
* `1Co 5:11` But now I have written to you not to keep company with any man who is called a brother if he is a lewd person, covetous, an idolater, a railer, a drunkard, or an extortioner. Do not even eat with *_such_* a person.
* `1Co 6:11` And *_such_* were some of you. But you are washed, you are sanctified, you are justified in the name of the Lord Jesus and by the Spirit of our God.
* `1Co 7:15` But if the unbelieving departs, let him depart. A brother or a sister is not under bondage in *_such_* cases, but God has called us to peace.
* `1Co 7:28` But if you marry, you have not sinned, and if a virgin marries, she has not sinned. Nevertheless, *_such_* will have trouble in the flesh, but I spare you.
* `1Co 10:13` There has no temptation taken you but *_such_* as is common to man. But God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make a way to escape so that you may be able to bear it.
* `1Co 11:16` But if any man seems to be contentious, we have no *_such_* custom, neither do the churches of God.
* `1Co 15:48` As is the earthy, *_such_* are those also who are earthy, and as is the heavenly, *_such_* are those also who are heavenly.
* `1Co 16:16` That you submit yourselves to *_such_* as these and to everyone who helps with us and labors.
* `1Co 16:18` For they have refreshed my spirit and yours. Therefore, acknowledge those who are *_such_*.
* `2Co 2:6` Sufficient to *_such_* a man is this punishment which was inflicted by many,
* `2Co 2:7` So that on the other hand you ought rather to forgive him and comfort him, lest perhaps *_such_* a one should be swallowed up with excessive sorrow.
* `2Co 3:4` And *_such_* trust we have through Christ toward God,
* `2Co 3:12` Seeing then that we have *_such_* hope, we use great plainness of speech,
* `2Co 10:11` Let *_such_* a one think this: that what we are in word by letters when we are absent, *_such_* we will also be in deed when we are present.
* `2Co 11:13` For *_such_* are false apostles, deceitful workers, transforming themselves into the apostles of Christ.
* `2Co 12:2` I knew a man in Christ fourteen years ago (whether in the body I cannot tell, or whether out of the body I cannot tell—God knows), *_such_* a one was caught up to the third heaven.
* `2Co 12:3` And I knew *_such_* a man (whether in the body, or out of the body, I cannot tell—God knows),
* `2Co 12:5` About *_such_* a one I will glory, yet about myself I will not glory, except in my infirmities.
* `2Co 12:20` For I fear, lest, when I come, I shall not find you *_such_* as I wish, and that I shall be found by you *_such_* as you do not wish, lest there be debates, envyings, wraths, strifes, backbitings, whisperings, conceits, tumults,
* `Gal 5:21` Envyings, murders, drunkenness, revelings, and *_such_* like these, of which I tell you before, as I have also told you in time past, that those who do *_such_* things shall not inherit the kingdom of God.
* `Gal 5:23` Meekness, and temperance. Against *_such_* there is no law.
* `Gal 6:1` Brothers, if a man is overtaken in a fault, you who are spiritual, restore *_such_* a one in the spirit of meekness, considering yourself, lest you also be tempted.
* `Eph 5:27` And that he might present it to himself a glorious church, not having spot or wrinkle, or any *_such_* thing, but that it should be holy and without blemish.
* `Phl 2:29` Receive him therefore in the Lord with all gladness, and hold *_such_* in reputation,
* `1Th 4:6` And that no man go beyond and defraud his brother in any matter, because the Lord is the avenger of all *_such_*, as we also have forewarned you and testified.
* `2Th 3:12` Now those who are *_such_* we command and exhort by our Lord Jesus Christ that they work with quietness and eat their own bread.
* `1Ti 6:5` Perverse disputings of men of corrupt minds and destitute of the truth, supposing gain to be godliness. Withdraw yourself from *_such_*.
* `2Ti 3:5` Having a form of godliness, but denying its power. Turn away from *_such_*.
* `2Ti 3:11` Persecutions, and afflictions which came to me at Antioch, at Iconium, and at Lystra. I endured *_such_* persecutions, and out of them all the Lord delivered me.
* `Tit 3:11` Knowing that he who is *_such_* is perverted and sins, being self-condemned.
* `Phm 1:9` Yet for love's sake I rather implore you, being *_such_* a one as Paul the aged and now also a prisoner of Jesus Christ.
* `Heb 7:26` For *_such_* a high priest was fitting for us, who is holy, harmless, undefiled, separate from sinners, and made higher than the heavens,
* `Heb 8:1` Now of the things which we have spoken, this is the sum: we have *_such_* a high priest who is set on the right hand of the throne of the Majesty in the heavens,
* `Heb 11:14` For those who say *_such_* things declare plainly that they seek a country.
* `Heb 12:3` Consider him who endured *_such_* contradiction of sinners against himself, lest you be wearied and faint in your minds.
* `Heb 13:5` Let your manner of life be without covetousness, and be content with *_such_* things as you have, for he has said, "I will never leave you, nor forsake you,"
* `Heb 13:16` But do not forget to do good and to share, for with *_such_* sacrifices God is well pleased.
* `Jms 2:12` Speak in *_such_* a manner and do in *_such_* a manner as those who are judged by the law of liberty.
* `Jms 4:16` But now you rejoice in your boastings. All *_such_* rejoicing is evil.
* `2Pe 3:14` Therefore, beloved, seeing that you look for *_such_* things, be diligent that you may be found by him in peace, without spot, and blameless.
* `3Jn 1:8` We therefore ought to receive *_such_* so that we may be fellow-helpers for the truth.
* `Rev 16:18` And there were voices, thunders, and lightnings, and there was a great earthquake *_such_* as has not been since men were upon the earth—so mighty an earthquake, and so great.
* `Rev 18:7` However much she has glorified herself and lived deliciously, in *_such_* amount give her torment and sorrow, for she says in her heart, '"I sit as a queen," "I am not a widow, and never shall I see sorrow."'
* `Rev 18:17` For in one hour *_such_* great wealth has come to nothing.' And every ship-master and all the company in ships, along with sailors and as many as trade by sea, stood afar off,
* `Rev 20:6` Blessed and holy is he who has part in the first resurrection. On *_such_* the second death has no power, but they shall be priests of God and of Christ and shall reign with him a thousand years.

_183 verses containing SUCH_

== SUCHATHITES

* `1Ch 2:55` And the families of the scribes who dwelt at Jabez: the Tirathites, the Shimeathites, and *_Suchathites_*. These are the Kenites who came from Hemath, the father of the house of Rechab.

_1 verse containing SUCHATHITES_

== SUCK

* `Job 20:16` He shall *_suck_* the poison of asps. The viper's tongue shall slay him.

_1 verse containing SUCK_

== SUDDEN

* `Job 22:10` Therefore, snares are around you, and *_sudden_* fear troubles you,
* `Pro 3:25` Do not be afraid of *_sudden_* fear or of the desolation of the wicked when it comes,
* `Zph 1:18` Neither their silver nor their gold shall be able to deliver them in the day of the LORD'S wrath. But the whole land shall be devoured by the fire of his jealousy, for he will make even a *_sudden_* end of all those who dwell in the land.
* `1Th 5:3` For when they say, "Peace and safety," then *_sudden_* destruction comes upon them, as travail upon a woman with child, and they shall not escape.
* `1Pe 3:6` Even as Sarah obeyed Abraham, calling him lord. You are her daughters as long as you do well and are "not afraid of *_sudden_* fear."

_5 verses containing SUDDEN_

== SUDDENLY

* `Num 6:9` 'And if any man dies very *_suddenly_* by him and he has defiled the head of his consecration, then he shall shave his head on the day of his cleansing. On the seventh day he shall shave it.
* `Num 12:4` And the LORD spoke *_suddenly_* to Moses, to Aaron, and to Miriam, "Come out, you three, to the Tabernacle of the Congregation." And the three of them came out.
* `Num 35:22` 'But if anyone pushes another *_suddenly_* without enmity, or casts upon him anything without lying in wait,
* `Deu 7:4` For they will turn away your son from following me so that they may serve other gods. Thus the anger of the LORD will be kindled against you and destroy you *_suddenly_*.
* `Jsh 10:9` Joshua therefore came to them *_suddenly_*, and went up from Gilgal all night.
* `Jsh 11:7` So Joshua and all the people of war with him came *_suddenly_* against them by the waters of Merom, and they fell upon them.
* `2Sa 15:14` And David said to all his servants who were with him at Jerusalem, "Arise and let us flee, or else we shall not escape from Absalom. Make speed to depart, lest he should overtake us *_suddenly_* and bring evil upon us and smite the city with the edge of the sword."
* `2Ch 29:36` And Hezekiah and all the people rejoiced that God had prepared the people, for the thing was done *_suddenly_*.
* `Job 5:3` I have seen the foolish taking root, but *_suddenly_* I cursed his habitation.
* `Job 9:23` If the scourge slays *_suddenly_*, he will laugh at the trial of the innocent.
* `Psa 6:10` Let all my enemies be ashamed and greatly disquieted. Let them return and be *_suddenly_* ashamed.
* `Psa 64:4` So that they may shoot in secret at the perfect. *_Suddenly_* they shoot at him and do not fear.
* `Psa 64:7` But God shall shoot at them with an arrow. *_Suddenly_* they shall be wounded.
* `Pro 6:15` Therefore, his calamity shall come *_suddenly_*. He shall be *_suddenly_* broken without remedy.
* `Pro 24:22` For their calamity shall rise *_suddenly_*. And who knows the ruin of the both of them?
* `Pro 29:1` He who is often reproved and hardens his neck shall *_suddenly_* be destroyed, and that without remedy.
* `Ecc 9:12` For man also does not know his time. As the fish that are taken in an evil net, and as the birds that are caught in the snare, so are the sons of men snared in an evil time when it falls *_suddenly_* upon them.
* `Isa 29:5` Moreover, the multitude of your strangers shall be like small dust and the multitude of the terrible ones shall be like chaff that passes away. It shall even be at an instant, *_suddenly_*.
* `Isa 30:13` Therefore this iniquity shall be to you as a breach ready to fall, swelling out in a high wall, whose breaking comes *_suddenly_* at an instant.
* `Isa 47:11` Therefore, evil shall come upon you. You shall not know from where it rises. And mischief shall fall upon you. You shall not be able to put it off. And desolation shall come upon you *_suddenly_*, which you shall not know.
* `Isa 48:3` I have declared the former things from the beginning, and they went forth from my mouth and I proclaimed them. I did them *_suddenly_* and they came to pass.
* `Jer 4:20` Destruction upon destruction is cried, for the whole land is laid waste. *_Suddenly_* my tents are ruined, and my curtains in a moment.
* `Jer 6:26` O daughter of my people, gird yourself with sackcloth and wallow yourself in ashes. Make for yourself a mourning, as for an only son, a most bitter lamentation, for the destroyer shall *_suddenly_* come upon us.
* `Jer 15:8` Their widows are multiplied to me above the sand of the seas. I have brought upon them against the mother of the young men a destroyer at noon-day. I will *_suddenly_* cause to fall upon her terrors and anguish.
* `Jer 18:22` Let a cry be heard from their houses when you bring a troop *_suddenly_* upon them, for they have dug a pit to take me and hid snares for my feet.
* `Jer 49:19` Behold, he shall come up like a lion from the swelling of the Jordan against the habitation of the strong, but I will *_suddenly_* make him run away from her. And who is a chosen man that I may appoint over her? For who is like me? And who will appoint me the time? And who is that shepherd who will stand before me?"
* `Jer 50:44` "Behold, he shall come up like a lion from the swelling of the Jordan to the habitation of the strong, but I will make them *_suddenly_* run away from her. And who is a chosen man whom I may appoint over her? For who is like me? And who will appoint me the time? And who is that shepherd who will stand before me?"
* `Jer 51:8` Babylon is *_suddenly_* fallen and destroyed. Howl for her. Take balm for her pain. It may be that she may be healed.
* `Hab 2:7` Shall they not rise *_suddenly_* who bite you, and awake who disturb you, and you shall be plunder for them?
* `Mal 3:1` "Behold, I will send my messenger, and he shall prepare the way before me. And the Lord, whom you seek, will *_suddenly_* come to his temple, even the messenger of the covenant, whom you delight in. Behold, he will come," says the LORD of hosts.
* `Mrk 9:8` And *_suddenly_*, when they had looked around, they saw no one with them anymore, except Jesus only.
* `Mrk 13:36` Lest coming *_suddenly_*, he should find you sleeping.
* `Luk 2:13` And *_suddenly_* there was with the angel a multitude of the heavenly host praising God, and saying,
* `Luk 9:39` And behold, a spirit takes him and he *_suddenly_* cries out, and it convulses him so that he foams, and bruising him, it hardly departs from him.
* `Act 2:2` And *_suddenly_* there came a sound from heaven, as of a rushing mighty wind, and it filled all the house where they were sitting.
* `Act 9:3` And as he journeyed, he came near Damascus, and *_suddenly_* there shined around him a light from heaven,
* `Act 16:26` And *_suddenly_* there was a great earthquake so that the foundations of the prison were shaken, and immediately all the doors were opened and everyone's bonds were loosened.
* `Act 22:6` "And it came to pass, that as I was passing on my journey and had come near to Damascus about noon, *_suddenly_* there shone from heaven a great light around me.
* `Act 28:6` But they expected that he would have swollen or *_suddenly_* fallen down dead. But after they had waited a long time and saw nothing amiss happen to him, they changed their minds and said that he was a god.

_39 verses containing SUDDENLY_

== SUE

* `Mth 5:40` And if any man wants to *_sue_* you and take away your coat, let him have your cloak also.

_1 verse containing SUE_

== SUF

* `Deu 1:1` These are the words which Moses spoke to all Israel on the east side of the Jordan in the wilderness, in the plain over against *_Suf_*, between Paran, Tophel, Laban, Hazeroth, and Dizahab.

_1 verse containing SUF_

== SUFFER

* `Job 24:11` Who make oil within their walls, tread their wine-presses, and *_suffer_* thirst.
* `Psa 9:13` Have mercy upon me, O LORD. Consider my trouble which I *_suffer_* from those who hate me, and lift me up from the gates of death
* `Psa 34:10` The young lions lack and *_suffer_* hunger, but those who seek the LORD shall not lack any good thing.
* `Psa 88:15` I am afflicted and ready to die from my youth. While I *_suffer_* your terrors I am distracted.
* `Pro 11:15` He who is surety for a stranger shall *_suffer_* for it, and he who hates suretyship is secure.
* `Pro 19:15` Slothfulness casts into a deep sleep, and an idle soul shall *_suffer_* hunger.
* `Pro 19:19` A man of great wrath shall *_suffer_* punishment, for if you deliver him, yet you must do it again.
* `Mth 16:21` From that time forth Jesus began to tell his disciples that he must go to Jerusalem and *_suffer_* many things from the elders, chief priests, and scribes, and be killed, and be raised again the third day.
* `Mth 17:12` But I say to you, that Elijah has come already, and they did not know him, but have done to him whatever they pleased. Likewise, the Son of man will also *_suffer_* by them."
* `Mrk 8:31` And he began to teach them that the Son of man must *_suffer_* many things and be rejected by the elders, the chief priests, and scribes, and be killed, and after three days rise again.
* `Mrk 9:12` And he answered and told them, "Elijah truly comes first and restores all things. How is it written concerning the Son of man that he must *_suffer_* many things and be set at nothing?
* `Luk 9:22` Saying, "The Son of man must *_suffer_* many things, be rejected by the elders, chief priests, and scribes, be put to death, and be raised on the third day."
* `Luk 17:25` But first, he must *_suffer_* many things and be rejected by this generation.
* `Luk 22:15` And he said to them, "I have earnestly desired to eat this passover with you before I *_suffer_*.
* `Luk 24:26` Did Christ not have to *_suffer_* these things and to enter into his glory?"
* `Luk 24:46` And said to them, "Thus it is written, and thus it behooved Christ to *_suffer_* and to rise from the dead on the third day,
* `Act 3:18` But those things which God before had shown by the mouth of all his prophets, that Christ should *_suffer_*, he has thus fulfilled.
* `Act 5:41` And they departed from the presence of the council, rejoicing that they were counted worthy to *_suffer_* shame for his name.
* `Act 7:24` And seeing one of them *_suffer_* wrong, he defended him and avenged him who was oppressed and smote the Egyptian.
* `Act 9:16` For I will show him what great things he must *_suffer_* for my name's sake."
* `Act 17:3` Opening and alleging that it was needful that Christ should *_suffer_* and rise again from the dead, and saying, "This Jesus, whom I preach to you, is Christ."
* `Act 26:23` That Christ should *_suffer_*, and that he first by the resurrection of the dead should proclaim light to the people and to the Gentiles."
* `Rom 8:17` And if children, then heirs—heirs of God and joint-heirs with Christ—if we *_suffer_* with him, so that we may be glorified together.
* `1Co 3:15` If any man's work is burned, he will *_suffer_* loss, but he himself shall be saved, but in the manner as by fire.
* `1Co 4:12` And we labor, working with our own hands. Being reviled, we bless. Being persecuted, we *_suffer_* it.
* `1Co 12:26` And thus if one member suffers, all the members *_suffer_* with it, or, if one member is honored, all the members rejoice with it.
* `2Co 1:6` And whether we are afflicted, it is for your consolation and salvation, which is effectual in the enduring of the same sufferings which we also *_suffer_*, or whether we are comforted, it is for your consolation and salvation.
* `2Co 7:9` Now I rejoice, not that you were made sorry, but that you sorrowed to repentance. For you were made sorry after a godly manner so that you might *_suffer_* loss in nothing by us.
* `Gal 5:11` And I, brothers, if I still preach circumcision, why do I still *_suffer_* persecution? Then the offense of the cross has ceased.
* `Gal 6:12` As many as desire to make a fair show in the flesh, they constrain you to be circumcised—only lest they should *_suffer_* persecution for the cross of Christ.
* `Phl 1:29` For to you it is given on behalf of Christ, not only to believe in him, but also to *_suffer_* for his sake,
* `Phl 4:12` I know both how to be abased and I know how to abound. Everywhere and in all things I am instructed both to be full and to be hungry, both to abound and to *_suffer_* need.
* `1Th 3:4` For truly, when we were with you, we told you before that we should *_suffer_* tribulation, even as it came to pass, and you know.
* `2Th 1:5` This is a manifest token of the righteous judgment of God, that you may be counted worthy of the kingdom of God, for which you also *_suffer_*,
* `1Ti 4:10` For therefore we both labor and *_suffer_* reproach, because we trust in the living God who is the Savior of all men, especially of those who believe.
* `2Ti 1:12` For this cause, I also *_suffer_* these things. Nevertheless, I am not ashamed, for I know whom I have believed and am persuaded that he is able to keep that which I have committed to him for that day.
* `2Ti 2:9` For this I *_suffer_* trouble as an evil-doer, even to bonds, but the word of God is not bound.
* `2Ti 2:12` If we *_suffer_*, we shall also reign with him. If we deny him, he will also deny us.
* `2Ti 3:12` And indeed all who desire to live godly in Christ Jesus will *_suffer_* persecution.
* `Heb 9:26` For then he would have had to *_suffer_* often since the foundation of the world. But now once in the end of the age he has appeared to put away sin by the sacrifice of himself.
* `Heb 11:25` Choosing rather to *_suffer_* affliction with the people of God than to enjoy the pleasures of sin for a season,
* `Heb 13:3` Remember those who are in bonds, as bound with them, and those who *_suffer_* adversity, as being yourselves also in the body.
* `1Pe 2:20` For what glory is it if, when you are buffeted for your sins, you bear it patiently? But if you do good and *_suffer_* for it and you bear it patiently, this is acceptable with God.
* `1Pe 3:14` But if you *_suffer_* for righteousness' sake, happy are you. "And do not be afraid of their terror, neither be troubled,"
* `1Pe 3:17` For it is better, if it is the will of God, that you *_suffer_* for well-doing than for evil-doing.
* `1Pe 4:15` But let none of you *_suffer_* as a murderer, as a thief, as an evildoer, or as a busy-body in other men's matters.
* `1Pe 4:19` Therefore, let those who *_suffer_* according to the will of God commit their souls in well-doing to a faithful Creator.
* `Rev 2:10` Fear none of those things which you shall *_suffer_*. Behold, the devil will cast some of you into prison so that you may be tried. And you shall have tribulation ten days. Be faithful until death, and I will give you a crown of life.

_48 verses containing SUFFER_

== SUFFERED

* `Jer 15:15` O LORD, you know. Remember me, visit me, and avenge me of my persecutors. Do not take me away in your patience. Know that for your sake I have *_suffered_* rebuke.
* `Mth 27:19` When he was sitting on the judgment-seat, his wife sent to him, saying, "Have nothing to do with that just man, for I have *_suffered_* many things this day in a dream because of him."
* `Mrk 5:26` Had *_suffered_* many things from many physicians, and had spent all that she had and was not relieved, but rather grew worse,
* `Luk 13:2` And Jesus, answering, said to them, "Do you suppose that these Galileans were sinners above all the Galileans because they *_suffered_* such things?
* `2Co 7:12` Therefore, though I wrote to you, I did not do it for his cause who had done the wrong, nor for his cause who *_suffered_* wrong, but that our care for you in the sight of God might appear to you.
* `2Co 11:25` Three times I was beaten with rods, once I was stoned, three times I *_suffered_* shipwreck, a night and a day I have been in the deep;
* `Gal 3:4` Have you *_suffered_* so many things in vain—if it is indeed in vain?
* `Phl 3:8` Indeed, I even count all things to be loss for the excellence of the knowledge of Christ Jesus my Lord. For him I have *_suffered_* the loss of all things and count them to be dung so that I may win Christ,
* `1Th 2:2` But even after we had *_suffered_* before and were shamefully treated at Phillippi, as you know, we were bold in our God to speak to you the gospel of God with much contention.
* `1Th 2:14` For you, brothers, became followers of the churches of God which in Judea are in Christ Jesus. For you also have *_suffered_* similar things from your own countrymen, even as they have from the Jews,
* `Heb 2:18` For in that he himself has *_suffered_*, being tempted, he is able to help those who are tempted.
* `Heb 5:8` Though he was a Son, yet he learned obedience by the things which he *_suffered_*.
* `Heb 13:12` Therefore, Jesus also, so that he might sanctify the people with his own blood, *_suffered_* outside the gate.
* `1Pe 2:21` For even to this you were called, because Christ also *_suffered_* for us, leaving us an example so that you should follow his steps.
* `1Pe 2:23` He, when he was reviled, did not revile in return. When he *_suffered_*, he did not threaten, but committed himself to him who judges righteously.
* `1Pe 3:18` For Christ also has once *_suffered_* for sins, the just for the unjust, so that he might bring us to God, being put to death in the flesh, but made alive by the Spirit,
* `1Pe 4:1` Therefore, since Christ has *_suffered_* for us in the flesh, arm yourselves likewise with the same mind. For he who has *_suffered_* in the flesh has ceased from sin,
* `1Pe 5:10` But the God of all grace who has called us to his eternal glory by Christ Jesus, after you have *_suffered_* a while, shall himself perfect, establish, strengthen, and settle you.

_18 verses containing SUFFERED_

== SUFFERING

* `Heb 2:9` But we see Jesus, who was made a little lower than the angels for the *_suffering_* of death, crowned with glory and honor, so that he, by the grace of God, should taste death for every man.
* `Jms 5:10` My brothers, take the prophets who have spoken in the name of the Lord for an example of *_suffering_* affliction and of patience.
* `1Pe 2:19` For this is thank-worthy, if a man for conscience toward God endures grief, *_suffering_* wrongfully.
* `Jde 1:7` Even as Sodom and Gomorrah, and the cities around them in like manner, giving themselves over to impurity and going after strange flesh, are set forth for an example, *_suffering_* the vengeance of eternal fire.

_4 verses containing SUFFERING_

== SUFFERINGS

* `Rom 8:18` For I reckon, that the *_sufferings_* of this present time are not worthy to be compared with the glory which shall be revealed in us.
* `2Co 1:5` For as the *_sufferings_* of Christ abound in us, so our consolation also abounds by Christ.
* `2Co 1:6` And whether we are afflicted, it is for your consolation and salvation, which is effectual in the enduring of the same *_sufferings_* which we also suffer, or whether we are comforted, it is for your consolation and salvation.
* `2Co 1:7` And our hope for you is steadfast, knowing, that as you are partakers of the *_sufferings_*, so you shall also be of the consolation.
* `Phl 3:10` So that I may know him and the power of his resurrection and the fellowship of his *_sufferings_*, being made conformable to his death,
* `Col 1:24` I now rejoice in my *_sufferings_* for you and fill up that which is lacking of the afflictions of Christ in my flesh for his body's sake, which is the church,
* `Heb 2:10` For it was fitting for him, for whom are all things and by whom are all things, in bringing many sons to glory, to make the Captain of their salvation perfect through *_sufferings_*.
* `1Pe 1:11` Searching for what or what manner of time the Spirit of Christ which was in them signified when it testified beforehand the *_sufferings_* of Christ and the glory that should follow.
* `1Pe 4:13` But rejoice, seeing you are partakers of Christ's *_sufferings_*, so that when his glory is revealed you may also be glad with exceeding joy.
* `1Pe 5:1` I exhort the elders who are among you as a fellow elder and a witness of the *_sufferings_* of Christ and also a partaker of the glory that shall be revealed:

_10 verses containing SUFFERINGS_

== SUFFERS

* `Mth 11:12` And from the days of John the Baptist until now, the kingdom of heaven *_suffers_* violence, and the violent take it by force.
* `1Co 12:26` And thus if one member *_suffers_*, all the members suffer with it, or, if one member is honored, all the members rejoice with it.
* `1Pe 4:16` Yet if any man *_suffers_* as a Christian, let him not be ashamed, but let him glorify God in this matter.

_3 verses containing SUFFERS_

== SUFFICE

* `Num 11:22` Shall the flocks and the herds be slain for them to *_suffice_* for them? Or shall all the fish of the sea be gathered for them to *_suffice_* for them?"
* `Deu 3:26` But the LORD was angry with me for your sakes and would not hear me. And the LORD said to me, 'Let it *_suffice_* you. Speak no more to me of this matter.
* `Jdg 21:14` And Benjamin came back at that time. And they gave them the women which they had saved alive from the women of Jabesh-gilead, yet they did not *_suffice_* them.
* `1Ki 20:10` And Ben-hadad sent to him and said, "May the gods do so to me and more also, if the dust of Samaria shall *_suffice_* for handfuls for all the people who follow me."
* `Ezk 44:6` And you shall say to the rebellious, even to the house of Israel, 'Thus says the Lord GOD: "O house of Israel, let it *_suffice_* you of all your abominations,
* `Ezk 45:9` 'Thus says the Lord GOD: "Let it *_suffice_* you, O princes of Israel. Remove violence and plunder, and execute judgment and justice. Take away your exactions from my people," says the Lord GOD.

_6 verses containing SUFFICE_

== SUFFICIENCY

* `Job 20:22` In the fullness of his *_sufficiency_* he shall be in distress. Every hand of the wicked shall come upon him.
* `2Co 3:5` Not that we are sufficient by ourselves to think anything as from ourselves, but our *_sufficiency_* is from God,
* `2Co 9:8` And God is able to make all grace abound toward you so that you, always having all *_sufficiency_* in all things, may abound to every good work,

_3 verses containing SUFFICIENCY_

== SUFFICIENT

* `Exo 36:7` For the stuff they had was *_sufficient_* for all the work to be done, with some left over.
* `Deu 15:8` But you shall open your hand wide to him and shall surely lend him *_sufficient_* for his need in that which he lacks.
* `Deu 33:7` And this is the blessing of Judah: "Hear, LORD, the voice of Judah, and bring him to his people. Let his hands be *_sufficient_* for him. May you be a help to him from his enemies."
* `Pro 25:16` Have you found honey? Eat so much as is *_sufficient_* for you, lest you be filled with it and vomit it.
* `Isa 23:18` And her merchandise and her wages shall be holiness to the LORD. It shall not be treasured nor laid up, for her merchandise shall be for those who dwell before the LORD, for *_sufficient_* food and for durable clothing.
* `Isa 40:16` And Lebanon is not *_sufficient_* to burn, nor its beasts *_sufficient_* for a burnt-offering.
* `Mth 6:34` "Therefore, do not be anxious for the next day, for the next day will be solicitous for the things of itself. *_Sufficient_* for each day is its own evil."
* `Jhn 6:7` Philip answered him, "Two hundred denarii worth of bread is not *_sufficient_* for them, so that each of them may receive a little."
* `Jhn 14:8` Philip says to him, "Lord, show us the Father and it will be *_sufficient_* for us."
* `2Co 2:6` *_Sufficient_* to such a man is this punishment which was inflicted by many,
* `2Co 2:16` To one we are the savor of death to death and to the other the savor of life to life. And who is *_sufficient_* for these things?
* `2Co 3:5` Not that we are *_sufficient_* by ourselves to think anything as from ourselves, but our sufficiency is from God,
* `2Co 12:9` And he said to me, "My grace is *_sufficient_* for you, for my strength is made perfect in weakness." Therefore, most gladly I will so much the more glory in my infirmities so that the power of Christ may rest upon me.
* `1Pe 4:3` For the past time is *_sufficient_* to have wrought the desire of the Gentiles, having walked in lasciviousness, lusts, excess of wine, revelings, banquetings, and abominable idolatries,

_14 verses containing SUFFICIENT_

== SUFFICIENTLY

* `2Ch 30:3` For they could not keep it at that time because the priests had not sanctified themselves *_sufficiently_*, neither had the people assembled themselves at Jerusalem.

_1 verse containing SUFFICIENTLY_

== SUIT

* `Jdg 17:10` And Micah said to him, "Dwell with me and be to me a father and a priest, and I will give you ten shekels of silver by the year, a *_suit_* of apparel, and your food." So the Levite went in.

_1 verse containing SUIT_

== SUITABLE

* `Gen 2:18` And the LORD God said, "It is not good that the man should be alone. I will make him a helper *_suitable_* for him."
* `Gen 2:20` And Adam gave names to all livestock, to the birds of the air, and to every beast of the field, but for Adam, a helper *_suitable_* for him was not found.
* `Deu 3:18` "And I commanded you at that time, saying, 'The LORD your God has given you this land to possess it. You shall pass over armed before your brothers the children of Israel, all who are *_suitable_* for the war.
* `Jdg 5:30` 'Have they not found, have they not divided the plunder: to every man a woman or two, to Sisera plunder of diverse colors, plunder of diverse colors of needle-work, of diverse colors of needle-work on both sides, *_suitable_* for the necks of those who take the plunder?'
* `Est 2:9` And the young woman pleased him and she obtained kindness from him. And he speedily gave her things for purification, with such things as belonged to her, and seven attendants who were *_suitable_* to be given to her out of the king's house. And he moved her and her attendants to the best place of the house of the women.
* `Psa 93:5` Your testimonies are very sure. Holiness is *_suitable_* for your house, O LORD, forever.
* `Pro 17:7` Excellent speech is not *_suitable_* for a fool, much less are lying lips for a prince.
* `Act 27:12` And because the haven was not *_suitable_* to winter in, the greater part advised to depart from there also, if by any means they might attain to Phenice and winter there, which is a haven of Crete looking toward the southwest and northwest.

_8 verses containing SUITABLE_

== SUITS

* `Isa 3:22` The changeable *_suits_* of apparel, the mantles, the cloaks, the purses,

_1 verse containing SUITS_

== SUKKIIMS

* `2Ch 12:3` With twelve hundred chariots and sixty thousand horsemen. And the people were without number who came with him out of Egypt: the Lubims, the *_Sukkiims_*, and the Cushites.

_1 verse containing SUKKIIMS_

== SUM

* `Exo 21:30` If there is laid on him a *_sum_* of money, then he shall give for the ransom of his life whatever is laid upon him.
* `Exo 30:12` "When you take the *_sum_* of the children of Israel after their number, they shall each give a ransom for his soul to the LORD when you number them so that there may be no plague among them when you number them.
* `Exo 38:21` This is the *_sum_* of the tabernacle, even of the tabernacle of testimony, as it was counted, according to the commandment of Moses, for the service of the Levites, by the hand of Ithamar, son to Aaron the priest.
* `Num 1:2` "Take the *_sum_* of all the congregation of the children of Israel after their families by the house of their fathers, with the number of their names, every male by their poll.
* `Num 1:49` "Only you shall not number the tribe of Levi, neither take the *_sum_* of them among the children of Israel.
* `Num 4:2` "Take the *_sum_* of the sons of Kohath from among the sons of Levi by their families and by the house of their fathers,
* `Num 4:22` "Take also the *_sum_* of the sons of Gershon throughout the house of their fathers and by their families.
* `Num 26:2` "Take the *_sum_* of all the congregation of the children of Israel from twenty years old and upward throughout their fathers' house, all who are able to go to war in Israel."
* `Num 26:4` "Take the *_sum_* of the people from twenty years old and upward as the LORD commanded Moses and the children of Israel, who went forth from the land of Egypt."
* `Num 31:26` "Take the *_sum_* of the plunder that was taken, both of man and of beast—you, Eleazar the priest, and the chief fathers of the congregation—
* `Num 31:49` And they said to Moses, "Your servants have taken the *_sum_* of the men of war who are under our charge, and there does not lack one man of us.
* `2Sa 24:9` And Joab presented the *_sum_* of the number of the people to the king. And there were in Israel eight hundred thousand valiant men who drew the sword, and the men of Judah were five hundred thousand men.
* `2Ki 22:4` "Go to Hilkiah the high priest so that he may *_sum_* the silver which is brought into the house of the LORD, which the keepers of the door have gathered from the people.
* `1Ch 21:5` And Joab gave the *_sum_* of the number of the people to David. And all the people of Israel numbered one million and one hundred thousand men who drew sword. And Judah was four hundred and seventy thousand men who drew sword.
* `Est 4:7` And Mordecai told him all that had happened to him and of the *_sum_* of the money that Haman had promised to pay to the king's treasuries for the destruction of the Jews.
* `Psa 139:17` How precious your thoughts are to me, O God! How great the *_sum_* of them is!
* `Ezk 28:12` "Son of man, take up a lamentation upon the king of Tyre, and say to him, 'Thus says the Lord GOD: "You seal up the *_sum_*, full of wisdom and perfect in beauty.
* `Dan 7:1` In the first year of Belshazzar king of Babylon, Daniel had a dream and visions of his head upon his bed. Then he wrote the dream and told the *_sum_* of the matters.
* `Mth 28:12` And when they were assembled with the elders and had taken counsel, they gave a large *_sum_* of money to the soldiers,
* `Act 7:16` They were carried over into Shechem and laid in the sepulcher that Abraham bought for a *_sum_* of money from the sons of Hamor the father of Shechem.
* `Act 22:28` And the chief captain answered, "With a great *_sum_* I obtained this freedom." And Paul said, "But I was born a citizen."
* `Heb 8:1` Now of the things which we have spoken, this is the *_sum_*: we have such a high priest who is set on the right hand of the throne of the Majesty in the heavens,

_22 verses containing SUM_

== SUMMER

* `Gen 8:22` While the earth remains, seed-time and harvest, cold and heat, *_summer_* and winter, and day and night shall not cease."
* `Jdg 3:20` And Ehud came to him. And he was sitting in a *_summer_*-parlor which he had for himself alone. And Ehud said, "I have a message from God to you." And he arose from his seat.
* `Jdg 3:24` When he had gone out, his servants came. And when they saw that, behold, the doors of the parlor were locked, they said, "Surely he covers his feet in his *_summer_*-chamber."
* `2Sa 16:1` And when David was a little past the top of the hill, behold, Ziba the servant of Mephibosheth met him, with a couple of donkeys saddled and upon them two hundred loaves of bread, one hundred bunches of raisins, one hundred of *_summer_* fruits, and a bottle of wine.
* `2Sa 16:2` And the king said to Ziba, "What do you mean by these?" And Ziba said, "The donkeys are for the king's household to ride on, the bread and *_summer_* fruit for the young men to eat, and the wine so that those who are faint in the wilderness may drink."
* `Psa 32:4` For day and night your hand was heavy upon me. My moisture is turned into the drought of *_summer_*. [Selah.]
* `Psa 74:17` You have set all the borders of the earth. You have made *_summer_* and winter.
* `Pro 6:8` Provides her provisions in the *_summer_* and gathers her food in the harvest.
* `Pro 10:5` He who gathers in *_summer_* is a wise son, but he who sleeps in harvest is a son who causes shame.
* `Pro 26:1` As snow in *_summer_* and as rain in harvest, so honor is not appropriate for a fool.
* `Pro 30:25` The ants are a people not strong, yet they prepare their food in the *_summer_*,
* `Isa 16:9` Therefore, I will wail with the weeping of Jazer for the vine of Sibmah. I will water you with my tears, O Heshbon and Elealeh, for on your *_summer_* fruits and on your harvest the battle shout has fallen.
* `Isa 18:6` They shall be left together to the birds of the mountains and to the beasts of the earth. And the birds shall *_summer_* upon them, and all the beasts of the earth shall winter upon them.
* `Isa 28:4` And the glorious beauty, which is on the head of the rich valley, shall be a fading flower and as the early fruit before the *_summer_*, which he who looks upon it sees, and while it is still in his hand he eats it up.
* `Jer 8:20` "The harvest has past, the *_summer_* has ended, and we are not saved."
* `Jer 40:10` As for me, behold, I will dwell at Mizpah to serve the Chaldeans who will come to us. But you, gather wine, *_summer_* fruits, and oil, and put them in your vessels and dwell in your cities that you have taken."
* `Jer 40:12` Even all the Jews returned out of all places where they were driven and came to the land of Judah, to Gedaliah, to Mizpah, and gathered wine and *_summer_* fruits in abundance.
* `Jer 48:32` O vine of Sibmah, I will weep for you with the weeping of Jazer. Your plants have gone over the sea. They reach even to the sea of Jazer. The destroyer has fallen upon your *_summer_* fruits and upon your vintage.
* `Dan 2:35` Then the iron, the clay, the brass, the silver, and the gold were broken to pieces together and became like the chaff of the *_summer_* threshing-floors, and the wind carried them away so that no place was found for them. And the stone that smote the image became a great mountain and filled the whole earth.
* `Amo 3:15` And I will smite the winter-house together with the *_summer_*-house, the houses of ivory shall perish, and the great houses shall have an end," says the LORD.
* `Amo 8:1` Thus the Lord GOD has shown to me, and behold, a basket of *_summer_* fruit.
* `Amo 8:2` And he said, "Amos, what do you see?" And I said, "A basket of *_summer_* fruit." Then the LORD said to me, "The end has come upon my people of Israel. I will not again pass by them anymore.
* `Mic 7:1` Woe is me! For I am as when they have gathered the *_summer_* fruits, as the grape-gleanings of the vintage. There is no cluster to eat. My soul desired the first ripe fruit.
* `Zch 14:8` And it shall be in that day, that living waters shall go out from Jerusalem: half of them toward the eastern sea and half of them toward the western sea. In *_summer_* and in winter it shall be.
* `Mth 24:32` "Now learn a parable of the fig-tree. When its branch is yet tender and puts forth leaves, you know that *_summer_* is near.
* `Mrk 13:28` "Now learn a parable of the fig-tree: when its branch is yet tender and puts forth leaves, you know that *_summer_* is near.
* `Luk 21:30` As soon as they shoot forth, you see and know for yourselves that *_summer_* is now near at hand.

_27 verses containing SUMMER_

== SUMMER-CHAMBER

* `Jdg 3:24` When he had gone out, his servants came. And when they saw that, behold, the doors of the parlor were locked, they said, "Surely he covers his feet in his *_summer-chamber_*."

_1 verse containing SUMMER-CHAMBER_

== SUMMER-HOUSE

* `Amo 3:15` And I will smite the winter-house together with the *_summer-house_*, the houses of ivory shall perish, and the great houses shall have an end," says the LORD.

_1 verse containing SUMMER-HOUSE_

== SUMMER-PARLOR

* `Jdg 3:20` And Ehud came to him. And he was sitting in a *_summer-parlor_* which he had for himself alone. And Ehud said, "I have a message from God to you." And he arose from his seat.

_1 verse containing SUMMER-PARLOR_

== SUMMON

* `Act 25:3` And desired favor against him that he would *_summon_* him to Jerusalem. (They were lying in wait in the way to kill him.)

_1 verse containing SUMMON_

== SUMMONED

* `1Sa 13:4` And all Israel heard it said that Saul had smitten a garrison of the Philistines and that Israel also was had in abomination with the Philistines. And the people were *_summoned_* to Saul at Gilgal.

_1 verse containing SUMMONED_

== SUMPTUOUSLY

* `Luk 16:19` "There was a certain rich man who was clothed in purple and fine linen and fared *_sumptuously_* every day.

_1 verse containing SUMPTUOUSLY_

== SUN

* `Gen 15:12` And when the *_sun_* was going down, a deep sleep fell upon Abram, and behold, a horror of great darkness fell upon him.
* `Gen 15:17` And it came to pass, that when the *_sun_* had gone down and it was dark, behold, a smoking furnace, and a burning lamp that passed between those pieces.
* `Gen 19:23` The *_sun_* had risen upon the earth when Lot entered into Zoar.
* `Gen 28:11` And he alighted upon a certain place and stayed there all night because the *_sun_* had set. And he took some of the stones of that place and set them for his head-rest and lay down in that place to sleep.
* `Gen 32:31` And as he passed over Penuel the *_sun_* rose upon him, and he limped upon his thigh.
* `Gen 37:9` And he dreamed yet another dream and told it to his brothers, and said, "Behold, I have dreamed a dream again, and behold, the *_sun_* and the moon and the eleven stars made obeisance to me."
* `Exo 16:21` And they gathered it every morning, every man according to his eating. And when the *_sun_* became hot, it melted.
* `Exo 17:12` But Moses's hands were heavy, and they took a stone and put it under him, and he sat upon it. And Aaron and Hur supported his hands, one on one side and the other on the other side. And his hands were steady until the going down of the *_sun_*.
* `Exo 22:3` If the *_sun_* has risen upon him, there shall be blood shed for him, for he should make full restitution. If he has nothing, then he shall be sold for his theft.
* `Exo 22:26` If you ever take your neighbor's clothing to pledge, you shall deliver it to him by the setting of the *_sun_*.
* `Lev 22:7` And when the *_sun_* is set, he shall be clean. And afterward, he may eat the holy things, because it is his food.
* `Num 2:3` And on the east side toward the rising of the *_sun_*, those of the standard of the camp of Judah shall pitch throughout their armies, and Nahshon the son of Amminadab shall be captain of the children of Judah.
* `Num 25:4` And the LORD said to Moses, "Take all the heads of the people and hang them up to the LORD before the *_sun_* so that the fierce anger of the LORD may be turned away from Israel."
* `Deu 4:19` And lest you should lift up your eyes to heaven, and when you see the *_sun_*, the moon, and the stars, even all the host of heaven, should be driven to worship them and serve them, which the LORD your God has divided to all nations under the whole heaven.
* `Deu 11:30` Are they not on the other side of the Jordan, by the way where the *_sun_* goes down in the land of the Canaanites who dwell in the plain over against Gilgal beside the plains of Moreh?
* `Deu 16:6` But at the place which the LORD your God chooses to place his name in, there you shall sacrifice the passover at evening, at the setting of the *_sun_*, at the time of your departure from Egypt.
* `Deu 17:3` And has gone and served other gods and worshiped them, either the *_sun_*, moon, or any of the host of heaven, which I have not commanded,
* `Deu 23:11` But it shall be when evening comes near, that he shall wash himself with water, and when the *_sun_* is down, he shall come into the camp again.
* `Deu 24:13` In any case, you shall return the pledge to him when the *_sun_* goes down, so that he may sleep in his own clothing and bless you. And it shall be righteousness for you before the LORD your God.
* `Deu 24:15` At his day you shall give him his hire, neither shall the *_sun_* go down upon it, for he is poor and sets his heart upon it, lest he should cry against you to the LORD and it be sin to you.
* `Deu 33:14` For the precious fruits brought forth by the *_sun_*, for the precious things put forth by the moon,
* `Jsh 1:4` From the wilderness and this Lebanon even to the great river, the Euphrates River, all the land of the Hittites, and to the Great Sea toward the setting of the *_sun_*, shall be your border.
* `Jsh 8:29` And the king of Ai he hanged on a tree until evening. And as soon as the *_sun_* was down, Joshua commanded that they should take his carcass down from the tree, cast it at the entering of the gate of the city, and raise upon it a great heap of stones, which remains to this day.
* `Jsh 10:12` Then Joshua spoke to the LORD in the day when the LORD delivered up the Amorites before the children of Israel, and he said in the sight of Israel, "*_Sun_*, stand still upon Gibeon, and you, Moon, in the valley of Ajalon."
* `Jsh 10:13` And the *_sun_* stood still and the moon stayed until the people had avenged themselves upon their enemies. Is this not written in the book of Jasher? So the *_sun_* stood still in the midst of the heavens and did not hasten to go down about a whole day.
* `Jsh 10:27` And it came to pass at the time of the setting of the *_sun_*, that Joshua commanded, and they took them down from the trees and cast them into the cave in which they had been hid and laid great stones upon the cave's mouth, which remain until this very day.
* `Jsh 12:1` Now these are the kings of the land whom the children of Israel smote and possessed their land on the other side of the Jordan toward the rising of the *_sun_*, from the Arnon River, to mount Hermon, and all the plain on the east:
* `Jdg 5:31` "So let all your enemies perish, O LORD. But let those who love him be as the *_sun_* when he goes forth in his might." And the land had rest for forty years.
* `Jdg 8:13` And Gideon the son of Joash returned from battle before the *_sun_* had risen
* `Jdg 9:33` And it shall be, that in the morning, as soon as the *_sun_* has risen, you shall rise early and attack the city. And behold, when he and the people who are with him come out against you, you may do to them as you find occasion."
* `Jdg 14:18` And the men of the city said to him on the seventh day before the *_sun_* went down, "What is sweeter than honey? And what is stronger than a lion?" And he said to them, "If you had not plowed with my heifer, you would not have found out my riddle."
* `Jdg 19:14` And they passed on and went their way. And the *_sun_* went down upon them when they were by Gibeah, which belongs to Benjamin.
* `1Sa 11:9` And they said to the messengers who came, "Thus you shall say to the men of Jabesh-gilead: 'Tomorrow by the time the *_sun_* is hot, you shall have help.'" And the messengers came and declared it to the men of Jabesh, and they were glad.
* `2Sa 2:24` Also, Joab and Abishai pursued Abner. And the *_sun_* went down when they had come to the hill of Ammah that lies before Giah by the way of the wilderness of Gibeon.
* `2Sa 3:35` And when all the people came to cause David to eat food while it was still day, David swore, saying, "May God do so to me and more also if I taste bread or anything else until the *_sun_* is down."
* `2Sa 12:11` Thus says the LORD: 'Behold, I will raise up evil against you out of your own house and will take your wives before your eyes and give them to your neighbor, and he shall lie with your wives in the sight of this *_sun_*.
* `2Sa 12:12` For you did it secretly. But I will do this thing before all Israel and before the *_sun_*.'"
* `2Sa 23:4` And he shall be as the light of the morning when the *_sun_* rises, even a morning without clouds, as the tender grass springing out of the earth from clear shining after the rain.'
* `1Ki 22:36` And there went a proclamation throughout the host at about the setting of the *_sun_*, saying, "Every man to his city and every man to his own country."
* `2Ki 3:22` And they rose early in the morning, and the *_sun_* shone upon the water. And the Moabites saw the water on the other side as red as blood.
* `2Ki 23:5` And he put down the idolatrous priests whom the kings of Judah had ordained to burn incense in the high places in the cities of Judah and in the places around Jerusalem, those who burned incense to Baal, to the *_sun_*, to the moon, to the planets, and to all the host of heaven.
* `2Ki 23:11` And he took away the horses that the kings of Judah had given to the *_sun_* at the entrance of the house of the LORD, by the chamber of Nathan-melech the chamberlain which was in the suburbs, and burned the chariots of the *_sun_* with fire.
* `Neh 7:3` And I said to them, "Do not let the gates of Jerusalem be opened until the *_sun_* is hot. And while they stand by, let them shut the doors and bar them. And appoint watches from the inhabitants of Jerusalem, each in his watch and each to be over against his house."
* `Job 8:16` He is green before the *_sun_*, and his branch shoots forth in his garden.
* `Job 9:7` He commands the *_sun_*, and it does not rise. He also seals up the stars.
* `Job 30:28` I went mourning without the *_sun_*. I stood up and cried in the congregation.
* `Job 31:26` If I have beheld the *_sun_* when it shined or the moon walking in brightness,
* `Psa 19:4` Their line has gone out through all the earth, and their words to the end of the world. In them he has set a tabernacle for the *_sun_*.
* `Psa 50:1` [A Psalm of Asaph.] The mighty God, even the LORD, has spoken and called the earth from the rising to the setting of the *_sun_*.
* `Psa 58:8` As a snail which melts, let every one of them pass away like the untimely birth of a woman so that they may not see the *_sun_*.
* `Psa 72:5` They shall fear you as long as the *_sun_* and moon endure, throughout all generations.
* `Psa 72:17` His name shall endure forever. His name shall be continued as long as the *_sun_*. And men shall be blessed in him. All nations shall call him blessed.
* `Psa 74:16` The day is yours, the night also is yours. You have prepared the light and the *_sun_*.
* `Psa 84:11` For the LORD God is a *_sun_* and shield. The LORD will give grace and glory. No good will he withhold from those who walk uprightly.
* `Psa 89:36` His offspring shall endure forever, and his throne as the *_sun_* before me.
* `Psa 104:19` He appoints the moon for seasons. The *_sun_* knows his going down.
* `Psa 104:22` The *_sun_* arises, and they collect and lay themselves down in their dens.
* `Psa 113:3` From the rising of the *_sun_* to the going down of the same, the LORD'S name is to be praised.
* `Psa 121:6` The *_sun_* shall not smite you by day, nor the moon by night.
* `Psa 136:8` The *_sun_* to rule by day—for his mercy endures forever—
* `Psa 148:3` Praise him, *_sun_* and moon. Praise him, all you stars of light.
* `Ecc 1:3` What profit does a man have of all his labor, which he takes under the *_sun_*?
* `Ecc 1:5` The *_sun_* also rises, and the *_sun_* goes down, and hastens to his place where he arose.
* `Ecc 1:9` The thing that has been, is that which shall be. And that which is done, is that which shall be done. And there is nothing new under the *_sun_*.
* `Ecc 1:14` I have seen all the works that are done under the *_sun_*, and behold, all is vanity and vexation of spirit.
* `Ecc 2:11` Then I considered all the works that my hands had wrought and the labor that I had labored to do, and behold, all was vanity and vexation of spirit, and there was no profit under the *_sun_*.
* `Ecc 2:17` Therefore, I hated life, because the work that is wrought under the *_sun_* is grievous to me. For all is vanity and vexation of spirit.
* `Ecc 2:18` Indeed, I hated all my labor which I had taken under the *_sun_*, because I must leave it to the man who shall be after me.
* `Ecc 2:19` And who knows whether he shall be a wise man or a fool? Yet he shall have rule over all my labor in which I have labored and in which I have shown myself wise under the *_sun_*. This is also vanity.
* `Ecc 2:20` Therefore, I began to cause my heart to despair of all the labor which I took under the *_sun_*.
* `Ecc 2:22` For what does man have of all his labor and of the vexation of his heart in which he has labored under the *_sun_*?
* `Ecc 3:16` And moreover, I saw under the *_sun_* the place of judgment, that wickedness was there, and the place of righteousness, that iniquity was there.
* `Ecc 4:1` Thus I returned, and considered all the oppressions that are done under the *_sun_*. And behold, the tears of those who were oppressed, and they had no comforter. And on the side of their oppressors there was power, but they had no comforter.
* `Ecc 4:3` Indeed, better is he than both of them who has not yet been, who has not seen the evil work that is done under the *_sun_*.
* `Ecc 4:7` Then I returned, and I saw vanity under the *_sun_*.
* `Ecc 4:15` I considered all the living who walk under the *_sun_*, that they were with the second youth who shall stand up in his stead.
* `Ecc 5:13` There is a grievous evil which I have seen under the *_sun_*, namely, riches kept for their owner to his hurt.
* `Ecc 5:18` Behold that which I have seen. It is good and fitting for one to eat and to drink and to enjoy the good of all his labor that he takes under the *_sun_* all the days of his life which God gives him, for it is his portion.
* `Ecc 6:1` There is an evil which I have seen under the *_sun_*, and it is common among men:
* `Ecc 6:5` Moreover, he has not seen the *_sun_*, nor known anything. This one has more rest than the other.
* `Ecc 6:12` For who knows what is good for man in this life, all the days of his vain life which he spends as a shadow? For who can tell a man what shall be after him under the *_sun_*?
* `Ecc 7:11` Wisdom is good with an inheritance, and by it there is profit to those who see the *_sun_*.
* `Ecc 8:9` All this I have seen, applying my heart to every work that is done under the *_sun_*. There is a time in which one man rules over another to his own hurt.
* `Ecc 8:15` Then I commended mirth, because a man has no better thing under the *_sun_* than to eat, to drink, and to be merry, for that shall abide with him in his labor all the days of his life which God gives him under the *_sun_*.
* `Ecc 8:17` I beheld all the work of God, that a man cannot find out the work that is done under the *_sun_*. Because even though a man may labor to seek it out, yet he shall not find it, and even though a wise man thinks to know it, yet he shall not be able to find it.
* `Ecc 9:3` This is an evil among all things that are done under the *_sun_*, that there is one event to all. Also the heart of the sons of men is full of evil, and madness is in their heart while they live, and after that they go to the dead.
* `Ecc 9:6` Also their love, their hatred, and their envy has now perished, neither do they have anymore a portion forever in anything that is done under the *_sun_*.
* `Ecc 9:9` Live joyfully with the wife whom you love all the days of the life of your vanity, which he has given you under the *_sun_*, all the days of your vanity, for that is your portion in this life and in your labor which you take under the *_sun_*.
* `Ecc 9:11` I returned, and saw under the *_sun_*, that the race is not to the swift, nor the battle to the strong, neither yet bread to the wise, nor yet riches to men of understanding, nor yet favor to men of skill, but time and chance happens to them all.
* `Ecc 9:13` This wisdom I have also seen under the *_sun_*, and it seemed to me great:
* `Ecc 10:5` There is an evil which I have seen under the *_sun_*, as an error which proceeds from the ruler:
* `Ecc 11:7` Truly the light is sweet, and a pleasant thing it is for the eyes to behold the *_sun_*.
* `Ecc 12:2` While the *_sun_*, the light, the moon, or the stars are not darkened, nor the clouds return after the rain;
* `Sos 1:6` Do not look upon me because I am black, because the *_sun_* has looked upon me. My mother's children were angry with me. They made me the keeper of the vineyards, but I have not kept my own vineyard.
* `Sos 6:10` Who is she who looks forth as the morning, fair as the moon, clear as the *_sun_*, and awesome as an army with banners?
* `Isa 13:10` For the stars of heaven and its constellations shall not give their light. The *_sun_* shall be darkened in his going forth, and the moon shall not cause her light to shine.
* `Isa 24:23` Then the moon shall be confounded and the *_sun_* ashamed when the LORD of hosts reigns on mount Zion, in Jerusalem, and before his ancients gloriously.
* `Isa 30:26` Moreover, the light of the moon shall be like the light of the *_sun_*, and the light of the *_sun_* shall be seven-fold, like the light of seven days, in the day that the LORD binds up the breach of his people and heals the stroke of their wound.
* `Isa 38:8` Behold, I will bring back the shadow of the degrees, which has gone down on the *_sun_*-dial of Ahaz, ten degrees backward." So the *_sun_* returned ten degrees, by which degrees it had gone down.
* `Isa 41:25` I have raised up one from the north, and he shall come. From the rising of the *_sun_* he shall call upon my name. And he shall come upon princes as upon mortar, and as the potter treads clay.
* `Isa 45:6` So that they may know from the rising of the *_sun_* and from the west, that there is no one besides me. I am the LORD, and there is no one else.
* `Isa 49:10` They shall neither hunger nor thirst, neither shall the heat or *_sun_* smite them, for he who has mercy on them shall lead them, even by the springs of water he shall guide them.
* `Isa 59:19` So they shall fear the name of the LORD from the west, and his glory from the rising of the *_sun_*. When the enemy comes in like a flood, the Spirit of the LORD will lift up a standard against him.
* `Isa 60:19` The *_sun_* shall no longer be your light by day, neither for brightness shall the moon give light to you, but the LORD will be to you an everlasting light, and your God will be your glory.
* `Isa 60:20` Your *_sun_* shall go down no more, neither shall your moon withdraw itself, for the LORD will be your everlasting light, and the days of your mourning shall be ended.
* `Jer 8:2` And they shall spread them before the *_sun_*, the moon, and all the host of heaven, whom they have loved, whom they have served, after whom they have walked, whom they have sought, and whom they have worshiped. They shall not be gathered nor be buried. They shall be for dung upon the face of the earth.
* `Jer 15:9` She who has borne seven languishes. She has resigned her breath. Her *_sun_* has gone down while it was still day. She has been ashamed and confounded. And their remnant I will deliver to the sword before their enemies," says the LORD.
* `Jer 31:35` Thus says the LORD, who gives the *_sun_* for a light by day and the ordinances of the moon and of the stars for a light by night, who divides the sea when its waves roar, the LORD of hosts is his name:
* `Ezk 8:16` And he brought me into the inner court of the LORD'S house, and behold, at the door of the temple of the LORD, between the porch and the altar, were about twenty-five men with their backs toward the temple of the LORD and their faces toward the east, and they worshiped the *_sun_* toward the east.
* `Ezk 32:7` And when I extinguish you, I will cover the heaven and make the stars thereof dark. I will cover the *_sun_* with a cloud and the moon shall not give her light.
* `Dan 6:14` Then the king, when he heard these words, was much displeased with himself and set his heart on Daniel to deliver him. And he labored until the setting of the *_sun_* to deliver him.
* `Joe 2:10` The earth shall quake before them. The heavens shall tremble. The *_sun_* and the moon shall be dark, and the stars shall withdraw their shining.
* `Joe 2:31` The *_sun_* shall be turned into darkness, and the moon into blood, before the great and terrible day of the LORD comes.
* `Joe 3:15` The *_sun_* and the moon shall be darkened, and the stars shall withdraw their shining.
* `Amo 8:9` And it shall come to pass in that day," says the Lord GOD, "that I will cause the *_sun_* to go down at noon and I will darken the earth in the clear day,
* `Jna 4:8` And it came to pass, when the *_sun_* rose, that God prepared a vehement east wind. And the *_sun_* beat upon the head of Jonah so that he fainted and wished in himself to die, and said, "It is better for me to die than to live."
* `Mic 3:6` "Therefore, night shall be for you so that you shall not have a vision. And it shall be dark for you so that you shall not divine. And the *_sun_* shall go down over the prophets, and the day shall be dark over them.
* `Nah 3:17` Your crowned ones are as the swarming-locusts, and your captains as the swarms of locusts, which settle in the hedges on the cold day. But when the *_sun_* arises they flee away, and the place where they are is unknown.
* `Hab 3:11` The *_sun_* and moon stood still in their habitation. At the light of your arrows they went, and at the shining of your glittering spear.
* `Mal 1:11` For from the rising of the *_sun_* even to the setting of the same, my name shall be great among the Gentiles, and in every place incense shall be offered to my name, even a pure offering, for my name shall be great among the heathen," says the LORD of hosts.
* `Mal 4:2` But to you who fear my name, the *_Sun_* of righteousness shall arise with healing in his wings, and you shall go forth and grow up as calves of the stall.
* `Mth 5:45` So that you may be the children of your Father who is in heaven. For he makes his *_sun_* to rise on the evil and on the good, and sends rain on the just and on the unjust.
* `Mth 13:6` And when the *_sun_* had risen, they were scorched, and because they did not have root, they withered.
* `Mth 13:43` Then 'the righteous shall shine as the *_sun_*' in the kingdom of their Father. He who has ears to hear, let him hear.
* `Mth 17:2` And he was transfigured before them. His face shone as the *_sun_*, and his clothing was white as the light.
* `Mth 24:29` "Immediately after the tribulation of those days 'the *_sun_* shall be darkened and the moon shall not give her light, the stars shall fall' from heaven and the powers of the heavens shall be shaken.
* `Mrk 1:32` And at evening when the *_sun_* had set, they brought to him all who were diseased and those who were possessed with demons.
* `Mrk 4:6` But when the *_sun_* had risen, it was scorched, and because it had no root, it withered away.
* `Mrk 13:24` "But in those days, after that tribulation, 'the *_sun_* shall be darkened, the moon shall not give her light,
* `Mrk 16:2` And very early in the morning, the first day of the week, they came to the sepulcher at the rising of the *_sun_*.
* `Luk 4:40` Now when the *_sun_* was setting, all those who had any sick with various diseases brought them to him. And he laid his hands on every one of them and healed them.
* `Luk 21:25` "And there shall be signs in the *_sun_*, in the moon, and in the stars, and upon the earth distress of nations in perplexity because of the roaring of the sea and the waves.
* `Luk 23:45` And the *_sun_* was darkened and the veil of the temple was rent in the midst.
* `Act 2:20` The *_sun_* shall be turned into darkness and the moon into blood before that great and notable day of the Lord comes.
* `Act 13:11` And now behold, the hand of the Lord is upon you and you shall be blind, not seeing the *_sun_* for a season." And immediately there fell on him a mist and a darkness and he went around seeking someone to lead him by the hand.
* `Act 26:13` At mid-day, O king, I saw in the way a light from heaven surpassing the brightness of the *_sun_*, shining around me and those who journeyed with me.
* `Act 27:20` And when neither *_sun_* nor stars in many days appeared and no small tempest lay on us, all hope that we should be saved was then taken away.
* `1Co 15:41` There is one glory of the *_sun_*, another glory of the moon, and another glory of the stars, for one star differs from another star in glory.
* `Eph 4:26` "Be angry, and do not sin." Do not let the *_sun_* go down upon your wrath,
* `Jms 1:11` For the *_sun_* arose with its burning heat and withered the grass. Its flower fell and the grace of its fashion perished. Likewise also, the rich man shall fade away in his ways.
* `Rev 1:16` And he had in his right hand seven stars. And out of his mouth went a sharp two-edged sword. And his countenance was as the *_sun_* shining in its strength.
* `Rev 6:12` And I beheld when he had opened the sixth seal, and behold, there was a great earthquake, and the *_sun_* became black as sackcloth of hair, and the moon became as blood.
* `Rev 7:16` 'They shall no longer hunger, neither thirst anymore, neither shall the *_sun_* fall upon them, nor any heat.'
* `Rev 8:12` And the fourth angel sounded, and the third part of the *_sun_* was smitten, along with the third part of the moon and the third part of the stars, so that the third part of them was darkened. And the day did not shine for a third part of it, and the night likewise.
* `Rev 9:2` And he opened the bottomless pit, and there arose a smoke out of the pit like the smoke of a great furnace. And the *_sun_* and the air were darkened by reason of the smoke of the pit.
* `Rev 10:1` And I saw another mighty angel come down from heaven clothed with a cloud and a rainbow upon his head. His face was like the *_sun_* and his feet like pillars of fire.
* `Rev 12:1` And there appeared a great wonder in heaven: a woman clothed with the *_sun_* and the moon under her feet, and upon her head a crown of twelve stars.
* `Rev 16:8` And the fourth angel poured out his vial upon the *_sun_*, and power was given to it to scorch men with fire.
* `Rev 19:17` And I saw an angel standing in the *_sun_*, and he cried with a loud voice, saying to all the birds that fly in the midst of heaven, "Come, and assemble yourselves to the supper of the great God
* `Rev 21:23` And the city had no need of the *_sun_* nor of the moon to shine in it, for the glory of God enlightened it, and the Lamb is its light.
* `Rev 22:5` And there shall be no night there. They need no candle, neither light of the *_sun_*, because the Lord God gives them light. And they shall reign forever and ever.

_151 verses containing SUN_

== SUN-DIAL

* `Isa 38:8` Behold, I will bring back the shadow of the degrees, which has gone down on the *_sun-dial_* of Ahaz, ten degrees backward." So the sun returned ten degrees, by which degrees it had gone down.

_1 verse containing SUN-DIAL_

== SUNG

* `Isa 26:1` In that day this song shall be *_sung_* in the land of Judah: "We have a strong city. God will appoint salvation for walls and bulwarks.
* `Mth 26:30` And when they had *_sung_* a hymn, they went out to the Mount of Olives.
* `Mrk 14:26` And when they had *_sung_* a hymn, they went out to the Mount of Olives.

_3 verses containing SUNG_

== SUNK

* `Exo 15:5` The depths have covered them. They *_sunk_* to the bottom like a stone.
* `Exo 15:10` You blew with your wind, the sea covered them. They *_sunk_* like lead in the mighty waters.
* `1Sa 17:49` And David put his hand in his bag, took from there a stone, hurled it with his sling, and smote the Philistine in his forehead so that the stone *_sunk_* into his forehead and he fell upon his face to the earth.
* `2Ki 9:24` And Jehu drew a bow with his full strength and smote Jehoram between his arms. The arrow went out at his heart, and he *_sunk_* down in his chariot.
* `Psa 9:15` The heathen are *_sunk_* down in the pit that they made. In the net which they hid, their own foot is taken.
* `Jer 38:6` Then they took Jeremiah and cast him into the dungeon of Malchiah the son of Hammelech that was in the court of the prison. And they let Jeremiah down with cords. And in the dungeon there was no water, but mire. So Jeremiah *_sunk_* in the mire.
* `Jer 38:22` 'And behold, all the women who are left in the king of Judah's house shall be brought forth to the king of Babylon's princes, and those women shall say, "Your friends have enticed you and have prevailed against you. Your feet are *_sunk_* in the mire, and they have turned away from you."
* `Lam 2:9` [TET] Her gates are *_sunk_* into the ground. He has destroyed and broken her bars. Her king and her princes are among the Gentiles. The law is no more. Her prophets also find no vision from the LORD.
* `Act 20:9` And a certain young man named Eutychus sat in a window, having fallen into a deep sleep. And as Paul discoursed longer still, he *_sunk_* down with sleep, fell from the third loft, and was taken up dead.

_9 verses containing SUNK_

== SUNRISE

* `Num 21:11` And they journeyed from Oboth and pitched at Ije-abarim in the wilderness which is before Moab, toward the *_sunrise_*.
* `Num 34:15` The two tribes and the half tribe have received their inheritance on this side of the Jordan near Jericho eastward toward the *_sunrise_*."
* `Deu 4:41` Then Moses set apart three cities on the side of the Jordan toward the *_sunrise_*
* `Deu 4:47` And they possessed his land and the land of Og king of Bashan, two kings of the Amorites who were on the side of the Jordan toward the *_sunrise_*,
* `Jsh 1:15` Until the LORD has given your brothers rest, as he has given you, and they also have possessed the land which the LORD your God gives them. Then you shall return to the land of your possession and enjoy it, which Moses the LORD'S servant gave you on this side of the Jordan toward the *_sunrise_*."
* `Jsh 13:5` And the land of the Giblites and all Lebanon toward the *_sunrise_*, from Baal-gad under mount Hermon to the entering into Hamath.
* `Jsh 19:12` Turned from Sarid eastward, toward the *_sunrise_*, to the border of Chisloth-tabor, then goes out to Daberath, then goes up to Japhia;
* `Jsh 19:27` And turns toward the *_sunrise_* to Beth-dagon, and reaches to Zebulun, and to the valley of Jiphthah-el toward the north side of Beth-emek, and Neiel, and goes out to Cabul on the left hand,
* `Jsh 19:34` And then the border turns westward to Aznoth-tabor, goes out from there to Hukkok, reaches to Zebulun on the south side, reaches to Asher on the west side, and to Judah upon the Jordan toward the *_sunrise_*;
* `Jdg 20:43` So they enclosed the Benjaminites on all sides and chased them and trod them down with ease over against Gibeah toward the *_sunrise_*.

_10 verses containing SUNRISE_

== SUNSET

* `2Ch 18:34` And the battle increased that day. Nevertheless, the king of Israel supported himself in his chariot against the Syrians until the evening. And about the time of the *_sunset_* he died.

_1 verse containing SUNSET_

== SUPERFLUOUS

* `Lev 21:18` For whatever man he may be who has a blemish, he shall not approach: a blind man, a lame, or he who has a flat nose, or anything *_superfluous_*,
* `Lev 22:23` Either a bull or a lamb that has anything *_superfluous_* or lacking in his parts, that you may offer for a voluntary-offering, but for a vow it shall not be accepted.
* `2Co 9:1` For as concerning the ministering to the saints, it is *_superfluous_* for me to write to you.

_3 verses containing SUPERFLUOUS_

== SUPERINTEND

* `2Ch 34:12` And the men did the work faithfully. And their overseers were Jahath and Obadiah, the Levites, of the sons of Merari; and Zechariah and Meshullam, of the sons of the Kohathites, to *_superintend_* it; and others of the Levites, all who had skill in instruments of music.

_1 verse containing SUPERINTEND_

== SUPERIOR

* `Dan 1:20` And in all matters of wisdom and understanding wherein the king questioned them, he found them ten times *_superior_* to all the magicians and astrologers who were in all his realm.

_1 verse containing SUPERIOR_

== SUPERSCRIPTION

* `Mth 22:20` And he says to them, "Whose image and *_superscription_* is this?"
* `Mrk 12:16` And they brought it, and he says to them, "Whose image and *_superscription_* is this?" And they said to him, "Caesar's."
* `Mrk 15:26` And the *_superscription_* of his accusation was written above, "THE KING OF THE JEWS."
* `Luk 20:24` Show me a denarius. Whose image and *_superscription_* does it have?" They answered and said, "Caesar's."
* `Luk 23:38` And also a *_superscription_* was written over him in letters of Greek, Latin, and Hebrew, "THIS IS THE KING OF THE JEWS."

_5 verses containing SUPERSCRIPTION_

== SUPERSTITION

* `Act 25:19` But had some questions against him of their own *_superstition_* and of one, Jesus, who was dead, whom Paul affirmed to be alive.

_1 verse containing SUPERSTITION_

== SUPERSTITIOUS

* `Act 17:22` Then Paul stood in the midst of Mars-hill, and said, "Men of Athens, I perceive that in all things you are too *_superstitious_*.

_1 verse containing SUPERSTITIOUS_

== SUPHAH

* `Num 21:14` Therefore, it is said in the Book of the Wars of the LORD, "At Vaheb in *_Suphah_* and in the brooks of Arnon,

_1 verse containing SUPHAH_

== SUPPER

* `Mrk 6:21` And when a convenient day had come, Herod, on his birthday, made a *_supper_* for his lords, high captains, and chief men of Galilee.
* `Luk 14:12` Then he also said to him who invited him, "When you make a dinner or a *_supper_*, do not call your friends, nor your brothers, neither your kinsmen, nor your rich neighbors, lest they also invite you again and a recompense be made to you.
* `Luk 14:16` Then he said to him, "A certain man made a great *_supper_*, invited many,
* `Luk 14:17` And sent his servant at *_supper_*-time to say to those who were invited, 'Come, for all things are now ready.'
* `Luk 14:24` For I say to you, that none of those men who were invited shall taste my *_supper_*.'"
* `Luk 17:8` Would he not rather say to him, 'Make ready with which I may have *_supper_*, gird yourself, and serve me until I have eaten and drank, and afterward, you shall eat and drink'?
* `Luk 22:20` Likewise, he took the cup after *_supper_*, saying, "This cup is the new testament in my blood which is shed for you.
* `Jhn 12:2` There they made him a *_supper_*, and Martha served. And Lazarus was one of those who sat at the table with him.
* `Jhn 13:2` And during *_supper_* (the devil having now put into the heart of Judas Iscariot, Simon's son, to betray him),
* `Jhn 13:4` Rises from *_supper_*, laid aside his garments, took a towel, and girded himself.
* `Jhn 21:20` Then Peter, turning around, sees the disciple whom Jesus loved following (who also leaned on his chest at *_supper_* and said, "Lord, who is he who betrays you?").
* `1Co 11:20` When therefore you come together in one place, this is not to eat the Lord's *_supper_*.
* `1Co 11:21` For in eating, each one takes before another his own *_supper_*. And one is hungry and another is drunken.
* `1Co 11:25` After the same manner, he also took the cup after *_supper_*, saying, "This cup is the new testament in my blood. Do this as often as you drink it in remembrance of me."
* `Rev 19:9` And he says to me, "Write, 'Blessed are those who are called to the marriage *_supper_* of the Lamb.'" And he says to me, "These are the true sayings of God."
* `Rev 19:17` And I saw an angel standing in the sun, and he cried with a loud voice, saying to all the birds that fly in the midst of heaven, "Come, and assemble yourselves to the *_supper_* of the great God

_16 verses containing SUPPER_

== SUPPER-TIME

* `Luk 14:17` And sent his servant at *_supper-time_* to say to those who were invited, 'Come, for all things are now ready.'

_1 verse containing SUPPER-TIME_

== SUPPLANT

* `Jer 9:4` "Everyone, take heed of his neighbor and do not trust in any brother, for every brother will utterly *_supplant_* and every neighbor will walk slanderously.

_1 verse containing SUPPLANT_

== SUPPLANTED

* `Gen 27:36` And he said, "Is he not rightly named Jacob? For he has *_supplanted_* me twice: he took away my birth-right, and behold, now he has taken away my blessing." And he said, "Have you not reserved a blessing for me?"

_1 verse containing SUPPLANTED_

== SUPPLE

* `Ezk 16:4` And as for your nativity, in the day you were born your navel was not cut, neither were you washed in water to *_supple_* you. You were not salted at all nor swaddled at all.

_1 verse containing SUPPLE_

== SUPPLIANTS

* `Zph 3:10` From beyond the rivers of Cush my *_suppliants_*, even the daughter of my dispersed, shall bring my offering.

_1 verse containing SUPPLIANTS_

== SUPPLICATION

* `1Sa 13:12` Therefore I said, 'The Philistines will now come down upon me at Gilgal, and I have not made *_supplication_* to the LORD.' I felt compelled therefore and offered a burnt-offering."
* `1Ki 8:28` Yet have respect to the prayer of your servant and to his *_supplication_*, O LORD my God, to listen to the cry and to the prayer which your servant prays before you this day,
* `1Ki 8:30` And listen to the *_supplication_* of your servant and of your people Israel when they pray toward this place. And hear in heaven your dwelling-place. And when you hear, forgive.
* `1Ki 8:33` "When your people Israel are smitten before the enemy because they have sinned against you, and they turn back to you, confess your name, pray, and make *_supplication_* to you in this house,
* `1Ki 8:38` Whatever prayer and *_supplication_* is made by any man or by all your people Israel, who shall each know the plague of his own heart, and spread forth his hands toward this house,
* `1Ki 8:45` Then hear in heaven their prayer and their *_supplication_* and maintain their cause.
* `1Ki 8:47` Yet if they repent themselves in the land where they were carried captives and repent and make *_supplication_* to you in the land of those who carried them captives, saying, 'We have sinned and have done perversely, we have committed wickedness,'
* `1Ki 8:49` Then hear their prayer and their *_supplication_* in heaven your dwelling-place, maintain their cause,
* `1Ki 8:52` So that your eyes may be open to the *_supplication_* of your servant and to the *_supplication_* of your people Israel to listen to them in all their supplications to you.
* `1Ki 8:54` And it was so, that when Solomon had made an end of praying all this prayer and *_supplication_* to the LORD, he arose from before the altar of the LORD, from kneeling on his knees, with his hands spread up to heaven.
* `1Ki 8:59` And let these words of mine with which I have made *_supplication_* before the LORD be near to the LORD our God day and night so that he may maintain the cause of his servant and the cause of his people Israel at all times, as the matter shall require,
* `1Ki 9:3` And the LORD said to him, "I have heard your prayer and your *_supplication_* that you have made before me. I have hallowed this house which you have built to put my name there forever. And my eyes and my heart shall be there perpetually.
* `2Ch 6:19` Have respect therefore to the prayer of your servant and to his *_supplication_*, O LORD my God, to listen to the cry and the prayer which your servant prays before you,
* `2Ch 6:24` "And if your people Israel are smitten before the enemy, because they have sinned against you, and return and confess your name and pray and make *_supplication_* before you in this house,
* `2Ch 6:29` Then whatever prayer or whatever *_supplication_* is made by any man or by all the people of Israel, when each knows his own calamity and his own grief and spreads forth his hands in this house,
* `2Ch 6:35` Then hear from the heavens their prayer and their *_supplication_* and maintain their cause.
* `2Ch 33:13` And he prayed to him, and God was entreated by him, heard his *_supplication_*, and brought him back to Jerusalem into his kingdom. Then Manasseh knew that the LORD is God.
* `Est 4:8` Also he gave him the copy of the writing of the decree that was given at Shushan to destroy them to show it to Esther, to declare it to her, and to charge her that she should go before the king to make *_supplication_* to him and to make request before him for her people.
* `Job 8:5` If you would seek God diligently and make your *_supplication_* to the Almighty,
* `Job 9:15` Though I were righteous, yet I would not answer. But I would make *_supplication_* to my judge.
* `Psa 6:9` The LORD has heard my *_supplication_*. The LORD will receive my prayer.
* `Psa 30:8` I cried to you, O LORD. And to the LORD I made *_supplication_*.
* `Psa 55:1` [To the Chief Musician on Neginoth. Maschil. A Psalm of David.] Give ear to my prayer, O God, and do not hide yourself from my *_supplication_*.
* `Psa 119:170` Let my *_supplication_* come before you. Deliver me according to your word.
* `Psa 142:1` [Maschil of David: a prayer when he was in the cave.] I cried to the LORD with my voice. With my voice to the LORD I made my *_supplication_*.
* `Isa 45:14` Thus says the LORD: "The labor of Egypt and merchandise of Cush, along with the Sabeans, men of stature, shall come over to you, and they shall be yours. They shall come after you. In chains they shall come over, and they shall fall down to you. They shall make *_supplication_* to you, saying, 'Surely God is in you, and there is no one else. There is no other God.'"
* `Jer 36:7` It may be that they will present their *_supplication_* before the LORD and will each return from his evil way, for the anger and the fury is great that the LORD has pronounced against this people."
* `Jer 37:20` Now therefore, hear, I pray you, O my lord the king. Let my *_supplication_*, I pray you, be accepted before you, that you do not cause me to return to the house of Jonathan the scribe, lest I die there."
* `Jer 38:26` Then you shall say to them, 'I presented my *_supplication_* before the king, that he would not cause me to return to Jonathan's house to die there.'"
* `Jer 42:2` And said to Jeremiah the prophet, "We implore you, let our *_supplication_* be accepted before you, and pray for us to the LORD your God, even for all this remnant (for we are left but a few of many, as your eyes behold us),
* `Jer 42:9` And said to them, "Thus says the LORD, the God of Israel, to whom you sent me to present your *_supplication_* before him:
* `Dan 6:11` Then these men assembled and found Daniel praying and making *_supplication_* before his God.
* `Dan 9:20` And while I was speaking, praying, and confessing my sin and the sin of my people Israel and presenting my *_supplication_* before the LORD my God for the holy mountain of my God,
* `Hos 12:4` He even had power over the angel and prevailed. He wept and made *_supplication_* to him. He found [God] in Beth-el, and there [God] spoke with us,
* `Act 1:14` All of these continued with one accord in prayer and *_supplication_*, with the women and Mary the mother of Jesus, and with his brothers.
* `Eph 6:18` Praying always with all prayer and *_supplication_* in the Spirit and watching for this purpose with all perseverance and *_supplication_* for all saints.
* `Phl 4:6` Be anxious for nothing, but in everything by prayer and *_supplication_* with thanksgiving let your requests be made known to God.

_37 verses containing SUPPLICATION_

== SUPPLICATIONS

* `1Ki 8:52` So that your eyes may be open to the supplication of your servant and to the supplication of your people Israel to listen to them in all their *_supplications_* to you.
* `2Ch 6:21` Listen therefore to the *_supplications_* of your servant and of your people Israel which they shall make toward this place. Hear from your dwelling-place, even from heaven, and when you hear, forgive.
* `2Ch 6:39` Then hear from the heavens, even from your dwelling-place, their prayer and their *_supplications_*, maintain their cause, and forgive your people who have sinned against you.
* `Job 41:3` Will he make many *_supplications_* to you? Will he speak soft words to you?
* `Psa 28:2` Hear the voice of my *_supplications_* when I cry to you, when I lift my hands toward your holy oracle.
* `Psa 28:6` Blessed be the LORD because he has heard the voice of my *_supplications_*.
* `Psa 31:22` For I said in my haste, "I am cut off from before your eyes." Nevertheless, you heard the voice of my *_supplications_* when I cried to you.
* `Psa 86:6` Give ear, O LORD, to my prayer and attend to the voice of my *_supplications_*.
* `Psa 116:1` I love the LORD because he has heard my voice and my *_supplications_*.
* `Psa 130:2` Lord, hear my voice. Let your ears be attentive to the voice of my *_supplications_*.
* `Psa 140:6` I said to the LORD, "You are my God." Hear the voice of my *_supplications_*, O LORD.
* `Psa 143:1` [A Psalm of David.] Hear my prayer, O LORD. Give ear to my *_supplications_*. Answer me in your faithfulness and in your righteousness.
* `Jer 3:21` A voice was heard upon the high places, weeping and *_supplications_* of the children of Israel, for they have perverted their way and have forgotten the LORD their God.
* `Jer 31:9` They shall come with weeping, and with *_supplications_* I will lead them. I will cause them to walk by the rivers of waters in a straight way, wherein they shall not stumble, for I am a father to Israel, and Ephraim is my first-born."
* `Dan 9:3` And I set my face to the Lord God, to seek by prayer and *_supplications_*, with fasting, sackcloth, and ashes.
* `Dan 9:17` Now therefore, O our God, hear the prayer and *_supplications_* of your servant and cause your face to shine upon your sanctuary that is desolate, for the Lord's sake.
* `Dan 9:18` O my God, incline your ear and hear. Open your eyes and behold our desolations and the city which is called by your name. For we do not present our *_supplications_* before you for our righteousnesses, but for your great mercies.
* `Dan 9:23` At the beginning of your *_supplications_* the commandment came forth, and I have come to show you, for you are greatly beloved. Therefore, understand the matter and consider the vision.
* `Zch 12:10` "And I will pour upon the house of David and upon the inhabitants of Jerusalem the Spirit of grace and of *_supplications_*. And they shall look upon me whom they have pierced, and they shall mourn for him as one mourns for his only son, and shall be in bitterness for him as one who is in bitterness for his first-born.
* `1Ti 2:1` I exhort therefore, that first of all, *_supplications_*, prayers, intercessions, and giving of thanks be made for all men,
* `1Ti 5:5` Now she who is a widow indeed and desolate trusts in God and continues in *_supplications_* and prayers night and day.
* `Heb 5:7` He, in the days of his flesh, when he had offered up prayers and *_supplications_* with strong crying and tears to him who was able to save him from death, was heard because of his reverence.

_22 verses containing SUPPLICATIONS_

== SUPPLIED

* `1Co 16:17` I am glad of the coming of Stephanas, Fortunatus, and Achaicus, for that which was lacking on your part, they have *_supplied_*,
* `2Co 11:9` And when I was present with you and was in need, I was chargeable to no man. For that which was lacking to me the brothers who came from Macedonia *_supplied_*. And in all things I have kept myself from being burdensome to you, and so I will keep myself.
* `Col 2:19` And not holding the head, from which all the body, being *_supplied_* and knit together by joints and ligaments, increases with the increase of God.

_3 verses containing SUPPLIED_

== SUPPLIES

* `2Co 9:10` Now may he who *_supplies_* "seed to the sower and bread for food," supply and multiply your seed for sowing and increase "the fruits of your righteousness,"
* `2Co 9:12` For the administration of this service not only *_supplies_* the needs of the saints, but is also abundant by many thanksgivings to God.
* `Eph 4:16` From whom the whole body properly joined together and united by that which every joint *_supplies_*, according to the effectual working in the measure of every part, makes increase of the body to the edifying of itself in love.

_3 verses containing SUPPLIES_

== SUPPLY

* `Nah 2:9` Take the plunder of silver and take the plunder of gold. There is no end to the *_supply_*. There is glory from all the desirable vessels.
* `2Co 8:14` But that there may be equality. Your abundance at this time may be a *_supply_* for their need so that their abundance may also be a *_supply_* for your need. This is so that there may be equality,
* `2Co 9:10` Now may he who supplies "seed to the sower and bread for food," *_supply_* and multiply your seed for sowing and increase "the fruits of your righteousness,"
* `Phl 1:19` For I know that "this will turn to my salvation" through your prayers and the *_supply_* of the Spirit of Jesus Christ,
* `Phl 2:30` Because for the work of Christ he was near to death, not regarding his life, to *_supply_* that which was lacking in your service toward me.
* `Phl 4:19` But my God will *_supply_* all your need according to his riches in glory by Christ Jesus.

_6 verses containing SUPPLY_

== SUPPORT

* `2Sa 22:19` They fell upon me in the day of my calamity, but the LORD was my *_support_*.
* `Psa 119:117` *_Support_* me, and I shall be safe and will have respect to your statutes continually.
* `Isa 3:1` For behold, the Lord, the LORD of hosts, takes away from Jerusalem and from Judah the rod and the staff, the whole *_support_* of bread, the whole *_support_* of water,
* `Isa 19:13` The princes of Zoan have become fools, the princes of Noph are deceived. They have also seduced Egypt, even those who are the *_support_* of its tribes.
* `Act 20:35` In all things I have shown you that in laboring this way you ought to *_support_* the weak and to remember the words of the Lord Jesus, that he said, 'It is more blessed to give than to receive.'"
* `1Th 5:14` Now we exhort you, brothers, warn those who are disorderly, comfort the feeble-minded, *_support_* the weak, and be patient toward all men.

_6 verses containing SUPPORT_

== SUPPORTED

* `Exo 17:12` But Moses's hands were heavy, and they took a stone and put it under him, and he sat upon it. And Aaron and Hur *_supported_* his hands, one on one side and the other on the other side. And his hands were steady until the going down of the sun.
* `Jdg 16:29` And Samson took hold of the two middle pillars upon which the house stood and on which it was *_supported_*, and laid hold of one with his right hand and the other with his left.
* `2Ch 18:34` And the battle increased that day. Nevertheless, the king of Israel *_supported_* himself in his chariot against the Syrians until the evening. And about the time of the sunset he died.
* `Ezk 41:6` And the side-chambers were three, one over another, and thirty in order, and there were ledges on the wall which belonged to the house for the side-chambers around, so that they might be *_supported_*, but not attached to the wall of the house.

_4 verses containing SUPPORTED_

== SUPPORTS

* `1Ki 7:30` And every base had four brazen wheels and plates of brass, and its four corners had *_supports_*. Under the basin were molten *_supports_*, with wreaths at the side of each.
* `1Ki 7:34` And there were four *_supports_* at the four corners of one base. And the *_supports_* were of one piece with the base itself.

_2 verses containing SUPPORTS_

== SUPPOSE

* `2Sa 13:32` And Jonadab, the son of Shimeah David's brother, answered and said, "Do not let my lord *_suppose_* that they have slain all the young men, the king's sons, for only Amnon is dead. For by the appointment of Absalom this has been determined from the day that he forced his sister Tamar.
* `Luk 7:43` Simon answered and said, "I *_suppose_* the one whom he forgave most." And he said to him, "You have rightly judged."
* `Luk 12:51` Do you *_suppose_* that I have come to give peace on earth? I tell you, no, but rather division.
* `Luk 13:2` And Jesus, answering, said to them, "Do you *_suppose_* that these Galileans were sinners above all the Galileans because they suffered such things?
* `Luk 17:9` Does he thank that servant because he did the things that were commanded of him? I *_suppose_* not.
* `Jhn 21:25` And there are also many other things which Jesus did, which, if they should all be written, I *_suppose_* that even the world itself could not contain the books that would be written. Amen.
* `Act 2:15` For these are not drunken, as you *_suppose_*, seeing it is but the third hour of the day.
* `1Co 7:26` I *_suppose_* therefore that this is good for the present distress, I say, that it is good for a man to be so.
* `2Co 11:5` For I *_suppose_* I was not at all inferior to the very greatest apostles.
* `Heb 10:29` How much more severe a punishment do you *_suppose_* he shall be thought worthy of who has trodden under foot the Son of God, has counted the blood of the covenant by which he was sanctified an unholy thing, and has done an indignity to the Spirit of grace?

_10 verses containing SUPPOSE_

== SUPPOSED

* `Mth 20:10` But when the first came, they *_supposed_* that they should receive more, and they likewise each received a denarius.
* `Mrk 6:49` But when they saw him walking upon the sea, they *_supposed_* it had been a spirit and cried out.
* `Luk 3:23` And Jesus himself began to be about thirty years of age, being (as was *_supposed_*) the son of Joseph, who was the son of Heli,
* `Luk 24:37` But they were terrified and frightened and *_supposed_* that they had seen a spirit.
* `Act 7:25` For he *_supposed_* his brothers to understand that God by his hand would deliver them, but they did not understand.
* `Act 21:29` For they had seen Trophimus, an Ephesian, with him before in the city, whom they *_supposed_* that Paul had brought into the temple.
* `Act 25:18` Against whom, when the accusers stood up, they brought no accusation of such things as I *_supposed_*,
* `Phl 2:25` Yet I *_supposed_* it necessary to send to you Epaphroditus, my brother, companion in labor, and fellow-soldier, but your messenger, and he who ministered to my needs.

_8 verses containing SUPPOSED_

== SUPPOSING

* `Luk 2:44` But they, *_supposing_* him to be in the company, went a day's journey, and they sought him among their relatives and acquaintances.
* `Jhn 20:15` Jesus says to her, "Woman, why do you weep? Whom do you seek?" She, *_supposing_* him to be the gardener, says to him, "Sir, if you have carried him from here, tell me where you have laid him and I will take him away."
* `Act 14:19` And some Jews from Antioch and Iconium came there, who persuaded the people. And having stoned Paul, they drew him out of the city *_supposing_* him to be dead.
* `Act 16:27` And the keeper of the prison, awaking out of his sleep and seeing the prison doors open, drew out his sword and was about to kill himself, *_supposing_* that the prisoners had fled.
* `Act 27:13` And when the south wind blew softly, *_supposing_* that they had obtained their purpose, they raised the anchor and sailed close by Crete.
* `Phl 1:16` The former preach Christ from contention, not sincerely, *_supposing_* to add affliction to my bonds,
* `1Ti 6:5` Perverse disputings of men of corrupt minds and destitute of the truth, *_supposing_* gain to be godliness. Withdraw yourself from such.

_7 verses containing SUPPOSING_

== SUPREME

* `1Pe 2:13` Submit yourselves to every ordinance of man for the Lord's sake, whether to the king as *_supreme_*,

_1 verse containing SUPREME_

