= VAGABOND - VEXED
:toc:

== VAGABOND

* `Gen 4:12` When you till the ground, it shall not from now on yield to you its strength. A fugitive and a *_vagabond_* you shall be in the earth."
* `Gen 4:14` Behold, you have driven me this day from the face of the earth, and from your face I shall be hid. And I shall be a fugitive and a *_vagabond_* in the earth. And it will come to pass, that everyone who finds me will slay me."
* `Act 19:13` Then some of the *_vagabond_* Jews, exorcists, took upon themselves to invoke the name of the Lord Jesus over those who had evil spirits, saying, "We adjure you by Jesus whom Paul preaches."

_3 verses containing VAGABOND_

== VAHEB

* `Num 21:14` Therefore, it is said in the Book of the Wars of the LORD, "At *_Vaheb_* in Suphah and in the brooks of Arnon,

_1 verse containing VAHEB_

== VAIN

* `Exo 5:9` Let more work be laid upon the men so that they may labor therein, and do not let them regard *_vain_* words."
* `Exo 20:7` "You shall not take the name of the LORD your God in *_vain_*, for the LORD will not hold him guiltless who takes his name in *_vain_*.
* `Lev 26:16` I also will do this to you: I will even appoint over you terror, consumption, and the fever that shall consume the eyes and cause sorrow of heart. And you shall sow your seed in *_vain_*, for your enemies shall eat it.
* `Lev 26:20` And your strength shall be spent in *_vain_*, for your land shall not yield her increase, neither shall the trees of the land yield their fruits.
* `Deu 5:11` 'You shall not take the name of the LORD your God in *_vain_*, for the LORD will not hold him guiltless who takes his name in *_vain_*.
* `Deu 32:47` For it is not a *_vain_* thing for you, because it is your life, and through this thing you shall prolong your days in the land where you go over the Jordan to possess it."
* `Jdg 9:4` And they gave him seventy pieces of silver out of the house of Baal-berith, with which Abimelech hired *_vain_* and light persons who followed him.
* `Jdg 11:3` Then Jephthah fled from his brothers and dwelt in the land of Tob. And *_vain_* men were gathered to Jephthah, and they went out with him.
* `1Sa 12:21` And do not turn aside, for then you would go after *_vain_* things which cannot profit nor deliver because they are *_vain_*.
* `1Sa 25:21` (Now David had said, "Surely in *_vain_* I have kept all that this man has in the wilderness so that nothing was missed of all that pertained to him, and he has requited me evil for good.
* `2Sa 6:20` Then David returned to bless his household. And Michal the daughter of Saul came out to meet David and said, "How glorious the king of Israel was today, who uncovered himself today in the eyes of his servants' women-servants, as one of the *_vain_* fellows shamelessly uncovers himself!"
* `2Ki 17:15` And they rejected his statutes, his covenant that he made with their fathers, and his testimonies which he testified against them, and they followed vanity, became *_vain_*, and went after the nations that were around them, concerning whom the LORD had charged them that they should not do like them.
* `2Ki 18:20` You say (but they are only *_vain_* words), 'I have counsel and strength for the war.' Now in whom do you trust that you rebel against me?
* `2Ch 13:7` And there are *_vain_* men gathered to him, the children of Belial, and they have strengthened themselves against Rehoboam the son of Solomon, when Rehoboam was young and tender-hearted and could not withstand them.
* `Job 9:29` If I am wicked, why then do I labor in *_vain_*?
* `Job 11:11` For he knows *_vain_* men. He sees wickedness also. Will he not then consider it?
* `Job 11:12` For *_vain_* man would be wise, though man is born like a wild donkey's colt.
* `Job 15:2` "Should a wise man utter *_vain_* knowledge and fill his belly with the east wind?
* `Job 16:3` Shall *_vain_* words have an end? Or what emboldens you that you answer?
* `Job 21:34` How then do you comfort me in *_vain_*, seeing in your answers there remains falsehood?"
* `Job 27:12` Behold, all of you have seen it yourselves. Why then are you thus altogether *_vain_*?
* `Job 35:16` Therefore, Job opens his mouth in *_vain_*. He multiplies words without knowledge."
* `Job 39:16` She is hardened against her young ones as though they were not hers. Her labor is in *_vain_* without fear,
* `Job 41:9` Behold, the hope of him is in *_vain_*. Shall one not be cast down even at the sight of him?
* `Psa 2:1` Why do the heathen rage and the people plot a *_vain_* thing?
* `Psa 26:4` I have not sat with *_vain_* persons, neither will I go in with dissemblers.
* `Psa 33:17` A horse is a *_vain_* thing for safety, neither shall he deliver any by his great strength.
* `Psa 39:6` "Surely every man walks in a *_vain_* show. Surely they are disquieted in *_vain_*. He heaps up riches and does not know who gathers them.
* `Psa 60:11` Give us help from trouble, for the help of man is *_vain_*.
* `Psa 62:10` Do not trust in oppression, and do not become *_vain_* in robbery. If riches increase, do not set your heart upon them.
* `Psa 73:13` Truly I have cleansed my heart in *_vain_* and washed my hands in innocence.
* `Psa 89:47` Remember how short my time is. Why have you made all men in *_vain_*?
* `Psa 108:12` Give us help from trouble, for *_vain_* is the help of man.
* `Psa 119:113` [SAMEKH] I hate *_vain_* thoughts, but I love your law.
* `Psa 127:1` [A Song of Degrees for Solomon.] Unless the LORD builds the house, they labor in *_vain_* who build it. Unless the LORD keeps the city, the watchman wakes in *_vain_*.
* `Psa 127:2` It is *_vain_* for you to rise early, to sit up late, to eat the bread of sorrows, for he gives his beloved sleep.
* `Psa 139:20` For they speak against you wickedly, and your enemies take your name in *_vain_*.
* `Pro 1:17` Surely in *_vain_* the net is spread in the sight of any bird.
* `Pro 12:11` He who tills his land shall be satisfied with bread, but he who follows *_vain_* persons is void of understanding.
* `Pro 28:19` He who tills his land shall have plenty of bread, but he who follows after *_vain_* persons shall be filled with poverty.
* `Pro 30:9` Lest I be full and deny you, and say, "Who is the LORD?" or lest I be poor and steal and take the name of my God in *_vain_*.
* `Pro 31:30` [SHIN] Favor is deceitful and beauty is *_vain_*, but a woman who fears the LORD shall be praised.
* `Ecc 6:12` For who knows what is good for man in this life, all the days of his *_vain_* life which he spends as a shadow? For who can tell a man what shall be after him under the sun?
* `Isa 1:13` Bring no more *_vain_* oblations. Incense is an abomination to me. The new moons and sabbaths, the calling of assemblies, I cannot endure. It is iniquity, even the solemn meeting.
* `Isa 30:7` For the Egyptian shall help in *_vain_* and to no purpose. Therefore, I have called her, "Rahab who sits still."
* `Isa 36:5` You say (but they are only *_vain_* words), 'I have counsel and strength for the war.' Now in whom do you trust that you rebel against me?
* `Isa 45:18` For thus says the LORD who created the heavens (God himself who formed the earth and made it, who has established it, who did not create it in *_vain_*, who formed it to be inhabited): "I am the LORD, and there is no one else.
* `Isa 45:19` I have not spoken in secret, in a dark place of the earth. I have not said to the offspring of Jacob, 'Seek me in *_vain_*.' I, the LORD, speak righteousness. I declare things that are right.
* `Isa 49:4` Then I said, "I have labored in *_vain_*. I have spent my strength for nothing and in *_vain_*. Yet surely my judgment is with the LORD and my work with my God."
* `Isa 65:23` They shall not labor in *_vain_*, nor bring forth for trouble, for they are a people blessed by the LORD, and their offspring with them.
* `Jer 2:5` Thus says the LORD: "What iniquity have your fathers found in me that they have gone far from me and have walked after vanity and have become *_vain_*?
* `Jer 2:30` "In *_vain_* I have smitten your children. They have received no correction. Your own sword has devoured your prophets like a destroying lion.
* `Jer 3:23` Truly in *_vain_* is salvation hoped for from the hills and from the multitude of mountains. Truly the salvation of Israel is in the LORD our God.
* `Jer 4:14` O Jerusalem, wash your heart from wickedness so that you may be saved. How long shall your *_vain_* thoughts lodge within you?
* `Jer 4:30` And when you are laid waste, what will you do? Though you clothe yourself with crimson, though you deck yourself with ornaments of gold, though you rend your face with painting, in *_vain_* you shall make yourself fair. Your lovers will despise you. They will seek your life.
* `Jer 6:29` The bellows is burned. The lead is consumed by the fire. The founder melts in *_vain_*, for the wicked are not plucked away.
* `Jer 8:8` How do you say, 'We are wise, and the law of the LORD is with us'? Behold, certainly in *_vain_* he has made it. The pen of the scribes is in *_vain_*.
* `Jer 10:3` For the customs of the people are *_vain_*. For one cuts a tree out of the forest, the work of the hands of the workman, with the ax.
* `Jer 23:16` Thus says the LORD of hosts: "Do not listen to the words of the prophets who prophesy to you. They make you *_vain_*. They speak a vision of their own heart and not from the mouth of the LORD.
* `Jer 46:11` Go up into Gilead and take balm, O virgin, the daughter of Egypt. In *_vain_* you shall use many medicines, for you shall not be cured.
* `Jer 50:9` For behold, I will raise and cause to come against Babylon an assembly of great nations from the north country. And they shall set themselves in array against her. From there she shall be taken. Their arrows shall be like those of an expert warrior. None shall return in *_vain_*.
* `Jer 51:58` Thus says the LORD of hosts: "The broad walls of Babylon shall be utterly broken, and her high gates shall be burned with fire. The people shall labor in *_vain_*, and the nations for the fire, and they shall be weary."
* `Lam 2:14` [NUN] Your prophets have seen *_vain_* and foolish things for you. And they have not revealed your iniquity to turn away your captivity, but have seen for you false burdens and causes of banishment.
* `Lam 4:17` [PE] As for us, our eyes still fail, looking in *_vain_* for our help. In our watching we have watched for a nation that could not save us.
* `Ezk 6:10` And they shall know that I am the LORD, and that I have not said in *_vain_* that I would do this evil to them."'
* `Ezk 12:24` For there shall no longer be any *_vain_* vision nor flattering divination within the house of Israel.
* `Ezk 13:7` Have you not seen a *_vain_* vision, and have you not spoken a lying divination when you say, 'The LORD says it,' even though I have not spoken?"'"
* `Zch 10:2` For the idols have spoken vanity, and the diviners have seen a lie. They have told false dreams. They comfort in *_vain_*. Therefore, they went their way as a flock. They were troubled because there was no shepherd.
* `Mal 1:10` "Oh that there were one of you who would shut the doors so that you would not kindle fire on my altar in *_vain_*! I have no pleasure in you," says the LORD of hosts, "neither will I accept an offering at your hand.
* `Mal 3:14` You have said, 'It is *_vain_* to serve God. And what profit is it that we have kept his ordinance and that we have walked mournfully before the LORD of hosts?
* `Mth 6:7` "But when you pray, do not use *_vain_* repetitions, as the heathen do, for they think that they shall be heard for their excessive speaking.
* `Mth 15:9` But they worship me in *_vain_*, teaching the commandments of men for doctrines.'"
* `Mrk 7:7` But in *_vain_* they worship me, teaching the commandments of men for doctrines.'
* `Act 4:25` Who, by the mouth of your servant David, said, 'Why did the heathen rage, and the people plot *_vain_* things?
* `Rom 1:21` For when they knew God, they did not glorify him as God, neither were thankful, but they became *_vain_* in their imaginations and their foolish hearts were darkened.
* `Rom 13:4` For he is the minister of God to you for good. But if you do that which is evil, be afraid, for he does not bear the sword in *_vain_*, for he is the minister of God, an avenger to execute wrath upon him who does evil.
* `1Co 3:20` And again, "The Lord knows the thoughts of the wise, that they are *_vain_*."
* `1Co 15:2` By which you are also saved, if you keep in memory what I preached to you, unless you have believed in *_vain_*.
* `1Co 15:10` But by the grace of God I am what I am, and his grace which was bestowed upon me was not in *_vain_*. But I labored more abundantly than all of them—yet not I, but the grace of God which was with me.
* `1Co 15:14` And if Christ has not been raised, then our preaching is *_vain_* and your faith is also *_vain_*.
* `1Co 15:17` And if Christ has not been raised, your faith is *_vain_*. You are still in your sins.
* `1Co 15:58` Therefore, my beloved brothers, be steadfast, immovable, always abounding in the work of the Lord, because you know that your labor is not in *_vain_* in the Lord.
* `2Co 6:1` And working together [with him], we entreat also that you do not receive the grace of God in *_vain_*.
* `2Co 9:3` Yet I have sent the brothers, lest our boasting about you should be in *_vain_* in this matter, so that, as I said, you may be ready,
* `Gal 2:2` And I went by revelation and communicated to them that gospel which I preach among the Gentiles, but privately to those who were of reputation, lest by any means I might be running, or had run, in *_vain_*.
* `Gal 2:21` I do not frustrate the grace of God. For if righteousness is attainable by the law, then Christ has died in *_vain_*."
* `Gal 3:4` Have you suffered so many things in *_vain_*—if it is indeed in *_vain_*?
* `Gal 4:11` I am afraid for you, lest I have bestowed upon you labor in *_vain_*.
* `Gal 5:26` Let us not be desirous of *_vain_*-glory, provoking one another, envying one another.
* `Eph 5:6` Let no man deceive you with *_vain_* words, for because of these things the wrath of God comes upon the children of disobedience.
* `Phl 2:3` Let nothing be done through strife or *_vain_* glory. But in lowliness of mind, let each esteem the other better than themselves—
* `Phl 2:16` Holding forth the word of life, so that I may rejoice in the day of Christ, that I have not run in *_vain_*, neither labored in *_vain_*.
* `Col 2:8` Beware lest any man make a prey of you through philosophy and *_vain_* deceit, after the tradition of men, after the rudiments of the world, and not after Christ.
* `1Th 2:1` For you yourselves, brothers, know our entering in to you, that it was not in *_vain_*.
* `1Th 3:5` For this cause, when I could no longer forbear, I sent to know your faith, lest by some means the tempter may have tempted you and our labor be in *_vain_*.
* `1Ti 1:6` From which some, having swerved, have turned aside to *_vain_* jangling,
* `1Ti 6:20` O Timothy, keep that which is committed to your trust, avoiding profane and *_vain_* babblings and oppositions of what is falsely called knowledge,
* `2Ti 2:16` But shun profane and *_vain_* babblings, for they will increase to more ungodliness.
* `Tit 1:10` For there are many disorderly and *_vain_* talkers and deceivers, especially those of the circumcision.
* `Tit 3:9` But avoid foolish questions, genealogies, contentions, and strivings about the law, for they are unprofitable and *_vain_*.
* `Jms 1:26` If any man among you seems to be religious and does not bridle his tongue, but deceives his own heart, this man's religion is *_vain_*.
* `Jms 2:20` But will you know, O *_vain_* man, that faith without works is dead?
* `Jms 4:5` Do you think that the Scripture says in *_vain_*, "The spirit which dwells in us earnestly desires to envy"?
* `1Pe 1:18` For you know that you were not redeemed with corruptible things, as silver and gold, from your *_vain_* course of life received by tradition from your fathers,

_104 verses containing VAIN_

== VAIN-GLORY

* `Gal 5:26` Let us not be desirous of *_vain-glory_*, provoking one another, envying one another.

_1 verse containing VAIN-GLORY_

== VAINLY

* `Col 2:18` Let no man beguile you of your reward in a voluntary humility and worshiping of angels, intruding into those things which he has not seen, *_vainly_* puffed up by his fleshly mind,

_1 verse containing VAINLY_

== VAJEZATHA

* `Est 9:9` Parmashta, Arisai, Aridai, and *_Vajezatha_*,

_1 verse containing VAJEZATHA_

== VALIANT

* `Jdg 21:10` And the congregation sent there twelve thousand men of the most *_valiant_*, and commanded them, saying, "Go and smite the inhabitants of Jabesh-gilead with the edge of the sword, along with the women and the children.
* `1Sa 14:52` And there was violent war against the Philistines all the days of Saul. And when Saul saw any strong man or any *_valiant_* man, he took him into his service.
* `1Sa 16:18` Then one of the servants answered and said, "Behold, I have seen a son of Jesse the Beth-lehemite who is skillful in playing, a mighty *_valiant_* man, a man of war, prudent in matters, and a handsome person, and the LORD is with him."
* `1Sa 18:17` And Saul said to David, "Behold, my elder daughter Merab, I will give her to you for a wife. Only be *_valiant_* for me and fight the LORD'S battles." For Saul thought, "Do not let my hand be upon him, but let the hand of the Philistines be upon him."
* `1Sa 26:15` And David said to Abner, "Are you not a *_valiant_* man? And who is like you in Israel? Why then have you not kept your lord the king? For there came in one of the people to destroy the king your lord.
* `1Sa 31:12` All the *_valiant_* men arose and went all night, took the body of Saul and the bodies of his sons from the wall of Beth-shan, and came to Jabesh and burnt them there.
* `2Sa 2:7` And now, let your hands be strengthened, and be *_valiant_*, for your master Saul is dead, and also the house of Judah has anointed me king over them."
* `2Sa 11:16` And it came to pass, when Joab observed the city, that he assigned Uriah to a place where he knew that *_valiant_* men were.
* `2Sa 13:28` Now Absalom had commanded his servants, saying, "Now mark when Amnon's heart is merry with wine, and when I say to you, 'Smite Amnon,' then kill him. Do not fear. Have I not commanded you? Be courageous and be *_valiant_*."
* `2Sa 17:10` And he also who is *_valiant_*, whose heart is as the heart of a lion, will utterly melt, for all Israel knows that your father is a mighty man, and those who are with him are *_valiant_* men.
* `2Sa 23:20` And Benaiah the son of Jehoiada, the son of a *_valiant_* man, of Kabzeel, who had done many acts, he slew two lion-like men of Moab. He went down also and slew a lion in the midst of a pit in time of snow.
* `2Sa 24:9` And Joab presented the sum of the number of the people to the king. And there were in Israel eight hundred thousand *_valiant_* men who drew the sword, and the men of Judah were five hundred thousand men.
* `1Ki 1:42` And while he still spoke, behold, Jonathan the son of Abiathar the priest came. And Adonijah said to him, "Come in, for you are a *_valiant_* man and bring good tidings."
* `1Ch 5:18` The sons of Reuben, the Gadites, and half the tribe of Manasseh, all who were *_valiant_* men—men able to bear buckler and sword, to shoot with bow, and skillful in war—forty-four thousand seven hundred and sixty who were able to go forth to war.
* `1Ch 7:2` And the sons of Tola: Uzzi, Rephaiah, Jeriel, Jahmai, Jibsam, and Shemuel, heads of their father's house, namely, of Tola. They were *_valiant_* men of might in their generations whose number was in the days of David twenty-two thousand and six hundred.
* `1Ch 7:5` And their brothers among all the families of Issachar were *_valiant_* men of might, reckoned in all by their genealogies eighty-seven thousand.
* `1Ch 10:12` They arose—all the *_valiant_* men—and took away the body of Saul and the bodies of his sons, brought them to Jabesh, buried their bones under the oak in Jabesh, and fasted seven days.
* `1Ch 11:22` Benaiah the son of Jehoiada, the son of a *_valiant_* man of Kabzeel, who had done many acts, he slew two lion-like men of Moab. Also, he went down and slew a lion in a pit on a snowy day.
* `1Ch 11:26` Also the *_valiant_* men of the armies were Asahel the brother of Joab, Elhanan the son of Dodo of Beth-lehem,
* `1Ch 28:1` And David assembled all the princes of Israel, the princes of the tribes, the captains of the companies that ministered to the king by course, the captains over the thousands, captains over the hundreds, and the stewards over all the substance and possession of the king and of his sons, with the officers, with the mighty men, and with all the *_valiant_* men at Jerusalem.
* `2Ch 13:3` And Abijah set the battle in array with an army of *_valiant_* men of war, even four hundred thousand chosen men. Jeroboam also set the battle in array against him with eight hundred thousand chosen men, being mighty men of valor.
* `2Ch 26:17` And Azariah the priest went in after him, and with him eighty priests of the LORD who were *_valiant_* men.
* `2Ch 28:6` For Pekah the son of Remaliah slew in Judah one hundred and twenty thousand in one day, who were all *_valiant_* men, because they had forsaken the LORD God of their fathers.
* `Neh 11:6` All the sons of Perez who dwelt at Jerusalem were four hundred and sixty-eight *_valiant_* men.
* `Sos 3:7` Behold his bed, which is Solomon's. Sixty *_valiant_* men are around it, of the *_valiant_* of Israel.
* `Isa 10:13` For he says, "By the strength of my hand I have done it, and by my wisdom, for I am prudent. And I have removed the bounds of the people and have robbed their treasures, and I have put down the inhabitants like a *_valiant_* man.
* `Isa 33:7` Behold, their *_valiant_* ones shall cry outside. The ambassadors of peace shall weep bitterly.
* `Jer 9:3` "And they bend their tongues like their bow for lies, but they are not *_valiant_* for the truth upon the earth, for they proceed from evil to evil and they do not know me," says the LORD.
* `Jer 46:15` Why are your *_valiant_* men swept away? They did not stand because the LORD drove them.
* `Nah 2:3` The shield of his mighty men is made red. The *_valiant_* men are in scarlet. The chariots shall be with flaming torches in the day of his preparation, and the fir-trees shall be terribly shaken.
* `Heb 11:34` Quenched the violence of fire, escaped the edge of the sword, out of weakness were made strong, became *_valiant_* in fight, and turned to flight the armies of the foreigners.

_31 verses containing VALIANT_

== VALIANTLY

* `Num 24:18` And Edom shall be a possession, Seir also shall be a possession for his enemies. And Israel shall do *_valiantly_*.
* `1Ch 19:13` Be of good courage, and let us behave ourselves *_valiantly_* for our people and for the cities of our God. And let the LORD do that which is good in his sight."
* `Psa 60:12` Through God we shall do *_valiantly_*, for he will tread down our enemies.
* `Psa 108:13` Through God we shall do *_valiantly_*, for he will tread down our enemies.
* `Psa 118:15` The voice of rejoicing and salvation is in the tabernacles of the righteous. The right hand of the LORD does *_valiantly_*.
* `Psa 118:16` The right hand of the LORD is exalted. The right hand of the LORD does *_valiantly_*.

_6 verses containing VALIANTLY_

== VALLEY

* `Gen 14:3` All these were joined together in the *_valley_* of Siddim, which is the Salt Sea.
* `Gen 14:8` And the king of Sodom, the king of Gomorrah, the king of Admah, the king of Zeboiim, and the king of Bela (the same is Zoar) went out, and they joined battle with them in the *_valley_* of Siddim,
* `Gen 14:10` And the *_valley_* of Siddim was full of slime-pits. And the kings of Sodom and Gomorrah fled and fell there. And those who remained fled to the mountain.
* `Gen 14:17` And the king of Sodom went out to meet him after his return from the slaughter of Chedorlaomer, and of the kings who were with him, at the *_valley_* of Shaveh, which is the king's dale.
* `Gen 26:17` And Isaac departed from there and pitched his tent in the *_valley_* of Gerar and dwelt there.
* `Gen 26:19` And Isaac's servants dug in the *_valley_* and found there a well of springing water.
* `Gen 37:14` And he said to him, "Go, I pray you, see whether it is well with your brothers and well with the flocks, and bring word back to me." So he sent him from the *_valley_* of Hebron, and he came to Shechem.
* `Num 14:25` (Now the Amalekites and the Canaanites dwelt in the *_valley_*.) Tomorrow turn and pass into the wilderness by the way of the Red Sea."
* `Num 21:12` From there they departed and pitched in the *_valley_* of Zared.
* `Num 21:20` And from Bamoth in the *_valley_*, which is in the country of Moab, to the top of Pisgah, which looks toward Jeshimon.
* `Num 32:9` For when they went up to the *_valley_* of Eshcol and saw the land, they discouraged the heart of the children of Israel so that they should not go into the land which the LORD had given them.
* `Deu 1:7` Turn, and take your journey, and go to the mountain of the Amorites and to all the places near it in the plain, on the hills, in the *_valley_*, in the south, and along the sea-side to the land of the Canaanites and to Lebanon, as far as the great river, the Euphrates River.
* `Deu 1:24` And they turned and ascended the mountain and came to the *_valley_* of Eshcol and explored it.
* `Deu 3:16` And to the Reubenites and to the Gadites I gave from Gilead even to the Arnon River, to the middle of the *_valley_* for a border, even to the Jabbok River, which is the border of the children of Ammon,
* `Deu 3:29` So we stayed in the *_valley_* over against Beth-peor."
* `Deu 4:46` On the east side of the Jordan, in the *_valley_* over against Beth-Peor, in the land of Sihon king of the Amorites, who dwelt at Heshbon, whom Moses and the children of Israel smote after they had come forth from Egypt.
* `Deu 21:4` And the elders of that city shall bring the heifer down to a rough *_valley_*, which is neither tilled nor sown, and shall strike off the heifer's neck there in the *_valley_*.
* `Deu 21:6` And all the elders of that city who are next to the slain man shall wash their hands over the heifer that is beheaded in the *_valley_*.
* `Deu 34:3` The south, and the plain of the *_valley_* of Jericho, the city of palm-trees, to Zoar.
* `Deu 34:6` And he buried him in a *_valley_* in the land of Moab, over against Beth-peor. But no man knows of his sepulcher to this day.
* `Jsh 7:24` And Joshua, and all Israel with him, took Achan the son of Zerah, the silver, the garment, the wedge of gold, his sons, his daughters, his oxen, his donkeys, his sheep, his tent, and all that he had. And they brought them to the *_valley_* of Achor.
* `Jsh 7:26` And they raised over him a great heap of stones to this day. So the LORD turned from the fierceness of his anger. Therefore, the name of that place was called the *_Valley_* of Achor to this day.
* `Jsh 8:11` And all the people, even the people of war who were with him, went up, drew near, came before the city, and pitched on the north side of Ai. Now there was a *_valley_* between them and Ai.
* `Jsh 8:13` So they set the people with all the host to the north of the city and their ambush to the west of the city. And Joshua went that night into the midst of the *_valley_*.
* `Jsh 10:12` Then Joshua spoke to the LORD in the day when the LORD delivered up the Amorites before the children of Israel, and he said in the sight of Israel, "Sun, stand still upon Gibeon, and you, Moon, in the *_valley_* of Ajalon."
* `Jsh 10:40` So Joshua smote all the country of the hills, of the south, of the *_valley_*, and of the springs, and all their kings. He left no one remaining, but utterly destroyed all that breathed, as the LORD God of Israel commanded.
* `Jsh 11:2` And to the kings who were on the north of the mountains, of the plains south of Cinneroth, in the *_valley_*, and in the borders of Dor on the west,
* `Jsh 11:8` And the LORD delivered them into the hand of Israel, who smote them and chased them to great Zidon, to Misrephoth-maim, and to the *_valley_* of Mizpeh eastward. And they smote them until they left to them no one remaining.
* `Jsh 11:16` So Joshua took all that land, the hills, all the south country, all the land of Goshen, the *_valley_*, the plain, the mountain of Israel, and the *_valley_* of the same,
* `Jsh 11:17` Even from the mount Halak that goes up to Seir, even to Baal-gad in the *_valley_* of Lebanon under mount Hermon. And all their kings he took, smote them, and slew them.
* `Jsh 12:7` And these are the kings of the country whom Joshua and the children of Israel smote on this side of the Jordan on the west, from Baal-gad in the *_valley_* of Lebanon, even to the mount Halak that goes up to Seir—which Joshua gave to the tribes of Israel for a possession according to their divisions,
* `Jsh 13:19` Kirjathaim, Sibmah, Zareth-shahar on the mountain of the *_valley_*,
* `Jsh 13:27` And in the *_valley_*, Beth-aram, Beth-nimrah, Succoth, and Zaphon, the rest of the kingdom of Sihon king of Heshbon, the Jordan and its border, even to the edge of the sea of Cinneroth, on the other side of the Jordan eastward.
* `Jsh 15:7` And the border went up toward Debir from the *_valley_* of Achor, and so northward looking toward Gilgal, that is before the going up to Adummim, which is on the south side of the river. And the border passed toward the waters of En-shemesh, and its borders were at En-rogel.
* `Jsh 15:8` And the border went up by the *_valley_* of the son of Hinnom, to the south side of the Jebusite (the same is Jerusalem). And the border went up to the top of the mountain that lies before the *_valley_* of Hinnom westward, which is at the end of the *_valley_* of Rephaim northward.
* `Jsh 15:33` And in the *_valley_*, Eshtaol, Zoreah, Ashnah,
* `Jsh 17:16` And the children of Joseph said, "The hill is not enough for us. And all the Canaanites who dwell in the land of the *_valley_* have chariots of iron—both those who are of Beth-shean and its towns, and those who are of the *_valley_* of Jezreel."
* `Jsh 18:16` And the border came down to the end of the mountain that lies before the *_valley_* of the son of Hinnom, which is in the *_valley_* of Rephaim on the north, and descended to the *_valley_* of Hinnom, to the side of Jebusi on the south, and descended to En-rogel,
* `Jsh 18:21` Now the cities of the tribe of the children of Benjamin, according to their families, were Jericho, Beth-hoglah, the *_valley_* of Keziz,
* `Jsh 19:14` And the border compasses it on the north side to Hannathon; and its limits are in the *_valley_* of Jiphthah-el;
* `Jsh 19:27` And turns toward the sunrise to Beth-dagon, and reaches to Zebulun, and to the *_valley_* of Jiphthah-el toward the north side of Beth-emek, and Neiel, and goes out to Cabul on the left hand,
* `Jdg 1:9` And afterward, the children of Judah went down to fight against the Canaanites who dwelt on the mountain, in the south, and in the *_valley_*.
* `Jdg 1:19` And the LORD was with Judah, and he drove out the inhabitants of the mountain, but could not drive out the inhabitants of the *_valley_*, because they had chariots of iron.
* `Jdg 1:34` And the Amorites forced the children of Dan to the mountain, for they would not allow them to come down to the *_valley_*.
* `Jdg 5:15` And the princes of Issachar were with Deborah, even Issachar, and also Barak. He was sent on foot into the *_valley_*. For the divisions of Reuben there were great thoughts of heart.
* `Jdg 6:33` Then all the Midianites, the Amalekites, and the children of the east were assembled and went over and encamped in the *_valley_* of Jezreel.
* `Jdg 7:1` Then Jerubbaal (who is Gideon) and all the people who were with him rose early and encamped beside the well of Harod. And the host of the Midianites were on the north side of them in the *_valley_* by the hill of Moreh.
* `Jdg 7:8` So the people took provisions in their hand and their trumpets. And he sent all the rest of Israel each to his tent and retained those three hundred men. And the host of Midian was beneath him in the *_valley_*.
* `Jdg 7:12` And the Midianites, the Amalekites, and all the children of the east lay along in the *_valley_* like swarming-locusts for multitude. And their camels were without number, as the sand by the sea side for multitude.
* `Jdg 16:4` And it came to pass afterward, that he loved a woman in the *_valley_* of Sorek, whose name was Delilah.
* `Jdg 18:28` And there was no deliverer because it was far from Zidon and they had no business with any man. And it was in the *_valley_* that lies by Beth-rehob. And they built a city and dwelt in it.
* `1Sa 6:13` And the people of Beth-shemesh were reaping their wheat harvest in the *_valley_*. And they lifted up their eyes, saw the ark, and rejoiced to see it.
* `1Sa 13:18` Another company turned the way to Beth-horon, and another company turned to the way of the border that looks to the *_valley_* of Zeboim toward the wilderness.
* `1Sa 15:5` And Saul came to a city of Amalek and laid wait in the *_valley_*.
* `1Sa 17:2` And Saul and the men of Israel were assembled and encamped by the *_valley_* of Elah, and they set the battle in array against the Philistines.
* `1Sa 17:3` And the Philistines stood on a mountain on one side, and Israel stood on a mountain on the other side, and there was a *_valley_* between them.
* `1Sa 17:19` Now Saul, and they, and all the men of Israel, were in the *_valley_* of Elah fighting with the Philistines.
* `1Sa 17:52` And the men of Israel and of Judah arose, shouted, and pursued the Philistines to the entrance of the *_valley_* and to the gates of Ekron. And the wounded of the Philistines fell down by the way to Shaaraim, even to Gath and to Ekron.
* `1Sa 21:9` And the priest said, "The sword of Goliath the Philistine, whom you slew in the *_valley_* of Elah, behold, it is here wrapped in a cloth behind the ephod. If you will take that, take it, for there is no other except that here." And David said, "There is none like that. Give it to me."
* `1Sa 31:7` And when the men of Israel who were on the other side of the *_valley_* and those who were on the other side of the Jordan saw that the men of Israel fled and that Saul and his sons were dead, they forsook the cities and fled. And the Philistines came and dwelt in them.
* `2Sa 5:18` The Philistines also came and spread themselves in the *_valley_* of Rephaim.
* `2Sa 5:22` And the Philistines came yet again and spread themselves in the *_valley_* of Rephaim.
* `2Sa 8:13` And David made himself a name when he returned from smiting the Syrians in the *_Valley_* of Salt, even eighteen thousand men.
* `2Sa 18:18` Now Absalom in his life-time had taken and raised for himself a pillar, which is in the king's *_valley_*, for he said, "I have no son to keep my name in remembrance." And he called the pillar after his own name, and it is called to this day, Absalom's Place.
* `2Sa 23:13` And three of the thirty chiefs went down and came to David in the harvest time to the cave of Adullam, and the troop of the Philistines encamped in the *_valley_* of Rephaim.
* `1Ki 10:27` And the king made silver to be in Jerusalem as stones, and cedars he made to be as abundant as the sycamore trees that are in the *_valley_*.
* `2Ki 2:16` And they said to him, "Behold now, there are with your servants fifty strong men. Let them go, we pray you, and seek your master, lest perhaps the Spirit of the LORD has taken him up and cast him upon some mountain or into some *_valley_*." And he said, "You shall not send."
* `2Ki 3:16` And he said, "Thus says the LORD: 'Make this *_valley_* full of ditches.'
* `2Ki 3:17` For thus says the LORD: 'You shall not see wind, neither shall you see rain, yet that *_valley_* shall be filled with water so that you may drink—you, your livestock, and your beasts.
* `2Ki 14:7` He slew ten thousand of Edom in the *_valley_* of Salt and took Selah by war and called its name Joktheel to this day.
* `2Ki 23:10` And he defiled Topheth, which is in the *_valley_* of the children of Hinnom, so that no man might make his son or his daughter to pass through the fire to Molech.
* `1Ch 4:14` Meonothai who begot Ophrah, and Seraiah who begot Joab, the father of the *_valley_* of Charashim, for they were craftsmen.
* `1Ch 4:39` And they went to the entrance of Gedor, even to the east side of the *_valley_*, to seek pasture for their flocks.
* `1Ch 10:7` And when all the men of Israel who were in the *_valley_* saw that they fled and that Saul and his sons were dead, they forsook their cities and fled. And the Philistines came and dwelt in them.
* `1Ch 11:15` Now three of the thirty captains went down to David, to the rock at the cave of Adullam, and the host of the Philistines encamped in the *_valley_* of Rephaim.
* `1Ch 14:9` And the Philistines came and spread themselves in the *_valley_* of Rephaim.
* `1Ch 14:13` And the Philistines yet again spread themselves abroad in the *_valley_*.
* `1Ch 18:12` Moreover, Abishai the son of Zeruiah slew of the Edomites in the *_valley_* of salt eighteen thousand.
* `2Ch 1:15` And the king made silver and gold at Jerusalem as plenteous as stones, and cedar trees he made as the sycamore trees that are in the *_valley_* for abundance.
* `2Ch 14:10` Then Asa went out against him, and they set the battle in array in the *_valley_* of Zephathath at Mareshah.
* `2Ch 20:26` And on the fourth day they assembled themselves in the *_valley_* of Berachah, for there they blessed the LORD. Therefore, the name of the same place has been called The *_Valley_* of Berachah to this day.
* `2Ch 25:11` And Amaziah strengthened himself, led forth his people, went to the *_valley_* of salt, and smote ten thousand of the children of Seir.
* `2Ch 26:9` Moreover, Uzziah built towers in Jerusalem at the corner gate, at the *_valley_* gate, and at the turning of the wall, and fortified them.
* `2Ch 28:3` Moreover, he burnt incense in the *_valley_* of the son of Hinnom and burnt his children in the fire, after the abominations of the heathen whom the LORD had cast out before the children of Israel.
* `2Ch 33:6` And he caused his children to pass through the fire in the *_valley_* of the son of Hinnom. He also observed times, used enchantments, used witchcraft, and dealt with a familiar spirit and with wizards. He wrought much evil in the sight of the LORD to provoke him to anger.
* `2Ch 33:14` Now after this, he built a wall outside the city of David on the west side of Gihon, in the *_valley_*, even to the entrance at the fish-gate, and he encircled Ophel with it and raised it up a very great height. And he put captains of war in all the fortified cities of Judah.
* `2Ch 35:22` Nevertheless, Josiah would not turn his face from him, but disguised himself that he might fight with him, and did not listen to the words of Necho from the mouth of God and came to fight in the *_valley_* of Megiddo.
* `Neh 2:13` And I went out by night by the gate of the *_valley_*, even before the dragon-well and to the dung-port, and viewed the walls of Jerusalem, which were broken down and their gates were consumed with fire.
* `Neh 2:15` Then I went up in the night by the brook, viewed the wall, turned back, and entered by the gate of the *_valley_*, and so returned.
* `Neh 3:13` The *_valley_*-gate was repaired by Hanun and the inhabitants of Zanoah. They built it, set up its doors, its locks, and its bars, and one thousand cubits on the wall to the dung-gate.
* `Neh 11:30` Zanoah, Adullam, and in their villages, at Lachish and its fields, and at Azekah and in its villages. And they dwelt from Beer-sheba to the *_valley_* of Hinnom.
* `Neh 11:35` Lod, and Ono, the *_valley_* of craftsmen.
* `Job 21:33` The clods of the *_valley_* will be sweet to him, and every man will draw after him, as there are innumerable before him.
* `Job 39:21` He paws in the *_valley_* and rejoices in his strength. He goes on to meet the armed men.
* `Psa 23:4` Even though I walk through the *_valley_* of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.
* `Psa 60:1` [To the Chief Musician upon Shushan-eduth. Michtam of David for Teaching: when he strove with Aram-naharaim and with Aram-zobah, when Joab returned and smote twelve thousand of Edom in the *_valley_* of salt.] O God, you have cast us off. You have scattered us. You have been displeased. O turn yourself to us again.
* `Psa 60:6` God has spoken in his holiness, "I will rejoice. I will divide Shechem and measure out the *_valley_* of Succoth.
* `Psa 84:6` Passing through the *_valley_* of Baca they make it a well. The rain also fills the pools.
* `Psa 108:7` God has spoken in his holiness: "I will rejoice. I will divide Shechem and measure out the *_valley_* of Succoth.
* `Pro 30:17` The eye that mocks at its father and despises to obey its mother, the ravens of the *_valley_* shall pick it out, and the young eagles shall eat it.
* `Sos 6:11` [Lady:] I went down into the garden of nuts to see the fruits of the *_valley_*, and to see whether the vine flourished and the pomegranates budded.
* `Isa 17:5` And it shall be as when the harvester gathers the grain and reaps the heads with his arm. And it shall be as he who gathers heads [of grain] in the *_valley_* of Rephaim.
* `Isa 22:1` [The burden of the *_valley_* of vision.] What ails you now, that you have wholly gone up to the house-tops?
* `Isa 22:5` For the Lord GOD of hosts has set a day of trouble, treading down, and perplexity in the *_valley_* of vision, of breaking down the walls and crying to the mountains.
* `Isa 28:4` And the glorious beauty, which is on the head of the rich *_valley_*, shall be a fading flower and as the early fruit before the summer, which he who looks upon it sees, and while it is still in his hand he eats it up.
* `Isa 28:21` For the LORD will rise as on mount Perazim, he will be angry as in the *_valley_* of Gibeon, so that he may do his work, his strange work, and bring to pass his act, his strange act.
* `Isa 40:4` Every *_valley_* shall be exalted, every mountain and hill shall be made low, the crooked shall be made straight, and the rough places plain.
* `Isa 63:14` Like the livestock that go down in the *_valley_*, the Spirit of the LORD caused him to rest. Thus you led your people to make yourself a glorious name.
* `Isa 65:10` And Sharon shall be a fold of flocks, and the *_valley_* of Achor a place for the herds to lie down in, for my people who have sought me.
* `Jer 2:23` "How can you say, 'I am not polluted. I have not gone after Baalim'? See your way in the *_valley_*. Know what you have done. You are a swift dromedary traversing her ways.
* `Jer 7:31` And they have built the high places of Tophet, which is in the *_valley_* of the son of Hinnom, to burn their sons and their daughters in the fire, which I did not command them, neither did it come into my heart.
* `Jer 7:32` "Therefore, behold, the days come," says the LORD, "that it shall no longer be called Tophet, nor the *_valley_* of the son of Hinnom, but the *_valley_* of slaughter, for they shall bury in Tophet until there is no place.
* `Jer 19:2` And go forth to the *_valley_* of the son of Hinnom, which is by the entry of the east gate, and proclaim there the words that I shall tell you,
* `Jer 19:6` Therefore, behold, the days come," says the LORD, "that this place shall no longer be called Tophet, nor The *_Valley_* of the Son of Hinnom, but The *_Valley_* of Slaughter.
* `Jer 21:13` Behold, I am against you, O inhabitant of the *_valley_* and rock of the plain," says the LORD, "who say, 'Who shall come down against us? Or who shall enter into our habitations?'
* `Jer 31:40` And the whole *_valley_* of the dead bodies and of the ashes, and all the fields to the brook of Kidron, to the corner of the horse-gate toward the east, shall be holy to the LORD. It shall not be plucked up nor thrown down anymore forever."
* `Jer 32:35` And they built the high places of Baal which are in the *_valley_* of the son of Hinnom to cause their sons and their daughters to pass through the fire to Molech, which I did not command them, neither did it come into my mind, that they should do this abomination to cause Judah to sin.
* `Jer 32:44` Men shall buy fields for money, sign evidences and seal them, and take witnesses in the land of Benjamin, in the places around Jerusalem, in the cities of Judah, in the cities of the mountains, in the cities of the *_valley_*, and in the cities of the south, for I will cause their captivity to return,' says the LORD."
* `Jer 33:13` In the cities of the mountains, in the cities of the *_valley_*, in the cities of the south, in the land of Benjamin, in the places around Jerusalem, and in the cities of Judah, the flocks shall pass again under the hands of him who counts them,' says the LORD.
* `Jer 47:5` Baldness has come upon Gaza. Ashkelon is cut off with the remnant of their *_valley_*. How long will you cut yourself?
* `Jer 48:8` And the destroyer shall come upon every city, and no city shall escape. The *_valley_* shall also perish, and the plain shall be destroyed, as the LORD has spoken.
* `Jer 49:4` Why do you glory in the valleys, your flowing *_valley_*, O backsliding daughter, who trusted in her treasures, saying, 'Who shall come to me?'
* `Ezk 37:1` The hand of the LORD was upon me, and he carried me out in the Spirit of the LORD and set me down in the midst of the *_valley_* which was full of bones.
* `Ezk 37:2` And he caused me to pass by them around, and behold, there were very many in the open *_valley_*, and behold, they were very dry.
* `Ezk 39:11` "And it shall come to pass in that day, that I will give to Gog a place of graves there in Israel: the *_valley_* of the passengers on the east of the sea. And it shall stop the noses of the passengers. And there they shall bury Gog and all his multitude. And they shall call it The *_Valley_* of Hamon-gog.
* `Ezk 39:15` And as passengers pass through the land, when any sees a man's bone, then he shall set up a sign by it until the buriers have buried it in The *_Valley_* of Hamon-gog.
* `Hos 1:5` And it shall come to pass at that day, that I will break the bow of Israel in the *_valley_* of Jezreel."
* `Hos 2:15` And I will give her her vineyards from there, and the *_valley_* of Achor for a door of hope. And she shall sing there, as in the days of her youth and as in the day when she came from the land of Egypt.
* `Joe 3:2` I will also gather all nations and bring them down into the *_valley_* of Jehoshaphat. I will plead with them there for my people and for my heritage Israel, whom they have scattered among the nations, and divided my land.
* `Joe 3:12` "Let the heathen be awakened and come up to the *_valley_* of Jehoshaphat, for there I will sit to judge all the heathen on every side.
* `Joe 3:14` Multitudes, multitudes in the *_valley_* of decision, for the day of the LORD is near in the *_valley_* of decision.
* `Joe 3:18` And it shall come to pass in that day, that the mountains shall drop down new wine, the hills shall flow with milk, and all the rivers of Judah shall flow with waters, and a fountain shall come forth from the house of the LORD and shall water the *_valley_* of Shittim.
* `Mic 1:6` Therefore, I will make Samaria as a heap of the field and as plantings of a vineyard. And I will pour down her stones into the *_valley_* and lay her foundations bare.
* `Zch 12:11` In that day there shall be a great mourning in Jerusalem as the mourning of Hadadrimmon in the *_valley_* of Megiddon.
* `Zch 14:4` And his feet will stand in that day upon the Mount of Olives, which is before Jerusalem on the east. And the Mount of Olives shall cleave in the midst of it toward the east and toward the west, and there shall be a very great *_valley_*. Half of the mountain shall move toward the north and half of it toward the south.
* `Zch 14:5` And you shall flee to the *_valley_* of the mountains, for the *_valley_* of the mountains shall reach to Azal. Indeed, you shall flee as you fled from before the earthquake in the days of Uzziah king of Judah. And the LORD my God shall come, and all the saints with you.
* `Luk 3:5` Every *_valley_* shall be filled, every mountain and hill shall be brought low, the crooked shall be made straight, and the rough ways shall be made smooth,

_137 verses containing VALLEY_

== VALLEY-GATE

* `Neh 3:13` The *_valley-gate_* was repaired by Hanun and the inhabitants of Zanoah. They built it, set up its doors, its locks, and its bars, and one thousand cubits on the wall to the dung-gate.

_1 verse containing VALLEY-GATE_

== VALLEYS

* `Num 24:6` As the *_valleys_* they are spread forth, as gardens by the river's side, as the trees of lign-aloes which the LORD has planted, and as cedar-trees beside the waters.
* `Deu 8:7` For the LORD your God brings you into a good land, a land of brooks of water, of fountains, and depths that spring out of *_valleys_* and hills;
* `Deu 11:11` But the land that you are entering to possess is a land of hills and *_valleys_*, and drinks water from the rain of heaven,
* `Jsh 9:1` And it came to pass, when all the kings who were on this side of the Jordan heard these things—those in the hills, in the *_valleys_*, and in all the coasts of the Great Sea over against Lebanon, the Hittite, the Amorite, the Canaanite, the Perizzite, the Hivite, and the Jebusite—
* `Jsh 12:8` In the mountains, in the *_valleys_*, in the plains, in the springs, in the wilderness, and in the south country—[the land of] the Hittites, the Amorites, the Canaanites, the Perizzites, the Hivites, and the Jebusites:
* `1Ki 20:28` And there came a man of God and spoke to the king of Israel and said, "Thus says the LORD: 'Because the Syrians have said, "The LORD is God of the hills, but he is not God of the *_valleys_*," therefore I will deliver all this great multitude into your hand, and you shall know that I am the LORD.'"
* `1Ch 12:15` These are those who went over the Jordan in the first month when it had overflowed all its banks, and they put to flight all those of the *_valleys_*, both toward the east and toward the west.
* `1Ch 27:29` And over the herds that fed in Sharon was Shitrai the Sharonite; and over the herds that were in the *_valleys_* was Shaphat the son of Adlai;
* `Job 30:6` To dwell in the clefts of the *_valleys_*, in caves of the earth, and in the rocks.
* `Job 39:10` Can you bind the wild ox with ropes in the furrow? Or will he harrow the *_valleys_* after you?
* `Psa 65:13` The pastures are clothed with flocks. The *_valleys_* are also covered over with grain. They shout for joy. They also sing.
* `Psa 104:8` They go up by the mountains. They go down by the *_valleys_* to the place which you have founded for them.
* `Psa 104:10` He sends the springs into the *_valleys_*, which run among the hills.
* `Sos 2:1` [Lady:] I am the rose of Sharon and the lily of the *_valleys_*.
* `Isa 7:19` And they shall come, and all of them shall rest in the desolate *_valleys_*, in the holes of the rocks, upon all thorns, and upon all bushes.
* `Isa 22:7` And it shall come to pass, that your choicest *_valleys_* shall be full of chariots, and the horsemen shall set themselves in array at the gate.
* `Isa 28:1` Woe to the crown of pride, to the drunkards of Ephraim, whose glorious beauty is a fading flower, who are on the head of the rich *_valleys_* of those who are overcome with wine!
* `Isa 41:18` I will open rivers in high places and fountains in the midst of the *_valleys_*. I will make the wilderness a pool of water and the dry land springs of water.
* `Isa 57:5` Inflaming yourselves with idols under every green tree, slaying the children in the *_valleys_* under the cliffs of the rocks?
* `Jer 49:4` Why do you glory in the *_valleys_*, your flowing valley, O backsliding daughter, who trusted in her treasures, saying, 'Who shall come to me?'
* `Ezk 6:3` And say, 'You mountains of Israel, hear the word of the Lord GOD. Thus says the Lord GOD to the mountains, to the hills, to the rivers, and to the *_valleys_*: "Behold, I, even I, will bring a sword upon you, and I will destroy your high places.
* `Ezk 7:16` But those of them who escape shall escape and be on the mountains like doves of the *_valleys_*, all of them mourning, each for his iniquity.
* `Ezk 31:12` And strangers, the terrible of the nations, have cut him off and have left him. Upon the mountains and in all the *_valleys_* his branches have fallen, and his boughs are broken by all the rivers of the land. And all the people of the earth have gone down from his shadow and have left him.
* `Ezk 32:5` And I will lay your flesh upon the mountains and fill the *_valleys_* with your height.
* `Ezk 35:8` And I will fill his mountains with his slain men. In your hills, in your *_valleys_*, and in all your rivers, they shall fall who are slain with the sword.
* `Ezk 36:4` Therefore, mountains of Israel, hear the word of the Lord GOD. Thus says the Lord GOD to the mountains, to the hills, to the rivers, to the *_valleys_*, to the desolate wastes, and to the cities that are forsaken, which became a prey and derision to the remnant of the heathen who are around—
* `Ezk 36:6` Prophesy therefore concerning the land of Israel, and say to the mountains, to the hills, to the rivers, and to the *_valleys_*, 'Thus says the Lord GOD: "Behold, I have spoken in my jealousy and in my fury, because you have borne the shame of the heathen."
* `Mic 1:4` And the mountains shall be melted under him, and the *_valleys_* shall be split, as wax before the fire and as the waters that are poured down a steep place.

_28 verses containing VALLEYS_

== VALOR

* `Jsh 1:14` Your wives, your little ones, and your livestock shall remain in the land which Moses gave you on this side of the Jordan, but you shall pass before your brothers armed, all the mighty men of *_valor_*, and help them
* `Jsh 6:2` And the LORD said to Joshua, "Behold, I have given into your hand Jericho, its king, and the mighty men of *_valor_*.
* `Jsh 8:3` So Joshua and all the people of war arose to go up against Ai. And Joshua chose out thirty thousand mighty men of *_valor_* and sent them away by night.
* `Jsh 10:7` So Joshua ascended from Gilgal—he, all the people of war with him, and all the mighty men of *_valor_*.
* `Jdg 3:29` And they slew of Moab at that time about ten thousand men, all lusty and all men of *_valor_*, and there did not escape a man.
* `Jdg 6:12` And the angel of the LORD appeared to him, and said to him, "The LORD is with you, you mighty man of *_valor_*."
* `Jdg 11:1` Now Jephthah the Gileadite was a mighty man of *_valor_*, and he was the son of a harlot. And Gilead begot Jephthah.
* `Jdg 18:2` And the children of Dan sent from their family five men from their borders, men of *_valor_*, from Zorah and from Eshtaol, to explore the land and to search it. And they said to them, "Go, search the land." When they came to mount Ephraim, to the house of Micah, they lodged there.
* `Jdg 20:44` And eighteen thousand men of Benjamin fell. All these were men of *_valor_*.
* `Jdg 20:46` So all who fell that day of Benjamin were twenty-five thousand men who drew the sword. All these were men of *_valor_*.
* `1Ki 11:28` And the man Jeroboam was a mighty man of *_valor_*. And Solomon, seeing that the young man was industrious, he made him ruler over all the charge of the house of Joseph.
* `2Ki 5:1` Now Naaman, captain of the army of the king of Syria, was a great man with his master and highly esteemed, because by him the LORD had given deliverance to Syria. He was also a mighty man in *_valor_*, but he was a leper.
* `2Ki 24:14` And he carried away all Jerusalem, all the princes, all the mighty men of *_valor_*, even ten thousand captives, and all the craftsmen and smiths. None remained, except the poorest sort of the people of the land.
* `1Ch 5:24` And these were the heads of the house of their fathers: even Epher, Ishi, Eliel, Azriel, Jeremiah, Hodaviah, and Jahdiel, mighty men of *_valor_*, famous men, and heads of the house of their fathers.
* `1Ch 7:7` And the sons of Bela: Ezbon, Uzzi, Uzziel, Jerimoth, and Iri, five, heads of the house of their fathers, mighty men of *_valor_*. They were reckoned by their genealogies twenty-two thousand and thirty-four.
* `1Ch 7:9` And their number, after their genealogy by their generations, heads of the house of their fathers, mighty men of *_valor_*, was twenty thousand and two hundred.
* `1Ch 7:11` All these the sons of Jediael by the heads of their fathers, mighty men of *_valor_*, were seventeen thousand and two hundred soldiers fit to go out for war and battle.
* `1Ch 7:40` All these were the children of Asher, heads of their father's house, choice and mighty men of *_valor_*, chief of the princes. And the number throughout the genealogy of those who were fit for war and for battle was twenty-six thousand men.
* `1Ch 8:40` And the sons of Ulam were mighty men of *_valor_*, archers, and had many sons and sons' sons numbering one hundred and fifty. All these are among the sons of Benjamin.
* `1Ch 12:21` And they helped David against the marauding band, for they were all mighty men of *_valor_* and were captains in the host.
* `1Ch 12:25` Of the children of Simeon, mighty men of *_valor_* for war, seven thousand and one hundred.
* `1Ch 12:28` And Zadok, a young man mighty of *_valor_*, and of his father's house twenty-two captains.
* `1Ch 12:30` And of the children of Ephraim twenty thousand and eight hundred, mighty men of *_valor_*, famous throughout the house of their fathers.
* `1Ch 26:6` To Shemaiah his son, sons were also born who ruled throughout the house of their father, for they were mighty men of *_valor_*.
* `1Ch 26:30` And of the Hebronites, Hashabiah and his brothers, men of *_valor_*, one thousand and seven hundred, had the oversight of Israel beyond the Jordan westward in all the business of the LORD and in the service of the king.
* `1Ch 26:31` Among the Hebronites was Jerijah the chief, even among the Hebronites, according to the generations of his fathers. In the fortieth year of the reign of David they were sought for, and there were found among them mighty men of *_valor_* at Jazer of Gilead.
* `1Ch 26:32` And his brothers, men of *_valor_*, were two thousand and seven hundred chief fathers, whom king David made rulers over the Reubenites, the Gadites, and the half-tribe of Manasseh, for every matter pertaining to God and affairs of the king.
* `2Ch 13:3` And Abijah set the battle in array with an army of valiant men of war, even four hundred thousand chosen men. Jeroboam also set the battle in array against him with eight hundred thousand chosen men, being mighty men of *_valor_*.
* `2Ch 14:8` And Asa had an army of three hundred thousand men out of Judah who bore bucklers and spears, and two hundred and eighty thousand out of Benjamin who bore shields and drew bows. All these were mighty men of *_valor_*.
* `2Ch 17:13` And he had much business in the cities of Judah. And the men of war, mighty men of *_valor_*, were in Jerusalem.
* `2Ch 17:14` And these are their numbers according to the house of their fathers. Of Judah, the captains of thousands: Adnah the chief, and with him three hundred thousand mighty men of *_valor_*;
* `2Ch 17:16` And next to him was Amasiah the son of Zichri, who willingly offered himself to the LORD, and with him two hundred thousand mighty men of *_valor_*.
* `2Ch 17:17` And of Benjamin: Eliada a mighty man of *_valor_*, and with him two hundred thousand armed men with bow and shield;
* `2Ch 25:6` He also hired one hundred thousand mighty men of *_valor_* out of Israel for one hundred talents of silver.
* `2Ch 26:12` The whole number of the chief of the fathers of the mighty men of *_valor_* was two thousand and six hundred.
* `2Ch 32:21` And the LORD sent an angel who cut off all the mighty men of *_valor_* and the leaders and captains in the camp of the king of Assyria. So he returned with shame of face to his own land. And when he had come into the house of his god, those who came forth from his own body slew him there with the sword.
* `Neh 11:14` And their brothers, mighty men of *_valor_*, one hundred twenty-eight. And their overseer was Zabdiel the son of one of the great men.

_37 verses containing VALOR_

== VALUE

* `Lev 27:8` But if he is poorer than your estimation, then he shall present himself before the priest, and the priest shall *_value_* him. According to the ability of him who vowed the priest shall *_value_* him.
* `Lev 27:12` And the priest shall *_value_* it, whether it is good or bad. As you *_value_* it, who are the priest, so it shall be.
* `Job 13:4` But you are forgers of lies. You are all physicians of no *_value_*.
* `Mth 10:31` Do not fear therefore. You are of more *_value_* than many sparrows.
* `Luk 12:7` But even every hair of your head has been numbered. Do not fear therefore. You are of more *_value_* than many sparrows.
* `Act 5:3` But Peter said, "Ananias, why has Satan filled your heart to lie to the Holy Spirit and to keep back part of the *_value_* of the land?

_6 verses containing VALUE_

== VALUED

* `Lev 27:16` 'And if a man sanctifies to the LORD some part of a field of his possession, then your estimation shall be according to its seed. A homer of barley seed shall be *_valued_* at fifty shekels of silver.
* `Job 28:16` It cannot be *_valued_* with the gold of Ophir, with the precious onyx, or the sapphire.
* `Job 28:19` The topaz of Cush shall not equal it, neither shall it be *_valued_* with pure gold.
* `Mth 27:9` Then that which was spoken by Jeremiah the prophet was fulfilled, saying, "'And they took the thirty pieces of silver,' 'the price of him who was *_valued_*,' whom they of the children of Israel *_valued_*,

_4 verses containing VALUED_

== VANIAH

* `Ezr 10:36` *_Vaniah_*, Meremoth, Eliashib,

_1 verse containing VANIAH_

== VANISH

* `Job 6:17` In the time when they become warm, they *_vanish_*. When it is hot, they are consumed out of their place.
* `Isa 51:6` Lift up your eyes to the heavens and look upon the earth beneath, for the heavens shall *_vanish_* away like smoke, the earth shall become old like a garment, and its inhabitants shall die in a like manner. But my salvation shall be forever and my righteousness shall not be abolished.
* `1Co 13:8` Charity never fails. But if there are prophecies, they shall fail. If there are languages, they shall cease. If there is knowledge, it shall *_vanish_* away.
* `Heb 8:13` In that he says, "A new covenant," he has made the first old. Now that which decays and grows old is ready to *_vanish_* away.

_4 verses containing VANISH_

== VANISHED

* `Jer 49:7` [Concerning Edom.] Thus says the LORD of hosts: "Is wisdom no longer in Teman? Has counsel perished from the prudent? Has their wisdom *_vanished_*?
* `Luk 24:31` And their eyes were opened and they knew him, and he *_vanished_* out of their sight.

_2 verses containing VANISHED_

== VANISHES

* `Job 7:9` As the cloud is consumed and *_vanishes_* away, so he who goes down to the grave shall come up no more.
* `Jms 4:14` You do not know what will be on the next day. For what is your life? It is even a vapor that appears for a little time and then *_vanishes_* away.

_2 verses containing VANISHES_

== VANITIES

* `Deu 32:21` They have moved me to jealousy with that which is not God. They have provoked me to anger with their *_vanities_*. And I will move them to jealousy with those who are not a people. I will provoke them to anger with a foolish nation.
* `1Ki 16:13` For all the sins of Baasha and the sins of Elah his son by which they sinned and by which they made Israel to sin, in provoking the LORD God of Israel to anger with their *_vanities_*.
* `1Ki 16:26` For he walked in all the way of Jeroboam the son of Nebat and in his sin with which he made Israel to sin to provoke the LORD God of Israel to anger with their *_vanities_*.
* `Psa 31:6` I have hated those who regard lying *_vanities_*, but I trust in the LORD.
* `Ecc 1:2` "Vanity of *_vanities_*," says the preacher. "Vanity of *_vanities_*. All is vanity."
* `Ecc 5:7` For in the multitude of dreams and many words there are also diverse *_vanities_*. But fear God.
* `Ecc 12:8` "Vanity of *_vanities_*," says the preacher. "All is vanity."
* `Jer 8:19` Behold the voice of the cry of the daughter of my people because of those who dwell in a distant country: "Is the LORD not in Zion? Is her king not in her?" "Why have they provoked me to anger with their engraved images and with strange *_vanities_*?"
* `Jer 10:8` But they are altogether brutish and foolish. The doctrine of *_vanities_* is but wood.
* `Jer 14:22` Are there any among the *_vanities_* of the Gentiles who can cause rain? Or can the heavens give showers? Are you not he, O LORD our God? Therefore, we will wait upon you, for you have made all these things.
* `Jna 2:8` Those who observe lying *_vanities_* forsake their own mercy.
* `Act 14:15` And saying, "Sirs, why do you do these things? We are also men of like passions with you and preach to you that you should turn from these *_vanities_* to the living God, who 'made heaven, earth, the sea, and all things that are in them,'

_12 verses containing VANITIES_

== VANITY

* `2Ki 17:15` And they rejected his statutes, his covenant that he made with their fathers, and his testimonies which he testified against them, and they followed *_vanity_*, became vain, and went after the nations that were around them, concerning whom the LORD had charged them that they should not do like them.
* `Job 7:3` So I am made to possess months of *_vanity_*, and wearisome nights are appointed to me.
* `Job 7:16` I loathe it. I shall not live forever. Leave me alone, for my days are *_vanity_*.
* `Job 15:31` Do not let him who is deceived trust in *_vanity_*, for *_vanity_* shall be his recompense.
* `Job 15:35` They conceive mischief and bring forth *_vanity_*, and their belly prepares deceit."
* `Job 31:5` If I have walked with *_vanity_*, or if my foot has hastened to deceit,
* `Job 35:13` Surely God will not hear *_vanity_*, neither will the Almighty regard it.
* `Psa 4:2` O sons of men, how long will you turn my glory into shame? How long will you love *_vanity_* and seek after falsehood? [Selah.]
* `Psa 10:7` His mouth is full of cursing and deceit and fraud. Under his tongue is mischief and *_vanity_*.
* `Psa 12:2` They each speak *_vanity_* with his neighbor. With flattering lips and with a double heart they speak.
* `Psa 24:4` He who has clean hands and a pure heart, who has not lifted up his soul to *_vanity_* nor sworn deceitfully.
* `Psa 39:5` Behold, you have made my days as a hand-breadth, and my age is as nothing before you. Truly every man at his best state is altogether *_vanity_*." [Selah.]
* `Psa 39:11` When you, with rebukes, correct man for iniquity, you make his beauty to consume away like a moth. Surely every man is *_vanity_*." [Selah.]
* `Psa 41:6` And if he comes to see me, he speaks *_vanity_*. His heart gathers iniquity to itself. When he goes abroad, he tells it.
* `Psa 62:9` Surely men of low degree are *_vanity_*, and men of high degree are a lie. They will be laid in the balance. They are altogether lighter than *_vanity_*.
* `Psa 78:33` Therefore, he consumed their days in *_vanity_* and their years in trouble.
* `Psa 94:11` The LORD knows the thoughts of man, that they are *_vanity_*.
* `Psa 119:37` Turn away my eyes from beholding *_vanity_* and revive me in your way.
* `Psa 144:4` Man is like *_vanity_*. His days are like a shadow that passes away.
* `Psa 144:8` Whose mouth speaks *_vanity_* and their right hand is a right hand of falsehood.
* `Psa 144:11` Rid me and deliver me from the hand of strange children, whose mouth speaks *_vanity_* and their right hand is a right hand of falsehood,
* `Pro 13:11` Wealth gotten by *_vanity_* shall be diminished, but he who gathers by labor shall increase.
* `Pro 21:6` The getting of treasures by a lying tongue is a *_vanity_* tossed to and fro by those who seek death.
* `Pro 22:8` He who sows iniquity shall reap *_vanity_*, and the rod of his anger shall fail.
* `Pro 30:8` Keep *_vanity_* and lies far from me, and give me neither poverty nor riches. Feed me with the food of my portion,
* `Ecc 1:2` "*_Vanity_* of vanities," says the preacher. "*_Vanity_* of vanities. All is *_vanity_*."
* `Ecc 1:14` I have seen all the works that are done under the sun, and behold, all is *_vanity_* and vexation of spirit.
* `Ecc 2:1` I said in my heart, "Come now, I will prove you with mirth; therefore, enjoy pleasure," and behold, this also is *_vanity_*.
* `Ecc 2:11` Then I considered all the works that my hands had wrought and the labor that I had labored to do, and behold, all was *_vanity_* and vexation of spirit, and there was no profit under the sun.
* `Ecc 2:15` Then I said in my heart, "As it happens to the fool, so it happens even to me. And why was I then more wise?" Then I said in my heart that this also is *_vanity_*.
* `Ecc 2:17` Therefore, I hated life, because the work that is wrought under the sun is grievous to me. For all is *_vanity_* and vexation of spirit.
* `Ecc 2:19` And who knows whether he shall be a wise man or a fool? Yet he shall have rule over all my labor in which I have labored and in which I have shown myself wise under the sun. This is also *_vanity_*.
* `Ecc 2:21` For there is a man whose labor is in wisdom, in knowledge, and in equity, yet to a man who has not labored in it, he shall leave it for his portion. This also is *_vanity_* and a great evil.
* `Ecc 2:23` For all his days are sorrows and his labor grief. Even his heart does not take rest in the night. This is also *_vanity_*.
* `Ecc 2:26` For to the man who is good in his sight, God gives wisdom, knowledge, and joy, but to the sinner he gives toil, to gather and to amass, so that he may give to him who is good before God. This also is *_vanity_* and vexation of spirit.
* `Ecc 3:19` For that which befalls the sons of men befalls beasts, even one thing befalls them: as one dies, so the other dies. Indeed, they all have one breath, so that a man has no pre-eminence above a beast, for all is *_vanity_*.
* `Ecc 4:4` Again, I considered all labor and every right work, that for this, a man is envied by his neighbor. This is also *_vanity_* and vexation of spirit.
* `Ecc 4:7` Then I returned, and I saw *_vanity_* under the sun.
* `Ecc 4:8` There is one alone, and there is not a second, and he has neither child nor brother. Yet there is no end of all his labor, neither is his eye satisfied with riches, neither does he say, "For whom do I labor and bereave my soul of good?" This is also *_vanity_*. It is even a grievous labor.
* `Ecc 4:16` There is no end of all the people, even of all who have been before them. Those who come after shall not rejoice in him. Surely this also is *_vanity_* and vexation of spirit.
* `Ecc 5:10` He who loves silver shall not be satisfied with silver, nor he who loves abundance with increase. This is also *_vanity_*.
* `Ecc 6:2` A man to whom God has given riches, wealth, and honor, so that he lacks nothing for his soul of all that he desires, yet God does not give him power to enjoy them, but a stranger enjoys them. This is *_vanity_*, and it is an evil disease.
* `Ecc 6:4` For that one comes with *_vanity_* and departs in darkness, and his name shall be covered with darkness.
* `Ecc 6:9` Better is the sight of the eyes than the wandering of the desire. This is also *_vanity_* and vexation of spirit.
* `Ecc 6:11` Seeing there are many things that increase *_vanity_*, what is man the better?
* `Ecc 7:6` For as the crackling of thorns under a pot, so is the laughter of the fool. This also is *_vanity_*.
* `Ecc 7:15` I have seen all things in the days of my *_vanity_*. There is a just man who perishes in his righteousness, and there is a wicked man who prolongs his life in his wickedness.
* `Ecc 8:10` And so I saw the wicked buried, who had come and gone from the holy place, and they were forgotten in the city where they had done so. This is also *_vanity_*.
* `Ecc 8:14` There is a *_vanity_* which is done upon the earth: there are just men, to whom it happens according to the work of the wicked, and there are wicked men, to whom it happens according to the work of the righteous. I said that this also is *_vanity_*.
* `Ecc 9:9` Live joyfully with the wife whom you love all the days of the life of your *_vanity_*, which he has given you under the sun, all the days of your *_vanity_*, for that is your portion in this life and in your labor which you take under the sun.
* `Ecc 11:8` But if a man lives many years and rejoices in them all, yet let him remember the days of darkness, for they shall be many. All that comes is *_vanity_*.
* `Ecc 11:10` Therefore, remove sorrow from your heart and put away evil from your flesh, for childhood and youth are *_vanity_*.
* `Ecc 12:8` "*_Vanity_* of vanities," says the preacher. "All is *_vanity_*."
* `Isa 5:18` Woe to those who draw iniquity with cords of *_vanity_* and sin as with a cart-rope,
* `Isa 30:28` And his breath, as an overflowing stream, shall reach to the midst of the neck, to sift the nations with the sieve of *_vanity_*. And there shall be a bridle in the jaws of the people, causing them to err.
* `Isa 40:17` All nations before him are as nothing, and they are counted to him less than nothing, and *_vanity_*.
* `Isa 40:23` Who brings the princes to nothing. He makes the judges of the earth as *_vanity_*.
* `Isa 41:29` Behold, they are all *_vanity_*. Their works are nothing. Their molten images are wind and confusion."
* `Isa 44:9` Those who make an engraved image are all of them *_vanity_*, and their delectable things shall not profit, and they are their own witnesses. They neither see nor know so that they may be ashamed.
* `Isa 57:13` When you cry, let your companies deliver you. But the wind shall carry them all away. *_Vanity_* shall take them. But he who puts his trust in me shall possess the land and shall inherit my holy mountain."
* `Isa 58:9` Then you shall call, and the LORD will answer. You shall cry, and he will say, 'Here I am.' If you take away from the midst of you the yoke, the putting forth of the finger, and speaking *_vanity_*,
* `Isa 59:4` No one calls for justice, nor any pleads for truth. They trust in *_vanity_* and speak lies. They conceive mischief and bring forth iniquity.
* `Jer 2:5` Thus says the LORD: "What iniquity have your fathers found in me that they have gone far from me and have walked after *_vanity_* and have become vain?
* `Jer 10:15` They are *_vanity_* and the work of errors. In the time of their visitation they shall perish.
* `Jer 16:19` O LORD, my strength and my fortress, and my refuge in the day of affliction, the Gentiles shall come to you from the ends of the earth, and shall say, "Surely our fathers have inherited lies, *_vanity_*, and things in which there is no profit."
* `Jer 18:15` For my people have forgotten me and they have burned incense to *_vanity_*. And they have been made to stumble in their ways in the ancient paths, to walk in tracks, in a way not cast up,
* `Jer 51:18` They are *_vanity_*, the work of errors. In the time of their visitation they shall perish.
* `Ezk 13:6` They have seen *_vanity_* and lying divination, saying, 'The LORD says,' and the LORD has not sent them, and they have made others to hope that they would confirm the word.
* `Ezk 13:8` Therefore, thus says the Lord GOD: "Because you have spoken *_vanity_* and seen lies, therefore, behold, I am against you," says the Lord GOD.
* `Ezk 13:9` "And my hand shall be upon the prophets who see *_vanity_* and who divine lies. They shall not be in the assembly of my people, neither shall they be written in the writing of the house of Israel, neither shall they enter into the land of Israel. And you shall know that I am the Lord GOD.
* `Ezk 13:23` Therefore you shall see no more *_vanity_* nor divine divinations, for I will deliver my people out of your hand. And you shall know that I am the LORD."
* `Ezk 21:29` While they see *_vanity_* for you, while they divine a lie for you—to bring you upon the necks of the wicked who are slain, whose day has come when their iniquity has an end.
* `Ezk 22:28` And her prophets have daubed them with untempered mortar, seeing *_vanity_* and divining lies for them, saying, 'Thus says the Lord GOD,' when the LORD has not spoken.
* `Hos 12:11` Is there iniquity in Gilead? Surely they are *_vanity_*. They sacrifice bulls in Gilgal. Even their altars are as heaps in the furrows of the fields.
* `Hab 2:13` Behold, is it not from the LORD of hosts that the people labor in the fire and the people weary themselves for *_vanity_*?
* `Zch 10:2` For the idols have spoken *_vanity_*, and the diviners have seen a lie. They have told false dreams. They comfort in vain. Therefore, they went their way as a flock. They were troubled because there was no shepherd.
* `Rom 8:20` For the creature was made subject to *_vanity_*, not willingly, but by reason of him who has subjected the same in hope,
* `Eph 4:17` This I say therefore, and testify in the Lord, that you from now on do not walk as other Gentiles walk, in the *_vanity_* of their mind,
* `2Pe 2:18` For when they speak great swelling words of *_vanity_*, they allure through the lusts of the flesh, through much wantonness, those who had quite escaped from those who live in error.

_79 verses containing VANITY_

== VAPOR

* `Job 36:27` For he makes the drops of water small. They pour down rain according to its *_vapor_*,
* `Act 2:19` And I will show wonders in heaven above and signs on the earth beneath: blood, fire, and *_vapor_* of smoke.
* `Jms 4:14` You do not know what will be on the next day. For what is your life? It is even a *_vapor_* that appears for a little time and then vanishes away.

_3 verses containing VAPOR_

== VAPORS

* `Psa 135:7` He causes the *_vapors_* to ascend from the ends of the earth. He makes lightnings for the rain. He brings the wind out of his treasuries.
* `Psa 148:8` Fire and hail, snow and *_vapors_*, stormy wind fulfilling his word,
* `Jer 10:13` When he utters his voice, there is a multitude of waters in the heavens, and he causes the *_vapors_* to ascend from the ends of the earth. He makes lightnings with rain and brings forth the wind out of his treasures.
* `Jer 51:16` When he utters his voice, there is a multitude of waters in the heavens, and he causes the *_vapors_* to ascend from the ends of the earth. He makes lightnings with rain and brings forth the wind out of his treasures.

_4 verses containing VAPORS_

== VARIABLENESS

* `Jms 1:17` Every good gift and every perfect gift is from above and comes down from the Father of lights, with whom there is no *_variableness_*, neither shadow of turning.

_1 verse containing VARIABLENESS_

== VARIANCE

* `Mth 10:35` For I have come to 'set a man at *_variance_* against his father, the daughter against her mother, and the daughter-in-law against her mother-in-law.'
* `Gal 5:20` Idolatry, witchcraft, hatred, *_variance_*, jealousy, wrath, strife, dissensions, heresies,

_2 verses containing VARIANCE_

== VARIOUS

* `Mth 4:24` And his fame spread throughout all Syria. And they brought to him all sick people who were taken with *_various_* diseases and torments, those who were possessed with demons, those who were lunatic, and those who were paralyzed, and he healed them.
* `Mrk 1:34` And he healed many who were sick with *_various_* diseases and cast out many demons. And he did not allow the demons to speak because they knew him.
* `Luk 4:40` Now when the sun was setting, all those who had any sick with *_various_* diseases brought them to him. And he laid his hands on every one of them and healed them.
* `Luk 21:11` Great earthquakes, famines, and pestilences will be in *_various_* places. And there will be fearful sights and great signs from heaven.

_4 verses containing VARIOUS_

== VASHNI

* `1Ch 6:28` And the sons of Samuel: the first-born *_Vashni_* and Abiah.

_1 verse containing VASHNI_

== VASHTI

* `Est 1:9` Also, *_Vashti_* the queen made a feast for the women in the royal house which belonged to king Ahasuerus.
* `Est 1:11` To bring *_Vashti_* the queen before the king with the royal crown to show the people and the princes her beauty, for she was fair to look upon.
* `Est 1:12` But the queen *_Vashti_* refused to come at the king's commandment by his chamberlains. Therefore, the king was very angry and his anger burned in him.
* `Est 1:15` "What shall we do to the queen *_Vashti_* according to law because she has not performed the commandment of king Ahasuerus by the chamberlains?"
* `Est 1:16` And Memucan answered before the king and the princes, "*_Vashti_* the queen has not done wrong to the king only, but also to all the princes and to all the people who are in all the provinces of king Ahasuerus.
* `Est 1:17` For this deed of the queen will come abroad to all women to make their husbands contemptible in their eyes when they say, 'King Ahasuerus commanded *_Vashti_* the queen to be brought in before him, but she did not come.'
* `Est 1:19` If it pleases the king, let a royal commandment go from him, and let it be written among the laws of the Persians and the Medes so that it may not be altered, that *_Vashti_* may no longer come before king Ahasuerus. And let the king give her royal estate to another who is better than she is.
* `Est 2:1` After these things, when the wrath of king Ahasuerus was appeased, he remembered *_Vashti_* and what she had done, and what was decreed against her.
* `Est 2:4` And let the young woman who pleases the king be queen instead of *_Vashti_*." And the thing pleased the king, and he did so.
* `Est 2:17` And the king loved Esther above all the women, and she obtained grace and favor in his sight more than all the virgins. So he set the royal crown upon her head and made her queen instead of *_Vashti_*.

_10 verses containing VASHTI_

== VATS

* `Joe 2:24` And the floors shall be full of wheat and the *_vats_* shall overflow with wine and oil.
* `Joe 3:13` Put in the sickle, for the harvest is ripe. Come, tread, for the press is full. The *_vats_* overflow, for their wickedness is great."

_2 verses containing VATS_

== VAULT

* `Amo 9:6` It is he who builds his upper chambers in the heaven and has founded his *_vault_* on the earth, he who calls for the waters of the sea and pours them out upon the face of the earth—Yahweh is his name.

_1 verse containing VAULT_

== VAUNT

* `Jdg 7:2` And the LORD said to Gideon, "The people who are with you are too many for me to give the Midianites into their hands, lest Israel *_vaunt_* themselves against me, saying, 'My own hand has saved me.'
* `1Co 13:4` Charity is patient and is kind. Charity does not envy. Charity does not *_vaunt_* itself, is not puffed up,

_2 verses containing VAUNT_

== VAV

* `Psa 25:6` [*_VAV_*] Remember, O LORD, your tender mercies and your loving kindnesses, for they have always been from of old.
* `Psa 119:41` [*_VAV_*] Let your mercies come also to me, O LORD, even your salvation, according to your word.
* `Pro 31:15` [*_VAV_*] She also rises while it is still night and gives food to her household and a portion to her attendants.
* `Lam 1:6` [*_VAV_*] And from the daughter of Zion all her beauty has departed. Her princes have become like bucks that find no pasture, and they have gone without strength before the pursuer.
* `Lam 2:6` [*_VAV_*] And he has violently taken away his tabernacle as if it were of a garden. He has destroyed his places of the assembly. The LORD has caused the solemn feasts and sabbaths to be forgotten in Zion, and in the indignation of his anger has despised the king and the priest.
* `Lam 3:16` [*_VAV_*] He has also broken my teeth with gravel stones. He has covered me with ashes.
* `Lam 4:6` [*_VAV_*] For the punishment of the iniquity of the daughter of my people is greater than the punishment of the sin of Sodom, which was overthrown as in a moment, and no hands stayed on her.

_7 verses containing VAV_

== VEHEMENT

* `Sos 8:6` Set me as a seal upon your heart, as a seal upon your arm. For love is as strong as death, jealousy as cruel as the grave. Its coals are coals of fire which has a most *_vehement_* flame.
* `Jna 4:8` And it came to pass, when the sun rose, that God prepared a *_vehement_* east wind. And the sun beat upon the head of Jonah so that he fainted and wished in himself to die, and said, "It is better for me to die than to live."
* `2Co 7:11` For behold this very thing, that you sorrowed after a godly manner, what it has wrought in you: what carefulness, what clearing of yourselves, what indignation, what fear, what *_vehement_* desire, what zeal, and what avenging! In all things you have approved yourselves to be clear in this matter.

_3 verses containing VEHEMENT_

== VEHEMENTLY

* `Mrk 14:31` But he spoke the more *_vehemently_*, "If I should die with you, I will not deny you in any way." They all also said likewise.
* `Luk 6:48` He is like a man who built a house and dug deep and laid the foundation on a rock, and when the flood arose, the stream beat *_vehemently_* upon that house and could not shake it, for it was founded upon a rock.
* `Luk 6:49` But he who hears and does not do, is like a man who built a house on the earth without a foundation, against which the stream beat *_vehemently_* and immediately it fell, and the ruin of that house was great."
* `Luk 11:53` And as he said these things to them, the scribes and the Pharisees began to urge him *_vehemently_* and to solicit him to speak of many things,
* `Luk 23:10` And the chief priests and scribes stood and *_vehemently_* accused him.

_5 verses containing VEHEMENTLY_

== VEIL

* `Gen 24:65` And she said to the servant, "What man is this who walks in the field to meet us?" And the servant said, "It is my master." Therefore, she took a *_veil_* and covered herself.
* `Gen 38:14` And she took off her widow's garments and covered herself with a *_veil_*, wrapped herself, and sat in an open place, which is by the way to Timnath, for she saw that Shelah was grown and she was not given to him for a wife.
* `Gen 38:19` And she arose and went her way and took off her *_veil_* from her and put on the garments of her widowhood.
* `Exo 26:31` "And you shall make a *_veil_* of blue, purple, scarlet, and fine twined linen of skillful work. With cherubim it shall be made.
* `Exo 26:33` And you shall hang the *_veil_* under the buttons so that you may bring in there within the *_veil_* the ark of the testimony. And the *_veil_* shall be for you a separation between the holy place and the holy of holies.
* `Exo 26:35` And you shall set the table outside the *_veil_*, and the candlestick over against the table on the side of the tabernacle toward the south, and you shall put the table on the north side.
* `Exo 27:21` In the Tabernacle of the Congregation outside the *_veil_*, which is before the testimony, Aaron and his sons shall order it from evening to morning before the LORD. It shall be a statute forever to their generations on behalf of the children of Israel."
* `Exo 30:6` And you shall put it before the *_veil_* that is by the ark of the testimony, before the mercy-seat that is over the testimony, where I will meet with you.
* `Exo 34:33` And until Moses had finished speaking with them, he put a *_veil_* on his face.
* `Exo 34:34` But when Moses went in before the LORD to speak with him, he took the *_veil_* off until he came out. And he came out and spoke to the children of Israel that which he was commanded.
* `Exo 34:35` And the children of Israel saw the face of Moses, that the skin of Moses's face shone. And Moses put the *_veil_* upon his face again until he went in to speak with him.
* `Exo 35:12` The ark and its staffs, the mercy-seat, and the *_veil_* of the covering;
* `Exo 36:35` And he made a *_veil_* of blue, purple, scarlet, and fine twined linen. With cherubim he made it of skillful work.
* `Exo 38:27` And from the hundred talents of silver the sockets of the sanctuary and the sockets of the *_veil_* were cast—one hundred sockets from the hundred talents, a talent for a socket.
* `Exo 39:34` The covering of rams' skins dyed red, the covering of badgers' skins, the *_veil_* of the covering,
* `Exo 40:3` And you shall put in it the ark of the testimony and cover the ark with the *_veil_*.
* `Exo 40:21` And he brought the ark into the tabernacle, set up the *_veil_* of the covering, and covered the ark of the testimony, as the LORD commanded Moses.
* `Exo 40:22` And he put the table in the tent of the congregation, upon the side of the tabernacle northward, outside the *_veil_*.
* `Exo 40:26` And he put the golden altar in the tent of the congregation before the *_veil_*,
* `Lev 4:6` And the priest shall dip his finger in the blood and sprinkle some of the blood seven times before the LORD, before the *_veil_* of the sanctuary.
* `Lev 4:17` And the priest shall dip his finger in some of the blood and sprinkle it seven times before the LORD, even before the *_veil_*.
* `Lev 16:2` And the LORD said to Moses, "Speak to Aaron your brother that he shall not come at all times into the holy place within the *_veil_* before the mercy-seat, which is upon the ark, so that he may not die. For I will appear in the cloud upon the mercy-seat.
* `Lev 16:12` And he shall take a censer full of burning coals of fire from off the altar before the LORD, and his hands full of sweet incense beaten small, and bring it within the *_veil_*.
* `Lev 16:15` "Then he shall kill the goat of the sin-offering that is for the people and bring its blood within the *_veil_*. And he shall do with that blood as he did with the blood of the bull and sprinkle it upon the mercy-seat and before the mercy-seat.
* `Lev 21:23` Only he shall not go in to the *_veil_*, nor come near to the altar, because he has a blemish, so that he may not profane my sanctuaries. For I, the LORD, sanctify them.'"
* `Lev 24:3` Outside the *_veil_* of the testimony, in the Tabernacle of the Congregation, Aaron shall order it from the evening to the morning before the LORD continually. It shall be a statute forever in your generations.
* `Num 4:5` "And when the camp moves forward, Aaron and his sons shall come, and they shall take down the covering *_veil_* and cover the ark of testimony with it.
* `Num 18:7` Therefore, you and your sons with you shall keep your priest's office for everything of the altar and within the *_veil_*, and you shall serve. I have given your priest's office to you as a service of gift. And the stranger who comes near shall be put to death."
* `Rth 3:15` Also he said, "Bring the *_veil_* that you have upon you and hold it." And when she held it, he measured six measures of barley and laid it on her. And she went into the city.
* `2Ch 3:14` And he made the *_veil_* of blue, purple, crimson, and fine linen, and wrought cherubim upon it.
* `Sos 4:1` [Gentleman:] Behold, you are fair, my love. Behold, you are fair. You have doves' eyes within your *_veil_*. Your hair is as a flock of goats that appear from mount Gilead.
* `Sos 4:3` Your lips are like a thread of scarlet and your speech is lovely. Your temples are like a piece of pomegranate within your *_veil_*.
* `Sos 5:7` The watchmen who went throughout the city found me, they smote me, they wounded me. The keepers of the walls took away my *_veil_* from me.
* `Sos 6:7` As a piece of pomegranate are your temples within your *_veil_*.
* `Isa 25:7` And he will destroy on this mountain the face of the covering cast over all people and the *_veil_* that is spread over all nations.
* `Mth 27:51` And behold, the *_veil_* of the temple was rent in two from the top to the bottom. And the earth shook and the rocks were split.
* `Mrk 15:38` And the *_veil_* of the temple was rent in two from the top to the bottom.
* `Luk 23:45` And the sun was darkened and the *_veil_* of the temple was rent in the midst.
* `2Co 3:13` And not as Moses who put a *_veil_* over his face so that the children of Israel could not steadfastly look to the end of that which is abolished.
* `2Co 3:14` But their minds were blinded, for until this day, the same *_veil_* remains untaken away in the reading of the old testament—which *_veil_* is done away in Christ.
* `2Co 3:15` But even to this day, when Moses is read, the *_veil_* is upon their heart.
* `2Co 3:16` Nevertheless, when it turns to the Lord, "the *_veil_* shall be taken away."
* `Heb 6:19` This hope we have as an anchor of the soul, both sure and steadfast, and which enters into that within the *_veil_*,
* `Heb 9:3` And after the second *_veil_* was the tabernacle which is called the holy of holies,
* `Heb 10:20` By a new and living way which he has dedicated for us through the *_veil_*, that is to say, his flesh,

_45 verses containing VEIL_

== VEILS

* `Isa 3:19` The chains, the bracelets, the *_veils_*,
* `Isa 3:23` The mirrors, the fine linen, the hoods, and the *_veils_*.
* `Ezk 13:18` And say, 'Thus says the Lord GOD: "Woe to the women who sew cushions to all armpits and make *_veils_* upon the head of every stature to hunt souls! Will you hunt the souls of my people, but save the souls alive who come to you?
* `Ezk 13:21` Your *_veils_* I will also tear and deliver my people out of your hand, and they shall no longer be in your hand to be hunted. And you shall know that I am the LORD.

_4 verses containing VEILS_

== VEIN

* `Job 28:1` "Surely there is a *_vein_* for the silver and a place for gold where they refine it.

_1 verse containing VEIN_

== VENGEANCE

* `Gen 4:15` And the LORD said to him, "Therefore, whoever slays Cain, *_vengeance_* shall be taken on him seven-fold." And the LORD set a mark upon Cain, lest anyone finding him should kill him.
* `Num 31:2` "Take *_vengeance_* against the Midianites for the children of Israel. Afterward, you shall be gathered to your people."
* `Deu 32:35` To me belongs *_vengeance_* and recompense. Their foot shall slide in due time, for the day of their calamity is at hand, and the things that shall come upon them make haste.
* `Deu 32:41` If I whet my glittering sword and my hand takes hold of judgment, I will render *_vengeance_* to my enemies and will recompense those who hate me.
* `Deu 32:43` "Rejoice, O nations, with his people, for he will avenge the blood of his servants, and will render *_vengeance_* to his adversaries, and will be merciful to his land and to his people."
* `Jdg 11:36` And she said to him, "My father, if you have opened your mouth to the LORD, do to me according to that which has proceeded out of your mouth, because the LORD has taken *_vengeance_* for you on your enemies, even on the children of Ammon."
* `Psa 58:10` The righteous shall rejoice when he sees the *_vengeance_*. He shall wash his feet in the blood of the wicked,
* `Psa 94:1` O LORD God, to whom *_vengeance_* belongs, O God, to whom *_vengeance_* belongs, show yourself.
* `Psa 99:8` You answered them, O LORD our God. You were a God who forgave them, though you took *_vengeance_* on their inventions.
* `Psa 149:7` To execute *_vengeance_* upon the heathen and punishments upon the people,
* `Pro 6:34` For jealousy is the rage of a man; therefore, he will not spare in the day of *_vengeance_*.
* `Isa 34:8` For it is the day of the LORD'S *_vengeance_*, and the year of recompenses for the controversy of Zion.
* `Isa 35:4` Say to those who are of a fearful heart, "Be strong. Do not fear. Behold, your God will come with *_vengeance_*, even God with a recompense. He will come and save you."
* `Isa 47:3` Your nakedness shall be uncovered. Even your shame shall be seen. I will take *_vengeance_*, and I will spare no man."
* `Isa 59:17` For he put on righteousness as a breast-plate, and a helmet of salvation upon his head. And he put on the garments of *_vengeance_* for clothing, and was clad with zeal as a cloak.
* `Isa 61:2` To proclaim the acceptable year of the LORD and the day of *_vengeance_* of our God, to comfort all who mourn,
* `Isa 63:4` For the day of *_vengeance_* is in my heart, and the year of my redeemed has come.
* `Jer 11:20` But, O LORD of hosts, who judges righteously, who tries the mind and the heart, let me see your *_vengeance_* on them, for to you I have revealed my cause.
* `Jer 20:12` But, O LORD of hosts, who tries the righteous and sees the mind and the heart, let me see your *_vengeance_* on them, for I have opened my cause to you.
* `Jer 46:10` For this is the day of the Lord GOD of hosts, a day of *_vengeance_*, so that he may avenge himself of his adversaries. And the sword shall devour and shall be satiated and made drunk with their blood, for the Lord GOD of hosts has a sacrifice in the north country by the Euphrates River.
* `Jer 50:15` Shout against her on every side. She has given her hand. Her foundations have fallen. Her walls are thrown down. Since it is the *_vengeance_* of the LORD, take *_vengeance_* upon her. As she has done, do to her.
* `Jer 50:28` The voice of those who flee and escape from the land of Babylon declares in Zion the *_vengeance_* of the LORD our God, the *_vengeance_* of his temple.
* `Jer 51:6` Flee from the midst of Babylon and deliver every man his soul. Do not be cut off in her iniquity, for this is the time of the LORD'S *_vengeance_*. He will render to her a recompense.
* `Jer 51:11` Make the arrows bright. Gather the shields. The LORD has raised up the spirit of the kings of the Medes, for his purpose is against Babylon to destroy it, because it is the *_vengeance_* of the LORD, the *_vengeance_* of his temple.
* `Jer 51:36` Therefore, thus says the LORD: "Behold, I will plead your cause and take *_vengeance_* for you, and I will dry up her sea and make her springs dry.
* `Lam 3:60` You have seen all their *_vengeance_* and all their imaginations against me.
* `Ezk 24:8` In order to cause fury to come up and to take *_vengeance_*, I have set her blood upon the top of a rock so that it should not be covered."
* `Ezk 25:12` 'Thus says the Lord GOD: "Because Edom has dealt against the house of Judah by taking *_vengeance_* and has greatly offended and revenged himself upon them,"
* `Ezk 25:14` And I will lay my *_vengeance_* upon Edom by the hand of my people Israel. And they shall do in Edom according to my anger and according to my fury, and they shall know my *_vengeance_*," says the Lord GOD.
* `Ezk 25:15` 'Thus says the Lord GOD: "Because the Philistines have dealt by revenge and have taken *_vengeance_* with a despiteful heart to destroy it for the old hatred,"
* `Ezk 25:17` And I will execute great *_vengeance_* upon them with furious rebukes. And they shall know that I am the LORD when I lay my *_vengeance_* upon them."'"
* `Mic 5:15` And I will execute *_vengeance_* in anger and fury upon the heathen who have not heard."
* `Nah 1:2` God is jealous, and the LORD avenges. The LORD avenges and has indignation. The LORD will take *_vengeance_* on his adversaries and he reserves wrath for his enemies.
* `Luk 21:22` For these are the days of *_vengeance_* so that all things which are written may be fulfilled.
* `Act 28:4` And when the barbarians saw the animal hang on his hand, they said among themselves, "No doubt this man is a murderer, whom, though he has escaped the sea, yet *_vengeance_* does not allow to live."
* `Rom 3:5` But if our unrighteousness commends the righteousness of God, what shall we say? Is God unrighteous who takes *_vengeance_*? (I speak as a man.)
* `Rom 12:19` Dearly beloved, do not avenge yourselves, but rather give place to wrath, for it is written, "*_Vengeance_* is mine and I will repay," says the Lord.
* `2Th 1:8` In flaming fire, taking *_vengeance_* on those who do not know God and who do not obey the gospel of our Lord Jesus Christ.
* `Heb 10:30` For we know him who has said, "*_Vengeance_* belongs to me. I will recompense," says the Lord. And again, "The Lord will judge his people."
* `Jde 1:7` Even as Sodom and Gomorrah, and the cities around them in like manner, giving themselves over to impurity and going after strange flesh, are set forth for an example, suffering the *_vengeance_* of eternal fire.

_40 verses containing VENGEANCE_

== VENOM

* `Deu 32:33` Their wine is the poison of serpents and the cruel *_venom_* of asps.

_1 verse containing VENOM_

== VENT

* `Job 32:19` Behold, my belly is like wine which has no *_vent_*, it is ready to burst like new bottles.

_1 verse containing VENT_

== VENTURE

* `Deu 28:56` The tender and delicate woman among you, who would not *_venture_* to set the sole of her foot upon the ground for delicateness and tenderness, her eye shall be evil toward the husband of her bosom, toward her son, toward her daughter,
* `Act 19:31` And some of the chief of Asia who were his friends sent to him, desiring him that he would not *_venture_* himself into the theater.

_2 verses containing VENTURE_

== VERDICT

* `Pro 16:33` The lot is cast into the lap, but its every *_verdict_* is from the LORD.

_1 verse containing VERDICT_

== VERIFIED

* `Gen 42:20` But bring your youngest brother to me. Thus your words shall be *_verified_*, and you shall not die." And they did so.
* `1Ki 8:26` And now, O God of Israel, let your word, I pray you, be *_verified_* which you spoke to your servant David my father.
* `2Ch 6:17` Now then, O LORD God of Israel, let your word be *_verified_* which you have spoken to your servant David.

_3 verses containing VERIFIED_

== VERITY

* `Psa 111:7` The works of his hands are *_verity_* and judgment. All his commandments are sure.
* `1Ti 2:7` For which I am ordained a preacher and an apostle (I speak the truth in Christ, and do not lie), a teacher of the Gentiles in faith and *_verity_*.

_2 verses containing VERITY_

== VERMILION

* `Jer 22:14` Who says, 'I will build myself a wide house and large chambers,' and cuts out windows for himself, and it is ceiled with cedar and painted with *_vermilion_*.
* `Ezk 23:14` So she increased her prostitutions, for when she saw men portrayed upon the wall, the images of the Chaldeans portrayed with *_vermilion_*,

_2 verses containing VERMILION_

== VERY

* `Gen 1:31` And God saw everything that he had made, and behold, it was *_very_* good. And the evening and the morning were the sixth day.
* `Gen 4:5` But for Cain and for his offering he did not have respect. And Cain was *_very_* angry and his countenance fell.
* `Gen 12:14` And it came to pass, that when Abram had come into Egypt, the Egyptians beheld the woman that she was *_very_* fair.
* `Gen 13:2` And Abram was *_very_* rich in livestock, in silver, and in gold.
* `Gen 18:20` And the LORD said, "Because the cry of Sodom and Gomorrah is great and because their sin is *_very_* grievous,
* `Gen 21:11` And the thing was *_very_* grievous in Abraham's sight because of his son.
* `Gen 24:16` And the young woman was *_very_* fair to look upon, a virgin, neither had any man known her. And she went down to the well and filled her pitcher and came up.
* `Gen 26:13` And the man became great and went forward and grew until he became *_very_* great.
* `Gen 26:14` For he had possession of flocks and possession of herds, and *_very_* many servants. And the Philistines envied him.
* `Gen 27:21` And Isaac said to Jacob, "Come near, I pray you, so that I may feel you, my son, whether you are my *_very_* son Esau, or not."
* `Gen 27:24` And he said, "Are you my *_very_* son Esau?" And he said, "I am."
* `Gen 34:7` And the sons of Jacob came from the field when they heard it, and the men were grieved and were *_very_* angry because he had wrought folly in Israel in lying with Jacob's daughter, which thing ought not to be done.
* `Gen 41:19` And behold, seven other cows came out after them, poor, *_very_* ill-favored, and lean-fleshed, such that I never saw worse in all the land of Egypt.
* `Gen 41:31` And the plenty shall not be known in the land by reason of the famine following, for it will be *_very_* grievous.
* `Gen 41:49` And Joseph gathered grain as the sand of the sea, *_very_* much, until he ceased numbering, for it was without number.
* `Gen 47:13` And there was no bread in all the land, for the famine was *_very_* distressing so that the land of Egypt and all the land of Canaan fainted by reason of the famine.
* `Gen 50:9` And both chariots and horsemen went with him. And it was a *_very_* great company.
* `Gen 50:10` And they came to the threshing-floor of Atad, which is beyond the Jordan, and there they mourned with a great and *_very_* sore lamentation. And he made a mourning for his father seven days.
* `Exo 1:20` Therefore, God dealt well with the midwives. And the people multiplied and became *_very_* mighty.
* `Exo 8:28` And Pharaoh said, "I will let you go so that you may sacrifice to the LORD your God in the wilderness. Only you shall not go *_very_* far away. Entreat for me."
* `Exo 9:3` Behold, the hand of the LORD is upon your livestock which are in the field, and also upon the horses, upon the donkeys, upon the camels, upon the oxen, and upon the sheep, and there shall be a *_very_* grievous pestilence.
* `Exo 9:18` Behold, tomorrow about this time I will cause it to rain a *_very_* grievous hail such as has not been in Egypt since its foundation even until now.
* `Exo 9:24` So there was hail, and fire mingled with the hail, *_very_* grievous, such as there had been none like it in all the land of Egypt since it became a nation.
* `Exo 10:14` And the locusts went up over all the land of Egypt and rested in all the borders of Egypt. They were *_very_* grievous. Before them there had never been [so many] locusts as this, neither after them will there be such.
* `Exo 11:3` And the LORD gave the people favor in the sight of the Egyptians. Moreover, the man Moses was *_very_* great in the land of Egypt, in the sight of Pharaoh's servants, and in the sight of the people.
* `Exo 12:38` And a mixed multitude went up also with them, and also flocks and herds, even a *_very_* large number of livestock.
* `Exo 30:36` And you shall beat some of it *_very_* small and put some of it before the testimony in the Tabernacle of the Congregation where I will meet with you. It shall be to you most holy.
* `Num 6:9` 'And if any man dies *_very_* suddenly by him and he has defiled the head of his consecration, then he shall shave his head on the day of his cleansing. On the seventh day he shall shave it.
* `Num 11:33` And while the flesh was still between their teeth, before it was chewed, the wrath of the LORD was kindled against the people and the LORD smote the people with a *_very_* great plague.
* `Num 12:3` (Now the man Moses was *_very_* meek above all the men who were upon the face of the earth.)
* `Num 13:28` Nevertheless, the people are strong who dwell in the land, and the cities are walled and *_very_* great. And moreover, we saw the children of Anak there.
* `Num 16:15` And Moses was *_very_* angry and said to the LORD, "Do not respect their offering. I have not taken one donkey from them, neither have I hurt one of them."
* `Num 22:17` For I will promote you to *_very_* great honor and I will do whatever you say to me. Come therefore, I pray you, curse this people for me.'"
* `Num 32:1` Now the children of Reuben and the children of Gad had a *_very_* great multitude of livestock. And when they saw the land of Jazer and the land of Gilead, that behold, the place was a place for livestock,
* `Deu 9:20` And the LORD was *_very_* angry with Aaron to have destroyed him. And I prayed for Aaron also at the same time.
* `Deu 9:21` And I took your sin, the calf which you had made, and burnt it with fire, stamped it, and ground it *_very_* small, even until it was as small as dust. And I cast the dust of it into the brook that descended from the mountain.
* `Deu 20:15` Thus you shall do to all the cities which are *_very_* distant from you, which are not of the cities of these nations.
* `Deu 27:8` And you shall write upon the stones all the words of this law *_very_* plainly."
* `Deu 28:43` The stranger who is within you shall rise above you *_very_* high, and you shall come down *_very_* low.
* `Deu 28:54` And the man who is tender among you and *_very_* delicate, his eye shall be evil toward his brother, toward the wife of his bosom, and toward the remnant of his children whom he leaves,
* `Deu 30:14` But the word is *_very_* near to you, in your mouth and in your heart, so that you may do it.
* `Deu 32:20` And he said, 'I will hide my face from them. I will see what their end will be, for they are a *_very_* perverse generation, children in whom there is no faith.
* `Jsh 1:7` Only be strong and *_very_* courageous so that you may observe to do according to all the law which Moses my servant commanded you. Do not turn from it to the right hand or to the left so that you may prosper wherever you go.
* `Jsh 3:16` The waters which came down from above stood and rose up in a heap *_very_* far from the city of Adam, that is beside Zaretan, and those which came down toward the sea of the plain, even the Salt Sea, failed, and were cut off. And the people passed through over against Jericho.
* `Jsh 5:11` And they ate unleavened cakes and parched grain from the produce of the land on the next day after the passover—on that *_very_* day.
* `Jsh 8:4` And he commanded them, saying, "Behold, you shall lie in wait against the city, even behind the city. Do not go *_very_* far from the city, but all of you be ready.
* `Jsh 9:9` And they said to him, "From a *_very_* far country your servants have come because of the name of the LORD your God, for we have heard the fame of him, and all that he did in Egypt,
* `Jsh 9:13` And these bottles of wine which we filled were new, and behold, they are rent. And our garments and our shoes have become old by reason of the *_very_* long journey."
* `Jsh 9:22` And Joshua called for them and spoke to them, saying, "Why have you deceived us, saying, 'We are *_very_* far from you,' when you dwell among us?
* `Jsh 10:20` And it came to pass, when Joshua and the children of Israel had made an end of slaying them with a *_very_* great slaughter until they were consumed, that the rest who remained of them entered into fortified cities.
* `Jsh 10:27` And it came to pass at the time of the setting of the sun, that Joshua commanded, and they took them down from the trees and cast them into the cave in which they had been hid and laid great stones upon the cave's mouth, which remain until this *_very_* day.
* `Jsh 11:4` And they went out—they and all their hosts with them, many people, even as the sand that is upon the sea-shore in multitude, with horses and chariots *_very_* numerous.
* `Jsh 13:1` Now Joshua was old and advanced in years, and the LORD said to him, "You are old and advanced in years, and there remains yet *_very_* much land to be possessed.
* `Jsh 22:8` And he spoke to them, saying, "Return with great riches to your tents, and with a *_very_* large number of livestock, with silver, with gold, with brass, with iron, and with *_very_* many clothes. Divide the plunder of your enemies with your brothers."
* `Jsh 23:6` Therefore, be *_very_* courageous to keep and to do all that is written in the book of the law of Moses, that you do not turn aside from it to the right hand or to the left,
* `Jdg 3:17` And he brought the tribute to Eglon king of Moab (Eglon was a *_very_* fat man).
* `Jdg 11:33` And he smote them from Aroer even as far as Minnith, even twenty cities, and to the plain of the vineyards, with a *_very_* great slaughter. Thus the children of Ammon were subdued before the children of Israel.
* `Jdg 11:35` And it came to pass when he saw her, that he rent his clothes, and said, "Alas, my daughter! You have brought me *_very_* low and you are one of those who trouble me. For I have opened my mouth to the LORD and I cannot go back."
* `Jdg 13:6` Then the woman came and told her husband, saying, "A man of God came to me, and his countenance was like the countenance of an angel of God, *_very_* awesome. But I did not ask him where he was from, neither did he tell me his name.
* `Jdg 15:18` And he was *_very_* thirsty and called on the LORD, and said, "You have given this great deliverance into the hand of your servant. And now shall I die by thirst and fall into the hand of the uncircumcised?"
* `Jdg 18:9` And they said, "Arise, so that we may go up against them. For we have seen the land, and behold, it is *_very_* good. And are you still? Do not be slothful to go and to enter to possess the land.
* `Rth 1:20` And she said to them, "Do not call me Naomi. Call me Mara, for the Almighty has dealt *_very_* bitterly with me.
* `1Sa 2:3` No longer talk so *_very_* proudly. Do not let arrogance come out of your mouth. For the LORD is a God of knowledge, and by him actions are weighed.
* `1Sa 2:17` Therefore, the sin of the young men was *_very_* great before the LORD, for men abhorred the offering of the LORD.
* `1Sa 2:22` Now Eli was *_very_* old and heard all that his sons did to all Israel and how they lay with the women who assembled at the door of the Tabernacle of the Congregation.
* `1Sa 4:10` So the Philistines fought, and Israel was smitten, and they each fled into his tent. And there was a *_very_* great slaughter, for there fell thirty thousand footmen of Israel.
* `1Sa 5:9` And it was so, that after they had carried it there, the hand of the LORD was against the city with a *_very_* great destruction, and he smote the men of the city both small and great, and they had emerods in their secret parts.
* `1Sa 5:11` So they sent and convened all the lords of the Philistines and said, "Send the ark of the God of Israel away, and let it go back to its own place so that it does not slay us and our people." For there was a deadly destruction throughout all the city. The hand of God was *_very_* heavy there.
* `1Sa 14:15` And there was a trembling in the host, in the field, and among all the people. The garrison and the raiders also trembled, and the earth quaked, and it was a *_very_* great trembling.
* `1Sa 14:20` And Saul and all the people who were with him assembled themselves and came to the battle. And behold, every man's sword was against his fellow and there was a *_very_* great confusion.
* `1Sa 14:31` And they smote the Philistines that day from Michmash to Ajalon. And the people were *_very_* faint.
* `1Sa 18:8` And Saul was *_very_* angry, and the saying displeased him. And he said, "They have ascribed to David tens of thousands, and to me they have ascribed thousands. And what can he have more but the kingdom?"
* `1Sa 18:15` Therefore, when Saul saw that he behaved himself *_very_* wisely, he was afraid of him.
* `1Sa 19:4` And Jonathan spoke good of David to Saul his father and said to him, "Do not let the king sin against his servant, against David, because he has not sinned against you and because his works have been *_very_* good toward you.
* `1Sa 20:7` If he says, 'It is well,' your servant will have peace. But if he is *_very_* angry, then be sure that evil is determined by him.
* `1Sa 23:22` Go, I pray you, prepare further, and know and see his place where his haunt is and who has seen him there, for it is told to me that he deals *_very_* subtly.
* `1Sa 25:2` And there was a man in Maon, whose possessions were in Carmel. And the man was *_very_* great, and he had three thousand sheep and one thousand goats. And he was shearing his sheep in Carmel.
* `1Sa 25:15` But the men were *_very_* good to us, and we were not hurt, neither did we miss anything as long as we were conversant with them when we were in the fields.
* `1Sa 25:36` And Abigail came to Nabal, and behold, he held a feast in his house, like the feast of a king. And Nabal's heart was merry within him, for he was *_very_* drunken. Therefore, she told him nothing at all until the morning light.
* `2Sa 1:26` I am distressed for you, my brother Jonathan. *_Very_* pleasant you have been to me. Your love to me was wonderful, passing the love of women.
* `2Sa 2:17` And there was a *_very_* severe battle that day. And Abner was defeated, along with the men of Israel, before the servants of David.
* `2Sa 3:8` Then Abner was *_very_* angry because of the words of Ish-bosheth and said, "Am I a dog's head of Judah? I show kindness this day to the house of Saul your father, to his brothers, and to his friends, and have not delivered you into the hand of David, and yet you charge me today with a fault concerning this woman.
* `2Sa 11:2` And it came to pass in an evening, that David arose from off his bed and walked upon the roof of the king's house. And from the roof he saw a woman washing herself. And the woman was *_very_* beautiful to look upon.
* `2Sa 12:2` The rich man had *_very_* numerous flocks and herds,
* `2Sa 12:15` And Nathan departed to his house. And the LORD struck the child whom Uriah's wife bore to David, and he was *_very_* sick.
* `2Sa 13:3` But Amnon had a friend whose name was Jonadab, the son of Shimeah David's brother. And Jonadab was a *_very_* subtle man.
* `2Sa 13:21` But when king David heard of all these things, he was *_very_* angry.
* `2Sa 18:17` And they took Absalom, cast him into a great pit in the forest, and laid a *_very_* great heap of stones upon him. And all Israel fled, each to his tent.
* `2Sa 19:32` Now Barzillai was a *_very_* aged man, even eighty years old, and he had provided the king with sustenance while he lay at Mahanaim, for he was a *_very_* great man.
* `2Sa 24:10` And David's heart smote him after he had numbered the people. And David said to the LORD, "I have sinned greatly in what I have done. And now, I implore you, O LORD, take away the iniquity of your servant, for I have done *_very_* foolishly."
* `1Ki 1:4` And the young woman was *_very_* fair, and she cherished the king and ministered to him, but the king did not know her.
* `1Ki 1:6` And his father had not displeased him at any time in saying, "Why have you done so?" And he also was a *_very_* handsome man. And his mother bore him after Absalom.
* `1Ki 1:15` And Bath-sheba went to the king into the chamber. And the king was *_very_* old, and Abishag the Shunamite ministered to the king.
* `1Ki 2:18` And Bath-sheba said, "*_Very_* well. I will speak for you to the king."
* `1Ki 7:47` And Solomon left all the vessels unweighed because they were *_very_* numerous, neither was the weight of the brass ascertained.
* `1Ki 10:2` And she came to Jerusalem with a *_very_* great train, with camels that bore spices, *_very_* much gold, and precious stones. And when she had come to Solomon, she spoke with him about all that was in her heart.
* `1Ki 10:10` And she gave the king one hundred and twenty talents of gold, a *_very_* great quantity of spices, and precious stones. Never again did there come such abundance of spices as these which the queen of Sheba gave to king Solomon.
* `1Ki 19:10` And he said, "I have been *_very_* jealous for the LORD God of hosts, for the children of Israel have forsaken your covenant, thrown down your altars, and slain your prophets with the sword. And I, only I, am left. And they seek my life to take it away."
* `1Ki 19:14` And he said, "I have been *_very_* jealous for the LORD God of hosts because the children of Israel have forsaken your covenant, thrown down your altars, and slain your prophets with the sword. And I, only I, am left. And they seek my life to take it away."
* `1Ki 21:26` And he did *_very_* abominably in following idols, according to all things that the Amorites did, whom the LORD cast out before the children of Israel.
* `2Ki 14:26` For the LORD saw the affliction of Israel, that it was *_very_* bitter, for there was no one shut up nor left at large, nor any helper for Israel.
* `2Ki 17:18` Therefore, the LORD was *_very_* angry with Israel and removed them out of his sight. There was none left but the tribe of Judah only.
* `2Ki 21:16` Moreover, Manasseh shed *_very_* much innocent blood until he had filled Jerusalem from one end to another, besides his sin with which he made Judah to sin in doing evil in the sight of the LORD.
* `1Ch 9:13` And their brothers, heads of the house of their fathers, one thousand seven hundred and sixty, *_very_* able men for the work of the service of the house of God.
* `1Ch 21:8` And David said to God, "I have sinned greatly because I have done this thing. But now, I implore you, put away the iniquity of your servant, for I have done *_very_* foolishly."
* `1Ch 21:13` And David said to Gad, "I am in great distress. Let me now fall into the hand of the LORD, for his mercies are *_very_* great. But do not let me fall into the hand of man."
* `1Ch 22:5` And David said, "Solomon my son is young and tender, and the house that is to be built for the LORD must be *_very_* magnificent for fame and glory throughout all countries. I will therefore now make preparation for it." So David made abundant preparation before his death.
* `1Ch 23:17` And the son of Eliezer was Rehabiah the chief. And Eliezer had no other sons, but the sons of Rehabiah were *_very_* many.
* `2Ch 7:8` Also at the same time Solomon kept the feast seven days, and all Israel with him, a *_very_* great congregation, from the entrance of Hamath to the river of Egypt.
* `2Ch 9:1` And when the queen of Sheba heard of the fame of Solomon, she came to prove Solomon with hard questions at Jerusalem, with a *_very_* great company and camels that bore spices, gold in abundance, and precious stones. And when she had come to Solomon, she spoke with him about all that was in her heart.
* `2Ch 16:8` Were the Cushites and the Lubims not a numerous army with *_very_* many chariots and horsemen? Yet, because you relied on the LORD, he delivered them into your hand.
* `2Ch 16:14` And they buried him in his own sepulchers which he had made for himself in the city of David, and laid him in the bed which was filled with sweet odors and diverse kinds of spices prepared by the perfumers' art. And they made a *_very_* great burning for him.
* `2Ch 20:35` And after this Jehoshaphat king of Judah joined himself with Ahaziah king of Israel, who did *_very_* wickedly.
* `2Ch 24:24` For the army of the Syrians came with a small company of men, and the LORD delivered a *_very_* great host into their hand because they had forsaken the LORD God of their fathers. Thus they executed judgment against Joash.
* `2Ch 30:13` And many people assembled at Jerusalem to keep the feast of unleavened bread in the second month, a *_very_* great congregation.
* `2Ch 32:27` And Hezekiah had *_very_* great riches and honor. And he made himself treasuries for silver, for gold, for precious stones, for spices, for shields, and for all manner of pleasant jewels,
* `2Ch 33:14` Now after this, he built a wall outside the city of David on the west side of Gihon, in the valley, even to the entrance at the fish-gate, and he encircled Ophel with it and raised it up a *_very_* great height. And he put captains of war in all the fortified cities of Judah.
* `2Ch 36:14` Moreover, all the chief of the priests and the people transgressed *_very_* much after all the abominations of the heathen and polluted the house of the LORD which he had hallowed in Jerusalem.
* `Ezr 10:1` Now when Ezra had prayed and when he had confessed, weeping and casting himself down before the house of God, there assembled to him out of Israel a *_very_* great congregation of men and women and children, for the people wept *_very_* bitterly.
* `Neh 1:7` We have dealt *_very_* corruptly against you and have not kept the commandments, nor the statutes, nor the judgments which you commanded your servant Moses.
* `Neh 2:2` Therefore, the king said to me, "Why is your countenance sad, seeing you are not sick? This is nothing but sorrow of heart." Then I was *_very_* greatly afraid,
* `Neh 4:7` But it came to pass, when Sanballat, Tobiah, the Arabians, the Ammonites, and the Ashdodites heard that the walls of Jerusalem were set up and that the breaches began to be stopped, they were *_very_* angry,
* `Neh 5:6` And I was *_very_* angry when I heard their cry and these words.
* `Neh 8:17` And all the congregation of those who had returned from the captivity made booths and sat under the booths, for since the days of Joshua the son of Nun to that day, the children of Israel had not done so. And there was *_very_* great gladness.
* `Est 1:12` But the queen Vashti refused to come at the king's commandment by his chamberlains. Therefore, the king was *_very_* angry and his anger burned in him.
* `Job 1:3` His substance also was seven thousand sheep, three thousand camels, five hundred yoke of oxen, five hundred female donkeys, and a *_very_* great household. This man was the greatest of all the men of the east.
* `Job 2:13` Thus they sat down with him upon the ground for seven days and seven nights, and no one spoke a word to him, for they saw that his grief was *_very_* great.
* `Job 15:10` With us are both the gray headed and *_very_* aged men, much older than your father.
* `Job 32:6` And Elihu the son of Barachel the Buzite answered and said, "I am young, and you are *_very_* old; therefore, I was afraid and dared not show you my opinion.
* `Psa 35:8` Let destruction come upon him unexpectedly, and let his net that he has hid catch himself. Into that *_very_* destruction let him fall.
* `Psa 46:1` [To the Chief Musician for the Sons of Korah. A Song upon Alamoth.] God is our refuge and strength, a *_very_* present help in trouble.
* `Psa 50:3` Our God shall come and shall not keep silence. A fire shall devour before him and it shall be *_very_* tempestuous around him.
* `Psa 71:19` Your righteousness also, O God, is *_very_* high, who have done great things. O God, who is like you?
* `Psa 79:8` O do not hold former iniquities against us. Let your tender mercies speedily meet us, for we are brought *_very_* low.
* `Psa 89:2` For I have said, "Mercy shall be built up forever. You will establish your faithfulness in the *_very_* heavens."
* `Psa 92:5` O LORD, how great your works are! And your thoughts are *_very_* deep.
* `Psa 93:5` Your testimonies are *_very_* sure. Holiness is suitable for your house, O LORD, forever.
* `Psa 104:1` Bless the LORD, O my soul. O LORD my God, you are *_very_* great. You are clothed with honor and majesty,
* `Psa 105:12` When they were a few men in number, even *_very_* few, and strangers in it.
* `Psa 119:107` I am afflicted *_very_* much. Revive me, O LORD, according to your word.
* `Psa 119:138` Your testimonies that you have commanded are righteous and *_very_* faithful.
* `Psa 119:140` Your word is *_very_* pure; therefore, your servant loves it.
* `Psa 142:6` Attend to my cry, for I am brought *_very_* low. Deliver me from my persecutors, for they are stronger than I am.
* `Psa 146:4` His breath goes forth and he returns to the earth. In that *_very_* day his thoughts perish.
* `Psa 147:15` He sends forth his commandment upon the earth. His word runs *_very_* swiftly.
* `Pro 27:15` A continual dropping on a *_very_* rainy day and a contentious woman are alike.
* `Pro 30:24` There are four things which are little upon the earth, but they are *_very_* wise:
* `Isa 1:9` Unless the LORD of hosts had left to us a *_very_* small remnant, we should have been like Sodom, we should have been like Gomorrah.
* `Isa 5:1` Now I will sing to my well-beloved a song of my beloved concerning his vineyard. My well-beloved has a vineyard on a *_very_* fruitful hill.
* `Isa 10:25` For yet a *_very_* little while and the indignation shall cease, and my anger will turn to their destruction.
* `Isa 10:32` This *_very_* day he shall remain at Nob. He shall shake his hand against the mountain of the daughter of Zion, the hill of Jerusalem.
* `Isa 16:6` We have heard of the pride of Moab, that he is *_very_* proud, even of his haughtiness, his pride, and his wrath. But his lies shall not be so.
* `Isa 16:14` But now the LORD has spoken, saying, "Within three years, as the years of a hireling, and the glory of Moab shall be despised with all that great multitude, and the remnant shall be *_very_* small and feeble."
* `Isa 24:16` From the uttermost part of the earth we have heard songs, even glory to the righteous. But I said, "My leanness, my leanness, woe to me! The treacherous dealers have dealt treacherously. Indeed, the treacherous dealers have dealt *_very_* treacherously."
* `Isa 29:17` Is it not yet a *_very_* little while, and Lebanon shall be turned into a fruitful field, and the fruitful field shall be esteemed as a forest?
* `Isa 30:19` For the people shall dwell in Zion at Jerusalem. You shall no longer weep. He will be *_very_* gracious to you at the voice of your cry. When he hears it, he will answer you.
* `Isa 31:1` Woe to those who go down to Egypt for help and rely on horses, and trust in chariots because they are many, and in horsemen because they are *_very_* strong, but they do not look to the Holy One of Israel, neither seek the LORD!
* `Isa 33:17` Your eyes shall see the king in his beauty. They shall behold the land that is *_very_* far off.
* `Isa 40:15` Behold, the nations are like a drop in a bucket and are counted as the small dust on the balance. Behold, he takes up the islands like a *_very_* little thing.
* `Isa 47:6` I was angry with my people. I have polluted my inheritance and given them into your hand. You showed them no mercy. Upon the ancient you have *_very_* heavily laid your yoke.
* `Isa 48:8` Indeed, you did not hear. Indeed, you did not know. Indeed, from that time your ear was not opened. For I knew that you would deal *_very_* treacherously and were called a transgressor from the womb.
* `Isa 52:13` Behold, my servant shall deal prudently. He shall be exalted and extolled, and be *_very_* high.
* `Isa 64:9` Do not be *_very_* angry, O LORD, neither remember iniquity forever. Behold, see, we implore you, we are all your people.
* `Jer 2:12` Be astonished, O heavens, at this, and be horribly afraid, be *_very_* desolate," says the LORD.
* `Jer 4:19` My anguish, my anguish! I am pained at my *_very_* heart. My heart makes a noise in me. I cannot hold my peace because you have heard, O my soul, the sound of the trumpet, the alarm of war.
* `Jer 5:11` For the house of Israel and the house of Judah have dealt *_very_* treacherously against me," says the LORD.
* `Jer 12:1` You are righteous, O LORD, when I plead with you. Yet let me speak with you about your judgments. Why does the way of the wicked prosper? Why are they all happy who deal *_very_* treacherously?
* `Jer 14:17` "Therefore, you shall say this word to them: 'Let my eyes run down with tears night and day, and do not let them cease, for the virgin daughter of my people is broken with a great breach, with a *_very_* grievous blow.
* `Jer 18:13` "Therefore, thus says the LORD: 'Ask now among the heathen, "Who has heard such things?" The virgin of Israel has done a *_very_* horrible thing.
* `Jer 20:15` Cursed is the man who brought tidings to my father, saying, "A male child is born to you," making him *_very_* glad.
* `Jer 24:2` One basket had *_very_* good figs, even like the figs that are first ripe, and the other basket had *_very_* poor figs, which could not be eaten they were so bad.
* `Jer 24:3` Then the LORD said to me, "What do you see, Jeremiah?" And I said, "Figs. The good figs, *_very_* good, and the bad, *_very_* bad, which cannot be eaten they are so bad."
* `Jer 27:7` And all nations shall serve him, his son, and his son's son until the *_very_* time of his land comes. And then many nations and great kings shall bring him into subjection.
* `Jer 46:20` Egypt is like a *_very_* fair heifer, but destruction comes. It comes out of the north.
* `Lam 5:22` But you have utterly rejected us. You are *_very_* angry against us.
* `Ezk 2:3` And he said to me, "Son of man, I send you to the children of Israel, to a rebellious nation that has rebelled against me. They and their fathers have transgressed against me, even to this *_very_* day,
* `Ezk 16:47` Yet you have not walked after their ways nor done according to their abominations. But as if that were a *_very_* little thing, you were corrupted more than they were in all your ways.
* `Ezk 24:2` "Son of man, write for yourself the name of the day, even of this *_very_* day. The king of Babylon set himself against Jerusalem this *_very_* day.
* `Ezk 27:25` "The ships of Tarshish sang of you in your market. And you were replenished and made *_very_* glorious in the midst of the seas.
* `Ezk 33:32` And behold, you are to them like a *_very_* lovely song by one who has a pleasant voice and can play well on an instrument, for they hear your words, but they do not perform them.
* `Ezk 37:2` And he caused me to pass by them around, and behold, there were *_very_* many in the open valley, and behold, they were *_very_* dry.
* `Ezk 40:2` In the visions of God he brought me into the land of Israel and set me upon a *_very_* high mountain, by which was as the frame of a city on the south.
* `Ezk 47:7` Now when I had returned, behold, at the bank of the river were *_very_* many trees on one side and on the other.
* `Ezk 47:9` And it shall come to pass, that wherever the rivers come, every living creature that swarms shall live. And there shall be a *_very_* great multitude of fish, because these waters shall come there, for they shall be healed, and everything shall live where the river comes.
* `Ezk 47:10` And it shall come to pass, that the fishermen shall stand upon it from En-gedi even to En-eglaim. They shall be a place to spread forth nets. Their fish shall be according to their kinds, as the fish of the Great Sea, *_very_* numerous.
* `Dan 2:12` For this cause the king was angry and *_very_* furious, and commanded to destroy all the wise men of Babylon.
* `Dan 3:15` Now if you are ready at the time you hear the sound of the horn, flute, harp, sackbut, psaltery, bagpipe, and all kinds of music, to fall down and worship the image which I have made, *_very_* well. But if you do not worship, you shall be cast the same hour into the midst of a burning fiery furnace. And who is that God who shall deliver you out of my hands?"
* `Dan 6:19` Then the king arose *_very_* early in the morning and went in haste to the den of lions.
* `Dan 7:20` And of the ten horns that were on his head, and of the other which came up and before which three fell, even of the horn that had eyes and a mouth that spoke *_very_* great things, whose look was more stout than his fellows.
* `Dan 8:8` Therefore, the male goat became *_very_* great, and when he was strong, the great horn was broken and in its stead four notable ones came up toward the four winds of heaven.
* `Dan 11:25` And he shall stir up his power and his courage against the king of the south with a great army. And the king of the south shall be stirred up to battle with a *_very_* great and mighty army, but he shall not stand, for they shall devise plans against him.
* `Joe 2:11` And the LORD will utter his voice before his army, for his camp is *_very_* great, and he is strong who executes his word. For the day of the LORD is great and *_very_* terrible. Who can endure it?
* `Amo 5:20` Shall the day of the LORD not be darkness rather than light, even *_very_* dark and no brightness in it?
* `Jna 4:1` But it displeased Jonah exceedingly and he was *_very_* angry.
* `Zch 1:15` And I am *_very_* greatly displeased with the heathen who are at ease. For I was but a little displeased, and they helped forward the affliction."
* `Zch 9:2` And also Hamath, which borders by it, and Tyre and Zidon, because they are *_very_* wise.
* `Zch 9:5` Ashkelon shall see it and fear. Gaza shall also see it and be *_very_* sorrowful, as will Ekron, for her expectation shall be ashamed. And the king shall perish from Gaza, and Ashkelon shall not be inhabited.
* `Zch 14:4` And his feet will stand in that day upon the Mount of Olives, which is before Jerusalem on the east. And the Mount of Olives shall cleave in the midst of it toward the east and toward the west, and there shall be a *_very_* great valley. Half of the mountain shall move toward the north and half of it toward the south.
* `Mth 15:28` Then Jesus answered and said to her, "O woman, your faith is great. It shall be to you even as you wish." And her daughter was healed from that *_very_* hour.
* `Mth 17:18` And Jesus rebuked the demon, and he departed out of him. And the child was cured from that *_very_* hour.
* `Mth 18:31` So when his fellow-servants saw what was done, they were *_very_* sorry and came and told to their lord all that was done.
* `Mth 21:8` And a *_very_* great multitude spread their garments in the way. Others cut down branches from the trees and spread them in the way.
* `Mth 24:24` For false Christs and false prophets will arise and will show great signs and wonders in such a way that, if it were possible, they would deceive the *_very_* elect.
* `Mth 26:7` A woman having an alabaster vial of *_very_* precious ointment came to him and poured it on his head as he sat at the table.
* `Mth 26:37` And he took with him Peter and the two sons of Zebedee and began to be sorrowful and *_very_* heavy.
* `Mrk 6:20` For Herod feared John and kept him safe, knowing that he was a just and holy man. And when he heard him, he was *_very_* perplexed, yet he heard him gladly.
* `Mrk 8:1` In those days when the multitude was *_very_* great and had nothing to eat, Jesus called his disciples and says to them,
* `Mrk 14:3` And being in Bethany, in the house of Simon the leper, as he sat at the table, there came a woman having an alabaster vial of ointment of spikenard, *_very_* precious, and she broke the vial and poured it on his head.
* `Mrk 14:33` And he takes with him Peter, James, and John and began to be greatly amazed and to be *_very_* heavy,
* `Mrk 16:2` And *_very_* early in the morning, the first day of the week, they came to the sepulcher at the rising of the sun.
* `Mrk 16:4` And when they looked, they saw that the stone was rolled away—for it was *_very_* large.
* `Luk 1:3` It seemed good to me also, having had perfect understanding of all things from the *_very_* first, to write to you in order, most excellent Theophilus,
* `Luk 9:5` And whoever will not receive you, when you go out of that city, shake off the *_very_* dust from your feet for a testimony against them."
* `Luk 10:11` 'Even the *_very_* dust of your city which cleaves on us, we wipe off against you. Nevertheless, be sure of this, that the kingdom of God has come near to you.'
* `Luk 12:59` I tell you, you shall not depart from there until you have paid the *_very_* last mite."
* `Luk 18:23` And when he heard this, he was *_very_* sorrowful, for he was *_very_* rich.
* `Luk 18:24` And when Jesus saw that he was *_very_* sorrowful, he said, "How hardly those who have riches will enter into the kingdom of God!
* `Luk 19:17` And he said to him, 'Well done, good servant. Because you have been faithful in a *_very_* little, you have authority over ten cities.'
* `Luk 19:48` And could not find what they might do, for all the people were *_very_* attentive to hear him.
* `Luk 24:1` Now upon the first day of the week, *_very_* early in the morning, they came to the sepulcher bringing the spices which they had prepared, and there were others with them.
* `Jhn 7:26` But behold, he speaks boldly and they say nothing to him. Do the rulers know indeed that this is the *_very_* Christ?
* `Jhn 8:4` They say to him, "Master, this woman was taken in adultery, in the *_very_* act.
* `Jhn 12:3` Then Mary took a pound of *_very_* costly ointment of spikenard, anointed the feet of Jesus, and wiped his feet with her hair. And the house was filled with the odor of the ointment.
* `Jhn 14:11` Believe me that I am in the Father and the Father in me, or else believe me for the *_very_* works' sake.
* `Act 10:10` And he became *_very_* hungry and wished to eat, but while they made ready, he fell into a trance
* `Act 24:2` And when he was called forth, Tertullus began to accuse him, saying, "Seeing that by you we enjoy great quietness and that *_very_* worthy deeds are done to this nation by your providence,
* `Act 25:10` Then Paul said, "I stand at Caesar's tribunal where I ought to be judged. I have done no wrong to the Jews as you *_very_* well know.
* `Rom 10:20` But Isaiah is *_very_* bold, and says, "I was found by those who did not seek me. I was made manifest to those who did not ask for me."
* `Rom 13:6` For because of this you also pay tribute, for they are God's ministers, attending continually upon this *_very_* thing.
* `1Co 4:3` But with me it is a *_very_* small thing that I should be judged by you or by man's judgment. Indeed, I do not judge my own self.
* `2Co 7:11` For behold this *_very_* thing, that you sorrowed after a godly manner, what it has wrought in you: what carefulness, what clearing of yourselves, what indignation, what fear, what vehement desire, what zeal, and what avenging! In all things you have approved yourselves to be clear in this matter.
* `2Co 9:2` For I know the forwardness of your mind, for which I boast about you to those of Macedonia that Achaia has been ready since last year. And your zeal has incited *_very_* many.
* `2Co 11:5` For I suppose I was not at all inferior to the *_very_* greatest apostles.
* `2Co 12:11` I have become a fool in glorying. You have compelled me. For I ought to have been commended by you, for in no way am I inferior to the *_very_* greatest apostles, though I am nothing.
* `2Co 12:15` And I will *_very_* gladly spend and be spent for you, though the more abundantly I love you, the less I am loved.
* `Phl 1:6` Being confident of this *_very_* thing, that he who has begun a good work in you will perform it until the day of Jesus Christ,
* `1Th 5:13` And to esteem them *_very_* highly in love for their work's sake. And be at peace among yourselves.
* `1Th 5:23` And may the *_very_* God of peace sanctify you wholly. And may your whole spirit, soul, and body be preserved blameless to the coming of our Lord Jesus Christ.
* `2Ti 1:17` But, when he was in Rome, he sought me out *_very_* diligently and found me.
* `2Ti 1:18` May the Lord grant to him that he may find mercy from the Lord in that day. And in all that he ministered to me at Ephesus, you know *_very_* well.
* `Phm 1:8` Therefore, though I might be *_very_* bold in Christ to enjoin you to that which is appropriate,
* `Heb 10:1` For the law, having a shadow of good things to come, and not the *_very_* image of the things, can never with those sacrifices, which they offered year by year continually, make perfect those who draw near.
* `Jms 3:4` Behold also the ships: though they are so great and are driven by fierce winds, yet they are directed with a *_very_* small helm, wherever the helmsman wills.
* `Jms 5:11` Behold, we count those happy who endure. You have heard of the patience of Job and have seen the outcome from the Lord, that the Lord is *_very_* compassionate and full of tender mercy.

_244 verses containing VERY_

== VESSEL

* `Lev 6:28` But the earthen *_vessel_* in which it is boiled shall be broken. And if it is boiled in a brazen pot, it shall be both scoured and rinsed in water.
* `Lev 11:32` And upon whatever any of them falls when they are dead, it shall be unclean, whether it is any *_vessel_* of wood, clothing, skin, or sack, whatever *_vessel_* it is, in which any work is done, it must be put into water, and it shall be unclean until the evening. Then it shall be cleansed.
* `Lev 11:33` And every earthen *_vessel_* into which any of them falls, whatever is in it shall be unclean and you shall break it.
* `Lev 11:34` Of all food which may be eaten, that on which such water comes shall be unclean. And all drink that may be drank in every such *_vessel_* shall be unclean.
* `Lev 14:5` And the priest shall command that one of the birds be killed in an earthen *_vessel_* over running water.
* `Lev 14:50` And he shall kill one of the birds in an earthen *_vessel_* over running water,
* `Lev 15:12` And the *_vessel_* of earth that he who has the issue touches shall be broken, and every *_vessel_* of wood shall be rinsed in water.
* `Num 5:17` And the priest shall take holy water in an earthen *_vessel_*, and some of the dust that is on the floor of the tabernacle the priest shall take and put it into the water.
* `Num 19:15` And every open *_vessel_* which has no covering bound upon it is unclean.
* `Num 19:17` And for an unclean person they shall take some of the ashes of the burnt heifer of purification for sin, and running water shall be put to it in a *_vessel_*.
* `Deu 23:24` "When you come into your neighbor's vineyard, you may satisfy your appetite with grapes at your own pleasure, but you shall not put any in your *_vessel_*.
* `1Sa 21:5` And David answered the priest and said to him, "Of a truth women have been kept from us about these three days since I came out, and the vessels of the young men are holy, and the bread is in a common manner, even though it was sanctified this day in the *_vessel_*."
* `1Ki 17:10` So he arose and went to Zarephath. And when he came to the gate of the city, behold, the widow woman was there gathering sticks. And he called to her and said, "Bring me, I pray you, a little water in a *_vessel_* that I may drink."
* `2Ki 4:6` And it came to pass, when the vessels were full, that she said to her son, "Bring me another *_vessel_*." And he said to her, "There is not another *_vessel_*." And the oil stopped.
* `Psa 2:9` You shall break them with a rod of iron. You shall dash them in pieces like a potter's *_vessel_*.'"
* `Psa 31:12` I am forgotten like a dead man out of mind. I am like a broken *_vessel_*.
* `Pro 25:4` Take away the dross from the silver, and there shall come forth a *_vessel_* for the refiner.
* `Isa 30:14` And he shall break it as the breaking of the potter's *_vessel_*, breaking it in pieces without sparing, so that there shall not be found in its bursting a piece to take fire from the hearth or to take water out of the pit."
* `Isa 66:20` And they shall bring all your brothers for an offering to the LORD out of all nations upon horses, in chariots, in litters, upon mules, and upon swift beasts, to my holy mountain Jerusalem," says the LORD, "as the children of Israel bring an offering in a clean *_vessel_* into the house of the LORD.
* `Jer 18:4` And the *_vessel_* that he made of clay was marred in the hand of the potter. So he made it again another *_vessel_*, as it seemed good to the potter to make it.
* `Jer 19:11` And shall say to them, 'Thus says the LORD of hosts: "Even so I will break this people and this city, as one breaks a potter's *_vessel_* that cannot be made whole again. And they shall bury them in Tophet until there is no place to bury.
* `Jer 22:28` "Is this man Coniah a despised broken idol? Is he a *_vessel_* in which there is no pleasure? Why are they cast out—he and his offspring—and are cast into a land which they do not know?
* `Jer 25:34` Howl, you shepherds, and cry, and wallow yourselves in the ashes, you principal of the flock, for the days of your slaughter and of your dispersions are accomplished, and you shall fall like a precious *_vessel_*.
* `Jer 32:14` 'Thus says the LORD of hosts, the God of Israel: "Take these evidences, this evidence of the purchase, both that which is sealed and this evidence which is open, and put them in an earthen *_vessel_* so that they may remain many days."
* `Jer 48:11` Moab has been at ease from his youth, and he has settled on his dregs and has not been emptied from *_vessel_* to *_vessel_*, neither has he gone into captivity. Therefore, his taste remained in him, and his scent is not changed.
* `Jer 48:38` There shall be lamentation generally upon all the house-tops of Moab and in its streets, for I have broken Moab like a *_vessel_* in which there is no pleasure," says the LORD.
* `Jer 51:34` "Nebuchadnezzar the king of Babylon has devoured me. He has crushed me. He has made me an empty *_vessel_*. He has swallowed me up like a sea-monster. He has filled his belly with my delicacies. He has cast me out.
* `Ezk 4:9` "Also take wheat, barley, beans, lentils, millet, and spelt, put them in one *_vessel_*, and make yourself bread from them. According to the number of the days that you shall lie upon your side, three hundred and ninety days, you shall eat it.
* `Ezk 15:3` Shall wood be taken from it to do any work? Or will men take a pin from it to hang any *_vessel_* upon it?
* `Hos 8:8` Israel is swallowed up. Now they shall be among the Gentiles as a *_vessel_* in which there is no pleasure.
* `Mrk 11:16` And would not allow any man to carry any *_vessel_* through the temple.
* `Luk 8:16` "No man, when he has lit a candle, covers it with a *_vessel_* or puts it under a bed, but sets it on a candlestick so that those who enter in may see the light.
* `Jhn 19:29` Now there was set a *_vessel_* full of vinegar. And they filled a sponge with vinegar, put it upon hyssop, and put it to his mouth.
* `Act 9:15` But the Lord said to him, "Go, for he is a chosen *_vessel_* for me to bear my name before the Gentiles, kings, and the children of Israel.
* `Act 10:11` And saw heaven opened and a certain *_vessel_* descending to him like a great sheet knit at the four corners being let down to the earth,
* `Act 10:16` This was done three times, and the *_vessel_* was received back into heaven.
* `Act 11:5` "I was in the city of Joppa praying, and in a trance I saw a vision: a certain *_vessel_* descending, like a great sheet, let down from heaven by four corners, and it even came to me,
* `Rom 9:21` Does the potter not have power over the clay of the same lump to make one *_vessel_* to honor and another to dishonor?
* `1Th 4:4` That each of you should know how to possess his *_vessel_* in sanctification and honor,
* `2Ti 2:21` If a man therefore will cleanse himself from these, he will be a *_vessel_* for honor, sanctified and profitable for the master's use, and prepared for every good work.
* `1Pe 3:7` Likewise, husbands, dwell with them according to knowledge, giving honor to the wife as to the weaker *_vessel_* and as being heirs together of the grace of life, so that your prayers are not hindered.

_41 verses containing VESSEL_

== VESSELS

* `Gen 43:11` And their father Israel said to them, "If it must be so now, do this: take some of the best fruits in the land in your *_vessels_* and carry to the man a present—a little balm, a little honey, spices, myrrh, nuts, and almonds.
* `Exo 7:19` And the LORD spoke to Moses, "Say to Aaron, 'Take your rod and stretch out your hand upon the waters of Egypt, upon their streams, upon their rivers, upon their ponds, and upon all their pools of water, so that they may become blood and that there may be blood throughout all the land of Egypt, both in *_vessels_* of wood and in *_vessels_* of stone.'"
* `Exo 25:39` From a talent of pure gold he shall make it, with all these *_vessels_*.
* `Exo 27:3` And you shall make its pans to receive its ashes, its shovels, its basins, its flesh-hooks, and its fire-pans. All its *_vessels_* you shall make of brass.
* `Exo 27:19` All the *_vessels_* of the tabernacle in all the service thereof, all the pins thereof, and all the pins of the court, shall be of brass.
* `Exo 30:27` The table and all its *_vessels_*, the candlestick and its *_vessels_*, the altar of incense,
* `Exo 30:28` The altar of burnt-offering with all its *_vessels_*, and the basin and its foot.
* `Exo 31:7` The Tabernacle of the Congregation, the ark of the testimony, the mercy-seat that is upon it, all the *_vessels_* of the tabernacle,
* `Exo 31:8` The table and its *_vessels_*, the pure candlestick with all its *_vessels_*, the altar of incense,
* `Exo 31:9` The altar of burnt-offering with all its *_vessels_*, the basin and its foot,
* `Exo 35:13` The table and its staffs, all its *_vessels_*, and the show-bread;
* `Exo 35:14` The candlestick for the light and its *_vessels_*, its lamps, and the oil for the light;
* `Exo 35:16` The altar of burnt-offering with its brazen grate, its staffs, and all its *_vessels_*; the basin and its foot;
* `Exo 37:16` And he made the *_vessels_* which were upon the table, its dishes, its spoons, its bowls, and its covers to cover with, of pure gold.
* `Exo 37:24` Of a talent of pure gold he made it and all its *_vessels_*.
* `Exo 38:3` And he made all the *_vessels_* of the altar: the pots, the shovels, the basins, the flesh-hooks, and the fire-pans. All its *_vessels_* he made of brass.
* `Exo 38:30` And with this he made the sockets to the door of the Tabernacle of the Congregation, the brazen altar, the brazen grate for it, all the *_vessels_* of the altar,
* `Exo 39:33` And they brought the tabernacle to Moses, the tent, all its *_vessels_*, its buttons, its boards, its bars, its pillars, and its sockets,
* `Exo 39:36` The table, all its *_vessels_*, the show-bread,
* `Exo 39:37` The pure candlestick with its lamps, even with the lamps to be set in order, all its *_vessels_*, the oil for light,
* `Exo 39:39` The brazen altar and its grate of brass, its staffs, and all its *_vessels_*, the basin and its foot,
* `Exo 39:40` The hangings of the court, its pillars, and its sockets, and the hanging for the court-gate, its cords, and its pins, and all the *_vessels_* of the service of the tabernacle, for the tent of the congregation,
* `Exo 40:9` And you shall take the anointing oil and anoint the tabernacle and all that is in it, and shall hallow it and all its *_vessels_*, and it shall be holy.
* `Exo 40:10` And you shall anoint the altar of the burnt-offering and all its *_vessels_* and sanctify the altar, and it shall be an altar most holy.
* `Lev 8:11` And he sprinkled part of it upon the altar seven times and anointed the altar and all its *_vessels_*, both the basin and its foot, to sanctify them.
* `Num 1:50` But you shall appoint the Levites over the tabernacle of testimony, over all its *_vessels_*, and over all things that belong to it. They shall bear the tabernacle and all its *_vessels_*, and they shall minister to it and encamp around the tabernacle.
* `Num 3:31` And their charge shall be the ark, the table, the candlestick, the altars, the *_vessels_* of the sanctuary with which they minister, the hanging, and all its service.
* `Num 3:36` And under the custody and charge of the sons of Merari shall be the boards of the tabernacle, its bars, its pillars, its sockets, all its *_vessels_*, all its service,
* `Num 4:9` And they shall take a cloth of blue and cover the candlestick for the light, its lamps, its tongs, its snuff-dishes, and all its oil *_vessels_*, with which they minister to it.
* `Num 4:10` And they shall put it and all its *_vessels_* within a covering of badgers' skins and put it upon a bar.
* `Num 4:14` And they shall put upon it all its *_vessels_*, with which they minister there, even the censers, the flesh-hooks, the shovels, and the basins, all the *_vessels_* of the altar, and they shall spread upon it a covering of badgers' skins and put in its staffs.
* `Num 4:15` And when Aaron and his sons have made an end of covering the sanctuary and all the *_vessels_* of the sanctuary as the camp is to move forward, after that, the sons of Kohath shall come to bear it, but they shall not touch any holy thing, lest they die. These things are the burden of the sons of Kohath in the Tabernacle of the Congregation.
* `Num 4:16` "And to the office of Eleazar the son of Aaron the priest pertain the oil for the light, the sweet incense, the daily food-offering, the anointing oil, the oversight of all the tabernacle, and of all that is in it, in the sanctuary, and in its *_vessels_*."
* `Num 7:1` And it came to pass on the day that Moses had fully set up the tabernacle, had anointed it, and sanctified it and all its instruments—both the altar and all its *_vessels_*—and had anointed them and sanctified them,
* `Num 7:85` Each charger of silver weighing one hundred and thirty shekels, each bowl seventy; all the silver *_vessels_* weighed two thousand and four hundred shekels, after the shekel of the sanctuary;
* `Num 18:3` And they shall keep your charge and the charge of all the tabernacle. Only they shall not come near the *_vessels_* of the sanctuary and the altar so that they do not die—neither they nor you.
* `Num 19:18` And a clean person shall take hyssop, dip it in the water, and sprinkle it upon the tent, upon all the *_vessels_*, upon the persons who were there, and upon him who touched a bone, someone slain, someone dead, or a grave.
* `Jsh 6:19` But all the silver, gold, and *_vessels_* of brass and iron are consecrated to the LORD. They shall come into the treasury of the LORD."
* `Jsh 6:24` And they burnt the city and all that was in it with fire. Only the silver, the gold, and the *_vessels_* of brass and of iron, they put into the treasury of the house of the LORD.
* `Rth 2:9` Let your eyes be on the field that they are reaping, and go after them. Have I not charged the young men that they shall not touch you? And when you are thirsty go to the *_vessels_* and drink of that which the young men have drawn."
* `1Sa 9:7` Then Saul said to his servant, "But behold, if we go, what shall we bring to the man? For the bread is spent in our *_vessels_* and there is not a present to bring to the man of God. What do we have?"
* `1Sa 10:22` Therefore, they inquired of the LORD further: "Is there still anyone to come here?" And the LORD answered, "Behold, he has hid himself among the *_vessels_*."
* `1Sa 21:5` And David answered the priest and said to him, "Of a truth women have been kept from us about these three days since I came out, and the *_vessels_* of the young men are holy, and the bread is in a common manner, even though it was sanctified this day in the vessel."
* `2Sa 8:10` Toi sent Joram his son to king David to salute him and to bless him, because he had fought against Hadadezer and smitten him (for Hadadezer had wars with Toi). And Joram brought with him *_vessels_* of silver, *_vessels_* of gold, and *_vessels_* of brass,
* `2Sa 17:28` Brought beds, basins, earthen *_vessels_*, wheat, barley, flour, parched grain, beans, lentils, parched pulse,
* `1Ki 7:45` And the pots, the shovels, and the basins. And all these *_vessels_* which Hiram made for king Solomon for the house of the LORD were of bright brass.
* `1Ki 7:47` And Solomon left all the *_vessels_* unweighed because they were very numerous, neither was the weight of the brass ascertained.
* `1Ki 7:48` And Solomon made all the *_vessels_* that pertained to the house of the LORD: the altar of gold; the table of gold, upon which was the show-bread;
* `1Ki 7:51` So all the work that king Solomon made for the house of the LORD was finished. And Solomon brought in the things which David his father had dedicated. Even the silver, the gold, and the *_vessels_* he placed among the treasures of the house of the LORD.
* `1Ki 8:4` And they brought the ark of the LORD, the Tabernacle of the Congregation, and all the holy *_vessels_* that were in the tabernacle, even those the priests and the Levites brought.
* `1Ki 10:21` And all king Solomon's drinking *_vessels_* were of gold, and all the *_vessels_* of the house of the forest of Lebanon were of pure gold. None were of silver, for it was nothing accounted of in the days of Solomon.
* `1Ki 10:25` And every man brought his present: *_vessels_* of silver, *_vessels_* of gold, garments, armor, spices, horses, and mules—a rate year by year.
* `1Ki 15:15` And he brought the things which his father had dedicated and the things which he himself had dedicated into the house of the LORD: silver, gold, and *_vessels_*.
* `2Ki 4:3` Then he said, "Go, borrow *_vessels_* abroad from all your neighbors, even empty *_vessels_*. Do not borrow a few.
* `2Ki 4:4` And when you have come in, you shall shut the door upon you and upon your sons, and shall pour out into all those *_vessels_* and set aside that which is full."
* `2Ki 4:5` So she went from him and shut the door upon her and upon her sons, who brought the *_vessels_* to her, and she poured out.
* `2Ki 4:6` And it came to pass, when the *_vessels_* were full, that she said to her son, "Bring me another vessel." And he said to her, "There is not another vessel." And the oil stopped.
* `2Ki 7:15` And they went after them to the Jordan. And behold, the whole way was full of garments and *_vessels_*, which the Syrians had cast away in their haste. And the messengers returned and told the king.
* `2Ki 12:13` Yet, there were not made for the house of the LORD bowls of silver, snuffers, basins, trumpets, any *_vessels_* of gold, or *_vessels_* of silver of the money that was brought into the house of the LORD.
* `2Ki 14:14` And he took all the gold and silver, all the *_vessels_* found in the house of the LORD and in the treasures of the king's house, and hostages, and returned to Samaria.
* `2Ki 23:4` And the king commanded Hilkiah the high priest, the priests of the second order, and the keepers of the door to bring forth out of the temple of the LORD all the *_vessels_* that were made for Baal, for the grove, and for all the host of heaven. And he burned them outside Jerusalem in the fields of Kidron and carried their ashes to Beth-el.
* `2Ki 24:13` And he carried out from there all the treasures of the house of the LORD and the treasures of the king's house, and cut in pieces all the *_vessels_* of gold which Solomon king of Israel had made in the temple of the LORD, as the LORD had said.
* `2Ki 25:14` And the pots, the shovels, the snuffers, the spoons, and all the *_vessels_* of brass with which they ministered, they took away.
* `2Ki 25:16` The two pillars, one sea, and the bases which Solomon had made for the house of the LORD, the brass of all these *_vessels_* was without weight.
* `1Ch 9:28` And some of them had the charge of the ministering *_vessels_*, that they should bring them in and out by number.
* `1Ch 9:29` Some of them also were appointed to oversee the *_vessels_*, all the instruments of the sanctuary, the fine flour, the wine, the oil, the frankincense, and the spices.
* `1Ch 18:8` Likewise, from Tibhath and from Chun, cities of Hadarezer, David brought large amounts of brass, with which Solomon made the brazen sea, the pillars, and the *_vessels_* of brass.
* `1Ch 18:10` He sent Hadoram his son to king David to inquire of his welfare and to congratulate him, because he had fought against Hadarezer and smitten him (for Hadarezer had warred with Tou), and with him all manner of *_vessels_* of gold, silver, and brass.
* `1Ch 22:19` Now set your heart and your soul to seek the LORD your God. Arise therefore, and build the sanctuary of the LORD God to bring the ark of the covenant of the LORD and the holy *_vessels_* of God into the house that is to be built to the name of the LORD."
* `1Ch 23:26` And also the Levites shall no longer carry the tabernacle, nor any of its *_vessels_* for its service."
* `1Ch 28:13` And also for the courses of the priests and the Levites, for all the work of the service of the house of the LORD, and for all the *_vessels_* of service in the house of the LORD.
* `2Ch 4:18` Thus Solomon made all these *_vessels_* in great abundance, for the weight of the brass could not be ascertained.
* `2Ch 4:19` And Solomon made all the *_vessels_* that were for the house of God: the golden altar and the tables on which the show-bread was set;
* `2Ch 5:5` And they brought up the ark, the Tabernacle of the Congregation, and all the holy *_vessels_* that were in the tabernacle. The priests and the Levites brought these up.
* `2Ch 9:20` And all the drinking *_vessels_* of king Solomon were of gold, and all the *_vessels_* of the house of the forest of Lebanon were of pure gold. None were of silver, for it was nothing accounted of in the days of Solomon.
* `2Ch 9:24` And they each brought his present: *_vessels_* of silver, *_vessels_* of gold, clothing, armor, spices, horses, and mules, a rate year by year.
* `2Ch 15:18` And he brought into the house of God the things that his father had dedicated and that he himself had dedicated: silver, gold, and *_vessels_*.
* `2Ch 24:14` And when they had finished it, they brought the rest of the money before the king and Jehoiada, of which were made *_vessels_* for the house of the LORD, even *_vessels_* to minister and to offer with, and spoons and *_vessels_* of gold and silver. And they offered burnt-offerings in the house of the LORD continually all the days of Jehoiada.
* `2Ch 25:24` And he took all the gold and the silver, all the *_vessels_* that were found in the house of God with Obed-edom, the treasures of the king's house, and the hostages, and returned to Samaria.
* `2Ch 28:24` And Ahaz collected the *_vessels_* of the house of God and cut in pieces the *_vessels_* of the house of God. And he shut up the doors of the house of the LORD and made for himself altars in every corner of Jerusalem.
* `2Ch 29:18` Then they went inside to Hezekiah the king and said, "We have cleansed all the house of the LORD, the altar of burnt-offering with all its *_vessels_*, and the show-bread table with all its *_vessels_*.
* `2Ch 29:19` Moreover, all the *_vessels_* which king Ahaz in his reign cast away in his transgression, we have prepared and sanctified, and behold, they are before the altar of the LORD."
* `2Ch 36:7` Nebuchadnezzar also carried some of the *_vessels_* of the house of the LORD to Babylon and put them in his temple at Babylon.
* `2Ch 36:10` And when the year had expired, king Nebuchadnezzar sent and brought him to Babylon with the precious *_vessels_* of the house of the LORD, and made Zedekiah his brother king over Judah and Jerusalem.
* `2Ch 36:18` And all the *_vessels_* of the house of God, great and small, the treasures of the house of the LORD, and the treasures of the king and of his princes, all these he brought to Babylon.
* `2Ch 36:19` And they burnt the house of God, broke down the wall of Jerusalem, burnt all its palaces with fire, and destroyed all its precious *_vessels_*.
* `Ezr 1:6` And all those who were around them strengthened their hands with *_vessels_* of silver, with gold, with goods, with beasts, and with precious things, besides all that was willingly offered.
* `Ezr 1:7` Also Cyrus the king brought forth the *_vessels_* of the house of the LORD, which Nebuchadnezzar had brought from Jerusalem, and had put them in the house of his gods.
* `Ezr 1:10` Thirty basins of gold, four hundred and ten silver basins of a second sort, and one thousand other *_vessels_*.
* `Ezr 1:11` All the *_vessels_* of gold and of silver were five thousand and four hundred. All these Sheshbazzar brought with those of the captivity who were brought from Babylon to Jerusalem.
* `Ezr 5:14` And also the *_vessels_* of gold and silver of the house of God, which Nebuchadnezzar took out of the temple that was in Jerusalem and brought them into the temple of Babylon, Cyrus the king took those out of the temple of Babylon, and they were delivered to someone whose name was Sheshbazzar, whom he had made governor,
* `Ezr 5:15` And said to him, "Take these *_vessels_*, go, carry them into the temple that is in Jerusalem, and let the house of God be built in its place."
* `Ezr 6:5` And also let the golden and silver *_vessels_* of the house of God, which Nebuchadnezzar took out of the temple which is at Jerusalem and brought to Babylon, be restored and brought back to the temple which is at Jerusalem, each to its place, and place them in the house of God.'"
* `Ezr 7:19` The *_vessels_* also that are given to you for the service of the house of your God, deliver those before the God of Jerusalem.
* `Ezr 8:25` And I weighed to them the silver, the gold, and the *_vessels_*, even the offering of the house of our God, which the king, his counselors, his lords, and all Israel present there had offered.
* `Ezr 8:26` I even weighed to their hand six hundred and fifty talents of silver, one hundred talents of silver *_vessels_*, one hundred talents of gold,
* `Ezr 8:27` Twenty basins of gold of one thousand drams, and two *_vessels_* of fine copper, precious as gold.
* `Ezr 8:28` And I said to them, "You are holy to the LORD. The *_vessels_* are also holy. And the silver and the gold are a voluntary-offering to the LORD God of your fathers.
* `Ezr 8:30` So the priests and the Levites took the weight of the silver, the gold, and the *_vessels_*, to bring them to Jerusalem to the house of our God.
* `Ezr 8:33` Now on the fourth day the silver, the gold, and the *_vessels_* were weighed in the house of our God by the hand of Meremoth the son of Uriah the priest, and with him was Eleazar the son of Phinehas, and with them were the Levites Jozabad the son of Jeshua and Noadiah the son of Binnui.
* `Neh 10:39` For the children of Israel and the children of Levi shall bring the offering of the grain, the new wine, and the oil to the chambers where the *_vessels_* of the sanctuary are, as well as the priests who minister, the gatekeepers, and the singers. And we will not forsake the house of our God.
* `Neh 13:5` And he had prepared for him a great chamber, where they formerly laid the food-offerings, the frankincense, the *_vessels_*, the tithes of the grain, the new wine, and the oil, which was commanded to be given to the Levites, the singers, and the gatekeepers, and the offerings of the priests.
* `Neh 13:9` Then I commanded, and they cleansed the chambers. And I brought there again the *_vessels_* of the house of God, with the food-offering and the frankincense.
* `Est 1:7` And they gave them drink in *_vessels_* of gold (the *_vessels_* being diverse from one another) and royal wine in abundance, according to the state of the king.
* `Isa 18:2` That sends ambassadors by the sea, even in *_vessels_* of bulrushes upon the waters, saying, "Go, you swift messengers, to a nation scattered and peeled, to a people awesome from their beginning until now, a nation measured by line and trodden down, whose land the rivers have laid waste."
* `Isa 22:24` And they shall hang upon him all the glory of his father's house: the offspring and the descendants, all *_vessels_* of small quantity, from the *_vessels_* of cups, even to all the *_vessels_* of flagons.
* `Isa 52:11` Depart, depart, go out from there. Touch no unclean thing. Go out of the midst of her. Be clean, you who bear the *_vessels_* of the LORD.
* `Isa 65:4` Who remain among the graves and lodge in the monuments, who eat swine's flesh and broth of abominable things is in their *_vessels_*,
* `Jer 14:3` And their nobles have sent their little ones to the waters. They came to the pits and found no water. They returned with their *_vessels_* empty. They were ashamed and confounded and covered their heads.
* `Jer 27:16` Also I spoke to the priests and to all this people, saying, "Thus says the LORD: 'Do not listen to the words of your prophets who prophesy to you, saying, "Behold, the *_vessels_* of the LORD'S house shall now shortly be brought back from Babylon," for they prophesy a lie to you.
* `Jer 27:18` But if they are prophets and if the word of the LORD is with them, let them now make intercession to the LORD of hosts so that the *_vessels_* which are left in the house of the LORD, in the house of the king of Judah, and in Jerusalem do not go to Babylon.
* `Jer 27:19` For thus says the LORD of hosts concerning the pillars, concerning the sea, concerning the bases, and concerning the rest of the *_vessels_* that remain in this city,
* `Jer 27:21` Indeed, thus says the LORD of hosts, the God of Israel, concerning the *_vessels_* that remain in the house of the LORD, in the house of the king of Judah, and in Jerusalem:
* `Jer 28:3` Within two full years I will bring back into this place all the *_vessels_* of the LORD'S house that Nebuchadnezzar king of Babylon took away from this place and carried to Babylon.
* `Jer 28:6` Even the prophet Jeremiah said, "Amen. May the LORD do so. May the LORD perform your words which you have prophesied, to bring back the *_vessels_* of the LORD'S house and all that is carried away captive from Babylon into this place.
* `Jer 40:10` As for me, behold, I will dwell at Mizpah to serve the Chaldeans who will come to us. But you, gather wine, summer fruits, and oil, and put them in your *_vessels_* and dwell in your cities that you have taken."
* `Jer 48:12` "Therefore, behold, the days come," says the LORD, "that I will send to him wanderers who shall cause him to wander, and shall empty his *_vessels_* and break their bottles.
* `Jer 49:29` Their tents and their flocks they shall take away. They shall take for themselves their curtains, all their *_vessels_*, and their camels, and they shall cry to them, 'Fear is on every side.'
* `Jer 52:18` And the cauldrons, the shovels, the snuffers, the bowls, the spoons, and all the *_vessels_* of brass with which they ministered, they took away.
* `Jer 52:20` The two pillars, one sea, and twelve brazen bulls that were under the bases, which king Solomon had made in the house of the LORD, the brass of all these *_vessels_* was without weight.
* `Ezk 27:13` Javan, Tubal, and Meshech, they were your merchants. They traded in the persons of men and *_vessels_* of brass in your market.
* `Dan 1:2` And the Lord gave Jehoiakim king of Judah into his hand, with part of the *_vessels_* of the house of God, which he carried into the land of Shinar to the house of his god. And he brought the *_vessels_* into the treasure-house of his god.
* `Dan 5:2` Belshazzar, while he tasted the wine, commanded to bring the golden and silver *_vessels_* which his father Nebuchadnezzar had taken out of the temple which was in Jerusalem, so that the king, his princes, his wives, and his concubines might drink from them.
* `Dan 5:3` Then they brought the golden *_vessels_* that were taken out of the temple of the house of God which was at Jerusalem, and the king, his princes, his wives, and his concubines drank from them.
* `Dan 5:23` But have lifted up yourself against the Lord of heaven. And they have brought the *_vessels_* of his house before you, and you, your lords, your wives, and your concubines have drank wine from them. And you have praised the gods of silver, gold, brass, iron, wood, and stone, which do not see, nor hear, nor know. And the God in whose hand is your breath and all your ways, you have not glorified.
* `Dan 11:8` And he shall also carry captive into Egypt their gods, with their princes, and with their precious *_vessels_* of silver and of gold, and he shall continue more years than the king of the north.
* `Hos 13:15` Though he is fruitful among his brothers, an east wind shall come, the wind of the LORD shall come up from the wilderness, and his spring shall become dry and his fountain shall be dried up. He shall pillage the treasure of all precious *_vessels_*.
* `Nah 2:9` Take the plunder of silver and take the plunder of gold. There is no end to the supply. There is glory from all the desirable *_vessels_*.
* `Hag 2:16` Since those days were, when someone came to a heap of twenty measures, there were but ten. When someone came to the press-vat to draw out fifty *_vessels_* out of the press, there were but twenty.
* `Mth 13:48` Which, when it was full, they drew to the shore, sat down, and gathered the good into *_vessels_*, but cast away the bad.
* `Mth 25:4` But the wise took oil in their *_vessels_* with their lamps.
* `Mrk 7:4` And when they come from the market, they do not eat unless they wash. And there are many other things which they have received to hold, as the washing of cups, pots, brazen *_vessels_*, and tables.
* `Rom 9:22` What if God, willing to show his wrath and to make his power known, endured with much patience the *_vessels_* of wrath fitted for destruction,
* `Rom 9:23` So that he might make known the riches of his glory for the *_vessels_* of mercy which he had before prepared for glory,
* `2Co 4:7` But we have this treasure in earthen *_vessels_* so that the excellence of the power may be from God and not from us.
* `2Ti 2:20` But in a great house there are not only *_vessels_* of gold and of silver, but also of wood and of earth. Some are for honor and some for dishonor.
* `Heb 9:21` And likewise, he sprinkled both the tabernacle and all the *_vessels_* of the ministry with blood.
* `Rev 2:27` And he shall rule them with a rod of iron, and as the *_vessels_* of a potter they shall be broken to pieces,' even as I received from my Father.
* `Rev 18:12` The merchandise of gold, silver, precious stones, of pearls, fine linen, purple, silk, scarlet, all thyine wood, all *_vessels_* of ivory, all *_vessels_* of most precious wood, of brass, iron, marble,

_139 verses containing VESSELS_

== VESTURE

* `Deu 22:12` "You shall make yourself fringes upon the four quarters of your *_vesture_* with which you cover yourself.
* `Psa 22:18` They part my garments among them and cast lots upon my *_vesture_*.
* `Psa 102:26` They shall perish, but you will endure. Indeed, all of them shall grow old like a garment. Like a *_vesture_* you will change them, and they shall be changed.
* `Mth 27:35` And when they had crucified him, they divided his garments by casting lots so that it might be fulfilled which was spoken by the prophet, "They parted my garments among them, and upon my *_vesture_* they cast lots."
* `Jhn 19:24` Therefore, they said among themselves, "Let us not rend it, but cast lots for it to decide whose it shall be," so that the Scripture might be fulfilled, which says, "They parted my clothing among them, and for my *_vesture_* they cast lots." Therefore the soldiers did these things.
* `Heb 1:12` And as a *_vesture_* you will fold them up, and they shall be changed. But you are the same, and your years shall not fail."
* `Rev 19:13` And he was clothed with a *_vesture_* dipped in blood. And his name is called, The Word of God.
* `Rev 19:16` And he has on his *_vesture_* and on his thigh a name written, "KING OF KINGS AND LORD OF LORDS."

_8 verses containing VESTURE_

== VESTURES

* `Gen 41:42` And Pharaoh took off his ring from his hand and put it upon Joseph's hand, and arrayed him in *_vestures_* of fine linen and put a gold chain around his neck.

_1 verse containing VESTURES_

== VETCHES

* `Isa 28:25` When he has made even its face, does he not cast abroad the *_vetches_*, scatter the cumin, cast in the principal wheat, the appointed barley, and the spelt in their place?
* `Isa 28:27` For the *_vetches_* are not threshed with a threshing instrument, neither is a cart-wheel turned around upon the cumin. But the *_vetches_* are beaten out with a staff and the cumin with a rod.

_2 verses containing VETCHES_

== VEX

* `Exo 22:21` "You shall neither *_vex_* a stranger, nor oppress him, for you were strangers in the land of Egypt.
* `Job 19:2` "How long will you *_vex_* my soul and break me in pieces with words?
* `Ezk 32:9` "I will also *_vex_* the hearts of many people when I bring your destruction among the nations into the countries which you have not known.

_3 verses containing VEX_

== VEXATION

* `Deu 28:20` "The LORD shall send upon you cursing, *_vexation_*, and rebuke in all that you undertake to perform until you are destroyed and until you perish quickly, because of the wickedness of your doings by which you have forsaken me.
* `Ecc 1:14` I have seen all the works that are done under the sun, and behold, all is vanity and *_vexation_* of spirit.
* `Ecc 1:17` And I gave my heart to know wisdom and to know madness and folly. I perceived that this also is *_vexation_* of spirit.
* `Ecc 2:11` Then I considered all the works that my hands had wrought and the labor that I had labored to do, and behold, all was vanity and *_vexation_* of spirit, and there was no profit under the sun.
* `Ecc 2:17` Therefore, I hated life, because the work that is wrought under the sun is grievous to me. For all is vanity and *_vexation_* of spirit.
* `Ecc 2:22` For what does man have of all his labor and of the *_vexation_* of his heart in which he has labored under the sun?
* `Ecc 2:26` For to the man who is good in his sight, God gives wisdom, knowledge, and joy, but to the sinner he gives toil, to gather and to amass, so that he may give to him who is good before God. This also is vanity and *_vexation_* of spirit.
* `Ecc 4:4` Again, I considered all labor and every right work, that for this, a man is envied by his neighbor. This is also vanity and *_vexation_* of spirit.
* `Ecc 4:6` Better is a handful with quietness, than both the hands full with toil and *_vexation_* of spirit.
* `Ecc 4:16` There is no end of all the people, even of all who have been before them. Those who come after shall not rejoice in him. Surely this also is vanity and *_vexation_* of spirit.
* `Ecc 6:9` Better is the sight of the eyes than the wandering of the desire. This is also vanity and *_vexation_* of spirit.
* `Isa 28:19` From the time that it goes forth it shall take you. For morning by morning it shall pass over, by day and by night. And it shall be a *_vexation_* only to understand the report."
* `Isa 65:14` Behold, my servants shall sing for joy of heart, but you shall cry for sorrow of heart and howl for *_vexation_* of spirit.

_13 verses containing VEXATION_

== VEXATIONS

* `2Ch 15:5` And in those times there was no peace to him who went out, nor to him who came in, but great *_vexations_* were upon all the inhabitants of the countries.

_1 verse containing VEXATIONS_

== VEXED

* `Jdg 16:16` And it came to pass when she pressed him daily with her words and urged him so that his soul was *_vexed_* to death,
* `Isa 63:10` But they rebelled and *_vexed_* his Holy Spirit; therefore, he was turned to be their enemy and he fought against them.

_2 verses containing VEXED_

