= HANG - HASUPHA
:toc:

== HANG

* `Gen 40:19` Within three days Pharaoh shall lift up your head from off you and *_hang_* you on a tree. And the birds shall eat your flesh from off you."
* `Exo 26:12` And the remnant that remains of the curtains of the tent, the half curtain that remains, shall *_hang_* over the back of the tabernacle.
* `Exo 26:13` And a cubit on one side and a cubit on the other side of that which remains in the length of the curtains of the tent shall *_hang_* over the sides of the tabernacle on this side and on that side to cover it.
* `Exo 26:32` And you shall *_hang_* it upon four pillars of shittim wood overlaid with gold. Their hooks shall be of gold upon the four sockets of silver.
* `Exo 26:33` And you shall *_hang_* the veil under the buttons so that you may bring in there within the veil the ark of the testimony. And the veil shall be for you a separation between the holy place and the holy of holies.
* `Exo 40:8` And you shall set up the court all around and *_hang_* up the hanging at the court-gate.
* `Num 25:4` And the LORD said to Moses, "Take all the heads of the people and *_hang_* them up to the LORD before the sun so that the fierce anger of the LORD may be turned away from Israel."
* `Deu 21:22` "And if a man has committed a sin worthy of death and he must be put to death, and you *_hang_* him on a tree,
* `Deu 28:66` And your life shall *_hang_* in doubt before you. And you shall fear day and night and shall have no assurance of your life.
* `2Sa 21:6` Let seven men of his sons be delivered to us, and we will *_hang_* them up to the LORD in Gibeah of Saul, whom the LORD chose." And the king said, "I will give them."
* `Est 6:4` And the king said, "Who is in the court?" Now Haman had come into the outward court of the king's house to speak to the king to *_hang_* Mordecai on the gallows that he had prepared for him.
* `Est 7:9` And Harbonah, one of the chamberlains, said before the king, "Behold also the gallows fifty cubits high which Haman had made for Mordecai, who had spoken good for the king, stands in the house of Haman." Then the king said, "*_Hang_* him upon it."
* `Sos 4:4` Your neck is like the tower of David built for an armory, on which *_hang_* a thousand bucklers, all shields of mighty men.
* `Isa 22:24` And they shall *_hang_* upon him all the glory of his father's house: the offspring and the descendants, all vessels of small quantity, from the vessels of cups, even to all the vessels of flagons.
* `Lam 2:10` [YOD] The elders of the daughter of Zion sit upon the ground and keep silence. They have cast up dust upon their heads. They have girded themselves with sackcloth. The virgins of Jerusalem *_hang_* down their heads to the ground.
* `Ezk 15:3` Shall wood be taken from it to do any work? Or will men take a pin from it to *_hang_* any vessel upon it?
* `Mth 22:40` All the law and the prophets *_hang_* on these two commandments."
* `Act 28:4` And when the barbarians saw the animal *_hang_* on his hand, they said among themselves, "No doubt this man is a murderer, whom, though he has escaped the sea, yet vengeance does not allow to live."

_18 verses containing HANG_

== HANGED

* `Gen 40:22` But he *_hanged_* the chief baker, as Joseph had interpreted to them.
* `Gen 41:13` And it came to pass, as he interpreted to us, it was so. He restored me to my office, and he *_hanged_* him."
* `Deu 21:23` His body shall not remain all night upon the tree, but you shall surely bury him that day (for he who is *_hanged_* is accursed of God) You shall not defile your land that the LORD your God gives you for an inheritance."
* `Jsh 8:29` And the king of Ai he *_hanged_* on a tree until evening. And as soon as the sun was down, Joshua commanded that they should take his carcass down from the tree, cast it at the entering of the gate of the city, and raise upon it a great heap of stones, which remains to this day.
* `Jsh 10:26` And afterward, Joshua smote them, slew them, and *_hanged_* them on five trees. And they were hanging upon the trees until the evening.
* `2Sa 4:12` And David commanded his young men, and they slew them, cut off their hands and their feet, and *_hanged_* them over the pool in Hebron. But they took the head of Ish-bosheth and buried it in the sepulcher of Abner in Hebron.
* `2Sa 17:23` And when Ahithophel saw that his counsel was not followed, he saddled his donkey, arose, and went home to his house, to his city, and put his household in order, *_hanged_* himself, and died and was buried in the sepulcher of his father.
* `2Sa 21:9` And he delivered them into the hands of the Gibeonites, and they *_hanged_* them on the hill before the LORD. And they fell all seven together and were put to death in the days of harvest, in the first days, in the beginning of barley harvest.
* `2Sa 21:12` And David went and took the bones of Saul and the bones of Jonathan his son from the men of Jabesh-gilead who had stolen them from the street of Beth-shan, where the Philistines had *_hanged_* them when the Philistines had slain Saul in Gilboa.
* `2Sa 21:13` And he brought up from there the bones of Saul and the bones of Jonathan his son, and they gathered the bones of those who were *_hanged_*.
* `Ezr 6:11` Also, I have made a decree, that whoever alters this word, let timber be pulled down from his house, and being set up, let him be *_hanged_* upon it, and let his house be made a dunghill for this.
* `Est 2:23` And when inquisition was made about the matter and it was discovered, they were both *_hanged_* on a tree. And it was written in the book of the chronicles before the king.
* `Est 5:14` Then Zeresh his wife and all his friends said to him, "Let a gallows be made fifty cubits high, and tomorrow speak to the king so that Mordecai may be *_hanged_* upon it. Then go in merrily with the king to the banquet." And the thing pleased Haman, and he caused the gallows to be made.
* `Est 7:10` So they *_hanged_* Haman on the gallows that he had prepared for Mordecai. Then the king's wrath was pacified.
* `Est 8:7` Then king Ahasuerus said to Esther the queen and to Mordecai the Jew, "Behold, I have given Esther the house of Haman, and they have *_hanged_* him upon the gallows because he laid his hand upon the Jews.
* `Est 9:13` Then Esther said, "If it pleases the king, let it be granted to the Jews who are in Shushan to do tomorrow also according to this day's decree, and let Haman's ten sons be *_hanged_* upon the gallows."
* `Est 9:14` And the king commanded it to be done so. And the decree was given at Shushan, and they *_hanged_* Haman's ten sons.
* `Est 9:25` But when Esther came before the king, he commanded by letters that his wicked plan which he devised against the Jews should return upon his own head, and that he and his sons should be *_hanged_* on the gallows.
* `Lam 5:12` Princes were *_hanged_* by their hand. The faces of elders were not honored.
* `Mth 18:6` But whoever causes one of these little ones who believe in me to sin, it would be better for him that a millstone were *_hanged_* around his neck and that he were drowned in the depth of the sea.
* `Mth 27:5` And he cast down the pieces of silver in the temple, departed, and went and *_hanged_* himself.
* `Mrk 9:42` "And whoever causes one of these little ones who believe in me to fall into sin, it is better for him that a millstone were *_hanged_* around his neck and he were cast into the sea.
* `Luk 17:2` It would be better for him that a millstone were *_hanged_* around his neck and he were cast into the sea than that he should cause one of these little ones to fall into sin.
* `Luk 23:39` And one of the malefactors who were *_hanged_* railed on him, saying, "If you are Christ, save yourself and us."
* `Act 5:30` The God of our fathers raised up Jesus, whom you slew and *_hanged_* on a tree.
* `Act 10:39` And we are witnesses of all things which he did, both in the land of the Jews and in Jerusalem, whom they slew and *_hanged_* on a tree.

_26 verses containing HANGED_

== HANGING

* `Exo 26:36` "And you shall make a *_hanging_* for the door of the tent of blue, purple, scarlet, and fine twined linen, wrought with needle work.
* `Exo 26:37` And you shall make for the *_hanging_* five pillars of shittim wood and overlay them with gold, and their hooks shall be of gold. And you shall cast five sockets of brass for them."
* `Exo 27:16` And for the gate of the court there shall be a *_hanging_* of twenty cubits of blue, purple, scarlet, and fine twined linen, wrought with needle-work, with their four pillars and their four sockets.
* `Exo 35:15` The incense-altar and its staffs; the anointing oil and the sweet incense; the *_hanging_* for the door at the entrance of the tabernacle;
* `Exo 35:17` The hangings of the court, its pillars, their sockets, and the *_hanging_* for the door of the court;
* `Exo 36:37` And he made a *_hanging_* for the tabernacle door of blue, purple, scarlet, and fine twined linen, of needle-work,
* `Exo 38:18` And the *_hanging_* for the gate of the court was needle-work of blue, purple, scarlet, and fine twined linen. And twenty cubits was the length, and the height in the breadth was five cubits, corresponding to the hangings of the court.
* `Exo 39:38` The golden altar, the anointing oil, and the sweet incense; the *_hanging_* for the tabernacle door;
* `Exo 39:40` The hangings of the court with its pillars and its sockets, the *_hanging_* for the court-gate with its cords and its pins, and all the vessels of the service of the tabernacle for the tent of the congregation;
* `Exo 40:5` And you shall set the altar of gold for the incense before the ark of the testimony and set up the *_hanging_* for the door of the tabernacle.
* `Exo 40:8` And you shall set up the court all around and hang up the *_hanging_* at the court-gate.
* `Exo 40:28` And he set up the *_hanging_* at the door of the tabernacle.
* `Exo 40:33` And he reared up the court all around the tabernacle and the altar and set up the *_hanging_* of the court-gate. So Moses finished the work.
* `Num 3:25` And the charge of the sons of Gershon in the Tabernacle of the Congregation shall be the tabernacle and the tent, its covering, the *_hanging_* for the door of the Tabernacle of the Congregation,
* `Num 3:31` And their charge shall be the ark, the table, the candlestick, the altars, the vessels of the sanctuary with which they minister, the *_hanging_*, and all its service.
* `Num 4:25` They shall bear the curtains of the tabernacle and the Tabernacle of the Congregation, its covering, the covering of the badgers' skins that is above upon it, the *_hanging_* for the door of the Tabernacle of the Congregation,
* `Num 4:26` The hangings of the court, the *_hanging_* for the door of the gate of the court which surrounds the tabernacle and the altar, their cords, all the instruments of their service, and all that is made for them. Thus they shall serve.
* `Jsh 10:26` And afterward, Joshua smote them, slew them, and hanged them on five trees. And they were *_hanging_* upon the trees until the evening.
* `2Sa 18:10` And a certain man saw it and told Joab and said, "Behold, I saw Absalom *_hanging_* in an oak."
* `1Ki 7:29` And on the borders that were between the ledges were lions, oxen, and cherubim. And upon the ledges there was a base above, and beneath the lions and oxen were wreaths of *_hanging_* work.
* `Job 41:23` The *_hanging_* parts of his flesh are joined together. They are firm in themselves. They cannot be moved.

_21 verses containing HANGING_

== HANGINGS

* `Exo 27:9` "And you shall make the court of the tabernacle. For the south side southward there shall be *_hangings_* for the court of fine twined linen of one hundred cubits long for one side.
* `Exo 27:11` And likewise for the north side in length there shall be *_hangings_* of one hundred cubits long, and its twenty pillars and their twenty sockets of brass. The hooks of the pillars and their fillets shall be of silver.
* `Exo 27:12` And for the breadth of the court on the west side shall be *_hangings_* of fifty cubits with their ten pillars and their ten sockets.
* `Exo 27:14` The *_hangings_* of one side of the gate shall be fifteen cubits with their three pillars and their three sockets.
* `Exo 27:15` And on the other side shall be *_hangings_*, fifteen cubits, with their three pillars and their three sockets.
* `Exo 35:17` The *_hangings_* of the court, its pillars, their sockets, and the hanging for the door of the court;
* `Exo 38:9` And he made the court. On the south side southward the *_hangings_* of the court were of fine twined linen, one hundred cubits.
* `Exo 38:11` And for the north side, the *_hangings_* were one hundred cubits, their pillars were twenty and their sockets of brass twenty. The hooks of the pillars and their fillets were made of silver.
* `Exo 38:12` And for the west side were *_hangings_* of fifty cubits, their pillars ten and their sockets ten. The hooks of the pillars and their fillets were made of silver.
* `Exo 38:14` The *_hangings_* of one side of the gate were fifteen cubits, their pillars three and their sockets three.
* `Exo 38:15` And for the other side of the court-gate, on this hand and that hand, were *_hangings_* of fifteen cubits, their pillars three and their sockets three.
* `Exo 38:16` All the *_hangings_* of the court all around were of fine twined linen.
* `Exo 38:18` And the hanging for the gate of the court was needle-work of blue, purple, scarlet, and fine twined linen. And twenty cubits was the length, and the height in the breadth was five cubits, corresponding to the *_hangings_* of the court.
* `Exo 39:40` The *_hangings_* of the court with its pillars and its sockets, the hanging for the court-gate with its cords and its pins, and all the vessels of the service of the tabernacle for the tent of the congregation;
* `Num 3:26` The *_hangings_* of the court, the curtain for the door of the court which surrounds the tabernacle and the altar, and its cords, for all its service.
* `Num 4:26` The *_hangings_* of the court, the hanging for the door of the gate of the court which surrounds the tabernacle and the altar, their cords, all the instruments of their service, and all that is made for them. Thus they shall serve.
* `2Ki 23:7` And he broke down the houses of the temple prostitutes that were by the house of the LORD, where the women wove *_hangings_* for the grove.
* `Est 1:6` Where white, green, and blue *_hangings_* were fastened with cords of fine linen and purple to silver rings and pillars of marble. The couches were of gold and silver upon a pavement of red, blue, white, and black marble.

_18 verses containing HANGINGS_

== HANGS

* `Job 26:7` He stretches out the north over the empty place and *_hangs_* the earth upon nothing.
* `Gal 3:13` Christ has redeemed us from the curse of the law, being made a curse for us, for it is written, "Accursed is everyone who *_hangs_* on a tree,"

_2 verses containing HANGS_

== HANIEL

* `1Ch 7:39` And the sons of Ulla: Arah, *_Haniel_*, and Rezia.

_1 verse containing HANIEL_

== HANNAH

* `1Sa 1:2` And he had two wives: the name of one was *_Hannah_* and the name of the other Peninnah. And Peninnah had children, but *_Hannah_* had no children.
* `1Sa 1:5` But to *_Hannah_* he gave a worthy portion, for he loved *_Hannah_*, but the LORD had rendered her barren.
* `1Sa 1:8` Then Elkanah her husband said to her, "*_Hannah_*, why do you weep? And why do you not eat? And why is your heart grieved? Am I not better to you than ten sons?"
* `1Sa 1:9` So *_Hannah_* rose after they had eaten in Shiloh and after they had drank. (Now Eli the priest sat upon a seat by a post of the temple of the LORD.)
* `1Sa 1:13` Now *_Hannah_* spoke in her heart. Only her lips moved, but her voice was not heard. Therefore, Eli thought she had been drunken.
* `1Sa 1:15` And *_Hannah_* answered and said, "No, my lord, I am a woman of a sorrowful spirit. I have drank neither wine or strong drink, but have poured out my soul before the LORD.
* `1Sa 1:19` And they rose early in the morning, worshiped before the LORD, and returned and came to their house in Ramah. And Elkanah knew *_Hannah_* his wife, and the LORD remembered her.
* `1Sa 1:20` Therefore, it came to pass, when the time had arrived after *_Hannah_* had conceived, that she bore a son and called his name Samuel, saying, "Because I have asked for him from the LORD."
* `1Sa 1:22` But *_Hannah_* did not go up, for she said to her husband, "I will not go up until the child is weaned, and then I will bring him so that he may appear before the LORD and abide there forever."
* `1Sa 2:1` And *_Hannah_* prayed and said, "My heart rejoices in the LORD. My horn is exalted in the LORD. My mouth is enlarged over my enemies because I rejoice in your salvation.
* `1Sa 2:21` And the LORD visited *_Hannah_* so that she conceived and bore three sons and two daughters. And the child Samuel grew before the LORD.

_11 verses containing HANNAH_

== HANNATHON

* `Jsh 19:14` And the border compasses it on the north side to *_Hannathon_*; and its limits are in the valley of Jiphthah-el;

_1 verse containing HANNATHON_

== HANNIEL

* `Num 34:23` The prince of the children of Joseph, for the tribe of the children of Manasseh, *_Hanniel_* the son of Ephod;

_1 verse containing HANNIEL_

== HANOCH

* `Gen 25:4` And the sons of Midian: Ephah, Epher, *_Hanoch_*, Abidah, and Eldaah. All these were the children of Keturah.
* `Gen 46:9` And the sons of Reuben: *_Hanoch_*, Phallu, Hezron, and Carmi.
* `Exo 6:14` These are the heads of their father's houses. The sons of Reuben (the first-born of Israel): *_Hanoch_*, Pallu, Hezron, and Carmi. These are the families of Reuben.
* `Num 26:5` Reuben, the eldest son of Israel—the children of Reuben: *_Hanoch_*, of whom comes the family of the Hanochites; Of Phallu, the family of the Phalluites;
* `1Ch 5:3` The sons of Reuben the first-born of Israel were *_Hanoch_*, Pallu, Hezron, and Carmi.

_5 verses containing HANOCH_

== HANOCHITES

* `Num 26:5` Reuben, the eldest son of Israel—the children of Reuben: Hanoch, of whom comes the family of the *_Hanochites_*; Of Phallu, the family of the Phalluites;

_1 verse containing HANOCHITES_

== HANUN

* `2Sa 10:1` And it came to pass after this, that the king of the children of Ammon died, and *_Hanun_* his son reigned in his stead.
* `2Sa 10:2` Then David said, "I will show kindness to *_Hanun_* the son of Nahash, as his father showed kindness to me." And David sent to comfort him by the hand of his servants for his father. And David's servants came into the land of the children of Ammon.
* `2Sa 10:3` And the princes of the children of Ammon said to *_Hanun_* their lord, "Do you think that David honors your father in that he has sent comforters to you? Has David not rather sent his servants to you to search the city, to spy it out, and to overthrow it?"
* `2Sa 10:4` Therefore, *_Hanun_* took David's servants and shaved off one half of their beards and cut off their garments in the middle, even past the small of the back, and sent them away.
* `1Ch 19:2` And David said, "I will show kindness to *_Hanun_* the son of Nahash because his father showed kindness to me." And David sent messengers to comfort him concerning his father. So the servants of David came into the land of the children of Ammon to *_Hanun_* to comfort him.
* `1Ch 19:3` But the princes of the children of Ammon said to *_Hanun_*, "Do you think that David honors your father in that he has sent comforters to you? Have his servants not come to you to search, to overthrow, and to explore the land?"
* `1Ch 19:4` Therefore, *_Hanun_* took David's servants, shaved them, and cut off their garments in the midst, even past the small of the back, and sent them away.
* `1Ch 19:6` And when the children of Ammon saw that they had made themselves odious to David, *_Hanun_* and the children of Ammon sent one thousand talents of silver to hire themselves chariots and horsemen out of Mesopotamia, out of Syria-maachah, and out of Zobah.
* `Neh 3:13` The valley-gate was repaired by *_Hanun_* and the inhabitants of Zanoah. They built it, set up its doors, its locks, and its bars, and one thousand cubits on the wall to the dung-gate.
* `Neh 3:30` After him Hananiah the son of Shelemiah and *_Hanun_* the sixth son of Zalaph repaired another piece. After him Meshullam the son of Berechiah repaired over against his chamber.

_10 verses containing HANUN_

== HAPHARAIM

* `Jsh 19:19` *_Hapharaim_*, Shihon, Anaharath,

_1 verse containing HAPHARAIM_

== HAPPEN

* `Jdg 20:3` (Now the children of Benjamin heard that the children of Israel had gone up to Mizpeh.) Then the children of Israel said, "Tell us, how did this wickedness *_happen_*?"
* `1Sa 28:10` And Saul swore to her by the LORD, saying, "As the LORD lives, no punishment shall *_happen_* to you for this thing."
* `Pro 12:21` No evil shall *_happen_* to the just, but the wicked shall be filled with mischief.
* `Isa 23:15` And it shall come to pass in that day, that Tyre shall be forgotten for seventy years, according to the days of one king. After the end of seventy years, it shall *_happen_* to Tyre as in the song of the harlot.
* `Isa 41:22` "Let them bring them forth and show us what shall *_happen_*. Let them show the former things, what they are, so that we may consider them and know the latter end of them. Or declare to us things to come.
* `Mrk 10:32` And they were on the way going up to Jerusalem, and Jesus went before them. And they were amazed, and as they followed, they were afraid. And again he took the twelve and began to tell them what things should *_happen_* to him,
* `Act 28:6` But they expected that he would have swollen or suddenly fallen down dead. But after they had waited a long time and saw nothing amiss *_happen_* to him, they changed their minds and said that he was a god.

_7 verses containing HAPPEN_

== HAPPENED

* `Deu 4:32` "For ask now about the days that are past, which were before you, since the day that God created man upon the earth, and ask from one side of heaven to the other, whether such a great thing as this has ever *_happened_*, or anything like it has been heard of.
* `Rth 2:3` And she went, and came and gleaned in the field after the reapers. And she *_happened_* to come to a part of the field belonging to Boaz, who was of the kindred of Elimelech.
* `1Sa 1:7` And so it *_happened_* year by year. When she went up to the house of the LORD, Peninnah provoked her; therefore, she wept and did not eat.
* `1Sa 6:9` And behold, if it goes up by the way of his own border to Beth-shemesh, then he has done us this great evil, but if not, then we shall know that it is not his hand that smote us. It was a chance that *_happened_* to us."
* `2Sa 1:6` And the young man who told him said, "As I *_happened_* by chance to be upon mount Gilboa, behold, Saul leaned upon his spear, and behold, the chariots and horsemen followed hard after him.
* `2Sa 20:1` And there *_happened_* to be a man of Belial there whose name was Sheba, the son of Bichri, a Benjaminite. And he blew a trumpet and said, "We have no part in David, neither do we have inheritance in the son of Jesse. Every man to his tents, O Israel."
* `2Ki 4:18` And when the child was grown, it *_happened_* on a day, that he went out to his father to the reapers.
* `2Ki 7:20` And so it *_happened_* to him, for the people trod upon him in the gate and he died.
* `Est 4:7` And Mordecai told him all that had *_happened_* to him and of the sum of the money that Haman had promised to pay to the king's treasuries for the destruction of the Jews.
* `Jer 44:23` Because you have burned incense and because you have sinned against the LORD and have not obeyed the voice of the LORD, nor walked in his law, nor in his statutes, nor in his testimonies, therefore this evil has *_happened_* to you, as at this day."
* `Luk 1:43` And how has this *_happened_* to me, that the mother of my Lord should come to me?
* `Luk 24:14` And they talked together of all these things which had *_happened_*.
* `Act 3:10` And they knew that it was he who sat for alms at the Beautiful gate of the temple. And they were filled with wonder and amazement at that which had *_happened_* to him.
* `Rom 11:25` For I do not wish, brothers, that you should be ignorant of this mystery (lest you should be wise in your own conceits), that blindness in part has *_happened_* to Israel until the fullness of the Gentiles has come in.
* `1Co 10:11` Now all these things *_happened_* to them for examples. And they are written for our admonition, upon whom the ends of the ages have come.
* `Phl 1:12` But I wish you to understand, brothers, that the things which *_happened_* to me have turned out rather for the furtherance of the gospel,
* `1Pe 4:12` Beloved, do not think it strange concerning the fiery trial which is to try you, as though some strange thing *_happened_* to you.
* `2Pe 2:22` But it has *_happened_* to them according to the true proverb, "The dog has turned to his own vomit again," and, "The sow that was washed to her wallowing in the mire."

_18 verses containing HAPPENED_

== HAPPENS

* `Deu 22:6` "If a bird's nest *_happens_* to be before you in the way on any tree or on the ground, whether with young ones or eggs, and the mother sitting upon the young or upon the eggs, you shall not take the mother with the young.
* `Deu 23:10` "If there is among you any man who is not clean by reason of uncleanness that *_happens_* to him by night, then he shall go abroad out of the camp. He shall not come within the camp.
* `Ecc 2:14` The wise man's eyes are in his head, but the fool walks in darkness. And I myself perceived also that one event *_happens_* to them all.
* `Ecc 2:15` Then I said in my heart, "As it *_happens_* to the fool, so it *_happens_* even to me. And why was I then more wise?" Then I said in my heart that this also is vanity.
* `Ecc 8:14` There is a vanity which is done upon the earth: there are just men, to whom it *_happens_* according to the work of the wicked, and there are wicked men, to whom it *_happens_* according to the work of the righteous. I said that this also is vanity.
* `Ecc 9:11` I returned, and saw under the sun, that the race is not to the swift, nor the battle to the strong, neither yet bread to the wise, nor yet riches to men of understanding, nor yet favor to men of skill, but time and chance *_happens_* to them all.

_6 verses containing HAPPENS_

== HAPPIER

* `1Co 7:40` But she is *_happier_* if she remains so, according to my judgment—and I think also that I have the Spirit of God.

_1 verse containing HAPPIER_

== HAPPINESS

* `2Jn 1:10` If anyone comes to you and does not bring this doctrine, do not receive him into your house, neither wish him *_happiness_*.
* `2Jn 1:11` For he who wishes him *_happiness_* is partaker of his evil deeds.

_2 verses containing HAPPINESS_

== HAPPY

* `Gen 30:13` And Leah said, "*_Happy_* am I, for the daughters will call me blessed." And she called his name Asher.
* `Deu 33:29` *_Happy_* are you, O Israel! Who is like you, O people saved by the LORD, the shield of your help, and he who is the sword of your excellence? And your enemies shall be found liars to you, and you shall tread upon their high places."
* `1Ki 10:8` *_Happy_* are your men. *_Happy_* are these your servants who stand continually before you and who hear your wisdom.
* `2Ch 9:7` *_Happy_* are your men and *_happy_* are these servants of yours who stand continually before you and hear your wisdom.
* `Job 5:17` Behold, *_happy_* is the man whom God corrects; therefore, do not despise the chastening of the Almighty.
* `Psa 127:5` *_Happy_* is the man who has his quiver full of them. They shall not be ashamed, but they shall speak with the enemies in the gate.
* `Psa 128:2` For you shall eat the labor of your hands. You shall be *_happy_*, and it shall be well with you.
* `Psa 137:8` O daughter of Babylon, who is to be destroyed, *_happy_* shall he be who rewards you as you have served us.
* `Psa 137:9` *_Happy_* shall he be who takes and dashes your little ones against the stones.
* `Psa 144:15` *_Happy_* are the people who are in such a case. Indeed, *_happy_* are the people whose God is the LORD.
* `Psa 146:5` *_Happy_* is he who has the God of Jacob for his help, whose hope is in the LORD his God,
* `Pro 3:13` *_Happy_* is the man who finds wisdom and the man who gets understanding,
* `Pro 3:18` She is a tree of life to those who lay hold upon her. And *_happy_* is everyone who retains her.
* `Pro 14:21` He who despises his neighbor sins, but he who has mercy on the poor is *_happy_*.
* `Pro 16:20` He who handles a matter wisely shall find good. And whoever trusts in the LORD is *_happy_*.
* `Pro 28:14` *_Happy_* is the man who fears always, but he who hardens his heart shall fall into mischief.
* `Pro 29:18` Where there is no vision, the people perish, but he who keeps the law is *_happy_*.
* `Jer 12:1` You are righteous, O LORD, when I plead with you. Yet let me speak with you about your judgments. Why does the way of the wicked prosper? Why are they all *_happy_* who deal very treacherously?
* `Mal 3:15` And now we call the proud *_happy_*. Even those who work wickedness are built up. Even those who test God are delivered.'"
* `Act 26:2` "I think myself *_happy_*, king Agrippa, because I shall answer for myself this day before you concerning all the things of which I am accused by the Jews,
* `Rom 14:22` Do you have faith? Have it to yourself before God. *_Happy_* is he who does not condemn himself in that thing which he allows.
* `Jms 5:11` Behold, we count those *_happy_* who endure. You have heard of the patience of Job and have seen the outcome from the Lord, that the Lord is very compassionate and full of tender mercy.
* `1Pe 3:14` But if you suffer for righteousness' sake, *_happy_* are you. "And do not be afraid of their terror, neither be troubled,"
* `1Pe 4:14` If you are reproached for the name of Christ, *_happy_* are you, for the Spirit of glory and of God rests upon you. On their part he is evil spoken of, but on your part he is glorified.

_24 verses containing HAPPY_

== HARA

* `1Ch 5:26` And the God of Israel stirred up the spirit of Pul king of Assyria and the spirit of Tilgath-pilneser king of Assyria, and he carried them away, even the Reubenites, the Gadites, and the half tribe of Manasseh, and brought them to Halah, Habor, *_Hara_*, and to the Gozan River to this day.

_1 verse containing HARA_

== HARADAH

* `Num 33:24` And they departed from mount Shapher and encamped in *_Haradah_*.
* `Num 33:25` And they departed from *_Haradah_* and encamped in Makheloth.

_2 verses containing HARADAH_

== HARAN

* `Gen 11:26` And Terah lived seventy years and begot Abram, Nahor, and *_Haran_*.
* `Gen 11:27` Now these are the generations of Terah. Terah begot Abram, Nahor, and *_Haran_*. And *_Haran_* begot Lot.
* `Gen 11:28` And *_Haran_* died before his father Terah in the land of his nativity, in Ur of the Chaldeans.
* `Gen 11:29` And Abram and Nahor took wives: the name of Abram's wife was Sarai, and the name of Nahor's wife Milcah, the daughter of *_Haran_*, the father of Milcah and the father of Iscah.
* `Gen 11:31` And Terah took Abram his son and Lot the son of *_Haran_*, his son's son, and Sarai his daughter-in-law, his son Abram's wife, and they went forth together from Ur of the Chaldeans to go into the land of Canaan. And they came to *_Haran_* and dwelt there.
* `Gen 11:32` And the days of Terah were two hundred and five years, and Terah died in *_Haran_*.
* `Gen 12:4` So Abram departed, as the LORD had spoken to him, and Lot went with him. And Abram was seventy-five years old when he departed from *_Haran_*.
* `Gen 12:5` And Abram took Sarai his wife, Lot his brother's son, all their substance that they had gathered, and the souls whom they had gotten in *_Haran_*, and they went to go forth into the land of Canaan. And into the land of Canaan they came.
* `Gen 27:43` Now therefore, my son, obey my voice. And arise, flee to Laban my brother in *_Haran_*.
* `Gen 28:10` And Jacob went out from Beer-sheba and went toward *_Haran_*.
* `Gen 29:4` And Jacob said to them, "My brothers, where are you from?" And they said, "We are from *_Haran_*."
* `Num 32:36` Beth-nimrah, and Beth-*_haran_*—fortified cities—and folds for sheep.
* `2Ki 19:12` Have the gods of the nations delivered them which my fathers have destroyed, as Gozan, *_Haran_*, Rezeph, and the children of Eden who were in Thelasar?
* `1Ch 2:46` And Ephah, Caleb's concubine, bore *_Haran_*, Moza, and Gazez. And *_Haran_* begot Gazez.
* `1Ch 23:9` The sons of Shimei: Shelomith, Haziel, and *_Haran_*, three. These were the chief of the fathers of Laadan.
* `Isa 37:12` Have the gods of the nations delivered them which my fathers have destroyed—Gozan, *_Haran_*, Rezeph, and the children of Eden who were in Telassar?
* `Ezk 27:23` *_Haran_*, Canneh, Eden, the merchants of Sheba, Asshur, and Chilmad were your merchants.
* `Act 7:2` And he said, "Men, brothers, and fathers, listen. The God of glory appeared to our father Abraham when he was in Mesopotamia, before he dwelt in *_Haran_*,
* `Act 7:4` Then he came from the land of the Chaldeans and dwelt in *_Haran_*. And from there, when his father was dead, he moved him into this land in which you now dwell.

_19 verses containing HARAN_

== HARARITE

* `2Sa 23:11` And after him was Shammah the son of Agee the *_Hararite_*. And the Philistines were collected into a troop where there was a piece of ground full of lentils, and the people fled from the Philistines.
* `2Sa 23:33` Shammah the *_Hararite_*, Ahiam the son of Sharar the *_Hararite_*,
* `1Ch 11:34` The sons of Hashem the Gizonite, Jonathan the son of Shage the *_Hararite_*,
* `1Ch 11:35` Ahiam the son of Sacar the *_Hararite_*, Eliphel the son of Ur,

_4 verses containing HARARITE_

== HARASS

* `Num 33:55` But if you will not drive out the inhabitants of the land from before you, then it shall come to pass, that those which you let remain of them shall be prickles in your eyes and thorns in your sides, and shall *_harass_* you in the land in which you dwell.
* `Isa 7:6` "Let us go up against Judah and *_harass_* it, and let us make a breach therein for us and set a king in the midst of it, even the son of Tabeal,"

_2 verses containing HARASS_

== HARASSED

* `Jdg 10:8` And from that year they *_harassed_* and oppressed the children of Israel for eighteen years—all the children of Israel who were on the other side of the Jordan in the land of the Amorites, which is in Gilead.
* `1Sa 14:47` So Saul took the kingdom over Israel and fought against all his enemies on every side: against Moab, against the children of Ammon, against Edom, against the kings of Zobah, and against the Philistines. And wherever he turned himself, he *_harassed_* them.

_2 verses containing HARASSED_

== HARBONA

* `Est 1:10` On the seventh day, when the heart of the king was merry with wine, he commanded Mehuman, Biztha, *_Harbona_*, Bigtha, Abagtha, Zethar, and Carcas, the seven chamberlains who served in the presence of Ahasuerus the king,

_1 verse containing HARBONA_

== HARBONAH

* `Est 7:9` And *_Harbonah_*, one of the chamberlains, said before the king, "Behold also the gallows fifty cubits high which Haman had made for Mordecai, who had spoken good for the king, stands in the house of Haman." Then the king said, "Hang him upon it."

_1 verse containing HARBONAH_

== HARD

* `Gen 18:14` Is anything too *_hard_* for the LORD? At the time appointed I will return to you, according to the time of life, and Sarah shall have a son."
* `Gen 19:9` And they said, "Stand back." And they said again, "This one came in as a sojourner and he wants to be a judge. Now we will deal worse with you than with them." And they pressed *_hard_* upon the man, Lot, and came near to break the door.
* `Gen 33:13` And he said to him, "My lord knows that the children are tender and the flocks and herds with young are with me, and if men should drive them *_hard_* one day, all the flock will die.
* `Gen 35:16` And they journeyed from Beth-el. And there was only a little distance to come to Ephrath, and Rachel travailed and had *_hard_* labor.
* `Gen 35:17` And it came to pass when she was in *_hard_* labor, that the midwife said to her, "Do not fear. You shall have this son also."
* `Exo 1:14` And they made their lives bitter with *_hard_* bondage in mortar, in brick, and in all manner of service in the field. All their service in which they made them serve was with rigor.
* `Exo 18:26` And they judged the people at all seasons. The *_hard_* causes they brought to Moses, but every small matter they judged themselves.
* `Deu 1:17` You shall not respect persons in judgment, but you shall hear the small as well as the great. You shall not be afraid of the face of man, for the judgment is God's. And the cause that is too *_hard_* for you, bring to me, and I will hear it.'
* `Deu 15:18` "It shall not seem *_hard_* to you when you send him away free from you, for he has been of double the worth of a hired servant to you in serving you six years. And the LORD your God shall bless you in all that you do.
* `Deu 17:8` "If there arises a matter too *_hard_* for you in judgment between blood and blood, between plea and plea, and between stroke and stroke, being matters of controversy within your gates, then you shall arise and go up to the place which the LORD your God chooses.
* `Deu 26:6` And the Egyptians ill-treated us and afflicted us and laid upon us *_hard_* bondage.
* `Jdg 20:45` And they turned and fled toward the wilderness to the rock of Rimmon. And they gleaned five thousand of them in the highways, and pursued *_hard_* after them to Gidom and slew two thousand of them.
* `1Sa 14:22` Likewise, all the men of Israel who had hid themselves in the mountains of Ephraim, when they heard that the Philistines fled, even they also followed *_hard_* after them in the battle.
* `1Sa 31:2` And the Philistines followed *_hard_* upon Saul and upon his sons, and the Philistines slew Jonathan, Abinadab, and Malchi-shua, Saul's sons.
* `2Sa 1:6` And the young man who told him said, "As I happened by chance to be upon mount Gilboa, behold, Saul leaned upon his spear, and behold, the chariots and horsemen followed *_hard_* after him.
* `2Sa 3:39` And I am this day weak, though anointed king. And these men, the sons of Zeruiah, are too *_hard_* for me. The LORD shall reward the doer of evil according to his wickedness."
* `2Sa 13:2` And Amnon was so afflicted that he fell sick for his sister Tamar, for she was a virgin. And Amnon thought it *_hard_* for him to do anything to her.
* `1Ki 10:1` And when the queen of Sheba heard of the fame of Solomon concerning the name of the LORD, she came to prove him with *_hard_* questions.
* `2Ki 2:10` And he said, "You have asked a *_hard_* thing. Nevertheless, if you see me when I am taken from you, it shall be so to you, but if not, it shall not be so."
* `1Ch 10:2` And the Philistines followed *_hard_* after Saul and after his sons. And the Philistines slew Jonathan, Abinadab, and Malchi-shua, the sons of Saul.
* `2Ch 9:1` And when the queen of Sheba heard of the fame of Solomon, she came to prove Solomon with *_hard_* questions at Jerusalem, with a very great company and camels that bore spices, gold in abundance, and precious stones. And when she had come to Solomon, she spoke with him about all that was in her heart.
* `Job 38:30` The waters become *_hard_* like stone, and the face of the deep is frozen.
* `Job 41:24` His heart is as firm as a stone, even as *_hard_* as a piece of the nether millstone.
* `Psa 60:3` You have shown your people *_hard_* things. You have made us to drink the wine of astonishment.
* `Psa 63:8` My soul follows *_hard_* after you. Your right hand upholds me.
* `Psa 88:7` Your wrath lies *_hard_* upon me, and you have afflicted me with all your waves. [Selah.]
* `Psa 94:4` How long shall they utter and speak *_hard_* things, and all the workers of iniquity boast themselves?
* `Pro 13:15` Good understanding gives favor, but the way of transgressors is *_hard_*.
* `Isa 14:3` And it shall come to pass in the day that the LORD gives you rest from your sorrow, from your fear, and from the *_hard_* bondage in which you were made to serve,
* `Jer 32:17` 'Ah, Lord GOD! Behold, you have made the heaven and the earth by your great power and out-stretched arm, and there is nothing too *_hard_* for you.
* `Jer 32:27` "Behold, I am the LORD, the God of all flesh. Is there anything too *_hard_* for me?"
* `Ezk 3:5` For you are not sent to a people of a strange speech and of a *_hard_* language, but to the house of Israel,
* `Ezk 3:6` Nor to many people of a strange speech and of a *_hard_* language, whose words you cannot understand. Surely, if I sent you to them, they would listen to you.
* `Ezk 3:7` But the house of Israel will not listen to you because they will not listen to me, for all the house of Israel are impudent and *_hard_*-hearted.
* `Jna 1:13` Nevertheless, the men rowed *_hard_* to bring it to the land, but they could not, for the sea wrought and was tempestuous against them.
* `Mth 25:24` "Then he who had received the one talent came, and said, 'Lord, I knew that you are a *_hard_* man, reaping where you have not sown and gathering where you have not scattered.
* `Mrk 10:24` And the disciples were astonished at his words. But Jesus answers again, and says to them, "Children, how *_hard_* it is for those who trust in riches to enter into the kingdom of God!
* `Jhn 6:60` Therefore, when they had heard this, many of his disciples said, "This is a *_hard_* saying. Who can hear it?"
* `Act 9:5` And he said, "Who are you, Lord?" And the Lord said, "I am Jesus whom you persecute. It is *_hard_* for you to kick against the goads."
* `Act 26:14` And when we had all fallen to the earth, I heard a voice speaking to me and saying in the Hebrew language, 'Saul, Saul, why do you persecute me? It is *_hard_* for you to kick against the goads.'
* `Phl 1:23` For I am *_hard_* pressed between the two, having a desire to depart and to be with Christ, which is far better.
* `Heb 5:11` Concerning him, we have many things to say, and *_hard_* of interpretation, seeing you have become dull of hearing.
* `2Pe 3:16` As also in all his epistles, speaking in them about these things, in which are some things *_hard_* to understand, which those who are unlearned and unstable wrest, as they also do the other Scriptures, to their own destruction.
* `Jde 1:15` To execute judgment upon all and to convict all who are ungodly among them of all their ungodly deeds which they have impiously committed and of all their *_hard_* speeches which ungodly sinners have spoken against him."

_44 verses containing HARD_

== HARD-HEARTED

* `Ezk 3:7` But the house of Israel will not listen to you because they will not listen to me, for all the house of Israel are impudent and *_hard-hearted_*.

_1 verse containing HARD-HEARTED_

== HARDEN

* `Exo 4:21` And the LORD said to Moses, "When you go to return into Egypt, see that you perform all those wonders before Pharaoh which I have put in your hand. But I will *_harden_* his heart so that he shall not let the people go.
* `Exo 7:3` And I will *_harden_* Pharaoh's heart and multiply my signs and my wonders in the land of Egypt.
* `Exo 14:4` And I will *_harden_* Pharaoh's heart, and he shall follow them. And I will be honored upon Pharaoh and upon all his host so that the Egyptians may know that I am the LORD." And they did so.
* `Exo 14:17` And I, behold, I will *_harden_* the hearts of the Egyptians, and they shall follow them, and I will get myself honor upon Pharaoh and upon all his host, upon his chariots and upon his horsemen.
* `Deu 15:7` "If there is among you a poor man, one of your brothers, within any of your gates in your land which the LORD your God gives you, you shall not *_harden_* your heart nor shut your hand from your poor brother.
* `Jsh 11:20` For it was of the LORD to *_harden_* their hearts and to come against Israel in battle so that he might utterly destroy them and that they might have no favor, in order that he might destroy them as the LORD commanded Moses.
* `1Sa 6:6` Why then do you *_harden_* your hearts, as the Egyptians and Pharaoh hardened their hearts? When he had wrought wonderfully among them, did they not let the people go, and they departed?
* `Job 6:10` Then I would still have comfort—I would even *_harden_* myself in sorrow, which does not spare—for I have not concealed the words of the Holy One.
* `Psa 95:8` Do not *_harden_* your heart, as at Meribah, and as in the day of Massah in the wilderness,
* `Heb 3:8` Do not *_harden_* your hearts as in the provocation, as in the day of testing in the wilderness,
* `Heb 3:15` While it is said, "Today if you will hear his voice, do not *_harden_* your hearts as in the provocation."
* `Heb 4:7` Again he limits a certain day, saying through David, "Today," after so long a time, as it is said, "Today, if you will hear his voice, do not *_harden_* your hearts."

_12 verses containing HARDEN_

== HARDENED

* `Exo 7:13` And he *_hardened_* Pharaoh's heart and he did not listen to them, as the LORD had said.
* `Exo 7:14` And the LORD said to Moses, "Pharaoh's heart is *_hardened_*. He refuses to let the people go.
* `Exo 7:22` And the magicians of Egypt did so with their enchantments. And Pharaoh's heart was *_hardened_*, neither did he listen to them, as the LORD had said.
* `Exo 8:15` But when Pharaoh saw that there was respite, he *_hardened_* his heart and did not listen to them, as the LORD had said.
* `Exo 8:19` Then the magicians said to Pharaoh, "This is the finger of God." But Pharaoh's heart was *_hardened_* and he did not listen to them, as the LORD had said.
* `Exo 8:32` And Pharaoh *_hardened_* his heart at this time also, neither would he let the people go.
* `Exo 9:7` And Pharaoh sent, and behold, there was not one of the livestock of the Israelites dead. And the heart of Pharaoh was *_hardened_* and he did not let the people go.
* `Exo 9:12` And the LORD *_hardened_* the heart of Pharaoh, and he did not listen to them, as the LORD had spoken to Moses.
* `Exo 9:34` And when Pharaoh saw that the rain and the hail and the thunders had ceased, he sinned yet again and *_hardened_* his heart—he and his servants.
* `Exo 9:35` And the heart of Pharaoh was *_hardened_*, neither would he let the children of Israel go, as the LORD had spoken by Moses.
* `Exo 10:1` And the LORD said to Moses, "Go to Pharaoh, for I have *_hardened_* his heart and the heart of his servants, so that I might show these signs of mine before him,
* `Exo 10:20` But the LORD *_hardened_* Pharaoh's heart so that he would not let the children of Israel go.
* `Exo 10:27` But the LORD *_hardened_* Pharaoh's heart, and he would not let them go.
* `Exo 11:10` And Moses and Aaron did all these wonders before Pharaoh, and the LORD *_hardened_* Pharaoh's heart so that he would not let the children of Israel depart from his land.
* `Exo 14:8` And the LORD *_hardened_* the heart of Pharaoh king of Egypt, and he pursued the children of Israel. And the children of Israel went out with a high hand.
* `Deu 2:30` But Sihon king of Heshbon would not let us pass by him, for the LORD your God *_hardened_* his spirit and made his heart obstinate so that he might deliver him into your hand, as appears this day.
* `1Sa 6:6` Why then do you harden your hearts, as the Egyptians and Pharaoh *_hardened_* their hearts? When he had wrought wonderfully among them, did they not let the people go, and they departed?
* `2Ki 17:14` But they would not hear, but *_hardened_* their necks like the necks of their fathers who did not believe in the LORD their God.
* `2Ch 36:13` And he also rebelled against king Nebuchadnezzar, who had made him swear by God. But he stiffened his neck and *_hardened_* his heart from turning to the LORD God of Israel.
* `Neh 9:16` But they and our fathers dealt proudly and *_hardened_* their necks and did not listen to your commandments.
* `Neh 9:17` And they refused to obey, neither were they mindful of your wonders that you performed among them, but *_hardened_* their necks, and in their rebellion appointed a captain to return to their bondage. But you are a God ready to pardon, gracious and merciful, slow to anger, and of great kindness, and did not forsake them.
* `Neh 9:29` You testified against them so that you might bring them back to your law. Yet they dealt proudly and did not listen to your commandments, but sinned against your judgments (which if a man does, he shall live in them), withdrew the shoulder, *_hardened_* their neck, and would not hear.
* `Job 9:4` He is wise in heart and mighty in strength. Who has *_hardened_* himself against him and prospered?
* `Job 39:16` She is *_hardened_* against her young ones as though they were not hers. Her labor is in vain without fear,
* `Isa 63:17` O LORD, why have you made us to err from your ways and *_hardened_* our heart from your fear? Return for your servants' sake, the tribes of your inheritance.
* `Jer 7:26` Yet they did not listen to me nor incline their ear, but *_hardened_* their neck. They did worse than their fathers.
* `Jer 19:15` "Thus says the LORD of hosts, the God of Israel: 'Behold, I will bring upon this city and upon all her towns all the evil that I have pronounced against it, because they have *_hardened_* their necks so that they might not hear my words.'"
* `Dan 5:20` But when his heart was lifted up and his mind *_hardened_* in pride, he was deposed from his kingly throne, and they took his glory from him.
* `Mrk 6:52` For they did not consider the miracle of the loaves, but their heart was *_hardened_*.
* `Mrk 8:17` And when Jesus knew it, he says to them, "Why do you discuss that you have no bread? Do you still not perceive or understand? Is your heart still *_hardened_*?
* `Jhn 12:40` "He has blinded their eyes and *_hardened_* their heart so that they should not see with their eyes, nor understand with their heart, and be converted, and I should heal them."
* `Act 19:9` But when some were *_hardened_* and did not believe, but spoke evil of that way before the multitude, he departed from them and separated the disciples, disputing daily in the school of one, Tyrannus.
* `Heb 3:13` But exhort one another daily while it is called Today, lest any of you be *_hardened_* through the deceitfulness of sin.

_33 verses containing HARDENED_

== HARDENS

* `Pro 21:29` A wicked man *_hardens_* his face, but as for the upright, he directs his way.
* `Pro 28:14` Happy is the man who fears always, but he who *_hardens_* his heart shall fall into mischief.
* `Pro 29:1` He who is often reproved and *_hardens_* his neck shall suddenly be destroyed, and that without remedy.
* `Rom 9:18` Therefore, he has mercy on whom he wills to have mercy, and whom he wills he *_hardens_*.

_4 verses containing HARDENS_

== HARDER

* `Pro 18:19` A brother offended is *_harder_* to be won than a strong city, and their contentions are like the bars of a castle.
* `Jer 5:3` O LORD, are your eyes not upon the truth? You have stricken them, but they have not grieved. You have consumed them, but they have refused to receive correction. They have made their faces *_harder_* than a rock. They have refused to return.
* `Ezk 3:9` As an adamant *_harder_* than flint I have made your forehead. Do not fear them, neither be dismayed at their looks, though they are a rebellious house."

_3 verses containing HARDER_

== HARDLY

* `Exo 13:15` And it came to pass when Pharaoh would *_hardly_* let us go, that the LORD slew all the first-born in the land of Egypt, both the first-born of man and the first-born of beasts. Therefore, I sacrifice to the LORD all that opens the womb, being males, but all the first-born of my children I redeem.'
* `Isa 40:24` They have *_hardly_* been planted, they have *_hardly_* been sown, their stock has *_hardly_* taken root in the earth, and then he blows upon them and they wither, and the whirlwind takes them away as stubble.
* `Mrk 10:23` And Jesus looked around and says to his disciples, "How *_hardly_* those who have riches shall enter into the kingdom of God!"
* `Luk 9:39` And behold, a spirit takes him and he suddenly cries out, and it convulses him so that he foams, and bruising him, it *_hardly_* departs from him.
* `Luk 18:24` And when Jesus saw that he was very sorrowful, he said, "How *_hardly_* those who have riches will enter into the kingdom of God!
* `Act 27:8` And *_hardly_* passing it, came to a place which is called The Fair Havens, near to which was the city of Lasea.

_6 verses containing HARDLY_

== HARDNESS

* `Job 38:38` When the dust grows into *_hardness_* and the clods cleave fast together?
* `Mth 19:8` He says to them, "Moses, because of the *_hardness_* of your hearts, allowed you to put away your wives, but from the beginning it was not so.
* `Mrk 3:5` And when he had looked around at them with anger, being grieved for the *_hardness_* of their hearts, he says to the man, "Stretch forth your hand." And he stretched it out and his hand was restored whole as the other.
* `Mrk 10:5` And Jesus answered and said to them, "For the *_hardness_* of your heart he wrote you this precept.
* `Mrk 16:14` Afterward, he appeared to the eleven as they sat at the table and rebuked them for their unbelief and *_hardness_* of heart because they did not believe those who had seen him after he was risen.
* `Rom 2:5` But because of your *_hardness_* and impenitent heart, you treasure up for yourself wrath against the day of wrath and revelation of the righteous judgment of God,

_6 verses containing HARDNESS_

== HARDSHIP

* `2Ti 2:3` Therefore, endure *_hardship_* as a good soldier of Jesus Christ.

_1 verse containing HARDSHIP_

== HARDSHIPS

* `2Co 12:10` Therefore, I take pleasure in infirmities, in reproaches, in *_hardships_*, in persecutions, in distresses for Christ's sake. For when I am weak, then I am strong.

_1 verse containing HARDSHIPS_

== HARE

* `Lev 11:6` The *_hare_*, because he chews the cud, but does not divide the hoof, he is unclean to you;
* `Deu 14:7` Nevertheless, these you shall not eat, of those that chew the cud or of those that divide the cloven hoof: the camel, the *_hare_*, and the coney. For they chew the cud, but do not divide the hoof; therefore, they are unclean to you.

_2 verses containing HARE_

== HAREPH

* `1Ch 2:51` Salma the father of Beth-lehem, and *_Hareph_* the father of Beth-gader.

_1 verse containing HAREPH_

== HARETH

* `1Sa 22:5` And the prophet Gad said to David, "Do not abide in the hold. Depart, and come into the land of Judah." Then David departed and came into the forest of *_Hareth_*.

_1 verse containing HARETH_

== HARHAIAH

* `Neh 3:8` Next to him Uzziel the son of *_Harhaiah_*, of the goldsmiths, repaired. Next to him Hananiah the son of one of the perfumers repaired, and they fortified Jerusalem to the broad wall.

_1 verse containing HARHAIAH_

== HARHAS

* `2Ki 22:14` So Hilkiah the priest, Ahikam, Achbor, Shaphan, and Asahiah went to Huldah the prophetess, the wife of Shallum, the son of Tikvah, the son of *_Harhas_*, keeper of the wardrobe (now she dwelt in Jerusalem in the second quarter), and they spoke with her.

_1 verse containing HARHAS_

== HARHUR

* `Ezr 2:51` The children of Bakbuk, the children of Hakupha, the children of *_Harhur_*,
* `Neh 7:53` The children of Bakbuk, the children of Hakupha, the children of *_Harhur_*,

_2 verses containing HARHUR_

== HARIM

* `1Ch 24:8` The third to *_Harim_*, the fourth to Seorim,
* `Ezr 2:32` The children of *_Harim_*, three hundred and twenty;
* `Ezr 2:39` The children of *_Harim_*, one thousand and seventeen.
* `Ezr 10:21` And of the sons of *_Harim_*: Maaseiah, Elijah, Shemaiah, Jehiel, and Uzziah.
* `Ezr 10:31` And of the sons of *_Harim_*: Eliezer, Ishijah, Malchiah, Shemaiah, Shimeon,
* `Neh 3:11` Malchijah the son of *_Harim_* and Hashub the son of Pahath-moab repaired the other piece and the tower of the furnaces.
* `Neh 7:35` The children of *_Harim_*, three hundred and twenty;
* `Neh 7:42` The children of *_Harim_*, one thousand and seventeen.
* `Neh 10:5` *_Harim_*, Meremoth, Obadiah,
* `Neh 10:27` Malluch, *_Harim_*, and Baanah.
* `Neh 12:15` Of *_Harim_*, Adna; of Meraioth, Helkai;

_11 verses containing HARIM_

== HARIPH

* `Neh 7:24` The children of *_Hariph_*, one hundred and twelve;
* `Neh 10:19` *_Hariph_*, Anathoth, Nebai,

_2 verses containing HARIPH_

== HARLOT

* `Gen 34:31` And they said, "Should he deal with our sister as with a *_harlot_*?"
* `Gen 38:15` When Judah saw her, he thought her to be a *_harlot_* because she had covered her face.
* `Gen 38:21` Then he asked the men of that place, saying, "Where is the *_harlot_* who was openly by the wayside?" And they said, "There was no *_harlot_* in this place."
* `Gen 38:22` And he returned to Judah and said, "I cannot find her. And also the men of the place said that there was no *_harlot_* in this place."
* `Gen 38:24` And it came to pass about three months after, that it was told to Judah, saying, "Tamar your daughter-in-law has played the *_harlot_*, and also, behold she is with child by lewdness." And Judah said, "Bring her forth and let her be burnt."
* `Lev 19:29` 'Do not profane your daughter to cause her to be a *_harlot_*, lest the land should fall to lewdness and the land become full of wickedness.
* `Lev 21:14` A widow, a divorced woman, a profane woman, or a *_harlot_*, these he shall not take, but he shall take a virgin of his own people for a wife,
* `Deu 23:17` "There shall be no *_harlot_* among the daughters of Israel, neither a temple prostitute among the sons of Israel.
* `Deu 23:18` You shall not bring the wages of a *_harlot_* or the price of a dog into the house of the LORD your God for any vow, for even both of these are an abomination to the LORD your God.
* `Jsh 2:1` And Joshua the son of Nun sent from Shittim two men to spy secretly, saying, "Go, view the land, even Jericho." And they went and came into the house of a *_harlot_* named Rahab and lodged there.
* `Jsh 6:17` And the city shall be accursed, even it and all who are in it, to the LORD. Only Rahab the *_harlot_* shall live—she and all who are with her in the house—because she hid the messengers that we sent.
* `Jsh 6:22` But Joshua had said to the two men who spied out the country, "Go into the *_harlot_*'s house and bring out from there the woman and all that she has, as you swore to her."
* `Jsh 6:25` But Rahab the *_harlot_*, her father's household, and all that she had, Joshua saved alive. And she dwells in Israel even to this day because she hid the messengers which Joshua sent to spy out Jericho.
* `Jdg 11:1` Now Jephthah the Gileadite was a mighty man of valor, and he was the son of a *_harlot_*. And Gilead begot Jephthah.
* `Jdg 16:1` Then Samson went to Gaza and saw a *_harlot_* there and went in to her.
* `Jdg 19:2` And his concubine played the *_harlot_* against him and went away from him to her father's house to Beth-lehem-judah, and was there for four whole months.
* `Pro 7:10` And behold, a woman met him with the attire of a *_harlot_* and subtle of heart.
* `Isa 1:21` How the faithful city has become a *_harlot_*! It was full of judgment and righteousness lodged in it, but now murderers.
* `Isa 23:15` And it shall come to pass in that day, that Tyre shall be forgotten for seventy years, according to the days of one king. After the end of seventy years, it shall happen to Tyre as in the song of the *_harlot_*.
* `Isa 23:16` Take a harp, go throughout the city, you *_harlot_* who has been forgotten. Make sweet melody and sing many songs so that you may be remembered.
* `Jer 2:20` "For of old time I have broken your yoke and torn off your bonds, and you said, 'I will not transgress,' when upon every high hill and under every green tree you wander, playing the *_harlot_*.
* `Jer 3:1` He says, "If a man puts away his wife, and she goes from him and becomes another man's, shall he return to her again? Shall that land not be greatly polluted? But you have played the *_harlot_* with many lovers, yet return again to me," says the LORD.
* `Jer 3:3` Therefore, the showers have been withheld and there has been no latter rain. Yet you had a *_harlot_*'s forehead and you refused to be ashamed.
* `Jer 3:6` The LORD also said to me in the days of Josiah the king, "Have you seen what backsliding Israel has done? She has gone up upon every high mountain and under every green tree, and there has played the *_harlot_*.
* `Jer 3:8` And I saw that for all the causes by which backsliding Israel committed adultery, I had put her away and given her a bill of divorce. Yet her treacherous sister Judah did not fear, but went and played the *_harlot_* also.
* `Ezk 16:15` "But you trusted in your own beauty, played the *_harlot_* because of your renown, and poured out your fornications on everyone who passed by—it became his.
* `Ezk 16:16` And you took some of your garments, decked your high places with diverse colors, and played the *_harlot_* upon them. Such things shall not come, neither shall it be so.
* `Ezk 16:28` You have played the *_harlot_* also with the Assyrians, because you were insatiable. Indeed, you have played the *_harlot_* with them, and yet could not be satisfied.
* `Ezk 16:31` In that you build your eminent place in the head of every way and make your high place in every street. But you have not been like a *_harlot_*, in that you scorn payment.
* `Ezk 16:35` Therefore, O *_harlot_*, hear the word of the LORD.
* `Ezk 16:41` And they shall burn your houses with fire and execute judgments upon you in the sight of many women. And I will cause you to cease from playing the *_harlot_*, and you shall also give no payment anymore.
* `Ezk 23:5` "And Aholah played the *_harlot_* when she was mine, and she doted on her lovers, on the Assyrians her neighbors.
* `Ezk 23:19` Yet she multiplied her prostitutions in calling to remembrance the days of her youth in which she had played the *_harlot_* in the land of Egypt,
* `Ezk 23:44` Yet they went in to her, as they go in to a woman who plays the *_harlot_*. Thus they went in to Aholah and to Aholibah, the lewd women.
* `Hos 2:5` For their mother has played the *_harlot_*. She who conceived them has done shamefully. For she said, 'I will go after my lovers who give me my bread and my water, my wool and my flax, my oil and my drink.'
* `Hos 3:3` And I said to her, "You shall wait for me many days. You shall not play the *_harlot_* and you shall not be with another man. I will also be so to you."
* `Hos 4:15` Though you, Israel, play the *_harlot_*, yet do not let Judah offend, and do not come to Gilgal, neither go up to Beth-aven, nor swear, 'The LORD lives.'
* `Joe 3:3` And they have cast lots for my people, have given a boy for a *_harlot_*, and sold a girl for wine so that they might drink.
* `Amo 7:17` Therefore, thus says the LORD: 'Your wife shall be a *_harlot_* in the city, and your sons and your daughters shall fall by the sword. Your land shall be divided by line, and you shall die in a polluted land. And Israel shall surely go from his land into captivity.'"
* `Mic 1:7` And all her engraved images shall be beaten to pieces, all her wages shall be burned with the fire, and all her idols I will lay desolate, for she gathered it from the payment of a *_harlot_*, and they shall return to the payment of a *_harlot_*."
* `Nah 3:4` All because of the multitude of the lewd deeds of the well-favored *_harlot_*, the mistress of witchcrafts, who sells nations through her lewd deeds and families through her witchcrafts.
* `1Co 6:15` Do you not know that your bodies are the members of Christ? Shall I then take the members of Christ and make them the members of a *_harlot_*? By no means.
* `1Co 6:16` Or do you not know that he who is joined to a *_harlot_* is one body? For he says, "The two shall be one flesh."
* `Heb 11:31` By faith the *_harlot_* Rahab did not perish with those who did not believe, as she had received the spies with peace.
* `Jms 2:25` Likewise also, was Rahab the *_harlot_* not justified by works when she had received the messengers and had sent them out another way?
* `Rev 17:1` And one of the seven angels who had the seven vials came and talked with me, saying to me, "Come here. I will show to you the judgment of the great *_harlot_* who sits upon many waters,
* `Rev 17:15` And he says to me, "The waters which you saw where the *_harlot_* sits are peoples, multitudes, nations, and languages.
* `Rev 17:16` And the ten horns which you saw upon the beast, these shall hate the *_harlot_*, shall make her desolate and naked, and shall eat her flesh and burn her with fire.
* `Rev 19:2` For 'true and righteous are his judgments.' For he has judged the great *_harlot_* who corrupted the earth with her lewdness and has 'avenged the blood of his servants at her hand.'"

_49 verses containing HARLOT_

== HARLOTS

* `1Ki 3:16` Then two women who were *_harlots_* came to the king and stood before him.
* `Pro 29:3` He who loves wisdom makes his father glad, but he who keeps company with *_harlots_* spends his substance.
* `Jer 5:7` "How shall I pardon you for this? Your children have forsaken me and sworn by those who are not gods. When I had fed them to the full, they committed adultery and assembled themselves by troops in the *_harlots_*' houses.
* `Hos 4:14` I will not punish your daughters when they are guilty of lewdness, nor your spouses when they commit adultery, for they themselves are separated with prostitutes and they sacrifice with *_harlots_*. Therefore, the people who do not understand shall fall.
* `Mth 21:31` Which of the two did the will of his father?" They say to him, "The first." Jesus says to them, "Truly I say to you, that the tax collectors and the *_harlots_* go into the kingdom of God before you.
* `Mth 21:32` For John came to you in the way of righteousness, and you did not believe him, but the tax collectors and the *_harlots_* believed him. And you, when you had seen it, did not repent afterward to believe him.
* `Luk 15:30` But as soon as this son of yours had come, who has devoured your living with *_harlots_*, you have killed the fattened calf for him.'
* `Rev 17:5` And upon her forehead was a name written, "MYSTERY, BABYLON THE GREAT, THE MOTHER OF *_HARLOTS_*, AND ABOMINATIONS OF THE EARTH."

_8 verses containing HARLOTS_

== HARM

* `Gen 31:52` This heap is a witness and this pillar is a witness that I will not pass over this heap to you and that you shall not pass over this heap and this pillar to me for *_harm_*.
* `Lev 5:16` And he shall make amends for the *_harm_* that he has done in the holy thing, and shall add to it the fifth part and give it to the priest. And the priest shall make an atonement for him with the ram of the trespass-offering, and he shall be forgiven.
* `Num 35:23` Or, without seeing him, casts upon him any stone by which a man may die so that he dies, but he was not his enemy nor sought his *_harm_*,
* `1Sa 26:21` Then Saul said, "I have sinned. Return, my son David, for I will no longer do you *_harm_* because my soul was precious in your eyes this day. Behold I have played the fool and have erred exceedingly."
* `2Sa 20:6` And David said to Abishai, "Now Sheba the son of Bichri shall do us more *_harm_* than Absalom did. Take your lord's servants and pursue him, lest he get for himself fortified cities and escape us."
* `2Ki 4:41` But he said, "Then bring meal." And he cast it into the pot and he said, "Pour some out for the people so that they may eat." And there was no *_harm_* in the pot.
* `1Ch 16:22` Saying, 'Do not touch my anointed and do my prophets no *_harm_*.'
* `Psa 105:15` Saying, "Do not touch my anointed and do my prophets no *_harm_*."
* `Pro 3:30` Do not strive with a man without cause, if he has done you no *_harm_*.
* `Jer 39:12` "Take him, look well to him, and do him no *_harm_*, but do to him even as he says to you."
* `Act 16:28` But Paul cried with a loud voice, saying, "Do yourself no *_harm_*, for we are all here."
* `Act 27:21` But after long abstinence, Paul stood forth in the midst of them, and said, "Sirs, you should have listened to me and not set sail from Crete and gained this *_harm_* and loss.
* `Act 28:5` And he shook off the animal into the fire and felt no *_harm_*.
* `Act 28:21` And they said to him, "We have neither received letters from Judea concerning you, nor have any of the brothers who came reported or spoken any *_harm_* about you.
* `1Pe 3:13` And who is he who will *_harm_* you if you are followers of that which is good?
* `Rev 9:19` For their power is in their mouth and in their tails. For their tails are like serpents and have heads, and with them they do *_harm_*.

_16 verses containing HARM_

== HARMLESS

* `Heb 7:26` For such a high priest was fitting for us, who is holy, *_harmless_*, undefiled, separate from sinners, and made higher than the heavens,

_1 verse containing HARMLESS_

== HARNEPHER

* `1Ch 7:36` The sons of Zophah: Suah, *_Harnepher_*, Shual, Beri, Imrah,

_1 verse containing HARNEPHER_

== HARNESS

* `1Ki 20:11` And the king of Israel answered and said, "Tell him, 'Do not let him who girds on his *_harness_* boast himself as he who takes it off.'"
* `1Ki 22:34` And a certain man drew a bow at random and smote the king of Israel between the joints of the *_harness_*. Therefore, he said to the driver of his chariot, "Turn your hand and carry me out of the host, for I am wounded."
* `2Ch 18:33` And a certain man drew a bow at random and smote the king of Israel between the joints of the *_harness_*. Therefore, he said to his chariot-man, "Turn your hand so that you may carry me out of the host, for I am wounded."
* `Jer 46:4` *_Harness_* the horses and mount, you horsemen, and stand forth with your helmets. Furbish the spears and put on the coats of mail.

_4 verses containing HARNESS_

== HAROD

* `Jdg 7:1` Then Jerubbaal (who is Gideon) and all the people who were with him rose early and encamped beside the well of *_Harod_*. And the host of the Midianites were on the north side of them in the valley by the hill of Moreh.

_1 verse containing HAROD_

== HARODITE

* `2Sa 23:25` Shammah the *_Harodite_*, Elika the *_Harodite_*,

_1 verse containing HARODITE_

== HAROEH

* `1Ch 2:52` And Shobal the father of Kirjath-jearim had sons: *_Haroeh_* and half of the Manahethites.

_1 verse containing HAROEH_

== HARORITE

* `1Ch 11:27` Shammoth the *_Harorite_*, Helez the Pelonite,

_1 verse containing HARORITE_

== HAROSHETH

* `Jdg 4:2` And the LORD sold them into the hand of Jabin king of Canaan who reigned in Hazor, the captain of whose host was Sisera, who dwelt in *_Harosheth_* of the Gentiles.
* `Jdg 4:13` And Sisera collected all his chariots, even nine hundred chariots of iron, and all the people who were with him, from *_Harosheth_* of the Gentiles to the river of Kishon.
* `Jdg 4:16` But Barak pursued the chariots and the host to *_Harosheth_* of the Gentiles. And all the host of Sisera fell upon the edge of the sword, and there was not a man left.

_3 verses containing HAROSHETH_

== HARP

* `Gen 4:21` And his brother's name was Jubal. He was the father of all those who handle the *_harp_* and pipe.
* `Gen 31:27` Why did you flee away secretly and steal away from me and not tell me? I would have sent you away with mirth, with songs, with tambourine, and with *_harp_*.
* `1Sa 10:5` After that you shall come to the hill of God where the garrison of the Philistines is. And it shall come to pass, when you have come there to the city, that you shall meet a company of prophets coming down from the high place with a psaltery, a tambourine, a pipe, and a *_harp_* before them, and they will prophesy.
* `1Sa 16:16` Let our lord now command your servants who are before you to seek a man who is a skillful player on a *_harp_*. And it shall come to pass, when the evil spirit from God is upon you, that he will play with his hand, and you will be well."
* `1Sa 16:23` And it came to pass, when the evil spirit from God was upon Saul, that David took a *_harp_* and played with his hand. Then Saul was refreshed and was well, and the evil spirit departed from him.
* `1Ch 25:3` Of Jeduthun, the sons of Jeduthun: Gedaliah, Zeri, Jeshaiah, Hashabiah, and Mattithiah, six, under the hands of their father Jeduthun who prophesied with a *_harp_* to give thanks and to praise the LORD.
* `Job 21:12` They take the tambourine and *_harp_* and rejoice at the sound of the pipe.
* `Job 30:31` My *_harp_* is also turned to mourning, and my pipe into the voice of those who weep."
* `Psa 33:2` Praise the LORD with the *_harp_*. Sing to him with the psaltery and an instrument of ten strings.
* `Psa 43:4` Then I will go to the altar of God, to God, my exceeding joy. Upon the *_harp_* I will even praise you, O God my God.
* `Psa 49:4` I will incline my ear to a parable. I will open my dark saying upon the *_harp_*.
* `Psa 57:8` Awake, my glory. Awake, psaltery and *_harp_*. I myself will awake early.
* `Psa 71:22` I will also praise you with the psaltery, even your truth, O my God. To you I will sing with the *_harp_*, O Holy One of Israel.
* `Psa 81:2` Take a psalm and bring here the tambourine, the pleasant *_harp_* with the psaltery.
* `Psa 92:3` Upon an instrument of ten strings and upon the psaltery, upon the *_harp_* with a solemn sound.
* `Psa 98:5` Sing to the LORD with the *_harp_*, with the *_harp_* and the voice of a psalm.
* `Psa 108:2` Awake, psaltery and *_harp_*. I myself will awake early.
* `Psa 147:7` Sing to the LORD with thanksgiving. Sing praise upon the *_harp_* to our God,
* `Psa 149:3` Let them praise his name in the dance. Let them sing praises to him with the tambourine and *_harp_*.
* `Psa 150:3` Praise him with the sound of the trumpet. Praise him with the psaltery and *_harp_*.
* `Isa 5:12` And the *_harp_*, the psaltery, the tambourine, pipe, and wine are in their feasts, but they do not regard the work of the LORD, neither consider the operation of his hands.
* `Isa 16:11` Therefore, my heart shall sound like a *_harp_* for Moab and my inward parts for Kir-haresh.
* `Isa 23:16` Take a *_harp_*, go throughout the city, you harlot who has been forgotten. Make sweet melody and sing many songs so that you may be remembered.
* `Isa 24:8` The mirth of tambourines ceases. The noise of those who rejoice ends. The joy of the *_harp_* ceases.
* `Dan 3:5` That at the time you hear the sound of the horn, flute, *_harp_*, sackbut, psaltery, bagpipe, and all kinds of music, you shall fall down and worship the golden image that Nebuchadnezzar the king has set up.
* `Dan 3:7` Therefore, at that time, when all the people heard the sound of the horn, flute, *_harp_*, sackbut, psaltery, and all kinds of music, all the people, the nations, and the languages fell down and worshiped the golden image that Nebuchadnezzar the king had set up.
* `Dan 3:10` You, O king, have made a decree, that every man who hears the sound of the horn, flute, *_harp_*, sackbut, psaltery, bagpipe, and all kinds of music, shall fall down and worship the golden image.
* `Dan 3:15` Now if you are ready at the time you hear the sound of the horn, flute, *_harp_*, sackbut, psaltery, bagpipe, and all kinds of music, to fall down and worship the image which I have made, very well. But if you do not worship, you shall be cast the same hour into the midst of a burning fiery furnace. And who is that God who shall deliver you out of my hands?"
* `Amo 6:5` You chant to the sound of the *_harp_* and invent for yourselves instruments of music, like David.
* `1Co 14:7` And even lifeless things giving sound, whether pipe or *_harp_*, unless they give a distinction in the sounds, how shall it be known what is piped or harped?

_30 verses containing HARP_

== HARPED

* `1Co 14:7` And even lifeless things giving sound, whether pipe or harp, unless they give a distinction in the sounds, how shall it be known what is piped or *_harped_*?

_1 verse containing HARPED_

== HARPERS

* `Rev 14:2` And I heard a voice from heaven, like the voice of many waters and like the voice of a great thunder. And I heard the voice of *_harpers_* harping with their harps.
* `Rev 18:22` And the voice of *_harpers_*, musicians, of pipers, and trumpeters shall no longer be heard in you. No craftsman of any craft shall be found in you anymore. The sound of a millstone shall no longer be heard in you.

_2 verses containing HARPERS_

== HARPING

* `Rev 14:2` And I heard a voice from heaven, like the voice of many waters and like the voice of a great thunder. And I heard the voice of harpers *_harping_* with their harps.

_1 verse containing HARPING_

== HARPS

* `2Sa 6:5` And David and all the house of Israel played before the LORD on all manner of instruments made of fir wood, even on *_harps_*, on psalteries, on tambourines, on horns, and on cymbals.
* `1Ki 10:12` And the king made from the almug trees pillars for the house of the LORD and for the king's house and *_harps_* and psalteries for singers. There have not come such almug trees, nor have they been seen to this day.
* `1Ch 13:8` And David and all Israel played before God with all their might, with singing, with *_harps_*, with psalteries, with tambourines, with cymbals, and with trumpets.
* `1Ch 15:16` And David spoke to the chief of the Levites to appoint their brothers to be the singers with instruments of music—psalteries, *_harps_*, and cymbals—sounding aloud and lifting up the voice with joy.
* `1Ch 15:21` And Mattithiah, Elipheleh, Mikneiah, Obed-edom, Jeiel, and Azaziah with *_harps_* on the Sheminith to excel.
* `1Ch 15:28` Thus all Israel brought up the ark of the covenant of the LORD with shouting, with the sound of the horn, with trumpets, and with cymbals, making a noise with psalteries and *_harps_*.
* `1Ch 16:5` Asaph the chief, and next to him Zechariah, Jeiel, Shemiramoth, Jehiel, Mattithiah, Eliab, Benaiah, and Obed-edom; and Jeiel with psalteries and with *_harps_*; but Asaph made a sound with cymbals;
* `1Ch 25:1` Moreover, David and the captains of the host separated for the service some of the sons of Asaph, of Heman, and of Jeduthun, who should prophesy with *_harps_*, with psalteries, and with cymbals. And this is the number of the workmen according to their service:
* `1Ch 25:6` All these were under the hands of their father in the music in the house of the LORD with cymbals, psalteries, and *_harps_*, for the service of the house of God, according to the king's order to Asaph, Jeduthun, and Heman.
* `2Ch 5:12` And also the Levites who were the singers, all of them of Asaph, of Heman, of Jeduthun, with their sons and their brothers, being arrayed in white linen, having cymbals and psalteries and *_harps_*, stood at the east end of the altar, and with them one hundred and twenty priests sounding with trumpets),
* `2Ch 9:11` And the king made terraces from the algum trees for the house of the LORD and for the king's palace, and *_harps_* and psalteries for singers. And there were none such seen before in the land of Judah.
* `2Ch 20:28` And they came to Jerusalem with psalteries, *_harps_*, and trumpets to the house of the LORD.
* `2Ch 29:25` And he set the Levites in the house of the LORD with cymbals, with psalteries, and with *_harps_*, according to the commandment of David, of Gad the king's seer, and Nathan the prophet, for thus was the commandment of the LORD by his prophets.
* `Neh 12:27` And at the dedication of the wall of Jerusalem, they sought the Levites out of all their places to bring them to Jerusalem to keep the dedication with gladness, with thanksgivings, with singing, and with cymbals, psalteries, and *_harps_*.
* `Psa 137:2` We hung our *_harps_* upon the willows in its midst.
* `Isa 14:11` Your pomp is brought down to the grave, and also the noise of your *_harps_*. The worm is spread under you, and the worms cover you.
* `Isa 30:32` And in every place where the grounded staff passes, which the LORD lays upon him, it shall be with tambourines and *_harps_*. And in battles of shaking he will fight with it.
* `Ezk 26:13` And I will cause the noise of your songs to cease, and the sound of your *_harps_* shall no longer be heard.
* `Amo 5:23` Take away from me the noise of your songs, for I will not hear the melody of your *_harps_*.
* `Rev 5:8` And when he had taken the book, the four living beings and the twenty-four elders fell down before the Lamb, each of them having *_harps_* and golden vials full of odors, which are the prayers of saints.
* `Rev 14:2` And I heard a voice from heaven, like the voice of many waters and like the voice of a great thunder. And I heard the voice of harpers harping with their *_harps_*.
* `Rev 15:2` And I saw something like a sea of glass mingled with fire. And those who had gained the victory over the beast, over his image, over his mark, and over the number of his name, stand on the sea of glass, having the *_harps_* of God.

_22 verses containing HARPS_

== HARROW

* `Job 39:10` Can you bind the wild ox with ropes in the furrow? Or will he *_harrow_* the valleys after you?

_1 verse containing HARROW_

== HARROWS

* `2Sa 12:31` And he brought forth the people who were in it and put them under saws, under *_harrows_* of iron, and under axes of iron, and made them pass through the brick-kiln. And thus he did to all the cities of the children of Ammon. So David and all the people returned to Jerusalem.
* `1Ch 20:3` And he brought out the people who were in it and cut them with saws, with *_harrows_* of iron, and with axes. And thus David dealt with all the cities of the children of Ammon. And David and all the people returned to Jerusalem.

_2 verses containing HARROWS_

== HARSHA

* `Ezr 2:52` The children of Bazluth, the children of Mehida, the children of *_Harsha_*,
* `Neh 7:54` The children of Bazlith, the children of Mehida, the children of *_Harsha_*,

_2 verses containing HARSHA_

== HARSHLY

* `Gen 16:6` But Abram said to Sarai, "Behold, your servant is in your hand. Do to her as it pleases you." And when Sarai dealt *_harshly_* with her, she fled from her face.

_1 verse containing HARSHLY_

== HARUM

* `1Ch 4:8` And Coz begot Anub, Zobebah, and the families of Aharhel the son of *_Harum_*.

_1 verse containing HARUM_

== HARUMAPH

* `Neh 3:10` And next to them Jedaiah the son of *_Harumaph_* repaired, even over against his house. And next to him Hattush the son of Hashabniah repaired.

_1 verse containing HARUMAPH_

== HARUPHITE

* `1Ch 12:5` Eluzai, Jerimoth, Bealiah, Shemariah, Shephatiah the *_Haruphite_*,

_1 verse containing HARUPHITE_

== HARUZ

* `2Ki 21:19` Amon was twenty-two years old when he began to reign, and he reigned two years in Jerusalem. And his mother's name was Meshullemeth, the daughter of *_Haruz_* of Jotbah.

_1 verse containing HARUZ_

== HARVEST

* `Gen 8:22` While the earth remains, seed-time and *_harvest_*, cold and heat, summer and winter, and day and night shall not cease."
* `Gen 30:14` And Reuben went, in the days of wheat-*_harvest_*, and found mandrakes in the field and brought them to his mother Leah. Then Rachel said to Leah, "Give me, I pray you, some of your son's mandrakes."
* `Gen 45:6` For these two years the famine has been in the land, and there are still five years in which there shall neither be tillage nor *_harvest_*.
* `Exo 23:16` And the feast of *_harvest_*, the first-fruits of your labors, which you have sown in the field; and the feast of in-gathering, which is at the end of the year, when you have gathered in your labors out of the field.
* `Exo 34:21` "Six days you shall work, but on the seventh day you shall rest. In time of plowing and in *_harvest_* you shall rest.
* `Exo 34:22` And you shall observe the feast of weeks with the first-fruits of wheat-*_harvest_*, and the feast of in-gathering at the year's end.
* `Lev 19:9` 'And when you reap the *_harvest_* of your land, you shall not wholly reap the corners of your field, neither shall you gather the gleanings of your *_harvest_*.
* `Lev 23:10` "Speak to the children of Israel and say to them, 'When you come into the land which I give to you and reap the *_harvest_* thereof, you shall bring a sheaf of the first-fruits of your *_harvest_* to the priest.
* `Lev 23:22` 'And when you reap the *_harvest_* of your land, you shall not make clean riddance of the corners of your field when you reap, neither shall you gather any gleaning of your *_harvest_*. You shall leave them for the poor and for the stranger. I am the LORD your God.'"
* `Lev 25:5` That which grows of its own accord of your *_harvest_*, you shall not reap, neither gather the grapes of your vine undressed, for it is a year of rest for the land.
* `Deu 24:19` "When you cut down your *_harvest_* in your field and forget a sheaf in the field, you shall not go back to fetch it. It shall be for the stranger, for the fatherless, and for the widow, so that the LORD your God may bless you in all the work of your hands.
* `Jsh 3:15` And when those who bore the ark had come to the Jordan, and the feet of the priests who bore the ark were dipped in the brim of the water (for the Jordan overflows all its banks all the days of *_harvest_*),
* `Jdg 15:1` But it came to pass after a while, in the time of wheat-*_harvest_*, that Samson visited his wife with a kid, and he said, "I will go in to my wife into the chamber." But her father would not allow him to go in.
* `Rth 1:22` So Naomi returned, and Ruth the Moabitess her daughter-in-law with her, who returned from the country of Moab. And they came to Beth-lehem in the beginning of barley-*_harvest_*.
* `Rth 2:21` And Ruth the Moabitess said, "He also said to me, 'You shall keep close by my young men until they have ended all my *_harvest_*.'"
* `Rth 2:23` So she kept close by the young women of Boaz to glean until the end of barley-*_harvest_* and of wheat-*_harvest_*, and dwelt with her mother-in-law.
* `1Sa 6:13` And the people of Beth-shemesh were reaping their wheat *_harvest_* in the valley. And they lifted up their eyes, saw the ark, and rejoiced to see it.
* `1Sa 8:12` And he will appoint for himself captains over thousands and captains over fifties and will set them to till his ground, to reap his *_harvest_*, and to make his instruments of war and instruments of his chariots.
* `1Sa 12:17` Is it not wheat-*_harvest_* today? I will call to the LORD, and he will send thunder and rain so that you may perceive and see that your wickedness is great which you have done in the sight of the LORD in asking for yourselves a king."
* `2Sa 21:9` And he delivered them into the hands of the Gibeonites, and they hanged them on the hill before the LORD. And they fell all seven together and were put to death in the days of *_harvest_*, in the first days, in the beginning of barley *_harvest_*.
* `2Sa 21:10` And Rizpah the daughter of Aiah took sackcloth and spread it for herself upon the rock, from the beginning of *_harvest_* until water dropped upon them out of heaven, and allowed neither the birds of the air to rest on them by day, nor the beasts of the field by night.
* `2Sa 23:13` And three of the thirty chiefs went down and came to David in the *_harvest_* time to the cave of Adullam, and the troop of the Philistines encamped in the valley of Rephaim.
* `Job 5:5` The hungry eat up his *_harvest_* and take it even out of the thorns, and the robber swallows up their substance.
* `Pro 6:8` Provides her provisions in the summer and gathers her food in the *_harvest_*.
* `Pro 10:5` He who gathers in summer is a wise son, but he who sleeps in *_harvest_* is a son who causes shame.
* `Pro 20:4` The sluggard will not plow by reason of the cold; therefore, he shall beg in *_harvest_* and have nothing.
* `Pro 25:13` As the cold of snow in the time of *_harvest_*, so is a faithful messenger to those who send him, for he refreshes the soul of his masters.
* `Pro 26:1` As snow in summer and as rain in *_harvest_*, so honor is not appropriate for a fool.
* `Isa 9:3` You have multiplied the nation. You have increased its joy. They joy before you according to the joy in *_harvest_*, and as men rejoice when they divide the plunder.
* `Isa 16:9` Therefore, I will wail with the weeping of Jazer for the vine of Sibmah. I will water you with my tears, O Heshbon and Elealeh, for on your summer fruits and on your *_harvest_* the battle shout has fallen.
* `Isa 17:11` In the day you shall make your plant to grow and in the morning you shall make your seed to flourish, but the *_harvest_* shall be a heap in the day of grief and of desperate sorrow.
* `Isa 18:4` For thus the LORD said to me: "I will take my rest, and I will consider in my dwelling-place like a clear heat upon herbs and like a cloud of dew in the heat of *_harvest_*."
* `Isa 18:5` For before the *_harvest_* when the bud is perfect and the sour grape is ripening in the flower, he shall both cut off the sprigs with pruning-hooks and take away and cut down the branches.
* `Isa 23:3` And by great waters the seed of Sihor, the *_harvest_* of the river, is her revenue, and she is a market of nations.
* `Jer 5:17` And they shall eat up your *_harvest_* and your bread, which your sons and your daughters should eat. They shall eat up your flocks and your herds. They shall eat up your vines and your fig-trees. They shall impoverish with the sword your fortified cities, in which you have trusted.
* `Jer 5:24` They do not say in their heart, "Let us now fear the LORD our God who gives rain, both the former and the latter, in its season. He reserves to us the appointed weeks of *_harvest_*."
* `Jer 8:20` "The *_harvest_* has past, the summer has ended, and we are not saved."
* `Jer 50:16` Cut off the sower from Babylon and him who handles the sickle in the time of *_harvest_*. For fear of the oppressing sword, they shall each turn to his people and shall each flee to his own land.
* `Jer 51:33` For thus says the LORD of hosts, the God of Israel: "The daughter of Babylon is like a threshing-floor at the time when it is trodden. Yet a little while and the time of her *_harvest_* shall come."
* `Hos 6:11` Also, O Judah, he has set a *_harvest_* for you, when I returned the captivity of my people."
* `Joe 1:11` Be ashamed, O farmers. Howl, O vine-dressers, for the wheat and for the barley, because the *_harvest_* of the field has perished.
* `Joe 3:13` Put in the sickle, for the *_harvest_* is ripe. Come, tread, for the press is full. The vats overflow, for their wickedness is great."
* `Amo 4:7` "And also I have withheld the rain from you when there were yet three months to the *_harvest_*. And I caused it to rain upon one city and did not cause it to rain upon another city. One piece was rained upon, and the piece on which it did not rain withered.
* `Mth 9:37` Then he says to his disciples, "The *_harvest_* truly is plentiful, but the laborers are few.
* `Mth 9:38` Therefore, pray to the Lord of the *_harvest_* that he will send forth laborers into his *_harvest_*."
* `Mth 13:30` Let both grow together until the *_harvest_*. And in the time of *_harvest_* I will say to the reapers, "Gather first the tares and bind them in bundles to burn them, but gather the wheat into my barn."'"
* `Mth 13:39` The enemy who sowed them is the devil. The *_harvest_* is the end of the age. The reapers are the angels.
* `Mrk 4:29` But when the fruit is brought forth, immediately he puts in the sickle because the *_harvest_* has come."
* `Luk 10:2` Therefore, he said to them, "The *_harvest_* is truly great, but the laborers are few. Pray therefore to the Lord of the *_harvest_* that he would send forth laborers into his *_harvest_*.
* `Jhn 4:35` Do you not say, 'There are yet four months and then comes *_harvest_*'? Behold, I say to you, lift up your eyes and look at the fields, for they are already white for *_harvest_*.
* `Rev 14:15` And another angel came out of the temple, crying with a loud voice to him who sat on the cloud, "Thrust in your sickle and reap, for the time has come for you to reap, because the *_harvest_* of the earth is ripe."

_51 verses containing HARVEST_

== HARVESTER

* `Isa 17:5` And it shall be as when the *_harvester_* gathers the grain and reaps the heads with his arm. And it shall be as he who gathers heads [of grain] in the valley of Rephaim.
* `Jer 9:22` Speak, "Thus says the LORD: 'Even the carcasses of men shall fall as dung upon the open field and as the handful after the *_harvester_*, and no one shall gather them.'"

_2 verses containing HARVESTER_

== HASADIAH

* `1Ch 3:20` And Hashubah, Ohel, Berechiah, *_Hasadiah_*, and Jushab-hesed, five.

_1 verse containing HASADIAH_

== HASENUAH

* `1Ch 9:7` And of the sons of Benjamin: Sallu the son of Meshullam, the son of Hodaviah, the son of *_Hasenuah_*,

_1 verse containing HASENUAH_

== HASHABIAH

* `1Ch 6:45` The son of *_Hashabiah_*, the son of Amaziah, the son of Hilkiah,
* `1Ch 9:14` And of the Levites: Shemaiah the son of Hasshub, the son of Azrikam, the son of *_Hashabiah_*, of the sons of Merari;
* `1Ch 25:3` Of Jeduthun, the sons of Jeduthun: Gedaliah, Zeri, Jeshaiah, *_Hashabiah_*, and Mattithiah, six, under the hands of their father Jeduthun who prophesied with a harp to give thanks and to praise the LORD.
* `1Ch 25:19` The twelfth to *_Hashabiah_*—he, his sons, and his brothers were twelve;
* `1Ch 26:30` And of the Hebronites, *_Hashabiah_* and his brothers, men of valor, one thousand and seven hundred, had the oversight of Israel beyond the Jordan westward in all the business of the LORD and in the service of the king.
* `1Ch 27:17` Of the Levites, *_Hashabiah_* the son of Kemuel; of the Aaronites, Zadok;
* `2Ch 35:9` And also Conaniah, Shemaiah, Nethaneel, his brothers, and *_Hashabiah_*, Jehiel, and Jozabad, chief of the Levites, gave to the Levites for passover-offerings five thousand small livestock, and five hundred oxen.
* `Ezr 8:19` And they also brought *_Hashabiah_*, and with him Jeshaiah of the sons of Merari, his brothers and their sons, twenty men,
* `Ezr 8:24` Then I separated twelve of the chief of the priests: Sherebiah, *_Hashabiah_*, and ten of their brothers with them.
* `Neh 3:17` After him the Levites repaired: Rehum the son of Bani. Next to him *_Hashabiah_*, the ruler of the half part of Keilah, repaired in his part.
* `Neh 10:11` Micha, Rehob, *_Hashabiah_*,
* `Neh 11:15` Also of the Levites: Shemaiah the son of Hashub, the son of Azrikam, the son of *_Hashabiah_*, the son of Bunni;
* `Neh 11:22` The overseer also of the Levites at Jerusalem was Uzzi the son of Bani, the son of *_Hashabiah_*, the son of Mattaniah, the son of Micha, of the sons of Asaph, the singers, over the business of the house of God.
* `Neh 12:21` Of Hilkiah, *_Hashabiah_*; of Jedaiah, Nethaneel.
* `Neh 12:24` And the chief of the Levites were *_Hashabiah_*, Sherebiah, and Jeshua the son of Kadmiel, with their brothers over against them, to praise and to give thanks according to the commandment of David the man of God, ward over against ward.

_15 verses containing HASHABIAH_

== HASHABNAH

* `Neh 10:25` Rehum, *_Hashabnah_*, Maaseiah,

_1 verse containing HASHABNAH_

== HASHABNIAH

* `Neh 3:10` And next to them Jedaiah the son of Harumaph repaired, even over against his house. And next to him Hattush the son of *_Hashabniah_* repaired.
* `Neh 9:5` Then the Levites, Jeshua, Kadmiel, Bani, *_Hashabniah_*, Sherebiah, Hodijah, Shebaniah, and Pethahiah, said, "Stand up and bless the LORD your God forever and ever: Blessed be your glorious name, which is exalted above all blessing and praise.

_2 verses containing HASHABNIAH_

== HASHBADANA

* `Neh 8:4` And Ezra the scribe stood upon a pulpit of wood, which they had made for this purpose. And beside him stood Mattithiah, Shema, Anaiah, Urijah, Hilkiah, and Maaseiah on his right hand, and on his left hand, Pedaiah, Mishael, Malchiah, Hashum, *_Hashbadana_*, Zechariah, and Meshullam.

_1 verse containing HASHBADANA_

== HASHEM

* `1Ch 11:34` The sons of *_Hashem_* the Gizonite, Jonathan the son of Shage the Hararite,

_1 verse containing HASHEM_

== HASHMONAH

* `Num 33:29` And they went from Mithcah and encamped in *_Hashmonah_*.
* `Num 33:30` And they departed from *_Hashmonah_* and encamped at Moseroth.

_2 verses containing HASHMONAH_

== HASHUB

* `Neh 3:11` Malchijah the son of Harim and *_Hashub_* the son of Pahath-moab repaired the other piece and the tower of the furnaces.
* `Neh 3:23` After him Benjamin and *_Hashub_* repaired over against their house. After him Azariah the son of Maaseiah, the son of Ananiah, repaired by his house.
* `Neh 10:23` Hoshea, Hananiah, *_Hashub_*,
* `Neh 11:15` Also of the Levites: Shemaiah the son of *_Hashub_*, the son of Azrikam, the son of Hashabiah, the son of Bunni;

_4 verses containing HASHUB_

== HASHUBAH

* `1Ch 3:20` And *_Hashubah_*, Ohel, Berechiah, Hasadiah, and Jushab-hesed, five.

_1 verse containing HASHUBAH_

== HASHUM

* `Ezr 2:19` The children of *_Hashum_*, two hundred and twenty-three;
* `Ezr 10:33` Of the sons of *_Hashum_*: Mattenai, Mattathah, Zabad, Eliphelet, Jeremai, Manasseh, and Shimei.
* `Neh 7:22` The children of *_Hashum_*, three hundred and twenty-eight;
* `Neh 8:4` And Ezra the scribe stood upon a pulpit of wood, which they had made for this purpose. And beside him stood Mattithiah, Shema, Anaiah, Urijah, Hilkiah, and Maaseiah on his right hand, and on his left hand, Pedaiah, Mishael, Malchiah, *_Hashum_*, Hashbadana, Zechariah, and Meshullam.
* `Neh 10:18` Hodijah, *_Hashum_*, Bezai,

_5 verses containing HASHUM_

== HASHUPHA

* `Neh 7:46` The Nethinims: the children of Ziha, the children of *_Hashupha_*, the children of Tabbaoth,

_1 verse containing HASHUPHA_

== HASRAH

* `2Ch 34:22` And Hilkiah and those whom the king had appointed went to Huldah the prophetess, the wife of Shallum the son of Tikvath, the son of *_Hasrah_*, keeper of the wardrobe (now she dwelt in Jerusalem in the second quarter), and they spoke to her to that effect.

_1 verse containing HASRAH_

== HASSENAAH

* `Neh 3:3` But the fish-gate was built by the sons of *_Hassenaah_*, who also laid its beams, set up its doors, its locks, and its bars.

_1 verse containing HASSENAAH_

== HASSHUB

* `1Ch 9:14` And of the Levites: Shemaiah the son of *_Hasshub_*, the son of Azrikam, the son of Hashabiah, of the sons of Merari;

_1 verse containing HASSHUB_

== HASTE

* `Gen 24:46` And she made *_haste_* and let down her pitcher from her shoulder and said, 'Drink, and I will give your camels drink also.' So I drank, and she made the camels drink also.
* `Gen 43:30` And Joseph made *_haste_*, for his heart yearned toward his brother, and he sought a place to weep. And he entered into his chamber and wept there.
* `Exo 10:16` Then Pharaoh called for Moses and Aaron in *_haste_* and he said, "I have sinned against the LORD your God and against you.
* `Exo 12:11` And thus you shall eat it: with your loins girded, your shoes on your feet, and your staff in your hand. And you shall eat it in *_haste_*. It is the LORD'S passover.
* `Exo 12:33` And the Egyptians were urgent upon the people so that they might send them out of the land in *_haste_*, for they said, "We are all dead men."
* `Exo 34:8` And Moses made *_haste_* and bowed his head toward the earth and worshiped.
* `Deu 16:3` You shall eat no leavened bread with it. Seven days you shall eat unleavened bread with it, even the bread of affliction, for you came forth from the land of Egypt in *_haste_*, so that you may remember the day when you came forth from the land of Egypt all the days of your life.
* `Deu 32:35` To me belongs vengeance and recompense. Their foot shall slide in due time, for the day of their calamity is at hand, and the things that shall come upon them make *_haste_*.
* `Jdg 9:48` And Abimelech ascended mount Zalmon—he and all the people who were with him—and Abimelech took an ax in his hand and cut down a bough from the trees, and took it, laid it on his shoulder, and said to the people who were with him, "What you have seen me do, make *_haste_*, and do as I have done."
* `Jdg 13:10` And the woman made *_haste_* and ran and declared to her husband, and said to him, "Behold, the man who came to me the other day has appeared to me."
* `1Sa 9:12` And they answered them and said, "He is. Behold, he is before you. Make *_haste_* now, for he came today to the city, for there is a sacrifice of the people today in the high place.
* `1Sa 21:8` And David said to Ahimelech, "And is there not here under your hand a spear or sword? For I have neither brought my sword nor my weapons with me because the king's business required *_haste_*."
* `1Sa 23:26` And Saul went on this side of the mountain, and David and his men on that side of the mountain. And David made *_haste_* to get away for fear of Saul, for Saul and his men surrounded David and his men to take them.
* `1Sa 23:27` But there came a messenger to Saul, saying, "Make *_haste_* and come, for the Philistines have invaded the land."
* `1Sa 25:18` Then Abigail made *_haste_* and took two hundred loaves, two bottles of wine, five sheep ready and dressed, five measures of parched grain, one hundred clusters of raisins, and two hundred cakes of figs, and laid them on donkeys.
* `2Sa 4:4` And Jonathan, Saul's son, had a son who was lame in his feet. He was five years old when the tidings of Saul and Jonathan came out of Jezreel, and his nurse took him up and fled. And it came to pass, as she made *_haste_* to flee, that he fell and became lame. And his name was Mephibosheth.
* `2Ki 7:15` And they went after them to the Jordan. And behold, the whole way was full of garments and vessels, which the Syrians had cast away in their *_haste_*. And the messengers returned and told the king.
* `2Ch 35:21` But he sent ambassadors to him, saying, "What have I to do with you, king of Judah? I do not come against you this day, but against the house with which I have war. For God commanded me to make *_haste_*. Forbear from meddling with God, who is with me, so that he may not destroy you."
* `Ezr 4:23` Now when the copy of king Artaxerxes' letter was read before Rehum, Shimshai the scribe, and their companions, they went up in *_haste_* to Jerusalem to the Jews and made them to cease by force and power.
* `Est 5:5` Then the king said, "Cause Haman to make *_haste_* so that he may do as Esther has said." So the king and Haman came to the banquet that Esther had prepared.
* `Est 6:10` Then the king said to Haman, "Make *_haste_* and take the apparel and the horse as you have said, and do even so to Mordecai the Jew who sits at the king's gate. Let nothing fail of all that you have spoken."
* `Job 20:2` "Therefore, my thoughts cause me to answer, and for this I make *_haste_*.
* `Psa 31:22` For I said in my *_haste_*, "I am cut off from before your eyes." Nevertheless, you heard the voice of my supplications when I cried to you.
* `Psa 38:22` Make *_haste_* to help me, O Lord my salvation.
* `Psa 40:13` Be pleased, O LORD, to deliver me. O LORD, make *_haste_* to help me.
* `Psa 70:1` [To the Chief Musician. A Psalm of David: to bring to remembrance.] Make *_haste_*, O God, to deliver me. Make *_haste_* to help me, O LORD.
* `Psa 70:5` But I am poor and needy. Make *_haste_* to me, O God. You are my help and my deliverer. O LORD, make no delay.
* `Psa 71:12` O God, do not be far from me. O my God, make *_haste_* for my help.
* `Psa 116:11` I said in my *_haste_*, "All men are liars."
* `Psa 119:60` I made *_haste_* and did not delay to keep your commandments.
* `Psa 141:1` [A Psalm of David.] LORD, I cry to you. Make *_haste_* to me. Give ear to my voice when I cry to you.
* `Pro 1:16` For their feet run to evil and make *_haste_* to shed blood.
* `Pro 28:20` A faithful man shall abound with blessings, but he who makes *_haste_* to be rich shall not be innocent.
* `Sos 8:14` [Lady:] Make *_haste_*, my beloved, and be like a gazelle or a young buck upon the mountains of spices.
* `Isa 28:16` Therefore, thus says the Lord GOD: "Behold, I lay a stone in Zion for a foundation, a tried stone, a precious cornerstone, a sure foundation. He who believes shall not make *_haste_*.
* `Isa 49:17` Your children shall make *_haste_*. Your destroyers and those who made you waste shall go forth from you.
* `Isa 52:12` For you shall not go out with *_haste_*, nor go by flight, for the LORD will go before you, and the God of Israel will be your rear-ward.
* `Isa 59:7` Their feet run to evil, and they make *_haste_* to shed innocent blood. Their thoughts are thoughts of iniquity. Wasting and destruction are in their paths.
* `Jer 9:18` And let them make *_haste_* and take up a wailing for us so that our eyes may run down with tears and our eyelids gush out with waters.
* `Dan 2:25` Then Arioch brought in Daniel before the king in *_haste_*, and said thus to him: "I have found a man of the captives of Judah who will make known to the king the interpretation."
* `Dan 3:24` Then Nebuchadnezzar the king was astonished, rose up in *_haste_*, and spoke, and said to his counselors, "Did we not cast three men bound into the midst of the fire?" They answered and said to the king, "True, O king."
* `Dan 6:19` Then the king arose very early in the morning and went in *_haste_* to the den of lions.
* `Nah 2:5` He shall recount his nobles. They shall stumble in their walk. They shall make *_haste_* to the wall thereof, and the defense shall be prepared.
* `Mrk 6:25` And she came in immediately with *_haste_* to the king, and asked, saying, "I wish that you would give me at once the head of John the Baptist in a dish."
* `Luk 1:39` And Mary arose in those days and went into the hill-country with *_haste_* to a city of Judah,
* `Luk 2:16` And they came with *_haste_* and found Mary and Joseph, and the baby lying in a manger.
* `Luk 19:5` And when Jesus came to the place, he looked up and saw him, and said to him, "Zaccheus, make *_haste_* and come down, for today I must abide at your house."
* `Luk 19:6` And he made *_haste_*, came down, and received him joyfully.
* `Act 22:18` And saw him saying to me, 'Make *_haste_*, and depart quickly from Jerusalem, for they will not receive your testimony concerning me.'

_49 verses containing HASTE_

== HASTEN

* `Gen 19:22` *_Hasten_*, escape there, for I cannot do anything until you get there." Therefore, the name of the city was called Zoar.
* `Gen 45:9` *_Hasten_*, return to my father, and say to him, 'Thus says your son Joseph: "God has made me lord of all Egypt. Come down to me. Do not delay.
* `Gen 45:13` And you shall tell my father about all my glory in Egypt and about all that you have seen. And you shall *_hasten_* and bring down my father here."
* `Jsh 10:13` And the sun stood still and the moon stayed until the people had avenged themselves upon their enemies. Is this not written in the book of Jasher? So the sun stood still in the midst of the heavens and did not *_hasten_* to go down about a whole day.
* `1Sa 20:38` And Jonathan cried after the boy, "Make speed, *_hasten_*, do not stay." And Jonathan's boy gathered up the arrows and came to his master.
* `1Ki 22:9` Then the king of Israel called an officer and said, "*_Hasten_* here Micaiah the son of Imlah."
* `2Ch 24:5` And he convened the priests and the Levites and said to them, "Go out to the cities of Judah and gather from all Israel money to repair the house of your God from year to year, and see that you *_hasten_* the matter." But the Levites did not *_hasten_* it.
* `Job 40:23` Behold, he drinks up a river and does not *_hasten_*. He trusts that he can draw up the Jordan into his mouth.
* `Psa 16:4` Their sorrows shall be multiplied who *_hasten_* after another god. Their drink-offerings of blood I will not offer, nor take their names into my lips.
* `Psa 22:19` But do not be far from me, O LORD. O my strength, *_hasten_* to help me.
* `Psa 55:8` "I would *_hasten_* my escape from the windy storm and tempest."
* `Ecc 2:25` For who can eat, or who else can *_hasten_* to it more than I?
* `Isa 5:19` Who say, "Let him make speed and *_hasten_* his work so that we may see it. And let the counsel of the Holy One of Israel draw near and come so that we may know it!"
* `Isa 60:22` A little one shall become a thousand and a small one a strong nation. I, the LORD, will *_hasten_* it in its time."
* `Jer 1:12` Then the LORD said to me, "You have seen well. For I will *_hasten_* my word to perform it."

_15 verses containing HASTEN_

== HASTENED

* `Gen 18:6` And Abraham *_hastened_* into the tent to Sarah and said, "Quickly make ready three measures of fine meal, knead it, and make cakes upon the hearth."
* `Gen 18:7` And Abraham ran to the herd, brought a calf tender and good, and gave it to a young man, and he *_hastened_* to dress it.
* `Gen 19:15` And when the morning arose, the angels *_hastened_* Lot, saying, "Arise, take your wife and your two daughters who are here, lest you be consumed in the iniquity of the city."
* `Gen 24:18` And she said, "Drink, my lord." And she *_hastened_* and let down her pitcher upon her hand and gave him drink.
* `Gen 24:20` And she *_hastened_* and emptied her pitcher into the trough, and ran back to the well to draw water, and drew for all his camels.
* `Exo 5:13` And the task-masters *_hastened_* them, saying, "Fulfill your works, your daily tasks, as when there was straw."
* `Jsh 4:10` For the priests who bore the ark stood in the midst of the Jordan until everything was finished that the LORD commanded Joshua to speak to the people, according to all that Moses commanded Joshua. And the people *_hastened_* and passed over.
* `Jsh 8:14` And it came to pass when the king of Ai saw it, that they *_hastened_* and rose early, and the men of the city went out against Israel to battle—he and all his people—at a time appointed, before the plain. But he did not know that there was an ambush against him behind the city.
* `Jsh 8:19` And the ambush arose quickly out of their place, and they ran as soon as he had stretched out his hand. And they entered into the city, took it, and *_hastened_* to set the city on fire.
* `Jdg 20:37` And the ambushers *_hastened_* and rushed upon Gibeah, and they drew themselves along and smote all the city with the edge of the sword.
* `1Sa 17:48` And it came to pass, when the Philistine arose and came and drew near to meet David, that David *_hastened_* and ran toward the army to meet the Philistine.
* `1Sa 25:23` And when Abigail saw David, she *_hastened_*, alighted off the donkey, fell before David on her face, and bowed herself to the ground.
* `1Sa 25:34` For indeed, as the LORD God of Israel lives, who has kept me back from hurting you, unless you had *_hastened_* and come to meet me, surely there had not been left to Nabal by the morning light any male person."
* `1Sa 25:42` And Abigail *_hastened_*, arose, and rode upon a donkey, with five of her attendants who went after her. And she went after the messengers of David and became his wife.
* `1Sa 28:24` And the woman had a fattened calf in the house and she *_hastened_* and killed it, and took flour, kneaded it, and baked unleavened bread from it.
* `2Sa 19:16` And Shimei the son of Gera, a Benjaminite who was from Bahurim, *_hastened_* and came down with the men of Judah to meet king David.
* `1Ki 20:41` And he *_hastened_* and took the ashes away from his face, and the king of Israel discerned him that he was of the prophets.
* `2Ki 9:13` Then they *_hastened_*, and every man took his garment, put it under him on the top of the stairs, and blew with trumpets, saying, "Jehu is king."
* `2Ch 26:20` And Azariah the chief priest and all the priests looked upon him, and behold, he was leprous in his forehead, and they thrust him out from there. Indeed, he himself *_hastened_* to go out, because the LORD had smitten him.
* `Est 3:15` The posts departed, being *_hastened_* by the king's commandment, and the decree was given in the palace of Shushan. And the king and Haman sat down to drink, but the city of Shushan was perplexed.
* `Est 6:12` And Mordecai came back to the king's gate, but Haman *_hastened_* to his house mourning and having his head covered.
* `Est 6:14` And while they were still talking with him, the king's chamberlains came and *_hastened_* to bring Haman to the banquet that Esther had prepared.
* `Est 8:14` So the posts who rode upon royal horses went out, being *_hastened_* and pressed on by the king's commandment. And the decree was given at the palace of Shushan.
* `Job 31:5` If I have walked with vanity, or if my foot has *_hastened_* to deceit,
* `Psa 48:5` They saw it, and so they wondered. They were troubled and *_hastened_* away.
* `Psa 104:7` At your rebuke they fled. At the voice of your thunder they *_hastened_* away.
* `Jer 17:16` As for me, I have not *_hastened_* from being a pastor to follow you, neither have I desired the woeful day. You know that which was uttered by my lips was right before you.
* `Act 20:16` For Paul had determined to sail by Ephesus because he would not spend the time in Asia, for he *_hastened_*, if it were possible for him, to be at Jerusalem on the day of Pentecost.

_28 verses containing HASTENED_

== HASTENING

* `Isa 16:5` And in mercy the throne shall be established. And he shall sit upon it in truth in the tabernacle of David, judging, seeking judgment, and *_hastening_* righteousness.
* `2Pe 3:12` Looking for and *_hastening_* to the coming of the day of God, in which the heavens being on fire will be dissolved and the elements will melt with fervent heat?

_2 verses containing HASTENING_

== HASTENS

* `Job 9:26` They have passed by like the swift ships, like the eagle that *_hastens_* to the prey.
* `Pro 7:23` Until a dart strikes through his liver, as a bird *_hastens_* to the snare, and does not know that it is for his life.
* `Pro 19:2` Also, for the soul to be without knowledge, it is not good. And he who *_hastens_* with his feet sins.
* `Pro 28:22` He who *_hastens_* to be rich has an evil eye and does not consider that poverty shall come upon him.
* `Ecc 1:5` The sun also rises, and the sun goes down, and *_hastens_* to his place where he arose.
* `Isa 51:14` The captive exile *_hastens_* so that he may be released. He shall not die in the pit, neither shall his bread fail.
* `Jer 48:16` "The calamity of Moab is near to come, and his affliction *_hastens_* fast.
* `Hab 1:8` Their horses are also swifter than the leopards and are more fierce than the evening wolves. And their horsemen shall spread themselves and their horsemen shall come from far. They shall fly as the eagle that *_hastens_* to devour.
* `Zph 1:14` The great day of the LORD is near, it is near and *_hastens_* greatly, even the voice of the day of the LORD. The mighty man shall cry there bitterly.

_9 verses containing HASTENS_

== HASTILY

* `Gen 41:14` Then Pharaoh sent and called Joseph, and they brought him *_hastily_* out of the dungeon. And he shaved himself and changed his clothing and came before Pharaoh.
* `Jdg 9:54` Then he called *_hastily_* to the young man his armor-bearer, and said to him, "Draw your sword and slay me so that men do not say of me, 'A woman slew him.'" And his young man thrust him through, and he died.
* `1Sa 4:14` And when Eli heard the noise of the crying, he said, "What does the noise of this tumult mean?" And the man came in *_hastily_* and told Eli.
* `1Ki 20:33` Now the men diligently observed whether anything would come from him, and *_hastily_* caught it, and they said, "Your brother Ben-hadad." Then he said, "Go, bring him." Then Ben-hadad came forth to him, and he caused him to come up into the chariot.
* `Pro 20:21` An inheritance may be gotten *_hastily_* at the beginning, but its end shall not be blessed.
* `Pro 25:8` Do not go forth *_hastily_* to strive, lest you not know what to do in the end thereof when your neighbor has put you to shame.
* `Jhn 11:31` Then the Jews who were with her in the house and comforting her, when they saw that Mary rose *_hastily_* and went out, followed her, saying, "She goes to the grave to weep there."
* `1Ti 5:22` Do not *_hastily_* lay hands on any man, neither be partaker of other men's sins. Keep yourself pure.

_8 verses containing HASTILY_

== HASTY

* `Pro 14:29` He who is slow to wrath is of great understanding, but he who is *_hasty_* of spirit exalts folly.
* `Pro 21:5` The thoughts of the diligent tend only to plenteousness, but of everyone who is *_hasty_*, only to poverty.
* `Pro 29:20` Do you see a man who is *_hasty_* in his words? There is more hope for a fool than for him.
* `Ecc 5:2` Do not be rash with your mouth, and do not let your heart be *_hasty_* to utter anything before God. For God is in heaven, and you upon earth; therefore, let your words be few.
* `Ecc 7:9` Do not be *_hasty_* in your spirit to be angry, for anger rests in the bosom of fools.
* `Ecc 8:3` Do not be *_hasty_* to go out of his sight. Do not stand in an evil thing, for he does whatever pleases him.
* `Dan 2:15` He answered and said to Arioch the king's captain, "Why is the decree so *_hasty_* from the king?" Then Arioch made the thing known to Daniel.
* `Hab 1:6` For behold, I raise up the Chaldeans, that bitter and *_hasty_* nation, which shall march through the breadth of the land to possess the dwelling-places that are not theirs.

_8 verses containing HASTY_

== HASUPHA

* `Ezr 2:43` The Nethinims: the children of Ziha, the children of *_Hasupha_*, the children of Tabbaoth,

_1 verse containing HASUPHA_

