= HUBS - HYSSOP
:toc:

== HUBS

* `1Ki 7:33` And the work of the wheels was like the work of a chariot wheel. Their axletrees, their rims, their *_hubs_*, and their spokes were all molten.

_1 verse containing HUBS_

== HUKKOK

* `Jsh 19:34` And then the border turns westward to Aznoth-tabor, goes out from there to *_Hukkok_*, reaches to Zebulun on the south side, reaches to Asher on the west side, and to Judah upon the Jordan toward the sunrise;

_1 verse containing HUKKOK_

== HUKOK

* `1Ch 6:75` *_Hukok_* with its suburbs, and Rehob with its suburbs.

_1 verse containing HUKOK_

== HUL

* `Gen 10:23` And the children of Aram: Uz, *_Hul_*, Gether, and Mash.
* `1Ch 1:17` The sons of Shem: Elam, Asshur, Arphaxad, Lud, Aram, Uz, *_Hul_*, Gether, and Meshech.

_2 verses containing HUL_

== HULDAH

* `2Ki 22:14` So Hilkiah the priest, Ahikam, Achbor, Shaphan, and Asahiah went to *_Huldah_* the prophetess, the wife of Shallum, the son of Tikvah, the son of Harhas, keeper of the wardrobe (now she dwelt in Jerusalem in the second quarter), and they spoke with her.
* `2Ch 34:22` And Hilkiah and those whom the king had appointed went to *_Huldah_* the prophetess, the wife of Shallum the son of Tikvath, the son of Hasrah, keeper of the wardrobe (now she dwelt in Jerusalem in the second quarter), and they spoke to her to that effect.

_2 verses containing HULDAH_

== HUMAN

* `Ezk 4:12` And you shall eat it as barley cakes and bake it with *_human_* excrement in their sight."
* `Dan 8:25` And through his understanding he shall also cause deceit to prosper in his hand. He shall magnify himself in his heart, and by peace shall destroy many. He shall also stand up against the Prince of princes, but he shall be broken, though not by *_human_* hands.

_2 verses containing HUMAN_

== HUMBLE

* `Exo 10:3` And Moses and Aaron came to Pharaoh and said to him, "Thus says the LORD God of the Hebrews: 'How long will you refuse to *_humble_* yourself before me? Let my people go so that they may serve me.
* `Deu 8:2` And you shall remember all the way which the LORD your God has led you these forty years in the wilderness, to *_humble_* you and to prove you, to know what was in your heart, whether you would keep his commandments or not.
* `Deu 8:16` Who fed you in the wilderness with manna which your fathers did not know so that he might *_humble_* you and that he might prove you, to do you good at your latter end—
* `Jdg 19:24` Behold, here is my daughter, a virgin, and his concubine. I will bring them out now, and you may *_humble_* them and do with them what seems good to you, but to this man do not do such a vile thing."
* `2Ch 7:14` If my people who are called by my name *_humble_* themselves, pray, seek my face, and turn from their wicked ways, then I will hear from heaven, forgive their sin, and will heal their land.
* `2Ch 33:23` And did not *_humble_* himself before the LORD, as Manasseh his father had humbled himself. But Amon trespassed more and more.
* `2Ch 36:12` And he did that which was evil in the sight of the LORD his God and did not *_humble_* himself before Jeremiah the prophet speaking from the mouth of the LORD.
* `Job 22:29` When men are cast down, you shall say, 'There is exaltation,' and he shall save the *_humble_* person.
* `Psa 9:12` For he who avenges blood remembers them. He does not forget the cry of the *_humble_*.
* `Psa 10:12` Arise, O LORD. O God, lift up your hand. Do not forget the *_humble_*.
* `Psa 10:17` LORD, you have heard the desire of the *_humble_*. You will prepare their heart. You will cause your ear to hear,
* `Psa 34:2` My soul shall make her boast in the LORD. The *_humble_* shall hear of it and be glad.
* `Psa 69:32` The *_humble_* shall see this and be glad. And you who seek God, your heart shall live.
* `Pro 6:3` Do this now, my son, and deliver yourself when you have come into the hand of your friend: go, *_humble_* yourself, and make urgent request to your friend.
* `Pro 16:19` It is better to be of a *_humble_* spirit with the lowly, than to divide the plunder with the proud.
* `Pro 29:23` A man's pride shall bring him low, but honor shall uphold the *_humble_* in spirit.
* `Isa 57:15` For thus says the high and lofty One who inhabits eternity, whose name is Holy: "I dwell in the high and holy place, with him also who is of a contrite and *_humble_* spirit, to revive the spirit of the *_humble_* and to revive the heart of the contrite ones.
* `Jer 13:18` Say to the king and to the queen, "*_Humble_* yourselves, sit down, for your principalities shall come down, even the crown of your glory."
* `2Co 12:21` And lest, when I come again, my God may *_humble_* me among you, and I shall bewail many who have sinned already and have not repented of the uncleanness, lewdness, and lasciviousness which they have committed.
* `Jms 4:6` But he gives more grace. Therefore, he says, "God resists the proud, but gives grace to the *_humble_*."
* `Jms 4:10` *_Humble_* yourselves in the sight of the Lord and he will lift you up.
* `1Pe 5:5` Likewise, you younger ones, submit yourselves to the elder. Indeed, all of you be subject to one another and be clothed with humility, for "God resists the proud and gives grace to the *_humble_*."
* `1Pe 5:6` *_Humble_* yourselves therefore under the mighty hand of God so that he may exalt you in due time,

_23 verses containing HUMBLE_

== HUMBLED

* `Lev 26:41` And that I also have walked contrary to them and have brought them into the land of their enemies, if then their uncircumcised hearts are *_humbled_* and they then accept the punishment of their iniquity,
* `Deu 8:3` And he *_humbled_* you and allowed you to be hungry, and fed you with manna which you did not know, neither did your fathers know, so that he might make you know that man does not live by bread only, but man lives by every word that proceeds out of the mouth of the LORD.
* `Deu 21:14` And it shall be, if you have no delight in her, then you shall let her go where she wishes. But you shall not sell her at all for money and you shall not make merchandise of her, because you have *_humbled_* her.
* `Deu 22:24` Then you shall bring them both out to the gate of that city and stone them with stones so that they may die—the young woman because she did not cry, though she was in the city, and the man because he has *_humbled_* his neighbor's wife. Thus you shall remove evil from among you.
* `Deu 22:29` Then the man who lay with her shall give to the young woman's father fifty shekels of silver, and she shall be his wife. Because he has *_humbled_* her, he may not put her away all his days.
* `2Ki 22:19` Because your heart was tender and you have *_humbled_* yourself before the LORD when you heard what I spoke against this place and against its inhabitants, that they should become a desolation and a curse, and have rent your clothes and wept before me, I also have heard you,' says the LORD.
* `2Ch 12:6` Upon this the princes of Israel and the king *_humbled_* themselves and said, "The LORD is righteous."
* `2Ch 12:7` And when the LORD saw that they *_humbled_* themselves, the word of the LORD came to Shemaiah, saying, "They have *_humbled_* themselves; therefore, I will not destroy them, but I will grant them some deliverance. And my wrath shall not be poured out upon Jerusalem by the hand of Shishak.
* `2Ch 12:12` And when he *_humbled_* himself, the wrath of the LORD turned from him so that he would not destroy him altogether. And also in Judah things went well.
* `2Ch 30:11` Nevertheless, some of Asher, Manasseh, and of Zebulun *_humbled_* themselves and came to Jerusalem.
* `2Ch 32:26` However, Hezekiah *_humbled_* himself for the pride of his heart, both he and the inhabitants of Jerusalem, so that the wrath of the LORD did not come upon them in the days of Hezekiah.
* `2Ch 33:12` And when he was in affliction, he implored the LORD his God and *_humbled_* himself greatly before the God of his fathers.
* `2Ch 33:19` His prayer also, and how God was entreated by him, and all his sin, his trespass, and the places in which he built high places, and set up groves and engraved images, before he was *_humbled_*, behold, they are written among the sayings of the seers.
* `2Ch 33:23` And did not humble himself before the LORD, as Manasseh his father had *_humbled_* himself. But Amon trespassed more and more.
* `2Ch 34:27` "Because your heart was tender and you *_humbled_* yourself before God when you heard his words against this place and against its inhabitants, and *_humbled_* yourself before me and rent your clothes and wept before me, I have even heard you also," says the LORD.
* `Psa 35:13` But as for me, when they were sick, my clothing was sackcloth. I *_humbled_* my soul with fasting, and my prayer returned into my own bosom.
* `Isa 2:11` The lofty looks of man shall be *_humbled_* and the haughtiness of men shall be abased, and the LORD alone shall be exalted in that day.
* `Isa 5:15` And man shall be brought down, the mighty man shall be *_humbled_*, and the eyes of the lofty shall be abased.
* `Isa 10:33` Behold, the Lord, the LORD of hosts will lop the bough with terror, and the high ones of stature shall be hewn down and the haughty shall be *_humbled_*.
* `Jer 44:10` They are not *_humbled_* even to this day, neither have they feared, nor walked in my law, nor in my statutes, which I set before you and before your fathers."'
* `Lam 3:20` My soul has them still in remembrance and is *_humbled_* in me.
* `Ezk 22:10` In you they have uncovered their fathers' nakedness. In you they have *_humbled_* her who was set apart for pollution.
* `Ezk 22:11` And one has committed abomination with his neighbor's wife, another has lewdly defiled his daughter-in-law, and another in you has *_humbled_* his sister, his father's daughter.
* `Dan 5:22` And you his son, O Belshazzar, have not *_humbled_* your heart, though you knew all this,
* `Phl 2:8` And being found in fashion as a man, he *_humbled_* himself and became obedient to death, even the death of the cross.

_25 verses containing HUMBLED_

== HUMBLENESS

* `Col 3:12` Put on therefore, as the elect of God, holy and beloved, hearts of mercies, kindness, *_humbleness_* of mind, meekness, patience,

_1 verse containing HUMBLENESS_

== HUMBLES

* `1Ki 21:29` "Do you see how Ahab *_humbles_* himself before me? Because he *_humbles_* himself before me, I will not bring the evil in his days. But in his son's days I will bring the evil upon his house."
* `Psa 10:10` He crouches and *_humbles_* himself so that the poor may fall by his strong ones.
* `Psa 113:6` Who *_humbles_* himself to behold the things that are in heaven and in the earth?
* `Isa 2:9` And the common man bows down, and the great man *_humbles_* himself; therefore, do not forgive them.
* `Mth 18:4` Whoever therefore *_humbles_* himself as this little child, the same is greatest in the kingdom of heaven.
* `Mth 23:12` Whoever exalts himself shall be abased, and he who *_humbles_* himself shall be exalted.
* `Luk 14:11` For whoever exalts himself shall be abased, and he who *_humbles_* himself shall be exalted."
* `Luk 18:14` I tell you, this man went down to his house justified rather than the other. For everyone who exalts himself shall be abased, and he who *_humbles_* himself shall be exalted."

_8 verses containing HUMBLES_

== HUMBLY

* `2Sa 16:4` Then the king said to Ziba, "Behold, all that pertained to Mephibosheth is yours." And Ziba said, "I *_humbly_* implore you that I may find grace in your sight, my lord, O king."
* `Mic 6:8` He has shown you, O man, what is good. And what does the LORD require of you, but to do justly, to love mercy, and to walk *_humbly_* with your God?

_2 verses containing HUMBLY_

== HUMILIATION

* `Act 8:33` In his *_humiliation_* his judgment was taken away. And who shall declare his generation? For his life is taken from the earth."

_1 verse containing HUMILIATION_

== HUMILITY

* `Pro 15:33` The fear of the LORD is the instruction of wisdom, and before honor is *_humility_*.
* `Pro 18:12` Before destruction the heart of man is haughty, and before honor is *_humility_*.
* `Pro 22:4` By *_humility_* and the fear of the LORD are riches, honor, and life.
* `Act 20:19` Serving the Lord with all *_humility_* of mind and with many tears and temptations which befell me by the lying in wait of the Jews,
* `Col 2:18` Let no man beguile you of your reward in a voluntary *_humility_* and worshiping of angels, intruding into those things which he has not seen, vainly puffed up by his fleshly mind,
* `Col 2:23` These things have indeed a show of wisdom in will-worship, *_humility_*, and neglecting of the body, but not in any honor to the satisfying of the flesh.
* `1Pe 5:5` Likewise, you younger ones, submit yourselves to the elder. Indeed, all of you be subject to one another and be clothed with *_humility_*, for "God resists the proud and gives grace to the humble."

_7 verses containing HUMILITY_

== HUMTAH

* `Jsh 15:54` *_Humtah_*, Kirjath-arba (which is Hebron), and Zior; nine cities with their villages.

_1 verse containing HUMTAH_

== HUNDRED

* `Gen 5:3` And Adam lived one *_hundred_* and thirty years and begot a son in his own likeness, after his image, and called his name Seth.
* `Gen 5:4` And the days of Adam after he had begotten Seth were eight *_hundred_* years. And he begot sons and daughters.
* `Gen 5:5` And all the days that Adam lived were nine *_hundred_* and thirty years, and he died.
* `Gen 5:6` And Seth lived one *_hundred_* and five years and begot Enos.
* `Gen 5:7` And Seth lived after he begot Enos eight *_hundred_* and seven years and begot sons and daughters.
* `Gen 5:8` And all the days of Seth were nine *_hundred_* and twelve years, and he died.
* `Gen 5:10` And Enos lived after he begot Cainan eight *_hundred_* and fifteen years and begot sons and daughters.
* `Gen 5:11` And all the days of Enos were nine *_hundred_* and five years, and he died.
* `Gen 5:13` And Cainan lived after he begot Mahalaleel eight *_hundred_* and forty years and begot sons and daughters.
* `Gen 5:14` And all the days of Cainan were nine *_hundred_* and ten years, and he died.
* `Gen 5:16` And Mahalaleel lived after he begot Jared eight *_hundred_* and thirty years and begot sons and daughters.
* `Gen 5:17` And all the days of Mahalaleel were eight *_hundred_* and ninety-five years, and he died.
* `Gen 5:18` And Jared lived one *_hundred_* and sixty-two years and he begot Enoch.
* `Gen 5:19` And Jared lived after he begot Enoch eight *_hundred_* years and begot sons and daughters.
* `Gen 5:20` And all the days of Jared were nine *_hundred_* and sixty-two years, and he died.
* `Gen 5:22` And Enoch walked with God after he begot Methuselah three *_hundred_* years and begot sons and daughters.
* `Gen 5:23` And all the days of Enoch were three *_hundred_* and sixty-five years.
* `Gen 5:25` And Methuselah lived one *_hundred_* and eighty-seven years, and begot Lamech.
* `Gen 5:26` And Methuselah lived after he begot Lamech seven *_hundred_* and eighty-two years and begot sons and daughters.
* `Gen 5:27` And all the days of Methuselah were nine *_hundred_* and sixty-nine years, and he died.
* `Gen 5:28` And Lamech lived one *_hundred_* and eighty-two years and begot a son,
* `Gen 5:30` And Lamech lived after he begot Noah five *_hundred_* and ninety-five years and begot sons and daughters.
* `Gen 5:31` And all the days of Lamech were seven *_hundred_* and seventy-seven years, and he died.
* `Gen 5:32` And Noah was five *_hundred_* years old, and Noah begot Shem, Ham, and Japheth.
* `Gen 6:3` And the LORD said, "My Spirit shall not always strive with man, because he is flesh; therefore, his days shall be one *_hundred_* and twenty years."
* `Gen 6:15` And this is the fashion in which you shall make it: the length of the ark shall be three *_hundred_* cubits, its breadth fifty cubits, and its height thirty cubits.
* `Gen 7:6` And Noah was six *_hundred_* years old when the flood of waters was on the earth.
* `Gen 7:24` And the waters prevailed upon the earth one *_hundred_* and fifty days.
* `Gen 8:3` And the waters returned from off the earth continually. And after the end of the *_hundred_* and fifty days the waters were abated.
* `Gen 8:13` And it came to pass in the six *_hundred_* and first year, in the first month, on the first day of the month, the waters were dried from off the earth. And Noah removed the covering of the ark and looked, and behold, the face of the ground was dry.
* `Gen 9:28` And Noah lived after the flood three *_hundred_* and fifty years.
* `Gen 9:29` And all the days of Noah were nine *_hundred_* and fifty years. And he died.
* `Gen 11:10` These are the generations of Shem. Shem was one *_hundred_* years old and begot Arphaxad two years after the flood.
* `Gen 11:11` And Shem lived after he begot Arphaxad five *_hundred_* years and begot sons and daughters.
* `Gen 11:13` And Arphaxad lived after he begot Salah four *_hundred_* and three years and begot sons and daughters.
* `Gen 11:15` And Salah lived after he begot Eber four *_hundred_* and three years and begot sons and daughters.
* `Gen 11:17` And Eber lived after he begot Peleg four *_hundred_* and thirty years and begot sons and daughters.
* `Gen 11:19` And Peleg lived after he begot Reu two *_hundred_* and nine years and begot sons and daughters.
* `Gen 11:21` And Reu lived after he begot Serug two *_hundred_* and seven years and begot sons and daughters.
* `Gen 11:23` And Serug lived after he begot Nahor two *_hundred_* years and begot sons and daughters.
* `Gen 11:25` And Nahor lived after he begot Terah one *_hundred_* and nineteen years and begot sons and daughters.
* `Gen 11:32` And the days of Terah were two *_hundred_* and five years, and Terah died in Haran.
* `Gen 14:14` And when Abram heard that his brother was taken captive, he armed his trained servants, born in his own house, three *_hundred_* and eighteen, and pursued them to Dan.
* `Gen 15:13` And he said to Abram, "Know certainly that your offspring shall be strangers in a land that is not theirs and shall serve them, and they shall afflict them four *_hundred_* years.
* `Gen 17:17` Then Abraham fell upon his face and laughed and said in his heart, "Shall a child be born to him who is one *_hundred_* years old? And shall Sarah, who is ninety years old, bear?"
* `Gen 21:5` And Abraham was one *_hundred_* years old when his son Isaac was born to him.
* `Gen 23:1` And Sarah was one *_hundred_* and twenty-seven years old. These were the years of the life of Sarah.
* `Gen 23:15` "My lord, listen to me. The land is worth four *_hundred_* shekels of silver. What is that between you and me? Therefore, bury your dead."
* `Gen 23:16` And Abraham listened to Ephron. And Abraham weighed to Ephron the silver which he had named in the audience of the sons of Heth, four *_hundred_* shekels of silver, current money with the merchant.
* `Gen 25:7` And these are the days of the years of Abraham's life which he lived: one *_hundred_* and seventy-five years.
* `Gen 25:17` And these are the years of the life of Ishmael: one *_hundred_* and thirty-seven years. And he expired and died and was gathered to his people.
* `Gen 26:12` Then Isaac sowed in that land and received in the same year one *_hundred_*-fold. And the LORD blessed him.
* `Gen 32:6` And the messengers returned to Jacob, saying, "We came to your brother Esau, and he is also coming to meet you, and four *_hundred_* men are with him."
* `Gen 32:14` Two *_hundred_* female goats, twenty male goats, two *_hundred_* ewes, twenty rams,
* `Gen 33:1` And Jacob lifted up his eyes and looked, and behold, Esau came, and with him four *_hundred_* men. And he divided the children between Leah, Rachel, and the two women-servants.
* `Gen 33:19` And he bought a part of a field where he had spread his tent at the hand of the children of Hamor, Shechem's father, for one *_hundred_* pieces of money.
* `Gen 35:28` And the days of Isaac were one *_hundred_* and eighty years.
* `Gen 45:22` To all of them he gave each man changes of clothing, but to Benjamin he gave three *_hundred_* pieces of silver and five changes of clothing.
* `Gen 47:9` And Jacob said to Pharaoh, "The days of the years of my pilgrimage are one *_hundred_* and thirty years. Few and evil have been the days of the years of my life, nor have they attained to the days of the years of the life of my fathers in the days of their pilgrimage."
* `Gen 47:28` And Jacob lived in the land of Egypt seventeen years. So the whole age of Jacob was one *_hundred_* and forty-seven years.
* `Gen 50:22` And Joseph dwelt in Egypt—he and his father's house. And Joseph lived one *_hundred_* and ten years.
* `Gen 50:26` So Joseph died, being one *_hundred_* and ten years old. And they embalmed him, and he was put in a coffin in Egypt.
* `Exo 6:16` And these are the names of the sons of Levi according to their generations: Gershon, Kohath, and Merari. And the years of the life of Levi were one *_hundred_* and thirty-seven years.
* `Exo 6:18` And the sons of Kohath: Amram, Izhar, Hebron, and Uzziel. And the years of the life of Kohath were one *_hundred_* and thirty-three years.
* `Exo 6:20` And Amram took for himself Jochebed, his father's sister, for a wife. And she bore him Aaron and Moses. And the years of the life of Amram were one *_hundred_* and thirty-seven years.
* `Exo 12:37` And the children of Israel journeyed from Rameses to Succoth, about six *_hundred_* thousand on foot who were men, besides children.
* `Exo 12:40` Now the sojourning of the children of Israel who dwelt in Egypt was four *_hundred_* and thirty years.
* `Exo 12:41` And it came to pass, at the end of the four *_hundred_* and thirty years, even the same day it came to pass, that all the hosts of the LORD departed from the land of Egypt.
* `Exo 14:7` And he took six *_hundred_* chosen chariots and all the chariots of Egypt and captains over every one of them.
* `Exo 27:9` "And you shall make the court of the tabernacle. For the south side southward there shall be hangings for the court of fine twined linen of one *_hundred_* cubits long for one side.
* `Exo 27:11` And likewise for the north side in length there shall be hangings of one *_hundred_* cubits long, and its twenty pillars and their twenty sockets of brass. The hooks of the pillars and their fillets shall be of silver.
* `Exo 27:18` The length of the court shall be one *_hundred_* cubits, the breadth fifty everywhere, and the height five cubits of fine twined linen, and their sockets of brass.
* `Exo 30:23` "Take also for yourself principal spices: of pure myrrh five *_hundred_* shekels, of sweet cinnamon half as much, even two *_hundred_* and fifty shekels, of sweet calamus two *_hundred_* and fifty shekels,
* `Exo 30:24` Of cassia five *_hundred_* shekels, after the shekel of the sanctuary, and of olive-oil a hin.
* `Exo 38:9` And he made the court. On the south side southward the hangings of the court were of fine twined linen, one *_hundred_* cubits.
* `Exo 38:11` And for the north side, the hangings were one *_hundred_* cubits, their pillars were twenty and their sockets of brass twenty. The hooks of the pillars and their fillets were made of silver.
* `Exo 38:24` All the gold that was occupied for the work in all the work of the holy place, even the gold of the offering, was twenty-nine talents and seven *_hundred_* and thirty shekels, after the shekel of the sanctuary.
* `Exo 38:25` And the silver of those who were numbered of the congregation was one *_hundred_* talents and one thousand seven *_hundred_* and seventy-five shekels, after the shekel of the sanctuary,
* `Exo 38:26` A bekah for every man (that is, half a shekel, after the shekel of the sanctuary), for everyone who went to be numbered, from twenty years old and upward, for six *_hundred_* and three thousand five *_hundred_* and fifty men.
* `Exo 38:27` And from the *_hundred_* talents of silver the sockets of the sanctuary and the sockets of the veil were cast—one *_hundred_* sockets from the *_hundred_* talents, a talent for a socket.
* `Exo 38:28` And from the one thousand seven *_hundred_* and seventy-five shekels he made hooks for the pillars, overlaid their capitals, and filleted them.
* `Exo 38:29` And the brass of the offering was seventy talents and two thousand and four *_hundred_* shekels.
* `Lev 26:8` And five of you shall chase one *_hundred_*, and one *_hundred_* of you shall put ten thousand to flight. And your enemies shall fall before you by the sword.
* `Num 1:21` Those who were numbered of them, even of the tribe of Reuben, were forty-six thousand and five *_hundred_*.
* `Num 1:23` Those who were numbered of them, even of the tribe of Simeon, were fifty-nine thousand and three *_hundred_*.
* `Num 1:25` Those who were numbered of them, even of the tribe of Gad, were forty-five thousand six *_hundred_* and fifty.
* `Num 1:27` Those who were numbered of them, even of the tribe of Judah, were seventy-four thousand and six *_hundred_*.
* `Num 1:29` Those who were numbered of them, even of the tribe of Issachar, were fifty-four thousand and four *_hundred_*.
* `Num 1:31` Those who were numbered of them, even of the tribe of Zebulun, were fifty-seven thousand and four *_hundred_*.
* `Num 1:33` Those who were numbered of them, even of the tribe of Ephraim, were forty thousand and five *_hundred_*.
* `Num 1:35` Those who were numbered of them, even of the tribe of Manasseh, were thirty-two thousand and two *_hundred_*.
* `Num 1:37` Those who were numbered of them, even of the tribe of Benjamin, were thirty-five thousand and four *_hundred_*.
* `Num 1:39` Those who were numbered of them, even of the tribe of Dan, were sixty-two thousand and seven *_hundred_*.
* `Num 1:41` Those who were numbered of them, even of the tribe of Asher, were forty-one thousand and five *_hundred_*.
* `Num 1:43` Those who were numbered of them, even of the tribe of Naphtali, were fifty-three thousand and four *_hundred_*.
* `Num 1:46` Even all those who were numbered were six *_hundred_* and three thousand five *_hundred_* and fifty.
* `Num 2:4` And his host and those who were numbered of them were seventy-four thousand and six *_hundred_*.
* `Num 2:6` And his host and those who were numbered of them were fifty-four thousand and four *_hundred_*.
* `Num 2:8` And his host and those who were numbered of them were fifty-seven thousand and four *_hundred_*.
* `Num 2:9` All who were numbered in the camp of Judah were one *_hundred_* and eighty-six thousand and four *_hundred_* throughout their armies. These shall first move forward.
* `Num 2:11` And his host and those who were numbered of them were forty-six thousand and five *_hundred_*.
* `Num 2:13` And his host and those who were numbered of them were fifty-nine thousand and three *_hundred_*.
* `Num 2:15` And his host and those who were numbered of them were forty-five thousand six *_hundred_* and fifty.
* `Num 2:16` All who were numbered in the camp of Reuben were one *_hundred_* and fifty-one thousand four *_hundred_* and fifty throughout their armies. And they shall move forward in the second rank.
* `Num 2:19` And his host and those who were numbered of them were forty thousand and five *_hundred_*.
* `Num 2:21` And his host and those who were numbered of them were thirty-two thousand and two *_hundred_*.
* `Num 2:23` And his host and those who were numbered of them were thirty-five thousand and four *_hundred_*.
* `Num 2:24` All who were numbered of the camp of Ephraim were one *_hundred_* and eight thousand and one *_hundred_* throughout their armies. And they shall go forward in the third rank.
* `Num 2:26` And his host and those who were numbered of them were sixty-two thousand and seven *_hundred_*.
* `Num 2:28` And his host and those who were numbered of them were forty-one thousand and five *_hundred_*.
* `Num 2:30` And his host and those who were numbered of them were fifty-three thousand and four *_hundred_*.
* `Num 2:31` All those who were numbered in the camp of Dan were one *_hundred_* and fifty-seven thousand and six *_hundred_*. They shall go hindmost with their standards."
* `Num 2:32` These are those who were numbered of the children of Israel by the house of their fathers. All those who were numbered of the camps throughout their hosts were six *_hundred_* and three thousand five *_hundred_* and fifty.
* `Num 3:22` Those who were numbered of them, according to the number of all the males, from a month old and upward, even those who were numbered of them were seven thousand and five *_hundred_*.
* `Num 3:28` According to the number of all the males from a month old and upward, there were eight thousand and six *_hundred_* keeping the charge of the sanctuary.
* `Num 3:34` And those who were numbered of them, according to the number of all the males from a month old and upward, were six thousand and two *_hundred_*.
* `Num 3:43` And all the first-born males according to the number of names from a month old and upward, of those who were numbered of them, were twenty-two thousand two *_hundred_* and seventy-three.
* `Num 3:46` And for those who are to be redeemed of the two *_hundred_* and seventy-three, of the first-born of the children of Israel, which are more than the Levites,
* `Num 3:50` From the first-born of the children of Israel he took the money: one thousand three *_hundred_* and sixty-five shekels after the shekel of the sanctuary.
* `Num 4:36` And those who were numbered of them by their families were two thousand seven *_hundred_* and fifty.
* `Num 4:40` Even those who were numbered of them throughout their families, by the house of their fathers, were two thousand six *_hundred_* and thirty.
* `Num 4:44` Even those who were numbered of them after their families, were three thousand and two *_hundred_*.
* `Num 4:48` Even those who were numbered of them, were eight thousand five *_hundred_* and eighty.
* `Num 7:13` And his offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them were full of fine flour mingled with oil for a food-offering;
* `Num 7:19` He offered for his offering one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:25` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:31` His offering was one silver charger, of the weight of one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:37` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:43` His offering was one silver charger, of the weight of one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:49` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:55` His offering was one silver charger of the weight of one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:61` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:67` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:73` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:79` His offering was one silver charger, the weight of which was one *_hundred_* and thirty shekels, and one silver bowl of seventy shekels, after the shekel of the sanctuary, both of them full of fine flour mingled with oil for a food-offering;
* `Num 7:85` Each charger of silver weighing one *_hundred_* and thirty shekels, each bowl seventy; all the silver vessels weighed two thousand and four *_hundred_* shekels, after the shekel of the sanctuary;
* `Num 7:86` Twelve golden spoons full of incense weighing ten shekels apiece, after the shekel of the sanctuary; all the gold of the spoons was one *_hundred_* and twenty shekels;
* `Num 11:21` And Moses said, "The people among whom I am, are six *_hundred_* thousand footmen, and you have said, 'I will give them flesh so that they may eat a whole month.'
* `Num 16:2` And they rose up before Moses, with some of the children of Israel, two *_hundred_* and fifty princes of the assembly, famous in the congregation, men of renown,
* `Num 16:17` And each take his censer and put incense in them, and each bring before the LORD his censer, two *_hundred_* and fifty censers—you and also Aaron, each his censer."
* `Num 16:35` And a fire came out from the LORD and consumed the two *_hundred_* and fifty men who offered incense.
* `Num 16:49` Now those who died in the plague were fourteen thousand and seven *_hundred_*, besides those who died on account of the matter with Korah.
* `Num 26:7` These are the families of the Reubenites. And those who were numbered of them were forty-three thousand seven *_hundred_* and thirty.
* `Num 26:10` And the earth opened her mouth and swallowed them up together with Korah, when that company died when the fire devoured two *_hundred_* and fifty men, and they became a sign.
* `Num 26:14` These are the families of the Simeonites, twenty-two thousand and two *_hundred_*.
* `Num 26:18` These are the families of the children of Gad according to those who were numbered of them, forty thousand and five *_hundred_*.
* `Num 26:22` These are the families of Judah according to those who were numbered of them, seventy-six thousand and five *_hundred_*.
* `Num 26:25` These are the families of Issachar according to those who were numbered of them, sixty-four thousand and three *_hundred_*.
* `Num 26:27` These are the families of the Zebulunites according to those who were numbered of them, sixty thousand and five *_hundred_*.
* `Num 26:34` These are the families of Manasseh and those who were numbered of them, fifty-two thousand and seven *_hundred_*.
* `Num 26:37` These are the families of the sons of Ephraim according to those who were numbered of them, thirty-two thousand and five *_hundred_*. These are the sons of Joseph after their families.
* `Num 26:41` These are the sons of Benjamin after their families. And those who were numbered of them were forty-five thousand and six *_hundred_*.
* `Num 26:43` All the families of the Shuhamites according to those who were numbered of them were sixty-four thousand and four *_hundred_*.
* `Num 26:47` These are the families of the sons of Asher according to those who were numbered of them, who were fifty-three thousand and four *_hundred_*.
* `Num 26:50` These are the families of Naphtali according to their families. And those who were numbered of them were forty-five thousand and four *_hundred_*.
* `Num 26:51` These were the numbered of the children of Israel, six *_hundred_* and one thousand seven *_hundred_* and thirty.
* `Num 31:28` And levy a tribute to the LORD of the men of war who went out to battle, one soul of five *_hundred_*, both of the persons, of the bulls, of the donkeys, and of the sheep.
* `Num 31:32` And the captives, being the rest of the plunder which the men of war had taken, was six *_hundred_* and seventy-five thousand sheep,
* `Num 31:36` And this was the half which was the portion of those who went out to war: in number, three *_hundred_* and thirty-seven thousand and five *_hundred_* sheep,
* `Num 31:37` And the LORD'S tribute of the sheep was six *_hundred_* and seventy-five;
* `Num 31:39` And the donkeys were thirty thousand and five *_hundred_*, of which the LORD'S tribute was sixty-one;
* `Num 31:43` (Now the half that pertained to the congregation was three *_hundred_* and thirty-seven thousand and five *_hundred_* sheep,
* `Num 31:45` Thirty thousand and five *_hundred_* donkeys,
* `Num 31:52` And all the gold of the offering that they offered to the LORD, from the captains of thousands and from the captains of hundreds, was sixteen thousand seven *_hundred_* and fifty shekels.
* `Num 33:39` And Aaron was one *_hundred_* and twenty-three years old when he died on mount Hor.
* `Deu 22:19` And they shall amerce him one *_hundred_* shekels of silver, and give them to the father of the young woman, because he has brought an evil name upon a virgin of Israel. And she shall be his wife. He may not put her away all his days.
* `Deu 31:2` And he said to them, "I am one *_hundred_* and twenty years old this day. I can no longer go out and come in. Also the LORD has said to me, 'You shall not go over this Jordan.'
* `Deu 34:7` And Moses was one *_hundred_* and twenty years old when he died. His eye was not dim, nor his natural force abated.
* `Jsh 7:21` When I saw among the plunder a fine Babylonish garment, two *_hundred_* shekels of silver, and a wedge of gold of fifty shekels weight, I coveted them and took them, and behold, they are hid in the earth in the midst of my tent, and the silver under it."
* `Jsh 24:29` And it came to pass after these things, that Joshua the son of Nun the servant of the LORD died, being one *_hundred_* and ten years old.
* `Jsh 24:32` And the bones of Joseph which the children of Israel brought out of Egypt, they buried in Shechem in a parcel of ground which Jacob bought of the sons of Hamor the father of Shechem for one *_hundred_* pieces of silver. And it became the inheritance of the children of Joseph.
* `Jdg 2:8` And Joshua the son of Nun, the servant of the LORD, died, being one *_hundred_* and ten years old.
* `Jdg 3:31` And after him was Shamgar the son of Anath, who slew of the Philistines six *_hundred_* men with an ox-goad, and he also delivered Israel.
* `Jdg 4:3` And the children of Israel cried to the LORD, for he had nine *_hundred_* chariots of iron. And for twenty years he mightily oppressed the children of Israel.
* `Jdg 4:13` And Sisera collected all his chariots, even nine *_hundred_* chariots of iron, and all the people who were with him, from Harosheth of the Gentiles to the river of Kishon.
* `Jdg 7:6` And the number of those who lapped, putting their hand to their mouth, were three *_hundred_* men, but all the rest of the people bowed down upon their knees to drink water.
* `Jdg 7:7` And the LORD said to Gideon, "By the three *_hundred_* men who lapped I will save you and deliver the Midianites into your hand, and let all the other people each go to his place."
* `Jdg 7:8` So the people took provisions in their hand and their trumpets. And he sent all the rest of Israel each to his tent and retained those three *_hundred_* men. And the host of Midian was beneath him in the valley.
* `Jdg 7:16` And he divided the three *_hundred_* men into three companies and put a trumpet in every man's hand, along with empty pitchers and lamps within the pitchers.
* `Jdg 7:19` So Gideon and the *_hundred_* men who were with him came to the outside of the camp in the beginning of the middle watch, and they had just set the watch. And they blew the trumpets and broke the pitchers that were in their hands.
* `Jdg 7:22` And the three *_hundred_* blew the trumpets, and the LORD set every man's sword against his fellow, even throughout all the host. And the host fled to Beth-shittah in Zereroth and to the border of Abel-meholah near Tabbath.
* `Jdg 8:4` And Gideon came to the Jordan and passed over—he and the three *_hundred_* men who were with him—faint, yet pursuing them.
* `Jdg 8:10` Now Zebah and Zalmunna were in Karkor, and their hosts with them, about fifteen thousand men, all who were left of all the hosts of the children of the east, for there fell one *_hundred_* and twenty thousand men who drew sword.
* `Jdg 8:26` And the weight of the golden earrings that he requested was one thousand and seven *_hundred_* shekels of gold, besides ornaments, collars, and purple clothing that was on the kings of Midian, and besides the chains that were around their camels' necks.
* `Jdg 11:26` While Israel dwelt in Heshbon and her towns, in Aroer and her towns, and in all the cities that are along by the borders of Arnon for three *_hundred_* years, why therefore did you not recover them within that time?
* `Jdg 15:4` And Samson went and caught three *_hundred_* foxes, and took fire-brands, turned tail to tail, and put a fire-brand in the midst between two tails.
* `Jdg 16:5` And the lords of the Philistines came to her, and said to her, "Entice him, and see in what his great strength lies and by what means we may prevail against him so that we may bind him to afflict him. And we will each give you eleven *_hundred_* pieces of silver."
* `Jdg 17:2` And he said to his mother, "The eleven *_hundred_* shekels of silver that were taken from you, about which you cursed and also spoke about in my ears, behold, the silver is with me. I took it." And his mother said, "Blessed are you of the LORD, my son."
* `Jdg 17:3` And when he had restored the eleven *_hundred_* shekels of silver to his mother, his mother said, "I had wholly dedicated the silver to the LORD from my hand for my son to make an engraved image and a molten image. Now therefore, I will restore it to you."
* `Jdg 17:4` So he restored the money to his mother, and his mother took two *_hundred_* shekels of silver and gave them to the founder, who made from it an engraved image and a molten image. And they were in the house of Micah.
* `Jdg 18:11` And there went from there of the family of the Danites, out of Zorah and out of Eshtaol, six *_hundred_* men appointed with weapons of war.
* `Jdg 18:16` And the six *_hundred_* men appointed with their weapons of war, who were of the children of Dan, stood by the entrance of the gate.
* `Jdg 18:17` And the five men who went to explore the land went up, came in there, and took the engraved image, the ephod, the teraphim, and the molten image. And the priest stood in the entrance of the gate with the six *_hundred_* men who were appointed with weapons of war.
* `Jdg 20:2` And the chief of all the people, even of all the tribes of Israel, presented themselves in the assembly of the people of God—four *_hundred_* thousand footmen who drew sword.
* `Jdg 20:10` And we will take ten men for one *_hundred_* throughout all the tribes of Israel, and one *_hundred_* for one thousand, and one thousand for ten thousand, to fetch provisions for the people, so that when they come to Gibeah of Benjamin, they may do according to all the folly that they have wrought in Israel."
* `Jdg 20:15` And the children of Benjamin were numbered at that time out of the cities twenty-six thousand men who drew sword, besides the inhabitants of Gibeah, who were numbered seven *_hundred_* chosen men.
* `Jdg 20:16` Among all this people there were seven *_hundred_* chosen men who were left-handed. Each could sling stones to a hair-breadth and not miss.
* `Jdg 20:17` And the men of Israel, besides Benjamin, were numbered four *_hundred_* thousand men who drew sword. All these were men of war.
* `Jdg 20:35` And the LORD smote Benjamin before Israel. And the children of Israel destroyed twenty-five thousand and one *_hundred_* men of the Benjaminites that day. All these drew the sword.
* `Jdg 20:47` But six *_hundred_* men turned and fled to the wilderness to the rock Rimmon and stayed at the rock Rimmon four months.
* `Jdg 21:12` And they found among the inhabitants of Jabesh-gilead four *_hundred_* young virgins who had known no man by lying with any male, and they brought them to the camp to Shiloh, which is in the land of Canaan.
* `1Sa 11:8` And when he numbered them in Bezek, the children of Israel were three *_hundred_* thousand and the men of Judah thirty thousand.
* `1Sa 13:15` And Samuel arose and went up from Gilgal to Gibeah of Benjamin. And Saul numbered the people who were present with him, about six *_hundred_* men.
* `1Sa 14:2` And Saul stayed in the uttermost part of Gibeah under a pomegranate tree which is in Migron. And the people who were with him were about six *_hundred_* men,
* `1Sa 15:4` And Saul assembled the people and numbered them in Telaim, two *_hundred_* thousand footmen and ten thousand men of Judah.
* `1Sa 17:7` And the staff of his spear was like a weaver's beam and his spear's head weighed six *_hundred_* shekels of iron. And someone bearing a shield went before him.
* `1Sa 18:25` And Saul said, "Thus you shall say to David: 'The king does not desire any dowry, but one *_hundred_* foreskins of the Philistines to be avenged of the king's enemies.'" But Saul thought to make David fall by the hand of the Philistines.
* `1Sa 18:27` Therefore, David arose and went—he and his men—and slew two *_hundred_* men of the Philistines. And David brought their foreskins, and they gave them in full number to the king so that he might be the king's son-in-law. And Saul gave him Michal his daughter for a wife.
* `1Sa 22:2` And everyone who was in distress, everyone who was in debt, and everyone who was discontented resorted to him, and he became a captain over them. And there were with him about four *_hundred_* men.
* `1Sa 23:13` Then David and his men who were about six *_hundred_* arose and departed from Keilah and went wherever they could go. And it was told to Saul that David had escaped from Keilah, and he forbore to go forth.
* `1Sa 25:13` And David said to his men, "Each of you gird on his sword." And they each girded on his sword. And David also girded on his sword. And about four *_hundred_* men went up after David, and two *_hundred_* stayed by the goods.
* `1Sa 25:18` Then Abigail made haste and took two *_hundred_* loaves, two bottles of wine, five sheep ready and dressed, five measures of parched grain, one *_hundred_* clusters of raisins, and two *_hundred_* cakes of figs, and laid them on donkeys.
* `1Sa 27:2` And David arose and he passed over with the six *_hundred_* men who were with him to Achish, the son of Maoch, king of Gath.
* `1Sa 30:9` So David went—he and the six *_hundred_* men who were with him—and came to the brook Besor, where those who were left behind remained.
* `1Sa 30:10` But David pursued—he and four *_hundred_* men—while two *_hundred_* stayed behind, who were so faint that they could not go over the brook of Besor.
* `1Sa 30:17` And David smote them from the twilight even to the evening of the next day. And there did not escape a man of them, except four *_hundred_* young men, who rode upon camels and fled.
* `1Sa 30:21` And David came to the two *_hundred_* men who were so faint that they could not follow David, whom they had made also to abide at the brook of Besor. And they went forth to meet David and to meet the people who were with him. And when David came near to the people, he saluted them.
* `2Sa 2:31` But the servants of David had smitten three *_hundred_* and sixty men of Benjamin and of Abner's men so that they died.
* `2Sa 3:14` And David sent messengers to Ish-bosheth, Saul's son, saying, "Deliver to me my wife Michal, whom I espoused to myself for one *_hundred_* foreskins of the Philistines."
* `2Sa 8:4` And David took from him one thousand chariots, seven *_hundred_* horsemen, and twenty thousand footmen. And David hamstrung all the chariot-horses, but reserved some of them for one *_hundred_* chariots.
* `2Sa 10:18` And the Syrians fled before Israel. And David slew the men of seven *_hundred_* chariots of the Syrians and forty thousand horsemen, and he smote Shobach the captain of their host, who died there.
* `2Sa 14:26` And when he polled his head (for it was at every year's end that he polled it; because the hair was heavy on him, therefore he polled it), he weighed the hair of his head at two *_hundred_* shekels after the king's weight.
* `2Sa 15:11` And with Absalom went two *_hundred_* men from Jerusalem who were invited, and they went in their simplicity and did not know anything.
* `2Sa 15:18` And all his servants passed on by his side, and all the Cherethites, all the Pelethites, and all the Gittites, six *_hundred_* men who came with him from Gath, passed on before the king.
* `2Sa 16:1` And when David was a little past the top of the hill, behold, Ziba the servant of Mephibosheth met him, with a couple of donkeys saddled and upon them two *_hundred_* loaves of bread, one *_hundred_* bunches of raisins, one *_hundred_* of summer fruits, and a bottle of wine.
* `2Sa 21:16` And Ishbi-benob, who was among the sons of the giant, the weight of whose spear was three *_hundred_* shekels of brass in weight, he being girded with a new sword, thought to have slain David.
* `2Sa 23:8` These are the names of the mighty men whom David had: The Tachmonite who sat in the seat, chief among the captains (the same was Adino the Eznite), he lifted up his spear against eight *_hundred_*, whom he slew at one time.
* `2Sa 23:18` And Abishai, the brother of Joab, the son of Zeruiah, was chief among three. And he lifted up his spear against three *_hundred_*, slew them, and had the name among three.
* `2Sa 24:3` And Joab said to the king, "Now may the LORD your God add to the people, however many they may be, one *_hundred_*-fold, and that the eyes of my lord the king may see it. But why does my lord the king delight in this thing?"
* `2Sa 24:9` And Joab presented the sum of the number of the people to the king. And there were in Israel eight *_hundred_* thousand valiant men who drew the sword, and the men of Judah were five *_hundred_* thousand men.
* `1Ki 4:23` Ten fat oxen, twenty oxen out of the pastures, one *_hundred_* sheep, besides deer, gazelles, and fallow-deer, and fattened birds.
* `1Ki 5:16` Besides Solomon's three thousand and three *_hundred_* chief officers who were over the work and ruled over the people who wrought in the work.
* `1Ki 6:1` And it came to pass in the four *_hundred_* and eightieth year after the children of Israel had come out of the land of Egypt, in the fourth year of Solomon's reign over Israel, in the month of Zif, which is the second month, that he began to build the house of the LORD.
* `1Ki 7:2` He also built the House of the Forest of Lebanon. Its length was one *_hundred_* cubits, its breadth fifty cubits, and its height thirty cubits, upon four rows of cedar pillars, with cedar beams upon the pillars.
* `1Ki 7:20` And the capitals upon the two pillars also had pomegranates above, over against the belly which was by the net-work. And the pomegranates were two *_hundred_* in rows around upon the other capital.
* `1Ki 7:42` And four *_hundred_* pomegranates for the two net-works, even two rows of pomegranates for one net-work, to cover the two bowls of the capitals that were upon the pillars;
* `1Ki 8:63` And Solomon offered a sacrifice of peace-offerings which he offered to the LORD: twenty-two thousand oxen and one *_hundred_* and twenty thousand sheep. So the king and all the children of Israel dedicated the house of the LORD.
* `1Ki 9:14` And Hiram sent to the king one *_hundred_* and twenty talents of gold.
* `1Ki 9:23` These were the chief of the officers who were over Solomon's work: five *_hundred_* and fifty who bore rule over the people who wrought in the work.
* `1Ki 9:28` And they came to Ophir and imported four *_hundred_* and twenty talents of gold from there and brought it to king Solomon.
* `1Ki 10:10` And she gave the king one *_hundred_* and twenty talents of gold, a very great quantity of spices, and precious stones. Never again did there come such abundance of spices as these which the queen of Sheba gave to king Solomon.
* `1Ki 10:14` Now the weight of gold that came to Solomon in one year was six *_hundred_* and sixty-six talents of gold,
* `1Ki 10:16` And king Solomon made two *_hundred_* bucklers of beaten gold. Six *_hundred_* shekels of gold went to one buckler.
* `1Ki 10:17` And he made three *_hundred_* shields of beaten gold. Three minas of gold went to one shield. And the king put them in the House of the Forest of Lebanon.
* `1Ki 10:26` And Solomon collected chariots and horsemen. And he had one thousand and four *_hundred_* chariots and twelve thousand horsemen, whom he bestowed in the cities for chariots and with the king at Jerusalem.
* `1Ki 10:29` And a chariot came up and went out of Egypt for six *_hundred_* shekels of silver, and a horse for one *_hundred_* and fifty. And in this manner they exported them to all the kings of the Hittites and to the kings of Syria.
* `1Ki 11:3` And he had seven *_hundred_* wives, princesses, and three *_hundred_* concubines. And his wives turned away his heart.
* `1Ki 12:21` And when Rehoboam had come to Jerusalem, he assembled all the house of Judah with the tribe of Benjamin, one *_hundred_* and eighty thousand chosen men who were warriors, to fight against the house of Israel to bring the kingdom back to Rehoboam the son of Solomon.
* `1Ki 18:4` For it was so, when Jezebel cut off the prophets of the LORD, that Obadiah took one *_hundred_* prophets and hid them by fifties in a cave and fed them with bread and water.)
* `1Ki 18:13` Was it not told to my lord what I did when Jezebel slew the prophets of the LORD, how I hid one *_hundred_* men of the LORD'S prophets by fifties in a cave and fed them with bread and water?
* `1Ki 18:19` Now therefore, send and gather to me all Israel at mount Carmel, along with the four *_hundred_* and fifty prophets of Baal and the four *_hundred_* prophets of the groves who eat at Jezebel's table."
* `1Ki 18:22` Then Elijah said to the people, "I, even I only, remain a prophet of the LORD, but Baal's prophet's are four *_hundred_* and fifty men.
* `1Ki 20:15` Then he numbered the young men of the princes of the provinces, and they were two *_hundred_* and thirty two. And after them he numbered all the people, even all the children of Israel, being seven thousand.
* `1Ki 20:29` And they encamped one over against the other seven days. And so it was, that in the seventh day the battle was joined. And the children of Israel slew one *_hundred_* thousand footmen of the Syrians in one day.
* `1Ki 22:6` Then the king of Israel assembled the prophets, about four *_hundred_* men, and said to them, "Shall I go against Ramoth-gilead to battle, or shall I forbear?" And they said, "Go up, for the Lord will deliver it into the hand of the king."
* `2Ki 3:4` And Mesha king of Moab was a sheep-master, and he rendered to the king of Israel one *_hundred_* thousand lambs and one *_hundred_* thousand rams, with the wool.
* `2Ki 3:26` And when the king of Moab saw that the battle was too severe for him, he took with him seven *_hundred_* men who drew swords to break through to the king of Edom, but they could not.
* `2Ki 4:43` And his servant said, "What, should I set this before one *_hundred_* men?" He said again, "Give it to the people so that they may eat, for thus says the LORD: 'They shall eat and shall have some left over.'"
* `2Ki 14:13` And Jehoash king of Israel took Amaziah king of Judah, the son of Jehoash the son of Ahaziah, at Beth-shemesh, and came to Jerusalem and broke down the wall of Jerusalem from the gate of Ephraim to the corner gate, four *_hundred_* cubits.
* `2Ki 18:14` And Hezekiah king of Judah sent to the king of Assyria at Lachish, saying, "I have offended. Withdraw from me. That which you put on me I will bear." And the king of Assyria appointed to Hezekiah king of Judah three *_hundred_* talents of silver and thirty talents of gold.
* `2Ki 19:35` And it came to pass that night, that the angel of the LORD went out and smote in the camp of the Assyrians one *_hundred_* and eighty-five thousand. And when they arose early in the morning, behold, they were all dead corpses.
* `2Ki 23:33` And Pharaoh-nechoh put him in bonds at Riblah in the land of Hamath so that he might not reign in Jerusalem, and subjected the land to a tribute of one *_hundred_* talents of silver and a talent of gold.
* `1Ch 4:42` And some of them from the sons of Simeon, five *_hundred_* men, went to mount Seir, having for their captains Pelatiah, Neariah, Rephaiah, and Uzziel, the sons of Ishi.
* `1Ch 5:18` The sons of Reuben, the Gadites, and half the tribe of Manasseh, all who were valiant men—men able to bear buckler and sword, to shoot with bow, and skillful in war—forty-four thousand seven *_hundred_* and sixty who were able to go forth to war.
* `1Ch 5:21` And they took away their livestock: fifty thousand of their camels, two *_hundred_* and fifty thousand sheep, and two thousand donkeys; and also one *_hundred_* thousand men.
* `1Ch 7:2` And the sons of Tola: Uzzi, Rephaiah, Jeriel, Jahmai, Jibsam, and Shemuel, heads of their father's house, namely, of Tola. They were valiant men of might in their generations whose number was in the days of David twenty-two thousand and six *_hundred_*.
* `1Ch 7:9` And their number, after their genealogy by their generations, heads of the house of their fathers, mighty men of valor, was twenty thousand and two *_hundred_*.
* `1Ch 7:11` All these the sons of Jediael by the heads of their fathers, mighty men of valor, were seventeen thousand and two *_hundred_* soldiers fit to go out for war and battle.
* `1Ch 8:40` And the sons of Ulam were mighty men of valor, archers, and had many sons and sons' sons numbering one *_hundred_* and fifty. All these are among the sons of Benjamin.
* `1Ch 9:6` And of the sons of Zerah: Jeuel and their brothers, six *_hundred_* and ninety.
* `1Ch 9:9` And their brothers, according to their generations, nine *_hundred_* and fifty-six. All these men were chief of the fathers in the house of their fathers.
* `1Ch 9:13` And their brothers, heads of the house of their fathers, one thousand seven *_hundred_* and sixty, very able men for the work of the service of the house of God.
* `1Ch 9:22` All these who were chosen to be gatekeepers in the gates were two *_hundred_* and twelve. These were reckoned by their genealogy in their villages, whom David and Samuel the seer ordained in their set office.
* `1Ch 11:11` And this is the number of the mighty men whom David had: Jashobeam a Hachmonite, the chief of the captains. He lifted his spear against three *_hundred_* slain by him at one time.
* `1Ch 11:20` And Abishai the brother of Joab, he was chief of the three. For lifting his spear against three *_hundred_*, he slew them, and had a name among the three.
* `1Ch 12:14` These were of the sons of Gad, captains of the host. One of the least was over one *_hundred_*, and the greatest over one thousand.
* `1Ch 12:24` The children of Judah who bore shield and spear were six thousand and eight *_hundred_*, ready armed for war.
* `1Ch 12:25` Of the children of Simeon, mighty men of valor for war, seven thousand and one *_hundred_*.
* `1Ch 12:26` Of the children of Levi four thousand and six *_hundred_*.
* `1Ch 12:27` And Jehoiada was the leader of the Aaronites, and with him were three thousand and seven *_hundred_*.
* `1Ch 12:30` And of the children of Ephraim twenty thousand and eight *_hundred_*, mighty men of valor, famous throughout the house of their fathers.
* `1Ch 12:32` And of the children of Issachar, who were men who had understanding of the times to know what Israel ought to do, their heads were two *_hundred_*, and all their brothers were at their command.
* `1Ch 12:35` And of the Danites there were twenty-eight thousand and six *_hundred_* expert in war.
* `1Ch 12:37` And on the other side of the Jordan, of the Reubenites, the Gadites, and of the half tribe of Manasseh, with all manner of instruments of war for the battle, were one *_hundred_* and twenty thousand.
* `1Ch 15:5` Of the sons of Kohath: Uriel the chief and his brothers one *_hundred_* and twenty.
* `1Ch 15:6` Of the sons of Merari: Asaiah the chief and his brothers two *_hundred_* and twenty.
* `1Ch 15:7` Of the sons of Gershom: Joel the chief and his brothers one *_hundred_* and thirty.
* `1Ch 15:8` Of the sons of Elizaphan: Shemaiah the chief and his brothers two *_hundred_*.
* `1Ch 15:10` Of the sons of Uzziel: Amminadab the chief and his brothers one *_hundred_* and twelve.
* `1Ch 18:4` And David took from him one thousand chariots, seven thousand horsemen, and twenty thousand footmen. David also hamstrung all the chariot-horses, but reserved of them one *_hundred_* chariots.
* `1Ch 21:3` And Joab answered, "May the LORD make his people one *_hundred_* times more numerous than they are. But, my lord the king, are they not all my lord's servants? Why then does my lord require this thing? Why will he be a cause of trespass to Israel?"
* `1Ch 21:5` And Joab gave the sum of the number of the people to David. And all the people of Israel numbered one million and one *_hundred_* thousand men who drew sword. And Judah was four *_hundred_* and seventy thousand men who drew sword.
* `1Ch 21:25` So David gave to Ornan for the place six *_hundred_* shekels of gold by weight.
* `1Ch 22:14` Now behold, in my trouble I have prepared for the house of the LORD one *_hundred_* thousand talents of gold and one million talents of silver, and of brass and iron without weight, for it is in abundance. I have also prepared timber and stone, and you may add to them.
* `1Ch 25:7` So their number, with their brothers who were instructed in the songs of the LORD, even all who were skillful, was two *_hundred_* and eighty-eight.
* `1Ch 26:30` And of the Hebronites, Hashabiah and his brothers, men of valor, one thousand and seven *_hundred_*, had the oversight of Israel beyond the Jordan westward in all the business of the LORD and in the service of the king.
* `1Ch 26:32` And his brothers, men of valor, were two thousand and seven *_hundred_* chief fathers, whom king David made rulers over the Reubenites, the Gadites, and the half-tribe of Manasseh, for every matter pertaining to God and affairs of the king.
* `1Ch 29:7` And gave for the service of the house of God five thousand talents and ten thousand drams of gold, ten thousand talents of silver, eighteen thousand talents of brass, and one *_hundred_* thousand talents of iron.
* `2Ch 1:14` And Solomon gathered chariots and horsemen. And he had one thousand and four *_hundred_* chariots and twelve thousand horsemen, which he placed in the chariot cities and with the king at Jerusalem.
* `2Ch 1:17` And they fetched up and brought out of Egypt a chariot for six *_hundred_* shekels of silver and a horse for one *_hundred_* and fifty. And so they brought out horses for all the kings of the Hittites and for the kings of Syria by their means.
* `2Ch 2:2` And Solomon numbered out seventy thousand men to bear burdens, eighty thousand to hew in the mountain, and three thousand and six *_hundred_* to oversee them.
* `2Ch 2:17` And Solomon numbered all the strangers who were in the land of Israel, after the numbering with which David his father had numbered them. And they were found one *_hundred_* and fifty-three thousand and six *_hundred_*.
* `2Ch 2:18` And he set seventy thousand of them to be bearers of burdens, eighty thousand to be hewers in the mountain, and three thousand and six *_hundred_* overseers to set the people to work.
* `2Ch 3:4` And the porch that was in the front of the house, its length was according to the breadth of the house, twenty cubits, and the height was one *_hundred_* and twenty. And he overlaid it inside with pure gold.
* `2Ch 3:8` And he made the most holy house, the length of which was according to the breadth of the house, twenty cubits, and its breadth twenty cubits. And he overlaid it with fine gold amounting to six *_hundred_* talents.
* `2Ch 3:16` And he made chains, as in the oracle, and put them on the heads of the pillars. And he made one *_hundred_* pomegranates and put them on the chains.
* `2Ch 4:8` He also made ten tables and placed them in the temple: five on the right side and five on the left. And he made one *_hundred_* basins of gold.
* `2Ch 4:13` And four *_hundred_* pomegranates on the two wreaths, two rows of pomegranates on each wreath to cover the two bowls of the capitals which were upon the pillars.
* `2Ch 5:12` And also the Levites who were the singers, all of them of Asaph, of Heman, of Jeduthun, with their sons and their brothers, being arrayed in white linen, having cymbals and psalteries and harps, stood at the east end of the altar, and with them one *_hundred_* and twenty priests sounding with trumpets),
* `2Ch 7:5` And king Solomon offered a sacrifice of twenty-two thousand oxen and one *_hundred_* and twenty thousand sheep. Thus the king and all the people dedicated the house of God.
* `2Ch 8:10` And these were the chief of king Solomon's officers, even two *_hundred_* and fifty, who bore rule over the people.
* `2Ch 8:18` And Huram sent to him by the hands of his servants ships and servants who had knowledge of the sea, and they went with the servants of Solomon to Ophir and took from there four *_hundred_* and fifty talents of gold and brought them to king Solomon.
* `2Ch 9:9` And she gave the king one *_hundred_* and twenty talents of gold, spices of great abundance, and precious stones. Never was there any such spice as the queen of Sheba gave to king Solomon.
* `2Ch 9:13` Now the weight of gold that came to Solomon in one year was six *_hundred_* and sixty-six talents of gold,
* `2Ch 9:15` And king Solomon made two *_hundred_* bucklers of beaten gold. Six *_hundred_* shekels of beaten gold went to each buckler.
* `2Ch 9:16` And three *_hundred_* shields he made of beaten gold. Three *_hundred_* shekels of gold went to each shield. And the king put them in the house of the forest of Lebanon.
* `2Ch 11:1` And when Rehoboam had come to Jerusalem, he gathered from the house of Judah and Benjamin one *_hundred_* and eighty thousand chosen men who were warriors to fight against Israel so that he might bring the kingdom back to Rehoboam.
* `2Ch 12:3` With twelve *_hundred_* chariots and sixty thousand horsemen. And the people were without number who came with him out of Egypt: the Lubims, the Sukkiims, and the Cushites.
* `2Ch 13:3` And Abijah set the battle in array with an army of valiant men of war, even four *_hundred_* thousand chosen men. Jeroboam also set the battle in array against him with eight *_hundred_* thousand chosen men, being mighty men of valor.
* `2Ch 13:17` And Abijah and his people slew them with a great slaughter. So there fell slain of Israel five *_hundred_* thousand chosen men.
* `2Ch 14:8` And Asa had an army of three *_hundred_* thousand men out of Judah who bore bucklers and spears, and two *_hundred_* and eighty thousand out of Benjamin who bore shields and drew bows. All these were mighty men of valor.
* `2Ch 14:9` And Zerah the Cushite came out against them with a host of one million, and also three *_hundred_* chariots, and came to Mareshah.
* `2Ch 15:11` And they offered to the LORD at the same time from the plunder which they had brought seven *_hundred_* oxen and seven thousand sheep.
* `2Ch 17:11` Also, some of the Philistines brought Jehoshaphat presents and tribute silver. And the Arabians brought him flocks: seven thousand and seven *_hundred_* rams and seven thousand and seven *_hundred_* male goats.
* `2Ch 17:14` And these are their numbers according to the house of their fathers. Of Judah, the captains of thousands: Adnah the chief, and with him three *_hundred_* thousand mighty men of valor;
* `2Ch 17:15` And next to him was Jehohanan the captain, and with him two *_hundred_* and eighty thousand;
* `2Ch 17:16` And next to him was Amasiah the son of Zichri, who willingly offered himself to the LORD, and with him two *_hundred_* thousand mighty men of valor.
* `2Ch 17:17` And of Benjamin: Eliada a mighty man of valor, and with him two *_hundred_* thousand armed men with bow and shield;
* `2Ch 17:18` And next to him was Jehozabad, and with him one *_hundred_* and eighty thousand ready prepared for the war.
* `2Ch 18:5` Therefore, the king of Israel gathered the prophets, four *_hundred_* men, and said to them, "Shall we go to Ramoth-gilead to battle, or shall I forbear?" And they said, "Go up, for God will deliver it into the king's hand."
* `2Ch 24:15` But Jehoiada grew old and was full of days when he died. He was one *_hundred_* and thirty years old when he died.
* `2Ch 25:5` Moreover, Amaziah assembled Judah and made them captains over thousands and captains over hundreds, according to the houses of their fathers, throughout all Judah and Benjamin. And he numbered them from twenty years old and above and found them to be three *_hundred_* thousand choice men, able to go forth to war, who could handle spear and shield.
* `2Ch 25:6` He also hired one *_hundred_* thousand mighty men of valor out of Israel for one *_hundred_* talents of silver.
* `2Ch 25:9` And Amaziah said to the man of God, "But what shall we do for the *_hundred_* talents which I have given to the army of Israel?" And the man of God answered, "The LORD is able to give you much more than this."
* `2Ch 25:23` And Joash the king of Israel took Amaziah king of Judah, the son of Joash, the son of Jehoahaz, at Beth-shemesh, and brought him to Jerusalem and broke down the wall of Jerusalem from the gate of Ephraim to the corner gate, four *_hundred_* cubits.
* `2Ch 26:12` The whole number of the chief of the fathers of the mighty men of valor was two thousand and six *_hundred_*.
* `2Ch 26:13` And under their hand was an army, three *_hundred_* and seven thousand and five *_hundred_*, that made war with mighty power, to help the king against the enemy.
* `2Ch 27:5` He also fought with the king of the Ammonites and prevailed against them. And the children of Ammon gave him the same year one *_hundred_* talents of silver, ten thousand measures of wheat, and ten thousand of barley. So the children of Ammon payed much to him, both the second year and the third.
* `2Ch 28:6` For Pekah the son of Remaliah slew in Judah one *_hundred_* and twenty thousand in one day, who were all valiant men, because they had forsaken the LORD God of their fathers.
* `2Ch 28:8` And the children of Israel carried away captive from their brothers two *_hundred_* thousand women, sons, and daughters. They also took away a large amount of plunder from them and brought the plunder to Samaria.
* `2Ch 29:32` And the number of the burnt-offerings, which the congregation brought, was seventy bulls, one *_hundred_* rams, and two *_hundred_* lambs. All these were for a burnt-offering to the LORD.
* `2Ch 29:33` And the consecrated things were six *_hundred_* oxen and three thousand sheep.
* `2Ch 35:8` And his princes gave willingly to the people, to the priests, and to the Levites. Hilkiah, Zechariah, and Jehiel, rulers of the house of God, gave to the priests for the passover-offerings two thousand and six *_hundred_* small livestock, and three *_hundred_* oxen.
* `2Ch 35:9` And also Conaniah, Shemaiah, Nethaneel, his brothers, and Hashabiah, Jehiel, and Jozabad, chief of the Levites, gave to the Levites for passover-offerings five thousand small livestock, and five *_hundred_* oxen.
* `2Ch 36:3` And the king of Egypt deposed him at Jerusalem and imposed upon the land a fine of one *_hundred_* talents of silver and a talent of gold.
* `Ezr 1:10` Thirty basins of gold, four *_hundred_* and ten silver basins of a second sort, and one thousand other vessels.
* `Ezr 1:11` All the vessels of gold and of silver were five thousand and four *_hundred_*. All these Sheshbazzar brought with those of the captivity who were brought from Babylon to Jerusalem.
* `Ezr 2:3` The children of Parosh, two thousand one *_hundred_* and seventy-two;
* `Ezr 2:4` The children of Shephatiah, three *_hundred_* and seventy-two;
* `Ezr 2:5` The children of Arah, seven *_hundred_* and seventy-five;
* `Ezr 2:6` The children of Pahath-moab, of the children of Jeshua and Joab, two thousand eight *_hundred_* and twelve;
* `Ezr 2:7` The children of Elam, one thousand two *_hundred_* and fifty-four;
* `Ezr 2:8` The children of Zattu, nine *_hundred_* and forty-five;
* `Ezr 2:9` The children of Zaccai, seven *_hundred_* and sixty;
* `Ezr 2:10` The children of Bani, six *_hundred_* and forty-two;
* `Ezr 2:11` The children of Bebai, six *_hundred_* and twenty-three;
* `Ezr 2:12` The children of Azgad, one thousand two *_hundred_* and twenty-two;
* `Ezr 2:13` The children of Adonikam, six *_hundred_* and sixty-six;
* `Ezr 2:15` The children of Adin, four *_hundred_* and fifty-four;
* `Ezr 2:17` The children of Bezai, three *_hundred_* and twenty-three;
* `Ezr 2:18` The children of Jorah, one *_hundred_* and twelve;
* `Ezr 2:19` The children of Hashum, two *_hundred_* and twenty-three;
* `Ezr 2:21` The children of Beth-lehem, one *_hundred_* and twenty-three;
* `Ezr 2:23` The men of Anathoth, one *_hundred_* and twenty-eight;
* `Ezr 2:25` The children of Kirjath-arim, Chephirah, and Beeroth, seven *_hundred_* and forty-three;
* `Ezr 2:26` The children of Ramah and Gaba, six *_hundred_* and twenty-one;
* `Ezr 2:27` The men of Michmas, one *_hundred_* and twenty-two;
* `Ezr 2:28` The men of Beth-el and Ai, two *_hundred_* and twenty-three;
* `Ezr 2:30` The children of Magbish, one *_hundred_* and fifty-six;
* `Ezr 2:31` The children of the other Elam, one thousand two *_hundred_* and fifty-four;
* `Ezr 2:32` The children of Harim, three *_hundred_* and twenty;
* `Ezr 2:33` The children of Lod, Hadid, and Ono, seven *_hundred_* and twenty-five;
* `Ezr 2:34` The children of Jericho, three *_hundred_* and forty-five;
* `Ezr 2:35` The children of Senaah, three thousand six *_hundred_* and thirty.
* `Ezr 2:36` The priests: the children of Jedaiah, of the house of Jeshua, nine *_hundred_* and seventy-three;
* `Ezr 2:38` The children of Pashur, one thousand two *_hundred_* and forty-seven;
* `Ezr 2:41` The singers: the children of Asaph, one *_hundred_* and twenty-eight.
* `Ezr 2:42` The children of the gatekeepers: the children of Shallum, the children of Ater, the children of Talmon, the children of Akkub, the children of Hatita, and the children of Shobai, in all one *_hundred_* and thirty-nine.
* `Ezr 2:58` All the Nethinims and the children of Solomon's servants were three *_hundred_* and ninety-two.
* `Ezr 2:60` The children of Delaiah, the children of Tobiah, and the children of Nekoda, six *_hundred_* and fifty-two.
* `Ezr 2:64` The whole congregation together was forty-two thousand three *_hundred_* and sixty,
* `Ezr 2:65` Besides their men-servants and their women-servants, of whom there were seven thousand three *_hundred_* and thirty-seven, and there were among them two *_hundred_* singing-men and singing-women.
* `Ezr 2:66` Their horses were seven *_hundred_* and thirty-six; their mules, two *_hundred_* and forty-five;
* `Ezr 2:67` Their camels, four *_hundred_* and thirty-five; their donkeys, six thousand seven *_hundred_* and twenty.
* `Ezr 2:69` They gave according to their ability to the treasury for the work sixty-one thousand drams of gold, five thousand minas of silver, and one *_hundred_* priests' garments.
* `Ezr 6:17` And they offered at the dedication of this house of God one *_hundred_* bulls, two *_hundred_* rams, four *_hundred_* lambs, and for a sin-offering for all Israel twelve male goats, according to the number of the tribes of Israel.
* `Ezr 7:22` To one *_hundred_* talents of silver, to one *_hundred_* measures of wheat, to one *_hundred_* baths of wine, to one *_hundred_* baths of oil, and salt without prescribing how much.
* `Ezr 8:3` Of the sons of Shechaniah, of the sons of Pharosh: Zechariah, and with him were one *_hundred_* and fifty reckoned by genealogy of the males.
* `Ezr 8:4` Of the sons of Pahath-moab: Elihoenai the son of Zerahiah, and with him two *_hundred_* males.
* `Ezr 8:5` Of the sons of Shechaniah: the son of Jahaziel, and with him three *_hundred_* males.
* `Ezr 8:9` Of the sons of Joab: Obadiah the son of Jehiel, and with him two *_hundred_* and eighteen males.
* `Ezr 8:10` Of the sons of Shelomith: the son of Josiphiah, and with him one *_hundred_* and sixty males.
* `Ezr 8:12` Of the sons of Azgad: Johanan the son of Hakkatan, and with him one *_hundred_* and ten males.
* `Ezr 8:20` And also of the Nethinims, whom David and the princes had appointed for the service of the Levites, two *_hundred_* and twenty Nethinims. All of them were expressed by name.
* `Ezr 8:26` I even weighed to their hand six *_hundred_* and fifty talents of silver, one *_hundred_* talents of silver vessels, one *_hundred_* talents of gold,
* `Neh 5:17` Moreover, there were at my table one *_hundred_* and fifty of the Jews and rulers, besides those who came to us from among the heathen who were around us.
* `Neh 7:8` The children of Parosh, two thousand one *_hundred_* and seventy-two;
* `Neh 7:9` The children of Shephatiah, three *_hundred_* and seventy-two;
* `Neh 7:10` The children of Arah, six *_hundred_* and fifty-two;
* `Neh 7:11` The children of Pahath-moab, of the children of Jeshua and Joab, two thousand eight *_hundred_* and eighteen;
* `Neh 7:12` The children of Elam, one thousand two *_hundred_* and fifty-four;
* `Neh 7:13` The children of Zattu, eight *_hundred_* and forty five;
* `Neh 7:14` The children of Zaccai, seven *_hundred_* and sixty;
* `Neh 7:15` The children of Binnui, six *_hundred_* and forty-eight;
* `Neh 7:16` The children of Bebai, six *_hundred_* and twenty-eight;
* `Neh 7:17` The children of Azgad, two thousand three *_hundred_* and twenty-two;
* `Neh 7:18` The children of Adonikam, six *_hundred_* and sixty-seven;
* `Neh 7:20` The children of Adin, six *_hundred_* and fifty-five;
* `Neh 7:22` The children of Hashum, three *_hundred_* and twenty-eight;
* `Neh 7:23` The children of Bezai, three *_hundred_* and twenty-four;
* `Neh 7:24` The children of Hariph, one *_hundred_* and twelve;
* `Neh 7:26` The men of Beth-lehem and Netophah, one *_hundred_* and eighty-eight;
* `Neh 7:27` The men of Anathoth, one *_hundred_* and twenty-eight;
* `Neh 7:29` The men of Kirjath-jearim, Chephirah, and Beeroth, seven *_hundred_* and forty-three;
* `Neh 7:30` The men of Ramah and Gaba, six *_hundred_* and twenty-one;
* `Neh 7:31` The men of Michmas, one *_hundred_* and twenty-two;
* `Neh 7:32` The men of Beth-el and Ai, one *_hundred_* and twenty-three;
* `Neh 7:34` The children of the other Elam, one thousand two *_hundred_* and fifty-four;
* `Neh 7:35` The children of Harim, three *_hundred_* and twenty;
* `Neh 7:36` The children of Jericho, three *_hundred_* and forty-five;
* `Neh 7:37` The children of Lod, Hadid, and Ono, seven *_hundred_* and twenty-one;
* `Neh 7:38` The children of Senaah, three thousand nine *_hundred_* and thirty.
* `Neh 7:39` The priests: the children of Jedaiah, of the house of Jeshua, nine *_hundred_* and seventy-three;
* `Neh 7:41` The children of Pashur, one thousand two *_hundred_* and forty-seven;
* `Neh 7:44` The singers: the children of Asaph, one *_hundred_* and forty-eight.
* `Neh 7:45` The gatekeepers: the children of Shallum, the children of Ater, the children of Talmon, the children of Akkub, the children of Hatita, and the children of Shobai, one *_hundred_* and thirty-eight.
* `Neh 7:60` All the Nethinims and the children of Solomon's servants were three *_hundred_* and ninety-two.
* `Neh 7:62` The children of Delaiah, the children of Tobiah, and the children of Nekoda, six *_hundred_* and forty-two.
* `Neh 7:66` The whole congregation together was forty-two thousand three *_hundred_* and sixty,
* `Neh 7:67` Besides their men-servants and their women-servants, of whom there were seven thousand three *_hundred_* and thirty-seven. And they had two *_hundred_* and forty five singing-men and singing-women.
* `Neh 7:68` Their horses, seven *_hundred_* and thirty-six; their mules, two *_hundred_* and forty-five;
* `Neh 7:69` Their camels, four *_hundred_* and thirty-five; and their donkeys, six thousand seven *_hundred_* and twenty.
* `Neh 7:70` And some of the chief of the fathers gave to the work. The Tirshatha gave to the treasure one thousand drams of gold, fifty basins, and five *_hundred_* and thirty priests' garments.
* `Neh 7:71` And some of the chief of the fathers gave to the treasury for the work twenty thousand drams of gold and two thousand and two *_hundred_* minas of silver.
* `Neh 11:6` All the sons of Perez who dwelt at Jerusalem were four *_hundred_* and sixty-eight valiant men.
* `Neh 11:8` And after him, Gabbai and Sallai, nine *_hundred_* and twenty-eight.
* `Neh 11:12` And their brothers who performed the work of the house numbered eight *_hundred_* and twenty-two; and Adaiah the son of Jeroham, the son of Pelaliah, the son of Amzi, the son of Zechariah, the son of Pashur, the son of Malchiah,
* `Neh 11:13` And his brothers, chief of the fathers, two *_hundred_* and forty-two; and Amashai the son of Azareel, the son of Ahasai, the son of Meshillemoth, the son of Immer,
* `Neh 11:14` And their brothers, mighty men of valor, one *_hundred_* twenty-eight. And their overseer was Zabdiel the son of one of the great men.
* `Neh 11:18` All the Levites in the holy city numbered two *_hundred_* and eighty-four.
* `Neh 11:19` Moreover, the gatekeepers, Akkub, Talmon, and their brothers who kept the gates numbered one *_hundred_* and seventy-two.
* `Est 1:1` Now it came to pass in the days of Ahasuerus (this is Ahasuerus who reigned from India even to Cush, over one *_hundred_* and twenty-seven provinces),
* `Est 1:4` When he showed the riches of his glorious kingdom and the honor of his excellent majesty many days, even one *_hundred_* and eighty days.
* `Est 8:9` Then the king's scribes were called at that time in the third month (that is, the month Sivan) on the twenty-third day. And it was written according to all that Mordecai commanded to the Jews, to the lieutenants, and the deputies and rulers of the provinces which are from India to Cush, one *_hundred_* and twenty-seven provinces, to every province according to its writing, to every people after their language, and to the Jews according to their writing and according to their language.
* `Est 9:6` And in the palace of Shushan the Jews slew and destroyed five *_hundred_* men.
* `Est 9:12` And the king said to Esther the queen, "The Jews have slain and destroyed five *_hundred_* men in the palace of Shushan and the ten sons of Haman. What have they done in the rest of the king's provinces? Now what is your petition? It shall be granted to you. Or what is your request further? It shall be done."
* `Est 9:15` For the Jews who were in Shushan assembled also on the fourteenth day of the month Adar and slew three *_hundred_* men at Shushan. But on the plunder they did not lay their hands.
* `Est 9:30` And he sent the letters to all the Jews, to the one *_hundred_* and twenty-seven provinces of the kingdom of Ahasuerus, with words of peace and truth,
* `Job 1:3` His substance also was seven thousand sheep, three thousand camels, five *_hundred_* yoke of oxen, five *_hundred_* female donkeys, and a very great household. This man was the greatest of all the men of the east.
* `Job 42:16` After this Job lived one *_hundred_* and forty years and saw his sons and his sons' sons, even four generations.
* `Pro 17:10` A reproof enters more into a wise man than one *_hundred_* stripes into a fool.
* `Ecc 6:3` If a man begets a *_hundred_* children and lives many years, so that the days of his years are many, but his soul is not filled with good and he also has no burial, I say that the one of an untimely birth is better than he is.
* `Ecc 8:12` Though a sinner does evil a *_hundred_* times and his days are prolonged, yet surely I know that it will be well with those who fear God, who fear before him.
* `Sos 8:12` My vineyard which is mine is before me. You, O Solomon, must have a thousand, and those who keep its fruit, two *_hundred_*.
* `Isa 37:36` Then the angel of the LORD went forth and smote in the camp of the Assyrians one *_hundred_* and eighty-five thousand. And when they arose early in the morning, behold, they were all dead corpses.
* `Isa 65:20` No longer shall there be from there an infant of days nor an old man who has not filled his days. For the child shall die at a *_hundred_* years old, but the sinner being a *_hundred_* years old shall be accursed.
* `Jer 52:23` And there were ninety-six pomegranates on a side, and all the pomegranates upon the net-work were one *_hundred_* on all sides.
* `Jer 52:29` In the eighteenth year of Nebuchadnezzar, he carried away captive from Jerusalem eight *_hundred_* and thirty-two persons;
* `Jer 52:30` In the twenty-third year of Nebuchadnezzar, Nebuzar-adan the captain of the guard carried away captive of the Jews seven *_hundred_* and forty-five persons. All the persons were four thousand and six *_hundred_*.
* `Ezk 4:5` For I have laid upon you the years of their iniquity, according to the number of the days, three *_hundred_* and ninety days. Thus you shall bear the iniquity of the house of Israel.
* `Ezk 4:9` "Also take wheat, barley, beans, lentils, millet, and spelt, put them in one vessel, and make yourself bread from them. According to the number of the days that you shall lie upon your side, three *_hundred_* and ninety days, you shall eat it.
* `Ezk 40:19` Then he measured the breadth from the front of the lower gate to the front of the inner court outside, one *_hundred_* cubits eastward and northward.
* `Ezk 40:23` And there was a gate in the inner court over against the gate toward the north, just like the one toward the east. And he measured from gate to gate one *_hundred_* cubits.
* `Ezk 40:27` And there was a gate in the inner court toward the south. And he measured from gate to gate toward the south one *_hundred_* cubits.
* `Ezk 40:47` So he measured the court, one *_hundred_* cubits long and one *_hundred_* cubits broad, square, and also the altar that was before the house.
* `Ezk 41:13` So he measured the house, one *_hundred_* cubits long, and the separate place and the building with its walls, one *_hundred_* cubits long,
* `Ezk 41:14` And the breadth of the face of the house and of the separate place toward the east, one *_hundred_* cubits.
* `Ezk 41:15` And he measured the length of the building over against the separate place which was behind it and its galleries on one side and on the other side, one *_hundred_* cubits. The inner temple and the porches of the court,
* `Ezk 42:2` Before the length of one *_hundred_* cubits was the north door, and the breadth was fifty cubits.
* `Ezk 42:8` For the length of the chambers that were in the outer court was fifty cubits. And behold, before the temple were one *_hundred_* cubits.
* `Ezk 42:16` He measured on the east side with the measuring reed five *_hundred_* reeds, with the measuring reed all around.
* `Ezk 42:17` He measured on the north side five *_hundred_* reeds with the measuring reed all around.
* `Ezk 42:18` He measured on the south side five *_hundred_* reeds with the measuring reed.
* `Ezk 42:19` He turned around to the west side and measured five *_hundred_* reeds with the measuring reed.
* `Ezk 42:20` He measured it by the four sides. It had a wall around, five *_hundred_* reeds long and five *_hundred_* broad, to make a separation between the sanctuary and the profane place.
* `Ezk 45:2` Of this there shall be for the sanctuary five *_hundred_* in length, with five *_hundred_* in breadth, square around, and fifty cubits around for its suburbs.
* `Ezk 45:15` And one lamb out of the flock, out of two *_hundred_*, out of the fat pastures of Israel, for a food-offering, for a burnt-offering, and for peace-offerings, to make reconciliation for them," says the Lord GOD.
* `Ezk 48:16` And these shall be its measures: the north side four thousand and five *_hundred_*, the south side four thousand and five *_hundred_*, on the east side four thousand and five *_hundred_*, and the west side four thousand and five *_hundred_*.
* `Ezk 48:17` And the suburbs of the city shall be toward the north two *_hundred_* and fifty, toward the south two *_hundred_* and fifty, toward the east two *_hundred_* and fifty, and toward the west two *_hundred_* and fifty.
* `Ezk 48:30` "And these are the exits of the city on the north side, four thousand and five *_hundred_* measures.
* `Ezk 48:32` And on the east side four thousand and five *_hundred_*, with three gates: the gate of Joseph, one; the gate of Benjamin, one; the gate of Dan, one.
* `Ezk 48:33` And on the south side four thousand and five *_hundred_* measures, and three gates: the gate of Simeon, one; the gate of Issachar, one; the gate of Zebulun, one.
* `Ezk 48:34` And on the west side four thousand and five *_hundred_*, with their three gates: the gate of Gad, one; the gate of Asher, one; the gate of Naphtali, one.
* `Dan 6:1` It pleased Darius to set over the kingdom one *_hundred_* and twenty princes who should be over the whole kingdom,
* `Dan 8:14` And he said to me, "Until two thousand and three *_hundred_* days. Then the sanctuary shall be cleansed."
* `Dan 12:11` And from the time that the daily sacrifice is taken away and the abomination that makes desolate is set up, there shall be one thousand two *_hundred_* and ninety days.
* `Dan 12:12` Blessed is he who waits, and comes to the one thousand three *_hundred_* and thirty-five days.
* `Amo 5:3` For thus says the Lord GOD: "The city that went out by a thousand shall leave a *_hundred_*, and that which went forth by a *_hundred_* shall leave ten to the house of Israel."
* `Jna 4:11` And should I not spare Nineveh, that great city, in which are more than one *_hundred_* and twenty thousand persons who cannot discern between their right hand and their left hand—and also a large number of livestock?"
* `Mth 13:8` But others fell upon good ground and brought forth fruit, some one *_hundred_*-fold, some sixty-fold, some thirty-fold.
* `Mth 13:23` But he who receives seed into the good ground is he who hears the word and understands it, who also bears fruit and brings forth, some one *_hundred_*-fold, some sixty, some thirty."
* `Mth 18:12` "What do you think? If a man has one *_hundred_* sheep, and one of them has gone astray, does he not leave the ninety-nine, go to the mountains, and seek that which has gone astray?
* `Mth 18:28` But the same servant went out, found one of his fellow-servants who owed him one *_hundred_* denarii, laid hands on him, and took him by the throat, saying, 'Pay me what you owe.'
* `Mth 19:29` And everyone who has forsaken houses, brothers, sisters, father, mother, wife, children, or lands for my name's sake, shall receive one *_hundred_*-fold and shall inherit everlasting life.
* `Mrk 4:8` And others fell on good ground and yielded fruit that sprang up, increased, and brought forth, some thirty-, some sixty-, and some one *_hundred_*-fold."
* `Mrk 4:20` And these are those who are sown on good ground: those who hear the word, receive it, and bring forth fruit, some thirty-, some sixty-, and some one *_hundred_*-fold."
* `Mrk 6:37` He answered and said to them, "You give them something to eat." And they say to him, "Shall we go and buy two *_hundred_* denarii worth of bread and give it to them to eat?"
* `Mrk 10:30` Who shall not receive one *_hundred_*-fold now in this time—houses, brothers, sisters, mothers, children, and lands, along with persecutions—and in the age to come, eternal life.
* `Mrk 14:5` For it might have been sold for more than three *_hundred_* denarii and given to the poor." And they murmured against her.
* `Luk 7:41` "There was a certain creditor who had two debtors: one owed five *_hundred_* denarii and the other fifty.
* `Luk 8:8` And others fell on good ground, sprang up, and bore fruit one *_hundred_*-fold." And when he had said these things, he cried, "He who has ears to hear, let him hear."
* `Luk 15:4` "What man of you having one *_hundred_* sheep, if he loses one of them, does not leave the ninety-nine in the wilderness and go after that which is lost until he finds it?
* `Luk 16:6` And he said, 'One *_hundred_* measures of oil.' And he said to him, 'Take your bill, sit down quickly, and write fifty.'
* `Luk 16:7` Then he said to another, 'And how much do you owe?' And he said, 'One *_hundred_* measures of wheat.' And he said to him, 'Take your bill and write eighty.'
* `Jhn 6:7` Philip answered him, "Two *_hundred_* denarii worth of bread is not sufficient for them, so that each of them may receive a little."
* `Jhn 12:5` "Why was this ointment not sold for three *_hundred_* denarii and given to the poor?"
* `Jhn 19:39` And Nicodemus (who at the first came to Jesus by night) also came and brought a mixture of myrrh and aloes, about one *_hundred_* pounds in weight.
* `Jhn 21:8` And the other disciples came in a little boat (for they were not far from land, but about two *_hundred_* cubits) dragging the net with fish.
* `Jhn 21:11` Simon Peter went up and drew the net to land full of great fish—one *_hundred_* and fifty-three. And even though there were so many, yet the net was not broken.
* `Act 1:15` And in those days, Peter stood up in the midst of the disciples, and said (the number of the names together were about one *_hundred_* and twenty),
* `Act 5:36` For before these days, Theudas rose, boasting himself to be somebody, to whom a number of about four *_hundred_* men joined themselves. He was slain, and as many as obeyed him were all scattered and brought to nothing.
* `Act 7:6` And God spoke in this way, that 'his offspring should sojourn in a foreign land, and that they should bring them into bondage and treat them ill four *_hundred_* years.'
* `Act 13:20` And after that, he gave judges to them, about the space of four *_hundred_* and fifty years, until Samuel the prophet.
* `Act 23:23` And he called two centurions to him, saying, "Make ready two *_hundred_* soldiers, seventy horsemen, and two *_hundred_* spearmen to go to Caesarea at the third hour of the night.
* `Act 27:37` In all, we were two *_hundred_* and seventy-six souls on the ship.
* `Rom 4:19` And not having been weak in faith, he did not consider his own body now dead when he was about one *_hundred_* years old, neither yet the deadness of Sarah's womb.
* `1Co 15:6` After that, he was seen by more than five *_hundred_* brothers at once, of whom the greater part remain to this present, but some have fallen asleep.
* `Gal 3:17` And I say this: that the law, which was four *_hundred_* and thirty years after, cannot invalidate the covenant that was confirmed before by God in Christ so that it should make the promise of no effect.
* `Rev 7:4` And I heard the number of those who were sealed. And there were sealed one *_hundred_* and forty-four thousand of all the tribes of the children of Israel.
* `Rev 9:16` And the number of the army of the horsemen was two *_hundred_* million. And I heard their number.
* `Rev 11:3` And I will give power to my two witnesses, and they shall prophesy for one thousand two *_hundred_* and sixty days clothed in sackcloth."
* `Rev 12:6` And the woman fled into the wilderness where she has a place prepared by God so that they should feed her there for one thousand two *_hundred_* and sixty days.
* `Rev 13:18` Here is wisdom. Let him who has understanding count the number of the beast, for it is the number of a man. And his number is six *_hundred_* and sixty-six.
* `Rev 14:1` And I looked, and behold, a Lamb stood on mount Zion, and with him one *_hundred_* and forty-four thousand, having his Father's name written on their foreheads.
* `Rev 14:3` And they sang a new song before the throne and before the four beasts and the elders. And no man could learn that song but the one *_hundred_* and forty-four thousand who were redeemed from the earth.
* `Rev 14:20` And the wine-press was trodden outside the city, and blood came out of the wine-press, even to the horses' bridles, by the space of one thousand and six *_hundred_* furlongs.
* `Rev 21:17` And he measured its wall: one *_hundred_* and forty-four cubits, according to the measure of a man, which is also of an angel.

_527 verses containing HUNDRED_

== HUNDRED-FOLD

* `Gen 26:12` Then Isaac sowed in that land and received in the same year one *_hundred-fold_*. And the LORD blessed him.
* `2Sa 24:3` And Joab said to the king, "Now may the LORD your God add to the people, however many they may be, one *_hundred-fold_*, and that the eyes of my lord the king may see it. But why does my lord the king delight in this thing?"
* `Mth 13:8` But others fell upon good ground and brought forth fruit, some one *_hundred-fold_*, some sixty-fold, some thirty-fold.
* `Mth 13:23` But he who receives seed into the good ground is he who hears the word and understands it, who also bears fruit and brings forth, some one *_hundred-fold_*, some sixty, some thirty."
* `Mth 19:29` And everyone who has forsaken houses, brothers, sisters, father, mother, wife, children, or lands for my name's sake, shall receive one *_hundred-fold_* and shall inherit everlasting life.
* `Mrk 4:8` And others fell on good ground and yielded fruit that sprang up, increased, and brought forth, some thirty-, some sixty-, and some one *_hundred-fold_*."
* `Mrk 4:20` And these are those who are sown on good ground: those who hear the word, receive it, and bring forth fruit, some thirty-, some sixty-, and some one *_hundred-fold_*."
* `Mrk 10:30` Who shall not receive one *_hundred-fold_* now in this time—houses, brothers, sisters, mothers, children, and lands, along with persecutions—and in the age to come, eternal life.
* `Luk 8:8` And others fell on good ground, sprang up, and bore fruit one *_hundred-fold_*." And when he had said these things, he cried, "He who has ears to hear, let him hear."

_9 verses containing HUNDRED-FOLD_

== HUNDREDS

* `Exo 18:21` Moreover, you shall provide out of all the people able men, those who fear God, men of truth, hating covetousness, and place those over them to be rulers of thousands, rulers of *_hundreds_*, rulers of fifties, and rulers of tens.
* `Exo 18:25` And Moses chose able men out of all Israel and made them heads over the people, rulers of thousands, rulers of *_hundreds_*, rulers of fifties, and rulers of tens.
* `Num 31:14` And Moses was angry with the officers of the host, with the captains over thousands, and captains over *_hundreds_*, who came from the battle.
* `Num 31:48` And the officers who were over thousands of the hosts, the captains of thousands, and captains of *_hundreds_* came near to Moses,
* `Num 31:52` And all the gold of the offering that they offered to the LORD, from the captains of thousands and from the captains of *_hundreds_*, was sixteen thousand seven hundred and fifty shekels.
* `Num 31:54` And Moses and Eleazar the priest took the gold from the captains of thousands and of *_hundreds_* and brought it into the Tabernacle of the Congregation for a memorial for the children of Israel before the LORD.
* `Deu 1:15` So I took the chief of your tribes, wise men, and known, and made them heads over you, captains over thousands, captains over *_hundreds_*, captains over fifties, captains over tens, and officers among your tribes.
* `1Sa 22:7` Saul said to his servants who stood around him, "Hear now, you Benjaminites. Will the son of Jesse give every one of you fields and vineyards and make you all captains of thousands and captains of *_hundreds_*?
* `1Sa 29:2` And the lords of the Philistines passed on by *_hundreds_* and by thousands, but David and his men passed on in the rear with Achish.
* `2Sa 18:1` And David numbered the people who were with him and set over them captains of thousands and captains of *_hundreds_*.
* `2Sa 18:4` And the king said to them, "What seems to you best I will do." And the king stood by the gate side, and all the people came out by *_hundreds_* and by thousands.
* `2Ki 11:4` And in the seventh year Jehoiada sent and took the rulers over *_hundreds_*, with the captains and the guard, and brought them to him into the house of the LORD. Then he made a covenant with them and made them swear an oath in the house of the LORD and showed them the king's son.
* `2Ki 11:9` And the captains over the *_hundreds_* did according to all things that Jehoiada the priest commanded. And they each took his men who were to come in on the sabbath, with those who should go out on the sabbath, and came to Jehoiada the priest.
* `2Ki 11:10` And to the captains over *_hundreds_* the priest gave king David's spears and shields that were in the temple of the LORD.
* `2Ki 11:15` But Jehoiada the priest commanded the captains of the *_hundreds_*, the officers of the host, and said to them, "Bring her forth outside the ranges and kill with the sword him who follows her." For the priest had said, "Do not let her be slain in the house of the LORD."
* `2Ki 11:19` And he took the rulers over *_hundreds_*, the captains, the guard, and all the people of the land, and they brought the king down from the house of the LORD and came by the way of the gate of the guard to the king's house. And he sat on the throne of the kings.
* `1Ch 13:1` And David consulted with the captains of thousands and of *_hundreds_* and with every leader.
* `1Ch 26:26` This Shelomith and his brothers were over all the treasures of the dedicated things which David the king, the chief fathers who were the captains over thousands and *_hundreds_*, and the captains of the host had dedicated.
* `1Ch 27:1` Now the children of Israel after their number, namely, the chief fathers, captains of thousands and *_hundreds_*, and their officers who served the king in any matter of the courses, which came in and went out month by month throughout all the months of the year, of every course were twenty-four thousand.
* `1Ch 28:1` And David assembled all the princes of Israel, the princes of the tribes, the captains of the companies that ministered to the king by course, the captains over the thousands, captains over the *_hundreds_*, and the stewards over all the substance and possession of the king and of his sons, with the officers, with the mighty men, and with all the valiant men at Jerusalem.
* `1Ch 29:6` Then the chief of the fathers and princes of the tribes of Israel and the captains of thousands and of *_hundreds_*, with the rulers over the king's work, offered willingly,
* `2Ch 1:2` Then Solomon spoke to all Israel, to the captains of thousands and of *_hundreds_*, to the judges, and to every governor in all Israel, the chief of the fathers.
* `2Ch 23:1` And in the seventh year Jehoiada strengthened himself and took the captains of *_hundreds_*, even Azariah the son of Jeroham, Ishmael the son of Jehohanan, Azariah the son of Obed, Maaseiah the son of Adaiah, and Elishaphat the son of Zichri, into covenant with him.
* `2Ch 23:9` Moreover, Jehoiada the priest delivered to the captains of *_hundreds_* spears, bucklers, and shields, which had been king David's, which were in the house of God.
* `2Ch 23:14` Then Jehoiada the priest brought out the captains of *_hundreds_* who were set over the host and said to them, "Bring her forth outside the ranges. And whoever follows her, let him be slain with the sword." For the priest said, "Do not slay her in the house of the LORD."
* `2Ch 23:20` And he took the captains of *_hundreds_*, the nobles, the governors of the people, and all the people of the land, and brought the king down from the house of the LORD. And they came through the high gate into the king's house and set the king upon the throne of the kingdom.
* `2Ch 25:5` Moreover, Amaziah assembled Judah and made them captains over thousands and captains over *_hundreds_*, according to the houses of their fathers, throughout all Judah and Benjamin. And he numbered them from twenty years old and above and found them to be three hundred thousand choice men, able to go forth to war, who could handle spear and shield.
* `Mrk 6:40` And they sat down in ranks by *_hundreds_* and by fifties.

_28 verses containing HUNDREDS_

== HUNDREDTH

* `Gen 7:11` In the six *_hundredth_* year of Noah's life, in the second month, on the seventeenth day of the month, the same day all the fountains of the great deep were broken up and the windows of heaven were opened.
* `Neh 5:11` I pray you, restore to them even this day their lands, their vineyards, their olive-groves, and their houses, also the *_hundredth_* part of the money, and of the grain, the wine, and the oil that you exact from them."

_2 verses containing HUNDREDTH_

== HUNG

* `Psa 137:2` We *_hung_* our harps upon the willows in its midst.
* `Ezk 27:10` "They of Persia, of Lud, and of Phut were in your army, your military men. They *_hung_* the shield and helmet in you. They set forth your splendor.
* `Ezk 27:11` The men of Arvad with your army were upon your walls on all sides, and the Gammadims were in your towers. They *_hung_* their shields upon your walls on every side. They have made your beauty perfect.

_3 verses containing HUNG_

== HUNGER

* `Exo 16:3` And the children of Israel said to them, "O that we had died by the hand of the LORD in the land of Egypt when we sat by the flesh-pots and when we ate bread to the full, for you have brought us forth into this wilderness to kill this whole assembly with *_hunger_*."
* `Deu 28:48` Therefore you shall serve your enemies which the LORD shall send against you in *_hunger_*, in thirst, in nakedness, and in lack of all things. And he shall put a yoke of iron upon your neck until he has destroyed you.
* `Deu 32:24` They shall be burnt with *_hunger_* and devoured with burning heat and with bitter destruction. I will also send the teeth of beasts upon them, with the poison of serpents of the dust.
* `Neh 9:15` And gave them bread from heaven for their *_hunger_* and brought forth water for them out of the rock for their thirst, and promised them that they should go in to possess the land which you had sworn to give them.
* `Job 18:12` His strength shall be *_hunger_*-bitten, and destruction shall be ready at his side.
* `Psa 34:10` The young lions lack and suffer *_hunger_*, but those who seek the LORD shall not lack any good thing.
* `Pro 19:15` Slothfulness casts into a deep sleep, and an idle soul shall suffer *_hunger_*.
* `Isa 49:10` They shall neither *_hunger_* nor thirst, neither shall the heat or sun smite them, for he who has mercy on them shall lead them, even by the springs of water he shall guide them.
* `Jer 38:9` "My lord the king, these men have done evil in all that they have done to Jeremiah the prophet, whom they have cast into the dungeon. And he is likely to die by *_hunger_* in the place where he is, for there is no more bread in the city."
* `Jer 42:14` Saying, "No, but we will go into the land of Egypt where we shall see no war, nor hear the sound of the trumpet, nor *_hunger_* for bread. And there we will dwell,"
* `Lam 2:19` [QOF] Arise, cry out in the night. In the beginning of the watches pour out your heart like water before the face of the Lord. Lift up your hands toward him for the life of your young children, who faint for *_hunger_* at the head of every street."
* `Lam 4:9` [TET] Those who are slain with the sword are better than those who are slain with *_hunger_*, for these pine away, stricken through for lack of the fruits of the field.
* `Ezk 34:29` And I will raise up for them a plant of renown, and they shall no longer be consumed with *_hunger_* in the land, neither bear the shame of the heathen anymore.
* `Mth 5:6` Blessed are those who *_hunger_* and thirst for righteousness, for they shall be filled.
* `Luk 6:21` Blessed are you who *_hunger_* now, for you shall be filled. Blessed are you who weep now, for you shall laugh.
* `Luk 6:25` Woe to you who are full! For you shall *_hunger_*. Woe to you who laugh now! For you shall mourn and weep.
* `Luk 15:17` And when he came to himself, he said, 'How many hired servants of my father have bread enough to spare, and I am perishing with *_hunger_*!
* `Jhn 6:35` And Jesus said to them, "I am the bread of life. He who comes to me shall never *_hunger_*, and he who believes in me shall never thirst.
* `1Co 4:11` Even to this present hour we *_hunger_*, thirst, are naked, are buffeted, and have no certain dwelling-place.
* `2Co 11:27` In weariness and painfulness, in watchings often, in *_hunger_* and thirst, in fastings often, in cold and nakedness.
* `Rev 6:8` And I looked, and behold, a pale horse. And his name who sat on him was Death, and hell followed with him. And power was given to them over the fourth part of the earth to kill with sword, with *_hunger_*, with death, and with the beasts of the earth.
* `Rev 7:16` 'They shall no longer *_hunger_*, neither thirst anymore, neither shall the sun fall upon them, nor any heat.'

_22 verses containing HUNGER_

== HUNGER-BITTEN

* `Job 18:12` His strength shall be *_hunger-bitten_*, and destruction shall be ready at his side.

_1 verse containing HUNGER-BITTEN_

== HUNGERS

* `Pro 25:21` If your enemy *_hungers_*, give him bread to eat, and if he thirsts, give him water to drink,
* `Rom 12:20` Therefore, "if your enemy *_hungers_*, feed him, and if he thirsts, give him drink, for in doing so you shall heap coals of fire on his head."
* `1Co 11:34` And if any man *_hungers_*, let him eat at home so that you do not come together to condemnation. And the rest I will set in order when I come.

_3 verses containing HUNGERS_

== HUNGRY

* `Deu 8:3` And he humbled you and allowed you to be *_hungry_*, and fed you with manna which you did not know, neither did your fathers know, so that he might make you know that man does not live by bread only, but man lives by every word that proceeds out of the mouth of the LORD.
* `1Sa 2:5` Those who were full have hired out themselves for bread, and those who were *_hungry_* ceased. Even the barren has borne seven, and she who has many children has become feeble.
* `2Sa 17:29` Honey, butter, sheep, and cheese of cows for David and for the people who were with him to eat, for they said, "The people are *_hungry_*, weary, and thirsty in the wilderness."
* `2Ki 7:12` And the king arose in the night and said to his servants, "I will now show you what the Syrians have done to us. They know that we are *_hungry_*; therefore, they have gone out of the camp to hide themselves in the field, saying, 'When they come out of the city, we shall take them alive and get into the city.'"
* `Job 5:5` The *_hungry_* eat up his harvest and take it even out of the thorns, and the robber swallows up their substance.
* `Job 22:7` You have not given water to the weary to drink and you have withheld bread from the *_hungry_*.
* `Job 24:10` They cause him to go naked without clothing and they take away the sheaf from the *_hungry_*,
* `Psa 50:12` If I were *_hungry_*, I would not tell you, for the world is mine, and the fullness thereof.
* `Psa 107:5` *_Hungry_* and thirsty, their soul fainted in them.
* `Psa 107:9` For he satisfies the longing soul and fills the *_hungry_* soul with goodness.
* `Psa 107:36` And there he makes the *_hungry_* to dwell so that they may prepare a city for habitation.
* `Psa 146:7` Who executes judgment for the oppressed, who gives food to the *_hungry_*. The LORD sets the prisoners free.
* `Pro 6:30` Men do not despise a thief if he steals to satisfy his soul when he is *_hungry_*.
* `Pro 27:7` The full soul loathes a honey-comb, but to the *_hungry_* soul every bitter thing is sweet.
* `Pro 28:15` As a roaring lion and a *_hungry_* bear, so is a wicked ruler over the poor people.
* `Isa 8:21` And they shall pass through it distressed and *_hungry_*. And it shall come to pass, that when they are *_hungry_*, they shall fret themselves and curse their king and their God and look upward.
* `Isa 9:20` And he shall snatch on the right hand and be *_hungry_*. And he shall eat on the left hand, and they shall not be satisfied. Every man shall eat the flesh of his own arm.
* `Isa 29:8` It shall even be as when a *_hungry_* man dreams, and behold, he eats, but he awakes and his soul is empty, or as when a thirsty man dreams, and behold, he drinks, but he awakes, and behold, he is faint and his soul has appetite. Thus the multitude of all the nations shall be who fight against mount Zion.
* `Isa 32:6` For the vile person will speak villainy, and his heart will work iniquity, to practice hypocrisy and to utter error against the LORD, to make the soul of the *_hungry_* empty, and to cause the drink of the thirsty to fail.
* `Isa 44:12` The smith with the tongs works in the coals, fashions it with hammers, and works it with the strength of his arms. Indeed, he is *_hungry_* and his strength fails. He drinks no water and is faint.
* `Isa 58:7` Is it not to deal your bread to the *_hungry_*, and that you should bring the poor who are cast out to your house, when you see the naked that you should cover him, and that you should not hide yourself from your own flesh?
* `Isa 58:10` And if you draw out your soul to the *_hungry_* and satisfy the afflicted soul, then your light shall rise in obscurity and your darkness shall be like the noon day.
* `Isa 65:13` Therefore, thus says the Lord GOD: "Behold, my servants shall eat, but you shall be *_hungry_*. Behold, my servants shall drink, but you shall be thirsty. Behold, my servants shall rejoice, but you shall be ashamed.
* `Ezk 18:7` Has not oppressed any, but has restored to the debtor his pledge, has stripped no one by violence, has given his bread to the *_hungry_*, has covered the naked with a garment,
* `Ezk 18:16` Neither has oppressed any, has not withheld the pledge, neither has stripped by violence, but has given his bread to the *_hungry_*, has covered the naked with a garment,
* `Mth 4:2` And when he had fasted forty days and forty nights, he was afterward *_hungry_*.
* `Mth 12:1` At that time Jesus went through the grain-fields on the sabbath, and his disciples were *_hungry_* and began to pluck the heads of grain and to eat.
* `Mth 12:3` But he said to them, "Have you not read what David did when he and those who were with him were *_hungry_*,
* `Mth 21:18` Now in the morning as he was returning into the city, he was *_hungry_*.
* `Mth 25:35` For I was *_hungry_* and you gave me food. I was thirsty and you gave me drink. I was a stranger and you took me in.
* `Mth 25:37` Then the righteous will answer him, saying, 'Lord, when did we see you *_hungry_* and feed you, or thirsty and give you drink?
* `Mth 25:42` For I was *_hungry_* and you gave me no food. I was thirsty and you gave me no drink.
* `Mth 25:44` Then they will also answer him, saying, 'Lord, when did we see you *_hungry_*, thirsty, a stranger, naked, sick, or in prison, and did not minister to you?'
* `Mrk 2:25` And he said to them, "Have you never read what David did when he had need and was *_hungry_*—he and those who were with him—
* `Mrk 11:12` And on the next day, when they had come from Bethany, he was *_hungry_*,
* `Luk 1:53` 'He has filled the *_hungry_* with good things,' and the rich he has sent away empty.
* `Luk 4:2` Being forty days tempted by the devil. And in those days he ate nothing, and when they had ended, he was afterward *_hungry_*.
* `Luk 6:3` And Jesus, answering them, said, "Have you not read so much as this, what David did when he was *_hungry_*, he and those who were with him,
* `Act 10:10` And he became very *_hungry_* and wished to eat, but while they made ready, he fell into a trance
* `1Co 11:21` For in eating, each one takes before another his own supper. And one is *_hungry_* and another is drunken.
* `Phl 4:12` I know both how to be abased and I know how to abound. Everywhere and in all things I am instructed both to be full and to be *_hungry_*, both to abound and to suffer need.

_41 verses containing HUNGRY_

== HUNT

* `Gen 27:3` Now therefore, take, I pray you, your weapons, your quiver and your bow, and go out to the field and *_hunt_* some wild game for me.
* `Gen 27:5` And Rebekah heard when Isaac spoke to Esau his son. And Esau went to the field to *_hunt_* for wild game and to bring it.
* `1Sa 24:11` Moreover, my father, look. Look at the skirt of your robe in my hand. For in that I cut off the skirt of your robe and did not kill you, know and see that there is neither evil nor transgression in my hand. I have not sinned against you, yet you *_hunt_* my soul to take it.
* `Job 10:16` And if my head exalts itself, you *_hunt_* me like a fierce lion, and again you show yourself wonderful upon me.
* `Job 38:39` Will you *_hunt_* the prey for the lion or fill the appetite of the young lions
* `Psa 140:11` Do not let an evil speaker be established on the earth. Evil shall *_hunt_* the violent man to overthrow him.
* `Pro 6:26` For by means of a lewd woman a man is brought to a piece of bread, and the adulteress will *_hunt_* for the precious life.
* `Jer 16:16` "Behold, I will send for many fishermen," says the LORD, "and they shall fish them. And afterward, I will send for many hunters, and they shall *_hunt_* them from every mountain, from every hill, and out of the holes of the rocks.
* `Lam 4:18` [TSADI] They *_hunt_* our steps so that we cannot go in our streets. Our end is near. Our days are fulfilled, for our end has come.
* `Ezk 13:18` And say, 'Thus says the Lord GOD: "Woe to the women who sew cushions to all armpits and make veils upon the head of every stature to *_hunt_* souls! Will you *_hunt_* the souls of my people, but save the souls alive who come to you?
* `Ezk 13:20` Therefore, thus says the Lord GOD: "Behold, I am against your cushions with which you *_hunt_* the souls there to make them fly. I will tear them from your arms and let the souls go, even the souls whom you *_hunt_* to make them fly.
* `Mic 7:2` The godly man has perished from the earth and there is no one upright among men. They all lie in wait for blood. They each *_hunt_* his brother with a net.

_12 verses containing HUNT_

== HUNTED

* `Ezk 13:21` Your veils I will also tear and deliver my people out of your hand, and they shall no longer be in your hand to be *_hunted_*. And you shall know that I am the LORD.

_1 verse containing HUNTED_

== HUNTER

* `Gen 10:9` He was a mighty *_hunter_* before the LORD; therefore, it is said, "Even as Nimrod the mighty *_hunter_* before the LORD."
* `Gen 25:27` And the boys grew. And Esau was a skillful *_hunter_*, a man of the field, and Jacob was a plain man dwelling in tents.
* `Pro 6:5` Deliver yourself like a gazelle from the hand of the *_hunter_* and like a bird from the hand of the fowler.

_3 verses containing HUNTER_

== HUNTERS

* `Jer 16:16` "Behold, I will send for many fishermen," says the LORD, "and they shall fish them. And afterward, I will send for many *_hunters_*, and they shall hunt them from every mountain, from every hill, and out of the holes of the rocks.

_1 verse containing HUNTERS_

== HUNTING

* `Gen 27:30` And it came to pass, as soon as Isaac had made an end of blessing Jacob, and Jacob had yet scarcely gone out from the presence of Isaac his father, that Esau his brother came in from his *_hunting_*.
* `Pro 12:27` The slothful man does not roast that which he took in *_hunting_*, but the substance of a diligent man is precious.

_2 verses containing HUNTING_

== HUNTS

* `Lev 17:13` And whatever man there may be of the children of Israel or of the strangers who sojourn among you who *_hunts_* and catches any beast or bird that may be eaten, he shall even pour out its blood and cover it with dust.
* `1Sa 26:20` Now therefore, do not let my blood fall to the earth before the face of the LORD, for the king of Israel has come out to seek a flea, as when one *_hunts_* a partridge in the mountains."

_2 verses containing HUNTS_

== HUPHAM

* `Num 26:39` Of Shupham, the family of the Shuphamites; of *_Hupham_*, the family of the Huphamites.

_1 verse containing HUPHAM_

== HUPHAMITES

* `Num 26:39` Of Shupham, the family of the Shuphamites; of Hupham, the family of the *_Huphamites_*.

_1 verse containing HUPHAMITES_

== HUPPAH

* `1Ch 24:13` The thirteenth to *_Huppah_*, the fourteenth to Jeshebeab,

_1 verse containing HUPPAH_

== HUPPIM

* `Gen 46:21` And the sons of Benjamin: Belah, Becher, Ashbel, Gera, Naaman, Ehi, Rosh, Muppim, *_Huppim_*, and Ard.
* `1Ch 7:12` Shuppim and *_Huppim_* were the children of Ir. And Hushim was the son of Aher.
* `1Ch 7:15` And Machir took for a wife the sister of *_Huppim_* and Shuppim, whose sister's name was Maachah), and the name of the second was Zelophehad, and Zelophehad had daughters.

_3 verses containing HUPPIM_

== HUR

* `Exo 17:10` So Joshua did as Moses had said to him and fought with Amalek. And Moses, Aaron, and *_Hur_* went up to the top of the hill.
* `Exo 17:12` But Moses's hands were heavy, and they took a stone and put it under him, and he sat upon it. And Aaron and *_Hur_* supported his hands, one on one side and the other on the other side. And his hands were steady until the going down of the sun.
* `Exo 24:14` And he said to the elders, "Wait here for us until we come back to you. And behold, Aaron and *_Hur_* are with you. If any man has any matters to do, let him come to them."
* `Exo 31:2` "Behold, I have called by name Bezaleel the son of Uri, the son of *_Hur_*, of the tribe of Judah,
* `Exo 35:30` And Moses said to the children of Israel, "Behold, the LORD has called by name Bezaleel, the son of Uri, the son of *_Hur_*, of the tribe of Judah.
* `Exo 38:22` And Bezaleel the son of Uri, the son of *_Hur_*, of the tribe of Judah, made all that the LORD commanded Moses.
* `Num 31:8` And they slew the kings of Midian, besides the rest of those who were slain, namely, Evi, Rekem, Zur, *_Hur_*, and Reba, five kings of Midian. Balaam the son of Beor they also slew with the sword.
* `Jsh 13:21` All the cities of the plain, and all the kingdom of Sihon king of the Amorites, who reigned in Heshbon. Moses smote him along with the princes of Midian: Evi, Rekem, Zur, *_Hur_*, and Reba—chiefs of Sihon who dwelt in the country.
* `1Ki 4:8` And these are their names: the son of *_Hur_*, in the mountains of Ephraim;
* `1Ch 2:19` And when Azubah was dead, Caleb took to him Ephrath who bore to him *_Hur_*,
* `1Ch 2:20` And *_Hur_* begot Uri, and Uri begot Bezaleel.
* `1Ch 2:50` These were the sons of Caleb. The sons of *_Hur_*, the first-born of Ephratah: Shobal the father of Kirjath-jearim,
* `1Ch 4:1` The sons of Judah: Pharez, Hezron, Carmi, *_Hur_*, and Shobal.
* `1Ch 4:4` And Penuel the father of Gedor, and Ezer the father of Hushah. These are the sons of *_Hur_*, the first-born of Ephratah, the father of Beth-lehem.
* `2Ch 1:5` Moreover, the brazen altar that Bezaleel the son of Uri, the son of *_Hur_*, had made, he put before the tabernacle of the LORD. And Solomon and the congregation sought it out.
* `Neh 3:9` And next to them Rephaiah the son of *_Hur_*, the ruler of the half part of Jerusalem, repaired.

_16 verses containing HUR_

== HURAI

* `1Ch 11:32` *_Hurai_* of the brooks of Gaash, Abiel the Arbathite,

_1 verse containing HURAI_

== HURAM

* `1Ch 8:5` Gera, Shephuphan, and *_Huram_*.
* `2Ch 2:3` And Solomon sent to *_Huram_* the king of Tyre, saying, "As you dealt with David my father and sent him cedars to build him a house to dwell in it, even so deal with me.
* `2Ch 2:11` Then *_Huram_* the king of Tyre answered in writing, which he sent to Solomon, "Because the LORD has loved his people, he has made you king over them."
* `2Ch 2:12` *_Huram_* said moreover, "Blessed be the LORD God of Israel who made heaven and earth, who has given to David the king a wise son, endued with prudence and understanding, who may build a house for the LORD and a house for his kingdom.
* `2Ch 2:13` "And now I have sent a skillful man, endued with understanding, even *_Huram_* my chief workman,
* `2Ch 4:11` And *_Huram_* made the pots, the shovels, and the basins. And *_Huram_* finished the work that he was to make for king Solomon for the house of God,
* `2Ch 4:16` The pots also, the shovels, the flesh-hooks, and all their instruments, *_Huram_* his chief workman made for king Solomon for the house of the LORD of bright brass.
* `2Ch 8:2` That the cities which *_Huram_* had restored to Solomon, Solomon built them and caused the children of Israel to dwell there.
* `2Ch 8:18` And *_Huram_* sent to him by the hands of his servants ships and servants who had knowledge of the sea, and they went with the servants of Solomon to Ophir and took from there four hundred and fifty talents of gold and brought them to king Solomon.
* `2Ch 9:10` And also the servants of *_Huram_* and the servants of Solomon who brought gold from Ophir, brought algum trees and precious stones.
* `2Ch 9:21` For the king's ships went to Tarshish with the servants of *_Huram_*. Once every three years the ships of Tarshish came bringing gold, silver, ivory, apes, and peacocks.

_11 verses containing HURAM_

== HURI

* `1Ch 5:14` These are the children of Abihail the son of *_Huri_*, the son of Jaroah, the son of Gilead, the son of Michael, the son of Jeshishai, the son of Jahdo, the son of Buz.

_1 verse containing HURI_

== HURLED

* `1Sa 17:49` And David put his hand in his bag, took from there a stone, *_hurled_* it with his sling, and smote the Philistine in his forehead so that the stone sunk into his forehead and he fell upon his face to the earth.

_1 verse containing HURLED_

== HURLING

* `1Ch 12:2` They were armed with bows and could use both the right hand and the left in *_hurling_* stones and shooting arrows from a bow. They were Saul's kinsmen from Benjamin.

_1 verse containing HURLING_

== HURLS

* `Num 35:20` But if he thrusts him out of hatred, *_hurls_* something at him while lying in wait so that he dies,

_1 verse containing HURLS_

== HURT

* `Gen 26:29` That you will do us no *_hurt_*, as we have not touched you and as we have done to you nothing but good and have sent you away in peace. You are now the blessed of the LORD.'"
* `Gen 31:7` And your father has deceived me and changed my wages ten times, but God did not allow him to *_hurt_* me.
* `Gen 31:29` It is in the power of my hand to do you *_hurt_*, but the God of your father spoke to me last night, saying, 'Take heed that you do not speak to Jacob either good or bad.'
* `Exo 21:22` "If men contend and *_hurt_* a woman with child so that her fruit departs from her, and yet no mischief follows, he shall surely be punished according as the woman's husband will lay upon him. And he shall pay as the judges determine.
* `Exo 22:10` "If a man delivers to his neighbor a donkey, an ox, a sheep, or any beast to keep and it dies, is *_hurt_*, or is driven away, no man seeing it,
* `Exo 22:14` "And if a man borrows anything from his neighbor and it is *_hurt_* or dies, its owner not being with it, he shall surely make it good.
* `Num 16:15` And Moses was very angry and said to the LORD, "Do not respect their offering. I have not taken one donkey from them, neither have I *_hurt_* one of them."
* `Jsh 24:20` If you forsake the LORD and serve strange gods, then he will turn and do you *_hurt_* and consume you, after he has done you good."
* `1Sa 20:21` And behold, I will send a boy, saying, 'Go, find the arrows.' If I expressly say to the boy, 'Behold, the arrows are on this side of you, take them,' then come, for there is peace to you, and no *_hurt_*, as the LORD lives.
* `1Sa 24:9` And David said to Saul, "Why do you hear men's words, saying, 'Behold, David seeks your *_hurt_*?'
* `1Sa 25:7` And now I have heard that you have shearers. Now your shepherds who were with us, we did not *_hurt_* them, neither was there anything missing to them all the while they were in Carmel.
* `1Sa 25:15` But the men were very good to us, and we were not *_hurt_*, neither did we miss anything as long as we were conversant with them when we were in the fields.
* `2Sa 18:32` And the king said to Cushi, "Is the young man Absalom safe?" And Cushi answered, "May the enemies of my lord the king and all who rise against you to do you *_hurt_* be as that young man is."
* `2Ki 14:10` You have indeed smitten Edom, and your heart has lifted you up. Glory in this and stay at home. For why should you meddle to your *_hurt_* that you should fall, even you and Judah with you?"
* `2Ch 25:19` You say, 'Behold, you have smitten the Edomites,' and your heart lifts you up to boast. Now abide at home. Why should you meddle to your *_hurt_* so that you should fall, even you, and Judah with you?"
* `Ezr 4:22` Take heed now that you do not fail to do this. Why should damage grow to the *_hurt_* of the kings?"
* `Est 9:2` The Jews assembled in their cities throughout all the provinces of king Ahasuerus to lay hands on those who sought their *_hurt_*. And no man could withstand them, for the fear of them fell upon all people.
* `Job 35:8` Your wickedness may *_hurt_* a man like yourself, and your righteousness may profit a son of man.
* `Psa 15:4` In whose eyes a vile person is despised, but he honors those who fear the LORD; he who swears to his own *_hurt_* and does not change;
* `Psa 35:4` Let them be confounded and put to shame who seek after my soul. Let them be turned back and brought to shame who devise my *_hurt_*.
* `Psa 35:26` Let them be ashamed and confounded together who rejoice at my *_hurt_*. Let them be clothed with shame and dishonor who magnify themselves against me.
* `Psa 38:12` Those who also seek after my life lay snares for me. And those who seek my *_hurt_* speak mischievous things and plot deceits all the day long.
* `Psa 41:7` All who hate me whisper together against me. They devise my *_hurt_* against me.
* `Psa 70:2` Let them be ashamed and confounded who seek after my soul. Let them be turned backward and put to shame who desire my *_hurt_*.
* `Psa 71:13` Let them be confounded and consumed who are adversaries to my soul. Let them be covered with reproach and dishonor who seek my *_hurt_*.
* `Psa 71:24` My tongue shall also talk of your righteousness all the day long. For they are confounded, for they are brought to shame who seek my *_hurt_*.
* `Psa 105:18` They *_hurt_* his feet with fetters, and he was laid in iron.
* `Ecc 5:13` There is a grievous evil which I have seen under the sun, namely, riches kept for their owner to his *_hurt_*.
* `Ecc 8:9` All this I have seen, applying my heart to every work that is done under the sun. There is a time in which one man rules over another to his own *_hurt_*.
* `Ecc 10:9` Whoever removes stones shall be *_hurt_* by them, and he who cleaves wood shall be endangered by it.
* `Isa 11:9` They shall not *_hurt_* nor destroy in all my holy mountain, for the earth shall be full of the knowledge of the LORD, as the waters cover the sea.
* `Isa 27:3` I, the LORD, keep it. I will water it every moment. Lest any *_hurt_* it, I will keep it night and day.
* `Isa 65:25` The wolf and the lamb shall feed together, and the lion shall eat straw like the bull, and dust shall be the serpents' food. They shall neither *_hurt_* nor destroy in all my holy mountain," says the LORD.
* `Jer 6:14` They have also healed the *_hurt_* of the daughter of my people slightly, saying, 'Peace, peace,' when there is no peace.
* `Jer 7:6` If you do not oppress the stranger, the fatherless, and the widow, and do not shed innocent blood in this place, neither walk after other gods to your *_hurt_*,
* `Jer 8:11` For they have healed the *_hurt_* of the daughter of my people slightly, saying, 'Peace, peace,' when there is no peace.
* `Jer 8:21` For the *_hurt_* of the daughter of my people am I *_hurt_*. I am black. Astonishment has taken hold upon me.
* `Jer 10:19` Woe is me for my *_hurt_*! My wound is grievous, but I said, "Truly this is a grief, and I must bear it."
* `Jer 24:9` And I will make them a horror among all the kingdoms of the earth for their *_hurt_*, to be a reproach and a proverb, a taunt and a curse, in all places where I shall drive them.
* `Jer 25:6` And do not go after other gods to serve them and to worship them, and do not provoke me to anger with the works of your hands, and I will do you no *_hurt_*.'
* `Jer 25:7` Yet you have not listened to me," says the LORD, "so that you might provoke me to anger with the works of your hands to your own *_hurt_*.
* `Jer 38:4` Therefore, the princes said to the king, "We implore you, let this man be put to death, for thus he weakens the hands of the men of war who remain in this city and the hands of all the people in speaking such words to them. For this man does not seek the welfare of this people, but the *_hurt_*."
* `Dan 3:25` He answered and said, "Behold, I see four men loose, walking in the midst of the fire, and they are not *_hurt_*. And the form of the fourth is like the son of God."
* `Dan 6:22` My God has sent his angel and has shut the lions' mouths, and they have not *_hurt_* me, because before him innocence was found in me. And also before you, O king, I have done no *_hurt_*."
* `Dan 6:23` Then the king was exceedingly glad for him and commanded that they should take Daniel out of the den. So Daniel was taken out of the den, and no manner of *_hurt_* was found upon him, because he believed in his God.
* `Mrk 16:18` They shall take up serpents, if they drink any deadly thing it shall not *_hurt_* them, and they shall lay hands on the sick and they shall recover."
* `Luk 4:35` And Jesus rebuked him, saying, "Hold your peace and come out of him." And when the demon had thrown him in the midst, he came out of him and did not *_hurt_* him.
* `Luk 10:19` Behold, I give to you power to tread on serpents and scorpions and over all the power of the enemy. And nothing shall by any means *_hurt_* you.
* `Act 18:10` For I am with you, and no man shall lay hands on you to *_hurt_* you, for I have many people in this city."
* `Act 27:10` And said to them, "Sirs, I perceive that this voyage will be with *_hurt_* and much damage, not only of the cargo and the ship, but also of our lives."
* `Rev 2:11` He who has an ear, let him hear what the Spirit says to the churches. He who overcomes shall not be *_hurt_* by the second death."'
* `Rev 6:6` And I heard a voice in the midst of the four living beings say, "A measure of wheat for a denarius, and three measures of barley for a denarius, and see that you do not *_hurt_* the oil and the wine."
* `Rev 7:2` And I saw another angel ascending from the east having the seal of the living God. And he cried with a loud voice to the four angels, to whom it was given to *_hurt_* the earth and the sea,
* `Rev 7:3` Saying, "Do not *_hurt_* the earth, neither the sea, nor the trees, until we have sealed the servants of our God in their foreheads."
* `Rev 9:4` And it was said to them that they should not *_hurt_* the grass of the earth, neither any green thing, neither any tree, but only those men who do not have the seal of God in their foreheads.
* `Rev 9:10` And they had tails like scorpions, and there were stings in their tails. And their power was to *_hurt_* men five months.
* `Rev 11:5` And if any man will *_hurt_* them, fire proceeds out of their mouth and devours their enemies. And if any man will *_hurt_* them, he must in this manner be killed.

_57 verses containing HURT_

== HURTFUL

* `Ezr 4:15` So that search may be made in the book of the records of your fathers. Thus you will find in the book of the records and know that this city is a rebellious city and *_hurtful_* to kings and provinces, and that they have moved sedition within the same of old time, for which cause this city was destroyed.
* `Psa 144:10` It is he who gives salvation to kings, who delivers David his servant from the *_hurtful_* sword.
* `1Ti 6:9` But those who wish to be rich fall into temptation, a snare, and into many foolish and *_hurtful_* lusts which drown men in destruction and perdition.

_3 verses containing HURTFUL_

== HURTING

* `Gen 4:23` And Lamech said to his wives, "Adah and Zillah, hear my voice. Wives of Lamech, listen to my speech. For I have slain a man for wounding me, even a young man for *_hurting_* me.
* `1Sa 25:34` For indeed, as the LORD God of Israel lives, who has kept me back from *_hurting_* you, unless you had hastened and come to meet me, surely there had not been left to Nabal by the morning light any male person."

_2 verses containing HURTING_

== HURTS

* `Exo 21:35` "And if one man's ox *_hurts_* another's so that he dies, then they shall sell the live ox and divide its money. And they shall also divide the dead ox.

_1 verse containing HURTS_

== HUSBAND

* `Gen 3:6` And when the woman saw that the tree was good for food and that it was pleasant to the eyes and a tree to be desired to make one wise, she took some of its fruit and ate, and gave some also to her *_husband_* with her, and he ate.
* `Gen 3:16` To the woman he said, "I will greatly multiply your sorrow and your conception. In sorrow you shall bring forth children. And your desire shall be for your *_husband_*, and he shall rule over you."
* `Gen 16:3` And Sarai, Abram's wife, took Hagar her servant, the Egyptian, after Abram had dwelt ten years in the land of Canaan, and gave her to her *_husband_* Abram to be his wife.
* `Gen 29:32` And Leah conceived and bore a son, and she called his name Reuben, for she said, "Surely the LORD has looked upon my affliction; therefore, now my *_husband_* will love me."
* `Gen 29:34` And she conceived again and bore a son, and said, "Now this time my *_husband_* will adhere to me because I have borne him three sons." Therefore, his name was called Levi.
* `Gen 30:15` And she said to her, "Is it a small matter that you have taken my *_husband_*? And would you take away my son's mandrakes also?" And Rachel said, "Therefore, he shall lie with you tonight for your son's mandrakes."
* `Gen 30:18` And Leah said, "God has given me my hire because I have given my servant to my *_husband_*." And she called his name Issachar.
* `Gen 30:20` And Leah said, "God has endowed me with a good dower. Now my *_husband_* will dwell with me because I have borne him six sons." And she called his name Zebulun.
* `Exo 4:25` Then Zipporah took a sharp stone, cut off the foreskin of her son, and cast it at his feet, and said, "Surely a bloody *_husband_* you are to me."
* `Exo 4:26` So he let him go. Then she said, "A bloody *_husband_* you are because of the circumcision."
* `Exo 21:22` "If men contend and hurt a woman with child so that her fruit departs from her, and yet no mischief follows, he shall surely be punished according as the woman's *_husband_* will lay upon him. And he shall pay as the judges determine.
* `Lev 19:20` 'And whoever lies carnally with a woman who is a servant betrothed to a *_husband_* and not at all redeemed, nor freedom given to her, she shall be scourged. They shall not be put to death because she was not free.
* `Lev 21:3` And for his sister, a virgin, who is near to him and has had no *_husband_*—for her he may be defiled.
* `Lev 21:7` They shall not take a wife who is a lewd woman, or profane, neither shall they take a woman put away from her *_husband_*, for he is holy to his God.
* `Num 5:13` And a man lies with her carnally, and it is hid from the eyes of her *_husband_* and is kept close, and she is defiled and there is no witness against her, neither is she taken with the manner,
* `Num 5:19` And the priest shall charge her by an oath and say to the woman, "If no man has lain with you and if you have not gone aside to uncleanness with another instead of your *_husband_*, be free from this bitter water that causes the curse.
* `Num 5:20` But if you have gone aside to another instead of your *_husband_*, and if you are defiled and some man has lain with you besides your *_husband_*"—
* `Num 5:27` And when he has made her to drink the water, it shall come to pass, that if she is defiled and has done trespass against her *_husband_*, that the water that causes the curse shall enter into her and become bitter, and her belly shall swell and her thigh shall perish, and the woman shall be a curse among her people.
* `Num 5:29` 'This is the law of jealousies when a wife goes astray to another instead of her *_husband_* and is defiled,
* `Num 30:6` "And if she had a *_husband_* when she vowed or uttered anything from her lips with which she bound her soul,
* `Num 30:7` And her *_husband_* heard it and held his peace at her in the day that he heard it, then her vows shall stand and her bonds with which she bound her soul shall stand.
* `Num 30:8` But if her *_husband_* disallowed her on the day that he heard it, then he shall make her vow which she vowed and that which she uttered with her lips with which she bound her soul of no effect. And the LORD shall forgive her.
* `Num 30:10` And if she vowed in her *_husband_*'s house or bound her soul by a bond with an oath,
* `Num 30:11` And her *_husband_* heard it and held his peace at her and did not disallow her, then all her vows shall stand and every bond with which she bound her soul shall stand.
* `Num 30:12` But if her *_husband_* has utterly made them void on the day he heard them, then whatever proceeded out of her lips concerning her vows or concerning the bond of her soul shall not stand. Her *_husband_* has made them void, and the LORD shall forgive her.
* `Num 30:13` Every vow and every binding oath to afflict the soul, her *_husband_* may establish it or her *_husband_* may make it void.
* `Num 30:14` But if her *_husband_* altogether holds his peace at her from day to day, then he establishes all her vows or all her bonds which are upon her. He confirms them because he held his peace at her in the day that he heard them.
* `Deu 21:13` And she shall take off from her the clothing of her captivity and shall remain in your house and bewail her father and her mother a full month. And after that, you shall go in to her and be her *_husband_*, and she shall be your wife.
* `Deu 22:22` "If a man is found lying with a woman married to a *_husband_*, then they shall die, both the man who lay with the woman and the woman. Thus you shall remove evil from Israel.
* `Deu 22:23` "If a young woman who is a virgin is betrothed to a *_husband_*, and a man finds her in the city and lies with her,
* `Deu 24:3` And if the latter *_husband_* hates her and writes her a bill of divorcement, gives it in her hand, and sends her out of his house, or if the latter *_husband_* dies, who took her to be his wife,
* `Deu 24:4` Her former *_husband_* who sent her away may not take her again to be his wife, since she is defiled, for that is abomination before the LORD. And you shall not cause the land to sin, which the LORD your God gives you for an inheritance.
* `Deu 25:5` "If brothers dwell together, and one of them dies and has no child, the wife of the dead shall not marry outside to a stranger. Her *_husband_*'s brother shall go in to her and take her for himself for a wife and perform the duty of a *_husband_*'s brother to her.
* `Deu 25:7` And if the man does not want to take his brother's wife, then let his brother's wife go up to the gate to the elders, and say, 'My *_husband_*'s brother refuses to raise up for his brother a name in Israel. He will not perform the duty of my *_husband_*'s brother.'
* `Deu 25:11` "When men strive together with one another, and the wife of one draws near to deliver her *_husband_* from the hand of him who smites him and puts forth her hand and takes him by the secrets,
* `Deu 28:56` The tender and delicate woman among you, who would not venture to set the sole of her foot upon the ground for delicateness and tenderness, her eye shall be evil toward the *_husband_* of her bosom, toward her son, toward her daughter,
* `Jdg 13:6` Then the woman came and told her *_husband_*, saying, "A man of God came to me, and his countenance was like the countenance of an angel of God, very awesome. But I did not ask him where he was from, neither did he tell me his name.
* `Jdg 13:9` And God listened to the voice of Manoah, and the angel of God came again to the woman as she sat in the field. But Manoah her *_husband_* was not with her.
* `Jdg 13:10` And the woman made haste and ran and declared to her *_husband_*, and said to him, "Behold, the man who came to me the other day has appeared to me."
* `Jdg 14:15` And it came to pass on the seventh day, that they said to Samson's wife, "Entice your *_husband_* so that he may declare to us the riddle, lest we burn you and your father's house with fire. Have you called us to take what we possess? Is it not so?"
* `Jdg 19:3` And her *_husband_* arose and went after her to speak kindly to her and to bring her back, having his servant with him and a couple of donkeys. And she brought him into her father's house. And when the father of the young woman saw him, he rejoiced to meet him.
* `Jdg 20:4` And the Levite, the *_husband_* of the woman who was slain, answered and said, "I came into Gibeah that belongs to Benjamin—I and my concubine—to lodge.
* `Rth 1:3` And Elimelech, Naomi's *_husband_*, died, and she was left, she and her two sons.
* `Rth 1:5` And Mahlon and Chilion both died also, and the woman was left by her two sons and her *_husband_*.
* `Rth 1:9` May the LORD grant you that you may find rest, each of you in the house of her *_husband_*." Then she kissed them, and they lifted up their voice and wept.
* `Rth 1:12` Turn back, my daughters, go your way, for I am too old to have a *_husband_*. If I should say, 'I have hope,' if I should have a *_husband_* also tonight and should also bear sons,
* `Rth 2:1` And Naomi had a kinsman of her *_husband_*'s, a mighty man of wealth, of the family of Elimelech, and his name was Boaz.
* `Rth 2:11` And Boaz answered and said to her, "It has fully been shown to me all that you have done to your mother-in-law since the death of your *_husband_*, and how you have left your father, your mother, and the land of your nativity and have come to a people which you did not know before.
* `1Sa 1:8` Then Elkanah her *_husband_* said to her, "Hannah, why do you weep? And why do you not eat? And why is your heart grieved? Am I not better to you than ten sons?"
* `1Sa 1:22` But Hannah did not go up, for she said to her *_husband_*, "I will not go up until the child is weaned, and then I will bring him so that he may appear before the LORD and abide there forever."
* `1Sa 1:23` And Elkanah her *_husband_* said to her, "Do what seems good to you. Stay until you have weaned him. Only may the LORD establish his word." So the woman stayed and nursed her son until she weaned him.
* `1Sa 2:19` Moreover, his mother made him a little coat and brought it to him from year to year when she came up with her *_husband_* to offer the yearly sacrifice.
* `1Sa 4:19` And his daughter-in-law, the wife of Phinehas, was with child and about to deliver. And when she heard the tidings that the ark of God was taken and that her father-in-law and her *_husband_* were dead, she bowed herself and travailed, for her pains came upon her.
* `1Sa 4:21` And she named the child Ichabod, saying, "The glory has departed from Israel"—because the ark of God was taken and because of her father-in-law and her *_husband_*.
* `1Sa 25:19` And she said to her servants, "Go on before me. Behold, I am coming after you." But she did not tell her *_husband_* Nabal.
* `2Sa 3:15` And Ish-bosheth sent and took her from her *_husband_*, even from Phaltiel the son of Laish.
* `2Sa 3:16` And her *_husband_* went with her, weeping behind her to Bahurim. Then Abner said to him, "Go, return." And he returned.
* `2Sa 11:26` And when the wife of Uriah heard that Uriah her *_husband_* was dead, she mourned for her *_husband_*.
* `2Sa 14:5` And the king said to her, "What ails you?" And she answered, "I am indeed a widow woman, and my *_husband_* is dead.
* `2Sa 14:7` And behold, the whole family has risen against your servant and they said, 'Deliver him who smote his brother so that we may kill him for the life of his brother whom he slew. And we will destroy the heir also.' And so they will quench my coal which is left and will not leave to my *_husband_* neither name nor remainder upon the earth."
* `2Ki 4:1` Now there cried a certain woman of the wives of the sons of the prophets to Elisha, saying, "Your servant my *_husband_* is dead. And you know that your servant feared the LORD. And the creditor has come to take for himself my two sons to be slaves."
* `2Ki 4:9` And she said to her *_husband_*, "Behold now, I perceive that this is a holy man of God who passes by us continually.
* `2Ki 4:14` And he said, "What then is to be done for her?" And Gehazi answered, "Truly she has no child, and her *_husband_* is old."
* `2Ki 4:22` And she called to her *_husband_* and said, "Send me, I pray you, one of the young men and one of the donkeys so that I may run to the man of God and come back."
* `2Ki 4:26` Now run, I pray you, to meet her, and say to her, 'Is it well with you? Is it well with your *_husband_*? Is it well with the child?'" And she answered, "It is well."
* `Pro 7:19` For the *_husband_* is not at home. He has gone on a long journey.
* `Pro 12:4` A virtuous woman is a crown to her *_husband_*, but she who makes him ashamed is like rottenness in his bones.
* `Pro 31:11` [BET] The heart of her *_husband_* safely trusts in her, and he shall have no lack of gain.
* `Pro 31:23` [NUN] Her *_husband_* is known in the gates when he sits among the elders of the land.
* `Pro 31:28` [QOF] Her children rise up and call her blessed, her *_husband_* also, and he praises her:
* `Isa 54:5` For your maker is your *_husband_*. The LORD of hosts is his name. And your Redeemer is the Holy One of Israel. He shall be called The God of the Whole Earth.
* `Jer 3:20` Surely as a wife treacherously departs from her *_husband_*, so you have dealt treacherously with me, O house of Israel," says the LORD.
* `Jer 6:11` Therefore, I am full of the fury of the LORD. I am weary with holding in. "I will pour it out upon the children abroad and upon the assembly of young men together. For even the *_husband_* with the wife shall be taken, the aged with him who is full of days.
* `Jer 31:32` But not according to the covenant that I made with their fathers in the day that I took them by the hand to bring them out of the land of Egypt, my covenant which they broke, although I was a *_husband_* to them," says the LORD.
* `Ezk 16:32` You are a wife who commits adultery, who takes strangers instead of her *_husband_*!
* `Ezk 16:45` You are your mother's daughter, who loathes her *_husband_* and her children, and you are the sister of your sisters, who loathed their husbands and their children. Your mother was a Hittite and your father an Amorite.
* `Ezk 44:25` And they shall not come near to a dead person to defile themselves. But for father, for mother, for son, for daughter, for brother, or for sister who has had no *_husband_*, they may defile themselves.
* `Hos 2:2` Plead with your mother. Plead, for she is not my wife, neither am I her *_husband_*. Let her therefore put away her prostitutions out of her sight and her adulteries from between her breasts,
* `Hos 2:7` And she shall follow after her lovers, but she shall not overtake them, and she shall seek them, but shall not find them. Then she shall say, 'I will go and return to my first *_husband_*, for then it was better with me than now.'
* `Joe 1:8` Lament like a virgin girded with sackcloth for the *_husband_* of her youth.
* `Mth 1:16` And Jacob begot Joseph the *_husband_* of Mary, by whom Jesus was born, who is called Christ.
* `Mth 1:19` Then Joseph her *_husband_*, being a just man and not willing to make her a public example, purposed to put her away privately.
* `Mrk 10:12` And if a woman puts away her *_husband_* and is married to another, she commits adultery."
* `Luk 2:36` And there was a prophetess, Anna, the daughter of Phanuel, of the tribe of Asher. She was of a great age and had lived with a *_husband_* seven years from her virginity,
* `Luk 16:18` "Whoever puts away his wife and marries another commits adultery, and whoever marries her who is put away from her *_husband_* commits adultery.
* `Jhn 4:16` Jesus says to her, "Go, call your *_husband_* and come here."
* `Jhn 4:17` The woman answered and said, "I have no *_husband_*." Jesus said to her, "You have rightly said, 'I have no *_husband_*,'
* `Jhn 4:18` For you have had five husbands, and he whom you now have is not your *_husband_*. In that you have spoken truth."
* `Act 5:9` Then Peter said to her, "How is it that you have agreed together to test the Spirit of the Lord? Behold the feet of those who have buried your *_husband_* are at the door and shall carry you out."
* `Act 5:10` Then she fell down immediately at his feet and expired. And the young men came in and found her dead, and carrying her forth, buried her by her *_husband_*.
* `Rom 7:2` For the woman who has a *_husband_* is bound by the law to her *_husband_* so long as he lives. But if the *_husband_* is dead, she is released from the law of her *_husband_*.
* `Rom 7:3` So then, if while her *_husband_* lives she is married to another man, she shall be called an adulteress. But if her *_husband_* is dead, she is free from that law so that she is not an adulteress if she is married to another man.
* `1Co 7:2` Nevertheless, to avoid lewdness, let every man have his own wife, and let every woman have her own *_husband_*.
* `1Co 7:3` Let the *_husband_* render to the wife due benevolence, and likewise also the wife to the *_husband_*.
* `1Co 7:4` The wife does not have power over her own body, but the *_husband_* does, and likewise also, the *_husband_* does not have power over his own body, but the wife does.
* `1Co 7:10` And to the married I command, yet not I, but the Lord, do not let the wife depart from her *_husband_*.
* `1Co 7:11` But if she departs, let her remain unmarried or be reconciled to her *_husband_*, and do not let the *_husband_* put away his wife.
* `1Co 7:13` And if a woman has a *_husband_* who does not believe and he is pleased to dwell with her, let her not leave him.
* `1Co 7:14` For the unbelieving *_husband_* is sanctified by the wife and the unbelieving wife is sanctified by the *_husband_*. Otherwise, your children would be unclean, but now they are holy.
* `1Co 7:16` For how do you know, O wife, whether you shall save your *_husband_*? Or how do you know, O man, whether you shall save your wife?
* `1Co 7:34` There is also a difference between a wife and a virgin. The unmarried woman is anxious for the things of the Lord so that she may be holy, both in body and in spirit. But she who is married is anxious for the things of the world, how she may please her *_husband_*.
* `1Co 7:39` The wife is bound by the law as long as her *_husband_* lives. But if her *_husband_* is dead, she is at liberty to be married to whom she wishes, only in the Lord.
* `2Co 11:2` For I am jealous over you with godly jealousy. For I have espoused you to one *_husband_* so that I may present you as a chaste virgin to Christ.
* `Gal 4:27` For it is written, "Rejoice, you barren who do not bear. Break forth and cry, you who do not travail. For the desolate has many more children than she who has a *_husband_*."
* `Eph 5:23` For the *_husband_* is the head of the wife, even as Christ is the head of the church, and he is the Savior of the body.
* `Eph 5:33` Nevertheless, let each of you in particular thus love his wife even as himself, and the wife see that she reverences her *_husband_*.
* `1Ti 3:2` An overseer then must be blameless, the *_husband_* of one wife, vigilant, sober, of good behavior, given to hospitality, apt to teach,
* `Tit 1:6` If anyone is blameless, the *_husband_* of one wife, having faithful children, not accused of riot, or disorderly.
* `Rev 21:2` And I, John, saw the holy city, new Jerusalem, coming down from God out of heaven, prepared as a bride adorned for her *_husband_*.

_109 verses containing HUSBAND_

== HUSBANDS

* `Rth 1:11` And Naomi said, "Turn back, my daughters. Why will you go with me? Shall I bear more sons so that they may be your *_husbands_*?
* `Rth 1:13` Would you wait for them until they were grown? Would you forbear from having *_husbands_* for them? No, my daughters, for it grieves me much for your sakes that the hand of the LORD has gone out against me."
* `Est 1:17` For this deed of the queen will come abroad to all women to make their *_husbands_* contemptible in their eyes when they say, 'King Ahasuerus commanded Vashti the queen to be brought in before him, but she did not come.'
* `Est 1:20` And when the king's decree which he shall make is published throughout all his empire (for it is great), all the wives will give to their *_husbands_* honor, both to great and small."
* `Jer 29:6` Take wives and beget sons and daughters. Take wives for your sons and give your daughters to *_husbands_* so that they may bear sons and daughters. Multiply there and do not be diminished.
* `Ezk 16:45` You are your mother's daughter, who loathes her husband and her children, and you are the sister of your sisters, who loathed their *_husbands_* and their children. Your mother was a Hittite and your father an Amorite.
* `Jhn 4:18` For you have had five *_husbands_*, and he whom you now have is not your husband. In that you have spoken truth."
* `1Co 14:35` And if they will learn anything, let them ask their *_husbands_* at home, for it is a shame for women to speak in the church.
* `Eph 5:22` Wives, submit yourselves to your own *_husbands_*, as to the Lord.
* `Eph 5:24` Therefore, as the church is subject to Christ, so let wives be to their own *_husbands_* in everything.
* `Eph 5:25` *_Husbands_*, love your wives, even as Christ also loved the church and gave himself for it,
* `Col 3:18` Wives, submit yourselves to your own *_husbands_*, as it is fit in the Lord.
* `Col 3:19` *_Husbands_*, love your wives and do not be bitter against them.
* `1Ti 3:12` Let the deacons be the *_husbands_* of one wife, ruling their children and their own houses well.
* `Tit 2:4` So that they may teach the young women to be sober, to love their *_husbands_*, to love their children,
* `Tit 2:5` To be discreet, chaste, keepers of the home, good, obedient to their own *_husbands_*, so that the word of God may not be blasphemed.
* `1Pe 3:1` Likewise, wives, be in subjection to your own *_husbands_* so that if any do not obey the word, they also may, without the word, be won by the deportment of the wives
* `1Pe 3:5` For after this manner in former times the holy women who trusted in God also adorned themselves, being in subjection to their own *_husbands_*,
* `1Pe 3:7` Likewise, *_husbands_*, dwell with them according to knowledge, giving honor to the wife as to the weaker vessel and as being heirs together of the grace of life, so that your prayers are not hindered.

_19 verses containing HUSBANDS_

== HUSHAH

* `1Ch 4:4` And Penuel the father of Gedor, and Ezer the father of *_Hushah_*. These are the sons of Hur, the first-born of Ephratah, the father of Beth-lehem.

_1 verse containing HUSHAH_

== HUSHAI

* `2Sa 15:32` And it came to pass, that when David had come to the top of the mountain, where he worshiped God, behold, *_Hushai_* the Archite came to meet him with his coat rent and earth upon his head.
* `2Sa 15:37` So *_Hushai_*, David's friend, came into the city, and Absalom came into Jerusalem.
* `2Sa 16:16` And it came to pass, when *_Hushai_* the Archite, David's friend, had come to Absalom, that *_Hushai_* said to Absalom, "God save the king. God save the king."
* `2Sa 16:17` And Absalom said to *_Hushai_*, "Is this your kindness to your friend? Why did you not go with your friend?"
* `2Sa 16:18` And *_Hushai_* said to Absalom, "No, but whom the LORD, this people, and all the men of Israel choose, I will be his, and with him I will abide.
* `2Sa 17:5` Then Absalom said, "Now call *_Hushai_* the Archite also, and let us hear likewise what he says."
* `2Sa 17:6` And when *_Hushai_* had come to Absalom, Absalom spoke to him, saying, "Ahithophel has spoken after this manner. Shall we do after his saying? If not, you speak."
* `2Sa 17:7` And *_Hushai_* said to Absalom, "The counsel that Ahithophel has given is not good at this time."
* `2Sa 17:8` Then *_Hushai_* said, "You know your father and his men. They are mighty men and they are chafed in their minds like a bear robbed of her whelps in the field. And your father is a man of war and will not lodge with the people.
* `2Sa 17:14` And Absalom and all the men of Israel said, "The counsel of *_Hushai_* the Archite is better than the counsel of Ahithophel." For the LORD had appointed to defeat the good counsel of Ahithophel, to the intent that the LORD might bring evil upon Absalom.
* `2Sa 17:15` Then *_Hushai_* said to Zadok and to Abiathar the priests, "In this manner Ahithophel counseled Absalom and the elders of Israel, and in such a manner I have counseled.
* `1Ki 4:16` Baanah the son of *_Hushai_* was in Asher and in Aloth;
* `1Ch 27:33` And Ahithophel was the king's counselor, and *_Hushai_* the Archite was the king's companion,

_13 verses containing HUSHAI_

== HUSHAM

* `Gen 36:34` And Jobab died, and *_Husham_* of the land of Temani reigned in his stead.
* `Gen 36:35` And *_Husham_* died, and Hadad the son of Bedad (who smote Midian in the field of Moab) reigned in his stead, and the name of his city was Avith.
* `1Ch 1:45` And when Jobab was dead, *_Husham_* of the land of the Temanites reigned in his stead.
* `1Ch 1:46` And when *_Husham_* was dead, Hadad the son of Bedad, who smote Midian in the field of Moab, reigned in his stead, and the name of his city was Avith.

_4 verses containing HUSHAM_

== HUSHATHITE

* `2Sa 21:18` And it came to pass after this, that there was again a battle with the Philistines at Gob. Then Sibbechai the *_Hushathite_* slew Saph, who was among the sons of the giant.
* `2Sa 23:27` Abiezer the Anethothite, Mebunnai the *_Hushathite_*,
* `1Ch 11:29` Sibbecai the *_Hushathite_*, Ilai the Ahohite,
* `1Ch 20:4` And it came to pass after this, that there arose war at Gezer with the Philistines. At that time Sibbechai the *_Hushathite_* slew Sippai, who was of the children of the giant, and they were subdued.
* `1Ch 27:11` The eighth captain for the eighth month was Sibbecai the *_Hushathite_*, of the Zarhites. And in his course were twenty-four thousand.

_5 verses containing HUSHATHITE_

== HUSHIM

* `Gen 46:23` And the son of Dan: *_Hushim_*.
* `1Ch 7:12` Shuppim and Huppim were the children of Ir. And *_Hushim_* was the son of Aher.
* `1Ch 8:8` And Shaharaim begot children in the country of Moab after he had sent them away. *_Hushim_* and Baara were his wives.
* `1Ch 8:11` And by *_Hushim_* he begot Ahitub and Elpaal.

_4 verses containing HUSHIM_

== HUSK

* `Num 6:4` All the days of his separation he shall eat nothing that is made of the vine-tree, from the kernels even to the *_husk_*.
* `2Ki 4:42` And there came a man from Baal-shalisha and brought the man of God bread of the first fruits, twenty loaves of barley and full heads of grain in its *_husk_*. And he said, "Give it to the people so that they may eat."

_2 verses containing HUSK_

== HUSKS

* `Luk 15:16` And he would willingly have filled his belly with the *_husks_* that the swine ate, and no man gave to him.

_1 verse containing HUSKS_

== HUZ

* `Gen 22:21` *_Huz_* his first-born, Buz his brother, Kemuel the father of Aram,

_1 verse containing HUZ_

== HYMENEUS

* `1Ti 1:20` Of whom are *_Hymeneus_* and Alexander, whom I have delivered to Satan so that they may learn not to blaspheme.
* `2Ti 2:17` And their word will spread like gangrene, of whom are *_Hymeneus_* and Philetus,

_2 verses containing HYMENEUS_

== HYMN

* `Mth 26:30` And when they had sung a *_hymn_*, they went out to the Mount of Olives.
* `Mrk 14:26` And when they had sung a *_hymn_*, they went out to the Mount of Olives.

_2 verses containing HYMN_

== HYMNS

* `Eph 5:19` Speaking to yourselves in psalms, *_hymns_*, and spiritual songs, singing and making melody in your heart to the Lord,
* `Col 3:16` Let the word of Christ dwell in you richly in all wisdom, teaching and admonishing one another in psalms, *_hymns_*, and spiritual songs, singing with grace in your hearts to the Lord.

_2 verses containing HYMNS_

== HYPOCRISIES

* `1Pe 2:1` Therefore, laying aside all malice, all guile, *_hypocrisies_*, envies, and all evil-speakings,

_1 verse containing HYPOCRISIES_

== HYPOCRISY

* `Isa 32:6` For the vile person will speak villainy, and his heart will work iniquity, to practice *_hypocrisy_* and to utter error against the LORD, to make the soul of the hungry empty, and to cause the drink of the thirsty to fail.
* `Jer 23:15` Therefore, thus says the LORD of hosts concerning the prophets: "Behold, I will feed them with wormwood and make them drink the water of gall, for from the prophets of Jerusalem *_hypocrisy_* has gone forth into all the land."
* `Mth 23:28` Thus you also outwardly appear righteous to men, but within you are full of *_hypocrisy_* and iniquity.
* `Mrk 12:15` Shall we give, or shall we not give?" But he, knowing their *_hypocrisy_*, said to them, "Why do you test me? Bring me a denarius so that I may see it."
* `Luk 12:1` In the mean time, when there was gathered an innumerable multitude of people so that they trod upon one another, he began to say to his disciples first of all, "Beware of the leaven of the Pharisees, which is *_hypocrisy_*.
* `1Ti 4:2` Speaking lies in *_hypocrisy_*, having their conscience seared with a hot iron,
* `Jms 3:17` But the wisdom that is from above is first pure, then peaceable, gentle, easy to be entreated, full of mercy and good fruits, without partiality, and without *_hypocrisy_*.

_7 verses containing HYPOCRISY_

== HYPOCRITE

* `Job 8:13` Thus are the paths of all who forget God. And the *_hypocrite_*'s hope shall perish,
* `Job 13:16` He also shall be my salvation, for a *_hypocrite_* shall not come before him.
* `Job 17:8` Upright men shall be astonished at this, and the innocent shall stir up himself against the *_hypocrite_*.
* `Job 20:5` That the triumphing of the wicked is short, and the joy of the *_hypocrite_* is only for a moment?
* `Job 27:8` For what is the hope of the *_hypocrite_*, though he has gained, when God takes away his soul?
* `Job 34:30` This is so that the *_hypocrite_* may not reign, lest the people should be ensnared.
* `Pro 11:9` A *_hypocrite_* destroys his neighbor with his mouth, but through knowledge the just shall be delivered.
* `Isa 9:17` Therefore, the Lord will have no joy in their young men, neither will he have mercy on their fatherless and widows, for everyone is a *_hypocrite_* and an evil-doer, and every mouth speaks folly. For all this his anger is not turned away, but his hand is stretched out still.
* `Mth 7:5` You *_hypocrite_*, first cast the beam out of your own eye, and then you shall see clearly to cast the mote out of your brother's eye.
* `Luk 6:42` Or how can you say to your brother, 'Brother, let me pull out the mote that is in your eye,' when you yourself do not behold the beam that is in your own eye? You *_hypocrite_*, first cast out the beam out of your own eye, and then you shall see clearly to pull out the mote that is in your brother's eye.
* `Luk 13:15` The Lord then answered him, and said, "You *_hypocrite_*. Does each one of you on the sabbath not untie his ox or his donkey from the stall and lead him away to watering?

_11 verses containing HYPOCRITE_

== HYPOCRITES

* `Job 15:34` For the congregation of *_hypocrites_* shall be desolate, and fire shall consume the tabernacles of bribery.
* `Job 36:13` But the *_hypocrites_* in heart heap up wrath. They do not cry when he binds them.
* `Isa 33:14` The sinners in Zion are afraid. Fearfulness has surprised the *_hypocrites_*. "Who among us shall dwell with the devouring fire? Who among us shall dwell with everlasting burnings?"
* `Mth 6:2` "Therefore, when you do your acts of charity, do not sound a trumpet before you as the *_hypocrites_* do in the synagogues and in the streets so that they may have glory from men. Truly, I say to you, they have their reward.
* `Mth 6:5` "And when you pray, you shall not be as the *_hypocrites_* are. For they love to pray standing in the synagogues and on the corners of the streets so that they may be seen by men. Truly, I say to you, they have their reward.
* `Mth 6:16` "Moreover, when you fast, do not be of a sad countenance like the *_hypocrites_*, for they disfigure their faces so that they may appear to men to fast. Truly, I say to you, they have their reward.
* `Mth 15:7` You *_hypocrites_*, Isaiah well prophesied of you, saying,
* `Mth 16:3` And in the morning, 'It will be foul weather today, for the sky is red and lowering.' O *_hypocrites_*, you can discern the face of the sky, but can you not discern the signs of the times?
* `Mth 22:18` But Jesus perceived their wickedness, and said, "Why do you test me, you *_hypocrites_*?
* `Mth 23:13` "But woe to you, scribes and Pharisees! *_Hypocrites_*! For you shut up the kingdom of heaven against men. For you neither go in yourselves, neither do you allow those who are entering to go in.
* `Mth 23:14` Woe to you, scribes and Pharisees! *_Hypocrites_*! For you devour widows' houses and for a pretense make long prayer; therefore, you shall receive the greater condemnation.
* `Mth 23:15` "Woe to you, scribes and Pharisees! *_Hypocrites_*! For you compass sea and land to make one proselyte, and when he is made, you make him two-fold more the child of hell than yourselves.
* `Mth 23:23` "Woe to you, scribes and Pharisees! *_Hypocrites_*! For you pay tithe of mint, anise, and cumin, and have omitted the weightier matters of the law: judgment, mercy, and faith. These you ought to have done, and not to leave the others undone.
* `Mth 23:25` "Woe to you, scribes and Pharisees! *_Hypocrites_*! For you make the outside of the cup and of the platter clean, but inside they are full of extortion and excess.
* `Mth 23:27` "Woe to you, scribes and Pharisees! *_Hypocrites_*! For you are like whitened sepulchers, which indeed appear beautiful outwardly, but are within full of dead men's bones and of all uncleanness.
* `Mth 23:29` "Woe to you, scribes and Pharisees! *_Hypocrites_*! For you build the tombs of the prophets and garnish the sepulchers of the righteous,
* `Mth 24:51` And will cut him apart and appoint him his portion with the *_hypocrites_*. There shall be weeping and gnashing of teeth."
* `Mrk 7:6` He answered and said to them, "Isaiah has prophesied well concerning you *_hypocrites_*, as it is written, 'This people honors me with their lips, but their heart is far from me.
* `Luk 11:44` Woe to you, scribes and Pharisees, *_hypocrites_*! For you are as graves which are unseen, and the men who walk over them are not aware of them."
* `Luk 12:56` You *_hypocrites_*. You can discern the face of the sky and of the earth, but how is it that you do not discern this time?

_20 verses containing HYPOCRITES_

== HYPOCRITICAL

* `Psa 35:16` With *_hypocritical_* mockers in feasts, they gnashed upon me with their teeth.
* `Isa 10:6` I will send him against a *_hypocritical_* nation, and against the people of my wrath I will give him a charge, to take the loot, to take the plunder, and to tread them down like the mire of the streets.

_2 verses containing HYPOCRITICAL_

== HYSSOP

* `Exo 12:22` And you shall take a bunch of *_hyssop_*, dip it in the blood that is in the basin, and strike the lintel and the two side-posts with the blood that is in the basin. And none of you shall go out of the door of his house until the morning.
* `Lev 14:4` Then the priest shall command to take for him who is to be cleansed two birds alive and clean, cedar-wood, scarlet, and *_hyssop_*.
* `Lev 14:6` As for the living bird, he shall take it, the cedar-wood, the scarlet, and the *_hyssop_* and shall dip them and the living bird in the blood of the bird that was killed over the running water.
* `Lev 14:49` And he shall take to cleanse the house two birds, cedar-wood, scarlet, and *_hyssop_*.
* `Lev 14:51` And he shall take the cedar-wood, the *_hyssop_*, the scarlet, and the living bird and dip them in the blood of the slain bird and in the running water, and sprinkle the house seven times.
* `Lev 14:52` And he shall cleanse the house with the blood of the bird, with the running water, with the living bird, with the cedar-wood, with the *_hyssop_*, and with the scarlet.
* `Num 19:6` And the priest shall take cedar-wood, *_hyssop_*, and scarlet and cast it into the midst of the burning of the heifer.
* `Num 19:18` And a clean person shall take *_hyssop_*, dip it in the water, and sprinkle it upon the tent, upon all the vessels, upon the persons who were there, and upon him who touched a bone, someone slain, someone dead, or a grave.
* `1Ki 4:33` And he spoke of trees, from the cedar tree that is in Lebanon even to the *_hyssop_* that springs out of the wall. He also spoke of beasts, of birds, of creeping animals, and of fish.
* `Psa 51:7` Purge me with *_hyssop_*, and I shall be clean. Wash me, and I shall be whiter than snow.
* `Jhn 19:29` Now there was set a vessel full of vinegar. And they filled a sponge with vinegar, put it upon *_hyssop_*, and put it to his mouth.
* `Heb 9:19` For when Moses had spoken every precept to all the people according to the law, he took the blood of calves and of goats, with water, scarlet wool, and *_hyssop_*, and sprinkled both the book and all the people,

_12 verses containing HYSSOP_

