= DISDAINED - DIZAHAB
:toc:

== DISDAINED

* `1Sa 17:42` And when the Philistine looked around and saw David, he *_disdained_* him, for he was a youth, ruddy, and of a fair countenance.
* `Job 30:1` "But now those who are younger than I have me in derision, whose fathers I would have *_disdained_* to put with the dogs of my flock.

_2 verses containing DISDAINED_

== DISEASE

* `2Ki 1:2` And Ahaziah fell down through a lattice in his upper chamber that was in Samaria and was sick. And he sent messengers and said to them, "Go, inquire of Baal-zebub the god of Ekron to see if I shall recover from this *_disease_*."
* `2Ki 8:8` And the king said to Hazael, "Take a present in your hand, go meet the man of God, and inquire of the LORD by him, saying, 'Shall I recover from this *_disease_*?'"
* `2Ki 8:9` So Hazael went to meet him and took a present with him, even forty camels' burden of every good thing of Damascus, and came and stood before him and said, "Your son Ben-hadad king of Syria has sent me to you, saying, 'Shall I recover from this *_disease_*?'"
* `2Ki 13:14` Now Elisha had fallen sick with his *_disease_* of which he died. And Joash the king of Israel came down to him and wept over his face and said, "O my father, my father, the chariot of Israel and the horsemen thereof."
* `2Ch 16:12` And Asa in the thirty-ninth year of his reign was diseased in his feet until his *_disease_* was exceedingly severe. Yet in his *_disease_* he did not seek the LORD, but the physicians.
* `2Ch 21:15` And you shall have great sickness by *_disease_* of your bowels until your bowels fall out by reason of the sickness day by day.'"
* `2Ch 21:18` And after all this the LORD smote him in his bowels with an incurable *_disease_*.
* `Job 30:18` By the great force of my *_disease_* my garment is changed. It binds me around like the collar of my coat.
* `Psa 38:7` For my loins are filled with a loathsome *_disease_*, and there is no soundness in my flesh.
* `Psa 41:8` "An evil *_disease_*," they say, "cleaves fast to him. And now that he lies he shall rise no more."
* `Ecc 6:2` A man to whom God has given riches, wealth, and honor, so that he lacks nothing for his soul of all that he desires, yet God does not give him power to enjoy them, but a stranger enjoys them. This is vanity, and it is an evil *_disease_*.
* `Isa 38:1` In those days Hezekiah was sick with a mortal *_disease_*. And Isaiah the prophet the son of Amoz came to him and said to him, "Thus says the LORD: 'Set your house in order, for you shall die, and not live.'"
* `Mth 4:23` And Jesus went throughout all Galilee, teaching in their synagogues, preaching the gospel of the kingdom, and healing all manner of sickness and all manner of *_disease_* among the people.
* `Mth 9:35` And Jesus went throughout all the cities and villages, teaching in their synagogues, preaching the gospel of the kingdom, and healing every sickness and every *_disease_* among the people.
* `Mth 10:1` And when he had called his twelve disciples to him, he gave them power against unclean spirits to cast them out, and to heal all manner of sickness and all manner of *_disease_*.
* `Jhn 5:4` For an angel went down at a certain season into the pool and agitated the water. Then whoever stepped in first after the stirring of the water was cured of whatever *_disease_* he had.

_16 verses containing DISEASE_

== DISEASED

* `1Ki 15:23` The rest of all the acts of Asa, all his might, all that he did, and the cities which he built, are they not written in the book of the chronicles of the kings of Judah? Nevertheless, in the time of his old age he was *_diseased_* in his feet.
* `2Ch 16:12` And Asa in the thirty-ninth year of his reign was *_diseased_* in his feet until his disease was exceedingly severe. Yet in his disease he did not seek the LORD, but the physicians.
* `Ezk 34:4` The *_diseased_* you have not strengthened, neither have you healed that which was sick, neither have you bound up that which was broken, neither have you brought back that which was driven away, neither have you sought that which was lost, but with force and with cruelty you have ruled them.
* `Ezk 34:21` Because you have thrust with side and with shoulder and pushed all the *_diseased_* with your horns until you have scattered them abroad,
* `Mth 9:20` (And behold, a woman who was *_diseased_* with an issue of blood for twelve years came behind him and touched the hem of his garment.
* `Mth 14:35` And when the men of that place had knowledge of him, they sent out into all the surrounding country and brought to him all who were *_diseased_*,
* `Mrk 1:32` And at evening when the sun had set, they brought to him all who were *_diseased_* and those who were possessed with demons.
* `Jhn 6:2` And a great multitude followed him because they saw his miracles which he performed on those who were *_diseased_*.

_8 verses containing DISEASED_

== DISEASES

* `Exo 15:26` And said, "If you will diligently listen to the voice of the LORD your God, do that which is right in his sight, and give ear to his commandments and keep all his statutes, I will put none of these *_diseases_* upon you which I have brought upon the Egyptians, for I am the LORD who heals you."
* `Deu 7:15` And the LORD will take away from you all sickness, and will put none of the evil *_diseases_* of Egypt (which you know) upon you, but will lay them upon all those who hate you.
* `Deu 28:60` Moreover, he will bring upon you all the *_diseases_* of Egypt, of which you were afraid, and they shall cleave to you.
* `2Ch 21:19` And it came to pass, that in process of time, after the end of two years, his bowels fell out by reason of his sickness. Thus he died of severe *_diseases_*. And his people made no burning for him, like the burning of his fathers.
* `2Ch 24:25` And when they had departed from him (for they left him in great *_diseases_*), his own servants conspired against him for the blood of the sons of Jehoiada the priest and slew him on his bed, and he died. And they buried him in the city of David, but they did not bury him in the sepulchers of the kings.
* `Psa 103:3` It is he who forgives all your iniquities, who heals all your *_diseases_*,
* `Mth 4:24` And his fame spread throughout all Syria. And they brought to him all sick people who were taken with various *_diseases_* and torments, those who were possessed with demons, those who were lunatic, and those who were paralyzed, and he healed them.
* `Mrk 1:34` And he healed many who were sick with various *_diseases_* and cast out many demons. And he did not allow the demons to speak because they knew him.
* `Mrk 3:10` For he had healed many; therefore, as many as had *_diseases_* pressed upon him to touch him.
* `Luk 4:40` Now when the sun was setting, all those who had any sick with various *_diseases_* brought them to him. And he laid his hands on every one of them and healed them.
* `Luk 6:17` And he came down with them and stood in the plain, with the company of his disciples and a great multitude of people out of all Judea, Jerusalem, and from the sea coast of Tyre and Sidon, who came to hear him and to be healed of their *_diseases_*,
* `Luk 7:21` And in that same hour he cured many of infirmities, *_diseases_*, and evil spirits, and to many who were blind he gave sight.
* `Luk 9:1` Then he called his twelve disciples together and gave them power and authority over all demons and to cure *_diseases_*.
* `Act 19:12` So that handkerchiefs or aprons were brought from his body to the sick, and the *_diseases_* departed from them, and the evil spirits went out of them.
* `Act 28:9` So when this was done, others also who had *_diseases_* on the island came and were healed,

_15 verses containing DISEASES_

== DISFIGURE

* `Mth 6:16` "Moreover, when you fast, do not be of a sad countenance like the hypocrites, for they *_disfigure_* their faces so that they may appear to men to fast. Truly, I say to you, they have their reward.

_1 verse containing DISFIGURE_

== DISGRACE

* `Ezr 9:7` Since the days of our fathers we have been in a great trespass to this day. And for our iniquities we, our kings, and our priests have been delivered into the hand of the kings of the lands, to the sword, to captivity, to plundering, and to *_disgrace_*, as it is this day.
* `Psa 44:15` My *_disgrace_* is continually before me, and the shame of my face has covered me,
* `Isa 30:3` Therefore, the strength of Pharaoh shall be your shame, and refuge in the shadow of Egypt your *_disgrace_*.
* `Isa 45:16` They shall be ashamed and also confounded, all of them. They shall go in *_disgrace_* together who are makers of idols.
* `Isa 61:7` Instead of your shame you shall have double. Instead of *_disgrace_* they shall rejoice in their portion. Therefore, in their land they shall possess the double. Everlasting joy shall be to them.
* `Jer 3:25` We lie down in our shame, and our *_disgrace_* covers us, for we have sinned against the LORD our God—we and our fathers—from our youth even to this day. We have not obeyed the voice of the LORD our God."
* `Jer 14:21` Do not abhor us for your name's sake. Do not *_disgrace_* the throne of your glory. Remember, do not break your covenant with us.
* `Jer 20:11` But the LORD is with me like an awesome mighty one; therefore, my persecutors shall stumble and shall not prevail. They shall be greatly ashamed, for they shall not prosper. Their everlasting *_disgrace_* shall never be forgotten.
* `Dan 9:7` "O Lord, righteousness belongs to you, but to us, *_disgrace_*, as at this day, to the men of Judah, to the inhabitants of Jerusalem, and to all Israel, who are near and who are far off, through all the countries where you have driven them, because of their trespass that they have trespassed against you.
* `Dan 9:8` O Lord, to us belongs *_disgrace_*, to our kings, to our princes, and to our fathers, because we have sinned against you.

_10 verses containing DISGRACE_

== DISGUISE

* `1Ki 14:2` And Jeroboam said to his wife, "Arise, I pray you, *_disguise_* yourself so that you may not be known to be the wife of Jeroboam and go to Shiloh. Behold, there is Ahijah the prophet who told me that I should be king over this people.
* `1Ki 22:30` And the king of Israel said to Jehoshaphat, "I will *_disguise_* myself and enter into the battle, but you put on your robes." And the king of Israel disguised himself and went into the battle.
* `2Ch 18:29` And the king of Israel said to Jehoshaphat, "I will *_disguise_* myself and go to the battle, but put on your robes." So the king of Israel disguised himself, and they went to the battle.

_3 verses containing DISGUISE_

== DISGUISED

* `1Sa 28:8` And Saul *_disguised_* himself and put on other clothing, and he went, and two men with him, and they came to the woman by night. And he said, "I pray you, divine to me by the familiar spirit and bring up for me whom I shall name to you."
* `1Ki 20:38` So the prophet departed and waited for the king by the way and *_disguised_* himself with ashes upon his face.
* `1Ki 22:30` And the king of Israel said to Jehoshaphat, "I will disguise myself and enter into the battle, but you put on your robes." And the king of Israel *_disguised_* himself and went into the battle.
* `2Ch 18:29` And the king of Israel said to Jehoshaphat, "I will disguise myself and go to the battle, but put on your robes." So the king of Israel *_disguised_* himself, and they went to the battle.
* `2Ch 35:22` Nevertheless, Josiah would not turn his face from him, but *_disguised_* himself that he might fight with him, and did not listen to the words of Necho from the mouth of God and came to fight in the valley of Megiddo.

_5 verses containing DISGUISED_

== DISGUISES

* `Job 24:15` Also, the eye of the adulterer waits for the twilight, saying, 'No eye shall see me,' and *_disguises_* his face.

_1 verse containing DISGUISES_

== DISH

* `Jdg 5:25` He asked water, and she gave him milk. She brought forth butter in a lordly *_dish_*.
* `2Ki 21:13` And I will stretch over Jerusalem the line of Samaria and the plummet of the house of Ahab, and I will wipe Jerusalem as a man wipes a *_dish_*, wiping it and turning it upside down.
* `Mth 14:8` And she, being before instructed by her mother, said, "Give me here the head of John the Baptist in a *_dish_*."
* `Mth 14:11` And his head was brought in a *_dish_* and given to the girl. Then she brought it to her mother.
* `Mth 26:23` And he answered and said, "He who dips his hand with me in the *_dish_*, the same will betray me.
* `Mrk 6:25` And she came in immediately with haste to the king, and asked, saying, "I wish that you would give me at once the head of John the Baptist in a *_dish_*."
* `Mrk 6:28` And brought his head in a *_dish_* and gave it to the girl. And the girl gave it to her mother.
* `Mrk 14:20` And he answered and said to them, "It is one of the twelve who dips with me in the *_dish_*.

_8 verses containing DISH_

== DISHAN

* `Gen 36:21` Dishon, Ezer, and *_Dishan_*. These are the chiefs of the Horites, the children of Seir in the land of Edom.
* `Gen 36:28` The children of *_Dishan_* are these: Uz and Aran.
* `Gen 36:30` Chief Dishon, chief Ezer, chief *_Dishan_*. These are the chiefs, descendants of Hori, among their chiefs in the land of Seir.
* `1Ch 1:38` And the sons of Seir: Lotan, Shobal, Zibeon, Anah, Dishon, Ezar, and *_Dishan_*.
* `1Ch 1:42` The sons of Ezer: Bilhan, Zavan, and Jakan. The sons of *_Dishan_*: Uz and Aran.

_5 verses containing DISHAN_

== DISHES

* `Exo 25:29` And you shall make its *_dishes_*, its spoons, its covers, and its bowls to cover it with. Of pure gold you shall make them.
* `Exo 25:38` And its tongs and its snuff-*_dishes_* shall be of pure gold.
* `Exo 37:16` And he made the vessels which were upon the table of pure gold: its *_dishes_*, its spoons, its bowls, and its covers to cover with.
* `Exo 37:23` And he made its seven lamps, its snuffers, and its snuff-*_dishes_* of pure gold.
* `Num 4:7` And upon the table of show-bread they shall spread a cloth of blue and put on it the *_dishes_*, the spoons, the bowls, and covers to cover with. And the continual bread shall be upon it.
* `Num 4:9` And they shall take a cloth of blue and cover the candlestick for the light, its lamps, its tongs, its snuff-*_dishes_*, and all its oil vessels, with which they minister to it.

_6 verses containing DISHES_

== DISHON

* `Gen 36:21` *_Dishon_*, Ezer, and Dishan. These are the chiefs of the Horites, the children of Seir in the land of Edom.
* `Gen 36:25` And the children of Anah are these: *_Dishon_* and Aholibamah the daughter of Anah.
* `Gen 36:26` And these are the children of *_Dishon_*: Hemdan, Eshban, Ithran, and Cheran.
* `Gen 36:30` Chief *_Dishon_*, chief Ezer, chief Dishan. These are the chiefs, descendants of Hori, among their chiefs in the land of Seir.
* `1Ch 1:38` And the sons of Seir: Lotan, Shobal, Zibeon, Anah, *_Dishon_*, Ezar, and Dishan.
* `1Ch 1:41` The son of Anah: *_Dishon_*. And the sons of *_Dishon_*: Amram, Eshban, Ithran, and Cheran.

_6 verses containing DISHON_

== DISHONEST

* `Ezk 22:13` "And behold, I have smitten my hand at your *_dishonest_* gain which you have made, and at your blood which has been in the midst of you.
* `Ezk 22:27` Her princes in the midst of her are like wolves ravening the prey, shedding blood, and destroying souls to get *_dishonest_* gain.

_2 verses containing DISHONEST_

== DISHONESTY

* `2Co 4:2` But have renounced the hidden things of *_dishonesty_*, not walking in craftiness, nor handling the word of God deceitfully, but by manifestation of the truth, commending ourselves to every man's conscience in the sight of God.

_1 verse containing DISHONESTY_

== DISHONOR

* `Ezr 4:14` Now because we eat the salt of the palace, and it was not proper for us to see the king's *_dishonor_*, therefore we have sent and informed the king,
* `Psa 35:26` Let them be ashamed and confounded together who rejoice at my hurt. Let them be clothed with shame and *_dishonor_* who magnify themselves against me.
* `Psa 69:19` You have known my reproach, my shame, and my *_dishonor_*. My adversaries are all before you.
* `Psa 71:13` Let them be confounded and consumed who are adversaries to my soul. Let them be covered with reproach and *_dishonor_* who seek my hurt.
* `Pro 6:33` He shall get a wound and *_dishonor_*, and his reproach shall not be wiped away.
* `Jhn 8:49` Jesus answered, "I do not have a demon. But I honor my Father, and you *_dishonor_* me.
* `Rom 1:24` Therefore, God also gave them up to uncleanness through the lusts of their own hearts to *_dishonor_* their own bodies among themselves,
* `Rom 2:23` You who make your boast in the law, through breaking the law, do you *_dishonor_* God?
* `Rom 9:21` Does the potter not have power over the clay of the same lump to make one vessel to honor and another to *_dishonor_*?
* `1Co 15:43` It is sown in *_dishonor_*, it is raised in glory. It is sown in weakness, it is raised in power.
* `2Co 6:8` By honor and *_dishonor_*, by evil report and good report; as deceivers and true;
* `2Ti 2:20` But in a great house there are not only vessels of gold and of silver, but also of wood and of earth. Some are for honor and some for *_dishonor_*.

_12 verses containing DISHONOR_

== DISHONORED

* `Deu 25:3` Forty stripes he may give him, but no more. Otherwise, if he should continue and beat him with many more stripes than these, then your brother would be *_dishonored_* in your eyes.

_1 verse containing DISHONORED_

== DISHONORS

* `Mic 7:6` For the son *_dishonors_* the father, the daughter rises up against her mother, the daughter-in-law against her mother-in-law. A man's enemies are the men of his own house.
* `1Co 11:4` Every man praying or prophesying with his head covered *_dishonors_* his head.
* `1Co 11:5` But every woman who prays or prophesies with her head uncovered *_dishonors_* her head, for that is even one and the same as if she were shaved.

_3 verses containing DISHONORS_

== DISINHERIT

* `Num 14:12` I will smite them with the pestilence and *_disinherit_* them, and I will make of you a greater and mightier nation than they are."

_1 verse containing DISINHERIT_

== DISMAYED

* `Deu 31:8` And the LORD, it is he who goes before you. He will be with you. He will not fail you nor forsake you. Do not fear, neither be *_dismayed_*."
* `Jsh 1:9` Have I not commanded you? Be strong and of a good courage. Do not be afraid, neither be *_dismayed_*, for the LORD your God is with you wherever you go."
* `Jsh 8:1` And the LORD said to Joshua, "Do not fear, neither be *_dismayed_*. Take all the people of war with you, and arise, go up to Ai. Behold, I have given into your hand the king of Ai and his people, his city, and his land.
* `Jsh 10:25` And Joshua said to them, "Do not fear nor be *_dismayed_*, be strong and of good courage, for thus the LORD shall do to all your enemies against whom you fight."
* `1Sa 17:11` When Saul and all Israel heard those words of the Philistine, they were *_dismayed_* and greatly afraid.
* `2Ki 19:26` Therefore, their inhabitants were of small power, they were *_dismayed_* and confounded, they were like the grass of the field, like the green herb, like the grass on the house-tops, and like grain blasted before it is grown up.
* `1Ch 22:13` Then you shall prosper if you take heed to fulfill the statutes and judgments which the LORD charged Moses with concerning Israel. Be strong and of good courage. Do not dread, nor be *_dismayed_*.
* `1Ch 28:20` And David said to Solomon his son, "Be strong and of good courage, and do it. Do not fear, nor be *_dismayed_*, for the LORD God, even my God, will be with you. He will not fail you, nor forsake you, until you have finished all the work for the service of the house of the LORD.
* `2Ch 20:15` And he said, "Listen, all Judah, inhabitants of Jerusalem, and king Jehoshaphat, thus says the LORD to you: 'Do not be afraid nor *_dismayed_* by reason of this great multitude, for the battle is not yours, but God's.
* `2Ch 20:17` You shall not need to fight in this battle. Set yourselves, stand still, and see the salvation of the LORD with you, O Judah and Jerusalem. Do not fear, nor be *_dismayed_*. Tomorrow, go out against them, for the LORD will be with you.'"
* `2Ch 32:7` "Be strong and courageous, do not be afraid nor *_dismayed_* before the king of Assyria, nor before all the multitude who is with him, for there are more with us than with him.
* `Isa 21:3` Therefore, my loins are filled with pain. Pangs have taken hold upon me like the pangs of a woman who travails. I was bowed down when I heard it. I was *_dismayed_* when I saw it.
* `Isa 37:27` Therefore, their inhabitants were of small power. They were *_dismayed_* and confounded. They were like the grass of the field, like the green herb, like the grass on the house-tops, and like grain blasted before it is grown up.
* `Isa 41:10` Do not fear, for I am with you. Do not be *_dismayed_*, for I am your God. I will strengthen you and I will even help you. I will also uphold you with the right hand of my righteousness.
* `Isa 41:23` Show the things that are to come hereafter so that we may know that you are gods. Indeed, do good or do evil so that we may be *_dismayed_* and behold it together.
* `Jer 1:17` Therefore, gird up your loins, arise, and speak to them all that I command you. Do not be *_dismayed_* at their faces, lest I confound you before them.
* `Jer 8:9` The wise men are ashamed. They are *_dismayed_* and taken. Behold, they have rejected the word of the LORD. And what wisdom is in them?
* `Jer 10:2` Thus says the LORD: "Do not learn the way of the heathen, and do not be *_dismayed_* at the signs of heaven, for the heathen are *_dismayed_* at them.
* `Jer 17:18` Let them be confounded who persecute me, but do not let me be confounded. Let them be *_dismayed_*, but do not let me be *_dismayed_*. Bring upon them the day of evil and destroy them with double destruction.
* `Jer 23:4` And I will set shepherds over them who shall feed them. And they shall no longer fear nor be *_dismayed_*, neither shall they be lacking," says the LORD.
* `Jer 30:10` 'Therefore, do not fear, O my servant Jacob,' says the LORD, 'neither be *_dismayed_*, O Israel, for behold, I will save you from afar and your offspring from the land of their captivity, and Jacob shall return and be in rest and quiet, and no one shall make him afraid.
* `Jer 46:5` Why have I seen them *_dismayed_* and turned away back? And their mighty ones are beaten down, have fled apace, and do not look back, for fear was on all sides," says the LORD.
* `Jer 46:27` "But do not fear, O my servant Jacob, and do not be *_dismayed_*, O Israel, for behold, I will save you from afar and your offspring from the land of their captivity. And Jacob shall return and be in rest and at ease, and no one shall make him afraid.
* `Jer 48:1` [Against Moab.] Thus says the LORD of hosts, the God of Israel: "Woe to Nebo! For it is laid waste. Kiriathaim is confounded and taken. Misgab is confounded and *_dismayed_*.
* `Jer 49:37` For I will cause Elam to be *_dismayed_* before their enemies and before those who seek their life. And I will bring evil upon them, even my fierce anger," says the LORD, "and I will send the sword after them until I have consumed them.
* `Jer 50:36` A sword is upon the liars, and they shall be foolish. A sword is upon her mighty men, and they shall be *_dismayed_*.
* `Ezk 2:6` And you, son of man, do not be afraid of them, neither be afraid of their words, even though briers and thorns are with you and you dwell among scorpions. Do not be afraid of their words nor be *_dismayed_* at their looks, though they are a rebellious house.
* `Ezk 3:9` I have made your forehead like an adamant, harder than flint. Do not fear them, neither be *_dismayed_* at their looks, though they are a rebellious house."
* `Oba 1:9` And your mighty men, O Teman, shall be *_dismayed_*, to the end that everyone of the mountain of Esau may be cut off by slaughter.

_29 verses containing DISMAYED_

== DISMAYING

* `Jer 48:39` "They shall howl, saying, 'How it is broken down! How Moab has turned the back with shame!' So Moab shall be a derision and a *_dismaying_* to all who are around him."

_1 verse containing DISMAYING_

== DISMISS

* `2Ch 23:8` So the Levites and all Judah did according to all things that Jehoiada the priest had commanded, and each took his men who were to come in on the sabbath with those who were to go out on the sabbath, for Jehoiada the priest did not *_dismiss_* the courses.
* `Jer 34:14` "At the end of seven years each of you shall *_dismiss_* his brother, a Hebrew, who has been sold to you. And when he has served you six years, you shall let him go free from you." But your fathers did not listen to me or incline their ear.

_2 verses containing DISMISS_

== DISMISSED

* `Mrk 6:46` And when he had *_dismissed_* them, he departed to a mountain to pray.
* `Mrk 8:9` And those who had eaten were about four thousand. Then he *_dismissed_* them.
* `Act 4:23` And being *_dismissed_*, they went to their own company and reported all that the chief priests and elders had said to them.
* `Act 15:30` So when they were *_dismissed_*, they came to Antioch. And when they had convened the multitude, they delivered the epistle,
* `Act 15:33` And after they had spent some time there, they were *_dismissed_* in peace from the brothers to the apostles.
* `Act 19:41` And when he had said this, he *_dismissed_* the assembly.

_6 verses containing DISMISSED_

== DISOBEDIENCE

* `Rom 5:19` For as by one man's *_disobedience_* many were made sinners, so by the obedience of one many shall be made righteous.
* `2Co 10:6` And we are ready to avenge all *_disobedience_*, when your obedience is fulfilled.
* `Eph 2:2` In which in time past you walked according to the course of this world, according to the prince of the power of the air, the spirit who now works in the children of *_disobedience_*,
* `Eph 5:6` Let no man deceive you with vain words, for because of these things the wrath of God comes upon the children of *_disobedience_*.
* `Col 3:6` Because of these things, the wrath of God comes on the children of *_disobedience_*,
* `Heb 2:2` For if the word spoken by angels was steadfast and every transgression and *_disobedience_* received a just recompense of reward,

_6 verses containing DISOBEDIENCE_

== DISOBEDIENT

* `1Ki 13:26` And when the prophet who brought him back from the way heard about it, he said, "It is the man of God who was *_disobedient_* to the word of the LORD. Therefore, the LORD has delivered him to the lion which has torn him and slain him, according to the word of the LORD which he spoke to him."
* `Neh 9:26` Nevertheless, they were *_disobedient_* and rebelled against you, and they cast your law behind their backs and slew your prophets who testified against them to turn them to you, and they wrought great provocations.
* `Luk 1:17` And he shall go before him in the spirit and power of Elijah to 'turn the hearts of the fathers to the children' and the *_disobedient_* to the wisdom of the just, to make ready a people prepared for the Lord."
* `Act 26:19` "Upon which, O king Agrippa, I was not *_disobedient_* to the heavenly vision,
* `Rom 1:30` Backbiters, haters of God, despiteful, proud, boasters, inventors of evil things, *_disobedient_* to parents,
* `Rom 10:21` But to Israel he says, "All day long I have stretched forth my hands to a *_disobedient_* and gainsaying people."
* `1Ti 1:9` Knowing this, that the law is not made for a righteous man, but for the lawless and *_disobedient_*, for the ungodly and for sinners, for unholy and profane, for murderers of fathers and murderers of mothers, for man-slayers,
* `2Ti 3:2` For men will be lovers of their own selves, covetous, boasters, proud, blasphemers, *_disobedient_* to parents, unthankful, unholy,
* `Tit 1:16` They profess that they know God, but in works they deny him, being abominable, *_disobedient_*, and worthless for every good work.
* `Tit 3:3` For we ourselves were also sometimes foolish, *_disobedient_*, deceived, serving diverse lusts and pleasures, living in malice and envy, hateful, and hating one another.
* `1Pe 2:7` To you therefore who believe, he is precious, but to those who are *_disobedient_*, "The stone which the builders disallowed, the same is made the head of the corner,"
* `1Pe 2:8` And "a stone of stumbling, and a rock of offense," even to those who stumble at the word, being *_disobedient_*, to which they were also appointed.
* `1Pe 3:20` Who formerly were *_disobedient_* when the patience of God waited in the days of Noah while the ark was preparing, in which few, that is, eight souls, were saved by water.

_13 verses containing DISOBEDIENT_

== DISOBEYED

* `1Ki 13:21` And he cried to the man of God who came from Judah, saying, "Thus says the LORD: 'Because you have *_disobeyed_* the mouth of the LORD and have not kept the commandment which the LORD your God commanded you,

_1 verse containing DISOBEYED_

== DISORDERLY

* `Job 30:12` Upon my right hand the *_disorderly_* youth rise. They push away my feet and raise up against me the ways of their destruction.
* `1Th 5:14` Now we exhort you, brothers, warn those who are *_disorderly_*, comfort the feeble-minded, support the weak, and be patient toward all men.
* `2Th 3:6` Now we command you, brothers, in the name of our Lord Jesus Christ, that you withdraw yourselves from every brother who walks *_disorderly_* and not after the tradition which he received from us.
* `2Th 3:7` For you yourselves know how you ought to follow us. For we did not behave ourselves *_disorderly_* among you,
* `2Th 3:11` For we hear that there are some who walk among you *_disorderly_*, not working at all, but are busy-bodies.
* `Tit 1:6` If anyone is blameless, the husband of one wife, having faithful children, not accused of riot, or *_disorderly_*.
* `Tit 1:10` For there are many *_disorderly_* and vain talkers and deceivers, especially those of the circumcision.

_7 verses containing DISORDERLY_

== DISPATCH

* `Ezk 23:47` And the company shall stone them with stones and *_dispatch_* them with their swords. They shall slay their sons and their daughters and burn their houses with fire.

_1 verse containing DISPATCH_

== DISPENSATION

* `1Co 9:17` For if I do this thing willingly, I have a reward, but if against my will, a *_dispensation_* of the gospel is committed to me.
* `Eph 1:10` So that in the *_dispensation_* of the fullness of times he might collect in one all things in Christ, both which are in heaven and which are on earth, even in him;
* `Eph 3:2` If you have heard of the *_dispensation_* of the grace of God which is given to me on your account,
* `Col 1:25` Of which I am made a minister according to the *_dispensation_* of God which is given to me for you to fulfill the word of God,

_4 verses containing DISPENSATION_

== DISPERSE

* `1Sa 14:34` And Saul said, "*_Disperse_* yourselves among the people and say to them, 'Every man bring me here his ox and every man his sheep, and slay them here and eat, and do not sin against the LORD in eating with the blood.'" And all the people each brought his ox with him that night and slew them there.
* `Ezk 12:15` And they shall know that I am the LORD when I scatter them among the nations and *_disperse_* them in the countries.
* `Ezk 20:23` I lifted up my hand to them also in the wilderness so that I would scatter them among the heathen and *_disperse_* them through the countries.
* `Ezk 22:15` And I will scatter you among the heathen and *_disperse_* you in the countries, and I will consume your filthiness out of you.
* `Ezk 29:12` And I will make the land of Egypt desolate in the midst of the countries that are desolate, and her cities among the cities that are laid waste shall be desolate forty years. And I will scatter the Egyptians among the nations and *_disperse_* them through the countries."
* `Ezk 30:23` And I will scatter the Egyptians among the nations and *_disperse_* them through the countries.
* `Ezk 30:26` And I will scatter the Egyptians among the nations and *_disperse_* them among the countries. And they shall know that I am the LORD.'"

_7 verses containing DISPERSE_

== DISPERSED

* `Gen 10:18` The Arvadite, the Zemarite, and the Hamathite. And afterward, the families of the Canaanites were *_dispersed_*.
* `2Ch 11:23` And he dealt wisely and *_dispersed_* some of his children throughout all the countries of Judah and Benjamin to every fortified city, and he gave them provisions in abundance. And he desired many wives.
* `Est 3:8` And Haman said to king Ahasuerus, "There is a certain people scattered abroad and *_dispersed_* among the people in all the provinces of your kingdom. And their laws are diverse from all people, neither do they keep the king's laws. Therefore, it is not for the king's profit to allow them to remain.
* `Psa 112:9` He has *_dispersed_*. He has given to the poor. His righteousness endures forever. His horn shall be exalted with honor.
* `Pro 5:16` Let your fountains be *_dispersed_* abroad, and rivers of waters in the streets.
* `Isa 11:12` And he shall set up an ensign for the nations, and shall assemble the outcasts of Israel and gather the *_dispersed_* of Judah from the four corners of the earth.
* `Ezk 36:19` And I scattered them among the heathen, and they were *_dispersed_* through the countries. According to their way and according to their doings I judged them.
* `Zph 3:10` From beyond the rivers of Cush my suppliants, even the daughter of my *_dispersed_*, shall bring my offering.
* `Jhn 7:35` Then the Jews said among themselves, "Where will he go that we shall not find him? Will he go to the *_dispersed_* among the Gentiles and teach the Gentiles?
* `Act 5:37` After this man, Judas of Galilee rose in the days of the taxing and drew away many people after him. He also perished, and even as many as obeyed him were all *_dispersed_*.
* `Act 8:1` And Saul was consenting to his death. And at that time there was a great persecution against the church which was at Jerusalem, and they were all *_dispersed_* throughout the regions of Judea and Samaria, except the apostles.
* `Act 8:4` Therefore, those who were *_dispersed_* went everywhere preaching the word.
* `Act 11:19` Now those who were *_dispersed_* upon the persecution that arose about Stephen traveled as far as Phenice, Cyprus, and Antioch, preaching the word to no one but to the Jews only.
* `2Co 9:9` As it is written, "He has *_dispersed_*. He has given to the poor. His righteousness remains forever."

_14 verses containing DISPERSED_

== DISPERSING

* `Dan 12:7` And I heard the man clothed in linen, who was upon the waters of the river, when he held up his right hand and his left hand to heaven and swore by him who lives forever, that it shall be for a time, times, and a half of a time. And when he has made an end of *_dispersing_* the power of the holy people, all these things shall be finished.

_1 verse containing DISPERSING_

== DISPERSIONS

* `Jer 25:34` Howl, you shepherds, and cry, and wallow yourselves in the ashes, you principal of the flock, for the days of your slaughter and of your *_dispersions_* are accomplished, and you shall fall like a precious vessel.

_1 verse containing DISPERSIONS_

== DISPLAYED

* `Psa 60:4` You have given a banner to those who fear you so that it may be *_displayed_* because of the truth. [Selah.]

_1 verse containing DISPLAYED_

== DISPLEASE

* `Gen 31:35` And she said to her father, "Do not let it *_displease_* my lord that I cannot rise up before you, for the custom of women is upon me." And he searched, but did not find the images.
* `1Sa 29:7` Now therefore, return and go in peace so that you do not *_displease_* the lords of the Philistines."
* `2Sa 11:25` Then David said to the messenger, "Thus you shall say to Joab: 'Do not let this thing *_displease_* you, for the sword devours one as well as another. Make your battle stronger against the city and overthrow it.' And encourage him."
* `Pro 24:18` Lest the LORD see it and it *_displease_* him, and he turn away his wrath from him.

_4 verses containing DISPLEASE_

== DISPLEASED

* `Gen 38:10` And the thing which he did *_displeased_* the LORD; therefore, he slew him also.
* `Gen 48:17` And when Joseph saw that his father laid his right hand upon the head of Ephraim, it *_displeased_* him. And he lifted his father's hand to move it from Ephraim's head to Manasseh's head.
* `Num 11:1` And when the people complained, it *_displeased_* the LORD. And the LORD heard it and his anger was kindled, and the fire of the LORD burnt among them and consumed those who were in the uttermost parts of the camp.
* `Num 11:10` Then Moses heard the people weeping throughout their families, each in the door of his tent. And the anger of the LORD was kindled greatly, and Moses was also *_displeased_*.
* `1Sa 8:6` But the thing *_displeased_* Samuel when they said, "Give us a king to judge us." And Samuel prayed to the LORD.
* `1Sa 18:8` And Saul was very angry, and the saying *_displeased_* him. And he said, "They have ascribed to David tens of thousands, and to me they have ascribed thousands. And what can he have more but the kingdom?"
* `2Sa 6:8` And David was *_displeased_* because the LORD had made a breach upon Uzzah. And he called the name of the place Perez-uzzah to this day.
* `2Sa 11:27` And when the mourning was past, David sent and brought her to his house, and she became his wife and bore him a son. But the thing that David had done *_displeased_* the LORD.
* `1Ki 1:6` And his father had not *_displeased_* him at any time in saying, "Why have you done so?" And he also was a very handsome man. And his mother bore him after Absalom.
* `1Ki 20:43` And the king of Israel went to his house heavy and *_displeased_* and came to Samaria.
* `1Ki 21:4` And Ahab came into his house heavy and *_displeased_* because of the word which Naboth the Jezreelite had spoken to him, for he had said, "I will not give you the inheritance of my fathers." And he laid himself down upon his bed and turned away his face and would eat no bread.
* `1Ch 13:11` And David was *_displeased_* because the LORD had made a breach upon Uzza. Therefore, that place is called Perez-uzza to this day.
* `1Ch 21:7` And God was *_displeased_* with this thing; therefore, he smote Israel.
* `Psa 60:1` [To the Chief Musician upon Shushan-eduth. Michtam of David for Teaching: when he strove with Aram-naharaim and with Aram-zobah, when Joab returned and smote twelve thousand of Edom in the valley of salt.] O God, you have cast us off. You have scattered us. You have been *_displeased_*. O turn yourself to us again.
* `Isa 59:15` Indeed, truth fails. And he who departs from evil makes himself plunder. And the LORD saw it, and it *_displeased_* him that there was no judgment.
* `Dan 6:14` Then the king, when he heard these words, was much *_displeased_* with himself and set his heart on Daniel to deliver him. And he labored until the setting of the sun to deliver him.
* `Jna 4:1` But it *_displeased_* Jonah exceedingly and he was very angry.
* `Hab 3:8` Was the LORD *_displeased_* with the rivers? Was your anger against the rivers? Was your wrath against the sea that you rode upon your horses and your chariots of salvation?
* `Zch 1:2` "The LORD has been greatly *_displeased_* with your fathers.
* `Zch 1:15` And I am very greatly *_displeased_* with the heathen who are at ease. For I was only a little *_displeased_*, and they helped forward the affliction."
* `Mth 21:15` And when the chief priests and scribes saw the wonderful things that he did and the children crying in the temple, and saying, "Hosanna to the son of David," they were greatly *_displeased_*,
* `Mrk 10:14` But when Jesus saw it, he was much *_displeased_* and said to them, "Allow the little children to come to me and do not forbid them, for of such is the kingdom of God.
* `Mrk 10:41` And when the ten heard it, they began to be much *_displeased_* with James and John.
* `Act 12:20` And Herod was highly *_displeased_* with those of Tyre and Sidon. But they came with one accord to him, and having made Blastus the king's chamberlain their friend, desired peace, because their country was nourished by the king's country.

_24 verses containing DISPLEASED_

== DISPLEASES

* `Num 22:34` And Balaam said to the angel of the LORD, "I have sinned. For I did not know that you stood in the way against me. Now therefore, if it *_displeases_* you, I will return again."

_1 verse containing DISPLEASES_

== DISPLEASURE

* `Deu 9:19` (For I was afraid of the anger and hot *_displeasure_* with which the LORD was angry against you to destroy you.) But the LORD listened to me at that time also.
* `Jdg 15:3` And Samson said concerning them, "Now I shall be more blameless than the Philistines, though I do them a *_displeasure_*."
* `Psa 2:5` Then he shall speak to them in his wrath and trouble them in his sore *_displeasure_*.
* `Psa 6:1` [To the Chief Musician on Neginoth upon Sheminith. A Psalm of David.] O LORD, do not rebuke me in your anger, neither chasten me in your hot *_displeasure_*.
* `Psa 38:1` [A Psalm of David: to bring to remembrance.] O LORD, do not rebuke me in your wrath, neither chasten me in your hot *_displeasure_*.

_5 verses containing DISPLEASURE_

== DISPOSED

* `1Sa 11:11` And it was so on the next day, that Saul *_disposed_* the people in three companies. And they came into the midst of the host in the morning-watch and slew the Ammonites until the heat of the day. And it came to pass, that those who remained were scattered so that two of them were not left together.
* `Ezr 7:13` I make a decree, that all those of the people of Israel and of his priests and Levites in my realm who are *_disposed_* of their own free will to go to Jerusalem, may go with you.
* `Job 34:13` Who has given him a charge over the earth? Or who has *_disposed_* the whole world?
* `Job 37:15` Do you know when God *_disposed_* them and caused the light of his cloud to shine?
* `Act 18:27` And when he was *_disposed_* to pass into Achaia, the brothers wrote, exhorting the disciples to receive him. When he had come, he helped them much who had believed through grace.
* `1Co 10:27` If any of those who do not believe invites you to a feast and you are *_disposed_* to go, whatever is set before you, eat, asking no question on account of conscience.

_6 verses containing DISPOSED_

== DISPOSITION

* `Act 7:53` Who have received the law by the *_disposition_* of angels and have not kept it."

_1 verse containing DISPOSITION_

== DISPOSSESS

* `Num 33:53` And you shall *_dispossess_* the inhabitants of the land and dwell in it, for I have given you the land to possess it.
* `Deu 7:17` "If you say in your heart, 'These nations are more than I. How can I *_dispossess_* them?'
* `Deu 9:1` "Hear, O Israel. You are to pass over the Jordan this day to go in and *_dispossess_* nations greater and mightier than yourself, cities great and fortified up to heaven,
* `Zch 9:4` Behold, the Lord will *_dispossess_* her and he will smite her power in the sea, and she shall be devoured with fire.

_4 verses containing DISPOSSESS_

== DISPOSSESSED

* `Num 32:39` And the children of Machir the son of Manasseh went to Gilead and took it and *_dispossessed_* the Amorite who was in it.
* `Jdg 11:23` So now the LORD God of Israel has *_dispossessed_* the Amorites from before his people Israel, and should you possess it?

_2 verses containing DISPOSSESSED_

== DISPUTATION

* `Act 15:2` Therefore, when Paul and Barnabas had no small dissension and *_disputation_* with them, they determined that Paul, Barnabas, and some others of them should go to Jerusalem to the apostles and elders about this question.

_1 verse containing DISPUTATION_

== DISPUTATIONS

* `Rom 14:1` Receive him who is weak in the faith, but not to doubtful *_disputations_*.

_1 verse containing DISPUTATIONS_

== DISPUTE

* `Job 23:7` There the righteous might *_dispute_* with him, and I would be delivered forever from my judge.
* `Act 28:29` And when he had said these words, the Jews departed, having a great *_dispute_* among themselves.

_2 verses containing DISPUTE_

== DISPUTED

* `Mrk 9:33` And he came to Capernaum. And being in the house, he asked them, "What was it that you *_disputed_* among yourselves on the way?"
* `Mrk 9:34` But they held their peace, for on the way they had *_disputed_* among themselves who should be the greatest.
* `Act 9:29` And he spoke boldly in the name of the Lord Jesus and *_disputed_* against the Grecians, but they were seeking to slay him.
* `Act 17:17` Therefore, he *_disputed_* in the synagogue with the Jews and with the devout persons, and in the market daily with those who met with him.

_4 verses containing DISPUTED_

== DISPUTER

* `1Co 1:20` Where is the wise? Where is the scribe? Where is the *_disputer_* of this world? Has God not made the wisdom of this world foolish?

_1 verse containing DISPUTER_

== DISPUTING

* `Act 6:9` Then there arose some from the synagogue called The Libertines, along with Cyrenians, Alexandrians, and some of those from Cilicia and Asia, *_disputing_* with Stephen.
* `Act 15:7` And when there had been much *_disputing_*, Peter rose and said to them, "Men, brothers, you know that a good while ago God made a choice among us, that by my mouth the Gentiles should hear the word of the gospel and believe.
* `Act 19:8` And he went into the synagogue and spoke boldly for three months, *_disputing_* and persuading the things concerning the kingdom of God.
* `Act 19:9` But when some were hardened and did not believe, but spoke evil of that way before the multitude, he departed from them and separated the disciples, *_disputing_* daily in the school of one, Tyrannus.
* `Act 24:12` And they neither found me in the temple *_disputing_* with any man; neither exciting the people to sedition, neither in the synagogues, nor in the city;
* `Jde 1:9` Yet Michael the archangel, when contending with the devil and *_disputing_* about the body of Moses, did not dare bring against him a railing accusation, but said, "May the Lord rebuke you."

_6 verses containing DISPUTING_

== DISPUTINGS

* `Phl 2:14` Do all things without murmurings and *_disputings_*,
* `1Ti 6:5` Perverse *_disputings_* of men of corrupt minds and destitute of the truth, supposing gain to be godliness. Withdraw yourself from such.

_2 verses containing DISPUTINGS_

== DISQUIET

* `Jer 50:34` Their Redeemer is strong. The LORD of hosts is his name. He will thoroughly plead their cause so that he may give rest to the land and *_disquiet_* the inhabitants of Babylon.

_1 verse containing DISQUIET_

== DISQUIETED

* `1Sa 28:15` And Samuel said to Saul, "Why have you *_disquieted_* me to bring me up?" And Saul answered, "I am grievously distressed, for the Philistines make war against me, and God has departed from me and no longer answers me, neither by prophets, nor by dreams. Therefore, I have called you so that you may make known to me what I shall do."
* `Psa 6:3` My soul is also greatly *_disquieted_*. But you, O LORD, how long?
* `Psa 6:10` Let all my enemies be ashamed and greatly *_disquieted_*. Let them return and be suddenly ashamed.
* `Psa 39:6` "Surely every man walks in a vain show. Surely they are *_disquieted_* in vain. He heaps up riches and does not know who gathers them.
* `Psa 42:5` Why are you cast down, O my soul? And why are you *_disquieted_* in me? Hope in God. For I shall again praise him for the help of his countenance.
* `Psa 42:11` Why are you cast down, O my soul? And why are you *_disquieted_* within me? Hope in God. For I shall again praise him who is the health of my countenance and my God.
* `Psa 43:5` Why are you cast down, O my soul? And why are you *_disquieted_* within me? Hope in God. For I shall again praise him who is the health of my countenance and my God.
* `Pro 30:21` For three things the earth is *_disquieted_*, even for four which it cannot bear:

_8 verses containing DISQUIETED_

== DISQUIETNESS

* `Psa 38:8` I am feeble and grievously broken. I have roared by reason of the *_disquietness_* of my heart.

_1 verse containing DISQUIETNESS_

== DISSEMBLED

* `Jsh 7:11` Israel has sinned, and they have also transgressed my covenant which I commanded them, for they have even taken some of the accursed things, and they have also stolen, *_dissembled_*, and put them even among their own goods.
* `Jer 42:20` For you *_dissembled_* in your hearts when you sent me to the LORD your God, saying, 'Pray for us to the LORD our God, and according to all that the LORD our God says, declare it to us, and we will do it.'
* `Gal 2:13` And the other Jews *_dissembled_* likewise with him so that Barnabas was also carried away with their dissimulation.

_3 verses containing DISSEMBLED_

== DISSEMBLERS

* `Psa 26:4` I have not sat with vain persons, neither will I go in with *_dissemblers_*.

_1 verse containing DISSEMBLERS_

== DISSEMBLES

* `Pro 26:24` He who hates *_dissembles_* with his lips and lays up deceit within him.

_1 verse containing DISSEMBLES_

== DISSENSION

* `Act 15:2` Therefore, when Paul and Barnabas had no small *_dissension_* and disputation with them, they determined that Paul, Barnabas, and some others of them should go to Jerusalem to the apostles and elders about this question.
* `Act 23:7` And when he had said this, there arose a *_dissension_* between the Pharisees and the Sadducees, and the multitude was divided.
* `Act 23:10` And when there arose a great *_dissension_*, the chief captain, fearing, lest Paul would have been pulled in pieces by them, commanded the soldiers to go down and take him by force from among them and bring him into the castle.

_3 verses containing DISSENSION_

== DISSENSIONS

* `Gal 5:20` Idolatry, witchcraft, hatred, variance, jealousy, wrath, strife, *_dissensions_*, heresies,

_1 verse containing DISSENSIONS_

== DISSIMULATION

* `Rom 12:9` Let love be without *_dissimulation_*. Abhor that which is evil. Cleave to that which is good.
* `Gal 2:13` And the other Jews dissembled likewise with him so that Barnabas was also carried away with their *_dissimulation_*.

_2 verses containing DISSIMULATION_

== DISSOLVE

* `Job 30:22` You lift me up to the wind and cause me to ride upon it. You *_dissolve_* my substance.
* `Dan 5:16` And I have heard of you, that you can make interpretations and *_dissolve_* doubts. Now if you can read the writing and make known to me its interpretation, you shall be clothed with scarlet and have a chain of gold around your neck, and shall be the third ruler in the kingdom."

_2 verses containing DISSOLVE_

== DISSOLVED

* `Psa 75:3` The earth and all its inhabitants are *_dissolved_*. I bear up its pillars." [Selah.]
* `Isa 14:31` Howl, O gate. Cry, O city. You, all Philistia, are *_dissolved_*. For there shall come from the north a smoke, and no one shall be alone in his appointed times.
* `Isa 24:19` The earth is utterly broken down, the earth is entirely *_dissolved_*, the earth is exceedingly moved.
* `Isa 34:4` And all the host of heaven shall be *_dissolved_*, and the heavens shall be rolled together like a scroll. And all their hosts shall fall down as the leaf falls from the vine and like a falling fig from the fig-tree.
* `Nah 2:6` The gates of the rivers shall be opened, and the palace shall be *_dissolved_*.
* `2Co 5:1` For we know that if our earthly house of this tabernacle were *_dissolved_*, we have a building from God, a house not made with hands, eternal in the heavens.
* `2Pe 3:11` Seeing then that all these things will be *_dissolved_*, what manner of persons ought you to be in all holy deportment and godliness,
* `2Pe 3:12` Looking for and hastening to the coming of the day of God, in which the heavens being on fire will be *_dissolved_* and the elements will melt with fervent heat?

_8 verses containing DISSOLVED_

== DISSOLVING

* `Dan 5:12` Because an excellent spirit, knowledge, understanding, the interpreting of dreams, the declaring of riddles, and *_dissolving_* of doubts were found in the same Daniel, whom the king named Belteshazzar. Now let Daniel be called, and he will reveal the interpretation."

_1 verse containing DISSOLVING_

== DISTAFF

* `Pro 31:19` [YOD] She lays her hands to the *_distaff_*, and her hands hold the spindle.

_1 verse containing DISTAFF_

== DISTANCE

* `Gen 35:16` And they journeyed from Beth-el. And there was only a little *_distance_* to come to Ephrath, and Rachel travailed and had hard labor.
* `Gen 48:7` And as for me, when I came from Padan, Rachel died beside me in the land of Canaan, on the way when there was only a little *_distance_* to come to Ephrath, and I buried her there on the way of Ephrath (the same is Beth-lehem)."
* `Mth 26:58` But Peter followed him at a *_distance_* to the high priest's palace, went in, and sat with the servants to see the end.
* `Mth 27:55` And many women were there (beholding at a *_distance_*) who followed Jesus from Galilee, ministering to him,
* `Mrk 8:3` And if I send them away fasting to their own houses, they will faint by the way, for some of them came from a *_distance_*."
* `Mrk 14:54` And Peter followed him at a *_distance_*, even into the palace of the high priest, and he sat with the servants and warmed himself at the fire.
* `Mrk 15:40` There were also women looking on at a *_distance_*, among whom were Mary Magdalene, Mary (the mother of James the younger and Joseph), Salome
* `Luk 17:12` And as he entered into a certain village, ten men who were lepers met him there, who stood at a *_distance_*.
* `Luk 22:54` Then they took him, led him, and brought him into the high priest's house. And Peter followed at a *_distance_*.

_9 verses containing DISTANCE_

== DISTANT

* `Exo 36:22` One board had two tenons, equally *_distant_* from one another. He did this for all the boards of the tabernacle.
* `Deu 20:15` Thus you shall do to all the cities which are very *_distant_* from you, which are not of the cities of these nations.
* `Deu 29:22` So that the generation to come of your children who arise after you and the stranger who comes from a *_distant_* land shall say—when they see the plagues of that land and the sicknesses which the LORD has laid upon it,
* `2Ch 6:32` "Moreover, concerning the stranger who is not of your people Israel, but has come from a *_distant_* country for your great name's sake and your mighty hand and your out-stretched arm, if they come and pray in this house,
* `Jer 6:20` For what purpose does incense come to me from Sheba and the sweet cane from a *_distant_* country? Your burnt-offerings are not acceptable, nor are your sacrifices sweet to me."
* `Jer 8:19` Behold the voice of the cry of the daughter of my people because of those who dwell in a *_distant_* country: "Is the LORD not in Zion? Is her king not in her?" "Why have they provoked me to anger with their engraved images and with strange vanities?"
* `Ezk 12:27` "Son of man, behold, those of the house of Israel say, 'The vision that he sees is for many days to come, and he prophesies of the times that are *_distant_*.'
* `Jhn 11:18` (Now Bethany was near Jerusalem, about fifteen furlongs *_distant_*.)

_8 verses containing DISTANT_

== DISTILL

* `Deu 32:2` My doctrine shall drop as the rain, my speech shall *_distill_* as the dew, as the small rain upon the tender herb, and as the showers upon the grass.
* `Job 36:28` Which the clouds drop and *_distill_* upon man abundantly.

_2 verses containing DISTILL_

== DISTINCTION

* `Exo 9:4` And the LORD shall make a *_distinction_* between the livestock of Israel and the livestock of Egypt, and there shall nothing die of all that belongs to the children of Israel."'"
* `1Co 14:7` And even lifeless things giving sound, whether pipe or harp, unless they give a *_distinction_* in the sounds, how shall it be known what is piped or harped?

_2 verses containing DISTINCTION_

== DISTINCTLY

* `Neh 8:8` So they read in the book in the law of God *_distinctly_*, giving the sense so that they understood the reading.

_1 verse containing DISTINCTLY_

== DISTINGUISH

* `Lev 20:25` You shall therefore *_distinguish_* between clean beasts and unclean and between unclean birds and clean. And you shall not make your souls abominable by beast or by bird, or by any manner of living animal that creeps on the ground, which I have separated from you as unclean.

_1 verse containing DISTINGUISH_

== DISTINGUISHED

* `2Ki 4:8` And it fell on a day, that Elisha passed to Shunem where a *_distinguished_* woman was, and she constrained him to eat bread. And so it was, that as often as he passed by, he turned in there to eat bread.

_1 verse containing DISTINGUISHED_

== DISTRACTED

* `Psa 88:15` I am afflicted and ready to die from my youth. While I suffer your terrors I am *_distracted_*.

_1 verse containing DISTRACTED_

== DISTRACTION

* `1Co 7:35` And this I speak for your own profit, not that I may cast a snare upon you, but for that which is proper and so that you may attend upon the Lord without *_distraction_*.

_1 verse containing DISTRACTION_

== DISTRESS

* `Gen 35:3` And let us arise and go up to Beth-el. And I will make there an altar to God, who answered me in the day of my *_distress_* and was with me in the way which I went."
* `Gen 42:21` And they said to one another, "We are truly guilty concerning our brother in that we saw the anguish of his soul when he implored us, and we would not hear; therefore, this *_distress_* has come upon us."
* `Num 25:17` "*_Distress_* the Midianites and smite them.
* `Num 25:18` For they *_distress_* you with their wiles, with which they have beguiled you in the matter of Peor and in the matter of Cozbi, the daughter of a prince of Midian, their sister, who was slain in the day of the plague for Peor's sake."
* `Deu 2:9` And the LORD said to me, 'Do not *_distress_* the Moabites, neither contend with them in battle, for I will not give you any of their land for a possession, because I have given Ar to the children of Lot for a possession.'
* `Deu 2:19` And when you come near over against the children of Ammon, do not *_distress_* them nor meddle with them, for I will not give you any possession of the land of the children of Ammon, because I have given it to the children of Lot for a possession.'
* `Deu 28:53` And you shall eat the fruit of your own body, the flesh of your sons and of your daughters which the LORD your God has given you, in the siege and in the *_distress_* with which your enemies shall *_distress_* you.
* `Deu 28:55` So that he will not give to any of them the flesh of his children whom he shall eat, because he has nothing left in the siege and in the *_distress_* with which your enemies shall *_distress_* you in all your gates.
* `Deu 28:57` Toward her young one, her own offspring, and toward her children which she shall bear, for she shall eat them secretly for lack of all things in the siege and *_distress_* with which your enemy shall *_distress_* you in your gates.
* `Jdg 11:7` And Jephthah said to the elders of Gilead, "Did you not hate me and expel me from my father's house? Why have you come to me now when you are in *_distress_*?"
* `1Sa 22:2` And everyone who was in *_distress_*, everyone who was in debt, and everyone who was discontented resorted to him, and he became a captain over them. And there were with him about four hundred men.
* `2Sa 22:7` "In my *_distress_* I called upon the LORD and cried to my God. And he heard my voice out of his temple, and my cry entered into his ears.
* `2Sa 24:14` And David said to Gad, "I am in great *_distress_*. Let us fall now into the hand of the LORD, for his mercies are great. But do not let me fall into the hand of man."
* `1Ki 1:29` And the king swore and said, "As the LORD lives, who has redeemed my soul out of all *_distress_*,
* `1Ch 21:13` And David said to Gad, "I am in great *_distress_*. Let me now fall into the hand of the LORD, for his mercies are very great. But do not let me fall into the hand of man."
* `2Ch 28:22` And in the time of his *_distress_* he trespassed yet more against the LORD—this same king Ahaz.
* `Neh 2:17` Then I said to them, "You see the *_distress_* that we are in, how Jerusalem lies waste and its gates are burned with fire. Come, and let us build up the wall of Jerusalem so that we may no more be a reproach."
* `Neh 9:37` And it yields much increase to the kings whom you have set over us because of our sins. They also have dominion over our bodies and over our livestock at their pleasure, and we are in great *_distress_*.
* `Job 20:22` In the fullness of his sufficiency he shall be in *_distress_*. Every hand of the wicked shall come upon him.
* `Job 36:16` Even so he would have enticed you out of *_distress_* into a broad place where there is no constraint, and that which should be set on your table would be full of fatness.
* `Psa 4:1` [To the Chief Musician on Neginoth. A Psalm of David.] Hear me when I call, O God of my righteousness. You have enlarged me when I was in *_distress_*. Have mercy upon me and hear my prayer.
* `Psa 18:6` In my *_distress_* I called upon the LORD and cried to my God. He heard my voice out of his temple, and my cry came before him, even into his ears.
* `Psa 118:5` I called upon the LORD in *_distress_*. The LORD answered me and set me in a large place.
* `Psa 120:1` [A Song of Degrees.] In my *_distress_* I cried to the LORD, and he heard me.
* `Pro 1:27` When your fear comes like desolation, and your destruction comes like a whirlwind, when *_distress_* and anguish come upon you.
* `Isa 11:13` The envy of Ephraim shall also depart, and the adversaries of Judah shall be cut off. Ephraim shall not envy Judah, and Judah shall not *_distress_* Ephraim.
* `Isa 25:4` For you have been a defense to the poor, a defense to the needy in his *_distress_*, a refuge from the storm, a shade from the heat, when the blast of the terrible ones is like a storm against the wall.
* `Isa 29:2` Yet I will *_distress_* Ariel, and there shall be heaviness and sorrow, and she shall be to me like Ariel.
* `Isa 29:7` And the multitude of all the nations who fight against Ariel, even all who fight against her and her fortress, and who *_distress_* her, shall be like a dream of a night-vision.
* `Jer 10:18` For thus says the LORD: "Behold, I will sling out the inhabitants of the land at this time and will *_distress_* them so that they are found out."
* `Jer 19:9` And I will cause them to eat the flesh of their sons and the flesh of their daughters, and they shall each eat the flesh of his friend in the siege and *_distress_* with which their enemies and those who seek their lives shall *_distress_* them."'
* `Lam 1:3` [GIMEL] Judah has gone into captivity because of affliction and because of great servitude. She dwells among the heathen. She finds no rest. All her persecutors overtook her in the midst of *_distress_*.
* `Lam 1:20` [RESH] Behold, O LORD, for I am in *_distress_*. My heart is troubled. My heart is turned within me, for I have grievously rebelled. Abroad the sword bereaves, at home it is as death.
* `Oba 1:12` But do not look in the day of your brother, in the day that he became a stranger, neither rejoice over the children of Judah in the day of their destruction, neither speak proudly in the day of *_distress_*.
* `Oba 1:14` Do not stand in the cross-way to cut off those of his who escaped, neither deliver up those of his who remain in the day of *_distress_*.
* `Zph 1:15` That day is a day of wrath, a day of trouble and *_distress_*, a day of wasting and desolation, a day of darkness and gloominess, a day of clouds and thick darkness,
* `Zph 1:17` And I will bring *_distress_* upon men so that they shall walk like blind men, because they have sinned against the LORD. And their blood shall be poured out like dust and their flesh like dung.
* `Luk 21:23` But woe to those who are with child and to those who nurse infants in those days! For there shall be great *_distress_* in the land and wrath upon this people.
* `Luk 21:25` "And there shall be signs in the sun, in the moon, and in the stars, and upon the earth *_distress_* of nations in perplexity because of the roaring of the sea and the waves.
* `Rom 8:35` Who shall separate us from the love of Christ? Shall tribulation, *_distress_*, persecution, famine, nakedness, peril, or sword?
* `1Co 7:26` I suppose therefore that this is good for the present *_distress_*, I say, that it is good for a man to be so.
* `1Th 3:7` Therefore, brothers, by your faith we were comforted over you in all our affliction and *_distress_*.

_42 verses containing DISTRESS_

== DISTRESSED

* `Gen 32:7` Then Jacob was greatly afraid and *_distressed_*. And he divided the people who were with him, along with the flocks, herds, and camels, into two bands,
* `Num 22:3` And Moab was greatly afraid of the people because they were many. And Moab was *_distressed_* because of the children of Israel.
* `Jdg 2:15` Wherever they went out, the hand of the LORD was against them for evil, as the LORD had said, and as the LORD had sworn to them. And they were greatly *_distressed_*.
* `Jdg 10:9` Moreover, the children of Ammon passed over the Jordan to fight also against Judah, against Benjamin, and against the house of Ephraim, so that Israel was greatly *_distressed_*.
* `1Sa 13:6` When the men of Israel saw that they were in trouble (for the people were *_distressed_*), the people hid themselves in caves, in thickets, in rocks, in high places, and in pits.
* `1Sa 14:24` And the men of Israel were *_distressed_* that day, for Saul had adjured the people, saying, "Cursed is the man who eats any food until evening and until I am avenged of my enemies." So none of the people tasted any food.
* `1Sa 28:15` And Samuel said to Saul, "Why have you disquieted me to bring me up?" And Saul answered, "I am grievously *_distressed_*, for the Philistines make war against me, and God has departed from me and no longer answers me, neither by prophets, nor by dreams. Therefore, I have called you so that you may make known to me what I shall do."
* `1Sa 30:6` And David was greatly *_distressed_*, for the people spoke of stoning him because the soul of all the people was grieved, every man for his sons and for his daughters, but David encouraged himself in the LORD his God.
* `2Sa 1:26` I am *_distressed_* for you, my brother Jonathan. Very pleasant you have been to me. Your love to me was wonderful, passing the love of women.
* `2Ch 28:20` And Tilgath-pilneser king of Assyria came to him and *_distressed_* him, but did not strengthen him.
* `Neh 9:27` Therefore, you delivered them into the hand of their enemies who *_distressed_* them. And in the time of their trouble, when they cried to you, you heard them from heaven. And according to your manifold mercies you gave them deliverers who saved them out of the hand of their enemies.
* `Isa 8:21` And they shall pass through it *_distressed_* and hungry. And it shall come to pass when they are hungry, that they shall fret themselves and curse their king and their God and look upward.
* `Mth 17:15` "Lord, have mercy on my son, for he is lunatic and grievously *_distressed_*. He often falls into the fire and often into the water.
* `Luk 12:50` But I have a baptism to be baptized with, and how I am *_distressed_* until it is accomplished!
* `2Co 4:8` We are troubled on every side, yet not *_distressed_*; we are perplexed, but not in despair;

_15 verses containing DISTRESSED_

== DISTRESSES

* `Psa 25:17` [PE] The troubles of my heart are enlarged. O bring me out of my *_distresses_*.
* `Psa 107:6` Then they cried to the LORD in their trouble, and he delivered them out of their *_distresses_*.
* `Psa 107:13` Then they cried to the LORD in their trouble, and he saved them out of their *_distresses_*.
* `Psa 107:19` Then they cry to the LORD in their trouble, and he saves them out of their *_distresses_*.
* `Psa 107:28` Then they cry to the LORD in their trouble, and he brings them out of their *_distresses_*.
* `Ezk 30:16` And I will set fire in Egypt. Sin shall have great pain, No shall be rent apart, and Noph shall have *_distresses_* daily.
* `2Co 6:4` But in all things approve ourselves as the ministers of God, in much patience, in afflictions, in necessities, in *_distresses_*,
* `2Co 12:10` Therefore, I take pleasure in infirmities, in reproaches, in hardships, in persecutions, in *_distresses_* for Christ's sake. For when I am weak, then I am strong.

_8 verses containing DISTRESSES_

== DISTRESSING

* `Gen 41:57` And all countries came into Egypt to Joseph to buy grain because the famine was *_distressing_* in all lands.
* `Gen 47:13` And there was no bread in all the land, for the famine was very *_distressing_* so that the land of Egypt and all the land of Canaan fainted by reason of the famine.
* `Deu 6:22` And the LORD showed signs and wonders, great and *_distressing_*, upon Egypt, upon Pharaoh, and upon all his household before our eyes.

_3 verses containing DISTRESSING_

== DISTRIBUTE

* `2Ch 31:14` And Kore the son of Imnah the Levite, the gatekeeper toward the east, was over the voluntary-offerings of God to *_distribute_* the oblations of the LORD and the most holy things.
* `Neh 13:13` And I made treasurers over the treasuries: Shelemiah the priest, Zadok the scribe, and of the Levites, Pedaiah, and next to them was Hanan the son of Zaccur, the son of Mattaniah, for they were accounted faithful. Their office was to *_distribute_* to their brothers.
* `Luk 18:22` Now when Jesus heard these things, he said to him, "Yet you lack one thing: sell all that you have and *_distribute_* to the poor, and you shall have treasure in heaven. Then come, follow me."
* `1Ti 6:18` Charge them to do good and that they be rich in good works, ready to *_distribute_*, willing to communicate,

_4 verses containing DISTRIBUTE_

== DISTRIBUTED

* `Jsh 13:32` These are the countries which Moses *_distributed_* for inheritance in the plains of Moab on the other side of the Jordan by Jericho eastward.
* `Jsh 14:1` And these are the countries which the children of Israel inherited in the land of Canaan, which Eleazar the priest, Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel *_distributed_* for inheritance to them.
* `1Ch 24:3` And David *_distributed_* them, both Zadok of the sons of Eleazar and Ahimelech of the sons of Ithamar, according to their offices in their service.
* `2Ch 23:18` Also Jehoiada appointed the offices of the house of the LORD by the hand of the priests the Levites, whom David had *_distributed_* in the house of the LORD to offer the burnt-offerings of the LORD, as it is written in the law of Moses, with rejoicing and with singing, as it was ordained by David.
* `Jhn 6:11` And Jesus took the loaves, and when he had given thanks, he *_distributed_* to the disciples, and the disciples to those who were sitting down, and likewise with the fish, as much as they wished.
* `1Co 7:17` But as God has *_distributed_* to every man, as the Lord has called each one, so let him walk. And thus I ordain in all churches.
* `2Co 10:13` But we will not boast of things beyond our measure, but according to the measure of the rule which God has *_distributed_* to us, a measure to reach even to you.

_7 verses containing DISTRIBUTED_

== DISTRIBUTES

* `Job 21:17` How often is the candle of the wicked put out? And how often does their destruction come upon them? God *_distributes_* sorrows in his anger.

_1 verse containing DISTRIBUTES_

== DISTRIBUTION

* `2Ch 31:17` This is the *_distribution_* of the priests by the house of their fathers and the Levites from twenty years old and upward, in their charges by their courses,
* `Act 4:35` And laid it down at the apostles' feet. And *_distribution_* was made to every man according as he had need.

_2 verses containing DISTRIBUTION_

== DISTURB

* `Ezk 32:13` I will also destroy all its beasts from beside the great waters, neither shall the foot of man *_disturb_* them anymore, nor the hooves of beasts *_disturb_* them.
* `Hab 2:7` Shall they not rise suddenly who bite you, and awake who *_disturb_* you, and you shall be plunder for them?

_2 verses containing DISTURB_

== DISTURBED

* `Psa 46:3` Though its waters roar and are *_disturbed_*, though the mountains shake with its swelling. [Selah.]
* `Psa 77:16` The waters saw you, O God, the waters saw you. They were afraid. The depths were also *_disturbed_*.
* `Ezk 26:18` Now the coastlands shall tremble in the day of your fall. Even the coastlands that are by the sea shall be *_disturbed_* at your departure.'"
* `Ezk 32:2` "Son of man, take up a lamentation for Pharaoh king of Egypt and say to him, 'You are like a young lion of the nations and you are like a dragon in the seas. And you came forth with your rivers and *_disturbed_* the waters with your feet and rendered their rivers foul.'"

_4 verses containing DISTURBED_

== DITCH

* `Job 9:31` Yet you will plunge me in the *_ditch_*, and my own clothes shall abhor me.
* `Psa 7:15` He made a pit, dug it, and has fallen into the *_ditch_* which he made.
* `Pro 23:27` For a lewd woman is a deep *_ditch_*, and a strange woman is a narrow pit.
* `Isa 22:11` You also made a *_ditch_* between the two walls for the water of the old pool. But you have not looked to its maker, neither had respect to him who fashioned it long ago.
* `Mth 15:14` Leave them alone. They are blind leaders of the blind. And if the blind lead the blind, both will fall into the *_ditch_*."
* `Luk 6:39` And he spoke a parable to them: "Can the blind lead the blind? Will they not both fall into the *_ditch_*?

_6 verses containing DITCH_

== DITCHES

* `2Ki 3:16` And he said, "Thus says the LORD: 'Make this valley full of *_ditches_*.'

_1 verse containing DITCHES_

== DIVERSE

* `Lev 19:19` 'You shall keep my statutes. You shall not let your livestock engender with a *_diverse_* kind. You shall not sow your field with mingled seed, neither shall a garment mingled of linen and woolen come upon you.
* `Deu 22:9` "You shall not sow your vineyard with *_diverse_* seeds, lest the fruit of your seed which you have sown and the fruit of your vineyard should be defiled.
* `Deu 25:13` "You shall not have in your bag *_diverse_* weights, a great and a small.
* `Deu 25:14` You shall not have in your house *_diverse_* measures, a great and a small.
* `Jdg 5:30` 'Have they not found, have they not divided the plunder: to every man a woman or two, to Sisera plunder of *_diverse_* colors, plunder of *_diverse_* colors of needle-work, of *_diverse_* colors of needle-work on both sides, suitable for the necks of those who take the plunder?'
* `2Sa 13:18` And she had a garment of *_diverse_* colors upon her, for with such robes the king's daughters who were virgins were appareled. Then his servant brought her out and bolted the door after her.
* `2Sa 13:19` And Tamar put ashes on her head, rent her garment of *_diverse_* colors that was on her, laid her hand on her head, and went on crying.
* `1Ch 29:2` Now I have prepared with all my might for the house of my God the gold for things to be made of gold, the silver for things of silver, the brass for things of brass, iron for things of iron, and wood for things of wood, onyx-stones and stones to be set, glittering stones and of *_diverse_* colors, and all manner of precious stones and marble stones in abundance.
* `2Ch 16:14` And they buried him in his own sepulchers which he had made for himself in the city of David, and laid him in the bed which was filled with sweet odors and *_diverse_* kinds of spices prepared by the perfumers' art. And they made a very great burning for him.
* `Est 1:7` And they gave them drink in vessels of gold (the vessels being *_diverse_* from one another) and royal wine in abundance, according to the state of the king.
* `Est 3:8` And Haman said to king Ahasuerus, "There is a certain people scattered abroad and dispersed among the people in all the provinces of your kingdom. And their laws are *_diverse_* from all people, neither do they keep the king's laws. Therefore, it is not for the king's profit to allow them to remain.
* `Pro 20:10` *_Diverse_* weights and *_diverse_* measures, both of them are alike abominations to the LORD.
* `Pro 20:23` *_Diverse_* weights are an abomination to the LORD, and a false balance is not good.
* `Ecc 5:7` For in the multitude of dreams and many words there are also *_diverse_* vanities. But fear God.
* `Ezk 16:16` And you took some of your garments, decked your high places with *_diverse_* colors, and played the harlot upon them. Such things shall not come, neither shall it be so.
* `Ezk 17:3` And say, 'Thus says the Lord GOD: "A great eagle with great wings and long feathers, full of feathers which had *_diverse_* colors, came to Lebanon and took the highest branch of the cedar.
* `Dan 7:3` And four great beasts came up from the sea, *_diverse_* from one another.
* `Dan 7:7` After this I saw in the night visions, and behold, a fourth beast, dreadful and terrible, and exceedingly strong, and it had great iron teeth. It devoured and broke in pieces and trampled the remainder with its feet. And it was *_diverse_* from all the beasts that were before it, and it had ten horns.
* `Dan 7:19` "Then I wished to know the truth of the fourth beast, which was *_diverse_* from all the others, exceedingly dreadful, whose teeth were of iron and his nails of brass, which devoured, broke in pieces, and trampled the remainder with his feet,
* `Dan 7:23` "Thus he said: 'The fourth beast shall be the fourth kingdom upon earth, which shall be *_diverse_* from all kingdoms and shall devour the whole earth, tread it down, and break it in pieces.
* `Dan 7:24` And the ten horns out of this kingdom are ten kings who shall arise. And another shall rise after them, and he shall be *_diverse_* from the first and he shall subdue three kings.
* `Mth 24:7` For nation will rise against nation and kingdom against kingdom. And there will be famines, pestilences, and earthquakes in *_diverse_* places.
* `Mrk 13:8` For nation will rise against nation, kingdom against kingdom. There will be earthquakes in *_diverse_* places, and there will be famines and troubles. These are the beginnings of sorrows.
* `1Co 12:10` To another, the working of miracles; to another, prophecy; to another, discerning of spirits; to another, *_diverse_* kinds of languages; to another, the interpretation of languages.
* `2Ti 3:6` For of this sort are those who creep into houses and lead captive silly women laden with sins, led away with *_diverse_* lusts,
* `Tit 3:3` For we ourselves were also sometimes foolish, disobedient, deceived, serving *_diverse_* lusts and pleasures, living in malice and envy, hateful, and hating one another.
* `Heb 1:1` God, who at many times and in *_diverse_* manners spoke in time past to the fathers by the prophets,
* `Heb 2:4` God also bearing them testimony, both with signs and wonders, and with *_diverse_* miracles and gifts of the Holy Spirit, according to his own will.
* `Heb 9:10` Which stood only in foods and drinks, *_diverse_* washings, and carnal ordinances imposed on them until the time of reformation.
* `Heb 13:9` Do not be carried away with *_diverse_* and strange doctrines. For it is a good thing that the heart is established with grace, not with foods, which have not profited those who have been occupied in them.
* `Jms 1:2` My brothers, count it all joy when you fall into *_diverse_* temptations,

_31 verses containing DIVERSE_

== DIVERSITIES

* `1Co 12:4` Now there are *_diversities_* of gifts, but the same Spirit.
* `1Co 12:6` And there are *_diversities_* of operations, but it is the same God who works all in all.
* `1Co 12:28` And God has set some in the church: first apostles, second prophets, third teachers, next miracles, then gifts of healings, helps, governments, and *_diversities_* of languages.

_3 verses containing DIVERSITIES_

== DIVIDE

* `Gen 1:6` And God said, "Let there be a firmament in the midst of the waters, and let it *_divide_* the waters from the waters."
* `Gen 1:14` And God said, "Let there be lights in the firmament of the heaven to *_divide_* the day from the night, and let them be for signs, for seasons, for days, and years.
* `Gen 1:18` To rule over the day and over the night, and to *_divide_* the light from the darkness. And God saw that it was good.
* `Gen 15:10` And he brought all these to him, divided them in the midst, and laid each piece one against another, but the birds he did not *_divide_*.
* `Gen 49:7` Cursed is their anger, for it was fierce, and their wrath, for it was cruel. I will *_divide_* them in Jacob and scatter them in Israel.
* `Gen 49:27` "Benjamin is a ravenous wolf. In the morning he shall devour the prey, and at night he shall *_divide_* the plunder."
* `Exo 14:16` But lift your rod and stretch out your hand over the sea and *_divide_* it. And the children of Israel shall go on dry ground through the midst of the sea.
* `Exo 15:9` The enemy said, 'I will pursue and I will overtake. I will *_divide_* the plunder. My lust shall be satisfied upon them. I will draw my sword. My hand shall destroy them.'
* `Exo 21:35` "And if one man's ox hurts another's so that he dies, then they shall sell the live ox and *_divide_* its money. And they shall also *_divide_* the dead ox.
* `Lev 1:17` And he shall cleave it with its wings, but shall not *_divide_* it apart. And the priest shall burn it upon the altar, upon the wood that is upon the fire. It is a burnt sacrifice, an offering made by fire, a sweet savor to the LORD.'"
* `Lev 5:8` And he shall bring them to the priest who shall offer that which is for the sin-offering first and wring off its head from its neck, but shall not *_divide_* it apart.
* `Lev 11:4` Nevertheless, these you shall not eat of those that chew the cud or of those that *_divide_* the hoof: the camel, because he chews the cud, but does not *_divide_* the hoof, he is unclean to you;
* `Lev 11:5` The coney, because he chews the cud, but does not *_divide_* the hoof, he is unclean to you;
* `Lev 11:6` The hare, because he chews the cud, but does not *_divide_* the hoof, he is unclean to you;
* `Num 31:27` And *_divide_* the plunder into two parts between those who took the war upon them, who went out to battle, and between all the congregation.
* `Num 33:54` And you shall *_divide_* the land by lot for an inheritance among your families. To the more you shall give the more inheritance and to the fewer you shall give the less inheritance. Every man's inheritance shall be in the place where his lot falls. According to the tribes of your fathers you shall inherit.
* `Num 34:17` "These are the names of the men who shall *_divide_* the land to you: Eleazar the priest and Joshua the son of Nun.
* `Num 34:18` And you shall take one prince of every tribe to *_divide_* the land by inheritance.
* `Num 34:29` These are those whom the LORD commanded to *_divide_* the inheritance to the children of Israel in the land of Canaan.
* `Deu 14:7` Nevertheless, these you shall not eat, of those that chew the cud or of those that *_divide_* the cloven hoof: the camel, the hare, and the coney. For they chew the cud, but do not *_divide_* the hoof; therefore, they are unclean to you.
* `Deu 19:3` You shall prepare yourself a way and *_divide_* into three parts the limits of your land which the LORD your God gives you to inherit so that every slayer may flee there.
* `Jsh 1:6` Be strong and of a good courage, for to this people you shall *_divide_* for an inheritance the land which I swore to their fathers to give them.
* `Jsh 13:6` And the inhabitants of the hill-country from Lebanon to Misrephoth-maim and all the Sidonians, I will drive them out from before the children of Israel. Only *_divide_* it by lot to the Israelites for an inheritance, as I have commanded you.
* `Jsh 13:7` Now therefore, *_divide_* this land for an inheritance to the nine tribes and the half tribe of Manasseh."
* `Jsh 18:5` And they shall *_divide_* it into seven parts. Judah shall abide in their border on the south, and the house of Joseph shall abide in their borders on the north.
* `Jsh 22:8` And he spoke to them, saying, "Return to your tents with great riches, with a very large number of livestock, with silver, with gold, with brass, with iron, and with very many clothes. *_Divide_* the plunder of your enemies with your brothers."
* `2Sa 19:29` And the king said to him, "Why do you speak anymore of your matters? I have said, 'You and Ziba *_divide_* the land.'"
* `1Ki 3:25` And the king said, "*_Divide_* the living child in two and give half to one and half to the other."
* `1Ki 3:26` Then the woman whose child the living one was spoke to the king, for her heart yearned upon her son, and she said, "O my lord, give her the living child and in no way slay him." But the other said, "Let him be neither mine nor yours, but *_divide_* him."
* `Job 27:17` He may lay it up, but the just shall put it on, and the innocent shall *_divide_* the silver.
* `Psa 55:9` Destroy, O Lord, and *_divide_* their languages, for I have seen violence and strife in the city.
* `Psa 60:6` God has spoken in his holiness, "I will rejoice. I will *_divide_* Shechem and measure out the valley of Succoth.
* `Psa 108:7` God has spoken in his holiness: "I will rejoice. I will *_divide_* Shechem and measure out the valley of Succoth.
* `Pro 16:19` It is better to be of a humble spirit with the lowly than to *_divide_* the plunder with the proud.
* `Isa 9:3` You have multiplied the nation. You have increased its joy. They joy before you according to the joy in harvest, and as men rejoice when they *_divide_* the plunder.
* `Isa 53:12` Therefore, I will *_divide_* to him a portion with the great, and he shall *_divide_* the plunder with the strong, because he has poured out his soul to death and he was numbered with the transgressors. And he bore the sin of many and made intercession for the transgressors.
* `Ezk 5:1` "And you, son of man, take a sharp knife, take a barber's razor, and cause it to pass upon your head and upon your beard. Then take balances to weigh and *_divide_* the hair.
* `Ezk 45:1` "'"Moreover, when you *_divide_* by lot the land for inheritance, you shall offer an oblation to the LORD, a holy portion of the land. The length shall be the length of twenty-five thousand reeds and the breadth shall be ten thousand. This shall be holy in all its borders on every side.
* `Ezk 47:21` "Thus you shall *_divide_* this land to yourselves according to the tribes of Israel.
* `Ezk 47:22` And it shall come to pass, that you shall *_divide_* it by lot for an inheritance to yourselves and to the strangers who sojourn among you who shall beget children among you. And they shall be to you as natives in the country among the children of Israel. They shall have inheritance with you among the tribes of Israel.
* `Ezk 48:29` This is the land which you shall *_divide_* by lot to the tribes of Israel for inheritance, and these are their portions," says the Lord GOD.
* `Dan 11:39` He shall do so in the strongest fortresses with a strange god, whom he shall acknowledge and increase with glory. And he shall cause them to rule over many, and shall *_divide_* the land for gain.
* `Luk 22:17` And he took the cup, gave thanks, and said, "Take this and *_divide_* it among yourselves.

_43 verses containing DIVIDE_

== DIVIDED

* `Gen 1:4` And God saw the light, that it was good, and God *_divided_* the light from the darkness.
* `Gen 1:7` And God made the firmament and *_divided_* the waters which were under the firmament from the waters which were above the firmament. And it was so.
* `Gen 10:5` By these the islands of the Gentiles were *_divided_* in their lands, each after his language, after their families, in their nations.
* `Gen 10:25` And to Eber two sons were born: the name of one was Peleg, for in his days the earth was *_divided_*, and his brother's name was Joktan.
* `Gen 10:32` These are the families of the sons of Noah after their generations, in their nations. And by these the nations were *_divided_* on the earth after the flood.
* `Gen 14:15` And he *_divided_* himself against them, he and his servants by night, and smote them and pursued them to Hobah, which is on the left hand of Damascus.
* `Gen 15:10` And he brought all these to him, *_divided_* them in the midst, and laid each piece one against another, but the birds he did not divide.
* `Gen 32:7` Then Jacob was greatly afraid and distressed. And he *_divided_* the people who were with him, along with the flocks, herds, and camels, into two bands,
* `Gen 33:1` And Jacob lifted up his eyes and looked, and behold, Esau came, and with him four hundred men. And he *_divided_* the children between Leah, Rachel, and the two women-servants.
* `Exo 14:21` And Moses stretched out his hand over the sea, and the LORD caused the sea to go back by a strong east wind all that night and made the sea dry land, and the waters were *_divided_*.
* `Num 26:53` "To these the land shall be *_divided_* for an inheritance according to the number of names.
* `Num 26:55` But the land shall be *_divided_* by lot. According to the names of the tribes of their fathers they shall inherit.
* `Num 26:56` According to the lot its possession shall be *_divided_* between many and few."
* `Num 31:42` And from the children of Israel's half, which Moses *_divided_* from the men who warred
* `Deu 4:19` And lest you should lift up your eyes to heaven, and when you see the sun, the moon, and the stars, even all the host of heaven, should be driven to worship them and serve them, which the LORD your God has *_divided_* to all nations under the whole heaven.
* `Deu 32:8` When the Most High *_divided_* to the nations their inheritance when he separated the sons of Adam, he set the bounds of the people according to the number of the children of Israel.
* `Jsh 14:5` As the LORD commanded Moses, so the children of Israel did, and they *_divided_* the land.
* `Jsh 18:10` And Joshua cast lots for them in Shiloh before the LORD. And there Joshua *_divided_* the land to the children of Israel according to their divisions.
* `Jsh 19:51` These are the inheritances which Eleazar the priest, and Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel *_divided_* for an inheritance by lot in Shiloh before the LORD, at the door of the Tabernacle of the Congregation. So they made an end of dividing the country.
* `Jsh 23:4` Behold, I have *_divided_* to you by lot these nations which remain to be an inheritance for your tribes, from the Jordan, with all the nations which I have cut off, even to the Great Sea westward.
* `Jdg 5:30` 'Have they not found, have they not *_divided_* the plunder: to every man a woman or two, to Sisera plunder of diverse colors, plunder of diverse colors of needle-work, of diverse colors of needle-work on both sides, suitable for the necks of those who take the plunder?'
* `Jdg 7:16` And he *_divided_* the three hundred men into three companies and put a trumpet in every man's hand, along with empty pitchers and lamps within the pitchers.
* `Jdg 9:43` And he took the people, *_divided_* them into three companies, and laid wait in the field. And he looked, and behold, the people had come out of the city. So he rose up against them and smote them.
* `Jdg 19:29` And when he had come into his house, he took a knife, laid hold upon his concubine, *_divided_* her with her bones into twelve pieces, and sent her into all the borders of Israel.
* `2Sa 1:23` "Saul and Jonathan were lovely and pleasant in their lives, and in their death they were not *_divided_*. They were swifter than eagles, they were stronger than lions.
* `1Ki 16:21` Then the people of Israel were *_divided_* into two parts: half of the people followed Tibni the son of Ginath to make him king, and half followed Omri.
* `1Ki 18:6` So they *_divided_* the land between them to pass throughout it. Ahab went one way by himself, and Obadiah went another way by himself.
* `2Ki 2:8` And Elijah took his mantle and wrapped it together and smote the waters, and they were *_divided_* here and there so that the two of them went over on dry ground.
* `1Ch 1:19` And to Eber were born two sons: the name of one was Peleg, because in his days the earth was *_divided_*, and his brother's name was Joktan.
* `1Ch 23:6` And David *_divided_* them into courses among the sons of Levi, namely, Gershon, Kohath, and Merari.
* `1Ch 24:4` And there were more chief men found among the sons of Eleazar than among the sons of Ithamar, and thus they were *_divided_*. Among the sons of Eleazar there were sixteen chief men of the house of their fathers and eight among the sons of Ithamar according to the house of their fathers.
* `1Ch 24:5` Thus they were *_divided_* by lot, one sort with another, for the governors of the sanctuary and governors of the house of God were of the sons of Eleazar and of the sons of Ithamar.
* `2Ch 35:13` And they roasted the passover with fire according to the ordinance, but the other holy offerings they boiled in pots, in cauldrons, and in pans, and *_divided_* them speedily among all the people.
* `Neh 9:11` And you *_divided_* the sea before them so that they went through the midst of the sea on the dry land. And you threw their persecutors into the depths, as a stone into the mighty waters.
* `Neh 9:22` Moreover, you gave them kingdoms and nations and *_divided_* them into corners. Thus they possessed the land of Sihon, the land of the king of Heshbon, and the land of Og king of Bashan.
* `Job 38:25` Who has *_divided_* a watercourse for the overflowing of waters or a way for the lightning of thunder,
* `Psa 68:12` Kings of armies fled apace. And she who waited at home *_divided_* the plunder.
* `Psa 74:13` You *_divided_* the sea by your strength. You broke the heads of the sea-monsters in the waters.
* `Psa 78:13` He *_divided_* the sea and caused them to pass through. He made the waters to stand like a heap.
* `Psa 78:55` He also cast out the heathen before them. He *_divided_* them an inheritance by line and made the tribes of Israel to dwell in their tents.
* `Psa 136:13` To him who *_divided_* the Red Sea into parts—for his mercy endures forever—
* `Isa 18:7` In that time the present shall be brought to the LORD of hosts from a people scattered and peeled, and from a people awesome from their beginning until now, a nation measured by line and trodden under foot, whose land the rivers have *_divided_*, to the place of the name of the LORD of hosts—mount Zion.
* `Isa 33:23` Your tacklings are loosened. They could not well strengthen their mast. They could not spread the sail. Then the loot of a great plunder is *_divided_*. The lame take the plunder.
* `Isa 34:17` And he has cast the lot for them, and his hand has *_divided_* it to them by line. They shall possess it forever. From generation to generation they shall dwell therein.
* `Isa 51:15` But I am the LORD your God who *_divided_* the sea, whose waves roared. The LORD of hosts is his name.
* `Lam 4:16` [AYIN] The anger of the LORD has *_divided_* them. He will no longer regard them. They did not respect the persons of the priests. They did not favor the elders.
* `Ezk 37:22` And I will make them one nation in the land upon the mountains of Israel, and one king shall be king to them all. And they shall no longer be two nations, neither shall they be *_divided_* into two kingdoms anymore at all,
* `Dan 2:41` And whereas you saw the feet and toes, part of potter's clay and part of iron, the kingdom shall be *_divided_*, but there shall be in it some of the strength of the iron, because you saw the iron mixed with the miry clay.
* `Dan 5:28` 'PERES': your kingdom is *_divided_*, and given to the Medes and Persians."
* `Dan 11:4` And when he stands up, his kingdom shall be broken and shall be *_divided_* toward the four winds of heaven, and not to his posterity, nor according to his dominion which he ruled, for his kingdom shall be plucked up, even for others beside those.
* `Hos 10:2` Their heart is *_divided_*. Now they shall be found faulty. He shall break down their altars. He shall destroy their images.
* `Joe 3:2` I will also gather all nations and bring them down into the valley of Jehoshaphat. I will plead with them there for my people and for my heritage Israel, whom they have scattered among the nations. They have *_divided_* my land,
* `Amo 7:17` Therefore, thus says the LORD: 'Your wife shall be a harlot in the city, and your sons and your daughters shall fall by the sword. Your land shall be *_divided_* by line, and you shall die in a polluted land. And Israel shall surely go from his land into captivity.'"
* `Mic 2:4` In that day one shall take up a parable against you and lament with a grievous lamentation and say, 'We are utterly wasted. He has changed the portion of my people. How he has removed it from me! To the rebellious he has *_divided_* our fields.'
* `Zch 14:1` Behold, the day of the LORD comes, and your plunder shall be *_divided_* in the midst of you.
* `Mth 12:25` And Jesus knew their thoughts, and said to them, "Every kingdom *_divided_* against itself is brought to desolation, and every city or house *_divided_* against itself shall not stand.
* `Mth 12:26` And if Satan casts out Satan, he is *_divided_* against himself. How then shall his kingdom stand?
* `Mth 27:35` And when they had crucified him, they *_divided_* his garments by casting lots so that it might be fulfilled which was spoken by the prophet, "They parted my garments among them, and upon my vesture they cast lots."
* `Mrk 3:24` And if a kingdom is *_divided_* against itself, that kingdom cannot stand.
* `Mrk 3:25` And if a house is *_divided_* against itself, that house cannot stand.
* `Mrk 3:26` And if Satan rises up against himself and is *_divided_*, he cannot stand, but has an end.
* `Mrk 6:41` And when he had taken the five loaves and the two fish, he looked up to heaven, blessed and broke the loaves, and gave them to his disciples to set before them. He also *_divided_* the two fish among them all.
* `Mrk 8:19` When I *_divided_* the five loaves among five thousand, how many baskets full of fragments did you take up?" They say to him, "Twelve."
* `Mrk 8:20` "And when I *_divided_* the seven among four thousand, how many baskets full of fragments did you take up?" And they said, "Seven."
* `Luk 11:17` But he, knowing their thoughts, said to them, "Every kingdom *_divided_* against itself is brought to desolation, and a house *_divided_* against a house falls.
* `Luk 11:18` If Satan also is *_divided_* against himself, how shall his kingdom stand? For you say that I cast out demons through Beelzebub.
* `Luk 12:52` For from now on there will be five in one house *_divided_*: three against two and two against three.
* `Luk 12:53` The father will be *_divided_* against the son and the son against the father, the mother against the daughter and the daughter against the mother, the mother-in-law against her daughter-in-law and the daughter-in-law against her mother-in-law."
* `Luk 15:12` And the younger of them said to his father, 'Father, give me the portion of goods that falls to me.' And he *_divided_* his living to them.
* `Act 13:19` And when he had destroyed seven nations in the land of Canaan, he *_divided_* their land to them by lot.
* `Act 14:4` But the multitude of the city was *_divided_*. And part held with the Jews and part with the apostles.
* `Act 23:7` And when he had said this, there arose a dissension between the Pharisees and the Sadducees, and the multitude was *_divided_*.
* `1Co 1:13` Is Christ *_divided_*? Was Paul crucified for you? Or were you baptized in the name of Paul?
* `Rev 16:19` And the great city was *_divided_* into three parts, and the cities of the nations fell. And great Babylon came in remembrance before God, to give to her the cup of the wine of the fierceness of his wrath.

_74 verses containing DIVIDED_

== DIVIDER

* `Luk 12:14` And he said to him, "Man, who made me a judge or a *_divider_* over you?"

_1 verse containing DIVIDER_

== DIVIDES

* `Lev 11:7` And the swine, though he *_divides_* the hoof and is cloven-footed, yet he does not chew the cud, he is unclean to you.
* `Lev 11:26` The carcasses of every beast which *_divides_* the hoof and is not cloven-footed, nor chews the cud, are unclean to you. Everyone who touches them shall be unclean.
* `Deu 14:8` And the swine, because it *_divides_* the hoof but does not chew the cud, is unclean to you. You shall not eat their flesh nor touch their dead carcass.
* `Job 26:12` He *_divides_* the sea by his power, and by his understanding he smites through the proud.
* `Psa 29:7` The voice of the LORD *_divides_* the flames of fire.
* `Jer 31:35` Thus says the LORD, who gives the sun for a light by day and the ordinances of the moon and of the stars for a light by night, who *_divides_* the sea when its waves roar, the LORD of hosts is his name:
* `Mth 25:32` And before him all nations shall be gathered, and he will separate them one from another, as a shepherd *_divides_* his sheep from the goats.
* `Luk 11:22` But when someone stronger than he comes upon him and overcomes him, he takes from him all his armor in which he trusted and *_divides_* his plunder.
* `Luk 12:13` And someone from the company said to him, "Master, speak to my brother so that he *_divides_* the inheritance with me."

_9 verses containing DIVIDES_

== DIVIDING

* `Jsh 19:49` When they had made an end of *_dividing_* the land for inheritance by their borders, the children of Israel gave an inheritance to Joshua the son of Nun among them.
* `Jsh 19:51` These are the inheritances which Eleazar the priest, and Joshua the son of Nun, and the heads of the fathers of the tribes of the children of Israel divided for an inheritance by lot in Shiloh before the LORD, at the door of the Tabernacle of the Congregation. So they made an end of *_dividing_* the country.
* `Isa 63:12` Who led them by the right hand of Moses with his glorious arm, *_dividing_* the water before them, to make himself an everlasting name,
* `Dan 7:25` And he shall speak great words against the most High and shall wear out the saints of the most High, and think to change times and laws. And they shall be given into his hand until a time and times and the *_dividing_* of time.
* `1Co 12:11` But the one and the same Spirit works all these, *_dividing_* to every man separately as he wills.
* `2Ti 2:15` Give diligence to show yourself approved to God, a workman who does not need to be ashamed, rightly *_dividing_* the word of truth.
* `Heb 4:12` For the word of God is living, powerful, and sharper than any two-edged sword, piercing even to the *_dividing_* apart of soul and spirit, of joints and marrow, and is a discerner of the thoughts and intents of the heart.

_7 verses containing DIVIDING_

== DIVINATION

* `Num 22:7` And the elders of Moab and the elders of Midian departed with the rewards of *_divination_* in their hand, and they came to Balaam and spoke to him the words of Balak.
* `Num 23:23` Surely there is no enchantment against Jacob, neither is there any *_divination_* against Israel. According to this time it shall be said of Jacob and of Israel, 'What God has wrought!'
* `Deu 18:10` There shall not be found among you anyone who makes his son or his daughter to pass through the fire, who uses *_divination_*, an observer of times, an enchanter, a witch,
* `2Ki 17:17` And they caused their sons and their daughters to pass through the fire, used *_divination_* and enchantments, and sold themselves to do evil in the sight of the LORD to provoke him to anger.
* `Ezk 12:24` For there shall no longer be any vain vision nor flattering *_divination_* within the house of Israel.
* `Ezk 13:6` They have seen vanity and lying *_divination_*, saying, 'The LORD says,' and the LORD has not sent them, and they have made others to hope that they would confirm the word.
* `Ezk 13:7` Have you not seen a vain vision, and have you not spoken a lying *_divination_* when you say, 'The LORD says it,' even though I have not spoken?"'"
* `Ezk 21:21` For the king of Babylon stood at the parting of the way, at the head of the two ways, to use *_divination_*: he shook the arrows, he consulted with images, and he examined the liver.
* `Ezk 21:22` At his right hand was the *_divination_* for Jerusalem to appoint captains, to open the mouth in the slaughter, to lift up the voice with shouting, to appoint battering rams against the gates, to cast a siege-mound, and to build a fort.
* `Ezk 21:23` And it shall be to them like a false *_divination_* in the sight of those who have sworn oaths, but he will call to remembrance their iniquity so that they may be taken.
* `Act 16:16` And it came to pass as we went to prayer, a certain woman-servant possessed with a spirit of *_divination_* met us, who brought her masters much gain by soothsaying.

_11 verses containing DIVINATION_

== DIVINATIONS

* `Jer 14:14` Then the LORD said to me, "The prophets prophesy lies in my name. I have not sent them, neither have I commanded them nor spoken to them. They prophesy to you false visions, *_divinations_*, predictions, and deceits of their heart.
* `Ezk 13:23` Therefore you shall see no more vanity nor divine *_divinations_*, for I will deliver my people out of your hand. And you shall know that I am the LORD."

_2 verses containing DIVINATIONS_

== DIVINE

* `Gen 44:15` And Joseph said to them, "What deed is this that you have done? Do you not know that such a man as I can certainly *_divine_*?"
* `1Sa 28:8` And Saul disguised himself and put on other clothing, and he went, and two men with him, and they came to the woman by night. And he said, "I pray you, *_divine_* to me by the familiar spirit and bring up for me whom I shall name to you."
* `Pro 16:10` A *_divine_* sentence is in the lips of the king. His mouth does not transgress in judgment.
* `Ezk 13:9` "And my hand shall be upon the prophets who see vanity and who *_divine_* lies. They shall not be in the assembly of my people, neither shall they be written in the writing of the house of Israel, neither shall they enter into the land of Israel. And you shall know that I am the Lord GOD.
* `Ezk 13:23` Therefore you shall see no more vanity nor *_divine_* divinations, for I will deliver my people out of your hand. And you shall know that I am the LORD."
* `Ezk 21:29` While they see vanity for you, while they *_divine_* a lie for you—to bring you upon the necks of the wicked who are slain, whose day has come when their iniquity has an end.
* `Mic 3:6` "Therefore, night shall be for you so that you shall not have a vision. And it shall be dark for you so that you shall not *_divine_*. And the sun shall go down over the prophets, and the day shall be dark over them.
* `Mic 3:11` Her heads judge for bribes, her priests teach for payment, and her prophets *_divine_* for money. Yet they will lean upon the LORD and say, "Is the LORD not among us? No evil can come upon us."
* `Heb 9:1` Then truly the first covenant also had ordinances of *_divine_* service and an earthly sanctuary.
* `2Pe 1:3` According as his *_divine_* power has given to us all things that pertain to life and godliness through the knowledge of him who has called us to glory and virtue,
* `2Pe 1:4` Through which exceedingly great and precious promises are given to us, so that by these you might be partakers of the *_divine_* nature, having escaped the corruption that is in the world through lust.

_11 verses containing DIVINE_

== DIVINERS

* `Deu 18:14` For these nations, which you shall possess, listened to observers of times and to *_diviners_*. But as for you, the LORD your God has not allowed you to do so.
* `1Sa 6:2` And the Philistines called for the priests and the *_diviners_*, saying, "What shall we do to the ark of the LORD? Tell us with what we shall send it to its place."
* `Isa 44:25` Who frustrates the tokens of the liars and makes *_diviners_* mad, who turns wise men backward and makes their knowledge foolish,
* `Jer 27:9` Therefore, do not listen to your prophets, to your *_diviners_*, to your dreamers, to your enchanters, nor to your sorcerers who speak to you, saying, "You shall not serve the king of Babylon."
* `Jer 29:8` For thus says the LORD of hosts, the God of Israel: 'Do not let your prophets and your *_diviners_* who are in the midst of you deceive you, neither listen to your dreams which you cause to be dreamed,
* `Mic 3:7` Then the seers shall be ashamed and the *_diviners_* confounded. Indeed, they shall all cover their lips, for there is no answer from God."
* `Zch 10:2` For the idols have spoken vanity, and the *_diviners_* have seen a lie. They have told false dreams. They comfort in vain. Therefore, they went their way like a flock. They were troubled because there was no shepherd.

_7 verses containing DIVINERS_

== DIVINES

* `Gen 44:5` Is this not the cup in which my lord drinks and by which indeed he *_divines_*? You have done evil in so doing.'"

_1 verse containing DIVINES_

== DIVINING

* `Ezk 22:28` And her prophets have daubed them with untempered mortar, seeing vanity and *_divining_* lies for them, saying, 'Thus says the Lord GOD,' when the LORD has not spoken.

_1 verse containing DIVINING_

== DIVISION

* `Exo 8:23` And I will put a *_division_* between my people and your people. Tomorrow this sign shall be."'"
* `2Ch 35:5` And stand in the holy place according to the divisions of the families of the fathers of your brothers the people, and according to the *_division_* of the families of the Levites.
* `Luk 12:51` Do you suppose that I have come to give peace on earth? I tell you, no, but rather *_division_*.
* `Jhn 7:43` So there was a *_division_* among the people because of him.
* `Jhn 9:16` Therefore, some of the Pharisees said, "This man is not from God because he does not keep the sabbath." Others said, "How can a man who is a sinner do such miracles?" And there was a *_division_* among them.
* `Jhn 10:19` There was a *_division_* therefore again among the Jews because of these sayings.

_6 verses containing DIVISION_

== DIVISIONS

* `Jsh 11:23` So Joshua took the whole land, according to all that the LORD said to Moses, and Joshua gave it for an inheritance to Israel according to their *_divisions_* by their tribes. And the land rested from war.
* `Jsh 12:7` And these are the kings of the country whom Joshua and the children of Israel smote on this side of the Jordan on the west, from Baal-gad in the valley of Lebanon, even to the mount Halak that goes up to Seir—which Joshua gave to the tribes of Israel for a possession according to their *_divisions_*,
* `Jsh 18:10` And Joshua cast lots for them in Shiloh before the LORD. And there Joshua divided the land to the children of Israel according to their *_divisions_*.
* `Jdg 5:15` And the princes of Issachar were with Deborah, even Issachar, and also Barak. He was sent on foot into the valley. For the *_divisions_* of Reuben there were great thoughts of heart.
* `Jdg 5:16` Why did you abide among the sheep-folds to hear the bleatings of the flocks? For the *_divisions_* of Reuben there were great searchings of heart.
* `1Ch 24:1` Now these are the *_divisions_* of the sons of Aaron: The sons of Aaron: Nadab, Abihu, Eleazar, and Ithamar.
* `1Ch 26:1` Concerning the *_divisions_* of the gatekeepers: Of the Korhites was Meshelemiah the son of Kore, of the sons of Asaph.
* `1Ch 26:12` Among these were the *_divisions_* of the gatekeepers, even among the chief men, having wards against one another, to minister in the house of the LORD.
* `1Ch 26:19` These are the *_divisions_* of the gatekeepers among the sons of Kore and among the sons of Merari.
* `2Ch 35:5` And stand in the holy place according to the *_divisions_* of the families of the fathers of your brothers the people, and according to the division of the families of the Levites.
* `2Ch 35:12` And they removed the burnt-offerings so that they might give according to the *_divisions_* of the families of the people to offer to the LORD, as it is written in the book of Moses. And they did so with the oxen.
* `Ezr 6:18` And they set the priests in their *_divisions_* and the Levites in their courses for the service of God who is at Jerusalem, as it is written in the book of Moses.
* `Neh 11:36` And some *_divisions_* of the Levites in Judah were joined to Benjamin.
* `Rom 16:17` Now I implore you, brothers, mark those who cause *_divisions_* and offenses contrary to the doctrine which you have learned, and avoid them.
* `1Co 1:10` Now I implore you, brothers, by the name of our Lord Jesus Christ, that you all speak the same thing and that there be no *_divisions_* among you, but that you be perfectly joined together in the same mind and in the same judgment.
* `1Co 3:3` Because you are still carnal. For whereas there is among you envying, strife, and *_divisions_*, are you not carnal and walk as men?
* `1Co 11:18` For first of all, when you come together in the church, I hear that there are *_divisions_* among you, and I partly believe it.

_17 verses containing DIVISIONS_

== DIVORCE

* `Jer 3:8` And I saw that for all the causes by which backsliding Israel committed adultery, I had put her away and given her a bill of *_divorce_*. Yet her treacherous sister Judah did not fear, but went and played the harlot also.

_1 verse containing DIVORCE_

== DIVORCED

* `Lev 21:14` A widow, a *_divorced_* woman, a profane woman, or a harlot, these he shall not take, but he shall take a virgin of his own people for a wife,
* `Lev 22:13` But if the priest's daughter is a widow or *_divorced_*, has no child, and has returned to her father's house as in her youth, she shall eat her father's food, but no stranger shall eat it.
* `Num 30:9` "But every vow of a widow and of her who is *_divorced_*, with which they have bound their souls, shall stand against her.
* `Mth 5:32` But I say to you, that whoever puts away his wife, except for the cause of lewdness, causes her to commit adultery. And whoever marries her who is *_divorced_*, commits adultery.

_4 verses containing DIVORCED_

== DIVORCEMENT

* `Deu 24:1` "When a man has taken a wife and married her, and it comes to pass that she finds no favor in his eyes because he has found some uncleanness in her, let him write her a bill of *_divorcement_*, give it in her hand, and send her out of his house.
* `Deu 24:3` And if the latter husband hates her and writes her a bill of *_divorcement_*, gives it in her hand, and sends her out of his house, or if the latter husband dies, who took her to be his wife,
* `Isa 50:1` Thus says the LORD: "Where is the bill of your mother's *_divorcement_*, whom I have put away? Or which of my creditors is it to whom I have sold you? Behold, for your iniquities you have sold yourselves, and for your transgressions your mother is put away.
* `Mth 5:31` "It has been said, 'Whoever puts away his wife, let him give her a writing of *_divorcement_*.'
* `Mth 19:7` They say to him, "Why then did Moses command to 'give a writing of *_divorcement_* and to put her away'?"
* `Mrk 10:4` And they said, "Moses 'allowed a man to write a bill of *_divorcement_* and to put her away.'"

_6 verses containing DIVORCEMENT_

== DIZAHAB

* `Deu 1:1` These are the words which Moses spoke to all Israel on the east side of the Jordan in the wilderness, in the plain over against Suf, between Paran, Tophel, Laban, Hazeroth, and *_Dizahab_*.

_1 verse containing DIZAHAB_

