= DROVE - DYSENTERY
:toc:

== DROVE

* `Gen 3:24` So he *_drove_* out the man, and he placed Cherubim at the east of the garden of Eden and a flaming sword which turned every way to keep the way of the tree of life.
* `Gen 15:11` And when the birds came down upon the carcasses, Abram *_drove_* them away.
* `Gen 32:16` And he delivered them into the hand of his servants, every *_drove_* by themselves, and said to his servants, "Pass over before me and put a space between *_drove_* and *_drove_*."
* `Gen 33:8` And he said, "What do you mean by all this *_drove_* which I met?" And he said, "These are to find grace in the sight of my lord."
* `Exo 2:17` And the shepherds came and *_drove_* them away, but Moses stood up and helped them and watered their flock.
* `Num 21:32` And Moses sent to explore Jaazer, and they took its villages and *_drove_* out the Amorites who were there.
* `Jsh 15:14` And Caleb *_drove_* from there the three sons of Anak: Sheshai, Ahiman, and Talmai, the children of Anak.
* `Jsh 24:12` And I sent the hornet before you, which *_drove_* them out from before you, even the two kings of the Amorites, but not with your sword nor with your bow.
* `Jsh 24:18` And the LORD *_drove_* out from before us all the people, even the Amorites who dwelt in the land. Therefore, we will also serve the LORD, for he is our God."
* `Jdg 1:19` And the LORD was with Judah, and he *_drove_* out the inhabitants of the mountain, but could not drive out the inhabitants of the valley because they had chariots of iron.
* `Jdg 6:9` And I delivered you from the hand of the Egyptians and from the hand of all who oppressed you. I *_drove_* them out from before you and gave you their land.
* `1Sa 19:10` And Saul sought to smite David even to the wall with the javelin, but he slipped away from Saul's presence as he *_drove_* the javelin into the wall. And David fled and escaped that night.
* `1Sa 30:20` And David took all the flocks and the herds which they *_drove_* before those other livestock and said, "This is David's plunder."
* `2Sa 6:3` And they set the ark of God upon a new cart and brought it out of the house of Abinadab that was in Gibeah. And Uzzah and Ahio the sons of Abinadab *_drove_* the new cart.
* `2Ki 16:6` At that time Rezin king of Syria recovered Elath to Syria and *_drove_* the Jews from Elath. And the Syrians came to Elath and have dwelt there to this day.
* `2Ki 17:21` For he rent Israel from the house of David, and they made Jeroboam the son of Nebat king. And Jeroboam *_drove_* Israel from following the LORD and made them sin a great sin.
* `1Ch 8:13` Beriah and Shema (who were heads of the fathers of the inhabitants of Ajalon, who *_drove_* away the inhabitants of Gath),
* `1Ch 13:7` And they carried the ark of God in a new cart out of the house of Abinadab. And Uzza and Ahio *_drove_* the cart.
* `2Ch 20:7` Are you not our God who *_drove_* out the inhabitants of this land before your people Israel and gave it to the offspring of Abraham your friend forever?
* `Psa 34:1` [A Psalm of David: when he changed his behavior before Abimelech, who *_drove_* him away, and he departed.] I will bless the LORD at all times. His praise shall continually be in my mouth.
* `Psa 44:2` How you *_drove_* out the heathen with your hand and planted them, how you afflicted the people and cast them out.
* `Jer 46:15` Why are your valiant men swept away? They did not stand because the LORD *_drove_* them.
* `Hab 3:6` He stood and measured the earth. He beheld and *_drove_* apart the nations. The everlasting mountains were scattered and the perpetual hills bowed. His ways are everlasting.
* `Jhn 2:15` And when he had made a scourge of small cords, he *_drove_* them all out of the temple, with the sheep and the oxen, and poured out the changers' money and overthrew the tables,
* `Act 7:45` Which also our fathers, in their turn, brought in with Joshua when they entered into the possession of the nations, whom God *_drove_* out before the face of our fathers until the days of David,
* `Act 18:16` And he *_drove_* them from the judgment-seat.

_26 verses containing DROVE_

== DROVES

* `Gen 32:19` And likewise he commanded the second, the third, and all who followed the *_droves_*, saying, "In this manner you shall speak to Esau when you find him.

_1 verse containing DROVES_

== DROWN

* `Sos 8:7` Many waters cannot quench love, neither can the floods *_drown_* it. If a man would give all the substance of his house for love, it would utterly be despised.
* `1Ti 6:9` But those who wish to be rich fall into temptation, a snare, and into many foolish and hurtful lusts which *_drown_* men in destruction and perdition.

_2 verses containing DROWN_

== DROWNED

* `Exo 15:4` "Pharaoh's chariots and his host he has cast into the sea. His chosen captains are also *_drowned_* in the Red Sea.
* `Amo 8:8` Shall the land not tremble for this, and everyone mourn who dwells in it? It shall rise up wholly as a flood, and it shall be cast out and *_drowned_* as by the flood of Egypt.
* `Amo 9:5` And the Lord GOD of hosts is he who touches the land, and it shall melt, and all who dwell in it shall mourn. And it shall rise up wholly like a flood, and shall be *_drowned_* as by the flood of Egypt.
* `Mth 18:6` But whoever causes one of these little ones who believe in me to sin, it would be better for him that a millstone were hanged around his neck and that he were *_drowned_* in the depth of the sea.
* `Heb 11:29` By faith they passed through the Red Sea as if by dry land, which the Egyptians essaying to do were *_drowned_*.

_5 verses containing DROWNED_

== DROWSINESS

* `Pro 23:21` For the drunkard and the glutton shall come to poverty, and *_drowsiness_* shall clothe a man with rags.

_1 verse containing DROWSINESS_

== DRUNK

* `Deu 32:42` I will make my arrows *_drunk_* with blood, and my sword shall devour flesh, and that with the blood of the slain and of the captives from the beginning of revenges upon the enemy.'
* `2Sa 11:13` And when David had called him, he ate and drank before him, and he made him *_drunk_*. And at evening he went out to lie on his bed with the servants of his lord, but did not go down to his house.
* `1Ki 16:9` And his servant Zimri, captain of half his chariots, conspired against him as he was in Tirzah drinking himself *_drunk_* in the house of Arza, steward of his house in Tirzah.
* `1Ki 20:16` And they went out at noon. But Ben-hadad was drinking himself *_drunk_* in the pavilions—he and the kings, the thirty-two kings who helped him.
* `Isa 63:6` And I will tread down the people in my anger and make them *_drunk_* in my fury, and I will bring their strength down to the earth."
* `Jer 46:10` For this is the day of the Lord GOD of hosts, a day of vengeance, so that he may avenge himself of his adversaries. And the sword shall devour and shall be satiated and made *_drunk_* with their blood, for the Lord GOD of hosts has a sacrifice in the north country by the Euphrates River.
* `Jer 51:57` "And I will make *_drunk_* her princes, her wise men, her captains, her rulers, and her mighty men. And they shall sleep a perpetual sleep and not wake," says the King, whose name is the LORD of hosts.
* `Hab 2:15` Woe to him who gives his neighbor drink, pouring out your bottle to him, and also making him *_drunk_*, so that you may look at their nakedness!
* `Eph 5:18` And do not be *_drunk_* with wine, in which is excess, but be filled with the Spirit,
* `Rev 17:2` With whom the kings of the earth have committed lewd deeds and the inhabitants of the earth have been made *_drunk_* with the wine of her lewdness."

_10 verses containing DRUNK_

== DRUNKARD

* `Deu 21:20` And they shall say to the elders of his city, 'This son of ours is stubborn and rebellious. He will not obey our voice. He is a glutton and a *_drunkard_*.'
* `Pro 23:21` For the *_drunkard_* and the glutton shall come to poverty, and drowsiness shall clothe a man with rags.
* `Pro 26:9` As a thorn goes up into the hand of a *_drunkard_*, so is a parable in the mouth of fools.
* `Isa 24:20` The earth shall reel to and fro like a *_drunkard_* and sway to and fro like a hammock. Its transgression shall be heavy upon it. It shall fall and not rise again.
* `Mth 11:19` The Son of man came eating and drinking, and they say, 'Behold, a gluttonous man and a *_drunkard_*, a friend of tax collectors and sinners.' But wisdom is justified by her children."
* `Luk 7:34` The Son of man has come eating and drinking, and you say, 'Behold, a gluttonous man, a *_drunkard_*, and a friend of tax collectors and sinners.'
* `1Co 5:11` But now I have written to you not to keep company with any man who is called a brother if he is a lewd person, covetous, an idolater, a railer, a *_drunkard_*, or an extortioner. Do not even eat with such a person.

_7 verses containing DRUNKARD_

== DRUNKARDS

* `Psa 69:12` Those who sit in the gate speak against me. I was the song of the *_drunkards_*.
* `Pro 23:20` Do not be among *_drunkards_*, among riotous eaters of flesh,
* `Isa 28:1` Woe to the crown of pride, to the *_drunkards_* of Ephraim, whose glorious beauty is a fading flower, who are on the head of the rich valleys of those who are overcome with wine!
* `Isa 28:3` The crown of pride of the *_drunkards_* of Ephraim shall be trodden under feet.
* `Joe 1:5` Awake, you *_drunkards_*, and weep. Howl, all you drinkers of wine, because of the new wine, for it is cut off from your mouth.
* `Nah 1:10` For while they are tangled together as thorns and while they are drunken as *_drunkards_*, they shall be devoured as fully dried stubble.
* `1Co 6:10` Thieves, covetous, *_drunkards_*, revilers, nor extortioners shall inherit the kingdom of God.

_7 verses containing DRUNKARDS_

== DRUNKEN

* `Gen 9:21` And he drank the wine and was *_drunken_* and uncovered within his tent.
* `1Sa 1:13` Now Hannah spoke in her heart. Only her lips moved, but her voice was not heard. Therefore, Eli thought she had been *_drunken_*.
* `1Sa 1:14` And Eli said to her, "How long will you be *_drunken_*? Put away your wine from you."
* `1Sa 25:36` And Abigail came to Nabal, and behold, he held a feast in his house, like the feast of a king. And Nabal's heart was merry within him, for he was very *_drunken_*. Therefore, she told him nothing at all until the morning light.
* `Job 12:25` They grope in the dark without light, and he makes them to stagger like a *_drunken_* man."
* `Psa 107:27` They reel to and fro and stagger like a *_drunken_* man. They are at their wit's end.
* `Isa 19:14` The LORD has mingled a perverse spirit in the midst of it. And they have caused Egypt to err in every work of it, as a *_drunken_* man staggers in his vomit.
* `Isa 29:9` Stay yourselves, and wonder. Cry out, and cry. They are *_drunken_*, but not with wine. They stagger, but not with strong drink.
* `Isa 49:26` And I will feed those who oppress you with their own flesh, and they shall be *_drunken_* with their own blood, as with sweet wine. And all flesh shall know that I, the LORD, am your Savior and your Redeemer, the mighty One of Jacob."
* `Isa 51:21` Now therefore, hear this, you afflicted and *_drunken_*, but not with wine.
* `Jer 23:9` My heart within me is broken because of the prophets. All my bones shake. I am like a *_drunken_* man and like a man whom wine has overcome because of the LORD and because of the words of his holiness.
* `Jer 25:27` "Therefore, you shall say to them, 'Thus says the LORD of hosts, the God of Israel: "Drink, be *_drunken_*, vomit, fall, and rise no more because of the sword which I will send among you."'
* `Jer 48:26` "Make him *_drunken_*, for he magnified himself against the LORD. Moab shall also wallow in his vomit and shall also be in derision.
* `Jer 51:7` Babylon has been a golden cup in the LORD'S hand, who made all the earth *_drunken_*. The nations have drank her wine; therefore, the nations are mad.
* `Jer 51:39` In their heat I will make their feasts, and I will make them *_drunken_* so that they may rejoice and sleep a perpetual sleep and not wake," says the LORD.
* `Lam 3:15` He has filled me with bitterness. He has made me *_drunken_* with wormwood.
* `Lam 4:21` [SHIN] Rejoice and be glad, O daughter of Edom, who dwells in the land of Uz. The cup shall also pass through to you. You shall be *_drunken_* and shall make yourself naked.
* `Ezk 39:19` And you shall eat fat until you are full and drink blood until you are *_drunken_* at my sacrifice which I have sacrificed for you.
* `Nah 1:10` For while they are tangled together as thorns and while they are *_drunken_* as drunkards, they shall be devoured as fully dried stubble.
* `Nah 3:11` You also shall be *_drunken_*. You shall be hid. You also shall seek strength because of the enemy.
* `Mth 24:49` And begins to beat his fellow-servants and to eat and drink with the *_drunken_*,
* `Luk 12:45` But if that servant says in his heart, 'My lord delays his coming,' and begins to beat the men-servants and women-servants and to eat, drink, and to be *_drunken_*,
* `Act 2:15` For these are not *_drunken_*, as you suppose, seeing it is but the third hour of the day.
* `1Co 11:21` For in eating, each one takes before another his own supper. And one is hungry and another is *_drunken_*.
* `1Th 5:7` For those who sleep, sleep in the night, and those who are *_drunken_*, are *_drunken_* in the night.
* `Rev 17:6` And I saw the woman *_drunken_* with the blood of the saints and with the blood of the martyrs of Jesus. And when I saw her, I wondered with great wonder.

_26 verses containing DRUNKEN_

== DRUNKENNESS

* `Ecc 10:17` You are blessed, O land, when your king is the son of nobles, and your princes eat in due season—for strength and not for *_drunkenness_*!
* `Jer 13:13` Then you shall say to them, 'Thus says the LORD: "Behold, I will fill all the inhabitants of this land, even the kings who sit upon David's throne, the priests, the prophets, and all the inhabitants of Jerusalem with *_drunkenness_*.
* `Ezk 23:33` You shall be filled with *_drunkenness_* and sorrow, with the cup of astonishment and desolation, with the cup of your sister Samaria.
* `Luk 21:34` "And take heed to yourselves, lest at any time your hearts are overcharged with surfeiting, *_drunkenness_*, and cares of this life, and that day come upon you unexpectedly.
* `Rom 13:13` Let us walk honestly, as in the day, not in rioting and *_drunkenness_*, not in lewdness and wantonness, and not in strife and envying.
* `Gal 5:21` Envyings, murders, *_drunkenness_*, revelings, and such like these, of which I tell you before, as I have also told you in time past, that those who do such things shall not inherit the kingdom of God.

_6 verses containing DRUNKENNESS_

== DRUSILLA

* `Act 24:24` And after some days, Felix came with his wife *_Drusilla_*, who was Jewish. He sent for Paul and heard him concerning the faith in Christ.

_1 verse containing DRUSILLA_

== DRY

* `Gen 1:9` And God said, "Let the waters under the heaven be gathered into one place, and let the *_dry_* land appear." And it was so.
* `Gen 1:10` And God called the *_dry_* land "earth," and he called the collection of waters "seas." And God saw that it was good.
* `Gen 7:22` All in whose nostrils was the breath of life, of all that was on the *_dry_* land, died.
* `Gen 8:13` And it came to pass in the six hundred and first year, in the first month, on the first day of the month, the waters were dried from off the earth. And Noah removed the covering of the ark and looked, and behold, the face of the ground was *_dry_*.
* `Exo 4:9` And it shall come to pass, if they will not believe even these two signs, neither listen to your voice, that you shall take some of the water from the river and pour it upon the *_dry_* land. And the water which you take out of the river shall become blood upon the *_dry_* land."
* `Exo 14:16` But lift your rod and stretch out your hand over the sea and divide it. And the children of Israel shall go on *_dry_* ground through the midst of the sea.
* `Exo 14:21` And Moses stretched out his hand over the sea, and the LORD caused the sea to go back by a strong east wind all that night and made the sea *_dry_* land, and the waters were divided.
* `Exo 14:22` And the children of Israel went into the midst of the sea upon the *_dry_* ground, and the waters were a wall to them on their right hand and on their left.
* `Exo 14:29` But the children of Israel walked upon *_dry_* land in the midst of the sea, and the waters were a wall to them on their right hand and on their left.
* `Exo 15:19` For the horse of Pharaoh went in with his chariots and with his horsemen into the sea, and the LORD brought back the waters of the sea upon them, but the children of Israel went on *_dry_* land in the midst of the sea.
* `Lev 7:10` And every food-offering mingled with oil, and *_dry_*, all the sons of Aaron shall have, one as much as another.
* `Deu 29:19` And it should come to pass when he hears the words of this curse, that he should bless himself in his heart, saying, 'I shall have peace, though I walk in the imagination of my heart,' to sweep away the moist with the *_dry_*.
* `Jsh 3:17` And the priests who bore the ark of the covenant of the LORD stood firm on *_dry_* ground in the midst of the Jordan, and all the Israelites passed over on *_dry_* ground until all the people had quite passed over the Jordan.
* `Jsh 4:18` And it came to pass when the priests who bore the ark of the covenant of the LORD had come up out of the midst of the Jordan, and the soles of the priests' feet were lifted up upon the *_dry_* land, that the waters of the Jordan returned to their place and flowed over all its banks as they did before.
* `Jsh 4:22` Then you shall let your children know, saying, 'Israel came over this Jordan on *_dry_* land.'
* `Jsh 9:5` And also old and patched shoes upon their feet and old garments upon themselves. And all the bread of their provision was *_dry_* and moldy.
* `Jsh 9:12` Our bread we took hot for our provision out of our houses on the day we came forth to go to you, but now, behold, it is *_dry_* and moldy.
* `Jdg 6:37` Behold, I will put a fleece of wool on the floor. And if the dew is on the fleece only, and it is *_dry_* upon all the earth beside it, then I shall know that you will save Israel by my hand, as you have said."
* `Jdg 6:39` And Gideon said to God, "Do not let your anger be hot against me, and I will speak only one more time. Let me make trial, I pray you, only one more time with the fleece. Let it now be *_dry_* only upon the fleece, and upon all the ground let there be dew."
* `Jdg 6:40` And God did so that night. For it was *_dry_* upon the fleece only, and there was dew on all the ground.
* `2Ki 2:8` And Elijah took his mantle and wrapped it together and smote the waters, and they were divided here and there so that the two of them went over on *_dry_* ground.
* `Neh 9:11` And you divided the sea before them so that they went through the midst of the sea on the *_dry_* land. And you threw their persecutors into the depths, as a stone into the mighty waters.
* `Job 12:15` Behold, he withholds the waters, and they *_dry_* up. He also sends them out, and they overturn the earth.
* `Job 13:25` Will you terrify a leaf driven to and fro? And will you pursue the *_dry_* stubble?
* `Job 15:30` He shall not depart out of darkness. The flame shall *_dry_* up his branches, and by the breath of his mouth he shall go away.
* `Psa 63:1` [A Psalm of David: when he was in the wilderness of Judah.] O God, you are my God. Early I will seek you. My soul thirsts for you. My flesh longs for you in a *_dry_* and thirsty land where there is no water.
* `Psa 66:6` He turned the sea into *_dry_* land. They went through the flood on foot. There we rejoiced in him.
* `Psa 68:6` God sets the solitary in families. He brings out those who are bound with chains. But the rebellious dwell in a *_dry_* land.
* `Psa 95:5` The sea is his, and he made it. And his hands formed the *_dry_* land.
* `Psa 105:41` He opened the rock, and the waters gushed out. They ran in the *_dry_* places like a river.
* `Psa 107:33` He turns rivers into a wilderness, the water-springs into *_dry_* ground,
* `Psa 107:35` He turns the wilderness into a standing water and *_dry_* ground into water-springs.
* `Pro 17:1` Better is a *_dry_* morsel and quietness with it, than a house full of sacrifices with strife.
* `Isa 25:5` Like the heat in a *_dry_* place, you will bring down the noise of strangers. Like the heat with the shade of a cloud, the song of the terrible ones shall be brought low.
* `Isa 32:2` And a man shall be like a hiding-place from the wind and a covert from the tempest, like streams of water in a *_dry_* place, like the shade of a great rock in a weary land.
* `Isa 41:18` I will open rivers in high places and fountains in the midst of the valleys. I will make the wilderness a pool of water and the *_dry_* land springs of water.
* `Isa 42:15` I will make waste mountains and hills and *_dry_* up all their herbs. And I will make the rivers to be islands, and I will *_dry_* up the pools.
* `Isa 44:3` For I will pour water upon him who is thirsty and floods upon the *_dry_* ground. I will pour my Spirit upon your descendants and my blessing upon your offspring.
* `Isa 44:27` Who says to the deep, 'Be *_dry_*,' and I will *_dry_* up your rivers,
* `Isa 50:2` Why, when I came, was there no man? Why, when I called, was there no one to answer? Is my hand shortened at all so that it cannot redeem? Or have I no power to deliver? Behold, at my rebuke I *_dry_* up the sea. I make the rivers a wilderness. Their fish become putrid because there is no water and die for thirst.
* `Isa 53:2` For he shall grow up before him as a tender plant and as a root out of a *_dry_* ground. He has no form nor majesty. And when we see him, there is no beauty that we should desire him.
* `Isa 56:3` Do not let the son of the stranger, who has joined himself to the LORD, speak, saying, "The LORD has utterly separated me from his people," neither let the eunuch say, "Behold, I am a *_dry_* tree."
* `Jer 4:11` At that time it shall be said to this people and to Jerusalem, "A *_dry_* wind of the high places in the wilderness toward the daughter of my people, not to fan, nor to cleanse,
* `Jer 50:12` Your mother shall be greatly confounded. She who bore you shall be ashamed. Behold, the hindmost of the nations shall be a wilderness, a *_dry_* land, and a desert.
* `Jer 51:36` Therefore, thus says the LORD: "Behold, I will plead your cause and take vengeance for you, and I will *_dry_* up her sea and make her springs *_dry_*.
* `Jer 51:43` Her cities are a desolation, a *_dry_* land, and a wilderness, a land in which no man dwells, neither does any son of man pass by it.
* `Ezk 17:24` And all the trees of the field shall know that I, the LORD, have brought down the high tree, have exalted the low tree, have dried up the green tree, and have made the *_dry_* tree to flourish. I, the LORD, have spoken and have done it."
* `Ezk 19:13` And now she is planted in the wilderness in a *_dry_* and thirsty ground.
* `Ezk 20:47` And say to the forest of the south, 'Hear the word of the LORD. Thus says the Lord GOD: "Behold, I will kindle a fire in you, and it shall devour every green tree and every *_dry_* tree in you. The flaming flame shall not be quenched, and all faces from the south to the north shall be burned therein.
* `Ezk 30:12` And I will make the rivers *_dry_*, and sell the land into the hand of the wicked. And I will make the land desolate and all that is in it by the hand of strangers. I, the LORD, have spoken it."
* `Ezk 37:2` And he caused me to pass by them around, and behold, there were very many in the open valley, and behold, they were very *_dry_*.
* `Ezk 37:4` Again he said to me, "Prophesy upon these bones, and say to them, 'O *_dry_* bones, hear the word of the LORD.
* `Hos 2:3` Lest I strip her naked, set her as in the day that she was born, make her as a wilderness, and set her like a *_dry_* land and kill her with thirst.
* `Hos 9:14` Give them, O LORD—what will you give? Give them a miscarrying womb and *_dry_* breasts.
* `Hos 13:15` Though he is fruitful among his brothers, an east wind shall come, the wind of the LORD shall come up from the wilderness, and his spring shall become *_dry_* and his fountain shall be dried up. He shall pillage the treasure of all precious vessels.
* `Jna 1:9` And he said to them, "I am a Hebrew, and I fear Yahweh, the God of heaven, who has made the sea and the *_dry_* land."
* `Jna 2:10` And the LORD spoke to the fish, and it vomited out Jonah upon the *_dry_* land.
* `Nah 1:4` He rebukes the sea and makes it *_dry_*, and dries up all the rivers. Bashan and Carmel languish, and the flower of Lebanon languishes.
* `Zph 2:13` And he will stretch out his hand against the north and destroy Assyria, and will make Nineveh a desolation and *_dry_* like a wilderness.
* `Hag 2:6` For thus says the LORD of hosts: 'Yet once, it is a little while, and I will shake the heavens, the earth, the sea, and the *_dry_* land,
* `Zch 10:11` And he shall pass through the sea with affliction and shall smite the waves in the sea, and all the deeps of the river shall *_dry_* up. And the pride of Assyria shall be brought down, and the scepter of Egypt shall depart.
* `Mth 12:43` "When the unclean spirit has gone out of a man, he walks through *_dry_* places, seeking rest, and he finds none.
* `Luk 11:24` "When the unclean spirit has gone out of a man, he walks through *_dry_* places seeking rest, and finding none, he says, 'I will return to my house where I came out.'
* `Luk 23:31` For if they do these things in a green tree, what will be done in the *_dry_*?"
* `Heb 11:29` By faith they passed through the Red Sea as if by *_dry_* land, which the Egyptians essaying to do were drowned.

_65 verses containing DRY_

== DUE

* `Lev 10:13` And you shall eat it in the holy place because it is your *_due_* and your sons' *_due_* of the sacrifices of the LORD made by fire, for so I am commanded.
* `Lev 10:14` And the wave-breast and heave-shoulder you shall eat in a clean place—you, your sons, and your daughters with you—for they are your *_due_* and your sons' *_due_*, which are given out of the sacrifices of peace-offerings of the children of Israel.
* `Lev 26:4` Then I will give you rain in *_due_* season, and the land shall yield her increase and the trees of the field shall yield their fruit,
* `Num 28:2` "Command the children of Israel and say to them, 'My offering and my bread for my sacrifices made by fire for a sweet savor to me, you shall observe to offer to me in their *_due_* season.'
* `Deu 11:14` That I will give you the rain of your land in its *_due_* season, the former rain and the latter rain, so that you may gather in your grain, your wine, and your oil.
* `Deu 18:3` "And this shall be the priest's *_due_* from the people, from those who offer a sacrifice, whether ox or sheep, and they shall give to the priest the shoulder, the two cheeks, and the stomach.
* `Deu 32:35` To me belongs vengeance and recompense. Their foot shall slide in *_due_* time, for the day of their calamity is at hand, and the things that shall come upon them make haste.
* `1Ch 15:13` For because you did not do it at the first, the LORD our God made a breach upon us, for we did not seek him after the *_due_* order."
* `1Ch 16:29` Give to the LORD the glory *_due_* to his name. Bring an offering and come before him. Worship the LORD in the beauty of holiness.
* `Neh 11:23` For it was the king's commandment concerning them, that a certain portion should be for the singers, *_due_* for every day.
* `Psa 29:2` Give to the LORD the glory *_due_* to his name. Worship the LORD in the beauty of holiness.
* `Psa 96:8` Give to the LORD the glory *_due_* to his name. Bring an offering and come into his courts.
* `Psa 104:27` These all wait upon you so that you may give them their food in *_due_* season.
* `Psa 145:15` The eyes of all wait upon you, and you give them their food in *_due_* season.
* `Pro 3:27` Do not withhold good from them to whom it is *_due_*, when it is in the power of your hand to do it.
* `Pro 15:23` A man has joy by the answer of his mouth, and a word spoken in *_due_* season, how good it is!
* `Ecc 10:17` You are blessed, O land, when your king is the son of nobles, and your princes eat in *_due_* season—for strength and not for drunkenness!
* `Mth 18:34` And his lord was angry and delivered him to the tormentors until he should pay everything that was *_due_* to him.
* `Mth 24:45` "Who then is a faithful and wise servant, whom his lord has made ruler over his household to give them food in *_due_* season?
* `Luk 12:42` And the Lord said, "Who then is that faithful and wise steward, whom his lord makes ruler over his household to give them their portion of provisions in *_due_* season?
* `Luk 23:41` And we indeed justly, for we receive the *_due_* reward of our deeds. But this man has done nothing amiss."
* `Rom 5:6` For when we were still without strength, in *_due_* time Christ died for the ungodly.
* `Rom 13:7` Render therefore to all their dues: tribute to whom tribute is *_due_*, custom to whom custom, fear to whom fear, honor to whom honor.
* `1Co 7:3` Let the husband render to the wife *_due_* benevolence, and likewise also the wife to the husband.
* `1Co 15:8` And last of all, he was seen by me also, as by one born out of *_due_* time.
* `Gal 6:9` And let us not be weary in well-doing, for in *_due_* season we shall reap if we do not faint.
* `1Ti 2:6` Who gave himself a ransom for all—the testimony in its own *_due_* times,
* `Tit 1:3` But has in *_due_* times manifested his word through preaching, which is committed to me according to the commandment of God our Savior,
* `1Pe 5:6` Humble yourselves therefore under the mighty hand of God so that he may exalt you in *_due_* time,

_29 verses containing DUE_

== DUES

* `Rom 13:7` Render therefore to all their *_dues_*: tribute to whom tribute is due, custom to whom custom, fear to whom fear, honor to whom honor.

_1 verse containing DUES_

== DUG

* `Gen 21:30` And he said, "You shall take these seven ewe-lambs from my hand so that they may be a witness to me that I have *_dug_* this well."
* `Gen 26:15` For all the wells which his father's servants had *_dug_* in the days of Abraham his father, the Philistines had stopped them and filled them with earth.
* `Gen 26:18` And Isaac *_dug_* again the wells of water which they had *_dug_* in the days of Abraham his father, for the Philistines had stopped them after the death of Abraham. And he called their names after the names by which his father had called them.
* `Gen 26:19` And Isaac's servants *_dug_* in the valley and found there a well of springing water.
* `Gen 26:21` And they *_dug_* another well and contended for that also, and he called its name Sitnah.
* `Gen 26:22` And he departed from there and *_dug_* another well. And for that they did not contend. And he called its name Rehoboth and he said, "For now the LORD has made room for us, and we shall be fruitful in the land."
* `Gen 26:25` And he built an altar there and called upon the name of the LORD and pitched his tent there. And Isaac's servants *_dug_* a well there.
* `Gen 26:32` And it came to pass the same day, that Isaac's servants came and told him concerning the well which they had *_dug_* and said to him, "We have found water."
* `Gen 49:6` O my soul, do not come into their secret. To their assembly, my honor, do not be united, for in their anger they slew a man and in their self-will they *_dug_* down a wall.
* `Gen 50:5` 'My father made me swear, saying, "Behold, I die. In my grave which I have *_dug_* for me in the land of Canaan, there you shall bury me." Now therefore, let me go, I pray you, and bury my father, and I will come back.'"
* `Exo 7:24` And all the Egyptians *_dug_* all around the river for water to drink because they could not drink the water from the river.
* `Num 21:18` The princes *_dug_* the well. The nobles of the people *_dug_* it, by the direction of the lawgiver, with their staffs." And from the wilderness they went to Mattanah,
* `Deu 6:11` And houses full of all good things which you did not fill, and wells *_dug_* which you did not dig, vineyards and olive-trees which you did not plant, when you have eaten and are full,
* `2Ki 19:24` I have *_dug_* and drank strange waters, and with the sole of my feet I have dried up all the rivers of besieged places."
* `2Ch 26:10` Also, he built towers in the desert and *_dug_* many wells, for he had a large number of livestock, both in the low country and in the plains, and also farmers and vine-dressers in the mountains and in Carmel, for he loved farming.
* `Neh 9:25` And they took strong cities and a fat land and possessed houses full of all goods, wells *_dug_*, vineyards and olive-groves, and fruit trees in abundance. Thus they ate and were filled and became fat and delighted themselves in your great goodness.
* `Psa 7:15` He made a pit, *_dug_* it, and has fallen into the ditch which he made.
* `Psa 35:7` For without cause they have hid for me their net in a pit, which without cause they have *_dug_* for my soul.
* `Psa 57:6` They have prepared a net for my steps. My soul is bowed down. They have *_dug_* a pit before me, into the midst of which they have fallen themselves. [Selah.]
* `Psa 94:13` So that you may give him rest from the days of adversity until the pit is *_dug_* for the wicked.
* `Psa 119:85` The proud have *_dug_* pits for me, which are not according to your law.
* `Isa 5:6` And I will lay it waste. It shall not be pruned nor *_dug_*, but there shall come up briers and thorns. I will also command the clouds that they rain no rain upon it.
* `Isa 7:25` And on all hills that are *_dug_* with the mattock, the fear of briers and thorns shall not come there, but it shall be for the sending forth of oxen and for the treading of sheep.
* `Isa 37:25` I have *_dug_* and drank water, and with the sole of my feet I have dried up all the rivers of the besieged places.'
* `Isa 51:1` "Listen to me, you who follow after righteousness, you who seek the LORD. Look to the rock from where you are hewn, and to the hole of the pit from where you are *_dug_*.
* `Jer 13:7` Then I went to the Euphrates, *_dug_*, and took the girdle from the place where I had hid it, and behold, the girdle was marred. It was profitable for nothing.
* `Jer 18:20` Shall evil be recompensed for good? For they have *_dug_* a pit for my soul. Remember that I stood before you to speak good for them and to turn away your wrath from them.
* `Jer 18:22` Let a cry be heard from their houses when you bring a troop suddenly upon them, for they have *_dug_* a pit to take me and hid snares for my feet.
* `Ezk 8:8` Then he said to me, "Son of man, now dig in the wall." And when I had *_dug_* in the wall, behold a door.
* `Ezk 12:7` And so I did as I was commanded. I brought forth my stuff for captivity by day, and in the evening I *_dug_* through the wall with my hand. I brought it forth in the twilight and bore it upon my shoulder in their sight.
* `Mth 21:33` "Hear another parable. There was a certain householder who planted a vineyard, hedged it around, *_dug_* a wine-press in it, built a tower, and lent it out to farmers and went into a remote country.
* `Mth 25:18` But he who had received one went and *_dug_* in the earth and hid his lord's money.
* `Mrk 12:1` And he began to speak to them in parables. "A certain man planted a vineyard, set a hedge around it, *_dug_* a place for the wine-vat, built a tower, lent it out to farmers, and went into a far country.
* `Luk 6:48` He is like a man who built a house and *_dug_* deep and laid the foundation on a rock, and when the flood arose, the stream beat vehemently upon that house and could not shake it, for it was founded upon a rock.
* `Rom 11:3` "Lord, they have killed your prophets and *_dug_* down your altars. I am left alone. And they seek my life."

_35 verses containing DUG_

== DULL

* `Mth 13:15` For this people's heart has become callous, their ears are *_dull_* of hearing, and their eyes they have closed, or else perhaps they should see with their eyes, hear with their ears, and should understand with their heart and should be converted, and I should heal them.'
* `Act 28:27` For the heart of this people has become callous, their ears are *_dull_* of hearing, and their eyes they have closed, lest they should see with their eyes, hear with their ears, understand with their heart, and be converted, and I should heal them."'
* `Heb 5:11` Concerning him, we have many things to say, and hard of interpretation, seeing you have become *_dull_* of hearing.

_3 verses containing DULL_

== DUMAH

* `Gen 25:14` Mishma, *_Dumah_*, Massa,
* `Jsh 15:52` Arab, *_Dumah_*, Eshean,
* `1Ch 1:30` Mishma, *_Dumah_*, Massa, Hadad, Tema,
* `Isa 21:11` [The burden of *_Dumah_*.] He calls to me out of Seir, "Watchman, what of the night? Watchman, what of the night?"

_4 verses containing DUMAH_

== DUNG

* `Exo 29:14` But the flesh of the bull, his skin, and his *_dung_* you shall burn with fire outside the camp. It is a sin-offering.
* `Lev 4:11` And the skin of the bull and all its flesh, with its head, its legs, its inwards, and its *_dung_*,
* `Lev 8:17` But the bull and its hide, its flesh, and its *_dung_*, he burnt with fire outside the camp, as the LORD commanded Moses.
* `Lev 16:27` And the bull for the sin-offering and the goat for the sin-offering, whose blood was brought in to make atonement in the holy place, someone shall carry forth outside the camp and they shall burn in the fire their skins, their flesh, and their *_dung_*.
* `Num 19:5` And someone shall burn the heifer in his sight—her skin, her flesh, and her blood, with her *_dung_*, he shall burn.
* `1Ki 14:10` Therefore, behold, I will bring evil upon the house of Jeroboam: I will cut off from Jeroboam the males, both him who is shut up and him who is left at large, in Israel, and will take away the remnant of the house of Jeroboam, as a man takes away *_dung_* until it is all gone.
* `2Ki 6:25` And there was a great famine in Samaria. And behold, they besieged it until a donkey's head was sold for eighty pieces of silver and the fourth part of a kab of dove's *_dung_* for five pieces of silver.
* `2Ki 9:37` And the carcass of Jezebel shall be as *_dung_* upon the face of the field in the portion of Jezreel so that they shall not say, "This is Jezebel."'"
* `Neh 2:13` And I went out by night by the gate of the valley, even before the dragon-well and to the *_dung_*-port, and viewed the walls of Jerusalem, which were broken down and their gates were consumed with fire.
* `Neh 3:13` The valley-gate was repaired by Hanun and the inhabitants of Zanoah. They built it, set up its doors, its locks, and its bars, and one thousand cubits on the wall to the *_dung_*-gate.
* `Neh 3:14` But the *_dung_*-gate was repaired by Malchiah the son of Rechab, the ruler of part of Beth-haccerem. He built it, set up its doors, its locks, and its bars.
* `Neh 12:31` Then I brought up the princes of Judah upon the wall and appointed two great companies of those who gave thanks, of which one went on the right hand upon the wall toward the *_dung_*-gate.
* `Job 20:7` Yet he shall perish forever like his own *_dung_*. Those who have seen him shall say, 'Where is he?'
* `Psa 83:10` Who perished at En-dor. They became like *_dung_* for the earth.
* `Jer 8:2` And they shall spread them before the sun, the moon, and all the host of heaven, whom they have loved, whom they have served, after whom they have walked, whom they have sought, and whom they have worshiped. They shall not be gathered nor be buried. They shall be for *_dung_* upon the face of the earth.
* `Jer 9:22` Speak, "Thus says the LORD: 'Even the carcasses of men shall fall as *_dung_* upon the open field and as the handful after the harvester, and no one shall gather them.'"
* `Jer 16:4` "They shall die by grievous deaths. They shall not be lamented, neither shall they be buried, but they shall be like *_dung_* upon the face of the earth. And they shall be consumed by the sword and by famine, and their carcasses shall be food for the birds of heaven and for the beasts of the earth."
* `Jer 25:33` And the slain of the LORD shall be at that day from one end of the earth even to the other end of the earth. They shall not be lamented, neither gathered, nor buried. They shall be *_dung_* upon the ground.
* `Ezk 4:15` Then he said to me, "Behold, I have given you cow's *_dung_* for man's *_dung_*, and you shall prepare your bread over that."
* `Zph 1:17` And I will bring distress upon men so that they shall walk like blind men, because they have sinned against the LORD. And their blood shall be poured out as dust and their flesh as the *_dung_*.
* `Mal 2:3` Behold, I will rebuke your offspring and spread *_dung_* upon your faces, even the *_dung_* of your solemn feasts, and you shall be taken away with it.
* `Phl 3:8` Indeed, I even count all things to be loss for the excellence of the knowledge of Christ Jesus my Lord. For him I have suffered the loss of all things and count them to be *_dung_* so that I may win Christ,

_22 verses containing DUNG_

== DUNG-GATE

* `Neh 3:13` The valley-gate was repaired by Hanun and the inhabitants of Zanoah. They built it, set up its doors, its locks, and its bars, and one thousand cubits on the wall to the *_dung-gate_*.
* `Neh 3:14` But the *_dung-gate_* was repaired by Malchiah the son of Rechab, the ruler of part of Beth-haccerem. He built it, set up its doors, its locks, and its bars.
* `Neh 12:31` Then I brought up the princes of Judah upon the wall and appointed two great companies of those who gave thanks, of which one went on the right hand upon the wall toward the *_dung-gate_*.

_3 verses containing DUNG-GATE_

== DUNG-PORT

* `Neh 2:13` And I went out by night by the gate of the valley, even before the dragon-well and to the *_dung-port_*, and viewed the walls of Jerusalem, which were broken down and their gates were consumed with fire.

_1 verse containing DUNG-PORT_

== DUNGEON

* `Gen 40:15` For indeed I was stolen away from the land of the Hebrews, and here also I have done nothing that they should put me into the *_dungeon_*."
* `Gen 41:14` Then Pharaoh sent and called Joseph, and they brought him hastily out of the *_dungeon_*. And he shaved himself and changed his clothing and came before Pharaoh.
* `Exo 12:29` And it came to pass, that at midnight the LORD smote all the first-born in the land of Egypt, from the first-born of Pharaoh who sat on his throne to the first-born of the captive who was in the *_dungeon_*, and all the first-born of livestock.
* `Jer 37:16` So Jeremiah had entered into the *_dungeon_* and into the cabins, and Jeremiah had remained there many days.
* `Jer 38:6` Then they took Jeremiah and cast him into the *_dungeon_* of Malchiah the son of Hammelech that was in the court of the prison. And they let Jeremiah down with cords. And in the *_dungeon_* there was no water, but mire. So Jeremiah sunk in the mire.
* `Jer 38:7` Now when Ebed-melech the Cushite, one of the eunuchs who was in the king's house, heard that they had put Jeremiah in the *_dungeon_* (the king was sitting in the gate of Benjamin),
* `Jer 38:9` "My lord the king, these men have done evil in all that they have done to Jeremiah the prophet, whom they have cast into the *_dungeon_*. And he is likely to die by hunger in the place where he is, for there is no more bread in the city."
* `Jer 38:10` Then the king commanded Ebed-melech the Cushite, saying, "Take from here thirty men with you and take up Jeremiah the prophet out of the *_dungeon_* before he dies."
* `Jer 38:11` So Ebed-melech took the men with him and went into the house of the king under the treasury, took from there old cast cloths and old decayed rags, and let them down by cords into the *_dungeon_* to Jeremiah.
* `Jer 38:13` So they drew Jeremiah up with cords and took him out of the *_dungeon_*. And Jeremiah remained in the court of the prison.
* `Lam 3:53` They have cut off my life in the *_dungeon_* and cast a stone upon me.
* `Lam 3:55` [QOF] I called upon your name, O LORD, out of the low *_dungeon_*.

_12 verses containing DUNGEON_

== DUNGHILL

* `1Sa 2:8` He raises the poor out of the dust and lifts the beggar from the *_dunghill_* to set them among princes and to make them inherit the throne of glory. For the pillars of the earth are the LORD'S, and he has set the world upon them.
* `Ezr 6:11` Also, I have made a decree, that whoever alters this word, let timber be pulled down from his house, and being set up, let him be hanged upon it, and let his house be made a *_dunghill_* for this.
* `Psa 113:7` He raises the poor out of the dust and lifts the needy out of the *_dunghill_*
* `Isa 25:10` For on this mountain the hand of the LORD shall rest, and Moab shall be trodden down under him, even as straw is trodden down for the *_dunghill_*.
* `Dan 2:5` The king answered and said to the Chaldeans, "The thing has gone from me. If you will not make known to me the dream, with its interpretation, you shall be cut in pieces and your houses shall be made a *_dunghill_*.
* `Dan 3:29` Therefore, I make a decree, that every people, nation, and language which speaks anything amiss against the God of Shadrach, Meshach, and Abed-nego, shall be cut in pieces and their houses shall be made a *_dunghill_*, because there is no other god who can deliver after this sort."
* `Luk 14:35` It is neither fit for the land, nor yet for the *_dunghill_*, but men cast it out. He who has ears to hear, let him hear."

_7 verses containing DUNGHILL_

== DUNGHILLS

* `Lam 4:5` [HE] Those who fed delicately are desolate in the streets. Those who were brought up in scarlet embrace *_dunghills_*.

_1 verse containing DUNGHILLS_

== DURA

* `Dan 3:1` Nebuchadnezzar the king made an image of gold whose height was sixty cubits and its breadth six cubits. He set it up in the plain of *_Dura_*, in the province of Babylon.

_1 verse containing DURA_

== DURABLE

* `Pro 8:18` Riches and honor are with me, *_durable_* riches and righteousness.
* `Isa 23:18` And her merchandise and her wages shall be holiness to the LORD. It shall not be treasured nor laid up, for her merchandise shall be for those who dwell before the LORD, for sufficient food and for *_durable_* clothing.

_2 verses containing DURABLE_

== DURING

* `Neh 8:14` And they found written in the law which the LORD had commanded by Moses, that the children of Israel should dwell in booths *_during_* the feast of the seventh month,
* `Jhn 13:2` And *_during_* supper (the devil having now put into the heart of Judas Iscariot, Simon's son, to betray him),
* `Act 7:42` Then God turned and gave them up to worship the host of heaven, as it is written in the book of the prophets, 'O house of Israel, have you offered to me slain beasts and sacrifices *_during_* forty years in the wilderness?

_3 verses containing DURING_

== DUST

* `Gen 2:7` And the LORD God formed man from the *_dust_* of the ground and breathed into his nostrils the breath of life. And man became a living soul.
* `Gen 3:14` And the LORD God said to the serpent, "Because you have done this, you are cursed above all livestock and above every beast of the field. Upon your belly you shall go, and *_dust_* you shall eat all the days of your life.
* `Gen 3:19` In the sweat of your face you shall eat bread until you return to the ground, for out of it you were taken. For you are *_dust_*, and to *_dust_* you shall return."
* `Gen 13:16` And I will make your offspring like the *_dust_* of the earth, so that if a man can number the *_dust_* of the earth, then your offspring shall also be numbered.
* `Gen 18:27` And Abraham answered and said, "Behold now, I, who am *_dust_* and ashes, have taken upon myself to speak to the Lord.
* `Gen 28:14` And your offspring shall be like the *_dust_* of the earth, and you shall spread abroad to the west, to the east, to the north, and to the south. And in you and in your offspring all the families of the earth shall be blessed.
* `Exo 8:16` And the LORD said to Moses, "Say to Aaron, 'Stretch out your rod and smite the *_dust_* of the land so that it may become lice throughout all the land of Egypt.'"
* `Exo 8:17` And they did so. For Aaron stretched out his hand with his rod and smote the *_dust_* of the earth, and it became lice on man and on beast. All the *_dust_* of the land became lice throughout all the land of Egypt.
* `Exo 9:9` And it shall become small *_dust_* in all the land of Egypt and shall be a boil breaking forth with sores upon man and upon beast throughout all the land of Egypt."
* `Lev 14:41` And he shall cause the house to be scraped inside on all sides, and they shall pour out the *_dust_* that they scrape off outside the city into an unclean place.
* `Lev 17:13` And whatever man there may be of the children of Israel or of the strangers who sojourn among you who hunts and catches any beast or bird that may be eaten, he shall even pour out its blood and cover it with *_dust_*.
* `Num 5:17` And the priest shall take holy water in an earthen vessel, and the priest shall take some of the *_dust_* that is on the floor of the tabernacle and put it into the water.
* `Num 23:10` Who can count the *_dust_* of Jacob and the number of the fourth part of Israel? Let me die the death of the righteous, and let my last end be like his!"
* `Deu 9:21` And I took your sin, the calf which you had made, and burnt it with fire, stamped it, and ground it very small, even until it was as small as *_dust_*. And I cast the *_dust_* of it into the brook that descended from the mountain.
* `Deu 28:24` The LORD shall make the rain of your land powder and *_dust_*. From heaven it shall come down upon you until you are destroyed.
* `Deu 32:24` They shall be burnt with hunger and devoured with burning heat and with bitter destruction. I will also send the teeth of beasts upon them, with the poison of serpents of the *_dust_*.
* `Jsh 7:6` And Joshua rent his clothes and fell to the earth upon his face before the ark of the LORD until the evening—he and the elders of Israel—and put *_dust_* upon their heads.
* `1Sa 2:8` He raises the poor out of the *_dust_* and lifts the beggar from the dunghill to set them among princes and to make them inherit the throne of glory. For the pillars of the earth are the LORD'S, and he has set the world upon them.
* `2Sa 16:13` And as David and his men went along the way, Shimei went along on the hill's side over against him and cursed as he went, threw stones at him, and cast *_dust_*.
* `2Sa 22:43` Then I beat them as small as the *_dust_* of the earth. I crushed them like the mire of the street and spread them abroad.
* `1Ki 16:2` "Because I exalted you from the *_dust_* and made you prince over my people Israel, and you have walked in the way of Jeroboam and have made my people Israel to sin to provoke me to anger with their sins,
* `1Ki 18:38` Then the fire of the LORD fell and consumed the burnt-sacrifice, the wood, the stones, and the *_dust_*, and licked up the water that was in the trench.
* `1Ki 20:10` And Ben-hadad sent to him and said, "May the gods do so to me and more also, if the *_dust_* of Samaria shall suffice for handfuls for all the people who follow me."
* `2Ki 13:7` For he did not leave to Jehoahaz any army except fifty horsemen, ten chariots, and ten thousand footmen, for the king of Syria had destroyed them and made them like the *_dust_* by threshing.
* `2Ki 23:12` And the altars that were on the top of the upper chamber of Ahaz, which the kings of Judah had made, and the altars which Manasseh had made in the two courts of the house of the LORD, the king beat down and broke them down from there and cast their *_dust_* into the brook Kidron.
* `2Ch 1:9` Now, O LORD God, let your promise to David my father be established, for you have made me king over a people like the *_dust_* of the earth in multitude.
* `2Ch 34:4` And they broke down the altars of Baalim in his presence, and he cut down the images that were on high above them. And the groves, the carved images, and the molten images he broke in pieces and made *_dust_* of them and scattered it upon the graves of those who had sacrificed to them.
* `Job 2:12` And when they lifted up their eyes afar off, they did not know him. And they raised their voice and wept, and they each rent his mantle and sprinkled *_dust_* upon their heads toward heaven.
* `Job 4:19` How much less in those who dwell in houses of clay, whose foundation is in the *_dust_*, who are crushed before the moth?
* `Job 5:6` Although affliction does not come forth from the *_dust_*, neither does trouble spring out of the ground,
* `Job 7:5` My flesh is clothed with worms and clods of *_dust_*. My skin has broken and become loathsome.
* `Job 7:21` And why do you not pardon my transgression and take away my iniquity? For now I shall sleep in the *_dust_*. And you shall seek me in the morning, but I shall be no more."
* `Job 10:9` Remember, I implore you, that you have made me like the clay. And will you bring me into *_dust_* again?
* `Job 14:19` The waters wear the stones. You wash away the things which grow out of the *_dust_* of the earth and you destroy the hope of man.
* `Job 16:15` I have sewed sackcloth upon my skin and defiled my horn in the *_dust_*.
* `Job 17:16` They shall go down to the bars of the pit when our rest together is in the *_dust_*."
* `Job 20:11` His bones are full of the sin of his youth, which shall lie down with him in the *_dust_*.
* `Job 21:26` They shall lie down alike in the *_dust_*, and the worms shall cover them.
* `Job 22:24` Then you shall lay your gold in the *_dust_*,the gold of Ophir in the stones of the brooks,
* `Job 27:16` Though he should heap up silver like the *_dust_* and lay up clothing like the clay,
* `Job 28:6` Its stones are the place of sapphires, and it has *_dust_* of gold.
* `Job 30:19` He has cast me into the mire, and I have become like *_dust_* and ashes.
* `Job 34:15` All flesh would perish together and man would return to *_dust_*.
* `Job 38:38` When the *_dust_* grows into hardness and the clods cleave fast together?
* `Job 39:14` Which leaves her eggs in the earth, warms them in the *_dust_*,
* `Job 40:13` Hide them in the *_dust_* together. Bind their faces in secret.
* `Job 42:6` Therefore, I abhor myself and repent in *_dust_* and ashes."
* `Psa 7:5` Let the enemy persecute my soul and take it. Let him even tread down my life upon the earth and lay my honor in the *_dust_*. [Selah.]
* `Psa 18:42` Then I beat them as small as the *_dust_* before the wind. I cast them out like the dirt in the streets.
* `Psa 22:15` My strength is dried up like a potsherd, and my tongue cleaves to my jaws. And you have brought me into the *_dust_* of death.
* `Psa 22:29` All those who are fat upon earth shall eat and worship. All those who go down to the *_dust_* shall bow before him. And no one can keep his own soul alive.
* `Psa 30:9` What profit is there in my blood when I go down to the pit? Shall the *_dust_* praise you? Shall it declare your truth?
* `Psa 44:25` For our soul is bowed down to the *_dust_*. Our belly cleaves to the earth.
* `Psa 72:9` Those who dwell in the wilderness shall bow before him, and his enemies shall lick the *_dust_*.
* `Psa 78:27` He also rained flesh upon them like *_dust_*, and feathered birds like the sand of the sea.
* `Psa 102:14` For your servants take pleasure in her stones and favor the *_dust_* thereof.
* `Psa 103:14` For he knows our frame. He remembers that we are *_dust_*.
* `Psa 104:29` You hide your face, and they are troubled. You take away their breath, and they die and return to their *_dust_*.
* `Psa 113:7` He raises the poor out of the *_dust_* and lifts the needy out of the dunghill
* `Psa 119:25` [DALET] My soul cleaves to the *_dust_*. Revive me according to your word.
* `Pro 8:26` While he had not yet made the earth, the fields, nor the highest part of the *_dust_* of the world.
* `Ecc 3:20` All go to one place. All are of the *_dust_*, and all turn to *_dust_* again.
* `Ecc 12:7` And the *_dust_* returns to the earth as it was, and the spirit returns to God who gave it.
* `Isa 2:10` Enter into the rock and hide in the *_dust_* from before the fear of the LORD and the glory of his majesty.
* `Isa 5:24` Therefore, as the fire devours the stubble and the flame consumes the chaff, so their root shall be as rottenness and their blossom shall go up like *_dust_*, because they have cast away the law of the LORD of hosts and despised the word of the Holy One of Israel.
* `Isa 25:12` And the fortress of the high fort of your walls he will bring down, lay low, and bring to the ground, even to the *_dust_*.
* `Isa 26:5` For he brings down those who dwell on high. The lofty city, he lays it low. He lays it low, even to the ground. He brings it even to the *_dust_*.
* `Isa 26:19` Your dead men shall live. Together with my dead body they shall arise. Awake and sing, you who dwell in *_dust_*, for your dew is like the dew of herbs, and the earth shall cast out the dead.
* `Isa 29:4` And you shall be brought down and shall speak out of the ground. Your speech shall be low out of the *_dust_*. Your voice shall be out of the ground, like one who has a familiar spirit. And your speech shall whisper out of the *_dust_*.
* `Isa 29:5` Moreover, the multitude of your strangers shall be like small *_dust_* and the multitude of the terrible ones shall be like chaff that passes away. It shall even be at an instant, suddenly.
* `Isa 34:7` And the wild oxen shall come down with them, and the young bulls with the strong bulls. And their land shall be drenched with blood and their *_dust_* made fat with fatness.
* `Isa 34:9` And its streams shall be turned into pitch and its *_dust_* into brimstone, and its land shall become burning pitch.
* `Isa 40:12` Who has measured the waters in the hollow of his hand, measured heaven with the span, comprehended the *_dust_* of the earth in a measure, and weighed the mountains in scales and the hills in a balance?
* `Isa 40:15` Behold, the nations are like a drop in a bucket and are counted as the small *_dust_* on the balance. Behold, he takes up the islands like a very little thing.
* `Isa 41:2` Who raised up the righteous man from the east, called him to his foot, gave the nations before him, and made him rule over kings? He gave them as the *_dust_* to his sword and as driven stubble to his bow.
* `Isa 47:1` "Come down and sit in the *_dust_*, O virgin daughter of Babylon. Sit on the ground without a throne, O daughter of the Chaldeans. For you shall no longer be called tender and delicate.
* `Isa 49:23` And kings shall be your nursing fathers, and their queens your nursing mothers. They shall bow to you with their face toward the earth and lick up the *_dust_* of your feet. And you shall know that I am the LORD, for they shall not be ashamed who wait for me.
* `Isa 52:2` Shake yourself from the *_dust_*. Arise, and sit down, O Jerusalem. Release yourself from the bonds of your neck, O captive daughter of Zion.
* `Isa 65:25` The wolf and the lamb shall feed together, and the lion shall eat straw like the bull, and *_dust_* shall be the serpents' food. They shall neither hurt nor destroy in all my holy mountain," says the LORD.
* `Lam 2:10` [YOD] The elders of the daughter of Zion sit upon the ground and keep silence. They have cast up *_dust_* upon their heads. They have girded themselves with sackcloth. The virgins of Jerusalem hang down their heads to the ground.
* `Lam 3:29` He puts his mouth in the *_dust_*, if there may be hope.
* `Ezk 24:7` For her blood is in the midst of her. She set it upon the top of a rock. She did not pour it upon the ground to cover it with *_dust_*.
* `Ezk 26:4` And they shall destroy the walls of Tyre and break down her towers. I will also scrape her *_dust_* from her and make her like the top of a rock.
* `Ezk 26:10` By reason of the abundance of his horses their *_dust_* shall cover you. Your walls shall shake at the noise of the horsemen, of the wheels, and of the chariots when he enters into your gates as men enter into a city in which a breach is made.
* `Ezk 26:12` And they shall make loot of your riches and make plunder of your merchandise. And they shall break down your walls and destroy your pleasant houses. And they shall lay your stones and your timber and your *_dust_* in the midst of the water.
* `Ezk 27:30` They shall cause their voice to be heard against you and shall cry bitterly. They shall cast up *_dust_* upon their heads. They shall wallow themselves in the ashes.
* `Dan 12:2` And many of those who sleep in the *_dust_* of the earth shall awake, some to everlasting life, and some to shame and everlasting contempt.
* `Amo 2:7` They pant after the *_dust_* of the earth on the head of the poor and turn aside the way of the meek. And a man and his father will go in to the same woman to profane my holy name.
* `Mic 1:10` Do not declare it at Gath. Do not weep at all. In the house of Aphrah roll yourself in the *_dust_*.
* `Mic 7:17` They shall lick the *_dust_* like a serpent. They shall move out of their holes like worms of the earth. They shall be afraid of the LORD our God and shall fear because of you.
* `Nah 1:3` The LORD is slow to anger and great in power, and will not at all acquit the wicked. The LORD has his way in the whirlwind and in the storm, and the clouds are the *_dust_* of his feet.
* `Nah 3:18` Your shepherds slumber, O king of Assyria. Your nobles shall dwell in the *_dust_*. Your people are scattered upon the mountains and no man gathers them.
* `Hab 1:10` And they shall scoff at the kings, and the princes shall be a scorn to them. They shall deride every stronghold, for they shall heap *_dust_* and take it.
* `Zph 1:17` And I will bring distress upon men so that they shall walk like blind men, because they have sinned against the LORD. And their blood shall be poured out as *_dust_* and their flesh as the dung.
* `Zch 9:3` And Tyre built herself a stronghold and amassed silver as the *_dust_* and fine gold as the mire of the streets.
* `Mth 10:14` And whoever does not receive you, nor hear your words, when you depart from that house or city, shake off the *_dust_* from your feet.
* `Mrk 6:11` And whoever does not receive you nor hear you, when you depart from there, shake off the *_dust_* under your feet for a testimony against them. Truly I say to you, it shall be more tolerable for Sodom and Gomorrah on the day of judgment than for that city."
* `Luk 9:5` And whoever will not receive you, when you go out of that city, shake off the very *_dust_* from your feet for a testimony against them."
* `Luk 10:11` 'Even the very *_dust_* of your city which cleaves on us, we wipe off against you. Nevertheless, be sure of this, that the kingdom of God has come near to you.'
* `Act 13:51` But they shook off the *_dust_* of their feet against them and came to Iconium.
* `Act 22:23` And as they cried out, cast off their clothes, and threw *_dust_* into the air,
* `Rev 18:19` And they cast *_dust_* on their heads and cried, weeping and wailing, saying, 'Alas, alas, that great city in which all who had ships in the sea were made rich by reason of her opulence!' For in one hour she has been made desolate.

_102 verses containing DUST_

== DUTIES

* `Ezk 18:11` Who does not do any of those *_duties_*, but even has eaten upon the mountains, defiled his neighbor's wife,

_1 verse containing DUTIES_

== DUTY

* `Exo 21:10` If he takes for himself another wife, her food, her clothing, and her *_duty_* of marriage he shall not diminish.
* `Deu 25:5` "If brothers dwell together, and one of them dies and has no child, the wife of the dead shall not marry outside to a stranger. Her husband's brother shall go in to her and take her for himself for a wife and perform the *_duty_* of a husband's brother to her.
* `Deu 25:7` And if the man does not want to take his brother's wife, then let his brother's wife go up to the gate to the elders and say, 'My husband's brother refuses to raise up for his brother a name in Israel. He will not perform the *_duty_* of my husband's brother.'
* `2Ch 8:14` And he appointed, according to the order of David his father, the courses of the priests to their service, the Levites to their charges to praise and minister before the priests as the *_duty_* of every day required, and the gatekeepers by their courses at every gate, for thus David the man of God had commanded.
* `Ezr 3:4` They also kept the feast of tabernacles, as it is written, and offered the daily burnt-offerings by number, according to the custom, as the *_duty_* of every day required,
* `Ecc 12:13` Let us hear the conclusion of the whole matter. Fear God and keep his commandments, for this is the whole *_duty_* of man.
* `Luk 17:10` So likewise you, when you have done all the things which are commanded of you, say, 'We are unprofitable servants. We have done that which was our *_duty_* to do.'"
* `Rom 15:27` It has pleased them truly, and their debtors they are. For if the Gentiles have been made partakers of their spiritual things, their *_duty_* is also to minister to them in carnal things.

_8 verses containing DUTY_

== DWARF

* `Lev 21:20` Crooked-backed, a *_dwarf_*, who has a blemish in his eye, has scurvy, is scabbed, or has his peculiar members broken.

_1 verse containing DWARF_

== DWELL

* `Gen 4:20` And Adah bore Jabal. He was the father of those who *_dwell_* in tents and of those who have livestock.
* `Gen 9:27` God shall enlarge Japheth, and he shall *_dwell_* in the tents of Shem, and Canaan shall be his servant."
* `Gen 12:10` And there was a famine in the land. And Abram went down into Egypt to *_dwell_* there, for the famine was grievous in the land.
* `Gen 13:6` And the land was not able to bear them so that they might *_dwell_* together, for their substance was so great that they could not *_dwell_* together.
* `Gen 16:12` And he will be a wild man. His hand will be against every man, and every man's hand against him. And he shall *_dwell_* in the presence of all his brothers."
* `Gen 19:30` And Lot went up from Zoar and dwelt in the mountain, and his two daughters with him, for he feared to *_dwell_* in Zoar. And he dwelt in a cave—he and his two daughters.
* `Gen 20:15` And Abimelech said, "Behold, my land is before you. *_Dwell_* where it pleases you."
* `Gen 24:3` And I will make you swear by the LORD, the God of heaven and the God of the earth, that you will not take a wife for my son from the daughters of the Canaanites among whom I *_dwell_*.
* `Gen 24:37` And my master made me swear, saying, 'You shall not take a wife for my son from the daughters of the Canaanites, in whose land I *_dwell_*.
* `Gen 26:2` And the LORD appeared to him and said, "Do not go down into Egypt. *_Dwell_* in the land of which I shall tell you.
* `Gen 30:20` And Leah said, "God has endowed me with a good dower. Now my husband will *_dwell_* with me because I have borne him six sons." And she called his name Zebulun.
* `Gen 34:10` And you shall *_dwell_* with us, and the land shall be before you. *_Dwell_* and trade therein and get possessions therein."
* `Gen 34:16` Then we will give our daughters to you and we will take your daughters for ourselves, and we will *_dwell_* with you, and we will become one people.
* `Gen 34:21` "These men are peaceable with us; therefore, let them *_dwell_* in the land and trade therein. For the land, behold, it is large enough for them. Let us take their daughters for wives and let us give them our daughters.
* `Gen 34:22` Only herein will the men consent to us to *_dwell_* with us to be one people: if every male among us is circumcised, as they are circumcised.
* `Gen 34:23` Will their livestock, their substance, and every beast of theirs not be ours? Only let us consent to them, and they will *_dwell_* with us."
* `Gen 35:1` And God said to Jacob, "Arise, go up to Beth-el and *_dwell_* there. And make there an altar to God, who appeared to you when you fled from the face of Esau your brother."
* `Gen 36:7` For their riches were too abundant for them to *_dwell_* together, and the land wherein they were strangers could not sustain them because of their livestock.
* `Gen 45:10` And you shall *_dwell_* in the land of Goshen and you shall be near to me—you, your children, your children's children, your flocks, your herds, and all that you have.
* `Gen 46:34` You shall say, 'Your servants have been keepers of livestock from our youth even until now—both we and also our fathers,' so that you may *_dwell_* in the land of Goshen, for every shepherd is an abomination to the Egyptians."
* `Gen 47:4` They said moreover to Pharaoh, "We have come to sojourn in the land, for your servants have no pasture for their flocks, for the famine is severe in the land of Canaan. Now therefore, we pray you, let your servants *_dwell_* in the land of Goshen."
* `Gen 47:6` The land of Egypt is before you. In the best of the land make your father and brothers to *_dwell_*. In the land of Goshen let them *_dwell_*. And if you know any able men among them, then make them rulers over my livestock."
* `Gen 49:13` "Zebulun shall *_dwell_* at the haven of the sea, and he shall be for a haven of ships. And his border shall be to Zidon.
* `Exo 2:21` And Moses was content to *_dwell_* with the man. And he gave Zipporah his daughter to Moses.
* `Exo 8:22` And in that day I will set apart the land of Goshen, in which my people *_dwell_*, so that no swarms of flies shall be there, to the end you may know that I am the LORD in the midst of the earth.
* `Exo 15:17` You shall bring them in and plant them in the mountain of your inheritance, in the place, O LORD, which you have made for you to *_dwell_* in, in the sanctuary, O Lord, which your hands have established.
* `Exo 23:33` They shall not *_dwell_* in your land, lest they make you to sin against me, for if you serve their gods, it will surely be a snare to you."
* `Exo 25:8` And let them make me a sanctuary so that I may *_dwell_* among them.
* `Exo 29:45` And I will *_dwell_* among the children of Israel and will be their God.
* `Exo 29:46` And they shall know that I am the LORD their God who brought them forth out of the land of Egypt so that I may *_dwell_* among them. I am the LORD their God."
* `Lev 13:46` All the days in which the plague is in him he shall be defiled. He is unclean. He shall *_dwell_* alone. His dwelling shall be outside the camp.
* `Lev 14:8` And he who is to be cleansed shall wash his clothes, shave off all his hair, and wash himself in water so that he may be clean. And after that, he shall come into the camp and shall *_dwell_* outside his tent for seven days.
* `Lev 20:22` 'You shall therefore keep all my statutes and all my judgments and do them so that the land where I bring you to *_dwell_* therein may not vomit you out.
* `Lev 23:42` You shall *_dwell_* in booths for seven days. All who are natives of Israel shall *_dwell_* in booths,
* `Lev 23:43` So that your generations may know that I made the children of Israel to *_dwell_* in booths when I brought them out of the land of Egypt. I am the LORD your God.'"
* `Lev 25:18` 'Therefore, you shall do my statutes, keep my judgments, and do them, and you shall *_dwell_* in the land in safety.
* `Lev 25:19` And the land shall yield her fruit, and you shall eat your fill and *_dwell_* in it in safety.
* `Lev 26:5` And your threshing shall reach to the vintage and the vintage shall reach to the sowing time, and you shall eat your bread to the full and *_dwell_* in your land safely.
* `Lev 26:32` And I will bring the land into desolation, and your enemies who *_dwell_* in it shall be astonished at it.
* `Num 5:3` Both male and female you shall send out. Outside the camp you shall send them so that they do not defile their camps, in the midst of which I *_dwell_*."
* `Num 13:18` And see the land, what it is, and the people who *_dwell_* therein, whether they are strong or weak, few or many;
* `Num 13:19` And what the land is that they *_dwell_* in, whether it is good or bad, and what cities they are that they *_dwell_* in, whether in tents or in strongholds;
* `Num 13:28` Nevertheless, the people are strong who *_dwell_* in the land, and the cities are walled and very great. And moreover, we saw the children of Anak there.
* `Num 13:29` The Amalekites *_dwell_* in the land of the south. And the Hittites, the Jebusites, and the Amorites *_dwell_* in the mountains. And the Canaanites *_dwell_* by the sea and along the side of the Jordan."
* `Num 14:30` Doubtless you shall not come into the land concerning which I swore to make you *_dwell_* therein, except Caleb the son of Jephunneh and Joshua the son of Nun.
* `Num 23:9` For from the top of the rocks I see him, and from the hills I behold him. Behold, the people shall *_dwell_* alone and shall not be reckoned among the nations.
* `Num 32:17` But we ourselves will go armed ready before the children of Israel until we have brought them to their place. And our little ones shall *_dwell_* in the fortified cities because of the inhabitants of the land.
* `Num 33:53` And you shall dispossess the inhabitants of the land and *_dwell_* in it, for I have given you the land to possess it.
* `Num 33:55` But if you will not drive out the inhabitants of the land from before you, then it shall come to pass, that those which you let remain of them shall be prickles in your eyes and thorns in your sides, and shall harass you in the land in which you *_dwell_*.
* `Num 35:2` "Command the children of Israel that they give to the Levites from the inheritance of their possession cities to *_dwell_* in. And you shall also give to the Levites suburbs for the cities around them.
* `Num 35:3` And they shall have the cities to *_dwell_* in. And their suburbs shall be for their livestock, for their goods, and for all their beasts.
* `Num 35:32` And you shall take no satisfaction for him who has fled to the city of his refuge, that he should come back to *_dwell_* in the land until the death of the priest.
* `Num 35:34` Therefore, do not defile the land which you inhabit, in which I *_dwell_*, for I, the LORD, *_dwell_* among the children of Israel.'"
* `Deu 2:4` And command the people, saying, "You are to pass through the border of your brothers, the children of Esau, who *_dwell_* in Seir, and they will be afraid of you. Therefore, take good heed to yourselves.
* `Deu 2:29` (As the children of Esau who *_dwell_* in Seir and the Moabites who *_dwell_* in Ar did to me), until I pass over the Jordan into the land which the LORD our God gives us.'
* `Deu 11:30` Are they not on the other side of the Jordan, by the way where the sun goes down in the land of the Canaanites who *_dwell_* in the plain over against Gilgal beside the plains of Moreh?
* `Deu 11:31` For you shall pass over the Jordan to go in to possess the land which the LORD your God gives you, and you shall possess it and *_dwell_* in it.
* `Deu 12:10` But when you go over the Jordan and *_dwell_* in the land which the LORD your God gives you to inherit, and when he gives you rest from all your enemies on every side so that you *_dwell_* in safety,
* `Deu 12:11` There shall be a place which the LORD your God chooses to cause his name to *_dwell_* there. There you shall bring all that I command you: your burnt-offerings, your sacrifices, your tithes, the heave-offering of your hand, and all your choice vows which you vow to the LORD.
* `Deu 12:29` "When the LORD your God cuts off the nations from before you where you go to possess them, and you succeed them and *_dwell_* in their land,
* `Deu 13:12` "If you hear it said in one of your cities which the LORD your God has given you to *_dwell_* there,
* `Deu 17:14` "When you come into the land which the LORD your God gives you and possess it and *_dwell_* in it and say, 'I will set a king over me like all the nations who are around me,'
* `Deu 19:1` "When the LORD your God has cut off the nations, whose land the LORD your God gives you, and you succeed them and *_dwell_* in their cities and in their houses,
* `Deu 23:16` He shall *_dwell_* with you, even among you in that place which he chooses in one of your gates where it pleases him best. You shall not oppress him.
* `Deu 25:5` "If brothers *_dwell_* together, and one of them dies and has no child, the wife of the dead shall not marry outside to a stranger. Her husband's brother shall go in to her and take her for himself for a wife and perform the duty of a husband's brother to her.
* `Deu 26:1` "And it shall be when you come in to the land which the LORD your God gives you for an inheritance and possess it and *_dwell_* therein,
* `Deu 28:30` You shall betroth a wife and another man shall lie with her. You shall build a house and you shall not *_dwell_* in it. You shall plant a vineyard and shall not gather its grapes.
* `Deu 30:20` To love the LORD your God, to obey his voice, and to cleave to him (for he is your life and the length of your days), so that you may *_dwell_* in the land which the LORD swore to your fathers, to Abraham, to Isaac, and to Jacob, to give them."
* `Deu 33:12` And of Benjamin he said, "The beloved of the LORD shall *_dwell_* in safety by him, and the LORD shall cover him all day long, and he shall *_dwell_* between his shoulders."
* `Deu 33:28` Israel then shall *_dwell_* in safety alone. The fountain of Jacob shall be upon a land of grain and wine. His heavens shall also drop down dew.
* `Jsh 9:7` And the men of Israel said to the Hivites, "It may be that you *_dwell_* among us. How shall we make a league with you?"
* `Jsh 9:22` And Joshua called for them and spoke to them, saying, "Why have you deceived us, saying, 'We are very far from you,' when you *_dwell_* among us?
* `Jsh 10:6` And the men of Gibeon sent to Joshua in the camp at Gilgal, saying, "Do not slack your hand from your servants. Come up to us quickly and save us, and help us, for all the kings of the Amorites who *_dwell_* in the mountains are assembled against us."
* `Jsh 13:13` Nevertheless, the children of Israel did not expel the Geshurites nor the Maachathites, but the Geshurites and the Maachathites *_dwell_* among the Israelites until this day.
* `Jsh 14:4` For the children of Joseph were two tribes, Manasseh and Ephraim; therefore, they gave no part to the Levites in the land, except cities to *_dwell_* in with their suburbs for their livestock and for their substance.
* `Jsh 15:63` As for the Jebusites, the inhabitants of Jerusalem, the children of Judah could not expel them. But the Jebusites *_dwell_* with the children of Judah in Jerusalem to this day.
* `Jsh 16:10` And they did not expel the Canaanites who dwelt in Gezer. But the Canaanites *_dwell_* among the Ephraimites to this day and serve under tribute.
* `Jsh 17:12` Yet the children of Manasseh could not expel the inhabitants of those cities. But the Canaanites would *_dwell_* in that land.
* `Jsh 17:16` And the children of Joseph said, "The hill is not enough for us. And all the Canaanites who *_dwell_* in the land of the valley have chariots of iron—both those who are of Beth-shean and its towns, and those who are of the valley of Jezreel."
* `Jsh 20:4` And when he who flees to one of those cities stands at the entering of the gate of the city and declares his cause in the ears of the elders of that city, they shall take him into the city to them and give him a place so that he may *_dwell_* among them.
* `Jsh 20:6` And he shall *_dwell_* in that city until he stands before the congregation for judgment and until the death of the high-priest who shall be in those days. Then the slayer shall return and come to his own city and to his own house, to the city from where he fled.'"
* `Jsh 21:2` And they spoke to them at Shiloh in the land of Canaan, saying, "The LORD commanded by the hand of Moses to give us cities to *_dwell_* in, with their suburbs for our livestock."
* `Jsh 24:13` And I have given you a land for which you did not labor and cities which you did not build, and you *_dwell_* in them. You eat from the vineyards and olive-groves which you did not plant.'
* `Jsh 24:15` And if it seems evil to you to serve the LORD, choose this day whom you will serve, whether the gods which your fathers served who were on the other side of the flood, or the gods of the Amorites in whose land you *_dwell_*. But as for me and my house, we will serve the LORD."
* `Jdg 1:21` And the children of Benjamin did not drive out the Jebusites who inhabited Jerusalem, but the Jebusites *_dwell_* with the children of Benjamin in Jerusalem to this day.
* `Jdg 1:27` Manasseh did not expel the inhabitants of Beth-shean and its towns, nor Tanach and its towns, nor the inhabitants of Dor and its towns, nor the inhabitants of Ibleam and its towns, nor the inhabitants of Megiddo and its towns, but the Canaanites would *_dwell_* in that land.
* `Jdg 1:35` But the Amorites wished to *_dwell_* at mount Heres in Ajalon and in Shaalbim, but the hand of the house of Joseph prevailed, and they became tributaries.
* `Jdg 6:10` And I said to you, "I am the LORD your God. Do not fear the gods of the Amorites, in whose land you *_dwell_*. But you have not obeyed my voice."'"
* `Jdg 9:41` And Abimelech dwelt at Arumah, and Zebul thrust out Gaal and his brothers, so that they should not *_dwell_* in Shechem.
* `Jdg 17:10` And Micah said to him, "*_Dwell_* with me and be to me a father and a priest, and I will give you ten shekels of silver by the year, a suit of apparel, and your food." So the Levite went in.
* `Jdg 17:11` And the Levite was content to *_dwell_* with the man, and the young man became like one of his sons to him.
* `Jdg 18:1` In those days there was no king in Israel. And in those days the tribe of the Danites sought for themselves an inheritance to *_dwell_* in, for to that day all their inheritance had not fallen to them among the tribes of Israel.
* `Rth 1:1` Now it came to pass in the days when the judges ruled, that there was a famine in the land. And a certain man of Beth-lehem-judah went to *_dwell_* in the country of Moab—he, his wife, and his two sons.
* `1Sa 12:8` When Jacob had come into Egypt, and your fathers cried to the LORD, the LORD sent Moses and Aaron, who brought forth your fathers from Egypt and made them *_dwell_* in this place.
* `1Sa 27:5` And David said to Achish, "If I have now found grace in your eyes, let them give me a place in some town in the country so that I may *_dwell_* there. For why should your servant *_dwell_* in the royal city with you?"
* `2Sa 7:2` That the king said to Nathan the prophet, "See now, I *_dwell_* in a house of cedar, but the ark of God dwells within curtains."
* `2Sa 7:5` "Go and tell my servant David, 'Thus says the LORD: "Will you build a house for me to *_dwell_* in?
* `2Sa 7:10` Moreover, I will appoint a place for my people Israel and will plant them so that they may *_dwell_* in a place of their own and move no more, neither shall the children of wickedness afflict them anymore, as formerly,
* `1Ki 2:36` And the king sent and called for Shimei and said to him, "Build yourself a house in Jerusalem, *_dwell_* there, and do not go forth from there to any place.
* `1Ki 3:17` And one woman said, "O my lord, this woman and I *_dwell_* in one house, and I had delivered a child with her in the house.
* `1Ki 6:13` And I will *_dwell_* among the children of Israel and will not forsake my people Israel."
* `1Ki 8:12` Then Solomon spoke, "The LORD said that he would *_dwell_* in the thick darkness.
* `1Ki 8:13` I have surely built you a house to *_dwell_* in, a settled place for you to abide in forever."
* `1Ki 8:27` "But will God indeed *_dwell_* on the earth? Behold, the heaven and heaven of heavens cannot contain you. How much less this house that I have built?
* `1Ki 17:9` "Arise, go to Zarephath, which belongs to Zidon, and *_dwell_* there. Behold, I have commanded a widow woman there to sustain you."
* `2Ki 4:13` And he said to him, "Now say to her, 'Behold, you have been careful for us with all this care. What is to be done for you? Would you be spoken for to the king or to the captain of the host?'" And she answered, "I *_dwell_* among my own people."
* `2Ki 6:1` And the sons of the prophets said to Elisha, "Behold now, the place where we *_dwell_* with you is too narrow for us.
* `2Ki 6:2` Let us go, we pray you, to the Jordan and each take from there a beam, and let us make for ourselves a place there where we may *_dwell_*." And he answered, "Go."
* `2Ki 17:27` Then the king of Assyria commanded, saying, "Carry there one of the priests whom you brought from there, and let them go and *_dwell_* there, and let him teach them the manner of the God of the land."
* `2Ki 25:24` And Gedaliah swore to them and to their men and said to them, "Do not fear to be the servants of the Chaldeans. *_Dwell_* in the land and serve the king of Babylon, and it shall be well with you."
* `1Ch 17:1` Now it came to pass, as David sat in his house, that David said to Nathan the prophet, "Behold, I *_dwell_* in a house of cedars, but the ark of the covenant of the LORD remains under curtains."
* `1Ch 17:4` "Go and tell David my servant, 'Thus says the LORD: "You shall not build me a house to *_dwell_* in,
* `1Ch 17:9` Also, I will ordain a place for my people Israel and will plant them, and they shall *_dwell_* in their place and shall no longer be moved, neither shall the children of wickedness waste them anymore, as at the beginning,
* `1Ch 23:25` For David said, "The LORD God of Israel has given rest to his people so that they may *_dwell_* in Jerusalem forever.
* `2Ch 2:3` And Solomon sent to Huram the king of Tyre, saying, "As you dealt with David my father and sent him cedars to build him a house to *_dwell_* in it, even so deal with me.
* `2Ch 6:1` Then Solomon said, "The LORD has said that he would *_dwell_* in the thick darkness.
* `2Ch 6:18` "But will God indeed *_dwell_* with men on the earth? Behold, heaven and the heaven of heavens cannot contain you. How much less this house which I have built!
* `2Ch 8:2` That the cities which Huram had restored to Solomon, Solomon built them and caused the children of Israel to *_dwell_* there.
* `2Ch 8:11` And Solomon brought up the daughter of Pharaoh from the city of David to the house that he had built for her, for he said, "My wife shall not *_dwell_* in the house of David king of Israel, because the places are holy, to which the ark of the LORD has come."
* `2Ch 19:10` And whatever cause comes to you from your brothers who *_dwell_* in their cities, between blood and blood, between law and commandment, statutes and judgments, you shall even warn them that they do not trespass against the LORD so that wrath may not come upon you and upon your brothers. Do this and you shall not trespass.
* `Ezr 4:17` Then the king sent an answer to Rehum the chancellor, to Shimshai the scribe, and to the rest of their companions who *_dwell_* in Samaria, and to the rest beyond the river: "Peace, and at such a time.
* `Ezr 6:12` And may the God who has caused his name to *_dwell_* there destroy all kings and people who attempt to alter and to destroy this house of God which is at Jerusalem. I, Darius, have made a decree. Let it be done with speed."
* `Neh 8:14` And they found written in the law which the LORD had commanded by Moses, that the children of Israel should *_dwell_* in booths during the feast of the seventh month,
* `Neh 11:1` And the rulers of the people dwelt at Jerusalem. The rest of the people also cast lots to bring one of ten to *_dwell_* in Jerusalem the holy city, and nine parts to *_dwell_* in other cities.
* `Neh 11:2` And the people blessed all the men who willingly offered themselves to *_dwell_* at Jerusalem.
* `Job 3:5` Let darkness and the shadow of death stain it. Let a cloud *_dwell_* upon it. Let the blackness of the day terrify it.
* `Job 4:19` How much less in those who *_dwell_* in houses of clay, whose foundation is in the dust, who are crushed before the moth?
* `Job 11:14` If iniquity is in your hand, put it far away, and do not let wickedness *_dwell_* in your tabernacles.
* `Job 18:15` There shall *_dwell_* in his tabernacle that which is no longer his. Brimstone shall be scattered upon his habitation.
* `Job 19:15` Those who *_dwell_* in my house and my women-servants count me for a stranger. I am a foreigner in their sight.
* `Job 30:6` To *_dwell_* in the clefts of the valleys, in caves of the earth, and in the rocks.
* `Psa 4:8` I will both lay myself down in peace and sleep, for you only, LORD, make me *_dwell_* in safety.
* `Psa 5:4` For you are not a God who has pleasure in wickedness, neither shall evil *_dwell_* with you.
* `Psa 15:1` [A Psalm of David.] LORD, who shall abide in your tabernacle? Who shall *_dwell_* on your holy hill?
* `Psa 23:6` Surely goodness and mercy shall follow me all the days of my life. And I will *_dwell_* in the house of the LORD forever.
* `Psa 24:1` [A Psalm of David.] The earth is the LORD'S, and the fullness thereof, the world, and those who *_dwell_* therein.
* `Psa 25:13` [MEM] His soul shall *_dwell_* at ease and his offspring shall inherit the earth.
* `Psa 27:4` One thing I have desired of the LORD that I will seek after: that I may *_dwell_* in the house of the LORD all the days of my life to behold the beauty of the LORD and to inquire in his temple.
* `Psa 37:3` Trust in the LORD and do good. *_Dwell_* in the land, and truly you shall be fed.
* `Psa 37:27` Depart from evil and do good, and *_dwell_* forevermore.
* `Psa 37:29` The righteous shall inherit the land and *_dwell_* therein forever.
* `Psa 65:4` Blessed is the man whom you choose and cause to approach you so that he may *_dwell_* in your courts. We shall be satisfied with the goodness of your house, even of your holy temple.
* `Psa 65:8` Also those who *_dwell_* in the uttermost parts are in awe of your signs. You make the outgoings of the morning and evening to rejoice.
* `Psa 68:6` God sets the solitary in families. He brings out those who are bound with chains. But the rebellious *_dwell_* in a dry land.
* `Psa 68:16` Why do you leap, you lofty hills? This is the hill which God desires to *_dwell_* in. Indeed, the LORD will *_dwell_* in it forever.
* `Psa 68:18` You have ascended on high. You have led captivity captive. You have received gifts among men, even among the rebellious also, so that the LORD God might *_dwell_* with them.
* `Psa 69:25` Let their habitation be desolate, and let no one *_dwell_* in their tents.
* `Psa 69:35` For God will save Zion and build the cities of Judah so that they may *_dwell_* there and have it in possession.
* `Psa 69:36` The offspring of his servants shall also inherit it. And those who love his name shall *_dwell_* therein.
* `Psa 72:9` Those who *_dwell_* in the wilderness shall bow before him, and his enemies shall lick the dust.
* `Psa 78:55` He also cast out the heathen before them. He divided them an inheritance by line and made the tribes of Israel to *_dwell_* in their tents.
* `Psa 80:1` [To the Chief Musician upon Shoshannim Eduth. A Psalm of Asaph.] Give ear, O Shepherd of Israel, you who lead Joseph like a flock. You who *_dwell_* between the cherubim, shine forth.
* `Psa 84:4` Blessed are those who *_dwell_* in your house. They are always praising you. [Selah.]
* `Psa 84:10` For a day in your courts is better than a thousand [elsewhere]. I would rather be a door-keeper in the house of my God than *_dwell_* in the tents of wickedness.
* `Psa 85:9` Surely his salvation is near those who fear him so that glory may *_dwell_* in our land.
* `Psa 98:7` Let the sea roar and its fullness, the world and those who *_dwell_* therein.
* `Psa 101:6` My eyes shall be upon the faithful of the land so that they may *_dwell_* with me. He who walks in a perfect way, he shall serve me.
* `Psa 101:7` He who works deceit shall not *_dwell_* within my house. He who tells lies shall not remain in my sight.
* `Psa 107:4` They wandered in the wilderness in a solitary way. They found no city to *_dwell_* in.
* `Psa 107:34` And a fruitful land into barrenness because of the wickedness of those who *_dwell_* in it.
* `Psa 107:36` And there he makes the hungry to *_dwell_* so that they may prepare a city for habitation.
* `Psa 120:5` Woe is me that I sojourn in Mesech, that I *_dwell_* in the tents of Kedar!
* `Psa 123:1` [A Song of Degrees.] I raise my eyes to you, O you who *_dwell_* in the heavens.
* `Psa 132:14` "This is my rest forever. Here I will *_dwell_*, for I have desired it.
* `Psa 133:1` [A Song of Degrees of David.] Behold, how good and how pleasant it is for brothers to *_dwell_* together in unity!
* `Psa 139:9` If I take the wings of the morning and *_dwell_* in the uttermost parts of the sea,
* `Psa 140:13` Surely the righteous shall give thanks to your name. The upright shall *_dwell_* in your presence.
* `Psa 143:3` For the enemy has persecuted my soul. He has smitten my life down to the ground. He has made me to *_dwell_* in darkness like those who have been long dead.
* `Pro 1:33` But whoever listens to me shall *_dwell_* in safety and shall be quiet from fear of evil."
* `Pro 2:21` For the upright shall *_dwell_* in the land, and the perfect shall remain in it.
* `Pro 8:12` I, wisdom, *_dwell_* with prudence and find out knowledge of ingenious inventions.
* `Pro 21:9` It is better to *_dwell_* in a corner of the house-top, than with a brawling woman in a wide house.
* `Pro 21:19` It is better to *_dwell_* in the wilderness than with a contentious and angry woman.
* `Pro 25:24` It is better to *_dwell_* in a corner of the house-top than with a brawling woman and in a wide house.
* `Sos 8:13` [Gentleman:] You who *_dwell_* in the gardens, the companions listen to your voice. Cause me to hear it.
* `Isa 6:5` Then I said, "Woe is me! For I am undone because I am a man of unclean lips and I *_dwell_* in the midst of a people of unclean lips. For my eyes have seen the King, the LORD of hosts."
* `Isa 9:2` The people who walked in darkness have seen a great light. Those who *_dwell_* in the land of the shadow of death, upon them the light has shined.
* `Isa 10:24` Therefore, thus says the Lord GOD of hosts: "O my people who *_dwell_* in Zion, do not be afraid of the Assyrian. He shall smite you with a rod and shall lift up his staff against you after the manner of Egypt.
* `Isa 11:6` The wolf shall also *_dwell_* with the lamb, and the leopard shall lie down with the kid. The calf, the young lion, and the fattened calf shall be together, and a little child shall lead them.
* `Isa 13:21` But wild beasts of the desert shall lie there, and their houses shall be full of doleful creatures. Owls shall *_dwell_* there, and wild goats shall dance there.
* `Isa 16:4` Let my outcasts *_dwell_* with you, Moab. Be a covert to them from the face of the destroyer. For the extortioner is at an end. Devastation ceases. The oppressors are consumed out of the land.
* `Isa 23:13` Behold the land of the Chaldeans. This people was not, until the Assyrian founded it for those who *_dwell_* in the wilderness. They set up its towers, they raised up its palaces, and they brought it to ruin.
* `Isa 23:18` And her merchandise and her wages shall be holiness to the LORD. It shall not be treasured nor laid up, for her merchandise shall be for those who *_dwell_* before the LORD, for sufficient food and for durable clothing.
* `Isa 24:6` Therefore, the curse has devoured the earth, and those who *_dwell_* in it are desolate. Therefore, the inhabitants of the earth are burned and few men are left.
* `Isa 26:5` For he brings down those who *_dwell_* on high. The lofty city, he lays it low. He lays it low, even to the ground. He brings it even to the dust.
* `Isa 26:19` Your dead men shall live. Together with my dead body they shall arise. Awake and sing, you who *_dwell_* in dust, for your dew is like the dew of herbs, and the earth shall cast out the dead.
* `Isa 30:19` For the people shall *_dwell_* in Zion at Jerusalem. You shall no longer weep. He will be very gracious to you at the voice of your cry. When he hears it, he will answer you.
* `Isa 32:16` Then judgment shall *_dwell_* in the wilderness, and righteousness shall remain in the fruitful field.
* `Isa 32:18` And my people shall *_dwell_* in a peaceable habitation, in sure dwellings, and in quiet resting-places,
* `Isa 33:14` The sinners in Zion are afraid. Fearfulness has surprised the hypocrites. "Who among us shall *_dwell_* with the devouring fire? Who among us shall *_dwell_* with everlasting burnings?"
* `Isa 33:16` He shall *_dwell_* on high. His place of defense shall be the fortresses of rocks. Bread shall be given to him. His waters shall be sure.
* `Isa 33:24` And the inhabitants shall not say, "I am sick." The people who *_dwell_* therein shall have their iniquity forgiven.
* `Isa 34:11` But the cormorant and the bittern shall possess it. The owl and the raven shall *_dwell_* in it. And he shall stretch out upon it the line of confusion and the stones of emptiness.
* `Isa 34:17` And he has cast the lot for them, and his hand has divided it to them by line. They shall possess it forever. From generation to generation they shall *_dwell_* therein.
* `Isa 40:22` It is he who sits upon the circle of the earth, and its inhabitants are like locusts, who stretches out the heavens like a curtain and spreads them out like a tent to *_dwell_* in.
* `Isa 47:8` Now therefore, hear this, you who are given to pleasures, who *_dwell_* carelessly, who say in your heart, 'I am, and no one else besides me. I shall not sit as a widow, neither shall I know the loss of children.'
* `Isa 49:20` The children which you shall have, after you have lost the other, shall say again in your ears, 'The place is too narrow for me. Give place to me so that I may *_dwell_*.'
* `Isa 57:15` For thus says the high and lofty One who inhabits eternity, whose name is Holy: "I *_dwell_* in the high and holy place, with him also who is of a contrite and humble spirit, to revive the spirit of the humble and to revive the heart of the contrite ones.
* `Isa 58:12` And those amidst you shall build the old waste places. You shall raise up the foundations of many generations, and you shall be called, The Repairer of the Breach, The Restorer of Paths to *_Dwell_* In.
* `Isa 65:9` And I will bring forth offspring out of Jacob, and out of Judah an inheritor of my mountains. And my elect shall inherit it and my servants shall *_dwell_* there.
* `Jer 7:3` Thus says the LORD of hosts, the God of Israel: "Amend your ways and your doings, and I will cause you to *_dwell_* in this place.
* `Jer 7:7` Then I will cause you to *_dwell_* in this place, in the land that I gave to your fathers, forever and ever.
* `Jer 8:16` The snorting of his horses was heard from Dan. The whole land trembled at the sound of the neighing of his strong ones, for they have come and have devoured the land and all that is in it, and also the city and those who *_dwell_* therein.
* `Jer 8:19` Behold the voice of the cry of the daughter of my people because of those who *_dwell_* in a distant country: "Is the LORD not in Zion? Is her king not in her?" "Why have they provoked me to anger with their engraved images and with strange vanities?"
* `Jer 9:26` Egypt, Judah, Edom, the children of Ammon, Moab, and all who are in the utmost corners who *_dwell_* in the wilderness. For all these nations are uncircumcised, and all the house of Israel are uncircumcised in the heart."
* `Jer 12:4` How long shall the land mourn and the herbs of every field wither for the wickedness of those who *_dwell_* therein? The beasts are consumed, and also the birds, because they said, "He will not see our last end."
* `Jer 20:6` And you, Pashur, and all who *_dwell_* in your house, shall go into captivity. And you shall come to Babylon, and there you shall die and be buried—you and all your friends to whom you have prophesied lies.'"
* `Jer 23:6` In his days Judah shall be saved, and Israel shall *_dwell_* in safety. And this is his name by which he shall be called: YAHWEH OUR RIGHTEOUSNESS.
* `Jer 23:8` But, 'The LORD lives, who brought and who led the offspring of the house of Israel out of the north country and from all countries where I have driven them,' and they shall *_dwell_* in their own land."
* `Jer 24:8` 'And as the bad figs, which cannot be eaten they are so bad,' surely thus says the LORD: 'So I will give up Zedekiah the king of Judah, his princes, the remnant of Jerusalem who remain in this land, and those who *_dwell_* in the land of Egypt.
* `Jer 25:5` They said, 'Turn back now each from his evil way and from the evil of your doings, and *_dwell_* in the land that the LORD has given to you and to your fathers forever and ever,
* `Jer 25:24` All the kings of Arabia, all the kings of the mingled people who *_dwell_* in the desert;
* `Jer 27:11` But the nations that bring their neck under the yoke of the king of Babylon and serve him, those I will let remain in their own land,' says the LORD, 'and they shall till it and *_dwell_* in it.'"'"
* `Jer 29:5` 'Build houses and *_dwell_* in them. Plant gardens and eat their fruit.
* `Jer 29:16` Know that thus says the LORD concerning the king who sits upon the throne of David, concerning all the people who *_dwell_* in this city, and concerning your brothers who have not gone forth with you into captivity—
* `Jer 29:28` For therefore he sent to us in Babylon, saying, 'This captivity is long. Build houses and *_dwell_* in them. Plant gardens and eat their fruit.'"'"
* `Jer 29:32` Therefore, thus says the LORD: "Behold, I will punish Shemaiah the Nehelamite and his offspring. He shall not have a man to *_dwell_* among this people, neither shall he behold the good that I will do for my people," says the LORD, "because he has taught rebellion against the LORD."'"
* `Jer 31:24` "And there shall *_dwell_* in Judah itself and in all her cities together farmers and those who go forth with flocks.
* `Jer 32:37` 'Behold, I will gather them out of all countries where I have driven them in my anger, in my fury, and in great wrath, and I will bring them back to this place and cause them to *_dwell_* in safety.
* `Jer 33:16` In those days Judah shall be saved and Jerusalem shall *_dwell_* in safety. And this is the name by which she shall be called: YAHWEH Our Righteousness.'
* `Jer 35:7` Neither shall you build house, sow seed, plant vineyard, nor have any. But all your days you shall *_dwell_* in tents so that you may live many days in the land where you are strangers.'
* `Jer 35:9` Nor to build houses for us to *_dwell_* in, neither do we have vineyard, field, nor seed.
* `Jer 35:11` But it came to pass when Nebuchadnezzar king of Babylon came up into the land, that we said, 'Come, and let us go to Jerusalem for fear of the army of the Chaldeans and for fear of the army of the Syrians.' So we *_dwell_* at Jerusalem."
* `Jer 35:15` I have also sent to you all my servants the prophets, rising early and sending them, saying, 'Return each of you now from his evil way, amend your doings, and do not go after other gods to serve them, and you shall *_dwell_* in the land which I have given to you and to your fathers. But you have not inclined your ear nor listened to me.
* `Jer 40:5` Now while he had not yet gone back, he said, "Go back also to Gedaliah the son of Ahikam the son of Shaphan, whom the king of Babylon has made governor over the cities of Judah, and *_dwell_* with him among the people, or go wherever it seems convenient for you to go." So the captain of the guard gave him provisions and a reward and let him go.
* `Jer 40:9` And Gedaliah the son of Ahikam, the son of Shaphan, swore to them and to their men, saying, "Do not fear to serve the Chaldeans. *_Dwell_* in the land and serve the king of Babylon, and it shall be well with you.
* `Jer 40:10` As for me, behold, I will *_dwell_* at Mizpah to serve the Chaldeans who will come to us. But you, gather wine, summer fruits, and oil, and put them in your vessels and *_dwell_* in your cities that you have taken."
* `Jer 42:13` But if you say, "We will not *_dwell_* in this land," neither obey the voice of the LORD your God,
* `Jer 42:14` Saying, "No, but we will go into the land of Egypt where we shall see no war, nor hear the sound of the trumpet, nor hunger for bread. And there we will *_dwell_*,"
* `Jer 43:4` So Johanan the son of Kareah, all the captains of the forces, and all the people did not obey the voice of the LORD to *_dwell_* in the land of Judah.
* `Jer 43:5` But Johanan the son of Kareah and all the captains of the forces took all the remnant of Judah, who had returned from all nations where they had been driven, to *_dwell_* in the land of Judah—
* `Jer 44:1` A word came to Jeremiah concerning all the Jews who *_dwell_* in the land of Egypt, who *_dwell_* at Migdol, at Tahpanhes, at Noph, and in the country of Pathros, saying,
* `Jer 44:8` In that you provoke me to wrath with the works of your hands, burning incense to other gods in the land of Egypt where you have gone to *_dwell_*, so that you may cut yourselves off and that you may be a curse and a reproach among all the nations of the earth?
* `Jer 44:13` For I will punish those who *_dwell_* in the land of Egypt, as I have punished Jerusalem, by the sword, by the famine, and by the pestilence,
* `Jer 44:14` So that none of the remnant of Judah who have gone into the land of Egypt to sojourn there shall escape or remain to return into the land of Judah, to which they have a desire to return to *_dwell_* there. For none shall return but those who escape.'"
* `Jer 44:26` Therefore, hear the word of the LORD, all you of Judah who *_dwell_* in the land of Egypt: 'Behold, I have sworn by my great name,' says the LORD, 'that my name shall no longer be named in the mouth of any man of Judah in all the land of Egypt, saying, "The Lord GOD lives."
* `Jer 47:2` Thus says the LORD: "Behold, waters rise out of the north and shall be an overflowing flood. They shall overflow the land and all that is in it—the city and those who *_dwell_* therein. Then the men shall cry, and all the inhabitants of the land shall howl.
* `Jer 48:9` Give wings to Moab so that it may flee and get away, for its cities shall be desolate without any to *_dwell_* in them.
* `Jer 48:28` "O you who *_dwell_* in Moab, leave the cities, *_dwell_* in the rock, and be like the dove that makes her nest in the sides of the hole's mouth.
* `Jer 49:1` [Concerning the Ammonites.] Thus says the LORD: "Does Israel have no sons? Does he have no heir? Why then does their king inherit Gad, and his people *_dwell_* in his cities?
* `Jer 49:8` Flee, turn back, *_dwell_* deep, O inhabitants of Dedan, for I will bring the calamity of Esau upon him, the time that I will visit him.
* `Jer 49:16` Your terribleness has deceived you, and the pride of your heart, O you who *_dwell_* in the clefts of the rock, who hold the height of the hill. Though you should make your nest as high as the eagle, I will bring you down from there," says the LORD.
* `Jer 49:18` As in the overthrow of Sodom and Gomorrah and the neighboring cities," says the LORD, "no man shall abide there, neither shall a son of man *_dwell_* in it.
* `Jer 49:30` Flee, get yourselves far off, *_dwell_* deep, O inhabitants of Hazor," says the LORD, "for Nebuchadnezzar king of Babylon has taken counsel against you and has conceived a purpose against you.
* `Jer 49:33` "And Hazor shall be a dwelling for jackals and a desolation forever. No man shall abide there. No son of man shall *_dwell_* in it."
* `Jer 50:3` For out of the north there comes a nation against her which shall make her land desolate, and no one shall *_dwell_* in it. They shall flee, they shall depart—both man and beast.
* `Jer 50:39` Therefore, the wild beasts of the desert and the wolves shall *_dwell_* there, and the owls shall *_dwell_* therein. And it shall be no longer inhabited forever, neither shall it be dwelt in from generation to generation.
* `Jer 50:40` As God overthrew Sodom and Gomorrah and the neighboring cities," says the LORD, "so shall no man abide there, neither shall any son of man *_dwell_* therein.
* `Jer 51:1` Thus says the LORD: "Behold, I will raise up a destroying wind against Babylon and against those who *_dwell_* in the midst of those who rise against me,
* `Jer 51:13` O you who *_dwell_* upon many waters, abundant in treasures, your end has come, and the measure of your covetousness.
* `Ezk 2:6` And you, son of man, do not be afraid of them, neither be afraid of their words, even though briers and thorns are with you and you *_dwell_* among scorpions. Do not be afraid of their words nor be dismayed at their looks, though they are a rebellious house.
* `Ezk 7:7` The morning has come upon you, O you who *_dwell_* in the land. The time has come. The day of trouble is near, and not of joyful shouting upon the mountains.
* `Ezk 12:2` "Son of man, you *_dwell_* in the midst of a rebellious house. They have eyes to see but do not see, and ears to hear but do not hear, for they are a rebellious house.
* `Ezk 12:19` And say to the people of the land, 'Thus says the Lord GOD of the inhabitants of Jerusalem and of the land of Israel: "They shall eat their bread with solicitude and drink their water with astonishment, for her land will be desolate from all that is therein because of the violence of all those who *_dwell_* therein.
* `Ezk 16:46` And your elder sister is Samaria—she and her daughters who *_dwell_* at your left hand. And your younger sister, who dwells at your right hand, is Sodom with her daughters.
* `Ezk 17:23` On the mountain of the height of Israel I will plant it. And it shall bring forth boughs, bear fruit, and be a majestic cedar. And under it all birds of every wing shall *_dwell_*. In the shade of its branches they shall *_dwell_*.
* `Ezk 28:25` 'Thus says the Lord GOD: "When I have gathered the house of Israel from the people among whom they are scattered and have been sanctified in them in the sight of the heathen, they shall *_dwell_* in their land that I have given to my servant Jacob.
* `Ezk 28:26` And they shall *_dwell_* safely therein, and shall build houses and plant vineyards. They shall even *_dwell_* with confidence when I have executed judgments upon all those around them who despise them. And they shall know that I am the LORD their God."'"
* `Ezk 32:15` "When I make the land of Egypt desolate and the country is destitute of that of which it was full, when I smite all those who *_dwell_* in it, they shall know that I am the LORD.
* `Ezk 34:25` "And I will make with them a covenant of peace and will cause the evil beasts to cease out of the land. And they shall *_dwell_* safely in the wilderness and sleep in the woods.
* `Ezk 34:28` And they shall no longer be a prey to the heathen, neither shall the beast of the land devour them, but they shall *_dwell_* safely, and no one shall make them afraid.
* `Ezk 36:28` And you shall *_dwell_* in the land that I gave to your fathers. And you shall be my people, and I will be your God.
* `Ezk 36:33` 'Thus says the Lord GOD: "In the day that I have cleansed you from all your iniquities I will also cause you to *_dwell_* in the cities, and the wastes shall be built.
* `Ezk 37:25` And they shall *_dwell_* in the land that I have given to Jacob my servant, in which your fathers have dwelt, and they shall *_dwell_* in it—even they, their children, and their children's children forever. And my servant David shall be their prince forever.
* `Ezk 38:8` After many days you shall be visited. In the latter years you shall come into the land that is brought back from the sword and is gathered out of many people, against the mountains of Israel, which have always been waste. But it is brought forth out of the nations and they shall all *_dwell_* in safety.
* `Ezk 38:11` And you shall say, 'I will go up to the land of unwalled villages. I will go to those who are at rest, who *_dwell_* safely, all of them dwelling without walls and having neither bars nor gates'—
* `Ezk 38:12` To take loot and to take plunder, to turn your hand upon the desolate places that are now inhabited and upon the people who are gathered out of the nations, which have gotten livestock and goods, who *_dwell_* in the midst of the land.
* `Ezk 38:14` "Therefore, son of man, prophesy and say to Gog, 'Thus says the Lord GOD: "In that day when my people of Israel *_dwell_* safely, shall you not know it?
* `Ezk 39:6` "And I will send a fire on Magog and among those who *_dwell_* carelessly in the coastlands. And they shall know that I am the LORD.
* `Ezk 39:9` "And those who *_dwell_* in the cities of Israel shall go forth and set on fire and burn the weapons: the shields, the bucklers, the bows and the arrows, the hand-staffs, and the spears. And they shall burn them with fire for seven years
* `Ezk 39:26` And they shall bear their shame and all their trespasses by which they have trespassed against me when they *_dwell_* safely in their land and no one makes them afraid,
* `Ezk 43:7` And he said to me, "Son of man, this is the place of my throne and the place of the soles of my feet where I will *_dwell_* in the midst of the children of Israel forever. And the house of Israel shall no more defile my holy name—neither they, nor their kings—by their lewd deeds, nor by the carcasses of their kings in their high places.
* `Ezk 43:9` Now let them put away their lewd deeds and the carcasses of their kings far from me, and I will *_dwell_* in the midst of them forever.
* `Dan 2:38` And wherever the children of men *_dwell_*, or the beasts of the field, or the birds of the heaven, he has given into your hand and has made you ruler over them all. You are this head of gold.
* `Dan 4:1` Nebuchadnezzar the king, to all people, nations, and languages who *_dwell_* in all the earth: "May peace be multiplied to you.
* `Dan 6:25` Then king Darius wrote to all people, nations, and languages who *_dwell_* in all the earth: "May peace be multiplied to you.
* `Hos 9:3` They shall not *_dwell_* in the LORD'S land, but Ephraim shall return to Egypt and they shall eat unclean things in Assyria.
* `Hos 12:9` "And I am the LORD your God from the land of Egypt. I will yet make you to *_dwell_* in tabernacles, as in the days of the solemn feast.
* `Hos 14:7` Those who *_dwell_* under his shadow shall return. They shall revive as the grain and grow as the vine. Its scent shall be as the wine of Lebanon.
* `Joe 3:20` But Judah shall *_dwell_* forever, and Jerusalem from generation to generation.
* `Amo 3:12` Thus says the LORD: "As the shepherd rescues out of the mouth of the lion two legs, or a piece of an ear, so the children of Israel shall be rescued who *_dwell_* in Samaria on the corner of a bed and in Damascus on a couch.
* `Amo 5:11` Because your treading is upon the poor and you take burdens of wheat from him, therefore you have built houses of hewn stone, but you shall not *_dwell_* in them. And you have planted pleasant vineyards, but you shall not drink their wine.
* `Amo 9:5` And the Lord GOD of hosts is he who touches the land, and it shall melt, and all who *_dwell_* in it shall mourn. And it shall rise up wholly like a flood, and shall be drowned as by the flood of Egypt.
* `Oba 1:3` The pride of your heart has deceived you, you who *_dwell_* in the clefts of the rock, whose habitation is high, who says in his heart, 'Who shall bring me down to the ground?'
* `Mic 4:10` Be in pain and labor to bring forth, O daughter of Zion, like a woman in travail. For now you shall go forth from the city and you shall *_dwell_* in the field, and you shall go even to Babylon. There you shall be delivered. There the LORD shall redeem you from the hand of your enemies.
* `Mic 7:13` But the land shall be desolate because of those who *_dwell_* in it, for the fruit of their doings.
* `Mic 7:14` Feed your people with your rod, the flock of your heritage, who *_dwell_* solitarily in the forest, in the midst of Carmel. Let them feed in Bashan and Gilead, as in the days of old.
* `Nah 1:5` The mountains quake at him and the hills melt. The earth is upheaved at his presence, even the world and all who *_dwell_* therein.
* `Nah 3:18` Your shepherds slumber, O king of Assyria. Your nobles shall *_dwell_* in the dust. Your people are scattered upon the mountains and no man gathers them.
* `Hab 2:8` Because you have laid waste many nations, all the remnant of the people shall lay you waste, because of men's blood and for the violence done to the land, to the city, and to all who *_dwell_* therein.
* `Hab 2:17` For the violence done to Lebanon shall overwhelm you, and the destruction of the beasts shall make you afraid, because of men's blood and for the violence done to the land, to the city, and to all who *_dwell_* therein.
* `Zph 1:18` Neither their silver nor their gold shall be able to deliver them in the day of the LORD'S wrath. But the whole land shall be devoured by the fire of his jealousy, for he will make even a sudden end of all those who *_dwell_* in the land.
* `Hag 1:4` "Is it a time for you yourselves to *_dwell_* in your ceiled houses and this house lie waste?"
* `Zch 2:7` "Deliver yourself, O Zion, who *_dwell_* with the daughter of Babylon."
* `Zch 2:10` Sing and rejoice, O daughter of Zion. For behold, I come and I will *_dwell_* in the midst of you," says the LORD.
* `Zch 2:11` "And many nations shall be joined to the LORD in that day and shall be my people. And I will *_dwell_* in the midst of you, and you shall know that the LORD of hosts has sent me to you.
* `Zch 8:3` Thus says the LORD: 'I have returned to Zion and will *_dwell_* in the midst of Jerusalem. And Jerusalem shall be called a city of truth, and the mountain of the LORD of hosts, the holy mountain.'
* `Zch 8:4` Thus says the LORD of hosts: 'Old men and old women shall yet *_dwell_* in the streets of Jerusalem, and every man with his staff in his hand for abundance of age.
* `Zch 8:8` And I will bring them and they shall *_dwell_* in the midst of Jerusalem. And they shall be my people, and I will be their God, in truth and in righteousness.'
* `Zch 9:6` And a foreigner shall *_dwell_* in Ashdod, and I will cut off the pride of the Philistines.
* `Zch 14:11` And men shall *_dwell_* in it, and there shall no longer be utter destruction. And Jerusalem shall be safely inhabited.
* `Mth 12:45` Then he goes, and takes with himself seven other spirits more wicked than himself, and they enter in and *_dwell_* there. And the last state of that man is worse than the first. Thus it shall also be to this wicked generation."
* `Luk 11:26` Then he goes and takes with him seven other spirits more wicked than himself, and they enter in and *_dwell_* there. Then the last state of that man is worse than the first."
* `Luk 21:35` For it shall come like a snare on all those who *_dwell_* on the face of the whole earth.
* `Jhn 1:38` Then Jesus turned and saw them following, and says to them, "What do you seek?" They said to him, "Rabbi"—which is to say, being interpreted, Master—"where do you *_dwell_*?"
* `Act 1:20` "For it is written in the book of Psalms, 'Let his habitation be desolate, and let no man *_dwell_* in it,' and, 'Let another take his office.'
* `Act 2:14` But Peter, standing up with the eleven, lifted up his voice and said to them, "Men of Judea and all you who *_dwell_* at Jerusalem, may this be known to you, and listen to my words.
* `Act 4:16` Saying, "What shall we do to these men? For that indeed a notable miracle has been done by them is manifest to all those who *_dwell_* in Jerusalem, and we cannot deny it.
* `Act 7:4` Then he came from the land of the Chaldeans and dwelt in Haran. And from there, when his father was dead, he moved him into this land in which you now *_dwell_*.
* `Act 7:48` Yet, the Most High does not *_dwell_* in temples made with hands, as says the prophet,
* `Act 13:27` For those who *_dwell_* at Jerusalem, and their rulers, because they did not know him, nor yet the words of the prophets which are read every sabbath, they have fulfilled them in condemning him.
* `Act 17:24` God who made the world and all things therein, seeing that he is Lord of heaven and earth, does not *_dwell_* in temples made with hands,
* `Act 17:26` And has made of one blood all nations of men to *_dwell_* on all the face of the earth and has determined the times before appointed and the bounds of their habitation,
* `Act 28:16` And when we came to Rome, the centurion delivered the prisoners to the captain of the guard, but Paul was allowed to *_dwell_* by himself, with a soldier who kept him.
* `1Co 7:12` But to the rest I speak, not the Lord, if any brother has a wife who does not believe and she is pleased to *_dwell_* with him, let him not put her away.
* `1Co 7:13` And if a woman has a husband who does not believe and he is pleased to *_dwell_* with her, let her not leave him.
* `2Co 6:16` And what agreement has the temple of God with idols? For you are the temple of the living God, as God has said, "'I will *_dwell_* in them' and walk in them. 'And I will be their God, and they shall be my people.'"
* `Eph 3:17` So that Christ may *_dwell_* in your hearts by faith, and that you, being rooted and grounded in love,
* `Col 1:19` For it pleased the Father that all fullness should *_dwell_* in him,
* `Col 3:16` Let the word of Christ *_dwell_* in you richly in all wisdom, teaching and admonishing one another in psalms, hymns, and spiritual songs, singing with grace in your hearts to the Lord.
* `1Pe 3:7` Likewise, husbands, *_dwell_* with them according to knowledge, giving honor to the wife as to the weaker vessel and as being heirs together of the grace of life, so that your prayers are not hindered.
* `1Jn 3:17` But he who has this world's goods and sees his brother have need and shuts up his heart of compassion from him, how does the love of God *_dwell_* in him?
* `1Jn 4:13` By this we know that we *_dwell_* in him and he in us: because he has given us of his Spirit.
* `Rev 2:13` "'"I know your works and where you *_dwell_*, even where Satan's seat is. And you hold firmly to my name and have not denied my faith, even in those days wherein Antipas was my faithful martyr, who was slain among you where Satan dwells.
* `Rev 3:10` Because you have kept the word of my patience, I also will keep you from the hour of temptation, which shall come upon all the world to try those who *_dwell_* upon the earth.
* `Rev 6:10` And they cried with a loud voice, saying, "How long, O Lord, holy and true, do you not judge and avenge our blood on those who *_dwell_* on the earth?"
* `Rev 7:15` Therefore, they are before the throne of God and serve him day and night in his temple. And he who sits on the throne will *_dwell_* among them.
* `Rev 8:13` And I beheld, and heard an angel flying through the midst of heaven, saying with a loud voice, "Woe, woe, woe to those who *_dwell_* on the earth by reason of the other voices of the trumpet of the three angels which are about to sound!"
* `Rev 11:10` And those who *_dwell_* upon the earth shall rejoice over them and make merry and shall send gifts to one another because these two prophets tormented those who dwelt on the earth.
* `Rev 12:12` Therefore, rejoice, you heavens and you who *_dwell_* in them. Woe to the earth and to the sea! For the devil has come down to you having great wrath because he knows that he has only a short time."
* `Rev 13:6` And he opened his mouth in blasphemy against God to blaspheme his name, his tabernacle, and those who *_dwell_* in heaven.
* `Rev 13:8` And all who *_dwell_* upon the earth shall worship him, whose names are not written in the book of life of the Lamb slain from the foundation of the world.
* `Rev 13:12` And he exercises all the power of the first beast before him and causes the earth and those who *_dwell_* in it to worship the first beast, whose deadly wound was healed.
* `Rev 13:14` He deceives those who *_dwell_* on the earth by the means of those miracles which he had power to do in the sight of the beast, saying to those who *_dwell_* on the earth that they should make an image to the beast which was wounded by the sword and lived.
* `Rev 14:6` And I saw another angel fly in the midst of heaven, having the everlasting gospel to preach to those who *_dwell_* on the earth and to every nation, kindred, language, and people,
* `Rev 17:8` The beast that you saw, it was and is no more. And it shall ascend out of the bottomless pit and go into perdition. And those who *_dwell_* on the earth shall wonder, whose names were not written in the book of life from the foundation of the world, when they behold the beast that was, is no more, and yet is.
* `Rev 21:3` And I heard a great voice out of heaven, saying, "Behold, the tabernacle of God is with men. He will *_dwell_* with them, and they shall be his people, and God himself will be with them and be their God.

_337 verses containing DWELL_

== DWELLERS

* `Isa 18:3` All you inhabitants of the world and *_dwellers_* on the earth, see when he lifts up an ensign on the mountains. And when he blows a trumpet, hear.
* `Act 1:19` And it was known to all the *_dwellers_* at Jerusalem, so that in their proper language that field is called, Aceldama, that is to say, The Field of Blood.)
* `Act 2:9` Parthians, Medes, Elamites, the *_dwellers_* in Mesopotamia, in Judea, Cappadocia, in Pontus, Asia,

_3 verses containing DWELLERS_

== DWELLING

* `Gen 10:30` And their *_dwelling_* was from Mesha, as far as to Sephar, a mountain of the east.
* `Gen 25:27` And the boys grew. And Esau was a skillful hunter, a man of the field, and Jacob was a plain man *_dwelling_* in tents.
* `Gen 27:39` And Isaac his father answered and said to him, "Behold, your *_dwelling_* shall be the fatness of the earth and of the dew of heaven from above.
* `Lev 13:46` All the days in which the plague is in him he shall be defiled. He is unclean. He shall dwell alone. His *_dwelling_* shall be outside the camp.
* `Lev 25:29` 'And if a man sells a *_dwelling_*-house in a walled city, then he may redeem it within a whole year after it is sold. Within a full year he may redeem it.
* `Num 21:15` And at the stream of the brooks that goes down to the *_dwelling_* of Ar, and lies upon the border of Moab."
* `Num 24:21` And he looked at the Kenites and took up his parable and said, "Your *_dwelling_*-place is strong and you put your nest in a rock.
* `Jdg 19:1` And it came to pass in those days when there was no king in Israel, that there was a certain Levite *_dwelling_* on the side of mount Ephraim, who took for himself a concubine out of Beth-lehem-judah.
* `1Ki 8:30` And listen to the supplication of your servant and of your people Israel when they pray toward this place. And hear in heaven your *_dwelling_*-place. And when you hear, forgive.
* `1Ki 8:39` Then hear in heaven your *_dwelling_*-place, and forgive, do, and give to each according to his ways, whose heart you know (for you, even you only, know the hearts of all the children of men),
* `1Ki 8:43` Then hear in heaven your *_dwelling_*-place and do according to all that the stranger calls to you for so that all people of the earth may know your name to fear you, as do your people Israel, and that they may know that this house which I have built is called by your name.
* `1Ki 8:49` Then hear their prayer and their supplication in heaven your *_dwelling_*-place, maintain their cause,
* `1Ki 21:8` So she wrote letters in Ahab's name, sealed them with his seal, and sent the letters to the elders and to the nobles who were in his city, *_dwelling_* with Naboth.
* `2Ki 17:25` And it was so at the beginning of their *_dwelling_* there, that they did not fear the LORD. Therefore, the LORD sent lions among them which slew some of them.
* `2Ki 19:15` And Hezekiah prayed before the LORD and said, "O LORD God of Israel, *_dwelling_* between the cherubim, you are the God, even you alone, of all the kingdoms of the earth. You have made heaven and earth.
* `1Ch 6:32` And they ministered before the *_dwelling_*-place of the Tabernacle of the Congregation with singing until Solomon had built the house of the LORD in Jerusalem, and then they waited on their office according to their order.
* `1Ch 6:54` Now these are their *_dwelling_*-places throughout their encampments in their limits: to the sons of Aaron from the families of the Kohathites, for theirs was the lot,
* `2Ch 6:2` But I have built a house of habitation for you and a place for your *_dwelling_* forever."
* `2Ch 6:21` Listen therefore to the supplications of your servant and of your people Israel which they shall make toward this place. Hear from your *_dwelling_*-place, even from heaven, and when you hear, forgive.
* `2Ch 6:30` Then hear from heaven your *_dwelling_*-place, forgive, and render to every man according to all his ways, whose heart you know (for you alone know the hearts of the children of men),
* `2Ch 6:33` Then hear from the heavens, even from your *_dwelling_*-place, and do according to all that the stranger calls to you for so that all people of the earth may know your name and fear you, as do your people Israel, and may know that this house which I have built is called by your name.
* `2Ch 6:39` Then hear from the heavens, even from your *_dwelling_*-place, their prayer and their supplications, maintain their cause, and forgive your people who have sinned against you.
* `2Ch 30:27` Then the priests the Levites arose and blessed the people. And their voice was heard and their prayer ascended to his holy *_dwelling_*-place, even to heaven.
* `2Ch 36:15` And the LORD God of their fathers sent to them by his messengers, rising up early and sending, because he had compassion on his people and on his *_dwelling_*-place.
* `Neh 3:26` Moreover, the Nethinims *_dwelling_* in Ophel, to the place over against the water-gate toward the east and the projecting tower.
* `Job 8:22` Those who hate you shall be clothed with shame. And the *_dwelling_* place of the wicked shall come to nothing."
* `Job 21:28` For you say, 'Where is the house of the prince? And where are the *_dwelling_* places of the wicked?'
* `Psa 49:11` Their inward thought is that their houses shall continue forever and their *_dwelling_* places to all generations. They call their lands after their own names.
* `Psa 49:14` Like sheep they are laid in the grave. Death shall feed on them. The upright shall have dominion over them in the morning. Their beauty shall consume in the grave from their *_dwelling_*.
* `Psa 52:5` God shall likewise destroy you forever. He shall take you away and pluck you out of your *_dwelling_*-place. He shall root you out of the land of the living. [Selah.]
* `Psa 74:7` They have cast fire into your sanctuary. They have defiled by casting down the *_dwelling_*-place of your name to the ground.
* `Psa 76:2` Also in Salem is his tabernacle and his *_dwelling_* place in Zion.
* `Psa 79:7` For they have devoured Jacob and laid waste his *_dwelling_*-place.
* `Psa 90:1` [A Prayer of Moses the Man of God.] Lord, you have been our *_dwelling_*-place in all generations.
* `Psa 91:10` There shall no evil befall you, neither shall any plague come near your *_dwelling_*.
* `Pro 21:20` There is a treasure to be desired, and oil in the *_dwelling_* of the wise, but a foolish man spends it up.
* `Pro 24:15` Do not lie in wait, O wicked man, against the *_dwelling_* of the righteous. Do not destroy his resting-place.
* `Isa 4:5` The LORD will create upon every *_dwelling_* place of mount Zion and upon her assemblies a cloud and smoke by day and the shining of a flaming fire by night, for upon all the glory there shall be a defense.
* `Isa 18:4` For thus the LORD said to me: "I will take my rest, and I will consider in my *_dwelling_*-place like a clear heat upon herbs and like a cloud of dew in the heat of harvest."
* `Isa 38:12` My *_dwelling_* is plucked up and carried away from me like a shepherd's tent. I have cut off my life like a weaver. He will cut me off with pining sickness. From day even to night you will make an end of me.
* `Jer 30:18` Thus says the LORD: 'Behold, I will bring back the captivity of Jacob's tents and have mercy on his *_dwelling_* places, and the city shall be built upon her own heap, and the palace shall remain after its manner.
* `Jer 46:19` O daughter *_dwelling_* in Egypt, furnish yourself to go into captivity, for Noph shall be waste and desolate without an inhabitant.
* `Jer 49:33` "And Hazor shall be a *_dwelling_* for jackals and a desolation forever. No man shall abide there. No son of man shall dwell in it."
* `Jer 51:30` The mighty men of Babylon have forborne to fight. They have remained in their holds. Their might has failed. They became like women. They have burned her *_dwelling_*-places. Her bars are broken.
* `Jer 51:37` And Babylon shall become heaps, a *_dwelling_*-place for jackals, an astonishment, and a hissing, without an inhabitant.
* `Ezk 6:6` In all your *_dwelling_*-places the cities shall be laid waste and the high places shall be desolate, so that your altars may be laid waste and made desolate, your idols may be broken and cease, your images may be cut down, and your works may be abolished.
* `Ezk 37:23` Neither shall they defile themselves anymore with their idols, nor with their detestable things, nor with any of their transgressions. But I will save them out of all their *_dwelling_*-places in which they have sinned and cleanse them. So they shall be my people, and I will be their God.
* `Ezk 38:11` And you shall say, 'I will go up to the land of unwalled villages. I will go to those who are at rest, who dwell safely, all of them *_dwelling_* without walls and having neither bars nor gates'—
* `Ezk 48:15` "And the five thousand that is left in the breadth over against the twenty-five thousand shall be a profane place for the city, for *_dwelling_* and for suburbs, and the city shall be in the midst of it.
* `Dan 2:11` And it is a rare thing that the king requires, and there is no other who can reveal it before the king, except the gods, whose *_dwelling_* is not with flesh."
* `Dan 4:25` They shall drive you from men and your *_dwelling_* shall be with the beasts of the field. They shall cause you to eat grass as oxen and they shall wet you with the dew of heaven. And seven times shall pass over you, until you know that the most High rules in the kingdom of men and gives it to whomever he wishes.
* `Dan 4:32` And they shall drive you from men and your *_dwelling_* shall be with the beasts of the field. They shall cause you to eat grass as oxen. And seven times shall pass over you, until you know that the most High rules in the kingdom of men and gives it to whomever he wishes."'
* `Dan 5:21` And he was driven from the sons of men and his heart was made like the beasts, and his *_dwelling_* was with the wild donkeys. They fed him with grass like oxen and his body was wet with the dew of heaven, until he knew that the most high God rules in the kingdom of men and that he appoints over it whomever he will.
* `Joe 3:17` "And you shall know that I am the LORD your God *_dwelling_* in Zion, my holy mountain. Then Jerusalem shall be holy, and no strangers shall pass through her anymore.
* `Nah 2:11` Where is the *_dwelling_* of the lions and the feeding-place of the young lions, where the lion, the lioness, and the lion's whelp walked and no one made them afraid?
* `Hab 1:6` For behold, I raise up the Chaldeans, that bitter and hasty nation, which shall march through the breadth of the land to possess the *_dwelling_*-places that are not theirs.
* `Zph 3:7` I said, 'Surely you will fear me and receive instruction. And her *_dwelling_* place shall not be destroyed on account of everything in which I have visited her.' But they rose early and corrupted all their doings.
* `Mrk 5:3` Who had his *_dwelling_* among the tombs. And no man could bind him, not even with chains,
* `Jhn 14:23` Jesus answered and said to him, "If a man loves me, he will keep my words. And my Father will love him, and we will come to him and make our *_dwelling_* with him.
* `Act 2:5` And there were Jews *_dwelling_* at Jerusalem, devout men, from every nation under heaven.
* `Act 19:17` And this was known to all the Jews and Greeks also *_dwelling_* at Ephesus. And fear fell on them all, and the name of the Lord Jesus was magnified.
* `1Co 4:11` Even to this present hour we hunger, thirst, are naked, are buffeted, and have no certain *_dwelling_*-place.
* `1Ti 6:16` Who only has immortality, *_dwelling_* in the light which no man can approach, whom no man has seen, nor can see, to whom be honor and everlasting power. Amen.
* `Heb 11:9` By faith he sojourned in the land of promise, as in a foreign country, *_dwelling_* in tabernacles with Isaac and Jacob, the heirs with him of the same promise.
* `2Pe 2:8` (For that righteous man *_dwelling_* among them, in seeing and hearing, grieved his righteous soul from day to day with their unlawful deeds),

_65 verses containing DWELLING_

== DWELLING-HOUSE

* `Lev 25:29` 'And if a man sells a *_dwelling-house_* in a walled city, then he may redeem it within a whole year after it is sold. Within a full year he may redeem it.

_1 verse containing DWELLING-HOUSE_

== DWELLING-PLACE

* `Num 24:21` And he looked at the Kenites and took up his parable and said, "Your *_dwelling-place_* is strong and you put your nest in a rock.
* `1Ki 8:30` And listen to the supplication of your servant and of your people Israel when they pray toward this place. And hear in heaven your *_dwelling-place_*. And when you hear, forgive.
* `1Ki 8:39` Then hear in heaven your *_dwelling-place_*, and forgive, do, and give to each according to his ways, whose heart you know (for you, even you only, know the hearts of all the children of men),
* `1Ki 8:43` Then hear in heaven your *_dwelling-place_* and do according to all that the stranger calls to you for so that all people of the earth may know your name to fear you, as do your people Israel, and that they may know that this house which I have built is called by your name.
* `1Ki 8:49` Then hear their prayer and their supplication in heaven your *_dwelling-place_*, maintain their cause,
* `1Ch 6:32` And they ministered before the *_dwelling-place_* of the Tabernacle of the Congregation with singing until Solomon had built the house of the LORD in Jerusalem, and then they waited on their office according to their order.
* `2Ch 6:21` Listen therefore to the supplications of your servant and of your people Israel which they shall make toward this place. Hear from your *_dwelling-place_*, even from heaven, and when you hear, forgive.
* `2Ch 6:30` Then hear from heaven your *_dwelling-place_*, forgive, and render to every man according to all his ways, whose heart you know (for you alone know the hearts of the children of men),
* `2Ch 6:33` Then hear from the heavens, even from your *_dwelling-place_*, and do according to all that the stranger calls to you for so that all people of the earth may know your name and fear you, as do your people Israel, and may know that this house which I have built is called by your name.
* `2Ch 6:39` Then hear from the heavens, even from your *_dwelling-place_*, their prayer and their supplications, maintain their cause, and forgive your people who have sinned against you.
* `2Ch 30:27` Then the priests the Levites arose and blessed the people. And their voice was heard and their prayer ascended to his holy *_dwelling-place_*, even to heaven.
* `2Ch 36:15` And the LORD God of their fathers sent to them by his messengers, rising up early and sending, because he had compassion on his people and on his *_dwelling-place_*.
* `Psa 52:5` God shall likewise destroy you forever. He shall take you away and pluck you out of your *_dwelling-place_*. He shall root you out of the land of the living. [Selah.]
* `Psa 74:7` They have cast fire into your sanctuary. They have defiled by casting down the *_dwelling-place_* of your name to the ground.
* `Psa 79:7` For they have devoured Jacob and laid waste his *_dwelling-place_*.
* `Psa 90:1` [A Prayer of Moses the Man of God.] Lord, you have been our *_dwelling-place_* in all generations.
* `Isa 18:4` For thus the LORD said to me: "I will take my rest, and I will consider in my *_dwelling-place_* like a clear heat upon herbs and like a cloud of dew in the heat of harvest."
* `Jer 51:37` And Babylon shall become heaps, a *_dwelling-place_* for jackals, an astonishment, and a hissing, without an inhabitant.
* `1Co 4:11` Even to this present hour we hunger, thirst, are naked, are buffeted, and have no certain *_dwelling-place_*.

_19 verses containing DWELLING-PLACE_

== DWELLING-PLACES

* `1Ch 6:54` Now these are their *_dwelling-places_* throughout their encampments in their limits: to the sons of Aaron from the families of the Kohathites, for theirs was the lot,
* `Jer 51:30` The mighty men of Babylon have forborne to fight. They have remained in their holds. Their might has failed. They became like women. They have burned her *_dwelling-places_*. Her bars are broken.
* `Ezk 6:6` In all your *_dwelling-places_* the cities shall be laid waste and the high places shall be desolate, so that your altars may be laid waste and made desolate, your idols may be broken and cease, your images may be cut down, and your works may be abolished.
* `Ezk 37:23` Neither shall they defile themselves anymore with their idols, nor with their detestable things, nor with any of their transgressions. But I will save them out of all their *_dwelling-places_* in which they have sinned and cleanse them. So they shall be my people, and I will be their God.
* `Hab 1:6` For behold, I raise up the Chaldeans, that bitter and hasty nation, which shall march through the breadth of the land to possess the *_dwelling-places_* that are not theirs.

_5 verses containing DWELLING-PLACES_

== DWELLINGS

* `Exo 10:23` They did not see one another, neither did any rise from his place for three days, but all the children of Israel had light in their *_dwellings_*.
* `Lev 3:17` It shall be a perpetual statute for your generations throughout all your *_dwellings_* that you eat neither fat nor blood.'"
* `Lev 7:26` Moreover, you shall eat no manner of blood, whether of bird or beast, in any of your *_dwellings_*.
* `Lev 23:3` 'Six days work shall be done, but the seventh day is the sabbath of rest, a holy convocation. You shall do no work. It is the sabbath of the LORD in all your *_dwellings_*.
* `Lev 23:14` And you shall eat neither bread, parched grain, nor new grain until the same day that you have brought an offering to your God. It shall be a statute forever throughout your generations in all your *_dwellings_*.
* `Lev 23:21` And you shall proclaim on the same day that it may be a holy convocation to you. You shall do no servile work on it. It shall be a statute forever in all your *_dwellings_* throughout your generations.
* `Lev 23:31` You shall do no manner of work. It shall be a statute forever throughout your generations in all your *_dwellings_*.
* `Num 35:29` 'So these things shall be for a statute of judgment to you throughout your generations in all your *_dwellings_*.
* `Job 18:19` He shall have neither son nor posterity among his people, nor anyone remaining in his *_dwellings_*.
* `Job 18:21` Surely such are the *_dwellings_* of the wicked, and this is the place of him who does not know God."
* `Job 39:6` Whose house I have made the wilderness and the barren land his *_dwellings_*?
* `Psa 55:15` Let death seize upon them, and let them go down alive into hell, for wickedness is in their *_dwellings_* and among them.
* `Psa 87:2` The LORD loves the gates of Zion more than all the *_dwellings_* of Jacob.
* `Isa 32:18` And my people shall dwell in a peaceable habitation, in sure *_dwellings_*, and in quiet resting-places,
* `Jer 9:19` For a voice of wailing is heard out of Zion, 'How we are laid waste! We are greatly confounded because we have forsaken the land, because our *_dwellings_* have cast us out.'"
* `Ezk 25:4` Therefore behold, I will deliver you to the men of the east for a possession, and they shall set their palaces in you and make their *_dwellings_* in you. They shall eat your fruit and they shall drink your milk.

_16 verses containing DWELLINGS_

== DWELLS

* `Exo 3:22` But every woman shall ask her neighbor and her who *_dwells_* in her house for jewels of silver, jewels of gold, and clothing. And you shall put them upon your sons and upon your daughters. And you shall plunder the Egyptians."
* `Lev 19:34` But the stranger who *_dwells_* with you shall be to you as one born among you, and you shall love him as yourself, for you were strangers in the land of Egypt. I am the LORD your God.
* `Lev 25:39` 'And if your brother who *_dwells_* by you becomes poor and is sold to you, you shall not compel him to serve as a slave.
* `Lev 25:47` 'And if a sojourner or a stranger becomes rich by you, and your brother who *_dwells_* by him becomes poor and sells himself to the stranger or sojourner by you, or to the stock of the stranger's family,
* `Deu 18:6` "And if a Levite comes from any of your gates out of all Israel where he *_dwells_*, and comes with all the desire of his mind to the place which the LORD chooses,
* `Deu 33:20` And of Gad he said, "Blessed is he who enlarges Gad. He *_dwells_* like a lion and tears the arm with the crown of the head.
* `Jsh 6:25` But Rahab the harlot, her father's household, and all that she had, Joshua saved alive. And she *_dwells_* in Israel even to this day because she hid the messengers which Joshua sent to spy out Jericho.
* `Jsh 22:19` However, if the land of your possession is unclean, then pass over to the land of the possession of the LORD, in which the LORD'S tabernacle *_dwells_*, and take possession among us. But do not rebel against the LORD nor rebel against us in building yourselves an altar besides the altar of the LORD our God.
* `1Sa 4:4` So the people sent to Shiloh so that they might bring from there the ark of the covenant of the LORD of hosts, who *_dwells_* between the cherubim. And the two sons of Eli, Hophni and Phinehas, were there with the ark of the covenant of God.
* `1Sa 27:11` And David saved neither man nor woman alive to bring tidings to Gath, saying, "Lest they should inform against us, saying, 'Thus David did, and so will be his manner all the time he *_dwells_* in the country of the Philistines.'"
* `2Sa 6:2` And David arose and went with all the people who were with him from Baale of Judah to bring up from there the ark of God, whose name is called by the name of the LORD of hosts who *_dwells_* between the cherubim.
* `2Sa 7:2` That the king said to Nathan the prophet, "See now, I dwell in a house of cedar, but the ark of God *_dwells_* within curtains."
* `1Ch 13:6` And David and all Israel went up to Baalah, that is, to Kirjath-jearim, which belonged to Judah, to bring up from there the ark of God the LORD, who *_dwells_* between the cherubim, whose name is called on it.
* `Job 15:28` And he *_dwells_* in desolate cities and in houses which no man inhabits, which are ready to become heaps.
* `Job 38:19` Where is the way where light *_dwells_*? And as for darkness, where is its place,
* `Job 39:28` She *_dwells_* and abides on the rock, upon the crag of the rock and the strong place.
* `Psa 9:11` Sing praises to the LORD who *_dwells_* in Zion. Declare among the people his doings.
* `Psa 26:8` LORD, I have loved the habitation of your house and the place where your honor *_dwells_*.
* `Psa 91:1` He who *_dwells_* in the secret place of the Most High shall abide under the shadow of the Almighty.
* `Psa 113:5` Who is like the LORD our God who *_dwells_* on high,
* `Psa 135:21` Blessed be the LORD out of Zion, who *_dwells_* at Jerusalem. Praise the LORD.
* `Pro 3:29` Do not devise evil against your neighbor, seeing he *_dwells_* securely by you.
* `Isa 8:18` Behold, I and the children whom the LORD has given me are for signs and for wonders in Israel from the LORD of hosts who *_dwells_* on mount Zion.
* `Isa 33:5` The LORD is exalted, for he *_dwells_* on high. He has filled Zion with judgment and righteousness.
* `Isa 37:16` "O LORD of hosts, God of Israel, who *_dwells_* between the cherubim, you are the God, even you alone, of all the kingdoms of the earth. You have made heaven and earth.
* `Jer 4:29` The whole city shall flee at the noise of the horsemen and bowmen. They shall go into thickets and climb up upon the rocks. Every city shall be forsaken, and not a man *_dwells_* therein.
* `Jer 44:2` "Thus says the LORD of hosts, the God of Israel: 'You have seen all the evil that I have brought upon Jerusalem and upon all the cities of Judah, and behold, this day they are a desolation, and no man *_dwells_* in them
* `Jer 49:31` Arise, go up to the wealthy nation that *_dwells_* without care," says the LORD, "that has neither gates nor bars, that *_dwells_* alone.
* `Jer 51:43` Her cities are a desolation, a dry land, and a wilderness, a land in which no man *_dwells_*, neither does any son of man pass by it.
* `Lam 1:3` [GIMEL] Judah has gone into captivity because of affliction and because of great servitude. She *_dwells_* among the heathen. She finds no rest. All her persecutors overtook her in the midst of distress.
* `Lam 4:21` [SHIN] Rejoice and be glad, O daughter of Edom, who *_dwells_* in the land of Uz. The cup shall also pass through to you. You shall be drunken and shall make yourself naked.
* `Ezk 16:46` And your elder sister is Samaria—she and her daughters who dwell at your left hand. And your younger sister, who *_dwells_* at your right hand, is Sodom with her daughters.
* `Ezk 17:16` As I live,' says the Lord GOD, 'surely in the place where the king *_dwells_* who made him king, whose oath he despised and whose covenant he broke, even with him in the midst of Babylon he shall die.
* `Dan 2:22` He reveals the deep and secret things. He knows what is in the darkness, and the light *_dwells_* with him.
* `Hos 4:3` Therefore, the land shall mourn, and everyone who *_dwells_* in it shall languish, with the beasts of the field and with the birds of heaven. Even the fish of the sea shall also be taken away.
* `Joe 3:21` For I will cleanse their blood that I have not cleansed. For the LORD *_dwells_* in Zion."
* `Amo 8:8` Shall the land not tremble for this, and everyone mourn who *_dwells_* in it? It shall rise up wholly as a flood, and it shall be cast out and drowned as by the flood of Egypt.
* `Mth 23:21` And whoever swears by the temple, swears by it and by him who *_dwells_* in it.
* `Jhn 6:56` He who eats my flesh and drinks my blood *_dwells_* in me, and I in him.
* `Jhn 14:10` Do you not believe that I am in the Father and the Father in me? The words that I speak to you, I do not speak from myself. But the Father who *_dwells_* in me, he does the works.
* `Jhn 14:17` Even the Spirit of truth, whom the world cannot receive because it does not see him or know him. But you know him because he *_dwells_* with you and will be in you.
* `Rom 7:17` Now then it is no longer I that do it, but sin that *_dwells_* in me.
* `Rom 7:18` For I know that in me (that is, in my flesh) no good thing *_dwells_*. For desire is present with me, but how to perform that which is good, I do not find.
* `Rom 7:20` Now if I do that which I do not wish to do, it is no longer I that do it, but sin that *_dwells_* in me.
* `Rom 8:9` But you are not in the flesh, but in the Spirit, if the Spirit of God *_dwells_* in you. Now if any man does not have the Spirit of Christ, he is not his.
* `Rom 8:11` But if the Spirit of him who raised Jesus from the dead *_dwells_* in you, he who raised Christ from the dead will also revive your mortal bodies by his Spirit who *_dwells_* in you.
* `1Co 3:16` Do you not know that you are the temple of God, and that the Spirit of God *_dwells_* in you?
* `Col 2:9` For in him all the fullness of the Godhead *_dwells_* bodily.
* `2Ti 1:14` Keep that good thing which was committed to you by the Holy Spirit which *_dwells_* in us.
* `Jms 4:5` Do you think that the Scripture says in vain, "The spirit which *_dwells_* in us earnestly desires to envy"?
* `2Pe 3:13` Nevertheless, we, according to his promise, look for new heavens and a new earth, in which *_dwells_* righteousness.
* `1Jn 3:24` And he who keeps his commandments *_dwells_* in him, and he in him. And by this we know that he abides in us: by the Spirit which he has given us.
* `1Jn 4:12` No man has seen God at any time. If we love one another, God *_dwells_* in us and his love is perfected in us.
* `1Jn 4:15` Whoever confesses that Jesus is the Son of God, God *_dwells_* in him, and he in God.
* `1Jn 4:16` And we have known and believed the love that God has to us. God is love. And he who *_dwells_* in love *_dwells_* in God, and God in him.
* `2Jn 1:2` For the truth's sake which *_dwells_* in us and shall be with us forever:
* `Rev 2:13` "'"I know your works and where you dwell, even where Satan's seat is. And you hold firmly to my name and have not denied my faith, even in those days wherein Antipas was my faithful martyr, who was slain among you where Satan *_dwells_*.

_57 verses containing DWELLS_

== DWELT

* `Gen 4:16` And Cain went out from the presence of the LORD and *_dwelt_* in the land of Nod, east of Eden.
* `Gen 11:2` And it came to pass as they journeyed from the east, that they found a plain in the land of Shinar and they *_dwelt_* there.
* `Gen 11:31` And Terah took Abram his son and Lot the son of Haran, his son's son, and Sarai his daughter-in-law, his son Abram's wife, and they went forth together from Ur of the Chaldeans to go into the land of Canaan. And they came to Haran and *_dwelt_* there.
* `Gen 13:7` And there was a strife between the herdsmen of Abram's livestock and the herdsmen of Lot's livestock. And the Canaanite and the Perizzite *_dwelt_* then in the land.
* `Gen 13:12` Abram *_dwelt_* in the land of Canaan, and Lot *_dwelt_* in the cities of the plain and pitched his tent toward Sodom.
* `Gen 13:18` Then Abram moved his tent and came and *_dwelt_* in the plain of Mamre, which is in Hebron, and built an altar there to the LORD.
* `Gen 14:7` And they returned and came to En-mishpat, which is Kadesh, and smote all the country of the Amalekites and also the Amorites, who *_dwelt_* in Hazezontamar.
* `Gen 14:12` And they took Lot, Abram's brother's son, who *_dwelt_* in Sodom, and his goods, and departed.
* `Gen 14:13` And someone who had escaped came and told Abram the Hebrew. For he *_dwelt_* in the plain of Mamre the Amorite, brother of Eshcol, and brother of Aner, and these were confederates with Abram.
* `Gen 16:3` And Sarai, Abram's wife, took Hagar her servant, the Egyptian, after Abram had *_dwelt_* ten years in the land of Canaan, and gave her to her husband Abram to be his wife.
* `Gen 19:29` And it came to pass when God destroyed the cities of the plain, that God remembered Abraham and sent Lot out of the midst of the overthrow when he overthrew the cities in which Lot *_dwelt_*.
* `Gen 19:30` And Lot went up from Zoar and *_dwelt_* in the mountain, and his two daughters with him, for he feared to dwell in Zoar. And he *_dwelt_* in a cave—he and his two daughters.
* `Gen 20:1` And Abraham journeyed from there toward the south country and *_dwelt_* between Kadesh and Shur and sojourned in Gerar.
* `Gen 21:20` And God was with the boy, and he grew and *_dwelt_* in the wilderness and became an archer.
* `Gen 21:21` And he *_dwelt_* in the wilderness of Paran. And his mother took for him a wife out of the land of Egypt.
* `Gen 22:19` So Abraham returned to his young men, and they rose and went together to Beer-sheba, and Abraham *_dwelt_* at Beer-sheba.
* `Gen 23:10` And Ephron *_dwelt_* among the children of Heth. And Ephron the Hittite answered Abraham in the audience of the children of Heth, of all who entered the gates of his city, saying,
* `Gen 24:62` And Isaac came from the way of the well Lahai-roi, for he *_dwelt_* in the south country.
* `Gen 25:11` And it came to pass after the death of Abraham, that God blessed his son Isaac. And Isaac *_dwelt_* by the well Lahai-roi.
* `Gen 25:18` And they *_dwelt_* from Havilah to Shur, that is before Egypt, as far as toward Assyria. And he died in the presence of all his brothers.
* `Gen 26:6` And Isaac *_dwelt_* in Gerar.
* `Gen 26:17` And Isaac departed from there and pitched his tent in the valley of Gerar and *_dwelt_* there.
* `Gen 35:22` And it came to pass when Israel *_dwelt_* in that land, that Reuben went and lay with Bilhah his father's concubine. And Israel heard it. Now the sons of Jacob were twelve.
* `Gen 36:8` Thus Esau *_dwelt_* in the mountains of Seir. Esau is Edom.
* `Gen 37:1` And Jacob *_dwelt_* in the land in which his father was a stranger, in the land of Canaan.
* `Gen 38:11` Then Judah said to Tamar his daughter-in-law, "Remain a widow at your father's house until Shelah my son is grown," for he said, "Lest perhaps he die also as his brothers did." And Tamar went and *_dwelt_* in her father's house.
* `Gen 47:27` And Israel *_dwelt_* in the land of Egypt, in the country of Goshen. And they had possessions in it and grew and multiplied exceedingly.
* `Gen 50:22` And Joseph *_dwelt_* in Egypt—he and his father's house. And Joseph lived one hundred and ten years.
* `Exo 2:15` Now when Pharaoh heard this thing, he sought to slay Moses. But Moses fled from the face of Pharaoh and *_dwelt_* in the land of Midian. And he sat down by a well.
* `Exo 12:40` Now the sojourning of the children of Israel who *_dwelt_* in Egypt was four hundred and thirty years.
* `Lev 18:3` After the doings of the land of Egypt in which you *_dwelt_*, you shall not do, and after the doings of the land of Canaan where I bring you, you shall not do, neither shall you walk in their ordinances.
* `Lev 26:35` As long as it lies desolate, it shall rest, because it did not rest in your sabbaths when you *_dwelt_* upon it.
* `Num 14:25` (Now the Amalekites and the Canaanites *_dwelt_* in the valley.) Tomorrow turn and pass into the wilderness by the way of the Red Sea."
* `Num 14:45` Then the Amalekites and the Canaanites who *_dwelt_* on that hill came down and smote them and completely defeated them, even to Hormah.
* `Num 20:15` How our fathers went down into Egypt, and we *_dwelt_* in Egypt a long time, and the Egyptians afflicted us and our fathers.
* `Num 21:1` And when king Arad the Canaanite, who *_dwelt_* in the south, heard that Israel came by the way of the spies, he fought against Israel and took some of them prisoners.
* `Num 21:25` And Israel took all these cities. And Israel *_dwelt_* in all the cities of the Amorites, in Heshbon and in all its villages.
* `Num 21:31` Thus Israel *_dwelt_* in the land of the Amorites.
* `Num 21:34` And the LORD said to Moses, "Do not fear him, for I have delivered him into your hand, along with all his people and his land. And you shall do to him as you did to Sihon king of the Amorites, who *_dwelt_* at Heshbon."
* `Num 31:10` And they burnt all their cities in which they *_dwelt_* and all their encampments with fire.
* `Num 32:40` And Moses gave Gilead to Machir the son of Manasseh, and he *_dwelt_* in it.
* `Num 33:40` And king Arad the Canaanite who *_dwelt_* in the south in the land of Canaan heard about the coming of the children of Israel.
* `Deu 1:4` After he had slain Sihon the king of the Amorites, who *_dwelt_* in Heshbon, and Og the king of Bashan, who *_dwelt_* at Astaroth in Edrei.
* `Deu 1:6` "The LORD our God spoke to us in Horeb, saying, 'You have *_dwelt_* long enough at this mountain.
* `Deu 1:44` And the Amorites, who *_dwelt_* on that mountain, came out against you and chased you, as bees do, and destroyed you in Seir, even to Hormah.
* `Deu 2:8` "And when we passed by from our brothers, the children of Esau, who *_dwelt_* in Seir, through the way of the plain from Elath and from Ezion-gaber, we turned and passed by the way of the wilderness of Moab.
* `Deu 2:10` (The Emims *_dwelt_* in it in times past, a people great and many and tall as the Anakims,
* `Deu 2:12` The Horims also *_dwelt_* formerly in Seir, but the children of Esau succeeded them when they had destroyed them from before them and *_dwelt_* in their stead, as Israel did to the land of his possession, which the LORD gave to them.)
* `Deu 2:20` (That also was accounted a land of Rephaim. Rephaim *_dwelt_* in it in old time, and the Ammonites call them Zamzummims,
* `Deu 2:21` A people great and many and tall as the Anakims. But the LORD destroyed them before them, and they succeeded them and *_dwelt_* in their stead,
* `Deu 2:22` As he did to the children of Esau, who *_dwelt_* in Seir when he destroyed the Horims from before them. And they succeeded them and *_dwelt_* in their stead even to this day.
* `Deu 2:23` And the Avims who *_dwelt_* in Hazerim even to Azzah, the Caphtorims, who came forth from Caphtor, destroyed them and *_dwelt_* in their stead.)
* `Deu 3:2` And the LORD said to me, 'Do not fear him, for I will deliver him, all his people, and his land into your hand. And you shall do to him as you did to Sihon king of the Amorites, who *_dwelt_* at Heshbon.'
* `Deu 4:46` On the east side of the Jordan, in the valley over against Beth-Peor, in the land of Sihon king of the Amorites, who *_dwelt_* at Heshbon, whom Moses and the children of Israel smote after they had come forth from Egypt.
* `Deu 8:12` Lest, when you have eaten and are full, when you have built good houses and *_dwelt_* in them,
* `Deu 29:16` (For you know how we have *_dwelt_* in the land of Egypt and how we came through the nations which you passed by,
* `Deu 33:16` For the precious things of the earth and its fullness, and for the good will of him who *_dwelt_* in the bush. Let the blessing come upon the head of Joseph and upon the top of the head of him who was separated from his brothers.
* `Jsh 2:15` Then she let them down by a cord through the window, for her house was upon the town-wall, and she *_dwelt_* upon the wall.
* `Jsh 7:7` And Joshua said, "Alas, O Lord GOD, why have you at all brought this people over the Jordan to deliver us into the hand of the Amorites to destroy us? O that we had been content and *_dwelt_* on the other side of the Jordan.
* `Jsh 9:16` And it came to pass at the end of three days after they had made a league with them, that they heard that they were their neighbors and that they *_dwelt_* among them.
* `Jsh 12:2` Sihon king of the Amorites, who *_dwelt_* in Heshbon and ruled from Aroer, which is upon the bank of the Arnon River, and from the middle of the river and from half Gilead, even to the Jabbok River, which is the border of the children of Ammon;
* `Jsh 12:4` And the border of Og king of Bashan, who was of the remnant of the Rephaim, who *_dwelt_* at Ashtaroth and at Edrei,
* `Jsh 13:21` All the cities of the plain, and all the kingdom of Sihon king of the Amorites, who reigned in Heshbon. Moses smote him along with the princes of Midian: Evi, Rekem, Zur, Hur, and Reba—chiefs of Sihon who *_dwelt_* in the country.
* `Jsh 16:10` And they did not expel the Canaanites who *_dwelt_* in Gezer. But the Canaanites dwell among the Ephraimites to this day and serve under tribute.
* `Jsh 19:47` And the border of the children of Dan, went out too little for them; therefore, the children of Dan went up to fight against Leshem, took it, smote it with the edge of the sword, possessed it, and *_dwelt_* in it, and called Leshem, Dan, after the name of Dan their father.
* `Jsh 19:50` According to the word of the LORD they gave him the city which he asked, even Timnath-serah in the mountains of Ephraim. And he built the city and *_dwelt_* in it.
* `Jsh 21:43` And the LORD gave to Israel all the land which he swore to give to their fathers. And they possessed it and *_dwelt_* in it.
* `Jsh 22:33` And the thing pleased the children of Israel. And the children of Israel blessed God and did not intend to go up against them in battle to destroy the land in which the children of Reuben and Gad *_dwelt_*.
* `Jsh 24:2` And Joshua said to all the people, "Thus says the LORD God of Israel: 'Your fathers *_dwelt_* on the other side of the flood in old time, even Terah, the father of Abraham, and the father of Nahor, and they served other gods.
* `Jsh 24:7` And when they cried to the LORD, he put darkness between you and the Egyptians and brought the sea upon them and covered them. And your eyes have seen what I have done in Egypt. And you *_dwelt_* in the wilderness for a long season.
* `Jsh 24:8` And I brought you into the land of the Amorites, who *_dwelt_* on the other side of the Jordan, and they fought with you. And I gave them into your hand so that you might possess their land, and I destroyed them from before you.
* `Jsh 24:18` And the LORD drove out from before us all the people, even the Amorites who *_dwelt_* in the land. Therefore, we will also serve the LORD, for he is our God."
* `Jdg 1:9` And afterward, the children of Judah went down to fight against the Canaanites who *_dwelt_* on the mountain, in the south, and in the valley.
* `Jdg 1:10` And Judah went against the Canaanites who *_dwelt_* in Hebron (now the name of Hebron was formerly Kirjath-arba), and they slew Sheshai, Ahiman, and Talmai.
* `Jdg 1:16` And the children of the Kenite, Moses's father-in-law, went up out of the city of palm-trees with the children of Judah into the wilderness of Judah, which lies in the south of Arad, and they went and *_dwelt_* among the people.
* `Jdg 1:29` Ephraim did not expel the Canaanites who *_dwelt_* in Gezer, but the Canaanites *_dwelt_* in Gezer among them.
* `Jdg 1:30` Zebulun did not expel the inhabitants of Kitron nor the inhabitants of Nahalol, but the Canaanites *_dwelt_* among them and became tributaries.
* `Jdg 1:32` But the Asherites *_dwelt_* among the Canaanites, the inhabitants of the land, for they did not expel them.
* `Jdg 1:33` Naphtali did not expel the inhabitants of Beth-shemesh nor the inhabitants of Beth-anath, but he *_dwelt_* among the Canaanites, the inhabitants of the land. Nevertheless, the inhabitants of Beth-shemesh and of Beth-anath became tributaries to them.
* `Jdg 3:3` The five lords of the Philistines, all the Canaanites, the Sidonians, and the Hivites who *_dwelt_* on mount Lebanon, from mount Baal-hermon to the entrance of Hamath.
* `Jdg 3:5` And the children of Israel *_dwelt_* among the Canaanites, Hittites, Amorites, Perizzites, Hivites, and Jebusites.
* `Jdg 4:2` And the LORD sold them into the hand of Jabin king of Canaan who reigned in Hazor, the captain of whose host was Sisera, who *_dwelt_* in Harosheth of the Gentiles.
* `Jdg 4:5` And she *_dwelt_* under the palm-tree of Deborah between Ramah and Beth-el in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `Jdg 8:11` And Gideon went up by the way of those who *_dwelt_* in tents on the east of Nobah and Jogbehah and smote the host, for the host was secure.
* `Jdg 8:29` And Jerubbaal the son of Joash went and *_dwelt_* in his own house.
* `Jdg 9:21` And Jotham ran away and fled and went to Beer and *_dwelt_* there for fear of Abimelech his brother.
* `Jdg 9:41` And Abimelech *_dwelt_* at Arumah, and Zebul thrust out Gaal and his brothers, so that they should not dwell in Shechem.
* `Jdg 10:1` And after Abimelech there arose to defend Israel Tola the son of Puah, the son of Dodo, a man of Issachar. And he *_dwelt_* in Shamir in the mountains of Ephraim.
* `Jdg 11:3` Then Jephthah fled from his brothers and *_dwelt_* in the land of Tob. And vain men were gathered to Jephthah, and they went out with him.
* `Jdg 11:26` While Israel *_dwelt_* in Heshbon and her towns, in Aroer and her towns, and in all the cities that are along by the borders of Arnon for three hundred years, why therefore did you not recover them within that time?
* `Jdg 15:8` And he smote them hip and thigh with a great slaughter. And he went down and *_dwelt_* in the cleft of the rock of Etam.
* `Jdg 18:7` Then the five men departed and came to Laish and saw the people who were in it, how they *_dwelt_* carelessly after the manner of the Zidonians, quiet and secure. And there was no magistrate in the land who might put them to shame in anything. And they were far from the Zidonians and had no business with any man.
* `Jdg 18:28` And there was no deliverer because it was far from Zidon and they had no business with any man. And it was in the valley that lies by Beth-rehob. And they built a city and *_dwelt_* in it.
* `Jdg 19:16` And behold, there came an old man from his work out of the field at evening, who was also of mount Ephraim, and he *_dwelt_* in Gibeah. But the men of the place were Benjaminites.
* `Jdg 21:23` And the children of Benjamin did so, and took wives, according to their number, from those who danced, whom they caught. And they went and returned to their inheritance and repaired the cities and *_dwelt_* in them.
* `Rth 1:4` And they took for themselves wives from the women of Moab: the name of one was Orpah and the name of the other Ruth. And they *_dwelt_* there about ten years.
* `Rth 2:23` So she kept close by the young women of Boaz to glean until the end of barley-harvest and of wheat-harvest, and *_dwelt_* with her mother-in-law.
* `1Sa 12:11` And the LORD sent Jerubbaal, Bedan, Jephthah, and Samuel and delivered you from the hand of your enemies on every side, and you *_dwelt_* safely.
* `1Sa 19:18` So David fled and escaped, and he came to Samuel at Ramah and told him all that Saul had done to him. And he and Samuel went and *_dwelt_* in Naioth.
* `1Sa 22:4` And he brought them before the king of Moab. And they *_dwelt_* with him all the while that David was in the hold.
* `1Sa 23:29` Then David went up from there and *_dwelt_* in strongholds at En-gedi.
* `1Sa 27:3` And David *_dwelt_* with Achish at Gath—he and his men, every man with his household, even David with his two wives, Ahinoam the Jezreelitess and Abigail the Carmelitess, Nabal's wife.
* `1Sa 27:7` And the time that David *_dwelt_* in the country of the Philistines was a full year and four months.
* `1Sa 31:7` And when the men of Israel who were on the other side of the valley and those who were on the other side of the Jordan saw that the men of Israel fled and that Saul and his sons were dead, they forsook the cities and fled. And the Philistines came and *_dwelt_* in them.
* `2Sa 2:3` And his men who were with him David brought up, every man with his household. And they *_dwelt_* in the cities of Hebron.
* `2Sa 5:9` So David *_dwelt_* in the fort and called it the city of David. And David built around from Millo and inward.
* `2Sa 7:6` Whereas I have not *_dwelt_* in any house since the time that I brought the children of Israel out of Egypt, even to this day, but have walked in a tent and in a tabernacle.
* `2Sa 9:12` And Mephibosheth had a young son whose name was Micah. And all who *_dwelt_* in the house of Ziba were servants to Mephibosheth.
* `2Sa 9:13` So Mephibosheth *_dwelt_* in Jerusalem, for he ate continually at the king's table. And he was lame in both his feet.
* `2Sa 14:28` So Absalom *_dwelt_* two full years in Jerusalem and did not see the king's face.
* `1Ki 2:38` And Shimei said to the king, "The saying is good. As my lord the king has said, so your servant will do." And Shimei *_dwelt_* in Jerusalem many days.
* `1Ki 4:25` And Judah and Israel *_dwelt_* safely, every man under his vine and under his fig-tree, from Dan even to Beer-sheba, all the days of Solomon.
* `1Ki 7:8` And his house where he *_dwelt_* had another court within the porch, which was of similar work. Solomon also made a house like this porch for Pharaoh's daughter, whom he had married.
* `1Ki 9:16` For Pharaoh king of Egypt had gone up, taken Gezer, burnt it with fire, slain the Canaanites who *_dwelt_* in the city, and given it for a present to his daughter, Solomon's wife.
* `1Ki 11:24` And he gathered men to him and became captain over a band when David slew those of Zobah. And they went to Damascus, *_dwelt_* in it, and reigned in Damascus.
* `1Ki 12:2` And it came to pass when Jeroboam the son of Nebat, who was still in Egypt, heard of it (for he had fled from the presence of king Solomon, and Jeroboam *_dwelt_* in Egypt),
* `1Ki 12:17` But as for the children of Israel who *_dwelt_* in the cities of Judah, Rehoboam reigned over them.
* `1Ki 12:25` Then Jeroboam built Shechem on mount Ephraim and *_dwelt_* in it, and he went out from there and built Penuel.
* `1Ki 13:11` Now there *_dwelt_* an old prophet in Beth-el. And his sons came and told him all the works that the man of God had done that day in Beth-el. The words which he had spoken to the king, they also told them to their father.
* `1Ki 13:25` And behold, men passed by and saw the carcass cast on the way and the lion standing by the carcass. And they came and told it in the city where the old prophet *_dwelt_*.
* `1Ki 15:18` Then Asa took all the silver and the gold that was left in the treasures of the house of the LORD and the treasures of the king's house and delivered them into the hand of his servants. And king Asa sent them to Ben-hadad, the son of Tabrimon, the son of Hezion, king of Syria, who *_dwelt_* at Damascus, saying,
* `1Ki 15:21` And it came to pass when Baasha heard of it, that he stopped building Ramah and *_dwelt_* in Tirzah.
* `1Ki 17:5` So he went and did according to the word of the LORD. For he went and *_dwelt_* by the brook Cherith, which is before the Jordan.
* `2Ki 13:5` (And the LORD gave Israel a savior so that they went out from under the hand of the Syrians, and the children of Israel *_dwelt_* in their tents as before.
* `2Ki 15:5` And the LORD smote the king so that he was a leper until the day of his death and *_dwelt_* in a separate house. And Jotham the king's son was over the house, judging the people of the land.
* `2Ki 16:6` At that time Rezin king of Syria recovered Elath to Syria and drove the Jews from Elath. And the Syrians came to Elath and have *_dwelt_* there to this day.
* `2Ki 17:24` And the king of Assyria brought men from Babylon, from Cuthah, from Ava, from Hamath, and from Sepharvaim, and placed them in the cities of Samaria instead of the children of Israel. And they possessed Samaria and *_dwelt_* in its cities.
* `2Ki 17:28` Then one of the priests whom they had carried away from Samaria came and *_dwelt_* in Beth-el and taught them how they should fear the LORD.
* `2Ki 17:29` Yet every nation made gods of their own and put them in the houses of the high places which the Samaritans had made, every nation in their cities in which they *_dwelt_*.
* `2Ki 19:36` So Sennacherib king of Assyria departed and went and returned and *_dwelt_* at Nineveh.
* `2Ki 22:14` So Hilkiah the priest, Ahikam, Achbor, Shaphan, and Asahiah went to Huldah the prophetess, the wife of Shallum, the son of Tikvah, the son of Harhas, keeper of the wardrobe (now she *_dwelt_* in Jerusalem in the second quarter), and they spoke with her.
* `1Ch 2:55` And the families of the scribes who *_dwelt_* at Jabez: the Tirathites, the Shimeathites, and Suchathites. These are the Kenites who came from Hemath, the father of the house of Rechab.
* `1Ch 4:23` These were the potters and those who *_dwelt_* among plants and hedges. There they *_dwelt_* with the king for his work.
* `1Ch 4:28` And they *_dwelt_* at Beer-sheba, Moladah, Hazar-shual,
* `1Ch 4:40` And they found rich and good pasture. And the land was wide, quiet, and peaceable, for those of Ham had *_dwelt_* there of old.
* `1Ch 4:41` And these written by name came in the days of Hezekiah king of Judah and smote their tents and the habitations that were found there, destroyed them utterly to this day, and *_dwelt_* in their stead, because there was pasture there for their flocks.
* `1Ch 4:43` And they smote the rest of the Amalekites who had escaped and have *_dwelt_* there to this day.
* `1Ch 5:8` And Bela the son of Azaz, the son of Shema, the son of Joel, who *_dwelt_* in Aroer, even to Nebo, and Baal-meon.
* `1Ch 5:10` And in the days of Saul they made war with the Hagarites, who fell by their hand. And they *_dwelt_* in their tents throughout all the east land of Gilead.
* `1Ch 5:11` And the children of Gad *_dwelt_* over against them in the land of Bashan to Salcah:
* `1Ch 5:16` And they *_dwelt_* in Gilead in Bashan and in its towns and in all the suburbs of Sharon, upon their borders.
* `1Ch 5:22` For many fell slain there because the war was God's. And they *_dwelt_* in their stead until the captivity.
* `1Ch 5:23` And the children of the half tribe of Manasseh *_dwelt_* in the land. They increased from Bashan to Baal-hermon and Senir and to mount Hermon.
* `1Ch 7:29` And by the borders of the children of Manasseh, Beth-shean and its towns, Taanach and its towns, Megiddo and its towns, and Dor and its towns. The children of Joseph the son of Israel *_dwelt_* in these.
* `1Ch 8:28` These were heads of the fathers by their generations, chief men. These *_dwelt_* in Jerusalem.
* `1Ch 8:29` And at Gibeon the father of Gibeon *_dwelt_*, whose wife's name was Maachah,
* `1Ch 8:32` And Mikloth begot Shimeah. And these also *_dwelt_* with their brothers in Jerusalem over against them.
* `1Ch 9:2` Now the first inhabitants who *_dwelt_* in their possessions in their cities were the Israelites, the priests, Levites, and the Nethinims.
* `1Ch 9:3` And in Jerusalem *_dwelt_* some of the children of Judah, some of the children of Benjamin, and some of the children of Ephraim and Manasseh:
* `1Ch 9:16` And Obadiah the son of Shemaiah, the son of Galal, the son of Jeduthun; and Berechiah the son of Asa, the son of Elkanah, who *_dwelt_* in the villages of the Netophathites.
* `1Ch 9:34` These chief fathers of the Levites were chief throughout their generations. These *_dwelt_* at Jerusalem.
* `1Ch 9:35` And in Gibeon *_dwelt_* the father of Gibeon, Jehiel, whose wife's name was Maachah,
* `1Ch 9:38` And Mikloth begot Shimeam. And they also *_dwelt_* with their brothers at Jerusalem over against their brothers.
* `1Ch 10:7` And when all the men of Israel who were in the valley saw that they fled and that Saul and his sons were dead, they forsook their cities and fled. And the Philistines came and *_dwelt_* in them.
* `1Ch 11:7` And David *_dwelt_* in the castle; therefore, they called it, The City of David.
* `1Ch 17:5` For I have not *_dwelt_* in a house since the day that I brought up Israel to this day, but have gone from tent to tent and from one tabernacle to another.
* `2Ch 10:17` But as for the children of Israel who *_dwelt_* in the cities of Judah, Rehoboam reigned over them.
* `2Ch 11:5` And Rehoboam *_dwelt_* in Jerusalem and built cities for defense in Judah.
* `2Ch 16:2` Then Asa brought silver and gold out of the treasures of the house of the LORD and of the king's house and sent to Ben-hadad king of Syria, who *_dwelt_* at Damascus, saying,
* `2Ch 19:4` And Jehoshaphat *_dwelt_* at Jerusalem. And he went out again through the people from Beer-sheba to mount Ephraim and brought them back to the LORD God of their fathers.
* `2Ch 20:8` And they *_dwelt_* in it and have built you a sanctuary in it for your name, saying,
* `2Ch 26:7` And God helped him against the Philistines, against the Arabians who *_dwelt_* in Gur-baal, and the Mehunims.
* `2Ch 26:21` And Uzziah the king was a leper to the day of his death and *_dwelt_* in a separate house, being a leper, for he was cut off from the house of the LORD. And Jotham his son was over the king's house judging the people of the land.
* `2Ch 28:18` The Philistines also had invaded the cities of the low country, and of the south of Judah, and had taken Beth-shemesh, Ajalon, Gederoth, Shocho with its villages, Timnah with its villages, and Gimzo with its villages, and they *_dwelt_* there.
* `2Ch 30:25` And all the congregation of Judah with the priests and the Levites, all the congregation who came out of Israel, the strangers who came from the land of Israel, and those who *_dwelt_* in Judah, rejoiced.
* `2Ch 31:4` Moreover, he commanded the people who *_dwelt_* in Jerusalem to give the portion of the priests and the Levites so that they might be encouraged in the law of the LORD.
* `2Ch 31:6` And the children of Israel and Judah who *_dwelt_* in the cities of Judah, they also brought in the tithe of oxen and sheep, and the tithe of holy things which were consecrated to the LORD their God, and laid them by heaps.
* `2Ch 34:22` And Hilkiah and those whom the king had appointed went to Huldah the prophetess, the wife of Shallum the son of Tikvath, the son of Hasrah, keeper of the wardrobe (now she *_dwelt_* in Jerusalem in the second quarter), and they spoke to her to that effect.
* `Ezr 2:70` Thus the priests, the Levites, some of the people, the singers, the gatekeepers, and the Nethinims *_dwelt_* in their cities, and all Israel in their cities.
* `Neh 4:12` And it came to pass, that when the Jews who *_dwelt_* by them came, they said to us ten times, "From all places where you shall return to us they will be upon you."
* `Neh 7:73` So the priests, the Levites, the gatekeepers, the singers, some of the people, the Nethinims, and all Israel *_dwelt_* in their cities. And when the seventh month came, the children of Israel were in their cities.
* `Neh 11:1` And the rulers of the people *_dwelt_* at Jerusalem. The rest of the people also cast lots to bring one of ten to dwell in Jerusalem the holy city, and nine parts to dwell in other cities.
* `Neh 11:3` Now these are the chief of the province who *_dwelt_* in Jerusalem. But in the cities of Judah everyone *_dwelt_* in his possession in their cities, namely, Israel, the priests, the Levites, the Nethinims, and the children of Solomon's servants.
* `Neh 11:4` And some of the children of Judah and some of the children of Benjamin *_dwelt_* at Jerusalem. Of the children of Judah: Athaiah the son of Uzziah, the son of Zechariah, the son of Amariah, the son of Shephatiah, the son of Mahalaleel, of the children of Perez;
* `Neh 11:6` All the sons of Perez who *_dwelt_* at Jerusalem were four hundred and sixty-eight valiant men.
* `Neh 11:21` But the Nethinims *_dwelt_* in Ophel. And Ziha and Gispa were over the Nethinims.
* `Neh 11:25` And for the villages, with their fields, some of the children of Judah *_dwelt_* at Kirjath-arba and in its villages, at Dibon and in its villages, at Jekabzeel and in its villages,
* `Neh 11:30` Zanoah, Adullam, and in their villages, at Lachish and its fields, and at Azekah and in its villages. And they *_dwelt_* from Beer-sheba to the valley of Hinnom.
* `Neh 11:31` The children of Benjamin also *_dwelt_* from Geba, at Michmash, Aija, and Beth-el, and in their villages,
* `Neh 13:16` Also, men of Tyre *_dwelt_* therein who brought fish and all manner of wares and sold on the sabbath to the children of Judah, even in Jerusalem.
* `Est 9:19` Therefore, the Jews of the villages, who *_dwelt_* in the unwalled towns, made the fourteenth day of the month Adar a day of gladness and feasting, and a good day, and of sending portions to one another.
* `Job 22:8` But as for the mighty man, he had the earth, and the honorable man *_dwelt_* in it.
* `Job 29:25` I chose out their way, sat as chief, and *_dwelt_* like a king in the army, like one who comforts the mourners."
* `Psa 68:10` Your congregation has *_dwelt_* therein. You, O God, have prepared your goodness for the poor.
* `Psa 74:2` Remember your congregation which you have purchased of old, the rod of your inheritance which you have redeemed, this mount Zion in which you have *_dwelt_*.
* `Psa 94:17` Unless the LORD had been my help, my soul would have almost *_dwelt_* in silence.
* `Psa 120:6` My soul has long *_dwelt_* with him who hates peace.
* `Isa 13:20` It shall never be inhabited, neither shall it be *_dwelt_* in from generation to generation, neither shall the Arabian pitch tent there, neither shall the shepherds make their fold there.
* `Isa 29:1` Woe to Ariel, to Ariel, the city where David *_dwelt_*! Add year to year. Let them kill sacrifices.
* `Isa 37:37` So Sennacherib king of Assyria departed and went and returned and *_dwelt_* at Nineveh.
* `Jer 2:6` They did not say, 'Where is the LORD who brought us out of the land of Egypt, who led us through the wilderness, through a land of deserts and of pits, through a land of drought and of the shadow of death, through a land that no man passed through and where no man *_dwelt_*?'
* `Jer 35:10` But we have *_dwelt_* in tents, and have obeyed and done according to all that Jonadab our father commanded us.
* `Jer 39:14` They even sent and took Jeremiah out of the court of the prison and committed him to Gedaliah the son of Ahikam, the son of Shaphan, so that he should carry him home. So he *_dwelt_* among the people.
* `Jer 40:6` Then Jeremiah went to Gedaliah the son of Ahikam at Mizpah and *_dwelt_* with him among the people who were left in the land.
* `Jer 41:17` And they departed and *_dwelt_* in the habitation of Chimham, which is by Beth-lehem, to go to enter into Egypt
* `Jer 44:15` Then all the men who knew that their wives had burned incense to other gods and all the women who stood by, a great multitude, even all the people who *_dwelt_* in the land of Egypt, in Pathros, answered Jeremiah, saying,
* `Jer 50:39` Therefore, the wild beasts of the desert and the wolves shall dwell there, and the owls shall dwell therein. And it shall be no longer inhabited forever, neither shall it be *_dwelt_* in from generation to generation.
* `Ezk 3:15` Then I came to those who were in captivity at Tel-abib, who *_dwelt_* by the river of Kebar, and I sat where they sat and remained there astonished among them for seven days.
* `Ezk 26:17` And they shall take up a lamentation for you, and say to you, 'How you are destroyed, O renowned city inhabited by sea-faring men—she who was strong in the sea, along with her inhabitants, who cause their terror to be on all who *_dwelt_* there!
* `Ezk 31:6` All the birds of heaven made their nests in his boughs, and under his branches all the beasts of the field brought forth their young, and under his shade all great nations *_dwelt_*.
* `Ezk 31:17` They also went down into the grave with him to those who are slain with the sword, even those who were his arm, who *_dwelt_* under his shadow in the midst of the heathen.
* `Ezk 36:17` "Son of man, when the house of Israel *_dwelt_* in their own land, they defiled it by their own way and by their doings. Their way was before me as the uncleanness of a woman in her impurity.
* `Ezk 37:25` And they shall dwell in the land that I have given to Jacob my servant, in which your fathers have *_dwelt_*, and they shall dwell in it—even they, their children, and their children's children forever. And my servant David shall be their prince forever.
* `Dan 4:12` Its leaves were fair and its fruit abundant, and in it was food for all. The beasts of the field had shade under it, the birds of heaven *_dwelt_* among its boughs, and all flesh was fed from it.
* `Dan 4:21` Whose leaves were fair, its fruit abundant, and in it was food for all, under which the beasts of the field *_dwelt_*, and upon whose branches the birds of heaven had their habitation—
* `Zph 2:15` This is the rejoicing city that *_dwelt_* in security, that said in her heart, "I am, and there is no one besides me." How she has become a desolation, a place for beasts to lie down in! Everyone who passes by her shall hiss and wag his hand.
* `Mth 2:23` And he came and *_dwelt_* in a city called Nazareth so that it might be fulfilled which was spoken by the prophets, "He shall be called a Nazarene."
* `Mth 4:13` And leaving Nazareth, he came and *_dwelt_* in Capernaum, which is upon the sea coast, in the borders of Zebulun and Naphtali,
* `Luk 1:65` And fear came on all who *_dwelt_* around them, and all these sayings were noised abroad throughout all the hill-country of Judea.
* `Luk 13:4` Or those eighteen, upon whom the tower in Siloam fell and killed them, do you think that they were sinners above all men who *_dwelt_* in Jerusalem?
* `Jhn 1:14` And the Word was made flesh and *_dwelt_* among us (and we beheld his glory, the glory as of the only begotten of the Father), full of grace and truth.
* `Jhn 1:39` He says to them, "Come and see." They came and saw where he *_dwelt_* and stayed with him that day, for it was about the tenth hour.
* `Act 7:2` And he said, "Men, brothers, and fathers, listen. The God of glory appeared to our father Abraham when he was in Mesopotamia, before he *_dwelt_* in Haran,
* `Act 7:4` Then he came from the land of the Chaldeans and *_dwelt_* in Haran. And from there, when his father was dead, he moved him into this land in which you now dwell.
* `Act 9:22` But Saul increased the more in strength and confounded the Jews who *_dwelt_* at Damascus, proving that this is the Christ.
* `Act 9:32` And it came to pass, as Peter passed throughout all quarters, he also came down to the saints who *_dwelt_* at Lydda.
* `Act 9:35` And all who *_dwelt_* at Lydda and Saron saw him and turned to the Lord.
* `Act 11:29` Then the disciples, each according to his ability, determined to send relief to the brothers who *_dwelt_* in Judea,
* `Act 13:17` The God of this people Israel chose our fathers and exalted the people when they *_dwelt_* as strangers in the land of Egypt, and with a high arm he brought them out of it.
* `Act 19:10` And this continued for two years so that all those who *_dwelt_* in Asia heard the word of the Lord Jesus—both Jews and Greeks.
* `Act 22:12` "And one, Ananias, a devout man according to the law, having a good report of all the Jews who *_dwelt_* there,
* `Act 28:30` And Paul *_dwelt_* two whole years in his own hired house and received all who came to him,
* `2Ti 1:5` When I call to remembrance the unfeigned faith that is in you, which *_dwelt_* first in your grandmother Lois and your mother Eunice, and I am persuaded that is in you also.
* `Rev 11:10` And those who dwell upon the earth shall rejoice over them and make merry and shall send gifts to one another because these two prophets tormented those who *_dwelt_* on the earth.

_224 verses containing DWELT_

== DYED

* `Exo 25:5` Rams' skins *_dyed_* red, badgers' skins, shittim wood,
* `Exo 26:14` And you shall make a covering for the tent of rams' skins *_dyed_* red and a covering above of badgers' skins.
* `Exo 35:7` Rams' skins *_dyed_* red, badgers' skins, shittim wood,
* `Exo 36:19` And he made a covering for the tent of rams' skins *_dyed_* red and a covering of badgers' skins above that.
* `Exo 39:34` The covering of rams' skins *_dyed_* red, the covering of badgers' skins, and the veil of the covering;
* `Isa 63:1` Who is this who comes from Edom with *_dyed_* garments from Bozrah, this who is glorious in his apparel, traveling in the greatness of his strength? "I who speak in righteousness, mighty to save."
* `Ezk 23:15` Girded with girdles upon their loins and *_dyed_* turbans upon their heads, all of them princes to look to, after the manner of the Babylonians of Chaldea, the land of their nativity,

_7 verses containing DYED_

== DYING

* `Num 17:13` Whoever approaches the tabernacle of the LORD shall die. Shall we be consumed with *_dying_*?"
* `Mrk 12:20` Now there were seven brothers: the first took a wife, and *_dying_* left no children;
* `Luk 8:42` For he had only one daughter, about twelve years of age, and she lay *_dying_*. But as he was going, the people thronged him.
* `Jhn 11:37` And some of them said, "Could this man, who opened the eyes of the blind, not have kept this man from *_dying_*?"
* `2Co 4:10` Always carrying around in the body the *_dying_* of the Lord Jesus so that the life of Jesus may also be made manifest in our body.
* `2Co 6:9` As unknown and well known; as *_dying_*, and behold, we live; as chastened and not killed;
* `Heb 11:21` By faith Jacob, when he was *_dying_*, blessed both the sons of Joseph "and worshiped while leaning upon the top of his staff."

_7 verses containing DYING_

== DYSENTERY

* `Act 28:8` And it came to pass that the father of Publius lay sick with a fever and *_dysentery_*, to whom Paul entered in, prayed, laid his hands on him, and healed him.

_1 verse containing DYSENTERY_

