= ZAANAIM - ZERUIAH
:toc:

== ZAANAIM

* `Jdg 4:11` Now Heber the Kenite, who was of the children of Hobab the father-in-law of Moses, had severed himself from the Kenites and pitched his tent as far as the oak in *_Zaanaim_*, which is by Kedesh.

_1 verse containing ZAANAIM_

== ZAANAN

* `Mic 1:11` Pass on, you inhabitant of Saphir, having your shame exposed. The inhabitant of *_Zaanan_* did not come forth in the mourning of Beth-ezel. He shall receive from you his standing.

_1 verse containing ZAANAN_

== ZAANANNIM

* `Jsh 19:33` And their border was from Heleph, from Allon to *_Zaanannim_*, Adami, Nekeb, and Jabneel, to Lakum; and the limits thereof were at the Jordan;

_1 verse containing ZAANANNIM_

== ZAAVAN

* `Gen 36:27` The children of Ezer are these: Bilhan, *_Zaavan_*, and Achan.

_1 verse containing ZAAVAN_

== ZABAD

* `1Ch 2:36` And Attai begot Nathan, Nathan begot *_Zabad_*,
* `1Ch 2:37` *_Zabad_* begot Ephlal, Ephlal begot Obed,
* `1Ch 7:21` *_Zabad_* his son, Shuthelah his son, Ezer, and Elead, whom the men of Gath who were born in that land slew because they came down to take away their livestock.
* `1Ch 11:41` Uriah the Hittite, *_Zabad_* the son of Ahlai,
* `2Ch 24:26` And these are those who conspired against him: *_Zabad_* the son of Shimeath the Ammonitess, and Jehozabad the son of Shimrith the Moabitess.
* `Ezr 10:27` And of the sons of Zattu: Elioenai, Eliashib, Mattaniah, Jeremoth, *_Zabad_*, and Aziza.
* `Ezr 10:33` Of the sons of Hashum: Mattenai, Mattathah, *_Zabad_*, Eliphelet, Jeremai, Manasseh, and Shimei.
* `Ezr 10:43` Of the sons of Nebo: Jeiel, Mattithiah, *_Zabad_*, Zebina, Jadau, Joel, and Benaiah.

_8 verses containing ZABAD_

== ZABBAI

* `Ezr 10:28` Of the sons also of Bebai: Jehohanan, Hananiah, *_Zabbai_*, and Athlai.
* `Neh 3:20` After him Baruch the son of *_Zabbai_* earnestly repaired the other piece, from the turning of the wall to the door of the house of Eliashib the high priest.

_2 verses containing ZABBAI_

== ZABBUD

* `Ezr 8:14` And of the sons of Bigvai: Uthai, and *_Zabbud_*, and with them seventy males.

_1 verse containing ZABBUD_

== ZABDI

* `Jsh 7:1` But the children of Israel committed a trespass in the accursed thing, for Achan the son of Carmi, the son of *_Zabdi_*, the son of Zerah, of the tribe of Judah, took some of the accursed things. And the anger of the LORD was kindled against the children of Israel.
* `Jsh 7:17` And he brought the family of Judah, and he took the family of the Zarhites. And he brought the family of the Zarhites man by man, and *_Zabdi_* was taken.
* `Jsh 7:18` And he brought his household man by man, and Achan the son of Carmi, the son of *_Zabdi_*, the son of Zerah, of the tribe of Judah, was taken.
* `1Ch 8:19` And Jakim, Zichri, *_Zabdi_*,
* `1Ch 27:27` And over the vineyards was Shimei the Ramathite; and over the increase of the vineyards for the wine cellars was *_Zabdi_* the Shiphmite;
* `Neh 11:17` And Mattaniah the son of Micha, the son of *_Zabdi_*, the son of Asaph, was the principal to begin the thanksgiving in prayer, and Bakbukiah the second among his brothers; and Abda the son of Shammua, the son of Galal, the son of Jeduthun.

_6 verses containing ZABDI_

== ZABDIEL

* `1Ch 27:2` Over the first course for the first month was Jashobeam the son of *_Zabdiel_*. And in his course were twenty-four thousand.
* `Neh 11:14` And their brothers, mighty men of valor, one hundred twenty-eight. And their overseer was *_Zabdiel_* the son of one of the great men.

_2 verses containing ZABDIEL_

== ZABUD

* `1Ki 4:5` Azariah the son of Nathan was over the officers, *_Zabud_* the son of Nathan was principal officer and the king's friend,

_1 verse containing ZABUD_

== ZACCAI

* `Ezr 2:9` The children of *_Zaccai_*, seven hundred and sixty;
* `Neh 7:14` The children of *_Zaccai_*, seven hundred and sixty;

_2 verses containing ZACCAI_

== ZACCHEUS

* `Luk 19:2` And behold, there was a man named *_Zaccheus_*, who was the chief among the tax collectors, and he was rich.
* `Luk 19:5` And when Jesus came to the place, he looked up and saw him, and said to him, "*_Zaccheus_*, make haste and come down, for today I must abide at your house."
* `Luk 19:8` And *_Zaccheus_* stood, and said to the Lord, "Behold, Lord, the half of my goods I give to the poor, and if I have taken anything from any man by false accusation, I restore him four-fold."

_3 verses containing ZACCHEUS_

== ZACCHUR

* `1Ch 4:26` And the sons of Mishma: Hamuel his son, *_Zacchur_* his son, and Shimei his son.

_1 verse containing ZACCHUR_

== ZACCUR

* `Num 13:4` And these were their names: Of the tribe of Reuben, Shammua the son of *_Zaccur_*;
* `1Ch 24:27` The sons of Merari by Jaaziah: Beno, Shoham, *_Zaccur_*, and Ibri.
* `1Ch 25:2` Of the sons of Asaph: *_Zaccur_*, Joseph, Nethaniah, and Asarelah, the sons of Asaph under the hands of Asaph who prophesied according to the order of the king.
* `1Ch 25:10` The third to *_Zaccur_*—he, his sons, and his brothers were twelve;
* `Neh 3:2` And next to him the men of Jericho built. And next to them *_Zaccur_* the son of Imri built.
* `Neh 10:12` *_Zaccur_*, Sherebiah, Shebaniah,
* `Neh 12:35` And some of the priests' sons with trumpets, namely, Zechariah the son of Jonathan, the son of Shemaiah, the son of Mattaniah, the son of Michaiah, the son of *_Zaccur_*, the son of Asaph;
* `Neh 13:13` And I made treasurers over the treasuries: Shelemiah the priest, Zadok the scribe, and of the Levites, Pedaiah, and next to them was Hanan the son of *_Zaccur_*, the son of Mattaniah, for they were accounted faithful. Their office was to distribute to their brothers.

_8 verses containing ZACCUR_

== ZACHARIAH

* `2Ki 14:29` And Jeroboam slept with his fathers, even with the kings of Israel. And *_Zachariah_* his son reigned in his stead.
* `2Ki 15:8` In the thirty-eighth year of Azariah king of Judah, *_Zachariah_* the son of Jeroboam reigned over Israel in Samaria six months.
* `2Ki 15:11` And the rest of the acts of *_Zachariah_*, behold they are written in the book of the chronicles of the kings of Israel.
* `2Ki 18:2` He was twenty-five years old when he began to reign, and he reigned twenty-nine years in Jerusalem. His mother's name was Abi, the daughter of *_Zachariah_*.

_4 verses containing ZACHARIAH_

== ZACHER

* `1Ch 8:31` Gedor, Ahio, and *_Zacher_*.

_1 verse containing ZACHER_

== ZADOK

* `2Sa 8:17` *_Zadok_* the son of Ahitub and Ahimelech the son of Abiathar were the priests, Seraiah was the scribe,
* `2Sa 15:24` And behold, *_Zadok_* also came, and all the Levites were with him bearing the ark of the covenant of God. And they set down the ark of God, and Abiathar went up until all the people finished passing out of the city.
* `2Sa 15:25` And the king said to *_Zadok_*, "Carry the ark of God back into the city. If I find favor in the eyes of the LORD, he will bring me back and show me both it and his habitation.
* `2Sa 15:27` The king said also to *_Zadok_* the priest, "Are you not a seer? Return into the city in peace, and your two sons with you, Ahimaaz your son and Jonathan the son of Abiathar.
* `2Sa 15:29` Therefore, *_Zadok_* and Abiathar carried the ark of God back to Jerusalem, and they remained there.
* `2Sa 15:35` And do you not have there with you *_Zadok_* and Abiathar the priests? Therefore, it shall be, that whatever thing you hear out of the king's house, you shall tell it to *_Zadok_* and Abiathar the priests.
* `2Sa 15:36` Behold, they have there with them their two sons: Ahimaaz the son of *_Zadok_* and Jonathan the son of Abiathar. And by them you shall send to me everything that you hear."
* `2Sa 17:15` Then Hushai said to *_Zadok_* and to Abiathar the priests, "In this manner Ahithophel counseled Absalom and the elders of Israel, and in such a manner I have counseled.
* `2Sa 18:19` Then Ahimaaz the son of *_Zadok_* said, "Let me now run and inform the king how the LORD has avenged himself of his enemies."
* `2Sa 18:22` Then Ahimaaz the son of *_Zadok_* yet again said to Joab, "But whatever may come, let me also, I pray you, run after Cushi." And Joab said, "Why will you run, my son, seeing that you have no tidings ready?"
* `2Sa 18:27` And the watchman said, "I think the running of the foremost is like the running of Ahimaaz the son of *_Zadok_*." And the king said, "He is a good man and comes with good news."
* `2Sa 19:11` And king David sent to *_Zadok_* and to Abiathar the priests, saying, "Speak to the elders of Judah, saying, 'Why are you the last to bring the king back to his house, seeing the speech of all Israel has come to the king, even to his house?
* `2Sa 20:25` Sheva was scribe, *_Zadok_* and Abiathar were the priests,
* `1Ki 1:8` But *_Zadok_* the priest, Benaiah the son of Jehoiada, Nathan the prophet, Shimei, Rei, and the mighty men who belonged to David were not with Adonijah.
* `1Ki 1:26` But me, even me your servant, and *_Zadok_* the priest, Benaiah the son of Jehoiada, and your servant Solomon, he has not called.
* `1Ki 1:32` And king David said, "Call for me *_Zadok_* the priest, Nathan the prophet, and Benaiah the son of Jehoiada." And they came before the king.
* `1Ki 1:34` And let *_Zadok_* the priest and Nathan the prophet anoint him there king over Israel. And blow with the trumpet and say, 'God save king Solomon.'
* `1Ki 1:38` So *_Zadok_* the priest, Nathan the prophet, Benaiah the son of Jehoiada, the Cherethites, and the Pelethites went down and caused Solomon to ride upon king David's mule and brought him to Gihon.
* `1Ki 1:39` And *_Zadok_* the priest took a horn of oil out of the tabernacle and anointed Solomon. And they blew the trumpet. And all the people said, "God save king Solomon."
* `1Ki 1:44` And the king has sent with him *_Zadok_* the priest, Nathan the prophet, Benaiah the son of Jehoiada, the Cherethites, and the Pelethites, and they have caused him to ride upon the king's mule.
* `1Ki 1:45` And *_Zadok_* the priest and Nathan the prophet have anointed him king in Gihon. And they have come from there rejoicing so that the city resounded. This is the noise that you have heard.
* `1Ki 2:35` And the king put Benaiah the son of Jehoiada in his place over the army. And the king put *_Zadok_* the priest in the place of Abiathar.
* `1Ki 4:2` And these were the princes which he had: Azariah the son of *_Zadok_* the priest,
* `1Ki 4:4` Benaiah the son of Jehoiada was over the army, *_Zadok_* and Abiathar were the priests,
* `2Ki 15:33` He was twenty-five years old when he began to reign, and he reigned sixteen years in Jerusalem. And his mother's name was Jerusha, the daughter of *_Zadok_*.
* `1Ch 6:8` Ahitub begot *_Zadok_*, *_Zadok_* begot Ahimaaz,
* `1Ch 6:12` Ahitub begot *_Zadok_*, *_Zadok_* begot Shallum,
* `1Ch 6:53` *_Zadok_* his son, and Ahimaaz his son.
* `1Ch 9:11` And Azariah the son of Hilkiah, the son of Meshullam, the son of *_Zadok_*, the son of Meraioth, the son of Ahitub, the ruler of the house of God;
* `1Ch 12:28` And *_Zadok_*, a young man mighty of valor, and of his father's house twenty-two captains.
* `1Ch 15:11` And David called for *_Zadok_* and Abiathar the priests, for the Levites, for Uriel, Asaiah, Joel, Shemaiah, Eliel, and Amminadab,
* `1Ch 16:39` And David left *_Zadok_* the priest and his brothers the priests before the tabernacle of the LORD in the high place that was at Gibeon,
* `1Ch 18:16` *_Zadok_* the son of Ahitub and Abimelech the son of Abiathar were the priests, Shavsha was scribe,
* `1Ch 24:3` And David distributed them, both *_Zadok_* of the sons of Eleazar and Ahimelech of the sons of Ithamar, according to their offices in their service.
* `1Ch 24:6` And Shemaiah the son of Nethaneel the scribe, one of the Levites, recorded them before the king, the princes, *_Zadok_* the priest, Ahimelech the son of Abiathar, and before the chief of the fathers of the priests and Levites. One principal household being taken for Eleazar and one taken for Ithamar.
* `1Ch 24:31` These likewise cast lots over against their brothers the sons of Aaron in the presence of David the king, *_Zadok_*, Ahimelech, and the chief of the fathers of the priests and Levites, even the principal fathers over against their younger brothers.
* `1Ch 27:17` Of the Levites, Hashabiah the son of Kemuel; of the Aaronites, *_Zadok_*;
* `1Ch 29:22` And they ate and drank before the LORD on that day with great gladness. And they made Solomon the son of David king the second time and anointed him to the LORD to be the chief governor, and *_Zadok_* to be priest.
* `2Ch 27:1` Jotham was twenty-five years old when he began to reign and he reigned sixteen years in Jerusalem. His mother's name was Jerushah, the daughter of *_Zadok_*.
* `2Ch 31:10` And Azariah the chief priest of the house of *_Zadok_* answered him and said, "Since the people began to bring the offerings into the house of the LORD, we have had enough to eat and have plenty left over, for the LORD has blessed his people. And that which is left is this great abundance."
* `Ezr 7:2` The son of Shallum, the son of *_Zadok_*, the son of Ahitub,
* `Neh 3:4` And next to them Meremoth the son of Urijah, the son of Koz, repaired. And next to them Meshullam the son of Berechiah, the son of Meshezabeel, repaired. And next to them *_Zadok_* the son of Baana repaired.
* `Neh 3:29` After them *_Zadok_* the son of Immer repaired over against his house. After him Shemaiah the son of Shechaniah, the keeper of the east gate, repaired.
* `Neh 10:21` Meshezabeel, *_Zadok_*, Jaddua,
* `Neh 11:11` Seraiah the son of Hilkiah, the son of Meshullam, the son of *_Zadok_*, the son of Meraioth, the son of Ahitub, was the ruler of the house of God.
* `Neh 13:13` And I made treasurers over the treasuries: Shelemiah the priest, *_Zadok_* the scribe, and of the Levites, Pedaiah, and next to them was Hanan the son of Zaccur, the son of Mattaniah, for they were accounted faithful. Their office was to distribute to their brothers.
* `Ezk 40:46` And the chamber whose prospect is toward the north is for the priests, the keepers of the charge of the altar. These are the sons of *_Zadok_* among the sons of Levi, who come near to the LORD to minister to him."
* `Ezk 43:19` And you shall give to the priests the Levites who are of the offspring of *_Zadok_*, who approach to me to minister to me,' says the Lord GOD, 'a young bull for a sin-offering.
* `Ezk 44:15` "But the priests, the Levites, the sons of *_Zadok_*, who kept the charge of my sanctuary when the children of Israel went astray from me, they shall come near to me to minister to me, and they shall stand before me to offer to me the fat and the blood," says the Lord GOD.
* `Ezk 48:11` It shall be for the priests who are sanctified of the sons of *_Zadok_* who have kept my charge, who did not go astray when the children of Israel went astray, as the Levites went astray.
* `Mth 1:14` Azor begot *_Zadok_*, *_Zadok_* begot Achim, Achim begot Eliud,

_51 verses containing ZADOK_

== ZAHAM

* `2Ch 11:19` Who bore him children: Jeush, Shamariah, and *_Zaham_*.

_1 verse containing ZAHAM_

== ZAIR

* `2Ki 8:21` So Joram went over to *_Zair_*, and all the chariots with him. And he rose by night and smote the Edomites who encompassed him and the captains of the chariots, and the people fled into their tents.

_1 verse containing ZAIR_

== ZALAPH

* `Neh 3:30` After him Hananiah the son of Shelemiah and Hanun the sixth son of *_Zalaph_* repaired another piece. After him Meshullam the son of Berechiah repaired over against his chamber.

_1 verse containing ZALAPH_

== ZALMON

* `Jdg 9:48` And Abimelech ascended mount *_Zalmon_*—he and all the people who were with him—and Abimelech took an ax in his hand and cut down a bough from the trees, and took it, laid it on his shoulder, and said to the people who were with him, "What you have seen me do, make haste and do as I have done."
* `2Sa 23:28` *_Zalmon_* the Ahohite, Maharai the Netophathite,

_2 verses containing ZALMON_

== ZALMONAH

* `Num 33:41` And they departed from mount Hor and encamped in *_Zalmonah_*.
* `Num 33:42` And they departed from *_Zalmonah_* and encamped in Punon.

_2 verses containing ZALMONAH_

== ZALMUNNA

* `Jdg 8:5` And he said to the men of Succoth, "Give, I pray you, loaves of bread to the people who follow me, for they are faint, and I am pursuing Zebah and *_Zalmunna_*, kings of Midian."
* `Jdg 8:6` And the princes of Succoth said, "Are the hands of Zebah and *_Zalmunna_* now in your hand that we should give bread to your army?"
* `Jdg 8:7` And Gideon said, "Therefore, when the LORD has delivered Zebah and *_Zalmunna_* into my hand, then I will tear your flesh with the thorns of the wilderness and with briers."
* `Jdg 8:10` Now Zebah and *_Zalmunna_* were in Karkor, and their hosts with them, about fifteen thousand men, all who were left of all the hosts of the children of the east, for there fell one hundred and twenty thousand men who drew the sword.
* `Jdg 8:12` And when Zebah and *_Zalmunna_* fled, he pursued them and took the two kings of Midian, Zebah and *_Zalmunna_*, and completely defeated all the host.
* `Jdg 8:15` And he came to the men of Succoth and said, "Behold Zebah and *_Zalmunna_*, with whom you upbraided me, saying, 'Are the hands of Zebah and *_Zalmunna_* now in your hand that we should give bread to your men who are weary?'"
* `Jdg 8:18` Then he said to Zebah and *_Zalmunna_*, "What manner of men were they whom you slew at Tabor?" And they answered, "As you are, so were they. Each one resembled the child of a king."
* `Jdg 8:21` Then Zebah and *_Zalmunna_* said, "Rise, and fall upon us. For as the man is, so is his strength." And Gideon arose, slew Zebah and *_Zalmunna_*, and took away the ornaments that were on their camels' necks.
* `Psa 83:11` Make their nobles like Oreb and like Zeeb, even all their princes like Zebah and like *_Zalmunna_*,

_9 verses containing ZALMUNNA_

== ZAMZUMMIMS

* `Deu 2:20` (That also was accounted a land of Rephaim. Rephaim dwelt in it in old time, and the Ammonites call them *_Zamzummims_*,

_1 verse containing ZAMZUMMIMS_

== ZANOAH

* `Jsh 15:34` *_Zanoah_*, En-gannim, Tappuah, Enam,
* `Jsh 15:56` Jezreel, Jokdeam, *_Zanoah_*,
* `1Ch 4:18` And his wife Jehudijah bore Jered the father of Gedor, Heber the father of Socho, and Jekuthiel the father of *_Zanoah_*. And these are the sons of Bithiah the daughter of Pharaoh whom Mered took.
* `Neh 3:13` The valley-gate was repaired by Hanun and the inhabitants of *_Zanoah_*. They built it, set up its doors, its locks, and its bars, and one thousand cubits on the wall to the dung-gate.
* `Neh 11:30` *_Zanoah_*, Adullam, and in their villages, at Lachish and its fields, and at Azekah and in its villages. And they dwelt from Beer-sheba to the valley of Hinnom.

_5 verses containing ZANOAH_

== ZAPHNATH-PAANEAH

* `Gen 41:45` And Pharaoh called Joseph's name *_Zaphnath-paaneah_*, and he gave him for a wife Asenath the daughter of Poti-pherah priest of On. And Joseph went over all the land of Egypt.

_1 verse containing ZAPHNATH-PAANEAH_

== ZAPHON

* `Jsh 13:27` And in the valley, Beth-aram, Beth-nimrah, Succoth, and *_Zaphon_*, the rest of the kingdom of Sihon king of Heshbon, the Jordan and its border, even to the edge of the sea of Cinneroth, on the other side of the Jordan eastward.

_1 verse containing ZAPHON_

== ZARAH

* `Gen 38:30` And afterward, his brother came out who had the scarlet thread upon his hand, and his name was called *_Zarah_*.
* `Mth 1:3` Judah begot Pharez and *_Zarah_* by Tamar, Pharez begot Hezron, Hezron begot Ram,

_2 verses containing ZARAH_

== ZAREAH

* `Neh 11:29` At En-rimmon, at *_Zareah_*, at Jarmuth,

_1 verse containing ZAREAH_

== ZARED

* `Num 21:12` From there they departed and pitched in the valley of *_Zared_*.

_1 verse containing ZARED_

== ZAREPHATH

* `1Ki 17:9` "Arise, go to *_Zarephath_*, which belongs to Zidon, and dwell there. Behold, I have commanded a widow woman there to sustain you."
* `1Ki 17:10` So he arose and went to *_Zarephath_*. And when he came to the gate of the city, behold, the widow woman was there gathering sticks. And he called to her and said, "Bring me, I pray you, a little water in a vessel that I may drink."
* `Oba 1:20` And the captivity of this host of the children of Israel shall possess that of the Canaanites, even to *_Zarephath_*. And the captivity of Jerusalem, which is in Sepharad, shall possess the cities of the south.
* `Luk 4:26` But Elijah was sent to none of them, except to *_Zarephath_*, a city of Sidon, to a woman who was a widow.

_4 verses containing ZAREPHATH_

== ZARETAN

* `Jsh 3:16` The waters which came down from above stood and rose up in a heap very far from the city of Adam, that is beside *_Zaretan_*, and those which came down toward the sea of the plain, even the Salt Sea, failed, and were cut off. And the people passed through over against Jericho.

_1 verse containing ZARETAN_

== ZARETH-SHAHAR

* `Jsh 13:19` Kirjathaim, Sibmah, *_Zareth-shahar_* on the mountain of the valley,

_1 verse containing ZARETH-SHAHAR_

== ZARHITES

* `Num 26:13` Of Zerah, the family of the *_Zarhites_*; of Shaul, the family of the Shaulites.
* `Num 26:20` And these were the sons of Judah after their families: of Shelah, the family of the Shelanites; of Pharez, the family of the Pharezites; of Zerah, the family of the *_Zarhites_*.
* `Jsh 7:17` And he brought the family of Judah, and he took the family of the *_Zarhites_*. And he brought the family of the *_Zarhites_* man by man, and Zabdi was taken.
* `1Ch 27:11` The eighth captain for the eighth month was Sibbecai the Hushathite, of the *_Zarhites_*. And in his course were twenty-four thousand.
* `1Ch 27:13` The tenth captain for the tenth month was Maharai the Netophathite, of the *_Zarhites_*. And in his course were twenty-four thousand.

_5 verses containing ZARHITES_

== ZARTANAH

* `1Ki 4:12` Baana the son of Ahilud—to him pertained Taanach, Megiddo, and all Beth-shean, which is by *_Zartanah_* beneath Jezreel, from Beth-shean to Abel-meholah, even to the place that is beyond Jokneam;

_1 verse containing ZARTANAH_

== ZARTHAN

* `1Ki 7:46` In the plain of the Jordan the king cast them, in the clay ground between Succoth and *_Zarthan_*.

_1 verse containing ZARTHAN_

== ZATTHU

* `Neh 10:14` The chief of the people: Parosh, Pahath-moab, Elam, *_Zatthu_*, Bani,

_1 verse containing ZATTHU_

== ZATTU

* `Ezr 2:8` The children of *_Zattu_*, nine hundred and forty-five;
* `Ezr 10:27` And of the sons of *_Zattu_*: Elioenai, Eliashib, Mattaniah, Jeremoth, Zabad, and Aziza.
* `Neh 7:13` The children of *_Zattu_*, eight hundred and forty five;

_3 verses containing ZATTU_

== ZAVAN

* `1Ch 1:42` The sons of Ezer: Bilhan, *_Zavan_*, and Jakan. The sons of Dishan: Uz and Aran.

_1 verse containing ZAVAN_

== ZAYIN

* `Psa 25:7` [*_ZAYIN_*] Do not remember the sins of my youth, nor my transgressions. According to your mercy remember me for your goodness' sake, O LORD.
* `Psa 119:49` [*_ZAYIN_*] Remember the word to your servant, upon which you have caused me to hope.
* `Pro 31:16` [*_ZAYIN_*] She considers a field and buys it. With the fruit of her hands she plants a vineyard.
* `Lam 1:7` [*_ZAYIN_*] Jerusalem remembers in the days of her affliction and of her miseries all her pleasant things that she had in the days of old. When her people fell into the hand of the enemy, no one helped her. The adversaries saw her and mocked at her desolations.
* `Lam 2:7` [*_ZAYIN_*] The Lord has cast off his altar. He has abhorred his sanctuary. He has given up into the hand of the enemy the walls of her palaces. They have made a noise in the house of the LORD as in the day of a solemn feast.
* `Lam 3:19` [*_ZAYIN_*] Remember my affliction and my misery, the wormwood and the gall.
* `Lam 4:7` [*_ZAYIN_*] Her Nazarites were purer than snow. They were whiter than milk. They were more ruddy in body than rubies. Their polishing was like sapphire.

_7 verses containing ZAYIN_

== ZAZA

* `1Ch 2:33` And the sons of Jonathan: Peleth and *_Zaza_*. These were the sons of Jerahmeel.

_1 verse containing ZAZA_

== ZEAL

* `2Sa 21:2` And the king called the Gibeonites and spoke to them. (Now the Gibeonites were not of the children of Israel, but of the remnant of the Amorites. And the children of Israel had sworn to them, but Saul sought to slay them in his *_zeal_* to the children of Israel and Judah.)
* `2Ki 10:16` And he said, "Come with me and see my *_zeal_* for the LORD." So they made him ride in his chariot.
* `2Ki 19:31` For out of Jerusalem a remnant shall go forth, and out of mount Zion those who escape. The *_zeal_* of the LORD of hosts shall do this.
* `Psa 69:9` For the *_zeal_* of your house has eaten me up. And the reproaches of those who reproached you have fallen upon me.
* `Psa 119:139` My *_zeal_* has consumed me because my enemies have forgotten your words.
* `Isa 9:7` Of the increase of his government and peace there shall be no end, upon the throne of David and upon his kingdom, to order it and to establish it with judgment and with justice from now on even forever. The *_zeal_* of the LORD of hosts will perform this.
* `Isa 26:11` LORD, when your hand is lifted up, they will not see. But they shall see your *_zeal_* for the people and be put to shame. Even the fire of your enemies shall devour them.
* `Isa 37:32` For out of Jerusalem a remnant shall go forth, and out of mount Zion those who escape. The *_zeal_* of the LORD of hosts will do this."'
* `Isa 59:17` For he put on righteousness as a breast-plate, and a helmet of salvation upon his head. And he put on the garments of vengeance for clothing, and was clad with *_zeal_* as a cloak.
* `Isa 63:15` Look down from heaven and behold from the habitation of your holiness and of your glory. Where is your *_zeal_* and your strength, the sounding of your heart and of your mercy toward me? Are they restrained?
* `Ezk 5:13` 'Thus my anger shall be accomplished, and I will cause my fury to rest upon them and I will be comforted. And they shall know that I, the LORD, have spoken it in my *_zeal_* when I have accomplished my fury in them.
* `Jhn 2:17` And his disciples remembered that it was written, "The *_zeal_* of your house has eaten me up."
* `Rom 10:2` For I bear them testimony that they have a *_zeal_* for God, but not according to knowledge.
* `2Co 7:11` For behold this very thing, that you sorrowed after a godly manner, what it has wrought in you: what carefulness, what clearing of yourselves, what indignation, what fear, what vehement desire, what *_zeal_*, and what avenging! In all things you have approved yourselves to be clear in this matter.
* `2Co 9:2` For I know the forwardness of your mind, for which I boast about you to those of Macedonia that Achaia has been ready since last year. And your *_zeal_* has incited very many.
* `Phl 3:6` Concerning *_zeal_*, persecuting the church; with respect to the righteousness which is by the law, found blameless.
* `Col 4:13` For I bear him testimony, that he has a great *_zeal_* for you and those who are in Laodicea and those in Hierapolis.

_17 verses containing ZEAL_

== ZEALOUS

* `Num 25:11` "Phinehas, the son of Eleazar, the son of Aaron the priest, has turned my wrath away from the children of Israel (while he was *_zealous_* for my sake among them) so that I did not consume the children of Israel in my jealousy.
* `Num 25:13` And he shall have it, and his offspring after him, even the covenant of an everlasting priesthood, because he was *_zealous_* for his God and made an atonement for the children of Israel.'"
* `Act 21:20` And when they heard it, they glorified the Lord and said to him, "You see, brother, how many thousands of Jews there are who believe, and they are all *_zealous_* of the law.
* `Act 22:3` "I am truly a Jew, born in Tarsus, a city in Cilicia, yet brought up in this city at the feet of Gamaliel and taught according to the perfect manner of the law of the fathers, being *_zealous_* toward God as you all are this day.
* `1Co 14:12` Even so you, because you are *_zealous_* of spiritual gifts, seek so that you may excel to the edifying of the church.
* `Gal 1:14` And profited in the Jews' religion above many of my equals in my own nation, being more exceedingly *_zealous_* of the traditions of my fathers.
* `Gal 4:17` They zealously affect you, but not in a good way. They wish to exclude you so that you may be *_zealous_* for them.
* `Tit 2:14` Who gave himself for us so that he might redeem us from all iniquity and purify for himself a peculiar people, *_zealous_* of good works.
* `Rev 3:19` As many as I love, I rebuke and chasten. Be *_zealous_* therefore, and repent.

_9 verses containing ZEALOUS_

== ZEALOUSLY

* `Gal 4:17` They *_zealously_* affect you, but not in a good way. They wish to exclude you so that you may be zealous for them.
* `Gal 4:18` But it is good to be *_zealously_* affected always in a good thing, and not only when I am present with you.

_2 verses containing ZEALOUSLY_

== ZEBADIAH

* `1Ch 8:15` *_Zebadiah_*, Arad, Ader,
* `1Ch 8:17` And *_Zebadiah_*, Meshullam, Hezeki, Heber,
* `1Ch 12:7` And Joelah and *_Zebadiah_* (the sons of Jeroham of Gedor).
* `1Ch 26:2` And the sons of Meshelemiah were Zechariah the first-born, Jediael the second, *_Zebadiah_* the third, Jathniel the fourth,
* `1Ch 27:7` The fourth captain for the fourth month was Asahel the brother of Joab and *_Zebadiah_* his son after him. And in his course were twenty-four thousand.
* `2Ch 17:8` And with them he sent Levites, even Shemaiah, Nethaniah, *_Zebadiah_*, Asahel, Shemiramoth, Jehonathan, Adonijah, Tobijah, and Tob-adonijah, Levites; and with them Elishama and Jehoram, priests.
* `2Ch 19:11` And behold, Amariah the chief priest is over you in all matters of the LORD, and *_Zebadiah_* the son of Ishmael, the ruler of the house of Judah, in all the king's matters. Also, the Levites shall be officers before you. Deal courageously, and the LORD will be with the good."
* `Ezr 8:8` Of the sons of Shephatiah: *_Zebadiah_* the son of Michael, and with him eighty males.
* `Ezr 10:20` And of the sons of Immer: Hanani and *_Zebadiah_*.

_9 verses containing ZEBADIAH_

== ZEBAH

* `Jdg 8:5` And he said to the men of Succoth, "Give, I pray you, loaves of bread to the people who follow me, for they are faint, and I am pursuing *_Zebah_* and Zalmunna, kings of Midian."
* `Jdg 8:6` And the princes of Succoth said, "Are the hands of *_Zebah_* and Zalmunna now in your hand that we should give bread to your army?"
* `Jdg 8:7` And Gideon said, "Therefore, when the LORD has delivered *_Zebah_* and Zalmunna into my hand, then I will tear your flesh with the thorns of the wilderness and with briers."
* `Jdg 8:10` Now *_Zebah_* and Zalmunna were in Karkor, and their hosts with them, about fifteen thousand men, all who were left of all the hosts of the children of the east, for there fell one hundred and twenty thousand men who drew the sword.
* `Jdg 8:12` And when *_Zebah_* and Zalmunna fled, he pursued them and took the two kings of Midian, *_Zebah_* and Zalmunna, and completely defeated all the host.
* `Jdg 8:15` And he came to the men of Succoth and said, "Behold *_Zebah_* and Zalmunna, with whom you upbraided me, saying, 'Are the hands of *_Zebah_* and Zalmunna now in your hand that we should give bread to your men who are weary?'"
* `Jdg 8:18` Then he said to *_Zebah_* and Zalmunna, "What manner of men were they whom you slew at Tabor?" And they answered, "As you are, so were they. Each one resembled the child of a king."
* `Jdg 8:21` Then *_Zebah_* and Zalmunna said, "Rise, and fall upon us. For as the man is, so is his strength." And Gideon arose, slew *_Zebah_* and Zalmunna, and took away the ornaments that were on their camels' necks.
* `Psa 83:11` Make their nobles like Oreb and like Zeeb, even all their princes like *_Zebah_* and like Zalmunna,

_9 verses containing ZEBAH_

== ZEBAIM

* `Ezr 2:57` The children of Shephatiah, the children of Hattil, the children of Pochereth of *_Zebaim_*, and the children of Ami.
* `Neh 7:59` The children of Shephatiah, the children of Hattil, the children of Pochereth of *_Zebaim_*, and the children of Amon.

_2 verses containing ZEBAIM_

== ZEBEDEE

* `Mth 4:21` And going on from there, he saw two other brothers, James the son of *_Zebedee_* and John his brother, in a boat with *_Zebedee_* their father, mending their nets, and he called them.
* `Mth 10:2` Now the names of the twelve apostles are these: The first, Simon, who is called Peter, and Andrew his brother; James the son of *_Zebedee_*, and John his brother;
* `Mth 20:20` Then the mother of *_Zebedee_*'s children came to him with her sons, worshiping him and desiring a certain thing of him.
* `Mth 26:37` And he took with him Peter and the two sons of *_Zebedee_* and began to be sorrowful and very heavy.
* `Mth 27:56` Among whom was Mary Magdalene, Mary the mother of James and Joseph, and the mother of *_Zebedee_*'s children.
* `Mrk 1:19` And when he had gone a little farther from there, he saw James the son of *_Zebedee_* and John his brother, who also were in the boat mending their nets.
* `Mrk 1:20` And immediately he called them, and they left their father *_Zebedee_* in the boat with the hired servants and went after him.
* `Mrk 3:17` James the son of *_Zebedee_* and John the brother of James (he surnamed them Boanerges, which is, Sons of Thunder),
* `Mrk 10:35` And James and John the sons of *_Zebedee_* come to him, saying, "Master, we wish that you should do for us whatever we desire."
* `Luk 5:10` And so were James and John the sons of *_Zebedee_*, who were partners with Simon. And Jesus said to Simon, "Do not fear. From now on you shall catch men."
* `Jhn 21:2` Simon Peter, Thomas called Didymus, Nathanael of Cana in Galilee, the sons of *_Zebedee_*, and two others of his disciples were together.

_11 verses containing ZEBEDEE_

== ZEBINA

* `Ezr 10:43` Of the sons of Nebo: Jeiel, Mattithiah, Zabad, *_Zebina_*, Jadau, Joel, and Benaiah.

_1 verse containing ZEBINA_

== ZEBOIIM

* `Gen 14:2` That these made war with Bera king of Sodom, Birsha king of Gomorrah, Shinab king of Admah, Shemeber king of *_Zeboiim_*, and the king of Bela, which is Zoar.
* `Gen 14:8` And the king of Sodom, the king of Gomorrah, the king of Admah, the king of *_Zeboiim_*, and the king of Bela (the same is Zoar) went out, and they joined battle with them in the valley of Siddim,

_2 verses containing ZEBOIIM_

== ZEBOIM

* `Gen 10:19` And the border of the Canaanites was from Sidon, as far as to Gerar, to Gaza, as far as to Sodom, Gomorrah, Admah, and *_Zeboim_*, even to Lashah.
* `Deu 29:23` And that its whole land is brimstone, salt, and burning, that it is not sown, nor does it bear, nor does any grass grow in it like the overthrow of Sodom, Gomorrah, Admah, and *_Zeboim_*, which the LORD overthrew in his anger and in his wrath—
* `1Sa 13:18` Another company turned the way to Beth-horon, and another company turned to the way of the border that looks to the valley of *_Zeboim_* toward the wilderness.
* `Neh 11:34` Hadid, *_Zeboim_*, Neballat,
* `Hos 11:8` How shall I give you up, Ephraim? How shall I deliver you, Israel? How shall I make you as Admah? How shall I set you as *_Zeboim_*? My heart is turned within me. My repentings are kindled together.

_5 verses containing ZEBOIM_

== ZEBUDAH

* `2Ki 23:36` Jehoiakim was twenty-five years old when he began to reign, and he reigned eleven years in Jerusalem. And his mother's name was *_Zebudah_*, the daughter of Pedaiah of Rumah.

_1 verse containing ZEBUDAH_

== ZEBUL

* `Jdg 9:28` And Gaal the son of Ebed said, "Who is Abimelech and who is Shechem that we should serve him? Is he not the son of Jerubbaal, and *_Zebul_* his officer? Serve the men of Hamor the father of Shechem. For why should we serve him?
* `Jdg 9:30` And when *_Zebul_* the ruler of the city heard the words of Gaal the son of Ebed, his anger was kindled.
* `Jdg 9:36` And when Gaal saw the people, he said to *_Zebul_*, "Behold, there, people come down from the top of the mountains." And *_Zebul_* said to him, "You see the shadow of the mountains as if they were men."
* `Jdg 9:38` Then *_Zebul_* said to him, "Where is your mouth now with which you said, 'Who is Abimelech that we should serve him?' Are these not the people whom you have despised? Go out, I pray now, and fight with them."
* `Jdg 9:41` And Abimelech dwelt at Arumah, and *_Zebul_* thrust out Gaal and his brothers, so that they should not dwell in Shechem.

_5 verses containing ZEBUL_

== ZEBULONITE

* `Jdg 12:11` And after him Elon, a *_Zebulonite_*, judged Israel, and he judged Israel for ten years.
* `Jdg 12:12` And Elon the *_Zebulonite_* died and was buried in Ajalon in the country of Zebulun.

_2 verses containing ZEBULONITE_

== ZEBULUN

* `Gen 30:20` And Leah said, "God has endowed me with a good dower. Now my husband will dwell with me because I have borne him six sons." And she called his name *_Zebulun_*.
* `Gen 35:23` The sons of Leah: Reuben (Jacob's first-born), Simeon, Levi, Judah, Issachar, and *_Zebulun_*.
* `Gen 46:14` And the sons of *_Zebulun_*: Sered, Elon, and Jahleel.
* `Gen 49:13` "*_Zebulun_* shall dwell at the haven of the sea, and he shall be for a haven of ships. And his border shall be to Zidon.
* `Exo 1:3` Issachar, *_Zebulun_*, Benjamin,
* `Num 1:9` Of *_Zebulun_*, Eliab the son of Helon;
* `Num 1:30` Of the children of *_Zebulun_*—by their generations, after their families, by the house of their fathers, according to the number of the names, from twenty years old and upward, all who were able to go forth to war—
* `Num 1:31` Those who were numbered of them, even of the tribe of *_Zebulun_*, were fifty-seven thousand and four hundred.
* `Num 2:7` Then the tribe of *_Zebulun_*, and Eliab the son of Helon shall be captain of the children of *_Zebulun_*.
* `Num 7:24` On the third day Eliab the son of Helon, prince of the children of *_Zebulun_*, offered.
* `Num 10:16` And over the host of the tribe of the children of *_Zebulun_* was Eliab the son of Helon.
* `Num 13:10` Of the tribe of *_Zebulun_*, Gaddiel the son of Sodi;
* `Num 26:26` Of the sons of *_Zebulun_* after their families: of Sered, the family of the Sardites; of Elon, the family of the Elonites; of Jahleel, the family of the Jahleelites.
* `Num 34:25` The prince of the tribe of the children of *_Zebulun_*, Elizaphan the son of Parnach;
* `Deu 27:13` And these shall stand upon mount Ebal to curse: Reuben, Gad, Asher, *_Zebulun_*, Dan, and Naphtali.
* `Deu 33:18` And of *_Zebulun_* he said, "Rejoice, *_Zebulun_*, in your going out, and Issachar, in your tents.
* `Jsh 19:10` And the third lot came up for the children of *_Zebulun_* according to their families. And the border of their inheritance was to Sarid.
* `Jsh 19:16` This is the inheritance of the children of *_Zebulun_* according to their families, these cities with their villages.
* `Jsh 19:27` And turns toward the sunrise to Beth-dagon, and reaches to *_Zebulun_*, and to the valley of Jiphthah-el toward the north side of Beth-emek, and Neiel, and goes out to Cabul on the left hand,
* `Jsh 19:34` And then the border turns westward to Aznoth-tabor, goes out from there to Hukkok, reaches to *_Zebulun_* on the south side, reaches to Asher on the west side, and to Judah upon the Jordan toward the sunrise;
* `Jsh 21:7` The children of Merari by their families had out of the tribe of Reuben, out of the tribe of Gad, and out of the tribe of *_Zebulun_*, twelve cities.
* `Jsh 21:34` And to the families of the children of Merari, the rest of the Levites, out of the tribe of *_Zebulun_*, Jokneam with its suburbs, Kartah with its suburbs,
* `Jdg 1:30` *_Zebulun_* did not expel the inhabitants of Kitron nor the inhabitants of Nahalol, but the Canaanites dwelt among them and became tributaries.
* `Jdg 4:6` And she sent and called Barak the son of Abinoam from Kedesh-naphtali and said to him, "Has the LORD God of Israel not commanded, saying, 'Go, draw toward mount Tabor, and take with you ten thousand men from the children of Naphtali and from the children of *_Zebulun_*.
* `Jdg 4:10` And Barak called *_Zebulun_* and Naphtali to Kedesh, and he went up with ten thousand men at his feet. And Deborah went up with him.
* `Jdg 5:14` Out of Ephraim there was a root of them against Amalek. After you was Benjamin among your people. Out of Machir governors came down, and out of *_Zebulun_* those who handle the pen of the writer.
* `Jdg 5:18` *_Zebulun_* was a people who jeopardized their lives to death, and Naphtali also, on the high places of the field.
* `Jdg 6:35` And he sent messengers throughout all Manasseh, who also was called after him. And he sent messengers to Asher, to *_Zebulun_*, and to Naphtali, and they came up to meet them.
* `Jdg 12:12` And Elon the Zebulonite died and was buried in Ajalon in the country of *_Zebulun_*.
* `1Ch 2:1` These are the sons of Israel: Reuben, Simeon, Levi, Judah, Issachar, *_Zebulun_*,
* `1Ch 6:63` To the sons of Merari were given by lot throughout their families, out of the tribe of Reuben, out of the tribe of Gad, and out of the tribe of *_Zebulun_*, twelve cities.
* `1Ch 6:77` To the rest of the children of Merari were given out of the tribe of *_Zebulun_*, Rimmon with its suburbs and Tabor with its suburbs.
* `1Ch 12:33` Of *_Zebulun_*, those who went forth to battle, expert in war with all instruments of war, were fifty thousand who could keep rank. They were not of double heart.
* `1Ch 12:40` Moreover, those who were near them, even as far as Issachar, *_Zebulun_*, and Naphtali, brought food on donkeys, on camels, on mules, and on oxen—abundant provision of meal, fig cakes, bunches of raisins, wine, oil, oxen, and sheep—for there was joy in Israel.
* `1Ch 27:19` Of *_Zebulun_*, Ishmaiah the son of Obadiah; of Naphtali, Jerimoth the son of Azriel;
* `2Ch 30:10` So the posts passed from city to city through the country of Ephraim and Manasseh and even to *_Zebulun_*, but they laughed them to scorn and mocked them.
* `2Ch 30:11` Nevertheless, some of Asher, Manasseh, and of *_Zebulun_* humbled themselves and came to Jerusalem.
* `2Ch 30:18` For a multitude of the people, even many of Ephraim, Manasseh, Issachar, and *_Zebulun_*, had not cleansed themselves, yet they ate the passover in a way other than it was written. But Hezekiah prayed for them, saying, "May the good LORD pardon everyone
* `Psa 68:27` There is the youngest, Benjamin, with their ruler, the princes of Judah and their counsel, the princes of *_Zebulun_*, and the princes of Naphtali.
* `Isa 9:1` Nevertheless, there shall be no more gloom to her who was in anguish. In the former time, he brought into contempt the land of *_Zebulun_* and the land of Naphtali, but in the latter time, he has made glorious the way of the sea, the land beyond the Jordan, Galilee of the nations.
* `Ezk 48:26` And by the border of Issachar, from the east side to the west side, *_Zebulun_* a portion.
* `Ezk 48:27` And by the border of *_Zebulun_*, from the east side to the west side, Gad a portion.
* `Ezk 48:33` And on the south side four thousand and five hundred measures, and three gates: the gate of Simeon, one; the gate of Issachar, one; the gate of *_Zebulun_*, one.
* `Mth 4:13` And leaving Nazareth, he came and dwelt in Capernaum, which is upon the sea coast, in the borders of *_Zebulun_* and Naphtali,
* `Mth 4:15` "The land of *_Zebulun_* and the land of Naphtali, toward the sea, beyond the Jordan, Galilee of the Gentiles—
* `Rev 7:8` Of the tribe of *_Zebulun_*, twelve thousand were sealed. Of the tribe of Joseph, twelve thousand were sealed. Of the tribe of Benjamin, twelve thousand were sealed.

_46 verses containing ZEBULUN_

== ZEBULUNITES

* `Num 26:27` These are the families of the *_Zebulunites_* according to those who were numbered of them, sixty thousand and five hundred.

_1 verse containing ZEBULUNITES_

== ZECHARIAH

* `1Ch 5:7` And his brothers by their families, when the genealogy of their generations was reckoned, were the chief: Jeiel, *_Zechariah_*,
* `1Ch 9:21` And *_Zechariah_* the son of Meshelemiah was gatekeeper of the door of the Tabernacle of the Congregation.
* `1Ch 9:37` Gedor, Ahio, *_Zechariah_*, and Mikloth.
* `1Ch 15:18` And with them their brothers of the second degree: *_Zechariah_*, Ben, Jaaziel, Shemiramoth, Jehiel, Unni, Eliab, Benaiah, Maaseiah, Mattithiah, Elipheleh, Mikneiah, Obed-edom, and Jeiel, the gatekeepers.
* `1Ch 15:20` And *_Zechariah_*, Aziel, Shemiramoth, Jehiel, Unni, Eliab, Maaseiah, and Benaiah with psalteries on Alamoth;
* `1Ch 15:24` And Shebaniah, Jehoshaphat, Nethaneel, Amasai, *_Zechariah_*, Benaiah, and Eliezer the priests blew with the trumpets before the ark of God. And Obed-edom and Jehiah were door-keepers for the ark.
* `1Ch 16:5` Asaph the chief, and next to him *_Zechariah_*, Jeiel, Shemiramoth, Jehiel, Mattithiah, Eliab, Benaiah, and Obed-edom; and Jeiel with psalteries and with harps; but Asaph made a sound with cymbals;
* `1Ch 24:25` The brother of Michah was Isshiah. Of the sons of Isshiah: *_Zechariah_*.
* `1Ch 26:2` And the sons of Meshelemiah were *_Zechariah_* the first-born, Jediael the second, Zebadiah the third, Jathniel the fourth,
* `1Ch 26:11` Hilkiah the second, Tebaliah the third, and *_Zechariah_* the fourth. All the sons and brothers of Hosah were thirteen.
* `1Ch 26:14` And the lot eastward fell to Shelemiah. Then for *_Zechariah_* his son, a wise counselor, they cast lots, and his lot came out northward.
* `1Ch 27:21` Of the half tribe of Manasseh in Gilead, Iddo the son of *_Zechariah_*; of Benjamin, Jaasiel the son of Abner;
* `2Ch 17:7` Also in the third year of his reign he sent to his princes, even to Ben-hail, to Obadiah, to *_Zechariah_*, to Nethaneel, and to Michaiah, to teach in the cities of Judah.
* `2Ch 20:14` Then upon Jehaziel the son of *_Zechariah_*, the son of Benaiah, the son of Jeiel, the son of Mattaniah, a Levite of the sons of Asaph, the Spirit of the LORD came in the midst of the congregation.
* `2Ch 21:2` And he had brothers, the sons of Jehoshaphat: Azariah, Jehiel, *_Zechariah_*, Azariahu, Michael, and Shephatiah. All these were the sons of Jehoshaphat king of Israel.
* `2Ch 24:20` And the Spirit of God came upon *_Zechariah_* the son of Jehoiada the priest, who stood above the people, and said to them, "Thus says God: 'Why do you transgress the commandments of the LORD so that you cannot prosper? Because you have forsaken the LORD, he has also forsaken you.'"
* `2Ch 26:5` And he sought God in the days of *_Zechariah_*, who had understanding in the visions of God. And as long as he sought the LORD, God made him to prosper.
* `2Ch 29:1` Hezekiah began to reign when he was twenty-five years old, and he reigned twenty-nine years in Jerusalem. And his mother's name was Abijah the daughter of *_Zechariah_*.
* `2Ch 29:13` And of the sons of Elizaphan: Shimri and Jeiel; and of the sons of Asaph: *_Zechariah_* and Mattaniah;
* `2Ch 34:12` And the men did the work faithfully. And their overseers were Jahath and Obadiah, the Levites, of the sons of Merari; and *_Zechariah_* and Meshullam, of the sons of the Kohathites, to superintend it; and others of the Levites, all who had skill in instruments of music.
* `2Ch 35:8` And his princes gave willingly to the people, to the priests, and to the Levites. Hilkiah, *_Zechariah_*, and Jehiel, rulers of the house of God, gave to the priests for the passover-offerings two thousand and six hundred small livestock, and three hundred oxen.
* `Ezr 5:1` Then the prophets, Haggai the prophet and *_Zechariah_* the son of Iddo, prophesied to the Jews who were in Judah and Jerusalem in the name of the God of Israel, even to them.
* `Ezr 6:14` And the elders of the Jews built, and they prospered through the prophesying of Haggai the prophet and *_Zechariah_* the son of Iddo. And they built and finished it according to the commandment of the God of Israel and according to the commandment of Cyrus, Darius, and Artaxerxes king of Persia.
* `Ezr 8:3` Of the sons of Shechaniah, of the sons of Pharosh: *_Zechariah_*, and with him were one hundred and fifty reckoned by genealogy of the males.
* `Ezr 8:11` Of the sons of Bebai: *_Zechariah_* the son of Bebai, and with him twenty-eight males.
* `Ezr 8:16` Then I sent for Eliezer, for Ariel, for Shemaiah, for Elnathan, for Jarib, for Elnathan, for Nathan, for *_Zechariah_*, and for Meshullam, chief men, and also for Joiarib and for Elnathan, men of understanding.
* `Ezr 10:26` And of the sons of Elam: Mattaniah, *_Zechariah_*, Jehiel, Abdi, Jeremoth, and Eliah.
* `Neh 8:4` And Ezra the scribe stood upon a pulpit of wood, which they had made for this purpose. And beside him stood Mattithiah, Shema, Anaiah, Urijah, Hilkiah, and Maaseiah on his right hand, and on his left hand, Pedaiah, Mishael, Malchiah, Hashum, Hashbadana, *_Zechariah_*, and Meshullam.
* `Neh 11:4` And some of the children of Judah and some of the children of Benjamin dwelt at Jerusalem. Of the children of Judah: Athaiah the son of Uzziah, the son of *_Zechariah_*, the son of Amariah, the son of Shephatiah, the son of Mahalaleel, of the children of Perez;
* `Neh 11:5` And Maaseiah the son of Baruch, the son of Col-hozeh, the son of Hazaiah, the son of Adaiah, the son of Joiarib, the son of *_Zechariah_*, the son of Shiloni.
* `Neh 11:12` And their brothers who performed the work of the house numbered eight hundred and twenty-two; and Adaiah the son of Jeroham, the son of Pelaliah, the son of Amzi, the son of *_Zechariah_*, the son of Pashur, the son of Malchiah,
* `Neh 12:16` Of Iddo, *_Zechariah_*; of Ginnethon, Meshullam;
* `Neh 12:35` And some of the priests' sons with trumpets, namely, *_Zechariah_* the son of Jonathan, the son of Shemaiah, the son of Mattaniah, the son of Michaiah, the son of Zaccur, the son of Asaph;
* `Neh 12:41` And the priests, Eliakim, Maaseiah, Miniamin, Michaiah, Elioenai, *_Zechariah_*, and Hananiah, with trumpets;
* `Isa 8:2` And I took for myself faithful witnesses to record: Uriah the priest and *_Zechariah_* the son of Jeberechiah.
* `Zch 1:1` In the eighth month, in the second year of Darius, the word of the LORD came to the prophet *_Zechariah_*, the son of Barachiah, the son of Iddo, saying,
* `Zch 1:7` On the twenty-fourth day of the eleventh month, which is the month Sebat, in the second year of Darius, the word of the LORD came to the prophet *_Zechariah_*, the son of Barachiah, the son of Iddo, saying,
* `Zch 7:1` And it came to pass in the fourth year of king Darius, that the word of the LORD came to *_Zechariah_* on the fourth day of the ninth month, even in Chisleu,
* `Zch 7:8` And the word of the LORD came to *_Zechariah_*, saying,
* `Mth 23:35` So that upon you may come all the righteous blood shed upon the earth, from the blood of righteous Abel, to the blood of *_Zechariah_* son of Barachiah, whom you slew between the temple and the altar.
* `Luk 1:5` There was in the days of Herod the king of Judea, a certain priest named *_Zechariah_*, of the course of Abia. And his wife was of the daughters of Aaron, and her name was Elizabeth.
* `Luk 1:12` And when *_Zechariah_* saw him, he was troubled and fear fell upon him.
* `Luk 1:13` But the angel said to him, "Do not fear, *_Zechariah_*, for your prayer is heard. Your wife Elizabeth shall bear you a son, and you shall call his name John.
* `Luk 1:18` And *_Zechariah_* said to the angel, "By what shall I know this? For I am an old man and my wife is far advanced in years."
* `Luk 1:21` And the people waited for *_Zechariah_* and marveled that he delayed so long in the temple.
* `Luk 1:40` And entered into the house of *_Zechariah_* and saluted Elizabeth.
* `Luk 1:59` And it came to pass, that on the eighth day they came to circumcise the child, and they called him *_Zechariah_*, after the name of his father.
* `Luk 1:67` And his father *_Zechariah_* was filled with the Holy Spirit and prophesied, saying,
* `Luk 3:2` Annas and Caiaphas being the high priests, the word of God came to John the son of *_Zechariah_* in the wilderness.
* `Luk 11:51` From the blood of Abel to the blood of *_Zechariah_*, who perished between the altar and the temple.' Truly I say to you, it shall be required of this generation.

_50 verses containing ZECHARIAH_

== ZEDAD

* `Num 34:8` From mount Hor you shall designate your border to the entrance of Hamath, and the limits of the border shall be at *_Zedad_*.
* `Ezk 47:15` "And this shall be the border of the land toward the north side: from the Great Sea, the way of Hethlon, as men go to *_Zedad_*;

_2 verses containing ZEDAD_

== ZEDEKIAH

* `1Ki 22:11` And *_Zedekiah_* the son of Chenaanah made him horns of iron. And he said, "Thus says the LORD: 'With these you shall push the Syrians until you have consumed them.'"
* `1Ki 22:24` But *_Zedekiah_* the son of Chenaanah went near and smote Micaiah on the cheek and said, "Which way did the Spirit of the LORD go from me to speak to you?"
* `2Ki 24:17` And the king of Babylon made Mattaniah his father's brother king in his stead and changed his name to *_Zedekiah_*.
* `2Ki 24:18` *_Zedekiah_* was twenty-one years old when he began to reign, and he reigned eleven years in Jerusalem. And his mother's name was Hamutal, the daughter of Jeremiah of Libnah.
* `2Ki 24:20` For through the anger of the LORD it came to pass in Jerusalem and Judah until he had cast them out from his presence, that *_Zedekiah_* rebelled against the king of Babylon.
* `2Ki 25:2` And the city was besieged until the eleventh year of king *_Zedekiah_*.
* `2Ki 25:7` And they slew the sons of *_Zedekiah_* before his eyes and put out the eyes of *_Zedekiah_*, bound him with fetters of brass, and carried him to Babylon.
* `1Ch 3:15` And the sons of Josiah were the first-born Johanan, the second Jehoiakim, the third *_Zedekiah_*, the fourth Shallum.
* `1Ch 3:16` And the sons of Jehoiakim: Jeconiah his son and *_Zedekiah_* his son.
* `2Ch 18:10` And *_Zedekiah_* the son of Chenaanah had made him horns of iron and said, "Thus says the LORD: 'With these you shall push Syria until they are consumed.'"
* `2Ch 18:23` Then *_Zedekiah_* the son of Chenaanah came near and smote Micaiah upon the cheek and said, "Which way did the Spirit of the LORD go from me to speak to you?"
* `2Ch 36:10` And when the year had expired, king Nebuchadnezzar sent and brought him to Babylon with the precious vessels of the house of the LORD, and made *_Zedekiah_* his brother king over Judah and Jerusalem.
* `2Ch 36:11` *_Zedekiah_* was twenty-one years old when he began to reign, and reigned eleven years in Jerusalem.
* `Jer 1:3` It also came in the days of Jehoiakim the son of Josiah king of Judah, to the end of the eleventh year of *_Zedekiah_* the son of Josiah king of Judah, to the carrying away of Jerusalem captive in the fifth month.]
* `Jer 21:1` A word came to Jeremiah from the LORD when king *_Zedekiah_* sent to him Pashur the son of Melchiah and Zephaniah the son of Maaseiah the priest, saying,
* `Jer 21:3` Then Jeremiah said to them, "Thus you shall say to *_Zedekiah_*:
* `Jer 21:7` And afterward," says the LORD, "I will deliver *_Zedekiah_* king of Judah, his servants, and the people who are left in this city from the pestilence, from the sword, and from the famine, into the hand of Nebuchadnezzar king of Babylon, and into the hand of their enemies and into the hand of those who seek their life. And he shall smite them with the edge of the sword. He shall not spare them, neither have pity, nor have mercy."'
* `Jer 24:8` 'And as the bad figs, which cannot be eaten they are so bad,' surely thus says the LORD: 'So I will give up *_Zedekiah_* the king of Judah, his princes, the remnant of Jerusalem who remain in this land, and those who dwell in the land of Egypt.
* `Jer 27:3` And send them to the king of Edom, to the king of Moab, to the king of the Ammonites, to the king of Tyre, and to the king of Zidon by the hand of the messengers who come to Jerusalem to *_Zedekiah_* king of Judah.
* `Jer 27:12` I also spoke to *_Zedekiah_* king of Judah according to all these words, saying, "Bring your necks under the yoke of the king of Babylon, serve him and his people, and live.
* `Jer 28:1` And it came to pass the same year, in the beginning of the reign of *_Zedekiah_* king of Judah, in the fourth year, and in the fifth month, that Hananiah the son of Azur the prophet, who was of Gibeon, spoke to me in the house of the LORD in the presence of the priests and of all the people, saying,
* `Jer 29:3` By the hand of Elasah the son of Shaphan and Gemariah the son of Hilkiah (whom *_Zedekiah_* king of Judah sent to Babylon to Nebuchadnezzar king of Babylon), saying,
* `Jer 29:21` Thus says the LORD of hosts, the God of Israel, concerning Ahab the son of Kolaiah and concerning *_Zedekiah_* the son of Maaseiah, who prophesy a lie to you in my name: 'Behold, I will deliver them into the hand of Nebuchadnezzar king of Babylon, and he shall slay them before your eyes.
* `Jer 29:22` And concerning them a curse shall be taken up by all the captivity of Judah who are in Babylon, saying, "May the LORD make you like *_Zedekiah_* and like Ahab, whom the king of Babylon roasted in the fire,
* `Jer 32:1` A word came to Jeremiah from the LORD in the tenth year of *_Zedekiah_* king of Judah, which was the eighteenth year of Nebuchadnezzar.
* `Jer 32:3` For *_Zedekiah_* king of Judah had confined him, saying, "Why do you prophesy, and say, 'Thus says the LORD: "Behold, I will give this city into the hand of the king of Babylon, and he shall take it.
* `Jer 32:4` And *_Zedekiah_* king of Judah shall not escape from the hand of the Chaldeans, but shall surely be delivered into the hand of the king of Babylon and shall speak with him mouth to mouth, and his eyes shall behold his eyes.
* `Jer 32:5` And he shall lead *_Zedekiah_* to Babylon, and there he shall be until I visit him," says the LORD. "Though you fight with the Chaldeans, you shall not prosper"'?"
* `Jer 34:2` "Thus says the LORD, the God of Israel: 'Go and speak to *_Zedekiah_* king of Judah, and tell him, "Thus says the LORD: 'Behold, I will give this city into the hand of the king of Babylon, and he shall burn it with fire.
* `Jer 34:4` Yet hear the word of the LORD, O *_Zedekiah_* king of Judah. Thus says the LORD concerning you: 'You shall not die by the sword,
* `Jer 34:6` Then Jeremiah the prophet spoke all these words to *_Zedekiah_* king of Judah in Jerusalem
* `Jer 34:8` A word came to Jeremiah from the LORD after king *_Zedekiah_* had made a covenant with all the people who were at Jerusalem to proclaim liberty to them,
* `Jer 34:21` And *_Zedekiah_* king of Judah and his princes I will give into the hand of their enemies, into the hand of those who seek their life, and into the hand of the king of Babylon's army, which have gone up from you.
* `Jer 36:12` He went down into the king's house, into the scribe's chamber, and behold, all the princes sat there, even Elishama the scribe, Delaiah the son of Shemaiah, Elnathan the son of Achbor, Gemariah the son of Shaphan, *_Zedekiah_* the son of Hananiah, and all the princes.
* `Jer 37:1` And king *_Zedekiah_* the son of Josiah reigned instead of Coniah the son of Jehoiakim, whom Nebuchadnezzar king of Babylon made king in the land of Judah.
* `Jer 37:3` And *_Zedekiah_* the king sent Jehucal the son of Shelemiah and Zephaniah the son of Maaseiah the priest to the prophet Jeremiah, saying, "Pray now to the LORD our God for us."
* `Jer 37:17` Then *_Zedekiah_* the king sent and took him out. And the king asked him secretly in his house, and said, "Is there any word from the LORD?" And Jeremiah said, "There is." He said, "You shall be delivered into the hand of the king of Babylon."
* `Jer 37:18` Moreover, Jeremiah said to king *_Zedekiah_*, "In what have I offended against you, against your servants, or against this people that you have put me in prison?
* `Jer 37:21` Then *_Zedekiah_* the king commanded that they should commit Jeremiah into the court of the prison and that they should give him a piece of bread daily out of the baker's street until all the bread in the city was consumed. Thus Jeremiah remained in the court of the prison.
* `Jer 38:5` Then *_Zedekiah_* the king said, "Behold, he is in your hand, for the king is not he who can do anything against you."
* `Jer 38:14` Then *_Zedekiah_* the king sent and took Jeremiah the prophet to him into the third entry that is in the house of the LORD. And the king said to Jeremiah, "I will ask you a thing. Hide nothing from me."
* `Jer 38:15` Then Jeremiah said to *_Zedekiah_*, "If I declare it to you, will you not surely put me to death? And if I give you counsel, you will not listen to me."
* `Jer 38:16` So *_Zedekiah_* the king swore secretly to Jeremiah, saying, "As the LORD lives, who made us this soul, I will not put you to death, neither will I give you into the hand of these men who seek your life."
* `Jer 38:17` Then Jeremiah said to *_Zedekiah_*, "Thus says the LORD, the God of hosts, the God of Israel: 'If you will assuredly go forth to the king of Babylon's princes, then your soul shall live and this city shall not be burned with fire, and you shall live, along with your house.
* `Jer 38:19` And *_Zedekiah_* the king said to Jeremiah, "I am afraid of the Jews who have fallen to the Chaldeans, lest they deliver me into their hand and they mock me."
* `Jer 38:24` Then *_Zedekiah_* said to Jeremiah, "Let no man know of these words, and you shall not die.
* `Jer 39:1` In the ninth year of *_Zedekiah_* king of Judah, in the tenth month, Nebuchadnezzar king of Babylon and all his army came against Jerusalem, and they besieged it.
* `Jer 39:2` And in the eleventh year of *_Zedekiah_*, in the fourth month, on the ninth day of the month, the city was broken up.
* `Jer 39:4` And it came to pass, when *_Zedekiah_* the king of Judah and all the men of war saw them, they fled and went out of the city by night, by the way of the king's garden, by the gate between the two walls, and he went out the way of the plain.
* `Jer 39:5` But the Chaldeans' army pursued them and overtook *_Zedekiah_* in the plains of Jericho. And when they had taken him, they brought him to Nebuchadnezzar king of Babylon at Riblah in the land of Hamath, where he gave judgment upon him.
* `Jer 39:6` Then the king of Babylon slew the sons of *_Zedekiah_* in Riblah before his eyes. The king of Babylon also slew all the nobles of Judah.
* `Jer 39:7` Moreover, he put out *_Zedekiah_*'s eyes and bound him with chains to carry him to Babylon.
* `Jer 44:30` Thus says the LORD: 'Behold, I will give Pharaoh-hophra king of Egypt into the hand of his enemies, and into the hand of those who seek his life, as I gave *_Zedekiah_* king of Judah into the hand of Nebuchadnezzar king of Babylon, who was his enemy and sought his life.'"
* `Jer 49:34` [The word of the LORD that came to Jeremiah the prophet against Elam in the beginning of the reign of *_Zedekiah_* king of Judah.]
* `Jer 51:59` This is the word which Jeremiah the prophet commanded Seraiah the son of Neriah, the son of Maaseiah, when he went with *_Zedekiah_* the king of Judah into Babylon in the fourth year of his reign. And this Seraiah was a quiet prince.
* `Jer 52:1` *_Zedekiah_* was twenty-one years old when he began to reign, and he reigned eleven years in Jerusalem. And his mother's name was Hamutal, the daughter of Jeremiah of Libnah.
* `Jer 52:3` For through the anger of the LORD it came to pass in Jerusalem and Judah, until he had cast them out from his presence, that *_Zedekiah_* rebelled against the king of Babylon.
* `Jer 52:5` So the city was besieged until the eleventh year of king *_Zedekiah_*.
* `Jer 52:8` But the army of the Chaldeans pursued the king and overtook *_Zedekiah_* in the plains of Jericho, and all his army was scattered from him.
* `Jer 52:10` And the king of Babylon slew the sons of *_Zedekiah_* before his eyes. He also slew all the princes of Judah in Riblah.
* `Jer 52:11` Then he put out the eyes of *_Zedekiah_*. And the king of Babylon bound him in chains, carried him to Babylon, and put him in prison until the day of his death.

_61 verses containing ZEDEKIAH_

== ZEEB

* `Jdg 7:25` And they took two princes of the Midianites, Oreb and *_Zeeb_*. And they slew Oreb upon the rock of Oreb, and they slew *_Zeeb_* at the wine-press of *_Zeeb_*. They pursued Midian and brought the heads of Oreb and *_Zeeb_* to Gideon on the other side of the Jordan.
* `Jdg 8:3` God has delivered into your hands the princes of Midian, Oreb and *_Zeeb_*. And what was I able to do in comparison of you?" Then, when he had said that, their anger toward him abated.
* `Psa 83:11` Make their nobles like Oreb and like *_Zeeb_*, even all their princes like Zebah and like Zalmunna,

_3 verses containing ZEEB_

== ZELAH

* `Jsh 18:28` *_Zelah_*, Eleph, Jebusi (which is Jerusalem), Gibeath, and Kirjath; fourteen cities with their villages. This is the inheritance of the children of Benjamin according to their families.
* `2Sa 21:14` And the bones of Saul and Jonathan his son they buried in the country of Benjamin in *_Zelah_* in the sepulcher of Kish his father. And they performed all that the king commanded. And after that God was entreated for the land.

_2 verses containing ZELAH_

== ZELEK

* `2Sa 23:37` *_Zelek_* the Ammonite, Naharai the Beerothite (armor-bearer to Joab the son of Zeruiah),
* `1Ch 11:39` *_Zelek_* the Ammonite, Naharai the Berothite—the armor-bearer of Joab the son of Zeruiah,

_2 verses containing ZELEK_

== ZELOPHEHAD

* `Num 26:33` And *_Zelophehad_* the son of Hepher had no sons, but daughters. And the names of the daughters of *_Zelophehad_* were Mahlah, Noah, Hoglah, Milcah, and Tirzah.
* `Num 27:1` Then came the daughters of *_Zelophehad_*, the son of Hepher, the son of Gilead, the son of Machir, the son of Manasseh, of the families of Manasseh the son of Joseph. And these are the names of his daughters: Mahlah, Noah, Hoglah, Milcah, and Tirzah.
* `Num 27:7` "The daughters of *_Zelophehad_* speak what is right. You shall surely give them a possession of an inheritance among their father's brothers, and you shall cause the inheritance of their father to pass to them.
* `Num 36:2` And they said, "The LORD commanded my lord to give the land for an inheritance by lot to the children of Israel. And my lord was commanded by the LORD to give the inheritance of *_Zelophehad_* our brother to his daughters.
* `Num 36:6` This is the thing which the LORD commands concerning the daughters of *_Zelophehad_*, saying, 'Let them marry to whom they think best. Only to the family of the tribe of their father they shall marry.'
* `Num 36:10` Even as the LORD commanded Moses, so the daughters of *_Zelophehad_* did.
* `Num 36:11` For Mahlah, Tirzah, Hoglah, Milcah, and Noah, the daughters of *_Zelophehad_*, were married to their father's brothers' sons.
* `Jsh 17:3` But *_Zelophehad_*, the son of Hepher, the son of Gilead, the son of Machir, the son of Manasseh, had no sons, but daughters. And these are the names of his daughters: Mahlah, Noah, Hoglah, Milcah, and Tirzah.
* `1Ch 7:15` And Machir took for a wife the sister of Huppim and Shuppim, whose sister's name was Maachah), and the name of the second was *_Zelophehad_*, and *_Zelophehad_* had daughters.

_9 verses containing ZELOPHEHAD_

== ZELOTES

* `Luk 6:15` Matthew and Thomas, James the son of Alpheus, Simon called *_Zelotes_*,
* `Act 1:13` And when they had arrived, they went into the upper room where they were staying, namely, Peter, James, John, Andrew, Philip, Thomas, Bartholomew, Matthew, James the son of Alpheus, Simon *_Zelotes_*, and Judas the brother of James.

_2 verses containing ZELOTES_

== ZELZAH

* `1Sa 10:2` When you have departed from me today, you shall find two men by Rachel's sepulcher in the border of Benjamin at *_Zelzah_*, and they will say to you, 'The donkeys which you went to seek are found, and behold, your father has ceased caring for the donkeys and sorrows for you, saying, "What shall I do for my son?"'

_1 verse containing ZELZAH_

== ZEMARAIM

* `Jsh 18:22` Beth-arabah, *_Zemaraim_*, Beth-el,
* `2Ch 13:4` And Abijah stood upon mount *_Zemaraim_*, which is in the mountains of Ephraim, and said, "Hear me, Jeroboam and all Israel.

_2 verses containing ZEMARAIM_

== ZEMARITE

* `Gen 10:18` The Arvadite, the *_Zemarite_*, and the Hamathite. And afterward, the families of the Canaanites were dispersed.
* `1Ch 1:16` The Arvadite, the *_Zemarite_*, and the Hamathite.

_2 verses containing ZEMARITE_

== ZEMIRA

* `1Ch 7:8` And the sons of Becher: *_Zemira_*, Joash, Eliezer, Elioenai, Omri, Jerimoth, Abiah, Anathoth, and Alameth. All these are the sons of Becher.

_1 verse containing ZEMIRA_

== ZENAN

* `Jsh 15:37` *_Zenan_*, Hadashah, Migdalgad,

_1 verse containing ZENAN_

== ZENAS

* `Tit 3:13` Bring *_Zenas_* the lawyer and Apollos on their journey diligently so that nothing may be lacking for them.

_1 verse containing ZENAS_

== ZEPHANIAH

* `2Ki 25:18` And the captain of the guard took Seraiah the chief priest, *_Zephaniah_* the second priest, and the three keepers of the door.
* `1Ch 6:36` The son of Elkanah, the son of Joel, the son of Azariah, the son of *_Zephaniah_*,
* `Jer 21:1` A word came to Jeremiah from the LORD when king Zedekiah sent to him Pashur the son of Melchiah and *_Zephaniah_* the son of Maaseiah the priest, saying,
* `Jer 29:25` "Thus speaks the LORD of hosts, the God of Israel, saying, 'Because you have sent letters in your name to all the people who are at Jerusalem, to *_Zephaniah_* the son of Maaseiah the priest, and to all the priests, saying,
* `Jer 29:29` And *_Zephaniah_* the priest read this letter in the ears of Jeremiah the prophet.
* `Jer 37:3` And Zedekiah the king sent Jehucal the son of Shelemiah and *_Zephaniah_* the son of Maaseiah the priest to the prophet Jeremiah, saying, "Pray now to the LORD our God for us."
* `Jer 52:24` And the captain of the guard took Seraiah the chief priest, *_Zephaniah_* the second priest, and the three keepers of the door.
* `Zph 1:1` [The word of the LORD which came to *_Zephaniah_* the son of Cushi, the son of Gedaliah, the son of Amariah, the son of Hizkiah, in the days of Josiah the son of Amon, king of Judah.]
* `Zch 6:10` "Take from those who are in captivity, even from Heldai, from Tobijah, and from Jedaiah, who have come from Babylon, and come the same day and go into the house of Josiah the son of *_Zephaniah_*.
* `Zch 6:14` And the crowns shall be to Helem, to Tobijah, to Jedaiah, and to Hen the son of *_Zephaniah_* for a memorial in the temple of the LORD.

_10 verses containing ZEPHANIAH_

== ZEPHATH

* `Jdg 1:17` And Judah went with Simeon his brother, and they slew the Canaanites who inhabited *_Zephath_* and utterly destroyed it. And the name of the city was called Hormah.

_1 verse containing ZEPHATH_

== ZEPHATHATH

* `2Ch 14:10` Then Asa went out against him, and they set the battle in array in the valley of *_Zephathath_* at Mareshah.

_1 verse containing ZEPHATHATH_

== ZEPHI

* `1Ch 1:36` The sons of Eliphaz: Teman, Omar, *_Zephi_*, Gatam, Kenaz, Timna, and Amalek.

_1 verse containing ZEPHI_

== ZEPHO

* `Gen 36:11` And the sons of Eliphaz were, Teman, Omar, *_Zepho_*, Gatam, and Kenaz.
* `Gen 36:15` These are the chiefs of the sons of Esau. The sons of Eliphaz the first-born son of Esau: chief Teman, chief Omar, chief *_Zepho_*, chief Kenaz,

_2 verses containing ZEPHO_

== ZEPHON

* `Exo 14:2` "Speak to the children of Israel that they turn and encamp before Pi-hahiroth, between Migdol and the sea, over against Baal-*_zephon_*. Before it you shall encamp by the sea.
* `Exo 14:9` But the Egyptians pursued them (all the horses and chariots of Pharaoh, his horsemen, and his army) and overtook them encamping by the sea, beside Pi-hahiroth, before Baal-*_zephon_*.
* `Num 26:15` The children of Gad after their families: of *_Zephon_*, the family of the Zephonites; of Haggai, the family of the Haggites; of Shuni, the family of the Shunites;
* `Num 33:7` And they departed from Etham and turned back to Pi-hahiroth, which is before Baal-*_zephon_*, and they encamped before Migdol.

_4 verses containing ZEPHON_

== ZEPHONITES

* `Num 26:15` The children of Gad after their families: of Zephon, the family of the *_Zephonites_*; of Haggai, the family of the Haggites; of Shuni, the family of the Shunites;

_1 verse containing ZEPHONITES_

== ZER

* `Jsh 19:35` And the fortified cities are Ziddim, *_Zer_*, Hammath, Rakkath, Chinnereth,

_1 verse containing ZER_

== ZERA

* `1Ch 1:44` And when Bela was dead Jobab the son of *_Zera_* of Bozrah reigned in his stead.

_1 verse containing ZERA_

== ZERAH

* `Gen 36:13` And these are the sons of Reuel: Nahath, *_Zerah_*, Shammah, and Mizzah. These are the sons of Bashemath, Esau's wife.
* `Gen 36:17` And these are the sons of Reuel, Esau's son: chief Nahath, chief *_Zerah_*, chief Shammah, chief Mizzah. These are the chiefs, descendants of Reuel, in the land of Edom. These are the sons of Bashemath, Esau's wife.
* `Gen 36:33` And Bela died, and Jobab the son of *_Zerah_* of Bozrah reigned in his stead.
* `Gen 46:12` And the sons of Judah: Er, Onan, Shelah, Pharez, and *_Zerah_*, but Er and Onan died in the land of Canaan. And the sons of Pharez were Hezron and Hamul.
* `Num 26:13` Of *_Zerah_*, the family of the Zarhites; of Shaul, the family of the Shaulites.
* `Num 26:20` And these were the sons of Judah after their families: of Shelah, the family of the Shelanites; of Pharez, the family of the Pharezites; of *_Zerah_*, the family of the Zarhites.
* `Jsh 7:1` But the children of Israel committed a trespass in the accursed thing, for Achan the son of Carmi, the son of Zabdi, the son of *_Zerah_*, of the tribe of Judah, took some of the accursed things. And the anger of the LORD was kindled against the children of Israel.
* `Jsh 7:18` And he brought his household man by man, and Achan the son of Carmi, the son of Zabdi, the son of *_Zerah_*, of the tribe of Judah, was taken.
* `Jsh 7:24` And Joshua, and all Israel with him, took Achan the son of *_Zerah_*, the silver, the garment, the wedge of gold, his sons, his daughters, his oxen, his donkeys, his sheep, his tent, and all that he had. And they brought them to the valley of Achor.
* `Jsh 22:20` Did Achan the son of *_Zerah_* not commit a trespass in the accursed thing and wrath fall on all the congregation of Israel? And that man did not perish alone in his iniquity.'"
* `1Ch 1:37` The sons of Reuel: Nahath, *_Zerah_*, Shammah, and Mizzah.
* `1Ch 2:4` And Tamar his daughter-in-law bore him Pharez and *_Zerah_*. All the sons of Judah were five.
* `1Ch 2:6` And the sons of *_Zerah_*: Zimri, Ethan, Heman, Calcol, and Dara; five of them in all.
* `1Ch 4:24` The sons of Simeon were Nemuel, Jamin, Jarib, *_Zerah_*, and Shaul;
* `1Ch 6:21` Joah his son, Iddo his son, *_Zerah_* his son, and Jeaterai his son.
* `1Ch 6:41` The son of Ethni, the son of *_Zerah_*, the son of Adaiah,
* `1Ch 9:6` And of the sons of *_Zerah_*: Jeuel and their brothers, six hundred and ninety.
* `2Ch 14:9` And *_Zerah_* the Cushite came out against them with a host of one million, and also three hundred chariots, and came to Mareshah.
* `Neh 11:24` And Pethahiah the son of Meshezabeel, of the children of *_Zerah_* the son of Judah, was at the king's hand in all matters concerning the people.

_19 verses containing ZERAH_

== ZERAHIAH

* `1Ch 6:6` Uzzi begot *_Zerahiah_*, *_Zerahiah_* begot Meraioth,
* `1Ch 6:51` Bukki his son, Uzzi his son, *_Zerahiah_* his son,
* `Ezr 7:4` The son of *_Zerahiah_*, the son of Uzzi, the son of Bukki,
* `Ezr 8:4` Of the sons of Pahath-moab: Elihoenai the son of *_Zerahiah_*, and with him two hundred males.

_4 verses containing ZERAHIAH_

== ZEREATHITES

* `1Ch 2:53` And the families of Kirjath-jearim: the Ithrites, the Puhites, the Shumathites, and the Mishraites. From them came the *_Zereathites_* and the Eshtaulites.

_1 verse containing ZEREATHITES_

== ZERED

* `Deu 2:13` 'Now rise,' I said, 'and pass over the brook *_Zered_*.' And we went over the brook *_Zered_*.
* `Deu 2:14` And the time in which we came from Kadesh-barnea, until we passed the brook *_Zered_*, was thirty-eight years, until all the generation of the men of war were wasted from among the host, as the LORD swore to them.

_2 verses containing ZERED_

== ZEREDA

* `1Ki 11:26` And Jeroboam the son of Nebat, an Ephrathite of *_Zereda_*, Solomon's servant, whose mother's name was Zeruah, a widow woman, even he raised his hand against the king.

_1 verse containing ZEREDA_

== ZEREDATHAH

* `2Ch 4:17` In the plain of the Jordan the king cast them, in the clay ground between Succoth and *_Zeredathah_*.

_1 verse containing ZEREDATHAH_

== ZEREROTH

* `Jdg 7:22` And the three hundred blew the trumpets, and the LORD set every man's sword against his fellow, even throughout all the host. And the host fled to Beth-shittah in *_Zereroth_* and to the border of Abel-meholah near Tabbath.

_1 verse containing ZEREROTH_

== ZERESH

* `Est 5:10` Nevertheless, Haman refrained himself. And when he came home, he sent and called for his friends and *_Zeresh_* his wife.
* `Est 5:14` Then *_Zeresh_* his wife and all his friends said to him, "Let a gallows be made fifty cubits high, and tomorrow speak to the king so that Mordecai may be hanged upon it. Then go in merrily with the king to the banquet." And the thing pleased Haman, and he caused the gallows to be made.
* `Est 6:13` And Haman told *_Zeresh_* his wife and all his friends everything that had befallen him. Then his wise men and *_Zeresh_* his wife said to him, "If Mordecai, before whom you have begun to fall, is of Jewish descent, you will not prevail against him, but will surely fall before him."

_3 verses containing ZERESH_

== ZERETH

* `1Ch 4:7` And the sons of Helah were *_Zereth_*, Jezoar, and Ethnan.

_1 verse containing ZERETH_

== ZERI

* `1Ch 25:3` Of Jeduthun, the sons of Jeduthun: Gedaliah, *_Zeri_*, Jeshaiah, Hashabiah, and Mattithiah, six, under the hands of their father Jeduthun who prophesied with a harp to give thanks and to praise the LORD.

_1 verse containing ZERI_

== ZEROR

* `1Sa 9:1` Now there was a man of Benjamin whose name was Kish, the son of Abiel, the son of *_Zeror_*, the son of Bechorath, the son of Aphiah, a Benjaminite, a mighty man of power.

_1 verse containing ZEROR_

== ZERUAH

* `1Ki 11:26` And Jeroboam the son of Nebat, an Ephrathite of Zereda, Solomon's servant, whose mother's name was *_Zeruah_*, a widow woman, even he raised his hand against the king.

_1 verse containing ZERUAH_

== ZERUBBABEL

* `1Ch 3:19` And the sons of Pedaiah were *_Zerubbabel_* and Shimei. And the sons of *_Zerubbabel_*: Meshullam and Hananiah, and Shelomith was their sister;
* `Ezr 2:2` Who came with *_Zerubbabel_*: Jeshua, Nehemiah, Seraiah, Reelaiah, Mordecai, Bilshan, Mizpar, Bigvai, Rehum, and Baanah. The number of the men of the people of Israel:
* `Ezr 3:2` Then Jeshua the son of Jozadak stood up, with his brothers the priests, *_Zerubbabel_* the son of Shealtiel, and his brothers, and built the altar of the God of Israel to offer burnt-offerings on it as it is written in the law of Moses the man of God.
* `Ezr 3:8` Now in the second year of their coming to the house of God at Jerusalem, in the second month, *_Zerubbabel_* the son of Shealtiel, Jeshua the son of Jozadak, the remnant of their brothers the priests and the Levites, and all those who had come out of the captivity to Jerusalem, began the work and appointed the Levites, from twenty years old and upward, to set forward the work of the house of the LORD.
* `Ezr 4:2` They came to *_Zerubbabel_* and to the chief of the fathers, and said to them, "Let us build with you, for we seek your God, as you do, and we have sacrificed to him since the days of Esar-haddon king of Assur, who brought us up here."
* `Ezr 4:3` But *_Zerubbabel_*, Jeshua, and the rest of the chief of the fathers of Israel, said to them, "You have nothing to do with us to build a house to our God. But we ourselves together will build to the LORD God of Israel, as king Cyrus the king of Persia has commanded us."
* `Ezr 5:2` Then *_Zerubbabel_* the son of Shealtiel and Jeshua the son of Jozadak rose up and began to build the house of God which is at Jerusalem. And with them were the prophets of God helping them.
* `Neh 7:7` Who came with *_Zerubbabel_*, Jeshua, Nehemiah, Azariah, Raamiah, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, and Baanah. The number of the men of the people of Israel was this:
* `Neh 12:1` Now these are the priests and the Levites who went up with *_Zerubbabel_* the son of Shealtiel and Jeshua: Seraiah, Jeremiah, Ezra,
* `Neh 12:47` And all Israel in the days of *_Zerubbabel_* and in the days of Nehemiah gave the portions for the singers and the gatekeepers, every day his portion. And they sanctified holy things to the Levites, and the Levites sanctified them to the children of Aaron.
* `Hag 1:1` In the second year of Darius the king, in the sixth month, on the first day of the month, the word of the LORD came by Haggai the prophet to *_Zerubbabel_* the son of Shealtiel, governor of Judah, and to Joshua the son of Josedech, the high priest, saying,
* `Hag 1:12` Then *_Zerubbabel_* the son of Shealtiel and Joshua the son of Josedech, the high priest, with all the remnant of the people, obeyed the voice of the LORD their God and the words of Haggai the prophet, as the LORD their God had sent him, and the people feared before the LORD.
* `Hag 1:14` And the LORD stirred up the spirit of *_Zerubbabel_* the son of Shealtiel, governor of Judah, and the spirit of Joshua the son of Josedech, the high priest, and the spirit of all the remnant of the people, and they came and performed work in the house of the LORD of hosts, their God,
* `Hag 2:2` "Speak now to *_Zerubbabel_* the son of Shealtiel, governor of Judah, and to Joshua the son of Josedech the high priest, and to the remnant of the people, saying,
* `Hag 2:4` Yet now be strong, O *_Zerubbabel_*,' says the LORD. 'Be strong, O Joshua, son of Josedech, the high priest. Be strong, all you people of the land,' says the LORD. 'Work, for I am with you,' says the LORD of hosts.
* `Hag 2:21` "Speak to *_Zerubbabel_*, governor of Judah, saying, 'I will shake the heavens and the earth.
* `Hag 2:23` In that day,' says the LORD of hosts, 'I will take you, O *_Zerubbabel_*, my servant, the son of Shealtiel,' says the LORD, 'and will make you as a signet, for I have chosen you,' says the LORD of hosts."
* `Zch 4:6` Then he answered and spoke to me, saying, "This is the word of the LORD to *_Zerubbabel_*, saying, 'Not by might, nor by power, but by my Spirit,' says the LORD of hosts.
* `Zch 4:7` 'Who are you, O great mountain? Before *_Zerubbabel_* you shall become a plain. And he shall bring forth its head-stone with shoutings, crying, "Grace, grace to it."'"
* `Zch 4:9` "The hands of *_Zerubbabel_* have laid the foundation of this house. His hands shall also finish it. And you shall know that the LORD of hosts has sent me to you.
* `Zch 4:10` For who has despised the day of small things? For they shall rejoice and see the plummet in the hand of *_Zerubbabel_*. These seven are the eyes of the LORD, which run to and fro through the whole earth."
* `Mth 1:12` And after they were brought to Babylon, Jechoniah begot Shealtiel, Shealtiel begot *_Zerubbabel_*,
* `Mth 1:13` *_Zerubbabel_* begot Abiud, Abiud begot Eliakim, Eliakim begot Azor,
* `Luk 3:27` Who was the son of Joanan, who was the son of Rhesa, who was the son of *_Zerubbabel_*, who was the son of Shealtiel, who was the son of Neri,

_24 verses containing ZERUBBABEL_

== ZERUIAH

* `1Sa 26:6` Then David answered and said to Ahimelech the Hittite and to Abishai the son of *_Zeruiah_*, brother to Joab, saying, "Who will go down with me to Saul in the camp?" And Abishai said, "I will go down with you."
* `2Sa 2:13` And Joab the son of *_Zeruiah_* and the servants of David went out and met together by the pool of Gibeon. And they sat down, one on one side of the pool and the other on the other side of the pool.
* `2Sa 2:18` And there were three sons of *_Zeruiah_* there: Joab, Abishai, and Asahel. And Asahel was as light of foot as a wild gazelle.
* `2Sa 3:39` And I am this day weak, though anointed king. And these men, the sons of *_Zeruiah_*, are too hard for me. The LORD shall reward the doer of evil according to his wickedness."
* `2Sa 8:16` And Joab the son of *_Zeruiah_* was over the host, Jehoshaphat the son of Ahilud was recorder,
* `2Sa 14:1` Now Joab the son of *_Zeruiah_* perceived that the king's heart was toward Absalom.
* `2Sa 16:9` Then Abishai the son of *_Zeruiah_* said to the king, "Why should this dead dog curse my lord the king? Let me go over, I pray you, and take off his head."
* `2Sa 16:10` And the king said, "What have I to do with you, you sons of *_Zeruiah_*? So let him curse, because the LORD has said to him, 'Curse David.' Who shall then say, 'Why have you done so?'"
* `2Sa 17:25` And Absalom made Amasa captain of the host instead of Joab (which Amasa was a man's son, whose name was Ithra, an Israelite, who went in to Abigail the daughter of Nahash, sister to *_Zeruiah_*, Joab's mother).
* `2Sa 18:2` And David sent forth a third part of the people under the hand of Joab, a third part under the hand of Abishai the son of *_Zeruiah_* (Joab's brother), and a third part under the hand of Ittai the Gittite. And the king said to the people, "I myself will surely go forth with you also."
* `2Sa 19:21` But Abishai the son of *_Zeruiah_* answered and said, "Shall Shimei not be put to death for this because he cursed the LORD'S anointed?"
* `2Sa 19:22` And David said, "What have I to do with you, you sons of *_Zeruiah_*, that you should this day be adversaries to me? Shall any man be put to death this day in Israel? For do I not know that I am this day king over Israel?"
* `2Sa 21:17` But Abishai the son of *_Zeruiah_* helped him, and smote the Philistine and killed him. Then the men of David swore to him, saying, "You shall no longer go out with us to battle so that you may not extinguish the light of Israel."
* `2Sa 23:18` And Abishai, the brother of Joab, the son of *_Zeruiah_*, was chief among three. And he lifted up his spear against three hundred, slew them, and had the name among three.
* `2Sa 23:37` Zelek the Ammonite, Naharai the Beerothite (armor-bearer to Joab the son of *_Zeruiah_*),
* `1Ki 1:7` And he conferred with Joab the son of *_Zeruiah_* and with Abiathar the priest. And following Adonijah, they helped him.
* `1Ki 2:5` "Moreover, you also know what Joab the son of *_Zeruiah_* did to me and what he did to the two captains of the armies of Israel, to Abner the son of Ner, and to Amasa the son of Jether, whom he slew, shedding the blood of war in peace and putting the blood of war upon his girdle that was around his loins and in his shoes that were on his feet.
* `1Ki 2:22` And king Solomon answered and said to his mother, "And why do you ask Abishag the Shunamite for Adonijah? Ask for him the kingdom also, for he is my elder brother, even for him, and for Abiathar the priest, and for Joab the son of *_Zeruiah_*."
* `1Ch 2:16` Whose sisters were *_Zeruiah_* and Abigail. And the three sons of *_Zeruiah_*: Abishai, Joab, and Asahel.
* `1Ch 11:6` And David said, "Whoever smites the Jebusites first shall be chief and captain." So Joab the son of *_Zeruiah_* went up first and was chief.
* `1Ch 11:39` Zelek the Ammonite, Naharai the Berothite—the armor-bearer of Joab the son of *_Zeruiah_*,
* `1Ch 18:12` Moreover, Abishai the son of *_Zeruiah_* slew of the Edomites in the valley of salt eighteen thousand.
* `1Ch 18:15` And Joab the son of *_Zeruiah_* was over the host, Jehoshaphat the son of Ahilud was recorder,
* `1Ch 26:28` And all that Samuel the seer, Saul the son of Kish, Abner the son of Ner, and Joab the son of *_Zeruiah_* had dedicated, and whoever had dedicated anything, it was under the hand of Shelomith and of his brothers.
* `1Ch 27:24` Joab the son of *_Zeruiah_* began to number, but he did not finish, for wrath came against Israel because of this, neither was the number put in the account of the chronicles of king David.

_25 verses containing ZERUIAH_

