= ZETHAM - ZUZIMS
:toc:

== ZETHAM

* `1Ch 23:8` The sons of Laadan: the chief was Jehiel, *_Zetham_*, and Joel, three.
* `1Ch 26:22` The sons of Jehieli: *_Zetham_* and Joel his brother, who were over the treasures of the house of the LORD.

_2 verses containing ZETHAM_

== ZETHAN

* `1Ch 7:10` The son of Jediael: Bilhan. And the sons of Bilhan: Jeush, Benjamin, Ehud, Chenaanah, *_Zethan_*, Tarshish, and Ahishahar.

_1 verse containing ZETHAN_

== ZETHAR

* `Est 1:10` On the seventh day, when the heart of the king was merry with wine, he commanded Mehuman, Biztha, Harbona, Bigtha, Abagtha, *_Zethar_*, and Carcas, the seven chamberlains who served in the presence of Ahasuerus the king,

_1 verse containing ZETHAR_

== ZEUS

* `Act 14:12` And they called Barnabas, "*_Zeus_*," and Paul, "Hermes," because he was the chief speaker.
* `Act 14:13` Then the priest of *_Zeus_* who was before their city brought oxen and garlands to the gates and would have done sacrifice with the people,

_2 verses containing ZEUS_

== ZIA

* `1Ch 5:13` And their brothers of the house of their fathers were Michael, Meshullam, Sheba, Jorai, Jachan, *_Zia_*, and Heber, seven.

_1 verse containing ZIA_

== ZIBA

* `2Sa 9:2` And there was from the house of Saul a servant whose name was *_Ziba_*. And when they had called him to David, the king said to him, "Are you *_Ziba_*?" And he said, "Your servant is he."
* `2Sa 9:3` And the king said, "Is there not anyone left from the house of Saul to whom I may show the kindness of God?" And *_Ziba_* said to the king, "Jonathan still has a son who is lame in his feet."
* `2Sa 9:4` And the king said to him, "Where is he?" And *_Ziba_* said to the king, "Behold, he is in the house of Machir, the son of Ammiel, in Lo-debar."
* `2Sa 9:9` Then the king called to *_Ziba_*, Saul's servant, and said to him, "I have given to your master's son all that pertained to Saul and to all his house.
* `2Sa 9:10` Therefore, you, your sons, and your servants shall till the land for him, and you shall bring in the fruits so that your master's son may have food to eat. But Mephibosheth your master's son shall always eat bread at my table." Now *_Ziba_* had fifteen sons and twenty servants.
* `2Sa 9:11` Then *_Ziba_* said to the king, "According to all that my lord the king has commanded his servant, so your servant shall do." "As for Mephibosheth," the king said, "he shall eat at my table as one of the king's sons."
* `2Sa 9:12` And Mephibosheth had a young son whose name was Micah. And all who dwelt in the house of *_Ziba_* were servants to Mephibosheth.
* `2Sa 16:1` And when David was a little past the top of the hill, behold, *_Ziba_* the servant of Mephibosheth met him, with a couple of donkeys saddled and upon them two hundred loaves of bread, one hundred bunches of raisins, one hundred of summer fruits, and a bottle of wine.
* `2Sa 16:2` And the king said to *_Ziba_*, "What do you mean by these?" And *_Ziba_* said, "The donkeys are for the king's household to ride on, the bread and summer fruit for the young men to eat, and the wine so that those who are faint in the wilderness may drink."
* `2Sa 16:3` And the king said, "And where is your master's son?" And *_Ziba_* said to the king, "Behold, he abides at Jerusalem, for he said, 'Today the house of Israel shall restore to me the kingdom of my father.'"
* `2Sa 16:4` Then the king said to *_Ziba_*, "Behold, all that pertained to Mephibosheth is yours." And *_Ziba_* said, "I humbly implore you that I may find grace in your sight, my lord, O king."
* `2Sa 19:17` And there were one thousand men from Benjamin with him, along with *_Ziba_* the servant of the house of Saul and his fifteen sons and his twenty servants. And they went over the Jordan before the king.
* `2Sa 19:29` And the king said to him, "Why do you speak anymore of your matters? I have said, 'You and *_Ziba_* divide the land.'"

_13 verses containing ZIBA_

== ZIBEON

* `Gen 36:2` Esau took his wives from the daughters of Canaan: Adah the daughter of Elon the Hittite; Aholibamah the daughter of Anah, the daughter of *_Zibeon_* the Hivite;
* `Gen 36:14` And these are the sons of Aholibamah, the daughter of Anah, the daughter of *_Zibeon_*, Esau's wife, and she bore to Esau, Jeush, Jaalam, and Korah.
* `Gen 36:20` These are the sons of Seir the Horite who inhabited the land: Lotan, Shobal, *_Zibeon_*, Anah,
* `Gen 36:24` And these are the children of *_Zibeon_*: Ajah and Anah. This was that Anah who found the mules in the wilderness as he fed the donkeys of *_Zibeon_* his father.
* `Gen 36:29` These are the chiefs, descendants of the Horites: chief Lotan, chief Shobal, chief *_Zibeon_*, chief Anah,
* `1Ch 1:38` And the sons of Seir: Lotan, Shobal, *_Zibeon_*, Anah, Dishon, Ezar, and Dishan.
* `1Ch 1:40` The sons of Shobal: Alian, Manahath, Ebal, Shephi, and Onam. And the sons of *_Zibeon_*: Aiah and Anah.

_7 verses containing ZIBEON_

== ZIBIA

* `1Ch 8:9` And he begot by Hodesh his wife: Jobab, *_Zibia_*, Mesha, Malcham,

_1 verse containing ZIBIA_

== ZIBIAH

* `2Ki 12:1` In the seventh year of Jehu, Jehoash began to reign, and he reigned for forty years in Jerusalem. And his mother's name was *_Zibiah_* of Beer-sheba.
* `2Ch 24:1` Joash was seven years old when he began to reign, and he reigned forty years in Jerusalem. His mother's name was *_Zibiah_* of Beer-sheba.

_2 verses containing ZIBIAH_

== ZICHRI

* `Exo 6:21` And the sons of Izhar: Korah, Nepheg, and *_Zichri_*.
* `1Ch 8:19` And Jakim, *_Zichri_*, Zabdi,
* `1Ch 8:23` Abdon, *_Zichri_*, Hanan,
* `1Ch 8:27` Jaresiah, Eliah, and *_Zichri_* were the sons of Jeroham.
* `1Ch 9:15` And Bakbakkar, Heresh, Galal, and Mattaniah the son of Micah, the son of *_Zichri_*, the son of Asaph;
* `1Ch 26:25` And his brothers, by Eliezer, were Rehabiah his son, Jeshaiah his son, Joram his son, *_Zichri_* his son, and Shelomith his son.
* `1Ch 27:16` Furthermore, over the tribes of Israel, the ruler of the Reubenites was Eliezer the son of *_Zichri_*; of the Simeonites, Shephatiah the son of Maachah;
* `2Ch 17:16` And next to him was Amasiah the son of *_Zichri_*, who willingly offered himself to the LORD, and with him two hundred thousand mighty men of valor.
* `2Ch 23:1` And in the seventh year Jehoiada strengthened himself and took the captains of hundreds, even Azariah the son of Jeroham, Ishmael the son of Jehohanan, Azariah the son of Obed, Maaseiah the son of Adaiah, and Elishaphat the son of *_Zichri_*, into covenant with him.
* `2Ch 28:7` And *_Zichri_*, a mighty man of Ephraim, slew Maaseiah the king's son, Azrikam the governor of the house, and Elkanah who was next to the king.
* `Neh 11:9` And Joel the son of *_Zichri_* was their overseer. And Judah the son of Senuah was second over the city.
* `Neh 12:17` Of Abijah, *_Zichri_*; of Miniamin, of Moadiah, Piltai;

_12 verses containing ZICHRI_

== ZIDDIM

* `Jsh 19:35` And the fortified cities are *_Ziddim_*, Zer, Hammath, Rakkath, Chinnereth,

_1 verse containing ZIDDIM_

== ZIDKIJAH

* `Neh 10:1` Now those who sealed were Nehemiah (the Tirshatha and the son of Hachaliah), *_Zidkijah_*,

_1 verse containing ZIDKIJAH_

== ZIDON

* `Gen 49:13` "Zebulun shall dwell at the haven of the sea, and he shall be for a haven of ships. And his border shall be to *_Zidon_*.
* `Jsh 11:8` And the LORD delivered them into the hand of Israel, who smote them and chased them to great *_Zidon_*, to Misrephoth-maim, and to the valley of Mizpeh eastward. And they smote them until they left to them no one remaining.
* `Jsh 19:28` And Hebron, Rehob, Hammon, and Kanah, even to great *_Zidon_*;
* `Jdg 1:31` Asher did not expel the inhabitants of Accho nor the inhabitants of *_Zidon_*, of Ahlab, of Achzib, of Helbah, of Aphik, or of Rehob,
* `Jdg 10:6` And the children of Israel did evil again in the sight of the LORD and served Baalim, Ashtaroth, the gods of Syria, the gods of *_Zidon_*, the gods of Moab, the gods of the children of Ammon, and the gods of the Philistines, and forsook the LORD and did not serve him.
* `Jdg 18:28` And there was no deliverer because it was far from *_Zidon_* and they had no business with any man. And it was in the valley that lies by Beth-rehob. And they built a city and dwelt in it.
* `2Sa 24:6` Then they came to Gilead and to the land of Tahtim-hodshi. And they came to Dan-jaan and around to *_Zidon_*,
* `1Ki 17:9` "Arise, go to Zarephath, which belongs to *_Zidon_*, and dwell there. Behold, I have commanded a widow woman there to sustain you."
* `1Ch 1:13` And Canaan begot *_Zidon_* his first-born and Heth,
* `Ezr 3:7` They gave money also to the masons and to the carpenters, and provisions, drink, and oil to those of *_Zidon_* and to those of Tyre, to bring cedar trees from Lebanon to the sea of Joppa, according to the grant that they had from Cyrus king of Persia.
* `Isa 23:2` Be still, you inhabitants of the coastland, you whom the merchants of *_Zidon_*, who pass over the sea, have replenished.
* `Isa 23:4` Be ashamed, O *_Zidon_*, for the sea has spoken, even the strength of the sea, saying, "I do not travail nor bring forth children, neither do I nourish young men nor bring up virgins."
* `Isa 23:12` And he said, "You shall no longer rejoice, O oppressed virgin, daughter of *_Zidon_*. Arise, pass over to Chittim. You shall have no rest there also."
* `Jer 25:22` All the kings of Tyre, all the kings of *_Zidon_*, the kings of the coastlands which are beyond the sea;
* `Jer 27:3` And send them to the king of Edom, to the king of Moab, to the king of the Ammonites, to the king of Tyre, and to the king of *_Zidon_* by the hand of the messengers who come to Jerusalem to Zedekiah king of Judah.
* `Jer 47:4` Because of the day that comes to lay waste all the Philistines, and to cut off from Tyre and *_Zidon_* every helper who remains. For the LORD will lay waste the Philistines, the remnant of the country of Caphtor.
* `Ezk 27:8` The inhabitants of *_Zidon_* and Arvad were your mariners. Your wise men, O Tyre, who were in you, were your pilots.
* `Ezk 28:21` "Son of man, set your face against *_Zidon_* and prophesy against it,
* `Ezk 28:22` And say, 'Thus says the Lord GOD: "Behold, I am against you, O *_Zidon_*, and I will be glorified in the midst of you. And they shall know that I am the LORD when I have executed judgments in her and have been sanctified in her.
* `Joe 3:4` "And what do you even have to do with me, O Tyre, *_Zidon_*, and all the regions of Palestine? Will you render me a recompense? And if you recompense me, swiftly and speedily I will return your recompense upon your own head,
* `Zch 9:2` And also Hamath, which borders by it, and Tyre and *_Zidon_*, because they are very wise.

_21 verses containing ZIDON_

== ZIDONIANS

* `Jdg 10:12` Also the *_Zidonians_*, the Amalekites, and the Maonites oppressed you, and you cried to me, and I delivered you out of their hand.
* `Jdg 18:7` Then the five men departed and came to Laish and saw the people who were in it, how they dwelt carelessly after the manner of the *_Zidonians_*, quiet and secure. And there was no magistrate in the land who might put them to shame in anything. And they were far from the *_Zidonians_* and had no business with any man.
* `1Ki 11:1` But king Solomon loved many foreign women, together with the daughter of Pharaoh, women of the Moabites, Ammonites, Edomites, *_Zidonians_*, and Hittites,
* `1Ki 11:5` For Solomon went after Ashtoreth the goddess of the *_Zidonians_* and after Milcom the abomination of the Ammonites.
* `1Ki 11:33` Because they have forsaken me and have worshiped Ashtoreth the goddess of the *_Zidonians_*, Chemosh the god of the Moabites, and Milcom the god of the children of Ammon, and have not walked in my ways to do that which is right in my eyes and to keep my statutes and my judgments, as David his father did.
* `1Ki 16:31` And it came to pass, as if it had been a light thing for him to walk in the sins of Jeroboam the son of Nebat, that he took for a wife Jezebel the daughter of Ethbaal king of the *_Zidonians_*, and went and served Baal and worshiped him.
* `2Ki 23:13` And the high places that were before Jerusalem, which were on the right hand of the mountain of corruption, which Solomon the king of Israel had built for Ashtoreth the abomination of the *_Zidonians_*, for Chemosh the abomination of the Moabites, and for Milcom the abomination of the children of Ammon, the king defiled.
* `1Ch 22:4` And also cedar trees in abundance, for the *_Zidonians_* and those of Tyre brought much cedar wood to David.
* `Ezk 32:30` "There are the princes of the north—all of them and all the *_Zidonians_*—who have gone down with the slain. With their terror they are ashamed of their might, and they lie uncircumcised with those who are slain by the sword, and bear their shame with those who go down to the pit.

_9 verses containing ZIDONIANS_

== ZIF

* `1Ki 6:1` And it came to pass in the four hundred and eightieth year after the children of Israel had come out of the land of Egypt, in the fourth year of Solomon's reign over Israel, in the month of *_Zif_*, which is the second month, that he began to build the house of the LORD.
* `1Ki 6:37` The foundation of the house of the LORD was laid in the fourth year, in the month of *_Zif_*.

_2 verses containing ZIF_

== ZIGLAG

* `Jsh 15:31` *_Ziglag_*, Madmannah, Sansannah,

_1 verse containing ZIGLAG_

== ZIHA

* `Ezr 2:43` The Nethinims: the children of *_Ziha_*, the children of Hasupha, the children of Tabbaoth,
* `Neh 7:46` The Nethinims: the children of *_Ziha_*, the children of Hashupha, the children of Tabbaoth,
* `Neh 11:21` But the Nethinims dwelt in Ophel. And *_Ziha_* and Gispa were over the Nethinims.

_3 verses containing ZIHA_

== ZIKLAG

* `Jsh 19:5` *_Ziklag_*, Beth-marcaboth, Hazar-susah,
* `1Sa 27:6` Then Achish gave him *_Ziklag_* that day. Therefore, *_Ziklag_* pertains to the kings of Judah to this day.
* `1Sa 30:1` And it came to pass when David and his men had come to *_Ziklag_* on the third day, that the Amalekites had invaded the south and *_Ziklag_*, had smitten *_Ziklag_* and burned it with fire,
* `1Sa 30:14` We made an invasion upon the south of the Cherethites, and upon the land which belongs to Judah, and upon the south of Caleb, and we burned *_Ziklag_* with fire."
* `1Sa 30:26` And when David came to *_Ziklag_*, he sent some of the plunder to the elders of Judah, even to his friends, saying, "Behold, a present for you from the plunder of the enemies of the LORD"—
* `2Sa 1:1` Now it came to pass after the death of Saul when David had returned from the slaughter of the Amalekites and David had stayed two days in *_Ziklag_*,
* `2Sa 4:10` When someone told me, saying, 'Behold, Saul is dead,' (thinking to have brought good tidings), I took hold of him and slew him in *_Ziklag_*, which was the reward I gave him for his tidings.
* `1Ch 4:30` At Bethuel, at Hormah, at *_Ziklag_*,
* `1Ch 12:1` Now these are those who came to David at *_Ziklag_* while he still kept away from before Saul the son of Kish. And they were among the mighty men, helpers of the war.
* `1Ch 12:20` And as he went to *_Ziklag_*, there fell to him from Manasseh, Adnah, Jozabad, Jediael, Michael, Jozabad, Elihu, and Zilthai—captains of the thousands who were of Manasseh.
* `Neh 11:28` At *_Ziklag_*, at Mekonah and in its villages,

_11 verses containing ZIKLAG_

== ZILLAH

* `Gen 4:19` And Lamech took for himself two wives: the name of one was Adah and the name of the other *_Zillah_*.
* `Gen 4:22` And *_Zillah_*, she also bore Tubalcain, a forger of every cutting instrument of brass and iron. And the sister of Tubalcain was Naamah.
* `Gen 4:23` And Lamech said to his wives, "Adah and *_Zillah_*, hear my voice. Wives of Lamech, listen to my speech. For I have slain a man for wounding me, even a young man for hurting me.

_3 verses containing ZILLAH_

== ZILPAH

* `Gen 29:24` And Laban gave *_Zilpah_* his servant to his daughter Leah as a servant.
* `Gen 30:9` When Leah saw that she had ceased bearing, she took *_Zilpah_* her servant and gave her to Jacob for a wife.
* `Gen 30:10` And *_Zilpah_*, Leah's servant, bore Jacob a son.
* `Gen 30:12` And *_Zilpah_*, Leah's servant, bore Jacob a second son.
* `Gen 35:26` And the sons of *_Zilpah_*, Leah's servant: Gad and Asher. These are the sons of Jacob who were born to him in Padan-aram.
* `Gen 37:2` These are the generations of Jacob. Joseph being seventeen years old was feeding the flock with his brothers, and the boy was with the sons of Bilhah and with the sons of *_Zilpah_*, his father's wives. And Joseph brought to his father their evil report.
* `Gen 46:18` These are the sons of *_Zilpah_*, whom Laban gave to Leah his daughter. And these she bore to Jacob, even sixteen souls.

_7 verses containing ZILPAH_

== ZILTHAI

* `1Ch 8:20` Elienai, *_Zilthai_*, Eliel,
* `1Ch 12:20` And as he went to Ziklag, there fell to him from Manasseh, Adnah, Jozabad, Jediael, Michael, Jozabad, Elihu, and *_Zilthai_*—captains of the thousands who were of Manasseh.

_2 verses containing ZILTHAI_

== ZIMMAH

* `1Ch 6:20` Of Gershom: Libni his son, Jahath his son, *_Zimmah_* his son,
* `1Ch 6:42` The son of Ethan, the son of *_Zimmah_*, the son of Shimei,
* `2Ch 29:12` Then the Levites arose: Mahath the son of Amasai and Joel the son of Azariah, of the sons of the Kohathites; and of the sons of Merari: Kish the son of Abdi and Azariah the son of Jehalelel; and of the Gershonites: Joah the son of *_Zimmah_* and Eden the son of Joah;

_3 verses containing ZIMMAH_

== ZIMRAN

* `Gen 25:2` And she bore him *_Zimran_*, Jokshan, Medan, Midian, Ishbak, and Shuah.
* `1Ch 1:32` Now the sons of Keturah, Abraham's concubine: she bore *_Zimran_*, Jokshan, Medan, Midian, Ishbak, and Shuah. And the sons of Jokshan: Sheba and Dedan.

_2 verses containing ZIMRAN_

== ZIMRI

* `Num 25:14` Now the name of the slain Israelite, who was slain with the Midianitish woman, was *_Zimri_*, the son of Salu, a prince of a chief house among the Simeonites.
* `1Ki 16:9` And his servant *_Zimri_*, captain of half his chariots, conspired against him as he was in Tirzah drinking himself drunk in the house of Arza, steward of his house in Tirzah.
* `1Ki 16:10` And *_Zimri_* went in and smote him and killed him in the twenty-seventh year of Asa king of Judah, and reigned in his stead.
* `1Ki 16:12` Thus *_Zimri_* destroyed all the house of Baasha, according to the word of the LORD which he spoke against Baasha by Jehu the prophet,
* `1Ki 16:15` In the twenty-seventh year of Asa king of Judah, *_Zimri_* reigned seven days in Tirzah. And the people were encamped against Gibbethon, which belonged to the Philistines.
* `1Ki 16:16` And the people who were encamped heard it said, "*_Zimri_* has conspired and has also slain the king." Therefore, all Israel made Omri, the captain of the host, king over Israel that day in the camp.
* `1Ki 16:18` And it came to pass when *_Zimri_* saw that the city was taken, that he went into the palace of the king's house and burnt the king's house over him with fire and died,
* `1Ki 16:20` Now the rest of the acts of *_Zimri_* and his treason that he wrought, are they not written in the book of the chronicles of the kings of Israel?
* `2Ki 9:31` And as Jehu entered the gate, she said, "Did *_Zimri_* have peace, who slew his master?"
* `1Ch 2:6` And the sons of Zerah: *_Zimri_*, Ethan, Heman, Calcol, and Dara; five of them in all.
* `1Ch 8:36` And Ahaz begot Jehoadah, and Jehoadah begot Alemeth, Azmaveth, and *_Zimri_*. And *_Zimri_* begot Moza.
* `1Ch 9:42` And Ahaz begot Jarah, and Jarah begot Alemeth, Azmaveth, and *_Zimri_*. And *_Zimri_* begot Moza.
* `Jer 25:25` All the kings of *_Zimri_*, all the kings of Elam, all the kings of the Medes;

_13 verses containing ZIMRI_

== ZIN

* `Num 13:21` So they went up and searched the land from the wilderness of *_Zin_* to Rehob, as men come to Hamath.
* `Num 20:1` Then the children of Israel came, even the whole congregation, into the desert of *_Zin_* in the first month, and the people stayed in Kadesh. And Miriam died there and was buried there.
* `Num 27:14` For you rebelled against my commandment in the desert of *_Zin_*, in the strife of the congregation, to sanctify me at the water before their eyes." That is the water of Meribah in Kadesh in the wilderness of *_Zin_*.
* `Num 33:36` And they departed from Ezion-gaber and encamped in the wilderness of *_Zin_*, which is Kadesh.
* `Num 34:3` Your south quarter shall be from the wilderness of *_Zin_* along by the border of Edom, and your south border shall be from the end of the Salt Sea eastward.
* `Num 34:4` And your border shall turn from the south to the ascent of Akrabbim and pass on to *_Zin_*. Its limit shall be from the south to Kadesh-barnea and shall go on to Hazar-addar and pass on to Azmon.
* `Deu 32:51` Because you trespassed against me among the children of Israel at the waters of Meribah-Kadesh, in the wilderness of *_Zin_*, and because you did not sanctify me in the midst of the children of Israel.
* `Jsh 15:1` And the lot for the tribe of the children of Judah according to their families was to the border of Edom, even to the wilderness of *_Zin_* southward, at the uttermost part of the south border.
* `Jsh 15:3` And it went out to the south side to Maaleh-acrabbim, passed along to *_Zin_*, ascended on the south side to Kadesh-barnea, passed along to Hezron, went up to Adar, and turned around to Karkaa.

_9 verses containing ZIN_

== ZINA

* `1Ch 23:10` And the sons of Shimei were Jahath, *_Zina_*, Jeush and Beriah. These four were the sons of Shimei.

_1 verse containing ZINA_

== ZION

* `2Sa 5:7` Nevertheless, David took the stronghold of *_Zion_*. The same is the city of David.
* `1Ki 8:1` Then Solomon assembled the elders of Israel and all the heads of the tribes, the chief of the fathers of the children of Israel, to king Solomon in Jerusalem, so that they might bring the ark of the covenant of the LORD out of the city of David, which is *_Zion_*.
* `2Ki 19:21` This is the word that the LORD has spoken concerning him: 'The virgin daughter of *_Zion_* has despised you and laughed you to scorn. The daughter of Jerusalem has shaken her head at you.
* `2Ki 19:31` For out of Jerusalem a remnant shall go forth, and out of mount *_Zion_* those who escape. The zeal of the LORD of hosts shall do this.
* `1Ch 11:5` And the inhabitants of Jebus said to David, "You shall not come here." Nevertheless, David took the castle of *_Zion_*, which is the city of David.
* `2Ch 5:2` Then Solomon assembled the elders of Israel and all the heads of the tribes, the chief of the fathers of the children of Israel, at Jerusalem to bring up the ark of the covenant of the LORD from the city of David, which is *_Zion_*.
* `Psa 2:6` "Yet I have set my king upon my holy hill of *_Zion_*.
* `Psa 9:11` Sing praises to the LORD who dwells in *_Zion_*. Declare among the people his doings.
* `Psa 9:14` So that I may show forth all your praise in the gates of the daughter of *_Zion_*. I will rejoice in your salvation.
* `Psa 14:7` Oh that the salvation of Israel would come out of *_Zion_*! When the LORD brings back the captivity of his people, Jacob shall rejoice and Israel shall be glad.
* `Psa 20:2` Send you help from the sanctuary, strengthen you out of *_Zion_*,
* `Psa 48:2` Beautiful in elevation, the joy of the whole earth, is mount *_Zion_*, on the sides of the north, the city of the great King.
* `Psa 48:11` Let mount *_Zion_* rejoice, let the daughters of Judah be glad because of your judgments.
* `Psa 48:12` Walk around *_Zion_* and encompass her. Number her towers,
* `Psa 50:2` Out of *_Zion_*, the perfection of beauty, God has shined.
* `Psa 51:18` Do good in your good pleasure to *_Zion_*. Build the walls of Jerusalem.
* `Psa 53:6` O that the salvation of Israel would come out of *_Zion_*! When God brings back the captivity of his people, Jacob shall rejoice and Israel shall be glad.
* `Psa 65:1` [To the Chief Musician. A Psalm and Song of David.] Praise waits for you, O God, in *_Zion_*. And to you the vow shall be performed.
* `Psa 69:35` For God will save *_Zion_* and build the cities of Judah so that they may dwell there and have it in possession.
* `Psa 74:2` Remember your congregation which you have purchased of old, the rod of your inheritance which you have redeemed, this mount *_Zion_* in which you have dwelt.
* `Psa 76:2` Also in Salem is his tabernacle and his dwelling place in *_Zion_*.
* `Psa 78:68` But chose the tribe of Judah, the mount *_Zion_* which he loved.
* `Psa 84:7` They go from strength to strength. Every one of them in *_Zion_* appears before God.
* `Psa 87:2` The LORD loves the gates of *_Zion_* more than all the dwellings of Jacob.
* `Psa 87:5` And of *_Zion_* it shall be said, "This and that man was born in her. And the Highest himself shall establish her."
* `Psa 97:8` *_Zion_* heard and was glad. And the daughters of Judah rejoiced because of your judgments, O LORD.
* `Psa 99:2` The LORD is great in *_Zion_* and he is high above all people.
* `Psa 102:13` You shall arise and have mercy upon *_Zion_*, for the time to favor her, even the set time, has come.
* `Psa 102:16` When the LORD builds up *_Zion_*, he will appear in his glory.
* `Psa 102:21` To declare the name of the LORD in *_Zion_* and his praise in Jerusalem,
* `Psa 110:2` The LORD will send the rod of your strength out of *_Zion_*. Rule in the midst of your enemies.
* `Psa 125:1` [A Song of Degrees.] Those who trust in the LORD shall be like mount *_Zion_*, which cannot be moved, but abides forever.
* `Psa 126:1` [A Song of Degrees.] When the LORD turned back the captivity of *_Zion_*, we were like those who dream.
* `Psa 128:5` The LORD shall bless you out of *_Zion_*, and you shall see the good of Jerusalem all the days of your life.
* `Psa 129:5` Let them all be confounded and turned back who hate *_Zion_*.
* `Psa 132:13` For the LORD has chosen *_Zion_*. He has desired it for his habitation.
* `Psa 133:3` It is like the dew of Hermon and like the dew that descended upon the mountains of *_Zion_*. For there the LORD commanded the blessing, even life forever.
* `Psa 134:3` May the LORD who made heaven and earth bless you out of *_Zion_*.
* `Psa 135:21` Blessed be the LORD out of *_Zion_*, who dwells at Jerusalem. Praise the LORD.
* `Psa 137:1` By the rivers of Babylon we sat down. We even wept when we remembered *_Zion_*.
* `Psa 137:3` For there those who carried us away captive required of us a song, and those who wasted us required of us mirth, saying, "Sing us one of the songs of *_Zion_*."
* `Psa 146:10` The LORD will reign forever, even your God, O *_Zion_*, to all generations. Praise the LORD.
* `Psa 147:12` Praise the LORD, O Jerusalem. Praise your God, O *_Zion_*.
* `Psa 149:2` Let Israel rejoice in him who made them. Let the children of *_Zion_* be joyful in their King.
* `Sos 3:11` Go forth, O daughters of *_Zion_*, and behold king Solomon with the crown with which his mother crowned him in the day of his espousals and in the day of the gladness of his heart.
* `Isa 1:8` And the daughter of *_Zion_* is left like a cottage in a vineyard, like a lodge in a garden of cucumbers, like a besieged city.
* `Isa 1:27` *_Zion_* shall be redeemed with judgment, and her converts with righteousness.
* `Isa 2:3` And many people shall go and say, "Come, and let us go up to the mountain of the LORD, to the house of the God of Jacob. And he will teach us his ways, and we will walk in his paths." For out of *_Zion_* the law shall go forth, and the word of the LORD from Jerusalem.
* `Isa 3:16` Moreover, the LORD says, "Because the daughters of *_Zion_* are haughty and walk with extended necks and wanton eyes, walking with short steps as they go and making a tinkling with their feet,
* `Isa 3:17` Therefore the Lord will smite with a scab the crown of the head of the daughters of *_Zion_*, and the LORD will uncover their secret parts."
* `Isa 4:3` And it shall come to pass, that he who is left in *_Zion_* and he who remains in Jerusalem shall be called holy, even everyone who is written among the living in Jerusalem.
* `Isa 4:4` When the Lord has washed away the filth of the daughters of *_Zion_* and has purged the blood of Jerusalem from the midst of it by the spirit of judgment and by the spirit of burning,
* `Isa 4:5` The LORD will create upon every dwelling place of mount *_Zion_* and upon her assemblies a cloud and smoke by day and the shining of a flaming fire by night, for upon all the glory there shall be a defense.
* `Isa 8:18` Behold, I and the children whom the LORD has given me are for signs and for wonders in Israel from the LORD of hosts who dwells on mount *_Zion_*.
* `Isa 10:12` Therefore, it shall come to pass, that when the Lord has performed his whole work upon mount *_Zion_* and on Jerusalem, I will punish the fruit of the stout heart of the king of Assyria and the glory of his high looks.
* `Isa 10:24` Therefore, thus says the Lord GOD of hosts: "O my people who dwell in *_Zion_*, do not be afraid of the Assyrian. He shall smite you with a rod and shall lift up his staff against you after the manner of Egypt.
* `Isa 10:32` This very day he shall remain at Nob. He shall shake his hand against the mountain of the daughter of *_Zion_*, the hill of Jerusalem.
* `Isa 12:6` Cry aloud and shout, inhabitant of *_Zion_*, for the Holy One of Israel is great in the midst of you."
* `Isa 14:32` What shall one then answer the messengers of the nation? That the LORD has founded *_Zion_*, and the poor of his people shall trust in it.
* `Isa 16:1` Send the lamb to the ruler of the land from Sela to the wilderness, to the mountain of the daughter of *_Zion_*.
* `Isa 18:7` In that time the present shall be brought to the LORD of hosts from a people scattered and peeled, and from a people awesome from their beginning until now, a nation measured by line and trodden under foot, whose land the rivers have divided, to the place of the name of the LORD of hosts—mount *_Zion_*.
* `Isa 24:23` Then the moon shall be confounded and the sun ashamed when the LORD of hosts reigns on mount *_Zion_*, in Jerusalem, and before his ancients gloriously.
* `Isa 28:16` Therefore, thus says the Lord GOD: "Behold, I lay a stone in *_Zion_* for a foundation, a tried stone, a precious cornerstone, a sure foundation. He who believes shall not make haste.
* `Isa 29:8` It shall even be as when a hungry man dreams, and behold, he eats, but he awakes and his soul is empty, or as when a thirsty man dreams, and behold, he drinks, but he awakes, and behold, he is faint and his soul has appetite. Thus the multitude of all the nations shall be who fight against mount *_Zion_*.
* `Isa 30:19` For the people shall dwell in *_Zion_* at Jerusalem. You shall no longer weep. He will be very gracious to you at the voice of your cry. When he hears it, he will answer you.
* `Isa 31:4` For thus the LORD has spoken to me: "As the lion and the young lion roaring on his prey when a multitude of shepherds is called forth against him, and he will not be afraid of their voice nor abase himself for their noise, so the LORD of hosts will come down to fight for mount *_Zion_* and for the hill thereof.
* `Isa 31:9` And he shall pass over to his stronghold for fear, and his princes shall be afraid of the ensign," says the LORD, whose fire is in *_Zion_* and his furnace in Jerusalem.
* `Isa 33:5` The LORD is exalted, for he dwells on high. He has filled *_Zion_* with judgment and righteousness.
* `Isa 33:14` The sinners in *_Zion_* are afraid. Fearfulness has surprised the hypocrites. "Who among us shall dwell with the devouring fire? Who among us shall dwell with everlasting burnings?"
* `Isa 33:20` Look upon *_Zion_*, the city of our solemnities. Your eyes shall see Jerusalem, a quiet habitation, a tabernacle that shall not be taken down. Not one of its stakes shall ever be removed, neither shall any of its cords be broken.
* `Isa 34:8` For it is the day of the LORD'S vengeance, and the year of recompenses for the controversy of *_Zion_*.
* `Isa 35:10` And the ransomed of the LORD shall return and come to *_Zion_* with songs and everlasting joy upon their heads. They shall obtain joy and gladness, and sorrow and sighing shall flee away.
* `Isa 37:22` This is the word which the LORD has spoken concerning him: "The virgin, the daughter of *_Zion_*, has despised you and derided you. The daughter of Jerusalem has shaken her head at you.
* `Isa 37:32` For out of Jerusalem a remnant shall go forth, and out of mount *_Zion_* those who escape. The zeal of the LORD of hosts will do this."'
* `Isa 40:9` O *_Zion_*, who brings good tidings, go up upon the high mountain. O Jerusalem, who brings good tidings, lift up your voice with strength. Lift it up, do not be afraid. Say to the cities of Judah, "Behold your God!"
* `Isa 41:27` The first shall say to *_Zion_*, 'Behold, behold them.' And I will give to Jerusalem one who brings good tidings.
* `Isa 46:13` I bring my righteousness near. It shall not be far off, and my salvation shall not delay. And I will place salvation in *_Zion_* for Israel my glory."
* `Isa 49:14` But *_Zion_* said, "The LORD has forsaken me, and my Lord has forgotten me."
* `Isa 51:3` For the LORD will comfort *_Zion_*. He will comfort all her waste places, and he will make her wilderness like Eden and her desert like the garden of the LORD. Joy and gladness shall be found therein, thanksgiving and the voice of melody.
* `Isa 51:11` Therefore, the redeemed of the LORD shall return and come with singing to *_Zion_*, and everlasting joy shall be upon their head. They shall obtain gladness and joy. Sorrow and mourning shall flee away.
* `Isa 51:16` And I have put my words in your mouth and have covered you in the shadow of my hand, so that I may plant the heavens, lay the foundations of the earth, and say to *_Zion_*, 'You are my people.'"
* `Isa 52:1` Awake, awake, put on your strength, O *_Zion_*. Put on your beautiful garments, O Jerusalem, the holy city. For from now on the uncircumcised and the unclean shall no longer come into you.
* `Isa 52:2` Shake yourself from the dust. Arise, and sit down, O Jerusalem. Release yourself from the bonds of your neck, O captive daughter of *_Zion_*.
* `Isa 52:7` How beautiful upon the mountains are the feet of him who brings good tidings, who publishes peace, who brings good tidings of good, who publishes salvation, who says to *_Zion_*, "Your God reigns!"
* `Isa 52:8` Your watchmen shall lift up their voices. With their voices together they shall sing, for they shall see eye to eye, when the LORD brings back *_Zion_*.
* `Isa 59:20` "And the Redeemer will come to *_Zion_* and to those in Jacob who turn from transgression," says the LORD.
* `Isa 60:14` The sons of those who afflicted you shall also come bending to you. And all those who despised you shall bow themselves down at the soles of your feet. And they shall call you, The City of the LORD, The *_Zion_* of the Holy One of Israel.
* `Isa 61:3` To appoint to those who mourn in *_Zion_*, to give to them beauty for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness. And they will be called trees of righteousness, the planting of the LORD, so that he may be glorified.
* `Isa 62:1` For *_Zion_*'s sake I will not hold my peace, and for Jerusalem's sake I will not rest, until its righteousness goes forth like brightness and its salvation like a lamp that burns.
* `Isa 62:11` Behold, the LORD has proclaimed to the end of the world, "Say to the daughter of *_Zion_*, 'Behold, your salvation comes. Behold, his reward is with him and his work before him.'"
* `Isa 64:10` Your holy cities are a wilderness. *_Zion_* is a wilderness, Jerusalem a desolation.
* `Isa 66:8` Who has heard such a thing? Who has seen such things? Shall the earth be made to bring forth in one day? Or shall a nation be born at once? For as soon as *_Zion_* travailed, she brought forth her children.
* `Jer 3:14` 'Turn, O backsliding children,' says the LORD. 'For I am married to you. And I will take you one from a city and two from a family, and I will bring you to *_Zion_*.'
* `Jer 4:6` Set up the standard toward *_Zion_*. Retire, do not stay, for I will bring evil from the north, and a great destruction.
* `Jer 4:31` For I have heard a voice as of a woman in travail, and the anguish as of her who brings forth her first child, the voice of the daughter of *_Zion_* who bewails herself, who spreads her hands, saying, "Woe is me now! For my soul is wearied because of murderers."
* `Jer 6:2` I have compared the daughter of *_Zion_* to a beautiful and delicate woman.
* `Jer 6:23` They shall lay hold on bow and spear. They are cruel and have no mercy. Their voice roars like the sea. And they ride upon horses, set in array as men for war against you, O daughter of *_Zion_*."
* `Jer 8:19` Behold the voice of the cry of the daughter of my people because of those who dwell in a distant country: "Is the LORD not in *_Zion_*? Is her king not in her?" "Why have they provoked me to anger with their engraved images and with strange vanities?"
* `Jer 9:19` For a voice of wailing is heard out of *_Zion_*, 'How we are laid waste! We are greatly confounded because we have forsaken the land, because our dwellings have cast us out.'"
* `Jer 14:19` Have you utterly rejected Judah? Has your soul loathed *_Zion_*? Why have you smitten us and there is no healing for us? We looked for peace, and there is no good, and for the time of healing, and behold, trouble!
* `Jer 26:18` "Micah the Morasthite prophesied in the days of Hezekiah king of Judah and spoke to all the people of Judah, saying, 'Thus says the LORD of hosts: "*_Zion_* shall be plowed like a field, Jerusalem shall become heaps, and the mountain of the house like the high places of the forest."'
* `Jer 30:17` For I will restore health to you and heal you of your wounds,' says the LORD, 'because they called you an outcast, saying, "This is *_Zion_*, whom no man seeks after."'
* `Jer 31:6` For there shall be a day that the watchmen upon the mountains of Ephraim shall cry, 'Arise, and let us go up to *_Zion_* to the LORD our God.'"
* `Jer 31:12` "Therefore, they shall come and sing in the height of *_Zion_* and shall flow together to the goodness of the LORD for wheat, for wine, for oil, and for the young of the flock and of the herd. And their soul shall be like a watered garden, and they shall not sorrow anymore at all.
* `Jer 50:5` They shall ask the way to *_Zion_* with their faces toward it, saying, 'Come, and let us join ourselves to the LORD in a perpetual covenant that shall not be forgotten.'
* `Jer 50:28` The voice of those who flee and escape from the land of Babylon declares in *_Zion_* the vengeance of the LORD our God, the vengeance of his temple.
* `Jer 51:10` The LORD has brought forth our righteousness. Come, and let us declare in *_Zion_* the work of the LORD our God.
* `Jer 51:24` And I will render to Babylon and to all the inhabitants of Chaldea all their evil that they have done in *_Zion_* in your sight," says the LORD.
* `Jer 51:35` May the violence done to me and to my flesh be upon Babylon," the inhabitant of *_Zion_* shall say. "May my blood be upon the inhabitants of Chaldea," Jerusalem shall say.
* `Lam 1:4` [DALET] The ways of *_Zion_* mourn, because no one comes to the solemn feasts. All her gates are desolate. Her priests sigh. Her virgins are afflicted. She is in bitterness.
* `Lam 1:6` [VAV] And from the daughter of *_Zion_* all her beauty has departed. Her princes have become like bucks that find no pasture, and they have gone without strength before the pursuer.
* `Lam 1:17` [PE] *_Zion_* spreads forth her hands, and there is no one to comfort her. The LORD has commanded concerning Jacob, that his adversaries should be around him. Jerusalem has become an unclean thing among them.
* `Lam 2:1` [ALEPH] How the Lord has covered the daughter of *_Zion_* with a cloud in his anger, and cast down from heaven to the earth the beauty of Israel, and not remembered his footstool in the day of his anger!
* `Lam 2:4` [DALET] He has bent his bow like an enemy. He stood with his right hand as an adversary and slew all who were pleasant to the eye in the tabernacle of the daughter of *_Zion_*. He poured out his fury like fire.
* `Lam 2:6` [VAV] And he has violently taken away his tabernacle as if it were of a garden. He has destroyed his places of the assembly. The LORD has caused the solemn feasts and sabbaths to be forgotten in *_Zion_*, and in the indignation of his anger has despised the king and the priest.
* `Lam 2:8` [HET] The LORD has purposed to destroy the wall of the daughter of *_Zion_*. He has stretched out a line. He has not withdrawn his hand from destroying. Therefore, he made the rampart and the wall to lament. They languished together.
* `Lam 2:10` [YOD] The elders of the daughter of *_Zion_* sit upon the ground and keep silence. They have cast up dust upon their heads. They have girded themselves with sackcloth. The virgins of Jerusalem hang down their heads to the ground.
* `Lam 2:13` [MEM] What thing shall I take to witness for you? What thing shall I compare to you, O daughter of Jerusalem? What shall I equal to you so that I may comfort you, O virgin daughter of *_Zion_*? For your breach is great like the sea. Who can heal you?
* `Lam 2:18` [TSADI] Their heart cried to the Lord, "O wall of the daughter of *_Zion_*, let tears run down like a river day and night. Give yourself no rest. Do not let the apple of your eye cease.
* `Lam 4:2` [BET] The precious sons of *_Zion_*, comparable to fine gold, how they are esteemed as earthen pitchers, the work of the hands of the potter!
* `Lam 4:11` [KAF] The LORD has accomplished his fury. He has poured out his fierce anger and has kindled a fire in *_Zion_*, and it has devoured her foundations.
* `Lam 4:22` [TAV] The punishment of your iniquity is accomplished, O daughter of *_Zion_*. He will no longer carry you away into captivity. He will visit your iniquity, O daughter of Edom. He will disclose your sins.
* `Lam 5:11` They ravished the women in *_Zion_* and the virgins in the cities of Judah.
* `Lam 5:18` Because of the mountain of *_Zion_*, which is desolate. The foxes walk upon it.
* `Joe 2:1` Blow the trumpet in *_Zion_* and sound an alarm on my holy mountain. Let all the inhabitants of the land tremble, for the day of the LORD comes. It is near at hand,
* `Joe 2:15` Blow the trumpet in *_Zion_*. Sanctify a fast. Call a solemn assembly.
* `Joe 2:23` Be glad then, children of *_Zion_*, and rejoice in the LORD your God, for he has given you the former rain moderately. He will cause to come down for you the rain, the former rain and the latter rain, in the first month.
* `Joe 2:32` And it shall come to pass, that whoever calls on the name of the LORD shall be delivered. For on mount *_Zion_* and in Jerusalem there shall be deliverance, as the LORD has said, and in the remnant whom the LORD calls."
* `Joe 3:16` The LORD will also roar out of *_Zion_* and utter his voice from Jerusalem, and the heavens and the earth shall shake. But the LORD will be the hope of his people and the strength of the children of Israel.
* `Joe 3:17` "And you shall know that I am the LORD your God dwelling in *_Zion_*, my holy mountain. Then Jerusalem shall be holy, and no strangers shall pass through her anymore.
* `Joe 3:21` For I will cleanse their blood that I have not cleansed. For the LORD dwells in *_Zion_*."
* `Amo 1:2` And he said, "The LORD will roar from *_Zion_* and utter his voice from Jerusalem, and the habitations of the shepherds shall mourn, and the top of Carmel shall wither."
* `Amo 6:1` Woe to those who are at ease in *_Zion_* and are secure on the mountain of Samaria, who are named chief of the nations, to whom the house of Israel came!
* `Oba 1:17` But upon mount *_Zion_* there shall be deliverance and there shall be holiness. And the house of Jacob shall possess their possessions.
* `Oba 1:21` And saviors shall come upon mount *_Zion_* to judge the mountain of Esau, and the kingdom shall be the LORD'S.
* `Mic 1:13` O inhabitant of Lachish, bind the chariot to the swift beast. She is the beginning of the sin to the daughter of *_Zion_*, for the transgressions of Israel were found in you.
* `Mic 3:10` They build up *_Zion_* with blood and Jerusalem with iniquity.
* `Mic 3:12` Therefore, *_Zion_* for your sake shall be plowed as a field, Jerusalem shall become heaps, and the mountain of the house as the high places of the forest.
* `Mic 4:2` And many nations shall come and say, "Come, and let us go up to the mountain of the LORD and to the house of the God of Jacob, and he will teach us of his ways, and we will walk in his paths." For the law shall go forth from *_Zion_* and the word of the LORD from Jerusalem.
* `Mic 4:7` I will make her who was lame a remnant and her who was cast far off a strong nation. And the LORD will reign over them on mount *_Zion_* from now on, even forever."
* `Mic 4:8` And you, O tower of the flock, the stronghold of the daughter of *_Zion_*, it shall come to you, even the former dominion shall come, the kingdom to the daughter of Jerusalem.
* `Mic 4:10` Be in pain and labor to bring forth, O daughter of *_Zion_*, like a woman in travail. For now you shall go forth from the city and you shall dwell in the field, and you shall go even to Babylon. There you shall be delivered. There the LORD shall redeem you from the hand of your enemies.
* `Mic 4:11` Now also many nations are gathered against you, who say, "Let her be defiled, and let our eye look upon *_Zion_*."
* `Mic 4:13` "Arise and thresh, O daughter of *_Zion_*, for I will make your horn iron and I will make your hooves brass. And you shall beat many people in pieces. And I will consecrate their gain to YAHWEH and their substance to the Lord of the whole earth."
* `Zph 3:14` Sing, O daughter of *_Zion_*. Shout, O Israel. Be glad and rejoice with all the heart, O daughter of Jerusalem.
* `Zph 3:16` In that day it shall be said to Jerusalem, "Do not fear, O *_Zion_*. Do not let your hands be slack.
* `Zch 1:14` So the angel who spoke with me said to me, "Cry, saying, 'Thus says the LORD of hosts: "I am jealous for Jerusalem and for *_Zion_* with a great jealousy.
* `Zch 1:17` Cry again, saying, 'Thus says the LORD of hosts: "My cities through prosperity shall again be spread abroad, and the LORD shall again comfort *_Zion_* and shall again choose Jerusalem."'"
* `Zch 2:7` "Deliver yourself, O *_Zion_*, who dwell with the daughter of Babylon."
* `Zch 2:10` Sing and rejoice, O daughter of *_Zion_*. For behold, I come and I will dwell in the midst of you," says the LORD.
* `Zch 8:2` "Thus says the LORD of hosts: 'I am jealous for *_Zion_* with great jealousy, and I am jealous for her with great fury.'
* `Zch 8:3` Thus says the LORD: 'I have returned to *_Zion_* and will dwell in the midst of Jerusalem. And Jerusalem shall be called a city of truth, and the mountain of the LORD of hosts, the holy mountain.'
* `Zch 9:9` Rejoice greatly, O daughter of *_Zion_*. Shout, O daughter of Jerusalem. Behold, your King comes to you. He is just and having salvation, lowly and riding upon a donkey, even upon a colt, the foal of a donkey.
* `Zch 9:13` When I have bent Judah for me, filled the bow with Ephraim, and raised up your sons, O *_Zion_*, against your sons, O Greece, and made you as the sword of a mighty man.
* `Mth 21:5` "Tell the daughter of *_Zion_*, 'Behold, your King comes to you, meek, and sitting upon a donkey, even a colt, the foal of a donkey.'"
* `Jhn 12:15` "Do not fear, daughter of *_Zion_*. Behold, your King comes, sitting on a donkey's colt."
* `Rom 9:33` As it is written, "Behold, I lay in *_Zion_* a stumbling-stone and rock of offense, and whoever believes in him shall not be ashamed."
* `Rom 11:26` And so all Israel shall be saved, as it is written, "The Deliverer will come out of *_Zion_*, and he will turn away ungodliness from Jacob.
* `Heb 12:22` But you have come to mount *_Zion_* and to the city of the living God, the heavenly Jerusalem, and to an innumerable company of angels,
* `1Pe 2:6` Therefore, it is also contained in the Scripture, "Behold, I lay in *_Zion_* a chief corner-stone, elect, precious. And he who believes in him shall not be confounded."
* `Rev 14:1` And I looked, and behold, a Lamb stood on mount *_Zion_*, and with him one hundred and forty-four thousand, having his Father's name written on their foreheads.

_161 verses containing ZION_

== ZIOR

* `Jsh 15:54` Humtah, Kirjath-arba (which is Hebron), and *_Zior_*; nine cities with their villages.

_1 verse containing ZIOR_

== ZIPH

* `Jsh 15:24` *_Ziph_*, Telem, Bealoth,
* `Jsh 15:55` Maon, Carmel, *_Ziph_*, Juttah,
* `1Sa 23:14` And David stayed in the wilderness in strongholds and remained in a mountain in the wilderness of *_Ziph_*. And Saul sought him every day, but God did not deliver him into his hand.
* `1Sa 23:15` And David saw that Saul had come out to seek his life. And David was in the wilderness of *_Ziph_* in a forest.
* `1Sa 23:24` And they arose and went to *_Ziph_* before Saul, but David and his men were in the wilderness of Maon, in the plain on the south of Jeshimon.
* `1Sa 26:2` Then Saul arose and went down to the wilderness of *_Ziph_*, having three thousand chosen men of Israel with him, to seek David in the wilderness of *_Ziph_*.
* `1Ch 2:42` Now the sons of Caleb the brother of Jerahmeel were Mesha his first-born, who was the father of *_Ziph_*, and the sons of Mareshah the father of Hebron.
* `1Ch 4:16` And the sons of Jehaleleel: *_Ziph_*, Ziphah, Tiria, and Asareel.
* `2Ch 11:8` Gath, Mareshah, *_Ziph_*,

_9 verses containing ZIPH_

== ZIPHAH

* `1Ch 4:16` And the sons of Jehaleleel: Ziph, *_Ziphah_*, Tiria, and Asareel.

_1 verse containing ZIPHAH_

== ZIPHIMS

* `Psa 54:1` [To the Chief Musician on Neginoth. Maschil. A Psalm of David: when the *_Ziphims_* came and said to Saul, "Does David not hide himself with us?"] Save me, O God, by your name, and judge me by your strength.

_1 verse containing ZIPHIMS_

== ZIPHION

* `Gen 46:16` And the sons of Gad: *_Ziphion_*, Haggai, Shuni, Ezbon, Eri, Arodi, and Areli.

_1 verse containing ZIPHION_

== ZIPHITES

* `1Sa 23:19` Then the *_Ziphites_* came up to Saul at Gibeah, saying, "Does David not hide himself with us in strongholds in the forest, in the hill of Hachilah, which is on the south of Jeshimon?
* `1Sa 26:1` And the *_Ziphites_* came to Saul at Gibeah, saying, "Does David not hide himself in the hill of Hachilah, which is before Jeshimon?"

_2 verses containing ZIPHITES_

== ZIPHRON

* `Num 34:9` And the border shall go on to *_Ziphron_*, and its limits shall be at Hazar-enan. This shall be your north border.

_1 verse containing ZIPHRON_

== ZIPPOR

* `Num 22:2` And Balak the son of *_Zippor_* saw all that Israel had done to the Amorites.
* `Num 22:4` And Moab said to the elders of Midian, "Now this company shall lick up all that is around us as the ox licks up the grass of the field." And Balak the son of *_Zippor_* was king of the Moabites at that time.
* `Num 22:10` And Balaam said to God, "Balak the son of *_Zippor_*, king of Moab, has sent to me, saying,
* `Num 22:16` And they came to Balaam and said to him, "Thus says Balak the son of *_Zippor_*: 'Let nothing, I pray you, hinder you from coming to me.
* `Num 23:18` And he took up his parable and said, "Rise, Balak, and hear. Listen to me, son of *_Zippor_*.
* `Jsh 24:9` Then Balak the son of *_Zippor_*, king of Moab, arose and warred against Israel, and sent and called Balaam the son of Beor to curse you.
* `Jdg 11:25` And now are you anything better than Balak the son of *_Zippor_* king of Moab? Did he ever strive against Israel? Did he ever fight against them?

_7 verses containing ZIPPOR_

== ZIPPORAH

* `Exo 2:21` And Moses was content to dwell with the man. And he gave *_Zipporah_* his daughter to Moses.
* `Exo 4:25` Then *_Zipporah_* took a sharp stone, cut off the foreskin of her son, and cast it at his feet, and said, "Surely a bloody husband you are to me."
* `Exo 18:2` Jethro, Moses's father-in-law, took *_Zipporah_*, Moses's wife, after he had sent her back,

_3 verses containing ZIPPORAH_

== ZITHRI

* `Exo 6:22` And the sons of Uzziel: Mishael, Elzaphan, and *_Zithri_*.

_1 verse containing ZITHRI_

== ZIZ

* `2Ch 20:16` Tomorrow, go down against them. Behold, they come up by the cliff of *_Ziz_*, and you shall find them at the end of the brook before the wilderness of Jeruel.

_1 verse containing ZIZ_

== ZIZA

* `1Ch 4:37` *_Ziza_* the son of Shiphi, the son of Allon, the son of Jedaiah, the son of Shimri, the son of Shemaiah—
* `2Ch 11:20` And after her he took Maachah the daughter of Absalom, who bore him Abijah, Attai, *_Ziza_*, and Shelomith.

_2 verses containing ZIZA_

== ZIZAH

* `1Ch 23:11` And Jahath was the chief and *_Zizah_* the second, but Jeush and Beriah did not have many sons; therefore, they were in one reckoning according to their father's house.

_1 verse containing ZIZAH_

== ZOAN

* `Num 13:22` And they ascended by the south and came to Hebron where Ahiman, Sheshai, and Talmai, the children of Anak, were. (Now Hebron was built seven years before *_Zoan_* in Egypt.)
* `Psa 78:12` He did marvelous things in the sight of their fathers, in the land of Egypt, in the field of *_Zoan_*.
* `Psa 78:43` How he had wrought his signs in Egypt and his wonders in the field of *_Zoan_*,
* `Isa 19:11` Surely the princes of *_Zoan_* are fools. The counsel of the wise counselors of Pharaoh has become brutish. How do you say to Pharaoh, "I am the son of the wise, the son of ancient kings"?
* `Isa 19:13` The princes of *_Zoan_* have become fools, the princes of Noph are deceived. They have also seduced Egypt, even those who are the support of its tribes.
* `Isa 30:4` For his princes were at *_Zoan_* and his ambassadors came to Hanes.
* `Ezk 30:14` And I will make Pathros desolate, set fire in *_Zoan_*, and execute judgments in No.

_7 verses containing ZOAN_

== ZOAR

* `Gen 13:10` And Lot lifted up his eyes and beheld all the plain of the Jordan, that it was well watered everywhere (before the LORD destroyed Sodom and Gomorrah), even as the garden of the LORD, like the land of Egypt, as far as to *_Zoar_*.
* `Gen 14:2` That these made war with Bera king of Sodom, Birsha king of Gomorrah, Shinab king of Admah, Shemeber king of Zeboiim, and the king of Bela, which is *_Zoar_*.
* `Gen 14:8` And the king of Sodom, the king of Gomorrah, the king of Admah, the king of Zeboiim, and the king of Bela (the same is *_Zoar_*) went out, and they joined battle with them in the valley of Siddim,
* `Gen 19:22` Hasten, escape there, for I cannot do anything until you get there." Therefore, the name of the city was called *_Zoar_*.
* `Gen 19:23` The sun had risen upon the earth when Lot entered into *_Zoar_*.
* `Gen 19:30` And Lot went up from *_Zoar_* and dwelt in the mountain, and his two daughters with him, for he feared to dwell in *_Zoar_*. And he dwelt in a cave—he and his two daughters.
* `Deu 34:3` The south, and the plain of the valley of Jericho, the city of palm-trees, to *_Zoar_*.
* `Isa 15:5` My heart shall cry out for Moab. His fugitives shall flee to *_Zoar_*, a heifer of three years old. For they shall go up the ascent of Luhith with weeping, for in the way of Horonaim they shall raise a cry of destruction.
* `Jer 48:34` "From the cry of Heshbon even to Elealeh, and even to Jahaz, they have uttered their voice, from *_Zoar_* even to Horonaim, as a heifer of three years old. For the waters also of Nimrim shall be desolate.

_9 verses containing ZOAR_

== ZOBA

* `2Sa 10:6` And when the children of Ammon saw that they had made themselves odious before David, the children of Ammon sent and hired the Syrians of Beth-rehob and the Syrians of *_Zoba_*, twenty thousand footmen, and one thousand men from the king of Maacah and twelve thousand men from the men of Tob.
* `2Sa 10:8` And the children of Ammon came out and put the battle in array at the entrance of the gate. And the Syrians of *_Zoba_* and of Rehob and the men of Tob and Maacah were by themselves in the field.

_2 verses containing ZOBA_

== ZOBAH

* `1Sa 14:47` So Saul took the kingdom over Israel and fought against all his enemies on every side: against Moab, against the children of Ammon, against Edom, against the kings of *_Zobah_*, and against the Philistines. And wherever he turned himself, he harassed them.
* `2Sa 8:3` David also smote Hadadezer, the son of Rehob, king of *_Zobah_*, as he went to recover his border at the Euphrates River.
* `2Sa 8:5` And when the Syrians of Damascus came to help Hadadezer king of *_Zobah_*, David slew twenty-two thousand men of the Syrians.
* `2Sa 8:12` From Syria, from Moab, from the children of Ammon, from the Philistines, from Amalek, and from the plunder of Hadadezer son of Rehob, king of *_Zobah_*.
* `2Sa 23:36` Igal the son of Nathan of *_Zobah_*, Bani the Gadite,
* `1Ki 11:23` And God stirred up another adversary for him: Rezon the son of Eliadah, who fled from his lord Hadadezer king of *_Zobah_*.
* `1Ki 11:24` And he gathered men to him and became captain over a band when David slew those of *_Zobah_*. And they went to Damascus, dwelt in it, and reigned in Damascus.
* `1Ch 18:3` And David smote Hadarezer king of *_Zobah_* to Hamath as he went to establish his dominion by the Euphrates River.
* `1Ch 18:5` And when the Syrians of Damascus came to help Hadarezer king of *_Zobah_*, David slew of the Syrians twenty-two thousand men.
* `1Ch 18:9` Now when Tou king of Hamath heard how David had smitten all the host of Hadarezer king of *_Zobah_*,
* `1Ch 19:6` And when the children of Ammon saw that they had made themselves odious to David, Hanun and the children of Ammon sent one thousand talents of silver to hire themselves chariots and horsemen out of Mesopotamia, out of Syria-maachah, and out of *_Zobah_*.
* `2Ch 8:3` And Solomon went to Hamath-*_zobah_* and prevailed against it.
* `Psa 60:1` [To the Chief Musician upon Shushan-eduth. Michtam of David for Teaching: when he strove with Aram-naharaim and with Aram-*_zobah_*, when Joab returned and smote twelve thousand of Edom in the valley of salt.] O God, you have cast us off. You have scattered us. You have been displeased. O turn yourself to us again.

_13 verses containing ZOBAH_

== ZOBEBAH

* `1Ch 4:8` And Coz begot Anub, *_Zobebah_*, and the families of Aharhel the son of Harum.

_1 verse containing ZOBEBAH_

== ZOHAR

* `Gen 23:8` And he spoke with them, saying, "If it is your mind that I should bury my dead out of my sight, hear me, and entreat for me to Ephron the son of *_Zohar_*,
* `Gen 25:9` And his sons Isaac and Ishmael buried him in the cave of Machpelah, in the field of Ephron the son of *_Zohar_* the Hittite, which is before Mamre,
* `Gen 46:10` And the sons of Simeon: Jemuel, Jamin, Ohad, Jachin, *_Zohar_*, and Shaul the son of a Canaanitish woman.
* `Exo 6:15` And the sons of Simeon: Jemuel, Jamin, Ohad, Jachin, *_Zohar_*, and Shaul the son of a Canaanitish woman. These are the families of Simeon.

_4 verses containing ZOHAR_

== ZOHELETH

* `1Ki 1:9` And Adonijah slew sheep, oxen, and fattened calves by the stone of *_Zoheleth_*, which is by En-rogel, and called all his brothers the king's sons and all the men of Judah the king's servants,

_1 verse containing ZOHELETH_

== ZOHETH

* `1Ch 4:20` And the sons of Shimon were Amnon, Rinnah, Ben-hanan, and Tilon. And the sons of Ishi were *_Zoheth_* and Benzoheth.

_1 verse containing ZOHETH_

== ZOPHAH

* `1Ch 7:35` And the sons of his brother Helem: *_Zophah_*, Imna, Shelesh, and Amal.
* `1Ch 7:36` The sons of *_Zophah_*: Suah, Harnepher, Shual, Beri, Imrah,

_2 verses containing ZOPHAH_

== ZOPHAI

* `1Ch 6:26` As for Elkanah, the sons of Elkanah: *_Zophai_* his son, Nahath his son,

_1 verse containing ZOPHAI_

== ZOPHAR

* `Job 2:11` Now when Job's three friends heard of all this evil that had come upon him, they each came from his own place: Eliphaz the Temanite, Bildad the Shuhite, and *_Zophar_* the Naamathite—for they had made an appointment together to come to mourn with him and to comfort him.
* `Job 11:1` Then *_Zophar_* the Naamathite answered and said,
* `Job 20:1` Then *_Zophar_* the Naamathite answered and said,
* `Job 42:9` So Eliphaz the Temanite, Bildad the Shuhite, and *_Zophar_* the Naamathite went and did according as the LORD commanded them. The LORD also accepted Job.

_4 verses containing ZOPHAR_

== ZOPHIM

* `Num 23:14` And he brought him into the field of *_Zophim_*, to the top of Pisgah, and built seven altars and offered a bull and a ram on every altar.
* `1Sa 1:1` Now there was a certain man of Ramathaim-*_zophim_*, of mount Ephraim, and his name was Elkanah, the son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephrathite.

_2 verses containing ZOPHIM_

== ZORAH

* `Jsh 19:41` And the border of their inheritance was *_Zorah_*, Eshtaol, Ir-shemesh,
* `Jdg 13:2` And there was a certain man of *_Zorah_*, of the family of the Danites, whose name was Manoah, and his wife was barren and did not bear.
* `Jdg 13:25` And the Spirit of the LORD began to move him at times in the camp of Dan, between *_Zorah_* and Eshtaol.
* `Jdg 16:31` Then his brothers and all the house of his father came down, took him, brought him up, and buried him between *_Zorah_* and Eshtaol in the burying-place of Manoah his father. And he judged Israel for twenty years.
* `Jdg 18:2` And the children of Dan sent from their family five men from their borders, men of valor, from *_Zorah_* and from Eshtaol, to explore the land and to search it. And they said to them, "Go, search the land." When they came to mount Ephraim, to the house of Micah, they lodged there.
* `Jdg 18:8` And they came to their brothers at *_Zorah_* and Eshtaol, and their brothers said to them, "What do you say?"
* `Jdg 18:11` And there went from there of the family of the Danites, out of *_Zorah_* and out of Eshtaol, six hundred men appointed with weapons of war.
* `2Ch 11:10` *_Zorah_*, Ajalon, and Hebron, which are in Judah and in Benjamin, fortified cities.

_8 verses containing ZORAH_

== ZORATHITES

* `1Ch 4:2` And Reaiah the son of Shobal begot Jahath, and Jahath begot Ahumai and Lahad. These are the families of the *_Zorathites_*.

_1 verse containing ZORATHITES_

== ZOREAH

* `Jsh 15:33` And in the valley, Eshtaol, *_Zoreah_*, Ashnah,

_1 verse containing ZOREAH_

== ZORITES

* `1Ch 2:54` The sons of Salma: Beth-lehem and the Netophathites, Ataroth-beth-joab, half of the Menahethites, and the *_Zorites_*.

_1 verse containing ZORITES_

== ZUAR

* `Num 1:8` Of Issachar, Nethaneel the son of *_Zuar_*;
* `Num 2:5` And those who shall pitch next to him shall be the tribe of Issachar, and Nethaneel the son of *_Zuar_* shall be captain of the children of Issachar.
* `Num 7:18` On the second day Nethaneel the son of *_Zuar_*, prince of Issachar, offered.
* `Num 7:23` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of Nethaneel the son of *_Zuar_*.
* `Num 10:15` And over the host of the tribe of the children of Issachar was Nethaneel the son of *_Zuar_*.

_5 verses containing ZUAR_

== ZUF

* `1Sa 9:5` And when they had come to the land of *_Zuf_*, Saul said to his servant who was with him, "Come, and let us return, lest my father cease caring for the donkeys and be anxious for us."

_1 verse containing ZUF_

== ZUPH

* `1Sa 1:1` Now there was a certain man of Ramathaim-zophim, of mount Ephraim, and his name was Elkanah, the son of Jeroham, the son of Elihu, the son of Tohu, the son of *_Zuph_*, an Ephrathite.
* `1Ch 6:35` The son of *_Zuph_*, the son of Elkanah, the son of Mahath, the son of Amasai,

_2 verses containing ZUPH_

== ZUR

* `Num 25:15` And the name of the Midianitish woman who was slain was Cozbi the daughter of *_Zur_*. He was head over a people and of a chief house in Midian.
* `Num 31:8` And they slew the kings of Midian, besides the rest of those who were slain, namely, Evi, Rekem, *_Zur_*, Hur, and Reba, five kings of Midian. Balaam the son of Beor they also slew with the sword.
* `Jsh 13:21` All the cities of the plain, and all the kingdom of Sihon king of the Amorites, who reigned in Heshbon. Moses smote him along with the princes of Midian: Evi, Rekem, *_Zur_*, Hur, and Reba—chiefs of Sihon who dwelt in the country.
* `Jsh 15:58` Halhul, Beth-*_zur_*, Gedor,
* `1Ch 2:45` And the son of Shammai was Maon, and Maon was the father of Beth-*_zur_*.
* `1Ch 8:30` And his first-born son Abdon, then *_Zur_*, Kish, Baal, Nadab,
* `1Ch 9:36` And his first-born son Abdon, then *_Zur_*, Kish, Baal, Ner, Nadab,
* `2Ch 11:7` Beth-*_zur_*, Shocho, Adullam,
* `Neh 3:16` After him Nehemiah the son of Azbuk, the ruler of the half part of Beth-*_zur_*, repaired to the place over against the sepulchers of David, and to the pool that was made, and to the house of the mighty.

_9 verses containing ZUR_

== ZURIEL

* `Num 3:35` And the chief of the house of the father of the families of Merari was *_Zuriel_* the son of Abihail. These shall pitch on the side of the tabernacle northward.

_1 verse containing ZURIEL_

== ZURISHADDAI

* `Num 1:6` Of Simeon, Shelumiel the son of *_Zurishaddai_*;
* `Num 2:12` And those who pitch by him shall be the tribe of Simeon, and the captain of the children of Simeon shall be Shelumiel the son of *_Zurishaddai_*.
* `Num 7:36` On the fifth day Shelumiel the son of *_Zurishaddai_*, prince of the children of Simeon, offered.
* `Num 7:41` And for a sacrifice of peace-offerings, two oxen, five rams, five male goats, and five lambs of the first year. This was the offering of Shelumiel the son of *_Zurishaddai_*.
* `Num 10:19` And over the host of the tribe of the children of Simeon was Shelumiel the son of *_Zurishaddai_*.

_5 verses containing ZURISHADDAI_

== ZUZIMS

* `Gen 14:5` And in the fourteenth year, Chedorlaomer and the kings who were with him came and smote the Rephaims in Ashteroth Karnaim, the *_Zuzims_* in Ham, the Emins in Shaveh Kiriathaim,

_1 verse containing ZUZIMS_

