= RAAMAH - RAZOR
:toc:

== RAAMAH

* `Gen 10:7` And the sons of Cush: Seba, Havilah, Sabtah, *_Raamah_*, and Sabtecha. And the sons of *_Raamah_*: Sheba and Dedan.
* `1Ch 1:9` And the sons of Cush: Seba, Havilah, Sabta, *_Raamah_*, and Sabtecha. And the sons of *_Raamah_*: Sheba and Dedan.
* `Ezk 27:22` The merchants of Sheba and *_Raamah_*, they were your merchants. They occupied in your fairs with chief of all spices, with all precious stones and gold.

_3 verses containing RAAMAH_

== RAAMIAH

* `Neh 7:7` Who came with Zerubbabel, Jeshua, Nehemiah, Azariah, *_Raamiah_*, Nahamani, Mordecai, Bilshan, Mispereth, Bigvai, Nehum, and Baanah. The number of the men of the people of Israel was this:

_1 verse containing RAAMIAH_

== RAAMSES

* `Exo 1:11` Therefore, they set over them task-masters to afflict them with their burdens. And they built for Pharaoh treasure-cities: Pithom and *_Raamses_*.

_1 verse containing RAAMSES_

== RAB-MAG

* `Jer 39:3` And all the princes of the king of Babylon came in and sat in the middle gate, even Nergal-sharezer, Samgar-nebo, Sarsechim, Rab-saris, Nergal-sharezer, and *_Rab-mag_*, with all the rest of the princes of the king of Babylon.
* `Jer 39:13` So Nebuzar-adan the captain of the guard sent, and Nebushasban, Rab-saris, Nergal-sharezer, *_Rab-mag_*, and all the king of Babylon's princes,

_2 verses containing RAB-MAG_

== RAB-SARIS

* `2Ki 18:17` And the king of Assyria sent Tartan, *_Rab-saris_*, and Rab-shakeh from Lachish to king Hezekiah with a great army against Jerusalem. And they went up and came to Jerusalem. And when they had come up, they came and stood by the conduit of the upper pool, which is in the highway of the fuller's field.
* `Jer 39:3` And all the princes of the king of Babylon came in and sat in the middle gate, even Nergal-sharezer, Samgar-nebo, Sarsechim, *_Rab-saris_*, Nergal-sharezer, and Rab-mag, with all the rest of the princes of the king of Babylon.
* `Jer 39:13` So Nebuzar-adan the captain of the guard sent, and Nebushasban, *_Rab-saris_*, Nergal-sharezer, Rab-mag, and all the king of Babylon's princes,

_3 verses containing RAB-SARIS_

== RAB-SHAKEH

* `2Ki 18:17` And the king of Assyria sent Tartan, Rab-saris, and *_Rab-shakeh_* from Lachish to king Hezekiah with a great army against Jerusalem. And they went up and came to Jerusalem. And when they had come up, they came and stood by the conduit of the upper pool, which is in the highway of the fuller's field.
* `2Ki 18:19` And *_Rab-shakeh_* said to them, "Speak now to Hezekiah, 'Thus says the great king, the king of Assyria: "What confidence is this in which you trust?
* `2Ki 18:26` Then Eliakim the son of Hilkiah, Shebna, and Joah said to *_Rab-shakeh_*, "Speak, I pray you, to your servants in the Syrian language, for we understand it. And do not talk with us in the Jews' language in the ears of the people who are on the wall."
* `2Ki 18:27` But *_Rab-shakeh_* said to them, "Has my master sent me to your master and to you to speak these words? Has he not sent me to the men who sit on the wall, who will have to feed on their vilest excretions with you?"
* `2Ki 18:28` Then *_Rab-shakeh_* stood and cried with a loud voice in the Jews' language and spoke, saying, "Hear the word of the great king, the king of Assyria.
* `2Ki 18:37` Then Eliakim the son of Hilkiah who was over the household, Shebna the scribe, and Joah the son of Asaph the recorder, came to Hezekiah with their clothes rent and told him the words of *_Rab-shakeh_*.
* `2Ki 19:4` It may be that the LORD your God will hear all the words of *_Rab-shakeh_*, whom the king of Assyria his master has sent to reproach the living God, and will reprove the words which the LORD your God has heard. Therefore, lift up your prayer for the remnant that is left.'"
* `2Ki 19:8` So *_Rab-shakeh_* returned and found the king of Assyria warring against Libnah, for he had heard that he had departed from Lachish.

_8 verses containing RAB-SHAKEH_

== RABBAH

* `Jsh 13:25` And their border was Jazer, and all the cities of Gilead, and half the land of the children of Ammon, to Aroer that is before *_Rabbah_*;
* `Jsh 15:60` Kirjath-baal (which is Kirjath-jearim) and *_Rabbah_*; two cities with their villages.
* `2Sa 11:1` And it came to pass after the year had expired, at the time when kings go forth to battle, that David sent Joab and his servants with him and all Israel. And they destroyed the children of Ammon and destroyed *_Rabbah_*. But David remained in Jerusalem.
* `2Sa 12:26` And Joab fought against *_Rabbah_* of the children of Ammon and took the royal city.
* `2Sa 12:27` And Joab sent messengers to David and said, "I have fought against *_Rabbah_* and have taken the city of waters.
* `2Sa 12:29` And David collected all the people, went to *_Rabbah_*, fought against it, and took it.
* `2Sa 17:27` And it came to pass when David had come to Mahanaim, that Shobi the son of Nahash of *_Rabbah_* of the children of Ammon, Machir the son of Ammiel of Lo-debar, and Barzillai the Gileadite of Rogelim,
* `1Ch 20:1` And it came to pass, that after the year had expired, at the time that kings go out to battle, Joab led forth the power of the army and wasted the country of the children of Ammon and came and besieged *_Rabbah_*. But David remained in Jerusalem. And Joab smote *_Rabbah_* and destroyed it.
* `Jer 49:2` Therefore, behold, the days come," says the LORD, "that I will cause an alarm of war to be heard in *_Rabbah_* of the Ammonites, and it shall be a desolate heap, and her daughters shall be burned with fire. Then Israel shall be heir to those who were his heirs," says the LORD.
* `Jer 49:3` "Howl, O Heshbon, for Ai is laid waste. Cry, you daughters of *_Rabbah_*. Gird yourselves with sackcloth. Lament, and run to and fro by the hedges. For their king shall go into captivity, and his priests and his princes together.
* `Ezk 21:20` Appoint a way that the sword may come to *_Rabbah_* of the Ammonites, and to Judah in Jerusalem the fortified.
* `Ezk 25:5` And I will make *_Rabbah_* a stable for camels and the Ammonites a couching-place for flocks. And you shall know that I am the LORD."
* `Amo 1:14` But I will kindle a fire in the wall of *_Rabbah_*, and it shall devour its palaces, with shouting in the day of battle, with a tempest in the day of the whirlwind.

_13 verses containing RABBAH_

== RABBATH

* `Deu 3:11` For only Og king of Bashan remained of the remnant of the Rephaim. Behold, his bedstead was a bedstead of iron. Is it not in *_Rabbath_* of the children of Ammon? Nine cubits was its length and four cubits its breadth, after the cubit of a man.

_1 verse containing RABBATH_

== RABBI

* `Mth 23:7` Greetings in the markets, and to be called by men, '*_Rabbi_*, *_Rabbi_*.'
* `Mth 23:8` But do not be called *_Rabbi_*, for One is your Teacher, even Christ, and all of you are brothers.
* `Jhn 1:38` Then Jesus turned and saw them following, and says to them, "What do you seek?" They said to him, "*_Rabbi_*"—which is to say, being interpreted, Master—"where do you dwell?"
* `Jhn 1:49` Nathanael answered and said to him, "*_Rabbi_*, you are the Son of God. You are the King of Israel."
* `Jhn 3:2` The same came to Jesus by night and said to him, "*_Rabbi_*, we know that you are a teacher come from God, for no man can do these miracles that you do unless God is with him."
* `Jhn 3:26` And they came to John and said to him, "*_Rabbi_*, he who was with you beyond the Jordan, to whom you bore testimony, behold, the same baptizes, and all men come to him."
* `Jhn 6:25` And when they had found him on the other side of the sea, they said to him, "*_Rabbi_*, when did you come here?"

_7 verses containing RABBI_

== RABBITH

* `Jsh 19:20` *_Rabbith_*, Kishion, Abez,

_1 verse containing RABBITH_

== RABBONI

* `Jhn 20:16` Jesus says to her, "Mary." She turned herself and says to him, "*_Rabboni_*," (which is to say, Master).

_1 verse containing RABBONI_

== RABSHAKEH

* `Isa 36:2` And the king of Assyria sent *_Rabshakeh_* from Lachish to Jerusalem against king Hezekiah with a great army. And he stood by the conduit of the upper pool in the highway of the fuller's field.
* `Isa 36:4` And *_Rabshakeh_* said to them, "Say now to Hezekiah, 'Thus says the great king, the king of Assyria: "What confidence is this in which you trust?
* `Isa 36:11` Then Eliakim, Shebna, and Joah said to *_Rabshakeh_*, "Speak, I pray you, to your servants in the Syrian language, for we understand it. And do not speak to us in the Jew's language, in the ears of the people who are on the wall."
* `Isa 36:12` But *_Rabshakeh_* said, "Has my master sent me to your master and to you to speak these words? Has he not sent me to the men who sit upon the wall, who will have to devour their vilest excretions with you?"
* `Isa 36:13` Then *_Rabshakeh_* stood, and cried with a loud voice in the Jew's language and said, "Hear the words of the great king, the king of Assyria.
* `Isa 36:22` Then Eliakim the son of Hilkiah, who was over the household, Shebna the scribe, and Joah, the son of Asaph, the recorder, came to Hezekiah with their clothes rent and told him the words of *_Rabshakeh_*.
* `Isa 37:4` It may be that the LORD your God will hear the words of *_Rabshakeh_*, whom the king of Assyria his master has sent to reproach the living God, and will reprove the words which the LORD your God has heard. Therefore, lift up your prayer for the remnant that is left.'"
* `Isa 37:8` So *_Rabshakeh_* returned and found the king of Assyria warring against Libnah, for he had heard that he had departed from Lachish.

_8 verses containing RABSHAKEH_

== RACA

* `Mth 5:22` But I say to you, that whoever is angry with his brother without a cause shall be in danger of the judgment. And whoever says to his brother, '*_Raca_*,' shall be in danger of the council. And whoever says, 'You fool,' shall be in danger of hell-fire.

_1 verse containing RACA_

== RACE

* `Psa 19:5` It is like a bridegroom coming out of his chamber. It rejoices like a strong man running a *_race_*.
* `Ecc 9:11` I returned, and saw under the sun, that the *_race_* is not to the swift, nor the battle to the strong, neither yet bread to the wise, nor yet riches to men of understanding, nor yet favor to men of skill, but time and chance happens to them all.
* `1Co 9:24` Do you not know, that those who run in a *_race_* all run, but one receives the prize? Likewise run so that you may obtain.
* `Heb 12:1` Therefore, seeing we also are encompassed with so great a cloud of witnesses, let us lay aside every weight and the sin which so easily besets us, and let us run with patience the *_race_* that is set before us,

_4 verses containing RACE_

== RACHAL

* `1Sa 30:29` To those who were in *_Rachal_*, to those who were in the cities of the Jerahmeelites, to those who were in the cities of the Kenites,

_1 verse containing RACHAL_

== RACHEL

* `Gen 29:6` And he said to them, "Is he well?" And they said, "He is well, and behold, *_Rachel_* his daughter comes with the sheep."
* `Gen 29:9` And while he was still speaking with them, *_Rachel_* came with her father's sheep, for she kept them.
* `Gen 29:10` And it came to pass when Jacob saw *_Rachel_*, the daughter of Laban his mother's brother, and the sheep of Laban his mother's brother, that Jacob went near and rolled the stone from the well's mouth and watered the flock of Laban his mother's brother.
* `Gen 29:11` And Jacob kissed *_Rachel_* and lifted up his voice and wept.
* `Gen 29:12` And Jacob told *_Rachel_* that he was her father's brother and that he was Rebekah's son. And she ran and told her father.
* `Gen 29:16` And Laban had two daughters: the name of the elder was Leah and the name of the younger was *_Rachel_*.
* `Gen 29:17` Leah was tender-eyed, but *_Rachel_* was beautiful and well-favored.
* `Gen 29:18` And Jacob loved *_Rachel_* and said, "I will serve you seven years for *_Rachel_* your younger daughter."
* `Gen 29:20` And Jacob served seven years for *_Rachel_*, and they seemed to him only a few days because of the love he had for her.
* `Gen 29:25` And it came to pass, that in the morning, behold, it was Leah. And he said to Laban, "What is this you have done to me? Did I not serve with you for *_Rachel_*? Why then have you deceived me?"
* `Gen 29:28` And Jacob did so and fulfilled her week. And he gave him *_Rachel_*, his daughter, for a wife also.
* `Gen 29:29` And Laban gave Bilhah his servant to *_Rachel_* his daughter to be her servant.
* `Gen 29:30` And he went in also to *_Rachel_*, and he also loved *_Rachel_* more than Leah, and served with him for seven more years.
* `Gen 29:31` And when the LORD saw that Leah was hated, he made her fruitful, but *_Rachel_* was barren.
* `Gen 30:1` And when *_Rachel_* saw that she bore Jacob no children, *_Rachel_* envied her sister and said to Jacob, "Give me children, or else I die."
* `Gen 30:2` And Jacob's anger was kindled against *_Rachel_* and he said, "Am I in God's stead, who has withheld from you the fruit of the womb?"
* `Gen 30:6` And *_Rachel_* said, "God has judged me and has also heard my voice and has given me a son." Therefore, she called his name Dan.
* `Gen 30:7` And Bilhah, *_Rachel_*'s servant, conceived again and bore Jacob a second son.
* `Gen 30:8` And *_Rachel_* said, "With great wrestlings I have wrestled with my sister and I have prevailed." And she called his name Naphtali.
* `Gen 30:14` And Reuben went, in the days of wheat-harvest, and found mandrakes in the field and brought them to his mother Leah. Then *_Rachel_* said to Leah, "Give me, I pray you, some of your son's mandrakes."
* `Gen 30:15` And she said to her, "Is it a small matter that you have taken my husband? And would you take away my son's mandrakes also?" And *_Rachel_* said, "Therefore, he shall lie with you tonight for your son's mandrakes."
* `Gen 30:22` And God remembered *_Rachel_*. And God listened to her and rendered her fruitful.
* `Gen 30:25` And it came to pass when *_Rachel_* had borne Joseph, that Jacob said to Laban, "Send me away so that I may go to my own place and to my country.
* `Gen 31:4` And Jacob sent and called *_Rachel_* and Leah into the field where his flock was,
* `Gen 31:14` And *_Rachel_* and Leah answered and said to him, "Is there still any portion or inheritance for us in our father's house?
* `Gen 31:19` And Laban went to shear his sheep, and *_Rachel_* had stolen the images that were her father's.
* `Gen 31:32` With whomever you find your gods, do not let him live. Before our brothers, discern what is yours with me and take it." For Jacob did not know that *_Rachel_* had stolen them.
* `Gen 31:33` And Laban went into Jacob's tent, into Leah's tent, and into the two women-servants' tents, but he did not find them. Then he went out of Leah's tent and entered into *_Rachel_*'s tent.
* `Gen 31:34` Now *_Rachel_* had taken the images and put them in the camel's saddle and sat upon them. And Laban searched all the tent, but did not find them.
* `Gen 33:1` And Jacob lifted up his eyes and looked, and behold, Esau came, and with him four hundred men. And he divided the children between Leah, *_Rachel_*, and the two women-servants.
* `Gen 33:2` And he put the women-servants and their children foremost, Leah and her children after, and *_Rachel_* and Joseph hindmost.
* `Gen 33:7` And Leah also came near with her children, and they bowed themselves. And afterward Joseph and *_Rachel_* came near, and they bowed themselves.
* `Gen 35:16` And they journeyed from Beth-el. And there was only a little distance to come to Ephrath, and *_Rachel_* travailed and had hard labor.
* `Gen 35:19` And *_Rachel_* died and was buried on the way to Ephrath, which is Beth-lehem.
* `Gen 35:20` And Jacob set a pillar on her grave. That is the pillar of *_Rachel_*'s grave to this day.
* `Gen 35:24` The sons of *_Rachel_*: Joseph and Benjamin.
* `Gen 35:25` And the sons of Bilhah, *_Rachel_*'s servant: Dan and Naphtali.
* `Gen 46:19` The sons of *_Rachel_* Jacob's wife: Joseph and Benjamin.
* `Gen 46:22` These are the sons of *_Rachel_* who were born to Jacob. All the souls were fourteen.
* `Gen 46:25` These are the sons of Bilhah, whom Laban gave to *_Rachel_* his daughter, and she bore these to Jacob. All the souls were seven.
* `Gen 48:7` And as for me, when I came from Padan, *_Rachel_* died beside me in the land of Canaan, on the way when there was only a little distance to come to Ephrath, and I buried her there on the way of Ephrath (the same is Beth-lehem)."
* `Rth 4:11` And all the people who were in the gate and the elders said, "We are witnesses. May the LORD make the woman who has come into your house like *_Rachel_* and like Leah, both of whom built the house of Israel. And may you do worthily in Ephratah and be famous in Beth-lehem.
* `1Sa 10:2` When you have departed from me today, you shall find two men by *_Rachel_*'s sepulcher in the border of Benjamin at Zelzah, and they will say to you, 'The donkeys which you went to seek are found, and behold, your father has ceased caring for the donkeys and sorrows for you, saying, "What shall I do for my son?"'
* `Jer 31:15` Thus says the LORD: "A voice was heard in Ramah, lamentation and bitter weeping. *_Rachel_* weeping for her children refused to be comforted for her children, because they were no more."
* `Mth 2:18` "In Ramah there was a voice heard, lamentation, weeping, and great mourning, *_Rachel_* weeping for her children, and would not be comforted, because they are no more."

_45 verses containing RACHEL_

== RADDAI

* `1Ch 2:14` Nethaneel the fourth, *_Raddai_* the fifth,

_1 verse containing RADDAI_

== RADIANT

* `Psa 34:5` They looked to him and were *_radiant_*, and their faces were not ashamed.

_1 verse containing RADIANT_

== RAFTERS

* `Sos 1:17` [Gentleman:] The beams of our house are cedar and our *_rafters_* of fir.

_1 verse containing RAFTERS_

== RAFTS

* `1Ki 5:9` My servants shall bring them down from Lebanon to the sea, and I will convey them by sea in *_rafts_* to the place that you shall appoint me and cause them to be discharged there, and you shall receive them. And you shall accomplish my desire in giving food for my household."
* `2Ch 2:16` And we will cut wood out of Lebanon, as much as you shall need, and we will bring it to you in *_rafts_* by sea to Joppa, and you may convey it to Jerusalem."

_2 verses containing RAFTS_

== RAGE

* `2Ki 5:12` Are Abana and Pharpar, rivers of Damascus, not better than all the waters of Israel? May I not wash in them and be clean?" So he turned and went away in a *_rage_*.
* `2Ki 19:27` 'But I know your abode, your going out, your coming in, and your *_rage_* against me.
* `2Ki 19:28` Because your *_rage_* against me and your tumult has come up into my ears, therefore I will put my hook in your nose and my bridle in your lips, and I will turn you back on the way by which you came.
* `2Ch 16:10` Then Asa was angry with the seer and put him in a prison house, for he was in a *_rage_* with him because of this thing. And Asa oppressed some of the people the same time.
* `2Ch 28:9` But a prophet of the LORD was there, whose name was Oded, and he went out before the army that came to Samaria and said to them, "Behold, because the LORD God of your fathers was angry with Judah, he has delivered them into your hand, and you have slain them in a *_rage_* that reaches to heaven.
* `Job 39:24` He swallows the ground with fierceness and *_rage_*, neither does he believe that it is the sound of the trumpet.
* `Job 40:11` Cast abroad the *_rage_* of your wrath. Behold everyone who is proud and abase him.
* `Psa 2:1` Why do the heathen *_rage_* and the people plot a vain thing?
* `Psa 7:6` Arise, O LORD, in your anger, lift up yourself because of the *_rage_* of my enemies, and awake for me to the judgment that you have commanded.
* `Pro 6:34` For jealousy is the *_rage_* of a man; therefore, he will not spare in the day of vengeance.
* `Isa 37:28` But I know your sitting down, your going out, your coming in, and your *_rage_* against me.
* `Isa 37:29` Because your *_rage_* against me and your tumult have come up into my ears, therefore I will put my hook in your nose and my bridle in your lips, and I will turn you back by the way by which you came.
* `Jer 46:9` Come up, you horses, and *_rage_*, you chariots, and let the mighty men come forth—the Cushites and the Libyans who handle the shield, and the Lydians who handle and bend the bow.
* `Dan 3:13` Then Nebuchadnezzar in his *_rage_* and fury commanded to bring Shadrach, Meshach, and Abed-nego. Then they brought these men before the king.
* `Hos 7:16` They return, but not to the most High. They are like a deceitful bow. Their princes shall fall by the sword for the *_rage_* of their tongue. This shall be their derision in the land of Egypt."
* `Nah 2:4` The chariots shall *_rage_* in the streets. They shall jostle one against another in the broad ways. They shall seem like torches and they shall run like the lightnings.
* `Act 4:25` Who, by the mouth of your servant David, said, 'Why did the heathen *_rage_*, and the people plot vain things?

_17 verses containing RAGE_

== RAGED

* `Psa 46:6` The heathen *_raged_*. The kingdoms were moved. He uttered his voice, and the earth melted.

_1 verse containing RAGED_

== RAGES

* `Pro 14:16` A wise man fears and departs from evil, but the fool *_rages_* and is confident.
* `Pro 29:9` If a wise man contends with a foolish man, whether he *_rages_* or laughs, there is no rest.

_2 verses containing RAGES_

== RAGGED

* `Isa 2:21` And they shall go into the clefts of the rocks and into the tops of the *_ragged_* rocks from before the fear of the LORD and the glory of his majesty, when he arises to shake the earth terribly.

_1 verse containing RAGGED_

== RAGING

* `Psa 89:9` You rule the *_raging_* of the sea. When its waves arise, you still them.
* `Pro 20:1` Wine is a mocker, strong drink is *_raging_*, and whoever is deceived by it is not wise.
* `Jna 1:15` So they took Jonah and cast him into the sea. And the sea ceased from her *_raging_*.
* `Luk 8:24` And they came to him and awoke him, saying, "Master, master, we perish." Then he arose and rebuked the wind and the *_raging_* of the water. Then they ceased, and there was a calm.
* `Jde 1:13` They are *_raging_* waves of the sea foaming out their own shame. They are wandering stars to whom the blackness of darkness is reserved forever.

_5 verses containing RAGING_

== RAGS

* `Pro 23:21` For the drunkard and the glutton shall come to poverty, and drowsiness shall clothe a man with *_rags_*.
* `Isa 64:6` But we are all like an unclean thing, and all our righteousnesses are like filthy *_rags_*. And we all fade like a leaf. And our iniquities, like the wind, have taken us away.
* `Jer 38:11` So Ebed-melech took the men with him and went into the house of the king under the treasury, took from there old cast cloths and old decayed *_rags_*, and let them down by cords into the dungeon to Jeremiah.
* `Jer 38:12` And Ebed-melech the Cushite said to Jeremiah, "Now put these old cast cloths and decayed *_rags_* under your armpits under the cords." And Jeremiah did so.

_4 verses containing RAGS_

== RAGUEL

* `Num 10:29` And Moses said to Hobab, the son of *_Raguel_* the Midianite, Moses's father-in-law, "We are journeying to the place of which the LORD said, 'I will give it to you.' Come with us, and we will do you good, for the LORD has spoken good concerning Israel."

_1 verse containing RAGUEL_

== RAHAB

* `Jsh 2:1` And Joshua the son of Nun sent from Shittim two men to spy secretly, saying, "Go, view the land, even Jericho." And they went and came into the house of a harlot named *_Rahab_* and lodged there.
* `Jsh 2:3` And the king of Jericho sent to *_Rahab_*, saying, "Bring forth the men who have come to you, who have entered into your house, for they have come to search out all the country."
* `Jsh 6:17` And the city shall be accursed, even it and all who are in it, to the LORD. Only *_Rahab_* the harlot shall live—she and all who are with her in the house—because she hid the messengers that we sent.
* `Jsh 6:23` And the young men who were spies went in and brought out *_Rahab_*, her father, her mother, her brothers, and all that she had. And they brought out all her kindred and left them outside the camp of Israel.
* `Jsh 6:25` But *_Rahab_* the harlot, her father's household, and all that she had, Joshua saved alive. And she dwells in Israel even to this day because she hid the messengers which Joshua sent to spy out Jericho.
* `Psa 87:4` "I will make mention of *_Rahab_* and Babylon to those who know me. Behold, Philistia, Tyre, and also Cush: 'This one was born there.'"
* `Psa 89:10` You have broken *_Rahab_* in pieces like one who is slain. You have scattered your enemies with your strong arm.
* `Isa 30:7` For the Egyptian shall help in vain and to no purpose. Therefore, I have called her, "*_Rahab_* who sits still."
* `Isa 51:9` Awake, awake, put on your strength, O arm of the LORD. Awake, as in the ancient days, in the generations of old. Is it not you who cut *_Rahab_* and wounded the dragon?
* `Mth 1:5` Salmon begot Boaz by *_Rahab_*, Boaz begot Obed by Ruth, Obed begot Jesse,
* `Heb 11:31` By faith the harlot *_Rahab_* did not perish with those who did not believe, as she had received the spies with peace.
* `Jms 2:25` Likewise also, was *_Rahab_* the harlot not justified by works when she had received the messengers and had sent them out another way?

_12 verses containing RAHAB_

== RAHAM

* `1Ch 2:44` And Shema begot *_Raham_* the father of Jorkoam, and Rekem begot Shammai.

_1 verse containing RAHAM_

== RAIDERS

* `1Sa 13:17` And the *_raiders_* came out of the camp of the Philistines in three companies: one company turned to the way that leads to Ophrah to the land of Shual,
* `1Sa 14:15` And there was a trembling in the host, in the field, and among all the people. The garrison and the *_raiders_* also trembled, and the earth quaked, and it was a very great trembling.
* `2Ki 17:20` And the LORD rejected all the offspring of Israel, afflicted them, and delivered them into the hand of *_raiders_* until he had cast them out of his sight.

_3 verses containing RAIDERS_

== RAIDS

* `Hos 7:1` "When I would have healed Israel, then the iniquity of Ephraim and the wickedness of Samaria was disclosed, for they commit falsehood. And the thief comes in, and the troop of robbers *_raids_* outside.

_1 verse containing RAIDS_

== RAIL

* `2Ch 32:17` He also wrote letters to *_rail_* at the LORD God of Israel and to speak against him, saying, "As the gods of the nations of other lands have not delivered their people out of my hand, so shall the God of Hezekiah not deliver his people out of my hand."

_1 verse containing RAIL_

== RAILED

* `1Sa 25:14` But one of the young men told Abigail, Nabal's wife, saying, "Behold, David sent messengers from the wilderness to salute our master, and he *_railed_* at them.
* `Mrk 15:29` And those who passed by, *_railed_* on him, wagging their heads, and saying, "Ah, you who destroy the temple and build it in three days,
* `Luk 23:39` And one of the malefactors who were hanged *_railed_* on him, saying, "If you are Christ, save yourself and us."

_3 verses containing RAILED_

== RAILER

* `1Co 5:11` But now I have written to you not to keep company with any man who is called a brother if he is a lewd person, covetous, an idolater, a *_railer_*, a drunkard, or an extortioner. Do not even eat with such a person.

_1 verse containing RAILER_

== RAILING

* `1Pe 3:9` Not rendering evil for evil or *_railing_* for *_railing_*, but on the contrary, blessing, knowing that you are called to this, so that you should inherit a blessing.
* `2Pe 2:11` Whereas angels, who are greater in power and might, do not bring *_railing_* accusation against them before the Lord.
* `Jde 1:9` Yet Michael the archangel, when contending with the devil and disputing about the body of Moses, did not dare bring against him a *_railing_* accusation, but said, "May the Lord rebuke you."

_3 verses containing RAILING_

== RAILINGS

* `1Ti 6:4` He is proud, knowing nothing, but doting about questions and strifes of words, from which comes envy, strife, *_railings_*, evil surmisings,

_1 verse containing RAILINGS_

== RAIN

* `Gen 2:5` And no plant of the field was yet in the earth and no herb of the field had yet grown, because the LORD God had not caused it to *_rain_* on the earth and there was not a man to till the ground.
* `Gen 7:4` For after seven more days, I will cause it to *_rain_* upon the earth forty days and forty nights. And every living substance that I have made I will destroy from the face of the earth."
* `Gen 7:12` And the *_rain_* was upon the earth forty days and forty nights.
* `Gen 8:2` Also the fountains of the deep and the windows of heaven were stopped, and the *_rain_* from heaven was restrained,
* `Exo 9:18` Behold, tomorrow about this time I will cause it to *_rain_* a very grievous hail such as has not been in Egypt since its foundation even until now.
* `Exo 9:33` And Moses went out of the city from Pharaoh and spread abroad his hands to the LORD, and the thunders and hail ceased, and the *_rain_* was not poured upon the earth.
* `Exo 9:34` And when Pharaoh saw that the *_rain_* and the hail and the thunders had ceased, he sinned yet again and hardened his heart—he and his servants.
* `Exo 16:4` Then the LORD said to Moses, "Behold, I will *_rain_* bread from heaven for you. And the people shall go out and gather a certain rate every day so that I may prove them, whether they will walk in my law or not.
* `Lev 26:4` Then I will give you *_rain_* in due season, and the land shall yield her increase and the trees of the field shall yield their fruit,
* `Deu 11:11` But the land that you are entering to possess is a land of hills and valleys, and drinks water from the *_rain_* of heaven,
* `Deu 11:14` That I will give you the *_rain_* of your land in its due season, the former *_rain_* and the latter *_rain_*, so that you may gather in your grain, your wine, and your oil.
* `Deu 11:17` And the LORD'S wrath be kindled against you, and he restrain the heavens so that there shall be no *_rain_*, and the land shall not yield her fruit; and lest you perish quickly from off the good land which the LORD gives you.
* `Deu 28:12` The LORD shall open to you his good treasure, the heavens, to give *_rain_* to your land in its season and to bless all the work of your hand. And you shall lend to many nations, and you shall not borrow.
* `Deu 28:24` The LORD shall make the *_rain_* of your land powder and dust. From heaven it shall come down upon you until you are destroyed.
* `Deu 32:2` My doctrine shall drop as the *_rain_*, my speech shall distill as the dew, as the small *_rain_* upon the tender herb, and as the showers upon the grass.
* `1Sa 12:17` Is it not wheat-harvest today? I will call to the LORD, and he will send thunder and *_rain_* so that you may perceive and see that your wickedness is great which you have done in the sight of the LORD in asking for yourselves a king."
* `1Sa 12:18` So Samuel called to the LORD. And the LORD sent thunder and *_rain_* that day, and all the people greatly feared the LORD and Samuel.
* `2Sa 1:21` "You mountains of Gilboa, let there be no dew, neither *_rain_* upon you, nor fields of offerings, for there the shield of the mighty is vilely cast away, the shield of Saul, as though he had not been anointed with oil.
* `2Sa 23:4` And he shall be like the light of the morning when the sun rises, even a morning without clouds, like the tender grass springing out of the earth from clear shining after the *_rain_*.'
* `1Ki 8:35` "When heaven is shut up and there is no *_rain_* because they have sinned against you, if they pray toward this place, confess your name, and turn from their sin when you afflict them,
* `1Ki 8:36` Then hear in heaven and forgive the sin of your servants and of your people Israel so that you may teach them the good way in which they should walk and give *_rain_* upon your land which you have given to your people for an inheritance.
* `1Ki 17:1` And Elijah the Tishbite who was of the inhabitants of Gilead said to Ahab, "As the LORD God of Israel lives, before whom I stand, there shall not be dew nor *_rain_* these years, but according to my word."
* `1Ki 17:7` And it came to pass after a while, that the brook dried up because there had been no *_rain_* in the land.
* `1Ki 17:14` For thus says the LORD God of Israel: 'The barrel of meal shall not waste, neither shall the cruse of oil fail, until the day that the LORD sends *_rain_* upon the earth.'"
* `1Ki 18:1` And it came to pass after many days, that the word of the LORD came to Elijah in the third year, saying, "Go, show yourself to Ahab, and I will send *_rain_* upon the earth."
* `1Ki 18:41` And Elijah said to Ahab, "Go up, eat and drink, for there is a sound of abundance of *_rain_*."
* `1Ki 18:44` And it came to pass at the seventh time, that he said, "Behold, there arises a little cloud out of the sea about the size of a man's palm." And he said, "Go up, say to Ahab, 'Prepare your chariot and go down so that the *_rain_* may not hinder you.'"
* `1Ki 18:45` And it came to pass in a little while, that the heaven was black with clouds and wind, and there was a great *_rain_*. And Ahab rode and went to Jezreel.
* `2Ki 3:17` For thus says the LORD: 'You shall not see wind, neither shall you see *_rain_*, yet that valley shall be filled with water so that you may drink—you, your livestock, and your beasts.
* `2Ch 6:26` "When the heaven is shut and there is no *_rain_* because they have sinned against you, yet if they pray toward this place, confess your name, and turn from their sin when you afflict them,
* `2Ch 6:27` Then hear from heaven and forgive the sin of your servants and of your people Israel when you have taught them the good way in which they should walk and send *_rain_* upon your land, which you have given to your people for an inheritance.
* `2Ch 7:13` If I shut up heaven so that there is no *_rain_*, if I command the locusts to devour the land, or if I send pestilence among my people,
* `Ezr 10:9` Then all the men of Judah and Benjamin assembled at Jerusalem within three days. It was the ninth month, and the twentieth day of the month. And all the people sat in the street of the house of God, trembling because of this matter and because of the great *_rain_*.
* `Ezr 10:13` But the people are many, and it is a time of much *_rain_*, and we are not able to stand abroad, neither is this a work of one day or two, for we are many who have transgressed in this thing.
* `Job 5:10` He gives *_rain_* upon the earth and sends waters upon the fields,
* `Job 20:23` When he is about to fill his belly, God shall cast the fury of his wrath upon him and shall *_rain_* it upon him while he is eating.
* `Job 28:26` When he made a decree for the *_rain_* and a way for the lightning of the thunder,
* `Job 29:23` And they waited for me as for the *_rain_*, and they opened their mouth wide as for the latter *_rain_*.
* `Job 36:27` For he makes the drops of water small. They pour down *_rain_* according to its vapor,
* `Job 37:6` For he says to the snow, 'Be on the earth,' and likewise to the small *_rain_* and to the great *_rain_* of his strength.
* `Job 38:26` To cause it to *_rain_* on the earth where no man is, on the wilderness in which there is no man,
* `Job 38:28` Has the *_rain_* a father? Or who has begotten the drops of the dew?
* `Psa 11:6` Upon the wicked he shall *_rain_* snares, fire and brimstone, and a horrible tempest. This shall be the portion of their cup.
* `Psa 68:9` You, O God, sent a plentiful *_rain_*, by which you confirmed your inheritance when it was weary.
* `Psa 72:6` He shall come down like *_rain_* upon the mown grass, like showers that water the earth.
* `Psa 84:6` Passing through the valley of Baca they make it a well. The *_rain_* also fills the pools.
* `Psa 105:32` He gave them hail for *_rain_* and flaming fire in their land.
* `Psa 135:7` He causes the vapors to ascend from the ends of the earth. He makes lightnings for the *_rain_*. He brings the wind out of his treasuries.
* `Psa 147:8` Who covers the heaven with clouds, who prepares *_rain_* for the earth, who makes grass to grow upon the mountains.
* `Pro 16:15` In the light of a king's countenance is life, and his favor is like a cloud of the latter *_rain_*.
* `Pro 25:14` Whoever boasts himself of a false gift is like clouds and wind without *_rain_*.
* `Pro 25:23` The north wind drives away *_rain_*, and so does an angry countenance to a backbiting tongue.
* `Pro 26:1` As snow in summer and as *_rain_* in harvest, so honor is not appropriate for a fool.
* `Pro 28:3` A poor man who oppresses the poor is like a sweeping *_rain_* which leaves no food.
* `Ecc 11:3` If the clouds are full of *_rain_*, they empty themselves upon the earth. And if the tree falls toward the south or toward the north, in the place where the tree falls, there it shall be.
* `Ecc 12:2` While the sun, the light, the moon, or the stars are not darkened, nor the clouds return after the *_rain_*;
* `Sos 2:11` For behold, the winter is past, the *_rain_* is over and gone.
* `Isa 4:6` And there shall be a tabernacle for a shade in the day-time from the heat, for a place of refuge, and for a covert from storm and from *_rain_*.
* `Isa 5:6` And I will lay it waste. It shall not be pruned nor dug, but there shall come up briers and thorns. I will also command the clouds that they *_rain_* no *_rain_* upon it.
* `Isa 30:23` Then he shall give the *_rain_* of your seed, with which you shall sow the ground, and bread of the increase of the earth, and it shall be fat and plenteous. In that day your livestock shall feed in large pastures.
* `Isa 44:14` He hews down cedars for himself and takes the cypress and the oak, which he strengthens for himself among the trees of the forest. He plants an ash, and the *_rain_* nourishes it.
* `Isa 55:10` For as the *_rain_* comes down, and the snow from heaven, and does not return there, but waters the earth and makes it bring forth and bud so that it may give seed to the sower and bread to the eater,
* `Jer 3:3` Therefore, the showers have been withheld and there has been no latter *_rain_*. Yet you had a harlot's forehead and you refused to be ashamed.
* `Jer 5:24` They do not say in their heart, "Let us now fear the LORD our God who gives *_rain_*, both the former and the latter, in its season. He reserves to us the appointed weeks of harvest."
* `Jer 10:13` When he utters his voice, there is a multitude of waters in the heavens, and he causes the vapors to ascend from the ends of the earth. He makes lightnings with *_rain_* and brings forth the wind out of his treasures.
* `Jer 14:4` Because the ground is cracked, for there was no *_rain_* on the earth, the plowmen were ashamed, they covered their heads.
* `Jer 14:22` Are there any among the vanities of the Gentiles who can cause *_rain_*? Or can the heavens give showers? Are you not he, O LORD our God? Therefore, we will wait upon you, for you have made all these things.
* `Jer 51:16` When he utters his voice, there is a multitude of waters in the heavens, and he causes the vapors to ascend from the ends of the earth. He makes lightnings with *_rain_* and brings forth the wind out of his treasures.
* `Ezk 1:28` Like the appearance of the bow that is in the cloud in the day of *_rain_*, so was the appearance of the brightness around. This was the appearance of the likeness of the glory of the LORD. And when I saw it, I fell upon my face, and I heard the voice of someone speaking.
* `Ezk 38:22` And I will plead against him with pestilence and with blood, and I will *_rain_* upon him, upon his bands, and upon the many people who are with him, an overflowing *_rain_*, with great hailstones, fire, and brimstone.
* `Hos 6:3` Then we shall know, if we follow on to know the LORD. His going forth is prepared as the morning, and he will come to us as the *_rain_*, as the latter and former *_rain_* to the earth."
* `Joe 2:23` Be glad then, children of Zion, and rejoice in the LORD your God, for he has given you the former *_rain_* moderately. He will cause to come down for you the *_rain_*, the former *_rain_* and the latter *_rain_*, in the first month.
* `Amo 4:7` "And also I have withheld the *_rain_* from you when there were yet three months to the harvest. And I caused it to *_rain_* upon one city and did not cause it to *_rain_* upon another city. One piece was rained upon, and the piece on which it did not *_rain_* withered.
* `Zch 10:1` Ask the LORD for *_rain_* in the time of the latter *_rain_*. The LORD will make bright clouds and give them showers of *_rain_*, and to everyone grass in the field.
* `Zch 14:17` And it shall be, that whoever will not come up of all the families of the earth to Jerusalem to worship the King, the LORD of hosts, there shall be no *_rain_* upon them.
* `Zch 14:18` And if the family of Egypt shall not go up and shall not come, they shall have no *_rain_*. There the plague shall be, with which the LORD will smite the heathen who do not come up to keep the feast of tabernacles.
* `Mth 5:45` So that you may be the children of your Father who is in heaven. For he makes his sun to rise on the evil and on the good, and sends *_rain_* on the just and on the unjust.
* `Mth 7:25` And the *_rain_* descended, the floods came, and the winds blew and beat upon that house, and it did not fall, for it was founded upon a rock.
* `Mth 7:27` And the *_rain_* descended, the floods came, and the winds blew and beat upon that house, and it fell, and its fall was great."
* `Act 14:17` Nevertheless, he did not leave himself without witness, in that he did good, and gave us *_rain_* from heaven and fruitful seasons, filling our hearts with food and gladness."
* `Act 28:2` And the barbarous people showed us unusual kindness, for they kindled a fire and received each of us, because of the present *_rain_* and because of the cold.
* `Heb 6:7` For the ground which drinks in the *_rain_* that comes often upon it and brings forth herbs fit for them by whom it is dressed receives a blessing from God.
* `Jms 5:7` Be patient, therefore, brothers, to the coming of the Lord. Behold, the farmer waits for the precious fruit of the earth, being patient for it until it receives the early and the latter *_rain_*.
* `Jms 5:17` Elijah was a man subject to similar passions as we are, and he prayed earnestly that it might not *_rain_*, and it did not *_rain_* on the earth for three years and six months.
* `Jms 5:18` And he prayed again, and the heaven gave *_rain_* and the earth brought forth its fruit.
* `Rev 11:6` These have power to shut heaven so that it may not *_rain_* in the days of their prophecy, and they have power over waters to turn them to blood and to smite the earth with all plagues, as often as they desire.

_86 verses containing RAIN_

== RAINBOW

* `Rev 4:3` And he who sat was in appearance like a jasper and a sardius stone. And there was a *_rainbow_* around the throne in sight like an emerald.
* `Rev 10:1` And I saw another mighty angel come down from heaven clothed with a cloud and a *_rainbow_* upon his head. His face was like the sun and his feet like pillars of fire.

_2 verses containing RAINBOW_

== RAINED

* `Gen 19:24` Then the LORD *_rained_* upon Sodom and upon Gomorrah brimstone and fire from the LORD out of heaven.
* `Exo 9:23` And Moses stretched forth his rod toward heaven, and the LORD sent thunder and hail, and the fire ran along upon the ground, and the LORD *_rained_* hail upon the land of Egypt.
* `Psa 78:24` And *_rained_* down manna upon them to eat and gave them the grain of heaven.
* `Psa 78:27` He also *_rained_* flesh upon them like dust, and feathered birds like the sand of the sea.
* `Ezk 22:24` "Son of man, say to her, 'You are the land that is not cleansed nor *_rained_* upon in the day of indignation.'
* `Amo 4:7` "And also I have withheld the rain from you when there were yet three months to the harvest. And I caused it to rain upon one city and did not cause it to rain upon another city. One piece was *_rained_* upon, and the piece on which it did not rain withered.
* `Luk 17:29` But the same day that Lot went out of Sodom, it *_rained_* fire and brimstone from heaven and destroyed them all—

_7 verses containing RAINED_

== RAINS

* `Hos 10:12` Sow to yourselves in righteousness. Reap in mercy. Break up your fallow ground. For it is time to seek the LORD until he comes and *_rains_* righteousness upon you.

_1 verse containing RAINS_

== RAINY

* `Pro 27:15` A continual dropping on a very *_rainy_* day and a contentious woman are alike.

_1 verse containing RAINY_

== RAISE

* `Gen 38:8` And Judah said to Onan, "Go in to your brother's wife and marry her and *_raise_* up a child for your brother."
* `Exo 23:1` "You shall not *_raise_* a false report. Do not put your hand with the wicked to be an unrighteous witness.
* `Num 16:3` And they assembled themselves against Moses and against Aaron and said to them, "You take too much upon yourselves, seeing all the congregation are holy, each of them, and the LORD is among them. Why then do you *_raise_* yourselves above the congregation of the LORD?"
* `Deu 18:15` "The LORD your God will *_raise_* up for you a Prophet like me from the midst of you, out of your brothers. To him you shall listen.
* `Deu 18:18` I will *_raise_* up to them a Prophet like you from among their brothers and will put my words in his mouth. And he shall speak to them all that I shall command him.
* `Deu 25:7` And if the man does not want to take his brother's wife, then let his brother's wife go up to the gate to the elders and say, 'My husband's brother refuses to *_raise_* up for his brother a name in Israel. He will not perform the duty of my husband's brother.'
* `Jsh 8:29` And the king of Ai he hanged on a tree until evening. And as soon as the sun was down, Joshua commanded that they should take his carcass down from the tree, cast it at the entering of the gate of the city, and *_raise_* upon it a great heap of stones, which remains to this day.
* `Rth 4:5` Then Boaz said, "The day you buy the field from the hand of Naomi, you must also accept Ruth the Moabitess, the wife of the dead, to *_raise_* up the name of the dead upon his inheritance."
* `Rth 4:10` Moreover, Ruth the Moabitess, the wife of Mahlon, I have purchased to be my wife to *_raise_* up the name of the dead upon his inheritance, so that the name of the dead is not cut off from among his brothers and from the gate of his place. You are witnesses this day."
* `1Sa 2:35` And I will *_raise_* up for myself a faithful priest who shall do according to that which is in my heart and in my mind. And I will build him a sure house, and he shall walk before my Anointed forever.
* `2Sa 12:11` Thus says the LORD: 'Behold, I will *_raise_* up evil against you out of your own house and will take your wives before your eyes and give them to your neighbor, and he shall lie with your wives in the sight of this sun.
* `2Sa 12:17` And the elders of his house arose and went to him to *_raise_* him from the earth, but he would not, neither did he eat bread with them.
* `1Ki 14:14` Moreover, the LORD shall *_raise_* himself up a king over Israel who shall cut off the house of Jeroboam that day. But what? Even now.
* `1Ch 17:11` And it shall come to pass, when your days are fulfilled that you must go to be with your fathers, that I will *_raise_* up your offspring after you, who shall be of your sons, and I will establish his kingdom.
* `Job 19:12` His troops come together, *_raise_* up their way against me, and encamp around my tabernacle.
* `Job 30:12` Upon my right hand the disorderly youth rise. They push away my feet and *_raise_* up against me the ways of their destruction.
* `Psa 41:10` But you, O LORD, be merciful to me and *_raise_* me up so that I may requite them.
* `Psa 123:1` [A Song of Degrees.] I *_raise_* my eyes to you, O you who dwell in the heavens.
* `Isa 10:26` And the LORD of hosts will *_raise_* up a scourge for him according to the slaughter of Midian at the rock of Oreb. And as his rod was upon the sea, so he shall lift it up after the manner of Egypt.
* `Isa 15:5` My heart shall cry out for Moab. His fugitives shall flee as far as Zoar, as far as Eglath-shelishiyah. For they shall go up the ascent of Luhith with weeping, for in the way of Horonaim they shall *_raise_* a cry of destruction.
* `Isa 29:3` And I will encamp against you all around, and I will lay siege against you with siege-works and *_raise_* forts against you.
* `Isa 44:26` Who confirms the word of his servant and performs the counsel of his messengers, who says to Jerusalem, 'You shall be inhabited,' and to the cities of Judah, 'You shall be built, and I will *_raise_* up her decayed places,'
* `Isa 49:6` And he said, "It is a light thing that you should be my servant to *_raise_* up the tribes of Jacob and to restore the preserved of Israel. I will also give you as a light to the Gentiles so that you may be my salvation to the end of the earth."
* `Isa 58:12` And those amidst you shall build the old waste places. You shall *_raise_* up the foundations of many generations, and you shall be called, The Repairer of the Breach, The Restorer of Paths to Dwell In.
* `Isa 61:4` And they shall build the old wastes, they shall *_raise_* up the former desolations, and they shall repair the waste cities, the desolations of many generations.
* `Jer 23:5` "Behold, the days come," says the LORD, "that I will *_raise_* to David a righteous Branch, and a King shall reign and prosper and shall execute judgment and justice upon the earth.
* `Jer 30:9` But they shall serve the LORD their God and David their king, whom I will *_raise_* up to them.
* `Jer 50:9` For behold, I will *_raise_* and cause to come against Babylon an assembly of great nations from the north country. And they shall set themselves in array against her. From there she shall be taken. Their arrows shall be like those of an expert warrior. None shall return in vain.
* `Jer 50:32` And the most proud shall stumble and fall, and no one shall *_raise_* him up. And I will kindle a fire in his cities, and it shall devour all around him."
* `Jer 51:1` Thus says the LORD: "Behold, I will *_raise_* up a destroying wind against Babylon and against those who dwell in the midst of those who rise against me,
* `Jer 51:14` The LORD of hosts has sworn by himself, saying, "Surely I will fill you with men, as with licking-locusts, and they shall *_raise_* a shout against you."
* `Ezk 23:22` "Therefore, O Aholibah, thus says the Lord GOD: 'Behold, I will *_raise_* up your lovers against you, from whom your mind is alienated, and I will bring them against you on every side:
* `Ezk 34:29` And I will *_raise_* up for them a plant of renown, and they shall no longer be consumed with hunger in the land, neither bear the shame of the heathen anymore.
* `Hos 6:2` After two days he will revive us. On the third day he will *_raise_* us up, and we shall live in his sight.
* `Joe 3:7` Behold, I will *_raise_* them out of the place where you have sold them and will return your recompense upon your own head.
* `Amo 5:2` "The virgin of Israel has fallen. She shall no longer rise. She is forsaken upon her land. There is no one to *_raise_* her up."
* `Amo 6:14` But behold, I will *_raise_* up against you a nation, O house of Israel," says the LORD the God of hosts, "and they shall afflict you from the entrance of Hamath to the river of the wilderness."
* `Amo 9:11` In that day I will *_raise_* up the tabernacle of David that has fallen and close up its breaches. And I will *_raise_* up its ruins and build it as in the days of old,
* `Mic 5:5` And this one will be peace. When the Assyrian comes into our land and treads in our palaces, we shall *_raise_* against him seven shepherds and eight principal men.
* `Hab 1:6` For behold, I *_raise_* up the Chaldeans, that bitter and hasty nation, which shall march through the breadth of the land to possess the dwelling-places that are not theirs.
* `Zch 11:16` For behold, I will *_raise_* up a shepherd in the land who shall not visit those who are cut off, neither shall seek the young one, nor heal that which is broken, nor feed that which stands still, but he shall eat the flesh of the fat and tear their hooves in pieces.
* `Mth 3:9` And do not think to say within yourselves, 'We have Abraham for our father.' For I say to you, that God is able to *_raise_* up children to Abraham from these stones.
* `Mth 10:8` Heal the sick, cleanse the lepers, *_raise_* the dead, and cast out demons. Freely you have received, freely give.
* `Mth 22:24` Saying, "Master, Moses said, 'If a man dies, having no children, his brother shall marry his wife and *_raise_* up children for his brother.'
* `Mrk 12:19` "Master, Moses wrote to us, 'If a man's brother dies and leaves his wife and leaves no children, his brother should take his wife and *_raise_* children for his brother.'
* `Luk 3:8` Bring forth therefore fruits worthy of repentance, and do not begin to say within yourselves, 'We have Abraham for our father.' For I say to you, that God is able of these stones to *_raise_* up children to Abraham.
* `Luk 13:11` And behold, there was a woman who had a spirit of infirmity eighteen years and was bowed together and could in no way *_raise_* herself.
* `Luk 20:28` Saying, "Master, Moses wrote to us that 'if any man's brother should die, having a wife, and he should die without children, that his brother should take his wife, and *_raise_* up children for his brother.'
* `Jhn 2:19` Jesus answered and said to them, "Destroy this temple, and in three days I will *_raise_* it up."
* `Jhn 6:39` And this is the Father's will who has sent me: that of all which he has given me, I should lose nothing, but should *_raise_* it up again at the last day.
* `Jhn 6:40` And this is the will of him who sent me: that everyone who sees the Son and believes in him may have everlasting life. And I will *_raise_* him up at the last day."
* `Jhn 6:44` No man can come to me unless the Father who has sent me draws him. And I will *_raise_* him up at the last day.
* `Jhn 6:54` Whoever eats my flesh and drinks my blood has eternal life. And I will *_raise_* him up at the last day.
* `Act 2:30` Therefore, being a prophet and knowing that God had sworn to him with an oath that from the fruit of his loins, according to the flesh, he would *_raise_* up Christ to sit on his throne,
* `Act 3:22` For Moses truly said to the fathers, 'The Lord your God will *_raise_* up for you a Prophet like me from your brothers. You shall hear him in all things, whatever he says to you.
* `Act 7:37` This is that Moses who said to the children of Israel, 'The Lord your God will *_raise_* up to you a prophet like me from your brothers. You will hear him.'
* `1Co 6:14` And God has both raised up the Lord and will also *_raise_* us up by his own power.
* `1Co 15:15` And indeed we are found false witnesses of God because we have testified concerning God that he raised up Christ, whom he did not *_raise_*, if in truth the dead do not rise.
* `2Co 4:14` Knowing that he who raised the Lord Jesus will *_raise_* us also by Jesus and will present us with you.
* `Heb 11:19` He accounted that God was able to *_raise_* him even from the dead, from where also he received him in a figure.
* `Jms 5:15` And the prayer of faith will save the sick, and the Lord will *_raise_* him up, and if he has committed sins, he will be forgiven.

_61 verses containing RAISE_

== RAISED

* `Gen 21:16` And she went and sat herself down over against him a good way off, about a bow-shot, for she said, "Do not let me see the death of the child." And she sat over against him and *_raised_* her voice and wept.
* `Gen 39:15` And it came to pass when he heard that I *_raised_* my voice and cried, that he left his garment with me and fled and went out."
* `Gen 39:18` And it came to pass as I *_raised_* my voice and cried, that he left his garment with me and fled."
* `Exo 9:16` And indeed for this cause I have *_raised_* you up: to show in you my power so that my name may be declared throughout all the earth.
* `Jsh 5:7` And their children, whom he *_raised_* up in their stead, Joshua circumcised, for they were uncircumcised, because they had not circumcised them along the way.
* `Jsh 7:26` And they *_raised_* over him a great heap of stones to this day. So the LORD turned from the fierceness of his anger. Therefore, the name of that place was called the Valley of Achor to this day.
* `Jdg 2:16` Nevertheless, the LORD *_raised_* up judges who delivered them out of the hand of those who plundered them.
* `Jdg 2:18` And when the LORD *_raised_* up judges for them, the LORD was with the judge and delivered them out of the hand of their enemies all the days of the judge (for the LORD repented because of their groanings by reason of those who oppressed them and burdened them).
* `Jdg 3:9` And when the children of Israel cried to the LORD, the LORD *_raised_* up a deliverer for the children of Israel who delivered them, even Othniel the son of Kenaz, Caleb's younger brother.
* `Jdg 3:15` But when the children of Israel cried to the LORD, the LORD *_raised_* up for them a deliverer: Ehud the son of Gera, a Benjaminite, a left-handed man. And by him the children of Israel sent a tribute to Eglon king of Moab.
* `Jdg 8:28` Thus Midian was subdued before the children of Israel, so that they *_raised_* their heads no more. And the country was in quietness for forty years in the days of Gideon.
* `2Sa 18:18` Now Absalom in his lifetime had taken and *_raised_* for himself a pillar, which is in the king's valley, for he said, "I have no son to keep my name in remembrance." And he called the pillar after his own name, and it is called to this day, Absalom's Place.
* `2Sa 18:28` And Ahimaaz called and said to the king, "All is well." And he fell down to the earth upon his face before the king and said, "Blessed be the LORD your God who has delivered up the men who *_raised_* their hand against my lord the king."
* `2Sa 23:1` Now these are the last words of David. David the son of Jesse, the man who was *_raised_* on high, the anointed of the God of Jacob, and the sweet psalmist of Israel, said,
* `1Ki 5:13` And king Solomon *_raised_* a levy out of all Israel, and the levy was thirty thousand men.
* `1Ki 9:15` And this is the reason of the levy which king Solomon *_raised_*: to build the house of the LORD, his own house, Millo, the wall of Jerusalem, Hazor, Megiddo, and Gezer.
* `1Ki 11:26` And Jeroboam the son of Nebat, an Ephrathite of Zereda, Solomon's servant, whose mother's name was Zeruah, a widow woman, even he *_raised_* his hand against the king.
* `1Ki 11:27` And this was the cause why he *_raised_* his hand against the king: Solomon built Millo and repaired the breaches of the city of David his father.
* `2Ch 6:10` The LORD therefore has performed his word that he has spoken, for I am *_raised_* up in place of David my father and am set on the throne of Israel, as the LORD promised, and have built the house for the name of the LORD God of Israel.
* `2Ch 32:5` He also strengthened himself, built up all the wall that was broken, *_raised_* it up to the towers, built another wall outside, repaired Millo in the city of David, and made darts and shields in abundance.
* `2Ch 33:14` Now after this, he built a wall outside the city of David on the west side of Gihon, in the valley, even to the entrance at the fish-gate, and he encircled Ophel with it and *_raised_* it up a very great height. And he put captains of war in all the fortified cities of Judah.
* `Ezr 1:5` Then arose the chief of the fathers of Judah and Benjamin, the priests, and the Levites, with all whose spirit God had *_raised_*, to go up to build the house of the LORD which is in Jerusalem.
* `Job 2:12` And when they lifted up their eyes afar off, they did not know him. And they *_raised_* their voice and wept, and they each rent his mantle and sprinkled dust upon their heads toward heaven.
* `Job 14:12` So man lies down and does not rise. Until the heavens are no more, they shall not awake nor be *_raised_* out of their sleep.
* `Psa 20:8` They are brought down and fallen, but we are *_raised_* and stand upright.
* `Sos 8:5` [Others:] Who is this who comes up from the wilderness leaning upon her beloved? [Lady:] I *_raised_* you up under the apple-tree. There your mother brought you forth. There she brought you forth who bore you.
* `Isa 14:9` Hell from beneath is moved for you to meet you at your coming. It stirs up the dead for you, even all the chief ones of the earth. It has *_raised_* up from their thrones all the kings of the nations.
* `Isa 23:13` Behold the land of the Chaldeans. This people was not, until the Assyrian founded it for those who dwell in the wilderness. They set up its towers, they *_raised_* up its palaces, and they brought it to ruin.
* `Isa 41:2` Who *_raised_* up the righteous man from the east, called him to his foot, gave the nations before him, and made him rule over kings? He gave them as the dust to his sword and as driven stubble to his bow.
* `Isa 41:25` I have *_raised_* up someone from the north, and he shall come. From the rising of the sun he shall call upon my name. And he shall come upon princes as upon mortar, like the potter who treads the clay.
* `Isa 45:13` I have *_raised_* him up in righteousness and I will direct all his ways. He shall build my city and let my captives go, not for price nor reward," says the LORD of hosts.
* `Jer 6:22` Thus says the LORD: "Behold, a people comes from the north country, and a great nation shall be *_raised_* from the sides of the earth.
* `Jer 25:32` Thus says the LORD of hosts: "Behold, evil shall go forth from nation to nation, and a great whirlwind shall be *_raised_* from the borders of the earth.
* `Jer 29:15` "Because you have said, 'The LORD has *_raised_* up prophets for us in Babylon,'
* `Jer 50:41` Behold, a people shall come from the north, and a great nation, and many kings shall be *_raised_* up from the borders of the earth.
* `Jer 51:11` Make the arrows bright. Gather the shields. The LORD has *_raised_* up the spirit of the kings of the Medes, for his purpose is against Babylon to destroy it, because it is the vengeance of the LORD, the vengeance of his temple.
* `Ezk 11:22` Then the cherubim *_raised_* their wings with the wheels beside them, and the glory of the God of Israel was over them above.
* `Dan 7:5` And behold another beast, a second, like a bear, and it *_raised_* itself on one side, and it had three ribs in its mouth between its teeth, and they said thus to it: 'Arise, devour much flesh.'
* `Amo 2:11` And I *_raised_* up some of your sons for prophets and some of your young men for Nazarites. Is it not even so, O children of Israel?" says the LORD.
* `Zch 2:13` "Be silent, all flesh, before the LORD, for he is *_raised_* up out of his holy habitation."
* `Zch 9:13` When I have bent Judah for me, filled the bow with Ephraim, and *_raised_* up your sons, O Zion, against your sons, O Greece, and made you as the sword of a mighty man.
* `Mth 1:24` Then Joseph, being *_raised_* from sleep, did as the angel of the Lord had bidden him and took for himself his wife,
* `Mth 11:5` 'The blind receive their sight,' 'the lame walk,' the lepers are cleansed, 'the deaf hear,' the dead are *_raised_*, and 'the poor have the gospel preached to them.'
* `Mth 16:21` From that time forth Jesus began to tell his disciples that he must go to Jerusalem and suffer many things from the elders, chief priests, and scribes, and be killed, and be *_raised_* again the third day.
* `Mth 17:9` And as they were descending the mountain, Jesus charged them, saying, "Tell the vision to no man until the Son of man is *_raised_* again from the dead."
* `Mth 17:23` And they will kill him. And on the third day he will be *_raised_* again." And they were exceedingly grieved.
* `Luk 1:69` He has *_raised_* up a horn of salvation for us, in the house of his servant David,
* `Luk 7:22` Then Jesus, answering, said to them, "Go, and tell John what things you have seen and heard: 'the blind see,' 'the lame walk,' lepers are cleansed, 'the deaf hear,' the dead are *_raised_*, and 'the gospel is preached to the poor.'
* `Luk 9:22` Saying, "The Son of man must suffer many things, be rejected by the elders, chief priests, and scribes, be put to death, and be *_raised_* on the third day."
* `Luk 20:37` But that the dead are *_raised_*, even Moses showed it at the bush when he calls the Lord 'the God of Abraham, the God of Isaac, and the God of Jacob.'
* `Jhn 8:7` So when they continued asking him, he *_raised_* himself and said to them, "He who is without sin among you, let him cast the first stone at her."
* `Jhn 8:10` When Jesus had *_raised_* himself and saw no one except the woman, he said to her, "Woman, where are your accusers? Has no man condemned you?"
* `Jhn 12:1` Then Jesus, six days before the passover, came to Bethany, where Lazarus was, who had been dead, whom he *_raised_* from the dead.
* `Jhn 12:9` Many people of the Jews therefore knew that he was there. And they came, not for Jesus' sake only, but so that they might see Lazarus also, whom he had *_raised_* from the dead.
* `Jhn 12:17` Therefore, the people who were with him when he called Lazarus out of his grave and *_raised_* him from the dead, bore testimony.
* `Act 2:24` Whom God has *_raised_* up, having released him from the pains of death, because it was not possible that he should be held by it.
* `Act 2:32` God has *_raised_* up this Jesus, of which we all are witnesses.
* `Act 3:15` And killed the Prince of life whom God has *_raised_* from the dead, of which we are witnesses.
* `Act 3:26` God, having *_raised_* up his Son Jesus, sent him to you first to bless you in turning away each of you from his iniquities."
* `Act 4:10` May it be known to you all and to all the people of Israel, that by the name of Jesus Christ of Nazareth, whom you crucified, whom God *_raised_* from the dead, even by him this man stands here before you sound.
* `Act 5:30` The God of our fathers *_raised_* up Jesus, whom you slew and hanged on a tree.
* `Act 10:40` God *_raised_* him on the third day and showed him openly,
* `Act 12:7` And behold, the angel of the Lord came upon him, and a light shined in the prison, and he smote Peter on the side and *_raised_* him up, saying, "Arise quickly." And his chains fell off from his hands.
* `Act 13:22` And when he had removed him, he *_raised_* up to them David to be their king, to whom also he gave testimony, and said, '"I have found David" the son of Jesse, "a man after my own heart" who shall fulfill all my will.'
* `Act 13:23` Of this man's offspring God has, according to his promise, *_raised_* up to Israel a Savior, Jesus.
* `Act 13:30` But God *_raised_* him from the dead,
* `Act 13:33` God has fulfilled the same to us their children in that he has *_raised_* up Jesus again, as it is also written in the second psalm, 'You are my Son. This day I have begotten you.'
* `Act 13:34` And concerning that he *_raised_* him from the dead, now no longer to return to corruption, he said in this way: 'I will give you the sure mercies of David.'
* `Act 13:37` But he whom God *_raised_* again saw no corruption.
* `Act 13:50` But the Jews stirred up the devout and honorable women and the chief men of the city, *_raised_* persecution against Paul and Barnabas, and expelled them from their borders.
* `Act 17:31` Because he has appointed a day in which he will judge the world in righteousness by that man whom he has ordained, of which he has given assurance to all men in that he has *_raised_* him from the dead."
* `Act 27:13` And when the south wind blew softly, supposing that they had obtained their purpose, they *_raised_* the anchor and sailed close by Crete.
* `Rom 4:24` But for us also, to whom it will be imputed, if we believe in him who *_raised_* Jesus our Lord from the dead,
* `Rom 4:25` Who was delivered for our offenses and *_raised_* again for our justification.
* `Rom 6:4` Therefore, we are buried with him by baptism into death, so that as Christ was *_raised_* from the dead by the glory of the Father, even so we also should walk in newness of life.
* `Rom 6:9` Knowing that Christ, being *_raised_* from the dead, dies no more. Death no longer has dominion over him.
* `Rom 7:4` Therefore, my brothers, you have also become dead to the law by the body of Christ so that you should be married to another, even to him who is *_raised_* from the dead, so that we should bring forth fruit to God.
* `Rom 8:11` But if the Spirit of him who *_raised_* Jesus from the dead dwells in you, he who *_raised_* Christ from the dead will also revive your mortal bodies by his Spirit who dwells in you.
* `Rom 9:17` For the Scripture says to Pharaoh, "Even for this same purpose I have *_raised_* you up so that I might show my power in you and that my name might be declared throughout all the earth."
* `Rom 10:9` That if you confess with your mouth the Lord Jesus and believe in your heart that God has *_raised_* him from the dead, you shall be saved.
* `1Co 6:14` And God has both *_raised_* up the Lord and will also raise us up by his own power.
* `1Co 15:13` But if there is no resurrection of the dead, then Christ has not been *_raised_*.
* `1Co 15:14` And if Christ has not been *_raised_*, then our preaching is vain and your faith is also vain.
* `1Co 15:15` And indeed we are found false witnesses of God because we have testified concerning God that he *_raised_* up Christ, whom he did not raise, if in truth the dead do not rise.
* `1Co 15:16` For if the dead do not rise, then Christ has not been *_raised_*.
* `1Co 15:17` And if Christ has not been *_raised_*, your faith is vain. You are still in your sins.
* `1Co 15:20` But now Christ has been *_raised_* from the dead and has become the first-fruits of those who slept.
* `1Co 15:35` But some man will say, "How are the dead *_raised_*? And with what body do they come?"
* `1Co 15:42` Thus also is the resurrection of the dead. It is sown in corruption, it is *_raised_* in incorruption.
* `1Co 15:43` It is sown in dishonor, it is *_raised_* in glory. It is sown in weakness, it is *_raised_* in power.
* `1Co 15:44` It is sown a natural body, it is *_raised_* a spiritual body. There is a natural body and there is a spiritual body.
* `1Co 15:52` In a moment, in the twinkling of an eye, at the last trumpet. For the trumpet shall sound, the dead shall be *_raised_* incorruptible, and we shall be changed.
* `2Co 4:14` Knowing that he who *_raised_* the Lord Jesus will raise us also by Jesus and will present us with you.
* `Gal 1:1` Paul, an apostle (not from men, neither by man, but by Jesus Christ and God the Father who *_raised_* him from the dead),
* `Eph 1:20` Which he wrought in Christ when he *_raised_* him from the dead and set him at his own right hand in the heavenly places,
* `Eph 2:6` And has *_raised_* us up together and made us sit together in heavenly places in Christ Jesus,
* `Col 2:12` Buried with him in baptism, in which you are also *_raised_* with him through the faith of the operation of God, who has *_raised_* him from the dead.
* `Col 3:1` If you then are *_raised_* with Christ, seek those things which are above, where Christ sits on the right hand of God.
* `1Th 1:10` And to wait for his Son from heaven, whom he *_raised_* from the dead, even Jesus who delivered us from the wrath to come.
* `2Ti 2:8` Remember that Jesus Christ of the offspring of David was *_raised_* from the dead according to my gospel.
* `Heb 11:35` Women received their dead *_raised_* to life again. Others were tortured, not accepting deliverance, so that they might obtain a better resurrection.
* `1Pe 1:21` Who, by him, believe in God, who *_raised_* him from the dead and gave him glory, so that your faith and hope might be in God.

_102 verses containing RAISED_

== RAISER

* `Dan 11:20` "Then a *_raiser_* of taxes shall stand up in his estate in the glory of the kingdom, but within few days he shall be destroyed, neither in anger, nor in battle.

_1 verse containing RAISER_

== RAISES

* `1Sa 2:8` He *_raises_* the poor out of the dust and lifts the beggar from the dunghill to set them among princes and to make them inherit the throne of glory. For the pillars of the earth are the LORD'S, and he has set the world upon them.
* `Job 41:25` When he *_raises_* himself, the mighty are afraid. By reason of breakings they purify themselves.
* `Psa 107:25` For he commands and *_raises_* the stormy wind, which lifts up its waves.
* `Psa 113:7` He *_raises_* the poor out of the dust and lifts the needy out of the dunghill
* `Psa 145:14` The LORD upholds all who fall and *_raises_* up all those who are bowed down.
* `Psa 146:8` The LORD opens the eyes of the blind. The LORD *_raises_* those who are bowed down. The LORD loves the righteous.
* `Jhn 5:21` For as the Father *_raises_* the dead and revives them, even so the Son revives whom he wishes.
* `Act 26:8` Why is it judged incredible with you if God *_raises_* the dead?
* `2Co 1:9` But we had the sentence of death in ourselves so that we should not trust in ourselves, but in God who *_raises_* the dead,

_9 verses containing RAISES_

== RAISINS

* `1Sa 25:18` Then Abigail made haste and took two hundred loaves, two bottles of wine, five sheep ready and dressed, five measures of parched grain, one hundred clusters of *_raisins_*, and two hundred cakes of figs, and laid them on donkeys.
* `1Sa 30:12` And they gave him a piece of a cake of figs and two clusters of *_raisins_*. And when he had eaten, his spirit came back to him, for he had eaten no bread nor drank any water for three days and three nights.
* `2Sa 16:1` And when David was a little past the top of the hill, behold, Ziba the servant of Mephibosheth met him, with a couple of donkeys saddled and upon them two hundred loaves of bread, one hundred bunches of *_raisins_*, one hundred of summer fruits, and a bottle of wine.
* `1Ch 12:40` Moreover, those who were near them, even as far as Issachar, Zebulun, and Naphtali, brought food on donkeys, on camels, on mules, and on oxen—abundant provision of meal, fig cakes, bunches of *_raisins_*, wine, oil, oxen, and sheep—for there was joy in Israel.

_4 verses containing RAISINS_

== RAKEM

* `1Ch 7:16` And Maachah the wife of Machir bore a son and she called his name Peresh. And the name of his brother was Sheresh, and his sons were Ulam and *_Rakem_*.

_1 verse containing RAKEM_

== RAKKATH

* `Jsh 19:35` And the fortified cities are Ziddim, Zer, Hammath, *_Rakkath_*, Chinnereth,

_1 verse containing RAKKATH_

== RAKKON

* `Jsh 19:46` Me-jarkon, and *_Rakkon_*, with the border before Japho.

_1 verse containing RAKKON_

== RAM

* `Gen 15:9` And he said to him, "Bring me a heifer of three years old, a female goat of three years old, a *_ram_* of three years old, a turtle-dove, and a young pigeon."
* `Gen 22:13` And Abraham lifted up his eyes and looked, and behold, behind him a *_ram_* caught in a thicket by his horns. And Abraham went and took the *_ram_* and offered him for a burnt-offering instead of his son.
* `Exo 29:15` "You shall also take one *_ram_*, and Aaron and his sons shall put their hands upon the head of the *_ram_*.
* `Exo 29:16` And you shall slay the *_ram_* and take his blood and sprinkle it around upon the altar.
* `Exo 29:17` And you shall cut the *_ram_* in pieces and wash his inwards and his legs and put them with his pieces and with his head.
* `Exo 29:18` And you shall burn the whole *_ram_* upon the altar. It is a burnt-offering to the LORD. It is a sweet savor, an offering made by fire to the LORD.
* `Exo 29:19` "And you shall take the other *_ram_*, and Aaron and his sons shall put their hands upon the head of the *_ram_*.
* `Exo 29:20` Then you shall kill the *_ram_* and take some of his blood and put it upon the tip of the right ear of Aaron, upon the tip of the right ear of his sons, upon the thumb of their right hand, and upon the great toe of their right foot, and sprinkle the blood around upon the altar.
* `Exo 29:22` "Also you shall take from the *_ram_* the fat and the rump, the fat that covers the inwards and the lobe of the liver, the two kidneys and the fat that is upon them, the right shoulder (for it is a *_ram_* of consecration),
* `Exo 29:26` "And you shall take the breast of the *_ram_* of Aaron's consecration and wave it for a wave-offering before the LORD, and it shall be your part.
* `Exo 29:27` And you shall sanctify the breast of the wave-offering and the shoulder of the heave-offering, which is waved and which is heaved up from the *_ram_* of the consecration, even from that which is for Aaron and from that which is for his sons.
* `Exo 29:31` "And you shall take the *_ram_* of the consecration and boil his flesh in the holy place.
* `Exo 29:32` And Aaron and his sons shall eat the flesh of the *_ram_* and the bread that is in the basket by the door of the Tabernacle of the Congregation.
* `Lev 5:15` "If a soul commits a trespass and sins through ignorance in the holy things of the LORD, then he shall bring for his trespass to the LORD a *_ram_* without blemish out of the flocks, with your estimation in shekels of silver after the shekel of the sanctuary, for a trespass-offering.
* `Lev 5:16` And he shall make amends for the harm that he has done in the holy thing, and shall add to it the fifth part and give it to the priest. And the priest shall make an atonement for him with the *_ram_* of the trespass-offering, and he shall be forgiven.
* `Lev 5:18` And he shall bring a *_ram_* without blemish out of the flock, with your estimation, for a trespass-offering to the priest. And the priest shall make an atonement for him concerning his ignorance wherein he erred and did not know it, and he shall be forgiven.
* `Lev 6:6` And he shall bring to the priest his trespass-offering to the LORD, a *_ram_* without blemish out of the flock, with your estimation, for a trespass-offering.
* `Lev 8:18` And he brought the *_ram_* for the burnt-offering. And Aaron and his sons laid their hands upon the head of the *_ram_*.
* `Lev 8:20` And Moses cut the *_ram_* into pieces and burnt the head, the pieces, and the fat,
* `Lev 8:21` And he washed the inwards and the legs in water. And then Moses burnt the whole *_ram_* upon the altar. It was a burnt-sacrifice for a sweet savor and an offering made by fire to the LORD, as the LORD commanded Moses.
* `Lev 8:22` And he brought the other *_ram_*, the *_ram_* of consecration. And Aaron and his sons laid their hands upon the head of the *_ram_*.
* `Lev 8:29` And Moses took the breast and waved it for a wave-offering before the LORD. It was Moses's part of the *_ram_* of consecration, as the LORD commanded Moses.
* `Lev 9:2` And he said to Aaron, "Take a young calf for a sin-offering and a *_ram_* for a burnt-offering, without blemish, and offer them before the LORD.
* `Lev 9:4` And also a bull and a *_ram_* for peace-offerings, to sacrifice before the LORD, and a food-offering mingled with oil, for today the LORD will appear to you.'"
* `Lev 9:18` He also slew the bull and the *_ram_* for a sacrifice of peace-offerings, which was for the people. And Aaron's sons presented to him the blood, which he sprinkled around upon the altar,
* `Lev 9:19` And the fat of the bull and of the *_ram_*, the rump, and that which covers the inwards, the kidneys, and the lobe of the liver.
* `Lev 16:3` Thus shall Aaron come into the holy place: with a young bull for a sin-offering and a *_ram_* for a burnt-offering.
* `Lev 16:5` And he shall take from the congregation of the children of Israel two kids of the goats for a sin-offering and one *_ram_* for a burnt-offering.
* `Lev 19:21` And he shall bring his trespass-offering to the LORD at the door of the Tabernacle of the Congregation, even a *_ram_* for a trespass-offering.
* `Lev 19:22` And the priest shall make an atonement for him with the *_ram_* of the trespass-offering before the LORD for his sin which he has done. And the sin which he has done shall be forgiven.
* `Num 5:8` But if the man has no kinsman to recompense the trespass to, let the trespass be recompensed to the LORD, even to the priest, besides the *_ram_* of the atonement, by which an atonement is made for him.
* `Num 6:14` And he shall offer his offering to the LORD: one male lamb of the first year without blemish for a burnt-offering, one ewe-lamb of the first year without blemish for a sin-offering, one *_ram_* without blemish for peace-offerings,
* `Num 6:17` And he shall offer the *_ram_* for a sacrifice of peace-offerings to the LORD with the basket of unleavened bread. The priest shall also offer his food-offering and his drink-offering.
* `Num 6:19` And the priest shall take the boiled shoulder of the *_ram_*, one unleavened cake out of the basket, and one unleavened wafer and put them upon the hands of the Nazarite after the hair of his separation is shaved.
* `Num 7:15` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:21` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:27` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:33` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:39` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:45` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:51` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:57` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:63` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:69` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:75` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 7:81` One young bull, one *_ram_*, and one lamb of the first year for a burnt-offering;
* `Num 15:6` Or for a *_ram_*, you shall prepare for a food-offering two tenth parts of flour mingled with the third part of a hin of oil.
* `Num 15:11` 'Thus it shall be done for one bull, for one *_ram_*, for a lamb, or a kid.
* `Num 23:2` And Balak did as Balaam had spoken. And Balak and Balaam offered on every altar a bull and a *_ram_*.
* `Num 23:4` And God met Balaam. And he said to him, "I have prepared seven altars and I have offered upon every altar a bull and a *_ram_*."
* `Num 23:14` And he brought him into the field of Zophim, to the top of Pisgah, and built seven altars and offered a bull and a *_ram_* on every altar.
* `Num 23:30` And Balak did as Balaam had said and offered a bull and a *_ram_* on every altar.
* `Num 28:11` 'And in the beginnings of your months you shall offer a burnt-offering to the LORD: two young bulls, one *_ram_*, and seven lambs of the first year without spot;
* `Num 28:12` Three tenth-parts of flour for a food-offering, mingled with oil, for one bull; two tenth-parts of flour for a food-offering, mingled with oil, for one *_ram_*;
* `Num 28:14` And their drink-offering shall be half a hin of wine to a bull, the third part of a hin to a *_ram_*, and a fourth part of a hin to a lamb. This is the burnt-offering of every month throughout the months of the year.
* `Num 28:19` But you shall offer a sacrifice made by fire for a burnt-offering to the LORD: two young bulls, one *_ram_*, and seven lambs of the first year—they shall be to you without blemish;
* `Num 28:20` And their food-offering shall be of flour mingled with oil; three tenth-parts you shall offer for a bull and two tenth-parts for a *_ram_*;
* `Num 28:27` But you shall offer the burnt-offering for a sweet savor to the LORD: two young bulls, one *_ram_*, and seven lambs of the first year;
* `Num 28:28` And their food-offering of flour mingled with oil—three tenth-parts to one bull, two tenth-parts to one *_ram_*,
* `Num 29:2` And you shall offer a burnt-offering for a sweet savor to the LORD: one young bull, one *_ram_*, and seven lambs of the first year without blemish;
* `Num 29:3` And their food-offering shall be of flour mingled with oil—three tenth-parts for a bull, two tenth-parts for a *_ram_*,
* `Num 29:8` But you shall offer a burnt-offering to the LORD for a sweet savor: one young bull, one *_ram_*, and seven lambs of the first year—they shall be to you without blemish;
* `Num 29:9` And their food-offering shall be of flour mingled with oil—three tenth-parts to a bull, two tenth-parts to one *_ram_*,
* `Num 29:14` And their food-offering shall be of flour mingled with oil—three tenth-parts to every bull of the thirteen bulls, two tenth-parts to each *_ram_* of the two rams,
* `Num 29:36` But you shall offer a burnt-offering, a sacrifice made by fire, a sweet savor to the LORD: one bull, one *_ram_*, and seven lambs of the first year without blemish;
* `Num 29:37` Their food-offering and their drink-offerings for the bull, for the *_ram_*, and for the lambs shall be according to their number, after the manner;
* `Jsh 6:5` And it shall come to pass, that when they make a long blast with the *_ram_*'s horn, and when you hear the sound of the trumpet, all the people shall shout with a great shout. And the wall of the city shall fall down flat, and the people shall each ascend straight before him."
* `Rth 4:19` Hezron begot *_Ram_*, *_Ram_* begot Amminadab,
* `1Ch 2:9` The sons also of Hezron who were born to him: Jerahmeel, *_Ram_*, and Chelubai.
* `1Ch 2:10` And *_Ram_* begot Amminadab, Amminadab begot Nahshon prince of the children of Judah,
* `1Ch 2:25` And the sons of Jerahmeel the first-born of Hezron were *_Ram_* (the first-born), Bunah, Oren, Ozem, and Ahijah.
* `1Ch 2:27` And the sons of *_Ram_* the first-born of Jerahmeel were Maaz, Jamin, and Eker.
* `Ezr 10:19` And they gave their hands that they would put away their wives. And being guilty, they offered a *_ram_* of the flock for their trespass.
* `Job 32:2` Then the wrath of Elihu the son of Barachel the Buzite, of the kindred of *_Ram_*, was kindled against Job because he justified himself rather than God.
* `Ezk 43:23` When you have made an end of cleansing it, you shall offer a young bull without blemish and a *_ram_* out of the flock without blemish.
* `Ezk 43:25` Seven days you shall prepare every day a goat for a sin-offering. They shall also prepare a young bull and a *_ram_* out of the flock without blemish.
* `Ezk 45:24` And he shall prepare a food-offering of an ephah for a bull, an ephah for a *_ram_*, and a hin of oil for an ephah.
* `Ezk 46:4` And the burnt-offering that the prince shall offer to the LORD on the sabbath day shall be six lambs without blemish and a *_ram_* without blemish.
* `Ezk 46:5` And the food-offering shall be an ephah for a *_ram_*, and the food-offering for the lambs as he shall be able to give, and a hin of oil to an ephah.
* `Ezk 46:6` And on the day of the new moon it shall be a young bull without blemish, six lambs, and a *_ram_*. They shall be without blemish.
* `Ezk 46:7` And he shall prepare a food-offering, an ephah for a bull and an ephah for a *_ram_*, and for the lambs according as his hand shall be able, along with a hin of oil to an ephah.
* `Ezk 46:11` "And in the feasts and in the solemnities the food-offering shall be an ephah to a bull and an ephah to a *_ram_*, and to the lambs as he is able to give, along with a hin of oil to an ephah.
* `Dan 8:3` Then I lifted up my eyes and saw, and behold, there stood before the river a *_ram_* which had two horns. And the two horns were high, but one was higher than the other, and the higher came up last.
* `Dan 8:4` I saw the *_ram_* goring westward, northward, and southward, so that no beasts might stand before him, neither was there any who could deliver out of his hand, but he did according to his will and became great.
* `Dan 8:6` And he came to the *_ram_* that had two horns, which I had seen standing before the river, and ran to him in the fury of his power.
* `Dan 8:7` And I saw him come close to the *_ram_*, and he was moved with anger against him and smote the *_ram_* and broke his two horns. And there was no power in the *_ram_* to stand before him, but he cast him down to the ground and stamped upon him. And there was no one who could deliver the *_ram_* out of his hand.
* `Dan 8:20` "The *_ram_* which you saw having two horns, these are the kings of Media and Persia.
* `Mth 1:3` Judah begot Pharez and Zarah by Tamar, Pharez begot Hezron, Hezron begot *_Ram_*,
* `Mth 1:4` *_Ram_* begot Amminadab, Amminadab begot Nahshon, Nahshon begot Salmon,
* `Luk 3:33` Who was the son of Amminadab, who was the son of *_Ram_*, who was the son of Hezron, who was the son of Pharez, who was the son of Judah,

_90 verses containing RAM_

== RAMAH

* `Jsh 18:25` Gibeon, *_Ramah_*, Beeroth,
* `Jsh 19:29` And then the border turns to *_Ramah_*, and to the strong city Tyre, and the border turns to Hosah; and its limits are at the sea by the region of Achzib;
* `Jsh 19:36` Adamah, *_Ramah_*, Hazor,
* `Jdg 4:5` And she dwelt under the palm-tree of Deborah between *_Ramah_* and Beth-el in the mountains of Ephraim, and the children of Israel came up to her for judgment.
* `Jdg 19:13` And he said to his servant, "Come, and let us draw near to one of these places, and we will lodge all night in Gibeah or in *_Ramah_*."
* `1Sa 1:19` And they rose early in the morning, worshiped before the LORD, and returned and came to their house in *_Ramah_*. And Elkanah knew Hannah his wife, and the LORD remembered her.
* `1Sa 2:11` And Elkanah went to his house in *_Ramah_*. And the child ministered to the LORD before Eli the priest.
* `1Sa 7:17` And his return was to *_Ramah_*, for his house was there. There he judged Israel and there he built an altar to the LORD.
* `1Sa 8:4` Then all the elders of Israel assembled and came to Samuel at *_Ramah_*
* `1Sa 15:34` Then Samuel went to *_Ramah_*, and Saul went up to his house to Gibeah of Saul.
* `1Sa 16:13` Then Samuel took the horn of oil and anointed him in the midst of his brothers. And the Spirit of the LORD came upon David from that day forward. So Samuel arose and went to *_Ramah_*.
* `1Sa 19:18` So David fled and escaped, and he came to Samuel at *_Ramah_* and told him all that Saul had done to him. And he and Samuel went and dwelt in Naioth.
* `1Sa 19:19` And it was told to Saul, saying, "Behold, David is at Naioth in *_Ramah_*."
* `1Sa 19:22` Then he went also to *_Ramah_* and came to a great well that is in Sechu. And he asked and said, "Where are Samuel and David?" And someone said, "Behold, they are at Naioth in *_Ramah_*."
* `1Sa 19:23` And he went there to Naioth in *_Ramah_*. And the Spirit of God was upon him also, and he went on and prophesied until he came to Naioth in *_Ramah_*.
* `1Sa 20:1` And David fled from Naioth in *_Ramah_* and came and said before Jonathan, "What have I done? What is my iniquity? And what is my sin before your father that he seeks my life?"
* `1Sa 22:6` When Saul heard that David was discovered, and the men who were with him (now Saul stayed in Gibeah under a tree in *_Ramah_*, having his spear in his hand, and all his servants were standing around him),
* `1Sa 25:1` And Samuel died. And all the Israelites assembled, lamented him, and buried him in his house at *_Ramah_*. And David arose and went down to the wilderness of Paran.
* `1Sa 28:3` Now Samuel was dead, and all Israel had lamented him and buried him in *_Ramah_*, even in his own city. And Saul had put away those who had familiar spirits and the wizards out of the land.
* `1Ki 15:17` And Baasha king of Israel went up against Judah and built *_Ramah_* so that he might not allow any to go out or come to Asa king of Judah.
* `1Ki 15:21` And it came to pass when Baasha heard of it, that he stopped building *_Ramah_* and dwelt in Tirzah.
* `1Ki 15:22` Then king Asa made a proclamation throughout all Judah. No one was exempted. And they took away the stones of *_Ramah_* and its timber, with which Baasha had built it, and king Asa built with them Geba of Benjamin and Mizpah.
* `2Ki 8:29` And king Joram went back to be healed in Jezreel of the wounds which the Syrians had given him at *_Ramah_* when he fought against Hazael king of Syria. And Ahaziah the son of Jehoram king of Judah went down to see Joram the son of Ahab in Jezreel because he was sick.
* `2Ch 16:1` In the thirty-sixth year of the reign of Asa, Baasha king of Israel came against Judah and built *_Ramah_* so that he might let no one go out or come in to Asa king of Judah.
* `2Ch 16:5` And it came to pass, when Baasha heard it, that he left off the building of *_Ramah_* and let his work cease.
* `2Ch 16:6` Then Asa the king took all Judah, and they carried away the stones of *_Ramah_* and its timber with which Baasha was building, and he built with it Geba and Mizpah.
* `2Ch 22:6` And he returned to be healed in Jezreel because of the wounds which were given to him at *_Ramah_* when he fought with Hazael king of Syria. And Azariah the son of Jehoram king of Judah went down to see Jehoram the son of Ahab at Jezreel because he was sick.
* `Ezr 2:26` The children of *_Ramah_* and Gaba, six hundred and twenty-one;
* `Neh 7:30` The men of *_Ramah_* and Gaba, six hundred and twenty-one;
* `Neh 11:33` Hazor, *_Ramah_*, Gittaim,
* `Isa 10:29` They have gone over the passage. They have taken up their lodging at Geba. *_Ramah_* is afraid. Gibeah of Saul has fled.
* `Jer 31:15` Thus says the LORD: "A voice was heard in *_Ramah_*, lamentation and bitter weeping. Rachel weeping for her children refused to be comforted for her children, because they were no more."
* `Jer 40:1` A word came to Jeremiah from the LORD after Nebuzar-adan the captain of the guard had let him go from *_Ramah_*, when he had taken him being bound in chains among all who were carried away captive of Jerusalem and Judah, who were carried away captive to Babylon.
* `Hos 5:8` Blow the horn in Gibeah and the trumpet in *_Ramah_*. Cry aloud at Beth-aven, after you, O Benjamin.
* `Mth 2:18` "In *_Ramah_* there was a voice heard, lamentation, weeping, and great mourning, Rachel weeping for her children, and would not be comforted, because they are no more."

_35 verses containing RAMAH_

== RAMATH

* `Jsh 13:26` And from Heshbon to *_Ramath_*-mizpeh, and Betonim; and from Mahanaim to the border of Debir;
* `Jsh 19:8` And all the villages that were around these cities to Baalath-beer (*_Ramath_* of the south). This is the inheritance of the tribe of the children of Simeon according to their families.
* `Jdg 15:17` And it came to pass when he had made an end of speaking, that he cast away the jaw-bone out of his hand and called that place *_Ramath_*-lehi.

_3 verses containing RAMATH_

== RAMATH-LEHI

* `Jdg 15:17` And it came to pass when he had made an end of speaking, that he cast away the jaw-bone out of his hand and called that place *_Ramath-lehi_*.

_1 verse containing RAMATH-LEHI_

== RAMATH-MIZPEH

* `Jsh 13:26` And from Heshbon to *_Ramath-mizpeh_*, and Betonim; and from Mahanaim to the border of Debir;

_1 verse containing RAMATH-MIZPEH_

== RAMATHAIM-ZOPHIM

* `1Sa 1:1` Now there was a certain man of *_Ramathaim-zophim_*, of mount Ephraim, and his name was Elkanah, the son of Jeroham, the son of Elihu, the son of Tohu, the son of Zuph, an Ephrathite.

_1 verse containing RAMATHAIM-ZOPHIM_

== RAMATHITE

* `1Ch 27:27` And over the vineyards was Shimei the *_Ramathite_*; and over the increase of the vineyards for the wine cellars was Zabdi the Shiphmite;

_1 verse containing RAMATHITE_

== RAMESES

* `Gen 47:11` And Joseph placed his father and his brothers and gave them a possession in the land of Egypt, in the best of the land, in the land of *_Rameses_*, as Pharaoh had commanded.
* `Exo 12:37` And the children of Israel journeyed from *_Rameses_* to Succoth, about six hundred thousand on foot who were men, besides children.
* `Num 33:3` And they departed from *_Rameses_* in the first month, on the fifteenth day of the first month. On the next day after the passover, the children of Israel went out with a high hand in the sight of all the Egyptians,
* `Num 33:5` And the children of Israel departed from *_Rameses_* and encamped in Succoth.

_4 verses containing RAMESES_

== RAMIAH

* `Ezr 10:25` Moreover, of Israel: of the sons of Parosh: *_Ramiah_*, Jeziah, Malchiah, Miamin, Eleazar, Malchijah, and Benaiah.

_1 verse containing RAMIAH_

== RAMOTH

* `Deu 4:43` Bezer in the wilderness in the plain country of the Reubenites, *_Ramoth_* in Gilead of the Gadites, and Golan in Bashan of the Manassites.
* `Jsh 20:8` And on the other side of the Jordan by Jericho eastward, they assigned Bezer in the wilderness upon the plain out of the tribe of Reuben, *_Ramoth_* in Gilead out of the tribe of Gad, and Golan in Bashan out of the tribe of Manasseh.
* `Jsh 21:38` And out of the tribe of Gad, *_Ramoth_* in Gilead with its suburbs to be a city of refuge for the slayer, Mahanaim with its suburbs,
* `1Sa 30:27` To those who were in Beth-el, to those who were in south *_Ramoth_*, to those who were in Jattir,
* `1Ki 4:13` The son of Geber, in *_Ramoth_*-gilead—to him pertained the towns of Jair the son of Manasseh, which are in Gilead, and also to him pertained the region of Argob, which is in Bashan, sixty great cities with walls and brazen bars;
* `1Ki 22:3` And the king of Israel said to his servants, "Do you know that *_Ramoth_* in Gilead is ours, and we are still and do not take it out of the hand of the king of Syria?"
* `1Ki 22:4` And he said to Jehoshaphat, "Will you go with me to battle at *_Ramoth_*-gilead?" And Jehoshaphat said to the king of Israel, "I am as you are, my people as your people, my horses as your horses."
* `1Ki 22:6` Then the king of Israel assembled the prophets, about four hundred men, and said to them, "Shall I go against *_Ramoth_*-gilead to battle, or shall I forbear?" And they said, "Go up, for the Lord will deliver it into the hand of the king."
* `1Ki 22:12` And all the prophets similarly prophesied, saying, "Go up to *_Ramoth_*-gilead and prosper, for the LORD will deliver it into the king's hand."
* `1Ki 22:15` So he came to the king. And the king said to him, "Micaiah, shall we go against *_Ramoth_*-gilead to battle, or shall we forbear?" And he answered him, "Go and prosper, for the LORD will deliver it into the hand of the king."
* `1Ki 22:20` And the LORD said, 'Who shall persuade Ahab that he may go up and fall at *_Ramoth_*-gilead?' And one said in this manner and another said in that manner.
* `1Ki 22:29` So the king of Israel and Jehoshaphat the king of Judah went up to *_Ramoth_*-gilead.
* `2Ki 8:28` And he went with Joram the son of Ahab to the war against Hazael king of Syria in *_Ramoth_*-gilead, and the Syrians wounded Joram.
* `2Ki 9:1` And Elisha the prophet called one of the children of the prophets and said to him, "Gird up your loins, take this vial of oil in your hand, and go to *_Ramoth_*-gilead.
* `2Ki 9:4` So the young man, even the young man the prophet, went to *_Ramoth_*-gilead.
* `2Ki 9:14` So Jehu the son of Jehoshaphat the son of Nimshi conspired against Joram. (Now Joram had kept *_Ramoth_*-gilead—he and all Israel—because of Hazael king of Syria.
* `1Ch 6:73` *_Ramoth_* with its suburbs, and Anem with its suburbs.
* `1Ch 6:80` And out of the tribe of Gad: *_Ramoth_* in Gilead with its suburbs, Mahanaim with its suburbs,
* `2Ch 18:2` And after some years he went down to Ahab in Samaria. And Ahab killed sheep and oxen in abundance for him and for the people who were with him, and persuaded him to go up with him to *_Ramoth_*-gilead.
* `2Ch 18:3` And Ahab king of Israel said to Jehoshaphat king of Judah, "Will you go with me to *_Ramoth_*-gilead?" And he answered him, "I am as you are and my people as your people. And we will be with you in the war."
* `2Ch 18:5` Therefore, the king of Israel gathered the prophets, four hundred men, and said to them, "Shall we go to *_Ramoth_*-gilead to battle, or shall I forbear?" And they said, "Go up, for God will deliver it into the king's hand."
* `2Ch 18:11` And all the prophets similarly prophesied, saying, "Go up to *_Ramoth_*-gilead and prosper, for the LORD will deliver it into the hand of the king."
* `2Ch 18:14` And when he had come to the king, the king said to him, "Micaiah, shall we go to *_Ramoth_*-gilead to battle, or shall I forbear?" And he said, "Go up and prosper, and they shall be delivered into your hand."
* `2Ch 18:19` And the LORD said, 'Who shall entice Ahab king of Israel that he may go up and fall at *_Ramoth_*-gilead?' And one spoke saying after this manner and another saying after that manner.
* `2Ch 18:28` So the king of Israel and Jehoshaphat the king of Judah went up to *_Ramoth_*-gilead.
* `2Ch 22:5` He also walked after their counsel and went with Jehoram the son of Ahab king of Israel to war against Hazael king of Syria at *_Ramoth_*-gilead. And the Syrians smote Joram.
* `Ezr 10:29` And of the sons of Bani: Meshullam, Malluch, Adaiah, Jashub, Sheal, and *_Ramoth_*.

_27 verses containing RAMOTH_

== RAMOTH-GILEAD

* `1Ki 4:13` The son of Geber, in *_Ramoth-gilead_*—to him pertained the towns of Jair the son of Manasseh, which are in Gilead, and also to him pertained the region of Argob, which is in Bashan, sixty great cities with walls and brazen bars;
* `1Ki 22:4` And he said to Jehoshaphat, "Will you go with me to battle at *_Ramoth-gilead_*?" And Jehoshaphat said to the king of Israel, "I am as you are, my people as your people, my horses as your horses."
* `1Ki 22:6` Then the king of Israel assembled the prophets, about four hundred men, and said to them, "Shall I go against *_Ramoth-gilead_* to battle, or shall I forbear?" And they said, "Go up, for the Lord will deliver it into the hand of the king."
* `1Ki 22:12` And all the prophets similarly prophesied, saying, "Go up to *_Ramoth-gilead_* and prosper, for the LORD will deliver it into the king's hand."
* `1Ki 22:15` So he came to the king. And the king said to him, "Micaiah, shall we go against *_Ramoth-gilead_* to battle, or shall we forbear?" And he answered him, "Go and prosper, for the LORD will deliver it into the hand of the king."
* `1Ki 22:20` And the LORD said, 'Who shall persuade Ahab that he may go up and fall at *_Ramoth-gilead_*?' And one said in this manner and another said in that manner.
* `1Ki 22:29` So the king of Israel and Jehoshaphat the king of Judah went up to *_Ramoth-gilead_*.
* `2Ki 8:28` And he went with Joram the son of Ahab to the war against Hazael king of Syria in *_Ramoth-gilead_*, and the Syrians wounded Joram.
* `2Ki 9:1` And Elisha the prophet called one of the children of the prophets and said to him, "Gird up your loins, take this vial of oil in your hand, and go to *_Ramoth-gilead_*.
* `2Ki 9:4` So the young man, even the young man the prophet, went to *_Ramoth-gilead_*.
* `2Ki 9:14` So Jehu the son of Jehoshaphat the son of Nimshi conspired against Joram. (Now Joram had kept *_Ramoth-gilead_*—he and all Israel—because of Hazael king of Syria.
* `2Ch 18:2` And after some years he went down to Ahab in Samaria. And Ahab killed sheep and oxen in abundance for him and for the people who were with him, and persuaded him to go up with him to *_Ramoth-gilead_*.
* `2Ch 18:3` And Ahab king of Israel said to Jehoshaphat king of Judah, "Will you go with me to *_Ramoth-gilead_*?" And he answered him, "I am as you are and my people as your people. And we will be with you in the war."
* `2Ch 18:5` Therefore, the king of Israel gathered the prophets, four hundred men, and said to them, "Shall we go to *_Ramoth-gilead_* to battle, or shall I forbear?" And they said, "Go up, for God will deliver it into the king's hand."
* `2Ch 18:11` And all the prophets similarly prophesied, saying, "Go up to *_Ramoth-gilead_* and prosper, for the LORD will deliver it into the hand of the king."
* `2Ch 18:14` And when he had come to the king, the king said to him, "Micaiah, shall we go to *_Ramoth-gilead_* to battle, or shall I forbear?" And he said, "Go up and prosper, and they shall be delivered into your hand."
* `2Ch 18:19` And the LORD said, 'Who shall entice Ahab king of Israel that he may go up and fall at *_Ramoth-gilead_*?' And one spoke saying after this manner and another saying after that manner.
* `2Ch 18:28` So the king of Israel and Jehoshaphat the king of Judah went up to *_Ramoth-gilead_*.
* `2Ch 22:5` He also walked after their counsel and went with Jehoram the son of Ahab king of Israel to war against Hazael king of Syria at *_Ramoth-gilead_*. And the Syrians smote Joram.

_19 verses containing RAMOTH-GILEAD_

== RAMPART

* `Lam 2:8` [HET] The LORD has purposed to destroy the wall of the daughter of Zion. He has stretched out a line. He has not withdrawn his hand from destroying. Therefore, he made the *_rampart_* and the wall to lament. They languished together.
* `Nah 3:8` Are you better than No-Amon that was situated among the rivers, that had the waters around it, whose *_rampart_* was the sea and her wall was from the sea?

_2 verses containing RAMPART_

== RAMS

* `Gen 31:10` And it came to pass at the time that the flock conceived, that I lifted up my eyes and saw in a dream, and behold, the *_rams_* which leaped upon the flock were striped, speckled, and grizzled.
* `Gen 31:12` And he said, 'Lift up now your eyes and see that all the *_rams_* which leap upon the flock are striped, speckled, and grizzled, for I have seen all that Laban does to you.
* `Gen 31:38` These twenty years I have been with you. Your ewes and your female goats have not miscarried their young, and the *_rams_* of your flock I have not eaten.
* `Gen 32:14` Two hundred female goats, twenty male goats, two hundred ewes, twenty *_rams_*,
* `Exo 25:5` *_Rams_*' skins dyed red, badgers' skins, shittim wood,
* `Exo 26:14` And you shall make a covering for the tent of *_rams_*' skins dyed red and a covering above of badgers' skins.
* `Exo 29:1` "And this is the thing that you shall do to them to hallow them, to minister to me in the priest's office. Take one young bull and two *_rams_* without blemish,
* `Exo 29:3` And you shall put them into one basket and bring them in the basket with the bull and the two *_rams_*.
* `Exo 35:7` *_Rams_*' skins dyed red, badgers' skins, shittim wood,
* `Exo 35:23` And every man, with whom was found blue, purple, scarlet, fine linen, goats' hair, red skins of *_rams_*, and badgers' skins, brought them.
* `Exo 36:19` And he made a covering for the tent of *_rams_*' skins dyed red and a covering of badgers' skins above that.
* `Exo 39:34` The covering of *_rams_*' skins dyed red, the covering of badgers' skins, and the veil of the covering;
* `Lev 8:2` "Take Aaron and his sons with him, along with the garments, the anointing oil, a bull for the sin-offering, two *_rams_*, and a basket of unleavened bread,
* `Lev 23:18` And you shall offer with the bread seven lambs without blemish of the first year, and one young bull and two *_rams_*. They shall be for a burnt-offering to the LORD, with their food-offering and their drink offerings, even an offering made by fire, a sweet savor to the LORD.
* `Num 7:17` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Nahshon the son of Amminadab.
* `Num 7:23` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Nethaneel the son of Zuar.
* `Num 7:29` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Eliab the son of Helon.
* `Num 7:35` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Elizur the son of Shedeur.
* `Num 7:41` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Shelumiel the son of Zurishaddai.
* `Num 7:47` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Eliasaph the son of Deuel.
* `Num 7:53` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Elishama the son of Ammihud.
* `Num 7:59` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Gamaliel the son of Pedahzur.
* `Num 7:65` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Abidan the son of Gideoni.
* `Num 7:71` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Ahiezer the son of Ammishaddai.
* `Num 7:77` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Pagiel the son of Ocran.
* `Num 7:83` And for a sacrifice of peace-offerings, two oxen, five *_rams_*, five male goats, and five lambs of the first year. This was the offering of Ahira the son of Enan.
* `Num 7:87` All the oxen for the burnt-offering were twelve bulls, the *_rams_* twelve, and the lambs of the first year twelve, with their food-offering; the kids of the goats for sin-offering, twelve;
* `Num 7:88` And all the oxen for the sacrifice of the peace-offerings were twenty-four bulls, the *_rams_* sixty, the male goats sixty, and the lambs of the first year sixty. This was the dedication of the altar, after it was anointed.
* `Num 23:1` And Balaam said to Balak, "Build for me seven altars here and prepare for me seven oxen and seven *_rams_* here."
* `Num 23:29` And Balaam said to Balak, "Build for me seven altars here and prepare for me seven bulls and seven *_rams_* here."
* `Num 29:13` And you shall offer a burnt-offering, a sacrifice made by fire, a sweet savor to the LORD: thirteen young bulls, two *_rams_*, and fourteen lambs of the first year—they shall be without blemish;
* `Num 29:14` And their food-offering shall be of flour mingled with oil—three tenth-parts to every bull of the thirteen bulls, two tenth-parts to each ram of the two *_rams_*,
* `Num 29:17` 'And on the second day you shall offer twelve young bulls, two *_rams_*, and fourteen lambs of the first year without spot;
* `Num 29:18` And their food-offering and their drink-offerings for the bulls, for the *_rams_*, and for the lambs shall be according to their number, after the manner;
* `Num 29:20` 'And on the third day eleven bulls, two *_rams_*, and fourteen lambs of the first year without blemish;
* `Num 29:21` And their food-offering and their drink-offerings for the bulls, for the *_rams_*, and for the lambs shall be according to their number, after the manner;
* `Num 29:23` 'And on the fourth day ten bulls, two *_rams_*, and fourteen lambs of the first year without blemish;
* `Num 29:24` Their food-offering and their drink-offerings for the bulls, for the *_rams_*, and for the lambs shall be according to their number, after the manner;
* `Num 29:26` 'And on the fifth day nine bulls, two *_rams_*, and fourteen lambs of the first year without spot;
* `Num 29:27` And their food-offering and their drink-offerings for the bulls, for the *_rams_*, and for the lambs shall be according to their number, after the manner;
* `Num 29:29` 'And on the sixth day eight bulls, two *_rams_*, and fourteen lambs of the first year without blemish;
* `Num 29:30` And their food-offering and their drink-offerings for the bulls, for the *_rams_*, and for the lambs shall be according to their number, after the manner;
* `Num 29:32` 'And on the seventh day seven bulls, two *_rams_*, and fourteen lambs of the first year without blemish;
* `Num 29:33` And their food-offering and their drink-offerings for the bulls, for the *_rams_*, and for the the lambs shall be according to their number, after the manner;
* `Deu 32:14` With butter of cows, and milk of sheep, with fat of lambs, and *_rams_* of the breed of Bashan and goats, with the finest of the wheat. And you drank the pure blood of the grape.
* `Jsh 6:4` And seven priests shall bear before the ark seven trumpets of *_rams_*' horns. And on the seventh day you shall compass the city seven times, and the priests shall blow with the trumpets.
* `Jsh 6:6` And Joshua the son of Nun called the priests and said to them, "Take up the ark of the covenant, and let seven priests bear seven trumpets of *_rams_*' horns before the ark of the LORD."
* `Jsh 6:8` And it came to pass when Joshua had spoken to the people, that the seven priests bearing the seven trumpets of *_rams_*' horns passed on before the LORD and blew with the trumpets. And the ark of the covenant of the LORD followed them.
* `Jsh 6:13` And seven priests bearing seven trumpets of *_rams_*' horns before the ark of the LORD went on continually and blew with the trumpets. And the armed men went before them, but the rear-guard came after the ark of the LORD, the priests going on and blowing with the trumpets.
* `1Sa 15:22` And Samuel said, "Has the LORD as great delight in burnt-offerings and sacrifices as in obeying the voice of the LORD? Behold, to obey is better than sacrifice and to listen than the fat of *_rams_*.
* `2Ki 3:4` And Mesha king of Moab was a sheep-master, and he rendered to the king of Israel one hundred thousand lambs and one hundred thousand *_rams_*, with the wool.
* `1Ch 15:26` And it came to pass, when God helped the Levites who bore the ark of the covenant of the LORD, that they offered seven bulls and seven *_rams_*.
* `1Ch 29:21` And they sacrificed sacrifices to the LORD and offered burnt-offerings to the LORD on the next day after that day, even one thousand bulls, one thousand *_rams_*, and one thousand lambs, with their drink-offerings, and sacrifices in abundance for all Israel.
* `2Ch 13:9` Have you not cast out the priests of the LORD, the sons of Aaron and the Levites, and have made for yourselves priests after the manner of the nations of other lands? Whoever comes to consecrate himself with a young bull and seven *_rams_*, the same may be a priest of those who are no gods.
* `2Ch 17:11` Also, some of the Philistines brought Jehoshaphat presents and tribute silver. And the Arabians brought him flocks: seven thousand and seven hundred *_rams_* and seven thousand and seven hundred male goats.
* `2Ch 29:21` And they brought seven bulls, seven *_rams_*, seven lambs, and seven male goats for a sin-offering for the kingdom, for the sanctuary, and for Judah. And he commanded the priests the sons of Aaron to offer them on the altar of the LORD.
* `2Ch 29:22` So they killed the bulls, and the priests received the blood and sprinkled it on the altar. Likewise, when they had killed the *_rams_*, they sprinkled the blood upon the altar. They also killed the lambs and sprinkled the blood upon the altar.
* `2Ch 29:32` And the number of the burnt-offerings, which the congregation brought, was seventy bulls, one hundred *_rams_*, and two hundred lambs. All these were for a burnt-offering to the LORD.
* `Ezr 6:9` And that which they have need of—young bulls, *_rams_*, and lambs, for the burnt-offerings of the God of heaven, wheat, salt, wine, and oil, according to the appointment of the priests who are at Jerusalem—let it be given to them day by day without fail
* `Ezr 6:17` And they offered at the dedication of this house of God one hundred bulls, two hundred *_rams_*, four hundred lambs, and for a sin-offering for all Israel twelve male goats, according to the number of the tribes of Israel.
* `Ezr 7:17` Therefore you may speedily buy with this money bulls, *_rams_*, and lambs, with their food-offerings and their drink-offerings, and offer them upon the altar of the house of your God which is in Jerusalem.
* `Ezr 8:35` Also, the children of those who had been carried away, who had come out of the captivity, offered burnt-offerings to the God of Israel: twelve bulls for all Israel, ninety-six *_rams_*, seventy-seven lambs, and twelve male goats for a sin-offering. All this was a burnt-offering to the LORD.
* `Job 42:8` Now therefore, take for yourselves seven bulls and seven *_rams_*, go to my servant Job, and offer for yourselves a burnt-offering. And my servant Job shall pray for you, for I will accept him, lest I deal with you after your folly, in that you have not spoken about me the thing which is right, like my servant Job."
* `Psa 66:15` I will offer to you burnt-sacrifices of fattened calves with the incense of *_rams_*. I will offer bulls with goats. [Selah.]
* `Psa 114:4` The mountains skipped like *_rams_*, and the little hills like lambs.
* `Psa 114:6` O mountains, that you skipped like *_rams_*; O little hills, like lambs?
* `Isa 1:11` The LORD says, "To what purpose is the multitude of your sacrifices to me? I am full of the burnt-offerings of *_rams_* and the fat of fed beasts, and I do not delight in the blood of bulls, of lambs, or of male goats.
* `Isa 34:6` The sword of the LORD is filled with blood. It is made fat with fatness, with the blood of lambs and goats, with the fat of the kidneys of *_rams_*. For the LORD has a sacrifice in Bozrah and a great slaughter in the land of Edom.
* `Isa 60:7` All the flocks of Kedar shall be gathered to you. The *_rams_* of Nebaioth shall minister to you. They shall come up with acceptance on my altar, and I will glorify the house of my glory.
* `Jer 51:40` "I will bring them down like lambs to the slaughter, like *_rams_* with male goats.
* `Ezk 4:2` And lay siege against it, build a fort against it, cast a siege-mound against it, set the camp against it, and set battering *_rams_* against it on every side.
* `Ezk 21:22` At his right hand was the divination for Jerusalem to appoint captains, to open the mouth in the slaughter, to lift up the voice with shouting, to appoint battering *_rams_* against the gates, to cast a siege-mound, and to build a fort.
* `Ezk 26:9` And he shall set battering *_rams_* of war against your walls, and with his axes he shall break down your towers.
* `Ezk 27:21` Arabia, and all the princes of Kedar, they occupied with you in lambs, *_rams_*, and goats. In these they were your merchants.
* `Ezk 34:17` "And as for you, O my flock, thus says the Lord GOD: 'Behold, I judge between sheep and sheep, between the *_rams_* and the male goats.
* `Ezk 39:18` You shall eat the flesh of the mighty and drink the blood of the princes of the earth—of *_rams_*, of lambs, of goats, and of bulls, all of them fattened beasts of Bashan.
* `Ezk 45:23` And on the seven days of the feast he shall prepare a burnt-offering to the LORD, seven bulls and seven *_rams_* without blemish daily the seven days and a kid of the goats daily for a sin-offering.
* `Mic 6:7` Will the LORD be pleased with thousands of *_rams_*, or with tens of thousands of rivers of oil? Shall I give my first-born for my transgression, the fruit of my body for the sin of my soul?

_78 verses containing RAMS_

== RAN

* `Gen 18:2` And he lifted up his eyes and looked, and behold, three men stood by him. And when he saw them, he *_ran_* to meet them from the tent door and bowed himself toward the ground,
* `Gen 18:7` And Abraham *_ran_* to the herd, brought a calf tender and good, and gave it to a young man, and he hastened to dress it.
* `Gen 24:17` And the servant *_ran_* to meet her and said, "Let me, I pray you, drink a little water from your pitcher."
* `Gen 24:20` And she hastened and emptied her pitcher into the trough, and *_ran_* back to the well to draw water, and drew for all his camels.
* `Gen 24:28` And the young woman *_ran_* and told these things to her mother's house.
* `Gen 24:29` And Rebekah had a brother, and his name was Laban. And Laban *_ran_* out to the man at the well.
* `Gen 29:12` And Jacob told Rachel that he was her father's brother and that he was Rebekah's son. And she *_ran_* and told her father.
* `Gen 29:13` And it came to pass when Laban heard the tidings of Jacob his sister's son, that he *_ran_* to meet him, embraced him, kissed him, and brought him to his house. And he told Laban all these things.
* `Gen 33:4` And Esau *_ran_* to meet him, embraced him, fell on his neck, and kissed him, and they wept.
* `Exo 9:23` And Moses stretched forth his rod toward heaven, and the LORD sent thunder and hail, and the fire *_ran_* along upon the ground, and the LORD rained hail upon the land of Egypt.
* `Num 11:27` And a young man *_ran_* there and told Moses, and said, "Eldad and Medad are prophesying in the camp."
* `Num 16:47` And Aaron took as Moses commanded and *_ran_* into the midst of the congregation, and behold, the plague had begun among the people. And he put incense on it and made an atonement for the people.
* `Jsh 7:22` So Joshua sent messengers and they *_ran_* to the tent, and behold, it was hid in his tent, with the silver under it.
* `Jsh 8:19` And the ambush arose quickly out of their place, and they *_ran_* as soon as he had stretched out his hand. And they entered into the city, took it, and hastened to set the city on fire.
* `Jdg 7:21` And they each stood in his place around the camp. And all the host *_ran_*, cried, and fled.
* `Jdg 9:21` And Jotham *_ran_* away and fled and went to Beer and dwelt there for fear of Abimelech his brother.
* `Jdg 9:44` And Abimelech and the company that was with him rushed forward and stood in the entrance of the gate of the city. And the two other companies *_ran_* upon all the people who were in the fields and slew them.
* `Jdg 13:10` And the woman made haste and *_ran_* and declared to her husband and said to him, "Behold, the man who came to me the other day has appeared to me."
* `1Sa 3:5` And he *_ran_* to Eli and said, "Here I am. You called me." And he said, "I did not call. Lie down again." And he went and lay down.
* `1Sa 4:12` And there *_ran_* a man of Benjamin out of the army and came to Shiloh the same day with his clothes rent and with earth upon his head.
* `1Sa 10:23` And they *_ran_* and brought him from there. And when he stood among the people, he was higher than any of the people from his shoulders and upward.
* `1Sa 17:22` And David left his baggage in the hand of the keeper of the baggage and *_ran_* into the army and came and saluted his brothers.
* `1Sa 17:48` And it came to pass when the Philistine arose and came and drew near to meet David, that David hastened and *_ran_* toward the army to meet the Philistine.
* `1Sa 17:51` Therefore, David *_ran_* and stood upon the Philistine, took his sword, drew it out of its sheath, slew him, and cut off his head with it. And when the Philistines saw their champion was dead, they fled.
* `1Sa 20:36` And he said to his boy, "Run, find the arrows which I shoot." And as the boy *_ran_*, he shot an arrow beyond him.
* `2Sa 18:21` Then Joab said to Cushi, "Go, tell the king what you have seen." And Cushi bowed himself to Joab and *_ran_*.
* `2Sa 18:23` "But whatever may come," he said, "let me run." And he said to him, "Run." Then Ahimaaz *_ran_* by the way of the plain and outran Cushi.
* `1Ki 2:39` And it came to pass at the end of three years, that two of the servants of Shimei *_ran_* away to Achish son of Maachah king of Gath. And they told Shimei, saying, "Behold, your servants are in Gath."
* `1Ki 18:35` And the water *_ran_* around the altar. And he also filled the trench with water.
* `1Ki 18:46` And the hand of the LORD was on Elijah. And he girded his loins and *_ran_* before Ahab to the entrance of Jezreel.
* `1Ki 19:20` And he left the oxen and *_ran_* after Elijah and said, "Let me, I pray you, kiss my father and my mother and then I will follow you." And he said to him, "Go back again. For what have I done to you?"
* `1Ki 22:35` And the battle increased that day. And the king was stayed up in his chariot against the Syrians and died at evening. And the blood *_ran_* out of the wound into the midst of the chariot.
* `2Ch 32:4` So there were many people assembled who stopped all the fountains and the brook that *_ran_* through the midst of the land, saying, "Why should the kings of Assyria come and find much water?"
* `Psa 105:41` He opened the rock, and the waters gushed out. They *_ran_* in the dry places like a river.
* `Psa 133:2` It is like the precious ointment upon the head that *_ran_* down upon the beard, even Aaron's beard, that went down to the skirts of his garment.
* `Jer 23:21` I have not sent these prophets, yet they *_ran_*. I have not spoken to them, yet they prophesied.
* `Ezk 1:14` And the living creatures *_ran_* and returned like the appearance of a flash of lightning.
* `Ezk 31:4` The waters made him great, the deep set him up on high. Her rivers *_ran_* around his planting-place and she sent out her little rivers to all the trees of the field.
* `Ezk 47:2` Then he brought me out of the way of the gate northward and led me around by the way outside to the outer gate that looks eastward, and behold, waters *_ran_* out on the right side.
* `Dan 8:6` And he came to the ram that had two horns, which I had seen standing before the river, and *_ran_* to him in the fury of his power.
* `Mth 8:32` And he said to them, "Go." And when they had come out, they went into the herd of swine. And behold, the whole herd of swine *_ran_* violently down a steep place into the sea and perished in the waters.
* `Mth 27:48` And immediately one of them *_ran_* and took a sponge, filled it with vinegar, put it on a reed, and gave it to him to drink.
* `Mth 28:8` And they departed quickly from the sepulcher with fear and great joy and *_ran_* to bring word to his disciples.
* `Mrk 5:6` But when he saw Jesus afar off, he *_ran_* and worshiped him,
* `Mrk 5:13` And immediately Jesus gave them leave. And the unclean spirits went out and entered into the swine, and the herd *_ran_* violently down a steep place into the sea (they were about two thousand) and were choked in the sea.
* `Mrk 6:33` And the people saw them departing, and many knew him. And they *_ran_* there together on foot out of all cities and went ahead of them.
* `Mrk 6:55` And *_ran_* throughout that whole region and began to carry around in beds those who were sick where they heard he was.
* `Mrk 9:15` And immediately, when they beheld him, all the people were greatly amazed and *_ran_* to him and saluted him.
* `Mrk 15:36` And someone *_ran_* and filled a sponge full of vinegar, put it on a reed, and gave it to him to drink, saying, "Wait. Let us see whether Elijah will come to take him down."
* `Luk 8:33` Then the demons went out of the man and entered into the swine. And the herd *_ran_* violently down a steep place into the lake and were choked.
* `Luk 15:20` And he arose and came to his father. But when he was yet a great way off, his father saw him, had compassion, *_ran_* and fell on his neck, and kissed him.
* `Luk 19:4` And he *_ran_* ahead and climbed up upon a sycamore-tree to see him, for he was to pass that way.
* `Luk 24:12` Then Peter arose and *_ran_* to the sepulcher, and stooping down, he beheld the linen cloths laid by themselves, and departed, wondering in himself at that which had come to pass.
* `Jhn 20:4` And they both *_ran_* together, but the other disciple outran Peter and came to the sepulcher first.
* `Act 3:11` And as the lame man who was healed held Peter and John, all the people *_ran_* together to them in the porch that is called Solomon's, greatly wondering.
* `Act 7:57` Then they cried out with a loud voice, stopped their ears, *_ran_* upon him with one accord,
* `Act 8:30` And Philip *_ran_* there to him and heard him reading the prophet Isaiah, and said, "Do you understand what you read?"
* `Act 12:14` And when she knew Peter's voice, she did not open the gate for gladness, but *_ran_* in and reported that Peter stood before the gate.
* `Act 14:14` But when the apostles Barnabas and Paul heard of it, they rent their clothes and *_ran_* in among the people, crying out,
* `Act 21:30` And all the city was moved and the people *_ran_* together. And they took Paul and drew him out of the temple. And immediately the doors were shut.
* `Act 21:32` Who immediately took soldiers and centurions and *_ran_* down to them. And when they saw the chief captain and the soldiers, they stopped beating Paul.
* `Act 27:41` And falling into a place where two seas met, they *_ran_* the ship aground. And the forepart stuck firmly and remained immovable, but the back part was broken with the violence of the waves.

_62 verses containing RAN_

== RANDOM

* `1Ki 22:34` And a certain man drew a bow at *_random_* and smote the king of Israel between the joints of the harness. Therefore, he said to the driver of his chariot, "Turn your hand and carry me out of the host, for I am wounded."
* `2Ch 18:33` And a certain man drew a bow at *_random_* and smote the king of Israel between the joints of the harness. Therefore, he said to his chariot-man, "Turn your hand so that you may carry me out of the host, for I am wounded."

_2 verses containing RANDOM_

== RANGE

* `Job 39:8` The *_range_* of the mountains is his pasture, and he searches after every green thing.

_1 verse containing RANGE_

== RANGES

* `Lev 11:35` And everything on which any part of their carcass falls shall be unclean. Whether an oven or *_ranges_* for pots, they shall be broken down, for they are unclean and shall be unclean to you.
* `2Ki 11:8` And you shall surround the king, each with his weapons in his hand. And he who comes within the *_ranges_*, let him be slain. And be with the king as he goes out and as he comes in."
* `2Ki 11:15` But Jehoiada the priest commanded the captains of the hundreds, the officers of the host, and said to them, "Bring her forth outside the *_ranges_* and kill with the sword him who follows her." For the priest had said, "Do not let her be slain in the house of the LORD."
* `2Ch 23:14` Then Jehoiada the priest brought out the captains of hundreds who were set over the host and said to them, "Bring her forth outside the *_ranges_*. And whoever follows her, let him be slain with the sword." For the priest said, "Do not slay her in the house of the LORD."

_4 verses containing RANGES_

== RANK

* `Num 2:16` All who were numbered in the camp of Reuben were one hundred and fifty-one thousand four hundred and fifty throughout their armies. And they shall move forward in the second *_rank_*.
* `Num 2:24` All who were numbered of the camp of Ephraim were one hundred and eight thousand and one hundred throughout their armies. And they shall go forward in the third *_rank_*.
* `1Ch 12:33` Of Zebulun, those who went forth to battle, expert in war with all instruments of war, were fifty thousand who could keep *_rank_*. They were not of double heart.
* `1Ch 12:38` All these men of war, who could keep *_rank_*, came with a perfect heart to Hebron to make David king over all Israel. And all the rest also of Israel were of one heart to make David king.

_4 verses containing RANK_

== RANKS

* `1Ki 7:4` And there were windows in three rows, and window was against window in three *_ranks_*.
* `1Ki 7:5` And all the doors and posts were square with beams, and window was against window in three *_ranks_*.
* `Joe 2:7` They shall run like mighty men. They shall climb the wall like men of war. They shall each march on his ways and shall not break their *_ranks_*,
* `Mrk 6:40` And they sat down in *_ranks_* by hundreds and by fifties.

_4 verses containing RANKS_

== RANSOM

* `Exo 21:30` If there is laid on him a sum of money, then he shall give for the *_ransom_* of his life whatever is laid upon him.
* `Exo 30:12` "When you take the sum of the children of Israel after their number, they shall each give a *_ransom_* for his soul to the LORD when you number them so that there may be no plague among them when you number them.
* `Job 33:24` Then he is gracious to him and says, 'Deliver him from going down to the pit. I have found a *_ransom_*.'
* `Job 36:18` Because there is wrath, beware lest he take you away with his stroke. Then a great *_ransom_* cannot deliver you.
* `Psa 49:7` None of them can by any means redeem his brother, nor give to God a *_ransom_* for him
* `Pro 6:35` He will not regard any *_ransom_*, neither will he rest content, though you give many gifts.
* `Pro 13:8` The *_ransom_* of a man's life is his riches, but the poor does not hear rebuke.
* `Pro 21:18` The wicked shall be a *_ransom_* for the righteous, and the transgressor for the upright.
* `Isa 43:3` For I am the LORD your God, the Holy One of Israel, your Savior. I gave Egypt for your *_ransom_*, Cush and Seba for you.
* `Hos 13:14` I will *_ransom_* them from the power of the grave. I will redeem them from death. O death, I will be your plagues. O grave, I will be your destruction. Repentance shall be hid from my eyes.
* `Mth 20:28` Even as the Son of man did not come to be ministered to, but to minister and to give his life a *_ransom_* for many."
* `Mrk 10:45` For even the Son of man did not come to be ministered to, but to minister and to give his life as a *_ransom_* for many."
* `1Ti 2:6` Who gave himself a *_ransom_* for all—the testimony in its own due times,

_13 verses containing RANSOM_

== RANSOMED

* `Isa 35:10` And the *_ransomed_* of the LORD shall return and come to Zion with songs and everlasting joy upon their heads. They shall obtain joy and gladness, and sorrow and sighing shall flee away.
* `Isa 51:10` Is it not you who dried the sea, the waters of the great deep, who has made the depths of the sea a way for the *_ransomed_* to pass over?
* `Jer 31:11` For the LORD has redeemed Jacob and *_ransomed_* him from the hand of him who was stronger than he is.

_3 verses containing RANSOMED_

== RAPHA

* `1Ch 4:12` And Eshton begot Beth-*_rapha_*, Paseah, and Tehinnah the father of Ir-nahash. These are the men of Rechah.
* `1Ch 8:2` Nohah the fourth, and *_Rapha_* the fifth.
* `1Ch 8:37` And Moza begot Bineah. *_Rapha_* was his son, Eleasah his son, Azel his son.

_3 verses containing RAPHA_

== RAPHU

* `Num 13:9` Of the tribe of Benjamin, Palti the son of *_Raphu_*;

_1 verse containing RAPHU_

== RAPIDLY

* `Ezr 5:8` May it be known to the king, that we went into the province of Judea to the house of the great God, which is being built with great stones and timber is laid in the walls. And this work proceeds *_rapidly_* and prospers in their hands.

_1 verse containing RAPIDLY_

== RARE

* `Dan 2:11` And it is a *_rare_* thing that the king requires, and there is no other who can reveal it before the king, except the gods, whose dwelling is not with flesh."

_1 verse containing RARE_

== RASH

* `Ecc 5:2` Do not be *_rash_* with your mouth, and do not let your heart be hasty to utter anything before God. For God is in heaven, and you upon earth; therefore, let your words be few.
* `Isa 32:4` The heart of the *_rash_* shall understand knowledge, and the tongue of the stammerers shall be ready to speak plainly.

_2 verses containing RASH_

== RASHLY

* `Act 19:36` Seeing then that these things cannot be contradicted, you ought to be quiet and to do nothing *_rashly_*.

_1 verse containing RASHLY_

== RATE

* `Exo 16:4` Then the LORD said to Moses, "Behold, I will rain bread from heaven for you. And the people shall go out and gather a certain *_rate_* every day so that I may prove them, whether they will walk in my law or not.
* `1Ki 10:25` And every man brought his present: vessels of silver, vessels of gold, garments, armor, spices, horses, and mules—a *_rate_* year by year.
* `2Ki 25:30` And his allowance was a continual allowance given to him by the king, a daily *_rate_* for every day, all the days of his life.
* `2Ch 8:13` Even after a certain *_rate_* every day, offering according to the commandment of Moses, on the sabbaths, on the new moons, and on the solemn feasts, three times in the year, even in the feast of unleavened bread, in the feast of weeks, and in the feast of tabernacles.
* `2Ch 9:24` And they each brought his present: vessels of silver, vessels of gold, clothing, armor, spices, horses, and mules, a *_rate_* year by year.

_5 verses containing RATE_

== RATHER

* `Jsh 22:24` And if we have not *_rather_* done it for fear of this thing, saying, 'In time to come your children may speak to our children, saying, "What have you to do with the LORD God of Israel?
* `1Sa 29:3` Then the princes of the Philistines said, "What are these Hebrews doing here?" And Achish said to the princes of the Philistines, "Is this not David, the servant of Saul the king of Israel, who has been with me these days, or *_rather_* these years? I have found no fault in him since he fell to me to this day."
* `2Sa 10:3` And the princes of the children of Ammon said to Hanun their lord, "Do you think that David honors your father in that he has sent comforters to you? Has David not *_rather_* sent his servants to you to search the city, to spy it out, and to overthrow it?"
* `2Ki 5:13` And his servants came near and spoke to him and said, "My father, if the prophet had bid you to do some great thing, would you not have done it? How much *_rather_* then, when he says to you, 'Wash, and be clean'?"
* `Job 7:15` So that my soul chooses strangling and death *_rather_* than my life.
* `Job 32:2` Then the wrath of Elihu the son of Barachel the Buzite, of the kindred of Ram, was kindled against Job because he justified himself *_rather_* than God.
* `Job 36:21` Take heed, do not regard iniquity, for this you have chosen *_rather_* than affliction.
* `Psa 52:3` You love evil more than good and lying *_rather_* than speaking righteousness. [Selah.]
* `Psa 84:10` For a day in your courts is better than a thousand [elsewhere]. I would *_rather_* be a door-keeper in the house of my God than dwell in the tents of wickedness.
* `Pro 8:10` Receive my instruction instead of silver, and knowledge *_rather_* than choice gold.
* `Pro 16:16` How much better it is to get wisdom than gold! And to get understanding is to be chosen *_rather_* than silver.
* `Pro 17:12` Let a bear robbed of her whelps meet a man, *_rather_* than a fool in his folly.
* `Pro 22:1` A good name is to be chosen *_rather_* than great riches, and loving favor *_rather_* than silver and gold.
* `Jer 8:3` And death shall be chosen *_rather_* than life by all the remnant of those who remain of this evil family, who remain in all the places where I have driven them," says the LORD of hosts.
* `Amo 5:20` Shall the day of the LORD not be darkness *_rather_* than light, even very dark and no brightness in it?
* `Mth 10:6` But *_rather_* go to the lost sheep of the house of Israel.
* `Mth 10:28` And do not fear those who kill the body, but are not able to kill the soul. But *_rather_* fear him who is able to destroy both soul and body in hell.
* `Mth 25:9` But the wise answered, saying, 'Not so, lest there not be enough for us and you. But *_rather_* go to those who sell and buy some for yourselves.'
* `Mth 27:24` When Pilate saw that he could not prevail at all, but that *_rather_* a tumult was made, he took water and washed his hands before the multitude, saying, "I am innocent of the blood of this just person. See to it yourselves."
* `Mrk 5:26` Had suffered many things from many physicians, and had spent all that she had and was not relieved, but *_rather_* grew worse,
* `Mrk 15:11` But the chief priests moved the people that he should *_rather_* release Barabbas to them.
* `Luk 10:20` Nevertheless, do not rejoice in this, that the spirits are subject to you, but *_rather_* rejoice because your names are written in heaven."
* `Luk 11:28` But he said, "Yes, but *_rather_* blessed are those who hear the word of God and keep it."
* `Luk 11:41` But *_rather_* give those things which you have on the inside as alms, and behold, all things are clean to you.
* `Luk 12:31` But *_rather_* seek the kingdom of God, and all these things shall be added to you.
* `Luk 12:51` Do you suppose that I have come to give peace on earth? I tell you, no, but *_rather_* division.
* `Luk 17:8` Would he not *_rather_* say to him, 'Make ready with which I may have supper, gird yourself, and serve me until I have eaten and drank, and afterward, you shall eat and drink'?
* `Luk 18:14` I tell you, this man went down to his house justified *_rather_* than the other. For everyone who exalts himself shall be abased, and he who humbles himself shall be exalted."
* `Jhn 3:19` And this is the condemnation: that light has come into the world, and men have loved darkness *_rather_* than light because their deeds were evil.
* `Act 4:19` But Peter and John answered and said to them, "Whether it is right in the sight of God to listen to you *_rather_* than to God, judge for yourselves.
* `Act 5:29` Then Peter and the other apostles answered and said, "We ought to obey God *_rather_* than men.
* `Rom 3:8` Why not *_rather_* say (as we are slanderously reported, and as some affirm that we say), "Let us do evil so that good may come"? Their condemnation is just.
* `Rom 8:34` Who is he who condemns? It is Christ who died, or *_rather_* who is risen again, who is even at the right hand of God, who also makes intercession for us.
* `Rom 9:20` But *_rather_*, O man, who are you who replies against God? Shall the thing formed say to him who formed it, "Why have you made me this way?"
* `Rom 11:11` I say then, have they stumbled so that they should fall? By no means. But *_rather_* through their fall salvation has come to the Gentiles, to provoke them to jealousy.
* `Rom 12:19` Dearly beloved, do not avenge yourselves, but *_rather_* give place to wrath, for it is written, "Vengeance is mine and I will repay," says the Lord.
* `Rom 14:13` Let us therefore not judge one another anymore. But *_rather_* judge this: that no man put a stumbling-block or an occasion to fall in his brother's way.
* `1Co 5:2` And you are puffed up and have not *_rather_* mourned so that he who has done this deed might be taken away from among you.
* `1Co 6:7` Now therefore, there is utterly a fault among you because you go to law with one another. Why do you not *_rather_* take wrong? Why do you not *_rather_* allow yourselves to be defrauded?
* `1Co 7:21` Are you called being a servant? Do not care for it, but if you may be made free, use it *_rather_*.
* `1Co 9:12` If others are partakers of this power over you, are we not *_rather_*? Nevertheless, we have not used this power, but bear all things, lest we should hinder the gospel of Christ.
* `1Co 12:22` Contrarily, much *_rather_* those members of the body which seem to be more feeble are necessary,
* `1Co 14:19` Yet in the church I would *_rather_* speak five words with my understanding, so that by my voice I may teach others also, than ten thousand words in an unknown language.
* `2Co 2:7` So that on the other hand you ought *_rather_* to forgive him and comfort him, lest perhaps such a one should be swallowed up with excessive sorrow.
* `2Co 5:8` We are confident, I say, and willing *_rather_* to be absent from the body and to be present with the Lord.
* `Gal 4:9` But now, after you have known God, or *_rather_* are known by God, how do you turn back to the weak and beggarly elements to which you desire again to be in bondage?
* `Eph 4:28` Let him who stole no longer steal, but *_rather_* let him labor, working with his hands the thing which is good, so that he may have [something] to give to him who needs.
* `Eph 5:4` Neither filthiness, foolish talking, nor jesting, which are not appropriate, but *_rather_* giving of thanks.
* `Eph 5:11` And have no fellowship with the unfruitful works of darkness, but *_rather_* reprove them.
* `Phl 1:12` But I wish you to understand, brothers, that the things which happened to me have turned out *_rather_* for the furtherance of the gospel,
* `1Ti 1:4` Neither give heed to fables and endless genealogies, which minister questions *_rather_* than godly edifying which is in faith.
* `1Ti 4:7` But refuse profane and old wives' fables and exercise yourself *_rather_* to godliness.
* `1Ti 6:2` And those who have believing masters, let them not despise them because they are brothers, but *_rather_* do them service because they are faithful and beloved, partakers of the benefit. Teach and exhort these things.
* `Phm 1:9` Yet for love's sake I *_rather_* implore you, being such a one as Paul the aged and now also a prisoner of Jesus Christ.
* `Heb 11:25` Choosing *_rather_* to suffer affliction with the people of God than to enjoy the pleasures of sin for a season,
* `Heb 12:9` Furthermore, we have had fathers of our flesh who corrected us, and we gave them reverence. Shall we not much *_rather_* be in subjection to the Father of spirits and live?
* `Heb 12:13` And make straight paths for your feet so that what is lame may not be turned out of the way, but *_rather_* be healed.
* `Heb 13:19` But I implore you the *_rather_* to do this so that I may be restored to you more quickly.

_58 verses containing RATHER_

== RATTLES

* `Job 39:23` The quiver *_rattles_* against him, the glittering spear and the shield.

_1 verse containing RATTLES_

== RATTLING

* `Nah 3:2` The noise of a whip and the noise of the *_rattling_* of the wheels, of the prancing horses, and of the bounding chariots!

_1 verse containing RATTLING_

== RAVAGE

* `Isa 17:14` And behold at the time of evening trouble. And before the morning he is no more. This is the portion of those who *_ravage_* us and the lot of those who rob us.

_1 verse containing RAVAGE_

== RAVAGING-LOCUST

* `1Ki 8:37` "If there is famine in the land, if there is pestilence, blight, mildew, swarming-locust, or if there is *_ravaging-locust_*, if their enemy besieges them in the land of their cities, whatever plague, whatever sickness there is,
* `Psa 78:46` He also gave their increase to the *_ravaging-locust_* and their labor to the swarming-locust.
* `Isa 33:4` And your plunder shall be gathered like the gathering of the *_ravaging-locust_*. As the running to and fro of locusts he shall run upon them.
* `Joe 1:4` That which the cutting-locust has left the swarming-locust has eaten, that which the swarming-locust has left the licking-locust has eaten, and that which the licking-locust has left the *_ravaging-locust_* has eaten.
* `Joe 2:25` "And I will restore to you the years that the swarming-locust, the licking-locust, the *_ravaging-locust_*, and the cutting-locust consumed—my great army which I sent among you.

_5 verses containing RAVAGING-LOCUST_

== RAVAGING-LOCUSTS

* `2Ch 6:28` "If there is famine in the land, if there is pestilence, if there is blight, mildew, swarming-locusts, or *_ravaging-locusts_*, if their enemies besiege them in the cities of their land, whatever calamity or whatever sickness there is,

_1 verse containing RAVAGING-LOCUSTS_

== RAVEN

* `Gen 8:7` And he sent forth a *_raven_*, which went forth to and fro until the waters were dried from off the earth.
* `Lev 11:15` Every *_raven_* after its kind,
* `Deu 14:14` Every *_raven_* after its kind,
* `Job 38:41` Who provides for the *_raven_* his food? When his young ones cry to God, they wander for lack of food."
* `Sos 5:11` His head is as the most fine gold. His locks are bushy and black as a *_raven_*.
* `Isa 34:11` But the cormorant and the bittern shall possess it. The owl and the *_raven_* shall dwell in it. And he shall stretch out upon it the line of confusion and the stones of emptiness.

_6 verses containing RAVEN_

== RAVENING

* `Psa 22:13` They gaped upon me with their mouths like a *_ravening_* and a roaring lion.
* `Ezk 22:25` There is a conspiracy of her prophets in the midst of her, like a roaring lion *_ravening_* the prey. They have devoured souls. They have taken the treasure and precious things. They have made her many widows in the midst of her.
* `Ezk 22:27` Her princes in the midst of her are like wolves *_ravening_* the prey, shedding blood, and destroying souls to get dishonest gain.
* `Mth 7:15` "Beware of false prophets who come to you in sheep's clothing, but inwardly they are *_ravening_* wolves.
* `Luk 11:39` And the Lord said to him, "Now you Pharisees make the outside of the cup and the platter clean, but your inward part is full of *_ravening_* and wickedness.

_5 verses containing RAVENING_

== RAVENOUS

* `Gen 49:27` "Benjamin is a *_ravenous_* wolf. In the morning he shall devour the prey, and at night he shall divide the plunder."
* `Isa 35:9` No lion shall be there, neither shall any *_ravenous_* beast go up thereon. It shall not be found there, but the redeemed shall walk there.
* `Isa 46:11` Calling a *_ravenous_* bird from the east, the man who executes my counsel from a far country. I have spoken it and I will also bring it to pass. I have purposed it and I will also perform it.
* `Ezk 39:4` You shall fall upon the mountains of Israel—you and all your bands, and the people who are with you. I will give you to the *_ravenous_* birds of every sort and to the beasts of the field to be devoured.

_4 verses containing RAVENOUS_

== RAVENS

* `1Ki 17:4` And it shall be, that you shall drink from the brook. And I have commanded the *_ravens_* to feed you there."
* `1Ki 17:6` And the *_ravens_* brought him bread and flesh in the morning and bread and flesh in the evening, and he drank from the brook.
* `Psa 147:9` He gives to the beast his food, and to the young *_ravens_* which cry.
* `Pro 30:17` The eye that mocks at its father and despises to obey its mother, the *_ravens_* of the valley shall pick it out, and the young eagles shall eat it.
* `Luk 12:24` Consider the *_ravens_*: they neither sow nor reap, which neither have store-house, nor barn, and God feeds them. How much more are you better than the birds?

_5 verses containing RAVENS_

== RAVISHED

* `Pro 5:19` Let her be as the loving doe and pleasant deer. Let her breasts satisfy you at all times, and be *_ravished_* always with her love.
* `Pro 5:20` And why will you, my son, be *_ravished_* with a strange woman and embrace the bosom of a stranger?
* `Sos 4:9` You have *_ravished_* my heart, my sister, my spouse. You have *_ravished_* my heart with one of your eyes, with one chain of your neck.
* `Isa 13:16` Their children shall also be dashed to pieces before their eyes. Their houses shall be plundered and their wives *_ravished_*.
* `Lam 5:11` They *_ravished_* the women in Zion and the virgins in the cities of Judah.
* `Zch 14:2` For I will gather all nations against Jerusalem to battle, and the city shall be taken, the houses plundered, and the women *_ravished_*. Half of the city shall go forth into captivity, but the rest of the people shall not be cut off from the city.

_6 verses containing RAVISHED_

== RAW

* `Exo 12:9` Do not eat any of it *_raw_* or boiled at all with water, but roasted with fire, its head with its legs and with its entrails.
* `Lev 13:10` And the priest shall see him, and behold, if the rising is white in the skin and it has turned the hair white and there is *_raw_* flesh in the rising,
* `Lev 13:14` But when *_raw_* flesh appears in him, he shall be unclean.
* `Lev 13:15` And the priest shall see the *_raw_* flesh and pronounce him to be unclean, for the *_raw_* flesh is unclean. It is a leprosy.
* `Lev 13:16` Or if the *_raw_* flesh turns again and is changed into white, he shall come to the priest,
* `1Sa 2:15` Also, before they burnt the fat, the priest's servant came and said to the man who sacrificed, "Give flesh to roast for the priest, for he will not have boiled flesh from you, only *_raw_*."

_6 verses containing RAW_

== RAYS

* `Hab 3:4` And his brightness was as the light. He had *_rays_* coming out of his hand, and there was the hiding of his power.

_1 verse containing RAYS_

== RAZE

* `Psa 137:7` Remember, O LORD, the children of Edom in the day of Jerusalem, who said, "*_Raze_* it, *_raze_* it, even to its foundation."

_1 verse containing RAZE_

== RAZOR

* `Num 6:5` 'All the days of the vow of his separation no *_razor_* shall come upon his head. Until the days are fulfilled in which he separates himself to the LORD, he shall be holy and shall let the locks of the hair of his head grow.
* `Jdg 13:5` For behold, you shall conceive and bear a son. And no *_razor_* shall come on his head, for the child shall be a Nazarite to God from his birth. And he shall begin to deliver Israel from the hand of the Philistines."
* `Jdg 16:17` That he told her all his heart and said to her, "No *_razor_* has ever come upon my head, for I have been a Nazarite to God from my birth. If I am shaved, then my strength will go from me, and I shall become weak and be like any other man."
* `1Sa 1:11` And she vowed a vow and said, "O LORD of hosts, if you will indeed look on the affliction of your servant and remember me and not forget your servant, but will give to your servant a male child, then I will give him to the LORD all the days of his life, and no *_razor_* shall ever come upon his head."
* `Psa 52:2` Your tongue devises mischiefs, like a sharp *_razor_*, working deceitfully.
* `Isa 7:20` In the same day the Lord will shave with a *_razor_* that is hired from beyond the river (namely, by the king of Assyria) the head and the hair of the feet. And it shall also consume the beard.
* `Ezk 5:1` "And you, son of man, take a sharp knife, take a barber's *_razor_*, and cause it to pass upon your head and upon your beard. Then take balances to weigh and divide the hair.

_7 verses containing RAZOR_

